### ISSUE TITLE
Import spydata not possible

### ISSUE THREAD

**Issue by hehe0703** [spyder-ide/spyder#21265] opened 2023-08-17 13:25 UTC
### What steps will reproduce the problem?

Click import button in Spyder IDE Variable Explorer and select spydata-file to load.

### Traceback
```python-traceback
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder/plugins/variableexplorer/widgets/main_widget.py", line 170, in <lambda>
    triggered=lambda x: self.import_data(),
                        ^^^^^^^^^^^^^^^^^^
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder/plugins/variableexplorer/widgets/main_widget.py", line 489, in import_data
    nsb.import_data(filenames=filenames)
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 239, in import_data
    error_message = self.shellwidget.load_data(self.filename,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 158, in load_data
    timeout=CALL_KERNEL_TIMEOUT).load_data(
                                 ^^^^^^^^^^
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 224, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 440, in _get_call_return_value
    return self._sync_error(reply['value'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 496, in _sync_error
    error_wrapper.raise_error()
  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call load_data:

  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 343, in _handle_remote_call
    return_value = self._remote_callback(
                   ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/frontendcomm.py", line 273, in _remote_callback
    return super(FrontendComm, self)._remote_callback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/console/kernel.py", line 260, in load_data
    data, error_message = load_func(filename)
                          ^^^^^^^^^^^^^^^^^^^

  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/spyder_kernels/utils/iofuncs.py", line 411, in load_dictionary
    data = pickle.loads(fdesc.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/henriette/.local/share/py-default/lib/python3.11/site-packages/matplotlib/cbook/__init__.py", line 224, in __setstate__
    self._cid_gen = itertools.count(cid_count)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: a number is required

```

## Versions

* Spyder version: 5.4.4  (pip)
* Python version: 3.11.3 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Linux-6.1.44-1-MANJARO-x86_64-with-glibc2.38

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.7.4 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.3.1 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  65.5.0 (OK)
sphinx >=0.6.6                                                              :  7.2.0 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
xdg >=0.26                                                                  :  0.28 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  None (NOK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.25.2 (OK)
pandas >=1.1.1                                                              :  None (NOK)
scipy >=0.17.0                                                              :  None (NOK)
sympy >=0.7.3                                                               :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
alabaster                     0.7.13
arrow                         1.2.3
astroid                       2.15.6
asttokens                     2.2.1
atomicwrites                  1.4.1
attrs                         23.1.0
autopep8                      2.0.2
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         23.7.0
bleach                        6.0.0
certifi                       2023.7.22
cffi                          1.15.1
chardet                       5.2.0
charset-normalizer            3.2.0
click                         8.1.6
cloudpickle                   2.2.1
comm                          0.1.4
contourpy                     1.1.0
cookiecutter                  2.3.0
cryptography                  41.0.3
cycler                        0.11.0
debugpy                       1.6.7.post1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20230430
dill                          0.3.7
docstring-to-markdown         0.12
docutils                      0.20.1
executing                     1.2.0
fastjsonschema                2.18.0
flake8                        6.0.0
fonttools                     4.42.0
h5py                          3.9.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.8.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.25.1
ipython                       8.14.0
ipython-genutils              0.2.0
isort                         5.12.0
jaraco.classes                3.3.0
jedi                          0.18.2
jeepney                       0.8.0
jellyfish                     1.0.0
Jinja2                        3.1.2
jsonschema                    4.19.0
jsonschema-specifications     2023.7.1
jupyter_client                8.3.0
jupyter_core                  5.3.1
jupyterlab-pygments           0.2.2
keyring                       24.2.0
kiwisolver                    1.4.4
lazy-object-proxy             1.9.0
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.7.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       3.0.1
more-itertools                10.1.0
mypy-extensions               1.0.0
nbclient                      0.8.0
nbconvert                     7.7.4
nbformat                      5.9.2
nest-asyncio                  1.5.7
numpy                         1.25.2
numpydoc                      1.5.0
packaging                     23.1
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.11.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.0.0
pip                           23.2.1
platformdirs                  3.10.0
pluggy                        1.2.0
prompt-toolkit                3.0.39
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.10.0
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.0.1
Pygments                      2.16.1
pylint                        2.17.5
pylint-venv                   3.0.2
pyls-spyder                   0.4.0
pyparsing                     3.0.9
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.12.2
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
python-dateutil               2.8.2
python-lsp-black              1.3.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.4
python-slugify                8.0.1
pytoolconfig                  1.2.5
pyxdg                         0.28
PyYAML                        6.0.1
pyzmq                         25.1.1
QDarkStyle                    3.1
qstylizer                     0.2.2
QtAwesome                     1.2.3
qtconsole                     5.4.3
QtPy                          2.3.1
referencing                   0.30.2
requests                      2.31.0
rich                          13.5.2
rope                          1.9.0
rpds-py                       0.9.2
Rtree                         1.0.1
SecretStorage                 3.3.3
setuptools                    65.5.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4.1
Sphinx                        7.2.0
sphinxcontrib-applehelp       1.0.7
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.6
sphinxcontrib-serializinghtml 1.1.8
spyder                        5.4.4
spyder-kernels                2.4.4
stack-data                    0.6.2
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.12.1
tornado                       6.3.3
traitlets                     5.9.0
ujson                         5.8.0
urllib3                       2.0.4
watchdog                      3.0.0
wcwidth                       0.2.6
webencodings                  0.5.1
whatthepatch                  1.0.5
wrapt                         1.15.0
wurlitzer                     3.0.3
yapf                          0.40.1
zipp                          3.16.2

```
</details>

**Comment by dalthviz** [comment] 2023-08-18 21:23
Hi @hehe0703 thank you for the feedback! Seems like your `.spydata` file contains `matplotlib` related variables which Spyder is unable to load. Does your current env have a different version of `matplotlib` from the one where the `.spydata` file was created? Maybe that could be causing the problem.

Seems like this could be related with https://github.com/spyder-ide/spyder/issues/13120

**Comment by dalthviz** [comment] 2024-07-06 00:11
Closing as a duplicate of #13120

**Closed by dalthviz** 2024-07-06 00:11 UTC
Labels: resolution:Duplicate, component:Variable Explorer, status:Awaiting Followup
