### ISSUE TITLE
I cannot input in Spyder or Jupter Notebook （Anaconda2.7） on Ubuntu Server 

### ISSUE THREAD

**Issue by KimSoybean** [spyder-ide/spyder#5399] opened 2017-10-05 11:39 UTC
## Description of your problem

Today I installed Anaconda2 on our lab sever-a Ubuntu Server
But I cannot input in Spyder or Jupter Notebook （Anaconda2.7） on Ubuntu Server 
I use Remote-Desktop-Connection to the server 
When I type on my keyboard ，Nothing in Spyder Ipython console！
But I can input in another things ，such as the terminal in Ubuntu，the Firefox search engine。 
I hope you can help me。I don't want to change my coding IDE to Pycharm。 

**Please provide any additional information below**
You can send me a email  ：376046034@qq.com
Thank you!

## Versions and main components

* Spyder Version:3.1.4
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system:UNBUNTU server

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-10-05 12:21
This seems like a duplicate of issue #3713. Please see that issue for a solution to this problem.

**Closed by ccordoba12** 2017-10-05 12:21 UTC

**Comment by KimSoybean** [comment] 2017-10-05 13:44
I‘m using ssh to connect the server.(not VNC) Can you help me?
