### ISSUE TITLE
OK

### ISSUE THREAD

**Issue by kexinyi71** [spyder-ide/spyder#7240] opened 2018-06-01 13:33 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 213, in paintEvent
Traceback (most recent call last):
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
Traceback (most recent call last):
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
    self.code_editor.linenumberarea_paint_event(event)Traceback (most recent call last):
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'

  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
    self.code_editor.scrollflagarea_paint_event(event)
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1438, in scrollflagarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
Traceback (most recent call last):
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 213, in paintEvent
    self.code_editor.scrollflagarea_paint_event(event)
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1438, in scrollflagarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
    self.code_editor.linenumberarea_paint_event(event)
  File "H:\ana3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-06-01 13:51
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-06-14 19:22
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-06-14 19:22 UTC
Labels: status:Awaiting Followup
