### ISSUE TITLE
Internal problem popup

### ISSUE THREAD

**Issue by chipmuenk** [spyder-ide/spyder#11095] opened 2019-12-15 10:07 UTC
### What steps will reproduce the problem?

It just happens like that during editing - this is not very reassuring ...

### Traceback
```python-traceback
  File "D:\Programme\Anaconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 256, in paintEvent

    self._draw_fold_region_background(block, painter)
  File "D:\Programme\Anaconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 300, in _draw_fold_region_background
    end = self.folding_regions[start]
KeyError: 88
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
cloudpickle >=0.5.0          :  0.8.0 (OK)
pygments >=2.0               :  2.3.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.4.1 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.1 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.3 (OK)
cython >=0.21                :  0.29.6 (OK)
IPython >=4.0                :  7.4.0 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.16.2 (OK)
scipy >=0.17.0               :  1.3.3 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-15 15:49
Duplicate of #10918

**Comment by ccordoba12** [comment] 2019-12-15 15:49
This will be fixed in our next version.

**Closed by ccordoba12** 2019-12-15 15:49 UTC
