### ISSUE TITLE
For loops taking too much when collapsed

### ISSUE THREAD

**Issue by soqueroprogramar** [spyder-ide/spyder#10398] opened 2019-10-14 14:59 UTC
### What steps will reproduce the problem?

I've comments a few lines after a the last line of a for loop. If I collapse that for loop it will englobe those comments. Is this the intended behaviour?

It wasn't what I was expecting, thus the report.

Example:

for i in l:
    print(i)

\#pls don't include this... (but it does)

## Versions

* Spyder version: 4.0.0b5 
* Python version: 3.6.8
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-65-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.0.3 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by bcolsen** [comment] 2019-10-15 16:46
@soqueroprogramar  Thank you for the bug report!

I am closing this as a duplicate of #9956. Feel free to join the discussion on that thread if you have anything helpful to add.

**Closed by bcolsen** 2019-10-15 16:46 UTC
