### ISSUE TITLE
Custom color themes can't be edited after creation

### ISSUE THREAD

**Issue by nbara** [spyder-ide/spyder#3832] opened 2016-12-13 14:53 UTC
## Description of your problem

**What steps will reproduce the problem?**

1.  Open Preferences
2.  Create a custom color syntax theme – save it – close the dialog window
3.  Click 'Edit selected', change one on the colors, click OK

**What is the expected output? What do you see instead?**

Clicking OK does NOT save the edited color. Furthermore, clicking OK closes both the color scheme creation window AND the preference pane.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
* Operating system: OSX 10.11

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by nbara** [comment] 2016-12-13 15:11
Correction: it seems it's actually a very minor bug. 

When clicking 'OK' in the color scheme window. the preference pane doesn't disappear, but goes in the background. Therefore I wasn't 'applying' the newly-edited theme.

**Comment by ccordoba12** [comment] 2016-12-13 16:38
@andfoy, please take a look at this one

**Comment by andfoy** [comment] 2016-12-13 17:25
I tried to reproduce the error, but the window actually works.

##Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5 (OK)
sympy >=0.7.3    :  0.7.6.1 (OK)

**Comment by GandalfSaxe** [comment] 2017-06-04 18:03
I don't know if this is the same problem, but I cannot make ANY changes to themes or to a newly create theme. Any attempt to change the any of pre-defined, or even the default settings when creating a new one, no changes are saved.

In effect, I can only use pre-defined themes.

**Comment by goanpeca** [comment] 2019-12-04 03:33
I cannot reproduce this. Closing

**Closed by goanpeca** 2019-12-04 03:33 UTC
Labels: tag:Ux-usability, type:Bug

**Comment by alexandertrinh** [comment] 2020-02-14 20:05
Thank god for this post! I had the exact same error. Im on a laptop, no screen real-estate left so after clicking 'ok' the preferences window went to the background of spyder, instead of staying on the front of the editor.
