### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by nattog** [spyder-ide/spyder#7266] opened 2018-06-07 15:29 UTC
Sorry I don't know how to contribute an error report. Hope this helps. This happens every time I try to open Spyder on Anaconda . I tried to upgrade my Spyder but now I can't use it! 

```
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
      File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
      File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
      File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: 
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
```

**Comment by ccordoba12** [comment] 2018-06-07 15:52
Thanks for reporting.  This is a duplicate of issue #6335 and you can fix it by opening Terminal.app and running there

    conda update python python.app

**Closed by ccordoba12** 2018-06-07 15:52 UTC
