### ISSUE TITLE
Editor adds final colon when I enter if a: b = c

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1417] opened 2015-02-17 19:17 UTC
_From [bgai...@gmail.com](https://code.google.com/u/115200413098054342316/) on 2013-05-31T12:04:43Z_

What steps will reproduce the problem?

 1. in editor enter if a: b = c

What is the expected output? 
if a: b = c

What do you see instead?
if a: b = c:

What version of the product are you using? 
2.3.0 Dev 1

On what operating system?
Win XP

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1417_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:17
_From [jerzy.ka...@gmail.com](https://code.google.com/u/115939771826139086635/) on 2013-11-16T03:25:35Z_

Version 2.3.0dev 6 on XP : the bug continues.
Actually, this is not restricted to "if". Others blocks, say
while True: ...

upon the continuation in the same line, say:
while True: go()
   ...
adds a superfluous colon, which demands some extra editing.
Also, the definition:

def fun(): print('goodbye')
does the same.

On the other hand, such (or similar) construction :

try: import Tkinter
...

doesn't add any colons.

Thank you.
J. Karczmarczuk, Caen, France.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:17
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:58:51Z_

**Labels:** Cat-Editor MS-v2.4

**Comment by Nodd** [comment] 2015-04-08 12:20
Duplicate of https://github.com/spyder-ide/spyder/issues/872

**Closed by Nodd** 2015-04-08 12:20 UTC
Labels: 1 star, bug, Editor
