### ISSUE TITLE
Support for displaying tensorflow object in the varibale explorer

### ISSUE THREAD

**Issue by imanpalsingh** [spyder-ide/spyder#12808] opened 2020-05-20 13:42 UTC
## Problem Description
I'm unable to view a tensorflow object  through the variable explorer, just like I can do for pandas object. If this is not already a feature I would like to request for a feature to display contents of tensorflow object through the variable explorer such as values, target and other meta data too.

### What steps reproduce the problem?
I tried loading data using  [`tf.data.Dataset`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) which reads the values from a pandas dataframe.
1. Load any csv through pandas : ` df = pd.read_csv(filepath)`
2. `target = df.pop('target')`
3. `dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))`

To obtain the output I have to do something like
```python
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))
```
It would be great to see the values inside the variable explorer

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by goanpeca** [comment] 2020-05-20 13:56
Hi @imanpalsingh thanks for the suggestion.

This seems to be a duplicate of #7042, so please follow that issue for future updates.

Thanks!

**Closed by goanpeca** 2020-05-20 13:56 UTC
