### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by directionly** [spyder-ide/spyder#6228] opened 2018-01-17 08:14 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\PROGRAM\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "D:\PROGRAM\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "D:\PROGRAM\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "D:\PROGRAM\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "D:\PROGRAM\anaconda3\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "D:\PROGRAM\anaconda3\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "D:\PROGRAM\anaconda3\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\JASON LY\\.spyder-py3\\profiler.results'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.

**Comment by CAM-Gerlach** [comment] 2018-01-17 10:07
Thanks for reporting. This error is an apparent duplicate of #5587 , and should be fixed in Spyder 3.2.5. You can update Spyder to solve it, and so this issue will be closed. If it still occurs, then please reopoen it with more details about the problem.

**Closed by CAM-Gerlach** 2018-01-17 10:07 UTC
