### ISSUE TITLE
First Run of 3.3

### ISSUE THREAD

**Issue by ayyuriss** [spyder-ide/spyder#7542] opened 2018-07-24 01:39 UTC
### What steps will reproduce the problem?

Just uninstalled Spyder 3.2 and installed 3.3

pip3 install --upgrade spyder --user

### Traceback
```python-traceback
  File "/home/thinkpad/.local/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.5.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-29-generic

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.21.0 (OK)
numpy >=1.7       :  1.14.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.3.1 (OK)
matplotlib >=2.0.0:  2.1.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-24 02:20
Thanks for reporting. This is a duplicate of issue #7403 and it'll be fixed in our next version.

**Closed by ccordoba12** 2018-07-24 02:20 UTC

**Comment by ayyuriss** [comment] 2018-07-24 02:48
Problem solved,
Edited the `valid_project` method starting from line 1959 in spyder/app/mainwindow.py .  
`if self.projects is not None:`  was removed from version 3.2.8 I had to put it back.

Thanks !
