### ISSUE TITLE
Spyder 5.0 issues

### ISSUE THREAD

**Issue by leyojoseph** [spyder-ide/spyder#15415] opened 2021-04-25 12:58 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Below two features we liked most is no more working on latest Spyder. I am using spyder 5.0
1. Go to definition (ctrl G) is not working. Tried all of the suggestions in the discussion forum.
2.  In the outline pane, not displaying the functions, class etc. of a module. Expand/collapse is not working

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2021-04-25 17:07
Hey @leyojoseph, thanks for reporting. This is a duplicate of issue #15139 and we'll try to fix in our next release.

For now, please uninstall Kite if you have it installed. That should solve your problem.

**Closed by ccordoba12** 2021-04-25 17:07 UTC

**Comment by Ikhwansong** [comment] 2021-05-01 18:00
The problem of "go to definition is not working" can be handled by modifying the configuration (Tools -> Preference -> General -> Providers. Uncheck the "Enable kite provider" .

In my case, it worked.

**Comment by ccordoba12** [comment] 2021-05-01 18:34
That's true too. We'll fix it in our next version (5.0.2), to be released soon.

**Comment by Ikhwansong** [comment] 2021-05-01 20:39
I performed the rollback that 5.0 to 4.1.3 and downgrade the spyder-kernel 1.9.4 to 1.9.3.

It worked! the 'go to definition' revived.
