### ISSUE TITLE
No way to disable introspection in the Editor

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#8301] opened 2018-11-23 20:48 UTC
## Problem Description
On MacOS and spyder 4.0.0 beta1, Code Introspection cannot be disabled. This is the issue for either style or error markers.

### What steps reproduce the problem?

1. Install anaconda or other python distribtution with last stable spyder 3.x
2. Start spyder, type some lines which lead to introspection markers. Style or errors.
3. Depending on your setting, you will see the markers or not. Change the Settings under Editor->Introspection. The markers will appear / disappear.
4. Update to spyder 4.0.0 beta1
5. Repeat 2 and 3.

### What is the expected output? What do you see instead?
Expected is the same as in 2 and 3. However Code Introspection is always on. When unchecking, nothing happens but the check is disappearing. On Apply, nothing changes. On OK, nothing changes, Prefs closing. When re-opening Prefs, checkmarks are back on. Restart spyder to no avail.

## Versions

* Spyder version: 4.0.0 beta 1
* Python version: 3.6.6, 3.7.0, 3.7.1
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS 10.14, darwin

**Comment by ccordoba12** [comment] 2018-11-23 22:34
Thanks for reporting. We'll address this in our next beta.

**Comment by ccordoba12** [comment] 2018-12-21 06:31
This is a duplicate of #8121.

**Closed by ccordoba12** 2018-12-21 06:31 UTC
Labels: component:Editor, type:Bug
