### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by eg3gatech** [spyder-ide/spyder#16225] opened 2021-08-17 02:11 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
### What steps will reproduce the problem?

I get this error box every time I open spyder now- I'm not sure why.  Once I hit close everything is fine.

**Comment by ccordoba12** [comment] 2021-08-17 13:11
Hey @eg3gatech, thanks for reporting. This problem could be fixed in our latest Spyder 3 version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

Let us know if it works for you.

**Comment by eg3gatech** [comment] 2021-08-17 14:55
The update took care of the error message at startup- thanks so much
erin

**Comment by ccordoba12** [comment] 2021-08-17 16:41
Great! I'm really glad the problem is solved for you.

**Closed by ccordoba12** 2021-08-17 16:41 UTC
Labels: status:Awaiting Followup
