### ISSUE TITLE
Crash after closing IPython window

### ISSUE THREAD

**Issue by copertool** [spyder-ide/spyder#20480] opened 2023-02-05 20:10 UTC
### What steps will reproduce the problem?

1. Created a conda environment with spyder and pandas
2. Load a variable
3. Open the variable in a window with Variable Explorer
4. Close the window

### Traceback
```python-traceback
Exception in callback AddThreadSelectorEventLoop._handle_select([7916], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([7916], [])>
Traceback (most recent call last):
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\site-packages\tornado\platform\asyncio.py", line 647, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\site-packages\tornado\platform\asyncio.py", line 661, in _handle_event
    callback()
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\site-packages\tornado\platform\asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\site-packages\zmq\eventloop\zmqstream.py", line 614, in _handle_events
    zmq_events = self.socket.EVENTS
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\site-packages\zmq\sugar\attrsettr.py", line 56, in __getattr__
    return self._get_attr_opt(upper_key, opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andriu\anaconda3\envs\keys\Lib\site-packages\zmq\sugar\attrsettr.py", line 68, in _get_attr_opt
    return self.get(opt)
           ^^^^^^^^^^^^^
  File "zmq\backend\cython\socket.pyx", line 512, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 270, in zmq.backend.cython.socket._getsockopt
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: not a socket
```

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.8
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.9.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.16.1 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Andriu\anaconda3\envs\keys:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
astroid                   2.14.1                   pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
autopep8                  1.6.0                    pypi_0    pypi
babel                     2.11.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bcrypt                    4.0.1                    pypi_0    pypi
beautifulsoup4            4.11.2                   pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
black                     23.1.0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
bzip2                     1.0.8                he774522_0  
ca-certificates           2023.01.10           haa95532_0  
certifi                   2022.9.24       py311haa95532_0  
cffi                      1.15.1                   pypi_0    pypi
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        3.0.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.2                    pypi_0    pypi
cookiecutter              2.1.1                    pypi_0    pypi
cryptography              39.0.0                   pypi_0    pypi
debugpy                   1.6.6                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
diff-match-patch          20200713                 pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docstring-to-markdown     0.11                     pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
flake8                    6.0.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.21.1                   pypi_0    pypi
ipython                   8.9.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
jaraco-classes            3.2.3                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jellyfish                 0.9.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-core              5.2.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
keyring                   23.13.1                  pypi_0    pypi
lazy-object-proxy         1.9.0                    pypi_0    pypi
libffi                    3.4.2                hd77b12b_6  
markupsafe                2.1.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
more-itertools            9.0.0                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.9                    pypi_0    pypi
nbformat                  5.7.3                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0  
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
paramiko                  3.0.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.11.0                   pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       22.2.2          py311haa95532_0  
platformdirs              2.6.2                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
prompt-toolkit            3.0.36                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydocstyle                6.2.3                    pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pylint                    2.16.1                   pypi_0    pypi
pylint-venv               2.3.0                    pypi_0    pypi
pyls-spyder               0.4.0                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyqt5                     5.15.8                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
pyqtwebengine             5.15.6                   pypi_0    pypi
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.11.0               h966fe2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
python-lsp-black          1.2.1                    pypi_0    pypi
python-lsp-jsonrpc        1.0.0                    pypi_0    pypi
python-lsp-server         1.7.1                    pypi_0    pypi
python-slugify            8.0.0                    pypi_0    pypi
pytoolconfig              1.2.5                    pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
pywin32                   305                      pypi_0    pypi
pywin32-ctypes            0.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.0                   pypi_0    pypi
qdarkstyle                3.0.3                    pypi_0    pypi
qstylizer                 0.2.2                    pypi_0    pypi
qtawesome                 1.2.2                    pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.3.0                    pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rope                      1.7.0                    pypi_0    pypi
rtree                     1.0.1                    pypi_0    pypi
setuptools                65.5.0          py311haa95532_0  
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sphinx                    6.1.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
spyder                    5.4.2                    pypi_0    pypi
spyder-kernels            2.4.2                    pypi_0    pypi
sqlite                    3.40.1               h2bbff1b_0  
stack-data                0.6.2                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
textdistance              4.5.0                    pypi_0    pypi
three-merge               0.1.1                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0  
toml                      0.10.2                   pypi_0    pypi
tomlkit                   0.11.6                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
tzdata                    2022g                h04d1e81_0  
ujson                     5.7.0                    pypi_0    pypi
urllib3                   1.26.14                  pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  2.2.1                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
whatthepatch              1.0.4                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wincertstore              0.2             py311haa95532_0  
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.10               h8cc25b3_1  
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.12.1                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0  

```
</details>

**Comment by dalthviz** [comment] 2023-02-11 00:28
Hi @copertool thank you for the feedback! Could you try to downgrade PyZMQ to 24.0 and check if the error persists? Let us know!

**Comment by dalthviz** [comment] 2023-03-29 21:16
Closing as a duplicate of #20381

**Closed by dalthviz** 2023-03-29 21:16 UTC
Labels: resolution:Duplicate, component:IPython Console, status:Awaiting Followup
