### ISSUE TITLE
Spyder crashed when close the pop windows of variable

### ISSUE THREAD

**Issue by luluman** [spyder-ide/spyder#2840] opened 2015-12-02 15:14 UTC
Spyder will crash when I try to click the "ok" or "Cancel" button of the variable window which pops up.
This bug shows both on 2.3.7 and 2.3.8 with python3 on macos.  But it works fine when choose the close button which system provided.

**Comment by ccordoba12** [comment] 2015-12-03 12:44
This is a duplicate of issue #2708

**Closed by ccordoba12** 2015-12-03 12:44 UTC
Labels: Duplicate
