### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start_installation'

### ISSUE THREAD

**Issue by ilberi** [spyder-ide/spyder#22306] opened 2024-07-31 09:38 UTC
### What steps will reproduce the problem?

11111111111111111111111111111111111111111111111111111111111

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 330, in _check_updates_ready
    self.application_update_status.start_installation(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_installation'
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.25.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  69.5.1 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.10 (OK)
matplotlib >=3.0.0               :  3.8.4 (OK)
numpy >=1.7                      :  1.24.3 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by dalthviz** [comment] 2024-08-01 00:19
Hi @ilberi thank you for the report! This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/21781 A fix for this was part of Spyder release 5.5.2. To update to 5.5.2 and more recent Spyder versions (latest Spyder 5 release is version 5.5.5) you will need to use the conda-forge channel. If you are using your conda base env to launch Spyder I would suggest you create a new env using packages from the conda-forge channel. Another option to workaround the issue, in case you can not use a more recent Spyder version, is to deactivate/uncheck the `Check for updates on startup` option (available at `Preferences > Application > Advanced settings`)

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2024-11-06 23:40
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/21781

**Closed by dalthviz** 2024-11-06 23:40 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
