### ISSUE TITLE
Turning selection to multiple cursors per line

### ISSUE THREAD

**Issue by SaeidJavadi** [spyder-ide/spyder#17328] opened 2022-02-11 19:26 UTC
Having used both Replace All and multiple cursors, for me multiple cursors is much faster in most cases. And it also opens up possibilities that are not as easy with regex & replace all.

For example, like the following image, which is taken from a code editor such as Pycharm or VSCode: 

![image](https://cloud.githubusercontent.com/assets/6655099/13059552/25f57042-d42b-11e5-8836-d64f3c19c483.gif)

**Comment by ccordoba12** [comment] 2022-02-11 21:09
Hey @SaeidJavadi, thanks for reporting. This is a duplicate of issue #2112.

We'll try to implement it next year, after a big refactoring that we need to do in the editor to support things like this.

**Closed by ccordoba12** 2022-02-11 21:09 UTC

**Comment by SaeidJavadi** [comment] 2022-02-12 04:57
Thank you
And a good feature that is great if added
**reformat your code** like pycharm
[![IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=0WfDm3KQ-Cw)](https://www.youtube.com/watch?v=0WfDm3KQ-Cw)

**Comment by ccordoba12** [comment] 2022-02-12 15:44
That is already available in this menu action

![imagen](https://user-images.githubusercontent.com/365293/153717903-7e35e2c7-a737-4e08-a8fa-ac6757d766ea.png)

and can be configured in the menu

    Tools > Preferences > Completion and linting > Code style and formatting

**Comment by gbazad93** [comment] 2024-09-17 21:54
> Hey @SaeidJavadi, thanks for reporting. This is a duplicate of issue #2112.
> 
> We'll try to implement it next year, after a big refactoring that we need to do in the editor to support things like this.

Still I can't see this feature. Any update? Thank you.

**Comment by ccordoba12** [comment] 2024-09-18 18:46
It's not there yet. But this is definitely high in our TODO list because more and more people is asking about.

So, we'll try to secure some funding to implement it next year.
