### ISSUE TITLE
Layout problem on Ubuntu and Anaconda

### ISSUE THREAD

**Issue by tq0** [spyder-ide/spyder#3524] opened 2016-10-11 16:11 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Start `spyder` from a Conda environment.

**What is the expected output? What do you see instead?**

I have two Ubuntu 16.04.1 machines running Anaconda 2 and using the same Conda environment. On one of the machines the layout of `spyder` GUI is messed up - button images appear too big: 

![spyder1](https://cloud.githubusercontent.com/assets/8254620/19278342/25423f36-8fdd-11e6-8d09-6f50cfd3872b.png)

On the other machine, the GUI layout is fine:

![spyder2](https://cloud.githubusercontent.com/assets/8254620/19278368/32dec1fa-8fdd-11e6-9d46-b999451b44b5.png)

The issue is also present when using Anaconda 3 or when using a different Conda environment (e.g. the 'root' environment).

I think the issue is related to the Qt version that is used, but I am not sure how I can select the correct one. Has anyone experienced such a behaviour and knows how to fix it?

**Please provide any additional information below**

The most significant difference between the two machines is that the one where the layout is OK has a fresh install of Ubuntu 16.04 and the one where the layout is messed up has been upgraded to 16.04 from 15.10. The system packages on both machines are roughly the same and are kept up-to-date.

## Versions and main components

On both machines:
* Spyder Version: 3.0.0 (Python 2.7.12 64bits, Qt 5.6.0, PyQt5 5.6 on Linux)
* Python Version: Python 2.7.12 |Anaconda 4.2.0 (64-bit)
* Operating system: Ubuntu 16.04.1 64-bit

## Dependencies

On both machines:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by TurtleDogBird** [comment] 2016-10-11 21:41
Just did a fresh anaconda install and the Spyder layout is scaled huge:
![screenshot_2016-10-11_23-40-01](https://cloud.githubusercontent.com/assets/11612496/19289653/0b50fe3a-900c-11e6-8cf7-e1653d6f684f.png)

Running Xubuntu 16

**Comment by ccordoba12** [comment] 2016-10-12 15:34
Thanks for reporting. This is a duplicate of issue #3489, so I'm closing it :-)

**Closed by ccordoba12** 2016-10-12 15:34 UTC
