### ISSUE TITLE
Default Spyder 4 syntax colors aren't suitable for white paper

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#12057] opened 2020-03-31 01:03 UTC
# Problem Description

I suppose they'd look great on black paper. (Spyder 4 is great!)

But it would be helpful to have an alternate set of default syntax highlighting colors for printing. (Say, something dark against white paper.)

While I'm wishing, it would be nice to be able to pre-set fonts and landscape-vs-portrait mode for printing, too.

(Of course this can be worked around by changing the syntax highlighting mode, but that requires a change, restart, print, change back, restart again. A lot more work than it really ought to be.)

### What steps reproduce the problem?

1.  Open source code in Spyder 4 with defaults.
2.  File>Print Preview...

Problem is obvious at that point. White text on white background isn't visible.

* Spyder version: 4.1.1
* Python version: 3.8
* Operating System name/version: Windows 10 x64

**Comment by bcolsen** [comment] 2020-03-31 06:02
Thank you for submitting this issue.

We are aware that printing with dark syntax highlighter is very broken and this is more of an issue now that Spyder 4 comes with a dark theme by default.

The work around is to change the syntax highlighter to a light one and then print, but you shouldn't have to restart Spyder. 

Closing as a duplicate of #2521

**Closed by bcolsen** 2020-03-31 06:02 UTC
