### ISSUE TITLE
Python Console Header Message Inconsistent

### ISSUE THREAD

**Issue by colinww** [spyder-ide/spyder#11027] opened 2019-12-11 17:57 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
From a clean 2019.10 Anaconda install, run `conda update anaconda` to get Spyder 4.0.0. When Spyder runs with the default interpreter, the Python console message does not align with the version of Python used.

### What steps reproduce the problem?

1. Install Anaconda 2019.10 in ~/anaconda3
2. Update anaconda
3. Launch spyder

### What is the expected output? What do you see instead?

The spyder console prompt shows
```
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
Type "copyright", "credits" or "license" for more information.

IPython 7.10.1 -- An enhanced Interactive Python.
```

However, the bottom bar of spyder shows
```
conda: base (Python 3.7.5)
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

```
spyder                    4.0.0                    py37_0
spyder-kernels            1.8.1                    py37_0
python                    3.7.5                h359304d_0
qt                        5.9.7                h468cd18_1
pyqt                      5.9.2            py37h655552a_2
```
OS: OSX 10.15.1 Catalina

**Comment by ccordoba12** [comment] 2019-12-12 03:33
Duplicate of #10984

**Closed by ccordoba12** 2019-12-12 03:33 UTC
