### ISSUE TITLE
Cannot enable Auto-HiDPI and throw out libGL error

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#16030] opened 2021-07-16 08:25 UTC
Version: 5.0.3 & 5.0.5
OS: Manjaro Linux 20.1

This happens when I open spyder in terminal
```
libGL error: MESA-LOADER: failed to open iris: /home/firestar/.miniconda/lib/python3.9/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /home/firestar/.miniconda/lib/python3.9/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /home/firestar/.miniconda/lib/python3.9/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
```
My Spyder displays the same ugly style on my 200% 2736*1824 screen in Normal and HiDPI mode:

![Screenshot_20210716_162342](https://user-images.githubusercontent.com/65082432/125916802-3c00aee1-d705-4cbe-9a50-42646f8be4d6.png)

It should not be like this, the buttons are too large and icons mixing with words.

![Screenshot_20210716_162502](https://user-images.githubusercontent.com/65082432/125916975-4992f26d-6b61-46dc-9be5-0006f2c50093.png)

**Comment by juanis2112** [comment] 2021-07-16 22:10
HI @1900011604 thanks for reporting this. I can't reproduce this issue in Mac, @ccordoba12 can you verify if this is a Linux issue? Do you see icons like this when switching to HiDPI mode?

**Comment by 1900011604** [comment] 2021-07-17 11:31
I remember that this do not happen every time, but when I return to windows to see, it says:
```
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
```

**Comment by 1900011604** [comment] 2021-07-26 09:07
Now, it has not been fixed.

**Comment by ccordoba12** [comment] 2021-07-28 00:06
Hey @1900011604, what's your screen resolution on Linux?

**Comment by 1900011604** [comment] 2021-07-28 02:46
I have mentioned it before that it is 2736x1824 200% enlarged

**Comment by ccordoba12** [comment] 2021-07-28 03:01
> I have mentioned it before that it is 2736x1824 200% enlarged

Sorry, I didn't see it.

Next question: did you change the options we provide for high resolution screens in Preferences?

![imagen](https://user-images.githubusercontent.com/365293/127256761-6bf9362a-ceca-4add-9bd6-0c6b57c8f0a7.png)

I think they should make Spyder scale correctly in your screen.

**Comment by 1900011604** [comment] 2021-07-28 03:29
No. I just enabled auto HiDPI settings and I found that it has no difference with Normal.

**Comment by ccordoba12** [comment] 2021-07-28 03:40
And what the scaling factor?

**Comment by 1900011604** [comment] 2021-07-28 03:50
It is 200%, and I don't know what the scaling factor of spyder is. Maybe around 1.2

**Comment by ccordoba12** [comment] 2021-07-28 04:06
You can play with it to see what value works for you.

**Comment by 1900011604** [comment] 2021-07-29 01:47
It does not works mainly because it's extremely large buttons. Without that about 1~1.25 will be fine.

**Comment by ccordoba12** [comment] 2021-07-29 03:00
Ok, so the only problem is the buttons size?

**Comment by 1900011604** [comment] 2021-07-29 07:02
![图片](https://user-images.githubusercontent.com/65082432/127446741-47d041ab-f286-499b-b010-c8843b523212.png)

**Comment by 1900011604** [comment] 2021-07-29 07:10
![屏幕截图(32)](https://user-images.githubusercontent.com/65082432/127447601-bf22a457-5895-4cf4-9642-5efa53df3ee4.png)

This is the display on my Windows 11 on the same computer and screen, and this is the right display I want.

**Comment by ccordoba12** [comment] 2021-07-29 15:24
Ok, so text seems to be scaling correctly and only icons are the problem. Then I think this issue is a duplicate of #15128.

We'll try to fix it in a future release, but for now there's no workaround available, sorry.

**Closed by ccordoba12** 2021-07-29 15:24 UTC
Labels: status:Awaiting Followup

**Comment by Firestar-Reimu** [comment] 2022-10-16 09:17
still not fixed

spyder 5.3.2 on Archlinux

```
Gtk-Message: 17:09:12.556: Failed to load module "appmenu-gtk-module"
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
```

**Comment by ccordoba12** [comment] 2022-10-16 13:44
@Firestar-Reimu, that's the expected toolbar size.
