### ISSUE TITLE
Have installed the Anaconda and opened Spyder, it returned FileNotFoundError

### ISSUE THREAD

**Issue by UnaPlugin** [spyder-ide/spyder#7077] opened 2018-05-07 02:47 UTC
## Error：Spyder has encountered  a problem.

The Error appeared when I just installed the whole anaconda and opened the Spyder. I did nothing but the application returned the error....

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "D:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "D:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "D:\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "D:\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
   File "D:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by CAM-Gerlach** [comment] 2018-05-07 04:08
Thanks for reporting. For reference, this is an apparent duplicate of #4958 (and its more recent reincarnation, #6319), fixed in Spyder 3.2.7. You can update Spyder by running the command ``conda update spyder`` from the Anaconda Prompt.

**Closed by CAM-Gerlach** 2018-05-07 04:08 UTC
