### ISSUE TITLE
can't load a file 

### ISSUE THREAD

**Issue by Vicat56** [spyder-ide/spyder#15111] opened 2021-04-05 13:08 UTC
### What steps will reproduce the problem?

 installed spyder 5.0.0 after uninstalling the previous version. Now i have a kenel error that i can't fix at the startup and can't load files.... nice 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 2162, in load
    self.switch_to_plugin()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 1644, in switch_to_plugin
    super(Editor, self).switch_to_plugin()
  File "C:\Program Files\Spyder\pkgs\spyder\api\plugins.py", line 406, in switch_to_plugin
    super(BasePluginWidget, self)._switch_to_plugin()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\base.py", line 284, in _switch_to_plugin
    self.main.maximize_dockwidget()
  File "C:\Program Files\Spyder\pkgs\spyder\app\mainwindow.py", line 1164, in __getattr__
    return super().__getattr__(attr)
AttributeError: 'MainWindow' object has no attribute 'maximize_dockwidget'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by dalthviz** [comment] 2024-11-28 22:53
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/15164 a

**Closed by dalthviz** 2024-11-28 22:53 UTC
Labels: resolution:Duplicate
