### ISSUE TITLE
spyder crashes

### ISSUE THREAD

**Issue by shadcomputer** [spyder-ide/spyder#6544] opened 2018-02-27 23:19 UTC
## Description

**What steps will reproduce the problem?**

1. spyder crashes once opened
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 950, in update_working_directory
    shellwidget.get_cwd()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 340, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
WARNING:traitlets:kernel died: 18.002039909362793

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-27 23:39
@shadcomputer, we want to help you but **please** stop opening more issues about this problem. We'll try to guide you with the steps you need to follow to solve this problem, ok?

**Comment by ccordoba12** [comment] 2018-02-27 23:46
@shadcomputer, the steps are:

1. Copy the contents of the following page to a file called `uuid.py` using Spyder or another plain text editor: https://raw.githubusercontent.com/python/cpython/d69794f4df81de731cc66dc82136e28bee691e1e/Lib/uuid.py
2. Open Terminal.app
3. Introduce the following command there:

       mv uuid.py /anaconda3/lib/python3.6/uuid.py

    If that command fails for some reason, you need to run this other command:

       sudo mv uuid.py /anaconda3/lib/python3.6/uuid.py

    then introduce your account password.

That's it. Please report back if the problem was fixed for you.

**Comment by shadcomputer** [comment] 2018-02-28 00:02
In terminal it does not accept my password 
( i just recovered my password as i had forgotten it is that the reason?)

**Comment by ccordoba12** [comment] 2018-02-28 00:03
What if you use your previous password?

**Comment by shadcomputer** [comment] 2018-02-28 00:04
I don’t remember it

**Comment by ccordoba12** [comment] 2018-02-28 00:06
Then please uninstall Anaconda from your current location and install again, but in your `Users` directory. I think you need to select the option *Only for me* (or something similar) from the installer.

**Comment by shadcomputer** [comment] 2018-02-28 00:08
Alright thanks you 
I did try the “only for me” but does not accept it 
I’ll try again and we’ll let you know

**Comment by ccordoba12** [comment] 2018-02-28 00:11
> I did try the “only for me” but does not accept it

That's very strange. What's the error?

**Comment by shadcomputer** [comment] 2018-02-28 00:20
Let me uninstall it and try again will let you know 
Thanks for following up!

**Comment by shadcomputer** [comment] 2018-02-28 00:30
When i try to install it for me only 
It says 
“You cannot install anaconda3 in this location. The anaconda3 installer does not allow its software to be installed here”

**Comment by CAM-Gerlach** [comment] 2018-02-28 06:07
Where are you trying to install it?

It sounds like the proximate issue is with your password or permissions, which (in case it wasn't clear) has nothing whatsoever to do with Spyder, and as mentioned in the previous three reports, the root issue is a duplicate of #6335. You can try doing a clean reboot of your machine to make sure everything is properly updated with your new password, and of course, make sure your new password works elsewhere.

**Comment by shadcomputer** [comment] 2018-02-28 14:25
I rebooted my system and it is finally working. thanks.

**Comment by ccordoba12** [comment] 2018-02-28 15:17
@shadcomputer, yay! Really glad to know!

An advice for next time: please try to be patient and wait for our help. If you think we didn't give you the right answer or direction to solve your problem, please keep commenting on the initial issue you open, instead of opening more and more issues (you opened four issues yesterday about the same problem, three here and one in anaconda-issues).

The thing is we are a purely volunteer organization and don't have time to answer all issues right away (we're receiving about 10 issues per day).

**Closed by ccordoba12** 2018-02-28 15:17 UTC
Labels: resolution:NotSpyder

**Comment by CAM-Gerlach** [comment] 2018-02-28 15:32
Also, _please_ search for your issue before posting a new one; this was already reported and resolved a half dozen times already. If it so (usually the case) you can get a quicker answer that way and avoid clogging up the system with numerous duplicates. Further, you can reference our [troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) for general solutions that resolve most common problems.

**Comment by shadcomputer** [comment] 2018-02-28 15:38
At first i thought it is a automatic answer. I did not see my email.
Thanks.

**Comment by ccordoba12** [comment] 2018-02-28 15:42
@CAM-Gerlach, for an experienced user it's easy to understand the fix for this problem, but I think for a newbie it's almost impossible to decipher what you're supposed to do (i.e. grab the patch from Github and apply it).

@shadcomputer, no worries. We're giving this advice so you can get better answers not only from us but from any other open source project you want to use (i.e. Pandas, Matplotlib, etc).

**Comment by CAM-Gerlach** [comment] 2018-02-28 15:50
@ccordoba12  Right, I see. However, wouldn't it be better to do that over on the main issue you've been marking things duplicates of, so all the information is in one place and when we mark further threads as duplicates, others will see it too?
