### ISSUE TITLE
Window zoomed in too far

### ISSUE THREAD

**Issue by astropolitan** [spyder-ide/spyder#3549] opened 2016-10-17 13:42 UTC
I recently updated Spyder and since then the window is zoomed in way too far at start up. The only way I've found to make it look like "normal" is to adjust my display settings for my computer but I don't want to do that permanently. Is there any other way to return the window back to normal?

This is currently what I see:
<img width="960" alt="spyder zoom" src="https://cloud.githubusercontent.com/assets/21104793/19439654/efb34fda-944c-11e6-935c-48d8910bb8f3.PNG">
You can use the taskbar on the bottom of the screen for reference. The text and icons are pixelated and the console isn't very useful at this level of zoom.

Sorry if this is a trivial question; I'm rather new to Spyder and computer programming...
Thanks in advance for your help!

**What steps will reproduce the problem?**
Not sure, it just happens whenever I open Spyder.

**What is the expected output?**
This is closer to what I'd like it to look like (this is what happens when I adjust display settings), but maybe not quite as "zoomed":
<img width="960" alt="spyder ideal" src="https://cloud.githubusercontent.com/assets/21104793/19439600/a3a3be0e-944c-11e6-873f-9cffc2ce259c.PNG">

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.1
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

**Comment by ccordoba12** [comment] 2016-10-17 14:23
Thanks for reporting, this is a duplicate of issue #3489, so I'm closing it.

**Closed by ccordoba12** 2016-10-17 14:23 UTC
