### ISSUE TITLE
[Spyder 3.0.0dev, python3] TypeError: decorated slot has no signature compatible with triggered(bool)

### ISSUE THREAD

**Issue by malfatti** [spyder-ide/spyder#3163] opened 2016-05-12 12:56 UTC
## Description of your problem
 When starting spyder with `python bootstrap.py`, splash screen appears and then spyder crashes.

**What steps will reproduce the problem?**

1. `git clone https://github.com/spyder-ide/spyder && cd spyder`
2. `python3 bootstrap.py`

**What is the expected output? What do you see instead?**
Spyder is expected to open. Instead, it crashes.

**Please provide any additional information below**
Maybe can be related to https://github.com/spyder-ide/spyder/issues/3145, since I had this problem after upgrading Debian yesterday.

In python2.7, it runs fine. In python3.5:
```bash
$ python3.5 bootstrap.py 
Executing Spyder from source checkout
Revision 1e85743, Branch: master
01. Patched sys.path with /home/cerebro/Malfatti/Software/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 3.5.1+ 64bits, Qt 5.6.0, PyQt5 5.6 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.4381
Traceback (most recent call last):
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/app/spyder.py", line 3128, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/app/spyder.py", line 3014, in run_spyder
    main.setup()
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/app/spyder.py", line 854, in setup
    self.editor = Editor(self)
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/plugins/editor.py", line 400, in __init__
    self.initialize_plugin()
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/plugins/__init__.py", line 299, in initialize_plugin
    self.plugin_actions = self.get_plugin_actions()
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/plugins/editor.py", line 639, in get_plugin_actions
    triggered=self.load)
  File "/home/cerebro/Malfatti/Software/spyder/spyderlib/utils/qthelpers.py", line 242, in create_action
    action.triggered.connect(triggered)
TypeError: decorated slot has no signature compatible with triggered(bool)
```
## Versions and main components

* Spyder Version: clone from master
* Python Version: 3.5
* Operating system: Debian

## Dependencies
I cannot open it, but here is a list:
```bash
$ dpkg -l python3 python3-jedi python3-jupyter-c* python3-matplotlib python3-numpy python3-pandas pep8 python3-pickleshare python3-psutil pyflakes python3-pygments pylint pyqt* ipython3* python3-sphinx | grep ii

ii  ipython3                   2.4.1-1            all
ii  ipython3-qtconsole         2.4.1-1            all
ii  pep8                       1.7.0-2            all
ii  pyflakes                   1.2.2-1            all
ii  pylint                     1.5.5-1            all
ii  pyqt5-dev                  5.6+dfsg-1         all
ii  python3                    3.5.1-3            amd64
ii  python3-jedi               0.9.0-1            all
ii  python3-jupyter-client     4.2.2-1            all
ii  python3-jupyter-core       4.1.0-1            all
ii  python3-matplotlib         1.5.1-1+b2         amd64
ii  python3-numpy              1:1.11.0-1         amd64
ii  python3-pandas             0.18.0+git114-g6c6 all
ii  python3-pickleshare        0.5-1              all
ii  python3-psutil             4.1.0-1            amd64
ii  python3-pygments           2.1.3+dfsg-1       all
ii  python3-sphinx             1.3.6-2            all
```

**Comment by ccordoba12** [comment] 2016-05-14 21:32
This is a general problem with Qt 5.6. I'm closing this one as a duplicate of issue #3145.

**Closed by ccordoba12** 2016-05-14 21:32 UTC
