### ISSUE TITLE
H folder default

### ISSUE THREAD

**Issue by jstyrud** [spyder-ide/spyder#8466] opened 2018-12-20 09:20 UTC
### What steps will reproduce the problem?

On my system there is a network drive called H:/ where Spyder must absolutely not store things. If I start up Spyder with network off, it will store things on C as any normal program, even though I can't choose folder, which kind of sucks too. 
But if I start up Spyder with network on, it will start storing a lot of crap on H, which it really must NOT do. How do I turn this off?

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by bcolsen** [comment] 2018-12-20 21:10
We need more specifics about "things" and "crap" to help yo in this case.

Are you referring to the Spyder configuration files or the output of one of your python scripts? Can you give an example?

**Comment by jstyrud** [comment] 2018-12-21 07:42
Sorry, I thought they were generally known expressions for these files ;-) 

It's mostly the configuration files I guess. Folders named ".ipython" ".matplotlib" and ".spyder-py3" which in turn contain a bunch of other folders. Here's whats in the ".spyder-py3" folder:
![image](https://user-images.githubusercontent.com/45998292/50330618-34771580-04fc-11e9-953b-d66665933b99.png)

**Comment by bcolsen** [comment] 2018-12-21 08:18
Yep those are the config files. The code that sets the location is the `get_home_dir` function:
https://github.com/spyder-ide/spyder/blob/a44ab08db8735b057b02e4fdb9ad7fd5fb5fe9f8/spyder/config/base.py#L107

To troubleshoot this can you run this in your spyder console with the network drive on and then off:
```python
import os.path as osp
import os
print(osp.expanduser('~'))
print(os.environ.get('HOME', ''))
print(os.environ.get('USERPROFILE',''))
```

**Comment by jstyrud** [comment] 2018-12-21 09:10
Thanks a bunch!

Removing/changing the HOME env variable from my system fixed the issue. Don't know if it was Spyder or my system admin who put it there in the first place. Either way, now it works as I want it to, I can use the HOME env to select folder.

As a suggestion for the future I guess it would be better to put some UI inside the preferences menu to set up the HOME variable (or preferably another variable else for spyder specifically), so the user doesn't have to do it "manually".

**Comment by bcolsen** [comment] 2018-12-21 17:17
I'm glad I could help.

> As a suggestion for the future I guess it would be better to put some UI inside the preferences menu to set up the HOME variable (or preferably another variable else for spyder specifically), so the user doesn't have to do it "manually".

We are working on this and hopefully getting it in for Spyder 4.

Closing as duplicate of #3891

**Comment by ccordoba12** [comment] 2018-12-21 17:20
> We are working on this and hopefully getting it in for Spyder 4.

@bcolsen, how useful do you think this would be? Should we open an issue about it?

**Comment by bcolsen** [comment] 2018-12-21 17:22
@ccordoba12 Wouldn't #3891 take care of it or is that only for the python-kernel?

**Comment by bcolsen** [comment] 2018-12-21 17:32
Yes we shouldn't touch HOME.

> we can simply define a custom directory in our prefs for our settings.

This sounds like the best, but how can we read the preferences about the preference location without knowing the location of the preferences in the first place.  I suppose it could be implemented by setting a SPYDER-HOME environment var

**Comment by ccordoba12** [comment] 2018-12-21 17:41
This is a duplicate of issue #4150.

**Closed by ccordoba12** 2018-12-21 17:41 UTC
Labels: component:Preferences, type:Enhancement
