### ISSUE TITLE
Hungarian keyboard layout ('[', ALT GR+F) problem

### ISSUE THREAD

**Issue by StJosy** [spyder-ide/spyder#16073] opened 2021-07-24 09:25 UTC
### What steps will reproduce the problem?

I have been unable to write the first square brackets on QWERTZ (Hungarian) keyboard layout in Spyder editor. (ALTGR+F must be displays  the '[') 

Thank you!

**Comment by ccordoba12** [comment] 2021-07-24 17:53
Hey @StJosy, thanks for reporting. This is a duplicate of issue #15654 and we still don't know how to fix it.

**Closed by ccordoba12** 2021-07-24 17:53 UTC

**Comment by StJosy** [comment] 2021-07-25 04:18
> Hey @StJosy, thanks for reporting. This is a duplicate of issue #15654 and we still don't know how to fix it.

Hi ccordoba12,

I hope you agree this is an awkward issue. If you don't just switch to Hungarian layout and try to code. :) I can tell you one sol

**Comment by martinpenickacz** [comment] 2021-09-08 12:59
I have same problem. I have Windows 10 on czech keyboards, but shortcut Right Alt+F doesnt work. How to fix this problem, please? Thanks you for reply.

**Comment by StJosy** [comment] 2021-09-08 15:20
> I have same problem. I have Windows 10 on czech keyboards, but shortcut Right Alt+F doesnt work. How to fix this problem, please? Thanks you for reply.

I gave up Spyder because of this annoying issue. Now I'm coding in VS Code and I love it.

**Comment by martinpenickacz** [comment] 2021-09-09 06:52
I solved this by setting a keyboard shortcut and deleting the part where the ALT + F key is. Solved!

Tools-> Preferences> Keyboard shortcuts and delete this shortcut ALT+F. Enjoy!

**Comment by VaclavTrpisovsky** [comment] 2022-04-19 17:02
Hi,
I also had AltGr+F "[" not working on my Czech keyboard under Windows.
This problem is not related to *Spyder IDE* but this is the only semi-relevant thread so I'm posting my working solution here:
1. Choose any shortcut (such as one of the icons on your desktop with the ⤤ or ➦ arrow - Unicode does not have the exact equivalent but you know what I mean)
2. Right-click → Properties
3. Place your cursor into the "Shortcut key" field and press Ctrl+Alt+F or AltGr+F.
4. Click Apply.
5. Place your cursor into the "Shortcut key" field and press Backspace to clear it.
6. Click OK.
