### ISSUE TITLE
Parsing a pandas ExcelFile object crashes Spyder 2.3.6

### ISSUE THREAD

**Issue by procha79** [spyder-ide/spyder#2652] opened 2015-08-27 14:26 UTC
I just upgraded Spyder to 2.3.6 (from 2.3.5.2) and I am having issues when trying to parse a pandas ExcelFile object. Spyder basically crashes (I have to force-quit Spyder: I am running Windows 7). I am using pandas 0.16.2 and IPython 4.0. The issue is not present if I downgrade to Spyder 2.3.5.2 and IPython 3.2.1

Thanks

**Comment by ccordoba12** [comment] 2015-08-27 14:29
Please post a sample code that generates your crash. We need that to test and fix your problem in our side.

**Comment by procha79** [comment] 2015-08-27 14:38
I type the following 2 statements one at a time in the console and everything is fine.
import pandas as pd
XL = pd.ExcelFile("Import Export Data.xlsx", encoding="utf-8")

Then I type the following statement and Spyder 2.3.6 crashes as described above
exports = XL.parse('Exports')

When I do the same in 2.3.5.2, everything is fine.

**Comment by ccordoba12** [comment] 2015-08-27 14:48
And `Import Export Data.xlsx` is a simple Excel file? Or does it have something relevant we should know about?

**Comment by procha79** [comment] 2015-08-27 15:03
Yes. It is just a simple Excel file. Actually, it happens also with the *xls file in this waterfall example posted here: http://tooblippe.github.io/waterfall/

In the case of that file I get the error when I type 
datos= XL.parse('Sheet1')

**Comment by ccordoba12** [comment] 2015-08-27 15:10
Ok, thanks. I'll start to take a look at this problem right away.

**Comment by ccordoba12** [comment] 2015-09-30 03:56
This is really a duplicate of issue #2654

**Closed by ccordoba12** 2015-09-30 03:56 UTC
Labels: bug, Variable-Explorer
