### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by wuyi1983** [spyder-ide/spyder#5447] opened 2017-10-11 20:23 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda2\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 261, in <lambda>
    self.finished(ec, es))
  File "C:\Anaconda2\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 326, in finished
    self.show_data(justanalyzed=True)
  File "C:\Anaconda2\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 347, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "C:\Anaconda2\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 459, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "C:\Anaconda2\envs\tensorflow\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "C:\Anaconda2\envs\tensorflow\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "C:\Anaconda2\envs\tensorflow\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wuyi\\.spyder-py3\\profiler.results'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >

**Comment by ccordoba12** [comment] 2017-10-11 22:51
Thanks for reporting. This is a duplicate of issue #5107.

In the meantime, you can open a terminal (cmd.exe) and run

    spyder --reset

to fix this.

**Closed by ccordoba12** 2017-10-11 22:51 UTC
