### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by apsql** [spyder-ide/spyder#6525] opened 2018-02-26 10:45 UTC
### What steps will reproduce the problem?

Go to Preferences using the wrench icon. Go to Syntax Coloring settings and change the color scheme, selecting one of the presets. Any selection will do. Click on "Apply" on the GUI and the internal error occurs.

### Traceback
```python-traceback
  File "C:\ProgramData\Miniconda3\lib\site-packages\spyder\plugins\configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "C:\ProgramData\Miniconda3\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\ProgramData\Miniconda3\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\ProgramData\Miniconda3\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\ProgramData\Miniconda3\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.6.4
* Qt 5.6.2
* PyQt5 5.6
* Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-02-26 17:43
Thanks for reporting. This is a duplicate of issue #6519.

**Closed by ccordoba12** 2018-02-26 17:43 UTC

**Comment by apsql** [comment] 2018-02-26 17:46
I apologize, I did not notice.

**Comment by ccordoba12** [comment] 2018-02-26 17:47
No worries, thanks for the taking to do the report.
