### ISSUE TITLE
IPython - It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

### ISSUE THREAD

**Issue by wmbm** [spyder-ide/spyder#3114] opened 2016-04-13 07:33 UTC
## Upon starting the IPython console repeatedly prints that the Kernel has died

**What steps will reproduce the problem?**
1.  Everytime I start Spyder (I can't run any code)

**What is the expected output? What do you see instead?**

I would expect IPython to function normally

**Please provide any additional information below**

I have tried to resetting Spyder to default and reinstalling Anaconda, but I get the same error code.
## Versions and main components
- Spyder Version: 2.3.8.
- Python Version: 2.7
- Operating system: Windows 7
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment] 2016-04-13 17:33
Thanks for reporting. If you are using Anaconda, please open a terminal (i.e. cmd.exe) and run

    conda install pyzmq=14.7.0

and try again to see if that fixes your problem.

If not, please use your package manager (pip or WinPython) to install that version of pyzmq .-)

**Comment by wmbm** [comment] 2016-04-13 22:20
Gave that a go. Pyzmq downgrade worked fine bit still the same error.
Am 13.04.2016 19:33 schrieb "Carlos Cordoba" <notifications@github.com>:

**Comment by ccordoba12** [comment] 2016-04-15 15:48
We're investigating what's happening with this problem. Thanks for trying my proposed solution :-)

**Comment by wmbm** [comment] 2016-04-15 17:34
Ok thanks for the update. I've decided to install Ubuntu and download
Spyder onto it for now ;)

**Comment by ffyring** [comment] 2016-08-11 08:23
Hi. I have the same problem and setup as the original poster so I can't use Spyder at all. Downgrade did not work for me either. Are there any way to debug this?

**Comment by ffyring** [comment] 2016-08-15 13:59
I looked into my system logged and my local firewall blocked connections to 127.0.0.1 from pythonw.exe. After changing the settings everything works.

**Comment by coandrei** [comment] 2016-09-20 16:45
Same error message here on Python 2.7 since yesterday when I thought it is a good idea to update Spider. The python process goes crazy to 10Gb+ [here] (https://www.dropbox.com/s/mjsew0tl07ikgfz/Screenshot%202016-09-20%2022.35.28.png?dl=0) Although not an expert, it seems to me that this happens when trying to generate and/or display a plot. If no plot, everything seems to work fine.

**Comment by ISAE-Nicolas** [comment] 2016-11-11 21:18
Hi. I have the same problem and I can't use Spyder to do heavy computation. After few minutes of computation, I get several time this message : "Kernel died, restarting" and the program is killed of course. Downgrade did not work for me either.
This is my setup: 
Windows 10
Anaconda 3
Spyder 3.0.0
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

Are there any way to debug this?

**Comment by ccordoba12** [comment] 2016-11-11 23:17
@ISAE-Nicolas, we need a reproducible example to test and debug this problem in our side. Please help us by posting one here :-)

Or you can send me your code privately if you prefer so (my email is in my Github profile :-)

**Comment by raphaelquast** [comment] 2016-11-20 22:14
Hello, I have installed anaconda portable on an external hd. Even though it doesn't stop
during computation, the very same problem appears every now and then (quite unpredictable) 
when I manually close the ipython-console.
(it shows several times "kernel died, restarting" before it actually manages to restart)
Sometimes this goes into tens of restarts which can get quite annoying...

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by dwiprasetyo-an** [comment] 2016-11-21 01:10
I got the same problem here, and @ffyring solution of allowing pythonw.exe on my firewall solved my problem.

**Comment by ISAE-Nicolas** [comment] 2016-11-21 18:36
In my case, it seems to be a memory leak due to DecisionTree from scikit learn : [#7811](https://github.com/scikit-learn/scikit-learn/issues/7811) and [#7903](https://github.com/scikit-learn/scikit-learn/issues/7903).

**Comment by ccordoba12** [comment] 2016-11-22 02:37
@ISAE-Nicolas, thanks a lot for tracking this down! Please let us know how things end up being solved in scikit-learn :-)

**Comment by dmitrenkoivan** [comment] 2016-12-12 10:34
It was helpfull for me
**conda install nomkl numpy scipy scikit-learn numexpr**
**conda remove mkl mkl-service**

**Comment by mati-92** [comment] 2016-12-19 21:12
does anyone have a solution for this problem?

**Comment by barryzhai** [comment] 2016-12-20 08:38
@ccordoba12 Hello, I also have this problem. I think I might have some clue. I'm running spyder on my work laptop, on which peer to peer connection is restricted. When I'm running spyder, the connection to kernel keeps being blocked. But when I run Ipython alone, it seems work fine.

**Comment by mati-92** [comment] 2016-12-20 08:40
I had the problem both in spyder and ipython! I just upgraded my spyder and happily it is working now!

**Comment by ccordoba12** [comment] 2016-12-20 15:47
@barryzhai, I created pull request #3861 to improve the situation in Spyder 3.1.

For now, please start Spyder from a terminal (i.e. cmd.exe on Windows, bash on Linux/macOS) and print the messages shown there here. If you are on Windows, you need to start Spyder with

    spyder --show-console

**Comment by robinkarmakar651** [comment] 2017-01-06 08:07
@ccordoba12 I experienced the same error. 

It seems that the source of the issue was possibly the following:

1. With Spyder running / coding / no machine restart for a couple of days. Everything working fine
2. Working on an internal network (firewalled)
3. With Spyder open, changed the network to a shared network from my mobile (4g), then running some commands. Still works fine.
4. Restarted machine, open Spyder and this triggered the error. Restarting does not help, and updating (3.0.0 -> 3.0.2) helped, but problem resurfaced after a couple of minutes (some network switching during this time as well with Spyder open)
5. **Solution for me: "** Tools -> Reset Spyder to factory defaults"
6. Spyder is automatically restarted when choosing this
7. Spyder working fine again.

Based on the above, my slight intuition (without any knowledge) points me in the direction of the network connection used, and something being used outside the network as a resource. Unfortunately I cant add more to the discussion than that. 

Hope this can help somebody in this thread as well.

**Comment by ccordoba12** [comment] 2017-02-20 04:26
Closing as this should fixed in Spyder 3.

**Closed by ccordoba12** 2017-02-20 04:26 UTC

**Comment by ErikaWarnatzsch** [comment] 2017-09-26 10:06
I am having the same problem. It was all working on Thursday but when I try to run my scripts today they come up with the following message: "It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console." which repeats over and over. I have done conda update spyder and conda update matplotlib, but no improvement... please help! 

IPython >=1.0      :  5.4.1 (OK)
jedi >=0.8.1;<0.9.0:  0.10.2 (NOK)
matplotlib >=1.0   :  2.0.0 (OK)
pandas >=0.13.1    :  0.20.3 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  5.2.2 (OK)
pyflakes >=0.5.0   :  1.6.0 (OK)
pygments >=1.6     :  2.2.0 (OK)
pylint >=0.25      :  1.7.1 (OK)
qtconsole >=4.0    :  4.3.1 (OK)
rope >=0.9.2       :  0.10.7 (OK)
sphinx >=0.6.6     :  1.6.3 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  14.7.0 (OK)

**Comment by jaiswalswapnil** [comment] 2019-07-12 12:15
I am using spyder in a server but I had the problem spyder "Kernel died, restarting"  this massage display, so please tell me the solution.

**Comment by abihacheema** [comment] 2020-03-26 20:31
this issue has not yet fixed please help me

**Comment by ccordoba12** [comment] 2020-03-26 21:03
@abihacheema, I already gave you the solution.
