### ISSUE TITLE
Unable to use the command ctrl+i in Spyder Python

### ISSUE THREAD

**Issue by AvishkarSeth** [spyder-ide/spyder#8533] opened 2019-01-07 09:12 UTC
## Description

**What steps will reproduce the problem?**

1. Neither cntrl+G nor
2. ctrl+i are functional
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
I am not able to use the command ctrl+i for object inspection

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2019-01-07 17:03
Thanks for reporting. This is a duplicate of #5782 because autocompletion, help and going to a definition are provided by the same libraries.

Please see that issue for possible solutions.

**Closed by ccordoba12** 2019-01-07 17:03 UTC

**Comment by AvishkarSeth** [comment] 2019-01-07 17:11
Okay.. Thanks!
The issue happened because the software was idle for a long time. After
doing a restart it works perfectly..
