### ISSUE TITLE
command not work

### ISSUE THREAD

**Issue by roy96w** [spyder-ide/spyder#15095] opened 2021-04-03 09:20 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I tried "conda install spyder-kernel", and terminal showed "# All requested packages already installed." 
But when I open Spyder 5, there still showing error while starting the kernel

I checked the version of kernel I installed, is 2.0.1. But Spyder 5.0.0 said 2.0.1 (NOK)

**Comment by jdsierral** [comment] 2021-04-03 16:11
maybe `conda install -c conda-forge spyder-kernels`

**Comment by stonebig** [comment] 2021-04-03 17:09
apparently, a duplicate of this https://github.com/spyder-ide/spyder/issues/15091#issuecomment-812848088

**Comment by ccordoba12** [comment] 2021-04-03 19:24
Hey  @roy96w, thanks for reporting. As @stonebig said, this is a duplicate of issue #15091 and until we release a new version un a couple of days, you can safely ignore it.

**Closed by ccordoba12** 2021-04-03 19:24 UTC
