### ISSUE TITLE
Code completion fails on macOS with Kite

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#15383] opened 2021-04-22 09:29 UTC
Hi,

just a quick report, when using Kite and just trying the tutorial im getting an error:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 4490, in _handle_completions
    if (len(text) >= self.automatic_completions_after_chars
TypeError: '>=' not supported between instances of 'int' and 'tuple'
```

I changed the setting as described in the Preferences. Now it seems to be tuple in there...

System:
`Python 3.9.4 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Darwin 20.2.0`

Resetting do default fixes it. Seems to be when setting the preference value...?

**Comment by Baalkikhaal** [comment] 2021-04-22 10:33
As per https://github.com/spyder-ide/spyder/issues/15245#issuecomment-817286603 , restart Spyder to integrate Kite plugin

**Comment by ccordoba12** [comment] 2021-04-22 16:50
Hey @max3-2, this is a duplicate of issue #15324 and we'll try to fix it in our next release.

**Closed by ccordoba12** 2021-04-22 16:50 UTC
