### ISSUE TITLE
Spyder standalone Windows installer can not startup if installed for all user in a different drive than C

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#20015] opened 2022-11-09 06:12 UTC
## Problem Description
  - install spyder5.4.0 with windows installer Spyder_64bit_full.exe
  - startup spyder5.4.0
![image](https://user-images.githubusercontent.com/1759365/200752018-7eab6000-b083-4e54-b2ae-d9ba397903bb.png)
  - add PYTHONPATH env variable
  - startup again
  - no result

### What steps reproduce the problem?
https://user-images.githubusercontent.com/1759365/200751439-34ce3ca9-a041-4a10-814c-473283764657.mp4

## Versions

* Spyder version: 5.4.0
* Python version: unknown
* Qt version: unknown
* PyQt version: unknown
* Operating System name/version: windows10

**Comment by ccordoba12** [comment] 2022-11-09 18:50
Hey @leavor, thanks for reporting. We really don't know what's happening in this case.

@dalthviz, could you take a look at it?

**Comment by dalthviz** [comment] 2022-11-09 19:27
Tested updating and Spyder starts normally for me 🤔:

![imagen](https://user-images.githubusercontent.com/16781833/200922870-942c4112-483c-4f21-b1c2-ba914257d4d2.png)

Did you recently updated Windows @leavor ? Could it be possible for you to manually uninstall and reinstall Spyder again? 
and you downloaded the installer from the GitHub release page, right?

Any new info in order to reproduce, better understand this is greatly appreciated. Let us know!

**Comment by leavor** [comment] 2022-11-10 02:35
@dalthviz 
Yes, I download installer from Github release page!
I uninstall spyder5.4.0, and install again, but change install path from D to C, startup, it is ok!
Next , I uninstall spyder5.4.0 again and still installed on the D, startup,  the problem is the same as the beginning!
So the cause of this problem is caused by the installation path

**Comment by dalthviz** [comment] 2022-11-10 18:08
Thanks for the new info @leavor ! Also, did you install Spyder using the `install for current user` or the `install for all users` option? Checking locally, seems like changing the installation path drive using the `install for current user` works (installed in my E drive instead of the default C drive). Maybe using the `install for current user` could be a workaround for the moment so you can install Spyder in a different drive?

In any case this seems like an issue so we will try to check it in a future release :+1:

**Comment by leavor** [comment] 2022-11-11 01:59
install to `C` and  `for all users`, ok
install to `D` and `just for me`, ok
install to 'D' and  `for all users`, can not startup!

**Comment by ccordoba12** [comment] 2022-11-11 16:20
@dalthviz, is there something we could to avoid this issue? For instance, not allowing users to install Spyder for all users in drives other than `C`?

**Comment by dalthviz** [comment] 2022-11-11 18:33
To be honest I don't know, we will need to check

**Comment by dalthviz** [comment] 2023-03-17 22:30
After checking for a while this with Spyder 5.4.2 I was able to install Spyder for all the users in an external hard drive (`E:`). It took a couple of tries to install it since sometimes it was giving me write errors but I think that is related to my external hard drive (and is something outside the scope of the installer I think).

Could it be possible for you @leavor to check the installation for all users in a different drive with the latest Spyder installer? Let us know if you still experience the error message!

**Comment by dalthviz** [comment] 2023-06-18 23:07
Checked again with Spyder 5.4.3 installing in an external drive (`D: `) over a `Spyder` dir (`D:/Spyder/`) for a all-user installation and I was able to launch Spyder, so still unable to reproduce this :/

**Comment by ccordoba12** [comment] 2023-10-20 23:03
Closing because @dalthviz was unable to reproduce this one.

**Closed by ccordoba12** 2023-10-20 23:03 UTC
Labels: type:Bug, OS:Windows, Installers
