### ISSUE TITLE
Spyder has encountered a problem. This is an automatic generated report.

### ISSUE THREAD

**Issue by SN-Yang** [spyder-ide/spyder#18311] opened 2022-06-16 06:12 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
    max_entries=self.get_option('max_entries', 50))
    self.show_data()
    self.treewidget.set_results(filename, results)
    self.refresh()
    for module, lineno, message, msg_id in messages:
ValueError: too many values to unpack (expected 4)

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.13
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.3.1 (OK)
pycodestyle >=2.3:  2.7.0 (OK)
pygments >=2.0   :  2.10.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  4.1.2 (OK)
rope >=0.9.4     :  0.19.0 (OK)
jedi >=0.9.0     :  0.18.0 (OK)
nbconvert >=4.0  :  5.6.0 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.1.1 (OK)
IPython >=4.0    :  5.8.0 (OK)
pylint >=0.25    :  2.7.2 (OK)

```

**Comment by andfoy** [comment] 2022-06-16 16:02
Hi @SN-Yang, thanks for reporting this issue, however, this is a duplicate of https://github.com/spyder-ide/spyder/issues/14776. We invite you to see the discussion there in order to fix this issue.

**Closed by andfoy** 2022-06-16 16:02 UTC
