### ISSUE TITLE
Freshly installed Anaconda, Spyder crash, Windows 8.1

### ISSUE THREAD

**Issue by josesan77** [spyder-ide/spyder#4435] opened 2017-05-06 18:21 UTC
##

Freshly installed Anaconda, tryed to launch Spyder from Anaconda Navigator on Windows 8.1.  &nbsp; Seems to start, but after showing the booting image of Spyder 3.1.2, error window pops up saying: '_Spyder crashed during last session_'.
I tryed 'python spyder --reset' as suggested, but did not work (and has no meaning anyway on brand new installation).
From command line trials I got that dycom package was missing. When tried to add package 'conda install -c conda forge pydicom' and similar with 'pip ...' the repodata.json file could not be reached (in spite of the fact that there is no proxy, I received proxy connection error as reason: ???). Downloaded manually the package, tried setup.py.
Package is in the ../Lib/site-packages folder. Tryed to launch again from Anaconda Navigator or from Prompt, but still get 'Spyder crashed during last session' message.

Meanwhile I made a try on Windows 10 (on other PC), with the same package and succeded to launch Spyder from Anaconda Navigator and verifyed: pydicom package is (was) not automatically installed. So at some point I am mislead by the software.
This is not User friendly installation package at all.

I guess Windows 8.1 is also a problem (one of the worst Op System in my life), but that's what I have.
Please help! Thanks!

**conda info:**
               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\USERNAME\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\USERNAME\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/8.1 Windows/6.3.9600

**What steps will reproduce the problem?**
I uninstalled, reinstalled... the same. Otherwise I don't know.

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6.0

## Dependencies
copied from the PC Win10 on which it works, as I cannot do it on mine. 

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-05-07 16:50
Please run in a terminal

    spyder --reset
    spyder --show-console

and print here any errors reported in the console. Thanks!

**Comment by josesan77** [comment] 2017-05-07 19:47
Tryed it several times.
Result is shown below. It blames that Windows has corrupted files, but I guess the connection is wrong somehow for downloading packages or for else that needs internet.
Since I launched this issue ticket I tried:
**anaconda   &nbsp;  spyder   &nbsp;       python  &nbsp;   result**
2.3 x86/64     &nbsp; ???  &nbsp;  &nbsp;  &nbsp; &nbsp;          2.7    &nbsp; &nbsp;      not working
2.7 64bit   &nbsp;  &nbsp;   3.1.2   &nbsp;  &nbsp; &nbsp; &nbsp;         2.7  &nbsp; &nbsp;      not working
4.3.1 64bit   &nbsp;  3.1.2        &nbsp; &nbsp;      3.6 32bit  &nbsp; not working

**error message:**
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2989, in main
    mainwindow = run_spyder(app, options, args)
  File "F:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2891, in run_spyder
    main = MainWindow(options)
  File "F:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 494, in __init__
    socket.IPPROTO_TCP)
  File "F:\ProgramData\Anaconda3\lib\socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [WinError 10106] The requested service cannot be loaded or initialised

Note1: I've run scf.exe to fix Windows errors, still the problem is present.
Note2: I received proxy, http, and further net connection related errors at other steps so I guess it is not a Windows corruption/conflict. All other net-dependent software works properly.
Note3: when launching Anaconda Navigator, tried to sign in and I could not do it (while on website I managed it).
I guess some connection invoked by python is broken. I don't know how to verify as I am beginner and solutions on the net are diverse. Can't find the right one.

**Comment by ccordoba12** [comment] 2017-05-07 23:22
This is a duplicate of issue #4132.

What happens if you run

    netsh winsock reset

?

**Closed by ccordoba12** 2017-05-07 23:22 UTC
Labels: resolution:Duplicate

**Comment by josesan77** [comment] 2017-05-08 20:52
Dear ccordoba12!
Thanks, it really did resolve the problem.
If anyone interested here is some explanation and verification of errors:
[Microsoft solution](https://support.microsoft.com/en-us/help/811259/how-to-determine-and-to-recover-from-winsock2-corruption-in-windows-server-2003,-in-windows-xp,-and-in-windows-vista)
go to session: _Method 2: Use the Msinfo32 program_

I've found so many suggestion online but this...

**Comment by ccordoba12** [comment] 2017-05-08 21:29
Ok, thanks for the confirmation! We'll try to make Spyder to automatically run this solution when it encounters your problem, or at least inform users about this solution.

**Comment by 9Codes** [comment] 2018-04-25 13:51
I am Ezemonye O from Nigeria. A few minutes ago, #4435, I had the same problem above and the "spyder --reset" from anaconda cmd prompt worked pretty fine. @ccordoba12 , Clear and thanks.
