### ISSUE TITLE
spyder 5.3.3 standalone for macos not launching

### ISSUE THREAD

**Issue by phjo33** [spyder-ide/spyder#19237] opened 2022-08-30 18:37 UTC
I tried to update Spyder.app (standalone for macos) to latest 5.3.3 version today, but the app refused to run, with a message pointing to the py2app page.

Instructions were to run the app from the terminal, which I did, to no avail (with ./Application/Spyder.app/Contents/MacOs/spyder, tried some --debug options too to no avail either)

No error message in the terminal, nor any debug file generated.

Tried to sudo launch Spyder, no change.

Deleted ~/.spyder-py3 folder, and tried running it again. No dice. (The folder did reappear, but only with langconfig and plugins folder)

Deleted 5.3.3 and reinstalled 5.3.2 for the time being.

My macbook air (M1) is running Monterey 12.3.1.

**Comment by ccordoba12** [comment] 2022-08-30 18:43
Closing as a duplicate of issue #19236.

**Closed by ccordoba12** 2022-08-30 18:43 UTC
