### ISSUE TITLE
Windows fatal exception code 0xc06d007e when running simple numpy code

### ISSUE THREAD

**Issue by Rational-IM** [spyder-ide/spyder#21798] opened 2024-02-13 20:28 UTC
To avoid replicating the issue I initially reported on numpy's GitHut, please see https://github.com/numpy/numpy/issues/25809

Because another person reported having the same issue with matplotlib, and was successful in running Spyder with version 5.4, I'm assuming it is an issue with the new Spyder 5.5.1.

Note: all the tests I described on the issue were done on dedicated environments - i.e. very uniquely it was due to a corrupt installation.

**Comment by ccordoba12** [comment] 2024-02-15 15:36
Hey @Rational-IM, thanks for reporting. This seems a duplicate of issue #21749, which will be fixed in our next version (5.5.2), to be released in a couple of weeks.

Could you test that starting Spyder from the command line solves the issue for you? That's the workaround we can offer you until 5.5.2 is released.

**Comment by ccordoba12** [comment] 2024-02-15 15:38
Sorry, I just saw that you mentioned that already in the Numpy issue you referenced above: https://github.com/numpy/numpy/issues/25809#issuecomment-1945201830

So, I'm going to close this issue as duplicate of #21749.

**Closed by ccordoba12** 2024-02-15 15:38 UTC
Labels: status:Awaiting Followup
