### ISSUE TITLE
Minor request: option to clear / reload modules at script runtime

### ISSUE THREAD

**Issue by jaxankey** [spyder-ide/spyder#5308] opened 2017-09-21 20:18 UTC
I often want to run scripts in a "clean" terminal, with no lingering memory (to avoid "Mathematica Syndrome"). The existing "Clear all variables before executing" option works great in most cases, but I'd also like to have a checkbox for "Clear / reload all modules" as well. 

This is especially important when I am developing a new module, and using a "real" user script that imports said module to test it. Currently, the changes I make to an imported module to not propagate upon subsequent script executions, forcing me to close the console and restart it. Oh no! (This is why it's a minor request.)

Anyway, if it's easy to implement, great. It might save others a whole lot of confusion as well.

Cheers,
Jack

**Comment by ccordoba12** [comment] 2017-09-22 13:47
Hey Jack, thanks for opening this issue. I'm wondering if you have our UMR facilities deactivated and that's why you're seeing this problem.

You can verify that in

    Preferences > Python interpreter > User Module Reloader

**Comment by jaxankey** [comment] 2017-09-22 15:30
Thanks for the response. It's enabled.

If you have trouble reproducing this, note that I am editing a module
directly in python's site-packages folder.

**Comment by ccordoba12** [comment] 2017-12-09 06:47
This is a duplicate of issue #5877. We'll fix it in our 3.2.5 version.

**Closed by ccordoba12** 2017-12-09 06:47 UTC
Labels: component:IPython Console, type:Enhancement
