### ISSUE TITLE
Spyder hands with complex numbers in Pandas DataFrame

### ISSUE THREAD

**Issue by jaredjc51** [spyder-ide/spyder#2743] opened 2015-10-06 16:36 UTC
## Description

If my .py file contains a pandas.DataFrame with complex values in it, Spyder will become non-responsive and I have to force quit.
An example of the code is below:

```python
import numpy as np
import pandas as pd

A = np.array([[1+1j, 2+2j],[3+3j,4+4j]])
df_A = pd.DataFrame(A) # This is the problem
print df_A
```

This code crashes Spyder on my machine but runs as expected in the command prompt.
I have tried uninstalling and reinstalling Spyder through Anaconda but this problem persists.

Thanks for the help!

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Optional dependencies
```
IPython >=1.0   :  4.0.0 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  1.0.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  None (NOK)
qtconsole >=4.0 :  4.0.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

```

**Comment by ccordoba12** [comment] 2015-10-06 16:57
This is a duplicate of issue #2654, and it was fixed in Spyder 2.3.7.

This new version will be available in Anaconda in a couple of days :-)

**Closed by ccordoba12** 2015-10-06 16:57 UTC
Labels: duplicate

**Comment by jaredjc51** [comment] 2015-10-07 13:44
Sorry about that!

**Comment by ccordoba12** [comment] 2015-10-07 13:48
Don't worry about it :-) It's just such an annoying bug that people have all the right to open as many bugs as they want about it ;-)
