### ISSUE TITLE
I checked tools > preferences > IPython console > Graphics backend > Backend as Automatic.

### ISSUE THREAD

**Issue by Galganom** [spyder-ide/spyder#16258] opened 2021-08-21 07:18 UTC
### What steps will reproduce the problem?

When I restart my python kernel, the "CommError: Can't make a request to a closed comm" occurs...

so I checked tools > preferences > IPython console > Graphics backend > Backend as Automatic.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 451, in apply_plugin_settings
    client_backend_not_inline = [
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 452, in <listcomp>
    client.shellwidget.get_matplotlib_backend() != inline_backend
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 351, in get_matplotlib_backend
    return self.call_kernel(
  File "c:\users\park\appdata\local\programs\python\python38\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    raise CommError("The comm is not connected.")
spyder_kernels.comms.commbase.CommError: The comm is not connected.
```

## Versions

* Spyder version: 5.1.0 
* Python version: 3.8.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0                         :  1.4.0 (OK)
chardet >=2.0.0                              :  4.0.0 (OK)
cloudpickle >=0.5.0                          :  1.6.0 (OK)
cookiecutter >=1.6.0                         :  1.7.3 (OK)
diff_match_patch >=20181111                  :  20200713 (OK)
intervaltree >=3.0.2                         :  3.1.0 (OK)
IPython >=7.6.0                              :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0                        :  0.18.0 (OK)
jsonschema >=3.2.0                           :  3.2.0 (OK)
keyring >=17.0.0                             :  23.0.1 (OK)
nbconvert >=4.0                              :  6.1.0 (OK)
numpydoc >=0.6.0                             :  1.1.0 (OK)
paramiko >=2.4.0                             :  2.7.2 (OK)
parso >=0.7.0;<0.9.0                         :  0.8.2 (OK)
pexpect >=4.4.0                              :  4.8.0 (OK)
pickleshare >=0.4                            :  0.7.5 (OK)
psutil >=5.3                                 :  5.8.0 (OK)
pygments >=2.0                               :  2.9.0 (OK)
pylint >=2.5.0                               :  2.9.6 (OK)
pyls_spyder >=0.4.0                          :  0.4.0 (OK)
pylsp >=1.2.0;<1.3.0                         :  1.2.0 (OK)
pylsp_black >=1.0.0                          :  None (OK)
qdarkstyle =3.0.2                            :  3.0.2 (OK)
qstylizer >=0.1.10                           :  0.2.1 (OK)
qtawesome >=1.0.2                            :  1.0.3 (OK)
qtconsole >=5.1.0                            :  5.1.1 (OK)
qtpy >=1.5.0                                 :  1.9.0 (OK)
rtree >=0.9.7                                :  0.9.7 (OK)
setuptools >=49.6.0                          :  56.0.0 (OK)
sphinx >=0.6.6                               :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0                :  2.1.0 (OK)
textdistance >=4.2.0                         :  4.2.1 (OK)
three_merge >=0.1.1                          :  0.1.1 (OK)
watchdog >=0.10.3                            :  2.1.3 (OK)
zmq >=17                                     :  22.1.0 (OK)

# Optional:
cython >=0.21                                :  None (OK)
matplotlib >=2.0.0                           :  3.4.2 (OK)
numpy >=1.7                                  :  1.19.5 (OK)
pandas >=1.1.1                               :  None (OK)
scipy >=0.17.0                               :  1.7.1 (OK)
sympy >=0.7.3                                :  None (OK)

# Spyder plugins:
spyder.plugins.completion.plugin 5.1.0       :  5.1.0 (OK)
spyder.plugins.outlineexplorer.plugin 5.1.0  :  5.1.0 (OK)
spyder.plugins.projects.plugin 5.1.0         :  5.1.0 (OK)
spyder.plugins.variableexplorer.plugin 5.1.0 :  5.1.0 (OK)
```

**Comment by ccordoba12** [comment] 2021-08-22 22:43
Hey @Galganom, thanks for reporting. Please upgrade to our latest version (5.1.1) and try again.

**Comment by ccordoba12** [comment] 2021-08-24 14:17
I'm going to close this as a duplicate of issue #15875 because it's the exact same problem and it's older.

Let us know if the update to 5.1.1 fixes the problem for you in that issue.

**Closed by ccordoba12** 2021-08-24 14:17 UTC
Labels: status:Awaiting Followup
