### ISSUE TITLE
Missing Dependances 

### ISSUE THREAD

**Issue by lawalls46** [spyder-ide/spyder#15222] opened 2021-04-10 04:17 UTC
### What steps will reproduce the problem?

Can't run anything! I checked to see if the mentioned depandances are present and they are there. 
I looked on the Group forums and this seems to be a common issue and not fixed. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 2701, in stop_debugging
    self.main.ipyconsole.stop_debugging()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 910, in stop_debugging
    sw.stop_debugging()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\debugging.py", line 367, in stop_debugging
    self.pdb_execute_command("exit")
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\debugging.py", line 252, in pdb_execute_command
    echo_stack_entry=False, add_history=False)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\debugging.py", line 293, in pdb_execute
    self.kernel_client.input(line)
AttributeError: 'NoneType' object has no attribute 'input'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.18.0 (NOK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.8.1 (NOK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment] 2021-04-10 16:25
Hey @lawalls46, thanks for reporting. This problem could be caused by a very strict firewall or antivirus. Please close Spyder, stop them for a moment and try again. That could help.

**Comment by lawalls46** [comment] 2021-04-10 20:52
Carlos,
   I did not have this problem with the previous version of Spyder. It only
started when I installed version 5.0. I am using this behind a company
firewall and I don't have control over it. If the firewall is indeed the
problem, I'll just uninstall 5.0 and go back to the 4.x until the
developers can make it less restrictive.  Or start using another IDE.  If
you have any further suggestions please let me know.
Thanks,
Lloyd

**Comment by ccordoba12** [comment] 2021-04-10 21:02
> I'll just uninstall 5.0 and go back to the 4.x until the developers can make it less restrictive

Sure, if you want to use a very stable and well tested version, please go back to Spyder 4.2.5. You can try Spyder 5 in a couple of months to see if things work as expected then.

By the way, I don't think this is a problem with Spyder and I have no other idea how to solve it, sorry.

**Comment by ccordoba12** [comment] 2021-04-10 21:03
I'm going to close this issue because I don't have any more feedback or suggestions for you.

**Closed by ccordoba12** 2021-04-10 21:03 UTC
Labels: status:Awaiting Followup

**Comment by lawalls46** [comment] 2021-04-12 15:04
Thanks!
