### ISSUE TITLE
Online Help is not working

### ISSUE THREAD

**Issue by Fred-Wu** [spyder-ide/spyder#10740] opened 2019-11-17 09:16 UTC
## Problem Description

Online help is not working. I shoud say it never worked. 

1.  Always show "Unable to load page" by clicking on module or package name. 
2. Always show "Error, XXX.html, pydoc.ErrorDuringImport: problem in xxx - RuntimeError: implement_array_function method already has a docstring"  when search module or package. 

### What is the expected output? What do you see instead?

Expected to see help information by clicking module or package name, or method name inside. 

* Spyder version: 4.0.0rc1
* Python version: Python 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04

**Comment by ccordoba12** [comment] 2019-11-17 19:38
@dalthviz, please take a look at this one.

**Comment by CAM-Gerlach** [comment] 2019-11-19 01:04
@ccordoba12 FYI, this appears to be a duplicate of #5533 first reported in 2017 on Spyder 3.2.4, and the subsequant #8743 and  #9070 which we closed as duplicates.

**Closed** 2019-11-19 02:15 UTC
Labels: component:Online Help, type:Bug

**Comment by dalthviz** [comment] 2019-11-19 02:35
@Fred-Wu about the second error: `Error, XXX.html, pydoc.ErrorDuringImport: problem in xxx - RuntimeError: implement_array_function method already has a docstring` is a error from `pydoc` itself as far as I can tell (the error page is generated by `pydoc`). Also it seems some how related with `numpy` but I'm unsure (https://github.com/numpy/numpy/issues?q=is%3Aissue+RuntimeError%3A+implement_array_function+method+already+has+a+docstring+is%3Aopen)

**Comment by Fred-Wu** [comment] 2019-11-19 04:49
Does Online Help work at your end? 

If the purpose of Online Help is to provide a convenient mechanism to search for the help, but it never works, should it be removed from Spyder?

**Comment by ccordoba12** [comment] 2019-11-19 04:50
There's a bug in Spyder (which we'll fix before Spyder 4 is released), and a bug in `pydoc` itself, for which we'll have to submit a patch to Python.

That's the best we can do about it.

**Comment by Fred-Wu** [comment] 2019-11-19 05:01
Thanks @ccordoba12 . Glad to hear you are going to take care of this. Looking forward to using the final release.

**Comment by dalthviz** [comment] 2019-11-19 05:34
@Fred-Wu a fix for the issues listed here can be found in PR #10755 :)
