### ISSUE TITLE
Error in sitecustomize; set PYTHONVERBOSE for traceback: RuntimeError: 'path' must be None or a list, not  Error in usercustomize; set PYTHONVERBOSE for traceback: RuntimeError: 'path' must be None or a list, not  Traceback (most recent call last): File "", line 888, in _find_spec AttributeError: 'PyxImporter' object has no attribute 'find_spec'

### ISSUE THREAD

**Issue by SuvarnaMadiraju** [spyder-ide/spyder#6390] opened 2018-02-06 06:22 UTC
## Description of your problem
"not {}".format(type(path)))
RuntimeError: 'path' must be None or a list, not 

**What steps will reproduce the problem?**

1. I have Spyder 3.2.6 version  but i keep getting this runtime error of path must be "none'while using polyglot function and Spyder crashes..
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2018-02-06 14:36
Thanks for reporting, this is a duplicate of issue #5299. Please see that thread for a temporary workaround.

**Closed by ccordoba12** 2018-02-06 14:36 UTC
