### ISSUE TITLE
Unable to start spyder 3 beta from command line 

### ISSUE THREAD

**Issue by zzhao212** [spyder-ide/spyder#3269] opened 2016-06-28 20:50 UTC
## Description of your problem

After installing a clean copy of Anaconda 4.1, I first updated `pyqt` and `qt`, and then did `conda install -c spyder-ide spyder==3.0.0b3` because spyder 2.3.9 (the default version shipped with Anaconda 4.1) causes sluggishness in the editor as described in #2724. Then I tried to fire up spyder from the command line but got the following error
<img width="571" alt="screen shot 2016-06-28 at 4 45 57 pm" src="https://cloud.githubusercontent.com/assets/17503044/16431718/db8a8342-3d4f-11e6-91bf-1b18429adef0.png">
Please advise. Thanks

**Please provide any additional information below**
There was an error on `ERROR:root:code for hash md5 was not found` during the installation of Anaconda. Not sure if that has to do with any of this.

## Versions and main components

* Spyder Version: 3.0.0b3 
* Python Version: 2.7.11, Anaconda custom (x86_64)
* Operating system: OS X El Capitan, Version 10.11.5

**Comment by ccordoba12** [comment] 2016-06-28 23:47
This is a duplicate of issue #3267.

**Closed by ccordoba12** 2016-06-28 23:47 UTC
