### ISSUE TITLE
Error in Dataframe Click

### ISSUE THREAD

**Issue by jmargitic** [spyder-ide/spyder#5343] opened 2017-09-27 14:11 UTC
## Description

**What steps will reproduce the problem?**

1. I click on a Dataframe Column
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Juan Margitic\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 562, in sortByColumn
    if not self.model().sort(index, sort_order):
  File "C:\Users\Juan Margitic\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 312, in sort
    kind='mergesort')
  File "C:\Users\Juan Margitic\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3196, in sort_values
    str(by))
ValueError: Cannot sort by duplicate column  2013-

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)

**Comment by Prikers** [comment] 2017-09-27 15:06
Thank you for this feedback. This is a duplicate of #5225: the operation you are trying to achieve is not authorized by pandas (trying to sort on a column that has a duplicate in the dataframe). In the next spyder release, a dedicated error message will be displayed.

**Closed by Prikers** 2017-09-27 15:06 UTC

**Comment by SanaMohanReddy** [comment] 2019-04-02 10:09
sort_cols = ['A','B','C','D']
sorted_data = sorted_data.sort_values(by=[sort_cols])
ValueError: Cannot sort by duplicate column ['A','B','C','D']
but when i specify columns like below i am not facing any error
sorted_data = sorted_data.sort_values(by=['A','B','C','D'])
Please let me know how to resolve the issue

**Comment by Prikers** [comment] 2019-04-02 11:29
> sorted_data = sorted_data.sort_values(by=[sort_cols])

Here you are sorting by a list of list (you basically said `.sort_values(by=[['A','B','C','D']])` which may be the cause of your problem.
