### ISSUE TITLE
"Execute + jump to next cell" brings me to two cells further instead of one

### ISSUE THREAD

**Issue by MichaelMAB2020** [spyder-ide/spyder#19919] opened 2022-10-24 15:16 UTC
### What steps will reproduce the problem?

This behaviour suddenly occured in an old spyder 3.X version. 
After some time I reinstalled Spyder (now having version 5.1.5) but the problem remained?

here some system info:
Python 3.9.12 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10 

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)

**Comment by dalthviz** [comment] 2022-10-26 16:51
Hi @MichaelMAB2020 thank you for the feedback! Could it be possible for you to share an example code snippet to reproduce this behavior? Also, could you try to update to at least Spyder 5.2.2 and check again? Let us know!

**Comment by MichaelMAB2020** [comment] 2022-10-27 08:23
Hi Daniel,
thanks for looking into my problem!
I just tried to update Spyder to the latest version - unfortunately that failed (also deinstallation of spyder) :-( . Tried it via the anaconda navigator as normal user and as admin ... - no success. I remember also the last time when I updated spyder (from 3.X to 5.X) at the end I had to totally deinstall anaconda and starting from scratch.

I attach an example file here. It includes the example python code and a spyder screenshot, showing the code and  also its results in the Konsole when I 
- run the full script at once wit the "play" button [F5]): In [29]
- run it from the first cell (cell #0) with the "Execute + jump to next cell" (Shift+Return) button: In [30] to In [33]
- run it from the second cell (cell #1) with the "Execute + jump to next cell" (Shift+Return) button: In [34] to In [36]
You see the jumping cell numbers executed and also the different result ...
 
If you think it's worth to upgrade I am willing to try, but as I wrote: the problem "survived" also the upgrade from 3.X to my current version 5.1.5 ...  :-(

[spyderTest.zip](https://github.com/spyder-ide/spyder/files/9877271/spyderTest.zip)

**Comment by dalthviz** [comment] 2022-10-27 17:52
Thanks for the new info @MichaelMAB2020 ! I was unable to reproduce this locally with Spyder 5.2.2 or 5.3.3:

#### Checking with Spyder 5.2.2 using the toolbar buttons

![imagen](https://user-images.githubusercontent.com/16781833/198362534-324e99fa-8e21-4db9-9a33-c57084fac137.png)

If your Spyder installation is on your base conda environment I would suggest to update to Spyder 5.2.2 and check again by running from an Anaconda prompt with your base env activated something like:

```
conda update anaconda
conda install spyder=5.2.2
```

Let us know!

**Comment by MichaelMAB2020** [comment] 2022-10-28 06:07
Hi Daniel,

the two command lines from your last comment worked so that I was able to install spyder 5.2.2 (in contrast to my update trials via the anaconda navigator :-( ) and ... it works again.

Thank you & best regards!!!

**Comment by dalthviz** [comment] 2022-10-28 16:39
Awesome! Glad to hear Spyder is working for you now. Thank you for letting us know and then I will close this one :)

**Closed by dalthviz** 2022-10-28 16:39 UTC
Labels: status:Awaiting Followup
