### ISSUE TITLE
Error when restarting kernel in 5.0.1

### ISSUE THREAD

**Issue by thistlillo** [spyder-ide/spyder#15399] opened 2021-04-23 05:28 UTC
This is my installation:
Python 3.7.9 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Windows 10 Pro

Spyder is ver 5.0.1

Spyder starts within a conda environment (`my_conda_env` below)  running Python 3.6.12. It starts fine.

If I restart the spyder kernel using the menu in the console pane, I get this long list of error messages in the console. Even after these errors, I can open a new console (default settings) without errors.

```
Traceback (most recent call last):
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\ipykernel\kernelapp.py", line 567, in initialize
self.init_sockets()
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\ipykernel\kernelapp.py", line 271, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\ipykernel\kernelapp.py", line 218, in _bind_socket
return self._try_bind_socket(s, port)
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\ipykernel\kernelapp.py", line 194, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "C:\Users\user\miniconda3\envs\my_conda_env\lib\site‑packages\zmq\sugar\socket.py", line 173, in bind
super().bind(addr)
File "zmq/backend/cython/socket.pyx", line 542, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
```

**Comment by juanis2112** [comment] 2021-04-24 00:20
HI @thistlillo. This seems to be a duplicate of #14739. Please take a look at the discussion there and if the solutions proposed don't work, let me know.

**Closed** 2021-04-24 00:21 UTC
Labels: resolution:Duplicate
