### ISSUE TITLE
Spyder 5 problems

### ISSUE THREAD

**Issue by fahmanali** [spyder-ide/spyder#15219] opened 2021-04-10 01:00 UTC
Spyder-kernel 2.1.0  issue
If there is an error when clicked on the line of code Spyder, doesn't open it.
I can't close and open cell of code.

**Comment by ccordoba12** [comment] 2021-04-10 02:17
Hey @fahmanali, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Comment by ccordoba12** [comment] 2021-04-10 02:18
> If there is an error when clicked on the line of code Spyder, doesn't open it.

This is a duplicate of issue #15166 and it'll also be fixed in 5.0.1

**Comment by ccordoba12** [comment] 2021-04-10 02:22
> I can't close and open cell of code.

I can't reproduce this problem. Collapsing cells is working for me as expected. Could you post a screenshot of what you're seeing? Thanks!

**Comment by fahmanali** [comment] 2021-04-10 23:03
One issue: If I want to open the function def by clicking its name; it is not opened.

**Comment by ccordoba12** [comment] 2021-04-11 00:54
What do you mean exactly by that? I don't get it.

**Comment by fahmanali** [comment] 2021-04-11 01:12
I mean if you create a function and call it later in code or in another file. So, when you right-click and choose to go to definition; it doesn't work.

**Comment by fahmanali** [comment] 2021-04-11 01:16
> > I can't close and open cell of code.
> 
> I can't reproduce this problem. Collapsing cells is working for me as expected. Could you post a screenshot of what you're seeing? Thanks!

I mean: like vscode near to each function, there is a row in the left to close and open cell of if block or function block.

**Comment by fahmanali** [comment] 2021-04-11 01:20
I wish also if we can change the variable name and at the same time change all the existence of it in the document.

**Comment by ccordoba12** [comment] 2021-04-11 01:54
Ok, please use one of our installers here:

https://github.com/spyder-ide/spyder/releases/tag/v5.0.0

and try again. It could an installation issue that you shouldn't experience with our installers.

**Comment by ccordoba12** [comment] 2021-04-19 01:22
Closing due to lack of response.

**Closed by ccordoba12** 2021-04-19 01:22 UTC
Labels: status:Awaiting Followup
