### ISSUE TITLE
Continious crashes - `zmq.error.ZMQError: not a socket`

### ISSUE THREAD

**Issue by Mateo-drr** [spyder-ide/spyder#20969] opened 2023-05-28 14:00 UTC
### What steps will reproduce the problem?

writing code, normally when trying to autofill but not sure

### Traceback
```python-traceback
Exception in callback AddThreadSelectorEventLoop._handle_select([8412], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([8412], [])>
Traceback (most recent call last):
  File "C:\Users\Mateo-drr\miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Mateo-drr\miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 647, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\Users\Mateo-drr\miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 661, in _handle_event
    callback()
  File "C:\Users\Mateo-drr\miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\Mateo-drr\miniconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 614, in _handle_events
    zmq_events = self.socket.EVENTS
  File "C:\Users\Mateo-drr\miniconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 56, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "C:\Users\Mateo-drr\miniconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 68, in _get_attr_opt
    return self.get(opt)
  File "zmq\backend\cython\socket.pyx", line 512, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 270, in zmq.backend.cython.socket._getsockopt
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: not a socket
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.11.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.2.9 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.1.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.0 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.3 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  65.6.3 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.3.1 (OK)
zmq >=22.1.0                                     :  25.0.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by dalthviz** [comment] 2023-05-28 21:32
Hi @Mateo-drr thank you for the feedback! This seems related with https://github.com/spyder-ide/spyder/issues/20381 what is your pyzmq and IPython versions? Maybe updating those packages could help?

Let us know if the info above helps!

**Comment by mscheltienne** [comment] 2023-06-05 12:23
Similar issue, mostly when I execute some code with F9, then open a multi-line str in the variable explorer and close the pop-up.

```
IPython: 8.13.1
pyzmq: 25.0.0
```

In Spyder 5.4.3 on 22.04 LTS. I can not find a reproducible example yet..

**Comment by dalthviz** [comment] 2023-06-05 14:43
Thanks for the info @mscheltienne ! Could it be possible for you to test if updating to the latest version of IPython and pyzmq helps? Checking seems like the latest versions are IPython 8.14.0 and pyzmq 25.1.0, let us know if updating them helps!

**Comment by mscheltienne** [comment] 2023-06-13 13:26
@dalthviz Hello, sorry for taking so long to reply.
It does seem to fix the issue. During the past week, I updated both IPython and pyzmq in my base environment; and then everytime I would work in a virtual env where the error would appear, I would update IPython and pyzmq in the venv, restart spyder, and I would not get this kind of error anymore for the remaining of my work in that venv.

**Comment by dalthviz** [comment] 2023-06-13 20:43
Thank you for the update @mscheltienne ! No worries, glad to hear things are working better after updating IPython and pyzmq! I will close this as a duplicate of https://github.com/spyder-ide/spyder/issues/20381 but if you face any other zmq related errors let us know!

**Comment by mscheltienne** [comment] 2023-06-20 13:08
@dalthviz This issue should be re-opened. I'm still hitting it even with my base env and my virtual env up to date for IPython and pyzmq.

**Comment by dalthviz** [comment] 2023-06-20 21:07
Hi @mscheltienne, sure :+1: Could you post here the details of your envs (base and other envs you are using) related with IPython and pyzmq versions? Also, did you find something that could trigger this error/enables the issue to be reproduced in a reliable way? Let us know!

**Comment by mscheltienne** [comment] 2023-06-21 11:03
<details>
<summary>Base environment with Spyder (pip list)</summary>
<br>
      
```python
Package                       Version
----------------------------- -----------
aiofiles                      22.1.0
aiosqlite                     0.18.0
alabaster                     0.7.13
anyio                         3.6.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.1
asttokens                     2.2.1
atomicwrites                  1.4.1
attrs                         22.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
beautifulsoup4                4.11.2
binaryornot                   0.4.4
black                         23.1.0
bleach                        6.0.0
certifi                       2022.12.7
cffi                          1.15.1
chardet                       5.1.0
charset-normalizer            3.0.1
click                         8.1.3
cloudpickle                   2.2.1
comm                          0.1.2
contourpy                     1.0.7
cookiecutter                  2.1.1
cryptography                  39.0.1
cycler                        0.11.0
Cython                        0.29.33
debugpy                       1.6.6
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
docstring-to-markdown         0.11
docutils                      0.19
entrypoints                   0.4
executing                     1.2.0
fastjsonschema                2.16.2
flake8                        6.0.0
fonttools                     4.38.0
fqdn                          1.5.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.21.1
ipython                       8.14.0
ipython-genutils              0.2.0
isoduration                   20.11.0
isort                         5.12.0
jaraco.classes                3.2.3
jedi                          0.18.2
jeepney                       0.8.0
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
json5                         0.9.11
jsonpointer                   2.3
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.2.0
jupyter-events                0.5.0
jupyter_server                2.2.1
jupyter_server_fileid         0.6.0
jupyter_server_terminals      0.4.4
jupyter_server_ydoc           0.6.1
jupyter-ydoc                  0.2.2
jupyterlab                    3.6.1
jupyterlab-pygments           0.2.2
jupyterlab_server             2.19.0
keyring                       23.13.1
kiwisolver                    1.4.4
lazy-object-proxy             1.9.0
MarkupSafe                    2.1.2
matplotlib                    3.6.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mistune                       2.0.5
more-itertools                9.0.0
mpmath                        1.2.1
mypy-extensions               1.0.0
nbclassic                     0.5.1
nbclient                      0.7.2
nbconvert                     7.2.9
nbformat                      5.7.3
nest-asyncio                  1.5.6
notebook                      6.5.2
notebook_shim                 0.2.2
numpy                         1.24.2
numpydoc                      1.5.0
packaging                     23.0
pandas                        1.5.3
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.11.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.1.2
platformdirs                  3.0.0
pluggy                        1.0.0
prometheus-client             0.16.0
prompt-toolkit                3.0.36
psutil                        5.9.4
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.10.0
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.0.1
Pygments                      2.14.0
pylint                        2.16.1
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
pyparsing                     3.0.9
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.1
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyrsistent                    0.19.3
python-dateutil               2.8.2
python-json-logger            2.0.4
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.2
python-slugify                8.0.0
pytoolconfig                  1.2.5
pytz                          2022.7.1
pyxdg                         0.28
PyYAML                        6.0
pyzmq                         25.1.0
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.2
QtPy                          2.3.0
requests                      2.28.2
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rope                          1.7.0
Rtree                         1.0.1
scipy                         1.10.0
SecretStorage                 3.3.3
Send2Trash                    1.8.0
setuptools                    67.7.2
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        6.1.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.3
spyder-kernels                2.4.3
stack-data                    0.6.2
sympy                         1.11.1
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.6
tornado                       6.2
traitlets                     5.9.0
typing_extensions             4.4.0
ujson                         5.7.0
uri-template                  1.2.0
urllib3                       1.26.14
watchdog                      2.2.1
wcwidth                       0.2.6
webcolors                     1.12
webencodings                  0.5.1
websocket-client              1.5.1
whatthepatch                  1.0.4
wheel                         0.40.0
wrapt                         1.14.1
wurlitzer                     3.0.3
y-py                          0.5.5
yapf                          0.32.0
ypy-websocket                 0.8.2
zipp                          3.12.1
```
</details>

---------------------------------

<details>
<summary>Base environment with Spyder (Spyder dependencies)</summary>
<br>
      
```python
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.2.9 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.16.1 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.3 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.7.2 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.2.1 (OK)
xdg >=0.26                                       :  0.28 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  0.29.33 (OK)
matplotlib >=3.0.0                               :  3.6.3 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.10.0 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```
</details>

---------------------------------

<details>
<summary>Virtual environment (pip list)</summary>
<br>
      
```python
Package                       Version    Editable project location
----------------------------- ---------- -----------------------------------
accessible-pygments           0.0.4
alabaster                     0.7.13
asttokens                     2.2.1
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.12.2
bibclean                      0.5.0
bibtexparser                  1.4.0
black                         23.3.0
bleach                        6.0.0
bsl                           0.6.0.dev0 /home/scheltie/git/mscheltienne/bsl
build                         0.10.0
certifi                       2022.12.7
cffi                          1.15.1
charset-normalizer            3.1.0
click                         8.1.3
cloudpickle                   2.2.1
codespell                     2.2.4
comm                          0.1.3
contourpy                     1.0.7
coverage                      7.2.3
cryptography                  40.0.2
cycler                        0.11.0
debugpy                       1.6.7
decorator                     5.1.1
distro                        1.8.0
docutils                      0.19
exceptiongroup                1.1.1
executing                     1.2.0
flake8                        6.0.0
fonttools                     4.39.3
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.6.0
iniconfig                     2.0.0
ipykernel                     6.22.0
ipython                       8.14.0
isort                         5.12.0
jaraco.classes                3.2.3
jedi                          0.18.2
jeepney                       0.8.0
Jinja2                        3.1.2
jupyter_client                8.2.0
jupyter_core                  5.3.0
keyring                       23.13.1
kiwisolver                    1.4.4
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mne                           1.4.2
more-itertools                9.1.0
mypy-extensions               1.0.0
nest-asyncio                  1.5.6
numpy                         1.24.3
numpydoc                      1.5.0
packaging                     23.1
parso                         0.8.3
pathspec                      0.11.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.1.1
pkginfo                       1.9.6
platformdirs                  3.2.0
pluggy                        1.0.0
pooch                         1.7.0
prompt-toolkit                3.0.38
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.10.0
pycparser                     2.21
pydata-sphinx-theme           0.13.3
pydocstyle                    6.3.0
pyflakes                      3.0.1
Pygments                      2.15.1
pyparallel                    0.2.2
pyparsing                     3.0.9
pyproject_hooks               1.0.0
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.12.1
pyqtgraph                     0.13.3
pyserial                      3.5
pytest                        7.3.1
pytest-cov                    4.0.0
pytest-timeout                2.1.0
python-dateutil               2.8.2
pyzmq                         25.1.0
readme-renderer               37.3
requests                      2.28.2
requests-toolbelt             0.10.1
rfc3986                       2.0.0
rich                          13.3.4
ruff                          0.0.264
scipy                         1.10.1
SecretStorage                 3.3.3
setuptools                    67.7.1
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.4.1
Sphinx                        6.2.0
sphinx-gallery                0.13.0
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder-kernels                2.4.3
stack-data                    0.6.2
toml                          0.10.2
tomli                         2.0.1
tornado                       6.3.1
tqdm                          4.65.0
traitlets                     5.9.0
twine                         4.0.2
typing_extensions             4.5.0
urllib3                       1.26.15
wcwidth                       0.2.6
webencodings                  0.5.1
wheel                         0.40.0
wurlitzer                     3.0.3
zipp                          3.15.0
```
</details>

**Comment by mscheltienne** [comment] 2023-06-21 11:15
> did you find something that could trigger this error/enables the issue to be reproduced in a reliable way? 

Sadly no, it's not reproducible. I tend to use a lot of selection + F9 to execute in the console, and it's usually after one of those F9 that the error appears.

**Comment by ccordoba12** [comment] 2023-06-21 16:51
@mscheltienne, please update Jupyter-client to 8.2.0 and try again. That version is also required to fix this problem.

Also, are you not mixing pip and conda packages, right? Just to be sure because that could be the cause of this.

**Comment by mscheltienne** [comment] 2023-06-21 16:58
Definitely not mixing pip and conda. Will try to update that and report back here in a couple. of days. Thanks!

**Comment by mscheltienne** [comment] 2023-06-28 14:44
For now, updating `jupyter-client` in the base environment seems to fix it. I haven't seen this issue in the past week.

**Comment by ccordoba12** [comment] 2023-07-14 15:38
Closing since no additional problems have been reported so far.

**Closed by ccordoba12** 2023-07-14 15:38 UTC
Labels: component:IPython Console, status:Awaiting Followup
