### ISSUE TITLE
configparser.DuplicateOptionError when creating a project

### ISSUE THREAD

**Issue by peterwright95** [spyder-ide/spyder#13450] opened 2020-08-01 19:55 UTC
### What steps will reproduce the problem?

- Download Github Repository
- Create project

### Traceback
```python-traceback
  File "C:\Users\peter\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 212, in opener
    self.open_project(path=project)
  File "C:\Users\peter\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 326, in open_project
    project = EmptyProject(path)
  File "C:\Users\peter\Anaconda3\lib\site-packages\spyder\plugins\projects\projecttypes\__init__.py", line 41, in __init__
    self.config = ProjectMultiConfig(
  File "C:\Users\peter\Anaconda3\lib\site-packages\spyder\config\user.py", line 782, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "C:\Users\peter\Anaconda3\lib\site-packages\spyder\config\user.py", line 212, in __init__
    self._load_from_ini(previous_fpath)
  File "C:\Users\peter\Anaconda3\lib\site-packages\spyder\config\user.py", line 333, in _load_from_ini
    self.read(fpath, encoding='utf-8')
  File "C:\Users\peter\Anaconda3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\peter\Anaconda3\lib\configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from 'C:\\Users\\peter\\Documents\\GitHub\\IMPAKTER_index\\.spyproject\\config\\workspace.ini' [line 12]: option 'recent_files' in section 'main' already exists
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-08-01 20:37
Hey @peterwright95, can you give us more details about this error?

**Comment by peterwright95** [comment] 2020-08-01 20:43
Yes. I just recently bought a new pc, installed Anaconda and through it the above mentioned version of Spyder. As I lost my Github projects by changing the PC, I cloned the repository utilizing GitHub desktop to my new PC. In order to apply changes I tried to create a new Project on Spyder with an already created directory (the cloned download) and when trying to create come up with this issue

**Comment by ccordoba12** [comment] 2020-08-16 17:06
@peterwright95, please give us a step by step description on how to reproduce this issue. Otherwise we won't be able to fix it.

**Comment by ccordoba12** [comment] 2023-11-24 03:52
Closing because this is quite old now. Hopefully you managed to solve this problem.

**Closed by ccordoba12** 2023-11-24 03:52 UTC
Labels: status:Awaiting Followup
