### ISSUE TITLE
Plots doesnt show up in version 6.0.0b2

### ISSUE THREAD

**Issue by Chuck321123** [spyder-ide/spyder#22224] opened 2024-07-02 11:13 UTC
### Issue Report Checklist

Checklist checked.

## Problem Description

So no plots show up in version 6.0.0b2. 

### What steps reproduce the problem?
```py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Generate 1 million random datetimes using pandas
start_time = '2020-01-01 00:00:00'
datetime_range = pd.date_range(start=start_time, periods=1_000_000, freq='min')

# Generate 1 million random floats
random_floats = np.random.random(1_000_000)

# Sort the random floats
sorted_random_floats = np.sort(random_floats)

# Create Polars DataFrame
df = pd.DataFrame({
    'datetime': datetime_range,
    'sorted_random_floats': sorted_random_floats
})

# Plot the first 1000 sorted random float values against their datetime values
plt.figure(figsize=(10, 6))
plt.plot(df['datetime'][:1000], df['sorted_random_floats'][:1000])
plt.xlabel('Datetime')
plt.ylabel('Sorted Random Floats')
plt.title('Sorted Random Float Values Over Time')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
```

### What is the expected output? 
That i can see plots

## Versions

* Spyder version: 6.0.0b2  (conda)
* Python version: 3.12.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-11-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                   :  3.9.5 (OK)
asyncssh >=2.0.0,<3.0.0           :  2.14.2 (OK)
atomicwrites >=1.2.0              :  1.4.1 (OK)
chardet >=2.0.0                   :  5.2.0 (OK)
cloudpickle >=0.5.0               :  3.0.0 (OK)
cookiecutter >=1.6.0              :  2.6.0 (OK)
diff_match_patch >=20181111       :  20230430 (OK)
github >=2.3.0                    :  2.3.0 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1  :  8.23.0 (OK)
jedi >=0.17.2,<0.20.0             :  0.19.1 (OK)
jellyfish >=0.7                   :  1.0.3 (OK)
jsonschema >=3.2.0                :  4.21.1 (OK)
keyring >=17.0.0                  :  25.0.1 (OK)
nbconvert >=4.0                   :  7.16.3 (OK)
numpydoc >=0.6.0                  :  1.7.0 (OK)
paramiko >=2.4.0                  :  3.4.0 (OK)
parso >=0.7.0,<0.9.0              :  0.8.3 (OK)
pexpect >=4.4.0                   :  4.9.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.9.8 (OK)
pygments >=2.0                    :  2.17.2 (OK)
pylint >=3.1,<4                   :  3.2.5 (OK)
pylint_venv >=3.0.2               :  3.0.3 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0            :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0        :  2.0.0 (OK)
pyuca >=1.2                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0         :  3.2.3 (OK)
qstylizer >=0.2.2                 :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0          :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0          :  5.5.1 (OK)
qtpy >=2.4.0                      :  2.4.1 (OK)
rtree >=0.9.7                     :  1.2.0 (OK)
setuptools >=49.6.0               :  68.2.2 (OK)
sphinx >=0.6.6                    :  7.2.6 (OK)
spyder_kernels >=3.0.0b7,<3.0.0b8 :  3.0.0b7 (OK)
superqt >=0.6.2,<1.0.0            :  0.6.7 (OK)
textdistance >=4.2.0              :  4.6.1 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  4.0.0 (OK)
yarl >=1.9.4                      :  1.9.4 (OK)
zmq >=24.0.0                      :  25.1.2 (OK)

# Optional:
cython >=0.21                     :  None (NOK)
matplotlib >=3.0.0                :  3.9.0 (OK)
numpy >=1.7                       :  1.26.4 (OK)
pandas >=1.1.1                    :  2.2.2 (OK)
scipy >=0.17.0                    :  None (NOK)
sympy >=0.7.3                     :  None (NOK)

```

**Comment by ccordoba12** [comment] 2024-07-03 17:16
Hey @Chuck321123, thanks for reporting. What do you mean by this?

> So no plots show up in version 6.0.0b2.

What's exactly happening in your case? Is the Plots pane not visible? Or are plots not being shown in the IPython console?

**Comment by Chuck321123** [comment] 2024-07-05 08:16
@ccordoba12 Plots are not showing up in the plot panel

**Comment by ccordoba12** [comment] 2024-07-05 14:35
Ok, and are you able to create plots outside Spyder?

**Comment by Chuck321123** [comment] 2024-07-05 23:01
@ccordoba12 Yes

**Comment by victorsanchezarevalo** [comment] 2024-07-08 12:01
I had the same problem

**Comment by victorsanchezarevalo** [comment] 2024-07-08 12:29
> Ok, and are you able to create plots outside Spyder?

I have been able to do it in Visual Studio Code

**Comment by victorsanchezarevalo** [comment] 2024-07-08 13:24
I have solved the problem with ploty using, import plotly.io as pio pio.renderers.default = "png" but I cannot see the graph with matplotlib

**Comment by victorsanchezarevalo** [comment] 2024-07-08 19:04
In a different computer I see the plots with ploty and matplotlib

**Comment by victorsanchezarevalo** [comment] 2024-07-09 08:17
I have change the conda enviroment and now I see the plots perfectly.

**Comment by ccordoba12** [comment] 2024-07-09 15:19
@Chuck321123, please post the output of `conda list` for the environment in which you have beta2 installed. That will help us to reproduce your problem on our side.

**Comment by victorsanchezarevalo** [comment] 2024-07-09 15:32
After changing the conda environment, it seemed to work, but again I am having problems plotting with matplotlib. Plotly works perfectly. I also had problems plotting survival curves with lifelines.

**Comment by Chuck321123** [comment] 2024-07-09 16:36
@ccordoba12 Sure:
```
# Name                    Version                   Build  Channel
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alabaster                 0.7.16                   pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
astroid                   3.2.2                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
asyncssh                  2.14.2                   pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
autopep8                  2.0.4                    pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
bcrypt                    4.1.2                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
binance-futures-connector 4.0.0                    pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
black                     24.3.0                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
bzip2                     1.0.8                h2bbff1b_5
ca-certificates           2024.3.11            haa95532_0
certifi                   2024.2.2                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cookiecutter              2.6.0                    pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dateparser                1.2.0                    pypi_0    pypi
debugpy                   1.8.1                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
diff-match-patch          20230430                 pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docstring-to-markdown     0.15                     pypi_0    pypi
docutils                  0.20.1                   pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
expat                     2.5.0                hd77b12b_0
fastjsonschema            2.19.1                   pypi_0    pypi
flake8                    7.0.0                    pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        7.1.0                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.29.4                   pypi_0    pypi
ipython                   8.23.0                   pypi_0    pypi
ipywidgets                8.1.3                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
isort                     5.13.2                   pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            4.3.0                    pypi_0    pypi
jaraco-functools          4.0.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jellyfish                 1.0.3                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
json5                     0.9.25                   pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.6.1                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.1                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.2.3                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.2                   pypi_0    pypi
jupyterlab-widgets        3.0.11                   pypi_0    pypi
keyring                   25.0.1                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
memory-profiler           0.61.0                   pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
more-itertools            10.2.0                   pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.3                   pypi_0    pypi
nbformat                  5.10.3                   pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
notebook                  7.2.1                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
numpydoc                  1.7.0                    pypi_0    pypi
openpyxl                  3.1.3                    pypi_0    pypi
openssl                   3.0.13               h2bbff1b_0
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pandas-ta                 0.3.14b0                 pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
paramiko                  3.4.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       23.3.1          py312haa95532_0
platformdirs              4.2.0                    pypi_0    pypi
pluggy                    1.4.0                    pypi_0    pypi
polars                    1.1.0                    pypi_0    pypi
prometheus-client         0.20.0                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyarrow                   16.1.0                   pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydocstyle                6.3.0                    pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pygithub                  2.3.0                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
pylint                    3.2.5                    pypi_0    pypi
pylint-venv               3.0.3                    pypi_0    pypi
pyls-spyder               0.4.0                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyqt5                     5.15.10                  pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.13.0                  pypi_0    pypi
pyqtwebengine             5.15.6                   pypi_0    pypi
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
python                    3.12.2               h1d929f7_0
python-binance            1.0.19                   pypi_0    pypi
python-dateutil           2.9.0.post0              pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-lsp-black          2.0.0                    pypi_0    pypi
python-lsp-jsonrpc        1.1.2                    pypi_0    pypi
python-lsp-server         1.11.0                   pypi_0    pypi
python-slugify            8.0.4                    pypi_0    pypi
pytoolconfig              1.3.1                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyuca                     1.2                      pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pywin32-ctypes            0.2.2                    pypi_0    pypi
pywinpty                  2.0.13                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
qdarkstyle                3.2.3                    pypi_0    pypi
qstylizer                 0.2.2                    pypi_0    pypi
qtawesome                 1.3.1                    pypi_0    pypi
qtconsole                 5.5.1                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
referencing               0.34.0                   pypi_0    pypi
regex                     2024.5.15                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rope                      1.13.0                   pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
rtree                     1.2.0                    pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                68.2.2          py312haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sphinx                    7.2.6                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
spyder                    6.0.0b2                  pypi_0    pypi
spyder-kernels            3.0.0b7                  pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack-data                0.6.3                    pypi_0    pypi
superqt                   0.6.7                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
textdistance              4.6.1                    pypi_0    pypi
three-merge               0.1.1                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.12.4                   pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
traitlets                 5.14.2                   pypi_0    pypi
types-python-dateutil     2.9.0.20240316           pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
tzlocal                   5.2                      pypi_0    pypi
ujson                     5.9.0                    pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  4.0.0                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.6.0                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
websockets                12.0                     pypi_0    pypi
whatthepatch              1.0.5                    pypi_0    pypi
wheel                     0.41.2          py312haa95532_0
widgetsnbextension        4.0.11                   pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h8cc25b3_0
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
```

**Comment by victorsanchezarevalo** [comment] 2024-07-30 14:20
I still have the same problem with 6.0 beta3

**Comment by victorsanchezarevalo** [comment] 2024-07-30 14:20
> @Chuck321123, are you still having this issue in 6.0 beta3?

I still have the same problem with 6.0 beta3

**Comment by tlstevenson** [comment] 2024-09-04 16:38
I wonder if this is related to the latest issue of plots not showing when using external python environments: https://github.com/spyder-ide/spyder/issues/22420

**Comment by tflidd** [comment] 2024-09-09 11:16
I have python 3.10.7, and I had the same symptoms after updating to spyder 6. In other software, matplotlib still worked. I updated a number of potentially related packages (everything with qt5). In the end I updated IPython from 8.22.1 to 8.27.0 and now it works again.

Downgrading IPython to 8.22.1 breaks it again.

**Comment by tlstevenson** [comment] 2024-09-09 18:03
>I updated a number of potentially related packages (everything with qt5)

Could you share what else you updated? I tried updating just IPython and I still couldn't get plots to show

**Comment by tflidd** [comment] 2024-09-10 07:42
I updated some upfront: matplotllib 3.9.2, pandas 2.2.2, numpy 1.26.4, and spyder 6.0.0. It's a native python environment and everything installed with pip (no additional package manager).

This is when I ran into problems, and I updated these on top:

| Package                       | old    | new     |
|:------------------------------|:-------|:--------|
| alabaster                     | 0.7.12 | 1.0.0   |
| bcrypt                        | 4.0.0  | 4.2.0   |
| colorama                      | 0.4.5  | 0.4.6   |
| comtypes                      | 1.1.14 | 1.4.6   |
| docutils                      | 0.19   | 0.21.2  |
| ipython                       | 8.22.1 | 8.27.0  |
| jupyter                       | 1.0.0  | 1.1.1   |
| mypy-extensions               | 0.4.3  | 1.0.0   |
| networkx                      | 2.8.7  | 3.3     |
| paramiko                      | 3.4.0  | 3.4.1   |
| patool                        | 1.12   | 2.4.0   |
| polars                        | 1.5.0  | 1.6.0   |
| pyarrow                       | 11.0.0 | 17.0.0  |
| Pygments                      | 2.13.0 | 2.18.0  |
| PyQt5                         | 5.15.7 | 5.15.11 |
| PyQtWebEngine                 | 5.15.6 | 5.15.7  |
| PySide6                       | 6.7.0  | 6.7.2   |
| PySide6_Addons                | 6.7.0  | 6.7.2   |
| PySide6_Essentials            | 6.7.0  | 6.7.2   |
| Rtree                         | 1.0.0  | 1.3.0   |
| setuptools                    | 68.2.2 | 74.1.2  |
| shiboken6                     | 6.7.0  | 6.7.2   |
| Sphinx                        | 5.2.1  | 8.0.2   |
| sphinxcontrib-serializinghtml | 1.1.5  | 2.0.0   |
| SQLAlchemy                    | 1.4.41 | 2.0.34  |
| sympy                         | 1.11.1 | 1.13.2  |
| watchdog                      | 2.1.9  | 5.0.2   |
| wheel                         | 0.37.1 | 0.44.0  |

**Comment by victorsanchezarevalo** [comment] 2024-09-10 10:15
I still have the same problem, It does not work.

**Comment by tflidd** [comment] 2024-09-11 13:29
I updated matplotlib-inline from `0.1.6` to `0.1.7`, and it broke again. Reverting back to 0.1.6 makes it work again. A bit strange, people here with problems seem to use `0.1.6`.

However, using IPython directly, both versions work with:
```
import matplotlib.pyplot as plt
%matplotlib qt5
plt.plot([0, 1, 2])
```

In spyder I get this error:

```
%matplotlib qt5
Warning: Cannot change to a different GUI toolkit: qt5. Using qt instead.
Traceback (most recent call last):

  Cell In[2], line 1
    get_ipython().run_line_magic('matplotlib', 'qt5')

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:2480 in run_line_magic
    result = fn(*args, **kwargs)

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\magics\pylab.py:103 in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\spyder_kernels\console\shell.py:96 in enable_matplotlib
    enabled_gui, backend = super().enable_matplotlib(gui)

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3681 in enable_matplotlib
    configure_inline_support(self, backend)

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib_inline\backend_inline.py:205 in configure_inline_support
    select_figure_formats(shell, cfg.figure_formats, **cfg.print_figure_kwargs)

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\pylabtools.py:297 in select_figure_formats
    raise ValueError("supported formats are: %s not %s" % (gs, bs))

ValueError: supported formats are: 'jpg','svg','jpeg','png2x','png','retina','pdf' not 'g','p','n'
```
it is the same if I use `qt` instead of `qt5`.
No idea if this helps, or just adds to the confusion.

**Comment by ccordoba12** [comment] 2024-09-14 00:51
Hi folks, we found the cause of this problem: a mix of incompatible Matplotlib and Matplotlib-inline versions, possibly with IPython in the mix too, as you found out.

Please checkout this comment for our latest findings: https://github.com/spyder-ide/spyder/issues/22420#issuecomment-2345629849

**Comment by ccordoba12** [comment] 2024-09-14 00:52
Please continue the discussion on that issue. I'm going to close this one to consolidate everything in a single place.

**Closed by ccordoba12** 2024-09-14 00:52 UTC
Labels: status:Awaiting Followup
