### ISSUE TITLE
Setting for Spyder Code Completion Issue

### ISSUE THREAD

**Issue by xieyiqun884886** [spyder-ide/spyder#21750] opened 2024-01-31 11:07 UTC
### Issue Report Checklist
* [ √] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ √] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ √] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ √] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ √] Tried basic troubleshooting (if a bug/error)
    * [√ ] Restarted Spyder
    * [ √] Reset preferences with ``spyder --reset``
    * [ √] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ √] Tried the other applicable steps from the Troubleshooting Guide
* [ √] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
"I currently have two main issues.

1.Why is it that sometimes I cannot trigger the automatic code completion, for example?"
![image](https://github.com/spyder-ide/spyder/assets/91885572/1aabe002-6fcc-4e45-bc68-8c1a5abab1db)
I want to input the 'index' method, but it's not displaying.
![image](https://github.com/spyder-ide/spyder/assets/91885572/6a55ad95-46f5-4c49-8fba-869a654fa2ae)
After entering 'd,' there is a display, but the 'index' method is not shown. I feel very confused about this.
2.My second issue is why the autocomplection displayed at the top every time is not the optimal suggestion but rather the content I entered itself.
![image](https://github.com/spyder-ide/spyder/assets/91885572/b2b41397-9618-4fcc-91ff-e97370eb95ea)
![image](https://github.com/spyder-ide/spyder/assets/91885572/25099ed8-2af0-49f7-ab3d-dcbf890f2d3d)
![image](https://github.com/spyder-ide/spyder/assets/91885572/53bcbfbb-5a1c-4bdd-a40b-7d3c8ce2eebd)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder 6.0.0a3
* Python version: 3
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```

```

**Comment by ccordoba12** [comment] 2024-02-02 01:25
Hey @xieyiqun884886, thanks for reporting. This is basically a duplicate of issue #21660, so I'm going to close it in favor of that one.

We'll try to fix it before Spyder 6 final is released.

**Closed by ccordoba12** 2024-02-02 01:25 UTC
