### ISSUE TITLE
Cannot use backslash as comment shortcut

### ISSUE THREAD

**Issue by quarkup** [spyder-ide/spyder#2287] opened 2015-03-30 18:50 UTC
Cannot use Backslash as a shortcut, eg: Ctrl+Backslash (\\) to comment out lines (meta/windows + \ also does not work).

Framework: spyder 2.3.4, python 3.4.3, windows (x64).~

Possibly due to the fact that '\' is a special symbol with programming needs special attention (\ -> \\\\ ?).

Best regards

**Comment by ccordoba12** [comment] 2015-03-31 16:36
We use `Ctrl+1` to comment lines. I don't know if `Ctrl+\` is allowed by Qt or not, but someone else would need to check that and (if possible) implement the necessary changes in our source code :-)

I see this as very low priority right now.

**Comment by age** [comment] 2015-04-18 16:29
This was previously reported in #478. Basically, you can manually specify Ctrl+/ in spyder.ini, which breaks the settings menu but Spyder functions, or try using the patch I proveded back at google code. I may eventually file a proper pull request with my patch.

**Comment by ccordoba12** [comment] 2015-04-18 21:03
Thanks, I'll take a look at your patch for beta1.

**Comment by ccordoba12** [comment] 2015-04-18 21:03
Sorry for not mentioning it but I'm closing this one as duplicate of issue #478

**Closed by ccordoba12** 2015-04-18 21:03 UTC
Labels: duplicate, enhancement, help wanted, Settings
