### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by lygbird** [spyder-ide/spyder#6752] opened 2018-03-13 21:18 UTC
cannot connect to kernel of ipython console

**Comment by CAM-Gerlach** [comment] 2018-03-14 00:03
No substantive information was provided with this report; however, it is most likely a duplicate of #6627 or perhaps an issue with ``jupyter_client`` we just discovered earlier. To fix it, run ``conda update pyzmq tornado ipykernel jupyter_client=5.2.2`` from the Anaconda Prompt/Terminal/shell (Windows/Mac/Linux) in the ``conda`` environment that Spyder is installed in. Thanks.

**Closed by CAM-Gerlach** 2018-03-14 00:03 UTC
Labels: resolution:Invalid
