### ISSUE TITLE
Colon is automatically given after a one line if-statement.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1448] opened 2015-02-17 19:19 UTC
_From [kram...@gmail.com](https://code.google.com/u/114411737424392267610/) on 2013-06-19T08:29:38Z_

Normally when you create an if-statement you do it like so:

if a == b:
    doSomething()

When I forget to put the colon at the end of the if-line, Spyder automatically adds the colon. Although I don't need this feature a lot, it works perfectly well.
Sometimes however, I use a lot of if-statements, so I make them shorter so that they only use one line:

if a == b: doSomething()

When I now hit enter it adds a colon at the end of this line so that it looks like this:

if a == b: doSomething():

When running this it obviously throws an error, which is quite inconvenient. The problem is that this happens a lot in my workflow. 

What steps will reproduce the problem?

 1. Write a one line if-statement (for example: "if 1 == 1: print 1")
2. Hit enter

What is the expected output?
Nothing, just for the cursor to move to the next line.

What do you see instead?
It adds a colon, which throws an error when running the program. What version of the product are you using? On what operating system? Spyder 2.2.0 on Ubuntu 12.04

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1448_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:19
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:59:43Z_

**Labels:** Cat-Editor MS-v2.4

**Comment by Nodd** [comment] 2015-04-08 12:20
Duplicate of https://github.com/spyder-ide/spyder/issues/872

**Closed by Nodd** 2015-04-08 12:20 UTC
Labels: 2–5 stars, bug, Editor
