### ISSUE TITLE
can't start spyder using chinese user name in windows

### ISSUE THREAD

**Issue by oijqws** [spyder-ide/spyder#19226] opened 2022-08-30 00:51 UTC
if my user name is following, I can't start spyder
C:\Users\小小\

**Comment by ccordoba12** [comment] 2022-08-30 15:00
Hey @oijqws, thanks for reporting. Unfortunately, the information you posted is not enough to help you.

Please let us know:

1. How did you install Spyder? In other words, did you use Anaconda, Conda-forge, Pip or our Windows installer?
2. What's your Spyder version?

**Comment by oijqws** [comment] 2022-09-01 03:15
Hi, CCoordoba

Thank you for your reply
I have tried to install using Anaconda and Windows installer. Install is OK, but when spyder is starting, I can see the booting windows, however it just quit.  I am using 5.1.5, I believe other version would have same issue.
To reproduce, you are create a new user 小小 then login and start spyder.

Thanks
James

**Comment by ccordoba12** [comment] 2022-09-01 14:27
Ok, I see, thanks for the extra information.

@dalthviz, could you create a new user in your machine as described by @oijqws and check if Spyder starts for you in that case?

**Comment by dalthviz** [comment] 2022-09-01 17:37
I got a message error related with Qt when creating a new account with `小小` as name after installing the Windows standalone version on that new account. Also, when checking the cmd or powershell, I can see that the system is not properly parsing the user name characters (since my regional config doesn't support that encoding).

Also @oijqws could you run from the Anaconda prompt `spyder --debug-info verbose` and post here the log that gets generated in the console to check if it is the same I got:

```



```

**Comment by oijqws** [comment] 2022-09-02 03:10
thanks for helping

**Comment by oijqws** [comment] 2022-09-02 03:27
hope we can assign spyder default folder during install.

**Comment by ccordoba12** [comment] 2022-09-02 03:42
@oijqws, as @dalthviz said, please open the Anaconda Prompt and run this command

    spyder --debug-info verbose --debug-output file

After Spyder crashes, look for a file called `spyder-debug.log` in the directory where you ran that command and upload it here.

That way we'll able to tell users what they need to do sort out this issue.

**Comment by dalthviz** [comment] 2022-09-02 15:59
Just in case, checked installing using the `for all users` option which doesn't use the user folder for the intallation path and Spyder launches

**Comment by oijqws** [comment] 2022-09-03 01:21
failed upload, here is errors

2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese prober hit error at byte 3
2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese prober hit error at byte 2
2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese prober hit error at byte 3
2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 2
2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> CP949 Korean prober hit error at byte 3
2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 2
2022-09-03 09:15:51,906 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 2
2022-09-03 09:15:51,929 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese prober hit error at byte 3
2022-09-03 09:15:51,929 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese prober hit error at byte 2
2022-09-03 09:15:51,929 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese prober hit error at byte 3
2022-09-03 09:15:51,929 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 2
2022-09-03 09:15:51,930 [DEBUG] [chardet.charsetprober] -> CP949 Korean prober hit error at byte 3
2022-09-03 09:15:51,930 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 2
2022-09-03 09:15:51,930 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 2
2022-09-03 09:15:51,937 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese prober hit error at byte 44
2022-09-03 09:15:51,937 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese prober hit error at byte 45
2022-09-03 09:15:51,937 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 44
2022-09-03 09:15:51,937 [DEBUG] [chardet.charsetprober] -> CP949 Korean prober hit error at byte 45
2022-09-03 09:15:51,937 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 44
2022-09-03 09:15:51,937 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 44
2022-09-03 09:15:53,143 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 11
2022-09-03 09:15:53,143 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 11
2022-09-03 09:15:53,143 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 11
2022-09-03 09:15:53,163 [DEBUG] [spyder.api.config.mixins] -> <spyder.plugins.editor.plugin.Editor object at 0x00000237D5857940> is observing underline_errors in section editor
2022-09-03 09:15:53,165 [DEBUG] [spyder.api.config.mixins] -> <spyder.plugins.editor.plugin.Editor object at 0x00000237D5857940> is observing underline_errors in section editor
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese prober hit error at byte 28
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese prober hit error at byte 13
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese prober hit error at byte 16
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 13
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> CP949 Korean prober hit error at byte 28
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 13
2022-09-03 09:15:53,269 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 13
2022-09-03 09:15:53,274 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese prober hit error at byte 105
2022-09-03 09:15:53,275 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese prober hit error at byte 105
2022-09-03 09:15:53,275 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese prober hit error at byte 105
2022-09-03 09:15:53,275 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 105
2022-09-03 09:15:53,275 [DEBUG] [chardet.charsetprober] -> CP949 Korean prober hit error at byte 105
2022-09-03 09:15:53,275 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 105
2022-09-03 09:15:53,275 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 105

**Comment by oijqws** [comment] 2022-09-04 15:08
I have tried install using All User, error is same above.

**Comment by ccordoba12** [comment] 2022-09-04 18:43
@oijqws, is that the full contents of `spyder-debug.log`?

**Comment by oijqws** [comment] 2022-09-06 05:53
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/9493621/spyder-debug.log)

**Comment by dalthviz** [comment] 2022-09-06 17:12
Are you using a custom interpreter @oijqws ? The last lines from the log show the IPython Console kernel trying to start using `C:\\app\\Python39\\python.exe`:

```
2022-09-03 09:15:54,259 [INFO] [spyder.app.mainwindow] -> *** End of MainWindow setup ***
2022-09-03 09:15:54,365 [DEBUG] [asyncio] -> Using proactor: IocpProactor
2022-09-03 09:15:54,411 [DEBUG] [traitlets] -> Instantiating kernel 'Python 3 (Spyder)' with kernel provisioner: local-provisioner
2022-09-03 09:15:54,489 [INFO] [spyder.plugins.ipythonconsole.utils.kernelspec] -> Kernel command: ['C:\\app\\Python39\\python.exe', '-m', 'spyder_kernels.console', '-f', '{connection_file}']
2022-09-03 09:15:54,490 [DEBUG] [traitlets] -> Starting kernel: ['C:\\app\\Python39\\python.exe', '-m', 'spyder_kernels.console', '-f', 'C:\\Users\\СС\\AppData\\Roaming\\jupyter\\runtime\\kernel-039f4bc72a1c.json']
```

I guess then what you are experiencig is that after that gets logged Spyder crashes, right?

Could you submit here a gif or video to understand what you are experiencing better? Let us know!

**Comment by oijqws** [comment] 2022-09-08 04:00
here is steps
1. double click Spyder 
2. spyder banner show up
3. spyder ide interface show up
4. everything disappear.

Yes, I have created another account and use custom interpreter now. However the default one also fail.

**Comment by ccordoba12** [comment] 2022-09-14 23:29
@oijqws, from your debug file, it seems you're running Spyder from a Windows account called `CC`, so this doesn't seem caused by Chinese characters in your user name. Furthermore, there are no errors displayed on that file, so I don't know how we could help you here.

**Comment by oijqws** [comment] 2022-09-16 04:34
this is the issue, my user name is "小小" but spyder think it is CC, then it cause problem. I do not have account CC. [dalthviz](https://github.com/dalthviz) has reproundced this issue already, right?

**Comment by ccordoba12** [comment] 2022-09-19 15:07
> this is exactly the issue, my user name is "小小" but spyder think it is CC, then it cause problem

Ok, thanks a lot for the clarification.

> [dalthviz](https://github.com/dalthviz) has reproundced this issue already, right?

No, he hasn't been able to do it yet.

> If you create a new account in windows (copy and paste"小小" or with any Chinese) spyder would fail to start.

That's what @dalthviz tried to do but unfortunately Windows has encoding problems to read those characters.

**Comment by ccordoba12** [comment] 2022-09-19 15:13
@dalthviz, I think you could do two additional things to test Spyder with @oijqws's username:

1. Change your system's locale to use either an encoding that supports Chinese or utf-8, as described [here].(https://helpcenter.nshift.com/hc/en-us/articles/360016886479-Errors-caused-by-Windows-10-Unicode-UTF-8-encoding).
2. Create a directory with @oijqws's username in your regular user account and use the Spyder option `--conf-dir` to create its config files on that directory. That would be equivalent to create a user named `小小`, but easier.

**Comment by dalthviz** [comment] 2022-09-20 16:29
I checked using the beta option for utf-8 in the regional settings for Windows but the same issue reported above shows up: `...application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

Just in case, maybe the `all users` install in my case worked for the `小小` user I created since my admin user doesn't have special characters in its name?

**Comment by ccordoba12** [comment] 2022-09-23 02:41
Ok, thanks @dalthviz for checking. Since we can't test further, please install Spyder for all users. That should fix your problem.

**Closed by ccordoba12** 2022-09-23 02:41 UTC
Labels: status:Awaiting Followup
