### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by koog1000** [spyder-ide/spyder#7284] opened 2018-06-12 16:04 UTC
### What steps will reproduce the problem?

I tries loading in a ~20MB tab delimited file into the variable explorer

### Traceback
```python-traceback
MemoryError
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.14
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-06-12 21:51
Thanks for reporting. This seems like a duplicate of issue #5830, which will be fixed in our next version (3.3.0), to be released in a couple of weeks.

**Closed by ccordoba12** 2018-06-12 21:51 UTC

**Comment by CAM-Gerlach** [comment] 2018-06-14 19:21
You can test it out to see by ``clone``ing this github repo and running ``python boostrap.py`` from the ``spyder`` directory to run a dev build of Spyder.

**Comment by koog1000** [comment] 2018-06-14 21:04
Couldn't check it out (my work may have github blocked) but I downloaded the master branch and tried running... same problem. It isn't really a pressing issue for me so I'm not concerned about it. Hopefully the next release fixes it though.

**Comment by CAM-Gerlach** [comment] 2018-06-14 23:32
I tried loading a 32MB and 120 MB CSV using the latest Spyder 3.3dev, and everything worked, other than it being extremely slow (minutes) to both load the dialog and process after clicking the next button (on a decently specced laptop with a 4 core/8 thread i7-3630QM, 24GB of DDR3-1600 and a fairly high end SATA SSD (850 Evo).
