### ISSUE TITLE
IPython Console syntax highlighting

### ISSUE THREAD

**Issue by zoquda** [spyder-ide/spyder#3490] opened 2016-10-01 13:48 UTC
## Description of your problem

It seems that in Spyder 3.0 by default the Editor and the IPython Console use different color schemes for syntax highlighting. Personally I find this a bit confusing on the eyes and brain.

<img width="466" alt="syntax_highlighting" src="https://cloud.githubusercontent.com/assets/20889585/19014214/2358943e-87e7-11e6-803c-2dab7a239fab.PNG">

Thus far all my efforts to change the color scheme for IPython Console syntax highlighting have been unsuccessful. I was unable to find an option to change the IPython Console color scheme in the Spyder Preferences, and using the magic command `colors` in the IPython Console did not seem to have any effect.

Would it be possible to implement the following two options in Spyder, and to set one of them as default?
1. Applying the Editor's color scheme to the IPython Console.
2. Applying no color scheme to the IPython Console (i.e. plain black text, like Spyder 2 used to have).

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5
* Operating system: Windows 10

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-01 18:36
Thanks for reporting. This is a duplicate of issue #916.

**Closed by ccordoba12** 2016-10-01 18:36 UTC
