### ISSUE TITLE
Debug arrow does not show when running script with "re-run last script" command

### ISSUE THREAD

**Issue by gabrielclow** [spyder-ide/spyder#11003] opened 2019-12-10 16:54 UTC
## Problem Description

Debug line arrow does not show when running with "re-run last script" shortcut.

### What steps reproduce the problem?

1. Run file in debug mode, normal arrow:
![debugarrowa](https://user-images.githubusercontent.com/9113853/70549990-d8196580-1b53-11ea-9d91-0ded3b0aa242.png)
2. Finish or stop and run again with "re-run last script" shortcut
3. Arrow doesn't show up through the rest of the run
![debugarrowb](https://user-images.githubusercontent.com/9113853/70550014-e5ceeb00-1b53-11ea-869c-342e829cf12a.png)

### What is the expected output? What do you see instead?

I expect to see the debug line arrow when re running the script through the shortcut.

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Win 10

### Dependencies

cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

**Comment by ccordoba12** [comment] 2019-12-10 17:20
Duplicate of #10538

**Closed by ccordoba12** 2019-12-10 17:20 UTC
