### ISSUE TITLE
Required to save all open files even if those files are not imported from, they only contain comments, or are completely empty

### ISSUE THREAD

**Issue by GalacticStarfish** [spyder-ide/spyder#6881] opened 2018-04-01 20:03 UTC
## Problem Description
Required to save all open files even if those files are not imported from, they only contain comments, or are completely empty.

### What steps will reproduce the problem?
1. set key binding  to default setting if not already
2. open a valid script (previously debugged and working) in the editor (herein referred to as 'the first file')
3. press Ctrl-N to open a new file (herein referred to as 'the second file')
4. run the first file.
5. Observe that the "save file" dialogue opens

### What is the expected output? What do you see instead?

I expect the program to run, and if it imports from an unsaved/temp file, and import error will be thrown at runtime.

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.4 32bits
* Qt: 5.9.3
* PyQt: 5.9.2
* Operating System: Windows 

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2018-04-01 22:19
Did you make changes to the second file?

**Comment by ccordoba12** [comment] 2018-04-01 22:19
I mean, before running the first file.

**Comment by CAM-Gerlach** [comment] 2018-04-02 00:56
Duplicate of #5970 , essentially, and a couple others...can we just go ahead with what we've seemed to have come to consensus on over there, and skip saving never-saved/new files when running a file that isn't that one, since they couldn't possibly be referenced in the file at hand and it can cause major user annoyance?

**Closed by CAM-Gerlach** 2018-04-02 00:56 UTC
Labels: status:Awaiting Followup
