### ISSUE TITLE
issue on opening array element

### ISSUE THREAD

**Issue by simba28** [spyder-ide/spyder#8726] opened 2019-02-07 15:08 UTC
## Description

**What steps will reproduce the problem?**

when i try to open any array element

**What is the expected output? What do you see instead?**
the array

**Please provide any additional information below**

  File "C:\Users\Simba\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\Users\Simba\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.16.1 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2019-02-07 15:15
Duplicate of issue #8582. It'll be fixed in our next version (3.3.3).

**Closed by ccordoba12** 2019-02-07 15:15 UTC
