### ISSUE TITLE
Problem in running spyder

### ISSUE THREAD

**Issue by avikla** [spyder-ide/spyder#6253] opened 2018-01-19 20:37 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2412, in run_file
    self.re_run_file()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2432, in re_run_file
    self.save_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2020, in save_all
    self.get_current_editorstack().save_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1805, in save_all
    if self.data[index].editor.document().isModified():
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-19 20:57
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by csabella** [comment] 2018-01-19 21:03
Duplicate of #5996, but still need additional info.

**Comment by ccordoba12** [comment] 2018-01-19 21:05
Thanks @csabella!

**Closed** 2018-01-19 21:06 UTC
Labels: resolution:Duplicate

**Comment by CAM-Gerlach** [comment] 2018-01-20 01:41
@avikla Please provide what is requested in this thread, and as much as possible of the items listed in the relevant [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include)of the Spyder Troubleshooting Guide, over on the #5996 thread to help this issue get fixed; thanks.
