### ISSUE TITLE
tried to commit a file after initializing the git repositiory

### ISSUE THREAD

**Issue by KVSSetty** [spyder-ide/spyder#7877] opened 2018-09-11 10:54 UTC
### What steps will reproduce the problem?

Had some spyder project in a directory with user designed modules and packages, then initialzed a git repo to that directory using init command, because of that a new blank  repo created, and two new context commands appeared in the context menu when right clicked a file in the project explorer of spyder and wanted to commit that file,this message appeared.
 I am on windows 10

### Traceback
```python-traceback
  File "C:\Users\kvssetty.SELP025\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 393, in <lambda>
    self.vcs_command(fnames, 'commit')
  File "C:\Users\kvssetty.SELP025\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 825, in vcs_command
    for path in sorted(fnames):
TypeError: 'bool' object is not iterable
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-09-11 15:36
Thanks for reporting. This is a duplicate of issue #7733 and it'll be fixed in our next version.

**Closed by ccordoba12** 2018-09-11 15:36 UTC
