### ISSUE TITLE
TypeError: tabText(self, int) when moving plugin tabs

### ISSUE THREAD

**Issue by JulienSt** [spyder-ide/spyder#5813] opened 2017-11-21 20:09 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

```
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 110, in eventFilter
    self.tab_moved(event)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 146, in tab_moved
    self.move_tab(from_index, to_index)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 158, in move_tab
    from_plugin = self._get_plugin(from_index)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 62, in _get_plugin
    tab_text = self.dock_tabbar.tabText(index).replace('&', '')
TypeError: tabText(self, int): argument 1 has unexpected type 'NoneType'
```

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0

**Comment by CAM-Gerlach** [comment] 2017-11-22 00:29
Something related to naming and moving around tabs somewhere in the UI, it seems. Others may know more specifically, but you describe what you were doing around the time the problem occurred?

**Comment by ccordoba12** [comment] 2017-11-22 15:38
This happens when moving plugin tabs to reorganize them (e.g. moving the IPython console to be next to the History Log).

I really don't understand why this error happens, but we can catch it and simply pass if it shows up.

**Comment by CAM-Gerlach** [comment] 2017-11-23 00:55
@ccordoba12  Is the help wanted tag for just catching the error, or tracing it more thoroughly?

**Comment by ccordoba12** [comment] 2018-01-06 21:29
Just catching the error.

**Comment by CAM-Gerlach** [comment] 2018-01-06 22:08
I can take a look...

**Comment by ccordoba12** [comment] 2018-01-06 22:12
Great, thanks!

**Comment by CAM-Gerlach** [comment] 2018-01-06 22:15
I can't actually reproduce it, but I can at least catch the error and just ``pass`` it if that'll do for now...not sure how much more I can do without actually seeing what's going on...

**Comment by ccordoba12** [comment] 2018-01-06 22:32
Yep, that's fine for now. I don't understand how this error appears 
either, but the best thing we can is to catch it and pass on it.

**Comment by JulienSt** [comment] 2018-01-07 18:49
Should I close this Issue? It didn't happen to me again; I just thought posting the error would help in development of Spyder, but you seem to need the discussion thread.

**Comment by ccordoba12** [comment] 2018-01-07 18:50
No, please leave it open. We'll make a simple fix for this error because it happens for other people as well.

**Comment by JulienSt** [comment] 2018-01-07 18:52
Alright, good luck with the fix!

**Comment by CAM-Gerlach** [comment] 2018-01-07 21:42
> I just thought posting the error would help in development of Spyder

It does, thank you! It should be first in my (long) queue as soon as I get my current PRs straightened out, and it should definitely make ``3.2.7``.

**Comment by ccordoba12** [comment] 2018-01-25 21:34
@dalthviz, please take a look at this one.

**Comment by CAM-Gerlach** [comment] 2018-01-25 21:37
@ccordoba12 I've got a straightforward fix done that was awaiting #6286 for the tests, but if @dalthviz can actually reproduce it properly in real use and fix it more comprehensively than I'm all for it.

**Comment by ccordoba12** [comment] 2018-01-25 21:50
Sorry, I thought you forgot about this one. If you have a PR ready, please submit it.

**Comment by CAM-Gerlach** [comment] 2018-01-25 23:47
No worries. Its at the top of the queue and I can make sure its in by tonight.

**Closed** 2018-02-03 14:55 UTC
Labels: component:Plugins, tag:Ui, type:Bug
