### ISSUE TITLE
why input no work

### ISSUE THREAD

**Issue by javicas85** [spyder-ide/spyder#19151] opened 2022-08-23 17:50 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by javicas85** [comment] 2022-08-23 17:51
Why input not workin?

**Comment by dalthviz** [comment] 2022-08-24 15:51
Hi @javicas85 not sure more of your setup context since you didn't basic info as your OS, Spyder version, Python version, dependencies, installation method, etc. However, since seems like you have problems with the `input` function, most probably yoru issue is related/a duplicate of #18947 

Also, please provide your setup info here and in any future issues you want to open, otherwise is quite difficult to help :/

Please check the metioned issue and let us know if something there helps!

**Comment by bociub** [comment] 2022-08-26 00:12
Hi
I just installed the latest version of Anaconda and this snipet crashes the Spider instantly :
x = input("choice")
print(x) 

win10 64bit
python 3.9.12
spyder ide 5.1.5

Thanks.

**Comment by bociub** [comment] 2022-08-26 07:51
Update: I uninstalled then I rebooted my system then reinstalled (the latest release of) Anaconda.(According to troubleshoot guide) (https://www.anaconda.com/products/distribution) . 

Still same: A single line of code 'input()' crashes the Spider instantly. 
Then I repeted again but before the reinstall I deleted every file or folder from my folder which contained *conda*, *python* or *spider*. 

After the third intallation the problem is still same: instant crash even in a virgin version of spider.

**Comment by bociub** [comment] 2022-08-26 08:33
updateing anaconda navigator and spider from terminal to the latest version solved this strange problem.

**Comment by dalthviz** [comment] 2022-08-26 16:14
Hi @bociub as described in my first comment the error with the input function is related with an old version of Spyder (Spyder 5.1.5) that's why updating helped you and then most probably this is a duplicate of #18947

**Comment by dalthviz** [comment] 2022-09-27 18:38
Closing as a duplicate of #18947

**Closed by dalthviz** 2022-09-27 18:38 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
