### ISSUE TITLE
Bundled rope version is causing Spyder to crash

### ISSUE THREAD

**Issue by sdbaylis** [spyder-ide/spyder#2779] opened 2015-10-23 16:33 UTC
When I launch Spyder, rope throws an exception (attached screenshot).  Some details on my install:

Windows 7 Professional 64bit
Python 3.4 amd64
I've installed the relevant PySide and PyQt4 libraries.

Any help hugely appreciated!
![spyder_launch_error](https://cloud.githubusercontent.com/assets/1876829/10699072/1ea45b3e-79ac-11e5-9967-8dd5f045df2e.jpg)

**Comment by ccordoba12** [comment] 2015-10-23 19:42
You're using the wrong version of rope for your Python version. Please run

    pip uninstall rope
    pip install rope_py3k

**Comment by sdbaylis** [comment] 2015-10-23 20:11
Thanks Carlos, much appreciated. I'll give that a go.
All the best,
Stuart.

Stuart Baylis
+44 7969 623438

**Comment by sdbaylis** [comment] 2015-10-24 13:29
Hi Carlos.  That didn't work I'm afraid.  When I try to uninstall rope, I get the error below.  
When I install rope_py3k, I still get the same error when launching Spyder.
![2015-10-24_142852](https://cloud.githubusercontent.com/assets/1876829/10710659/8f71408e-7a5b-11e5-9480-424226c22825.jpg)

**Comment by ccordoba12** [comment] 2015-10-24 13:53
Well, I don't know how you installed rope. You need to look in your `site-packages` directory and remove rope manually.

**Comment by vishniakou** [comment] 2015-11-06 00:56
I had the same problem. I solved it by deleting the following directory:
Python34\Lib\site-packages\spyderlib\utils\external\rope

Now spyder opens up okay, but shows that jedi and rope are not installed. Have not yet looked into that,

**Comment by sdbaylis** [comment] 2015-11-06 09:35
Quite right, that's sorted it.  It looks like the Pyhton3 AMD64 version of Spyder that I installed came bundled with an incorrect version of rope. 

Got Spyder working now - great development environment!

**Comment by ccordoba12** [comment] 2015-11-06 14:56
@vishniakou, thanks for finding the cause of this problem. We'll fix it for Spyder 3.0.

**Comment by Nodd** [comment] 2015-11-06 16:44
@ccordoba12 Is this not tested by travis/appveyor ? I didn't look precisely but I thought external dependencies were tested.

**Comment by ccordoba12** [comment] 2015-11-06 20:18
I think this problem is caused by our Windows exe installers (which are untested) because they install a copy of `rope` in `utils/external`.

I hope this would be fixed when we stop to distribute those installers and only use wheels.

**Comment by ccordoba12** [comment] 2015-11-26 03:29
This is fixed now in pull request #2831 and it's going to be part of Spyder 3.0

**Closed by ccordoba12** 2015-11-26 03:29 UTC
Labels: bug, Editor

**Comment by eduamf** [comment] 2018-02-24 22:26
Spyder 3.2.6 is not recognizing the jedi version 0.11. 

I recomend you to install the jedi version 0.10.0

```
pip uninstall jedi
pip install jedi==0.10.0
```

Now it's ok

![image](https://user-images.githubusercontent.com/23469103/36635709-9fdf1674-1998-11e8-9a96-1f01ef851f6a.png)

**Comment by CAM-Gerlach** [comment] 2018-03-19 01:46
@eduamf We appreciate you trying to help. However, are you aware the issue you are responding to was closed almost two and a half years ago, likely has nothing to do with what you posted, and any issue is not, in fact "Spyder not recognizing jedi version 0.11" but rather incompatibility between certain third-party, non-Spyder packages? Furthermore, the commands given would likely break most users' installs who use the recommended Anaconda distribution, both due to installing via ``pip`` and because ``jedi`` 0.10 is not compatible with the current version of ``parso``, 0.11, which breaks Spyder's completion, introspection and help and causes continuous error messages when trying to use them.

**Comment by eduamf** [comment] 2018-03-19 07:21
?Thank you!

________________________________
De: C.A.M. Gerlach <notifications@github.com>
Enviado: domingo, 18 de março de 2018 22:46
Para: spyder-ide/spyder
Cc: Eduardo Antonio Mello Freitas; Mention
Assunto: Re: [spyder-ide/spyder] Bundled rope version is causing Spyder to crash (#2779)


@eduamf<https://github.com/eduamf> We appreciate you trying to help. However, are you aware the issue you are responding to was closed almost two and a half years ago, likely has nothing to do with what you posted, and any issue is not, in fact "Spyder not recognizing jedi version 0.11" but rather incompatibility between certain third-party, non-Spyder packages? Furthermore, the commands given would likely break most users' installs who use the recommended Anaconda distribution, both due to installing via pip and because jedi 0.10 is not compatible with the current version of parso, 0.11, which breaks Spyder's completion, introspection and help and causes continuous error messages when trying to use them.

-
