### ISSUE TITLE
Indentation after a line with [] and {} is reset

### ISSUE THREAD

**Issue by vladimirg** [spyder-ide/spyder#3214] opened 2016-06-08 15:52 UTC
## Indentation in the editor breaks after lines with [] and {} in them

1. Create a new file (or open an existing one).
2. Start a new indentation block (with, say, a new function definition).
3. Add something innocuous, like 'print "hello world"', press the Return button.
4. The next line will be at the correct level on indentation.
5. Then add something like 'print []', press the Return button..
6. The next line will not be indented at all. This seems to be regardless of the level of indentation of the previous line.

## Versions and main components

* Spyder Version: 3.0.0.dev0 (installed using 'conda install -c spyder-ide spyder==3.0.0b3')
* Python Version: 2.7.11, 64-bit, Qt 5.3.1, PyQt 5.3.1
* Operating system: Mac OS X  10.11.5

## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.0 (OK)
nbconvert >=4.0 :  4.0.0 (OK)
numpy >=1.7     :  1.10.1 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
psutil >=0.3    :  3.3.0 (OK)
pyflakes >=0.5.0:  1.0.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.4    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)

**Comment by Nodd** [comment] 2016-06-11 19:41
I can reproduce it with python2 but not with python3. I suppose that it's because python3 requires parenthesis for print.
The problem is present in python3 if the parenthesis are omitted but since the syntax is invalid I wouldn't count it as a bug.

**Comment by vladimirg** [comment] 2016-06-12 19:14
This happens with lines without print, such as:

z = []

As a bonus, list comprehensions, also behave funny. This line:

z = [i for i in range(5)]

*increases* indentation (I think it has to do with the parentheses of the range call, this also happens if I use a hard-coded tuple, for example), while this line:

z = []

decreases it (as 'print []' does). Should I open a separate bug about this?

Unfortunately I can't help with Python 3.

**Comment by Nodd** [comment] 2016-06-12 20:11
Thanks for the clarification.
For list comprehension I think it's because of `for`.

**Comment by jpoeppel** [comment] 2016-09-01 13:33
Not sure if you already have this covered, but what I found interesting is that the indentation works properly when one presses Enter inside the list such as:
```
tmp = [1,2,
       _
```
(_ should symbolize where the indentation jumps to when pressing Enter at the end of the first line).

**Comment by ccordoba12** [comment] 2016-09-01 14:55
@jitseniesen, would you like to take a look at this one?

**Comment by jitseniesen** [comment] 2016-09-01 19:00
I'll self-assign but it will take a while.

**Comment by jitseniesen** [comment] 2016-10-24 14:14
Closing because apparently fixed by #3576.

**Closed by jitseniesen** 2016-10-24 14:14 UTC
Labels: Comp-Editor, Type-Bug
