### ISSUE TITLE
Feature request: shortcut to open console for different environment

### ISSUE THREAD

**Issue by thangleiter** [spyder-ide/spyder#20326] opened 2023-01-07 18:38 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

## Description
I have started using the standalone installer of Spyder in order to reduce the amount of 'Spyders' I have flying around in different conda environments. However, I miss being able to quickly switch to a console in a different environment. 

I realize I can switch the default interpreter for *all* consoles in the setting (or launch a kernel externally and connect to it), but having, say, a new entry below `New console (default settings)` in the Hamburger menu of the console would be great for this. Something like `New console (different environment)`, or even extending this to arbitrary custom settings.

## Versions

* Spyder version: 5.4.1 (standalone)

**Comment by ccordoba12** [comment] 2023-01-08 16:42
Hey @thangleiter, thanks for reporting. This is basically a duplicate of issue https://github.com/spyder-ide/ux-improvements/issues/10 and we'll fix it in Spyder 6, to be released in the second half of the year.

**Closed by ccordoba12** 2023-01-08 16:42 UTC
