### ISSUE TITLE
Spyder leaves python workers running after exit

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#15953] opened 2021-06-29 21:55 UTC
## Problem Description

Running Spyder from PS or CMD leaves python workers running in background after exiting, and they can accumulate over time

### What steps reproduce the problem?

1. Launch Spyder
2. Click OK to any prompts, notice various python workers running
3. Exit Spyder, threads are still running
4. Closing the terminal has no effect.

Please see attached video

https://user-images.githubusercontent.com/30508983/123872507-6863fa80-d8f2-11eb-8286-104378e765f1.mp4

### What is the expected output? What do you see instead?

Workers started by Spyder should terminate on exit.

### Paste Traceback/Error Below (if applicable)

```python-traceback

None

```

## Versions

* Spyder version: 5.0.4 None
* Python version: 3.8.10 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.24.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by ccordoba12** [comment] 2021-06-30 03:29
Hey @eafpres, thanks for reporting. Those processes should be killed after Spyder is closed, so I don't understand what happens in your case.

@dalthviz, could you test if Spyder installed by pip has this problem for you on Windows?

**Comment by dalthviz** [comment] 2021-06-30 17:49
@ccordoba12 @eafpres checking this for me some process take some more time to be removed but at the end are effectively removed:

![process](https://user-images.githubusercontent.com/16781833/124007649-d801e480-d9db-11eb-83fb-28aa3483e703.gif)

Although I'm running from an Anaconda prompt in an env with spyder installe using pip, so maybe there is a subtle difference there @ccordoba12 ?

**Comment by eafpres** [comment] 2021-06-30 18:06
@dalthviz Unfortunately for me they do not close.  Opening another Spyder creates new ones, so over time they pile up.  My env was made with venv in PowerShell and everything 100% pip installed.

I ran from the same env except launching on a cmd.exe window, and the result is the same.

Maybe conda does something that cmd and powershell don't?

I have moved away from conda/Anaconda so this is my main setup now.

**Comment by dalthviz** [comment] 2021-06-30 18:24
Not totally sure @eafpres :/ For now, what happen if you try to use our installer: https://github.com/spyder-ide/spyder/releases/latest? The only thing there is that you will need to use the preferences to choose the interpreter as explained here: http://docs.spyder-ide.org/5/faq.html#using-existing-environment

Let us know if that helps!

**Comment by eafpres** [comment] 2021-06-30 18:34
I was unclear how to use the installer along with venvs.  It seems to install globally on the machine, but when I created a venv after, spyder wasn't in there.  So I removed all versiosns, created the venv first, then pip installed Spyder.  Can you tell me how to add Spyder to a venv when using the installer?

**Comment by dalthviz** [comment] 2021-06-30 18:55
>Can you tell me how to add Spyder to a venv when using the installer?

Well the idea with the installer is for Spyder to be isolated from any environment (venv, conda or other type). Following this, with the installer you don't at Spyder to a venv or your python installation, instead it gives you a way to execute a self-contained Spyder that then you can connect with your venvs by setting the interpreter preference inside Spyder as explained in the link I put above: http://docs.spyder-ide.org/5/faq.html#using-existing-environment (in this way Spyder can use the packages you have in your venvs)

>Another thing you might investigate--on my system, one of those orphan processes held open the file handle to the project directory. I found by accident I was trying to rename the dir after existing Spyder, and it said it was open in another process. I closed those two and then I could rename. Not sure if that helps.

Thanks for the info :+1: maybe this processes could be related then with the LSP @ccordoba12 ?

**Comment by ccordoba12** [comment] 2021-07-01 15:47
> Thanks for the info +1 maybe this processes could be related then with the LSP @ccordoba12 ?

I think this could really be the cause of the problem @eafpres is having! If the LSP server has a handle to the project directory before Spyder is closed, then it shouldn't be possible to automatically kill it (which is what we are doing now).

@dalthviz, could you verify what happens when Spyder is closed with an open project?

**Comment by dalthviz** [comment] 2021-07-01 16:02
@ccordoba12 tried with a project but I experience a similar behavior (at the end some process take a little bit more time to end but they end)

**Comment by ccordoba12** [comment] 2021-07-13 01:44
Ok, I'm going to close this one for one because we were unable to reproduce this problem.

@eafpres, I'd say this could be caused by something specific to your computer. Or perhaps by starting Spyder in Powershell (although I really doubt that).

**Closed by ccordoba12** 2021-07-13 01:44 UTC
Labels: status:Awaiting Followup

**Comment by eafpres** [comment] 2021-12-01 02:29
FYI, this issue went away with version 5.2.0 in Windows 10!

**Comment by ccordoba12** [comment] 2021-12-01 02:48
Well, that's good news! Perhaps the improvements we made to improve responsiveness in the editor help to not leave the server hanging.
