### ISSUE TITLE
Feature request: file explorer enhancement

### ISSUE THREAD

**Issue by JoeXinfa** [spyder-ide/spyder#8353] opened 2018-12-03 04:55 UTC
The file explorer tree sets the current item to be the current tab/file in the Editor. The tree would highlight the current item and jump to it, when user switches to another Editor tab. This feature is helpful when package at hand is big or users need navigate between packages, meaning the file explorer tree is very tall.

BTW, I'm a big fan of spyder and use it daily. Thanks a ton to the developers!

**Comment by ccordoba12** [comment] 2018-12-04 02:50
Thanks for reporting.

@jnsebgosselin, I think the behavior in master is different, right?

**Comment by jnsebgosselin** [comment] 2018-12-04 03:15
It is the Outline Explorer that we've reworked in Spyder4 and that works now mostly like that. I do not think that we have touch to the file explorer though.

**Comment by ccordoba12** [comment] 2018-12-04 04:09
@JoeXinfa, do you refer to the File Explorer or the Outline Explorer?

**Comment by JoeXinfa** [comment] 2018-12-04 05:08
I meant the File Explorer.

I see if I select a method in the Outline Explorer,  the Editor jumps to the line of that method, which is very handy. But the reverse does not work; if I move to a line in the Editor, the Outline Explorer does not jump to the method of that line. My request is for the latter behavior for the File explorer.

**Comment by jnsebgosselin** [comment] 2018-12-04 13:00
So if we are talking about the *File explorer*, how would you handle files that are not located under the same tree? For example

- a file opened in the editor located in C:/some/folder
- a file opened in the editor located in D:/some/folder

What would be the expected behavior of the File Explorer when switching from one file to the other in the Editor?

**Comment by ccordoba12** [comment] 2018-12-11 16:08
Closing because we don't understand how to implement this.

@JoeXinfa, you're welcome to submit a pull request with the behavior you'd like to see.

**Closed by ccordoba12** 2018-12-11 16:09 UTC
Labels: status:Awaiting Followup
