### ISSUE TITLE
After ipython restart the console does not evaluate commands

### ISSUE THREAD

**Issue by Diti24** [spyder-ide/spyder#2972] opened 2016-02-09 19:45 UTC
## Description

**What steps will reproduce the problem?**

1. Restart ipython console
2. try to send a command lide a=3
3. press enter 

**What is the expected output? What do you see instead?**
Would expect ipython to report result, but what happens is that it remains in a sort of editing mode
In [1]: a=3
   ...: 
   ...: 
   ...: 
   ...: 
   ...: 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.4.3
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.1 (OK)
zmq >=2.1.11       :  15.1.0 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
pandas >=0.13.1    :  0.16.2 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.3.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  0.25.1 (OK)

```

**Comment by ccordoba12** [comment] 2016-02-10 00:19
This is a duplicate of issue #2696

**Closed by ccordoba12** 2016-02-10 00:19 UTC
Labels: Duplicate
