### ISSUE TITLE
CWD does not persist across Spyder sessions

### ISSUE THREAD

**Issue by hiccup7** [spyder-ide/spyder#4984] opened 2017-08-17 12:48 UTC
The current working directory is not restored after restarting Spyder.

**What steps will reproduce the problem?**
1. Tools > Preferences > Current working directory = The current working directory (default)
2. Change the CWD to C:\some_folder
3. Close Spyder
4. Run Spyder

**What is the expected output? What do you see instead?**
Expected: CWD=C:\some_folder
Instead: CWD=$HOME$
C:\some_folder is available as one of the items in the drop-down for the CWD.

**Please provide any additional information below**
This used to work with Spyder versions before 3.2.0

## Versions and main components

* Spyder Version: 3.2.0 or 3.2.1
* Python Version: 3.5.3 or 3.5.4
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: 64-bit Windows 8.1
* Dependencies: included in WinPython-64bit 3.5.4.0Qt5rc

**Comment by ccordoba12** [comment] 2017-08-17 14:27
Thanks for reporting. We'll take a look at it in 3.2.2.

**Comment by ccordoba12** [comment] 2017-08-18 21:47
This is a duplicate of issue #4879.

**Comment by ccordoba12** [comment] 2017-08-29 00:23
Sorry, this was not a duplicate of that issue, but we'll fix it in 3.2.2

**Comment by ccordoba12** [comment] 2017-08-29 00:33
Sorry, I forgot that we decided Spyder will always set the CWD after startup at your home directory. If you want to use a particular directory, please use *the following directory* option.

**Closed by ccordoba12** 2017-08-29 00:33 UTC
Labels: component:IPython Console, type:Bug
