### ISSUE TITLE
Scipy.stats is not imported 

### ISSUE THREAD

**Issue by eltabbal** [spyder-ide/spyder#6489] opened 2018-02-21 15:41 UTC
## Description
when trying to import stats from scipy it produces the following error, 

  File "<ipython-input-34-b66176eb2d0a>", line 1, in <module>
    import scipy.stats

  File "/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py", line 343, in <module>
    from .stats import *

  File "/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 169, in <module>
    import scipy.special as special

  File "/anaconda3/lib/python3.6/site-packages/scipy/special/__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal

  File "/anaconda3/lib/python3.6/site-packages/scipy/special/_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

ImportError: cannot import name '_ellipsoid'

**What steps will reproduce the problem?**

1.  SpyderVersion 3.2.6 / conda environment/ Mac system 
2. just try to import 

**What is the expected output? What do you see instead?**
importing the stats from scipy. 

  File "<ipython-input-34-b66176eb2d0a>", line 1, in <module>
    import scipy.stats

  File "/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py", line 343, in <module>
    from .stats import *

  File "/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 169, in <module>
    import scipy.special as special

  File "/anaconda3/lib/python3.6/site-packages/scipy/special/__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal

  File "/anaconda3/lib/python3.6/site-packages/scipy/special/_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

ImportError: cannot import name '_ellipsoid'

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-21 19:15
I think this is a duplicate of issue #5299. Please take a look at that issue for a possible fix.

**Comment by eltabbal** [comment] 2018-02-24 09:51
I reinstalled SciPy package and the problem was solved

**Comment by ccordoba12** [comment] 2018-02-24 12:50
Great! Thanks for letting us know about it.

**Closed by ccordoba12** 2018-02-24 12:50 UTC
Labels: status:Awaiting Followup
