### ISSUE TITLE
`TypeError: __new__() missing 1 required positional argument: 'hidden'` when connecting to remote kernel

### ISSUE THREAD

**Issue by HitachiAIL** [spyder-ide/spyder#21605] opened 2023-12-11 15:55 UTC
I followed all the steps here:
http://docs.spyder-ide.org/current/panes/ipythonconsole.html?highlight=ssh#connect-to-a-remote-kernel

But then, when I import the json, it fails to start, and pop the "issue reporter" window.

I have been connecting to remote serve using this approach in the past (almost 1yr ago), but I have no idea why it fails now.

### Traceback
```python-traceback
  File "C:\Users\aohaz\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 959, in create_client_for_kernel
    self._create_client_for_kernel(connection_file, hostname, sshkey,
  File "C:\Users\aohaz\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1789, in _create_client_for_kernel
    shellwidget.check_spyder_kernel()
  File "C:\Users\aohaz\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 256, in check_spyder_kernel
    self.silent_exec_method(code)
  File "C:\Users\aohaz\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 618, in silent_exec_method
    self._request_info['execute'][msg_id] = self._ExecutionRequest(msg_id,
TypeError: __new__() missing 1 required positional argument: 'hidden'
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  8.7.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  4.16.0 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.4.4 (OK)
numpydoc >=0.6.0                :  1.5.0 (OK)
paramiko >=2.4.0                :  2.8.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.0 (OK)
pygments >=2.0                  :  2.16.1 (OK)
pylint >=1.0                    :  2.14.5 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.3               :  5.3.2 (OK)
qtpy >=1.5.0                    :  2.2.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  65.5.0 (OK)
sphinx >=0.6.6                  :  5.0.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  23.2.0 (OK)

# Optional:
cython >=0.21                   :  0.29.32 (OK)
matplotlib >=2.0.0              :  3.6.2 (OK)
numpy >=1.7                     :  1.23.4 (OK)
pandas >=1.1.1                  :  1.4.4 (OK)
scipy >=0.17.0                  :  1.9.3 (OK)
sympy >=0.7.3                   :  1.11.1 (OK)
```

**Comment by dalthviz** [comment] 2023-12-11 21:01
Hi @HitachiAIL! Seems like this is a duplicate of https://github.com/spyder-ide/spyder/issues/17452. In the linked issue there are some instructions regarding installing a specific QtConsole version, which could help you prevent the problem. Also, seems like you are using a quite out of date Spyder version (you are using 4.2.5 and the latest release is 5.5.0) out of curiosity, is there any reason why you prefere to stick with such an old Spyder version?

Let us know if the info above helps and any feedback you could have!

**Comment by dalthviz** [comment] 2024-07-06 00:11
Closing as a duplicate of #17452

**Closed by dalthviz** 2024-07-06 00:11 UTC
Labels: resolution:Duplicate, component:IPython Console, status:Awaiting Followup
