### ISSUE TITLE
Terminal not showing

### ISSUE THREAD

**Issue by dhorangic** [spyder-ide/spyder#19102] opened 2022-08-18 22:18 UTC
## Problem Description
Whenever I open Spyder (whether using base or custom env) the terminal will not show up, see image.
<img width="695" alt="Screen Shot 2022-08-17 at 9 05 36 PM" src="https://user-images.githubusercontent.com/71292086/185504343-bc856f13-cd46-43c4-a056-2790fc677d07.png">

### What is the expected output? What do you see instead?
Either a solid black or solid white screen is seen in the terminal window. I have restarted Spyder a number of times.

## Versions

* Spyder version: 5.3.2
* Python version: 3.9.5 (64-bit)
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: MacOS Monterey 12.5.1

### Dependencies
Dirac is my machine name. All of these are base env at /Users/dirac/opt/miniconda3/bin/python:
brotlipy 0.7.0
bzip2 1.0.8
ca-certificates 2022.07.19
certifi 2022.6.15
cffi 1.15.1
charset-normalizer 2.0.4
conda 4.13.0
conda-package-handling 1.8.1
cryptography 37.0.1
idna 3.3
libcxx 12.0.0
libffi 3.3
ncurses 6.3
openssl 1.1.1q
pip 22.1.2
pycosat 0.6.3
pycparser 2.21
pyopenssl 22.0.0
pysocks 1.7.1
python 3.10.4
python.app 3
readline 8.1.2
requests 2.28.1
ruamel_yaml 0.15.100
setuptools 61.2.0
sqlite 3.39.2
tk 8.6.12
tqdm 4.64.0
tzdata 2022a
urllib3 1.26.11
wheel 0.37.1
xz 5.2.5
yaml 0.2.5
zlib 1.2.12

**Comment by dhorangic** [comment] 2022-08-19 17:37
Hi - just to update on the problem, I deleted Spyder and re-installed. The terminal began working. Then I downloaded miniconda, created an environment, installed some packages on the env (numpy, pandas, scikit-image, and pytorch) and switched to using that env's interpreter. Re-opened Spyder and now the terminal no longer works. 
This time when I go back to the default interpreter I get a working terminal though.
But now I'm having problems, I can't use any of the environments I create because 1) the terminal won't work and 2) whenever I update the env to the latest available version of the spyder-kernels package (2.3.2 through conda-forge) the kernel runs but then crashes with this error message whenever I try to import torch:
/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/scripts/conda-activate.sh: line 18: 10226 Abort trap: 6           $CONDA_ENV_PYTHON -m spyder_kernels.console -f $SPYDER_KERNEL_SPEC


Fatal Python error: Aborted


Main thread:
Current thread 0x0000000110e81600 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/dirac/Documents/miniconda3/envs/env1/lib/python3.10/site-packages/torch/__init__.py", line 197 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/var/folders/nr/wd230rdd1_d4whmf5qmg3krm0000gn/T/ipykernel_10226/4265195184.py", line 1 in <module>


Restarting kernel...

See image:
<img width="797" alt="Screen Shot 2022-08-19 at 2 35 21 PM" src="https://user-images.githubusercontent.com/71292086/185675806-5cce70fd-48ec-4918-9b2c-ffb54efc1ea5.png">

**Comment by dalthviz** [comment] 2022-08-19 19:09
Hi @dhorangic thank you for your feedback! Regarding the terminal (from the `Terminal` pane), what happens if you try to create a new one? Is it blank too? 

Regarding the activation of the environments from a console instance when importing `torch` (from the IPython Console pane) , could you share the conda list env output, please?

And could you run Spyder in debug mode (`Files > Restart in debug mode > Verbose`) and share the .log file generated (which should be located at the `.spyder-py3` directory in your user home directory) here?

I was unable to reproduce these issues with the standalone installer on Windows so maybe is something only happening with the standalone MacOS installer 🤔

Just in case, the env I used as custom interpreter to test:


<details>

```

# Name                    Version                   Build  Channel
aom                       3.4.0                h0e60522_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
blosc                     1.21.1               h74325e0_3    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.3.0                hdf67494_0    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cffi                      1.15.1          py310hcbf9ad4_0    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0          py310he2412df_0    conda-forge
dask-core                 2022.8.0           pyhd8ed1ab_0    conda-forge
dav1d                     1.0.0                h8ffe710_1    conda-forge
debugpy                   1.6.3           py310h8a704f9_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
fsspec                    2022.7.1           pyhd8ed1ab_0    conda-forge
future                    0.18.2          py310h5588dad_5    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
imagecodecs               2022.8.8        py310hb4e33f4_4    conda-forge
imageio                   2.21.1             pyhfa7a67d_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.1             pyh025b116_0    conda-forge
ipython                   7.33.0          py310h5588dad_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310h5588dad_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
krb5                      1.19.3               hc8ab02b_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libavif                   0.10.1               h8ffe710_1    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.13                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_4    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.39.2               h8ffe710_1    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.4.0                h92677e6_3    conda-forge
libuv                     1.44.2               h8ffe710_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0           py310hcf6e17e_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.5              pyhd8ed1ab_0    conda-forge
ninja                     1.11.0               h2d74725_0    conda-forge
numpy                     1.23.2          py310h8a5b91a_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   3.0.5                h8ffe710_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3           py310hf5e1058_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h52929f7_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1           py310he2412df_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.10.5          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.10.2          cpu_py310habb1308_0
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0           py310h2873277_1    conda-forge
pywin32                   303             py310he2412df_0    conda-forge
pyyaml                    6.0             py310he2412df_4    conda-forge
pyzmq                     23.2.1          py310h73ada01_0    conda-forge
scikit-image              0.19.3          py310hf5e1058_1    conda-forge
scipy                     1.9.0           py310h578b7cb_0    conda-forge
setuptools                65.0.2          py310h5588dad_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
spyder-kernels            2.3.2           py310h5588dad_0    conda-forge
sqlite                    3.39.2               h8ffe710_1    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tifffile                  2022.8.12          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310he2412df_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       1.0.0                h0e60522_1    conda-forge
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge

```

</details>

Also, pinging @mrclary maybe he could have some ideas to further debug these issues.

**Comment by mrclary** [comment] 2022-08-19 19:41
@dhorangic, I think this is a macOS installer issue.
Just to reiterate:
1. Please post the external conda environment that you are using.
```bash
$ conda list
```
2. Are you running with an Intel or Arm processor?
```bash
$ arch  # i386 or arm64?
```
This may be important to distinguish as I only have two machines to test on: macOS 11.6.8 with x86-64 and 12.5 with M1.

**Comment by mrclary** [comment] 2022-08-19 19:48
@dhorangic, sorry, two more things.
1. When you say you reinstalled Spyder, did you re-download the 5.3.2 dmg from GitHub, mount the dmg, and replace the Spyder.app? Or did you mount a previously downloaded dmg and replace the Spyder.app?
2. Did you download "Spyder-Lite.dmg" or "Spyder.dmg"?

**Comment by dhorangic** [comment] 2022-08-19 23:56
To answer first reply:
1. If I try to create a new one, it is also blank whenever this error occurs. 
2. Conda list env output is here:
[packages1.pdf](https://github.com/spyder-ide/spyder/files/9385816/packages1.pdf)
3. Ran spyder in debug mode, then using the same env here^ encountered both issues (terminal not showing up & kernel crashing/restarting whenever torch is imported), I cannot find the log file, navigated to my user home directory and it isn't showing up (at least not under a .spyder-py3 file, could it be saved under something else?)

To answer second reply:
1. Posted list as a pdf above - would you also like to see the packages installed on the base environment or the default? I however don't know how to get a list of the base env in miniconda3 or the Spyder app dependencies, would I do this w/ pip or pkg_resources?
2. I am running with an Intel processor (i386), here are the specs: 1.4 GHz Quad-Core Intel Core i5

To answer third reply:
1. I re-downloaded the 5.3.2 dmg from the Spyder website and then mounted it, the previously downloaded dmg I deleted a while ago.
2. I downloaded 'Spyder.dmg'

**Comment by mrclary** [comment] 2022-08-20 02:35
Unfortunately, I am unable to reproduce your issues.
- The Terminal plugin seems to be working for me, although it is sluggish and has a long typing latency. This is a known issue.
- I was able to create an external environment for pytorch and import it without issue in the IPython Console.
- My company updated my operating system today, so I was able to test with macOS 12.5.1 on Intel processor.
- Below are my specs, external environment list, and a gif illustrating the successful use of IPython Console and Terminal plugin.

System specs:
* macOS 12.5.1 with Intel processor
* Spyder version: 5.3.2 8b5ac96d6 (standalone)
* Python version: 3.9.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 21.6.0

Creating the environment:
```bash
$ mamba create -n issue-19102 pytorch pandas scikit-image spyder-kernels
```
<details><summary>pytorch environment</summary>

```
# packages in environment at /Users/rclary/opt/mambaforge/envs/issue-19102:
#
# Name                    Version                   Build  Channel
aom                       3.4.0                hb486fe8_1    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h97e831e_3    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-blosc2                  2.3.0                had5f71b_0    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
cffi                      1.15.1          py310h96bbf6e_0    conda-forge
cfitsio                   4.1.0                h2c97ad1_0    conda-forge
charls                    2.3.4                he49afe7_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2          py310h1961e1f_2    conda-forge
dask-core                 2022.8.1           pyhd8ed1ab_0    conda-forge
dav1d                     1.0.0                hac89ed1_1    conda-forge
debugpy                   1.6.3           py310h154be8b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h3f81eb7_0    conda-forge
fsspec                    2022.7.1           pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
imagecodecs               2022.8.8        py310h4c5f5bb_4    conda-forge
imageio                   2.21.1             pyhfa7a67d_0    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
ipython                   7.33.0          py310h2ec42d9_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310h2ec42d9_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
krb5                      1.19.3               hb98e516_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libavif                   0.10.1               hac89ed1_1    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libcurl                   7.83.1               h23f1065_0    conda-forge
libcxx                    14.0.6               hce7ea42_0    conda-forge
libdeflate                1.13                 h775f41a_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           10_4_0_h97931a8_25    conda-forge
libgfortran5              11.3.0              h082f757_25    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libnghttp2                1.47.0               h5aae05b_1    conda-forge
libopenblas               0.3.21          openmp_h1027af7_0    conda-forge
libpng                    1.6.37               h5481273_4    conda-forge
libprotobuf               3.20.1               hfa58983_1    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.39.2               h5a3d3bf_1    conda-forge
libssh2                   1.10.0               h47af595_3    conda-forge
libtiff                   4.4.0                h5e0c7b4_3    conda-forge
libwebp-base              1.2.4                h775f41a_0    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.12               hfe4f2af_2    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h860c996_928    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.5              pyhd8ed1ab_0    conda-forge
ninja                     1.11.0               h1b54a9f_0    conda-forge
numpy                     1.23.2          py310hf910466_0    conda-forge
openjpeg                  2.5.0                h5d0d7b0_1    conda-forge
openssl                   3.0.5                hb81d4ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3           py310h3099161_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h54af1cc_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1           py310h6c45266_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.10.5          hdd68b96_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.12.1          cpu_py310h32957a8_0    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0           py310h7f5fb2b_1    conda-forge
pyyaml                    6.0             py310h1961e1f_4    conda-forge
pyzmq                     23.2.1          py310hcabbbd4_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
scikit-image              0.19.3          py310hc61ff8f_1    conda-forge
scipy                     1.9.0           py310h70707f4_0    conda-forge
setuptools                65.1.0          py310h2ec42d9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h6db0672_2    conda-forge
snappy                    1.1.9                h6e38e02_1    conda-forge
spyder-kernels            2.3.2           py310h2ec42d9_0    conda-forge
sqlite                    3.39.2               hd9f0692_1    conda-forge
tbb                       2021.5.0             hbb4e6a2_1    conda-forge
tifffile                  2022.8.12          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h6c45266_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wurlitzer                 3.0.2              pyhd8ed1ab_2    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zfp                       1.0.0                hb9aa9fd_1    conda-forge
zlib-ng                   2.0.6                hac89ed1_0    conda-forge
zstd                      1.5.2                hfa58983_4    conda-forge
```
</details>

![issue-19102](https://user-images.githubusercontent.com/9618975/185725693-db5df972-266e-46d7-9194-c3e393b32926.gif)

I see from your environment list that you primarily use the defaults channel. Can you try creating the environment and installing all packages using the conda-forge channel? Use the flag `-c conda-forge`.

**Comment by dhorangic** [comment] 2022-08-20 19:19
Hi, so I need either a working spyder-kernels or a working terminal ideally to get my work done - I will try reinstalling Spyder again + creating an environment and installing all the packages with conda-forge to see if that fixes anything
If this does not work - could we try to troubleshoot the kernel crashing issue alone? Seems like there should be some error file generated somewhere there, an error message at least is generated vs. just the terminal not appearing

**Comment by mrclary** [comment] 2022-08-21 06:52
> Hi, so I need either a working spyder-kernels or a working terminal ideally to get my work done - I will try reinstalling Spyder again + creating an environment and installing all the packages with conda-forge to see if that fixes anything
> If this does not work - could we try to troubleshoot the kernel crashing issue alone? Seems like there should be some error file generated somewhere there, an error message at least is generated vs. just the terminal not appearing

I understand how frustrating it is when something prevents you from getting your work done. We will do our best to help you fix this issue.

In addition to building the environment with the conda-forge channel (can you provide the _exact_ command you use to build the environment?), you may try removing any old Spyder configuration files: either delete or rename the `~/.spyder-py3` directory.

Can you also provide a list of your environment variables? From Terminal.app
```bash
$ printenv
```
Just copy and paste the result into a comment.

**Comment by dhorangic** [comment] 2022-08-21 15:42
Hi - thank you so much for the conda-forge idea!
I deleted both spyder/miniconda3 and reinstalled both (miniconda via shell script, spyder via .dmg again). Then I installed all the same packages as before on a new environment, but all with conda-forge instead. 
The kernel no longer crashes and I can run things!
The terminal still won't show up but I can use the kernel for my work - should we keep trying to debug the terminal issue?
This is the terminal now (with the new env):
<img width="615" alt="Screen Shot 2022-08-21 at 12 41 54 PM" src="https://user-images.githubusercontent.com/71292086/185799126-da6efee8-5e4d-49b7-8621-620b544b485c.png">
But I can get along fine with just the kernel working!

**Comment by dhorangic** [comment] 2022-08-21 15:44
Also, here is the `printenv` output:
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/nr/wd230rdd1_d4whmf5qmg3krm0000gn/T/
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Kfr4spqNZA/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=2E47984A-650C-4260-973F-2FBAAB21566A
SHELL=/bin/zsh
HOME=/Users/dirac
LOGNAME=dirac
USER=dirac
PATH=/Users/dirac/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
SHLVL=1
PWD=/Users/dirac
OLDPWD=/Users/dirac
CONDA_EXE=/Users/dirac/miniconda3/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/dirac/miniconda3/bin/python
CONDA_SHLVL=0
LANG=en_US.UTF-8
_=/usr/bin/printenv

**Comment by mrclary** [comment] 2022-08-21 16:04
@dhorangic, I'm glad the IPython Console is working now. Is there a `spyder_terminal_err.log` file in your home folder? If so, you can drag-and-drop it into a comment here.

Also, if you do not see the spyder debug log file (`/Users/<users>/.spyder-py3/spyder-debug.log`), it may be that Spyder failed to restart in debug mode. You may try one of the following:
- If you have a bash (or zsh) startup file, you may temporarily add a line `SPYDER_DEBUG=3`.
- Or you may start Spyder from Terminal.app as follows
  ```bash
  $ SPYDER_DEBUG=3 /Applications/Spyder.app/Contents/MacOS/Spyder
  ```
  If your Spyder.app is located somewhere else, change the above path accordingly.

Either of these will cause Spyder to startup in debug mode and produce the debug file.

To be frank, I do not use the Terminal plugin because of it's high typing latency, and prefer to use Terminal.app along side Spyder.

**Comment by dhorangic** [comment] 2022-08-21 16:44
Hi - checked home folder again, there is no .spyder-py3 folder still
Started Spyder from Terminal in debug mode
Yes I noticed the latency, terminal plugin works w/ the default interpreter but is slow like you said
Found the spyder_terminal_err.log file in my home folder, here it is:
[spyder_terminal_err.log](https://github.com/spyder-ide/spyder/files/9389588/spyder_terminal_err.log)

**Comment by mrclary** [comment] 2022-08-21 17:01
> Hi - checked home folder again, there is no .spyder-py3 folder still

Ahhh, sorry, I neglected to mention that because it starts with a ".", .spyder-py3 is a hidden folder. You can toggle hidden file visibility in Finder with the keyboard shortcut ⌘⇧. (command + shift + .)

**Comment by dhorangic** [comment] 2022-08-21 17:10
Thank you, I found the debug file in the .spyder-py3 folder
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/9389646/spyder-debug.log)

**Comment by mrclary** [comment] 2022-08-21 17:36
Well, since the Terminal plugin is now working, I did not expect to see anything in the spyder-debug.log or spyder_terminal_err.log. Hopefully, this intermittent behavior will be fixed in the coming months. Sorry for inconvenience and hope that Terminal will not fail on you again and you can be productive with just the IPython Console if it does.

I'm going to close this issue, but if the problem resurfaces, feel free to reopen it.

**Closed by mrclary** 2022-08-21 17:36 UTC
Labels: type:Bug, OS:MacOS, status:Awaiting Followup, tag:Installer
