### ISSUE TITLE
Console right click

### ISSUE THREAD

**Issue by DrSpooglemon** [spyder-ide/spyder#12944] opened 2020-06-03 16:28 UTC
### What steps will reproduce the problem?

Right clicking on the conole in order to copy text.

### Traceback
```python-traceback
  File "/usr/local/lib/python3.6/dist-packages/qtconsole/console_widget.py", line 2456, in _custom_context_menu_requested
    menu = self._context_menu_make(pos)
  File "/usr/local/lib/python3.6/dist-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 603, in _context_menu_make
    menu = super(ShellWidget, self)._context_menu_make(pos)
  File "/usr/local/lib/python3.6/dist-packages/qtconsole/rich_jupyter_widget.py", line 104, in _context_menu_make
    menu = super(RichJupyterWidget, self)._context_menu_make(pos)
  File "/usr/local/lib/python3.6/dist-packages/qtconsole/frontend_widget.py", line 293, in _context_menu_make
    menu = super(FrontendWidget, self)._context_menu_make(pos)
  File "/usr/local/lib/python3.6/dist-packages/qtconsole/console_widget.py", line 1072, in _context_menu_make
    menu = QtGui.QMenu(self)
AttributeError: module 'qtpy.QtGui' has no attribute 'QMenu'
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.6.9
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-53-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.2 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment] 2020-06-03 16:40
Hi @DrSpooglemon this is a duplicate of #11740

Please update `QtConsole` (the current version has a fix for the issue). Also, seems like you are using `pip` so something like `pip install -U qtconsole` should be enough to do the update :)

**Closed by dalthviz** 2020-06-03 16:40 UTC
