### ISSUE TITLE
Can't open notebook in Windows after plugin install

### ISSUE THREAD

**Issue by shaq** [spyder-ide/spyder#8824] opened 2019-02-21 20:46 UTC
### What steps will reproduce the problem?

View > Panes > Notebook > Right-Click in Notebook Pane > Open

 

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 437, in open_notebook
    self.create_new_client(filename=filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 329, in create_new_client
    server_info = nbopen(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\utils\nbopen.py", line 56, in nbopen
    server_info = find_best_server(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\utils\nbopen.py", line 40, in find_best_server
    servers = [si for si in notebookapp.list_running_servers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\utils\nbopen.py", line 40, in <listcomp>
    servers = [si for si in notebookapp.list_running_servers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1836, in list_running_servers
    info = json.load(f)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.1 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-22 10:40
Duplicate of spyder-ide/spyder-notebook#120. We still don't know how to fix it, sorry.

**Closed by ccordoba12** 2019-02-22 10:40 UTC
