### ISSUE TITLE
Spyder halted and I was forced to shut it down

### ISSUE THREAD

**Issue by morawi** [spyder-ide/spyder#7589] opened 2018-07-31 10:09 UTC
### What steps will reproduce the problem?

I was running some experiments on the GPU, then, Spyder hlated and did not response. I forced it to shut down. Then, I tried to launch it but it gave a black screen and nothing showed. I had to do unisnall and install to bring it back to normal.

### Traceback
```python-traceback
  File "/home/malrawi/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.4.0-130-generic

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-31 15:03
Thanks for reporting. This is a duplicate of issue #7403 and it'll be fixed in our next version.

**Closed by ccordoba12** 2018-07-31 15:03 UTC
