### ISSUE TITLE
raise TimeoutError(timeout_msg)

### ISSUE THREAD

**Issue by shlpu** [spyder-ide/spyder#12440] opened 2020-04-22 06:43 UTC
### What steps will reproduce the problem?

triggered=lambda: self.debug_command("exit"))
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2443, in debug_command
    self.main.ipyconsole.pdb_execute(command, hidden=True, echo_code=False)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 601, in pdb_execute
    sw.set_pdb_echo_code(echo_code)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 321, in set_pdb_echo_code
    self.call_kernel(interrupt=True).set_pdb_echo_code(state)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "D:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 45.000683069229126
WARNING:traitlets:kernel died: 45.000683069229126

### Traceback
```python-traceback
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 572, in <lambda>
    triggered=lambda: self.debug_command("exit"))
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2443, in debug_command
    self.main.ipyconsole.pdb_execute(command, hidden=True, echo_code=False)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 601, in pdb_execute
    sw.set_pdb_echo_code(echo_code)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 321, in set_pdb_echo_code
    self.call_kernel(interrupt=True).set_pdb_echo_code(state)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "D:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 45.000683069229126
WARNING:traitlets:kernel died: 45.000683069229126
WARNING:traitlets:kernel died: 45.00068521499634
WARNING:traitlets:kernel died: 45.00068426132202
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.0.3 (OK)
numpy >=1.7                    :  1.18.2 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-04-22 16:20
Duplicate of #11889

**Comment by ccordoba12** [comment] 2020-04-22 16:21
This error should not happen if you close the current console and open a new one.

**Closed by ccordoba12** 2020-04-22 16:20 UTC
