### ISSUE TITLE
Cannot direct Spyder 5.0 to conda-env - Spyder-kernels dependency issue

### ISSUE THREAD

**Issue by doublezz10** [spyder-ide/spyder#15126] opened 2021-04-05 22:56 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In fresh install using Standalone Installer on macOS Big Sur, Spyder-kernels is not working correctly. I can successfully run code in the default env that comes with Spyder, but I cannot change to other Conda environments to use other packages: whether the env was made before or after installing Spyder. I have a Conda-env successfully working in Spyder 4.2.1. I'm afraid to Conda update Spyder in that env at risk of disrupting my day-to-day workflow.

### What steps reproduce the problem?

1. Download .dmg installer ('keep both')
2. Open Spyder (1st below error message appears)
3. Point Spyder to Python interpreter in previously working Conda-env
4. Restart Spyder (2nd error message appears)

### Paste Traceback/Error Below (if applicable)

https://imgur.com/a/0UmopAT
https://imgur.com/a/TIBsa0v

## Versions

* Spyder version: 5.0.0 None
* Python version: 3.9.2 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  54.1.2 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK) -- not sure why this is not ok
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by steff456** [comment] 2021-04-05 23:24
Hi @doublezz10,

This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

Thanks for reporting!

**Closed by steff456** 2021-04-05 23:24 UTC

**Comment by ccordoba12** [comment] 2021-04-05 23:26
> but I cannot change to other Conda environments to use other packages: whether the env was made before or after installing Spyder

This will be fixed once the Anaconda team releases new packages for spyder-kernels 2.0.1

**Comment by doublezz10** [comment] 2021-04-06 00:17
thanks all. did not see that issue when I was searching as I typed 'Spyder kernels' rather than 'spyder-kernels'

glad to hear it should be resolved soon

**Comment by ccordoba12** [comment] 2021-04-06 00:42
No prob @doublezz10. Also, if you want a very stable and robust Spyder, please stay with Spyder 4. Spyder 5 will take a couple of months to be stabilized and in the meantime we'll keep maintaining Spyder 4.
