### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by guangyu-shi** [spyder-ide/spyder#14673] opened 2021-01-31 19:51 UTC
### What steps will reproduce the problem?

Follow the Contributing guide:

$ conda create -n spyder-dev python=3
$ conda activate spyder-dev
$ conda install -c spyder-ide/label/dev --file requirements/conda.txt
$ python bootstrap.py

### Traceback
```python-traceback
  File "/home/gary/anaconda3/envs/spyder-dev/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/gary/anaconda3/envs/spyder-dev/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/gary/anaconda3/envs/spyder-dev/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/gary/src/spyder/external-deps/python-language-server/pyls/python_ls.py", line 208, in m_initialize
    self.config = config.Config(rootUri, initializationOptions or {},
  File "/home/gary/src/spyder/external-deps/python-language-server/pyls/config/config.py", line 53, in __init__
    entry_point.load()
  File "/home/gary/anaconda3/envs/spyder-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/gary/anaconda3/envs/spyder-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/gary/anaconda3/envs/spyder-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.VersionConflict: (python-language-server 0+untagged.1.g4d31270 (/home/gary/src/spyder/external-deps/python-language-server), Requirement.parse('python-language-server>=0.36.2')
```

## Versions

* Spyder version: 5.0.0.dev0 4d31270
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-135-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0        :  1.4.0 (OK)
chardet >=2.0.0             :  4.0.0 (OK)
cloudpickle >=0.5.0         :  1.6.0 (OK)
cookiecutter >=1.6.0        :  1.7.2 (OK)
diff_match_patch >=20181111 :  20200713 (OK)
intervaltree >=3.0.2        :  3.1.0 (OK)
IPython >=7.6.0             :  7.19.0 (OK)
jedi =0.17.2                :  0.17.2 (OK)
jsonschema >=3.2.0          :  3.2.0 (OK)
keyring >=17.0.0            :  22.0.1 (OK)
nbconvert >=4.0             :  6.0.7 (OK)
numpydoc >=0.6.0            :  1.1.0 (OK)
parso =0.7.0                :  0.7.0 (OK)
pexpect >=4.4.0             :  4.8.0 (OK)
pickleshare >=0.4           :  0.7.5 (OK)
psutil >=5.3                :  5.7.2 (OK)
pygments >=2.0              :  2.7.4 (OK)
pylint >=1.0                :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0        :  0+untagged.1.g4d31270 (OK)
pyls_black >=0.4.6          :  0.4.6 (OK)
pyls_spyder >=0.3.0         :  0.3.0 (OK)
qdarkstyle >=2.8            :  2.8.1 (OK)
qtawesome >=0.5.7           :  1.0.1 (OK)
qtconsole >=5.0.1           :  5.0.1 (OK)
qtpy >=1.5.0                :  1.9.0 (OK)
rtree >=0.8.3               :  0.9.4 (OK)
setuptools >=39.0.0         :  52.0.0.post20210125 (OK)
sphinx >=0.6.6              :  3.4.3 (OK)
spyder_kernels >=2.0.0dev0  :  2.0.0.dev0 (OK)
textdistance >=4.2.0        :  4.2.0 (OK)
three_merge >=0.1.1         :  0.1.1 (OK)
watchdog >=0.10.3           :  0.10.4 (OK)
xdg >=0.26                  :  0.27 (OK)
zmq >=17                    :  20.0.0 (OK)

# Optional:
cython >=0.21               :  None (NOK)
matplotlib >=2.0.0          :  None (NOK)
numpy >=1.7                 :  None (NOK)
pandas >=1.1.1              :  None (NOK)
scipy >=0.17.0              :  None (NOK)
sympy >=0.7.3               :  None (NOK)
```

**Comment by steff456** [comment] 2021-02-01 22:07
Hi @guangyu-shi,

Are you running the `python bootstrap.py` instruction in the `spyder-dev` environment? Or did you installed any extra package after creating the environment?

**Comment by ccordoba12** [comment] 2021-02-01 23:41
Another question for you @guangyu-shi: what command did you use to clone our git repository? Or how did you install it?

I say it because it seems you don't have any of our git tags and that's the cause of the failure.

**Comment by guangyu-shi** [comment] 2021-02-02 15:53
I clone spyder's master branch.

**Comment by guangyu-shi** [comment] 2021-02-02 15:56
I didn't  installed any extra package after creating the environment; running 'python bootstrap.py' hits the issue.

**Comment by guangyu-shi** [comment] 2021-02-02 16:26
git tag -a v5.0.0a3 -m "my v5.0.0a3" 

The above command solves the issue; the master branch has no tag associated.

Why does Python Language Server have no its own version instead of relying on tags?

**Comment by ccordoba12** [comment] 2021-02-02 18:57
Closing because you were able to solve this. The Python language server uses versioneer to define a version, and that requires a tag in the repo with the appropriate version.

**Closed by ccordoba12** 2021-02-02 18:57 UTC
Labels: status:Awaiting Followup

**Comment by ccordoba12** [comment] 2021-02-02 18:58
I still don't understand how you manage to clone a repo without pulling its tags (I thought it was done automatically by git).

**Comment by guangyu-shi** [comment] 2021-02-02 19:07
git clone --depth 1 https://github.com/spyder-ide/spyder.git

This get the master, but no any tags.

**Comment by ccordoba12** [comment] 2021-02-02 23:23
Well, that's where you deviated from our Contributing guide:

![imagen](https://user-images.githubusercontent.com/365293/106675759-b105ca80-6583-11eb-8f1e-a7bfd20f429d.png)

We don't suggest to use `--depth 1` or other clever tricks to clone our repo.
