### ISSUE TITLE
Left parenthesis swallowed

### ISSUE THREAD

**Issue by naspitha** [spyder-ide/spyder#12905] opened 2020-05-30 02:46 UTC
### What steps will reproduce the problem?

When typing the left parenthesis, (, character into the iPython console, the character does not show up until several seconds later, and it can even insert itself after characters that I type up afterwards. For example, if I try to quickly type:

func(abcdefg)

The "(" character does not show up as a type it, and it randomly pops up after I've already typed up the rest of the code, i.e.:

funcabcde(fg)

I have not encountered this problem with any other character (including the right-side parenthesis). I also noticed that the problem does NOT appear if the character "(" is the first one in the input line. I have not noticed this problem occur on the main editor window, just on the iPython console.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.5
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.1 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.11.1 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  1.17.5 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.5 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
```

**Comment by bcolsen** [comment] 2020-06-04 04:18
This looks like a duplicate of #8228. You can stop it by disabling the tips in the console with:

    Preferences > IPython console > Display > Display ballon tips

Closing as a duplicate of #8228

**Closed by bcolsen** 2020-06-04 04:18 UTC
