### ISSUE TITLE
Editor tabbar keeps scrolling automatically

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#4673] opened 2017-06-30 05:34 UTC
@rlaverde, this is still not fixed. If I have these tabs in the Editor

![seleccion_005](https://user-images.githubusercontent.com/365293/27722168-62596216-5d2b-11e7-872f-fd92adecc635.png)

and then select the `mainwindow.py` tab, I end up with this

![seleccion_003](https://user-images.githubusercontent.com/365293/27722142-22d3bd12-5d2b-11e7-82b7-6d09e4cb85a5.png)

while what I would like to see is this

![seleccion_006](https://user-images.githubusercontent.com/365293/27722191-96a122a2-5d2b-11e7-9feb-27ea9ccf1774.png)

i.e that after selecting `mainwindow.py` there's no scrolling at all in the tabbar.

Please fix this one.

**Comment by ccordoba12** [comment] 2017-06-30 14:41
Sorry, this only seems to be an issue when using KDE's default theme (i.e. Breeze), so it's not that important.

I'm leaving it for 3.2.1.

**Comment by goanpeca** [comment] 2019-11-30 02:09
Closing as duplicate of https://github.com/spyder-ide/spyder/issues/5459

**Closed by goanpeca** 2019-11-30 02:09 UTC
Labels: component:Editor, type:Bug
