### ISSUE TITLE
crash when setting location bar to windows network locate

### ISSUE THREAD

**Issue by soldcake** [spyder-ide/spyder#14397] opened 2020-12-09 23:33 UTC
### What steps will reproduce the problem?

set location bar to \\server-name\aaaa\bbb
path becomes \\\\\\\\server-name\\\\aaaa\\\\bbb at kernel.py line 352. (set_cwd())

### Traceback
```python-traceback
Exception in comms call set_cwd:
  File "C:\Anaconda3_x64\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Anaconda3_x64\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Anaconda3_x64\lib\site-packages\spyder_kernels\console\kernel.py", line 352, in set_cwd
    os.chdir(dirname)
FileNotFoundError: [Errno 2] The specified path is invalid: '\\\\\\\\sc-lab958\\\\JenkinsWorkspace\\\\MV7_x64\\\\build\\\\InstallationScripts'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.6.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.19.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  6.0.7 (OK)
numpydoc >=0.6.0             :  1.1.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.2 (OK)
pygments >=2.0               :  2.7.3 (OK)
pylint >=0.25                :  2.6.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  20.0.0 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  1.0.1 (OK)
qtconsole >=4.6.0            :  4.7.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  3.2.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.21 (OK)
matplotlib >=2.0.0           :  3.3.2 (OK)
numpy >=1.7                  :  1.19.2 (OK)
pandas >=0.13.1              :  1.1.3 (OK)
scipy >=0.17.0               :  1.5.2 (OK)
sympy >=0.7.3                :  1.6.2 (OK)
```

**Comment by dalthviz** [comment] 2020-12-10 00:18
Hi @soldcake this is a duplicate of #10785 please update to at least Spyder 4.1.0 to get the fix

**Closed by dalthviz** 2020-12-10 00:18 UTC
Labels: resolution:Duplicate
