### ISSUE TITLE
Error when closing an IPython console when using a custom interpreter without the correct `spyder-kernels` version

### ISSUE THREAD

**Issue by adamsmail54321** [spyder-ide/spyder#16985] opened 2021-12-08 19:46 UTC
### What steps will reproduce the problem?

i dont understand,
kernel_manager.stop_restarter()

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Python3\SpyderIDE\pkgs\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1746, in close_client
    client.shutdown(last_client)
  File "C:\Python3\SpyderIDE\pkgs\spyder\plugins\ipythonconsole\widgets\client.py", line 585, in shutdown
    self.shellwidget.shutdown(shutdown_kernel)
  File "C:\Python3\SpyderIDE\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 176, in shutdown
    self.kernel_manager.stop_restarter()
AttributeError: 'NoneType' object has no attribute 'stop_restarter'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.11.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.0 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.2.0 (OK)
sphinx >=0.6.6                :  4.3.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by AMasrar** [comment] 2021-12-09 15:10
I had this same bug after updating Spyder to 5.2.0, I think that this is related to using a custom interpreter. Try to change these two lines in `"%HOMEPATH%\.spyder-py3\config\spyder.ini"`
from:
```ini
[main_interpreter]
default = False
custom = True
```
to 
```ini
[main_interpreter]
default = True
custom = False
```
If it doesn't work and you don't mind losing your Spyder settings (open files, history, autosave...), delete the `"%HOMEPATH%\.spyder-py3"` folder.

After Spyder launched on my machine I did change my interpreter to a custom one and restarted Spyder with no problem.

**Comment by dalthviz** [comment] 2021-12-09 18:18
Hi @adamsmail54321 and @AMasrar thank you for the feedback! As @AMasrar said there was an issue in Spyder 5.2.0 related with the handling of the custom interpreter preference (#16896).

Another thing that could help with this is updating in the env of your custom interpreter the version of `spyder-kernels` to `2.2.0`

Let us know if something of the above helps!

**Comment by adamsmail54321** [comment] 2021-12-09 20:26
Thank you so much for answering my request, I will try that today!

**Comment by dalthviz** [comment] 2021-12-16 18:12
Closing as duplicate of https://github.com/spyder-ide/spyder/issues/16896

**Closed by dalthviz** 2021-12-16 18:12 UTC
Labels: status:Awaiting Followup
