### ISSUE TITLE
Spyder Bug

### ISSUE THREAD

**Issue by haiouzsf** [spyder-ide/spyder#5820] opened 2017-11-23 03:37 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 527, in <lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 549, in editor_accepted
    self.set_value(index, conv_func(value))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1370, in set_value
    self.set_value_func(name, value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 305, in set_value
    self.shellwidget.set_value(name, value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 100, in set_value
    value = to_text_string(value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\py3compat.py", line 129, in to_text_string
    return str(obj)
MemoryError

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0

**Comment by ccordoba12** [comment] 2017-11-23 04:39
What were you doing when this happened?

**Comment by haiouzsf** [comment] 2017-11-23 07:18
1 headers= [...];data = pd.read_csv("...data.txt",header=0,names = headers)" # this file's size is 72+m
2 data2 = data.replace(0,np.nan)
3 click the "reset the namespaces" button in Variable explorer, then Spyder die.

**Comment by ccordoba12** [comment] 2017-12-06 17:17
This is duplicate of issue #5830.

**Closed by ccordoba12** 2017-12-06 17:17 UTC
