### ISSUE TITLE
Error when trying to view subclass of Dataframe in the Variable Explorer

### ISSUE THREAD

**Issue by st12iker** [spyder-ide/spyder#5199] opened 2017-09-11 15:30 UTC
## Description of your problem

Spyder was unable to retrieve the value of this variable from the console.

The error mesage was:
AttributeError("Can't get attribute 'DataSetTest' on ",)

**What steps will reproduce the problem?**

1.   Assign variable to a new Pandas DataFrame
2.  Double click on the newly created variable within the "variable explorer"

**What is the expected output? What do you see instead?**

The expected output is a GUI with the values of the dataframe (attributes, rows, and values)
Instead error message appears in pop-up.  See information above in "Description of problem"

**Please provide any additional information below**

## Versions and main components

* Spyder Version:  3.2.3
* Python Version:  3.6.1
* Operating system: Mac OSX - OS X El Capitan (version 10.11.3)
* Anaconda custom (x86_64)
* IPython 5.3.0

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-09-11 17:08
> Spyder was unable to retrieve the value of this variable

What variable? Please post a reproducible example.

**Comment by st12iker** [comment] 2017-09-11 17:27
so I create a custom class that inherits pd.DataFrame. (see below)
then ...

test_df = DataSet()

test_df appears in the "variable explorer" but when I double-click to inspect I get the error aforementions

```
import pandas as pd

class DataSet(pd.DataFrame):
#class DataSet():
    """
    
    Encapsulates a dataset
    Extends a Pandas DataFrame
    
    """

    
    def __init__(self, fileLocation = r'/Users/julian/Downloads/movie_metadata.csv'):
        """
        
        !! CONSTRUCTOR !!
        
        PRECONDITION
            "dataset" is a Pandas DataFrame
        
        POSTCONDITION
            Prepares a Pandas DataFrame
        """
            
        super().__init__()
        
        ##  prepare datasets
        self.__dataset = self.load_dataset_file( fileLocation )
        
        ##  load data into dataframe
        super().__init__(data = self.__dataset)
        
        ##  get categorical attributes, numerical attributes, adn dataset with missing numeric
        ##  values replaced with "np.nan" a special missing value replacement
        self.__list_category_attributes, self.__list_numeric_attributes, self.__dataset = self.prepare_dataset()
            
```

**Comment by ccordoba12** [comment] 2017-09-11 17:30
Thanks for reporting. We'll take a look at this in a future release.

**Comment by CAM-Gerlach** [comment] 2018-03-12 03:31
Thanks for the information. Unfortunately, the above code is neither minimal nor complete, as it is missing several methods needed to run, and when I faked some to get around the errors, I was unable to reproduce the problem. However, it is an apparent duplicate of #5270 , which does contain a minimal reproducible example that produces the same error as this one on an older Spyder version and I can confirm now does not with some recent Variable Explorer changes, and the original reporter there confirmed the same for their code. Therefore, I'm closing this as a duplicate. If it still happens in Spyder 3.2.7, please re-open if you can post an actual reproducible example, but hopefully its all fixed for you.

**Closed by CAM-Gerlach** 2018-03-12 03:31 UTC
Labels: component:Variable Explorer, type:Bug
