### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by omowunmiayo** [spyder-ide/spyder#8424] opened 2018-12-12 17:00 UTC
### What steps will reproduce the problem?

 File "C:\Users\ooa616\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1940, in load
    finfo = self.editorstacks[0].load(filename, set_current=False)
  File "C:\Users\ooa616\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2248, in load
    text, enc = encoding.read(filename)
  File "C:\Users\ooa616\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
OSError: [Errno 22] Invalid argument

### Traceback
```python-traceback
  File "C:\Users\ooa616\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1940, in load
    finfo = self.editorstacks[0].load(filename, set_current=False)
  File "C:\Users\ooa616\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2248, in load
    text, enc = encoding.read(filename)
  File "C:\Users\ooa616\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
OSError: [Errno 22] Invalid argument
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

Please How can I resolve this?

Thank you

**Comment by ccordoba12** [comment] 2018-12-12 17:22
Closing as a duplicate of #8423.

Please don't open more issues about this.

**Closed by ccordoba12** 2018-12-12 17:22 UTC
