### ISSUE TITLE
Spyder won't start

### ISSUE THREAD

**Issue by tijmen03** [spyder-ide/spyder#21420] opened 2023-10-11 19:36 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder won't start from shortcut or from the anaconda navigator, it might have to do with installing a package with pip but after reseting spyder and uninstalling and installing everything it still gives the same error

### What steps reproduce the problem?

1. starting spyder from anaconda 

### What is the expected output? What do you see instead?
I expect spyder to start

### Paste Traceback/Error Below (if applicable)

```python-traceback

i dont have a traceback but here is the error code
Exit code: 3221225477
```

## Versions

* Spyder version: 5.4.3
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 11

### Dependencies

```
i cant start spyder
```

**Comment by dalthviz** [comment] 2023-10-11 20:00
Hi @tijmen03 thank you for the feedback! At first glance seems like something broke in your anaconda installation (maybe due to the package installed via pip). Checking the issue tracker seems like this could be related with https://github.com/spyder-ide/spyder/issues/21124 or https://github.com/spyder-ide/spyder/issues/21217. Could you check if following some of the suggestions on those issues helps? Let us know!

**Comment by tijmen03** [comment] 2023-10-12 07:18
I think i have the same issue as #21217 with that the docking station we have is causing the problem

**Comment by dalthviz** [comment] 2023-10-12 17:58
Thank you for letting us know! I will close this then as a duplicate of #21217 and potencially https://github.com/spyder-ide/spyder/issues/20344

**Closed by dalthviz** 2023-10-12 17:58 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
