### ISSUE TITLE
Cannot open new file

### ISSUE THREAD

**Issue by quinnman2017** [spyder-ide/spyder#6405] opened 2018-02-07 18:53 UTC
Whenever I go to open a new file in the Spyder editor, it shoots me the message that Spyder has encountered a problem.  I am not sure how this happened as I have been creating and saving new folders for the past few days now.  

I expect to create a new file, and I'm not sure how to recreate the issue. 

**Please provide any additional information below**

  File "C:\Users\Quinn Wieber\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1712, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "C:\Users\Quinn Wieber\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Quinn Wieber\\.spyder-py3\\template.py'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-07 19:50
Thanks for reporting. This is a duplicate of issue #5717.

Please run in a system terminal (cmd.exe)

    spyder --reset

to see if that fixes it.

**Closed by ccordoba12** 2018-02-07 19:50 UTC

**Comment by CAM-Gerlach** [comment] 2018-02-09 01:19
Just in case it doesn't, Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.
