### ISSUE TITLE
Spyder 5.x does not preserve filter settings

### ISSUE THREAD

**Issue by krisvanneste** [spyder-ide/spyder#16044] opened 2021-07-19 16:28 UTC
### What steps will reproduce the problem?

Open Preferences
In the Files tab, under Filter settings, add a pattern (e.g. *.py)
Save preferences
Click on "Filter" symbol in Files panel --> it works, only .py files and folders are shown
Restart Spyder
--> Files panel again shows all files, and clicking on the Filter symbol does nothing
--> The Filter settings box in Preferences is empty.

**Comment by steff456** [comment] 2021-07-20 15:58
Hi @krisvanneste,

In what version of Spyder are you encountering this behavior?

**Comment by krisvanneste** [comment] 2021-07-22 07:41
> 
> 
> Hi @krisvanneste,
> 
> In what version of Spyder are you encountering this behavior?

In version 5.0.5

**Comment by ccordoba12** [comment] 2021-07-24 02:49
Hey @krisvanneste, this is a duplicate of issue #15459. We'll try to fix it on our next release.

**Closed by ccordoba12** 2021-07-24 02:49 UTC
Labels: status:Awaiting Followup
