### ISSUE TITLE
failed to update

### ISSUE THREAD

**Issue by badinplaid737** [spyder-ide/spyder#21799] opened 2024-02-14 02:30 UTC
### What steps will reproduce the problem?

I have spyder check for updates when starting, get pop up saying 5.5.1 is available would you like update now. click box indicating yes and issue reporter pops up 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/steventhomasmbp/anaconda3/lib/python3.11/site-packages/spyder/plugins/application/container.py", line 330, in _check_updates_ready
    self.application_update_status.start_installation(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_installation'
```

## Versions

* Spyder version: 5.5.0  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: macOS-14.3.1-arm64-arm-64bit

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0        :  0.3.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.2.1 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.0 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.0 (OK)
numpy >=1.7                      :  1.26.3 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /Users/steventhomasmbp/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2023.09         py311_openblas_1  
abseil-cpp                20230802.0           h313beb8_2  
aiobotocore               2.7.0           py311hca03da5_0  
aiofiles                  22.1.0          py311hca03da5_0  
aiohttp                   3.9.3           py311h80987f9_0  
aioitertools              0.7.1              pyhd3eb1b0_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
aiosqlite                 0.18.0          py311hca03da5_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda-anon-usage       0.4.3           py311hd6b623d_100  
anaconda-catalogs         0.2.0           py311hca03da5_0  
anaconda-client           1.12.2          py311hca03da5_0  
anaconda-cloud-auth       0.1.4           py311hca03da5_0  
anaconda-navigator        2.5.2           py311hca03da5_0  
anaconda-project          0.11.1          py311hca03da5_0  
anyio                     4.2.0           py311hca03da5_0  
aom                       3.6.0                h313beb8_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
applaunchservices         0.3.0           py311hca03da5_0  
appnope                   0.1.2           py311hca03da5_1001  
appscript                 1.1.2           py311h80987f9_0  
archspec                  0.2.1              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py311h80987f9_0  
arrow                     1.2.3           py311hca03da5_1  
arrow-cpp                 14.0.2               hc7aafb3_1  
astroid                   2.14.2          py311hca03da5_0  
astropy                   5.3.4           py311hb9f6ed7_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-lru                 2.0.4           py311hca03da5_0  
async-timeout             4.0.3           py311hca03da5_0  
atomicwrites              1.4.0                      py_0  
attrs                     23.1.0          py311hca03da5_0  
automat                   20.2.0                     py_0  
autopep8                  2.0.4              pyhd8ed1ab_0    conda-forge
aws-c-auth                0.6.19               h80987f9_0  
aws-c-cal                 0.5.20               h80987f9_0  
aws-c-common              0.8.5                h80987f9_0  
aws-c-compression         0.2.16               h80987f9_0  
aws-c-event-stream        0.2.15               h313beb8_0  
aws-c-http                0.6.25               h80987f9_0  
aws-c-io                  0.13.10              h80987f9_0  
aws-c-mqtt                0.7.13               h80987f9_0  
aws-c-s3                  0.1.51               h80987f9_0  
aws-c-sdkutils            0.1.6                h80987f9_0  
aws-checksums             0.1.13               h80987f9_0  
aws-crt-cpp               0.18.16              h313beb8_0  
aws-sdk-cpp               1.10.55              h313beb8_0  
babel                     2.11.0          py311hca03da5_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backoff                   1.11.1             pyhd8ed1ab_0    conda-forge
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0           py311h80987f9_1  
beautifulsoup4            4.12.2          py311hca03da5_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     23.11.0         py311hca03da5_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.3               h313beb8_0  
bokeh                     3.3.4           py311hb6e6a13_0  
boltons                   23.0.0          py311hca03da5_0  
boost-cpp                 1.82.0               h48ca7d4_2  
botocore                  1.31.64         py311hca03da5_0  
bottleneck                1.3.7           py311hb9f6ed7_0  
brotli                    1.0.9                h1a28f6b_7  
brotli-bin                1.0.9                h1a28f6b_7  
brotli-python             1.0.9           py311h313beb8_7  
brunsli                   0.1                  hc377ac9_1  
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.19.1               h80987f9_0  
c-blosc2                  2.12.0               h7df6c2f_0  
ca-certificates           2023.12.12           hca03da5_0  
cctools                   949.0.1             hc179dcd_25  
cctools_osx-arm64         949.0.1             h332cad3_25  
certifi                   2024.2.2        py311hca03da5_0  
cffi                      1.16.0          py311h80987f9_0  
cfitsio                   3.470                h7f6438f_7  
chardet                   4.0.0           py311hca03da5_1003  
charls                    2.2.0                hc377ac9_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py311hca03da5_0  
cloudpickle               2.2.1           py311hca03da5_0  
clyent                    1.2.2           py311hca03da5_1  
colorama                  0.4.6           py311hca03da5_0  
colorcet                  3.0.1           py311hca03da5_0  
comm                      0.1.2           py311hca03da5_0  
conda                     24.1.1          py311hca03da5_0  
conda-build               24.1.1          py311hca03da5_0  
conda-content-trust       0.2.0           py311hca03da5_0  
conda-index               0.4.0              pyhd3eb1b0_0  
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    2.2.0           py311hca03da5_0  
conda-package-streaming   0.9.0           py311hca03da5_0  
conda-repo-cli            1.0.75          py311hca03da5_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
constantly                23.10.4         py311hca03da5_0  
contourpy                 1.2.0           py311h48ca7d4_0  
cookiecutter              2.5.0           py311hca03da5_0  
cryptography              42.0.2          py311hd4332d6_0  
cssselect                 1.2.0           py311hca03da5_0  
curl                      8.5.0                h02f6b3c_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h9131b1a_1  
cytoolz                   0.12.2          py311h80987f9_0  
dask                      2023.11.0       py311hca03da5_0  
dask-core                 2023.11.0       py311hca03da5_0  
datasets                  2.12.0          py311hca03da5_0  
datashader                0.16.0          py311hca03da5_0  
datashape                 0.5.4           py311hca03da5_1  
dav1d                     1.2.1                h80987f9_0  
debugpy                   1.6.7           py311h313beb8_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.6           py311hca03da5_0  
distributed               2023.11.0       py311hca03da5_0  
distro                    1.8.0           py311hca03da5_0  
docstring-to-markdown     0.11            py311hca03da5_0  
docutils                  0.18.1          py311hca03da5_3  
entrypoints               0.4             py311hca03da5_0  
et_xmlfile                1.1.0           py311hca03da5_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.13.1          py311hca03da5_0  
flake8                    6.1.0           py311hca03da5_0  
flask                     2.2.5           py311hca03da5_0  
fmt                       9.1.0                h48ca7d4_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h1192e45_0  
frozenlist                1.4.0           py311h80987f9_0  
fsspec                    2023.10.0       py311hca03da5_0  
future                    0.18.3          py311hca03da5_0  
gensim                    4.3.0           py311h6956b77_0  
gettext                   0.21.0               h13f89a0_1  
gflags                    2.2.2                h313beb8_1  
giflib                    5.2.1                h80987f9_3  
glib                      2.69.1               h514c7bf_2  
glog                      0.5.0                h313beb8_1  
gmp                       6.2.1                hc377ac9_3  
gmpy2                     2.1.2           py311h40f64dc_0  
greenlet                  3.0.1           py311h313beb8_0  
grpc-cpp                  1.48.2               hc60591f_4  
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
gtest                     1.14.0               h48ca7d4_0  
h5py                      3.9.0           py311hba6ad2f_0  
hdf5                      1.12.1               h05c076b_3  
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.18.3          py311hca03da5_0  
huggingface_hub           0.17.3          py311hca03da5_0  
hvplot                    0.9.2           py311hca03da5_0  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icu                       73.1                 h313beb8_0  
idna                      3.4             py311hca03da5_0  
imagecodecs               2023.1.23       py311h5e7c512_0  
imageio                   2.33.1          py311hca03da5_0  
imagesize                 1.4.1           py311hca03da5_0  
imbalanced-learn          0.11.0          py311hca03da5_1  
importlib-metadata        7.0.1           py311hca03da5_0  
importlib_metadata        7.0.1                hd3eb1b0_0  
importlib_resources       6.1.1           py311hca03da5_1  
incremental               21.3.0             pyhd3eb1b0_0  
inflection                0.5.1           py311hca03da5_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    0.6.8           py311hca03da5_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.28.0          py311hca03da5_0  
ipython                   8.20.0          py311hca03da5_0  
ipython-sql               0.3.9           py311hca03da5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                8.0.4           py311hca03da5_0  
isort                     5.9.3              pyhd3eb1b0_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.0.4              pyhd3eb1b0_1  
itsdangerous              2.0.1              pyhd3eb1b0_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.18.1          py311hca03da5_1  
jellyfish                 1.0.1           py311h15d1925_0  
jinja2                    3.1.3           py311hca03da5_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jmespath                  1.0.1           py311hca03da5_0  
joblib                    1.2.0           py311hca03da5_0  
jpeg                      9e                   h80987f9_1  
jq                        1.6                  h1a28f6b_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.19.2          py311hca03da5_0  
jsonschema-specifications 2023.7.1        py311hca03da5_0  
jupysql                   0.10.9             pyhd8ed1ab_0    conda-forge
jupysql-plugin            0.4.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0           py311hca03da5_8  
jupyter-lsp               2.2.0           py311hca03da5_0  
jupyter_client            8.6.0           py311hca03da5_0  
jupyter_console           6.6.3           py311hca03da5_0  
jupyter_core              5.5.0           py311hca03da5_0  
jupyter_events            0.8.0           py311hca03da5_0  
jupyter_server            2.10.0          py311hca03da5_0  
jupyter_server_fileid     0.9.0           py311hca03da5_0  
jupyter_server_terminals  0.4.4           py311hca03da5_1  
jupyter_server_ydoc       0.8.0           py311hca03da5_1  
jupyter_ydoc              0.2.4           py311hca03da5_0  
jupyterlab                4.0.11          py311hca03da5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.25.1          py311hca03da5_0  
jupyterlab_widgets        3.0.9           py311hca03da5_0  
jxrlib                    1.1                  h1a28f6b_2  
kaleido-core              0.2.1                h80987f9_0  
keyring                   23.13.1         py311hca03da5_0  
kiwisolver                1.4.4           py311h313beb8_0  
krb5                      1.20.1               hf3e1bf2_1  
lazy-object-proxy         1.6.0           py311h80987f9_0  
lazy_loader               0.3             py311hca03da5_0  
lcms2                     2.12                 hba8e193_0  
ld64                      530                 hb29bf3f_25  
ld64_osx-arm64            530                 h001ce53_25  
ldid                      2.1.5                h20b2a84_3  
lerc                      3.0                  hc377ac9_0  
libaec                    1.0.4                hc377ac9_1  
libarchive                3.6.2                h62fee54_2  
libavif                   0.11.1               h80987f9_0  
libboost                  1.82.0               h0bc93f9_2  
libbrotlicommon           1.0.9                h1a28f6b_7  
libbrotlidec              1.0.9                h1a28f6b_7  
libbrotlienc              1.0.9                h1a28f6b_7  
libclang                  14.0.6          default_h1b80db6_1  
libclang13                14.0.6          default_h24352ff_1  
libcurl                   8.5.0                h3e2b118_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_1  
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libiconv                  1.16                 h1a28f6b_2  
liblief                   0.12.3               h313beb8_0  
libllvm14                 14.0.6               h7ec7a93_3  
libmamba                  1.5.6                h15e39b3_0  
libmambapy                1.5.6           py311h1c5506f_0  
libnghttp2                1.57.0               h62f6fdd_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     12.17                h02f6b3c_0  
libprotobuf               3.20.3               h514c7bf_0  
libsodium                 1.0.18               h1a28f6b_0  
libsolv                   0.7.24               h514c7bf_0  
libspatialindex           1.9.3                hc377ac9_0  
libsqlite                 3.45.1               h091b4b1_0    conda-forge
libssh2                   1.10.0               h02f6b3c_2  
libthrift                 0.15.0               h73c2103_2  
libtiff                   4.5.1                h313beb8_0  
libwebp                   1.3.2                ha3663a8_0  
libwebp-base              1.3.2                h80987f9_0  
libxml2                   2.10.4               h0dcf63f_1  
libxslt                   1.1.37               h80987f9_1  
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                hc377ac9_0  
linkify-it-py             2.0.0           py311hca03da5_0  
llvm-openmp               14.0.6               hc6e5704_0  
llvmlite                  0.42.0          py311h313beb8_0  
locket                    1.0.0           py311hca03da5_0  
lxml                      4.9.3           py311h50ffb84_0  
lz4                       4.3.2           py311h80987f9_0  
lz4-c                     1.9.4                h313beb8_0  
lzo                       2.10                 h1a28f6b_2  
markdown                  3.4.1           py311hca03da5_0  
markdown-it-py            2.2.0           py311hca03da5_1  
markupsafe                2.1.3           py311h80987f9_0  
mathjax                   2.7.5                hca03da5_0  
matplotlib                3.8.0           py311hca03da5_0  
matplotlib-base           3.8.0           py311h7aedaa7_0  
matplotlib-inline         0.1.6           py311hca03da5_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdit-py-plugins           0.3.0           py311hca03da5_0  
mdurl                     0.1.0           py311hca03da5_0  
menuinst                  2.0.2           py311hca03da5_0  
mistune                   2.0.4           py311hca03da5_0  
monotonic                 1.5                        py_0    conda-forge
more-itertools            10.1.0          py311hca03da5_0  
mpc                       1.1.0                h8c48613_1  
mpfr                      4.0.2                h695f6f0_1  
mpmath                    1.3.0           py311hca03da5_0  
msgpack-python            1.0.3           py311h48ca7d4_0  
multidict                 6.0.4           py311h80987f9_0  
multipledispatch          0.6.0           py311hca03da5_0  
multiprocess              0.70.14         py311hca03da5_0  
munkres                   1.1.4                      py_0  
mypy_extensions           1.0.0           py311hca03da5_0  
mysql                     5.7.24               ha71a6ea_2  
navigator-updater         0.4.0           py311hca03da5_1  
nbclassic                 1.0.0           py311hca03da5_0  
nbclient                  0.8.0           py311hca03da5_0  
nbconvert                 7.10.0          py311hca03da5_0  
nbconvert-core            7.10.0             pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2           py311hca03da5_0  
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.5.6           py311hca03da5_0  
networkx                  3.1             py311hca03da5_0  
nltk                      3.8.1           py311hca03da5_0  
notebook                  7.0.6           py311hca03da5_0  
notebook-shim             0.2.3           py311hca03da5_0  
numba                     0.59.0          py311h7aedaa7_0  
numexpr                   2.8.7           py311h6dc990b_0  
numpy                     1.26.3          py311he598dae_0  
numpy-base                1.26.3          py311hfbfe69c_0  
numpydoc                  1.5.0           py311hca03da5_0  
oniguruma                 6.9.7.1              h1a28f6b_0  
openjpeg                  2.3.0                h7a6adac_2  
openpyxl                  3.0.10          py311h80987f9_0  
openssl                   3.2.0                h0d3ecfb_1    conda-forge
orc                       1.7.4                hdca1487_1  
overrides                 7.4.0           py311hca03da5_0  
packaging                 23.1            py311hca03da5_0  
pandas                    2.1.4           py311h7aedaa7_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     1.3.8           py311hca03da5_0  
param                     2.0.2           py311hca03da5_0  
parsel                    1.8.1           py311hca03da5_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1           py311hca03da5_0  
patch                     2.7.6             h1a28f6b_1001  
pathlib                   1.0.1              pyhd3eb1b0_1  
pathspec                  0.10.3          py311hca03da5_0  
patsy                     0.5.3           py311hca03da5_0  
pcre                      8.45                 hc377ac9_0  
pcre2                     10.42                hb066dcc_0  
pep8                      1.7.1           py311hca03da5_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.2.0          py311h80987f9_0  
pip                       23.3.1          py311hca03da5_0  
pkce                      1.0.3           py311hca03da5_0  
pkginfo                   1.9.6           py311hca03da5_0  
platformdirs              3.10.0          py311hca03da5_0  
ploomber-core             0.2.25             pyhd8ed1ab_0    conda-forge
plotly                    5.9.0           py311hca03da5_0  
pluggy                    1.0.0           py311hca03da5_1  
ply                       3.11            py311hca03da5_0  
posthog                   3.4.1              pyhd8ed1ab_0    conda-forge
poyo                      0.5.0              pyhd3eb1b0_0  
prettytable               3.9.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1          py311hca03da5_0  
prompt-toolkit            3.0.43          py311hca03da5_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
protego                   0.1.16                     py_0  
psutil                    5.9.0           py311h80987f9_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-cpuinfo                9.0.0           py311hca03da5_0  
py-lief                   0.12.3          py311h313beb8_0  
pyarrow                   14.0.2          py311ha07b5f9_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pybind11-abi              4                    hd3eb1b0_1  
pycodestyle               2.11.1          py311hca03da5_0  
pycosat                   0.6.6           py311h80987f9_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0           py311hca03da5_0  
pycurl                    7.45.2          py311h02f6b3c_1  
pydantic                  1.10.12         py311h80987f9_1  
pydispatcher              2.0.5           py311hca03da5_2  
pydocstyle                6.3.0           py311hca03da5_0  
pyerfa                    2.0.0           py311h80987f9_0  
pyflakes                  3.1.0           py311hca03da5_0  
pygments                  2.15.1          py311hca03da5_1  
pyjwt                     2.4.0           py311hca03da5_0  
pylint                    2.16.2          py311hca03da5_0  
pylint-venv               3.0.3              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyobjc-core               9.0             py311h3eb5a62_1  
pyobjc-framework-cocoa    9.0             py311hb094c41_0  
pyobjc-framework-coreservices 9.0             py311hdd8dd1f_0  
pyobjc-framework-fsevents 9.0             py311hca03da5_0  
pyodbc                    5.0.1           py311h313beb8_0  
pyopenssl                 24.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9           py311hca03da5_0  
pyqt                      5.15.10         py311h313beb8_0  
pyqt5-sip                 12.13.0         py311h80987f9_0  
pyqtwebengine             5.15.10         py311h313beb8_0  
pysocks                   1.7.1           py311hca03da5_0  
pytables                  3.9.2           py311h0326f10_0  
pytest                    7.4.0           py311hca03da5_0  
python                    3.11.7          hdf0ec26_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-dotenv             0.21.0          py311hca03da5_0  
python-fastjsonschema     2.16.2          py311hca03da5_0  
python-json-logger        2.0.7           py311hca03da5_0  
python-kaleido            0.2.1           py311hca03da5_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lmdb               1.4.1           py311h313beb8_0  
python-lsp-black          1.2.1           py311hca03da5_0  
python-lsp-jsonrpc        1.1.2              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.9.0              pyhd8ed1ab_0    conda-forge
python-lsp-server-base    1.9.0              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.1           py311h313beb8_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python-xxhash             2.0.2           py311h80987f9_1  
python.app                3               py311h80987f9_0  
python_abi                3.11                    4_cp311    conda-forge
pytoolconfig              1.2.6           py311hca03da5_0  
pytz                      2023.3.post1    py311hca03da5_0  
pyviz_comms               3.0.0           py311hca03da5_0  
pywavelets                1.5.0           py311hb9f6ed7_0  
pyyaml                    6.0.1           py311h80987f9_0  
pyzmq                     25.1.2          py311h313beb8_0  
qdarkstyle                3.2                pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2           py311hca03da5_0  
qt-main                   5.15.2              h0917680_10  
qt-webengine              5.15.9               h2903aaf_7  
qtawesome                 1.2.2           py311hca03da5_0  
qtconsole                 5.5.0           py311hca03da5_0  
qtconsole-base            5.5.1              pyha770c72_0    conda-forge
qtpy                      2.4.1           py311hca03da5_0  
queuelib                  1.6.2           py311hca03da5_0  
re2                       2022.04.01           hc377ac9_0  
readline                  8.2                  h1a28f6b_0  
referencing               0.30.2          py311hca03da5_0  
regex                     2023.10.3       py311h80987f9_0  
reproc                    14.2.4               hc377ac9_1  
reproc-cpp                14.2.4               hc377ac9_1  
requests                  2.31.0          py311hca03da5_1  
requests-file             1.5.1              pyhd3eb1b0_0  
requests-toolbelt         1.0.0           py311hca03da5_0  
responses                 0.13.3             pyhd3eb1b0_0  
rfc3339-validator         0.1.4           py311hca03da5_0  
rfc3986-validator         0.1.1           py311hca03da5_0  
rich                      13.3.5          py311hca03da5_0  
rope                      1.7.0           py311hca03da5_0  
rpds-py                   0.10.6          py311hf0e4da2_0  
rtree                     1.0.1           py311hca03da5_0  
ruamel.yaml               0.17.21         py311h80987f9_0  
ruamel_yaml               0.17.21         py311h80987f9_0  
s3fs                      2023.10.0       py311hca03da5_0  
safetensors               0.4.0           py311h62f922a_0  
scikit-image              0.22.0          py311h7aedaa7_0  
scikit-learn              1.2.2           py311h313beb8_1  
scipy                     1.11.4          py311hc76d9b0_0  
scrapy                    2.8.0           py311hca03da5_0  
seaborn                   0.12.2          py311hca03da5_0  
semver                    2.13.0             pyhd3eb1b0_0  
send2trash                1.8.2           py311hca03da5_0  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                68.2.2          py311hca03da5_0  
sip                       6.7.12          py311h313beb8_0  
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.2.1           py311hca03da5_0  
snappy                    1.1.10               h313beb8_1  
sniffio                   1.3.0           py311hca03da5_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5             py311hca03da5_0  
sphinx                    5.0.2           py311hca03da5_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.5.0           py311h267d04e_3    conda-forge
spyder-kernels            2.5.0           unix_pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.46                   pypi_0    pypi
sqlglot                   20.1.0             pyhd8ed1ab_0    conda-forge
sqlite                    3.41.2               h80987f9_0  
sqlparse                  0.4.4           py311hca03da5_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.14.0          py311hb9f6ed7_0  
sympy                     1.12            py311hca03da5_0  
tabulate                  0.9.0           py311hca03da5_0  
tapi                      1100.0.11            h8754e6a_1  
tbb                       2021.8.0             h48ca7d4_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.2.2           py311hca03da5_0  
terminado                 0.17.1          py311hca03da5_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2023.4.12       py311hca03da5_0  
tinycss2                  1.2.1           py311hca03da5_0  
tk                        8.6.13               h5083fa2_1    conda-forge
tldextract                3.2.0              pyhd3eb1b0_0  
tokenizers                0.13.2          py311h3dd52b7_1  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py311hca03da5_0  
tomlkit                   0.11.1          py311hca03da5_0  
toolz                     0.12.0          py311hca03da5_0  
tornado                   6.3.3           py311h80987f9_0  
tqdm                      4.65.0          py311hb6e6a13_0  
traitlets                 5.7.1           py311hca03da5_0  
transformers              4.32.1          py311hca03da5_0  
truststore                0.8.0           py311hca03da5_0  
twisted                   22.10.0         py311h80987f9_0  
typing-extensions         4.9.0           py311hca03da5_1  
typing_extensions         4.9.0           py311hca03da5_1  
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023d                h04d1e81_0  
uc-micro-py               1.0.1           py311hca03da5_0  
ujson                     5.4.0           py311h313beb8_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
unixodbc                  2.3.11               h1a28f6b_0  
urllib3                   2.0.7           py311hca03da5_0  
utf8proc                  2.6.1                h80987f9_1  
w3lib                     1.21.0             pyhd3eb1b0_0  
watchdog                  2.1.6           py311h80987f9_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py311hca03da5_1  
websocket-client          0.58.0          py311hca03da5_4  
werkzeug                  2.2.3           py311hca03da5_0  
whatthepatch              1.0.2           py311hca03da5_0  
wheel                     0.41.2          py311hca03da5_0  
widgetsnbextension        4.0.5           py311hca03da5_0  
wrapt                     1.14.1          py311h80987f9_0  
wurlitzer                 3.0.2           py311hca03da5_0  
xarray                    2023.6.0        py311hca03da5_0  
xlwings                   0.29.1          py311hca03da5_0  
xxhash                    0.8.0                h1a28f6b_3  
xyzservices               2022.9.0        py311hca03da5_1  
xz                        5.4.5                h80987f9_0  
y-py                      0.5.9           py311ha6e5c4f_0  
yaml                      0.2.5                h1a28f6b_0  
yaml-cpp                  0.8.0                h313beb8_0  
yapf                      0.33.0             pyhd8ed1ab_1    conda-forge
yarl                      1.9.3           py311h80987f9_0  
ypy-websocket             0.8.2           py311hca03da5_0  
zeromq                    4.3.5                h313beb8_0  
zfp                       1.0.0                h313beb8_0  
zict                      3.0.0           py311hca03da5_0  
zipp                      3.17.0          py311hca03da5_0  
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h80987f9_0  
zope                      1.0             py311hca03da5_1  
zope.interface            5.4.0           py311h80987f9_0  
zstandard                 0.19.0          py311h80987f9_0  
zstd                      1.5.5                hd90d995_0  

```
</details>

**Comment by ccordoba12** [comment] 2024-02-15 02:05
Hey @badinplaid737, thanks for reporting. This is a duplicate of issue #21781, which we'll fix in our next version (5.5.2), to be released in a couple of weeks.

In the meantime please ignore it because it's not harmful.

**Closed by ccordoba12** 2024-02-15 02:05 UTC
