### ISSUE TITLE
Asynicio error with Spyder and certain versions of Tornado

### ISSUE THREAD

**Issue by rkdasari** [spyder-ide/spyder#6623] opened 2018-03-06 22:50 UTC
File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError

**Comment by ccordoba12** [comment] 2018-03-06 23:27
Closing as duplicate of #6622.

**Comment by rkdasari** [comment] 2018-03-07 00:02
PermissionError: [Errno 13] Permission denied: 'C:\Users\Radha\AppData\Roaming\jupyter\runtime\kernel-16eae32a20f1.json'

Well, the error says it all. You don't have reading nor writing permissions in that directory and Spyder needs that to start an IPython console. Please fix that in your end because there's nothing we can do about it

This can't be the explanation to close this issue as a duplicate.

**Comment by ccordoba12** [comment] 2018-03-07 00:28
Sorry, they looked like the same problem, but this is an issue with Tornado.

Please run in a system terminal, after activating your environment:

    conda install tornado=4.5.3

to fix it.

**Comment by CAM-Gerlach** [comment] 2018-03-07 03:31
Indeed, almost surely a duplicate of #6627 . As such, closed.

**Closed by CAM-Gerlach** 2018-03-07 03:31 UTC
Labels: status:Awaiting Followup

**Comment by sergoliv** [comment] 2018-03-07 10:08
Thank you for your replies. I have solved the problem by reinstalling a clean Anaconda Distribution. spyder is starting without problems. In fact, the version of Tornado that is installed by this Anaconda Distribution is indeed 4.5.3. I should not have updated Tornado to version 5.0.

**Comment by rkdasari** [comment] 2018-03-07 15:09
Thank you. Changing to 4.5.3 fixed the issue

**Comment by sergoliv** [comment] 2018-03-07 15:33
Yes. It fixed the issue. Thank you.


Os Melhores Cumprimentos,

Sérgio Oliveira

2018-03-07 15:10 GMT+00:00 Radhakrishna Dasari <notifications@github.com>:

**Comment by BojanMatovski** [comment] 2018-04-01 12:02
Changing tornado to 4.5.3 doesn't change the issue in Anaconda 1.8.2. I can't find a solution online, except for "reinstalling anaconda", which I would very much like to avoid because of all of the environments, libraries and everything I have already installed and set up. So, would be very happy if we figure out a solution to the problem.

All the best,
Bojan

**Comment by CAM-Gerlach** [comment] 2018-04-01 17:36
> So, would be very happy if we figure out a solution to the problem.

Sorry you're still having this issue. As we have been very clear, unfortunately there is nothing we can do about this from the Spyder side, as the problem lies in interactions between several third party packages on your system, and has nothing to do with Spyder itself.

> Anaconda 1.8.2

Try installing a more recent version of Anaconda...1.8.x is 4-5 years old; the current version is 5.1.0

> if I start the Spyder in a separate conda environment

Again, this is a clear indication that it is due to conflicting versions of certain factors in one environment, but not the other. Closely examine the versions between the two environments, and try to replicate what you have in the environment that works in the one that doesn't—or just ditch the old one and just use the one that works.

> I am not sure if anaconda updates all environments when I use the automatic updater, so I was wondering if this might be the problem (different anaconda versions for different environments)

Nope; that's the whole point of different environments, to be able to isolate them from one another in order to resolve problems like these.

> I would like to try it out, but I really don't want my spyder broken in the separate environment as well, so I wouldn't try it just yet.

There's no harm in trying; that's the whole point of it being an isolated environment.

Best of luck!.

**Comment by BojanMatovski** [comment] 2018-04-02 08:49
I am sorry, I guess I meant to say that I was updating the Anaconda Navigator, not Anaconda itself. It was just a boring message that prompted me to update to latest version of Anaconda Navigator (v 1.8.2) and when I did it all broke down, as I explained. I was trying to downgrade all the relevant (in my opinion) packages to the version of the environment that works, but as it appears, I just made it worse.

When I tried and executeed spyder it didn't even start, it was just printing this error:
Traceback (most recent call last):

  File "C:\Users\bojan\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\bojan\Anaconda3\lib\site-packages\spyder\app\start.py", line 159, in main
    from spyder.app import mainwindow
  File "C:\Users\bojan\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 78, in <module>
    from qtpy.compat import from_qvariant
  File "C:\Users\bojan\Anaconda3\lib\site-packages\qtpy\compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "C:\Users\bojan\Anaconda3\lib\site-packages\qtpy\QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: DLL load failed: The specified procedure could not be found.

This happened when I tried to downgrade Python from 3.6.4 (that was in my base environment) to 3.5.5 (which was in my other environment that was working correctly).

I had a similar qtpy/pyqt5 issue with Anaconda itself before. Each time I tried to start the anaconda-navigator, this error appeared. Then I manually (re)installed qtpy and pyqt5 (I had to install pyqt5with pip since conda couldn't find it) and the navigator started working again. Now, both libraries are installed, but for some reason, when I start spyder (but apparently anaconda-navigator as well) this error still occurs. I uninstalled them and reinstalled them again and then a pop up window was reporting a "Python is not responding" each time I tried to start Spyder or Anaconda Navigator. So I get the feeling that I am just doing worse and worse with every attempt at trying to fix it.

Also, I am not sure whether it is relevant, but when I am updating some libraries, this message appears:
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\user_name\Anaconda3\pythonw.exe, args are ['C:\\Users\\user_name\\Anaconda3\\cwp.py', 'C:\\Users\\user_name\\Anaconda3', 'C:\\Users\\user_name\\Anaconda3\\pythonw.exe', 'C:\\Users\\user_name\\Anaconda3\\Scripts\\spyder-script.py']
It is weird, since i haven't seen it before when updating/installing packages and libraries.

Then I tried updating python again and the previous error didn't occur, but the kernel was not starting still. It showed the following message:
An error ocurred while starting the kernel
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File 

Also, while spyder was on, a cmd windows was turning off and then on every 2 or 3 seconds. When I checked the anaconda prompt, it was reporting this messages:
js: Not allowed to load local resource: file:///C:/Users/bojan/Anaconda3/lib/site-packages/spyder/utils/help/static/css/default.css
js: Not allowed to load local resource: file:///C:/Users/bojan/Anaconda3/lib/site-packages/spyder/utils/help/static/css/default.css
js: Not allowed to load local resource: file:///C:/Users/bojan/Anaconda3/lib/site-packages/spyder/utils/help/static/css/default.css
js: Not allowed to load local resource: file:///C:/Users/bojan/Anaconda3/lib/site-packages/spyder/utils/help/static/css/default.css
js: Not allowed to load local resource: file:///C:/Users/bojan/Anaconda3/lib/site-packages/spyder/utils/help/static/css/default.css
js: Not allowed to load local resource: file:///C:/Users/bojan/Anaconda3/lib/site-packages/spyder/utils/help/static/css/default.css

So, since I just made it worse, I would stop now and would like to hear your opinion. My point is, I don't really care about my base/root environment, since I do most of the work in separate environments all the time. So, if there is something like a "environment reset to defaults", or something like that, I would be willing to do that. Also, I know it is possible to clone an environment, so if it is OK to remove the base environment and then clone one of my other and name it (base) and set it as root, I would do that as well. But, since it is my root environment, I am afraid not to break something in general, so yeah, that's my question.

**Comment by CAM-Gerlach** [comment] 2018-04-02 14:26
@BojanMatovski We're sorry, but as we've stated multiple times, and your most recent statement only continues to confirm, your issue clearly has nothing to do with Spyder, and is instead due to your Anaconda installation. Though we'd like to help further, and we have already provided a few solutions/workarounds that should get Spyder functional again and answered your questions, as the bug tracker for Spyder and given our limited resources due to being unfunded, there isn't really much more we're able to do. Thanks for understanding, and best of luck!

**Comment by ccordoba12** [comment] 2018-04-02 14:33
@BojanMatovski, did you use pip to install PyQt5? If that was the case, you most probably corrupted all your conda envs and you'll have to recreate them again.

**Comment by BojanMatovski** [comment] 2018-04-03 07:41
I know that pip and conda don't like each other a lot, but I was forced to use pip to install PyQt5 because conda couldn't locate it in its own repository.

As I said, I've done this in the past and it didn't had an (obvious) negative impact and it affect only the local environment, as far as I can tell, all of the remaining environments work OK.

I don't want to spam any longer, so if anybody has an idea how to revert the root environment to its defaults I would really like to hear it, if not, I wouldn't want to be all over the place with my problems, which obviously, as said, are connected more with anaconda than they are with spyder.

So thanks for the help guys and all the best!
