### ISSUE TITLE
Spyder process does not terminate on Windows 10

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#6672] opened 2018-03-08 07:12 UTC
## Problem Description

After closing Spyder on Windows 10 the process does not terminate and remains in the process manager (I'm using System Explorer here).

After starting Spyder the process tree looks like this:

```
pythonw.exe C:\Users\...\anaconda3\Scripts\spyder-script.py
    pythonw.exe C:\Users\...\anaconda3\Scripts\spyder-script.py
        pythonw.exe -u plugin_server.py 54329 fallback
        pythonw.exe -u plugin_server.py 54320 jedi
        pythonw.exe -u plugin_server.py 54311 rope
        pythonw.exe -u plugin_server.py 54329 fallback
```

When quitting the application the four plugin_server.py instances are terminated, but the `spyder-script.py` instance remains and has to be terminated manually in the process manager.

Starting a new Spyder instance while the old one is still there starts a completely new process tree, after quitting Spyder again now two zombie instances remain. Interestingly the second process I had started is displaying the following parameters in System Explorer: `0 764 768 776 8192 772`

The first process does not display any parameters. Maybe that helps in some way.

When started using Anaconda Navigator, Navigator will detect Spyder still running when quitting Navigator and ask you it should terminate it. 

## Package Versions

* Spyder: 3.2.7
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-03-08 08:49
As far as I'm aware, I haven't experienced the same trouble with all the same Spyder, Python, Qt/PyQt, OS, and main dependency versions as you, other than if I quit it when the kernel was hung or something. Does it always happen, or only sometimes? When did it start? Are you sure you aren't leaving any variable explorer windows open when closing Spyder (this prevents it from closing all the way)? What happens if you try enabling single instance mode? Starting with ``spyder --debug`` and then quitting from the Anaconda prompt? Anything unusual about your system, environment, or install?

**Comment by Khris777** [comment] 2018-03-08 11:14
Trying to do `spyder --debug` in the windows command prompt returns `error: no such option: --debug`.

**Comment by Khris777** [comment] 2018-03-08 11:22
> What happens if you try enabling single instance mode?

I already have been in single instance mode the entire time as I just noticed. I disabled it but the behaviour stays the same.

**Comment by CAM-Gerlach** [comment] 2018-03-08 11:39
Thanks for all the information.

> I do have a variable explorer tab in my setup (not a separate window) but I was expecting that when I'm closing down Spyder the console also closes down and with it the variable explorer.

Nope. As I stated above, this keeps Spyder open. Therefore, this issue appears to be a duplicate of my #5696 ; however, the fix seems rather simple. I'll take a look at it sometime soon, since its bothered me for a while now.

**Closed by CAM-Gerlach** 2018-03-08 11:39 UTC
Labels: status:Awaiting Followup

**Comment by ccordoba12** [comment] 2018-03-08 15:19
> Until last update it seemed to happen occassionally

This is another side effect of Tornado 5. Please downgrade to Tornado 4.5.3 to temporarily fix it with:

    conda install tornado=4.5.3

**Comment by CAM-Gerlach** [comment] 2018-03-08 19:24
Hmm, interesting...I've always had it stay open whenever I left a Var explorer window open.

**Comment by ccordoba12** [comment] 2018-03-08 19:31
This also happens when you have a view a VarExp viewer open, but @Khris777 didn't mention that.

**Comment by CAM-Gerlach** [comment] 2018-03-08 19:36
Oh, sorry. I misread the OP's statement that I quoted above

> I do have a variable explorer tab in my setup (not a separate window) but I was expecting that when I'm closing down Spyder the console also closes down and with it the variable explorer.

and didn't see the part that they didn't have it as a separate window. My mistake,  sorry; thanks for the catch. So is this a duplicate of #6627 or a separate issue that should be reopened?

**Comment by ccordoba12** [comment] 2018-03-08 19:41
It's a different issue but not something we can fix in Spyder. It's been worked out in `jupyter_client`.

**Comment by CAM-Gerlach** [comment] 2018-03-08 19:43
Thanks
