### ISSUE TITLE
I didn't konw what happende.

### ISSUE THREAD

**Issue by lzpeter** [spyder-ide/spyder#6067] opened 2017-12-27 07:47 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "D:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 125, in to_text_string
    return unicode(obj, encoding)
  File "D:\Anaconda2\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7: character maps to <undefined>
Traceback (most recent call last):
  File "D:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "D:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 125, in to_text_string
    return unicode(obj, encoding)
  File "D:\Anaconda2\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7: character maps to <undefined>
Traceback (most recent call last):
  File "D:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 2

**Comment by CAM-Gerlach** [comment] 2017-12-27 08:05
Thanks for reporting. Looks like something in your dataframe, most probably the column names, contains non-ASCII characters, which Python 2 doesn't like. If you can provide us with more details and a minimal reproducible example of a dataframe and any further actions required to trigger the problem, as well as the requested Python, Spyder, etc. versions and information about your platform then we might be able to fix it on our end. Otherwise, we'll have to close this issue after a week (7 days). In any case, Python 2 does not deal well with Unicode/non-ASCII characters, so to fix this for now, either don't use any non-ASCII characters anywhere in your data/dataframe (generally a good idea when possible for interoperability), or upgrade to Python 3 with Unicode/UTF-8 which has vastly improved internationalization support. Best of luck!

**Comment by CAM-Gerlach** [comment] 2018-01-04 11:45
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-01-04 11:45 UTC
Labels: status:AwaitingFollowup
