### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by theumairahmed** [spyder-ide/spyder#6650] opened 2018-03-07 16:16 UTC
I have reset the Spyder IDE and now changing the syntax color from Tools->Preferences is causing an internal problem with Spyder.

**Comment by ccordoba12** [comment] 2018-03-07 16:18
Thanks for reporting. This is a duplicate of issue #6519, which will be fixed in our next release.

**Closed by ccordoba12** 2018-03-07 16:18 UTC
