### ISSUE TITLE
Real-time code style analysis not working

### ISSUE THREAD

**Issue by StefanWaal** [spyder-ide/spyder#10356] opened 2019-10-04 11:04 UTC
### Issue Report Checklist

* [ X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ X] Tried basic troubleshooting (if a bug/error)
    * [ X] Restarted Spyder
    * [ X] Reset preferences with ``spyder --reset``
    * [ X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ X] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
A colleague of mine wrote some code and since he is leaving I'm responsible for taking it over. The code wasn't PEP8 compliant, so one of my first actions was to turn on Preferences -> Editor -> Code Introspection/Analysis -> Real-time code style analysis.
It works like it should for all files I have but one. None of the warnings show up. Eventually I was able to shorten my code to the following:
```
# Test

x = ["ë"]
```
If one of the following gets removed the warnings start showing up again:

- The comment at the top
- The empty line between the comment and the list
- The ë gets removed (replacing it with an e also works)

Here's Spyder without the warnings:
![image](https://user-images.githubusercontent.com/36788716/66202718-bceb2f00-e6a6-11e9-9973-94e153119d7c.png)

Here's Spyder after removing the ë and with the warning:
![image](https://user-images.githubusercontent.com/36788716/66202771-d7250d00-e6a6-11e9-964c-c6b2cc75d4fd.png)

### What steps reproduce the problem?

1. Turn on Real-time code style analysis
2. Write the following code (no newline at end of file):
```
# Test

x = ["ë"]
```
### What is the expected output? What do you see instead?
Expectation: E391 for having no white line at the end

Reality: no warnings

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies
```
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by scott-8** [comment] 2019-10-04 14:28
For what it's worth, I can't reproduce this in 4.0.0 beta5.

**Comment by ccordoba12** [comment] 2019-10-04 20:04
Thanks @scott-8, me neither. Our code completion and linting architecture was completely rewritten for Spyder 4, so fixing this issue seems to be a side effect of that.

Spyder 4 will be released in a month or so.

**Closed by ccordoba12** 2019-10-04 20:04 UTC

**Comment by tangxianrong** [comment] 2020-05-14 01:35
I used spyder version 4.1.2 and it didn't work, too.

I changed to 4.0.1 by conda install and it worked.
