### ISSUE TITLE
Spyder does not run when installed via Anaconda in Linux

### ISSUE THREAD

**Issue by eterray** [spyder-ide/spyder#21493] opened 2023-11-05 21:52 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description:  Installed most recent version of anaconda.  Spyder (5.4.3) appears in anaconda-navigator (ver 2.5.0)  but when run (also from cmd line) hangs at step "Loading Code Analysis" with message to console "from Icc Profile: failed minimal tag size sanity". 
The OS is Linux 5.15.0-88-generic #98~20.04.1-Ubuntu SMP x86_64 GNU/Linux, and python 3.1.5 was installed by anaconda.

conda update spyder  stops after trying a number (4-5?) of repos.

### What steps reproduce the problem?

1. trying to run spyder from anaconda-navigator or the command line
2. 
3. 

### What is the expected output? What do you see instead?
spyder initialization hangs at "Loading Code Analysis" step and gives the console message:  "from Icc Profile: failed minimal tag size sanity".

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

conda list | grep anaconda  returns
_anaconda_depends         2023.09              py311_mkl_1  
anaconda-anon-usage       0.4.2           py311hfc0e8ea_0  
anaconda-catalogs         0.2.0              py311h06a4308_0  
anaconda-client           1.12.1               py311h06a4308_0  
anaconda-cloud-auth       0.1.3           py311h06a4308_0  
anaconda-navigator        2.5.0            py311h06a4308_0  
anaconda-project          0.11.1            py311h06a4308_0  
fonts-anaconda            1                                 h8fa9717_0  

conda list | grep spyder returns
pyls-spyder               0.4.0                   pyhd3eb1b0_0  
spyder                       5.4.3              py311h06a4308_1  
spyder-kernels         2.4.4              py311h06a4308_0  

* Spyder version: 5.4.3
* Python version: 3.1.1.5
* Qt version:  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5   (????)
* PyQt version:   jupyter QtConsole 5.4.2   (????)
* Operating System name/version:  Linux 5.15.0-88-generic #98~20.04.1-Ubuntu SMP x86_64 GNU/Linux

### Dependencies

```
Sorry - I don't know how to get this info because spyder does not run
```

**Comment by ccordoba12** [comment] 2023-11-06 14:27
Hey @eterray, thanks for reporting. Please open a terminal and run

    spyder --reset

and try again. That could help to solve your problem.

**Comment by ekerins** [comment] 2023-11-06 17:34
Same problem as described above running on Ubuntu 22.04. Also reproducible when running directly from command line. Running as root works but not as an ordinary user. I have run spyder --reset but problem persists. Debug log file attached.

conda list | grep spyder
pyls-spyder               0.4.0              pyhd3eb1b0_0  
spyder                    5.4.3            py38h06a4308_1  
spyder-kernels            2.4.4            py38h06a4308_0

[spyder-debug.log](https://github.com/spyder-ide/spyder/files/13270570/spyder-debug.log)

**Comment by eterray** [comment] 2023-11-07 21:36
Hi Carlos -

I tried  "spyder --reset"  but the problem persists.  Spyder initialization still hangs at the "Loading Code Analysis" step - so this seems to be the same problem encountered by  Eamonn Kerins.

Invoking spyder as a user via sudo also does not work (I have not tried a root shell).

I have not been able to find an initialization script (does one exist?), but as a temporary fix (just to get going) would it be possible simply to remove that step from the initialization ?

Thanks,

      -  E. Terray
________________________________

**Comment by ccordoba12** [comment] 2023-11-07 23:03
Hey guys, I think this is very similar to issue #21172, which is going to be fixed in Spyder 5.5.0, to be released later today.

So, please run the following commands in two or three days to see if it solves the problem for you:

    conda create -n spyder-env -c conda-forge python=3.10 spyder=5.5
    conda activate spyder-env
    spyder

Let us know if works for you.

**Comment by ekerins** [comment] 2023-11-13 10:33
That works for me - thanks!

**Comment by ccordoba12** [comment] 2023-11-13 17:10
Thanks for the confirmation @ekerins! Closing then as a duplicate of issue #21172.

**Closed by ccordoba12** 2023-11-13 17:10 UTC
Labels: status:Awaiting Followup
