### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ZihanRen** [spyder-ide/spyder#10295] opened 2019-09-24 15:05 UTC
Spyder has encountered an internal problem
I can't see variables in variable explorer
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by goanpeca** [comment] 2019-09-24 16:23
@ZihanRen please fill in the issue template that was there when you opened the issue

**Comment by ccordoba12** [comment] 2019-09-24 16:49
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

@goanpeca, this problem was caused by our incorrect usage of Numpy's internal API but it was fixed several months ago.

**Closed by ccordoba12** 2019-09-24 16:49 UTC
Labels: status:Awaiting Followup

**Comment by goanpeca** [comment] 2019-09-24 17:00
>@goanpeca, this problem was caused by our incorrect usage of Numpy's internal API but it was fixed several months ago.

Got it!
