### ISSUE TITLE
Spyder fail launch from Anaconda Navigator

### ISSUE THREAD

**Issue by jjschier** [spyder-ide/spyder#6147] opened 2018-01-06 15:39 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 418, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 841, in load_module
  File "<frozen importlib._bootstrap_external>", line 700, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ImportError: No module named 'pylint'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.2.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.10.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  4.3.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.1.0 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-06 17:17
Thanks for reporting; this is a probable duplicate of #5391 . As the error message suggests, it seems ``pylint`` is not installed or at least detected in your current environment, and I don't see it listed under your dependencies. Therefore, you should install it to presumably fix this problem; if that doesn't do it, it is very likely something is wrong with your Anaconda environment or install, which is completely outside of Spyder's control. Accordingly, this issue will be closed.

**Closed by CAM-Gerlach** 2018-01-06 17:17 UTC
