### ISSUE TITLE
Spyder doesn't show complete object documentation.

### ISSUE THREAD

**Issue by ghltshubh** [spyder-ide/spyder#4792] opened 2017-07-22 19:09 UTC
## Description of your problem
I am trying to get documentation of some objects by pressing cmd+I in spyder but it gives a one line definition of the object instead of a detailed one. I am using python 3.5 and spyder 3.1.4. For e.g. documentation for OLS object looks like 
**What steps will reproduce the problem?**

1. Type name of any class object
2. Press Cmd+I
3. Look for documentation in Help

**What is the expected output? What do you see instead?**
Expected a full documentation about the object. Got a one line documentation describing what the object does. No mention of parameters etc.

**Please provide any additional information below**
It looks like 
<img width="742" alt="screen shot 2017-07-22 at 1 24 39 pm" src="https://user-images.githubusercontent.com/16928813/28494073-2b55eecc-6ee9-11e7-9ea7-aac8a4a7b886.png">

but should look like this(image from an online video)
<img width="475" alt="screen shot 2017-07-22 at 1 25 28 pm" src="https://user-images.githubusercontent.com/16928813/28494075-34418ca8-6ee9-11e7-96b8-9c5236ad5145.png">

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: macOS 10.12.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ghltshubh** [comment] 2017-07-22 19:21
<img width="742" alt="screen shot 2017-07-22 at 1 24 39 pm" src="https://user-images.githubusercontent.com/16928813/28494070-1ad8236c-6ee9-11e7-8c06-6164c762e36e.png">

**Comment by jitseniesen** [comment] 2017-07-22 20:52
So what do you do different to get the first (incorrect) picture as opposed to the second (correct) picture?

**Comment by ghltshubh** [comment] 2017-07-22 20:56
The second picture is from an online video.

**Comment by Prikers** [comment] 2017-07-23 19:14
Is this because `OLS` uses `__doc__` rather than the "triple quote" docstring (`"""..."""`) for the class definition? Anytime it uses `__doc__`, trying to get the documentation from Cmd+I brings the problem. 
For instance:
```python
from statsmodels.regression.linear_model import OLS
OLS() # Cmd + I on this --> problem (OLS uses __doc__) 
OLS.score() # Cmd + I on this --> no problem (OLS.score uses triple quote docstring)
```
From the console `OLS?` brings the full documentation though.

**Comment by ccordoba12** [comment] 2017-07-23 23:37
@Prikers, that could be it, thanks! We'll take a look at this after we release 3.2

**Comment by bcolsen** [comment] 2019-04-08 15:22
Duplicate of #5522

**Closed by bcolsen** 2019-04-08 15:22 UTC
Labels: component:Help, type:Bug
