### ISSUE TITLE
IPython console won't open, but normal Python console does.

### ISSUE THREAD

**Issue by NArtin** [spyder-ide/spyder#2814] opened 2015-11-17 17:38 UTC
I've been using Spyder on this computer (Ubuntu 15.04) for about 6 months. Recently I decided to try out an IDE called yHat Rodeo. This required me to install/update some packages, like jupyter (works fine) and updating to IPython 4. Since then Spyder no longer works with the IPython console giving this error when I attempt to open one:

    traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config,
    but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist',
    'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.

The regular console works fine, but obviously I would much rather use the IPython console. Any idea? I tried uninstalling/reinistalling both spyder and ipython, installing qtconsole and almost all other suggested remedies I could find, nothing has worked so far, and I'm hoping there is a more specific remedy for this. Thanks.

**Comment by ccordoba12** [comment] 2015-11-17 19:33
This is an installation problem and not a bug in Spyder. If I remember correctly, this problem is caused because you have IPython 3 and qtconsole 4 in your system.

I don't know you installed those packages, nor Spyder, but the easiest solution would be to run

    pip install -U jupyter

or

    conda install jupyter

**Comment by NArtin** [comment] 2015-11-17 22:03
I get the same error after attempting that. Currently when I enter into IPython in my terminal it shows IPython 4.0.0. Importing qtconsole and executing qtconsole.__version__ shows '4.1.0'. So it seems that both are updated. Is it possible that spyder is attempting to use an older version of IPython behind the scenes?

**Comment by ccordoba12** [comment] 2015-11-18 00:07
Yep, that's the problem. But you need to find it and remove it in your system. We can't do anything else to help you, sorry :-s

**Comment by ccordoba12** [comment] 2015-11-18 14:00
Closing, as this is not a Spyder bug per se, sorry :-)

**Closed by ccordoba12** 2015-11-18 14:00 UTC

**Comment by NArtin** [comment] 2015-11-18 20:23
No worries, I just reverted to rolled back my IPython and qtconsole versions and everything is working again.
