### ISSUE TITLE
KeyError when completion plugin is missing

### ISSUE THREAD

**Issue by Akshatabn** [spyder-ide/spyder#6490] opened 2018-02-21 17:57 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "G:\ana\lib\site-packages\spyder\utils\introspection\manager.py", line 235, in show_object_info
    self.plugin_manager.send_request(info)
  File "G:\ana\lib\site-packages\spyder\utils\introspection\manager.py", line 95, in send_request
    plugins = [self.plugins[desired]]
KeyError: 'fallback'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-21 18:18
Thanks for reporting. We'll fix this error in our next release.

**Comment by csabella** [comment] 2018-03-02 01:47
Duplicate of #4938.

**Closed** 2018-03-02 01:48 UTC
Labels: component:Editor, resolution:Duplicate, type:Bug
