### ISSUE TITLE
Assigning ctrl-alt-shift-l causes a UnicodeEncodeError

### ISSUE THREAD

**Issue by andyDoucette** [spyder-ide/spyder#7046] opened 2018-05-01 03:11 UTC
File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/plugins/shortcuts.py", line 890, in apply_settings
    self.table.save_shortcuts()
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/plugins/shortcuts.py", line 760, in save_shortcuts
    shortcut.save()
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/plugins/shortcuts.py", line 498, in save
    set_shortcut(self.context, self.name, self.key)
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/config/gui.py", line 100, in set_shortcut
    CONF.set('shortcuts', '%s/%s' % (context, name), keystr)
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/config/user.py", line 449, in set
    self._save()
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/config/user.py", line 114, in _save
    _write_file(fname)
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/site-packages/spyder/config/user.py", line 111, in _write_file
    self.write(configfile)
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/configparser.py", line 919, in write
    self._sections[section].items(), d)
  File "/home/andromodon/.anaconda3/envs/snoutScan/lib/python3.6/configparser.py", line 931, in _write_section
    fp.write("{}{}\n".format(key, value))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc20' in position 33: surrogates not allowed

### What steps will reproduce the problem?

Assigning ctrl-alt-shift-l to a shortcut caused some unicode something to show up and then error.

**Comment by ccordoba12** [comment] 2018-05-01 15:28
Thanks for reporting. We'll take a look at it in a future release.

**Comment by CAM-Gerlach** [comment] 2018-05-06 19:27
@andyDoucette  Was unable to reproduce assigning ``Show toolbars`` to Ctrl-Shift-Alt-L ; it assigned, saved, and worked just fine in Spyder 3.2.8 on Py 3.6.4 , Qt/PyQt 5.6 on Windows 8.1. Therefore, might it have to do with the specific command you're trying to assign to, instead of the shortcut used?

**Comment by andyDoucette** [comment] 2018-05-10 06:14
Hmm....  I'm nervous to try it again since it completely hosed my spyder installation and I spent 2 hours trying to get my config back the way I liked it...  There might have been a windows or a function key in there too.  If I get some time later I'll try again, otherwise feel to close until someone else reports it.

**Comment by CAM-Gerlach** [comment] 2018-05-10 14:38
> completely hosed my spyder installation and I spent 2 hours trying to get my config back the way I liked it...

If this happens again, just run ``spyder --reset`` from the command line to fix it, or if you don't want to recreate your settings, edit the config file manually (should be under ``.spyder-py3/spyder.ini`` in your home directory).

> There might have been a windows or a function key in there too.

Possibly, but it could have just been a specific command you were setting the shortcut for. Do you remember which?

**Comment by CAM-Gerlach** [comment] 2018-05-20 22:03
If we don't have a clear way to reproduce this, we won't be able to fix it, sorry. Please let us know the answer to the above questions if you're able so we can track it down. Thanks.

**Closed by CAM-Gerlach** 2018-05-20 22:03 UTC
Labels: status:Awaiting Followup
