### ISSUE TITLE
1

### ISSUE THREAD

**Issue by zzdbirdsfly** [spyder-ide/spyder#14143] opened 2020-11-04 12:31 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\spyder\plugins\ipythonconsole.py", line 709, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\spyder\plugins\ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1018, in connect_client_to_kernel
    stderr_file)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1420, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\jupyter_client\manager.py", line 220, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\site-packages\jupyter_client\launcher.py", line 131, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\zzdong\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.9
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.2.0 (OK)
pycodestyle >=2.3:  2.6.0 (OK)
pygments >=2.0   :  2.7.2 (OK)
pandas >=0.13.1  :  1.1.3 (OK)
numpy >=1.7      :  1.19.2 (OK)
sphinx >=0.6.6   :  3.2.1 (OK)
rope >=0.9.4     :  0.18.0 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  1.6.2 (OK)
cython >=0.21    :  0.29.21 (OK)
qtconsole >=4.2.0:  4.7.7 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by dalthviz** [comment] 2020-11-04 14:58
Hi @zzdbirdsfly please update to the latest Spyder version 3 available running from an Anaconda prompt (with your env activated) something like `conda install spyder=3.3.6`

Duplicate of #5257

**Closed by dalthviz** 2020-11-04 14:58 UTC
Labels: resolution:Duplicate

**Comment by zzdbirdsfly** [comment] 2020-11-04 15:03
thanks, i just figure it out. (spyder --reset)  command is useful in Anaconda prompt
