### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by IamDavyG** [spyder-ide/spyder#7325] opened 2018-06-21 17:40 UTC
### What steps will reproduce the problem?

Connect to a Linux Spyder remote kernel from a Windows Spyder client

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1060, in create_client_for_kernel
    password)
  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1782, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "C:\ProgramData\Anaconda2\lib\site-packages\qtconsole\base_frontend_mixin.py", line 57, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-06-21 21:16
This is a duplicate of issue #7082.

**Closed by ccordoba12** 2018-06-21 21:16 UTC
