### ISSUE TITLE
macOS, Spyder: Text selecting throwing Spyder error 

### ISSUE THREAD

**Issue by KaterinaTik** [spyder-ide/spyder#10800] opened 2019-11-21 23:13 UTC
When I trying to select some text (sometimes it is reproducible at first attempt) ,Spyder throws an error

Here is the recording

Here are logs:
 File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1217, in handle_hover_response
    at_point=self._last_point)
  File "//anaconda3/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 634, in show_hint
    inspect_word=inspect_word)
  File "//anaconda3/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 474, in _check_signature_and_format
    name_plus_char = inspect_word + open_func_char
TypeError: can only concatenate tuple (not "str") to tuple
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "//anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3716, in main
    mainwindow = run_spyder(app, options, args)
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3598, in run_spyder
    app.exec_()
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 921, in handle_response
    handler(params)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1224, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 952, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)

**Comment by ccordoba12** [comment] 2019-11-21 23:15
Duplicate of #10752

**Closed by ccordoba12** 2019-11-21 23:15 UTC
