### ISSUE TITLE
Spyder 4.2.3 spydata

### ISSUE THREAD

**Issue by yvespayette** [spyder-ide/spyder#14913] opened 2021-03-11 22:32 UTC
### What steps will reproduce the problem?

Cannot save spydata anymore...
Makes Kernel restart.

nothing special in data.

### Traceback
```python-traceback
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 115, in comm_channel_manager
    yield
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 194, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 253, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'47a4205c72fd4a058d3bb43bcfc8e1b2': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 511, in save_data
    error_message = self.shellwidget.save_namespace(self.filename)
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 174, in save_namespace
    return self.call_kernel(
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 194, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\p0111964\documents\wpy64\python-3.8.5.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 118, in comm_channel_manager
    self._comms[comm_id]['comm']._send_channel = (
KeyError: '706bed2582ae11ebaaca401c8327e38c'
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.8.5
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.5.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.3.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.5.3 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  53.0.0 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  0.10.3 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.1 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.0 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)

# Spyder plugins:
spyder_notebook                 :  0.3.0 (OK)
```

**Comment by ccordoba12** [comment] 2021-03-16 02:01
Hey @yvespayette, thanks for reporting. This seems like a duplicate of issue #14886. It'll be fixed in our next version (4.2.4), to be released in the next couple of days.

**Closed by ccordoba12** 2021-03-16 02:01 UTC
