### ISSUE TITLE
Spyder in Windows 10 is not working correctly

### ISSUE THREAD

**Issue by Sarwat-Fatima** [spyder-ide/spyder#2633] opened 2015-08-23 08:54 UTC
I am trying to open the editor in Windows 10 but every time it crashes and the Spyder reset settings is also not solving this problem! Any solutions?

**Comment by vchollati** [comment] 2015-08-23 13:11
Same problem here on Windows 7.

**Comment by insolor** [comment] 2015-08-23 13:19
Windows 10, Python 3.4, Sypder works without any problems, both Spyder 2.3.5.2 and Spyder 3.0.0 beta1.

**Comment by vchollati** [comment] 2015-08-23 14:21
@insolor how did you install the 3.0.0 beta?

**Comment by insolor** [comment] 2015-08-23 14:49
@vchollati,
1. Download spyder-3.0.0b1.zip archive from [Releases](https://github.com/spyder-ide/spyder/releases)
2. Unpack
3. Run command `python setup.py install`
4. Run python\scripts\spyder.bat
Note: it also needs PyQt to be installed.
![spyder3 0 0b1](https://cloud.githubusercontent.com/assets/2442833/9428673/2069feaa-49bf-11e5-99c3-9a64d82d2b29.png)

**Comment by ccordoba12** [comment] 2015-08-23 15:08
@Sarwat-Fatima, if you're using Anaconda, then you'll have to wait until I update PyQt4 on Windows for it.

I say it because the PyQt4 version available in Anaconda is really old and it could be the culprit of these problems on Windows 10.

**Comment by vchollati** [comment] 2015-08-23 15:15
@ccordoba12 thanks for the update, same problem using anaconda on windows 7.

**Comment by ccordoba12** [comment] 2015-08-23 15:16
Windows 7 shouldn't be a problem. Please open a terminal (i.e. `cmd.exe`) and run

    spyder --reset

then start Spyder again to see if that helps.

**Comment by vchollati** [comment] 2015-08-23 15:22
![image](https://cloud.githubusercontent.com/assets/6666812/9428812/369a1f10-4989-11e5-85f2-17de74f066cc.png)

still doesn't work, sorry

**Comment by stonebig** [comment] 2015-08-24 17:41
@vchollati you may be more precise on the versions you try to use:
- Python (2.7 or 3.4)
- Ipython 3.0.0 or 3.2.1 or Jupyter 4.0.3 or ...
- Spyder 2.3.5.2 or 3.0.0.b1 or ...
- Anaconda or ...

**Comment by vchollati** [comment] 2015-08-24 18:36
@stonebig-
Anaconda distro, python 2.7.8, jupyter 4.0 and spyder 2.3.* but tried the 3.0 beta as well to no avail.

**Comment by stonebig** [comment] 2015-08-24 19:14
The Jupyter4.0  team mentioned in their last week web video meeting, that they had a lot of:
- Python2.7 bugs,
- Windows bugs.

You may stay on Ipython 3.2.1 a few more days.

**Comment by ccordoba12** [comment] 2015-08-24 19:16
Besides, at this point Spyder 2.3.5.2 is not compatible with Jupyter 4 (but 2.3.6 will be).

@vchollati, please stop stealing this bug. You mentioned you were on Windows 7, and this bug is about Windows 10. So, please open a new bug about your problem.

**Comment by vchollati** [comment] 2015-08-24 22:41
@ccordoba12 sorry, that was not my intention. First time reporting a bug and was just answering questions. Apologies.

**Comment by ccordoba12** [comment] 2015-08-25 02:03
@vchollati, don't worry. Just open a new issue for your problem :-)

Truth is I use Spyder on Windows 7 on a regular basis and I haven't seen any problem there, so we need to get deeper with what's happening in your case.

**Comment by sho-87** [comment] 2015-09-08 19:46
I'm having the same problem. Spyder isn't useable on windows 10 because it only launches about 10% of the time. The rest of the time I get the error above

I'm using the latest release of anaconda, python 2.7, 32bit

**Comment by sho-87** [comment] 2015-09-28 19:00
@ccordoba12 any progress on the Anaconda PyQT4 update?

**Comment by Davo36** [comment] 2015-12-13 08:31
I got an email from Anaconda 2.4.1 is available!

And so used the suggested upgrade commands.

Now Spyder won't start.

It was working a few hours ago.  This is on Windows 10.  

So for me it seems to be an upgrade issue.  IPython, Jupyter etc. work.

**Comment by jdweaver** [comment] 2016-04-23 20:26
I'm having a similar issue: Windows 10 64 bit version, Sypder 2.3.8. Jupyter 4.2.0 works but Sypder won't launch.

**Comment by rmalshe** [comment] 2016-06-04 19:39
Here is what happens when I run spyder -- reset. 
Unfortunately, this is still not solved for me. 

C:\Users\rmalshe>spyder --reset
Traceback (most recent call last):
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script
.py", line 1, in <module>
    from spyderlib import start_app
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\start_app.py", line 13, in <module>
    from spyderlib.config import CONF
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\config.py", line 736, in <module>
    subfolder=SUBFOLDER, backup=True, raw_mode=True)
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\userconfig.py", line 215, in __init__
    self.load_from_ini()
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\userconfig.py", line 260, in load_from_ini
    self.readfp(configfile)
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\ConfigParser.py",
 line 324, in readfp
    self._read(fp, filename)
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\ConfigParser.py",
 line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: C:\Users\rmalshe\.spyde
r2\spyder.ini
        [line 333]: u'_/switch to outl'

**Comment by Nodd** [comment] 2016-06-07 12:04
@rmalshe You already posted the exact same message in #2698. When no opened issue corresponds to your problem, please create a new one, it'll be easier for everyone ! :smiley:

**Comment by rmalshe** [comment] 2016-06-08 04:06
Sorry, I am a little new to this, but soon I will learn all the norms :) 
Yes indeed, the issue is solved and closed. I was not able to figure out why it was happening. 
Perhaps this may have happened when I tried to update anaconda, or some other python package, and in the process, Spyder had stopped working.

**Comment by collawolley** [comment] 2016-07-23 12:42
Hi, I have a problem with spyder. I have been using it for several months on windows 10 without any problem until 3 days ago when it just wouldn't come up again.
I have tried to re install but i keep getting the same error and same same issue of not starting up. To be specific, it worked immediately after I uninstall anaconda and reinstalled anaconda but when i restarted my laptop for work the following day, Spyder again refused to come up and I keep getting the same error messages as before.
Please see the error message below for both for starting spyder as well as attempting to rreset. The issue has been the same ever.

C:\Users\user>spyder --reset
Traceback (most recent call last):
  File "C:\Users\user\Anaconda2\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 78, in <module>
    import bs4
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

C:\Users\user>spyder
Traceback (most recent call last):
  File "C:\Users\user\Anaconda2\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 78, in <module>
    import bs4
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'


I will appreciate any help in resolving this issue.
Thanks

**Comment by RobertCordery** [comment] 2016-08-19 17:52
I had the same problem on my surface pro 3 and my dell desktop after installing the new Windows 10 update.  Running Spyder once as administrator seemed to solve the problem for me.

**Comment by Matou1** [comment] 2016-09-09 10:35
I tried Anaconda 64-bit under Windows10 and Spyder stopped launching after some time. Someone on another board mentioned switching to the 32-bit version to fix the problem, but it also stopped working just now.
I didn't realize at first, but both versions stopped working right after running pip install html5lib. I ran pip uninstall html5lib, and now Spyder launches just fine.
Hope this helps!

**Comment by ccordoba12** [comment] 2016-10-15 21:54
This should be fixed after we released Spyder 3.0 because it supports Qt 5, and Qt 5 supports Windows 10.

So to everyone involved in this issue, please update Spyder and Qt 5 :-)

**Closed by ccordoba12** 2016-10-15 21:54 UTC
Labels: OS-Windows, Type-Bug

**Comment by hmttn** [comment] 2016-11-06 12:19
I installed  anaconda 4.2 in Win 10, but Jupyter Qtconsole  Did'nt work.
the error message :
"this application failed to start because  it could not find or load the Qt platform plugin "windows" in "".
Reinstalling the application may fix this problem." 
conda info:
[info.txt](https://github.com/spyder-ide/spyder/files/573802/info.txt)
conda list:
[list.txt](https://github.com/spyder-ide/spyder/files/573803/list.txt)

**Comment by maishuguang** [comment] 2016-11-16 03:39
My solution is to delete the folder: %userprofile%/.spyder/spyder.lock, then Spyder can be started normally.

**Comment by ferreat** [comment] 2016-11-21 16:13
I have just installed the latest Anaconda 4.2.0 (Python 3.5 - 64 bit) on Windows 10. Windows stops Spyder from running and reports an error has happened.

**Comment by kjoth** [comment] 2016-11-28 08:35
I just installed on Windows 10, but Anaconda navigator has been stopped due to Python stopped working. But Spyder, Jupiter and Ipython works individually. Problem with Anaconda Navigator. Any steps to solve this Navigator problem?

**Comment by ccordoba12** [comment] 2016-11-28 13:16
@kjoth, Navigator is going to receive an update in a couple of weeks that should solve your problem :-)

**Comment by Godsownboy** [comment] 2016-12-14 06:47
Hello ccordoba12,
I must say you are doing a marvelous Job!
I was enjoying Anaconda on my computer then all of a sudden I started getting the error message 'python has stopped working'. This only happens when I run Spyder and try to open a file. I then decided to reinstall Anaconda but it wouldn't install correctly(this is a different issue altogether!).
To get away from this problem I decided to install standard python 3.5, then install matplotlib and Spyder using pip... but now I still get the same 'python has stopped working' error message.
![image](https://cloud.githubusercontent.com/assets/24444714/21172156/8fd895e6-c1d0-11e6-9c00-12314bcc6715.png)
This is what happens when I click Debug:
![image](https://cloud.githubusercontent.com/assets/24444714/21172250/1a16aff4-c1d1-11e6-8c40-ad7725ba3e23.png)
Please help. Thanks

**Comment by ccordoba12** [comment] 2016-12-14 16:31
@Godsownboy, I really don't what's happening in your case :-/

**Comment by Godsownboy** [comment] 2016-12-14 16:47
@ccordoba12 I don't know if the pictures  are clear enough. the second picture gives some insight to the problem: An unhandled win32 exception occured in pythonw.exe[11016]. Should I uninstall visual studio?
Anyway, I give up!

**Comment by ccordoba12** [comment] 2016-12-14 16:52
Some people have reported this problem, but I don't know the cause of it.

Installing Visual Studio is not probably useful...

**Comment by Godsownboy** [comment] 2016-12-14 16:53
uninstall*

**Comment by Godsownboy** [comment] 2016-12-15 13:33
I finally got around this problem... so far so good, spyder 3.0.2 + python 3.5 is now working without glitches on my computer. 
I uninstalled python 3.5 64bit and installed python 3.5 32bit and the problem disappeared.
Python 3.5 64bit was the villain!

**Comment by ccordoba12** [comment] 2016-12-15 16:25
@Godsownboy, glad you were able to figure it out your problem!

**Comment by martmists** [comment] 2017-03-29 19:55
Having the same issue here

- Windows 10, latest
- Python 3.6 64 bit
- Latest PyQt5 

I'm not really eager to downgrade to 32 bit as I'll have to reinstall a lot of dependencies for my projects, such as ImageMagick

**Comment by Zach988** [comment] 2017-04-19 13:43
I had this same problem with Anaconda 4.2.0 64-bit on Windows 10. I used pip to upgrade Spyder to version 3.1.3. Works fine now.

**Comment by jbanegas** [comment] 2018-01-11 04:30
I had this same problem with Win10 64-bits and Anaconda3-5.0.1, the problem was that I installed the Anaconda package in a different device than C:
So, I reinstalled and now works fine.

**Comment by LA1824** [comment] 2018-06-28 02:34
![loading editor problem](https://user-images.githubusercontent.com/33568902/42009670-0bfc2588-7aa9-11e8-87a4-50d5274980a9.png)
I have been getting this window, but the spyder interface is not loading up. 
Anaconda Navigator 1.8.7
Spyder 3.2.8
Windows 10 64-bit
It seems the spyder is running, but it doesn't show on screen.
Tried everything reset, installing pyqt5, show console, re-installation, spyder upgrade.
Tried opening it with terminal and it doesn't throw any error, rather it showed me the same screen attached image.

**Comment by ccordoba12** [comment] 2018-06-28 02:36
@LA1824, this could be a problem with your firewall/antivirus. Please deactivate them and try again.

**Comment by LA1824** [comment] 2018-06-28 09:14
@ccordoba12 thank you.Tried it, But it doesn't show up as well.

**Comment by ccordoba12** [comment] 2018-06-28 21:57
@LA1824, I'm out of ideas, sorry.

**Comment by martmists** [comment] 2018-06-29 12:34
Did your PC hit a RAM/CPU limit? That could cause Qt to not load and hang.

**Comment by SergioEduardoAntonio** [comment] 2018-11-10 01:20
I'm trying to solve two kinds of bugs on my Anaconda/Spyder instalation.
First one the Syder (Python 3.7) dont save files.
The second one is that I can't get help inside Editor when I use Ctrl + I. Please if some one knows how to solve both bugs let me know. 
I'm using Windows 10 Pro 64bits and the last 64bit version of the Anaconda Navigator.
Regards,
