### ISSUE TITLE
Variable explorer causes a significant slow down while debugging

### ISSUE THREAD

**Issue by DediGadot** [spyder-ide/spyder#2396] opened 2015-05-03 12:15 UTC
## Description
If debugging while 'Variable Explorer' is visible, there is a significant slowdown in spyder, i.e. pressing ctrl+f10 results in ~5-10 seconds of freeze, and only then the line get executed.

If, on the other hand, one debugs while only the 'object explorer' or 'file explorer' is visible, no such phenomena occurs.

 * *What steps will reproduce the problem?*
1. Create a python script that loads 'large' variables, i.e. ~5-10GB in RAM
2. Set a breakpoint, start debugging with ctrl-f5, while 'variable explorer' is visible
3. When reaching a breakpoint, press ctrl-f10 once with 'variable explorer' visible and another time with something else (say, 'object explorer') visible

* *What is the expected output? What do you see instead?*
Debugging performance not affected whether I view variable explorer or not

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.3
* Qt Version    :  4.8.1, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.1 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  0.25.0 (OK)

**Comment by Nodd** [comment] 2015-05-03 19:08
What happens if you try to disable the variable explorer auto-update ?

**Comment by ccordoba12** [comment] 2015-05-04 23:25
@DediGadot, we need a reproducible example to test things in our side :-)

**Comment by ccordoba12** [comment] 2015-07-14 06:57
Closing because of lack of further info

**Closed by ccordoba12** 2015-07-14 06:57 UTC
Labels: bug, Variable-Explorer
