### ISSUE TITLE
Add support for Spyder to run on WSL

### ISSUE THREAD

**Issue by angrosamund** [spyder-ide/spyder#13034] opened 2020-06-16 04:33 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I tried launching Spyder from a fresh Anaconda install, but it crashed almost immediately upon launching. I'm not too sure how to interpret the error message I got, and how to solve it. Would appreciate some advice on this, thank you!

### What steps reproduce the problem?

1.  installed X11 for WSL 
2. append the following to .bashrc file
DISPLAY=:0
export DISPLAY
LIBGL_ALWAYS_INDIRECT=1
Export LIBGL_ALWAYS_INDIRECT
3.  installed Anaconda 2020.02 on Ubuntu 20.04 LTS
4. launch spyder

### What is the expected output? What do you see instead?

I see the spyder start-up screen that says 'initialising', but then it crashes almost soon after and I see the following error message. 

### Paste Traceback/Error Below (if applicable)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-apeiyin'
[10430:10448:0616/122439.101045:FATAL:udev_linux.cc(29)] Check failed: 0 == ret (0 vs. -22)
#0 0x7ff83d3860be <unknown>
#1 0x7ff83d3986c2 <unknown>
#2 0x7ff83ce44c18 <unknown>
#3 0x7ff83dc5654b <unknown>
#4 0x7ff83d3fd9e3 <unknown>
#5 0x7ff83d3a1090 <unknown>
#6 0x7ff83d3a26e8 <unknown>
#7 0x7ff83d3a2a7b <unknown>
#8 0x7ff83d3a4132 <unknown>
#9 0x7ff83d3a0438 <unknown>
#10 0x7ff83d3bce9b <unknown>
#11 0x7ff83ceb70dc <unknown>
#12 0x7ff83ceb72de <unknown>
#13 0x7ff83d3d5678 <unknown>
#14 0x7ff83d3d16db <unknown>
#15 0x7ff856f16609 start_thread
#16 0x7ff856e32103 clone

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7
* Qt version: 5.9.7
* PyQt version: 
* Operating System name/version: Windows 10 (but using Ubuntu 20.04 LTS for WSL)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment] 2020-06-16 16:24
Hi @angrosamund, we currently do not provide testing on WSL on Linux so things are most likely not going to work in the setup you describe.

**Comment by ccordoba12** [comment] 2020-06-16 17:40
Duplicate of #13023.

@angrosamund, please do not open new issues about the same problem.

**Closed by ccordoba12** 2020-06-16 17:40 UTC
Labels: type:Feature
