### ISSUE TITLE
Custom layout issues upon update

### ISSUE THREAD

**Issue by johallorb** [spyder-ide/spyder#15333] opened 2021-04-18 15:43 UTC
### What steps will reproduce the problem?

[0] Rearrange panes to create custom layout
[1] Save custom layout in Spyder 4
[2] Update to Spyder 5
[3] Attempt to use custom layout in Spyder 5
[4] Warning! Custom layout not found
[5] Restore defaults
[6] Delete custom layout
[7] Rearrange panes to create custom layout
[8] Save custom layout with same name as previously
[9] Spyder has encountered an interal problem!

Please also note that the link to the "Troubleshooting Guide" in the issue reporter is broken. It directs to https://docs.spyder-ide.org/current/first-steps.html which is not found. It appears the correct link is https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

Below is the internal console error traceback (redacted for privacy):
### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\[user]\anaconda3\lib\site-packages\spyder\plugins\layout\container.py", line 131, in <lambda>
    triggered=lambda: self.show_save_layout(),
  File "C:\Users\[user]\anaconda3\lib\site-packages\spyder\plugins\layout\container.py", line 307, in show_save_layout
    self.save_current_window_settings('layout_{}/'.format(index),
AttributeError: 'LayoutContainer' object has no attribute 'save_current_window_settings'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.4.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment] 2021-04-19 01:29
Hey @johallorb, thanks for reporting. This is a duplicate of issue #15129 and it'll be fixed in our next version (5.0.1), to be part of Anaconda shortly.

**Closed by ccordoba12** 2021-04-19 01:29 UTC
