### ISSUE TITLE
a problem when switching to python2

### ISSUE THREAD

**Issue by beignner** [spyder-ide/spyder#12860] opened 2020-05-26 06:51 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
a problem when using ythoninterpret to switch to python2

**Comment by steff456** [comment] 2020-05-26 17:25
Hi @beignner,

Can you please give us a step-by-step for us to be able to reproduce your issue?

**Comment by steff456** [comment] 2020-06-03 02:42
Closing this issue because there was not a response after a week.

**Closed by steff456** 2020-06-03 02:42 UTC
Labels: status:Awaiting Followup
