### ISSUE TITLE
Anaconda does not include the Spyder 3.3 for Win-64

### ISSUE THREAD

**Issue by VanitarNordic** [spyder-ide/spyder#7511] opened 2018-07-20 07:08 UTC
hello,

You have published the Spyder 3.3 fat time ago, but the Anaconda does not publish this version for the Win-64 package. Do you think there is a reason behind this? 

if there is no reason, I'll create a custom package myself for everyone to use

**Comment by ccordoba12** [comment] 2018-07-20 13:39
Duplicate of #7496. We don't know why new packages haven't been uploaded, sorry.

**Closed by ccordoba12** 2018-07-20 13:39 UTC

**Comment by ccordoba12** [comment] 2018-07-20 13:42
> if there is no reason, I'll create a custom package myself for everyone to use

conda-forge packages are already available.

**Comment by VanitarNordic** [comment] 2018-07-20 14:42
The problem is although I have installed the Spyder 3.3 on an environment, but when I run it, it loads 3.2.8 from unknown source which I don't know where it is. I have activated and type inside an environment, this behavior is weird.

**Comment by ColWriter** [comment] 2018-07-20 18:41
Interesting system - no  comments - no reason - no information - no answers.

**Comment by ccordoba12** [comment] 2018-07-20 18:55
Please continue the discussion in #7496.
