### ISSUE TITLE
error on launch of Spyder

### ISSUE THREAD

**Issue by tamtwill** [spyder-ide/spyder#7633] opened 2018-08-07 00:56 UTC
When I open Spyder, I immeadiately get en error.  That's all there is to it.  Recently upgraded Anaconda via the Anaconda Navigator enviroment manager window.  Other than that, no changes to the system, which had been stable and error free.
I have not added, changes or updated packages via Pip since I know that can cause issues.  Error from "Issue Report" dialog:

  File "/home/tam/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'

**Comment by ccordoba12** [comment] 2018-08-07 19:38
Thanks for reporting. This is a duplicate of issue #7403 and it'll be fixed in our next release.

**Closed by ccordoba12** 2018-08-07 19:38 UTC
