### ISSUE TITLE
Replace "\" by "\\"

### ISSUE THREAD

**Issue by badiay** [spyder-ide/spyder#5386] opened 2017-10-03 17:21 UTC
## Description

**What steps will reproduce the problem?**

1.  Tried to replace all "\" by "\\"
2.  Crash 
3. my code : 
" 
import pandas as pd 

a = pd.read_csv("C:\\Users\badia\Desktop\PSB\s1\Python\Exercices\data.csv")
"

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\badia\Anaconda3\lib\site-packages\spyder\widgets\findreplace.py", line 504, in replace_find_all
    self.replace_find(focus_replace_text, replace_all=True)
  File "C:\Users\badia\Anaconda3\lib\site-packages\spyder\widgets\findreplace.py", line 449, in replace_find
    if len(re.findall(pattern, cmptxt2)) > 0:
  File "C:\Users\badia\Anaconda3\lib\re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
  File "C:\Users\badia\Anaconda3\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\badia\Anaconda3\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\badia\Anaconda3\lib\sre_parse.py", line 847, in parse
    source = Tokenizer(str)
  File "C:\Users\badia\Anaconda3\lib\sre_parse.py", line 231, in __init__
    self.__next()
  File "C:\Users\badia\Anaconda3\lib\sre_parse.py", line 245, in __next
    self.string, len(self.string) - 1) from None
sre_constants.error: bad escape (end of pattern) at position 0

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Win

**Comment by ccordoba12** [comment] 2017-10-04 06:21
Thanks for reporting. We'll fix this problem is a future release.

**Comment by timhoffm** [comment] 2017-10-30 17:02
Note: This happens if the user has activated regular expressions. `\` is of course not a valid expression to search for.

One part of the problem is that the user was probably not aware of this fact. This is addressed by the above PR [#5614].

The second aspect is that acually performing the search on an invalid regexp raises the above error. One can debate how to handle this. In the simplest case, one could catch `re.error` for the call of `re.findall()` in `FindReplace.replace_find()`. Alternatively, one could deactivate the replace buttons for invalid regular expressions. Personally, I'd think that the former solution is enough if the user has already feedback through PR [#5614].

**Comment by ccordoba12** [comment] 2017-10-30 18:21
@timhoffm, I agree that catching `re.error` is the best that we can do. Could you implement that in another PR, please?

**Closed** 2017-11-01 15:03 UTC
Labels: component:Editor, type:Bug
