### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by hafez-ahmad** [spyder-ide/spyder#13899] opened 2020-10-01 03:43 UTC
I am using python 3.8 with miniconda. two days ago, I installed a new updated spyder then I am facing it when I tried to open a new project, and then it is constantly happening. I am using spyder for 4 years without any problems with anaconda distribution.

![image](https://user-images.githubusercontent.com/20365917/94762760-5e948180-03ca-11eb-9edc-d92db1d43b2d.png)

  File "c:\users\hafez\miniconda3\lib\site-packages\spyder\plugins\explorer\widgets\explorer.py", line 136, in icon
    icon = im icon = ima.get_icon_by_extension_or_type(fname,
  File "c:\users\hafez\miniconda3\lib\site-packages\spyder\utils\icon_manager.py", line 438, in get_icon_by_extension_or_type
    icon_by_extension = icon(LANGUAGE_ICONS[extension], scale_factor)
  File "c:\users\hafez\miniconda3\lib\site-packages\spyder\utils\icon_manager.py", line 403, in icon
    return qta.icon(*args, **kwargs)
  File "c:\users\hafez\miniconda3\lib\site-packages\qtawesome\__init__.py", line 150, in icon
    return _instance().icon(*names, **kwargs)
  File "c:\users\hafez\miniconda3\lib\site-packages\qtawesome\iconic_font.py", line 302, in icon
    parsed_options.append(self._parse_options(specific_options,
  File "c:\users\hafez\miniconda3\lib\site-packages\qtawesome\iconic_font.py", line 352, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "c:\users\hafez\miniconda3\lib\site-packages\qtawesome\iconic_font.py", line 383, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid icon name "markdown" in font "mdi"

**Comment by dalthviz** [comment] 2020-10-01 05:01
Hi @hafez-ahmad checking your traceback this is a duplicate of #13875 please update `qtawesome` to `1.0.1` or downgrade it to `0.7.3`. You can use something like `conda install -c conda-forge qtawesome=1.0.1` (since you have this error I'm guessing that you are using the conda-forge `qtawesome` package 1.0.0). Let us know if that helps

**Closed by dalthviz** 2020-10-01 05:01 UTC
Labels: resolution:Duplicate
