### ISSUE TITLE
Internal problem presented

### ISSUE THREAD

**Issue by DigitalRadiohead** [spyder-ide/spyder#21617] opened 2023-12-15 02:12 UTC
### What steps will reproduce the problem?

Please see issue #21610 on github, I've created a new environment, but I still get this problem. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\hammo\anaconda3\envs\spyder-cf-311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000023322CB2DF0> still has pending operation at deallocation, the process may crash
```

## Versions

* Spyder version: 5.5.0  (conda)
* Python version: 3.11.6 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.20.0 (OK)
keyring >=17.0.0                 :  24.3.0 (OK)
nbconvert >=4.0                  :  7.12.0 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
paramiko >=2.4.0                 :  3.3.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.5 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.3 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.3.0 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  None (NOK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2023-12-15 17:07
Hey @DigitalRadiohead, thanks for reporting this problem again. I'm going to close this issue as a duplicate of #21610 but with my message I'm acknowledging that this problem also appears with the our latest version when installed from Conda-forge.

**Closed by ccordoba12** 2023-12-15 17:07 UTC
