### ISSUE TITLE
Connecting to kernel...

### ISSUE THREAD

**Issue by willianads** [spyder-ide/spyder#18209] opened 2022-06-08 13:24 UTC
### What steps will reproduce the problem?

conda create -n ML python==3.8 
conda activate ML
pip install --upgrade tensorflow
pip install spyder

When I call for spyder, its open as if should, but in Ipython Console stay permanently showing the message: Connecting to kernel...

### Traceback
```python-traceback
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\willi\Miniconda3\envs\ML\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\willi\Miniconda3\envs\ML\lib\site-packages\jupyter_client\channels.py", line 113, in run
    loop.close()
  File "C:\Users\willi\Miniconda3\envs\ML\lib\asyncio\proactor_events.py", line 679, in close
    signal.set_wakeup_fd(-1)
ValueError: set_wakeup_fd only works in main thread
```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.8.0
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.0 (OK)
keyring >=17.0.0              :  23.5.1 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.3.1 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.0.1 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by arturdaraujo** [comment] 2022-06-08 13:50
I had the same issue. Try downgrading jupyter_client=7.3.1
https://github.com/spyder-ide/spyder/issues/18174#issuecomment-1147759762

**Comment by dalthviz** [comment] 2022-06-08 15:13
Hi all, I'm closing this as a duplicate of #18174 if you want to add further information please post a comment there, thanks!

**Closed by dalthviz** 2022-06-08 15:13 UTC
Labels: resolution:Duplicate
