### ISSUE TITLE
Index column not showing correctly in variable explorer for 4.1.5

### ISSUE THREAD

**Issue by yomoko** [spyder-ide/spyder#13822] opened 2020-09-20 20:20 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After I use 4.1.5, all the displayed dates (index column) are wrong in variable explorer, but if I copy whole data to excel, they are displayed correctly. I think it's because no matter how you sort the index column, they are not being sorted at all. So while other columns are changing, index column remains the same. 

### What steps reproduce the problem?

1.  Just create a dataframe with a few columns and a few rows.
2.  Then sort the index column, or other columns.
3.  Index column is the same, while other columns are different

### What is the expected output? What do you see instead?
Expected output should be the data with the correct index(which is date in my case) But they're displayed incorrectly now. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-09-21 01:33
Hey @yomoko, thanks for reporting. This is a duplicate of issue #13544.

We'll try to fix it in a future release.

**Closed by ccordoba12** 2020-09-21 01:33 UTC
