### ISSUE TITLE
When use pandas command "pd.read_table" with "header=None" ,spyder will crash when run it

### ISSUE THREAD

**Issue by cheny8907** [spyder-ide/spyder#2694] opened 2015-09-14 08:52 UTC
## Description

**What steps will reproduce the problem?**

1. import pandas as pd
2. x=pd.read_table('a file path',header=None)
3. run it 

**What is the expected output? What do you see instead?**
whenever run this command with "header=None",spyder will crash

**Please provide any additional information below**
I test the same command in the Ipython QTconsole ,it works OK.
so I wonder it may be a bug in spyder
Besides I use the latested verson anaconda(python 2.7)

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment] 2015-09-14 17:15
Thanks for reporting. This is a duplicate of issue #2654.

**Closed by ccordoba12** 2015-09-14 17:15 UTC
Labels: duplicate
