### ISSUE TITLE
Unable to visualize Dataframe spyder virtual environment

### ISSUE THREAD

**Issue by paolosanchez** [spyder-ide/spyder#13682] opened 2020-09-01 15:22 UTC
### What steps will reproduce the problem?

On spyder installed in a virtual environment, when I try to open a DataFrame, using the variable explorer the issue occurs.
Can not visualize the Dataframe. The Dataframe is saved correctly when run on the console.  

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  [Previous line repeated 993 more times]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 493, in _info_axis
    return getattr(self, self._info_axis_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas\_libs\properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by steff456** [comment] 2020-09-01 17:16
Hi @paolosanchez,

This is a duplicate of #13620, please go to this thread and verify if your virtualenv pandas version matches with the spyder-kernels pandas version.

Thanks for reporting!

**Comment by paolosanchez** [comment] 2020-09-01 17:51
Hi @steff456,
still having issues. How can I check the spyder-kernels pandas version?
When I check the version of the library, in and outside Spyder is the same '1.1.1'.
Also just reinstalled spyder-kernels-1.9.4. Can you walk me through a little bit to solve it?

**Comment by steff456** [comment] 2020-09-02 04:18
Hi @paolosanchez,

Are you using just one conda environment in your machine? If not, did you change the python executable in the configurations of Spyder?

**Comment by paolosanchez** [comment] 2020-09-02 09:14
Hi Stephannie,

I am not using just one conda environment, yet I did  change the python
executable in the configurations of Spyder to the environment python.exe,
and activate the environment every time.

Paolo

**Comment by steff456** [comment] 2020-09-02 22:31
Can you please see that the version of pandas is the same in the environment you are launching it vs the environment that you have under the python executable?

You can verify that via `conda list` after activating the environment and searching in the list for `pandas`.

Please let me know if they are the same or if they don't match

**Comment by ccordoba12** [comment] 2023-02-26 15:31
Closing due to lack of response.

**Closed by ccordoba12** 2023-02-26 15:31 UTC
Labels: status:Awaiting Followup
