### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by vkmaheshbhat** [spyder-ide/spyder#7451] opened 2018-07-14 20:02 UTC
### What steps will reproduce the problem?

System: Ubuntu 18.04 64 bit, Spyder 3.3.0, Python 3.6. I start spyder either by clicking the icon on the launcher or from terminal. When spyder starts, issue reporter launches and I see this error message in it:
```
  File "/home/mahesh/.local/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
```
This happens every time and I see no other error messages on the terminal. Also, the functioning of Spyder is not affected by this in any way.

### Traceback
```python-traceback
  File "/home/mahesh/.local/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-23-generic

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.5 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.28.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-14 23:28
This is a duplicate of issue #7403 and it'll be fixed in our next release.

**Closed by ccordoba12** 2018-07-14 23:28 UTC
