### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by giorgecaique** [spyder-ide/spyder#6943] opened 2018-04-11 15:14 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 131, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 2325010502424
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1551, in analysis_results_changed
    other_editorstack.set_analysis_results(index, results)
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1717, in set_analysis_results
    self.data[index].set_analysis_results(analysis_results)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1582, in todo_results_changed
    other_editorstack.set_todo_results(index, results)
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1725, in set_todo_results
    self.data[index].set_todo_results(todo_results)
IndexError: list index out of range
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 131, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 2325010395000
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1551, in analysis_results_changed
    other_editorstack.set_analysis_results(index, results)
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1717, in set_analysis_results
    self.data[index].set_analysis_results(analysis_results)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1582, in todo_results_changed
    other_editorstack.set_todo_results(index, results)
  File "C:\Users\giorge.luiz\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1725, in set_todo_results
    self.data[index].set_todo_results(todo_results)
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-04-11 15:15
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-04-19 14:53
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-04-19 14:53 UTC
Labels: status:Awaiting Followup
