### ISSUE TITLE
IPython crash because of problems with pyzmq

### ISSUE THREAD

**Issue by Amal-Vincent** [spyder-ide/spyder#2187] opened 2015-02-21 11:44 UTC
![screenshot from 2015-02-20 18 39 43](https://cloud.githubusercontent.com/assets/11134381/6313981/0a6e84e8-b9ed-11e4-9181-ead734742aae.png)

**Comment by ccordoba12** [comment] 2015-02-21 14:44
Please go to

    Help > Optional dependencies

press the button called *Copy to clipboard* and paste its contents here

**Comment by ccordoba12** [comment] 2015-02-21 14:45
I also need to know what Spyder version you're using.

**Comment by Amal-Vincent** [comment] 2015-02-21 17:20
IPython >=0.13  :  2.4.1 (OK)
matplotlib >=1.0:  1.4.0 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
psutil >=0.3    :  2.1.1 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
zmq >=2.1.11    :  14.5.0 (OK)

**Comment by Amal-Vincent** [comment] 2015-02-21 17:21
version 2.3.2, thanks for helping me out again, I was the guy who had the issue after octave installation

**Comment by SylvainCorlay** [comment] 2015-02-21 17:30
The reason is that the path to the zmq module changed between IPython 1.0 and 2.0. Now zmq is its own separate package. 

We already take this into account in `ipythonconsole.py`
```python
try: # IPython = "<=2.0"
    from IPython.external.ssh import tunnel as zmqtunnel
    import IPython.external.pexpect as pexpect
except ImportError:
    from zmq.ssh import tunnel as zmqtunnel      # analysis:ignore
    try:
        import pexpect                           # analysis:ignore
    except ImportError:
        pexpect = None                           # analysis:ignore
```

We should do the same with `start_ipython_kernel`.

**Comment by SylvainCorlay** [comment] 2015-02-21 17:42
Hum this is weird. I am surprised by your zmq version number. It might be a flaw in the way dependencies are detected. You probably don't have python zmq installed. 

If you are running on the ubuntu packages, try installing the `python-zmq` package:

```bash
sudo apt-get install python-zmq
```

**Comment by Amal-Vincent** [comment] 2015-02-21 18:06
nope still the same problem, should I restart after this?

**Comment by Amal-Vincent** [comment] 2015-02-21 18:07
resetting spyder  does fix it, but that is a temporary solution, the problem return after a restart, or when I run a python file

**Comment by SylvainCorlay** [comment] 2015-02-21 18:24
I don't think that you need to restart your system. 
You did not specify whether you were using the ubuntu packages or some distribution like Anaconda?

If you are still having the issue, printing the exception message could help troubleshooting.

(Whatever is in the `except` statement is to support IPython 0.13 and is not expected to work for you, hence you could print the exception that is raised in the try statement.) 

You could just keep 
```
from IPython.kernel.zmq.kernelapp import IPKernelApp
```

**Comment by Amal-Vincent** [comment] 2015-02-21 19:08
I am using it from anaconda

**Comment by SylvainCorlay** [comment] 2015-02-21 19:36
Then the deb package we just installed is just useless.

**Comment by Amal-Vincent** [comment] 2015-02-23 16:42
k so what do u suggest

**Comment by SylvainCorlay** [comment] 2015-02-25 16:19
Sorry for the late reply. I cannot reproduce your problem hence a good way to troubleshoot would be to get the (first) exception error message. 

In `start_ipython_kernel.py` please replace
```python
# Fire up the kernel instance.
try:
    from IPython.kernel.zmq.kernelapp import IPKernelApp  # 1.0
except:
    from IPython.zmq.ipkernel import IPKernelApp  # 0.13  (analysis:ignore)
```
with 
```python
from IPython.kernel.zmq.kernelapp import IPKernelApp
```
and report the error message that you get in Spyder. (The first version with the try-catch is meant to support IPython 0.13 anyway.)

**Comment by Amal-Vincent** [comment] 2015-03-03 08:53
5b96aece304a1422224f9a41b228416028f9ba26b0d1058f400200f06a589949
Traceback (most recent call last):
File "/home/amal/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 183, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "/home/amal/anaconda/lib/python2.7/site‑packages/IPython/kernel/__init__.py", line 4, in 
from . import zmq
File "/home/amal/anaconda/lib/python2.7/site‑packages/IPython/kernel/zmq/__init__.py", line 16, in 
from .session import Session
File "/home/amal/anaconda/lib/python2.7/site‑packages/IPython/kernel/zmq/session.py", line 224, in 
class Session(Configurable):
File "/home/amal/anaconda/lib/python2.7/site‑packages/IPython/kernel/zmq/session.py", line 344, in Session
auth = Instance(hmac.HMAC)
AttributeError: 'module' object has no attribute 'HMAC'

**Comment by ccordoba12** [comment] 2015-03-12 01:06
This seems to be (very strange) problem with zmq, according to your last error report. So I'm closing this because it's not a Spyder error.

**Closed by ccordoba12** 2015-03-12 01:06 UTC
