### ISSUE TITLE
Python console

### ISSUE THREAD

**Issue by FSJMGitHub** [spyder-ide/spyder#3623] opened 2016-10-31 12:43 UTC
## Description of your problem
Python console do not work quite well.  
- The prompt (>>>) emerges after the first output. If the output should be the sequence "0 ,1, 3, 4" then, in each row it appears "0 ,>>> 1, 3, 4"; but no ">>>" at the end.
- After a script in the editor window is executed, any othe script or comand will keep on delivering the same result of the previous script

**What steps will reproduce the problem?**
1. N/A
2. N/A
3. N/A

**What is the expected output? What do you see instead?**
N/A

**Please provide any additional information below**
N/A
![2016-10-31_spyder_bug](https://cloud.githubusercontent.com/assets/17232354/19854555/db9f12f8-9f6f-11e6-8ae0-ef378e7d1863.jpg)

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
* Operating system: Windows 7 Enterprise 64 bits

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-31 14:18
Thanks for reporting. Closing as a duplicate of issue #3533.

**Closed by ccordoba12** 2016-10-31 14:18 UTC
