### ISSUE TITLE
Code not executing in new console and problem plotting figure

### ISSUE THREAD

**Issue by JimHokanson** [spyder-ide/spyder#2539] opened 2015-07-15 04:30 UTC
I just installed a fresh version of Anaconda with Spyder 2.3.5.2 and Python 3.4.3 64 bits, Qt 4.8.6, PyQt4 (API v2) 4.10.4 on Windows

When I first ran a script it prompted me for console settings which I accidentally accepted right away. I then went into the settings and changed the run settings to "execute in a new dedicated Python console"

This seemed to have no effect.

I then ran my code in the current console and had a breakpoint put in with:
```python
import pdb
pdb.set_trace()
```

I then called some plot code:
```python
import matplotlib.pyplot as plt
plt.plot(data)
plt.show()
```

The figure showed up with the typical icon (IPython) but failed to respond ("Windows not responding").

After restarting and playing around with the settings many times I couldn't get the execution to work as desired or for the plot to not hang.

I then reset Spyder settings via the shortcut that was installed. When I started Spyder again, I was again prompted for execution preferences, and this time I selected the new console right away. This time the code executed as desired and when I plotted the figure showed up with a Spyder icon that I've never seen before (but it works). Looking at the settings (preferences -> run) they look incorrect, almost as if they are no longer referencing the settings that are being used internally.

**Comment by ccordoba12** [comment] 2015-07-15 04:34
Sorry, it's not possible to show plots in our Python or IPython consoles while debugging. We hope to solve this problem next year when some improvements are made to Jupyter.

For a workaround see https://github.com/spyder-ide/spyder/issues/620#issuecomment-74596841.

Closing as a duplicate of issue #620 itself :-)

**Closed by ccordoba12** 2015-07-15 04:34 UTC
Labels: duplicate

**Comment by JimHokanson** [comment] 2015-07-15 05:34
Oops, I shouldn't have thrown two issues together. What about the execution settings? This seems to not function properly. Let me know if I should open a separate issue.

**Comment by JimHokanson** [comment] 2015-07-15 09:43
I rewrote just the preferences portion in #2540
