### ISSUE TITLE
Output of a core.relational.Equality bad to read

### ISSUE THREAD

**Issue by update-freak** [spyder-ide/spyder#13538] opened 2020-08-14 20:59 UTC
## Problem Description
If the code for Sympy is executed as shown in the following example, the output is difficult to read.
While confirming the code
C:\texlive\2020\bin\win32\latex.exe 
and
C:\texlive\2020\bin\win32\dvipng.exe
is executed.

![bild](https://user-images.githubusercontent.com/40196995/90291820-fcff6e80-de80-11ea-9179-c8fb90af8bbc.png)

```
import sympy as sp
y = sp.Function('y')
t = sp.symbols('t')
dgl = sp.Eq(y(t).diff(t), y(t))
```

### What steps reproduce the problem?
1. Copy and execute the code

### What is the expected output? What do you see instead?
I expect that the output can be read easily.

## Versions
* Spyder version: 4.1.4
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10
* Latex: TeX Live 2020

**Comment by juanis2112** [comment] 2020-08-15 00:08
Hi @update-freak! Thanks for reporting this. I confirmed this behavior, looks like some kind of bug. We will fix it for our next release.

**Comment by ccordoba12** [comment] 2020-08-15 19:35
@update-freak, what's your Sympy version?

**Comment by ccordoba12** [comment] 2020-08-15 19:43
@update-freak, sorry, I think the problem in your case is that didn't initialize the Sympy's printing system before starting to work with it.

In other words, you need to run the following code if you want to see Sympy objects printed correctly:

```python
from sympy import init_printing
init_printing()
```

Please try that and let us know if it works for you.

**Comment by update-freak** [comment] 2020-08-15 20:51
My Sympy version is 1.19.1.

With the following code

`import sympy as sp
sp.init_printing()
y = sp.Function('y')
t = sp.symbols('t')
dgl = sp.Eq(y(t).diff(t), y(t))`

nothing happens after typing dgl in the consol

**Comment by ccordoba12** [comment] 2020-08-15 22:05
@dalthviz, could you check what happens in this case on Windows?

**Comment by dalthviz** [comment] 2020-09-10 15:50
Also the latest SymPy version seems tobe 1.6.2 (that's the one I used to do the testing)

**Comment by ccordoba12** [comment] 2020-09-10 21:42
Thanks @dalthviz for your help!

I'm closing this issue because we were not able to reproduce this problem. @update-freak, most probably the Latex binaries (latex.exe and dvipng.exe) are not in your PATH.

**Closed by ccordoba12** 2020-09-10 21:42 UTC
Labels: component:IPython Console, type:Bug
