### ISSUE TITLE
dataframe series show no data

### ISSUE THREAD

**Issue by lhx121** [spyder-ide/spyder#6606] opened 2018-03-05 13:18 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 516, in createEditor
    readonly=readonly)
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1327, in setup
    remote=remote)
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1275, in __init__
    title)
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1152, in __init__
    minmax=minmax)
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 110, in __init__
    self.set_data(data)
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 158, in set_data
    self.set_size_and_type()
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 178, in set_size_and_type
    for index in range(start, stop) ]
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 178, in <listcomp>
    for index in range(start, stop) ]
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 78, in __getitem__
    return getattr(self.__obj__, key)
  File "/Users/weidian/anaconda/envs/tensorflow/lib/python3.6/site-packages/pandas/core/generic.py", line 206, in _constructor_sliced
    raise AbstractMethodError(self)
pandas.core.common.AbstractMethodError: This method must be defined in the concrete class of Series

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-03-05 14:23
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2018-03-06 02:47
Thanks for reporting. This looks like a duplicate of #6258 , and thus will be closed. If you can provide more details to help us fix it for you, please do so on that issue.

**Closed by CAM-Gerlach** 2018-03-06 02:47 UTC
Labels: status:Awaiting Followup
