### ISSUE TITLE
Spyder IPython console does not report exceptions when using %run magic command

### ISSUE THREAD

**Issue by jpblackburn** [spyder-ide/spyder#4187] opened 2017-02-22 16:25 UTC
## Description of your problem
When you run a script using the IPython magic command %run in the Spyder IPython console, exceptions in the script are not shown in the IPython terminal.  

**What steps will reproduce the problem?**

1. Create a python script "valueErrorTest.py" with the single line "raise ValueError('This is a test')"
2. At the IPython console, type "%run valueErrorTest.py"

**What is the expected output? What do you see instead?**

The expected output is the current output of following these steps:
1. In a terminal, open an IPython console
2. Type, "%run valueErrorTest.py"

This expected output is an IPython record that shows that a value error was thrown and provides traceback information.  What I see instead is a return to the IPython prompt without acknowledging that an error was raised.  

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 8.1
* IPython: 5.1.0
My python environment is Anaconda.

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by bruot** [comment] 2017-02-24 05:10
I can reproduce the error with Windows 10 and Anaconda 1.4.3.

Oddly, when I launch ipython.exe located in C:\Users\UserName\Anaconda3\Scripts and type "%run valueErrorTest.py", the error is displayed as expected.

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by dalthviz** [comment] 2017-02-24 14:43
@jpblackburn @bruot thanks for reporting. @ccordoba12 I think this is a duplicate of issue #4116

**Comment by ccordoba12** [comment] 2017-02-24 14:47
You're right, thanks for noticing it :-)

**Closed** 2017-02-24 14:48 UTC
Labels: component:IPython Console, resolution:Duplicate, type:Bug
