### ISSUE TITLE
Ignore pyflakes Fxxx warnings? 

### ISSUE THREAD

**Issue by Ubaldo79** [spyder-ide/spyder#19392] opened 2022-09-10 19:50 UTC
I have noticed that in Spyder one can ignore `pydocstyle `errors/warnings (`Wxxx, Exxx`) by specifying them in **Preferences/Completion and linting/Code style and formatting/Ignore the following errors or warnings** but not `pyflakes `warnings (`Fxxx`), see here:

https://www.flake8rules.com/

Is there a way to ignore also `Fxxx `warnings?  

In my understanding that is possible only through `flake8` and therefore I was wondering if there is a plan of directly considering `flake8 ` in `Spyder `instead of separately considering `pydocstyle `and `pyflakes`.

**Comment by Ubaldo79** [comment] 2022-09-10 20:06
Oh, just found that it is a duplicate: https://github.com/spyder-ide/spyder/issues/16249

**Comment by ccordoba12** [comment] 2022-09-12 02:30
Yep, closing as a duplicate of that issue.

**Closed by ccordoba12** 2022-09-12 02:30 UTC
