### ISSUE TITLE
getting error in profiler

### ISSUE THREAD

**Issue by prisar** [spyder-ide/spyder#6275] opened 2018-01-23 09:33 UTC
## Description

**What steps will reproduce the problem?**

1. Open spyder
2. Write some code
3. Press F10

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "C:\ProgramData\Anaconda3\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "C:\ProgramData\Anaconda3\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "C:\ProgramData\Anaconda3\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.spyder-py3\\profiler.results'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK

**Comment by csabella** [comment] 2018-01-23 14:31
This is a duplicate of #6220.  The good news is that it will be fixed in the next release coming out soon.  :-)

One question though -- did you press the Stop button after pressing F10?  The reason for the error is that the profiler file isn't being created, which on #6220 was because the profiler was being ended before it could finish.

**Closed** 2018-01-23 15:16 UTC
Labels: resolution:Duplicate
