### ISSUE TITLE
Format code problem

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#16257] opened 2021-08-21 04:01 UTC
I find that the problem of format code hasn't been solved yet.

https://user-images.githubusercontent.com/82581024/130309902-d630f79b-c743-44e2-a82e-2dcdb8f675e3.mp4

## Versions

* Spyder version: 5.1.1 None
* Python version: 3.9.5 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by ccordoba12** [comment] 2021-08-21 17:08
Hey @Vincent0706, thanks for reporting. This is a duplicate of issue #16180 and it'll fixed in our next version (5.1.2), to be released shortly.

**Closed by ccordoba12** 2021-08-21 17:08 UTC
