### ISSUE TITLE
Dead  lock on find and replace

### ISSUE THREAD

**Issue by AntonSkorohodov** [spyder-ide/spyder#14144] opened 2020-11-04 14:51 UTC
### What steps will reproduce the problem?

When you try to find and replace a text1 in your code with new text2 that consist of text1 (for example text1 = "params" text2 = "new_params") then you press "Replace All", Spyder enters in endless loop replacing same part of the text "params" over and over again until Spyder crushes.
Thank you,
Anton.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by dalthviz** [comment] 2020-11-04 19:52
Hi @AntonSkorohodov could you provide a more specific example of a code snippet that triggers the error? (I was unable to reproduce this). Maybe a GIF could help us too to understand better the situation. Thanks!

**Comment by AntonSkorohodov** [comment] 2020-11-05 08:40
For some reason I could not reproduce this bug too, maybe I've been mistaken. Sorry for your time.

**Comment by dalthviz** [comment] 2020-11-05 14:59
Thanks for the info, I will close this one then but feel free to reopen if you manage to get more info :)

**Closed by dalthviz** 2020-11-05 14:59 UTC
Labels: status:Awaiting Followup
