### ISSUE TITLE
ImportError: cannot import name 'quick_guide' from IPython.core.usage

### ISSUE THREAD

**Issue by H-Shen** [spyder-ide/spyder#4382] opened 2017-04-22 07:10 UTC
## Description of your problem

**What steps will reproduce the problem?**

Initiate Spyder or restart IPython Kernel or create a new IPython Console

**What is the expected output? What do you see instead?**

Some prompting information of version and current time at the beginning of the IPython Console.
A black screen with nothing in the console and some error messages popped from Internal Console.
A python file named **traitlets.py** was opened in the editor.

**Please provide any additional information below**
I press **Enter** and make the prompts and cursor be shown in the IPython console again.
I have reset Spyder from shell once to see if it would work normally but nothing changed.

## Versions and main components

* Spyder Version:3.1.3
* Python Version:3.6.1
* Qt Version:5.6.2
* PyQt Version:5.5.6
* Operating system:Ubuntu 16.04 xenial x86_64 Linux 4.4.0-72-generic

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-04-23 23:51
This is a duplicate of issue #4170, and it'll be fixed in Spyder **3.1.4**

**Closed by ccordoba12** 2017-04-23 23:51 UTC
Labels: resolution:Duplicate
