### ISSUE TITLE
DeprecationWarning from Shapely

### ISSUE THREAD

**Issue by joooeey** [spyder-ide/spyder#16939] opened 2021-12-02 16:23 UTC
### What steps will reproduce the problem?

Whenever I work with `shapely.geometry.MultiPolygon`, I get an annoying Deprecation warning that __len__ is not supported. That clutters the console a lot because it gets printed twice for every console input as long as there is a MultiPolygon assigned to a name.

Example:
```
from shapely.geometry import Polygon, MultiPolygon

t1 = Polygon(((1, 2), (3, 4), (5, 6)))

t2 = Polygon(((7, 8), (9, 0), (1, 2)))

mp = MultiPolygon((t1, t2))

Output from spyder call 'get_namespace_view':
/home/lukas/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py:108: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  return len(item)

Output from spyder call 'get_var_properties':
/home/lukas/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/spyder_kernels/console/kernel.py:615: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  return len(var)

print("hi")
hi

Output from spyder call 'get_namespace_view':
/home/lukas/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py:108: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  return len(item)

Output from spyder call 'get_var_properties':
/home/lukas/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/spyder_kernels/console/kernel.py:615: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  return len(var)

del mp

print("hi")
hi

print("hi")
hi
```

**Comment by dalthviz** [comment] 2021-12-02 17:08
Hi @joooeey thank you for the feedback. I'm closing this as duplicate of https://github.com/spyder-ide/spyder/issues/16854 . If you have any more feedback please put it there. Thanks!

**Closed by dalthviz** 2021-12-02 17:08 UTC
Labels: resolution:Duplicate
