### ISSUE TITLE
Spyder closes by itself with no error message whenever open/save file

### ISSUE THREAD

**Issue by kgita** [spyder-ide/spyder#8164] opened 2018-10-29 19:58 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Everytime I tried to open or save a file, spyder closes by itself and no error message was displayed.

**Comment by ccordoba12** [comment] 2018-10-29 23:57
This seems like a duplicate of issue #3903. Please look there for a possible solution.

**Closed by ccordoba12** 2018-10-29 23:57 UTC

**Comment by kgita** [comment] 2018-10-30 00:07
I did try those as instructed in issue #3903 before but still getting the same issue:
- reinstalling the Ananconda, 
- conda update qt pyqt spyder to update Spyder
- and I don't have Dell's backup and recovery installed so this should not be the error

**Comment by ccordoba12** [comment] 2018-10-30 15:35
I'm very sorry but that's all we know about this problem.
