### ISSUE TITLE
Error with the Rich library in the Mac app

### ISSUE THREAD

**Issue by seanmag** [spyder-ide/spyder#21173] opened 2023-07-22 21:01 UTC
### What steps will reproduce the problem?

```python
from manim import *


class CreateCircle(Scene):
    def construct(self):
        circle = Circle()  # create a circle
        circle.set_fill(PINK, opacity=0.5)  # set the color and transparency
        self.play(Create(circle))  # show the circle on screen
```

The above code is me trying to use manim in spyder, manim is using python version 3.11.4 and spyder's base terminal is running python 3.9.1. I've already changed the interpereter preference of spyder to be the manim environment and reset the spyder kernel. How do i get manim to work properly?

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/comms/commbase.py", line 317, in _comm_message
ModuleNotFoundError: No module named 'rich'
Exception in comms call get_var_properties:
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/comms/commbase.py", line 317, in _comm_message
ModuleNotFoundError: No module named 'rich'
```

## Versions

* Spyder version: 5.4.4 d28269e66 (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: macOS-13.4.1-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.1.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.2.3 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.18.4 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.7.1 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.15.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.4 (OK)
pylint_venv >=3.0.2                                                         :  None (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.3.1 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.0.0 (OK)
sphinx >=0.6.6                                                              :  5.1.1 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.0 (OK)

# Optional:
cython >=0.21                                                               :  3.0.0 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.25.1 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.11.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2023-07-23 14:23
Hey @seanmag, thanks for reporting. Could you post a screenshot of the error you're seeing in Spyder when trying to run the code above? Thanks!

**Comment by seanmag** [comment] 2023-07-23 17:42
Sure thing, here you are
<img width="720" alt="Screenshot 2023-07-23 at 1 39 33 PM" src="https://github.com/spyder-ide/spyder/assets/125331380/07e58b5f-b551-4569-9ec1-8be8664d8573">

**Comment by ccordoba12** [comment] 2023-07-24 01:52
Ok, thanks for the screenshot. This should have been fixed in 5.4.4, but apparently it was not for Mac. We'll take a look at it. 

Do you also get our report error dialog shown when you run your `manim` code?

**Comment by ccordoba12** [comment] 2023-07-24 01:54
@mrclary, could you test this use case with our Mac app? Thanks!

**Comment by mrclary** [comment] 2023-07-24 18:27
I can confirm the OP. The report error dialog is shown with the following details:
```python
Exception in comms call get_namespace_view:
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/comms/commbase.py", line 317, in _comm_message
ModuleNotFoundError: No module named 'rich'
Exception in comms call get_var_properties:
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/comms/commbase.py", line 317, in _comm_message
ModuleNotFoundError: No module named 'rich'
```
* Spyder version: 5.4.4 d28269e66 (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: macOS-13.4.1-x86_64-i386-64bit

I created a separate environment using:
```
$ mamba create -n issue-21173 python=3.11.4 manim spyder-kernels
```

**Comment by demisjohn** [comment] 2023-07-29 21:56
Hello all,
I just installed the Windows 10 version of Anaconda + Spyder from anaconda.com : Anaconda3-2023.07-1-Windows-x86_64.exe [https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Windows-x86_64.exe], and my first simple script to read a CSV and plot the data also shows this same warning.

Just FYI, my previous version(s) (probably 1 year old) of anaconda on other computers (old macs) do not show this warning.

```
runfile('<REDACTED>analysis_v1.py', wdir='<REDACTED>')
d[0] ['-1900.209922' '-1900.176409' '-1900.142897' '-1900.109384'
 '-1900.075871' '-1900.042358' '-1900.008845' '-1899.975333'
 '-1899.941820' '-1899.908307']

This version of python seems to be incorrectly compiled
(internal generated filenames are not absolute).
This may make the debugger miss breakpoints.
Related bug: http://bugs.python.org/issue1666807
```

the script:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 25 21:57:44 2023
@author: demis
"""

import numpy as np
import matplotlib.pyplot as plt
import csv

# Read CSV file
with open(r"<REDACTED>top_ridge_graph.csv", encoding='utf-8-sig') as fp:
    reader = csv.reader(fp, delimiter=",", quotechar='"', )
    # next(reader, None)  # skip the headers
    data_read = [row for row in reader]

d = np.array(data_read).T # transpose

print("d[0]", d[0][0:1000])

fig, ax = plt.subplots()
ax.plot( d[0][0:1000], d[1][0:1000] )

```

Windows Version: 10.0.22621 Build 22621
Processor: Intel i7

**Comment by ccordoba12** [comment] 2023-08-04 14:02
@demisjohn, we fixed not showing that warning in our latest version (5.4.4), which unfortunately is not part of Anaconda yet.

**Comment by ccordoba12** [comment] 2023-08-04 14:02
@mrclary, are you seeing that warning in our 5.4.4 Mac app?

**Comment by ccordoba12** [comment] 2023-08-04 14:08
@mrclary, please also take care of this issue to check what's happening with `rich` in the Mac app (it seems it was not packaged correctly).

**Comment by ccordoba12** [comment] 2023-08-09 16:09
> I don't think this is a macOS app issue since rich is not part of Spyder's runtime environment (in the Mac app, or otherwise)

Ok, so even if `rich` is installed in the same env as `manim`, users are getting an error because `rich` is not part of the Spyder runtime env?

**Comment by mrclary** [comment] 2023-08-09 16:30
> > I don't think this is a macOS app issue since rich is not part of Spyder's runtime environment (in the Mac app, or otherwise)
> 
> Ok, so even if `rich` is installed in the same env as `manim`, users are getting an error because `rich` is not part of the Spyder runtime env?

I believe that is correct. spyder-kernels _in the runtime environment_ appears to be looking for `rich`, which it does not find. Note that this occurs for _all_ 5.x versions (macOS standalone, Windows standalone, bootstrap), but _not_ for bootstrap on master. This is why I suspect it may be related to spyder-kernels.

**Comment by ccordoba12** [comment] 2023-08-09 17:19
> I believe that is correct. spyder-kernels in the runtime environment appears to be looking for rich, which it does not find. Note that this occurs for all 5.x versions (macOS standalone, Windows standalone, bootstrap).

Ok, in that case I'd suggest to add `rich` to our installers respective envs because this is not something users can address by themselves. For bootstrap and other use cases, they can easily install `rich` in the Spyder runtime env.

> This is why I suspect it may be related to spyder-kernels.

Yeah, probably a new spyder-kernels dependency pull `rich`, so my suggested fix above wouldn't be necessary in Spyder 6.

**Comment by mrclary** [comment] 2023-08-09 17:55
> > This is why I suspect it may be related to spyder-kernels.
> 
> Yeah, probably a new spyder-kernels dependency pulls `rich`

This is not the case. Even for the master branch and spyder-kernels=3.0.0b2, `rich` is not installed in the runtime environment.

**Comment by ccordoba12** [comment] 2023-08-09 19:10
But the error doesn't show up in master?

**Comment by mrclary** [comment] 2023-08-09 19:58
> But the error doesn't show up in master?

Correct.

**Comment by mrclary** [comment] 2023-08-10 22:46
So I successfully created the animation from the OP using Spyder 6.0.0a1 with spyder-kernels 3.0.0b1 in the external environment. I think this confirms that the issue is resolved for Spyder 6.

https://github.com/spyder-ide/spyder/assets/9618975/2fa9803d-4666-4f4f-b5ab-02f9a0bb2c3a

**Comment by mrclary** [comment] 2023-08-10 22:52
@seanmag, if you want to install Spyder 6.0.0alpha1, you can download it here: https://github.com/spyder-ide/spyder/releases/tag/v6.0.0a1.
You will need to install spyder-kernels in your external environment. After activating your external environment run the following.
```
conda install -c conda-forge -c conda-forge/label/spyder_kernels_rc --override-channels spyder-kernels=3.0.0b1
```

**Closed** 2023-08-11 14:02 UTC
Labels: type:Bug, component:IPython Console
