### ISSUE TITLE
wrong  indentation in new version

### ISSUE THREAD

**Issue by yehao-jiaaocap** [spyder-ide/spyder#4119] opened 2017-02-08 02:21 UTC
## Description of your problem
wrong  indentation in some situation at the lastet version
**What steps will reproduce the problem?**

1. example:AFTER dataframe = pd.Dataframe(data).T

**What is the expected output? What do you see instead?**
there is a indentation aligning with the parentheses but no indentation is needed in fact

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.1.2
* Python Version:3.5.2
* Operating system:Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-02-08 16:05
Thanks for reporting. This is a duplicate of issue #4096.

**Closed by ccordoba12** 2017-02-08 16:05 UTC
