### ISSUE TITLE
Spyder Crash in df.groupby.rolling.mean with forward window indexer

### ISSUE THREAD

**Issue by mIgLLL** [spyder-ide/spyder#16283] opened 2021-08-26 01:23 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When you use df.groupby.rolling.mean with a forward-looking period, it would crash if you run the df.groupby.rolling.mean again.

### What steps reproduce the problem?

Here is a replicate code:
df = pd.DataFrame({'B': [np.nan, 1, 2, np.nan, 4,5,6,7,8,9,10,11,12,13,14,15]})
df['A']=1
indexer =  pd.api.indexers.FixedForwardWindowIndexer(window_size=12) # forward 12 period
# First time is OK
df['mean']=df.groupby('A')['B'].rolling(window=indexer, min_periods=1).mean().reset_index().loc[:,'B']
# Second time would crash!
df['mean']=df.groupby('A')['B'].rolling(window=indexer, min_periods=1).mean().reset_index().loc[:,'B']

If don't have groupby, it won't crash.
If don't forward window indexer, it won't crash.
If in the first time, it won't crash.

### Paste Traceback/Error Below (if applicable)

![image](https://user-images.githubusercontent.com/31037879/130884777-c476eb7d-5601-4d48-b135-1230c69f1e50.png)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.5
* Python version: 3.8.11
* Qt version: 5.10.1
* PyQt version: 5.10.1
* Operating System name/version: Win10 (Education) 19042.1165

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by mIgLLL** [comment] 2021-08-28 02:32
> This issue is not related to Spyder, I think. Python itself is silently crashing trying to run that code (try running this in a Python or IPython console outside of Spyder). Might be worth to post this issue to pandas-dev.
> 
> PS: this code should also produce the same result I think
> `df[::-1].groupby('A')['B'].rolling(window=12, min_periods=1).mean()[::-1]`

Oh! Thank you very much!

**Comment by mIgLLL** [comment] 2021-08-29 00:25
> This issue is not related to Spyder, I think. Python itself is silently crashing trying to run that code (try running this in a Python or IPython console outside of Spyder). Might be worth to post this issue to pandas-dev.
> 
> PS: this code should also produce the same result I think
> `df[::-1].groupby('A')['B'].rolling(window=12, min_periods=1).mean()[::-1]`

**Comment by ccordoba12** [comment] 2021-08-29 17:55
Hey @mIgLLL, sorry but I'm going to close this issue because it's not caused by an internal problem in Spyder.

Of course, @rhkarls is welcome to keep helping you here if they want.

**Closed by ccordoba12** 2021-08-29 17:55 UTC
