### ISSUE TITLE
Loading a second NPZ-file with same labels

### ISSUE THREAD

**Issue by versionbayjc** [spyder-ide/spyder#11680] opened 2020-02-28 12:20 UTC
### What steps will reproduce the problem?

I started Spyder from terminal (macOS). Loaded an NPZ-file in the Variable Explorer and a few seconds later loaded a different NPZ-file. Both files can load correctly after a restart, but if I load them one after another I get the internal problem.
Incidentally: both NPZ-files contain the same variables with different values. So maybe the issue is related to "overwriting" existing variables in the Variable explorer?

### Traceback
```python-traceback
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 207, in <lambda>
    triggered=lambda: self.import_data())
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 444, in import_data
    error_message = self.shellwidget.load_data(self.filename, ext)
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 125, in load_data
    timeout=CALL_KERNEL_TIMEOUT).load_data(filename, ext)
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 542, in __call__
    call_dict, call_data, self._comm_id)
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 114, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 420, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 480, in _sync_error
    error_wrapper.raise_error()
  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call load_data:

  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])

  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)

  File "/Users/jorik/miniconda3/lib/python3.7/site-packages/spyder_kernels/console/kernel.py", line 257, in load_data
    data[new_key] = data.pop(key)

AttributeError: 'NpzFile' object has no attribute 'pop'

```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.3.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-02-28 14:47
Duplicate of #11596

**Comment by ccordoba12** [comment] 2020-02-28 14:48
It'll be fixed in our next version.

**Closed by ccordoba12** 2020-02-28 14:47 UTC
