### ISSUE TITLE
Autocomplete and Doc help not working.

### ISSUE THREAD

**Issue by AchuthSankar** [spyder-ide/spyder#5815] opened 2017-11-22 14:24 UTC
## Description

**What steps will reproduce the problem?**

1. Create a .py file
2. type from sklearn.pre and tab
3. autocomplete not working,
4. also type ctrl I near LinearRegressor, nothing is shown in the help

Autocomplete is working fine from jupyter notebook.

Tried uninstalling and installing still not working.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-11-22 15:38
Does this only occur with certain names, like the one you described? Or with anything you try to autocomplete/get help on? If the former, can you specify which? Due to the intracies of some packages, autocomplete and help aren't always 100% reliable...an annoying issue, I agree, but I'm not sure how much it can be fixed on Spyder's or even `rope`/`jedi`''s end...

**Comment by AchuthSankar** [comment] 2017-11-22 15:45
It's for all packages :(. I tried with sklearn, pandas, numpy etc...

**Comment by ccordoba12** [comment] 2017-11-22 15:56
Please try to uninstall the `enum34` package and try again.

**Comment by partha1968** [comment] 2017-11-23 09:26
Same issue of autocomplete in editor. Didnt find enum34 package.

**Comment by AchuthSankar** [comment] 2017-11-23 09:44
no enum34 for me too

**Comment by kuo000** [comment] 2017-11-25 21:15
I started getting this exact same problem since a couple days ago. (I might have updated some python packages but I honestly don't remember.)

My problem is just like what everyone above said. Autocomplete **does not work in Spyder** but **works in Jupyter Notebook**. In Spyder, autocomplete does not work with any package I tried -- `numpy`, `pandas`, `matplotlib`, `sklearn`, and many more. I also have `enum34==1.1.6` installed.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.9.3
* PyQt Version: 5.9.2
* Operating system: Ubuntu 16.04


## Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by CAM-Gerlach** [comment] 2017-11-25 21:32
Did you try uninstalling `enum34`?

**Comment by kuo000** [comment] 2017-11-25 21:38
@CAM-Gerlach No. I have not tried that. Sorry. I misread @ccordoba12's comment above and thought I should install it. That's why I reported I had `enum34` installed.

I don't have access to my machine right now. Once I have a chance, I will try uninstalling `enum34` and report back here. Thanks.

**Comment by kuo000** [comment] 2017-11-26 02:05
Uninstalling `enum34` works for me. Autocomplete is back. Thanks @CAM-Gerlach and @ccordoba12 .

**Comment by CAM-Gerlach** [comment] 2017-11-26 02:08
Great, @kuo000 . All I did was steal @ccordoba12 's suggestion, so not sure I deserve any real credit, heh.

**Comment by ccordoba12** [comment] 2017-12-06 17:18
Duplicate of #5782.

**Closed by ccordoba12** 2017-12-06 17:18 UTC
