### ISSUE TITLE
configparser.NoOptionError: No option 'custom-0/normal' in section: 'color_schemes'

### ISSUE THREAD

**Issue by christinahalemba** [spyder-ide/spyder#7064] opened 2018-05-04 13:26 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Christina Halemba\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2635, in edit_preferences
    widget.initialize()
  File "C:\Users\Christina Halemba\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 76, in initialize
    self.setup_page()
  File "C:\Users\Christina Halemba\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 1175, in setup_page
    self.scheme_editor_dialog.add_color_scheme_stack(name, custom=True)
  File "C:\Users\Christina Halemba\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 1502, in add_color_scheme_stack
    value = self.parent.get_option(option)
  File "C:\Users\Christina Halemba\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 55, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\Users\Christina Halemba\Anaconda3\lib\site-packages\spyder\config\user.py", line 378, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'custom-0/normal' in section: 'color_schemes'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-05-04 14:38
Please close Spyder, open a system terminal (cmd.exe), run there

    spyder --reset

and start Spyder again. That should fix your problem.

**Comment by CAM-Gerlach** [comment] 2018-05-06 19:41
Duplicate of #5790 , which is a specific corner case invoked by creating duplicate color schemes and deleting them in a certain order. It should be fixed at some point, but you're welcome to take a crack at it now with the detailed information I've provided on how it occurs. ``spyder --reset`` should fix it, but you can also edit your settings file manually via the instructions there to fix it without resetting the rest of your settings or your custom color tables, etc. Also, #1493 will also mitigate it at least.

**Comment by CAM-Gerlach** [comment] 2018-05-06 19:42
Duplicate of #5790 , which is a specific corner case invoked by creating duplicate color schemes and deleting them in a certain order. It should be fixed at some point, but you're welcome to take a crack at it now with the detailed information I've provided on how it occurs. ``spyder --reset`` should fix it, but you can also edit your settings file manually via the instructions there to fix it without resetting the rest of your settings or your custom color tables, etc. Also, #1493 will also mitigate it at least.

**Closed by CAM-Gerlach** 2018-05-06 19:42 UTC
Labels: component:Preferences, type:Bug

**Comment by SuperZing** [comment] 2018-11-30 21:08
For anyone google searching to **fix this bug and not restart,** here it is.

**0.** **Close Anaconda and spyder**
**1.** In user search for **spyder.ini**, backup in case and edit the original. 
**2.** Find **color_schemes** then **custom_names**, it will look like this **"custom_names = ['custom-0', 'custom-1', 'custom-3']",** delete the custom causing the error.
**3.** Still wont work, delete the error custom from **custom_names**

**Comment by CAM-Gerlach** [comment] 2018-12-01 00:15
@SuperZing Thanks for distilling my findings in the lengthy thread down to a much more manageable form for public consumption. Since this thread is closed in favor of that one, the canonical one, could you post this over there instead? Thanks!

**Comment by SuperZing** [comment] 2018-12-01 21:14
@CAM-Gerlach I see. I would gladly post it, but still being inexperience to GitHub is it thread #5790, just want to confirm first.

**Comment by CAM-Gerlach** [comment] 2018-12-02 07:57
>  is it thread #5790

Yes indeed!
