### ISSUE TITLE
Spyder 4: how to remove any integration of figures with spyder?

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#11097] opened 2019-12-15 12:18 UTC
Hello,

Although "IPython console/Graphics/Support for graphics (Matplotlib)/Activate support" is set off, I still get my graphics in the Plots tab. There, I don't see the native toolbar. The new toolbar has the zoom icons grayed and it doesn't display the mouse coordinates, so I don't want such integration.

Is it a bug or a design feature?

**Comment by jnsebgosselin** [comment] 2019-12-15 14:24
Thanks for your report.

Closing as duplicate of https://github.com/spyder-ide/spyder/issues/10932.

Also please see https://github.com/spyder-ide/spyder/issues/11062.

The plot pane is only displaying the static figures that are received by the IPython console when matplotlib backend is set to 'inline'. The zoom is grayed out when the option `Fit plots to window` is checked.

![image](https://user-images.githubusercontent.com/10170372/70864018-35c6fc80-1f1c-11ea-89aa-e78e572ff84c.png)

**Closed by jnsebgosselin** 2019-12-15 14:24 UTC
