### ISSUE TITLE
matplotlib restarts kernel

### ISSUE THREAD

**Issue by jyauri** [spyder-ide/spyder#16690] opened 2021-10-31 23:27 UTC
### What steps will reproduce the problem?

Just call to the plot function of matplotlib, it restarts the kernel

Here a example.

import matplotlib.pyplot as plt

x = [1, 2, 3]

y = [2, 5, 3]

plt.plot(x,y)

plt.show()

**Comment by ccordoba12** [comment] 2021-11-01 02:34
Duplicate of issue #16659.

**Closed by ccordoba12** 2021-11-01 02:34 UTC
