### ISSUE TITLE
when using tab while writing cv2.waitkey()

### ISSUE THREAD

**Issue by ultradluffy8** [spyder-ide/spyder#11319] opened 2020-01-15 13:20 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

runcell(0, 'C:/Mobile Videos/OPencv/opencv-master/samples/data/untitled2.py')
This command failed to be executed because an error occurred while trying to get the cell code from Spyder's editor. The error was:

An exception has occurred, use %tb to see the full traceback.

CommError: Can't make a request to a closed comm

**Comment by ultradluffy8** [comment] 2020-01-15 13:21
Could any one help me to out of this error

**Comment by ccordoba12** [comment] 2020-01-15 15:23
Duplicate of #11137

**Closed by ccordoba12** 2020-01-15 15:23 UTC

**Comment by ccordoba12** [comment] 2020-01-15 15:24
We'll try to fix this in our next release. In the meantime, please restart Spyder to fix it.
