### ISSUE TITLE
Find in Files not working in 3.1.3

### ISSUE THREAD

**Issue by nbonacchi** [spyder-ide/spyder#4197] opened 2017-02-24 12:30 UTC
## Description
Should have been fixed by PR #4144  
Same as issue #4005 
Issue persists

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-02-27 15:35
I think the problem is that the directory where *Find in files* is working is not set correctly. To see if that's the case, please press the **+** button in *Find in Files* and be sure that the **Here** option is selected and points to the directory you want to search in.

This is an image of *Find in Files* after pressing that button:

![seleccion_001](https://cloud.githubusercontent.com/assets/365293/23367367/025c14ca-fcd8-11e6-91d9-fd2e292be23c.png)

**Comment by mherrmann3** [comment] 2017-02-27 15:47
Thanks Carlos, but that's not it. Path is the same there, but still doesn't show results. I have to note again that I have the impression that it doesn't even _start_ to search through the files....

**Comment by ccordoba12** [comment] 2017-02-27 15:52
Then I can't reproduce this error, sorry.

Are you using Qt 4 or Qt 5?

**Comment by mherrmann3** [comment] 2017-02-27 15:52
I'm using this:

> Python 3.5.2 64bits, Qt 5.7.1, PyQt5 5.7.1 on Linux

**Comment by nbonacchi** [comment] 2017-02-27 15:58
Qt Versions: 5.6.0, PyQt5 5.6 on Linux

**Comment by ccordoba12** [comment] 2017-02-27 16:01
@nbonacchi, did you test that the search directory is selected correctly? It's the only thing being different between searching when using projects and not using projects.

**Comment by nbonacchi** [comment] 2017-02-27 16:07
Yes, folder is correct, whether using projects or no projects I still get nothing... It's really weird.

**Comment by ccordoba12** [comment] 2017-02-27 17:23
Find in files is going to be dramatically improved in Spyder 3.2, thanks to pull request #4056.

So unless you help us to solve this problem by finding its cause and sending us a pull request for it, I'm afraid you'll have to wait until 3.2 is released to get a fix for this.

**Comment by ccordoba12** [comment] 2017-02-27 17:27
3.2 is planned to be released in mid April.

**Closed** 2017-05-14 14:23 UTC
Labels: component:Find in files, type:Bug
