### ISSUE TITLE
autosubmit

### ISSUE THREAD

**Issue by snowpearbiggod** [spyder-ide/spyder#5590] opened 2017-10-27 07:51 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\user3\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 562, in sortByColumn
    if not self.model().sort(index, sort_order):
  File "C:\Users\user3\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 312, in sort
    kind='mergesort')
  File "C:\Users\user3\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3196, in sort_values
    str(by))
ValueError: Cannot sort by duplicate column Engine

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25

**Comment by Prikers** [comment] 2017-10-27 11:59
Thank you @snowpearbiggod. This is a duplicate of #5225 which has been fixed in the 3.2.4 release. Please update to the latest release. 
Please note that in the latest release you will get an error message from `spyder` rather than a crash. This is because you are trying to sort a column on a `dataframe` which contains twice the very same column `Engine`. `pandas` does not allow to sort on a duplicate column.

**Closed by Prikers** 2017-10-27 11:59 UTC
