### ISSUE TITLE
Python has stopped working (Spyder crash)

### ISSUE THREAD

**Issue by Rasta15** [spyder-ide/spyder#4094] opened 2017-02-02 10:44 UTC
## Description of your problem

Spyder crashes when I try to open a file. The description is copied and pasted as follows:

  Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pythonw.exe
  Application Version:	3.6.150.1013
  Application Timestamp:	585d65af
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.23572
  Fault Module Timestamp:	57fd0651
  Exception Code:	c0000005
  Exception Offset:	000000000004f23c
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	7177
  Additional Information 1:	a745
  Additional Information 2:	a745a5fe3d4bc55416c4959c3f9fee16
  Additional Information 3:	3f00
  Additional Information 4:	3f008431c988f5c1d2cbbb05cf3bf3b4

**What steps will reproduce the problem?**

1. When I open Spyder after installing. Then attempting to open an existing program
2. 
3. 

**What is the expected output? What do you see instead?**
A program to run.

**Please provide any additional information below**
The got the Spyder IDE through Anaconda. 

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Operating system: Windows 7 professional

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-02-02 21:33
This is a duplicate of issue #3903, so I'm closing it.

Unfortunately, we don't know how to fix it, sorry.

**Closed by ccordoba12** 2017-02-02 21:33 UTC
Labels: resolution:Duplicate

**Comment by lixuancheng** [comment] 2018-06-25 15:42
Select compatibility in spyder‘s properties and check Run spyder as administrator can solve the problem.
