### ISSUE TITLE
Scheme changing issue

### ISSUE THREAD

**Issue by VanitarNordic** [spyder-ide/spyder#6639] opened 2018-03-07 08:16 UTC
### What steps will reproduce the problem?

The issue happens when I try to change scheme in Preferences/Syntax coloring. The Scheme changes applies by pressing the "Apply", but it generates this error either. 
I have to press the cancel to return back to the Spyder environment.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.4-CPU\lib\site-packages\spyder\plugins\configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.4-CPU\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.4-CPU\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.4-CPU\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.4-CPU\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

```

## Package Versions

* Spyder: 3.2.7
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by csabella** [comment] 2018-03-07 11:43
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed** 2018-03-07 11:43 UTC
Labels: resolution:Duplicate
