### ISSUE TITLE
Terminal shows a blank screen and hangs

### ISSUE THREAD

**Issue by ukalwa** [spyder-ide/spyder#7896] opened 2018-09-14 00:07 UTC
### What steps will reproduce the problem?

```bash
conda install spyder-terminal -c conda-forge
```
My system configuration:

Python 3.5.5
Spyder 3.3.1
spyder-terminal 0.2.4

### Traceback
```python-traceback
  File "C:\Users\ukalwa\AppData\Local\conda\conda\envs\dl35\lib\site-packages\spyder_terminal\terminalplugin.py", line 327, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\ukalwa\AppData\Local\conda\conda\envs\dl35\lib\site-packages\spyder_terminal\terminalplugin.py", line 340, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'json': {'documentation_url': 'https://developer.github.com/v3', 'message': 'Bad credentials'}, 'code': 401}
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.5.5
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.0 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-09-14 00:15
Thanks for reporting. This is a duplicate of spyder-ide/spyder-terminal#123

**Closed by ccordoba12** 2018-09-14 00:15 UTC
