### ISSUE TITLE
No curly brackets on Spyder 4.0.0b3 on macOS with a French keyboard

### ISSUE THREAD

**Issue by jproy** [spyder-ide/spyder#9749] opened 2019-07-04 15:43 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
No curly brackets on Mac

### What steps reproduce the problem?

Type { }

### What is the expected output? What do you see instead?
I see only parentheses ( )

## Versions

* Spyder version: 4.0.0beta3 (same in beta2)
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: MacOS 10.13.6

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by jproy** [comment] 2019-07-04 15:46
I forgot to say that this is an editor problem. I can get { } at the console.

**Comment by ccordoba12** [comment] 2019-07-05 10:01
@steff456 or @juanis2112, can you reproduce this problem?

**Comment by steff456** [comment] 2019-07-05 14:48
I am able to get curly brackets at the editor.

![curly](https://user-images.githubusercontent.com/20992645/60730148-0ee6b200-9f0a-11e9-8aac-15e40d465895.gif)

**Comment by jproy** [comment] 2019-07-06 16:14
It is probably something going with the french keyboard. Could you contact another french person using Spyder 4.0.0beta3 (nobody around me using Spyder on MacOS)... I use 3.3.5 now.

**Comment by ccordoba12** [comment] 2019-07-06 18:31
@steff456, please use a French keyboard layout distribution to see what happens.

@jproy, sorry, we don't have French macOS developers in our team, so that's the best we can do.

**Comment by steff456** [comment] 2019-07-09 04:20
@ccordoba12, I can reproduce the this problem using the French keyboard layout distribution.

**Comment by ccordoba12** [comment] 2019-07-09 14:45
@steff456, what combination of keys are you using to enter curly braces?

**Comment by steff456** [comment] 2019-07-09 15:27
With alt + 5

**Comment by ccordoba12** [comment] 2019-07-09 15:53
@jproy, is that the same combination you have to use?

**Comment by jproy** [comment] 2019-07-10 16:12
@ccordoba12 Yes I use "Alt (" and "Alt )".

**Comment by jproy** [comment] 2019-07-10 16:15
@ccordoba12 Do not confuse "5" and "(" because "Alt 5" is "Alt-Shift (" which gives "[" and "Alt (" gives "{".

**Comment by steff456** [comment] 2019-07-10 16:20
@jproy yes, sorry is the same key combination I used "Alt ("

**Comment by ccordoba12** [comment] 2019-07-10 17:30
I'm not confusing anything because I didn't test this, @steff456 did.

@jnsebgosselin, any insights here?

**Comment by jnsebgosselin** [comment] 2019-07-10 19:34
@jproy does your keyboard look like this :

![image](https://user-images.githubusercontent.com/10170372/60998450-f40ba780-a326-11e9-873f-f8b4003f12ec.png)

versus this for the english keyboard :

![image](https://user-images.githubusercontent.com/10170372/60998620-4b117c80-a327-11e9-812b-ed12093d93fc.png)

**Comment by jnsebgosselin** [comment] 2019-07-10 20:02
@steff456 Can you comment out this block of code in `codeeditor.py` and test again if this bug is still occurring please. Thanks!

```
def event(self, event):
    """Qt method override."""
    if event.type() == QEvent.ShortcutOverride:
        event.ignore()
        return False
    else:
        return super(CodeEditor, self).event(event)
```

**Comment by jnsebgosselin** [comment] 2019-07-10 20:14
If the bug still occur when testing the above (which I really hope it does...), can you test again but with commenting these lines in the `codeeditor.py` :

```
self.editor_extensions.add(CloseQuotesExtension())
self.editor_extensions.add(CloseBracketsExtension())
```

And replacing this line in `spyder.plugins.editor.extensions.manager.py`:

`return self._extensions[name_or_klass]`

by

`return self._extensions.get(name_or_klass, None)`

Thanks!

**Comment by steff456** [comment] 2019-07-11 04:37
@jnsebgosselin the first option doesn't fix the bug, the second one does but now the editor does not close any bracket.

![image](https://user-images.githubusercontent.com/20992645/61022491-a4030400-a36b-11e9-8c95-d90b7efb9bb0.png)

**Comment by jnsebgosselin** [comment] 2019-07-11 04:41
> @jnsebgosselin the first option doesn't fix the bug, the second one does but now the editor does not close any bracket.
> 
> ![image](https://user-images.githubusercontent.com/20992645/61022491-a4030400-a36b-11e9-8c95-d90b7efb9bb0.png)

Ok thank you very much for your invaluable feedback. Now that we have been able to pinpoint the source of this issue, let me check and try to propose a valid fix for this.

**Comment by jproy** [comment] 2019-07-11 06:52
@jnsebgosselin YES this is my french keyboard.

**Comment by jproy** [comment] 2019-07-11 06:59
@jnsebgosselin OUPS, no, it is almost my keyboard. In fact, I have only three jeys on the left of the space bar, labelled "ctrl", "alt" and "cmd". It is named APPLE MAGIC KEYBOARD I think and has the numeric keypad included.
https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/image/AppleInc/aos/published/images/M/Q0/MQ052F/MQ052F?wid=572&hei=572&fmt=jpeg&qlt=95&op_usm=0.5,0.5&.v=1496359289903

**Comment by jnsebgosselin** [comment] 2019-07-11 12:52
Thanks @jproy 

@steff456 I have created a PR with a proposed solution for this bug. I cannot test if this is actually working, so if you could do that, that would be really great! If this work, could you also add an animation or something in the opening post of the PR.

Thanks!

**Closed** 2019-07-11 21:31 UTC
Labels: component:Editor, type:Bug
