### ISSUE TITLE
Make a matplotlib figures panes

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#5550] opened 2017-10-23 17:14 UTC
Ok, this is a pure enhancement request for a future version

## Description of your problem

Setting the matplotlib backend to inline gives us figures within the overall spyder UI but are not really ideal as they can't be zoomed and you have to keep scrolling back in the console to look at them. Setting the backend to automatic or one of the other toolkit specific options allows greater functionality but losses the single window interface advantages of spyder.

## Enhancement Suggestion

Create a new  plots component/pane that embeds new matplotlib figures created in the console or script within tabs in a view-pane in spyder. I would imagine each tab would correspond to a separate matplotlib figure and would allow the same sort of panning/zooming options that the standalone matplotlib figure windows do. This would allow the user to keep the plot in view whilst working at the console with realtime updates etc, but also allow manipulation oif the plot in the figure window. This would be activated by setting the matplotlibbackend preference to some appropriate value and then enabling the pane in the view menu (perhaps settign the preference should enable/disable the view pane automatically).

I think this would make a considerable enhancement in the productivity of spyder for data exploration/analysis. I'm afraid my coding skills are not really up to even begining to think how to actually implement this other than general hand waving about embedding mpl figures.... :-(

**Comment by ccordoba12** [comment] 2017-10-23 20:17
Thanks for reporting. This is a duplicate of issue #2550.

**Closed by ccordoba12** 2017-10-23 20:17 UTC
