### ISSUE TITLE
"ERROR: execution aborted" after any exception, or line script. 

### ISSUE THREAD

**Issue by DanielIAvila** [spyder-ide/spyder#13453] opened 2020-08-02 03:43 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have recently re-installed Anaconda and Spyder from scratch, since `conda update conda` did not work. After it, Spyder started to give me problems. Every now and then, probably 6 out 10 times a run a line/code the Console shots a `ERROR: execution aborted`, and I have to re-start the code from scratch.

### What steps reproduce the problem?

1. Running a single line or a full script.
2. At any moment, in the beginning, running code chunks, or close to finish.
3. I have to start from scratch every time.

### What is the expected output? What do you see instead?
A smooth and clean run from beginning to end of my script.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.1.4                    py38_0 
* Python version:  3.8.3                he1778fa_2 
* Qt version:         5.9.7            vc14h73c81de_0
* PyQt version:     5.9.2            py38ha925a31_4
* Operating System name/version: Windows 10, x64bits

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

```

**Comment by steff456** [comment] 2020-08-04 15:52
Hi @DanielIAvila,
Can you please upload here a gif or screenshot with the behavior that you are getting? As well, if you can share with us some file that you write and is presenting the issue to see if we can reproduce it. 
Thanks for reporting!

**Comment by steff456** [comment] 2020-08-11 15:40
I'm closing this issue because there wasn't a follow-up response after a week

**Closed by steff456** 2020-08-11 15:40 UTC
Labels: status:Awaiting Followup

**Comment by windengineer0** [comment] 2020-09-04 07:44
I am experiencing the same problem, in Spyder 4.1.5:

![image](https://user-images.githubusercontent.com/32761710/92212828-d9817f80-ee92-11ea-82e3-125fe545dd0b.png)

I think it could be related to the iPython kernel.

**Comment by DanielIAvila** [comment] 2020-09-04 13:43
Hey @windengineer0 ,

Maybe it is a library you are using, or the installation went wrong. In any case, I solved the problem like this:

1. With the `conda shell` create a new environment.
2. Install everything in this new `environment` with `conda install`. If this does not work, use `conda forge XX`, where `XX` is the library you want to use.
3. In the new environment install `spyder`, `kernels`, `pandas`, `xx`

This was the only way I could solved the problem. After you encounter this problem, what you are going to find is that `variable explorer` will not work. So, better to fix it right away.

**Comment by mathewjowens** [comment] 2020-09-23 16:35
I've got the same issue. Any exception means I have to restart the kernel.

![image](https://user-images.githubusercontent.com/31659031/94042219-3356d480-fdc3-11ea-96d0-5045f41a5343.png)

**Comment by dalthviz** [comment] 2020-09-23 16:56
Hi, could you guys check if updating `ipykernel` to 5.3.4 helps?

**Comment by mathewjowens** [comment] 2020-09-23 17:00
Same problem after updating for me. But thanks for trying.

**Comment by dalthviz** [comment] 2020-09-23 17:21
Could you try to update `IPython` and `QtConsole`? Maybe looking our [Basic First Aid Guide](https://docs.spyder-ide.org/current/basic-first-aid.html) could give more alternatives to try. Sorry to not be so helpful (there is not much we can do in this sort of installation issues for now :/ ).

**Comment by mathewjowens** [comment] 2020-09-23 17:40
None of the updates (ipython, qtconsole, Spyder, Spyder dependencies) make a difference. But `spyder --reset` seems to have done the trick. Which is odd, as this was a fresh environment. But thanks!

**Comment by windengineer0** [comment] 2020-09-24 06:14
I had some success with a new environment, but it eventually produced the same behavior. Now I've tried `spyder --reset` and it seems to work, hopefully for good. Thanks for the tip!

**Comment by AlastairShipman1** [comment] 2020-11-02 16:52
I have been having this same problem- it doesn't occur with my conda python installation, but whenever I use a different version (e.g. Python 3.8.5), it brings back to this issue.  spyder --reset reverts the python installation to conda, so isn't really a fix?

**Comment by FerTorresUriel** [comment] 2020-11-04 18:14
> I have been having this same problem- but it only happens when I'm using an automatic graphics backend, for interacting with graphs. inline plotting doesn't give me this issue
> spyder --reset reverts it to inline plotting, but it isn't really a fix?

This, solved my problem. I returned the plotted graphics to in line format

**Comment by traemand** [comment] 2020-11-09 00:21
> I had some success with a new environment, but it eventually produced the same behavior. Now I've tried `spyder --reset` and it seems to work, hopefully for good. Thanks for the tip!

This worked for me as well

**Comment by Vinnipure** [comment] 2021-01-28 16:53
> I have been having this same problem- but it only happens when I'm using an automatic graphics backend, for interacting with graphs. inline plotting doesn't give me this issue
> spyder --reset reverts it to inline plotting, but it isn't really a fix?

This is exactly the same issue I have as well. Plotting inline solved all issues. It is the case for two python versions (3.8.3 and 3.8.7).  However, I would still like to have interactive plots. Any ideas?

**Comment by jonathanayalaleon** [comment] 2021-04-06 09:23
I had the same issue I thought initially that my python version was having issues with the spyder interpreter, but it turned out that I was generating graphs not inline but automatic, this causes too many problems in my case, I do not know what the reason of that is but I changed to graphs inline in tools->preferences->IPython-console->Graphics->backend->inline. my debugger was not working either, but now it is working, I hope this is useful for some people.

**Comment by abnerm28** [comment] 2021-06-05 15:22
> I had the same issue I thought initially that my python version was having issues with the spyder interpreter, but it turned out that I was generating graphs not inline but automatic, this causes too many problems in my case, I do not know what the reason of that is but I changed to graphs inline in tools->preferences->IPython-console->Graphics->backend->inline. my debugger was not working either, but now it is working, I hope this is useful for some people.

Thank you a lot!
