### ISSUE TITLE
Strange Character in Editor -> Browse Tabs button

### ISSUE THREAD

**Issue by dougthor42** [spyder-ide/spyder#2262] opened 2015-03-23 19:17 UTC
There is a strange character in the Editor -> Browse Tabs button:
![image](https://cloud.githubusercontent.com/assets/5386897/6788279/7c1c6b4e-d155-11e4-8418-73e4f99acc06.png)
It looks to be "Latin Small Letter A With Circumflex" `â` , unicode `0x00E2`, alt-code 0226.

Spyder Version:  2.3.2
Python Version:  2.7.6
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
zmq >=2.1.11    :  14.0.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
coverage >=0.25 :  3.7.1 (OK)
pylint >=0.25   :  1.0.0 (OK)

**Comment by ccordoba12** [comment] 2015-03-23 22:49
Thanks for reporting. What Python distribution (if any) are you using on Windows? WinPython or Anaconda?

**Comment by dougthor42** [comment] 2015-03-23 22:59
WinPython 2.7.6.2

**Comment by ccordoba12** [comment] 2015-03-23 23:14
@stonebig, can you reproduce this error?

**Comment by stonebig** [comment] 2015-03-24 05:20
not in the more recent winpythons.... upgrade.

**Comment by dougthor42** [comment] 2015-03-24 17:16
Here are the results from the other versions of Spyder/WinPython I have installed:

WinPython 3.4.2.4 has a similar issue, but in this case part of the file path is chopped off:
![image](https://cloud.githubusercontent.com/assets/5386897/6807767/cf1b31be-d20d-11e4-8339-7e128a0e3de2.png)
**Spyder Version:  2.3.2**
Python Version:  3.4.2
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Windows
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
coverage >=0.25 :  3.7.1 (OK)
pylint >=0.25   :  1.4.0 (OK)


===========================

WinPython 3.3.3.2 seems to be OK:
![image](https://cloud.githubusercontent.com/assets/5386897/6807840/2fa079ea-d20e-11e4-91d2-e26150946e8d.png)
**Spyder Version:  2.3.0beta2**
Python Version:  3.3.3
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.0.0 (OK)

Note that the working one is **Spyder 2.3.0beta2**

Care to tell me why you're asking about the WinPython version? Seems like it would be purely a Spyder issue to me...

**Comment by stonebig** [comment] 2015-03-24 17:56
about the `WinPython version`, I can only reproduce against very recent release of winpython, and your winpython version was too old.
Testing against a my current winpython 3.4 +spyder2.3.4 this morning:
- I didn't have the `â`.
- I didn't have your loss of `path` either. 
now checking on a winpython3.4.2.4, for which I have a copy

**Comment by dougthor42** [comment] 2015-03-24 18:15
Ah I see.

Interesting note about the Qt ``graphic`` bug.

**Comment by stonebig** [comment] 2015-03-24 18:18
I'm on windows 7, on what windows version are you ?

**Comment by dougthor42** [comment] 2015-03-24 19:00
Yeah, Win 7 Pro SP1.

**Comment by stonebig** [comment] 2015-03-24 19:51
it's a little strange it doesn't react exactly like mine. Qt is not my domain of comfort, so I can't help further on this

**Comment by ccordoba12** [comment] 2015-03-24 20:08
If @stonebig can't reproduce this problem, it means it's not in our side but something about Qt on Windows.

So I don't know how to proceed from here.

**Comment by dougthor42** [comment] 2015-03-24 20:53
Not a problem. It's obviously not a critical bug. I was just reporting it so that it's known. If I have the time I might look into it myself, but since it appears that it's fixed on some newer releases, I won't worry too much about it.

**Comment by ccordoba12** [comment] 2017-01-28 23:54
Closing as related to Qt4. Hopefully this is fixed when using Spyder with Qt5.

**Closed by ccordoba12** 2017-01-28 23:54 UTC
Labels: component:Editor, type:Bug
