### ISSUE TITLE
Can't run matplotlib script twice

### ISSUE THREAD

**Issue by CaptainAL** [spyder-ide/spyder#3193] opened 2016-05-27 01:57 UTC
In a new console window (not IPython) I run my script with F5 (or the run button). The script executes, the plots appear and function normally, but I cannot run the script or type in any other commands, even after hitting CTRL-C. I can't run another script either.

I'm using Qt4 though I tried with every combination of Qt4,5, pysides and backends Automatic, None, Tkinter.

Windows 10
Python 2.7
Spyder 3.0 dev

**Comment by ccordoba12** [comment] 2016-06-01 03:10
This is a duplicate of issue #1831, and we don't really know how to fix it.

Please use the IPython console instead :-)

**Closed by ccordoba12** 2016-06-01 03:10 UTC
Labels: Type-Duplicate
