### ISSUE TITLE
kite error pops up if open vpn while using spyder

### ISSUE THREAD

**Issue by PeteLeng** [spyder-ide/spyder#14671] opened 2021-01-30 07:27 UTC
### What steps will reproduce the problem?

open astrill vpn while in spyder

the error pops up

### Traceback
```python-traceback
  File "C:\Users\lengy\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 108, in get_status
    self.sig_status_response_ready[dict].emit(kite_status)
TypeError: KiteClient.sig_status_response_ready[dict].emit(): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  4.0.0 (OK)
cloudpickle >=0.5.0          :  1.6.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.19.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  6.0.7 (OK)
numpydoc >=0.6.0             :  1.1.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.2 (OK)
pygments >=2.0               :  2.7.4 (OK)
pylint >=0.25                :  2.6.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  20.0.0 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  1.0.1 (OK)
qtconsole >=4.6.0            :  4.7.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  3.4.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.21 (OK)
matplotlib >=2.0.0           :  3.3.2 (OK)
numpy >=1.7                  :  1.19.2 (OK)
pandas >=0.13.1              :  1.2.1 (OK)
scipy >=0.17.0               :  1.5.2 (OK)
sympy >=0.7.3                :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment] 2021-01-31 01:00
Hey @PeteLeng, this is fixed in our the latest version available in Anaconda. Please update by running these commands in your Anaconda Prompt:

    conda update anaconda
    conda install spyder=4.2.0

**Comment by PeteLeng** [comment] 2021-02-03 01:16
problem solved, thanks!

**Comment by PeteLeng** [comment] 2021-02-03 01:23
any reason causing this problem? @ccordoba12

**Comment by ccordoba12** [comment] 2021-02-03 02:10
Does the problem still appear for you in our 4.2.0 version?

**Comment by PeteLeng** [comment] 2021-02-03 04:10
not anymore in 4.2.0

**Comment by ccordoba12** [comment] 2021-02-03 16:30
> any reason causing this problem? @ccordoba12

I think it was caused by an incorrect uninstallation of Kite.

> not anymore in 4.2.0

Great! Closing this issue then.

**Closed by ccordoba12** 2021-02-03 16:30 UTC
Labels: status:Awaiting Followup
