### ISSUE TITLE
Error when importing module's function when running file in Spyder console

### ISSUE THREAD

**Issue by pj1989** [spyder-ide/spyder#15068] opened 2021-03-31 13:30 UTC
This problem was firstly discussed here https://stackoverflow.com/questions/66886458/attributeerror-importdenier-object-has-no-attribute-find-spec-when-loading

## Problem Description
I have a module exactly as follows

```
my_module
   |-> _sub_module
   |     |-> test_fun.py
   |-> test_fun1.py
   |-> run.py
   |-> __init__.py
```

the content of the files is the followng

test_fun.py
```
def test_fun():
    pass
```

test_fun1.py
```
def test_fun1():
    pass
```

run.py
```
from my_module.test_fun1 import test_fun1
from my_module._sub_module.test_fun import test_fun
```

while `__init__.py` is empty.

##TEST 1

when I run `run.py` (from the module parent directory) it works just fine. However, if I comment the first line in `run.py` and execute only the second one (`from my_module._sub_module.test_fun import test_fun`) I get the following error

```
runfile('C:/Users/###/Documents/GitLab/test_project/my_module/run.py')
Reloaded modules: my_module, my_module.test_fun1, my_module._sub_module.test_fun
Traceback (most recent call last):

  File "<frozen importlib._bootstrap>", line 908, in _find_spec

AttributeError: 'ImportDenier' object has no attribute 'find_spec'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\###\Documents\GitLab\test_project\my_module\run.py", line 4, in <module>
    from my_module._sub_module.test_fun import test_fun

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 910, in _find_spec

  File "<frozen importlib._bootstrap>", line 884, in _find_spec_legacy

  File "C:\Users\###\Anaconda3\lib\site-packages\IPython\external\qt_loaders.py", line 48, in find_module
    if path:

  File "<frozen importlib._bootstrap_external>", line 1183, in __len__

  File "<frozen importlib._bootstrap_external>", line 1162, in _recalculate

  File "<frozen importlib._bootstrap_external>", line 1158, in _get_parent_path

KeyError: 'my_module'
```

##TEST 2

To make the example even more trivial, I edited the structure of the project moving `run.py` up one level.
The behavior now, however, is even weirder!

Now, when I run the code the first time it runs fine (always with only the second line in `run.py`). But if I run it a second time immediately after, the error pops up as before.

```
runfile('C:/Users/###/Documents/GitLab/test_project/run.py', wdir='C:/Users/###/Documents/GitLab/test_project')

runfile('C:/Users/###/Documents/GitLab/test_project/run.py', wdir='C:/Users/###/Documents/GitLab/test_project')
Reloaded modules: my_module, my_module._sub_module.test_fun
Traceback (most recent call last):

  File "<frozen importlib._bootstrap>", line 908, in _find_spec

AttributeError: 'ImportDenier' object has no attribute 'find_spec'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\###\Documents\GitLab\test_project\run.py", line 4, in <module>
    from my_module._sub_module.test_fun import test_fun

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 910, in _find_spec

  File "<frozen importlib._bootstrap>", line 884, in _find_spec_legacy

  File "C:\Users\###\Anaconda3\lib\site-packages\IPython\external\qt_loaders.py", line 48, in find_module
    if path:

  File "<frozen importlib._bootstrap_external>", line 1183, in __len__

  File "<frozen importlib._bootstrap_external>", line 1162, in _recalculate

  File "<frozen importlib._bootstrap_external>", line 1158, in _get_parent_path

KeyError: 'my_module'
```

## NOTES:
- The issue cannot be reproduced neither in a python console, nor in an IPython console outside Spyder
- If I copy-paste the line `from my_module._sub_module.test_fun import test_fun` the problem disappears
-  If I use the "Execute current line" command or use the `runcell` command, the problem disappears

## Versions
* Spyder version: 4.1.5
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by real-yfprojects** [comment] 2021-04-04 13:24
I am able to reproduce the Problem on Linux. The problem doesn't occur when adding a `__init__.py` file to the `_sub_module`. Or when removing the `__init__.py` file in `my_module`. The issue only occurs when running `runfile` after the file was already run. It seems to be a issue with the `runfile` function

But I don't think this bug is worth to look into further because I don't think it is common or even right to define a *namespace* package inside a normal package. Tell me if I am wrong about that.

**Comment by steff456** [comment] 2021-04-05 16:03
Hi @pj1989,

As @real-yfprojects already mentioned the problem will be fixed when you add an `__init__.py` file in the submodule. Please remember when writing modules that it is always a best practice to add an `__init__.py` file even if it is empty.

As your problem is already fixed by this, I'm closing this issue.
Thanks for reporting!

**Closed by steff456** 2021-04-05 16:03 UTC

**Comment by real-yfprojects** [comment] 2021-04-06 05:52
> Hi @pj1989,
> 
> As @real-yfprojects already mentioned the problem will be fixed when you add an `__init__.py` file in the submodule. Please remember when writing modules that it is always a best practice to add an `__init__.py` file even if it is empty.
> 
> As your problem is already fixed by this, I'm closing this issue.
> Thanks for reporting!

It is not good practice, it is necessary. Otherwise the python package will be treated as a namespace package which is different than the standard.
