### ISSUE TITLE
Selection on the outline causes error

### ISSUE THREAD

**Issue by arman00** [spyder-ide/spyder#5058] opened 2017-08-25 13:19 UTC
## Description
Spyder shows error when a symbol is selected from the outline view. This happens only for some files in the editor. Also it does not happen always. For instance, as soon as I restarted Spyder, it worked on the same file without an error.

**What steps will reproduce the problem?**

1. Select a symbol in the outline view

**What is the expected output? What do you see instead?**
Expected: go to that symbol in the file
Actual: Error dialog is shown not going to that symbol

**Please provide any additional information below**

  File "C:\WinPython-64bit-3.5.3.2Qt5b6\python-3.5.3.amd64\lib\site-packages\spyder\widgets\editortools.py", line 490, in clicked
    self.activated(item)
  File "C:\WinPython-64bit-3.5.3.2Qt5b6\python-3.5.3.amd64\lib\site-packages\spyder\widgets\editortools.py", line 481, in activated
    if _id == editor_id and editor.parent() is parent:
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-25 15:08
Does this happen if you have splitted the Editor in some way?

**Comment by arman00** [comment] 2017-08-25 15:18
It happened while I was working on splitted Editor. However, then I closed all the split panels but the error was popping up although there was no split anymore. After I restarted Spyder, it worked fine with and without the split panels. Maybe the error was initiated due to the split and then became persistent, but I am not sure. If I can observe some pattern regarding the cause of the error, I can report here.

**Comment by ccordoba12** [comment] 2017-08-25 15:19
Ok, thanks.

**Comment by jnsebgosselin** [comment] 2017-08-28 17:35
@ccordoba12 potentially a duplicate of https://github.com/spyder-ide/spyder/issues/3390

**Comment by ccordoba12** [comment] 2017-08-28 22:24
You're right.

**Closed by ccordoba12** 2017-08-28 22:24 UTC
Labels: component:Editor, type:Bug
