### ISSUE TITLE
matplotlib window hang

### ISSUE THREAD

**Issue by mhofsaess** [spyder-ide/spyder#17506] opened 2022-03-17 22:34 UTC
### What steps will reproduce the problem?

I'm using as graphical backend the qt5 options. 
When I am ploting something for example

import matplotlib.pyplot as plt
plt.plot([1,2,3,4,5,6,7])

and open then the preference menu to adjust the plot, then the figure hang and I can only close it with plt.close('all') at the console. 

If I do the same at a python console without spyder I can not reproduce the problem, so I think the problems has something to do with spyder. 

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.3
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 4.19.0-19-amd64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=2.5.0                :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by rhkarls** [comment] 2022-03-18 15:50
Is it the same issue as described here https://github.com/spyder-ide/spyder/issues/16946 ?
If so it appears to be a matplotlib issue, and a fix is merged for next release of matplotlib 3.5.2 (see https://github.com/matplotlib/matplotlib/pull/22202). Might also work to downgrade matplotlib to 3.4

**Comment by mhofsaess** [comment] 2022-03-18 23:31
Thank you for the feedback. 

Yes it looks like the issue [#16946](https://github.com/spyder-ide/spyder/issues/16946).

**Comment by ccordoba12** [comment] 2022-03-19 01:42
Ok, closing then, It should be fix for good in Matplotlib 3.5.1

**Closed by ccordoba12** 2022-03-19 01:42 UTC
Labels: status:Awaiting Followup

**Comment by mhofsaess** [comment] 2022-03-23 22:45
Hi all,

I have solved my original problem with the code snippet, but I have another problem which causes my plot window to freeze. Maybe it goes in the same direction. 

When I execute the following code (the crucial line here is the twinx line I think) and then click on "Edit Axes..." in the menu bar, the window pops up briefly, disappears again and the figure hangs. 

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot([1,2,3,4,5,6])
axx = ax.twinx()
axx.plot([6,5,4,3,2,1])

I can close the figure only with 
plt.close()

When I execute the code in an Ipython console directly in the terminal, the behaviour does not occur.

**Comment by ccordoba12** [comment] 2022-03-23 23:10
@mhofsaess, that problem is caused by a bug in matplotlib and will be fixed in its next version (3.5.1).

**Comment by mhofsaess** [comment] 2022-03-24 08:02
@ccordoba12, 

but I'm using matplotlib 3.5.1.

**Comment by ccordoba12** [comment] 2022-03-26 16:42
Then please post it in Matplotlib because it's not related to Spyder.

**Comment by ccordoba12** [comment] 2022-03-26 17:40
Thanks @rhkarls for the clarification!

@mhofsaess, my bad, sorry. I messed up the Matplotlib versions.
