### ISSUE TITLE
Spyder crashes on launch with PyLS >=0.21

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8153] opened 2018-10-27 19:53 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

@ccordoba12 

@bcolsen reported the following issue:

----

I installed miniconda on a virtualbox windows 10 64-bit install. I can run beta1 fine on the install.

But with latest master I get a traceback at least instead of a hard crash(like the laptop yesterday):

<details>
```
2018-10-26 10:40:04,450 [INFO] [spyder.app.mainwindow] -> Loading history plugin...
2018-10-26 10:40:04,481 [INFO] [spyder.app.mainwindow] -> Loading IPython console...
2018-10-26 10:40:04,919 [INFO] [spyder.app.mainwindow] -> Loading file explorer...
2018-10-26 10:40:04,919 [DEBUG] [spyder.plugins.editor.lsp.client] -> python response: server_ready
2018-10-26 10:40:04,919 [DEBUG] [spyder.plugins.editor.lsp.client] -> python request: initialize
2018-10-26 10:40:05,122 [INFO] [spyder.app.mainwindow] -> Loading project explorer...
Handling signal: 0
Traceback (most recent call last):
  File "C:\Users\user\spyder-dev\spyder\app\mainwindow.py", line 3336, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\user\spyder-dev\spyder\app\mainwindow.py", line 3185, in run_spyder
    main.setup()
  File "C:\Users\user\spyder-dev\spyder\app\mainwindow.py", line 943, in setup
    from spyder.plugins.projects.plugin import Projects
  File "C:\Users\user\spyder-dev\spyder\plugins\projects\plugin.py", line 30, in <module>
    from spyder.plugins.projects.widgets.explorer import ProjectExplorerWidget
  File "C:\Users\user\spyder-dev\spyder\plugins\projects\widgets\__init__.py", line 11, in <module>
    from spyder.plugins.projects.api import EmptyProject
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 788, in get_code
  File "<frozen importlib._bootstrap_external>", line 848, in _cache_bytecode
  File "<frozen importlib._bootstrap_external>", line 873, in set_data
  File "<frozen importlib._bootstrap_external>", line 118, in _write_atomic
KeyboardInterrupt
```
</details>

`conda list`
<details>
```
alabaster                 0.7.12                   py36_0
asn1crypto                0.24.0                   py36_0
astroid                   2.0.4                    py36_0
autopep8                  1.4.2                     <pip>
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
bleach                    3.0.2                    py36_0
ca-certificates           2018.03.07                    0
certifi                   2018.10.15               py36_0
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
cloudpickle               0.6.1                    py36_0
colorama                  0.4.0                    py36_0
cryptography              2.3.1            py36h74b6da3_0
decorator                 4.3.0                    py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3                    py36_2
future                    0.17.0                    <pip>
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
imagesize                 1.1.0                    py36_0
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.0.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
isort                     4.3.4                    py36_0
jedi                      0.13.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter_client            5.2.3                    py36_0
jupyter_core              4.4.0                    py36_0
keyring                   15.1.0                   py36_0
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
markupsafe                1.0              py36hfa6e2cd_1
mccabe                    0.6.1                    py36_1
mistune                   0.8.3            py36hfa6e2cd_1
nbconvert                 5.3.1                    py36_0
nbformat                  4.4.0            py36h3a5bc1b_0
numpydoc                  0.8.0                    py36_0
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                     py36_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
parso                     0.3.1                    py36_0
pickleshare               0.7.5                    py36_0
pip                       10.0.1                   py36_0
pluggy                    0.8.0                     <pip>
prompt_toolkit            2.0.6                    py36_0
psutil                    5.4.7            py36hfa6e2cd_0
pycodestyle               2.4.0                    py36_0
pycparser                 2.19                     py36_0
pydocstyle                3.0.0                     <pip>
pyflakes                  2.0.0                    py36_0
pygments                  2.2.0            py36hb010967_0
pylint                    2.1.1                    py36_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.2                    py36_0
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.6.8                    py36_0
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.3                    py36_0
python-jsonrpc-server     0.0.2                     <pip>
python-language-server    0.21.2                    <pip>
pytz                      2018.5                   py36_0
pywin32                   223              py36hfa6e2cd_1
pyzmq                     17.1.2           py36hfa6e2cd_0
QDarkStyle                2.5.4                     <pip>
qt                        5.9.6            vc14h62aca36_0
qtawesome                 0.5.1                    py36_1
qtconsole                 4.4.2                    py36_0
qtpy                      1.5.2                    py36_0
requests                  2.19.1                   py36_0
rope                      0.11.0                   py36_0
setuptools                40.4.3                   py36_0
simplegeneric             0.8.1                    py36_2
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
snowballstemmer           1.2.1            py36h763602f_0
sphinx                    1.8.1                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder-kernels            1.0.1                    py36_0
sqlite                    3.25.2               hfa6e2cd_0
testpath                  0.4.2                    py36_0
tornado                   5.1.1            py36hfa6e2cd_0
traitlets                 4.3.2            py36h096827d_0
typed-ast                 1.1.0            py36hfa6e2cd_0
urllib3                   1.23                     py36_0
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
wheel                     0.32.2                   py36_0
win_inet_pton             1.0.1                    py36_1
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36hfa6e2cd_2
yapf                      0.24.0                    <pip>
zeromq                    4.2.5                he025d50_1
zlib                      1.2.11               h8395fce_2
```
</details>

----

I then followed up with some further testing:

0.19.0 both launched correctly and completion/introspection worked. I then installed 0.21.2 and confirmed the bug: Spyder launched and the mainwindow displayed, but then crashed, with the following relevant debug output:

<details>
```
2018-10-26 12:56:58,229 [DEBUG] [spyder.plugins.editor.plugin] -> Call LSP for C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\runtests.py
2018-10-26 12:56:58,230 [DEBUG] [spyder.plugins.editor.widgets.codeeditor] -> LSP available for: C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\runtests.py
2018-10-26 12:56:58,230 [DEBUG] [spyder.plugins.editor.plugin] -> LSP request: 'textDocument/didOpen'
2018-10-26 12:56:58,231 [DEBUG] [spyder.plugins.editor.lsp.client] -> python request: textDocument/didOpen
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFECDD994C4  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFEEC9FD32F  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFEEE5213D2  Unknown               Unknown  Unknown
ntdll.dll          00007FFEEF4C54F4  Unknown               Unknown  Unknown
QObject::~QObject: Timers cannot be stopped from another thread
````
</details>

I then installed 0.20.0 and Spyder launched fine, but completion and introspection didn't work from the Editor. When I tried, I got no output at all or the following in the attached console, and nothing happened in the UI:

<details>
```
2018-10-26 13:12:46,193 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Added thread <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7A40F78> to queue
2018-10-26 13:12:46,208 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Added thread <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7B35708> to queue
2018-10-26 13:12:46,244 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,244 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,245 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2018-10-26 13:12:46,245 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7A40F78>
2018-10-26 13:12:46,247 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,247 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,248 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 0
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7B35708>
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 0
```
</details>

I then installed 0.21.0, and Python crashed on startup, seemingly sooner than the before (the exact time the crash seems to happen seems to vary, as well as the exact debug output as to what Spyder's doing (so its presumably some sort of asynchronous event/thread with respect to the main Spyder setup), but it always seems to happen right around or a few seconds after the GUI first appears.

Also, I'm getting very unreliable behavior as to whether completion/introspection actually works or not. It worked when I first tested it in 0.19.0, didn't work when I upgraded to 0.20.0, crashed on 0.21.2 (obviously), didn't work when I downgraded again to 0.19.0, worked when I uninstalled and reinstalled it, didn't work again upgrading to 0.20.0, didn't work downgrading to 0.19.0 and now won't even work if I uninstall and reinstall 0.19.0, restarted Spyder twice, let it sit for several minutes, poked around the UI, ran some commands in the console, switched back and forth between help sources (and triggered help and completion from the console) and clicked my heels three times. I don't get any errors, just similar output to the above. Hopefully these are still teething difficulties...

----

UPDATE: I launched Spyder a day later (today) with the exact same commit, environment (0.19.0), even terminal window as before with zero changes (it was literally the next line in the shell I'd left open), and completion/introspection are now working again, with the typical output:

```
2018-10-27 14:50:16,836 [DEBUG] [spyder.plugins.editor.plugin] -> LSP request: 'textDocument/hover'
2018-10-27 14:50:16,836 [DEBUG] [spyder.plugins.editor.lsp.client] -> python request: textDocument/hover
```

It worked 3/3 times, whereas before with everything identical it was 0/3. Is this worth a separate issue? Or could there be something on my end that's causing it?

## Versions

* Spyder version: 4.0 master
* Python version: 3.6.6 x64
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

**Comment by jnsebgosselin** [comment] 2018-10-28 05:11
Related if not a duplicate of https://github.com/spyder-ide/spyder/issues/8022#issuecomment-430125437

As of today, the new architecture for introspection is more flimsy and less responsive than the old architecture was on Windows. But I have a lot of faith :)

**Closed** 2019-01-23 22:53 UTC
Labels: component:Help, type:Bug
