### ISSUE TITLE
Spyder tries to decode normal strings when used as an argument for an exception.

### ISSUE THREAD

**Issue by Giset0** [spyder-ide/spyder#6560] opened 2018-03-01 01:56 UTC
## Problem Description
When raising an Exception in Spyder with Python 2.7 with  a normal string (type 'str') containing special unicode characters, an UnicodeDecodeError is raised. But only if the string is used directly as an argument for the Exception, and not when a variable is used.

I know that you can't use unicode with exceptions in Python 2, but in Python 2 a string containing unicode characters should still be treated as a normal string, and not a unicode string. So I think that no decoding should happen, the unicode literal should just not be displayed correctly, but Spyder tries to decode the string anyway, but it can't with the 'ascii' decoding.

### What steps will reproduce the problem?

1.  Run the following line in Spyder:
```
raise Exception("é")
```

2. A different example showing the same behaviour, it doesn't help to give the coding explicitly for a unicode string.
```
raise Exception(u"é".encode('utf-8'))
```

3. A third example, happening with assert statements:
```
assert False, "é"
```
4. But the following lines dont cause the UnicodeDecodeError and work as expected:
```
s="é"
raise Exception(s)
```

5. And it works as expected, when the default encoding in sys is changed:
```
import sys
reload(sys) 
sys.setdefaultencoding('utf-8')
raise Exception("é")
```

### What is the expected output? What do you see instead?
The expected output would be a normal Error, instead of UnicodeDecodeError.

### Paste Traceback/Error Below (if applicable)

```python-traceback

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
```

## Package Versions

* Spyder: 3.2.6
* Python: 2.7.14 64bits
* Qt: 5.6.2
* PyQt: 5.6 on Windows
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-03-01 21:37
Thanks for reporting. I was unable to reproduce the error with identical versions of Spyder, Python, Qt, PyQt, IPython, and qtconsole on Win 8.1 Pro x64, either by running the above code in Spyder or in bare qtconsole. ``sys.getdefaultencoding()`` returns `'ascii`. What about on your machine? In any case, does this the exception a Spyder error (with an error dialog, etc) or in the console itself? If the latter does the exception occur only in Spyder, or in qtconsole (``jupyter qtconsole``), plain ``IPython``, and/or the standard Python interpreter? If not the former, then it is outside of our control.

**Comment by Giset0** [comment] 2018-03-01 22:11
Ok, I checked again, on a different computer. The `UnicodeDecodeError` does not occur if I enter the code directly into the console in Spyder, it only occurs if I create a script and run the file in Sypder (F5).
When I run the file in qtconsole, no `UnicodeDecodeError` occurs.

`sys.getdefaultencoding()` returns `'ascii'` for me as well.

So on two different computers (both with Windows 10 64bit, Spyder installed through Anaconda), the error occurs when I run a file with the line `raise Exception("é")`. Maybe it has to do with the way Spyder is parsing the file?
The Error is shown in the Console Window in Spyder.

This is the full Traceback, sorry I did not show in my last comment.
```
Traceback (most recent call last):

  File "C:\Users\Default\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2899, in run_code
    self.showtraceback()

  File "C:\Users\Default\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 1826, in showtraceback
    value, tb, tb_offset=tb_offset)

  File "C:\Users\Default\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1412, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)

  File "C:\Users\Default\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1329, in structured_traceback
    self, etype, value, elist, tb_offset, number_of_lines_of_context

  File "C:\Users\Default\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 644, in structured_traceback
    out_list.extend(self._format_list(elist))

  File "C:\Users\Default\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 694, in _format_list
    Colors.Normal)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
```

I hope it helps.

**Comment by CAM-Gerlach** [comment] 2018-03-01 22:42
It does, thanks very much. Running the file with ``runfile()`` does indeed produce the output you describe above; other methods do not. Furthermore, the full traceback is indeed helpful in pointing to the source of the problem. However, the actual traceback is entirely within the IPython codebase; it appears that for whatever reason, the runfile call is triggering the problem, while sending lines to the console normally is not. Its possible that could be worked around from the Spyder side, but it appears either the issue is with IPython in which case it should be taken up with them, or it is intrinsic to the lack of proper Unicode support in Python 2, in which case you should either avoid non-ASCII chars or upgrade to modern Python 3.

**Comment by Giset0** [comment] 2018-03-01 23:33
Ok, I can easily try to avoid non-ASCII characters.
But the error does not occur, if I run the the file through IPython (with the `%run` command). So I had the impression Spyder is passing for some reason the string as a unicode instead of normal string to IPython.

**Comment by CAM-Gerlach** [comment] 2018-03-01 23:35
Thanks. We'll see what @ccordoba12 thinks...

**Comment by CAM-Gerlach** [comment] 2018-03-02 01:45
@Giset0 You could start by taking a look at runfile and seeing how it calls IPython differently than just sending lines to console to isolate what's causing it and determine if it is fixable.

**Comment by Giset0** [comment] 2018-03-03 12:16
Ok, I will have a look at the code, but probably not before the end of next week.

**Comment by CAM-Gerlach** [comment] 2018-03-03 18:16
Thanks @Giset0 !

**Comment by goanpeca** [comment] 2019-11-28 01:05
I cannot reproduce this behavior.

<img width="691" alt="Screen Shot 2019-11-27 at 20 05 16" src="https://user-images.githubusercontent.com/3627835/69769076-41ab7400-1151-11ea-99f1-5a7a210642f2.png">

Closing.

**Closed by goanpeca** 2019-11-28 01:05 UTC
Labels: Package:Python2, component:IPython Console, status:Reproduced, type:Bug
