### ISSUE TITLE
Formatting error in Help pane 

### ISSUE THREAD

**Issue by wtheis** [spyder-ide/spyder#3632] opened 2016-11-01 13:52 UTC
## Description

**What steps will reproduce the problem?**

1. Display help for function with rich text docstring (e.g. numpy.sum())

**What is the expected output? What do you see instead?**
Parameters should be displayed with name and type in the same line:
**a** : array_like

Instead there is a newline after the ':'. See image below.

**Please provide any additional information below**
Same issue on Windows.
![spyder_help](https://cloud.githubusercontent.com/assets/21359688/19891935/432a0534-a03a-11e6-8e59-27ae839ddce0.png)

## Version and main components

* Spyder Version: 3.0.1 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2016-11-01 15:38
I don't know why this is the case now. Probably something that changed in Sphinx.

**Comment by ccordoba12** [comment] 2016-11-01 15:39
This is a duplicate of #3404, so closing.

**Closed by ccordoba12** 2016-11-01 15:39 UTC
Labels: Comp-Help, Type-Bug
