### ISSUE TITLE
Variable Explorer fails to display parent variable if child variable cannot be displayed

### ISSUE THREAD

**Issue by cirnod** [spyder-ide/spyder#21476] opened 2023-10-31 11:26 UTC
## Problem Description
The "Variable Explorer" of Spyder fails to display a (parent) variable if a (child) variable, that is contained in the double-clicked parent variable, cannot be displayed. 

### What steps reproduce the problem?

Example with pandas 1.5.3:
```
import pandas as pd
df = pd.DataFrame()
df['a'] = [1, 2, 3]
df.index = pd.Int64Index(df.index)
d = {0: df, 1: 5}
```

1. Create a parent data structure that contains a variable that cannot be displayed (in this case a DataFrame with Int64Index)
2. Double click the `d` variable in "Variable Explorer"

### What is the expected output? What do you see instead?
Expected output: variable is displayed in a new window
Actual output: "Spyder was unable to retrieve the value of this variable form the console. [...] An unknown error occurred. [...]"

I do not see any reason why the parent dictionary could not be displayed with a generic value / placeholder value for the DataFrame that cannot be displayed. 

## Versions
* Spyder version: 5.4.5 (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment] 2023-10-31 18:32
This is again due to the incompatibility with respect to serialization between Pandas 2 and 1.5. To expand a bit more on that, serialization means transforming a live object into a string so that it can recreated in another process.

When part of an object fails to be serialized, the entire object fails too, so it can't be deserialized to be displayed in our Variable Explorer. This is a fundamental limitation of the way serialization works, so we can't do anything about it, sorry.

**Comment by ccordoba12** [comment] 2023-10-31 18:33
Since this is basically a duplicate of #21475, I'm going to close it too.

**Closed by ccordoba12** 2023-10-31 18:33 UTC
