### ISSUE TITLE
Variable explorer doesn't work when click variable name

### ISSUE THREAD

**Issue by JasonLuo5** [spyder-ide/spyder#8617] opened 2019-01-22 06:03 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.15rc1
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.0 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
pylint >=0.25     :  1.9.4 (OK)

```

**Comment by bcolsen** [comment] 2019-01-22 17:08
Thanks for reporting. This is a duplicate of issue #8582

**Closed by bcolsen** 2019-01-22 17:08 UTC
