### ISSUE TITLE
Spyder3.0.1 starting with strange resolution

### ISSUE THREAD

**Issue by p1347** [spyder-ide/spyder#3566] opened 2016-10-20 17:00 UTC
## Hello,
whenever I start spyer3.0.1 the splash (startup) screen is greatly zoomed and looks pixelated, like when you select a wrong (a much smaller) resolution than the native monitor resolution on your system. That wouldn't bother me at all, but unfortunately the toolbar and its icons is HUGE and so is the content of the help-window (what used to be the object inspector). I searched all the settings but I don't think I can adjust this by myself to the normal size again, this is probably some dependency issue with some graphic lib (I successfully installed all the necessary files, spyder depends on with pip3 on my fedora24 system). In the console where I start spyder I get the message
"[1020/184355:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on." but I don't know whether that is related to my problem.

Many thanks in advance!

**What steps will reproduce the problem?**

1. starting spyder on fedora24

**What is the expected output? What do you see instead?**
GUI with normal sizes on toolbars and contents e.g. in the help-window.

**Please provide any additional information below**
I installed spyder with pip3 on Fedora24

## Versions and main components

* Spyder Version:3.0.1
* Python Version: 3.5
* Operating system: Fedora24

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-20 20:28
Thanks for reporting. This is a duplicate of issue #3489 and it'll be fixed in 3.0.2 :-)

**Closed by ccordoba12** 2016-10-20 20:28 UTC

**Comment by ccordoba12** [comment] 2016-10-20 20:30
And the error you reported about `SUID sandbox` is harmless ;-)

**Comment by p1347** [comment] 2016-10-20 20:31
Great - many thanks!
