### ISSUE TITLE
Spyder crashes trying to edit a DataFrame (needs reproducible example)

### ISSUE THREAD

**Issue by skidzo** [spyder-ide/spyder#2496] opened 2015-06-20 11:17 UTC
## Description

* *What steps will reproduce the problem?*
1. click on values of DataFrame object in Variable explorer
2. loading slow like hell
3. when i click ok to get rid of this spyder crashes, see below...

* *What is the expected output? What do you see instead?*

Expecting to see the relatively small sized array, with its values, rows/indexes and columns/header

* *Please provide any additional information below*

```
(process:11419): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(firefox:11419): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(firefox:11419): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(firefox:11419): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(firefox:11419): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
get_contentWindow@chrome://global/content/bindings/browser.xml:429:54
get_securityUI@chrome://global/content/bindings/browser.xml:675:17
browser_XBL_Constructor@chrome://global/content/bindings/browser.xml:799:17
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
get_contentWindow@chrome://global/content/bindings/browser.xml:429:54
get_securityUI@chrome://global/content/bindings/browser.xml:675:17
browser_XBL_Constructor@chrome://global/content/bindings/browser.xml:799:17
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
exports.Utils.yield@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/utils.js:382:12
INIParser.prototype.process@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/filterStorage.js:870:7
exports.IO.readFromFile/onProgress@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/io.js:97:15
exports.IO.readFromFile/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/jeckstein/.mozilla/firefox/blw2231t.default/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/io.js:182:11
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:867:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:688:37
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
get_contentWindow@chrome://global/content/bindings/browser.xml:429:54
get_securityUI@chrome://global/content/bindings/browser.xml:675:17
browser_XBL_Constructor@chrome://global/content/bindings/browser.xml:799:17
SelfSupportBackendInternal._makeHiddenBrowser/<@resource:///modules/SelfSupportBackend.jsm:192:7
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
pbs<@resource://unity/observer.js:38:71
Observer.prototype.observe@resource://unity/observer.js:77:24
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QWidget::repaint: Recursive repaint detected
QPaintDevice: Cannot destroy paint device that is being painted
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.6
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=1.0   :  1.2.1 (OK)
zmq >=2.1.11    :  14.0.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.13.1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  0.9.2 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.1.0 (OK)

**Comment by ccordoba12** [comment] 2015-06-20 19:59
A couple of comments:

1. Please give us a reproducible example, i.e. a code snippet that we can test in our side to debug your problem.
2. Did you append your `~/.xsession-errors` file? That's not helpful either because, as you can see, there are Firefox errors and warnings in your report that don't help us to fix your problem :-)

**Comment by ccordoba12** [comment] 2015-07-14 05:51
Closing because of lack of further info

**Closed by ccordoba12** 2015-07-14 05:51 UTC
Labels: bug, Variable-Explorer
