### ISSUE TITLE
just starting up

### ISSUE THREAD

**Issue by DrAndrewHayes-NRLSSC** [spyder-ide/spyder#15596] opened 2021-05-11 20:04 UTC
### What steps will reproduce the problem?

As soon as I start Spyder, this issue reported pops up. LSP Python always fails at first and has to be manually restarted to work. I don't know if that's related.

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ahayes\Anaconda3\lib\logging\__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\ahayes\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2312, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2208, in create_window
    app.exec_()
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.016377449035645,)
```

## Versions

* Spyder version: 5.0.2 
* Python version: 3.8.10
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.2;<2.1.0 :  2.0.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.18.5 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by steff456** [comment] 2021-05-12 03:28
Hi @DrAndrewHayes-NRLSSC,

This issue is happening for you on 5.0.2 version? If so, can you explain to me how you made the update and what were you doing when this error pop out?

**Comment by ccordoba12** [comment] 2021-06-03 17:31
Closing as a duplicate of issue #15768. We're investigating why this problem happens and we'll try to solve it soon.

**Closed by ccordoba12** 2021-06-03 17:31 UTC
Labels: status:Awaiting Followup
