### ISSUE TITLE
Spyder + Plotly Debug Mode Error

### ISSUE THREAD

**Issue by xywang84** [spyder-ide/spyder#20949] opened 2023-05-19 23:36 UTC
### What steps will reproduce the problem?

The following code does not run in debug mode in Spyder:

test_script.py
```
import plotly.express as px
import numpy as np
import plotly.io as pio
pio.renderers.default="browser"

fig = px.imshow(np.random.randn(100,100))
print("done")
```

running test_script.py as follows:

>> runfile('test_script.py')
done

But running in debug mode yields the message 

```
  fig = px.imshow(np.random.randn(100,100))

  File ~/miniconda3/envs/linearx/lib/python3.11/site-packages/plotly/express/_imshow.py:236 in imshow
    apply_default_cascade(args)


   apply_default_cascade(args)

  File ~/miniconda3/envs/linearx/lib/python3.11/site-packages/plotly/express/_core.py:931 in apply_default_cascade
    x[1] for x in args["template"].layout.colorscale.sequential

AttributeError: 'NoneType' object has no attribute 'layout'
```

I view this as a spyder error because it does not show up when debugging the same script in VS studio code. 

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Linux 5.15.90.1-microsoft-standard-WSL2

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.1 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.5 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  65.6.3 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
xdg >=0.26                                       :  0.28 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  None (NOK)
numpy >=1.7                                      :  None (NOK)
pandas >=1.1.1                                   :  None (NOK)
scipy >=0.17.0                                   :  None (NOK)
sympy >=0.7.3                                    :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /home/xywang/miniconda3/envs/linearx:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
abseil-cpp                20211102.0           hd4dd3e8_0  
absl-py                   1.3.0           py311h06a4308_0  
aiohttp                   3.8.3           py311h5eee18b_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
astroid                   2.14.2          py311h06a4308_0  
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2           py311h06a4308_0  
attrs                     22.1.0          py311h06a4308_0  
backcall                  0.2.0                    pypi_0    pypi
black                     23.3.0          py311h06a4308_0  
blas                      1.0                         mkl  
blinker                   1.4             py311h06a4308_0  
bottleneck                1.3.5           py311hbed6279_0  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py311h5eee18b_1002  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.01.10           h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2022.12.7       py311h06a4308_0  
cffi                      1.15.1          py311h5eee18b_3  
cfgv                      3.3.1                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py311h06a4308_0  
cloudpickle               2.2.1                    pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
colorama                  0.4.6           py311h06a4308_0  
comm                      0.1.3                    pypi_0    pypi
contourpy                 1.0.5           py311hdb19cb5_0  
coverage                  7.2.2           py311h5eee18b_0  
cryptography              39.0.1          py311h9ce1e76_0  
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.6           py311h06a4308_0  
distlib                   0.3.6                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0  
fastjsonschema            2.16.3                   pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3           py311h5eee18b_0  
garpy-linearx             0.1.0                     dev_0    <develop>
giflib                    5.2.1                h5eee18b_3  
glib                      2.69.1               he621ea3_2  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.1                      py_2  
grpc-cpp                  1.48.2               h5bf31a4_0  
grpcio                    1.48.2          py311h5bf31a4_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
icu                       58.2                 he6710b0_3  
identify                  2.5.22                   pypi_0    pypi
idna                      3.4             py311h06a4308_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.22.0                   pypi_0    pypi
ipython                   8.12.0                   pypi_0    pypi
isort                     5.9.3              pyhd3eb1b0_0  
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.4.4           py311h6a678d5_0  
krb5                      1.19.4               h568e23c_0  
lazy-object-proxy         1.6.0           py311h5eee18b_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libllvm14                 14.0.6               hdb19cb5_2  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.9                 h16c4e8d_3  
libprotobuf               3.20.3               he621ea3_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.0                h6a678d5_2  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.3               hcbfbd50_0  
libxslt                   1.1.37               h2085143_0  
lit                       16.0.1                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.1           py311h06a4308_0  
markupsafe                2.1.1           py311h5eee18b_0  
matplotlib                3.7.1           py311h06a4308_1  
matplotlib-base           3.7.1           py311ha02d727_1  
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0              pyhd3eb1b0_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py311h5eee18b_0  
mkl_fft                   1.3.1           py311h30b3d60_0  
mkl_random                1.2.2           py311hba01205_0  
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.2           py311h5eee18b_0  
multiprocess              0.70.14                  pypi_0    pypi
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3           py311h06a4308_1  
nbformat                  5.8.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
nodeenv                   1.7.0                    pypi_0    pypi
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numexpr                   2.8.4           py311h802d673_0  
numpy                     1.23.5          py311h75bd12f_0  
numpy-base                1.23.5          py311h0ff3221_0  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
oauthlib                  3.2.2           py311h06a4308_0  
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
orjson                    3.8.12                   pypi_0    pypi
packaging                 23.0            py311h06a4308_0  
pandas                    1.5.3           py311hba01205_0  
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.10.3          py311h06a4308_0  
patsy                     0.5.3           py311h06a4308_0  
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.4.0           py311h6a678d5_0  
pip                       23.0.1          py311h06a4308_0  
platformdirs              3.2.0                    pypi_0    pypi
plotly                    5.9.0           py311h06a4308_0  
pluggy                    1.0.0           py311h06a4308_1  
ply                       3.11            py311h06a4308_0  
pooch                     1.4.0              pyhd3eb1b0_0  
pre-commit                3.2.2                    pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  3.20.3          py311h6a678d5_0  
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0             pyhd3eb1b0_0  
pyarbtools                2022.11.2                pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.15.1                   pypi_0    pypi
pyjwt                     2.4.0           py311h06a4308_0  
pylint                    2.16.2          py311h06a4308_0  
pyopenssl                 23.0.0          py311h06a4308_0  
pyparsing                 3.0.9           py311h06a4308_0  
pyqt                      5.15.7          py311h6a678d5_0  
pyqt5-sip                 12.11.0         py311h6a678d5_0  
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1           py311h06a4308_0  
pytest                    7.1.2           py311h06a4308_0  
pytest-cov                4.0.0           py311h06a4308_0  
python                    3.11.2               h7a1cb2a_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytz                      2022.7          py311h06a4308_0  
pyvisa                    1.13.0                   pypi_0    pypi
pyyaml                    6.0             py311h5eee18b_1  
pyzmq                     25.0.2                   pypi_0    pypi
qt-main                   5.15.2               h8373d8f_8  
qt-webengine              5.15.9               hbbf29b9_6  
qtwebkit                  5.212                h3fafdc1_5  
re2                       2022.04.01           h295c915_0  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1          py311h06a4308_1  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
scipy                     1.10.1          py311hc206e33_0  
setuptools                66.0.0          py311h06a4308_0  
sip                       6.6.2           py311h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
socketscpi                2023.4.0                 pypi_0    pypi
spyder-kernels            2.4.3                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.2                    pypi_0    pypi
statsmodels               0.13.5          py311h5eee18b_1  
sympy                     1.11.1                   pypi_0    pypi
tenacity                  8.0.1           py311h06a4308_1  
tensorboard               2.6.0                      py_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py311h06a4308_0  
tomlkit                   0.11.1          py311h06a4308_0  
torch                     2.0.0                    pypi_0    pypi
torchaudio                2.0.1                    pypi_0    pypi
torchvision               0.15.1                   pypi_0    pypi
tornado                   6.2             py311h5eee18b_0  
tqdm                      4.65.0          py311h92b7b1e_0  
traitlets                 5.9.0                    pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.15         py311h06a4308_0  
virtualenv                20.22.0                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.2.3           py311h06a4308_0  
wget                      3.2                      pypi_0    pypi
wheel                     0.38.4          py311h06a4308_0  
wrapt                     1.14.1          py311h5eee18b_0  
wurlitzer                 3.0.3                    pypi_0    pypi
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                3.0.3              pyhd3eb1b0_0  
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.8.1           py311h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0  

```
</details>

**Comment by xywang84** [comment] 2023-05-19 23:40
Is this similar to

**Comment by xywang84** [comment] 2023-05-19 23:40
Is this similar to https://github.com/spyder-ide/spyder/issues/20639

**Comment by xywang84** [comment] 2023-05-20 00:10
Also to further elaborate. it appears this problem appears anytime you enter debug mode in ipdb. Even if you use the breakpoint() keyword in a file, the first time the breakpoint is activated once any further invocations of px.imshow or other plotly functions that call the plotly/express/_core.py  apply_default_cascade function will cause this error until the kernel is restarted **even if you exit debug mode**

**Comment by ccordoba12** [comment] 2023-05-20 18:10
> Is this similar to https://github.com/spyder-ide/spyder/issues/20639

Yep, it is. Closing as a duplicate of that issue then.

**Closed by ccordoba12** 2023-05-20 18:10 UTC
