### ISSUE TITLE
Matplotlib Figures not cleaned up during loop

### ISSUE THREAD

**Issue by mpu-creare** [spyder-ide/spyder#2538] opened 2015-07-14 17:52 UTC
It seems like while generating plots in a loop, the memory grows over time when running the script in spyder.

I have a funny use-case where I'm making a lot of large plots, and then when I'm done I like to interactively look at the last plot that was generated. 

To reproduce using this little script:

``` python
import sys
import gc
import numpy as np
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt

arr = np.random.rand(10000, 10000)

def memplot_plot(arr):
    plt.matshow(arr)    
    plt.close()

print '*' * 80
for i in range(1, 10):
    print 'i : ' + str(i)    
    print  len( gc.get_objects())
    print sys.getsizeof(gc.get_objects())
    memplot_plot(arr)    
    gc.collect()
print '*' * 80
```

From the command-line

``` bash
*****************************************
i : 1
61424
514568
i : 2
61710
514568
i : 3
61713
514568
i : 4
61716
514568
i : 5
61719
514568
i : 6
61722
514568
i : 7
61725
514568
i : 8
61728
514568
i : 9
61731
514568
*****************************************
```

From spyder, running in a dedicated terminal with interaction afterwards

```
********************************************************************************
i : 1
64416
578936
i : 2
67685
578936
i : 3
70737
578936
i : 4
73789
651352
i : 5
76841
651352
i : 6
79893
651352
i : 7
82945
732816
i : 8
85997
732816
i : 9
89049
732816
********************************************************************************
```

And for fun, my windows task manager. The four small blips are four runs from the commandline (python, python -i, ipython and ipython -i). The last one is from Spyder. And this is not clean because I'm also working in the background. 
![mpl_memory_leak](https://cloud.githubusercontent.com/assets/12446685/8680364/e2557b94-2a2e-11e5-88da-71207994268a.png)

``` python
matplotlib.get_backend()
Out[2]: u'Qt4Agg'

matplotlib.__version__
Out[3]: '1.4.3'
```

Let me know if you need any more information. Same behavior was observed on a colleague's machine.

**Comment by ccordoba12** [comment] 2015-07-15 04:15
What's your Spyder version?

**Comment by mpu-creare** [comment] 2015-07-15 12:10
Spyder version 2.3.5.2 . (btw, loved the docrepr talk at scipy).

**Comment by Nodd** [comment] 2015-09-30 12:44
I can't reproduce it in last master under Linux.

**Comment by mpu-creare** [comment] 2015-10-02 20:28
I haven't tried to reproduce in Linux. I've only seen this on Windows.

**Comment by goanpeca** [comment] 2019-11-28 02:09
@dalthviz could you check if you can reproduce this on win?

**Comment by dalthviz** [comment] 2019-11-28 15:19
This is what I'm getting:

### Using Spyder:

![image](https://user-images.githubusercontent.com/16781833/69817181-06985780-11c8-11ea-8e19-3e903050e8bd.png)

```python
********************************************************************************
i : 1
106810
927568
i : 2
107586
927568
i : 3
107594
927568
i : 4
107592
927568
i : 5
107600
927568
i : 6
107603
927568
i : 7
107601
927568
i : 8
107609
927568
i : 9
107607
927568
********************************************************************************
```

### Using the command line

![image](https://user-images.githubusercontent.com/16781833/69816915-67736000-11c7-11ea-83fb-dbb007eb7fef.png)

```python
********************************************************************************
i : 1
50745
406496
1611
i : 2
51645
457352
1611
i : 3
51647
457352
1611
i : 4
51650
457352
1611
i : 5
51653
457352
1611
i : 6
51656
457352
1611
i : 7
51659
457352
1611
i : 8
51662
457352
1611
i : 9
51665
457352
1611
********************************************************************************
```

So I think some cleaning its being done while using Spyder

**Comment by goanpeca** [comment] 2019-11-28 15:22
So, should we close?

**Comment by ccordoba12** [comment] 2019-11-28 15:22
This is very old, let's close it.

**Closed by ccordoba12** 2019-11-28 15:22 UTC
Labels: component:IPython Console, type:Bug
