### ISSUE TITLE
Spyder problem(help)

### ISSUE THREAD

**Issue by delroypearson** [spyder-ide/spyder#5936] opened 2017-12-09 13:51 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\administrator.lt12delroy\appdata\local\programs\python\python35-32\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "c:\users\administrator.lt12delroy\appdata\local\programs\python\python35-32\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "c:\users\administrator.lt12delroy\appdata\local\programs\python\python35-32\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "c:\users\administrator.lt12delroy\appdata\local\programs\python\python35-32\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "c:\users\administrator.lt12delroy\appdata\local\programs\python\python35-32\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "c:\users\administrator.lt12delroy\appdata\local\programs\python\python35-32\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "c:\users\administrator.lt1

**Comment by CAM-Gerlach** [comment] 2017-12-09 20:47
Thanks for reporting. The error message above is incomplete, but this appears to be a duplicate of e.g. #5673. As the full error message states, Jedi is only compatible with `parso` 0.1.0, not 0.1.1. Therefore, please downgrade to 0.1.0 to fix this, e.g. with
```
conda install parso=0.1.0
```
or
```
pip install parso==0.1.0
```
 and you can close this issue.

**Comment by delroypearson** [comment] 2017-12-09 22:50
How?

**Comment by CAM-Gerlach** [comment] 2017-12-09 23:41
As stated above, enter 
> ```
> conda install parso=0.1.0
> ```
> or
> ```
> pip install parso==0.1.0
> ```
at the Anaconda prompt/command prompt, depending on how you installed `parso` or whatever it came with (e.g. Anaconda).

**Comment by ccordoba12** [comment] 2017-12-10 01:05
@delroypearson, stop opening more issues about the same problem and switch to Anaconda if you want to fix this problem.

**Closed** 2017-12-10 01:04 UTC

**Comment by delroypearson** [comment] 2017-12-10 11:40
Ok
