### ISSUE TITLE
Comments not compliant with PEP8

### ISSUE THREAD

**Issue by joe-123** [spyder-ide/spyder#3507] opened 2016-10-06 09:46 UTC
## Description
Toggle comment (Ctrl+1) and block comment (Ctrl+4) don't comply to PEP8 since white-spaces are missing. The code style analysis (great feature!) always complains which is quite annoying.

**What is the expected output? What do you see instead?**
-> # comment (PEP8)
-> #comment (not PEP8)

## Version and main components

* Spyder Version: 2.x and 3

**Comment by Nodd** [comment] 2016-10-06 16:26
There should be an opened issue about it already. Following pep8 can make problems when uncommenting in some corner cases, that's why no one has worked on it yet.

**Comment by ccordoba12** [comment] 2016-10-07 21:15
Yep, this is a duplicate of issue #1785, but thanks for reporting :-)

**Closed by ccordoba12** 2016-10-07 21:15 UTC
