### ISSUE TITLE
Profiler does not work 

### ISSUE THREAD

**Issue by Aeishwaryab** [spyder-ide/spyder#12331] opened 2020-04-15 07:34 UTC
### What steps will reproduce the problem?

Starting the profiler 
Click profile
it shows an internal error 

The script is working normally. 

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\profiler\widgets\profilergui.py", line 267, in <lambda>
    self.finished(ec, es))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\profiler\widgets\profilergui.py", line 335, in finished
    self.show_errorlog()  # If errors occurred, show them.
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\profiler\widgets\profilergui.py", line 240, in show_errorlog
    readonly=True, size=(700, 500), parent=self).exec_()
TypeError: __init__() got an unexpected keyword argument 'size'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.4
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.1 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.2 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by jitseniesen** [comment] 2020-04-15 08:04
Thank you for your report. This is a duplicate of issue #11875 which is already fixed in our development version. The next release of Spyder will include this fix.

**Closed by jitseniesen** 2020-04-15 08:04 UTC
