### ISSUE TITLE
Failed to suto-install kite

### ISSUE THREAD

**Issue by JLongford** [spyder-ide/spyder#14808] opened 2021-02-23 20:07 UTC
### What steps will reproduce the problem?

Auto pop-up on launching Spyder asked to install kite. I agreeed and it failed. 

### Traceback
```python-traceback
  File "C:\Users\Jonathan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\completion\kite\widgets\install.py", line 308, in install
    self.setup(integration=False, welcome=False, installation=True)
TypeError: setup() got an unexpected keyword argument 'welcome'
```

## Versions

* Spyder version: 4.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  53.0.0 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by dalthviz** [comment] 2021-02-24 17:58
Hi @JLongford thanks for the feedback!

Pinging @ccordoba12 just in case

**Comment by dalthviz** [comment] 2021-02-24 18:06
@JLongford if you want to install Kite you can download the installer here: https://www.kite.com/download (no further setup is needed from the Spyder side)

**Comment by ccordoba12** [comment] 2021-02-24 19:58
Hey @dalthviz and @JLongford, this is a duplicate of issue #14801. So I'm closing it in favor of that one.

**Closed by ccordoba12** 2021-02-24 19:58 UTC
Labels: type:Bug

**Comment by JLongford** [comment] 2021-02-24 20:07
Kite successful installed,

Thank you for your help!
