### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by rhiosutoyo** [spyder-ide/spyder#5648] opened 2017-11-03 09:27 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\avalon\appdata\local\programs\python\python36\lib\site-packages\spyder\app\mainwindow.py", line 2610, in edit_preferences
    dlg.add_page(widget)
  File "c:\users\avalon\appdata\local\programs\python\python36\lib\site-packages\spyder\plugins\configdialog.py", line 234, in add_page
    widget.apply_button_enabled.connect(self.apply_btn.setEnabled)
AttributeError: 'NoneType' object has no attribute 'setEnabled'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by liuyaqiu** [comment] 2017-11-03 12:51
I also meet this problem.It may be a bug.

**Comment by kov-serg** [comment] 2017-11-03 13:47
Solved https://github.com/spyder-ide/spyder/issues/5649

**Comment by ccordoba12** [comment] 2017-11-03 14:35
Closing as a duplicate of #5649.

**Closed by ccordoba12** 2017-11-03 14:35 UTC
