### ISSUE TITLE
启动ipython内核时发生错误

### ISSUE THREAD

**Issue by yugukaci** [spyder-ide/spyder#15332] opened 2021-04-18 14:50 UTC
### What steps will reproduce the problem?

Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\browser.py", line 332, in contextMenuEvent
    self.context_menu.popup(event.globalPos())
AttributeError: 'NoneType' object has no attribute 'popup'
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\browser.py", line 332, in contextMenuEvent
    self.context_menu.popup(event.globalPos())
AttributeError: 'NoneType' object has no attribute 'popup'
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\browser.py", line 332, in contextMenuEvent
    self.context_menu.popup(event.globalPos())
AttributeError: 'NoneType' object has no attribute 'popup'
--- Logging error ---
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\external\github.py", line 246, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\github\backend.py", line 141, in send_report
    ret = repo.issues.post(title=title, body=body)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\external\github.py", line 124, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\external\github.py", line 260, in _http
    raise ApiError(url, req, resp)
spyder.utils.external.github.ApiError: https://api.github.com/repos/spyder-ide/spyder/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "D:\ProgramData\Anaconda3\envs\tensorflow\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\reporterror.py", line 380, in _submit_to_github
    github_report = github_backend.send_report(title, issue_text)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\github\backend.py", line 143, in send_report
    _logger().warning('Failed to send bug report on Github. '
Message: 'Failed to send bug report on Github. response=%r'
Arguments: {'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-04-19 01:30
Hey @yugukaci, thanks for reporting. This is a duplicate of issue #15098 and it'll be fixed in our next version (5.0.1), to be part of Anaconda shortly.

**Closed by ccordoba12** 2021-04-19 01:30 UTC
