### ISSUE TITLE
very slow auto completion with pandas

### ISSUE THREAD

**Issue by MarcusAllen** [spyder-ide/spyder#2407] opened 2015-05-06 08:58 UTC
Hi,
I'm using the latest version of spyder 2.3.4 and pandas 16.0 , both installed with conda. 
Python 3.4.3 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.3 on Linux

The auto completion works fine on ipython console but in script editor it is extremly slow. Here is an example

import pandas as pd

pd. #<-- this will work fine

df=pd.read_csv('myfile.csv') #<- this will work fine too

df. #<- this would freeze my laptop for about 5 seconds

I noticed that bug only with pandas package and on the editor (again, on ipython console it works fine).

Thank you

**Comment by ccordoba12** [comment] 2015-05-06 20:17
@MarcusAllen, you're basically lucky to get any completions at all :-)

We're trying to develop a better method to get completions on assignations, like the one you're using

    df = pd.read_csv('myfile.csv')

and the issue we're discussing this is #2162, so I'm marking this one as duplicate of that one.

**Comment by Nodd** [comment] 2015-05-06 20:37
About speed, it seems that the autocompletion blocks the main thread instead of being done in the background. Did you notice that @blink1073 ?
So I don't think it's a duplicate as it is about speed and not about results.

**Comment by ccordoba12** [comment] 2015-05-06 20:40
@Nodd, I'm not getting any completions, and usually Jedi nor Rope can't get completions on assignations.

Could you tell @blink1073 where exactly the blocking is happening?

**Comment by Nodd** [comment] 2015-05-06 20:50
I didn't test with this example, it's just something I notice from time to time. Since usually it's very fast it's not visible, but from time to time I see small freezes with autocompletion (I use it almost exclusively in the editor, I don't know about consoles). It may be due to the machine itself which is occupied so I don't know for sure (that's why I didn't report it yet).

**Comment by MarcusAllen** [comment] 2015-05-07 09:42
I do have completions after the freeze.
Sorry i'll try to be for more precise: right after writing the dot in "df." the system starts to freeze and five seconds later the tab of completions appears.

i repost my config

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.6.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  None (NOK)



if you need a video i can try to upload one

**Comment by ccordoba12** [comment] 2015-05-07 21:29
@MarcusAllen, as I say, I don't understand how you're getting completions in this case. But this is a problem we're trying to solve in a different way.

**Comment by ccordoba12** [comment] 2015-05-07 21:30
In any case, the delay is not Spyder's fault but of the libraries it uses to get completions in the Editor, i.e. rope and jedi :-)

**Comment by Argentan** [comment] 2015-05-23 20:30
I had been using Winpython 2.7.9.4 and I came across a very similar issue after updating to 3.4.3.3 (equivalent release in 2.7 is 2.7.9.5). After reading this, I notice that this release of winpython included jedi for the first time, the jedi version is 0.8.1. I solved the problem updating jedi to 0.9.0.
I had to uninstall 0.8.1 too, somehow both versions coexisted. I don't know if this is Winpyton specific or not.

To be clear about the problem, I was getting a 5-10 sec freeze after the typing a dot after a pd.DataFrame object created from_csv. e.g.:
df = pd.DataFrame.from_csv('file.csv')
df.<freeze>

Finally, with 0.8.1 I was getting completions, but the freeze was too annoying. After updating to 9.0 I don't get any completion but no freeze either. Also, this happen only on the editor, the console completions were as fast as usual

**Comment by MarcusAllen** [comment] 2015-05-23 21:32
I agree it's totally a jedi related issue.
I removed jedi and now everything is smooth. However i still have auto completion in editor except for the "df." thing.

**Comment by ccordoba12** [comment] 2015-05-25 18:05
@blink1073, could you take a quick look at this one?

Have Jedi improved its support to complete assignments?

**Comment by blink1073** [comment] 2015-05-25 22:47
@ccordoba12, the reason they were seeing no completions is that completions are broken with Jedi 0.9 pending #2445.  This is related to an open issue in Jedi: https://github.com/davidhalter/jedi/issues/520.  Also, the overall slowdown of our editor is most likely due to the fact that the Introspection is run in a thread, so it is contending with the main thread for resources.

**Comment by ccordoba12** [comment] 2015-05-30 22:06
I merged #2245, so now we have to wait for a fix in Jedi ;-)

**Comment by blink1073** [comment] 2015-05-30 22:29
@ccordoba12, I think you mean #2445.  :stuck_out_tongue_winking_eye:

**Comment by ccordoba12** [comment] 2015-05-30 22:31
Yep, busted here!! ;-)

**Comment by auerbacs** [comment] 2015-07-31 19:49
I've never heard of Jedi, but I similarly get this lag after typing a period following a dataframe that was loaded from a csv. It's obviously the autocompletion, as turning off autocompletion fixes the issue. Do I have Jedi and I just don't know about it, or is it something else. I'm just using Anaconda and Spyder (though I know a lot is rolled into Anaconda).

**Comment by ccordoba12** [comment] 2015-07-31 19:53
If you're using the latest Anaconda (2.3), or updated to the latest 
Spyder (2.3.5.2), then yes, you're using Jedi :-)

**Comment by auerbacs** [comment] 2015-07-31 20:09
Indeed I am, so that explains it. Thanks @ccordoba12 .

**Closed** 2016-02-29 04:48 UTC
Labels: Bug, Editor
