### ISSUE TITLE
The output text color of pandas.DataFrame.shape is same as background

### ISSUE THREAD

**Issue by AlexLuya** [spyder-ide/spyder#4099] opened 2017-02-03 10:19 UTC
Just look like this:
![workspace 1_053](https://cloud.githubusercontent.com/assets/303353/22587587/e1b9c9b0-e9c7-11e6-92b3-d1d25479596f.png)

## Versions and main components
* Spyder Version: 3.0.2
* Python Version: 2.7.12
* Operating system:ubuntu 16.04 64bit

**Comment by ccordoba12** [comment] 2017-02-06 09:58
This probably happens because you're using a dark background and perhaps Sympy too.

Am I right about Sympy?

**Comment by AlexLuya** [comment] 2017-03-21 06:15
Yes,I am using a dark background and sympy,why do this combination cause problem?

**Comment by ccordoba12** [comment] 2017-03-21 13:44
Because sympy makes some output to transformed to images with text in black.

To fix this we need to submit a pull request to sympy.

**Comment by ccordoba12** [comment] 2017-08-13 17:43
This is a duplicate of issue #3798.

**Closed by ccordoba12** 2017-08-13 17:43 UTC
Labels: resolution:Duplicate
