### ISSUE TITLE
Bug in the Ipython console (Spyder 2.3.8)

### ISSUE THREAD

**Issue by maimonid** [spyder-ide/spyder#2876] opened 2015-12-20 21:38 UTC
I used to restart the kernel of the Ipython console very often because there is nothing else in Ipython that allows clearing the variables and cleaning the memory. After I have updated to the last version of Anaconda (Python 3.5, spyder 2.3.8), it turns out that it is difficult to work this way; the reason: a bug (apparently) in the Ipython console, that forces me to restart the whole Spyder each time. Here is a way to reproduce the bug that appears very often and in various circumstances: open Spyder, then type some stupid thing in the Ipython console, like "asdf" and type "Enter" in order to generate an error message. Then restart the kernel using the top right button of the Ipython console. Now, type "1" or anything else and then "Enter": nothing will appear but only a "...: " will appear on the next line. Actually, the Ipython console is now unusable, and you are forced to restart the whole Spyder.

**Comment by ccordoba12** [comment] 2015-12-21 05:01
This is a duplicate of issue #2696 and will be fixed in Spyder 3.0.

**Closed** 2015-12-21 05:01 UTC
Labels: Duplicate
