### ISSUE TITLE
autocomplete of pandas DataFrames filled by .from_csv() causes crash on OS X

### ISSUE THREAD

**Issue by ptthompsonzul** [spyder-ide/spyder#2695] opened 2015-09-14 16:56 UTC
On my mac mini (Macmini6,1) with OS X 10.10.5, using autocomplete on a pandas DataFrame object which has been filled with the pandas.DataFrame.from_csv() method, Spyder crashes to desktop.  Following code provides reliable crash reproduction on my system:

import pandas as pd
a = pd.DataFrame()
a = pd.DataFrame.from_csv('test.csv')
b = a.

As soon as the . is typed following 'b = a', spyder begins to hang, and then crashes within a few seconds.  If the from_csv() assignment is not made, then no crash occurs. Assigning using the DataFrame constructor as below also does not cause a crash, and the autocomplete list populates as expected when the . is typed after 'b = a':

import pandas as pd
a = pd.DataFrame([[1,1],[2,1]])
b = a.

Using Anaconda python distribution with a python 3.4 environment. Have run 'conda update --all' several times to make sure no packages are out of date.

**Comment by ccordoba12** [comment] 2015-09-14 17:03
Does this happen in the Editor or the Python/IPython console?

**Comment by ptthompsonzul** [comment] 2015-09-14 17:04
Occurs in the editor.  Haven't tried it in the iPython console.

**Comment by ccordoba12** [comment] 2015-09-14 17:06
Please downgrade Jedi to 0.8.1 with this command:

    conda install jedi==0.8.1

to temporarily fix this problem.

**Comment by ccordoba12** [comment] 2015-09-14 17:10
Closing as duplicate of #2659

**Closed by ccordoba12** 2015-09-14 17:10 UTC
Labels: duplicate

**Comment by ptthompsonzul** [comment] 2015-09-14 17:17
Confirming, downgrade to jedi 0.8.1 does prevent crash. There IS a noticeable delay before the autocomplete list shows up though (on the order of 5-10 seconds).  Thanks for the work around. :)
