### ISSUE TITLE
UnicodeEncodeError when autosaving

### ISSUE THREAD

**Issue by pgr123** [spyder-ide/spyder#11868] opened 2020-03-19 10:26 UTC
I tried to update my spyder 4.0.1 with 4.1.1 but I got a problem :+1: 

pascal@Lenovo-H515s:~$ sudo pip install --pre -U spyder

and when I run spyder, I get :

pascal@Lenovo-H515s:~$ spyder
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 955, in setup
    self.editor = Editor(self)
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/editor/plugin.py", line 178, in __init__
    self.autosave.try_recover_from_autosave()
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/editor/utils/autosave.py", line 178, in try_recover_from_autosave
    dialog = RecoveryDialog(files_to_recover, parent=parent)
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/editor/widgets/recover.py", line 99, in __init__
    self.add_table()
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/editor/widgets/recover.py", line 183, in add_table
    self.add_label_to_table(idx, 0, file_data_to_str(original))
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/editor/widgets/recover.py", line 54, in file_data_to_str
    res += '<br><i>{}</i>: {}'.format(_('Last modified'), mtime_as_str)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 5: ordinal not in range(128)

What can I do ?
Thank you.

**Comment by aconceicao** [comment] 2020-03-19 11:11
I also have a problem when updating to Spyder 4.1.0

> Traceback (most recent call last):
File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site‑packages\jupyter_client\manager.py", line 267, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, env=env, **kw)
File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site‑packages\jupyter_client\manager.py", line 211, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\site‑packages\jupyter_client\launcher.py", line 135, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "C:\Users\concea\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

> 

Can anyone help me with that?

**Comment by goanpeca** [comment] 2020-03-19 15:46
@aconceicao that is a different problem and has been fixed with 4.1.1. please update

**Comment by ccordoba12** [comment] 2020-03-19 19:40
@pgr123, please post the contents of any files placed in

     ~/.config/spyder/autosave/

Thanks!

**Comment by yurigba** [comment] 2020-03-19 21:52
The output here is a bit different, but I think the issue is of the same nature.

When I run Spyder, I get:

```
Traceback (most recent call last):
  File "/home/yuri/anaconda3/envs/tf-gpu/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/yuri/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/yuri/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3700, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/yuri/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3556, in run_spyder
    main.setup()
  File "/home/yuri/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1217, in setup
    self.apply_shortcuts()
  File "/home/yuri/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3207, in apply_shortcuts
    self.help.show_intro_message()
  File "/home/yuri/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/spyder/plugins/help/plugin.py", line 456, in show_intro_message
    shortcut_editor, "\n\n", prefs)
TypeError: not enough arguments for format string
```

The folder `~/.config/spyder-py3/autosave/` is empty. The folder `~/.config/spyder/autosave/` doesn't even exists. Spyder was installed using `conda` in the `conda-forge` repo.

**Comment by ccordoba12** [comment] 2020-03-19 22:52
@yurigba, your problem has nothing to do with this. Please don't step into other people's issues because that adds a lot of noise and confusion. So I'm going to hide your comment and ask you to open a new one instead.

**Comment by jitseniesen** [comment] 2020-03-20 11:19
Without looking at the code, my guess is an internationalization issue. Either the string 'Last modified' or the modification time converted to a string contains a non-ASCII character in the setup of the user.

@pgr123 What is your language setting in Spyder? In your OS? Switching to Python 3 might well solve the problem.

**Comment by ccordoba12** [comment] 2020-03-26 16:11
Closing due to lack of response.

**Closed by ccordoba12** 2020-03-26 16:11 UTC
Labels: status:Awaiting Followup
