### ISSUE TITLE
A Python background process stays opened after closing Spyder in master

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7796] opened 2018-08-31 15:39 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After opening Spyder in master with the `bootstrap.py` or from the Anaconda navigator and closing it, a Python  process remains opened in Windows. Introspection becomes broken by this until I close these background processes and restart Spyder. So this is probably related with the problems I reported in Issue #7726.

Note that this is not occurring with the 3.x branch.

![image](https://user-images.githubusercontent.com/10170372/44921920-e56d6080-ad11-11e8-8aec-6f45053ad312.png)

### What steps reproduce the problem?

1. Open Spyder
2. Close Spyder

### What is the expected output? What do you see instead?

All Python processes started by Spyder should be closed

## Versions

* Spyder version: Spyder 4.0.0.dev0 https://github.com/spyder-ide/spyder/commit/3465e77f077a346b71dfdf85d5f7eea98e64162b
* Python version: Python 3.6.5 64bits
* Qt version: Qt 5.9.3
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.11.0     :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.13.0 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.2.0 (OK)
pylint >=0.25     :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2018-08-31 17:09
This is probably related to the fact that the old code completion architecture has not been removed yet. It's in our TODO list: #7724.

**Comment by jnsebgosselin** [comment] 2018-09-12 19:30
I just want to confirm that without killing these background processes in Windows, introspection stop working.

I wish I could help more, but I do not understand enough what is going on.

**Comment by jnsebgosselin** [comment] 2018-10-01 18:42
@ccordoba12 Note that, this does not occur when running in debug mode.

I'm under the impression that the LSP client do not have time to close correctly when Spyder is not run in debug mode.

![image](https://user-images.githubusercontent.com/10170372/46308610-1b5b6a00-c588-11e8-8d01-d49ed0d418ac.png)

**Comment by jnsebgosselin** [comment] 2018-10-11 19:05
@ccordoba12 This is still occurring even after the removal of the old architecture. But when running in debug, it is not. Sometimes, the LSP Client takes a long time to close. Like 15-20 sec.

**Comment by jnsebgosselin** [comment] 2018-10-15 15:48
@ccordoba12 This problem is not happening if I run Spyder from my Anaconda env with `pyls==0.19`.

**Comment by jnsebgosselin** [comment] 2018-10-16 12:51
> Ok, so the problem is with the latest pyls. Thanks for confirming it.

With the latest pyls (>0.19), introspection simply doesn't work at all or make Spyder crash, whether in pip or Anaconda..

The problem I've reported here happens on Windows with pyls==0.19, but I think this is an issue that is specific to my pip install. The problem doesn't occur with Anaconda also using pyls==0.19.

**Comment by CAM-Gerlach** [comment] 2018-10-28 05:30
> The problem I've reported here happens on Windows with pyls==0.19, but I think this is an issue that is specific to my pip install. The problem doesn't occur with Anaconda also using pyls==0.19.

As part of #8153 I believe I likely reproduced the same problem, since I was upgrading and downgrading with ``pip``, got errors related to ``pyls.exe`` being in use, and with all other variables (other than background processes, which I speculated were the cause but wasn't able to isolate a specific one since I had so many Spyders and Pythons open at the time) being equal it would not work after some of the installs downgrades, but when I came back and tried a day later it did. It occurred on 0.19 and 0.20, the two versions I tested.

**Comment by ccordoba12** [comment] 2018-12-10 23:32
@dalthviz, are you able to reproduce this with PyLS 0.19?

**Comment by CAM-Gerlach** [comment] 2018-12-10 23:33
I have been able to, although it doesn't always make completion stop working at least in my limited testing.

**Comment by ccordoba12** [comment] 2018-12-10 23:34
Ok, thanks! I'm moving this to beta3 because I think we need to address this in PyLS itself.

**Comment by stonebig** [comment] 2019-01-29 18:59
today, I don't see this, using PyLS-0.22.0 and spyder master of 2 days ago.

**Comment by CAM-Gerlach** [comment] 2019-01-29 19:06
I haven't really seen this either recently that I recall over the past few weeks with 0.21.

**Comment by ccordoba12** [comment] 2019-01-29 19:12
Ok, that's good to know. @jnsebgosselin?

**Comment by jnsebgosselin** [comment] 2019-01-29 19:17
> Ok, that's good to know. @jnsebgosselin?

This has stopped to be a problem for me the day I started to use conda instead of pip to setup my Python environments. So, for me, it is not a problem anymore, but I don't know exactly what fixed what.

**Comment by ccordoba12** [comment] 2019-01-29 19:34
Ok, thanks for the confirmation. Let's close this one for the time being.

**Comment by CAM-Gerlach** [comment] 2019-01-29 19:35
For the record, I've used ``pip`` inside a ``conda`` environment for installing and updating PyLS throughout.

**Closed by ccordoba12** 2019-01-29 19:34 UTC
Labels: component:Code Completion, type:Bug

**Comment by pbower** [comment] 2019-10-23 23:53
All - this still happens. I am using Spyder 4 and after closing had 6 python.exe processes open (that appeared to have each accumulated after separate Spyder instances).

**Comment by CAM-Gerlach** [comment] 2019-10-24 00:41
@pbower Which Spyder 4 beta or dev version are you using? What is your OS and PyLS versions and how did you install them (pip, conda-forge, `spyder-ide` channel, etc))?

As of Beta 6 (and consistently in previous betas since this issue was first reported), I indeed have had 3 processes stick around indefinitely each time after Spyder crashes, but I haven't noticed it happen if Spyder exits cleanly. The three are Spyder's LSP transport (I assume the client), the PyLS server, and the Jedi subprocess of the server, and depending on use occupy anywhere from 100 MB to well over half a GB of RAM per triplet.

I cannot be 100% sure this occurs on the latest Beta 7 as I'm not sure if it has crashed yet, but next time Spyder crashes I will check. From what I can tell, it looks like the Beta 6 processes are running under the window-mode ``pythonw`` while the Beta 7 processes appear to be running under the standard command-line ``python``. I'm running PyLS 0.28.3 with all deps from `spyder-ide`, no pip installs like before.

**Comment by pbower** [comment] 2019-10-24 03:08
Hi there,
Thanks for looking into this issue.
I am using 4.0.0.b5
Installed via conda
OS is windows 10 and python is 3.7.3
It did appear to be crash related - as screens completely locked up and froze until I closed via the task manager. This is when I noticed it.
If you require any more info please let me know.
Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pbower** [comment] 2019-10-24 04:12
Also I should add even normally python runs Spyder runs with 6 python.exe processes? Is there a reason for this? No ones put a bitcoin miner in there that persists after shutdown have they 😂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pbower** [comment] 2019-10-24 10:14
Oh ok great thanks. So it’s just that on crash something isn’t quitting.
Thanks for that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ccordoba12** [comment] 2019-10-24 21:45
> I indeed have had 3 processes stick around indefinitely each time after Spyder crashes

For the record, this is being worked on in PR #10111.
