### ISSUE TITLE
Spyder frequently terminates without error dialog

### ISSUE THREAD

**Issue by pilotjoe** [spyder-ide/spyder#11324] opened 2020-01-15 18:37 UTC
## Description

I’m using Spyder V4.0.1 in Anaconda 2019.03 on Windows 10.  Frequently Spyder seems to disappear with no on-screen message so that I can send an error report.  Often when I leave Spyder running and the screen locks, or I have another application in the foreground, Spyder will just go away with no error dialog.  Sometimes Spyder will close while I’m using it, but more often it’s when I’ve neglected it in the background for some period of time.  I’ve read the troubleshooting guide, but didn’t see a way to log what happens when Spyder stops.  This issue has persisted through multiple versions of Spyder (always updated using conda).  Any ideas I can use to help get more detailed diagnostic information?

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.8 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-15 20:18
Please start Spyder in a terminal with the following command:

    spyder --debug-info verbose

and check what error messages appear there when it terminates without reason.

**Comment by ccordoba12** [comment] 2020-01-15 20:19
This could be caused by your firewall/antivirus, so please disable or uninstall them and try again.

**Comment by pilotjoe** [comment] 2020-01-17 14:02
Amazingly, I started Spyder from a terminal as you suggested right after your email came in, and Spyder hasn't crashed once in well over 24 hours, where launched normally it tends to crash at least once an hour.  Maybe something about launching from a terminal or in debug mode

**Comment by impact27** [comment] 2020-01-17 14:04
This looks like a segmentation fault in my opinion. It looks like #10553 could help.

**Comment by ccordoba12** [comment] 2020-01-17 14:25
I agree. My plan is to add support for sending crash tracebacks in 4.1, but using a command line option to activate that functionality.

**Comment by pilotjoe** [comment] 2020-01-17 14:34
I've never seen the message or dialog as discussed in #10553 - Spyder just comes up normally when I start it again.

**Comment by ccordoba12** [comment] 2020-01-17 14:44
That'ss because it hasn't been merged.

**Comment by pilotjoe** [comment] 2020-01-17 14:50
Understood.  Perhaps I should just always launch Spyder from the terminal as described until V4.1 is released?  If there's any other way I can get diagnostic information for you running Spyder directly (double clicking the icon), I'd be happy to.

**Comment by ccordoba12** [comment] 2020-01-17 16:19
>  If there's any other way I can get diagnostic information for you running Spyder directly (double clicking the icon), I'd be happy to.

No, there isn't.

**Comment by pilotjoe** [comment] 2020-01-17 22:24
I guess I spoke too soon - Spyder disappeared several times today, particularly when I moved between different WiFi networks (I'm not sure that had anything to do with it).  The terminal log didn't show anything unusual, just an "Autosave triggered" message that it shows every so often.

**Comment by ccordoba12** [comment] 2020-01-29 22:03
Closing as a duplicate of #10536

**Closed by ccordoba12** 2020-01-29 22:03 UTC
Labels: status:Awaiting Followup
