### ISSUE TITLE
spyder cannot use

### ISSUE THREAD

**Issue by jpy12138** [spyder-ide/spyder#6507] opened 2018-02-24 08:52 UTC
File "D:\MyDownloads\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "D:\MyDownloads\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "D:\MyDownloads\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "D:\MyDownloads\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "D:\MyDownloads\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "D:\MyDownloads\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "D:\MyDownloads\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "D:\MyDownloads\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "D:\MyDownloads\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\MyDownloads\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by ccordoba12** [comment] 2018-02-24 13:25
This is a duplicate of issue #4958 and it'll be fixed in our 3.2.7 version, to be released in a couple of days.

In the meantime, please go to

    Preferences > Python interpreter

and select the `Default` option there.

**Closed by ccordoba12** 2018-02-24 13:25 UTC
