### ISSUE TITLE
Windows layout is not saved in version 4.2.4

### ISSUE THREAD

**Issue by mvillion** [spyder-ide/spyder#15003] opened 2021-03-24 08:42 UTC
## Problem Description
It seems that move from 4.2.3 to 4.2.4 has broken saving of windows layout.
I like to display the "outline" pane by default.
When I open 4.2.4, it always start with the default layout.

### What steps reproduce the problem?

1. Install version 4.2.4, select view->panes->outline
2. quit spyder
3. restart spyder

### What is the expected output? What do you see instead?
outline pane is not visible.
In 4.2.3, outline is visible when restarting.

### Paste Traceback/Error Below (if applicable)
n/a

## Versions
* Spyder version: 4.2.3 None
* Python version: 3.8.7 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 4.4.0-203-generic
* 
### Dependencies

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  49.2.1 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  22.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

**Comment by alexbovet** [comment] 2021-03-24 09:26
Same problem here.

Also, if I move panes around and save my current layout, it is not available after a restart.

Python 3.6.10 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Linux 5.10.24-1-lts

**Comment by mvillion** [comment] 2021-03-24 11:08
Same issue after move from 5.0.0a5 to 5.0.0.a6.

**Comment by ccordoba12** [comment] 2021-03-24 19:34
Thanks for reporting. This is a duplicate of issue #14962 and it'll be fixed in our 4.2.5 version, to be released shortly.

**Closed by ccordoba12** 2021-03-24 19:34 UTC
