### ISSUE TITLE
Spyder 5.0.0 incorrectly reports missing dependencies?

### ISSUE THREAD

**Issue by janvanmastbergen** [spyder-ide/spyder#15258] opened 2021-04-12 14:06 UTC
### What steps will reproduce the problem?

Immediately after upgrading Spyder under Conda to 5.0.0 it reports a missing dependency warning for 'spyder_kernels' while the offending module actually is at the required minimum version of 2.0.1.

**Comment by Hamberfim** [comment] 2021-04-12 15:15
I have the same issue even though spyder_kernels 2.0.1 is installed.
Reproducible upon every launch of Spyder 5.

i.e.,
# Mandatory:
spyder_kernels  >=2.0.1, <2.1.0 : 2.0.1 (NOK)

![image](https://user-images.githubusercontent.com/33159808/114416683-8bde9b00-9b76-11eb-8024-ce4e14ba9bd2.png

**Comment by stonebig** [comment] 2021-04-12 15:27
duplicate of https://github.com/spyder-ide/spyder/issues/15091
fixed in Spyder-5.0.1 coming very soon

**Comment by steff456** [comment] 2021-04-12 18:25
Hi @janvanmastbergen and @Hamberfim,

As @stonebig already mentioned, this is a duplicate of #15091 and we are working on releasing Spyder 5.0.1 very soon with the fix. 

Thanks for reporting!

**Closed by steff456** 2021-04-12 18:25 UTC
