### ISSUE TITLE
execution aborted

### ISSUE THREAD

**Issue by sebastianvbvb** [spyder-ide/spyder#14910] opened 2021-03-11 02:35 UTC
### What steps will reproduce the problem?

The console does not work. When I run I get "ERROR: execution aborted". I have update,remove, install spyder and unpdate anaconda and the problems still happens. I have read that it can be for the plot. I do not know exactly but I need your help asap

### Traceback
```python-traceback
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'd4a5cd4e821111eb8f89f0038c0774ba'
ERROR:traitlets:Exception in comm_msg for d4a5cd4e821111eb8f89f0038c0774ba
Traceback (most recent call last):
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'd4a5cd4e821111eb8f89f0038c0774ba'
ERROR:traitlets:Exception in comm_msg for d4a5cd4e821111eb8f89f0038c0774ba
Traceback (most recent call last):
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'd4a5cd4e821111eb8f89f0038c0774ba'
ERROR:traitlets:Exception in comm_msg for d4a5cd4e821111eb8f89f0038c0774ba
Traceback (most recent call last):
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\ADMIN\dacon\envs\prueba\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'd4a5cd4e821111eb8f89f0038c0774ba'
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by dalthviz** [comment] 2021-03-11 16:33
Hi @sebastianvbvb sorry to hear that, is this happening for you running any kind of code? Seems like an issue with a similar traceback was submitted recently (in that case when using the debugger) #14886. Could you provide us a code snippet and the steps you followed to trigger this error?

Pinging @ccordoba12 and @impact27 just in case

**Comment by ccordoba12** [comment] 2021-03-13 17:25
Thanks @dalthviz for the ping. Let's close this one as a duplicate of issue #14886.

@sebastianvbvb, if you have a way to reproduce this problem, please post it on that issue.

**Closed by ccordoba12** 2021-03-13 17:25 UTC
Labels: status:Awaiting Followup, type:Bug
