### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#16315] opened 2021-08-31 03:39 UTC
## Problem Description
The bugs encountered by chance do not appear every time and cannot be reproduced

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in update_and_merge_folding
    folding_panel.root)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\spyder\plugins\editor\panels\utils.py", line 162, in merge_folding
    changed_entry_i.clone_node(deleted_entry_i)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\spyder\plugins\editor\panels\utils.py", line 76, in clone_node
    self.parent.replace_node(self.index, self)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\spyder\plugins\editor\panels\utils.py", line 79, in replace_node
    self.children[index] = node
IndexError: list assignment index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1951, in update_and_merge_folding
    self.log_lsp_handle_errors("Error when processing folding")
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1141, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)

```

## Versions

* Spyder version: 4.2.5
* Python version: 3.7.9
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.26.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.1 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.2.1 (OK)

# Optional:
cython >=0.21                   :  0.29.24 (OK)
matplotlib >=2.0.0              :  3.4.2 (OK)
numpy >=1.7                     :  1.21.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)

```

**Comment by steff456** [comment] 2021-09-01 05:51
Hi @leavor,

For now I'm going to close this issue because there's no way we can reproduce it. If you find any way to reproduce this issue please reopen it and give us the steps.

Thanks for reporting!

**Closed by steff456** 2021-09-01 05:51 UTC
