### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by nadianaji** [spyder-ide/spyder#8591] opened 2019-01-17 21:17 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by nadianaji** [comment] 2019-01-17 21:23
Hi,
I needed to install theano anf for installing it I follow the below stages and after that when I want to implement my codes in spyder it produces this error An error occurred while starting the kernel
 conda update conda
 conda update --all
 conda install mingw libpython
pip install git+git://github.com/Theano/Theano.git
 pip install git+git://github.com/fchollet/keras.git

now I have Python 3.6.8 and IPython 7.2.0 on windows 10. my spyder version is 3.3.2 and it only produces this error "An error occurred while starting the kernel: b'' " without any explanations. I change my setting to factory setting or reinstall spyder, delete .ipyton folder but I could not solve my problem. please help me. I am a beginner and I really do not know what should I do now? thanks

**Comment by ccordoba12** [comment] 2019-01-17 22:17
Closing as a duplicate of issue #8581.

**Closed by ccordoba12** 2019-01-17 22:17 UTC
