### ISSUE TITLE
Sometimes automatic complete can't work

### ISSUE THREAD

**Issue by falseform** [spyder-ide/spyder#6552] opened 2018-02-28 13:02 UTC
### What steps will reproduce the problem?

1. when i run
   a1=pd.DataFrame(np.random.rand(5,5))
2. i input
   a1.to_c
   and press tab
   it will automatic complete  
   a1.to_csv
3. but if it will like this
   a2=pd.read_csv('data.csv')
   a2.to_c
   and press  tab it will no-response
   this a1 can't automatic complete

both a1 and a2 are dataframe,but i input a2.  can't automatic complete

is it cannot identify when pd.read_csv?

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:3.2.7
* Python:3.6.4
* Qt:5.6.2
* PyQt:5.6
* Operating System:win 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment] 2018-02-28 20:36
Thanks for reporting. This is a known issue, a duplicate of #5998 , with Spyder's third party completion library, ``jedi``, and the structure of certain packages like ``pandas``, and is thus outside of our control. Therefore, this issue will be closed.

**Closed** 2018-02-28 20:36 UTC
Labels: resolution:Duplicate
