### ISSUE TITLE
black inserting blank lines in multiline strings

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#17989] opened 2022-05-23 18:59 UTC
### What steps will reproduce the problem?

1. Enable formatting with black on save.
2. turn off all the editor save options due to existing issue that causes it to break #1

3. Create a file with a multiline string, save it.

An extra blank line is inserted onto every line of the multistring.

4. Make some minor edit, save again. Blank lines are inserted again.

I'll upload a screen capture in a minute.

## Versions

* Spyder version: 5.3.0 
* Python version: 3.9.12
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment] 2022-05-24 18:54
Hey @rlabbe, thanks for reporting. I can't reproduce this problem on Linux.

@dalthviz, could you check if you can do it on Windows? Please set the exact same options shown by @rlabbe in his screenshot.

**Comment by dalthviz** [comment] 2022-05-25 15:46
I was unable to reproduce this with Spyder 5.3.1 @rlabbe could you update to Spyder 5.3.1 and let us know if you keep experiencing the error? Thanks!

**Comment by rlabbe** [comment] 2022-05-25 16:11
Yes, I updated to 5.3.1, same issue.

[spyder.init.txt](https://github.com/spyder-ide/spyder/files/8772729/spyder.init.txt)

I uploaded all of my settings in case that helps - had to rename with .txt to be able to upload. 

I am going on vacation and won't be able to deal with this for a few weeks. But if you can't duplicate, if you wanted to you could point me to a few places in the spyder source code to look at where this might be happening once I'm back. I'm not terribly familiar with the source and am having trouble finding it myself.

**Comment by dalthviz** [comment] 2022-05-25 16:29
Thanks @rlabbe !

**Comment by dalthviz** [comment] 2022-06-17 19:12
Just in case, checked again this using the provided `spyder.ini` config file but I was unable to reproduce the issue :/

Tested with the Spyder 5.3.1 standalone version on Windows and a conda env with conda-forge packages. I only got a warning regarding an uninstalled font `Fira Code` (`Warning: None of the following fonts is installed: ['Fira Code']`), but the formatting worked (no extra blank lines).

**Comment by ccordoba12** [comment] 2022-06-19 16:55
Ok, I'm going to close this issue because we were unable to reproduce it.

**Closed by ccordoba12** 2022-06-19 16:55 UTC
Labels: status:Awaiting Followup
