### ISSUE TITLE
error when remove variable from variable explorer.

### ISSUE THREAD

**Issue by gzhechu** [spyder-ide/spyder#11165] opened 2019-12-23 10:58 UTC
### What steps will reproduce the problem?

error when remove variable from variable explorer.

### Traceback
```python-traceback
Exception in comms call remove_value:
  File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'x2'
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.9
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-72-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.1 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.1.1 (OK)
cython >=0.21                :  0.26.1 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.0 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.16.0 (OK)
scipy >=0.17.0               :  1.3.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-23 14:23
Duplicate of #11001

**Closed by ccordoba12** 2019-12-23 14:23 UTC

**Comment by ccordoba12** [comment] 2019-12-23 14:27
@gzhechu, I can't reproduce this. Please post a video (animated gif with the Licecap program) to see how this is generated.

**Comment by gzhechu** [comment] 2020-02-01 17:04
sorry, I fogot how it happened, it's been a little time. but I think it might because I was upgrading system (which has some python dependency libraries) in anohter terminal window.
