### ISSUE TITLE
Crash on creating empty Pandas DataFrame

### ISSUE THREAD

**Issue by drsaunders** [spyder-ide/spyder#2822] opened 2015-11-20 14:03 UTC
Only when I use Spyder, not using Python or iPython from the console, these lines of code cause an immediate hang (endless beachball, nothing in the interface responsive):

    import pandas as pd
    a = pd.DataFrame()

The error only occurs when I assign the dataframe to a variable, and I don't include a "columns" or "data" input argument to DataFrame().

I running OS X, 10.9.4 and the latest versions of all the packages updated with condas, e.g.:

    spyder                    2.3.7 
    ipython                   4.0.0
    pandas                    0.17.0

**Comment by ccordoba12** [comment] 2015-11-20 14:05
This is a duplicate of issue #2744

**Comment by ccordoba12** [comment] 2015-11-20 14:05
And it'll be fixed in 2.3.8 :-)

**Closed by ccordoba12** 2015-11-20 14:05 UTC
Labels: duplicate
