### ISSUE TITLE
Documentation incomplete depending on how the module is imported

### ISSUE THREAD

**Issue by JackCaster** [spyder-ide/spyder#8112] opened 2018-10-21 15:06 UTC
## Problem Description
If a submodule is directly imported, Spyder fails to display the full documentation.
For example, if I import the `pyplot` module as 
```python
import matplotlib.pyplot as plt
```
the help panel in the editor does not show the extended documentation for the module, for example `plt.scatter(...)` (in the image below, notice the _No further documentation available_):
![image](https://user-images.githubusercontent.com/18400141/47268453-8da0e800-d551-11e8-9ab4-4e7d8d276f76.png)

If I change my import to 
```python
import matplotlib as mpl
```
then, when I type `mpl.pyplot.scatter(...)` the documentation is complete:
![image](https://user-images.githubusercontent.com/18400141/47268486-fee09b00-d551-11e8-85c2-5c026480f653.png)

The help panel for the IPython console, instead, works properly, independently on how I imported the module. 

### What steps reproduce the problem?

1. `import matplotlib.pyplot as plt`
2. `plt.scatter()` does not show the full docstring.

### What is the expected output? What do you see instead?
The help panel for `plt.scatter()` should display the full docstring.

## Versions

* Spyder version: 3.3.1 (via Conda)
* Python version: 3.6.6
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro 

### Dependencies
```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.0 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment] 2018-10-21 18:11
Thanks for reporting. We'll take a look at this in a future release.

**Comment by Khalilsqu** [comment] 2018-10-29 23:39
It does not show anything using either methods for me, **No documentation available**

`import matplotlib.pyplot as plt`
or 
`import matplotlib as mpl`

`import numpy as np` works

windows 10, 
spyder 4 beta 1
python 3.6 from miniconda

**Comment by bcolsen** [comment] 2019-04-08 15:22
Duplicate of #5522

**Closed by bcolsen** 2019-04-08 15:22 UTC
Labels: component:Help, type:Bug
