### ISSUE TITLE
Missing color scheme option for highlight-functionality in search

### ISSUE THREAD

**Issue by PJussel** [spyder-ide/spyder#10679] opened 2019-11-12 10:36 UTC
## Problem Description

Missing color scheme option for highlight-functionality in search

### What steps reproduce the problem?

1. Search for a string
2. Activate hightlight (see screenshot)
3. Try to find a possibility to change this specific colour in preferences, fail... ;-)

![highlight](https://user-images.githubusercontent.com/12828726/68664416-ab683300-0540-11ea-881d-d27ee5db6290.jpg)

## Versions

* Spyder version: 4.0.0rc1
* Python 3.7.4 64-bit
* Qt 5.9.6
* PyQt5 5.9.2
* Windows 10

**Comment by goanpeca** [comment] 2019-11-12 14:12
Duplicate of https://github.com/spyder-ide/spyder/issues/10429

**Closed by goanpeca** 2019-11-12 14:12 UTC
