### ISSUE TITLE
Error outputs in the console cause the kernel to restart

### ISSUE THREAD

**Issue by lawpdas** [spyder-ide/spyder#6198] opened 2018-01-12 10:29 UTC
Why the new version doesn't output information in the system terminal?
I need to use caffe, a deep learning framework, in spyder. The version 3.0.0 can output caffe's log in the system terminal, so I can check the error information. 
How to make the new version output information in the terminal?

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 2.7
* Qt Version: 5.6.2
* PyQt Version: 1.3.1
* Operating system: ubuntu16.04

## Dependencies
```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
psutil >=0.3      :  5.4.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-01-12 17:34
> How to make the new version output information in the terminal?

Please run in a terminal

    pip install wurlitzer

restart Spyder and try again.

**Comment by lawpdas** [comment] 2018-01-13 02:13
It doesn't work! 
But I find the log can be output in the IPython console only when error ocurred.
![](https://raw.githubusercontent.com/lawpdas/page/master/Screenshot%20from%202018-01-13%2010-08-49.png)

**Comment by ccordoba12** [comment] 2018-01-13 15:14
Sorry, after installing that package, you need to run in an IPython console this

    %load_ext wurlitzer

Then it should work.

**Comment by lawpdas** [comment] 2018-01-14 05:28
Yes， it works! But ....
Now, the new version can output log in IPython console after `%load_ext wurlitzer`. 
But when there was an error,  kernel will restart and the log in IPython console will be cleaned  immediately. There is not enough time for me to check the log.
Spyder 3.0.0 can output the log in system terminal, and the log can be retained in system terminal.
What should I do?
Thanks very much!

**Comment by ccordoba12** [comment] 2018-01-17 14:43
We'll take a look at this in a future release.

**Comment by ccordoba12** [comment] 2018-05-22 17:37
Closing as a duplicate of issue #3777.

**Closed by ccordoba12** 2018-05-22 17:37 UTC
Labels: component:IPython Console, type:Bug
