### ISSUE TITLE
spyder  ValueError: Invalid Signature:  

### ISSUE THREAD

**Issue by Andyyowei** [spyder-ide/spyder#7006] opened 2018-04-22 18:43 UTC
## Description

**What steps will reproduce the problem?**

1. I open spyder and error is produced
2.
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

ValueError: Invalid Signature: b'4eb60105a40ae5efed4462fcda95240d465fb552a040592f88e612f7fc314337'
ValueError: Invalid Signature: b'4eb60105a40ae5efed4462fcda95240d465fb552a040592f88e612f7fc314337'
ValueError: Invalid Signature: b'9231b9cc51a19211b13179fcec6bfbce467be9db144f7aff7c702d4b8fefff2c'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-04-23 04:48
Thanks for reporting. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. In particular, make sure you update spyder, and if that doesn't do it, reinstall Anaconda.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by Andyyowei** [comment] 2018-04-23 13:34
Hi I have tried the  Spyder Troubleshooting Guide 
and i also uninstall anaconda  then reinstall many times
when I start spyder it will display connecting to kernel 
and then I restart the kernel the error produced as below

ValueError: Invalid Signature: b'efb4db041b933cb3c96671930dcc7e360ee59376f61ccfe602bf615f75fd6477'
ValueError: Invalid Signature: b'efb4db041b933cb3c96671930dcc7e360ee59376f61ccfe602bf615f75fd6477'
ValueError: Invalid Signature: b'efb4db041b933cb3c96671930dcc7e360ee59376f61ccfe602bf615f75fd6477'

**Comment by ccordoba12** [comment] 2018-04-23 13:57
This looks like a duplicate of issue #6335. Please update Python to 3.6.5 and try again.

**Comment by CAM-Gerlach** [comment] 2018-04-24 04:27
Thanks, that's exactly what we needed.

> ERROR:tornado.general:Uncaught exception in ZMQStream callback

> The following is jupyter qtconsole

This tells us two things: The problem has nothing to do with Spyder (as it also occurs in ``qtconsole``), and specifically that its a duplicate of #6627 . Therefore, running the above ``conda update`` command I requested previously will almost certainly fix it.

**Closed by CAM-Gerlach** 2018-04-24 04:27 UTC
Labels: status:Awaiting Followup

**Comment by Andyyowei** [comment] 2018-04-24 04:45
I start spyder and it appears
ValueError: Invalid Signature: b'b116539a06f524f33676a8bdd22ee50d7e2bd08209effb68392d880e50fb19e6'
ValueError: Invalid Signature: b'f950e7d1407089f28178cd51e0e5e65cf698f349d3845c942c8980acf49bf07a'

actually, before I post those two comments I had tried conda update spyder ipython .....
but some of them appeared safety ERROR: ...... is corupted and ........ sha 256 ....   like that

and then I tried again the following is 
(base) C:\Users\MC_Server>conda update ipykernel
Solving environment: done
# All requested packages already installed.

(base) C:\Users\MC_Server>conda update tornado
Solving environment: done
# All requested packages already installed.

(base) C:\Users\MC_Server>conda update pyzmq
Solving environment: done
# All requested packages already installed.

**Comment by CAM-Gerlach** [comment] 2018-04-24 05:04
Protip: Put triple backticks `` ``` `` above and below code or output blocks on github; otherwise, the formatting and spacing will be crazy. I did it for you on your post above.

> but some of them appeared safety ERROR: ...... is corupted and ........ sha 256 .... like that

What do you mean by this? Sorry, but I don't understand at all what you're trying to say here.

> and then I tried again the following is
>> # All requested packages already installed.

That means they're already up to date.

> ValueError: Invalid Signature: 

Now if you start ``jupyter qtconsole``, does an error still appear? If not, can you run Spyder in debug mode as you did previously and post the output? It still seems as if something is messed up with your install, or its something else specific to your local machine.

**Comment by Andyyowei** [comment] 2018-04-24 08:52
I mean first time I run conda update spyder ipython .......
some of update appeared the message something like below
SafetyError: The package for ______ located at ~/anaconda3/pkgs/_____ appears to be corrupted. The path '~/____' has a sha256 mismatch. reported sha256: e3df799e317d2796d064e1b384e0acfeee81f03399465ad87a78c91e39ea9c32 actual sha256: 

And second time I do the same thing as first time 
all of them appear:
Solving environment: done
# All requested packages already installed.

Sorry, I am not sure what hydrogen is. 
First time I install anaconda spyder ,they all works. 
After running some code about tensorflow , spyder crashes so I uninstall all of them and reinstall
then occurred the above problums

**Comment by CAM-Gerlach** [comment] 2018-04-24 14:04
Thanks for the followup. Please remember to put `` ```` `` above and below your code/output blocks as I stated previously, or they will be all messed up and very hard to read due to Github's formatting, as you can clearly see looking at your posts. I had to do so again editing your post above so I could follow it.

> some of update appeared the message something like below

Thanks, that's quite helpful. Please try to post error messages in full like that in the future. The message suggests something is indeed corrupted with your install, which has to do with ``conda`` and other Anaconda infrastructure rather than anything related to Spyder, and a quick Google revealed [this relevant issue](https://github.com/conda/conda/issues/6689) on the ``conda`` repo, to which further problems in the vein should be reported it has nothing to do with Spyder and there isn't anything we can do about it. Very likely, this is related to something specific in your environment, like installing a bad package, using ``pip`` in any way, or something weird with your environments; there's also a chance it could be security/antivirus software messing with things (as the Guide suggests).

> First time I install anaconda spyder ,they all works.

Right...

> After running some code about tensorflow , spyder crashes

Well, there you go. That's the most likely source of the problem discussed above; there are many problems with Tensorflow and many users install it with ``pip`` or its whole problem ``conda`` environment, so very likely this is your issue. Again, this has nothing to do with Spyder and there's nothing more we can do to help from our side; this should be reported to the ``conda`` folks or possibly ``Tensorflow`` if you're sure its not a problem on your end (which it seems like to some extent).

Also, I didn't get an answer to my previous question,

> Now if you start jupyter qtconsole, does an error still appear?

But I assume the answer is still yes, which is yet another piece of clear evidence this error is not Spyder-related.

Best of luck!
