### ISSUE TITLE
a=1

### ISSUE THREAD

**Issue by sision0816** [spyder-ide/spyder#4826] opened 2017-07-27 09:13 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\chen_w1\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 895, in set_working_directory
    refresh_console=False)
  File "C:\Users\chen_w1\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\plugins\workingdirectory.py", line 286, in chdir
    os.chdir( to_text_string(directory) )
WindowsError: [Error 3] The system cannot find the path specified: u'J:\\Instron_TMF1-2\\Mean stress-strain effect air and water\\Kraftgeregelt_288\ufffdC\\In water environment\\SK200_17'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython

**Comment by ccordoba12** [comment] 2017-07-27 13:58
Thanks for reporting. This is a duplicate of issue #4816.

**Closed by ccordoba12** 2017-07-27 13:58 UTC
Labels: resolution:Duplicate
