### ISSUE TITLE
An error occurred while starting the kernel

### ISSUE THREAD

**Issue by imrankhan441** [spyder-ide/spyder#11858] opened 2020-03-19 03:16 UTC
![problem](https://user-images.githubusercontent.com/26671669/77028102-2bf0e180-69c2-11ea-832a-c9f068169c6a.png)

**I face this problem in spyder version 4.1.0 but it's totally ok in version 4.0.1 [fix please]**

**Comment by goanpeca** [comment] 2020-03-19 03:38
Duplicate of #11854 11819

**Closed by goanpeca** 2020-03-19 03:38 UTC
