### ISSUE TITLE
No IPython console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1744] opened 2015-02-17 20:31 UTC
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2014-02-27T14:38:27Z_

IPython >=0.13  :  1.2.1 (OK)
matplotlib >=1.0:  1.4.x (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.5.0:  0.7.3 (OK)
pylint >=0.25   :  0.26.0 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  1.1.3 (OK) 

What steps will reproduce the problem?

1. Open Spyder
2. Go to "consoles" menu 3. What is the expected output? What do you see instead? To have an option for starting an ipython console or have it even started at beginning.
3. No Ipython comes up.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1744_

**Comment by nanders83** [comment] 2015-03-24 11:36
is this fixed yet? I experience the same problem with spyder 2.3.4, ipython 3.0, python 2.7.9 on windows 7 x64. worked before on spyder 2.2.x and ipython < 0.12

**Comment by ccordoba12** [comment] 2015-03-24 16:57
This can be caused by a number of reasons. We're working to improve the situation in our next release.

**Comment by ccordoba12** [comment] 2015-07-13 04:57
Closing as duplicate of issue #1860

**Closed by ccordoba12** 2015-07-13 04:57 UTC
Labels: 1 star, bug, duplicate, IPython-Console
