### ISSUE TITLE
Spyder 5.1.1: Tab file name truncated

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#16189] opened 2021-08-10 07:46 UTC
In macOS Spyder 5.1.1, when I open many tabs in the Editor, the file names shown in the tabs are cut off from both the left and the right.

I can't show a screenshot, but here is a diagram to show what I mean:

![image](https://user-images.githubusercontent.com/25124332/128828444-ee4d67da-7f39-4671-8842-9e79c9928efc.png)

This only happens on macOS, and happens when I use three panes (the "MATLAB layout" in Spyder 4) and the Editor pane is the middle pane.

On Windows Spyder 5.1.1, I don't see this issue.

**Comment by ccordoba12** [comment] 2021-08-11 02:53
Hey @jsh9, thanks for reporting. Probably this has to do with the way Qt handles eliding in Mac.

@steff456, are you able to reproduce this problem?

**Comment by steff456** [comment] 2021-08-11 18:21
Yes, I'm able to reproduce this issue

This is how it looks like right now:
![image](https://user-images.githubusercontent.com/20992645/129082495-e24f5b45-f949-4673-a70e-5f5de68d76b3.png)

**Comment by ccordoba12** [comment] 2022-08-15 16:06
This is a duplicate of issue #18817 and it'll be fixed in our next version (5.3.3), to be released in a couple of weeks.

**Closed by ccordoba12** 2022-08-15 16:06 UTC
Labels: type:Bug, OS:MacOS, tag:Ui
