### ISSUE TITLE
Interface freezes when closing IPython console tab

### ISSUE THREAD

**Issue by homocomputeris** [spyder-ide/spyder#4669] opened 2017-06-28 12:13 UTC
## Description

**What steps will reproduce the problem?**

1. Open an IPython console
2. Compute something in the console
3. Close the console's tab

**What is the expected output? What do you see instead?**
Expected: close the tab
Got: the interface freezes for some seconds after pressing the 'x' button. The console is eventually closed.

**Please provide any additional information below**
If there has been no computation, the interface freezes for less time

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.9.0, PyQt5 5.8.2 on Linux

## Dependencies
```
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.1 (OK)
pycodestyle >=0.6:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by ccordoba12** [comment] 2017-06-28 14:35
It looks like an issue with PyQt5. What happens if you use Qt **5.8** with PyQt **5.8**?

**Comment by homocomputeris** [comment] 2017-06-28 17:08
Well, maybe a PyQt bug.
Having downgraded, I got

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/lib/python3.6/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

In any case, I believe one can expect a good 5.9 support, eventually, because

> We are pleased to announce that Qt 5.9 will be a Long Term Supported (LTS) release.

**Comment by samotracio** [comment] 2017-06-29 15:36
Similar issue here. Closing an ipython console in Spyder takes around 8s. Does not matter if the console was pristine or had done some computations. Closing Spyder (from the X button) also takes several seconds. 

- Spyder Version: 3.1.4
- Python Version: 3.6.1
- Qt Versions: 5.6.2, PyQt5 5.6 on Linux 64-bit (Tumbleweed)
- Fresh Anaconda 4.4.0 install

**Comment by ccordoba12** [comment] 2017-06-29 15:42
Really weird. Unfortunately, we're not able to reproduce this one, sorry.

**Comment by homocomputeris** [comment] 2017-06-29 15:50
@ccordoba12 Thanks!
It's very probable that this might depend on the toolkit combination.

@samotracio At least I'm no the only one. 😄 

Looking forward for a better behaviour when the all the components and toolkits are based on Qt 5.9 LTS.

**Comment by samotracio** [comment] 2017-06-29 15:59
Thanks @ccordoba12 . I am about to boot in a newer Tumbleweed and try again. I shall let you know.
I suspect a Qt issue or a qdbus issue (what?). Yes, latest Anaconda broke my qtpaths and had to patch the startkde file to bring the X system back. See at the end of [here](https://forums.opensuse.org/showthread.php/520628-Could-not-start-D-bus-Can-you-call-qdbus-qt5/page2)

**Comment by samotracio** [comment] 2017-06-29 19:05
Nope. Same behavior under Tumbleweed 20170420 (KDE 5.94 and system-wide Qt 5.9).
@homocomputeris what is your graphics backend? When I set the graphics backend to Inline, then the sluggishness goes away. Any other choice, e.g. Qt5, Qt4, Tkinter, makes it comes back.

**Comment by homocomputeris** [comment] 2017-06-30 06:49
@samotracio I see no difference between inline and automatic.

**Comment by ccordoba12** [comment] 2017-07-26 02:42
This is a duplicate of issue #4051.

**Closed by ccordoba12** 2017-07-26 02:42 UTC
Labels: component:IPython Console, Package:PyQt, resolution:Duplicate, type:Bug
