### ISSUE TITLE
Segmentation fault crash

### ISSUE THREAD

**Issue by SadhviV** [spyder-ide/spyder#14111] opened 2020-10-31 22:22 UTC
### What steps will reproduce the problem?

Open Anaconda
Open Spyder, click on new file
Try saving the new file and this error will pop up.

### Traceback
```python-traceback
Windows fatal exception: access violation

Thread 0x00001430 (most recent call first):
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 306 in wait
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 558 in wait
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\jupyter_client\channels.py", line 161 in run
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 890 in _bootstrap

Thread 0x00005444 (most recent call first):
  File "C:\Users\SUDEEP\anaconda3\lib\selectors.py", line 314 in _select
  File "C:\Users\SUDEEP\anaconda3\lib\selectors.py", line 323 in select
  File "C:\Users\SUDEEP\anaconda3\lib\asyncio\base_events.py", line 1823 in _run_once
  File "C:\Users\SUDEEP\anaconda3\lib\asyncio\base_events.py", line 570 in run_forever
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 149 in start
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 187 in run
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 890 in _bootstrap

Thread 0x0000139c (most recent call first):
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 302 in wait
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 558 in wait
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\IPython\core\history.py", line 829 in run
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\IPython\core\history.py", line 58 in needs_sqlite
  File "<decorator-gen-25>", line 2 in run
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 890 in _bootstrap

Thread 0x00005768 (most recent call first):
  File "C:\Users\SUDEEP\anaconda3\lib\socket.py", line 292 in accept
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3307 in start_open_files_server
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 870 in run
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 932 in _bootstrap_inner
  File "C:\Users\SUDEEP\anaconda3\lib\threading.py", line 890 in _bootstrap

Thread 0x0000573c (most recent call first):
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\qtpy\compat.py", line 129 in _qfiledialog_wrapper
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\qtpy\compat.py", line 193 in getsavefilename
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2094 in select_savename
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2134 in save_as
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2131 in save_as
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3679 in run_spyder
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3761 in main
  File "C:\Users\SUDEEP\anaconda3\lib\site-packages\spyder\app\start.py", line 205 in main
  File "C:\Users\SUDEEP\anaconda3\Scripts\spyder-script.py", line 10 in <module>
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-11-01 00:48
Closing as a duplicate of issue #14066. I'll continue the discussion there.

**Closed by ccordoba12** 2020-11-01 00:48 UTC
