### ISSUE TITLE
Spyder project creation fails

### ISSUE THREAD

**Issue by exodiuss** [spyder-ide/spyder#5773] opened 2017-11-16 10:20 UTC
## Description

**What steps will reproduce the problem?**

1. I had a perfectly working project on my C:/
2. Then I switched all files to my firm server (UNC path) - only switching data and code folders - not the .spyproject folder
3. I tried to create a new project on this fresh folder and I get this message

Note : [BLURREDPATH] in the path is just because I'm blurring the firm's name.

**Please provide any additional information below**

  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '//fichiers/Projets/[BLURREDPATH]/01_App\\.spyproject\\workspace.ini'

Traceback (most recent call last):
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\projects.py", line 234, in _create_project
    self.open_project(path=path)
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\projects.py", line 261, in open_project
    self.set_project_filenames(self.editor.get_open_filenames())
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\projects.py", line 325, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\projects\type\__init__.py", line 74, in set_recent_files
    list(OrderedDict.fromkeys(recent_files)))
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\user.py", line 448, in set
    self._save()
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
    raise(e)
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\user.py", line 120, in _save
    _write_file(fname)
  File "C:\Users\Flaval\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '//fichiers/Projets/[BLURREDPATH]/01_App\\.spyproject\\workspace.ini'

**Comment by ccordoba12** [comment] 2017-11-17 00:43
Thanks for reporting. This is a duplicate of issue #5765.

**Closed by ccordoba12** 2017-11-17 00:43 UTC
