### ISSUE TITLE
Profiling error

### ISSUE THREAD

**Issue by GPoloVera** [spyder-ide/spyder#9743] opened 2019-07-04 10:43 UTC
### What steps will reproduce the problem?

Just in the "Run" section click on Profile give this error

### Traceback
```python-traceback
  File "/home/dsu/anaconda3/envs/pdf_bucket_env_local/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 264, in <lambda>
    self.finished(ec, es))
  File "/home/dsu/anaconda3/envs/pdf_bucket_env_local/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 335, in finished
    self.show_data(justanalyzed=True)
  File "/home/dsu/anaconda3/envs/pdf_bucket_env_local/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 362, in show_data
    self.datatree.show_tree()
  File "/home/dsu/anaconda3/envs/pdf_bucket_env_local/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 526, in show_tree
    rootkey = self.find_root()  # This root contains profiler overhead
  File "/home/dsu/anaconda3/envs/pdf_bucket_env_local/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 507, in find_root
    self.profdata.sort_stats("cumulative")
AttributeError: 'NoneType' object has no attribute 'sort_stats'
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.6.7
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Linux 3.10.0-693.21.1.el7.x86_64

### Dependencies

```
pyflakes >=0.6.0  :  2.1.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.5.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-05 11:15
Thanks for reporting. This is a duplicate of issue #8336.

**Closed by ccordoba12** 2019-07-05 11:15 UTC
