### ISSUE TITLE
Issue when starting spyder

### ISSUE THREAD

**Issue by arnyeinstein** [spyder-ide/spyder#11867] opened 2020-03-19 09:50 UTC
### What steps will reproduce the problem?

Installed spyder 4.1.1 using pip install spyder --upgrade (from 4.1.0). When starting spyder. Tried to reset spyder (problem remained). Uninstalled and reinstalled using pip. Still the same problem

### Traceback
```python-traceback
  File "C:\Users\renge\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 986, in setup
    plugin = mod.PLUGIN_CLASS(self)
TypeError: 'bool' object is not callable
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.4
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.8.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.2.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.13 (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.16.5 (OK)
pandas >=0.13.1                :  0.25.1 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.4 (OK)

# Spyder plugins:
spyder_notebook                :  0.2.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-19 15:38
Duplicate of #11847

**Comment by ccordoba12** [comment] 2020-03-19 15:39
Please uninstall spyder_notebook, try again and post what you find in the issue I referenced above, not here.

**Closed by ccordoba12** 2020-03-19 15:38 UTC

**Comment by arnyeinstein** [comment] 2020-03-22 12:37
removed spyder_notebook, uninstalled spyder and reinstalled: no effect
