### ISSUE TITLE
ok fdine. this is

### ISSUE THREAD

**Issue by momince** [spyder-ide/spyder#18197] opened 2022-06-07 20:15 UTC
### What steps will reproduce the problem?

I don't know. I just want to use it. so please let me use it. thanks

### Traceback
```python-traceback
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f8fabc2b5e0>)
Traceback (most recent call last):
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 661, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/Users/khondokar/opt/anaconda3/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.1.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  8.4.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  23.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by steff456** [comment] 2022-06-07 22:57
Hi @momince !

This is a duplicate of issue https://github.com/spyder-ide/spyder/issues/18174, please use that one to discuss about possible fixes. Please check your version of jupyter client to see if that fixes this error!

Thanks a lot for reporting!

**Closed by steff456** 2022-06-07 22:57 UTC
