### ISSUE TITLE
Project explorer widget crash if project located on UNC path after %clear command

### ISSUE THREAD

**Issue by ihormelnyk** [spyder-ide/spyder#13910] opened 2020-10-02 09:42 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder application crashes after the first script run if the project is located in UNC path and configured to run the script in dedicated console.
It crashes after moving the mouse to the project tree.

Windows fatal exception: access violation
Faulting application name: pythonw.exe, version: 3.8.5150.1013, time stamp: 0x5f15bf72
Faulting module name: Qt5Widgets.dll, version: 5.12.9.0, time stamp: 0x5ee1d6fa
Exception code: 0xc0000005
Fault offset: 0x00000000002055ba
Faulting application path: c:\python38\pythonw.exe
Faulting module path: c:\python38\lib\site-packages\PyQt5\Qt\bin\Qt5Widgets.dll

As I understand, QtTree refreshes and crashes by access violation after %clear command.
Also if you add file to project (which is located in UNC path) via the project widget it will not appear in project tree.

### What steps reproduce the problem?

1. Create a project located in UNC path
2. Add new python file
3. Configure to run script in dedicated console
4. Run script (could be even empty)
5. Move the mouse to project tree
6. App crashes

### What is the expected output? What do you see instead?
No crash

### Paste Traceback/Error Below (if applicable)
Windows fatal exception: access violation
Faulting application name: pythonw.exe, version: 3.8.5150.1013, time stamp: 0x5f15bf72
Faulting module name: Qt5Widgets.dll, version: 5.12.9.0, time stamp: 0x5ee1d6fa
Exception code: 0xc0000005

## Versions
* Spyder version: 4.1.5 None
* Python version: 3.8.5 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)

```

**Comment by juanis2112** [comment] 2020-10-02 20:17
Hi @ihormelnyk. Thanks for reporting this. It seems that this can be related to this issue https://github.com/spyder-ide/spyder/issues/10762 which was solved already in the latest release of ipykernel: 5.2.1. Please run 'conda list ipykernel' to see your ipykernel version and if it is previous to 5.2.1 please run 'conda update ipykernel'.
If this doesn't solve your issue, let us know so we can take a different approach.

**Comment by ihormelnyk** [comment] 2020-10-02 20:23
Hi @juanis2112 ,
I have ipykernel 5.3.4 version.
Looks like my issue is not related to console, it is related to project explorer widget refresh.

**Comment by ihormelnyk** [comment] 2020-10-04 19:44
Hi @juanis2112 , @ccordoba12 
Here is GIF file attached for Spyder crash demonstration. 
In my opinion, this is quite a critical issue, as it is almost impossible to work with projects on a network location
![spyder_crash](https://user-images.githubusercontent.com/276431/95025373-f677c100-0691-11eb-907e-b7a3ce914058.gif)

**Comment by ccordoba12** [comment] 2020-10-04 22:53
@dalthviz, could you try to reproduce this one?

**Comment by ihormelnyk** [comment] 2020-10-06 15:55
Hi @dalthviz ,
I've checked, it can be easily reproduced on another windows machine with fresh python and the latest Spyder.

**Comment by ihormelnyk** [comment] 2020-10-07 17:45
Hi @ccordoba12 ,
Would it be possible to take a look at this problem in the near future because our clients are not able to work with the projects located on the network location?, because Spyder crashes constantly after the first run.

**Comment by ccordoba12** [comment] 2020-10-08 01:01
Hey @ihormelnyk, unfortunately we are pretty busy at the moment, so it could take us a couple of months to solve this, sorry.

So you have two options:

1. Solve the problem yourself (after all, everything in Spyder is pure Python).
2. If this is critical for you or your company, you could consider to hire us through Quansight Labs, as described [here](https://labs.quansight.org/blog/2019/05/community-driven-opensource-funded-development/).

**Comment by amitsureka** [comment] 2021-01-02 10:49
@ccordoba12 happy new year ... Could you please let us know if this issue of project explorer crashing is resolved in 4.2.1 as i am facing this issue on 4.1.5.

**Comment by amitsureka** [comment] 2021-01-02 10:54
@ihormelnyk happy new year to as well... please do let me know if you found any workaround for this issue. Is the issue even with new 4.2.1 release?

**Comment by ihormelnyk** [comment] 2021-01-02 17:55
> @ihormelnyk happy new year to as well... please do let me know if you found any workaround for this issue. Is the issue even with new 4.2.1 release?

Hi @amitsureka , happy New Year to you too, 4.2.1 crashes as well (just run any script from a project or execute %clear command) and there is no workaround.

**Comment by amitsureka** [comment] 2021-01-03 02:55
@ihormelnyk thanks for your reply.

**Comment by amitsureka** [comment] 2021-01-04 10:20
@ccordoba12 @ihormelnyk @juanis2112 i intended to move to pycharm after encountering this bug in spyder and thought spyder was unstable platform.

Pycharm doesn't have this project explorer instability and i used pycharm for first time after using spyder for 2 years now.

Must say both ide have their pros and cons but in many cases spyder wins...it is much more simpler and powerful for not so geeky users which is a big portion of community...

So i applaud you guys for all effort you have put over years :)

I will continue using spyder with version 4.1.5 and wait for 4.2.2 when you guys fix this bug and other bugs :)

**Comment by sk-ys** [comment] 2021-01-05 22:59
Creating symbolic links may be a temporary solution.

**Comment by ccordoba12** [comment] 2021-01-06 23:36
@amitsureka, we'll try to fix this for our 4.2.2 version, to be released in February 15th.

@sk-ys, glad you found a workaround.

**Comment by amitsureka** [comment] 2021-01-07 03:40
> @amitsureka, we'll try to fix this for our 4.2.2 version, to be released in February 15th.
> 
> @sk-ys, glad you found a workaround.
Thanks a lot both

**Comment by juanis2112** [comment] 2021-01-07 23:56
@amitsureka thanks for your patience and for your kind words :) 
@sk-ys thanks for your help

**Comment by amitsureka** [comment] 2021-01-08 05:43
@ihormelnyk thanks all...

I didn't know what symbolic links are..
But i tried mapping my full network drive to a drive letter like Y:/ in my computer and woah ...the project explorer doesn't crash any more...

May be this only was symbolic links...

**Comment by ccordoba12** [comment] 2021-05-30 23:58
No, there aren't in the short term, sorry.

**Comment by ihormelnyk** [comment] 2022-04-14 06:42
Hi @dalthviz , looks like it works with the Windows installer, thanks!

**Comment by ccordoba12** [comment] 2022-04-14 14:38
I'm going to close this issue as fixed then.

**Closed by ccordoba12** 2022-04-14 14:38 UTC
Labels: type:Bug, component:Projects
