### ISSUE TITLE
Spyder 3.0 crash in Win 10 

### ISSUE THREAD

**Issue by wliu2016** [spyder-ide/spyder#3897] opened 2016-12-30 16:47 UTC
## Description of your problem
After installing Anacoda3 in Win 10 with Intel I7 6700 and AMD Radeon(TM) R5 340x, Spyder keeps crashing when I open it. 

**What steps will reproduce the problem?**

1. Just install the program and keeps crashing.
Attachment 1: Spyder 3.0
![spyder](https://cloud.githubusercontent.com/assets/20285043/21568786/65e68b6e-ce85-11e6-8a44-e6d681127937.jpg)
2. NA
3. NA

**What is the expected output? What do you see instead?**

I see the Spyder IDE keeps throwing out errors and finally the program is not responding.  I used the VS 2015 to debug and it gives the following information:

_Unhandled exception at 0x00007FF8AF31E7C0 (Qt5Gui.dll) in pythonw.exe: 0xC000041D: An unhandled exception was encountered during a user **callback.**_

And the module information:

Version: 5.06.0.0
Original Location: C:\Program Files\Anaconda3\Library\bin\Qt5Gui.dll

Attachment 2: VS 2015 debug
![vs 2015 debug](https://cloud.githubusercontent.com/assets/20285043/21568797/7a5a6e08-ce85-11e6-9d50-e68fe297bac5.jpg)
**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0
* Python Version: 3.5
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Sorry, I can not open Spyder 3.0.

**Comment by ccordoba12** [comment] 2016-12-30 16:49
Thanks for reporting. This is a duplicate of issue #3843 and will be fixed in Spyder 3.1.

Please see my last comment in that issue for a workaround until we release 3.1 ;-)

**Closed by ccordoba12** 2016-12-30 16:49 UTC
