### ISSUE TITLE
Console blocks when debugging if using the Tkinter graphics backend on Windows

### ISSUE THREAD

**Issue by Rabijns** [spyder-ide/spyder#17523] opened 2022-03-22 16:05 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
when using ctrl-F5 to debug a file , the console blocks 

debugfile('D:/code/hyperion_metadata/python_code/untitled4.py', wdir='D:/code/hyperion_metadata/python_code')
> d:\code\hyperion_metadata\python_code\untitled4.py(2)<module>()
      1 # -*- coding: utf-8 -*-
----> 2 """
      3 Created on Tue Mar 22 16:52:09 2022
      4 
      5 @author: RMT7801

IPdb [1]: !continue

I did not find a way to get the console active again.

### What steps reproduce the problem?

1. create a simple python file 
2. place a break point
3. press ctrl+F5

### What is the expected output? What do you see instead?
in previous versions, the console goes trough the file in debug mode and halts on the first breakpoint.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.2.2 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)

```

**Comment by LiGengLei** [comment] 2022-03-29 11:51
I have the same problem.

**Comment by ccordoba12** [comment] 2022-03-29 13:15
Closing as a duplicate of #17519.

**Comment by LiGengLei** [comment] 2022-03-29 13:51
Hi, I have looked carefully at the question #17519. But it doesn't match this question.  When start the debug mode, all buttons can not work as normal as follows.
![spyder_debug_error](https://user-images.githubusercontent.com/34147727/160626699-2273900a-9d64-42a8-a173-6cc9d3006745.gif)

**Comment by ccordoba12** [comment] 2022-03-29 17:19
Ok, I see. Thanks for the video @LiGengLei! Reopening then.

**Comment by ccordoba12** [comment] 2022-03-29 17:20
Since both @Rabijns and @LiGengLei seems to be using our Windows installer, I'd like to ask @dalthviz if he sees the same problem with it.

**Comment by Rabijns** [comment] 2022-03-29 18:43
First of all, thank you for the investigations.
I checked a few more things on my side, they might or might not be helpful for your analysis.

In a first step, I tried to recreate the exact same behaviour as in the gif above.
It is not identical, even if the differences are subtle.
For instance, I have an exclamation mark before the continue command, which I do not see in the gif of @LiGengLei [LiGengLei](https://github.com/LiGengLei)

![environment1](https://user-images.githubusercontent.com/9770955/160681293-169f8eda-a02f-4c03-814e-4bc8f4bdf140.gif)
  
Second observation:  The console is using an anaconda environment with python3.9.10. So I switched to the base environment (had to update spyder-kernels) and tried again. The base environment is in python 3.8.5. The behaviour seems different.
![environment2-base](https://user-images.githubusercontent.com/9770955/160681965-d30829ad-d446-4247-8a19-f3366ecf9e32.gif)
  
Finally, I switched to Default (i.e. same as Spyder's), which gave the following:
![environment3-spyder](https://user-images.githubusercontent.com/9770955/160682369-09aa0658-5bf7-426c-99fe-0ba27408c6d8.gif)

**Comment by LiGengLei** [comment] 2022-03-30 02:33
As @ccordoba12 said, I use the Windows installer, the version is 5.2.2. And my debugger setting is identical to those posted by @dalthviz . yet when I click "consoles->restart kernel", the Ipython consoles always show as below, I have to close spyder and reopen.
![image](https://user-images.githubusercontent.com/34147727/160739129-b0161c79-962c-44a8-b649-7cfaa01cbd59.png)

![image](https://user-images.githubusercontent.com/34147727/160739022-425ebfe2-3573-4e87-98bd-bf33f38bfe6a.png)

**Comment by dalthviz** [comment] 2022-03-30 18:41
@LiGengLei @Rabijns could you restart Spyder in debug mode an post here the `spyder-debug.log` file generated (should be located in the spyder config folder `.spyder-py3`) after trying to debug?

To restart Spyder in debug mode you can go to `Files > Restart in debug mode` and then select the `Verbose` option

**Comment by LiGengLei** [comment] 2022-03-31 05:52
Today I opened spyder and received an update reminder for version 5.3.0, I tried to upgrade to the new version. Everything is fine now. Thanks for your work and responses!

**Comment by Rabijns** [comment] 2022-03-31 06:25
I did two tests, you can find the log files for both below.
The first one was spyder with the environment set to default(same as spyder), the second one with an anaconda environment with python 3.9.
for the second one, the timing is as follows:
08:19:29: I click on the red stop button at the top of the console
08:20:29: As the console is blocked, I click on the 'close' x of the console tab

[spyder-debug - default interpreter.log](https://github.com/spyder-ide/spyder/files/8386497/spyder-debug.-.default.interpreter.log)
[spyder-debug - python9 env.log](https://github.com/spyder-ide/spyder/files/8386498/spyder-debug.-.python9.env.log)

As 5.3.0 might solve the issue, I'll do an install and report back.

**Comment by Rabijns** [comment] 2022-03-31 07:27
I'm less lucky: spyder 5.3.0 did not solve the issue.
Just to be sure, I also did a 'reset to factory default', but no change.
You can find an extra log file below, now made in 3.5.0. There are 3 actions:

1. test debug by using the icon in the menu bar
2. test debug by using ctrl+F5
3. stop debugging using the 'interrupt kernel' button in the console.
Then I closed spyder, so as to ensure the log file is not locked.

[spyder-debug -python9- spyder5.3.0.log](https://github.com/spyder-ide/spyder/files/8386930/spyder-debug.-python9-.spyder5.3.0.log)

just ot show the exact behaviour in 5.3.0, please find hereafter a gif.

![environment3-spyder5 3 0](https://user-images.githubusercontent.com/9770955/161001014-ace619f1-3e6f-4295-aaf4-236145a82223.gif)

**Comment by ccordoba12** [comment] 2022-04-01 04:22
@Rabijns, the error shown by @dalthviz above could be caused if you installed `pyzmq` (or a package that depends on it) with `pip --user`.

**Comment by Rabijns** [comment] 2022-04-01 07:24
I'm not 100% sure how to check this, but:

1. normally, I actively avoid pip and only use conda. But I'm not sure if it might have arrived on my computer with something else using python (eg qgis).
2. if in the ipython console, with the conda environment active, I try to do `import pyzmq as test`, I get a message `ModuleNotFoundError: No module named 'pyzmq'`
3. If I go to preferences, set the interpeter to use the default (i.e. the same as spyder)  interpreter, start a new console and do the same, I also get the message that pyzmq is not found.
4. when I open the anaconda prompt, and I do `conda list` (in base environment), pyzmq is not listed.

So I would guess it is not installed at all. Are these checks enough to confirm the absence or should I do something more?

ps: I forgot to confirm this before, but I did indeed install spyder via the windows installer.

**Comment by dalthviz** [comment] 2022-04-05 15:44
I think that to import `pyzmq` you need to use something like `import zmq` @Rabijns Also, checking your conda list output, the `pyzmq` version installed seems like is `22.3.0` which seems ok I think (maybe @ccordoba12 has more input on that aspect). However seems like `ipykernel` have had a couple of release in the past week so maybe updating it could help. Could you try to update `ipykernel` @Rabijns and check if the debugging situation changes when you are using a custom interpreter? Let us know!

**Comment by dalthviz** [comment] 2022-04-06 15:07
@Rabijns I suggested updating `ipykernel` (seems like you have version `6.9.2` and currently the latest version is `6.12.1` ) no `ipython` (you already had version `7.32.0` in the conda list output).

Checking the Windows installer, it comes with `ipykernel`  `6.10.0` so maybe updating to that version in you customn interpreter env could help. Also, seems like for the `zmq.error.ZMQError: not a socket` error getting `jupyter_client` `7.1.0` or `7.2.0` can help as mentioned in https://github.com/spyder-ide/spyder/issues/17615

**Comment by Rabijns** [comment] 2022-04-06 19:49
I did the following steps:

- upgraded ipykernel from 6.9.2 to 6.12.1. This did not resolve the issue.
- upgraded jupyter_client from 7.1.2 to 7.2.0: issue still present.
- downgraded ipykernel from 6.12.1 to 6.10.0, to be on the same version as the windows installer: problem still there.
-  `conda update --all --channel conda-forge`  not a solution, as it upgrades jupyter_client to 7.2.1, so it triggers the bug you linked to.
- downgrade jupyter_client to 7.2.0: no luck.

I will not be able to test further the coming days, but end of next week, I'll try to create a new environment with python 3.8 instead of 3.9. After all, the issue seems related to my env. I'll keep you informed.  Anyhow, your help is appreciated.

**Comment by daharn** [comment] 2022-04-08 13:44
Just in case this adds information, debugging doesn't work for me any more either. 

I have experimented a little:
Creating a new environment with `conda new -n newEnv spyder=5.1.5` results in a spyder version with the above error. 
The resulting environment is
* Spyder version: 5.1.5 None
* Python version: 3.9.12 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 3.10.0-1160.31.1.el7.x86_64```


```


However, when I use `conda new -n newEnv -c conda-forge spyder=5.1.5` will not cause this bug to appear.

**Comment by ccordoba12** [comment] 2022-04-08 14:01
@daharn, debugging is broken in Spyder 5.1.5. We have let users know about that a lot during the last months.

That error is already fixed in our latest version (5.3.0). Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Given that this doesn't add anything to the discussion taking place here, I'm going to hide your comment as well as mine. For next time, please open a new issue instead of posting in an unrelated one.

**Comment by Rabijns** [comment] 2022-04-14 08:03
As promised, I created a new environment, with python 3.8 instead of 3.9. 
In this new env, ipykernel is at 6.13.0. The issue remains present.

**Comment by Rabijns** [comment] 2022-04-14 09:59
I did some more testing. Instead of creating the complete environment all at once, I started with a minimal version (python3.9+spyder-kernels) and added one by one the libraries, each time testing if the debugger worked in spyder.  
All tests below are done with conda-forge as channel.

**step 1:**
- python 3.9 + spyder-kernels : ok
- added lxml : ok
- added sqlalchemy: ok
- added python-pdal : ok
- added pandas: ok
- added geopandas: **no longer ok**  
  
**step 2:**
As adding geopandas loads a lot of packages, I decided to add them one by one.
Starting from the previous env, I went back one revision (so without geopandas) and started adding the packages normally installed together with geopandas one by one.
- added fonttools: ok
- added pillow : ok
- added shapely : ok
- added gdal: ok
- added rtree: ok
- added scipy: ok
- added fiona (including shapely): ok
- added folium: ok
- added matplotlib-base: ok
- added pyproj : **no longer ok**  

**step 3:**
Assuming the issue is related to pyproj, I created a new environment, with only python3.9, spyder-kernels.
- added pyproj. Strangely enough, this environment works. 
- added geopandas: ok
- added sqlalchemy: **no longer ok**
- go back one revision: **no longer ok** This is weird, as it used to work...
- go back to revision 0: **no longer works**

I repeated this test a second time, just to be sure, arriving at the same conclusions.

**step 4:**
The original issue was discovered with my environment called hyperion_metadata. For testing purposes, I loaded pycharm community edition on my system. There, I have no issues with my environment , including for debugging with breakpoints in ipython.

**Comment by Rabijns** [comment] 2022-04-15 09:09
You can find the export in attachment. I added .txt as extension, because github does not accept .yml files. 
 
[hyperion_metadata.yml.txt](https://github.com/spyder-ide/spyder/files/8495077/hyperion_metadata.yml.txt)

**Comment by dalthviz** [comment] 2022-04-19 17:50
@Rabijns thanks for the `.yml` file! However, checking it seems like I'm not being able to create the env with it due to `poppler` (not totally sure why 🤔 ). This is what I'm getting:

![imagen](https://user-images.githubusercontent.com/16781833/164064075-26a0b421-d174-407d-8a9c-49ea0350f7ba.png)


```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - poppler==22.01.0=h24fffdf_1
```

**Comment by Rabijns** [comment] 2022-04-21 06:25
@dalthviz I'm not a conda specialist, so I cannot really help you with poppler.
What you culd try as an alternative, is to create the environment using:   
`conda create --name test --channel conda-forge python=3.9 spyder-kernels==2.3 geopandas lxml sqlalchemy python-pdal`  
I did this just now, and the resulting environment does have the debugging issue in spyder.
  
Note that I do get a warning on the size of one download when I create this env. This env does contain poppler, but with anoter number at the end (conda-forge/win-64::poppler-22.01.0-h24fffdf_2).

**Comment by Rabijns** [comment] 2022-04-21 13:59
I now have access to a second machine, which allows me to confirm two things:
1. I also have the message from poppler
2. If I create the environment as described in the previous post, I still have the debug issue.

**Comment by dalthviz** [comment] 2022-04-21 15:37
Thanks for the new info @Rabijns ! With your comment at https://github.com/spyder-ide/spyder/issues/17523#issuecomment-1104763657 I was able to reproduce this!

Checking around the IPython console plugin preferences I make the debugging work by changing the graphics backend to `inline` (`Preferences > IPython Console > Graphics > Graphics backend`), deactivating the option `Activate support` (`Preferences > IPython Console > Graphics > Support for graphics (Matplotlib)`) or changing the graphics backend to `Qt5`. With the `Qt5` I can use the debugger but I also got a message regarding being unable to find a qt binding:

![imagen](https://user-images.githubusercontent.com/16781833/164495839-e15687a4-0970-4aef-9242-c11015244274.png)

If I set the graphics backend to `Automatic` or `Tkinter` I get the console blocked when entering debug mode and I get a `Tkinter` error message when trying to interrupt it:

![imagen](https://user-images.githubusercontent.com/16781833/164497485-224f3f81-4f28-4050-add7-5964d2fd686b.png)

So I think the problem is debugging while having selected the Tkinter backend

**Comment by Rabijns** [comment] 2022-04-21 17:00
I tested your explanation above and confirm your observations. Thanks a lot for your support.

**Comment by ccordoba12** [comment] 2022-04-21 17:13
I think this problem only happens on Windows (I can't reproduce it on Linux). Also, perhaps the only way to fix it is by automatically switching to the Inline backend before entering the debugger and re-enable the Tkinter one afterwards.

**Comment by ccordoba12** [comment] 2022-09-02 03:21
@dalthviz, I think we need to update the Tkinter binaries packaged with the installer to be the same ones used in the Python 3.8.10 version that we're using to build it (it seems we're still packaging the ones for Python 3.7).

If after that this problem persists, then I'd suggest to show a message in the console saying that debugging doesn't work with the Tkinter backend and that users need to switch to a different one.

**Comment by dalthviz** [comment] 2022-09-21 16:33
After checking this for a while I was finally able to debug using the Tkinter backend. The problem is reproducible in both standalone and conda installations (and most probably pip too). The actual problem comes from the integration that ipykernel tries to provide for Tkinter on Windows. Adding a call to `quit()` the Tkinter app over the code on ipykernel that handles the kernel `do_one_iteration` call fixes the issue on Spyder. Should I do a PR with the change on ipykernel @ccordoba12 ?

**Comment by ccordoba12** [comment] 2022-09-21 17:01
> Should I do a PR with the change on ipykernel @ccordoba12 ?

Yeah, if that fixes the problem, please do that @dalthviz. Also, after a new ipykernel version is released with your fix, please add a test here to be aware of possible regressions due to future changes on that project.

**Closed** 2022-10-01 01:34 UTC
Labels: type:Bug, OS:Windows, component:Debugger, component:IPython Console, status:Reproduced, upstream
