### ISSUE TITLE
Add option to set syntax highlighting language for a file

### ISSUE THREAD

**Issue by ptoche** [spyder-ide/spyder#3270] opened 2016-06-29 18:47 UTC
Syntax highlighting is not switched on if the extension is `py2` instead of `py`. Is there an option I can configure to switch the sytax highlighting on? Thanks!

**Why?**
I am translating some python2 code into python3 and found it useful to have the python2 version of spyder alongside the python3 version (latest dmgs for MacOS). I have also found it useful to change the python2 code extension to `.py2`. And I recolored the spyder icon and have the standard red icon for spyder3 and blue for spyder2!

**Comment by ccordoba12** [comment] 2016-06-30 00:29
There is currently no way to change the highlighting language for a file.

This will be solved by adding a menu to let users do this. However, I don't see it as an easy task, so we won't do it in in the immediate future.

**Comment by goanpeca** [comment] 2016-06-30 00:41
i guess this is like the notepad++ functionality, right?

**Comment by ccordoba12** [comment] 2016-06-30 02:17
Yep, exactly. But we need to generate that menu dynamically according to 
the available Pygments lexers. And we also need to add a way to change 
the highlighting language on the fly.

**Comment by Nodd** [comment] 2016-06-30 05:45
I think that there is an old issue about it already. (on my phone right now, not easy to search…)

**Comment by ptoche** [comment] 2016-06-30 07:04
Thank you :-)

**Comment by Nodd** [comment] 2016-06-30 07:49
Found it: #638

**Comment by ptoche** [comment] 2016-06-30 11:29
Actually my request was rather simpler: to prevent switching off syntax highlighting for files not ending in ``.py``. The file assocation mentioned in #638 is working for me: I can open ``.py2`` files within ``spyder`` and they will also open when I double-click on them. 

How often is spyder used to edit files that are not ``.py``? If the answer is very rarely, then a simple solution is to treat all text presented to the editor as python code.

**Comment by Nodd** [comment] 2016-06-30 12:12
I think it's way more common to edit non python files than editing python files with an extension different than .py.

The issue is still that the user should be able to choose the syntax highlighting himself. In your specific case it's for .py2, but for us the problem is more general.
A menu is just the most obvious way to do it.

**Comment by ccordoba12** [comment] 2016-06-30 13:48
@Nodd, I also recalled we had an old issue about this, but I couldn't find it! Good searching powers my friend!

@ptoche, as @Nodd said, the easiest and more intuitive way to solve this for our users is to add a menu that will let them select the highlighting they prefer.

**Comment by ptoche** [comment] 2016-06-30 13:57
@ccordoba12 , sure, can't argue with that. I didn't realize that spyder was often used to edit code other than python, but reading the description I see that the editor is described as "multilanguage", so yes your approach makes sense! Thanks.

**Comment by bramson** [comment] 2019-01-10 02:16
It has been a couple of years now, is there currently a way to set (or at least turn on the default) syntax coloring for non *.py files?

**Comment by michaelblowry** [comment] 2019-06-06 20:16
I am also curious if this is possible now or will be in the future. My use case is *.pyt files which are Python Toolbox files for ArcGIS.

**Comment by tjhallum** [comment] 2019-11-26 17:25
> I am also curious if this is possible now or will be in the future. My use case is *.pyt files which are Python Toolbox files for ArcGIS.

+1, as I'm running into this too!

**Comment by svHatch** [comment] 2020-04-21 12:05
+1 same with me

**Comment by nkleinbaer** [comment] 2020-10-29 21:30
I'm having the same issue as svHatch and tjhallum, this would be a great feature for GIS developers.

**Comment by ccordoba12** [comment] 2020-10-29 22:24
Sorry, this is a duplicate of issue #638. Please add further comments there.

**Closed** 2020-10-29 22:24 UTC
Labels: component:Editor, resolution:Duplicate, type:Enhancement
