### ISSUE TITLE
spyder kernel 

### ISSUE THREAD

**Issue by Zhijun166** [spyder-ide/spyder#8597] opened 2019-01-19 15:47 UTC
# #My mac has a kernel crash. Every time I use this model to predict, the kernel crashes. I want to know what I should do. Very urgent

anaconda 3

python 3.6.8

spyder 3.3.2。kernel 0.3.0

My mac has a kernel crash. Every time I use this model to predict, the kernel crashes. I want to know what I should do. Very urgent

![image](https://user-images.githubusercontent.com/40523376/51428906-62a75c80-1c44-11e9-855d-83d011d296d1.png)
![image](https://user-images.githubusercontent.com/40523376/51428941-6aff9780-1c44-11e9-8d97-3996c0231a22.png)
![image](https://user-images.githubusercontent.com/40523376/51428942-6cc95b00-1c44-11e9-9c09-5394ae2302c2.png)

**Comment by Zhijun166** [comment] 2019-01-20 00:32
help me

**Comment by Zhijun166** [comment] 2019-01-20 04:55
help me
  thanks @maraigue @jondo @ehabkost @spillz

**Comment by Zhijun166** [comment] 2019-01-20 04:57
@Quansight

**Comment by Zhijun166** [comment] 2019-01-20 04:59
@Daniel Althviz Moré

**Comment by Zhijun166** [comment] 2019-01-20 06:57
why

**Comment by Zhijun166** [comment] 2019-01-20 14:11
![image](https://user-images.githubusercontent.com/40523376/51440259-39e49d00-1d00-11e9-9383-05aebcc780ca.png)

**Comment by ccordoba12** [comment] 2019-01-20 16:31
This is a duplicate of #8581.

**Closed by ccordoba12** 2019-01-20 16:31 UTC

**Comment by Zhijun166** [comment] 2019-01-21 01:06
no ，my system is mac   os majave ，This is not a copy of 8591. My problem is still unresolved. I can publish my source files.

**Comment by ccordoba12** [comment] 2019-01-21 03:39
That issue is not related to Mojave. Please see compare your third screenshot with the one in

https://github.com/spyder-ide/spyder/issues/8581#issuecomment-455354955

to see that both are exactly the same issue. So please don't make us waste our time by opening the same issue again.
