### ISSUE TITLE
Shift-Enter to run a cell is not cached

### ISSUE THREAD

**Issue by joelmontoy** [spyder-ide/spyder#9725] opened 2019-07-01 09:39 UTC
### What steps will reproduce the problem?

If you have two consecutive code cells (starting with a #%%) and you try to run them both by pressing Shift-Enter twice, only the first cell will be run.

This happens when the first cell takes some time to run, and it's still running when you press the second shift-enter. The second shift-enter is ignored.

In version 3.X it works fine, running the two cells one after the other.

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.0 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.10 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-01 10:37
Thanks for reporting.

@bcolsen, could you take a look at this one?

**Comment by bcolsen** [comment] 2019-07-02 06:25
This behavior was introduced in `runfile` with #7294 in version 3.3 to fix #7293. This allowed the stop button to stop all executing tasks by not allowing additional calls to the kernel while it's executing.

When I made the `codecell` function for spyder4 I included this fix for code cell execution.

There is also a ux issue here with the cell being advanced to the next cell without cell execution.

I for one regularly used this unofficial queuing behavior for code cells.


## Some possible resolutions:

### Solution 1
Don't allow cell advancement without cell execution.

This might need some sort of error or users might think the functionality is broken.

### Solution 2 
Make a runcell queue.

I personally like this idea but it would be quite work to implement.

### Solution 3
Remove the fix for #7293 from `runcell` and regain the feature from spyder3

This reintroduces #7293, and gives broken output in the console:
```
In [14]: runcell('Cell at line 0','/home/bcolsen/Documents/python/runcell_queue.py')

In [15]: runcell('Long cell','/home/bcolsen/Documents/python/runcell_queue.py')
running long...


Ran long
running 1...
Ran 1

In [16]: runcell('short cell 2','/home/bcolsen/Documents/python/runcell_queue.py')Ran 2


In [17]:
```
Testing Code:

```python
from time import sleep

# %% Long cell
print('running long...')
sleep(5)
print('Ran long')
# %% short cell 1
print('running 1...')
sleep(3)
print('Ran 1')
# %% short cell 2
print('Ran 2')
```

**Comment by ccordoba12** [comment] 2019-07-02 13:09
I don't agree with reverting the fix for #7293, so the only possible solution would be to create a queue for cells (and files too). But I don't think if that's a good idea because each evaluation could change the current namespace in significant ways, which could produce odd results for future evaluations.

**Comment by bcolsen** [comment] 2019-07-03 00:00
> I don't agree with reverting the fix for #7293

Yes that solution is isn't good.

> But I don't think if that's a good idea because each evaluation could change the current namespace in significant ways, which could produce odd results for future evaluations.

I can see that this could be a problem with files and cells in the same queue, but it would be less of a problem if we only queue cell execution. I think that it would cover most of the use cases for this and users would expect that the commands would be run sequetially

There will be problems with queuing the new implementation of the `runcell` function @impact27 is working on. It currently gets the cell from editor at runtime in the kernel using the API. If the user queues up a few long running cells and makes changes to the file in the editor the queued commands would take the changed code from the file and not the code from the cell at that time it was queued. It's likely that most users would find this unexpected. The same thing would happen if you queued a couple of files for execution and then changed them.

**Comment by impact27** [comment] 2019-07-03 08:01
> There will be problems with queuing the new implementation of the `runcell` function @impact27 is working on. It currently gets the cell from editor at runtime in the kernel using the API. If the user queues up a few long running cells and makes changes to the file in the editor the queued commands would take the changed code from the file and not the code from the cell at that time it was queued. It's likely that most users would find this unexpected. The same thing would happen if you queued a couple of files for execution and then changed them.

The solution would be to capture the code when Shift-Enter is pressed, and cache it in some way. The logic would then be: 
- If there is code cached, use it. (verify the cell name and file name matches, maybe a `dict`)
- else, use the api to get the code

This poses the problem of cache invalidation of course. How do we know if the cache is still valid (What to do if the user cancelled execution of one of the cached cells?). 

An alternative would be to add an argument to `runcell` to explicitly fetch from cache. something like:
`runcell(cellname, filename, cached=True)`
This way it would be clear if `runcell` should use the api or the cache.

**Comment by bcolsen** [comment] 2019-07-04 18:17
>The solution would be to capture the code when Shift-Enter is pressed, and cache it in some way. The logic would then be:
>
>   - If there is code cached, use it. (verify the cell name and file name matches, maybe a dict)
>   - else, use the api to get the code

An edge case would be running the same cell 5 times with 5 different edits.

One way around this and cache invalidation is to cache the code directly into the queue. 

- While the kernel is busy, commands(and cached code) should be added to the queue every time a command(like `runcell` and `runline`) is given in Spyder. 
- When the kernel is finished, the next command in the queue is run.
    - This can include sending cache code to the server 
- If at any point the user clicks the stop button the current command is stopped and the queue is flushed. 
- This queue would be part of the Spyder IPython plugin so it would be unique to each kernel and still be modified while the kernel is busy.

**Comment by bcolsen** [comment] 2019-08-29 20:53
Moving this here because it's not a regression and whether we save or not might not make a difference. 

@impact27 said:
>Why? Do you want to let the user run a cell and then modify it while it is in the queue? This will already be difficult, as the code is fetched at execution time.

I want to modify cell and execute a cell while a previous version of the cell is in the queue but I don't want to modify the code that is already in the queue.

The front end(spyder) queue needs to contain cached code because a user would expect that when they press a button on the front end on a cell or a file that the code at that time will be the code that eventually runs.

One solution would be to have a comms queue handler in spyder kernels that gets a command and cached code from the spyder queue(a list of dictionaries with commands and code caches). The queue handler could populate a code variable in ipython that if populated would be used as the code instead of asking spyder what the code should be.  There should be a few other ways as well.

**Comment by impact27** [comment] 2019-08-29 22:08
> Moving this here because it's not a regression and whether we save or not might not make a difference.
> 
> @impact27 <https://github.com/impact27> said:
> 
> Why? Do you want to let the user run a cell and then modify it while it is in the queue? This will already be difficult, as the code is fetched at execution time.
> 
> I want to modify cell and execute a cell while a previous version of the cell is in the queue but I don't want to modify the code that is already in the queue.
> 
> The front end(spyder) queue needs to contain cached code because a user would expect that when they press a button on the front end on a cell or a file that the code at that time will be the code that eventually runs.
> 
> One solution would be to have a comms queue handler in spyder kernels that gets a command and cached code from the spyder queue(a list of dictionaries with commands and code caches). The queue handler could populate a code variable in ipython that if populated would be used as the code instead of asking spyder what the code should be. There should be a few other ways as well.
> 
One way I can think of would be to add something to the cell name: if we want to run the cell "do stuff", and the kernel is busy, we could cache the cell content and give it a name like "do Stuff @ cache:1234". When the line is executed, the run_cell function will ask the frontend for the code for cell "do Stuff @ cache:1234", and the frontend could pop the cache. This way we don't need to modify the kernel.

**Comment by bcolsen** [comment] 2019-08-30 19:50
>One way I can think of would be to add something to the cell name: if we want to run the cell "do stuff", and the kernel is busy, we could cache the cell content and give it a name like "do Stuff @ cache:1234". When the line is executed, the run_cell function will ask the frontend for the code for cell "do Stuff @ cache:1234", and the frontend could pop the cache. This way we don't need to modify the kernel.

Yeah that's great idea. Definitely the way to go. The queue would then be a simple list of command strings and the cache would be a dictionary of code and hashes. We can have Spyder do all the code caching separately when it adds to the queue.

We could add an optional parameter to the runcell and runfile like `cache=None` which would be a little cleaner than adding it to the cellname and then having to parse it. Then we would be be able to  cache whole files for runcell as well(the imported modules could still change but we have to stop somewhere).

**Comment by impact27** [comment] 2019-08-31 09:49
> Yeah that's great idea. Definitely the way to go. The queue would then be a simple list of command strings and the cache would be a dictionary of code and hashes. We can have Spyder do all the code caching separately when it adds to the queue.
> 
> We could add an optional parameter to the runcell and runfile like `cache=None` which would be a little cleaner than adding it to the cellname and then having to parse it. Then we would be be able to cache whole files for runcell as well(the imported modules could still change but we have to stop somewhere).

I think this is the correct way of doing this. I modified `runfile` in https://github.com/spyder-ide/spyder/pull/10115 to get the code from the editor, so we could even cache `runfile`. When this PR is merged, a `cache` parameter can be added to `_handle_get_file_code` and `handle_run_cell`.

**Closed** 2020-09-28 00:45 UTC
Labels: component:IPython Console, type:Enhancement
