### ISSUE TITLE
can't input msg

### ISSUE THREAD

**Issue by RedSQr** [spyder-ide/spyder#18491] opened 2022-06-30 05:34 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
myName = input("Please enter your name: ")
myAge = input("What about your age: ")
print ("Hello World, my name is", myName, "and I am", myAge, "years old.")
print()

**Comment by dalthviz** [comment] 2022-06-30 15:24
Hi @RedSQr seem like you are having problems with the `input` function? What Spyder version are you using? Since seems like `input` is involved I would say most probably that this is a duplicate of https://github.com/spyder-ide/spyder/issues/17616

To fix the situation the first suggestion that we could give you is to update Spyder to the latest version available (currently 5.3.1). For that you have some options dependending on the OS you are working on and the way you installed Spyder:

* Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases). With this option you will get an standalone Spyder version installed that then you can launch from a shortcut named `Spyder`.
* Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt or terminal and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
    With the commands above you will create a new env call `spyder-cf` with Spyder latest version installed, activate the env and launch Spyder from it.

Also, in the future, please fill out the issue template. Without that info is quite difficult to fully understand your setup and give proper help/advise.

Let us know if something of the above helps!

**Comment by RedSQr** [comment] 2022-07-01 00:05
TY

**Closed** 2022-07-01 15:31 UTC
Labels: resolution:Completed, status:Awaiting Followup
