### ISSUE TITLE
Encounter to error While installing Spyder

### ISSUE THREAD

**Issue by NitinSaini18** [spyder-ide/spyder#13777] opened 2020-09-14 11:04 UTC
### What steps will reproduce the problem?

I was installing spyder on new environment of python==3.5 and then i installed tensorflow=1.0.0 After when i try to install Spyder using * conda install Spyder * then it gives me this error
 *conda.core.link:_execute(481): an error occurred while installing package 'defaults::ipykernel-4.10.0-py35_0'. 
linkerror: post-link script failed for package defaults::ipykernel-4.10.0-py35_0 running your command again with `-v` will provide additional information*
 please do not tell me to update conda because if i update then my command then I am not able to install tensorflow of specific version 1.0.0 So please tell me other Alternatives
 please tell me how can I solve this issue

## Versions

* Spyder version: 4.1.5 
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-09-14 12:53
Closing as a duplicate of #13776 

@NitinSaini18, please stop reporting these bugs here and instead report them in the Anaconda repo I told you about

https://github.com/ContinuumIO/anaconda-issues

**Closed by ccordoba12** 2020-09-14 12:53 UTC

**Comment by NitinSaini18** [comment] 2020-09-14 12:57
I reported error there also but i do not have any response from there.
Please can you suggest me some other solution.

**Comment by ccordoba12** [comment] 2020-09-14 13:00
I'm sorry to hear that. Unfortunately, I don't have other suggestions.

**Comment by NitinSaini18** [comment] 2020-09-14 13:31
Okay, let me tell you  my actual problem : when I create a new environment with python 3.7 and tensorflow 2.3 the spyder install perfectly and runs very smoothly and when run my code of Chatbot.py it gives me error : 
AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'prepare_attention' I know that prepare_attention no longer is available in tensorflow lastest version rather this function only available in tensorflow 1.0.0 version thats why i am installing spyder to new env. But As you read it I am getting error. Can you suggest me alternative of Prepare attention for my lastest version. Here is my part of code:

**Comment by ccordoba12** [comment] 2020-09-14 17:00
@NitinSaini18, thanks for details. What you need to do to solve this problem is to create a conda environment, then use pip to install Tensorflow 1.0, spyder-kernels and the other packages you need to run your code. Finally, you need to connect Spyder to the Python interpreter of that environment by going to the menu

    Tools > Preferences > Main Interpreter

and selecting it as your custom interpreter.

The second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) describes this process in detail, so please take a look at it.

**Comment by NitinSaini18** [comment] 2020-09-15 06:54
@ccordoba12 I was facing this problem from the past 3 days and you are the only one who solved my issue. Thank you so much!!!

**Comment by ccordoba12** [comment] 2020-09-15 14:35
I'm really glad to know @NitinSaini18!
