### ISSUE TITLE
Freeze variable window

### ISSUE THREAD

**Issue by RafaBG** [spyder-ide/spyder#10597] opened 2019-11-04 03:46 UTC
### What steps will reproduce the problem?

inspect a variable (List of Dataframe) the pop for the list stays open while still navigating between code and ispect variable.

### Traceback
```python-traceback
  File "/Users/rafaelbarragan/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 544, in <lambda>
    lambda val: self.load_more_data(val, rows=True))
NameError: free variable 'self' referenced before assignment in enclosing scope
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.13.0
* PyQt5 version: 5.13.1
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-11-05 02:21
Thanks for reporting. This is a duplicate of issue #7880 and it'll be fixed in Spyder 4.

**Closed by ccordoba12** 2019-11-05 02:21 UTC
