### ISSUE TITLE
Crash occurs frequently when using the Replace selection

### ISSUE THREAD

**Issue by ssswokao** [spyder-ide/spyder#12150] opened 2020-04-05 13:21 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Crash occurs frequently when using the Replace selection.
For example I have 100 `(i,4)))=1` and I want to replace 30 of them with `(ii,4)))=1 and bool(ws_cq.cell_value(i,5) in del_templ)==0` . 
I select some lines which contain 30 `(i,4)))=1`  , then press ctrl+R paste  `(i,4)))=1` in the upper box and paste `(ii,4)))=1 and bool(ws_cq.cell_value(i,5) in del_templ)==0` in the lower box then click Replace selection, and then Spyder crash.
Sometime restart Spyder and do the same steps will work .

### What steps reproduce the problem?

1. select some lines which contain 30 `(i,4)))=1` 
2. press ctrl+R
3. paste  `(i,4)))=1` in the upper box
4. paste `(ii,4)))=1 and bool(ws_cq.cell_value(i,5) in del_templ)==0` in the lower box
5. click Replace selection
6. Spyder crash

### What is the expected output? What do you see instead?
Expected: 30 `(i,4)))=1` are replaced by  `(ii,4)))=1 and bool(ws_cq.cell_value(i,5) in del_templ)==0`
What I see : crash

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.1 & 4.0.1
* Python version: 3.7.6 64-bit
* Qt version: 5.12.7
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)


```

**Comment by ssswokao** [comment] 2020-04-06 04:27
Well, I am little surprised that issues opened before and after this one are replied.
This issue is not a common problem or my description is unclear？
thx

**Comment by ccordoba12** [comment] 2020-04-06 18:54
@andfoy, please take a look at this one.

**Comment by ssswokao** [comment] 2020-04-07 02:11
> @andfoy, please take a look at this one.

And it seems more frequently when replacing with a long one

**Comment by andfoy** [comment] 2020-04-09 23:13
It seems I'm unable to reproduce this one:

![Peek 09-04-2020 18-12](https://user-images.githubusercontent.com/1878982/78948403-cad2a000-7a8d-11ea-8757-7577f6704057.gif)

**Comment by ssswokao** [comment] 2020-04-10 02:41
Well，please remain this open and I will post a GIF here next time I meet this problem

**Comment by ssswokao** [comment] 2020-04-10 02:42
Well，please remain this open and I will post a GIF here next time I meet this problem
Thanks！

**Comment by ccordoba12** [comment] 2020-04-11 20:39
Closing for now. Please post again here when you're able to reproduce the error.

**Closed by ccordoba12** 2020-04-11 20:39 UTC
Labels: component:Editor, type:Bug

**Comment by ams6737** [comment] 2023-08-31 18:28
New to github, but this issue is still occurring with 5.3.3. I replace all in selection.
