### ISSUE TITLE
Sporadic Spyder crashes when using import GUI with CSV

### ISSUE THREAD

**Issue by dwaynepaschall** [spyder-ide/spyder#5948] opened 2017-12-10 17:27 UTC
## Description
importing csv file with row1 = column names
**What steps will reproduce the problem?**

1. use the import gui from the variable explorer pane
2. select a csv file; change the skip rows value from 0 -> 1 -> 0
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\ddp\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 574, in _set_step
    self.text_widget.get_skiprows(),
  File "C:\Users\ddp\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 251, in get_skiprows
    return int(to_text_string(self.skiprows_edt.text()))
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\ddp\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 574, in _set_step
    self.text_widget.get_skiprows(),
  File "C:\Users\ddp\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 251, in get_skiprows
    return int(to_text_string(self.skiprows_edt.text()))
ValueError: invalid literal for int() with base 10: ''

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-10 18:53
Thanks for reporting. I was unable to reproduce this error on my Windows machine, identical versions of everything and an arbitrary csv; I changed the "skip rows" field from 0 to 1 to 0 and back a few dozen times, with various combinations of settings and other actions before/during/after, and did not see any error. 

Therefore, can you post precisely the actions you took to prompt this error, and if possible, the CSV (or an abridged portion thereof that still produces the error)? Thanks.

**Comment by dwaynepaschall** [comment] 2017-12-10 18:57
Thanks very much for the message. I will try. I had been working in Spyder
for a few days without a restart (just clearing the variable space via the
'X' in the varExplorer pane. So this may have been a contributing factor.
I'll try experimenting a bit more with it and try to re-create the
identical steps....as soon as I specify my LSTM mode and save it. Attached
is the full csv file I was attempting to load at the time.

cheers,
Dwayne

**Comment by CAM-Gerlach** [comment] 2017-12-10 22:28
Thanks very much for responding. It could very well be a corner case due to your data/environment, but it could certainly also be something more general. Unfortunately, I don't see anything attached to this message—perhaps you attached it to the email and github doesn't support that?

**Comment by CAM-Gerlach** [comment] 2017-12-16 21:27
Any luck? If we can't isolate this to Spyder, we'll probably want to close it in a few days. Thanks!

**Comment by dwaynepaschall** [comment] 2017-12-16 21:39
I've replicated *an* error several times. Still working to identify the key
contributors or repeatable steps.

**Comment by CAM-Gerlach** [comment] 2017-12-16 21:40
Great, thanks. Keep us in the loop!

**Comment by dwaynepaschall** [comment] 2017-12-16 21:42
Will do, gladly.

**Comment by CAM-Gerlach** [comment] 2017-12-19 05:17
Hey; anything new to report?

**Comment by CAM-Gerlach** [comment] 2017-12-27 08:14
Hey, don't want to leave you hanging, but if you aren't able to isolate this so it can be addressed, it might be best to close this until you do...thanks for your followups so far.

**Comment by dwaynepaschall** [comment] 2017-12-27 15:11
I agree. Reproducing the error is spotty at best right now. I'm getting the
sense that its related to an edge case with the data, environment, libs
loaded, etc. Probably makes sense to go ahead and close it, monitor the use
case and see if it persists or can be nailed down after the next update.

Thanks again for taking time to consider the problem.

Regards,
Dwayne

**Comment by CAM-Gerlach** [comment] 2017-12-27 16:04
Okay, thanks very much for all your help so far. Definitely keep us up to date if you can and re open this issue if you get it nailed down. Best of luck!

**Closed by CAM-Gerlach** 2017-12-27 16:04 UTC
Labels: status:AwaitingFollowup
