### ISSUE TITLE
spyder_kernels error at startup

### ISSUE THREAD

**Issue by Mark531** [spyder-ide/spyder#15260] opened 2021-04-12 19:28 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Right after upgrading Spyder to 5.0.0, I got a pop-up showing an error.
![spyder](https://user-images.githubusercontent.com/17707763/114448608-0f7aa500-9bd4-11eb-95c5-2042e86fcde6.jpg)
I cannot understand the problem since I have the 2.0.1 version, which is >= 2.0.1 and < 2.1.0.

### What steps reproduce the problem?

1. Run pip install --upgrade spyder
2. Run spyder

### What is the expected output? What do you see instead?
I don't expect any issue after a successful installation.

## Versions

* Spyder version: 5.0.0
* Python version:  3.7.7
* Qt version: 5
* PyQt version: 5.12
* Operating System name/version: Windows 10 64-bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by CameraEngineer** [comment] 2021-04-12 21:57
I too am experiencing the same issue.  After upgrading to Spyder5, I am unable to open the spyder window from cmd on my windows 10 computer.

**Comment by Mark531** [comment] 2021-04-12 22:00
Contrary to you, I can open Spyder and use it without problem. I just have this pop-message at start up.

**Comment by ccordoba12** [comment] 2021-04-12 22:05
Hey all, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1) to be released shortly.

**Comment by ccordoba12** [comment] 2021-04-12 22:05
@CameraEngineer, please install Spyder in a new conda environment. It should work then.

**Closed by ccordoba12** 2021-04-12 22:05 UTC

**Comment by Mark531** [comment] 2021-04-12 22:08
Oh, I'm sorry, I did search **open** issues containing "spyder_kernels" but the one you mentioned was closed...

**Comment by ccordoba12** [comment] 2021-04-12 22:24
No worries, it's not a big deal.
