### ISSUE TITLE
Can't run static code analysis

### ISSUE THREAD

**Issue by NiyaGN** [spyder-ide/spyder#5817] opened 2017-11-22 17:19 UTC
## After code was finished I wanted to run a static code analysis but that was not possible.
Instead I got this: 
KeyError: None

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by CAMGerlach-Baron** [comment] 2017-11-22 18:04
Thanks for reporting. Sounds like a duplicate of #5640 which is already fixed in Spyder 3.2.5, therefore this issue should presumably be closed.

**Closed** 2017-11-22 21:48 UTC
