### ISSUE TITLE
TimeoutError when running cells after a kernel restart

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11137] opened 2019-12-19 01:57 UTC
Full traceback below; cell runs fine via highlight + "Run selection or current line"; behavior's fixed upon restarting kernel, but returns randomly after finishing a TensorFlow training session (didn't test in other settings).

```python
Traceback (most recent call last):

  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\comms\commbase.py", line 542, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\comms\commbase.py", line 415, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 161, in _wait_reply
    call_name))

TimeoutError: Timeout while waiting for 'run_cell' reply
```

<hr>

**Update**: reproduced immediately after restarting kernel and working with basic numpy operations

<hr>

**Update 2**: interrupting frozen run-cell command yields below:

```python
Traceback (most recent call last):

  File "<ipython-input-4-633e420a5051>", line 1, in <module>
    runcell('[], #5', 'C:/DL_code/dev_ensemble_subset.py')
  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 539, in runcell
    cell_code = frontend_request().run_cell(cellname, filename)
  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\comms\commbase.py", line 542, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\comms\commbase.py", line 415, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 167, in _wait_reply
    time.sleep(0.01)

KeyboardInterrupt
```

**Comment by ccordoba12** [comment] 2019-12-19 02:17
@impact27, what do you think we should do about this?

**Comment by impact27** [comment] 2019-12-19 08:31
Is the frontend frozen when you see that? I ask because this function is here for the kernel to ask the frontend for the cell code. Are you using a remote kernel? Is there any text in the front end internal console? (View > Panes > internalconsole)

**Comment by OverLordGoldDragon** [comment] 2019-12-21 04:20
@impact27 If by "frontend" you mean the usual / default Spyder interface, then yes; I've never used any consoles besides the IPython kernel, including internal console. I haven't reproduced this issue since, so unsure what the internal console outputs when it occurs - but will look out for next occurrence.

**Comment by OverLordGoldDragon** [comment] 2019-12-24 08:30
@impact27 Happened again now, I checked the internal console - it logged something:

![image](https://user-images.githubusercontent.com/16495490/71403431-2b59e080-2649-11ea-9c92-c2b9adc4287a.png)

**Comment by OverLordGoldDragon** [comment] 2019-12-25 16:01
@impact27  @ccordoba12 Finally found a reproducible instance:

[demo1.mp4](https://www.dropbox.com/s/3lxqfqdfhwx2nmq/s4_demo1.mp4?dl=0)<br>
[demo2.mp4](https://www.dropbox.com/s/3lxqfqdfhwx2nmq/s4_demo1.mp4?dl=0)

**Comment by ccordoba12** [comment] 2019-12-25 16:09
It seems that that's related to the code you're programming in Spyder. Could you share it with us?

**Comment by OverLordGoldDragon** [comment] 2019-12-25 16:12
@ccordoba12 Finally an actually reproducible snippet: [s4_demo3](https://www.dropbox.com/s/uzalizyodjwpkcy/s4_demo3.mp4?dl=0). Note that it doesn't [i]always[/i] occur - for me it happens every other attempt or so.

**Comment by doggyulee** [comment] 2019-12-27 13:35
same issue with me ... i wish i wanna fix it but, there are no any advices apart from only this .. please help !!

**Comment by OverLordGoldDragon** [comment] 2019-12-27 16:05
@doggyulee For an alternative, you can highlight the code in the cell and "Run selection":

![image](https://user-images.githubusercontent.com/16495490/71523831-26648d80-28e4-11ea-9ef4-aa42130959bf.png)

**Comment by impact27** [comment] 2019-12-28 16:23
I can't reproduce on mac. A workaroud could be to select this in the settings:
<img width="1055" alt="Screenshot 2019-12-28 at 17 21 12" src="https://user-images.githubusercontent.com/6740194/71546392-ab0fe400-2996-11ea-8e63-219d69c668a5.png">

**Comment by impact27** [comment] 2019-12-28 23:19
I can reproduce with windows. This is caused by the comm port not being set. 
 - We should not try to send a reply from the frontend without this port being open. this should be an error.
 - O don't know why the port is not set on restart sometimes, this looks like a race condition.

**Comment by impact27** [comment] 2019-12-29 00:00
The real workaround is to simply close the tab and don't restart the kernel.

**Comment by impact27** [comment] 2019-12-30 10:54
Solved in https://github.com/spyder-ide/spyder/pull/11192

**Comment by OverLordGoldDragon** [comment] 2019-12-30 12:57
@impact27 Great, will mark this solved and reopen if it recurs in the next release - thanks

**Comment by ccordoba12** [comment] 2019-12-30 14:12
> will mark this solved and reopen if it recurs in the next release - thanks

Please don't do that for next time. Issues are marked as solved once their associated pull requests are merged.

**Comment by OverLordGoldDragon** [comment] 2020-01-09 02:21
@ccordoba12 Indeed, I celebrated too early; recurred in Spyder 4.0.1. Identical error trace.

**Comment by ccordoba12** [comment] 2020-01-09 05:07
This will be fixed in Spyder 4, to be released in a couple of months. In the meantime, please switch to old way of evaluating cells, as described here:

https://stackoverflow.com/a/59494870/438386

**Closed** 2020-02-05 18:51 UTC
Labels: component:IPython Console, type:Bug

**Comment by Foroozani** [comment] 2020-11-03 08:46
I had the same error, and I fixed it easily. In my case the reason was because I had two different version of spyder on my "base environment" and "virtual environment" that I installed trough anaconda-navigator manually.
