### ISSUE TITLE
Crash after deleting a code block

### ISSUE THREAD

**Issue by Dan-Patterson** [spyder-ide/spyder#11200] opened 2019-12-31 10:40 UTC
### What steps will reproduce the problem?

I have been experiencing intermittent problems when deleting lines/blocks of code.  Spyder crashes with the "issue reporter" flashing onscreen then vanishing. The only 'reproducable' steps are to highlight a block of code, then hit the delete key.  Nothing special about the code.  New code, old code, doesn't matter. Again, it doesn't happen all the time, and I can rehighlight the same block of code after a crash and it deletes without issue (assuming autosave hasn't kicked in.)  
I can't locate a crash log or I would forward it.
Spyder 4.0.0 with all the required dependencies, Windows 10 fully uptodate.  
So this is more of an FYI in case others experience the issue.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-31 14:24
Duplicate of #10918

**Comment by ccordoba12** [comment] 2019-12-31 14:24
It'll be fixed in our next version.

**Closed by ccordoba12** 2019-12-31 14:24 UTC
