### ISSUE TITLE
Just updated Mac to High Sierra and updated Anaconda. Spyder crashes after opening

### ISSUE THREAD

**Issue by keef615** [spyder-ide/spyder#7085] opened 2018-05-08 02:01 UTC
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Today I updated my Mac to High Sierra, Anaconda to 1.8.4, and Spyder to version 3.2.8. Spyder continually crashes ~30 sec after opening.

### What steps reproduce the problem?

After upgrading to High Sierra I tried updating Spyder using pip. I'm new to coding and didn't see until after I ran this that this can cause issues. Spyder continues to crash after opening. I've tried restarting my computer, deleting anaconda and the anaconda preferences file, reinstalling Anaconda, and restarting Spyder preferences. I've also ran "export EVENT_NOKQUEUE=1" in the terminal because it was a solution on a similar issue ticket, but this did not work for me.

### What is the expected output? What do you see instead?

Instead of not crashing I see "Spyder has encountered an internal problem" and the window crashes.

### Paste Traceback/Error Below (if applicable)

```python-traceback

 File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 956, in update_working_directory
    shellwidget.get_cwd()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6
* qtconsole version: 4.3.1
* Qt version: 
* PyQt version: 
* Operating System name/version: MacOS High Sierra 10.13.4

### Dependencies

```
Unable to find this
```

**Comment by AntiS3** [comment] 2018-05-08 23:56
This solution worked for me: https://github.com/Azure/azure-cli/issues/5184

**Comment by ccordoba12** [comment] 2018-05-09 00:57
This is duplicate of issue #6335. To fix it you need to run in Terminal.app

    conda update python python.app

**Closed by ccordoba12** 2018-05-09 00:57 UTC

**Comment by keef615** [comment] 2018-05-09 01:51
This worked, thank you!
