### ISSUE TITLE
another way to donate to spyder?

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder#6039] opened 2017-12-23 05:39 UTC
have you ever investigate?how many user from China?
could you please give us another way to donate to spyder project?
such as "alipay", we called "支付宝" , and "Wechat Payment" , we called "微信支付“

**Comment by CAM-Gerlach** [comment] 2017-12-23 21:00
Thanks for your input. This is actually a duplicate of #5872 that we're already looking in to, and so will be closed, but feel free to submit your suggestions over there.

**Closed by CAM-Gerlach** 2017-12-23 21:00 UTC
