### ISSUE TITLE
When variables are too many, display of variable explorer is incorrect

### ISSUE THREAD

**Issue by greharwin** [spyder-ide/spyder#8287] opened 2018-11-22 13:23 UTC
### What steps reproduce the problem?
For example
```
a = ['A', 'B', 'C']
for n in range(100):
    exec("name%d = %d" %(n, n))
```
The type of a is "list", but it is displayed as "int" in the variable explorer.

## Versions

* Spyder version: 3.3.1
* Python version: 3.5.4
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  6.2.1 (OK)
cython >=0.21     :  0.27.3 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-11-22 20:34
Thanks for reporting and for the reproducible case. We'll take a look at this in a future release.

**Comment by Khalilsqu** [comment] 2019-01-26 08:15
In spyder 4 (under development) a is shown as a list to me in the variable explorer! maybe I am not reproducing tour case example correctly, or the issue do not exist in the new version under development.

![image](https://user-images.githubusercontent.com/22060413/51784560-71a97580-2142-11e9-80c3-fec9f30e7f80.png)

**Comment by ccordoba12** [comment] 2019-01-27 08:42
Thanks @Khalilsqu for the check. Closing for now since you were unable to reproduce it.

**Closed by ccordoba12** 2019-01-27 08:42 UTC
Labels: component:Variable Explorer, type:Bug
