### ISSUE TITLE
How to use git account in spyder

### ISSUE THREAD

**Issue by tanminhnu** [spyder-ide/spyder#5964] opened 2017-12-12 10:15 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/dainping/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 234, in _create_project
    self.open_project(path=path)
  File "/Users/dainping/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 261, in open_project
    self.set_project_filenames(self.editor.get_open_filenames())
  File "/Users/dainping/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 325, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "/Users/dainping/anaconda/lib/python2.7/site-packages/spyder/widgets/projects/type/__init__.py", line 74, in set_recent_files
    list(OrderedDict.fromkeys(recent_files)))
  File "/Users/dainping/anaconda/lib/python2.7/site-packages/spyder/config/user.py", line 448, in set
    self._save()
  File "/Users/dainping/anaconda/lib/python2.7/site-packages/spyder/config/user.py", line 124, in _save
    raise(e)
IOError: [Errno 2] No such file or directory: u'/Users/dainping/Documents/GitCode/platform-data/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.10
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.20.2 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.0.1 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-12-12 19:42
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2017-12-12 23:15
Appears to be a duplicate of #5934 ; not sure if it has anything to do with git. Probably a user install issue unless it only appears in specific situations; please see that issue and the potential fixes suggested there to see if that resolves your issue. If this can be isolated to something specific in Spyder, there is a chance it can get fixed from this end, but you'll need to provide more specific information first. Thanks.

**Comment by CAM-Gerlach** [comment] 2017-12-23 00:32
Closed due to lack of response.

**Closed by CAM-Gerlach** 2017-12-23 00:32 UTC
Labels: status:AwaitingFollowup
