### ISSUE TITLE
The copy functionality in the online help is not working

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#13685] opened 2020-09-01 20:59 UTC
## Problem Description
When you try to copy in the online help, an error appears

![image](https://user-images.githubusercontent.com/20992645/91905345-03a52880-ec6c-11ea-913b-ca2483b0de00.png)

### What steps reproduce the problem?

1. Go to Online Help pane
2. Use the context menu option to `Select all`
3. Use the context menu option to `Copy`

### What is the expected output? What do you see instead?
Copy the selected text in the clipboard

**Comment by goanpeca** [comment] 2020-09-01 21:05
Thanks for the feedback @steff456 

This is a duplicate of https://github.com/spyder-ide/spyder/issues/13665 and has already been fixed on https://github.com/spyder-ide/spyder/pull/13676

**Closed by goanpeca** 2020-09-01 21:05 UTC
Labels: component:Online Help, type:Bug
