### ISSUE TITLE
Can't open .py file saved on citrix files folder

### ISSUE THREAD

**Issue by paoloflorian** [spyder-ide/spyder#14666] opened 2021-01-29 15:43 UTC
### What steps will reproduce the problem?

Just trying opening a .py file saved into citrix files local folder. If same file is saved into other folder i can open it

### Traceback
```python-traceback
  File "C:\dati_locali\anaconda\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1005] Il volume non contiene un file system riconosciuto.
Controllare che siano caricati tutti i driver richiesti per il file system e che il volume non sia danneggiato: 'S:\\Cartelle personali\\analisi_dati\\pt\\elabora_pt.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dati_locali\anaconda\lib\site-packages\spyder\plugins\editor\plugin.py", line 2025, in load
    current_editor = self.set_current_filename(filename,
  File "C:\dati_locali\anaconda\lib\site-packages\spyder\plugins\editor\plugin.py", line 1558, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "C:\dati_locali\anaconda\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1694, in set_current_filename
    index = self.has_filename(filename)
  File "C:\dati_locali\anaconda\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1688, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\dati_locali\anaconda\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1686, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\dati_locali\anaconda\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\dati_locali\anaconda\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1005] Il volume non contiene un file system riconosciuto.
Controllare che siano caricati tutti i driver richiesti per il file system e che il volume non sia danneggiato: 'S:\\Cartelle personali\\analisi_dati\\pt\\elabora_pt.py'
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by paoloflorian** [comment] 2021-01-29 16:52
Even saving a file in that folder create the error. Spyder version 3 didn't have this issue on same folder.

**Comment by ccordoba12** [comment] 2021-01-31 16:19
Hey @paoloflorian, thanks for reporting. This is a duplicate of issue #14660, so let's continue the discussion there.

One question for you to answer on that issue: does this problem happen for you if you open a file in `D:\` or another regular disk partition?

**Closed by ccordoba12** 2021-01-31 16:19 UTC
Labels: status:Awaiting Followup

**Comment by paoloflorian** [comment] 2021-01-31 16:49
HiNo issue opening in other folder.Only in citrix files folder. Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Carlos Cordoba <notifications@github.com> Data: 31/01/21  17:19  (GMT+01:00) A: spyder-ide/spyder <spyder@noreply.github.com> Cc: paoloflorian <pflorian@alice.it>, Mention <mention@noreply.github.com> Oggetto: Re: [spyder-ide/spyder] Can't open .py file saved on citrix files folder (#14666) 
Hey @paoloflorian, thanks for reporting. This is a duplicate of issue #14660, so let's continue the discussion there.
One question for you to answer on that issue: does this problem happen for you if you open a file in D:\ or another regular disk partition?
