### ISSUE TITLE
New features request: Automatically search and install plugins

### ISSUE THREAD

**Issue by taoari** [spyder-ide/spyder#16070] opened 2021-07-24 07:15 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I found that the plugins system of Spyder is great, you simply need to copy the files to `~/.spyder-py3/plugins` folders. However, this process must be done manually. Is it possible to provide a Plugins Panel that you can search and install spyder plugins automatically?

What I mean is something like this: you can simply search a name, find a suitable plugin and click to install the plugin. The following is a screenshot of Sublime Text 3 installing a package Panel for reference.

![image](https://user-images.githubusercontent.com/3815006/126860651-e6a3d56e-d92f-4461-a026-788901d82828.png)

## Versions

* Spyder version: 5.0.5
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2021-07-24 18:33
Hey @taoari, thanks for reporting. This was requested already in https://github.com/spyder-ide/ux-improvements/issues/54 and we'll try to implement it next year.

If a plugin is self-contained, installing it is very simple (as you already discovered). However, since Spyder is written in Python, you can use any Python package for a plugin. In that case, things become more complex and we'd need to implement a package manager for our plugins.

This is an short explanation to let you know why it'll take us some time to address this.

**Comment by ccordoba12** [comment] 2021-07-24 18:34
I'm going to close this as a duplicate of issue https://github.com/spyder-ide/ux-improvements/issues/54 to have everything in one place.

**Closed by ccordoba12** 2021-07-24 18:34 UTC
