### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by tkorach** [spyder-ide/spyder#9703] opened 2019-06-27 20:20 UTC
### What steps will reproduce the problem?

Code completion barely working and very slow despite using a local kernel (and pandas, a common library)

### Traceback
```python-traceback
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls\python_ls.py", line 292, in m_text_document__signature_help
    return self.signature_help(textDocument['uri'], position)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls\python_ls.py", line 233, in signature_help
    return self._hook('pyls_signature_help', doc_uri, position=position)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls\python_ls.py", line 122, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\_tracing.py", line 80, in __call__
    return outcome.get_result()
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\callers.py", line 52, in from_call
    result = func()
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\_tracing.py", line 78, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\pyls\plugins\signature.py", line 17, in pyls_signature_help
    signatures = document.jedi_script(position).call_signatures()
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\jedi\api\__init__.py", line 329, in call_signatures
    helpers.get_call_signature_details(self._module_node, self._pos)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\jedi\api\helpers.py", line 225, in get_call_signature_details
    result = _get_call_signature_details_from_error_node(n, position)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\jedi\api\helpers.py", line 198, in _get_call_signature_details_from_error_node
    *_get_index_and_key(children, position)
  File "C:\Users\tkora\Anaconda3\envs\s4\lib\site-packages\jedi\api\helpers.py", line 180, in _get_index_and_key
    key_str = nodes_before[-2].value
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.0 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  2.2.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-28 10:47
Thanks for reporting. This is a duplicate of issue #9588.

**Closed by ccordoba12** 2019-06-28 10:47 UTC
