### ISSUE TITLE
Can't select lines in Editor when using wrap mode

### ISSUE THREAD

**Issue by William96911** [spyder-ide/spyder#7387] opened 2018-07-05 08:36 UTC
### Issue Report Checklist

* [✓] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [✓] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [✓] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [✓] Tried basic troubleshooting (if a bug/error)
    * [✓] Restarted Spyder
    * [✓] Reset preferences with ``spyder --reset``
    * [✓] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [✓] Tried the other applicable steps from the Troubleshooting Guide
* [✓] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When editor select wraps lines, if one or more sentense is too long that beyond window size(I use half window), then can't select current line correctly below wrapped too long sentences

### What steps reproduce the problem?

1. Preferences - Editor - Display - select Wrap lines
2. In Editor window, input one or more sentence beyond window size(I use half window)
3. Can't select sentence correctly below long sentences

### What is the expected output? What do you see instead?
Can select sentence correctly when select Wrap line below long sentence

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.6 32bits
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 x64

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2018-07-05 13:08
> Can't select sentence correctly below long sentences

What does this mean? This is too vague, so please post screenshot of what you mean.

**Comment by William96911** [comment] 2018-07-05 23:20
Because screenshot software can't capture mouse pointer, so I taking pictures:
As you can see, line 11 and line 13 are too long and they are wrapped. In first picture, I select line 13,  the cursor select line 12
![2018-07-06_1](https://user-images.githubusercontent.com/24632097/42352281-f6c21a62-80eb-11e8-84be-ba8996d59f02.jpg)
In second picture, I select line 15,  the cursor select line 13
![2018-07-06_2](https://user-images.githubusercontent.com/24632097/42352313-4215e764-80ec-11e8-82f7-bf5ff2b4c63f.jpg)
In third picture, I select line 22,  the cursor select line 20
![2018-07-06_3](https://user-images.githubusercontent.com/24632097/42352324-65605614-80ec-11e8-9dc5-91719f8a50bb.jpg)

**Comment by ccordoba12** [comment] 2018-07-06 01:46
Ok, thanks for the pictures. I understand what's happening now.

We'll try to address this problem in a future release.

**Comment by William96911** [comment] 2018-07-06 01:48
Thank you!

**Comment by goanpeca** [comment] 2019-11-27 23:25
I cannot reproduce this. Closing.

![lines](https://user-images.githubusercontent.com/3627835/69765762-4701c200-1143-11ea-8b21-ad387cb443a2.gif)

**Closed by goanpeca** 2019-11-27 23:25 UTC
Labels: component:Editor, type:Bug
