### ISSUE TITLE
Text being cut in the `About` dialog

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#22180] opened 2024-06-19 00:41 UTC
## Problem Description

Some text gets cut in the About dialog (at least on Windows on my setup while checking the Spyder 6 beta2 rc0 installer - https://github.com/spyder-ide/spyder/actions/runs/9573557891):

![image](https://github.com/spyder-ide/spyder/assets/16781833/f4f94001-cb7d-44fa-98e7-5bc7542d0ec3)

### What steps reproduce the problem?

1. Launch Spyder 
2. Open the About dialog (`Help > About Spyder`)

### What is the expected output? What do you see instead?

Be able to see the full content of the About dialog

## Versions

* Spyder version: 6.0.0b2.dev174  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment] 2024-07-14 17:49
@dalthviz, I'm unable to reproduce this problem on my VM:

![imagen](https://github.com/user-attachments/assets/dc4e17c8-970f-4a2f-a27d-7f262da4954e)

As you can see, I added more empty lines to the label on that tab. However, since it's placed inside a scroll area, a scrollbar should be shown when the contents don't fit into the available space.

I don't understand why the scrollbar is not shown in your case, but I can't test our installer because my VM is too old (Windows 7). However, this shouldn't be a problem for stable releases (in your case, I think what caused the content to not fit is the very long Spyder version on the left).

So, could you test what's shown with the beta3 installer? Also, please check all tabs, not just the first one. Thanks!

**Comment by dalthviz** [comment] 2024-07-15 23:15
Checked and this happens from me when I launch from the latest beta available (beta2) and also from source/using `python bootstrap.py`:

* From the Spyder 6.0.0b2 installer:
 
![about_dialog_beta](https://github.com/user-attachments/assets/12632be0-3047-4bbb-ad64-7c2e215316e5)

* From `master` (4f7976e):

![about_dialog](https://github.com/user-attachments/assets/a77f4c00-f036-4e3c-8e41-5434e52f97bc)

**Comment by ccordoba12** [comment] 2024-07-16 00:19
Ok, then I'm going to assign this issue to you. A simple solution could be to increase the width of dialog a bit here:

https://github.com/spyder-ide/spyder/blob/72d0904859def2637d126d2bedc4fb7419e020d0/spyder/plugins/application/widgets/about.py#L288

That way the `PyQt5 5.15.9` line wouldn't be broke into two, which should show the social media links without problems.

**Closed** 2024-07-24 22:34 UTC
Labels: type:Bug, User Interface (UI), component:Main Window
