### ISSUE TITLE
"An error ocurred while starting the kernel" Error 

### ISSUE THREAD

**Issue by denizozdemir** [spyder-ide/spyder#22347] opened 2024-08-14 09:12 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I've installed python 3.12.5 and Sypder 5.5.5.  I've changed python interpreter of Sypder (defult python version was 3.8 and now it it 3.12). When I perfomed that change there is a error message in console. I've installed spyder-kernels 2.5.2 as suggested. However, still same error appers in the console. I've opened and closed sypder. What should i do?

### What steps reproduce the problem?

1. Changing python interpreter
2. Nessary spyder-kernel version is installed
3. Error does not solved

### What is the expected output? What do you see instead?
I was expecting this error go away but it does not.

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error ocurred while starting the kernel
The Python environment or installation whose interpreter is located at
    C:\Program Files\Python312\python.exe
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.5.0 and < 2.6.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment first (if necessary) and then running in a system terminal:
    conda install spyder-kernels=2.5
or
    pip install spyder-kernels==2.5.*

```

## Versions

* Spyder version: 5.5.5
* Python version: 3.12.5
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.4 (OK)
jsonschema >=3.2.0            :  4.22.0 (OK)
keyring >=17.0.0              :  25.2.1 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.0 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.8 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.3 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0        :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.2.0 (OK)
setuptools >=49.6.0           :  70.0.0 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.2,<2.6.0 :  2.5.2 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.1 (OK)
zmq >=24.0.0                  :  26.0.3 (OK)

# Optional:
cython >=0.21                 :  3.0.10 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12.1 (OK)

**Comment by dalthviz** [comment] 2024-08-23 22:47
Hi @denizozdemir thank you for the feedback! Did you install `spyder-kernels` for you global Python installation without using an env right? If that is the case, maybe this is related with https://github.com/spyder-ide/spyder/issues/20968

Let us know if the info above helps!

**Comment by ccordoba12** [comment] 2024-10-24 15:55
Closing as a duplicate of #20698.

**Closed by ccordoba12** 2024-10-24 15:55 UTC
Labels: component:IPython Console, status:Awaiting Followup
