### ISSUE TITLE
Dictionary Order not maintained in Variable Explorer

### ISSUE THREAD

**Issue by PhilipYip1988** [spyder-ide/spyder#20669] opened 2023-03-10 09:15 UTC
### What steps reproduce the problem?

1.  Example Code:

```
mapping = {'red': '#FF0000', 
           'green': '#00B050', 
           'blue': '#0070C0'}

for key in mapping:
    print(key)
```

2. In Python 3.6 and later, dictionaries are ordered (taking on some of the properties of the OrderedDict in the collections module). The dictionary order displays correctly in the variable explorer preview. 
3.  When expanded however, the dictionary is automatically displayed alphabetically by the key. There is no way to view it by the insertion order.  
4. This also happens with an OrderedDict. Example code:

```
from collections import OrderedDict
mapping2 = OrderedDict(mapping)
```

![dictionary](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/dictionary_spyder.png)

![ordered_dict](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/dictionary_spyder2.png)

### What is the expected output? What do you see instead?

The expanded view of the dictionary should display the insertion order red, green, blue opposed to the alphabetical order of the keys blue, green, red by default. The key can be selected to rearrange the data alphabetically by the key if desired. However there should perhaps also be an additional button at the top to reset the dictionary to insertion order.

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.9.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.1.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=3.0.0            :  3.6.3 (OK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)

```

**Comment by dalthviz** [comment] 2023-03-10 21:16
Hi @PhilipYip1988 thank you for the feedback! I was able to reproduce this and I think in general it makes sense to have a way to preserve/restore the dict keys insertion order. What do you think @spyder-ide/core-developers ?

**Comment by mrclary** [comment] 2023-03-11 03:00
Interesting...
I think that it makes sense to be able to restore the insertion order. However, I don't know how to make that compatible with the sortable columns except to disable sorting for the key column.

**Comment by CAM-Gerlach** [comment] 2023-03-11 05:30
What would be ideal, and the general UI pattern I'm seen in other applications where there's a key column that has some sort of "natural"/"default" order but can also be sorted lexicographically, is that the column is sorted by that order (i.e. insertion order) by default, clicking it once sorts lexicographically descending, clicking it twice sorts descending and clicking it a third time restores the default (i.e. insertion order) sort. However, I'm not sure how easy this would be to implement with the existing Qt widgets, without just adding an explicit index column for insertion order.

**Comment by ccordoba12** [comment] 2023-03-12 17:06
> I think that it makes sense to be able to restore the insertion order. However, I don't know how to make that compatible with the sortable columns except to disable sorting for the key column.

Good idea, and perhaps the simplest one we could implement.

> However, I'm not sure how easy this would be to implement with the existing Qt widgets, without just adding an explicit index column for insertion order.

Yeah, that could be really hard to do on Qt.

**Comment by ccordoba12** [comment] 2023-03-12 17:07
Hey guys, I'm going to close this issue as a duplicate of #9136 (yeah, reported a long time ago).

**Closed by ccordoba12** 2023-03-12 17:07 UTC
Labels: type:Enhancement, component:Variable Explorer, type:Discussion, status:Reproduced

**Comment by CAM-Gerlach** [comment] 2023-03-12 17:47
Closing with the correct close reason.

> Yeah, that could be really hard to do in Qt.

In that case, I would consider the mentioned fallback of adding an index column with the insertion order and sorting by that as default—not ideal, but better than regressing on existing functionality (sorting by keys).
