### ISSUE TITLE
IPython kernel dies when running a program

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2079] opened 2015-02-17 22:13 UTC
_From [hoza...@hotmail.dk](https://code.google.com/u/116362936282735392100/) on 2014-12-07T12:16:30Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2079_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [hoza...@hotmail.dk](https://code.google.com/u/116362936282735392100/) on 2014-12-07T09:20:05Z_

It's a program, running the first algorithm for deterministic subspace identification. It does run correctly for others but not for me.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-09T15:46:44Z_

Please upload the program so we can test it in our side.

**Labels:** Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [hoza...@hotmail.dk](https://code.google.com/u/116362936282735392100/) on 2014-12-27T15:07:55Z_

Hi,

Sorry for my late reply. I uploaded the python program and the file which has the data I used in the program. Thank you for helping.

**Attachment:** [Subspace-Identification.testhz.py scope_3.csv](http://code.google.com/p/spyderlib/issues/detail?id=2079#hc3)

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [astrola...@gmail.com](https://code.google.com/u/100656913232780312647/) on 2014-12-27T17:39:10Z_

I've seen the same problem coming back up from sleep mode, and while doing some plotting in Qt. I'll try to capture the console next time.

Spyder Version:  2.3.2
Python Version:  2.7.9
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK)

Larry

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [astrola...@gmail.com](https://code.google.com/u/100656913232780312647/) on 2014-12-28T09:04:34Z_

Addition to `#4`.

Nothing in the IPython console except the error message; nothing in the internal console.

This time I was able to recover by deleting the IPython console and starting a new one. Previously this has not worked.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T14:31:48Z_

Thanks for the program @-astrolad47. I'll see what I can do about it.

**Summary:** IPython kernel dies when running a program  \<span class="oldvalue"> (was: When I run my program on Ipython, I receive this message: It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.) \</span>  
  **Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment] 2015-02-17 22:13
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T20:07:16Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment] 2015-12-16 03:59
Closing because this seems a very specific use case that I don't have time to test and reproduce.

**Closed by ccordoba12** 2015-12-16 03:59 UTC
Labels: 1 star, Bug, Component: IPython Console
