### ISSUE TITLE
Spyder error scaled up to anaconda-navigator crash

### ISSUE THREAD

**Issue by rnrpereira** [spyder-ide/spyder#7140] opened 2018-05-16 21:17 UTC
SPYDER ERROR:

## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/spyder/plugins/__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 709, in toggle_view
    self.create_new_client(give_focus=False)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1027, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/qtconsole/kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/jupyter_client/threaded.py", line 209, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/jupyter_client/client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/jupyter_client/threaded.py", line 202, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/tornado/ioloop.py", line 844, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/tornado/ioloop.py", line 356, in initialize
    self.make_current()
  File "/home/administrador/anaconda3/envs/Python36/lib/python3.6/site-packages/tornado/ioloop.py", line 314, in make_current
    assert asyncio is None
AssertionError

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.5
* Qt Versions: 5.9.4, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.5 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```
ANACONDA-NAVIGATOR CRASH:

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

'user_agent'

Traceback

Traceback (most recent call last):
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2183, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/home/administrador/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 509, in set_conda_prefix
    self._user_agent = info['user_agent']
KeyError: 'user_agent'

**Comment by ccordoba12** [comment] 2018-05-16 21:41
Closing as a duplicate of #7139. Please don't open more bugs about the same (we can't help you about the error in Navigator).

**Closed by ccordoba12** 2018-05-16 21:41 UTC
