### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Edulongo7** [spyder-ide/spyder#7094] opened 2018-05-09 19:13 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\ccxt\async\base\exchange.py", line 114, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\aiohttp\client.py", line 779, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\aiohttp\client.py", line 404, in _request
    break
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

Traceback (most recent call last):
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\spyder\plugins\help.py", line 92, in validate
    valid = self.is_valid(qstr)
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\spyder\plugins\help.py", line 74, in is_valid
    return shell.is_defined(objtxt, force_import=True)
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\spyder\widgets\internalshell.py", line 467, in is_defined
    return self.interpreter.is_defined(objtxt, force_import)
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\spyder\interpreter.py", line 312, in is_defined
    namespace=self.locals)
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\spyder\utils\dochelpers.py", line 305, in isdefined
    module = __import__(base, globals(), namespace)
  File "C:\mktdata\teste.py", line 27, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Eduardo\Anaconda3update\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\mktdata\teste.py", line 23, in main
    async for (symbol, ticker) in poll(['BTC/BRL','BTC/BRL']):
  File "C:\mktdata\teste.py", line 17, in poll
    yield (symbol, await foxbit.fetch_ticker(symbol))
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\ccxt\async\foxbit.py", line 85, in fetch_ticker
    }, params))
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\ccxt\async\foxbit.py", line 179, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\ccxt\async\base\exchange.py", line 92, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\ccxt\async\base\exchange.py", line 129, in fetch
    self.raise_error(RequestTimeout, method, url, e, None)
  File "C:\Users\Eduardo\Anaconda3update\lib\site-packages\ccxt\base\exchange.py", line 274, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: foxbit GET https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC 

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  0.8.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-05-09 19:27
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-05-17 18:14
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-05-17 18:14 UTC
Labels: status:Awaiting Followup
