### ISSUE TITLE
Spyder takes long to change to a directory with lots of files.

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#10247] opened 2019-09-18 13:20 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

It tooks long to switch to a directory with lots of files via `os.chdir()`.

### What steps reproduce the problem?

1. Prepare a directory with 1000 files.
2. Switching to the test directory `os.chdir('d:/test')`

**1. Codes to prepare the test directory**:

```python
test_dir = 'd:/test'
for i in range(1000):
    with open(f'{test_dir}/测试文件_{i}.{i}', 'w', encoding='gb2312') as file:
        file.write('''Spyder 是一个很好用的 IDE。''')
```

**2. Codes to test**:

```python
# Run the following codes line by line in spyder editor
import os
os.chdir('d:/test')
```

### What is the expected output? What do you see instead?

It took too long to change a directory. In the `--debug` mode, there's 1000 messages like:

```
2019-09-18 20:59:31,019 [DEBUG] [spyder.utils.external.binaryornot.check] -> is_binary: 'D:\\test\\测试文件_999.999'
2019-09-18 20:59:31,019 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio1: 0.5925925925925926
2019-09-18 20:59:31,020 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio2: 0.4074074074074074
2019-09-18 20:59:31,020 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> is_likely_binary: False
2019-09-18 20:59:31,021 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 11
2019-09-18 20:59:31,022 [DEBUG] [chardet.charsetprober] -> utf-8 not active
2019-09-18 20:59:31,022 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese confidence = 0.01
2019-09-18 20:59:31,022 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese confidence = 0.01
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese confidence = 0.99
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean confidence = 0.01
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> CP949 Korean confidence = 0.01
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> Big5 Chinese confidence = 0.01
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> EUC-TW not active
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> windows-1251 Russian confidence = 0.0
2019-09-18 20:59:31,023 [DEBUG] [chardet.charsetprober] -> KOI8-R Russian confidence = 0.12125837740446603
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> ISO-8859-5 Russian confidence = 0.0
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> MacCyrillic Russian confidence = 0.01
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> IBM866 Russian confidence = 0.0
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> IBM855 Russian confidence = 0.0
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> ISO-8859-7 Greek confidence = 0.0
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> windows-1253 Greek confidence = 0.0
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> ISO-8859-5 Bulgairan confidence = 0.0
2019-09-18 20:59:31,024 [DEBUG] [chardet.charsetprober] -> windows-1251 Bulgarian confidence = 0.0
2019-09-18 20:59:31,026 [DEBUG] [chardet.charsetprober] -> TIS-620 Thai confidence = 0.16412897391123246
2019-09-18 20:59:31,027 [DEBUG] [chardet.charsetprober] -> ISO-8859-9 Turkish confidence = 0.14134213188104292
2019-09-18 20:59:31,027 [DEBUG] [chardet.charsetprober] -> windows-1255 Hebrew confidence = 0.0
2019-09-18 20:59:31,027 [DEBUG] [chardet.charsetprober] -> windows-1255 Hebrew confidence = 0.0
2019-09-18 20:59:31,027 [DEBUG] [chardet.charsetprober] -> windows-1255 Hebrew confidence = 0.0
2019-09-18 20:59:31,027 [DEBUG] [chardet.charsetprober] -> utf-8 not active
2019-09-18 20:59:31,027 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese confidence = 0.01
2019-09-18 20:59:31,028 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese confidence = 0.01
2019-09-18 20:59:31,028 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese confidence = 0.99
2019-09-18 20:59:31,028 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean confidence = 0.01
2019-09-18 20:59:31,028 [DEBUG] [chardet.charsetprober] -> CP949 Korean confidence = 0.01
2019-09-18 20:59:31,028 [DEBUG] [chardet.charsetprober] -> Big5 Chinese confidence = 0.01
2019-09-18 20:59:31,028 [DEBUG] [chardet.charsetprober] -> EUC-TW not active
2019-09-18 20:59:31,028 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> detected_encoding: {'encoding': 'GB2312', 'confidence': 0.99, 'language': 'Chinese'}
2019-09-18 20:59:31,029 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> success: decodable_as_unicode: True
2019-09-18 20:59:31,029 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> failure: decodable_as_unicode: True
```

## Versions

* Spyder version: 4.0.0.dev0 97fc318bc
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0.dev0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.1 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-09-18 20:27
This is a duplicate of issue #10081.

**Closed by ccordoba12** 2019-09-18 20:27 UTC
