### ISSUE TITLE
Kite autocompletion - Spyder internal problem

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#10960] opened 2019-12-07 18:18 UTC
### Steps to reproduce the problem

 1. `import matplotlib.pyplot as plt`
 2. `plt.plot()`
 3. Place cursor between `()`
 4. Press "Ctrl + Space"
 5. Select any option, press "Tab" (_note_: pressing "Enter" or clicking instead proceeds error-less)

No crash, just Issue reporter pops up and says `"Spyder has encountered an internal problem!"`

### Traceback
```python-traceback
File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 860, in insert_snippet
  leaf, snippet_root, ast, line, column)
File "D:\Anaconda\envs\s4_env\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 489, in _insert_snippet_at_node
  list(possible_snippet.placeholder) +
TypeError: 'TextNode' object is not iterable
```

#### Preferences -> Completion and linting

**Off**:  `Show completions on the fly` -- all else on / defaulted; Kite installed and running.

### Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-13 17:54
Thanks for reporting. This is a duplicate of #10971.

**Closed by ccordoba12** 2019-12-13 17:54 UTC
