### ISSUE TITLE
spyder error

### ISSUE THREAD

**Issue by liubotao920** [spyder-ide/spyder#6167] opened 2018-01-08 09:34 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\An

**Comment by ccordoba12** [comment] 2018-01-08 15:53
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2018-01-09 08:07
Thanks for reporting. Not sure exactly what's going on with this error, but very likely to be something specific to your machine. Please follow our [troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the **Basic First Aid** and then **Emergency CPR** sections, and more than likely your problem will be resolved. In case you are still having trouble, please respond with the requested items under the **Calling for Help** heading, and we'll see what we can do. Otherwise, if we don't hear from you after a week (7 days), this issue will be closed. Best of luck!

**Comment by CAM-Gerlach** [comment] 2018-01-16 02:28
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-01-16 02:28 UTC
Labels: status:AwaitingFollowup
