### ISSUE TITLE
Huge variable printing in a Python console freezes Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1154] opened 2015-02-17 17:19 UTC
_From [geg...@gmail.com](https://code.google.com/u/105115295234164435475/) on 2012-09-25T06:07:24Z_

Printing huge in size variable (500 MB RAM) causes the IDE to freeze. There are two ways of printing, using 'print' and typing variable name and pressing enter. 'pprint' command solves this problem, but I couldn't find the way to set it to default. https://groups.google.com/d/topic/spyderlib/V-Q9ETsTyi0/discussion

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1154_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:19
_From [kinnison...@gmail.com](https://code.google.com/u/104685941974947235171/) on 2013-02-20T09:25:13Z_

The console printing uses repr() I believe.  So you could try overloading that to use pprint instead as a workaround.

I think I have the same issue, though the IDE doesn't freeze right away for me.  It'll usually keep printing out the huge variable until I try to stop it with Ctrl+C.  And that's when it often freezes.  Is this consistent with what you have experienced?

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:19
_From [geg...@gmail.com](https://code.google.com/u/105115295234164435475/) on 2013-02-20T10:51:20Z_

On my own the whole OS GUI was almost frozen. I had rather clean Ubuntu installation, and through very huge lags I was able to somewhat open terminal or Alt+Ctrl+f{2-6} - virtual console and stop the python process.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:19
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:27:14Z_

**Summary:** Huge variable printing in a Python console freezes Spyder  \<span class="oldvalue"> (was: Huge variable printing freeze) \</span>  
  **Labels:** Cat-Console MS-v2.4

**Comment by ccordoba12** [comment] 2015-07-13 05:45
Closing as duplicate of #1431

**Closed by ccordoba12** 2015-07-13 05:45 UTC
Labels: 2–5 stars, bug, duplicate, Python-Console
