### ISSUE TITLE
Ipython terminal put exception traceback message in the next In [ ] line.

### ISSUE THREAD

**Issue by SlimeDoudoune** [spyder-ide/spyder#5021] opened 2017-08-21 19:55 UTC
## Description of your problem

**What steps will reproduce the problem?**

1.   Write into Ipython terminal some function name that is not defined (for example :  seize() )

**What is the expected output? What do you see instead?**

Here is the example and the following message that should appear : 

"In [36] : seize()
Traceback (most recent call last):

  File "<ipython-input-35-3b5d5c371295>", line 1, in <module>
    seize()

NameError: name 'seize' is not defined

In [37] : 
"
**What I see instead :** 
"
In [36] : seize()

In [37] : Traceback (most recent call last):

  File "<ipython-input-36-2409e32188a5>", line 1, in <module>
    seize()

NameError: name 'seize' is not defined
"
cursor stay after "not defined" (I can write on that line) and no new In [ ] line pop.

**Please provide any additional information below**

To make a new In [ ] line to pop I have to press several times the space bar and then enter and it happens.

I do not encounter this issue when  I simply write a noun (undefined) (traceback message is correctly written in the same In [ ] line as the input.
It may occurs for others inputs but I can't remember now.

## Versions and main components

* Spyder Version:  3.2.1 (but had the same problem with 3.2.0 )
* Python Version: 3.6.2.final.0
* Qt Version:  5.6.2
* PyQt Version:  5.6.0
* Operating system:  Win10 -64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-08-22 01:34
Thanks for reporting. This is a duplicate of #4504 and it'll be fixed in version 3.2.2 (to be released in a couple of weeks).

**Closed by ccordoba12** 2017-08-22 01:34 UTC
Labels: resolution:Duplicate
