### ISSUE TITLE
Variable explorer not ordering index / background color grayed-out

### ISSUE THREAD

**Issue by Rational-IM** [spyder-ide/spyder#13708] opened 2020-09-03 13:09 UTC
I noticed the following issues a couple of days ago:
1) Variable explorer doesn't sort the index if sorting done in any of its columns; there is also a miss-formating after sorting
2) The "background color" check-box is grayed-out

For issue #1, look at the DataFrame below (pre-sorting):
![image](https://user-images.githubusercontent.com/57544001/92117982-e2efe680-edc3-11ea-90e5-783021e31faf.png)

Now look at it when sorting by the last column (9/2/20) - see that the index column remained the same and there is some strange formatting happening (making it hard to navigate to the last column, sorting again etc):
![image](https://user-images.githubusercontent.com/57544001/92118626-b9838a80-edc4-11ea-9b06-6d3d169bb955.png)

Regarding issue #2, you can see on both pictures above that the "background color" button is grayed-out (so the whole DataFrame was a black background).

I've been using Spyder for a while now, so I'm not sure I missed something obvious from the latest updates. It doesn't appear to be an issue of an extremely large/complex DataFrame. Size here:

![image](https://user-images.githubusercontent.com/57544001/92118817-f9e30880-edc4-11ea-9784-732a206da489.png)

**Comment by rhkarls** [comment] 2020-09-03 13:39
I have the same sorting issue on 4.1.5, testing on a simple dataframe:

    df = pd.DataFrame(index=[1,2,3], data={'col1':[1,2,3],'col2':[10,20,30],'col3':[100,200,300]})

The sorting works for the columns, even sorting on index, but the index column does not update visually.
I don't see any formatting issue, but perhaps due to the simple format of the data and keys.

**Comment by ccordoba12** [comment] 2020-09-03 15:06
@rhkarls, thanks for reporting. This is a duplicate of issue #13544 and we'll try to fix it in a future release.

**Closed by ccordoba12** 2020-09-03 15:06 UTC

**Comment by Ceballosk** [comment] 2022-03-09 10:16
It is fixed? I have the same problem with the baggrund for Python 3.9
