### ISSUE TITLE
Spyder sometimes crashes randomly on certain user actions on Python 3

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#4886] opened 2017-08-03 09:10 UTC
## Description of your problem

Sometimes when selecting code in an open file using the mouse (hold down left mouse-button and drag mouse) or more rarely when pulling the horizontal scroll bar on the bottom, Spyder crashes with the message "Python Stopped Working".

I don't know any way to reproduce this as it happens randomly, only thing I notice is that it only seems to happen after working for a while, not immediatly. It doesn't happen daily either, sometimes not at all, sometimes several times a day.

**What steps will reproduce the problem?**

1. Work normally for a while, preferrably with large amounts of data
2. Have several files open, continue performing one of the specified actions
3. Maybe it crashes, maybe not

**Please provide any additional information below**

I know this is really vague, but that's the best I can provide without deeper inquiry.

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.2
* Qt Version: 5.8.0
* PyQt Version: 5.8.2
* Operating system: Windows 10
* IPython Version: 6.1.0

## Dependencies

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2017-08-03 19:51
Thanks for reporting, but without a way to reproduce your problem it's not possible for us to fix it.

**Comment by ccordoba12** [comment] 2017-08-04 02:30
> Work normally for a while, preferrably with large amounts of data

I think this could be the problem. How big are the files you're loading in Spyder?

**Comment by Khris777** [comment] 2017-08-04 07:05
I'm working with Big Data, so I'm using pandas and often read large csv files, where one file can be 1 or 2 GB big.
My machine has 128 GB RAM so I can easily handle pandas dataframes with many millions of rows.

**Comment by ccordoba12** [comment] 2017-08-04 15:18
But are you opening those CSV files in our Editor, besides loading them as Dataframes?

**Comment by Khris777** [comment] 2017-08-07 05:36
No, I only load them as dataframes.

**Comment by ccordoba12** [comment] 2017-08-08 14:06
Sorry, I don't know how we could help you. We don't have machines with that much RAM to test a use case like this.

**Comment by ccordoba12** [comment] 2017-08-22 00:12
Closing because we can't anything about it for now, sorry.

**Closed by ccordoba12** 2017-08-22 00:12 UTC

**Comment by Khris777** [comment] 2017-09-07 08:40
Here's some new info on this issue.

I am on Windows 10 in a company network. Authentification and several security-related settings are managed centrally.

I have Kaspersky Endpoint Security 10 and Baramundi Management Agent running.

The problem I have is actually system-wide one, usually a few times per day my whole system freezes for like 2-3 seconds, that is, the desktop becomes unresponsive and then completely reloads. Mouse movements are still possible. Since I'm mostly programming these freezes usually happen while I'm doing something in Spyder. 

Most times after such a system freeze Sypder will crash with the message that Python has stopped working. Occasionally Spyder survives and continues working. 

However the majority of freezes still happen while doing something like selecting code in Spyder, so it might be some kind of unfortunate interaction between Spyder and another program like Kaspersky.

**Comment by ccordoba12** [comment] 2017-09-07 15:42
> it might be some kind of unfortunate interaction between Spyder and another program like Kaspersky

Yep, it looks like that's the case. Maybe you could ask IT to add a white list rule to Kaspersky so it doesn't interfere with any Python process.
