### ISSUE TITLE
Problem removing variables from Variable Explorer

### ISSUE THREAD

**Issue by dsmaciel** [spyder-ide/spyder#13219] opened 2020-07-08 00:27 UTC
### What steps will reproduce the problem?

Restarted the Kernel, variable explorer did not clean up. Tried to manually erase the variables, Spyder crashed.

### Traceback
```python-traceback
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'RANDOM_SEED'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'SMALL_ENOUGHT'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'GAMMA'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'REWARD_DICTIONARY'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'DESTINY_STD_REWARD'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'ACTIONS_DICTIONARY'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'PARKING_LOT_POSITION_TAG'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'POD_ID'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'POD_STATUS_DICTIONARY'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'POD_MAX_BATTERY'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'DEFAULT_NUMBER_PODS'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'DEFAULT_PARKING_STALL'
Exception in comms call remove_value:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 236, in remove_value
    ns.pop(name)
KeyError: 'REQUEST_PROBABILITY'
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.3 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```

**Comment by ccordoba12** [comment] 2020-07-08 02:46
Closing as a duplicate of #13218. Please don't open duplicate issues for next time.

**Closed by ccordoba12** 2020-07-08 02:46 UTC
