### ISSUE TITLE
spyder kernels not installed

### ISSUE THREAD

**Issue by mayurpande** [spyder-ide/spyder#7412] opened 2018-07-09 09:01 UTC
### What steps will reproduce the problem?

opening spyder. I think its more down to my virtual env not having spyder-kernels installed. As it is already installed out of my virtual env.

### Traceback
```python-traceback
  File "/usr/local/lib/python3.5/dist-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.5.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.4.0-130-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.6 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-09 14:11
This is a duplicate of issue #7403 and it'll be fixed in our next version.

**Closed by ccordoba12** 2018-07-09 14:11 UTC
