### ISSUE TITLE
When black or autopep turned on, multiple copies of either the last  code block or the entire source generated in the text editor.

### ISSUE THREAD

**Issue by MGinsberg** [spyder-ide/spyder#15086] opened 2021-04-02 16:23 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment] 2021-04-02 17:03
Hi @MGinsberg, could you please provide the required information about your Spyder environment? From the title description, I would assume that this a duplicate of https://github.com/spyder-ide/spyder/issues/14653, which was fixed already.

**Closed by andfoy** 2021-04-02 17:03 UTC

**Comment by MGinsberg** [comment] 2021-04-02 18:15
Possibly a duplicate, but not fixed.  I have version 4.2.5.  I have no earthly idea how to test.  It happens every once in a while.  I have had either the last few lines or the entire file duplicated.
If you give me a hint how to proceed, I'm happy to do so.

    On Friday, April 2, 2021, 12:03:15 PM CDT, Edgar Andrés Margffoy Tuay ***@***.***> wrote:  
 
 


Closed #15086.

**Comment by MGinsberg** [comment] 2021-04-02 18:29
After playing around for a few minutes.  I can get the bad behavior several different ways.  Two empty lines at the beginning of the file still causes problems.
Leaving less than two empty lines before a class causes bad behavior too.
    On Friday, April 2, 2021, 1:15:04 PM CDT, Nerd ***@***.***> wrote:  
 
  Possibly a duplicate, but not fixed.  I have version 4.2.5.  I have no earthly idea how to test.  It happens every once in a while.  I have had either the last few lines or the entire file duplicated.
If you give me a hint how to proceed, I'm happy to do so.

    On Friday, April 2, 2021, 12:03:15 PM CDT, Edgar Andrés Margffoy Tuay ***@***.***> wrote:  
 
 


Closed #15086.

**Comment by ccordoba12** [comment] 2021-04-02 18:55
@MGinsberg, sorry but I can't reproduce this error. Please post an animated gif with the exact conditions that generate this problem so we can reproduce it on our side.
