### ISSUE TITLE
spyder初始化时失败

### ISSUE THREAD

**Issue by duyuzhen** [spyder-ide/spyder#6329] opened 2018-01-30 01:45 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "h:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "h:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "h:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "h:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "h:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "h:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "h:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "h:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "h:\ProgramData\Anaconda3\lib\subproces

**Comment by CAM-Gerlach** [comment] 2018-01-30 09:02
Thanks for reporting. While the error traceback is incomplete, it is an apparent duplicate of #6319 , which should be fixed in the next Spyder release. In the meantime, you can fix it yourself by either:

* Running ``spdyer --reset`` from the Anaconda prompt, or
* Going to ``Preferences`` > ``Python interpreter`` and selecting either the Default interpreter or a new, valid custom one.

**Closed by CAM-Gerlach** 2018-01-30 09:02 UTC

**Comment by ccordoba12** [comment] 2018-01-30 12:35
This is really a duplicate of issue #4958.

**Comment by CAM-Gerlach** [comment] 2018-01-30 16:32
@ccordoba12 Thanks. I presume I should now mark these as such in the future, when they inevitably re-appear, rather than #6319 as you were before?

**Comment by ccordoba12** [comment] 2018-01-30 18:27
Yes, please.
