### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by v2thegreat** [spyder-ide/spyder#6564] opened 2018-03-01 08:12 UTC
I tried to change the theme from the default to Monokai, and as I clicked OK, an error was raised, even if the theme changed perfectly. Did something happen in the background or is this just a bug?

**Comment by ccordoba12** [comment] 2018-03-01 13:45
Thanks for reporting. This is a duplicate of issue #6519.

**Closed by ccordoba12** 2018-03-01 13:45 UTC
