### ISSUE TITLE
Cannot open project

### ISSUE THREAD

**Issue by YvYh** [spyder-ide/spyder#16541] opened 2021-10-05 08:09 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Hello, I cannot open a project in Spyder.    

Each time when I click on "Projects" and then choose "Open project", I will get the "Issue reporter" dierectly.

**Comment by steff456** [comment] 2021-10-05 16:53
Hi @YvYh,

Can you let me know which version of Spyder are you using? Also, what method of installation did you use? And if you can post a screenshot or gif with the behavior here, it will help us to try to reproduce it.

**Comment by YvYh** [comment] 2021-10-06 08:39
> Hi @YvYh,
> 
> Can you let me know which version of Spyder are you using? Also, what method of installation did you use? And if you can post a screenshot or gif with the behavior here, it will help us to try to reproduce it.

Hello @steff456 ,

I'm in Spyer 4.1.4 which is installed by Anaconda. Actually there is no spacial action, just click on 'Project' and get the error. You can see what happen in this gif.
![2021-10-06 10h35_25](https://user-images.githubusercontent.com/22756011/136168954-49dd1b32-60c0-469d-a46e-736afb244234.gif)
.

**Comment by ccordoba12** [comment] 2023-03-05 19:11
Closing because this probably no longer applies to our latest version.

**Closed by ccordoba12** 2023-03-05 19:11 UTC
Labels: status:Awaiting Followup
