### ISSUE TITLE
Conflicts when install Spyder 5.0.0 in new environment

### ISSUE THREAD

**Issue by 93chanle** [spyder-ide/spyder#15147] opened 2021-04-06 21:34 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [] Restarted Spyder

    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Create new enviroment with ``conda create -n myenv python=3.8 spyder=5.0.0``
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.8
spyder=5.0.0 -> atomicwrites[version='>=1.2.0'] -> python[version='>=2.7|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.5|>=3|>=3.6']
spyder=5.0.0 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment] 2021-04-06 21:46
Hi @93chanle,

This is a duplicate of , were we noticed that the recipe for Spyder in the default channel of anaconda is broken. For now, please install Spyder using the conda-forge channel in a clean environment,

```
conda create -n spyder-cf python=3.8
conda activate spyder-cf
conda install spyder -c conda-forge
```

 We are working really hard to fix this issue as soon as we can.

Thanks for reporting!

**Closed** 2021-04-06 21:47 UTC

**Comment by Dan-Patterson** [comment] 2021-04-06 23:04
@steff456 Does this mean the package that was uploaded today (April 6th) is still causing issues?

**Comment by steff456** [comment] 2021-04-06 23:28
I'm afraid so, we are checking on it right now. We will close #15113 once the package is working.
