### ISSUE TITLE
Catch erros than change color scheme

### ISSUE THREAD

**Issue by MakarevichDmitry** [spyder-ide/spyder#6745] opened 2018-03-13 15:19 UTC
Steps:
* choose any *Scheme* in Preferences
* click *Apply* or *OK* button
* color scheme change successful but I catch errors.

```

  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
```

**Comment by ccordoba12** [comment] 2018-03-13 15:44
Thanks for the report. This is a duplicate of #6519 and it'll be fixed in our next version.

**Closed by ccordoba12** 2018-03-13 15:44 UTC
