### ISSUE TITLE
fqrafqaqQFAadasdas

### ISSUE THREAD

**Issue by Gulugulu0045** [spyder-ide/spyder#13006] opened 2020-06-12 03:33 UTC
### What steps will reproduce the problem?

asdasdasdasdsadfasfasfasdfsdadsadcxzczxczxczxczxcxzc

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2741, in edit_preferences
    widget.initialize()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 78, in initialize
    self.setup_page()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 1244, in setup_page
    self.scheme_editor_dialog.add_color_scheme_stack(name, custom=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 1571, in add_color_scheme_stack
    value = self.parent.get_option(option)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 57, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 375, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'custom-0/normal' in section: 'color_schemes'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by juanis2112** [comment] 2020-06-12 18:08
HI @Gulugulu0045, this is a duplicate of #5790. Try to fix it with the instructions from the last comment. 

However, I would suggest updating to the latest spyder version. In your anaconda prompt type:
```
conda update anaconda
conda install spyder=4.1.3
```

**Closed by juanis2112** 2020-06-12 18:08 UTC
