### ISSUE TITLE
black stopped working. Spyder 5.2.2 (Anaconda)

### ISSUE THREAD

**Issue by Ubaldo79** [spyder-ide/spyder#19377] opened 2022-09-09 15:20 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Black does not seem to work in Spyder 5.2.2. whereas autopep8 does.
However, black works if I run it from the Powershell. 

### What steps reproduce the problem?

Try this sample code and try to format with black (`ctrl+alt+i` or save  if you have the option `autoformat on save` enabled). 

```
import numpy as np

def ThisIsGoingToBeALongFunction(first:float, second:float,third:float,fourth:float):
    
    
    return first+second+third+fourth





print(ThisIsGoingToBeALongFunction(1,1,1,1))
```

### What is the expected output? What do you see instead?
I expect the code to be formatted according to black. 

## Versions

* Spyder version: 5.2.2 None
* Python version: 3.9.12 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment] 2022-09-09 15:51
Hi @Ubaldo79 thank you for the feedback! Seems like this could be a duplicate of https://github.com/spyder-ide/spyder/issues/16552

Seems like this was fixed on Spyder 5.3.x, however, from the Anaconda default channel the latest release available is 5.2.2 and there is not much we can do about that from the Spyder side.

I would suggest to either create a new env to install Spyder in it using the conda-forge channel (where Spyder 5.3.3 is available), try installing our standalone installers available at the release page: https://github.com/spyder-ide/spyder/releases/latest or wait for the Anaconda default channel to upload Spyder 5.3.3 there.

Let us know if the info above helps!

**Comment by Ubaldo79** [comment] 2022-09-09 16:05
Thanks for the very quick reply! 
I will try. Given that I have many packages installed, perhaps I should clone my environment? 

```
conda create --name spyder53x --clone myenv
conda install spyder=5.3.3
```

Is it correct?

**Comment by dalthviz** [comment] 2022-09-09 16:28
In fact a good question, understanding how channels and environments work is not trivial at all I would say :)

My initial suggestion will be to use something like the following for a new clean environment to just use conda-forge packages (however then you will need to install the packages you are using in this new env):

    conda create --name spyder-cf --channel conda-forge spyder

With that command you will create a new env with name `spyder-cf` using the conda-forge channel and installing the latest Spyder release available (5.3.3). We usually suggest this since mixing channels sometimes can end up in things not working properly but, since you want to try to clone your env to try to keep the packages you installed availale, then the only missing thing for your proposed commands is to add the flag for the conda-forge channel when installing Spyder so:

     conda create --name spyder533 --clone myenv
     conda install --channel conda-forge spyder=5.3.3

Let us know if the info above helps!

**Comment by Ubaldo79** [comment] 2022-09-09 17:42
Done, but it went a disaster.
Firstly, I tried to clone the environment  and I get many of these warnings:

```
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/win-64::jupyterlab-3.4.4-py39haa95532_0, defaults/win-64::_ipyw_jlab_nb_ext_conf-0.1.0-py39haa95532_0
  path: 'scripts/jupyter-labhub-script.py'
```
 I decided to go on, and I tried to install Spyder and I got a lot of incompatibilities, for example this:

```
Package pyct-core conflicts for:
defaults/win-64::datashader==0.14.1=py39haa95532_0 -> pyct[version='>=0.4.5'] -> pyct-core[version='0.4.5.*|0.4.6.*']
defaults/win-64::panel==0.13.1=py39haa95532_0 -> pyct[version='>=0.4.4'] -> pyct-core[version='0.4.5.*|0.4.6.*']
defaults/win-64::colorcet==3.0.0=py39haa95532_0 -> pyct[version='>=0.4.4'] -> pyct-core[version='0.4.5.*|0.4.6.*']
```
 
and everything ended with this:

```
 - feature:/win-64::__win==0=0
  - feature:|@/win-64::__win==0=0
  - defaults/noarch::ipywidgets==7.6.5=pyhd3eb1b0_1 -> ipykernel[version='>=4.5.1'] -> __win
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0 -> ipykernel -> __linux
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0 -> ipykernel -> __osx
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0 -> ipykernel -> __win
  - defaults/win-64::holoviews==1.15.0=py39haa95532_0 -> ipython[version='>=5.4.0'] -> __win
  - defaults/win-64::jupyter==1.0.0=py39haa95532_8 -> ipykernel -> __win
  - defaults/win-64::jupyterlab==3.4.4=py39haa95532_0 -> ipython -> __win
  - defaults/win-64::notebook==6.4.12=py39haa95532_0 -> ipykernel -> __win
  - defaults/win-64::urllib3==1.26.11=py39haa95532_0 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __unix
  - defaults/win-64::urllib3==1.26.11=py39haa95532_0 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __win
  - ipykernel==6.9.1 -> ipython[version='>=7.23.1'] -> __win
  - qtconsole==5.2.2 -> ipykernel[version='>=4.1'] -> __win
  - spyder-kernels==2.2.1 -> ipykernel[version='>=6.6.1'] -> __win

Your installed version is: 0
```

I will try if everything is still up and running tomorrow, but in the meantime, shall I be worried that my Anaconda installation has gone?

**Comment by dalthviz** [comment] 2022-09-09 18:05
Well, did you activate your cloned env before running the command to install Spyder? If that is the case then the problem is isolated to the `spyder533` env you created. However, I think that probably you runned from your base environment instead of activating the create clone env before with something like `conda activate spyder533` then there is a high chance of your Anaconda installation go wrong (I forgot to add that command, sorry about that :/).

However, before trying to reinstall Anaconda if you see it is failing, you could try to check the `revisions` and try to 'rollback' your base env to a previous revision (for more details on that maybe this post could be helpful): https://stackoverflow.com/a/54172505/15954282

**Comment by Ubaldo79** [comment] 2022-09-09 20:08
I  am fairly sure that I activated the new environment but regardless, it was a clone. 

I think I can go back to the base env. 
I will check tomorrow.
Either way, no worries, things happen:)

**Comment by Ubaldo79** [comment] 2022-09-10 10:36
Checked!
It seems that I was able to reverse to the `base env` and everything is still working. 
I think the problems originated during the cloning (so nothing to do with Spyder), when I got this error:

```
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/win-64::jupyterlab-3.4.4-py39haa95532_0, defaults/win-64::_ipyw_jlab_nb_ext_conf-0.1.0-py39haa95532_0
  path: 'scripts/jupyter-labhub-script.py'
```

**Comment by Ubaldo79** [comment] 2022-09-11 20:26
At the end, given the many troubles of not having created a new virtual environment at the very beginning when I installed Anaconda, the fastest was to uninstall/reinstall Anaconda, create a new environment just after the installation, change the default channels (I placed conda-forge as the first option) and installed Spyder 5.3.3 along with many other packages that I needed. 
Everything seems to work now! :)

**Closed** 2022-09-12 16:19 UTC
Labels: resolution:Duplicate, resolution:Completed, status:Awaiting Followup
