### ISSUE TITLE
Kernel is not restarting

### ISSUE THREAD

**Issue by dosti88** [spyder-ide/spyder#16781] opened 2021-11-09 13:05 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by brummel-promed** [comment] 2021-11-09 17:00
I'm having the same issue. I tried downgrading matplotlib since it was mentioned in a previous report, but downgrading from matplotlib 3.4.3 to 3.3.4 did not resolve the issue. I ran the command line test and the kernel appears to work outside of spyder as observed in the other post.

Downgrading spyder to my previous 5.0.3 resolved the kernel issue, but caused LSP to fail, which was working before I upgraded spyder. I'm stuck choosing between a broken kernel or broken LSP.

**Comment by steff456** [comment] 2021-11-09 17:20
Hi @dosti88 and @brummel-promed, can you please explain to me the issue you are experiencing?

**Comment by brummel-promed** [comment] 2021-11-09 17:42
> 
> 
> Hi @dosti88 and @brummel-promed, can you please explain to me the issue you are experiencing? Also, can you let me know how did you installed Spyder?

When starting spyder, the console is stuck on "Connecting to Kernel..."

I installed spyder in the anaconda prompt using : "conda update anaconda" and "conda install spyder=5.1.5". I'm running windows 10 64 bit os. 

![image](https://user-images.githubusercontent.com/64868757/140976127-7abcb4d0-257c-44d7-9854-2e0bb4b3cbfb.png)

**Comment by ccordoba12** [comment] 2021-11-09 18:15
This is a duplicate of issue #16765. Please continue the discussion there.

**Closed by ccordoba12** 2021-11-09 18:15 UTC
Labels: status:Awaiting Followup
