### ISSUE TITLE
od.PLUGIN_CLASS(self)
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by ashura1** [spyder-ide/spyder#11856] opened 2020-03-19 01:04 UTC
### What steps will reproduce the problem?

upgrading spyder 3 to 4 windows 10. Python 3.8...

### Traceback
```python-traceback
  File "c:\users\lauj3\docume~1\python~2\env\lib\site-packages\spyder\app\mainwindow.py", line 985, in setup
    plugin = mod.PLUGIN_CLASS(self)
TypeError: 'bool' object is not callable
```

## Versions

* Spyder version: 4.1.0 
* Python version: 3.8.0
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.10.1 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.2.2 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.17.4 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.3.3 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-03-19 02:46
Duplicate of #11849

**Comment by ccordoba12** [comment] 2020-03-19 02:47
It seems to be a problem with Python 3.8 only. We're trying to find the cause right now.

**Closed by ccordoba12** 2020-03-19 02:46 UTC
