### ISSUE TITLE
Menubar doesn't work immediately when installing from git

### ISSUE THREAD

**Issue by astrofrog** [spyder-ide/spyder#3329] opened 2016-07-28 17:26 UTC
[I should preface this by saying that it is not a spyder bug, but a problem that both spyder and glueviz have and need to find a solution for, so I am opening this in the hope that you have ideas on how to fix it properly]

Steps to reproduce the issue on MacOS X:
- `conda create -n spyder-dev -c spyder-ide spyder`
- `conda remove spyder --force`
- Install developer version of spyder
- Open spyder

At this point, the menubar (File, Edit, etc.) is not responsive, and one needs to switch to a different application and then back for it to work.

This is an issue I've brought up with the conda developers [here](https://github.com/ContinuumIO/anaconda-issues/issues/446) but with no satisfactory conclusion. This problem can actually be demonstrated with a simple python script:

``` python
from PyQt4.QtGui import QApplication, QMainWindow, QMenu

app = QApplication([''])
main = QMainWindow()
mbar = main.menuBar()
menu = QMenu(mbar)
menu.setTitle("&File")
mbar.addMenu(menu)
main.show()
main.raise_()
app.exec_()
```

which can then be run with:

```
python script.py
```

Note that one way to get it to work is to run the script with:

```
python.app script.py
```

The reason this is not an issue with the stable releases of spyder is that the interpreter for the spyder script is set correctly to be `python.app` in those cases:

```
#!/bin/bash /Users/tom/miniconda3/envs/spyder-dev-3/bin/python.app
```

but when installing from git, the interpreter is then set to:

```
#!/Users/tom/miniconda3/envs/dev35/bin/python
```

I was curious whether you are able to reproduce this, and if so whether you have ideas for a solution?

cc @goanpeca

**Comment by ccordoba12** [comment] 2016-08-22 05:58
It seems this was caused because I was using an old version of conda-build to create our beta packages. I tried with the latest conda-build (1.21.14) and `python.app` is added correctly to the spyder script shebang :-)

**Comment by astrofrog** [comment] 2016-08-22 06:48
@ccordoba12 - just to be clear, this issue was not when installing conda package, but when installing from git directly using ``python setup.py install``. Are you not able to reproduce that issue?

**Comment by ccordoba12** [comment] 2016-08-22 13:29
I thought you were talking about our conda packages :-) Yes, I can reproduce this problem and to solve it we need to use  `pythonw` instead of `python` in our scripts.

**Comment by ccordoba12** [comment] 2016-08-22 13:45
However, I think this is a minor problem because most of the core devs use this command to run Spyder from git:

    python bootstrap.py

issued from the root of our repo. And in Mac this command needs to be changed to

    pythonw bootstrap.py

**Comment by ccordoba12** [comment] 2019-07-09 09:18
Closing because this no longer applies.

**Closed by ccordoba12** 2019-07-09 09:18 UTC
Labels: OS:MacOS, type:Bug
