### ISSUE TITLE
Error when getting the namespace view from the kernel

### ISSUE THREAD

**Issue by mitchell5** [spyder-ide/spyder#4855] opened 2017-07-29 14:48 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

```python-traceback
  File "/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 311, in handle_exec_method
    view = ast.literal_eval(data['text/plain'])
  File "/anaconda/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/anaconda/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x12f124400>
```

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-07-29 17:12
What were you evaluating when you get this error?

**Comment by ccordoba12** [comment] 2017-07-29 17:22
Note to self: take a look at

https://stackoverflow.com/questions/14611352/malformed-string-valueerror-ast-literal-eval-with-string-representation-of-tup

**Comment by mitchell5** [comment] 2017-07-29 17:33
Hi,
Today I made some package downloads and updates:

conda install -c anaconda nltk

conda install -c conda-forge textblob 

conda install -c conda-forge spacy 

conda install -c anaconda gensim


After that I am getting these error messages as I am trying to parse RDF/XML files like:

import rdflib
from rdflib import Graph

fileid = "http%253A%252F%252Fboards.ie%252Fvbulletin%252Fsioc.php%253Fsioc_type%253Dthread%2526sioc_id%253D9"

## Parsing the file
g = Graph()
g.parse("boards.ie SIOC Datasets/1998/threads/" + fileid,format = "xml")
 
# tokenizing the message content 
import pprint
for stmt in g:
    pprint.pprint(stmt)

Also my Variable Explorer does not show any variables.

Thank you
Deniz

**Comment by ccordoba12** [comment] 2017-07-29 17:47
Thanks for the reproducible code. We'll take a look at this as soon as possible.

> Also my Variable Explorer does not show any variables.

That's caused by the error you reported.

**Comment by ccordoba12** [comment] 2017-07-29 17:47
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment] 2017-07-29 22:21
Hi @mitchell5 I tried the updates and the code you provided but it doesn´t run (maybe the `parse` part and the `fileid` are not correct) it says it can't find the source.

However, running something like

```python
from rdflib import Graph 
## Parsing the file 
g = Graph() 
g.parse("http://www.w3.org/2000/10/swap/test/meet/blue.rdf",format = "xml")
# tokenizing the message content 
import pprint 
for stmt in g:
    pprint.pprint(stmt)
```

works for me, and the last tuple (saved in the `stmt` var) is shown in the variable explorer:

![imagen](https://user-images.githubusercontent.com/16781833/28748582-010349ba-7481-11e7-8d3c-09ba4e0cf64e.png)

Could you try again with the code above and see if the error still happen, maybe could be something in the source are you trying to parse? all the info will be greatly appreciated :)

**Comment by mitchell5** [comment] 2017-07-30 13:03
Hi Daniel,
Thank you for your interest in the problem. I am still getting similar error messages although I get the evaluation right after I ran my code. 

The error I get now:

 File "/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
handler(msg)
File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 214, in _handle_execute_reply
self.handle_exec_method(msg)
File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 311, in handle_exec_method
view = ast.literal_eval(data['text/plain'])
File "/anaconda/lib/python3.6/ast.py", line 85, in literal_eval
return _convert(node_or_string)
File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
in zip(node.keys, node.values))
File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
return dict((_convert(k), _convert(v)) for k, v
File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
in zip(node.keys, node.values))
File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
return dict((_convert(k), _convert(v)) for k, v
File "/anaconda/lib/python3.6/ast.py", line 84, in _convert
raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x1469c9518>

**Comment by ccordoba12** [comment] 2017-07-30 15:02
@mitchell5, please provide a working example if you want us to fix this. For example

    fileid = "http%253A%252F%252Fboards.ie%252Fvbulletin%252Fsioc.php%253Fsioc_type%253Dthread%2526sioc_id%253D9"

is not a valid URL, so the rest of your code fails.

**Comment by mitchell5** [comment] 2017-07-30 15:46
Hi,
The files are on my local. But it does not matter what code I ran, I ran into the same errors. Recently, the program just shut itself.

Thanks in advance for the help,

  File "/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
handler(msg)
File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 214, in _handle_execute_reply
self.handle_exec_method(msg)
File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 311, in handle_exec_method
view = ast.literal_eval(data['text/plain'])
File "/anaconda/lib/python3.6/ast.py", line 85, in literal_eval
return _convert(node_or_string)
File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
in zip(node.keys, node.values))
File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
return dict((_convert(k), _convert(v)) for k, v
File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
in zip(node.keys, node.values))
File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
return dict((_convert(k), _convert(v)) for k, v
File "/anaconda/lib/python3.6/ast.py", line 84, in _convert
raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x13151af60>

**Comment by ccordoba12** [comment] 2017-07-30 16:08
So does is this error appear for you even if you run `1+1` in a console?

**Comment by mitchell5** [comment] 2017-07-30 16:09
Yes, it does

**Comment by ccordoba12** [comment] 2017-07-30 16:14
And are using a different Python interpreter in

    Preferences > Python interpreter

?

**Comment by mitchell5** [comment] 2017-07-30 16:17
I am using the default one ?

**Comment by ccordoba12** [comment] 2017-07-30 16:22
Then, please run

    spyder --reset

in a terminal and try again.

**Comment by mitchell5** [comment] 2017-07-30 16:35
Thank you, it seems like it solved the problem :)

**Comment by ccordoba12** [comment] 2017-07-30 16:37
Great! Thanks for letting us know about it.

**Comment by mitchell5** [comment] 2017-07-30 20:33
Hi,
Sorry for bothering again, but I get the same problem even when I run 1+1. I tried to reset spyder(spyder --reset) but it didn’t solve the issue this time.

  File "/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
handler(msg)
File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 214, in _handle_execute_reply
self.handle_exec_method(msg)
File "/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 311, in handle_exec_method
view = ast.literal_eval(data['text/plain'])
File "/anaconda/lib/python3.6/ast.py", line 85, in literal_eval
return _convert(node_or_string)
File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
in zip(node.keys, node.values))
File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
return dict((_convert(k), _convert(v)) for k, v
File "/anaconda/lib/python3.6/ast.py", line 66, in _convert
in zip(node.keys, node.values))
File "/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
return dict((_convert(k), _convert(v)) for k, v
File "/anaconda/lib/python3.6/ast.py", line 84, in _convert
raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x12bb9eeb8>

**Comment by dalthviz** [comment] 2017-07-30 22:46
Hi @mitchell5 , maybe you could try to create another env? (you can do it with something like `conda create -n new_env anaconda`) and see if in the Spyder of that env the error persists? Also, did you install any library with pip? I think this is some kind of installation issue.

**Comment by mitchell5** [comment] 2017-07-31 09:14
Hi,
Yes, before I installed anaconda,  my system had python 2 and I installed python 3 and some libraries with pip3. I was using python with IDLE until I installed anaconda environment. I tried to create new environment but nothing has changed. Sorry for taking so much time. What would you suggest for me to do in this situation?

Thanks in advance

**Comment by ccordoba12** [comment] 2017-07-31 23:00
@mitchell5, I really don't understand where this error is coming from. If you want to help us to solve it, please follow these steps:

1. Put a line with `print([data['text/plain']])` before line `311` in `/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py`.
2. Restart Spyder.
3. Go to the menu `View > Panes > Internal console` and copy the text printed there after you run `1+1` in a console.
4. Post the result here.

With that info we will be able to understand why the console is not returning the result Spyder expects.

**Comment by ccordoba12** [comment] 2017-08-04 02:45
@dalthviz, giving that this is a very critical error (because it makes the IPython console unusable), I think we should catch all errors when trying to use `ast.literal_eval` in `handle_exec_method` (specifically in `get_namespace_view` and `get_var_properties`) and raise a new error that includes the values of `view` and `properties`.

I think something like this should work:

```python
if 'get_namespace_view' in method:
    if data is not None and 'text/plain' in data:
        try:
            view = ast.literal_eval(data['text/plain'])
        except Exception as error:
            error = to_text_string(error)
            view = to_text_string(data['text/plain'])
            text = "An error occurred while getting a "
                   "representation of your namespace. "
                   "The error was {0} and the obtained "
                   "value was {1}".format(error, view)
            raise ValueError(text)
    else:
        view = None
    self.sig_namespace_view.emit(view)
```

This way we will be able to better understand what the kernel is sending to Spyder.

However, the problem with this is we would also need the code a user is running in the console to make sense of the namespace representation we get in the error.

Let's wait to see if more errors like this one are reported in the future before implementing this solution.

**Comment by mitchell5** [comment] 2017-08-04 08:47
Hi,
Thank you for the direction. I did what you have said below:

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel died: 6.001140832901001

But before that I uninstalled Anaconda and reinstalled it. Now, I got another error but I think this is because of my application:

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel died: 6.001140832901001
Traceback (most recent call last):
  File "/Users/denizgokalp/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/denizgokalp/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 189, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "/Users/denizgokalp/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 248, in handle_exec_method
    view = ast.literal_eval(data['text/plain'])
  File "/Users/denizgokalp/anaconda/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/Users/denizgokalp/anaconda/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/Users/denizgokalp/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/Users/denizgokalp/anaconda/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/Users/denizgokalp/anaconda/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/Users/denizgokalp/anaconda/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x1317f4208>

**Comment by ccordoba12** [comment] 2017-08-18 21:44
I'm closing this one because we don't a way to reproduce it, sorry.

**Closed by ccordoba12** 2017-08-18 21:44 UTC
Labels: component:IPython Console, type:Bug
