### ISSUE TITLE
Auto generated error on startup

### ISSUE THREAD

**Issue by jared18y** [spyder-ide/spyder#5362] opened 2017-09-29 15:46 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/jyoung/Devel/anaconda3/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 904, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/home/jyoung/Devel/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 114, in set_cwd
    self.silent_execute(code)
  File "/home/jyoung/Devel/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 293, in silent_execute
    self.kernel_client.execute(to_text_string(code), silent=True)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-29 19:55
This is a duplicate of issue #5053 and it'll be fixed in Spyder 3.2.4

**Closed by ccordoba12** 2017-09-29 19:55 UTC
