### ISSUE TITLE
Help not available from Editor

### ISSUE THREAD

**Issue by Rayapur** [spyder-ide/spyder#5827] opened 2017-11-25 06:16 UTC
## Description

**What steps will reproduce the problem?**

1. (I am using MacBook Pro OSX High Sierra) Open Spyder from Anaconda navigator
2. Write any line of code in python
3. press command + I to see help
4. Or, even go to help window on right and select EDITOR, the object textbook is disabled and cannot enter.
5. I have made sure the checkboxes are checked in PREFERENCES --> HELP

**What is the expected output? What do you see instead?**
I want to see the help for the specific object or library loaded in help window

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-11-25 07:24
Hmm. Could potentially be an issue with High Sierra support? There have been various bugs reported with that....did it work before at some point, or is this your first time installing? If the former, what changed? If the latter, anything out of the ordinary about your installation? Did you try launching it from a shortcut or from the command line (with `spyder` from the Terminal)?

As for 
> Or, even go to help window on right and select EDITOR, the object textbook is disabled and cannot enter.

This isn't something specific to your platform, I can confirm—this occurs on both my Windows boxes running various OS and Spyder/Anaconda versions, since the beginning. Whether or not the "lock" icon is clicked, text cannot be manually entered into the help search box when the `source` is the Editor, only the `Console`. Extremely annoying, I agree...going back to Rstudio made me appreciate its vastly superior help system with actual searching, forward/back, zero lag, hyperlinks, and most of all far better reliability all the more. But I digress...

**Comment by Rayapur** [comment] 2017-11-25 22:07
Thanks for the response. Earlier I launched Spyder from navigator. I just tried launching from terminal window. while Spyder was successfully launched, I saw 9 warnings on terminal window, all being same. i.e. [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

I do not know what this means. Also, I had Navigator installed earlier but I have uninstalled with following commands (Googled, found some instructions and did it)
conda install anaconda-clean
anaconda-clean --yes
rm -rf ~/anaconda3

However, I do remember that even earlier seeing floating help in editor and help in the help window were issues. 

Lately I have installed theano, tensorflow and keras. Overall, not having help is painful and appreciate your help. Thanks in advance.

**Comment by CAM-Gerlach** [comment] 2017-11-25 22:12
This is looking like a potential duplicate of #5815 . Did you try the solutions suggested there? Specifically, did you try removing `enum34`? Is autocomplete working?

**Comment by Rayapur** [comment] 2017-11-26 03:37
Autocomplete is not working. let me go thru the reference you provided and follow the steps.

**Comment by Rayapur** [comment] 2017-11-26 03:47
Its working, thank you. I have uninstalled enum34 (pip uninstall enum34), relaunched Spyder. Now, autocomplete, balloon help and help window work like charm. Thank you @CAM-Gerlach and all for your input, sincerely appreciate your time.

**Comment by CAM-Gerlach** [comment] 2017-11-26 04:09
Sure, no problem. Glad you got it fixed. In that case, can this issue now be closed?

**Comment by Rayapur** [comment] 2017-11-26 04:47
Yes, please.

**Comment by CAM-Gerlach** [comment] 2017-11-26 06:57
Err, I meant you'll want to close it then, as you're the original reporter and thus are able to do so (regular users can't close other users' issues). Thanks.

Also, out of curiosity, is there a particular reason you're +1/thumbsup-ing your own posts?

**Closed** 2017-11-26 17:22 UTC
