### ISSUE TITLE
Spyder problem

### ISSUE THREAD

**Issue by arthurrinaldi** [spyder-ide/spyder#6290] opened 2018-01-24 15:40 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Arthur.EFFICIENCE\\.spyder-py3\\spyder.ini'

Traceback (most recent call last):
  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\Arthur.EFFICIENCE\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1420, in create_kernel_manager_and_kernel_client
    ker

**Comment by csabella** [comment] 2018-01-24 20:49
Thanks for reporting. The error message above is incomplete; please paste the full thing from the error dialog or the internal console. From what we have, this seems like it could be a problem with your install in some fashion, or with your antivirus/firewall, and a possible duplicate of #5257 . Also, this issue has been reported by some when ``TensorFlow`` is installed. 

Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, providing as much specific detail as possible, and we'll try to help if we can. Presuming it occurs on launching, does it only happen when launching Spyder from the Anaconda navigator, the start menu shortcut, and/or directly from the command line (with `spyder`)? Is there anything new, modified or unusual with your installation or environment?  You can get the relevant version information with ``conda list`` from the Anaconda Prompt. Otherwise, your issue will have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment] 2018-02-03 02:17
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-02-03 02:17 UTC
Labels: status:AwaitingFollowup
