### ISSUE TITLE
Run cell in new window Editor runs the whole script

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#12610] opened 2020-05-05 07:19 UTC
Running a cell in a script in a new window of the Editor runs the whole script.

Steps to reproduce:
1. open New window from the Editor menu,
2. in the new window run a cell from your code, e.g. run the first cell of this example script:
```python
import numpy as np
# %% 
a = np.arange(10)
```
3. the whole code gets executed, i.e. you can find `a` in the Variable explorer.

I'm on Spyder 4.1.2 | Python 3.6.7 64-bit | Qt 5.12.5 | PyQt5 5.12.3 | Linux 5.4.35-1-MANJARO

**Comment by ccordoba12** [comment] 2020-05-05 16:09
Duplicate of #12597

**Closed by ccordoba12** 2020-05-05 16:09 UTC
