### ISSUE TITLE
isuue

### ISSUE THREAD

**Issue by akshaylakade** [spyder-ide/spyder#6424] opened 2018-02-09 23:27 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Akshay Lakade\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2392, in run_file
    self.re_run_file()
  File "C:\Users\Akshay Lakade\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2412, in re_run_file
    self.save_all()
  File "C:\Users\Akshay Lakade\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2000, in save_all
    self.get_current_editorstack().save_all()
  File "C:\Users\Akshay Lakade\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1689, in save_all
    if self.data[index].editor.document().isModified():
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-02-09 23:55
Thanks for reporting. This issue appears to be a duplicate of #5996 (and others), which were closed due to non-response. 

We'll probably need more information about the circumstances in which this error occurred in order to fix it—was this the first time you tried saving a file? Does it only occur saving a particular file, or in a particular location? Did you try restarting Spyder, or saving somewhere else? Anything special about your system or environment?

Please provide what is requested above, and as much as possible of the items listed in the relevant [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include)of the Spyder Troubleshooting Guide, over on the #5996 thread to help this issue get fixed. Otherwise, we'll have to close it after one week (7 days) if we don't hear from you. Thanks!

**Comment by CAM-Gerlach** [comment] 2018-02-17 18:47
Sadly, this one meets the same fate...closed due to lack of response.

**Closed by CAM-Gerlach** 2018-02-17 18:47 UTC
Labels: status:Awaiting Followup
