### ISSUE TITLE
Error wile opening Spyder

### ISSUE THREAD

**Issue by Okroshiashvili** [spyder-ide/spyder#8702] opened 2019-02-04 06:36 UTC
### What steps will reproduce the problem?

I opened spyder and got this error. I do not know how to reproduce this error.

### Traceback
```python-traceback
    plugin.register_plugin()
    self.create_new_client(give_focus=False)
    server_info = nbopen(filename)
    server_info = find_best_server(filename)
    servers = [si for si in notebookapp.list_running_servers()
    servers = [si for si in notebookapp.list_running_servers()
    info = json.load(f)
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.7
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.14.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-04 08:37
Duplicate of spyder-ide/spyder-notebook#120. Unfortunately we don't know why it happens, sorry.

**Closed by ccordoba12** 2019-02-04 08:37 UTC

**Comment by Okroshiashvili** [comment] 2019-02-04 09:38
@ccordoba12  I removed spyder-notebook extension and error disappeared
