### ISSUE TITLE
Activation of kernel env fails when using anaconda shortcut (FileNotFound error kernel start 4.1.0)

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#11819] opened 2020-03-17 02:26 UTC
## Problem Description

Spyder4.1.0 IPython kernel startup error
Close spyder and restart, the problem persists.
### What steps reproduce the problem?

After upgrading spyder4.0.1 to 4.1.0, IPython kernel startup error occurs when starting spyder.
The following command is used to upgrade in a virtual environment:
conda install spyder=4.1.0
```python-traceback
启动 IPython 内核时发生错误（An error occurred while starting the IPython kernel）
错误：（Error）
Traceback (most recent call last):
File "C:\Users\Admin\Anaconda3\envs\python37\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\Users\Admin\Anaconda3\envs\python37\lib\site‑packages\jupyter_client\manager.py", line 259, in start_kernel
**kw)
File "C:\Users\Admin\Anaconda3\envs\python37\lib\site‑packages\jupyter_client\manager.py", line 204, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\Users\Admin\Anaconda3\envs\python37\lib\site‑packages\jupyter_client\launcher.py", line 138, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\Users\Admin\Anaconda3\envs\python37\lib\subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "C:\Users\Admin\Anaconda3\envs\python37\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件（The system can not find the file specified）。
```

## Versions

* Spyder version: 4.1.0
* Python version: Python3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win10

**Comment by leavor** [comment] 2020-03-17 02:42
Roll back to the 4.0.1 version, there is no error when starting the spyder.

**Comment by ccordoba12** [comment] 2020-03-17 03:55
@dalthviz, please try to reproduce this one by installing Spyder in a conda env and trying to start from it.

**Comment by leavor** [comment] 2020-03-17 07:11
Create the new Python virtual environment with the following command, and install spyder4.1.0 at the same time, the same error occurs

conda create -n python37_new python=3.7 spyder=4.1.0

![image](https://user-images.githubusercontent.com/1759365/76830889-35af0380-6861-11ea-8de8-c14c9bf85588.png)

**Comment by hilldog1378** [comment] 2020-03-17 19:16
I too was getting this same error after updating to 4.1.0.  A rollback to 4.0.1 fixed it for me.

**Comment by ccordoba12** [comment] 2020-03-17 19:19
Some questions:

* Did you install Anaconda for all users or just for your user?
* Did you install Anaconda in another partition (like `D:\`)?

**Comment by bmarr** [comment] 2020-03-17 19:32
I created issue #11829 from the Spyder issue reporting interface. My issue appears to be similar to this issue. I should have checked for this issue already existing first!
1. I don't remember if I installed Anaconda for all users or just for my user on this machine, and I am aware this is [I think] a well known annoying Anaconda install issue, and I never remember which is the preferred install option.
2. Anaconda was installed to D:\ mechanical hard drive because I prefer to install mostly only OS on the smaller capacity C:\ SSD for OS performance and reliability reasons. I imagine many others also do this.
Spyder 4.0.1 was very frustrating to use because of the constant freezing problem. I am motivated to continue finding a solution to getting 4.1.0 working on my system.

**Comment by b1139atpmme** [comment] 2020-03-17 19:34
Same issue.
Notes: default partition information, single user installation, basic environment, fresh anaconda install with conda-forge packages updated.

At one point I got the kernel to load using python start.py in the
spyder-#.#.#-py##_#/Lib/site-packages/spyder/app of a separate environment, but it couldn't locate libraries.

**Comment by gabrielclow** [comment] 2020-03-17 19:35
Same thing here, had to rollback

![image](https://user-images.githubusercontent.com/9113853/76894636-49f8fd80-686d-11ea-9847-b3635b338760.png)

**Comment by ccordoba12** [comment] 2020-03-17 19:42
> Notes: default partition information,

@b1139atpmme, so you don't have Anaconda installed in another partition?

**Comment by bmarr** [comment] 2020-03-17 20:06
> I too was getting this same error after updating to 4.1.0. A rollback to 4.0.1 fixed it for me.

Can confirm rolling back has no issues for me (apart from being back to 4.01!)

**Comment by yomoko** [comment] 2020-03-17 20:09
Same issue here.

**Comment by manfred2020** [comment] 2020-03-17 20:15
i had the same issue as all the others with spyder 4.1 in both of my environments (python 3.8.2 and 3.7.6).

will now go back to 4.0.1

**Comment by cccsmoreno** [comment] 2020-03-17 20:18
Same issue for me too. Removed and recreated env and the issue persists

![image](https://user-images.githubusercontent.com/59842743/76897838-7f4c1e00-6862-11ea-81d2-57f649ab29c7.png)

**Comment by manfred2020** [comment] 2020-03-17 20:24
just went back to spyder 4.0.1 in my python 3.8.2 env...

now it didn't even start anymore! not so great.

**Comment by yomoko** [comment] 2020-03-17 20:26
> just went back to spyder 4.0.1 in my python 3.8.2 env...
> 
> now it didn't even start anymore! not so great.

Rolled back to 4.0.1 and worked as b4 for me.

**Comment by cccsmoreno** [comment] 2020-03-17 20:33
> just went back to spyder 4.0.1 in my python 3.8.2 env...
> 
> now it didn't even start anymore! not so great.

Rollback worked fine for me as well

**Comment by dalthviz** [comment] 2020-03-17 20:33
@gabrielclow @b1139atpmme @leavor @bmarr @cccsmoreno @manfred2020 @yomoko I created envs in C and D (with conda-forge and the default channel) but I'm unable to reproduce this :/ could you guys check if you have anything different in your envs than the following?:

### Env in C with default channel (Note: creating it in D gives the same list of packages)
<details>

What I run was something like: `conda create -n python37_new python=3.7 spyder=4.1.0`

```
# packages in environment at C:\Users\Daniel\Anaconda3\envs\python37_new:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
argh                      0.26.2                   py37_0
asn1crypto                1.3.0                    py37_0
astroid                   2.3.3                    py37_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.1.0                    py37_0
bcrypt                    3.1.7            py37he774522_0
bleach                    3.1.0                    py37_0
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
cloudpickle               1.3.0                      py_0
colorama                  0.4.3                      py_0
cryptography              2.8              py37h7a1dbc1_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
docutils                  0.16                     py37_0
entrypoints               0.3                      py37_0
flake8                    3.7.9                    py37_0
future                    0.18.2                   py37_0
icu                       58.2                 ha66f8fd_1
idna                      2.9                        py_1
imagesize                 1.2.0                      py_0
importlib_metadata        1.5.0                    py37_0
intervaltree              3.0.2                      py_0
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.13.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.21                   py37_0
jedi                      0.14.1                   py37_0
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py37_0
jupyter_client            6.0.0                      py_0
jupyter_core              4.6.1                    py37_0
keyring                   21.1.0                   py37_0
lazy-object-proxy         1.4.3            py37he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
markupsafe                1.1.1            py37he774522_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37he774522_0
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
numpydoc                  0.9.2                      py_0
openssl                   1.1.1e               he774522_0
packaging                 20.3                       py_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
pathtools                 0.1.2                      py_1
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pip                       20.0.2                   py37_1
pluggy                    0.13.1                   py37_0
prompt_toolkit            3.0.3                      py_0
psutil                    5.7.0            py37he774522_0
pycodestyle               2.5.0                    py37_0
pycparser                 2.20                       py_0
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.6.1                      py_0
pylint                    2.4.4                    py37_0
pynacl                    1.3.0            py37h62dcd97_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.15.7           py37he774522_0
pysocks                   1.7.1                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.8                   py37_0
pytz                      2019.3                     py_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1000
pyyaml                    5.3              py37he774522_0
pyzmq                     18.1.1           py37ha925a31_0
qdarkstyle                2.8                        py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.0                      py_0
qtconsole                 4.7.1                      py_0
qtpy                      1.9.0                      py_0
requests                  2.23.0                   py37_0
rope                      0.16.0                     py_0
rtree                     0.9.3            py37h21ff451_0
setuptools                46.0.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.14.0                   py37_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.1.0                    py37_0
sphinx                    2.4.0                      py_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.1.0                    py37_0
spyder-kernels            1.9.0                    py37_0
sqlite                    3.31.1               he774522_0
testpath                  0.4.4                      py_0
tornado                   6.0.4            py37he774522_1
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
urllib3                   1.25.8                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.10.2                   py37_0
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1           py37he774522_1
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_3

```

</details>

### Env in D with conda-forge

<details>

What I run was something like: `conda create --prefix D:/kernel_test_forge -c conda-forge python=3.7 spyder=4.1.0`

```

# packages in environment at D:\kernel_test_forge:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2                py37_1001    conda-forge
astroid                   2.3.3                    py37_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5                        py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.7            py37hfa6e2cd_0    conda-forge
bleach                    3.1.3              pyh8c360ce_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37ha419a9e_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.8              py37hb32ad35_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20181111                   py_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
flake8                    3.7.9            py37hc8dfbb8_1    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.5.0                    py37_0    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.13.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21           py37hc8dfbb8_1    conda-forge
jedi                      0.14.1                   py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.0.0                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
keyring                   21.1.1                   py37_0    conda-forge
lazy-object-proxy         1.4.3            py37hfa6e2cd_1    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
markupsafe                1.1.1            py37h8055547_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.1                    py37_0    conda-forge
parso                     0.5.2                      py_0
pathtools                 0.1.2                      py_1    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
prompt-toolkit            3.0.4                      py_0    conda-forge
prompt_toolkit            3.0.4                         0    conda-forge
psutil                    5.7.0            py37h8055547_1    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pydocstyle                5.0.2                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pylint                    2.4.4                    py37_0    conda-forge
pynacl                    1.3.0           py37h2fa13f4_1001    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h8055547_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h5b45d93_4_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4                      py_0    conda-forge
python-language-server    0.31.8           py37hc8dfbb8_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   227              py37hfa6e2cd_0    conda-forge
pywin32-ctypes            0.2.0           py37hc8dfbb8_1001    conda-forge
pyyaml                    5.3              py37h8055547_1    conda-forge
pyzmq                     19.0.0           py37h8c16cda_1    conda-forge
qdarkstyle                2.8                        py_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.7.0                      py_0    conda-forge
qtconsole                 4.7.1                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
rope                      0.16.0                     py_0    conda-forge
rtree                     0.9.4            py37h804a536_1    conda-forge
setuptools                46.0.0           py37hc8dfbb8_2    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    2.4.4                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.1.0            py37hc8dfbb8_0    conda-forge
spyder-kernels            1.9.0            py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
typed-ast                 1.4.1            py37hfa6e2cd_0    conda-forge
ujson                     1.35            py37h63f7a3c_1002    conda-forge
urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.10.2                   py37_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
wrapt                     1.12.1           py37h8055547_1    conda-forge
yaml                      0.2.2                hfa6e2cd_1    conda-forge
yapf                      0.29.0                     py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge

```

</details>

**Comment by manfred2020** [comment] 2020-03-17 20:45
you are listening plain python installations, right? of course there are a lot of differences. i have pandas, scipy, seaborn, numpy, matplotlib, etc. installed.

so both of my environments are broken right now (i.e. no sypder, could only work with jupyter notebook from now on). i'm off to delete my environments and recreate them. some work ahead...

**Comment by dalthviz** [comment] 2020-03-17 20:54
@manfred2020 yep a basic installation, what I was thinking is that maybe you guys can create an env with the commands I supply just to check if the issue is related with some sort of package version or is something else. Also, could you provide your envs package list to check them then?

**Comment by cccsmoreno** [comment] 2020-03-17 20:56
@dalthviz Sorry, I do not have a D drive. Only a C Drive

My list of packages running the first command is this one:

## Package Plan ##

  environment location: C:\Users\SMORENO\AppData\Local\Continuum\miniconda3\envs\python37_new

  added / updated specs:
    - python=3.7
    - spyder=4.1.0


The following NEW packages will be INSTALLED:

  alabaster          conda-forge/noarch::alabaster-0.7.12-py_0
  argh               conda-forge/win-64::argh-0.26.2-py37_1001
  astroid            conda-forge/win-64::astroid-2.3.3-py37_1
  atomicwrites       conda-forge/noarch::atomicwrites-1.3.0-py_0
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  autopep8           conda-forge/noarch::autopep8-1.5-py_0
  babel              conda-forge/noarch::babel-2.8.0-py_0
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  bcrypt             conda-forge/win-64::bcrypt-3.1.7-py37hfa6e2cd_0
  bleach             conda-forge/noarch::bleach-3.1.3-pyh8c360ce_0
  ca-certificates    conda-forge/win-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/win-64::certifi-2019.11.28-py37hc8dfbb8_1
  cffi               conda-forge/win-64::cffi-1.14.0-py37ha419a9e_0
  chardet            conda-forge/win-64::chardet-3.0.4-py37hc8dfbb8_1006
  cloudpickle        conda-forge/noarch::cloudpickle-1.3.0-py_0
  colorama           conda-forge/noarch::colorama-0.4.3-py_0
  cryptography       conda-forge/win-64::cryptography-2.8-py37hb32ad35_1
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  diff-match-patch   conda-forge/noarch::diff-match-patch-20181111-py_0
  docutils           conda-forge/win-64::docutils-0.16-py37hc8dfbb8_1
  entrypoints        conda-forge/win-64::entrypoints-0.3-py37hc8dfbb8_1001
  flake8             conda-forge/win-64::flake8-3.7.9-py37hc8dfbb8_1
  future             conda-forge/win-64::future-0.18.2-py37hc8dfbb8_1
  icu                conda-forge/win-64::icu-64.2-he025d50_1
  idna               conda-forge/noarch::idna-2.9-py_1
  imagesize          conda-forge/noarch::imagesize-1.2.0-py_0
  importlib-metadata conda-forge/win-64::importlib-metadata-1.5.0-py37_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.5.0-1
  intervaltree       conda-forge/noarch::intervaltree-3.0.2-py_0
  ipykernel          conda-forge/win-64::ipykernel-5.1.4-py37h5ca1d4c_0
  ipython            conda-forge/win-64::ipython-7.13.0-py37h5ca1d4c_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  isort              conda-forge/win-64::isort-4.3.21-py37hc8dfbb8_1
  jedi               conda-forge/win-64::jedi-0.14.1-py37_0
  jinja2             conda-forge/noarch::jinja2-2.11.1-py_0
  jpeg               conda-forge/win-64::jpeg-9c-hfa6e2cd_1001
  jsonschema         conda-forge/win-64::jsonschema-3.2.0-py37hc8dfbb8_1
  jupyter_client     conda-forge/noarch::jupyter_client-6.0.0-py_0
  jupyter_core       conda-forge/win-64::jupyter_core-4.6.3-py37hc8dfbb8_1
  keyring            conda-forge/win-64::keyring-21.1.1-py37_0
  lazy-object-proxy  conda-forge/win-64::lazy-object-proxy-1.4.3-py37hfa6e2cd_1
  libclang           conda-forge/win-64::libclang-9.0.1-default_hf44288c_0
  libpng             conda-forge/win-64::libpng-1.6.37-h7602738_0
  libsodium          conda-forge/win-64::libsodium-1.0.17-h2fa13f4_0
  libspatialindex    conda-forge/win-64::libspatialindex-1.9.3-he025d50_3
  markupsafe         conda-forge/win-64::markupsafe-1.1.1-py37h8055547_1
  mccabe             conda-forge/noarch::mccabe-0.6.1-py_1
  mistune            conda-forge/win-64::mistune-0.8.4-py37hfa6e2cd_1000
  nbconvert          conda-forge/win-64::nbconvert-5.6.1-py37_0
  nbformat           conda-forge/noarch::nbformat-5.0.4-py_0
  numpydoc           conda-forge/noarch::numpydoc-0.9.2-py_0
  openssl            conda-forge/win-64::openssl-1.1.1d-hfa6e2cd_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pandoc             conda-forge/win-64::pandoc-2.9.2-0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  paramiko           conda-forge/win-64::paramiko-2.7.1-py37_0
  parso              pkgs/main/noarch::parso-0.5.2-py_0
  pathtools          conda-forge/noarch::pathtools-0.1.2-py_1
  pexpect            conda-forge/win-64::pexpect-4.8.0-py37hc8dfbb8_1
  pickleshare        conda-forge/win-64::pickleshare-0.7.5-py37hc8dfbb8_1001
  pip                conda-forge/noarch::pip-20.0.2-py_2
  pluggy             conda-forge/noarch::pluggy-0.12.0-py_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.4-py_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-3.0.4-0
  psutil             conda-forge/win-64::psutil-5.7.0-py37h8055547_1
  pycodestyle        conda-forge/noarch::pycodestyle-2.5.0-py_0
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pydocstyle         conda-forge/noarch::pydocstyle-5.0.2-py_0
  pyflakes           conda-forge/noarch::pyflakes-2.1.1-py_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  pylint             conda-forge/win-64::pylint-2.4.4-py37_0
  pynacl             conda-forge/win-64::pynacl-1.3.0-py37h2fa13f4_1001
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pyqt               conda-forge/win-64::pyqt-5.12.3-py37h6538335_1
  pyrsistent         conda-forge/win-64::pyrsistent-0.15.7-py37h8055547_1
  pysocks            conda-forge/win-64::pysocks-1.7.1-py37hc8dfbb8_1
  python             conda-forge/win-64::python-3.7.6-h5b45d93_4_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python-jsonrpc-se~ conda-forge/noarch::python-jsonrpc-server-0.3.4-py_0
  python-language-s~ conda-forge/win-64::python-language-server-0.31.8-py37hc8dfbb8_0
  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pywin32            conda-forge/win-64::pywin32-227-py37hfa6e2cd_0
  pywin32-ctypes     conda-forge/win-64::pywin32-ctypes-0.2.0-py37hc8dfbb8_1001
  pyyaml             conda-forge/win-64::pyyaml-5.3-py37h8055547_1
  pyzmq              conda-forge/win-64::pyzmq-19.0.0-py37h8c16cda_1
  qdarkstyle         conda-forge/noarch::qdarkstyle-2.8-py_0
  qt                 conda-forge/win-64::qt-5.12.5-h7ef1ec2_0
  qtawesome          conda-forge/noarch::qtawesome-0.7.0-py_0
  qtconsole          conda-forge/noarch::qtconsole-4.7.1-py_0
  qtpy               conda-forge/noarch::qtpy-1.9.0-py_0
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  rope               conda-forge/noarch::rope-0.16.0-py_0
  rtree              conda-forge/win-64::rtree-0.9.4-py37h804a536_1
  setuptools         conda-forge/win-64::setuptools-46.0.0-py37hc8dfbb8_2
  six                conda-forge/noarch::six-1.14.0-py_1
  snowballstemmer    conda-forge/noarch::snowballstemmer-2.0.0-py_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sphinx             conda-forge/noarch::sphinx-2.4.4-py_0
  sphinxcontrib-app~ conda-forge/noarch::sphinxcontrib-applehelp-1.0.2-py_0
  sphinxcontrib-dev~ conda-forge/noarch::sphinxcontrib-devhelp-1.0.2-py_0
  sphinxcontrib-htm~ conda-forge/noarch::sphinxcontrib-htmlhelp-1.0.3-py_0
  sphinxcontrib-jsm~ conda-forge/noarch::sphinxcontrib-jsmath-1.0.1-py_0
  sphinxcontrib-qth~ conda-forge/noarch::sphinxcontrib-qthelp-1.0.3-py_0
  sphinxcontrib-ser~ conda-forge/noarch::sphinxcontrib-serializinghtml-1.1.4-py_0
  spyder             conda-forge/win-64::spyder-4.1.0-py37hc8dfbb8_0
  spyder-kernels     conda-forge/win-64::spyder-kernels-1.9.0-py37hc8dfbb8_0
  sqlite             conda-forge/win-64::sqlite-3.30.1-hfa6e2cd_0
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  tornado            conda-forge/win-64::tornado-6.0.4-py37hfa6e2cd_0
  traitlets          conda-forge/win-64::traitlets-4.3.3-py37hc8dfbb8_1
  typed-ast          conda-forge/win-64::typed-ast-1.4.1-py37hfa6e2cd_0
  ujson              conda-forge/win-64::ujson-1.35-py37h63f7a3c_1002
  urllib3            conda-forge/win-64::urllib3-1.25.7-py37hc8dfbb8_1
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  watchdog           conda-forge/win-64::watchdog-0.10.2-py37_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.8-py_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py37_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py37_1003
  wrapt              conda-forge/win-64::wrapt-1.12.1-py37h8055547_1
  yaml               conda-forge/win-64::yaml-0.2.2-hfa6e2cd_1
  yapf               conda-forge/noarch::yapf-0.29.0-py_0
  zeromq             conda-forge/win-64::zeromq-4.3.2-h6538335_2
  zipp               conda-forge/noarch::zipp-3.1.0-py_0
  zlib               conda-forge/win-64::zlib-1.2.11-h2fa13f4_1006

I tried comparing them with text compare but it says "Sorry, but finding all the differences for these two texts takes too long", I noticed asn1crypto does not show for me though

**Comment by manfred2020** [comment] 2020-03-17 21:02
ok, got it.
i did you D installation and compared it with yours.
they are identical.

**Comment by ccordoba12** [comment] 2020-03-17 21:04
Some more questions:

* What happens if you open the Anaconda Prompt and type `spyder`?
* And what's the result when you start Spyder graphically from its entry on the Anaconda menu?

**Comment by manfred2020** [comment] 2020-03-17 21:08
in my 3.7.6 env. (where i still have spyder 4.1):
graphically: works now
prompt: works now

didn't work before (see above). only thing i changed since then: removed spyder from my 3.8.2 env. and created your conda forge test env (where spyder 4.1 works too).

very strange....

**Comment by testor321** [comment] 2020-03-17 21:12
in fact, I am getting the same error if I start spyder as a shortcut (or from console)
But if I start the same spyder 4.1 from Anaconda Navigator, it works OK.
****
![image](https://user-images.githubusercontent.com/18244189/76902468-56e11580-689c-11ea-8370-841fdd2f9f2e.png)

**Comment by manfred2020** [comment] 2020-03-17 21:16
yes, via desktop shortcut sypder 4.1 still doesn't work (works from prompt and anaconda)

**Comment by cccsmoreno** [comment] 2020-03-17 21:18
This is very strange.. For me it works the same either from console or shortcut.. The GUI opens for me in both cases but its the kernel that shows the error. Maybe these are seperate issues?

**Comment by dalthviz** [comment] 2020-03-17 21:24
Testing with the desktop shortcut I can reproduce this! Thank you all for the feedback! for now please launch Spyder from the Anaconda prompt/Anaconda Navigator

**Comment by gabrielclow** [comment] 2020-03-17 22:09
> Testing with the desktop shortcut I can reproduce this! Thank you all for the feedback! for now please launch Spyder from the Anaconda prompt/Anaconda Navigator

Working perfect here through with Anaconda Prompt

**Comment by pythonic2020** [comment] 2020-03-17 22:09
I get the exact same problem when starting spyder 4.1.0 from Windows 10 Start Menu shortcut.  Running spyder from anaconda prompt (type "spyder") or from Anaconda Navigator menu both work perfectly.  Spyder 4.1.0 is installed into a conda 4.8.3 env (fully updated) running Python 3.7.6.  Spyder isn't installed in simple Miniconda base environment where Navigator is installed.

**Comment by ccordoba12** [comment] 2020-03-17 22:15
Thanks everyone for your feedback. We were analyzing the problem with @dalthviz for the last hour and finally found out the root cause for it.

We'll release 4.1.1 with a fix for this as soon as we can.

**Closed** 2020-03-18 01:46 UTC
Labels: OS:Windows, component:IPython Console, status:Reproduced, type:Bug

**Comment by ccordoba12** [comment] 2020-03-19 21:31
Our **4.1.1** version, with a fix for this problem is part of Anaconda now. You can update with

    conda install spyder=4.1.1
