### ISSUE TITLE
Mac and Spyder 4.0

### ISSUE THREAD

**Issue by spanishinquistion** [spyder-ide/spyder#8064] opened 2018-10-13 11:48 UTC
Minor problem with a Mac and using Anaconda Spyder 4.0.0b1

The normal spyder opens up but the icons for new files and open directory do not work. 

Work around is to use the file explorer to search for file but a bit cumbersome. 

'Nobody expects the spanish inquisition'

**Comment by ccordoba12** [comment] 2018-10-13 16:35
Please post a screenshot of the buttons you say don't work. Thanks!

**Comment by ccordoba12** [comment] 2018-10-15 21:22
We'll take a look at this for beta2. Please stop closing and opening the issue, there's no need for that.

**Comment by ccordoba12** [comment] 2018-10-16 04:33
Thanks @bcolsen. Closing as a duplicate of #7111.

**Closed by ccordoba12** 2018-10-16 04:33 UTC
Labels: component:Editor, type:Bug
