### ISSUE TITLE
Spyder crashes

### ISSUE THREAD

**Issue by Ujjwal98** [spyder-ide/spyder#7181] opened 2018-05-23 09:00 UTC
## Description

**What steps will reproduce the problem?**

1. reading large csv file
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/ujjwal/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 524, in <lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "/home/ujjwal/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 546, in editor_accepted
    self.set_value(index, conv_func(value))
  File "/home/ujjwal/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1386, in set_value
    self.set_value_func(name, value)
  File "/home/ujjwal/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 297, in set_value
    self.shellwidget.set_value(name, svalue)
  File "/home/ujjwal/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 101, in set_value
    value = to_text_string(value)
  File "/home/ujjwal/anaconda3/lib/python3.6/site-packages/spyder/py3compat.py", line 140, in to_text_string
    return str(obj)
MemoryError

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-05-23 13:11
This is a duplicate of issue #5830 and we'll fix it our next release (Spyder 3.3).

**Closed by ccordoba12** 2018-05-23 13:11 UTC

**Comment by Ujjwal98** [comment] 2018-05-23 13:15
Thanks for the response.
I will eagerly waiting for next release.

**Comment by ccordoba12** [comment] 2018-05-23 13:19
In the meantime you can avoid this error by **not** pressing the Ok button when closing our Variable Explorer viewers for Dataframes, arrays, lists, etc.

**Comment by CAM-Gerlach** [comment] 2018-05-24 17:11
(i.e. press <kbd>Cancel</kbd> or the window close button ("X").
