### ISSUE TITLE
 Goto Definition is not working

### ISSUE THREAD

**Issue by SomannaKuri** [spyder-ide/spyder#13461] opened 2020-08-03 06:34 UTC
### What steps will reproduce the problem?

After right clicking on the function, its not showing "goto defition option".

### Traceback
```python-traceback
  File "C:\Users\somanna.kuri\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

During handling of the above exception, another exception occurred:

ImportError: numpy.core.multiarray failed to import
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by steff456** [comment] 2020-08-04 17:35
Hi @SomannaKuri,
With which function are you trying to use the `goto definition` option?

**Comment by SomannaKuri** [comment] 2020-08-04 19:39
Hi,

I am using 4.1.4 version.

Thanks,
Somanna

**Comment by steff456** [comment] 2020-08-04 19:52
Can you please let me know which function gives you the error? In this way we can try to reproduce the issue

**Comment by SomannaKuri** [comment] 2020-08-04 20:05
When I right click on the function, which is called from other package or
within same file, and select "go to definition", it's not working.

Thanks & Regards,
Somanna

**Comment by steff456** [comment] 2020-08-04 20:07
Can you please upload a gif to see the behavior of the error?

**Comment by SomannaKuri** [comment] 2020-08-05 06:48
Hi Stephannie,

Thank you so much for your response. After restarting the system its
working fine.
Please find the attached file.


Thank you,
Somanna

**Comment by steff456** [comment] 2020-08-05 15:13
So your problem is fixed now?

**Comment by SomannaKuri** [comment] 2020-08-05 16:30
Yes it is fixed now.


Thank you,
Somanna

**Comment by steff456** [comment] 2020-08-05 17:08
I'm closing this issue since it is fixed, if you encounter another error please open a new issue.

Thanks for reporting!

**Closed by steff456** 2020-08-05 17:08 UTC
Labels: status:Awaiting Followup
