### ISSUE TITLE
Editor autocomplete failure after installed tensorflow

### ISSUE THREAD

**Issue by OpenMindInternational** [spyder-ide/spyder#5899] opened 2017-12-05 15:52 UTC
## Description

**What steps will reproduce the problem?**

1.  install tensorflow
2.  try to trigger autocomplete in editor
3.  nothing happens

**What is the expected output? What do you see instead?**
After installed tensorflow, 
the editor suffers autocomplete failure, 
while IPython does work well.

for example,
type 
>> import numpy as np
>> np.a<Tab>
>> [expected] autocomplete suggestion list
>> [now] nothing happens

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-12-05 15:56
Closing as a duplicate of issue #5782. Please read that issue for the solutions.

**Closed by ccordoba12** 2017-12-05 15:56 UTC

**Comment by OpenMindInternational** [comment] 2017-12-05 16:36
@ccordoba12 Many thanks!
Solution works:
conda uninstall enum34
conda install jedi=0.11.0
conda install parso=0.1.0
