### ISSUE TITLE
spyder 3.2.3 editor code auto completion does't work

### ISSUE THREAD

**Issue by nunoyu** [spyder-ide/spyder#6074] opened 2017-12-27 22:47 UTC
Hi guys, 
## Description of your problem
I just found that my spyder editor can't auto complete codes as before.  
**What steps will reproduce the problem?**

1.  Checked the Tools->Preference-> Editor -> CodeIntrospection -> Automatic Code Completion. But it doesn't work! 
2. Tried to  downgrade spyder from 3.2.3 to 3.0.2 but failed. 

**What is the expected output? What do you see instead?**
Regain the automatic code completion. 

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.3 
* Qt Version: 5.6.2
* PyQt Version:4.11.4
* Operating system: win10 64bits

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-12-28 00:52
Closing as a duplicate of issue #5782. Please read that issue for possible fixes.

**Closed by ccordoba12** 2017-12-28 00:52 UTC

**Comment by CAM-Gerlach** [comment] 2017-12-28 00:56
Thanks for reporting. Unfortunately, as code completion is working just fine (well, with the normal caveats) on my Win 10 x64 machine running Spyder 3.2.5, and we don't have any other information to go on here, we cannot really do anything about it other than note you are using a slightly outdated version of Spyder and oddly mismatched Qt and PyQt versions. 

Most likely, your problem can be fixed by restarting Spyder, doing a clean reinstall of the latest version of the Anaconda distribution with all the needed dependencies (5.0.1), updating Spyder to the latest stable version (3.2.5), and/or resetting preferences with `spyder --reset` from the anaconda prompt, as well as trying completion with different packages as some don't play well with Spyder's third party completion libraries (`rope` and `jedi`) for reasons well outside of our control. 

If after those steps code completion still doesn't work, then in order to isolate the problem to Spyder's codebase you'll need to describe in detail whether it worked before, what you did leading up to the problem occurring and any special circumstances thereof, and what you already tried to attempt to fix it, as well as a minimal reproducible example and information about how you installed Spyder, your Python, Qt, PyQt, Spyder, OS, and dependency versions, and anything special about your environment, so we can determine the problem and if it is in fact in Spyder's code. Thanks.

**Comment by nunoyu** [comment] 2017-12-28 19:33
thanks you! @CAM-Gerlach @ccordoba12
