### ISSUE TITLE
GUI profiler error

### ISSUE THREAD

**Issue by rlloretb** [spyder-ide/spyder#12718] opened 2020-05-13 11:21 UTC
### What steps will reproduce the problem?

I simply run the profiler tool over a python script.

### Traceback
```python-traceback
  File "/Users/lloretroger/opt/miniconda3/envs/geo_env/lib/python3.8/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 267, in <lambda>
    self.finished(ec, es))
  File "/Users/lloretroger/opt/miniconda3/envs/geo_env/lib/python3.8/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 335, in finished
    self.show_errorlog()  # If errors occurred, show them.
  File "/Users/lloretroger/opt/miniconda3/envs/geo_env/lib/python3.8/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 239, in show_errorlog
    TextEditor(self.error_output, title=_("Profiler output"),
TypeError: __init__() got an unexpected keyword argument 'size'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.8.2
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Darwin 18.7.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment] 2020-05-13 14:40
Hi @rlloretb this seems like a duplicate of #11875 please update to our latest release `4.1.3` to get the fix. You can do this with something like: `conda install spyder=4.1.3`

**Closed by dalthviz** 2020-05-13 14:40 UTC
