### ISSUE TITLE
Issue on click of Maximize current pane button

### ISSUE THREAD

**Issue by akhildar** [spyder-ide/spyder#6037] opened 2017-12-22 17:03 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/akhil/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2248, in maximize_dockwidget
    self.last_plugin.dockwidget.toggleViewAction().setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'dockwidget'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-23 00:36
Thanks for reporting. This issue is a duplicate of #5477 , and so will be closed. If you have more to add, please comment over there.

**Closed by CAM-Gerlach** 2017-12-23 00:36 UTC
