### ISSUE TITLE
sklearn import fails only on Spyder

### ISSUE THREAD

**Issue by Goldesel23** [spyder-ide/spyder#5421] opened 2017-10-07 20:13 UTC
## Description of your problem

When trying to import sklearn in Spyder, the import fails, although on IPyhon and QtIPyhon the import is succeeded.

**What steps will reproduce the problem?**

import sklearn on console

**What is the expected output? What do you see instead?**

The output is:

`
  File "<ipython-input-6-b7c74cbf5af0>", line 1, in <module>
    import sklearn

  File "/home/tfreitas/.local/lib/python3.5/site-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone

  File "/home/tfreitas/.local/lib/python3.5/site-packages/sklearn/base.py", line 12, in <module>
    from .utils.fixes import signature

  File "/home/tfreitas/.local/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,

  File "/home/tfreitas/.local/lib/python3.5/site-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature

  File "/home/tfreitas/.local/lib/python3.5/site-packages/sklearn/utils/fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa

  File "/home/tfreitas/.local/lib/python3.5/site-packages/scipy/sparse/linalg/__init__.py", line 114, in <module>
    from .dsolve import *

  File "/home/tfreitas/.local/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/__init__.py", line 60, in <module>
    from .linsolve import *

  File "/home/tfreitas/.local/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 15, in <module>
    import scikits.umfpack as umfpack

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 892, in _find_spec

  File "<frozen importlib._bootstrap>", line 873, in _find_spec_legacy

  File "/home/tfreitas/.local/lib/python3.5/site-packages/pyximport/pyximport.py", line 253, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)

  File "/usr/lib/python3.5/imp.py", line 270, in find_module
    "not {}".format(type(name)))

RuntimeError: 'list' must be None or a list, not <class 'str'>`

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.5.2
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

## Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.1 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-10-09 14:19
Thanks for reporting. This is (essentially) a duplicate of issue #5299. We're working to fix it in a future release.

**Closed by ccordoba12** 2017-10-09 14:19 UTC
