### ISSUE TITLE
Spyder 4.0.0rc2 bug

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10788] opened 2019-11-21 09:05 UTC
I can't really describe what this bug is, so I have to use this vague title, but I know how to reproduce it.

Use this code snippet:

```python
import torch
import torch.utils.data as Data

X = torch.tensor([[1, 2], [3, 4], [5, 6]])
y = torch.tensor([1, 2, 3])

dataset = Data.TensorDataset(X, y)
dataloader = Data.DataLoader(dataset, batch_size=2, shuffle=True)
```

Paste it into the editor, save as a .py file, and then run it.

After running it, go to the IPython console, type these exact characters:
```python
dataloader(
```

As soon as I enter the `(` character, the "Issue reporter" opens up, and the error details are as follows:
```
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\ipythonconsole\widgets\help.py", line 176, in _handle_inspect_reply
    text_new_line=new_line
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\widgets\mixins.py", line 573, in show_calltip
    inspect_word=inspect_word,
UnboundLocalError: local variable 'inspect_word' referenced before assignment
```

**Comment by MrFuppes** [comment] 2019-11-21 13:34
maybe related? https://github.com/spyder-ide/spyder/issues/10752

**Comment by ccordoba12** [comment] 2019-11-21 13:59
Duplicate of #10752

**Closed by ccordoba12** 2019-11-21 13:59 UTC
