### ISSUE TITLE
there are no output after running the file and I keep getting the same message

### ISSUE THREAD

**Issue by arshif685** [spyder-ide/spyder#11598] opened 2020-02-19 20:16 UTC
there are no output after running the file and I keep getting the same message

runfile('D:/Projects/cameradistance.py', wdir='D:/Projects')
![error](https://user-images.githubusercontent.com/60957363/74872093-92aebb00-5382-11ea-987a-91a8b9463645.png)

**Comment by bcolsen** [comment] 2020-02-19 20:30
Closing as duplicate of #11599

**Closed by bcolsen** 2020-02-19 20:30 UTC
