### ISSUE TITLE
Crash report during start

### ISSUE THREAD

**Issue by CrimsonKoba** [spyder-ide/spyder#11796] opened 2020-03-15 01:36 UTC
### What steps will reproduce the problem?

Crash message when I start spyder.
Fresh install in ubuntu using pip in a virtualenv

### Traceback
```python-traceback
  File "/home/koba/.pyenv/lib/python3.8/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/home/koba/.pyenv/lib/python3.8/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/home/koba/.pyenv/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 2d22d554665c11ea98834f868c3fba4d
Traceback (most recent call last):
  File "/home/koba/.pyenv/lib/python3.8/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/home/koba/.pyenv/lib/python3.8/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/home/koba/.pyenv/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.8.0
* Qt version: 5.14.1
* PyQt5 version: 5.14.1
* Operating System: Linux 5.3.0-40-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
sphinx >=0.6.6               :  2.4.4 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-03-15 17:19
Duplicate of #11798

**Closed by ccordoba12** 2020-03-15 17:19 UTC
