### ISSUE TITLE
Launching tutorial

### ISSUE THREAD

**Issue by alha68** [spyder-ide/spyder#9821] opened 2019-07-12 13:29 UTC
### What steps will reproduce the problem?

Launching tutuorial after upgrading to 4.0.0 beta3

### Traceback
```python-traceback
  File "/Users/malhashi/anaconda3/lib/python3.7/site-packages/spyder/plugins/help/plugin.py", line 459, in handle_link_clicks
    self.show_tutorial()
  File "/Users/malhashi/anaconda3/lib/python3.7/site-packages/spyder/plugins/help/plugin.py", line 453, in show_tutorial
    text = open(tutorial).read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/malhashi/anaconda3/lib/python3.7/site-packages/spyder/plugins/help/utils/tutorial.rst'
```

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-12 15:49
Duplicate of #9794.

**Closed by ccordoba12** 2019-07-12 15:49 UTC
