### ISSUE TITLE
just error

### ISSUE THREAD

**Issue by Magicwangs** [spyder-ide/spyder#6053] opened 2017-12-25 14:09 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\App\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 476, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "D:\App\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 679, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "D:\App\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 105, in __init__
    self.max_min_col_update()
  File "D:\App\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 145, in max_min_col_update
    for dummy, col in self.df.iteritems():
  File "D:\App\Anaconda\lib\site-packages\pandas\core\frame.py", line 646, in iteritems
    if self.columns.is_unique and hasattr(self, '_item_cache'):
  File "pandas/_libs/src\properties.pyx", line 34, in pandas._libs.lib.cache_readonly.__get__
  File "D:\App\Anaconda\lib\site-packages\pandas\core\indexes\base.py", line 1261, in is_unique
    return self._engine.is_unique
  File "pandas\_libs\index.pyx", line 219, in pandas._libs.index.IndexEngine.is_unique.__get__
  File "pandas\_libs\index.pyx", line 226, in pandas._libs.index.IndexEngine._do_unique_check
  File "pandas\_libs\in

**Comment by CAM-Gerlach** [comment] 2017-12-25 19:24
Thanks for reporting. This error message looks like a new one, but it is incomplete; please copy and paste the entire thing here so we can properly diagnose the error; also, please describe step by step how you got it (including minimal code to reproduce it, if possible). Without that, we won't be able to fix it, and so we'll have to close this issue in a week (7 days) from now. Thanks.

**Comment by CAM-Gerlach** [comment] 2018-01-02 16:49
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-01-02 16:49 UTC
Labels: status:AwaitingFollowup
