### ISSUE TITLE
Spyder code editor is lagging 

### ISSUE THREAD

**Issue by koresaram777** [spyder-ide/spyder#15598] opened 2021-05-12 05:26 UTC
In Spyder 4.2.5 keyboard response is very slow, after restarting the editor is working properly for about 20 minutes and afterwards is lagging again.

**Comment by dalthviz** [comment] 2021-05-12 15:57
Hi @koresaram777 could you give us more details about your setup (OS, Python, what did you use to install Spyder, etc)? Without that their not much else we can do, sorry :/

**Comment by koresaram777** [comment] 2021-05-13 05:15
> Hi @koresaram777 could you give us more details about your setup (OS, Python, what did you use to install Spyder, etc)? Without that their is not much else we can do, sorry :/

Hi dalthviz! my OS is windows 10 pro, python version is 3.7.10, I have installed spyder via anaconda. Spyder version is 4.2.5. 
Thank you for your response

**Comment by dalthviz** [comment] 2021-05-13 08:50
Thank you for the info @koresaram777 do you have Kite installed? Also, are you using any specific configuration related to the Editor which is not the default one?

Maybe this elements in our troubleshooting guide could be worthy to check: https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#lsp-has-stopped-working 

Let us know :)

**Comment by koresaram777** [comment] 2021-05-13 08:58
> Thank you for the info @koresaram777 do you have Kite installed? Also, are you using any specific configuration related to the Editor which is not the default one?
> 
> Maybe this elements in our troubleshooting guide could be worthy to check: https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#lsp-has-stopped-working
> 
> Let us know :)

Yes, I have kite installed. No specific configuration, all is default except interface theme

**Comment by dalthviz** [comment] 2021-05-13 11:27
@koresaram777 did a restart of the LSP server helps in your case? I'm afraid there is not much we can do besides that for the moment :/

**Comment by hackenjoe** [comment] 2021-05-13 20:55
Probably the reason for the problem is the massive memory consumption of Kite. Also in general if you have opened lot of tabs (i.e. different .py files) then it becomes laggy, even with powerful hardware (e.g. 64 gb ram + Win10).  I guess something like multi-threading would solve the problem.

**Comment by ccordoba12** [comment] 2021-05-23 19:06
Closing in favor of issue #15631, which has more details about this problem.

**Closed by ccordoba12** 2021-05-23 19:06 UTC
Labels: status:Awaiting Followup
