### ISSUE TITLE
Execute the python file in a directory containing Chinese characters show errors -- os.chdir -> WindowsError [Error 3] 

### ISSUE THREAD

**Issue by yanjinyi1987** [spyder-ide/spyder#4837] opened 2017-07-28 07:13 UTC
## Description

**What steps will reproduce the problem?**

1. save a python file in a directory whose path contains Chinese characters.
2. press the run button.
3. the error information would be shown.

**What is the expected output? What do you see instead?**
The python file can be executed correctly, but the error information is annoying.

**Please provide any additional information below**

  File "G:\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 895, in set_working_directory
    refresh_console=False)
  File "G:\Anaconda2\lib\site-packages\spyder\plugins\workingdirectory.py", line 286, in chdir
    os.chdir( to_text_string(directory) )
WindowsError: [Error 3] : u'O:\\\ufffd\u03fd\ufffd\u04bb\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd\\SAF Design\\program'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-07-28 14:04
Thanks for reporting. This is a duplicate of issue #4816.

For now, please avoid running code in directories with non-ascii characters. We're working to fix this one in Spyder **3.2.1**.

**Closed by ccordoba12** 2017-07-28 14:04 UTC
Labels: resolution:Duplicate
