### ISSUE TITLE
[Question] Use a type-checker or different linter than those provided inside Spyder?

### ISSUE THREAD

**Issue by qexat** [spyder-ide/spyder#22727] opened 2024-10-24 19:08 UTC
### Issue Report Checklist

(Since this is a question, I removed the irrelevant checkboxes)

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

## Question

Is there a way to use pieces of software such as [Pyright](https://github.com/microsoft/pyright/) or [Ruff](https://github.com/astral-sh/ruff) in Spyder? I went through the settings but could not find anything. I also searched for the corresponding plugins with no avail.

## Versions

* Spyder version: 6.0.0

I'm leaving the version here in case someone searches through the issue tracker in the future.

**Comment by dalthviz** [comment] 2024-11-01 23:11
Hi @qexat and thank your for the feedback! I think this could be related with https://github.com/spyder-ide/spyder/issues/21040 For the moment, from the Spyder side, we don't have support for those projects. However, the package we use as LSP server to do the linting and completions for Python (https://github.com/python-lsp/python-lsp-server) seems like has a third party ruff extension available

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2024-12-12 00:35
Closing as a duplicate of #21040

**Closed by dalthviz** 2024-12-12 00:35 UTC
Labels: resolution:Duplicate, type:Question, component:Code Completion and linting, status:Awaiting Followup
