### ISSUE TITLE
Spyder 3.2.7, change color scheme

### ISSUE THREAD

**Issue by tokenarky** [spyder-ide/spyder#6709] opened 2018-03-10 08:40 UTC
1. system: Manjaro Linux 17.1.6, Spyder 3.2.7
2. Spyder->Tools->Preferences->Syntax coloring->Scheme
3. select a scheme, click "Apply", color scheme changed successfully, but produce this problem.

details:
File "/usr/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "/usr/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/usr/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/usr/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/usr/lib/python3.6/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

![snapshot](https://user-images.githubusercontent.com/17881318/37240070-fb2ae074-2480-11e8-92c1-54b4b77ffd6f.png)

**Comment by csabella** [comment] 2018-03-10 10:12
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed by csabella** 2018-03-10 10:12 UTC

**Comment by tokenarky** [comment] 2018-03-10 10:49
Thank you!
