### ISSUE TITLE
Anaconda3 Spyder Launch Error: DLL load failed 

### ISSUE THREAD

**Issue by ruoyuwangeel4930** [spyder-ide/spyder#3939] opened 2017-01-10 06:13 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Newly installed Anaconda3 for windows x86.
2. Launch Spyder 3.0.0 in Anaconda Navigator.
3. Nothing would happen then.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Every time I try to launch Spyder, a cmd window pops up and closes immediately. Spyder wouldn't launch (the cmd window says couldn't find the program). The ipython works fine.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5
* Operating system:  Win10 x84

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

![default](https://cloud.githubusercontent.com/assets/25001755/21795692/c202a042-d73e-11e6-9ed8-31fc82da482b.PNG)

**Comment by ccordoba12** [comment] 2017-01-10 12:42
Did you install Anaconda in a directory with non-ascii characters?

**Comment by ruoyuwangeel4930** [comment] 2017-01-11 00:55
I don't think so. The whole path is just C:\Program Files\Anaconda3. I tried to reinstall in other directory and the problem is still there.

**Comment by ccordoba12** [comment] 2017-01-11 02:53
Please try in a directory without spaces and that it's in your Users personal directory to see if that fixes this error.

**Comment by ruoyuwangeel4930** [comment] 2017-01-11 10:26
Thanks for your reply:-). I tried to install in directory such as D:\Software\Anaconda and installed a lower version of Anaconda. It showed the same error information. Then I examined the QtWebEngineWidgets.py file and found none of the modules it imports is in the folder (as the picture showed below). 

![image](https://cloud.githubusercontent.com/assets/25001755/21844813/08ed343a-d82b-11e6-8093-61b1415e6791.png)

Should there be these files in the folder or there are some setting error in my .ini files? but I changed nothing after installation.

**Comment by ccordoba12** [comment] 2017-01-11 20:30
It seems you have Canopy and Anaconda both installed in your machine. What if you uninstall Canopy and try again?

**Comment by ruoyuwangeel4930** [comment] 2017-01-12 00:21
This problem exists before I install Canopy. I have homework due that day, that's why I install it after Anaconda.

**Comment by jsh9** [comment] 2017-11-22 04:49
I encountered a similar issue. I first installed anaconda 2 on my Windows 10 (64 bit), and then I created an Python 3.6 environment inside my Anaconda 2 (as suggested here: https://conda.io/docs/user-guide/tasks/manage-python.html#installing-a-different-version-of-python).

Then I installed spyder into this new environment, and run spyder. But I saw this error message, apparently qt related:

```
Traceback (most recent call last):
  File "C:\Anaconda2\envs\py36\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Anaconda2\envs\py36\lib\site-packages\spyder\app\start.py", line 145, in main
    from spyder.app import mainwindow
  File "C:\Anaconda2\envs\py36\lib\site-packages\spyder\app\mainwindow.py", line 78, in <module>
    from qtpy.compat import from_qvariant
  File "C:\Anaconda2\envs\py36\lib\site-packages\qtpy\compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "C:\Anaconda2\envs\py36\lib\site-packages\qtpy\QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: DLL load failed: The specified procedure could not be found.
```
Is there a bug fix on the way? I want to switch to Python 3, but is getting bogged down by these bugs.

**Comment by ccordoba12** [comment] 2017-12-02 14:39
Closing as a duplicate of issue #5876.

**Closed by ccordoba12** 2017-12-02 14:39 UTC

**Comment by kiranvarghesev** [comment] 2018-01-05 14:31
from . import _imaging as core

ImportError: DLL load failed: The specified module could not be found.

**Comment by prasahu** [comment] 2019-05-02 05:27
> 
> 
> Please try in a directory without spaces and that it's in your Users personal directory to see if that fixes this error.

I tried without spaces still facing the same problem.

**Comment by prasahu** [comment] 2019-05-02 06:59
Hello,
I have been facing an issue from last 3 days regarding the installation of Anaconda3. 

Following steps I have already tried:

1. pyqt5 installation. However, this worked as It can able to launch Anaconda Navigator.
But again the problem in launching Spyder any version only. Otherwise all other versions like IPython, Jupyter are working fine.
![image](https://user-images.githubusercontent.com/49840169/57060094-bf032900-6cd5-11e9-98a6-194735246425.png)


2. pyside installation: Here I can able to launch Spyder but the problem I observed as it's all about Anaconda2 with Python 2.7 rather than Anaconda3 with Python 3.7.
Hope you have understood the problem, can you help me to answer this issue.
With Regards,
Pradeepta Sahu

**Comment by DEMONCELL1** [comment] 2020-08-14 15:28
![Screenshot (86)](https://user-images.githubusercontent.com/45090961/90265844-c9b4e380-de70-11ea-95c6-3f65a9478f86.png)
 
i am getting this error please tell me how to solve this error

**Comment by Ritvik-Sapra** [comment] 2020-11-30 19:48
I had to pip install PyQt5 because one day Anaconda just stopped working. Since then it showed that Spyder is not compatible with the latest version of PyQt5..
