### ISSUE TITLE
"Help" pane not automatically opening docs from editor

### ISSUE THREAD

**Issue by bcaddy** [spyder-ide/spyder#11354] opened 2020-01-20 15:36 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Opening help/docs automatically in the help pane works as expected when a function name is typed in the console.  Example: I type "np.linspace(" and the docs open right up.  When I do the same thing from the editor nothing happens.  When I force it with cmd+I the help pane says "no documentation available".

Note: This is a fresh install of Anaconda and Spyder.

### What steps reproduce the problem?

1. Type any function/object etc into editor
2. docs do not come up in the help pane

### What is the expected output? What do you see instead?
Expected output: The docs/docstrings.  What I see: nothing or "No documentation available"

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS 10.15.2 "Catalina"

### Dependencies

No results found

**Comment by ccordoba12** [comment] 2020-01-20 15:39
Duplicate of #10671

**Closed by ccordoba12** 2020-01-20 15:39 UTC
