### ISSUE TITLE
Graphics backend creating a loop-like error

### ISSUE THREAD

**Issue by 12lberry** [spyder-ide/spyder#16511] opened 2021-09-29 22:18 UTC
I am new to the GitHub world but I have been working with spyder and python for several years now and never had this issue. I hope this is the right place and I am sorry if the solution is found somewhere else. I tried doing some searching but couldnt find anything, possibly because I didnt know where to start searching.

## Problem Description
When my graphics backend is set to inline under Preferences->IPython Console->Graphics->Graphics Backend, Then everything works like it should. However, if I change the graphics backend to anything other than inline my code will not run. The console will show my code is trying to run but will act as if it is in a loop. No errors will occur, the console will just sit there with nothing happening.

I do not think it is not code related because this happens with ANY script I run. Even something as simple as,
import numpy as np
print(np.pi)

I have the same setup (spyder, python, and QT versions) on my home desktop (Windows 10, maybe Windows 10 Pro has something to do with it?) and I have never had this issue. This problem is occuring on my university lab computer. I would like to be able to have the plots be generated with Qt5.

### What steps reproduce the problem?

1.  Changing the graphics backend to Qt5
2.  Changing the graphics backend to Tnker

### What is the expected output? What do you see instead?

I expect the code to run and execute, or throw and error if syntax is bad. But none of this is happening.

## Versions
* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 Pro

Let me know if anything else is needed from me and thank you for the help in advance!

**Comment by ccordoba12** [comment] 2021-10-02 04:09
Hey @12lberry, thanks for reporting. I think his is a duplicate of issue #15875. I mean, the error is not exactly the same, but we have a bug when setting interactive backends (i.e. other than Inline) that generates not only the error on that issue but also the one you reported here.

I already have a fix for this problem and it'll be part of our next version (5.2.0), to be released later this month. So please wait until that version is released and let us know if the bug is fixed for you. Otherwise, open a new issue about it.

By the way, the Tkinter backend is broken on Windows (not our fault but due to a bug in one of our dependencies), so you can only use the Qt5 backend on that platform.

**Closed by ccordoba12** 2021-10-02 04:09 UTC
