### ISSUE TITLE
[Linux] Segmentation fault on start because of problems with OpenGL on Intel cards

### ISSUE THREAD

**Issue by xxblx** [spyder-ide/spyder#4495] opened 2017-05-19 20:00 UTC
## Description

Spyder3 segfaults on start on Fedora 25

```
$ spyder3
Segmentation fault (core dumped)
$
```

**What steps will reproduce the problem?**

1. `# pip3 install -U spyder`
2. `$ spyder3`
3. segfault

**Please provide any additional information below**

Hardware:
1. Laptop
* Model: DELL XPS 13
* Distro and DE: Fedora 25, GNOME3 on Xorg
* CPU: Intel Core i7-7500U
* Video
```
$ inxi -G
Graphics:  Card: Intel Device 5916
           Display Server: Fedora X.org 119.3 driver: N/A Resolution: 3200x1800@59.98hz
           GLX Renderer: Mesa DRI Intel HD Graphics 620 (Kabylake GT2) GLX Version: 3.0 Mesa 17.0.5
```

2. Desktop
* Distro and DE: Fedora 25, GNOME3 on Xorg
* CPU: Intel Core i5-4460
* Video
```
$ inxi -G
Graphics:  Card: NVIDIA GP107 [GeForce GTX 1050]
           Display Server: Fedora X.org 119.3 driver: nvidia
           Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 1050/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 375.66
```

## Solution
1. `# pip3 install pyopengl`
2. Add `from OpenGL import GL` to site-packages/spyder/app/start.py
3. After that Spyder3 starts fine

## Versions

* Spyder Version: 3.1.4
* Python Version: 3.5.3
* Qt Version: 5.7.1
* PyQt Version: 5.7
* Operating system: Fedora 25 x86_64 with GNOME3 on Xorg
```
$ uname -a
Linux xxblx-laptop 4.10.15-200.fc25.x86_64 #1 SMP Mon May 8 18:46:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

## Dependencies

```
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  1.5.2rc2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by ccordoba12** [comment] 2017-05-19 21:02
This is a duplicate of issue #3332.

**Comment by xxblx** [comment] 2017-05-20 13:23
@ccordoba12, I know this issue. But I reproduced this issue on intel card with open source drivers while issues #3332 and #3226 about nvidia + pyqt5. 
Looks like and modern linux can has troubles with any video card. And solution is pretty simple add +1 import to spyder/app/start.py - `from OpenGL import GL`

**Comment by ccordoba12** [comment] 2017-06-13 01:19
@xxblx, I'm going to merge this one with #3332 because the solution for both issues is the same. Thanks for understanding!

**Closed by ccordoba12** 2017-06-13 01:19 UTC
Labels: component:Main Window, resolution:Duplicate, type:Bug

**Comment by 124938** [comment] 2018-06-16 11:07
**Problem:**
$ anaconda-navigator 
/home/asus/.anaconda/navigator/scripts/spyder.sh: line 3: 23879 Segmentation fault      (core dumped) spyder > /home/asus/.anaconda/navigator/scripts/spyder-out-1.txt 2> /home/asus/.anaconda/navigator/scripts/spyder-err-1.txt

**Solution**
$ inxi -G
$ sudo apt install python3-pip
$ pip3 install pyopengl
$ anaconda-navigator

**Comment by GodinNut** [comment] 2018-07-07 08:18
@124938 Thank you so much, you saved my day!
