### ISSUE TITLE
Cannot launch Spyder - Python 3 - macOS

### ISSUE THREAD

**Issue by agombert** [spyder-ide/spyder#7129] opened 2018-05-14 14:55 UTC
## Problem Description

Hi, I've got a problem when I launch spyder on my computer. Actually, the kernel cannot connect. I upgraded the dependencies, but I still got this error. Do you have an idea on how solve the issue ?

### What steps reproduce the problem?

1.  Launch spyder with the command line : spyder3

### What do you see instead?

```python-traceback
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 269, in 
main()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 15, in 
from tornado import ioloop
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/tornado/ioloop.py", line 51, in 
from tornado.concurrent import Future, is_future, chain_future, future_set_exc_info, future_add_done_callback # noqa: E501
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/tornado/concurrent.py", line 42, in 
from concurrent import futures
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/concurrent/futures/__init__.py", line 8, in 
from concurrent.futures._base import (FIRST_COMPLETED,
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site‑packages/concurrent/futures/_base.py", line 381
raise exception_type, self._exception, self._traceback
^
SyntaxError: invalid syntax
```

## Versions

* Spyder version: 3.2.8.
* Python version: 3.6.4
* Qt version: 5.9.3.
* PyQt version: 5.9.2
* Operating System name/version: macOS High Sierra version 10.13.4

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.5 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-05-14 16:36
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by CAM-Gerlach** [comment] 2018-05-15 01:56
Possible duplicate of #6407 or similar. Very likely an install issue, quite possibly due to an old version of the ``concurrent.futures`` package or the like. Furthermore, you've evidently installed Spyder with your system Python, which is for experts only who are able to fix the resulting problems on their own. For everyone else, we recommend you install Anaconda, as we lack the resources to help resolve the many install-related issues that often occur otherwise, like this one. Therefore, closing this; please consult the Troubleshooting Guide and follow all the steps as @ccordoba12 suggested.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can.  Thanks, and best of luck!

**Closed** 2018-05-15 01:57 UTC
Labels: status:Awaiting Followup

**Comment by agombert** [comment] 2018-05-15 08:29
Hi,

FYI : I installed the last version of python 3.6.5. and it worked well. 

Thx for your messages.

Cheers,

Arnault

**Comment by CAM-Gerlach** [comment] 2018-05-15 13:59
Glad you got it fixed!
