### ISSUE TITLE
spyder error popup on iPython error

### ISSUE THREAD

**Issue by ajheller** [spyder-ide/spyder#5184] opened 2017-09-09 18:42 UTC
## Description

**What steps will reproduce the problem?**

1. start spyder
2. do something that generates an error, for example type 1/0 in the iPython console
3. 

**What is the expected output? What do you see instead?**

expect an error in iPython console, but window pops up saying Spyder has encountered an error and offers to submit to GitHub (which I am)

**Please provide any additional information below**

  File "/Users/heller/anaconda/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/heller/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.20.2 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.0.1 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-09 20:06
Thanks for reporting. This is a duplicate of issue #5158.

**Closed by ccordoba12** 2017-09-09 20:06 UTC
