### ISSUE TITLE
spyder closes when trying to save an image or the like .html

### ISSUE THREAD

**Issue by rinkorn** [spyder-ide/spyder#4114] opened 2017-02-07 15:09 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi >=0.8.1     :  0.10.0 (OK)
psutil >=0.3     :  5.1.2 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by goanpeca** [comment] 2017-02-07 16:07
@rinkorn could you be more specific? Are you suing the editor the variable explorer? Please give more details

**Comment by ccordoba12** [comment] 2017-02-07 16:48
This seems a duplicate of issue #4088.

**Closed by ccordoba12** 2017-02-07 16:48 UTC
Labels: resolution:Duplicate
