### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by OverfloError** [spyder-ide/spyder#7108] opened 2018-05-11 17:18 UTC
No idea what happened internally or what caused it.
The only thing that I found was that the "Help" window did not respond.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 264, in <lambda>
    self.finished(ec, es))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 335, in finished
    self.show_data(justanalyzed=True)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 362, in show_data
    self.datatree.show_tree()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 526, in show_tree
    rootkey = self.find_root()  # This root contains profiler overhead
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 507, in find_root
    self.profdata.sort_stats("cumulative")
AttributeError: 'NoneType' object has no attribute 'sort_stats'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.3.1 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by CAM-Gerlach** [comment] 2018-05-11 19:28
Thanks for reporting. It looks like its a problem with the Spyder profiler. Were you doing anything with that beforehand? Also, there are a number of known issues with the TensorFlow Anaconda environment you seem to be working under. Please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). 

Also, if it occurs again, please reference [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!

**Comment by OverfloError** [comment] 2018-05-11 19:58
I currently use 3 environments in anaconda. The base, the glueviz and the tensorflow environments.
The crash only happened once in the tensorflow environment as far as I know.
I just tested the above-mentioned error in connection with the help function and the ctrl-1 shortcut for all of the above when selecting a command in the editor.

No command in the editor that I tested was recognised by the helper. The ones in the command windows did work. 

Ps:
When there is any further information I can provide I will do my best to deliver, but as I am relatively new to git I am not too experienced, so sorry about that

**Comment by OverfloError** [comment] 2018-05-11 20:26
Also here is a gif of a reproduction of the error. [Dropbox link](https://www.dropbox.com/sh/9vrlpzqwp37wx8w/AAB55SZpOcb_qPcrjRUomQAsa?dl=0)

**Comment by CAM-Gerlach** [comment] 2018-05-11 21:34
Thanks for the quick response.

> The crash only happened once in the tensorflow environment as far as I know.

Okay, then this implies there's something going on with your install, likely outside of Spyder's control. Exactly what that might be, I'm not entirely sure, but most likely some form of dependency conflict. It does look we might be able to at least catch the error, but it won't be easy to confirm without a way to reproduce it.

> I just tested the above-mentioned error

I'm still not clear—how did you reproduce the error? By what specific steps?

> No command in the editor that I tested was recognised by the helper. The ones in the command windows did work.

If I understand you correctly, this part is a well known issue, likely install related in your case (``enum34``, maybe?) and is a duplicate or near duplicate of #2162 and #5393 .

> Also here is a gif of a reproduction of the error. Dropbox link

All I could see was a brief shot you you clicking on the launch button for Spyder. Is there a part to it I'm missing? Also, you should be able to embed gifs directly in github by just copy and pasting here.

**Comment by OverfloError** [comment] 2018-05-12 14:32
I have fixed the problem by using the steps described in the comments of #5393. Please feel free to close this error report and mark this problem as solved.
In case I can reproduce the crash I will try to write a more detailed description about it in another report.

**Comment by CAM-Gerlach** [comment] 2018-05-12 14:53
Thanks for the update, and glad you got that one fixed. If you can reproduce the crash, since its already the subject of this issue there is no need to open another duplicate. Instead, just re-open this issue with a comment describing it in more detail. Best of luck!

**Closed by CAM-Gerlach** 2018-05-12 14:53 UTC
Labels: component:Profiler, status:Awaiting Followup
