### ISSUE TITLE
chinese character input problem

### ISSUE THREAD

**Issue by matteoshen** [spyder-ide/spyder#4701] opened 2017-07-05 08:34 UTC
## Description
I m in Ubuntu 16.04LTS, with spyder installed with anaconda-4.4.0-Linux-amd64.
I can NOT input chinese character in editor neither in editor pane nor ipython pane

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by jitseniesen** [comment] 2017-07-05 08:44
Thanks for your report. We are aware of the issue after we were told in issue #4120. Unfortunately, we don't know of a solution.

I am closing this issue as a duplicate of #4120 in order to keep the discussion in one place.

**Closed by jitseniesen** 2017-07-05 08:44 UTC
