### ISSUE TITLE
Notebook  Notebook 

### ISSUE THREAD

**Issue by yanqinwu711** [spyder-ide/spyder#8783] opened 2019-02-15 21:40 UTC
### What steps will reproduce the problem?

Notebook 
Notebook 
Notebook 
Notebook 
Notebook 
Notebook 

### Traceback
```python-traceback
  File "/Users/wyy/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 329, in create_new_client
    server_info = nbopen(filename)
  File "/Users/wyy/anaconda3/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 56, in nbopen
    server_info = find_best_server(filename)
  File "/Users/wyy/anaconda3/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 40, in find_best_server
    servers = [si for si in notebookapp.list_running_servers()
  File "/Users/wyy/anaconda3/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 40, in <listcomp>
    servers = [si for si in notebookapp.list_running_servers()
  File "/Users/wyy/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1767, in list_running_servers
    info = json.load(f)
  File "/Users/wyy/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/wyy/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/wyy/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/wyy/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 16.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.7 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-15 21:56
Duplicate of https://github.com/spyder-ide/spyder-notebook/issues/120

**Closed by ccordoba12** 2019-02-15 21:56 UTC
