### ISSUE TITLE
Sudden crash trying to split editor horizontally right after startup

### ISSUE THREAD

**Issue by RLive** [spyder-ide/spyder#5024] opened 2017-08-22 06:30 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1350, in close_file_in_all_editorstacks
    editorstack.close_file(index, force=True)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1332, in close_file
    self.remove_from_data(index)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1125, in remove_from_data
    self.update_fileswitcher_dlg()
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 784, in update_fileswitcher_dlg
    self.fileswitcher_dlg.setup()
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\fileswitcher.py", line 744, in setup
    current_path = self.current_path
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\fileswitcher.py", line 339, in current_path
    return self.paths_by_widget[self.get_widget()]
KeyError: None

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :

**Comment by ccordoba12** [comment] 2017-08-22 12:35
Thanks for reporting.

@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment] 2017-08-23 04:59
Hi @RLive could you try to test the error again after updating to Spyder 3.2.1? When testing with 3.2.0 I'm getting a different error but I think that it was fixed for 3.2.1:

```
File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1236, in __setup_menu
    add_actions(self.menu, list(actions)+self.__get_split_actions())
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 309, in add_actions
    action = action.no_icon_action
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 443, in __getattribute__
    attr = super(SpyderAction, self).__getattribute__(name)
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 462, in no_icon_action
    return self._action_no_icon
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 445, in __getattribute__
    if hasattr(attr, '__call__') and name not in ['triggered', 'toggled',
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted
``` 

Also, did you try to do something more than split the editor horizontally?. All the info to reproduce the error will be greatly appreciated :).

**Comment by ccordoba12** [comment] 2017-08-23 12:14
@dalthviz, I think this happens if you close Spyder with the editor in a splitted state and open it again.

**Comment by dalthviz** [comment] 2017-08-24 03:08
@ccordoba12 I tried letting the editor in split state before openning it again but no error appears. From the traceback it seems that @RLive was closing a file(?) Also tried to close files but I'm not being able to reproduce the error.

**Comment by ccordoba12** [comment] 2017-08-26 18:50
Closing because we're unable to reproduce this error, sorry.

**Closed by ccordoba12** 2017-08-26 18:50 UTC
Labels: component:Main Window, type:Bug
