### ISSUE TITLE
spyder (version 3.2.4) won't allow me to access preferences.

### ISSUE THREAD

**Issue by lukemenzies87** [spyder-ide/spyder#5912] opened 2017-12-07 10:01 UTC
## Description

**What steps will reproduce the problem?**

1. spyder (version 3.2.4) won't allow me to access preferences.
2. Installed on Windows (10) using anaconda version (5.0.1)
3.  Either by using the icon or by using ctrl+alt+shift+p

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2609, in edit_preferences
    widget.initialize()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 77, in initialize
    self.load_from_conf()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 381, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :

**Comment by CAM-Gerlach** [comment] 2017-12-07 12:29
Thanks for reporting. This is a well known bug, duplicate of #5578 , and is resolved in 3.2.5 which is planned to be released in a few days, In the meantime, running `spyder --reset` from the command line (e.g. Anaconda Prompt) should fix it. Therefore, this issue can be closed.

**Closed** 2017-12-07 12:53 UTC
