### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'execute'

### ISSUE THREAD

**Issue by ajing1** [spyder-ide/spyder#7134] opened 2018-05-15 12:46 UTC
## Description

**What
  File "C:\Users\dear\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 890, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "C:\Users\dear\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 936, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "C:\Users\dear\Anaconda3\envs\tensorflow\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Users\dear\Anaconda3\envs\tensorflow\lib\site-packages\qtconsole\console_widget.py", line 632, in execute
    self._execute(source, hidden)
  File "C:\Users\dear\Anaconda3\envs\tensorflow\lib\site-packages\qtconsole\frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

**Comment by CAM-Gerlach** [comment] 2018-05-15 14:32
Thanks for reporting. This appears to be a duplicate of #5053 which was fixed in Spyder 3.2.4, released many months ago. You can update with ``conda update spyder`` from the Anaconda prompt.

**Closed by CAM-Gerlach** 2018-05-15 14:32 UTC
