### ISSUE TITLE
Unable to run spyder due to error of "Error reading broker pipe: The pipe has been ended. (0x6D)"

### ISSUE THREAD

**Issue by tuchysony** [spyder-ide/spyder#7250] opened 2018-06-04 16:03 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm being faced with the issue that I couldn't launch spyder due to an error below.
"[7756:2332:0604/105603.937:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)"
When I launch Spyder, it appears once and then after 5 to 10 seconds, it disappears with (Not responding) message @ the top next to "Spyder (python 3.6)"

I also turned off a firewall/anti-virus system, though it still not working.
Your advice would be highly appreciated.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment] 2018-06-04 17:29
@tuchysony Thanks for reporting. If you had searched the above error message, you would have found that this issue appears to be a duplicate of #6938 and #7136 . Did you try all the potential solutions mentioned in those threads (deactivating any firewall/antivirus, uninstalling ``spyder-autopep8`` or any other third party Spyder plugins, ``conda install pyopengl``, ``conda update qt pyqt``, ``conda install pyqt=5.6``, updating everything else with ``conda update anaconda``, installing/updating your graphics drivers, etc)? Also, based on both the information here and is what is stated on those threads, this is a qt/pyqt or packaging/conda issue, not really something Spyder can fix. Also, you *did* try everything in the troubleshooting guide including reinstalling Anaconda, correct?

Let us know; if we don't hear from you, this issue will be closed after one week (7 days). Thanks.

**Comment by tuchysony** [comment] 2018-06-04 21:48
Thank you very much for your clear indication.
I finally made it by installing old version of anaconda 4.4 (w/ Python 3.5), instead of anaconda 5.2.
I don't still know why it doesn't work with latest version.

**Comment by tuchysony** [comment] 2018-06-04 21:50
In addition, I did try everything in the troubleshooting guide including reinstalling anaconda (latest) and other solutions you wrote down. Unfortunately, it doesn't work.
Thank you.

**Comment by CAM-Gerlach** [comment] 2018-06-04 21:53
Glad you got it working for now, but this really shouldn't happen, and you shouldn't have to downgrade to fix it. Check out the ContinuumIO/anaconda-issues#9142 thread where it is discussed in more detail, with some potential solutions, and feel free to chime in if you have something to add there. Thanks!

**Closed by CAM-Gerlach** 2018-06-04 21:53 UTC
Labels: status:Awaiting Followup

**Comment by bruot** [comment] 2018-08-20 08:38
I had the same issue. ``conda install pyqt=5.6`` solved the issue:

``conda install pyqt=5.6``:

```
## Package Plan ##

  environment location: C:\Users\bruot\Anaconda3

  added / updated specs:
    - pyqt=5.6


The following packages will be DOWNGRADED:

    pyqt: 5.9.2-py36ha878b3d_0  --> 5.6.0-py36ha878b3d_6
    qt:   5.9.6-vc14h62aca36_0  --> 5.6.2-vc14h6f8c307_12
    sip:  4.19.8-py36h6538335_0 --> 4.18.1-py36h6538335_2
```
After that, Spyder manages to start.

And if I do ``conda upgrade pyqt``:

```
## Package Plan ##

  environment location: C:\Users\bruot\Anaconda3

  added / updated specs:
    - pyqt


The following packages will be UPDATED:

    pyqt: 5.6.0-py36ha878b3d_6  --> 5.9.2-py36ha878b3d_0
    qt:   5.6.2-vc14h6f8c307_12 --> 5.9.6-vc14h62aca36_0
    sip:  4.18.1-py36h6538335_2 --> 4.19.8-py36h6538335_0
```
After that, Spyder crashes at startup again.

**Comment by CAM-Gerlach** [comment] 2018-08-20 09:08
Just to confirm, by

> I had the same issue.

you mean the error message

> Error reading broker pipe: The pipe has been ended

Presuming that's the case, see the solutions suggested over in #7690 ; while both threads are similar/identical that one's more relevant than this one so please continue future comments over there. Also, please try downgrading ``qt`` to 5.9.5 and 5.9.4 (with ``conda install qt=5.9.#`` where ``#`` is 5 and then 4) when on PyQt 5.9, and see if the error re-occurs. Also, please provide the information requested by our issue template (OS/version, Python version, and most importantly Spyder version and how you installed it). Also, make sure the issue occurs starting in a fresh environment; run ``conda create -n spyder-test python=3.6`` to create it. then ``activate spyder-test`` to make it the active environment and finally ``conda install spyder`` to get Spyder; Spyder can then be started by simply running ``spyder``.

**Comment by Antzxz** [comment] 2019-01-29 18:12
I was receiving the same error message as the original commentor. I was also only able to get spyder to launch after downgrading to anaconda v 4.4. However, I then ran into the issue where spyder crashed when trying to open a file #[3903](https://github.com/spyder-ide/spyder/issues/3903). I uninstalled Dell Backup and Recovery as described by some users in the thread, which resolved that issue. I next re-updated my anaconda version (5.3.0), and was finally able to get spyder to launch with no issues in the updated version. Perhaps these two issues are linked, and uninstalling the Dell Backup and Recovery will resolve this issue?

**Comment by CAM-Gerlach** [comment] 2019-01-29 19:12
Its possible it was that, or it could have just been reinstalling Anaconda did the trick. Either way, glad you found a solution to your problem, and thanks so much for letting us know, @Antzxz . I'll post this on the other thread I asked people to post further comments on, so hopefully it will help others as well.

> anaconda v 4.4

That's almost *two years* old, BTW! I wasn't even using Python that long ago, haha.

**Comment by Antzxz** [comment] 2019-01-29 20:37
@CAM-Gerlach 
I hope the Dell Backup and Recovery is actually the issue! That would be a much simpler fix then trying to uninstall/reinstall every package that has been suggested. LOL,  I was having such a difficult time trying to get it to launch, I was desperate enough to use version 4.4..

I did see a Mac user post on [stackoverflow](https://stackoverflow.com/questions/51125462/spyder-not-launching) that using conda to reinstall the tornado package worked for them. Just posting this for others to explore since I have not seen it on these forums. 

Goodluck!
