### ISSUE TITLE
Search for backslash via 'Find in files' invokes spyder error

### ISSUE THREAD

**Issue by fgotzens** [spyder-ide/spyder#6241] opened 2018-01-18 12:02 UTC
## Description

**What steps will reproduce the problem?**

1. Open a project of your choice.
2. Search -> Find in Files -> Search for a backslash only:  \\
3. Spyder displays 'Spyder has encountered a problem.' and throws the error message below.

**Please provide any additional information below**

  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\widgets\findinfiles.py", line 770, in append_result
    line = self.truncate_result(line, colno, match_end)
  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\widgets\findinfiles.py", line 695, in truncate_result
    line = to_text_string(line)
  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9e in position 0: ordinal not in range(128)
  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\widgets\findinfiles.py", line 770, in append_result
    line = self.truncate_result(line, colno, match_end)
  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\widgets\findinfiles.py", line 695, in truncate_result
    line = to_text_string(line)
  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9e in position 0: ordinal not in range(128)
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\<NAME>\Anaconda2\lib\site-packages\spyder\widgets\find

**Versions**
Spyder: 3.2.6
Python: 2.7.14 64 bits
Qt 5.6.2
PyQt5 5.6 on Windows

**Comment by ccordoba12** [comment] 2018-01-18 13:48
Thanks for reporting. This is a duplicate of #6218.

**Closed by ccordoba12** 2018-01-18 13:48 UTC
