### ISSUE TITLE
list() function

### ISSUE THREAD

**Issue by LastLucker** [spyder-ide/spyder#20780] opened 2023-04-06 09:53 UTC
### What steps will reproduce the problem?

Function list() dont work.
Try easy example:

a = ('xyz', 'zara', 'ab')
abc = list(a)
print (abc)

I have a TypeError: 'list' object is not callable

But this example work in all other programs otherwise Spyder with result ['xyz', 'zara', 'ab']

## Versions

* Spyder version: 5.4.3  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree                                     :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.1.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.6.1 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog                                         :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.34 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2             :  1.2.2 (OK)
```

**Comment by dalthviz** [comment] 2023-04-06 17:27
Hi @LastLucker thank you for the feedback! I was not able to reproduce the issue using the Windows standalone installer and the  selected default Python interpreter:

![image](https://user-images.githubusercontent.com/16781833/230450965-0fd0f36c-5542-48fc-8ffe-15a06ac81174.png)

Is this happening for you in a specific console client or just by running the code provided? Are you maybe using a custom interpreter by any chance?

Also, what happens if you run `list` in the console? Could it be possible that you had run some code in the console where the problem happens that assigned `list` to something? Like doing `list = ['xyz', 'zara', 'ab']`?

Any new info in order to better understand what could be happening here and reproduce it locally is greatly appreciated. Let us know!

**Comment by LastLucker** [comment] 2023-04-06 19:02
Hi, Daniel.

I'll just say that before writing to you, I reinstalled Spyder and that
didn't fix the problem.
Then I wrote to you.
But while I was waiting for your reply to my query, I reinstalled Spyder
again (re-downloaded the installer) and now the problem is gone.
So now I can conclude that probably the problem was with my PC or with the
installer. But it doesn't matter anymore.
I apologize for taking up your time and please consider the issue closed.

Thanks and sorry again!

чт, 6 квіт. 2023 р. о 20:27 Daniel Althviz Moré ***@***.***>
пише:

**Comment by dalthviz** [comment] 2023-04-06 19:07
Awesome, thank you for letting us know @LastLucker ! Closing this then as completed

**Closed by dalthviz** 2023-04-06 19:07 UTC
Labels: component:IPython Console, resolution:Completed, status:Awaiting Followup
