### ISSUE TITLE
Cannot start spyder5.4.1

### ISSUE THREAD

**Issue by jy99846025** [spyder-ide/spyder#20304] opened 2023-01-04 12:49 UTC
Spyder, which has always been updated with Pip, does not like anaconda. The latest version 5.4.1 of Spyder was updated a few days ago, and it cannot be started. Several new Python environments have been reset. The first thing is to install Spyder 5.4.1. From 3.11.1 to 3.11.0 to 3.10, it cannot be started.

**Comment by ccordoba12** [comment] 2023-01-04 15:16
Hey @jy99846025, thanks for reporting. You said

> Spyder, which has always been updated with Pip, does not like anaconda.

If you're using pip to update Spyder in Anaconda, please stop doing it. That's a terrible practice because conda and pip packages are binary incompatible, which leads to all sorts of strange problems. Furthermore, we recommend you to remove and reinstall Anaconda, as described in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).

In the future, we recommend you to use conda-forge to get the latest Spyder and use a dedicated conda environment to install/update it, as described in [our documentation](http://docs.spyder-ide.org/current/installation.html#installing-with-conda).

> The latest version 5.4.1 of Spyder was updated a few days ago, and it cannot be started. Several new Python environments have been reset. The first thing is to install Spyder 5.4.1. From 3.11.1 to 3.11.0 to 3.10, it cannot be started.

This looks like a duplicate of issue #20097, so I'm going to close it in favor of that issue since you didn't provide more details about the problem.

**Closed by ccordoba12** 2023-01-04 15:16 UTC
