### ISSUE TITLE
Variable explorer crash with Numpy arrays made of strings

### ISSUE THREAD

**Issue by wolfobert** [spyder-ide/spyder#2961] opened 2016-01-29 11:17 UTC
This code crashes the variable explorer (works with the variable explorer closed):
x = numpy.array(['1','2'])

Version: Spyder 2.3.8 with Anaconda 2.4.1, Windows 7 (recent install)

**Comment by ccordoba12** [comment] 2016-01-29 14:56
What's your Python version?

**Comment by wolfobert** [comment] 2016-01-29 15:12
Python 2.7.11 :: Anaconda 2.4.1 (64-bit)

**Comment by ccordoba12** [comment] 2016-02-07 20:16
It seems this is a Windows only problem. I'm unable to reproduce it on Linux.

**Comment by albertogomcas** [comment] 2016-02-16 07:59
I believe I reported the same/similar issue https://github.com/spyder-ide/spyder/issues/2983

**Comment by ccordoba12** [comment] 2016-02-16 12:18
@albertogomcas, you're right. so I'm closing this issue as a duplicate of issue #2983.

**Closed by ccordoba12** 2016-02-16 12:18 UTC
Labels: Bug, Duplicate, Variable-Explorer, Windows
