### ISSUE TITLE
Python3.7 Spyder

### ISSUE THREAD

**Issue by GeorgeJub** [spyder-ide/spyder#8692] opened 2019-02-03 02:02 UTC
### What steps will reproduce the problem?

_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/georgejubran/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
====================
I got this message in the python output when I was trying to see the contents of X , an array float 64 

### Traceback
```python-traceback
  File "/Users/georgejubran/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/Users/georgejubran/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 403, 'json': {'message': 'At least one email address must be verified to do that.', 'documentation_url': 'https://help.github.com/articles/adding-an-email-address-to-your-github-account'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 403, 'json': {'message': 'At least one email address must be verified to do that.', 'documentation_url': 'https://help.github.com/articles/adding-an-email-address-to-your-github-account'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 15.6.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.5.0 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-03 09:14
Duplicate of #8582. It'll be fixed in our next version (3.3.3).

**Closed by ccordoba12** 2019-02-03 09:14 UTC
