### ISSUE TITLE
Cannot launch Spyder

### ISSUE THREAD

**Issue by yordiak** [spyder-ide/spyder#3804] opened 2016-12-08 20:15 UTC
Hello, I installed anacoda in a system that uses manjaro lxqt. When I try to launch spyder I get the following error

```
File "/opt/anaconda/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/opt/anaconda/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/opt/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/opt/anaconda/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```

**Comment by ccordoba12** [comment] 2016-12-08 20:21
This is a duplicate of issue #3383.

Please install libselinux.so in your computer to fix.

**Closed by ccordoba12** 2016-12-08 20:21 UTC

**Comment by JnjR** [comment] 2017-03-19 14:51
Totally worked ... Thanks!
