### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Gowtham1729** [spyder-ide/spyder#7276] opened 2018-06-11 06:47 UTC
### What steps will reproduce the problem?

unable to view the pandas dataset from variable explorer. please help !!

### Traceback
```python-traceback
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    Traceback (most recent call last):
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
return to_qvariant(to_text_string(self.df_index[row]))
Traceback (most recent call last):
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 283, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/gowtham/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.14
* Qt version: 4.8.7
* PyQt4 (API v2) version: 4.11.4
* Operating system: Linux 4.13.0-36-generic

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.21.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
psutil >=0.3      :  5.4.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-06-11 21:11
Thanks for reporting. This is a duplicate of issue #5833 and it'll be fixed in our next version (**3.3.0**) to be released in a couple of weeks.

Also,

> Qt version: 4.8.7
> PyQt4 (API v2) version: 4.11.4

Please update to PyQt5 because we stopped to support PyQt4.

**Closed by ccordoba12** 2018-06-11 21:11 UTC
