### ISSUE TITLE
New Console often non-responsive when I press F5 on Editor window

### ISSUE THREAD

**Issue by vahidsafavi** [spyder-ide/spyder#20124] opened 2022-11-28 03:14 UTC
### What steps will reproduce the problem?

Since I installed Spyder 5.4.0 my scripts often fail to launch properly. I got the usual: runfile('aaa', wdir='bbb'), but then the console freezes. It becomes non-responsive even to ^C. This happens about 80% of attempts on a new Console. 
Additional observation, but not sure whether it is related to the above:
If I hit enter in console, then the original In[1] console prompt changes to In[0] followed by a newline followed by In [1] prompt. Afterwards, the python script freeze happens far less frequently. Also, if the first line of script is print('\n'), similarly the script freeze happens much less frequently. None of the two workarounds are 100% consistent though!

## Versions

* Spyder version: 5.4.0  (pip)
* Python version: 3.10.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.0 (OK)
keyring >=17.0.0              :  23.11.0 (OK)
nbconvert >=4.0               :  7.2.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.12.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.5 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  63.2.0 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.23.4 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
arrow                         1.2.3
astroid                       2.12.12
asttokens                     2.1.0
atomicwrites                  1.4.1
attrs                         22.1.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
bcrypt                        4.0.1
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.10.0
bleach                        5.0.1
certifi                       2022.9.24
cffi                          1.15.1
chardet                       5.0.0
charset-normalizer            2.1.1
click                         8.1.3
cloudpickle                   2.2.0
colorama                      0.4.6
contourpy                     1.0.6
cookiecutter                  2.1.1
cryptography                  38.0.3
cycler                        0.11.0
debugpy                       1.6.3
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
docstring-to-markdown         0.10
docutils                      0.19
entrypoints                   0.4
executing                     1.2.0
fastjsonschema                2.16.2
flake8                        5.0.4
fonttools                     4.38.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            5.0.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.17.1
ipython                       7.34.0
ipython-genutils              0.2.0
isort                         5.10.1
jaraco.classes                3.2.3
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.17.0
jupyter_client                7.4.5
jupyter_core                  5.0.0
jupyterlab-pygments           0.2.2
keyring                       23.11.0
kiwisolver                    1.4.4
lazy-object-proxy             1.8.0
MarkupSafe                    2.1.1
matplotlib                    3.6.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mistune                       2.0.4
more-itertools                9.0.0
mypy-extensions               0.4.3
nbclient                      0.7.0
nbconvert                     7.2.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
numpy                         1.23.4
numpydoc                      1.5.0
packaging                     21.3
pandocfilters                 1.5.0
paramiko                      2.12.0
parso                         0.8.3
pathspec                      0.10.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.3.0
pip                           22.3.1
platformdirs                  2.5.3
pluggy                        1.0.0
prompt-toolkit                3.0.32
psutil                        5.9.4
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.9.1
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.5.0
Pygments                      2.13.0
pylint                        2.15.5
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyrsistent                    0.19.2
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.6.0
python-slugify                6.1.2
pytoolconfig                  1.2.2
pytz                          2022.6
pywin32                       305
pywin32-ctypes                0.2.0
PyYAML                        6.0
pyzmq                         24.0.1
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.2.1
qtconsole                     5.4.0
QtPy                          2.3.0
requests                      2.28.1
rope                          1.4.0
Rtree                         1.0.1
setuptools                    63.2.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.3.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.0
spyder-kernels                2.4.0
stack-data                    0.6.0
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.6
tornado                       6.2
traitlets                     5.5.0
ujson                         5.5.0
urllib3                       1.26.12
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
whatthepatch                  1.0.2
wrapt                         1.14.1
yapf                          0.32.0
zipp                          3.10.0

```
</details>

**Comment by ccordoba12** [comment] 2022-11-28 16:04
Hey @vahidsafavi, thanks for reporting. We haven't this behavior, but please post a simple script that generates this problem to see if we can reproduce it on our side.

**Comment by vahidsafavi** [comment] 2022-11-28 22:28
![image](https://user-images.githubusercontent.com/81710987/204393392-c696cb03-5af3-4162-8a8a-c67d81443324.png)
Hi Carlos
If I close console and then hit enter (no input) a few times, the issue subsides significantly. If I close console and just try to run, the issue happens vary frequently.
Cheers
Vahid

**Comment by vahidsafavi** [comment] 2022-11-28 22:29
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 28 14:12:05 2022

@author: VahidSafavi_iy
"""
import json
import numpy as np
import time

print('\n')
time.sleep(1)

#Initialize dict structure to be dimped in jason file at the end
jdict={}

#define script revision to be recorded in json file
jdict['jsontype']='Simple Test'
jdict['jsonrev']='0.0'

#tell user which revision is this
print('\n')
print('Trying to reproduce Issu #20124')
for II in jdict:
    print(II, ' = ', jdict[II])
print('\n')

#define test speeds and temperatures
speeds=input('Speed levels (separate values with commas) = ')
# Please enter 100,200,300
temps=input('Temperature levels (separate values with commas) = ')
# Please enter 50,60,70,80
speeds=list(map(float, speeds.split(',')))
temps=list(map(float, temps.split(',')))
nspeeds=len(speeds)
ntemps=len(temps)
jdict['Test_Speeds']=speeds
jdict['Test_Temperatures']=temps

#Create json file
with open('test output.json', 'w', encoding='utf-8') as f:
    json.dump(jdict, f, ensure_ascii=False, indent=2)

**Comment by vahidsafavi** [comment] 2022-11-28 22:29
I couldn't attache the .py file!

**Comment by ccordoba12** [comment] 2022-11-28 23:34
Don't worry, that's fine. I'll check your code later this week.

Also, do you have a particular Graphics backend set in

    Preferences > IPython console > Graphics > Graphics backend?

**Comment by vahidsafavi** [comment] 2022-11-29 02:15
There is no urgency for a fix. It looks like one can easily survive by restarting console often and hitting "Enter" a few times.

**Comment by ccordoba12** [comment] 2022-12-12 18:00
> Looked it up: I have changed that setting to "QT5"

Ok, please change it back to `Inline`. That could help.

> There is no urgency for a fix. It looks like one can easily survive by restarting console often and hitting "Enter" a few times.

Ok, that's good to know. I'm leaving this for 5.4.2 to take a deeper look at it.

**Comment by vahidsafavi** [comment] 2022-12-12 18:15
Thank you very much. Looking forward to 5.4.2 release.
-Vahid

**Comment by FabienFellay** [comment] 2022-12-29 12:10
I also have this issue with all scripts on Windows and Linux. It seems that it only happens when the option *'Remove all variables before execution'* is enabled in the *'Run'* tab of the preferences: what actually freezes is the automatic removal of variables when pushing F5 (consider this when you will have time to look at it).

**Comment by ccordoba12** [comment] 2023-05-02 16:57
Closing as a duplicate of issue #16138.

**Closed by ccordoba12** 2023-05-02 16:57 UTC
Labels: type:Bug, component:IPython Console
