### ISSUE TITLE
An error window at Spyder IDE startup

### ISSUE THREAD

**Issue by didier31** [spyder-ide/spyder#6496] opened 2018-02-22 16:54 UTC
## Description

**What steps will reproduce the problem?**

1. Run spyder.exe

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\users\didier\appdata\local\programs\python\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.1
* Qt Versions: 5.10.0, PyQt5 5.10 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-23 15:09
Thanks for reporting. This is a duplicate of #4958 and it'll be fixed in our 3.2.7 version, to be released in a couple of days.

In the meantime, please go to

     Preferences > Python interpreter

and select the `Default` option.

**Closed by ccordoba12** 2018-02-23 15:09 UTC
