### ISSUE TITLE
ModuleNotFoundError("No module named 'pandas'",)

### ISSUE THREAD

**Issue by Chanarin** [spyder-ide/spyder#7867] opened 2018-09-09 08:24 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1083, in copy
    obj = self.delegate.get_value(idx)
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1381, in get_value
    return self.get_value_func(name)
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 284, in get_value
    value = self.shellwidget.get_value(name)
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 95, in get_value
    raise ValueError(msg)
ValueError: ModuleNotFoundError("No module named 'pandas'",)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.5
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2018-09-09 15:53
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by ccordoba12** [comment] 2018-09-18 13:44
Closing because of lack of response.

**Closed by ccordoba12** 2018-09-18 13:44 UTC
Labels: status:Awaiting Followup

**Comment by waageesh** [comment] 2020-04-30 15:05
Hi @ccordoba12  , 
I am getting same Error in Spyder Ipython console.
I have installed Spyder using PIP and created a virtualenvironment and istalled sklearn , pandas, numpy, Django and django_restframework in virtualenv,
I have checked python versions in virtualenv created by runing query

> `python -c  "import sys;print(sys.executable)"`
> `C:\Users\Jyothi\AppData\Local\Programs\Python\Python38-32\Scripts\spyder3.exe`

it gives python console that is being run in the environment
now i opened spyder and changed the default spyder's python console to above python.exe in virtual environment as below

> Preferences > Python Interpreter > Use the following interpreter

Later checked what all libraries are available in spyder now using 
`pip freeze.`
```
asgiref==3.2.7Note: you may need to restart the kernel to use updated packages.
backcall==0.1.0
cloudpickle==1.4.1
colorama==0.4.3
decorator==4.4.2
Django==3.0.5

djangorestframework==3.11.0
gunicorn==20.0.4
ipykernel==5.2.1
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.17.0
joblib==0.14.1
jupyter-client==6.1.3
jupyter-core==4.6.3
numpy==1.18.3
parso==0.7.0
pickleshare==0.7.5
prompt-toolkit==3.0.5
psycopg2==2.8.4
Pygments==2.6.1
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
pyzmq==19.0.0
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.14.0
sklearn==0.0
spyder-kernels==1.9.0
sqlparse==0.3.1
tornado==6.0.4
traitlets==4.3.3
wcwidth==0.1.9
```
packages and libraries i have installed in my virtual environment are all available in Spyder Ipython console
when i checked 
`import pandas as pd`
`Traceback (most recent call last):`
`  File "<ipython-input-1-7dd3504c366f>", line 1, in <module>`
`ModuleNotFoundError: No module named 'pandas'`

I have even restarted the kernel multiple time, still the same error

How to run/open spyder with created virtualenv in django ?
please help me

![image](https://user-images.githubusercontent.com/16902073/80726214-bf6d1480-8b21-11ea-93a0-4a877137f808.png)

![image](https://user-images.githubusercontent.com/16902073/80726423-fba07500-8b21-11ea-9238-ffd9ffbbc043.png)

![image](https://user-images.githubusercontent.com/16902073/80726422-fba07500-8b21-11ea-94fb-f5db0fd0ecb3.png)
