### ISSUE TITLE
Issue with spyder

### ISSUE THREAD

**Issue by ankurkumar983** [spyder-ide/spyder#7878] opened 2018-09-11 11:27 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 259, in to_string
    fmt_values = self._get_formatted_values()
  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 249, in _get_formatted_values
    float_format=self.float_format, na_rep=self.na_rep)
  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1822, in format_array
    return fmt_obj.get_result()
  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1842, in get_result
    fmt_values = self._format_strings()
  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1888, in _format_strings
    fmt_values.append(u' {v}'.format(v=_format(v)))
  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1867, in _format
    return u'{x}'.format(x=x)
  File "d:\Profiles\ankumar\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\base.py", line 59, in __str__
    return self.__unicode__()
  Fi

**Comment by ccordoba12** [comment] 2018-09-11 15:37
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by ccordoba12** [comment] 2018-09-18 13:42
Closing because of lack of response.

**Closed by ccordoba12** 2018-09-18 13:42 UTC
Labels: status:Awaiting Followup
