### ISSUE TITLE
errors when loading sklearn and scipy modules

### ISSUE THREAD

**Issue by sinanmut** [spyder-ide/spyder#5385] opened 2017-10-03 15:45 UTC
These errors are happening in spyder3 console (ipython), but if I run the ipython in the terminal I don't get any errors.

Any suggestions?
 
import scipy.special as spec
Traceback (most recent call last):
  File "<ipython-input-9-f4252bb1d87c>", line 1, in <module>
    import scipy.special as spec
  File "/usr/lib/python3.6/site-packages/scipy/special/__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "/usr/lib/python3.6/site-packages/scipy/special/_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

ImportError: cannot import name '_ellipsoid'

---------------------------------------------------------

import sklearn
Traceback (most recent call last):
  File "<ipython-input-3-b7c74cbf5af0>", line 1, in <module>
    import sklearn
  File "/usr/lib/python3.6/site-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/usr/lib/python3.6/site-packages/sklearn/base.py", line 12, in <module>
    from .utils.fixes import signature
  File "/usr/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "/usr/lib/python3.6/site-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/usr/lib/python3.6/site-packages/sklearn/utils/fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "/usr/lib/python3.6/site-packages/scipy/sparse/linalg/__init__.py", line 114, in <module>
    from .dsolve import *
  File "/usr/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/__init__.py", line 60, in <module>
    from .linsolve import *
  File "/usr/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 15, in <module>
    import scikits.umfpack as umfpack
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 946, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 881, in _find_spec
  File "<frozen importlib._bootstrap>", line 855, in _find_spec_legacy
  File "/usr/lib/python3.6/site-packages/pyximport/pyximport.py", line 253, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)
  File "/usr/lib/python3.6/imp.py", line 270, in find_module
    "not {}".format(type(path)))
RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

**Comment by ccordoba12** [comment] 2017-10-04 06:22
This seems like a duplicate of #4838. Unfortunately we don't know how to solve it, sorry.

**Closed by ccordoba12** 2017-10-04 06:22 UTC
