### ISSUE TITLE
Error when importing rdflib

### ISSUE THREAD

**Issue by Poux-Florent** [spyder-ide/spyder#6219] opened 2018-01-16 14:35 UTC
## Description

**What steps will reproduce the problem?**

1. using anaconda
2. installing rdflib via pip
3. launching a basic "import rdflib"

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\DEV\Anaconda\envs\spc\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "D:\DEV\Anaconda\envs\spc\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 220, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "D:\DEV\Anaconda\envs\spc\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 351, in handle_exec_method
    view = ast.literal_eval(literal)
  File "D:\DEV\Anaconda\envs\spc\lib\ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "D:\DEV\Anaconda\envs\spc\lib\ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "D:\DEV\Anaconda\envs\spc\lib\ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "D:\DEV\Anaconda\envs\spc\lib\ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "D:\DEV\Anaconda\envs\spc\lib\ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "D:\DEV\Anaconda\envs\spc\lib\ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
Va

**Comment by CAM-Gerlach** [comment] 2018-01-16 22:07
Also, appears to be a direct duplicate of #4855 , and so can probably be closed on that grounds unless it is shown to reoccur in Spyder 3.2.6.

**Comment by CAM-Gerlach** [comment] 2018-01-24 08:22
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-01-24 08:22 UTC
Labels: status:AwaitingFollowup
