### ISSUE TITLE
no file menu with python 3

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder#2942] opened 2016-01-20 09:22 UTC
With the current code (commit 03888fd423680a23c0b0584e5c2b95e24cf81443) I have no file menu when I start with `python3 bootstrap.py`. There are no warnings or errors.

With `python2 bootstrap.py` there are no problems.

**Comment by ccordoba12** [comment] 2016-01-20 15:27
What platform are you working on?

**Comment by ccordoba12** [comment] 2016-01-20 15:28
I mean: Windows, Linux or Mac? And also: PyQt4 or PyQt5?

**Comment by eendebakpt** [comment] 2016-01-20 15:41
``` 
eendebakpt@marmot:~/develop/spyder$ python3 bootstrap.py --no-apport
Executing Spyder from source checkout
NOTICE: Ubuntu Apport exception hook is disabed
Revision 03888fd, Branch: master
01. Patched sys.path with /home/eendebakpt/develop/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 3.4.3 64bits, Qt 5.2.1, PyQt5 5.2.1 on Linux]
04. Executing spyder.main()
Bootstrap completed in 00:00:00.3443
```

**Comment by ccordoba12** [comment] 2016-02-07 20:30
I'm sorry, I'm unable to reproduce this problem.

**Comment by eendebakpt** [comment] 2016-02-08 09:41
With Qt4 the system is working fine (latest checkout from git)

``` 
python3 bootstrap.py --gui pyqt
```

The system with Qt5 is still missing the file menu. I will check the issue again once I update my system (currently ubuntu 14.04, will go to 16.04).

**Comment by ccordoba12** [comment] 2016-02-08 13:33
My configuration is almost the same (PyQt5, Kubuntu 14.04) and I can't reproduce this error.

**Comment by Nodd** [comment] 2016-02-08 14:46
I seems that I can reproduce it but randomly. It's the same symptoms as when a transparent QWidget is placed at the default position (0, 0), so that the clicks don't pass the the underlying menus.
Maybe it's random because the widgets are not always created in the same order ?

**Comment by ccordoba12** [comment] 2017-02-20 04:32
This was fixed in master.

**Closed by ccordoba12** 2017-02-20 04:32 UTC
