### ISSUE TITLE
After update to 4.1 I get "An error ocurred while starting the kernel" on Windows 10

### ISSUE THREAD

**Issue by michaelklachko** [spyder-ide/spyder#11833] opened 2020-03-17 20:21 UTC
Just did `conda update spyder` from Anaconda console on my Windows 10 PC. Spyder was updated from 4.0 to 4.1.
When launched by clicking on the icon pointing to `C:\ProgramData\Miniconda3\Scripts\spyder-script.py` (that's how I have always launched it) the Spyder got launched successfully, but I see the following error displayed in Console 1/A: 

```
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\ProgramData\Miniconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\ProgramData\Miniconda3\lib\site‑packages\jupyter_client\manager.py", line 267, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, env=env, **kw)
File "C:\ProgramData\Miniconda3\lib\site‑packages\jupyter_client\manager.py", line 211, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\ProgramData\Miniconda3\lib\site‑packages\jupyter_client\launcher.py", line 135, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 709, in __init__
restore_signals, start_new_session)
File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 997, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

However, if I instead launch spyder by typing `spyder` in Anaconda prompt, it launches without that error shown (works fine). The Anaconda prompt is launched by clicking on icon pointing to `%windir%\System32\cmd.exe "/K" C:\ProgramData\Miniconda3\Scripts\activate.bat C:\ProgramData\Miniconda3`

To reiterate: it worked fine this morning *before* the update to 4.1.

* Spyder version: 4.1
* Python version: 3.6
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.2 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29 (OK)
matplotlib >=2.0.0             :  3.2.0 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

**Comment by ccordoba12** [comment] 2020-03-17 20:54
Duplicate of #11819

**Comment by ccordoba12** [comment] 2020-03-17 20:54
We're investigating the issue, but the information you provided above is very valuable.

**Closed by ccordoba12** 2020-03-17 20:54 UTC
