### ISSUE TITLE
Can't open dataframes in variable explorer

### ISSUE THREAD

**Issue by annukkaa** [spyder-ide/spyder#13825] opened 2020-09-21 09:57 UTC
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps will reproduce the problem?

Create a Dataframe: 

# Import pandas library 
```import pandas as pd```
  
# initialize list of lists 
```data = [['A', 1], ['B', 2], ['C', 3]]```
  
# Create the pandas DataFrame 
```df = pd.DataFrame(data, columns = ['Letter', 'Number'])```

Try to open it in the variable explorer

### What is the expected output? What do you see instead?

Can't open dataframe variables when opening them in variable explorer
An issue reporter window pops up: "Spyder has encountered an internal problem"

### Paste Traceback/Error Below (if applicable)

```python-traceback
RecursionError: maximum recursion depth exceeded
```

## Versions

* Spyder version: 4.1.5
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04.4

### Dependencies

```
conda install pandas
```

**Comment by ccordoba12** [comment] 2020-09-21 15:35
Hey @annukkaa, thanks for reporting. This is a duplicate of issue #13620.

The solution for now is to update Pandas in the same environment where Spyder is installed to 1.1.0.

**Closed by ccordoba12** 2020-09-21 15:35 UTC

**Comment by annukkaa** [comment] 2020-09-21 15:44
Thanks, it worked when I updated pandas
