### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by 17150934** [spyder-ide/spyder#14887] opened 2021-03-08 00:59 UTC
### What steps will reproduce the problem?

Just installed spyder 4.2.1 and encounteredan internal problem,clicked on details it showed 
File "/home/neousys/anaconda3/envs/flow/lib/python3.7/site-packages/spyder/app/mainwindow.py",line 2198,in update_source_menu
   self.editor.refresh_formatter_name()
AttributeError: 'NoneType' object has no attribute 'refresh_formatter_name'

### Traceback
```python-traceback
  File "/home/neousys/anaconda3/envs/flow/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 2198, in update_source_menu
    self.editor.refresh_formatter_name()
AttributeError: 'NoneType' object has no attribute 'refresh_formatter_name'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-136-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  41.0.0 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.0.0 (OK)
numpy >=1.7                     :  1.20.0 (OK)
pandas >=1.1.1                  :  0.24.2 (NOK)
scipy >=0.17.0                  :  1.1.0 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-03-08 05:10
Hey @17150934, thanks for reporting. Could you give us a step by step description of how you got this error? Otherwise it won't be possible for us to understand how to fix it.

Thanks!

**Comment by ccordoba12** [comment] 2021-03-16 02:02
Closing as a duplicate of issue #14901.

**Closed by ccordoba12** 2021-03-16 02:02 UTC
Labels: status:Awaiting Followup
