### ISSUE TITLE
Its appears why Ctrl-S  pressing for save

### ISSUE THREAD

**Issue by VasilijKolomiets** [spyder-ide/spyder#17004] opened 2021-12-13 09:20 UTC
### What steps will reproduce the problem?

I was just pressing Ctrl-S after adding some new rows

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\manager\anaconda3\envs\post_meest\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1904, in _save_file
    self.modification_changed(index=index)
  File "C:\Users\manager\anaconda3\envs\post_meest\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2360, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.7.11
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by steff456** [comment] 2021-12-13 18:13
Hi @VasilijKolomiets,

Can you tell me if the error persists after restarting Spyder? If so, can you give me a set of instructions to try to reproduce it on my end?

**Comment by VasilijKolomiets** [comment] 2022-01-26 08:13
> Shure - not.
After restart all works well along 2-3 hours.
Than - all again )

**Comment by ccordoba12** [comment] 2022-01-27 23:01
@VasilijKolomiets, do you have the autoformat on save option activated?

![imagen](https://user-images.githubusercontent.com/365293/151457527-363bd575-8802-4967-ab85-8853b4c1003e.png)

**Comment by VasilijKolomiets** [comment] 2022-01-28 03:55
Yes, shure

Завантажте Outlook для Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ccordoba12** [comment] 2022-01-28 14:55
Ok, then this is a duplicate of issue #14639. We'll try to fix it in our next version.

**Closed by ccordoba12** 2022-01-28 14:55 UTC
Labels: status:Awaiting Followup
