### ISSUE TITLE
spyder tool/ perference doesn`t work

### ISSUE THREAD

**Issue by Rachecave** [spyder-ide/spyder#5835] opened 2017-11-26 11:57 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/sunxuxiang/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2609, in edit_preferences
    widget.initialize()
  File "/home/sunxuxiang/anaconda2/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 77, in initialize
    self.load_from_conf()
  File "/home/sunxuxiang/anaconda2/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 381, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by jitseniesen** [comment] 2017-11-26 16:56
This looks like a duplicate of #5578, which will be fixed in Spyder 3.2.5. In the meantime, the only solution I know is to reset your Spyder preferences by running
```
spyder --reset
```
from a terminal.

I am closing this issue on the assumption that it is indeed a duplicate. Feel free to continue to comment and/or re-open if necessary.

**Closed by jitseniesen** 2017-11-26 16:56 UTC
