### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by ahjamesxi** [spyder-ide/spyder#21615] opened 2023-12-14 13:46 UTC
### What steps will reproduce the problem?

No special step. Just launch spyder and it crashes

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001999B9B4660> still has pending operation at deallocation, the process may crash
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.9.18 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.8.0 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.1.1 (OK)
scipy >=0.17.0                                   :  1.9.1 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment] 2023-12-14 15:13
Hey @ahjamesxi, thanks for reporting. I'm going to close this issue as a duplicate of #21610, as you already found out.

**Closed by ccordoba12** 2023-12-14 15:13 UTC
