### ISSUE TITLE
Size of active vs non-active toolbar buttons

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9772] opened 2019-07-07 10:58 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
There is a small width change between active and non-active toolbar buttons:

![sizechange](https://user-images.githubusercontent.com/8114497/60767312-a5f06d00-a0b6-11e9-9f09-f83485cfbc4c.gif)

### What steps reproduce the problem?

1. Open a file
2. Make some edits and note the moving toolbar buttons to the right of the save button

### What is the expected output? What do you see instead?
Same width

## Versions

* Spyder version: 4.0.0.dev0
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.0 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.10 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment] 2019-07-07 18:55
I don't see an issue here. As it's clear from the video you posted, the size of the first tab changes because we add an asterisk next to its name to signal that the file is dirty (i.e. that it has unsaved changes).

So, I think we should close this issue. @oscargus, what do you think?

**Comment by oscargus** [comment] 2019-07-10 21:38
It is the toolbar buttons, not the tabs that is the issue here. They move right as the save and save all buttons are activated.

**Comment by oscargus** [comment] 2019-07-10 21:49
I just noticed another width-change of the toolbar buttons while browsing the menus. Not really sure what causes it but will try to record a video of it. It seems to happen when first clicking on a menu and then going to another menu. When going to the second menu the toolbar shrinks a few pixels to expand again when clicking in the editor/disabling the menus. This happens at least when all toolbars are activated, but will try to come up with a more detailed description.

**Comment by goanpeca** [comment] 2019-07-10 22:24
@oscargus I will check with the latest version of QDarkStyle to see if the issue is still present. Just to check, @dpizzetta do you know if this has this been corrected?

**Comment by jnsebgosselin** [comment] 2019-07-11 01:29
I confirm this is happening in the latest version of QDarkStyle on dev, I think an issue should be opened there to fix it.

**Comment by ccordoba12** [comment] 2019-07-11 07:54
Ok, thanks @jnsebgosselin for your help.

@oscargus, could you reopen this issue in

https://github.com/ColinDuquesnoy/QDarkStyleSheet

? Thanks!

**Closed by ccordoba12** 2019-07-11 07:54 UTC
Labels: status:Awaiting Followup

**Comment by oscargus** [comment] 2019-07-11 10:04
I'll open an issue. (I guess one just needs to add a bit of spacing to disabled QToolButton.)
