### ISSUE TITLE
Execution buttons get grey forever

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#20590] opened 2023-02-24 14:43 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After launching some file from the button (F5-like), all the launch buttons remain grey (and the related menu titles as well), once the processed is finished. Sometimes the debugs button as well, sometimes no (?).
I can relaunch the file from the ipython console, using runfile(...) or arrows key. But the buttons keep grey forever. I update the source about once a week, it happens since a week or so.

## Versions
* Spyder version: 6.0.0.dev0 7512977f1 (pip)
* Python version: 3.10.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.10.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.5.0.dev0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.3.2 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  3.0.0.dev0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)

```

**Comment by ccordoba12** [comment] 2023-02-24 15:42
Hey @sylvain-bougnoux, thanks for reporting. Could you provide a series of steps to reproduce this problem? Otherwise, it'll be difficult for us to address it.

**Comment by sylvain-bougnoux** [comment] 2023-02-24 16:10
Sure but pretty straightforward. Open spyder, some tabs are already filled with py scripts. Select a tab. Press the run button (F5), the execution related buttons get grey, the scripts is processed. It takes a few minutes (1-2). Then the script returns (ends). I've the prompt in the console but the buttons remain grey preventing a 2nd launch. AFAIR, it may take several iterations for the problem to occur. The mode is to run in the current console (with current globals). As nobody reported it, I am afraid it is more complex than that! Thanks Carlos, I always wonder how you can deal with so many issues ;-). 
PS : I've not run 'spyder --reset' because I am afraid to lose my config. I am not sure if backing the '.spyder' folder allows me to restore it?

**Comment by sylvain-bougnoux** [comment] 2023-03-01 16:40
I am afraid a screenshot is difficult because the script runs for a while (and I need cumbersome authorizations). BUT in the last git version : 6.0.0.dev0 91a741123 (pip) from yesterday the executable icons do not turn grey anymore at all (for a few attempts)! Therefore are usable when the script returns (actually even before it returns, which is weird!). Either there is a global issue turning on/off these buttons, either someone made a tentative fix? I will try --reset and keep you informed. Thanks.

**Comment by ccordoba12** [comment] 2023-03-04 00:14
> Either there is a global issue turning on/off these buttons, either someone made a tentative fix? I will try --reset and keep you informed. Thanks.

This is quite strange and we definitely need to take a look at it for Spyder 6.

**Comment by ccordoba12** [comment] 2023-11-16 14:37
Closing this one for now because it seems hard to reproduce.

**Closed by ccordoba12** 2023-11-16 14:37 UTC
Labels: type:Bug, component:Run
