### ISSUE TITLE
I have python 3.8 installed along with my Anaconda Spyder setup. When trying to upgrade to spyder 4.2.0, error message indicated that spyder 3.8 is not compatible with python 3.8

### ISSUE THREAD

**Issue by NaderNazemi** [spyder-ide/spyder#14417] opened 2020-12-13 16:37 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have python 3.8 installed along with my Anaconda Spyder setup. When trying to upgrade to spyder 4.2.0, error message indicated that spyder 3.8 is not compatible with python 3.8

### What steps reproduce the problem?

1. conda install spyder=4.2.0
2. 
3. 

### What is the expected output? What do you see instead?

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spyder=4.2.0 -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-12-13 20:28
Hey @NaderNazemi, thanks for reporting. This is a duplicate of issue #14416.

I'll post an answer there about this problem.

**Closed by ccordoba12** 2020-12-13 20:28 UTC

**Comment by NaderNazemi** [comment] 2020-12-13 21:05
I appreciate it.
Thank you very much.
