### ISSUE TITLE
Error importing scipy module when using external interpreter(Python 3.11.1)

### ISSUE THREAD

**Issue by LuYupeng311** [spyder-ide/spyder#20638] opened 2023-03-05 14:29 UTC
### What steps will reproduce the problem?

import scipy
Traceback (most recent call last):

  File F:\Spyder\pkgs\scipy\__init__.py:184
    from scipy._lib._ccallback import LowLevelCallable

  File F:\Spyder\pkgs\scipy\_lib\_ccallback.py:1
    from . import _ccallback_c

ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (F:\Spyder\pkgs\scipy\_lib\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  Cell In[2], line 1
    import scipy

  File F:\Spyder\pkgs\scipy\__init__.py:189
    raise ImportError(msg) from e

ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

## Versions

* Spyder version: 5.4.2  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<9.0.0              :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.3 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.2.8 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.12.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.4 (OK)
pygments >=2.0                       :  2.14.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.10 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                 :  1.7.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.3.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  66.0.0 (OK)
sphinx >=0.6.6                       :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0        :  2.4.2 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.2.1 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.33 (OK)
matplotlib >=3.0.0                   :  3.6.3 (OK)
numpy >=1.7                          :  1.24.1 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.10.0 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
alabaster                     0.7.13
arrow                         1.2.3
astroid                       2.13.2
asttokens                     2.2.1
attrs                         22.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.12.0
bleach                        5.0.1
certifi                       2022.12.7
cffi                          1.15.1
chardet                       5.1.0
charset-normalizer            3.0.1
click                         8.1.3
cloudpickle                   2.2.0
colorama                      0.4.6
coloredlogs                   15.0.1
comm                          0.1.2
contourpy                     1.0.7
cookiecutter                  2.1.1
cryptography                  39.0.0
cycler                        0.11.0
Cython                        0.29.33
debugpy                       1.6.5
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
docstring-to-markdown         0.11
docutils                      0.19
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     1.2.0
fastjsonschema                2.16.2
ffmpeg-python                 0.2.0
flake8                        6.0.0
Flask                         2.2.3
fonttools                     4.38.0
future                        0.18.3
gitdb                         4.0.10
GitPython                     3.1.31
humanfriendly                 10.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
importlib-resources           5.10.2
inflection                    0.5.1
ipykernel                     6.20.2
ipython                       8.8.0
ipython-genutils              0.2.0
isort                         5.11.4
itsdangerous                  2.1.2
jaraco.classes                3.2.3
jedi                          0.18.2
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.1.3
jupyterlab-pygments           0.2.2
keyring                       23.13.1
kiwisolver                    1.4.4
lazy-object-proxy             1.9.0
MarkupSafe                    2.1.2
matplotlib                    3.6.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mfix                          22.4.2
mistune                       2.0.4
more-itertools                9.0.0
mpmath                        1.2.1
mypy-extensions               0.4.3
nbclient                      0.7.2
nbconvert                     7.2.8
nbformat                      5.7.3
nest-asyncio                  1.5.6
numpy                         1.24.1
numpydoc                      1.5.0
openpyxl                      3.0.10
packaging                     23.0
pandas                        1.5.2
pandocfilters                 1.5.0
paramiko                      2.12.0
parso                         0.8.3
pathspec                      0.10.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.0.1
pkgutil_resolve_name          1.3.10
platformdirs                  2.6.2
pluggy                        1.0.0
prompt-toolkit                3.0.36
psutil                        5.9.4
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.10.0
pycparser                     2.21
pydocstyle                    6.2.3
pyflakes                      3.0.1
Pygments                      2.14.0
pylint                        2.15.10
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
pyqtgraph                     0.13.2
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyreadline3                   3.4.1
pyrsistent                    0.19.3
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.1
pytoolconfig                  1.2.4
pytz                          2022.7.1
pywin32                       305
pywin32-ctypes                0.2.0
pywinpty                      2.0.10
pyxdg                         0.28
PyYAML                        6.0
pyzmq                         24.0.1
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.0
QtPy                          2.3.0
requests                      2.28.2
rope                          1.7.0
scipy                         1.10.0
setuptools                    66.0.0
simplejson                    3.18.3
six                           1.16.0
smmap                         5.0.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        6.1.3
sphinxcontrib.applehelp       1.0.3
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.2
spyder-kernels                2.4.2
spyder-terminal               1.2.2
stack-data                    0.6.2
sympy                         1.11.1
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.6
tornado                       6.2
traitlets                     5.8.1
typing_extensions             4.4.0
ujson                         5.7.0
urllib3                       1.26.14
vtk                           9.2.6
watchdog                      2.2.1
wcwidth                       0.2.6
webencodings                  0.5.1
Werkzeug                      2.2.3
whatthepatch                  1.0.3
wheel                         0.38.4
wrapt                         1.14.1
yapf                          0.32.0
zipp                          3.11.0

```
</details>

**Comment by ccordoba12** [comment] 2023-03-05 18:30
Hey @LuYupeng311, thanks for reporting. This is a duplicate of issue #20242 and we'll fix it in our next version (5.4.3), to be released at the end of the month.

Please read that issue for a workaround until that version is released.

**Closed by ccordoba12** 2023-03-05 18:30 UTC
