### ISSUE TITLE
PyTorch Internal Error

### ISSUE THREAD

**Issue by Swarna2001** [spyder-ide/spyder#18914] opened 2022-08-03 06:11 UTC
### What steps will reproduce the problem?

I have created a virtual environment and installed PyTorch library there. When I execute the statements 
```
import torch
x = torch.rand(3)
```
the code works, and output is displayed but this internal error keeps popping up. I don't know what's the issue.

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "D:\Anaconda\lib\site-packages\spyder_kernels\comms\commbase.py", line 314, in _comm_message
    buffer = cloudpickle.loads(msg['buffers'][0],
ModuleNotFoundError: No module named 'torch'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment] 2022-08-03 15:48
Hi @Swarna2001 thank you for the feedback! This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/16348 . A fix for that was implemented in Spyder 5.2.0 and the latest Spyder release is 5.3.2. Could you update and check again?

To update you will need to create a new env for the Spyder installation using the conda-forge channel since the default Anaconda channel doesn't have the latests Spyder releases. For that, run from an Anaconda prompt something like the this:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder

After that you can also access the new Spyder installation from the `spyder-cf` environment using the created shortcut (you can search for it from the start menu by typing `Spyder (spyder-cf)`.

Let us know if something of the above helps!

**Comment by Swarna2001** [comment] 2022-08-04 13:45
Hi @dalthviz. Thank you for the immediate reply. 

You had asked me to create a new environment `spyder-cf` using the instructions you had given. However, in order to use PyTorch library, I had to create a virtual environment for that separately (`pytorch`). So how am I supposed to invoke the `pytorch` environment within this `spyder-cf` environment? Won't that cause any issues?

**Comment by dalthviz** [comment] 2022-08-04 16:16
You can connect a custom interpreter to Spyder. For that you need to install spyder-kernels in the env you want to use along side other packages (like in your case PyTorch) and set a custom interpreter from Spyder preferences. For more info about that you can check:

* Spyder wiki about working with environments and packages: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
* Spyder docs FAQ page: https://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if that info helps!

**Comment by Swarna2001** [comment] 2022-08-05 17:57
@dalthviz Thank you so much. The wiki helped a lot, and now everything is working perfectly. Thanks once again :)

**Comment by dalthviz** [comment] 2022-08-05 18:06
Awesome! Glad to hear that you got Spyder working! I will close this issue as duplicate then but if you have more questions let us know in a new issue

**Closed by dalthviz** 2022-08-05 18:06 UTC
Labels: resolution:Duplicate, resolution:Completed, status:Awaiting Followup
