### ISSUE TITLE
SyntaxError when evaluating ast of autosave file

### ISSUE THREAD

**Issue by molirun** [spyder-ide/spyder#11499] opened 2020-02-08 10:16 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\MisterOIlz\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\MisterOIlz\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\Users\MisterOIlz\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 955, in setup
    self.editor = Editor(self)
  File "C:\Users\MisterOIlz\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 178, in __init__
    self.autosave.try_recover_from_autosave()
  File "C:\Users\MisterOIlz\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 176, in try_recover_from_autosave
    files_to_recover, pidfiles = self.get_files_to_recover()
  File "C:\Users\MisterOIlz\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 149, in get_files_to_recover
    txt_as_dict = ast.literal_eval(txt)
  File "C:\Users\MisterOIlz\Anaconda3\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\MisterOIlz\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0

    ^
SyntaxError: unexpected EOF while parsing
[13252:12040:0208/170603.661:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Window 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-02-09 16:04
@jitseniesen, maybe this happen for files whose paths have unicode characters.

**Comment by PrinceFPF** [comment] 2020-02-10 15:06
@molirun Hello，my dear brother, I encountered a problem similar to yours, please try to execute the following command to solve it.
```
conda update --force conda
```

**Comment by molirun** [comment] 2020-02-10 16:14
> @molirun Hello，my dear brother, I encountered a problem similar to yours, please try to execute the following command to solve it.
> 
> ```
> conda update --force conda
> 
It not work for me.

**Comment by RainyRen** [comment] 2020-02-11 09:13
Hi, I met the same problem

Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "C:\Software\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\Software\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 955, in setup
    self.editor = Editor(self)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 178, in __init__
    self.autosave.try_recover_from_autosave()
  File "C:\Software\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 176, in try_recover_from_autosave
    files_to_recover, pidfiles = self.get_files_to_recover()
  File "C:\Software\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 149, in get_files_to_recover
    txt_as_dict = ast.literal_eval(txt)
  File "C:\Software\Anaconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Software\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0

    ^
SyntaxError: unexpected EOF while parsing

My OS: winodws 10 pro, English version
Spyder: 4.0.1

**Comment by ccordoba12** [comment] 2020-02-11 17:06
@molirun, @RainyRen, please go to this directory:

    C:\Users\<your user>\.spyder-py3\autosave

and upload a screenshot with the contents of that directory.

**Comment by jitseniesen** [comment] 2020-02-11 17:24
This is probably the same issue as reported in #11375 

> please go to this directory:
> 
> ```
> C:\Users\<your user>\.spyder-py3\autosave
> ```
> 
> and upload a screenshot with the contents of that directory.

I am particularly interested if there are any files called like `pid6268.txt`, but with a different number. Please show us the contents of the file (it may be empty).

As a workaround, try deleting the file (after you tell us what's in it).

**Comment by molirun** [comment] 2020-02-12 09:36
> @molirun, @RainyRen, please go to this directory:
> 
> ```
> C:\Users\<your user>\.spyder-py3\autosave
> ```
> 
> and upload a screenshot with the contents of that directory.
![image](https://user-images.githubusercontent.com/43033884/74321908-a7ed7d80-4db5-11ea-8396-b1d9e3634e06.png)

**Comment by ccordoba12** [comment] 2020-02-12 17:06
@molirun, thanks! Now please open the file called `pid4288` and paste its contents here (if any).

**Comment by molirun** [comment] 2020-02-12 17:10
It is empty.

**Comment by ccordoba12** [comment] 2020-02-12 17:12
@molirunm, thanks!

@jitseniesen, I think that's the problem here. So simply skipping the autorecovery process if the pid file is empty should be enough to solve it.

**Comment by molirun** [comment] 2020-02-13 12:02
@jitseniesen @ccordoba12
Thank you so much. 
I can open Spyder when I deleted pidxxxx.txt file.

**Comment by ccordoba12** [comment] 2020-02-13 15:21
Duplicate of #11375

**Comment by ccordoba12** [comment] 2020-02-13 15:22
> This is probably the same issue as reported in #11375

You were right @jitseniesen.

**Closed by ccordoba12** 2020-02-13 15:21 UTC
Labels: component:Editor, type:Bug
