### ISSUE TITLE
Profiler not working - Script runs fine in console.

### ISSUE THREAD

**Issue by vancromy** [spyder-ide/spyder#12334] opened 2020-04-15 08:02 UTC
### What steps will reproduce the problem?

Step 1:
Click open button on Profiler and select file to be profiled.

Step 2:
Click OK. Issue reporter automatically opens and no profiling is completed ("Profiling, please wait" can still be seen in the profiler window though).

Spyder version: 4.1.2
Anaconda version: 4.8.3
Python version: 3.7.4
MacOS version: Catalina version 10.15.4

### Traceback
```python-traceback
  File "/Users/yvc/anaconda3/lib/python3.7/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 267, in <lambda>
    self.finished(ec, es))
  File "/Users/yvc/anaconda3/lib/python3.7/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 335, in finished
    self.show_errorlog()  # If errors occurred, show them.
  File "/Users/yvc/anaconda3/lib/python3.7/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 240, in show_errorlog
    readonly=True, size=(700, 500), parent=self).exec_()
TypeError: __init__() got an unexpected keyword argument 'size'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by jitseniesen** [comment] 2020-04-15 08:05
Thank you for your report. This is a duplicate of issue #11875 which is already fixed in our development version. The next release of Spyder will include this fix.

**Closed by jitseniesen** 2020-04-15 08:05 UTC
