### ISSUE TITLE
Changed editor settings.

### ISSUE THREAD

**Issue by n0dat** [spyder-ide/spyder#17266] opened 2022-01-31 03:05 UTC
### What steps will reproduce the problem?

All from top to bottom.

Disabled: Show Completion Details, Enable Code Snippers, Show Completions on the fly, Enable Fallback Provider, Enable Kite Provider, Enable Language Server Protocol (LSP) Provider, Enable Text Snippets Provider, and Enable Basic Linting

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\api.py", line 108, in apply_changes
    self.apply_callback()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\api.py", line 140, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\api.py", line 168, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Program Files\Spyder\pkgs\spyder\api\preferences.py", line 105, in wrapper
    func(opts)
  File "C:\Program Files\Spyder\pkgs\spyder\api\plugins\new_api.py", line 550, in apply_conf
    self.after_configuration_update(list(options_set))
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\completion\plugin.py", line 403, in after_configuration_update
    self.unregister_statusbar(provider_name)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\completion\plugin.py", line 477, in unregister_statusbar
    if id_ in container.statusbar_widgets[id_]:
TypeError: argument of type 'LSPStatusWidget' is not iterable
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2022-01-31 14:52
Hey @n0dat, thanks for reporting. This is a duplicate of issue #17262 and we'll fix it in our next version (5.3.0) to be released in March.

**Closed by ccordoba12** 2022-01-31 14:52 UTC
