### ISSUE TITLE
spyder has stopped

### ISSUE THREAD

**Issue by tanmoyndp** [spyder-ide/spyder#6615] opened 2018-03-06 12:06 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\tanmoy.g\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\tanmoy.g\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "C:\Users\tanmoy.g\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\Users\tanmoy.g\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "C:\Users\tanmoy.g\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1171, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  File "C:\

**Comment by ccordoba12** [comment] 2018-03-06 16:27
Please copy and paste the full error reported by Spyder from the error dialog. Since the one you posted above is incomplete, we can't help you.

**Comment by CAM-Gerlach** [comment] 2018-03-06 21:54
Please provide the requested information within one week (7 days), @tanmoyndp . Otherwise, this issue will be closed as we won't be able to reproduce and fix the error. Thanks.

**Comment by CAM-Gerlach** [comment] 2018-03-15 15:18
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-03-15 15:18 UTC
Labels: status:Awaiting Followup
