### ISSUE TITLE
Spyder closes when try to open file

### ISSUE THREAD

**Issue by Olivdrou** [spyder-ide/spyder#3903] opened 2016-12-31 00:43 UTC
## Description

**What steps will reproduce the problem?**

1. Try to open or save file 
2. 
3. 

**What is the expected output? What do you see instead?**
Windows message "Python has stop working - close program" (in french)
![image](https://cloud.githubusercontent.com/assets/24848499/21574824/7c3f259a-cefa-11e6-85c8-4cf79d014656.png)

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2016-12-31 06:06
Please try to update qt, pyqt and Spyder by running this command in a terminal (if you're using Anaconda)

    conda update qt pyqt spyder

and try again.

**Comment by Olivdrou** [comment] 2016-12-31 10:40
Try to run command : 

![installanaconda](https://cloud.githubusercontent.com/assets/24848499/21577063/4b8d6e22-cf4d-11e6-808f-59a71075cc2e.png)


Now, I am not able to open any one of the programs (spyder-anaconda navigator)
How should I proceed to re-built as asked ?
Sorry, I really knows nothing with all of this

**Comment by ccordoba12** [comment] 2016-12-31 19:57
@Olivdrou, don't worry about it. To revert to the previous state, please run

    conda install qt=5.6.0

@mingwandroid, have you seen this error before?

**Comment by Olivdrou** [comment] 2017-01-01 00:49
Hello again and thanks for your support,
Last command didn't change nothing. So I have remove and install again. In the same time I have remove one python 3.6 distribution installed before.
Now anaconda and spyder works again, but opening file is already impossible. 

Another information, when opening spyder, this windows is displayed : 
![image](https://cloud.githubusercontent.com/assets/24848499/21579787/9dc7a6f6-cfc2-11e6-9f5a-72a2cae544b4.png)

But I'm not able to select anything else than close

Do you think environnement variables conflict can cause this kind of problems ?

**Comment by ccordoba12** [comment] 2017-01-02 01:45
Please run

    conda update spyder

and try again. That should fix the error you're seeing that dialog and (perhaps) also the open file error.

**Comment by mingwandroid** [comment] 2017-01-02 09:58
@Olivdrou, to avoid the prefix length conda bug, first do `conda update conda`.

Then after installing qt 5.6.2, if this happens again, you need to use procmon from Microsoft to figure out what's being accessed just before the crash happens.

I've not seen this problem, no. My initial guess is some Unicode mismanagement though. Please show the output of `conda info`.

**Comment by Olivdrou** [comment] 2017-01-03 15:04
Hello,
Here is the output of `conda info`
![image](https://cloud.githubusercontent.com/assets/24848499/21610891/ce0f4eb8-d1ca-11e6-9eba-65aea229bf82.png)

For procmon info, can you tell me if I can use some filters? There is a lot of informations and LogFile is more than 100 Mo even if I try to get it few seconds before and after crash

**Comment by Olivdrou** [comment] 2017-01-03 15:11
Actually, I use the spyder internal file explorer and it works.

Crash occurs when I try to use the open icon, running windows explorer. Sequence is always the same : 
-Clic on open
-Explorer windows opened
-2 seconds later, mouse pointer change in "wait" and windows "program stop running"(or something like this) appears
-The only way is to clic on "close the program", witch close spyder, but not anaconda nav

**Comment by ccordoba12** [comment] 2017-01-03 16:38
We did some changes in Spyder 3.1 that could fix this. 3.1 will be released in two weeks, so when it's ready, please update to that version and let us know if it works for you.

**Comment by Olivdrou** [comment] 2017-01-04 09:11
Ok, thanks.
I'll keep you inform

**Comment by zawawahoge** [comment] 2017-01-18 07:01
I get the same bug in Spyder 3.1.
It stop about two seconds later after it show windows explorer to open files.
I can avoid spyder stopping by closing the explorer within two seconds.

**Comment by ccordoba12** [comment] 2017-01-18 12:42
@andfoy, please take a look at this one

**Comment by Olivdrou** [comment] 2017-01-20 10:01
I have updated Spyder to 3.1 but it already bug

**Comment by aviolov** [comment] 2017-02-07 13:49
for reference, I experience the issue on both Spyder 3.0 and SPyder 3.1.2 on Win10 using the anaconda(3) distributions and the crash happens every time, you try to load/save files, i.e use the Windows File Dialogue. After downgrading to Spyder 2.3.9, I no longer experience the issue.

**Comment by Tim-Kindberg** [comment] 2017-02-13 11:04
Set out to learn Python today and got this bug almost immediately (tried to save working file). Tried to follow last poster's advice (downgrade to 2.3.9) in Anaconda but that silently fails. Wow. Is this how broken Python programming support normally is?!

**Comment by ccordoba12** [comment] 2017-02-13 14:27
> Set out to learn Python today and got this bug almost immediately

We have been unable to reproduce this bug, that's the problem. We'll investigate further to see what we can find.

**Comment by Tim-Kindberg** [comment] 2017-02-13 14:34
Bug is as described above by zawawahoge. I'm on Win 10. Conda info is below. I can confirm that when I eventually managed to change to Spyder 2.3.9 the bug went away. 

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\tim\Miniconda3  (writable)
    default environment : C:\Users\tim\Miniconda3
       envs directories : C:\Users\tim\Miniconda3\envs
                          C:\Users\tim\AppData\Local\conda\conda\envs
                          C:\Users\tim\.conda\envs
          package cache : C:\Users\tim\Miniconda3\pkgs
                          C:\Users\tim\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

**Comment by takumi601** [comment] 2017-03-09 04:26
I get the same bug in spyder3.1.3 on Windows7 64bit.
Moreover, when try to open file on glueviz0.9.1, the same crash happens.(APPCRASH/pythonw.exe /c0000005/ntdll.dll...)

**Comment by ccordoba12** [comment] 2017-03-09 14:16
@takumi601, that means that the error is in Qt and not in Spyder. Thanks for letting us know about it.

**Comment by takumi601** [comment] 2017-03-10 09:06
Thank you for your reply.
What I can do is to wait for Qt update?
 I hope this bug will be fixed soon.

**Comment by takumi601** [comment] 2017-03-17 00:33
After uninstalling Dell's application, Backup and Recovery, the crash no longer happens on my PC.

I found this
http://pixinsight.com/forum/index.php?topic=9190.0

**Comment by takumi601** [comment] 2017-03-22 09:50
Could you reply?
It has nothing to do with the problem?

**Comment by ccordoba12** [comment] 2017-03-22 15:13
Sorry for not replying before. Quite the contrary, it seems to have a lot to do with the problem!!

What this points out to is that this problem is caused by other Qt5 installations in the system. So if you have this problem, you have to find those installations and remove them or report the error with the package creators.

**Comment by mingwandroid** [comment] 2017-03-22 15:26
@ccordoba12, to me, this seems to be a bug in a Windows shell extension in 3rd party software and not to do with Qt5, except that it causes Qt5 to crash unfortunately?

**Comment by ccordoba12** [comment] 2017-03-22 15:38
But I doubt all people affected by this bug have Dell backup and recovery in their systems.

Still the only solution is to uninstall the problematic software, right @mingwandroid?

**Comment by mingwandroid** [comment] 2017-03-22 15:45
Sure, but problems with file open are consistent with shell extension bugs.

The bugreport at https://bugreports.qt.io/browse/QTBUG-41416 indicates a possible workaround:

> If a QFileDialog with AnyFile file mode is opened/executed at least once before the one which causes the issue, then the "bugged" file dialog does not cause any issues and keeps working correctly.

.. I wonder if that can be employed for people running into this? A hidden key combo to bring up such a AnyFile file dialog that they can then just cancel and proceed with the normal file open?

**Comment by takumi601** [comment] 2017-03-22 23:34
Thanks for your reply! I think many people 's pc has the backup application installed. Besides, Windows 7, Windows 8, it seems that this application is not currently being updated automatically. Is not it better to call attention with troubleshooting pages etc? Autodesk (CG Developer) describes this on the web page.

https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/On-some-Dell-systems-Maya-2017-crashes-when-you-use-a-file-browser.html

**Comment by KMac0615** [comment] 2017-08-08 16:22
"What this points out to is that this problem is caused by other Qt5 installations in the system. So if you have this problem, you have to find those installations and remove them or report the error with the package creators."

Pardon my lack of knowledge on this topic but how do I find other Qt5 installation on my system?

**Comment by tosscoin88** [comment] 2018-01-02 20:27
Hi Everyone,

Just wanted to help here: I am a Dell PC user who has been suffering from this "Spyder has stopped working" problem for a long time.  As of 10 minutes ago I uninstalled "Dell Backup and Recovery" from Control Panel and rebooted my PC.  It is not crashing anymore.

Hopefully this can help.  Will update if there is any new issue popping up.

**Comment by c-siddharth** [comment] 2018-04-15 06:09
facing the same issue while saving

this is the error report

[5988:2672:0415/112412.248:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[5988:2672:0415/112412.260:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\SIDDU\AppData\Local\Spyder\QtWebEngine\Default\GPUCache to C:\Users\SIDDU\AppData\Local\Spyder\QtWebEngine\Default\old_GPUCache_000
[5988:2672:0415/112412.260:ERROR:cache_creator.cc(134)] Unable to create cache
[5988:2672:0415/112412.260:ERROR:shader_disk_cache.cc(570)] Shader Cache Creation failed: -2

**Comment by alekh226** [comment] 2018-05-24 00:07
​Try to install it seperately
+ Install latest version of python

+ Install PyQt5
```pip3 install pyqt5​```
+ Install Spyder

    ```pip install spyder```
+ Launch Spyder: Create a .bat file
   ```@echo off ```
   ``` spyder3 ```
   ```exit ```
reference: https://pythonhosted.org/spyder/installation.html

**Comment by emma-branigan** [comment] 2018-07-20 08:39
Removing Dell Backup and Recovery was the only solution for me also!!

**Comment by MonicaSai7** [comment] 2018-07-29 06:40
When I launch Spyder, while loading editor the error saying "Python not working" pops up.
Even python code is not executing in Jupyter notebook.
I've already tried re-installing anaconda over 10 times. Still the issue is not resolved.

**Comment by Antzxz** [comment] 2019-01-29 18:13
I was also able to get Spyder to save by uninstalling Dell Backup and Recovery.

**Comment by lyl868xyz** [comment] 2019-03-19 05:10
> To all,
> I confirm that uninstalling "Dell Backup and Recovery" and rebooting the PC is the solution.
> Regards

Thanks ! Your method sovles my same open/save file crash problem of Spyder. You are a genius ! What is the rationale behind this ?

**Comment by ccordoba12** [comment] 2019-03-19 09:33
> What is the rationale behind this ?

That that Dell application conflicts with some libraries needed by Spyder.

**Comment by xiaobabyh** [comment] 2019-03-27 07:23
I faced the same problem and solved by uninstalled the dell backup and recovery.

**Comment by Ing-sn** [comment] 2019-11-21 08:54
I do not have admin rights at my work space and I cant uninstall the dell backup and recovery. What shall I do? I am facing the same problem and tried all the stuff mentioned here.

**Comment by ccordoba12** [comment] 2019-11-21 15:17
> I cant uninstall the dell backup and recovery

Sorry, there's nothing else to do about it.

**Comment by mar1ja** [comment] 2020-03-27 11:09
Hello all,

I was facing the same error. And then I realized that I was opening Anaconda2->Spyder2, whereas I should be opening Anaconda3->Spyder3, due to my update to Python 3. I hope this helps someone.

Best,
Marija

**Comment by ccordoba12** [comment] 2024-04-09 15:43
Closing because we haven't hear about this problem during the last years.

**Closed by ccordoba12** 2024-04-09 15:43 UTC
Labels: component:Editor, OS:Windows, Package:PyQt
