### ISSUE TITLE
Spyder 4.0 fails to connect to kernel 

### ISSUE THREAD

**Issue by rahikalantari** [spyder-ide/spyder#11456] opened 2020-02-02 20:03 UTC
### Issue Report Checklist

 [* ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
 [* ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
 [* ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
 * [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
[* ] Tried basic troubleshooting (if a bug/error)
     [* ] Restarted Spyder
    [* ] Reset preferences with ``spyder --reset``
    [* ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
     [* ] Tried the other applicable steps from the Troubleshooting Guide
[* ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I had anaconda 2.7 and older spyder version and everything used to be working fine. I just installed the anaconda 3.7 and updated the spyder to v 4.0.1 (I still have my anaconda 2.7 installation and plan to keep it). when opening spyder , the spedyer cannot connect to kernel , following is the materials showed up on spyder consul.  
Pyhton 3.7.6
Spyder 4.0.1
Ubuntu 18.04

there seems to be the issue for other versions of spyder but solution were not the same on different version and instances 

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 287, in main
import_spydercustomize()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 17, in 
import pdb
File "/home/rahikalantari/anaconda3/lib/python3.7/pdb.py", line 76, in 
import code
File "/home/rahikalantari/code.py", line 36
parser.add_argument('‑‑log‑interval', type=int, default=10, metavar='N',
^
SyntaxError: invalid syntax

### What steps reproduce the problem?

1. call spyder on the consul 
2. as soon as it opens up, it cannot find the kernel
3. 

### What is the expected output? What do you see instead?
I expect to see python version and be able to write python command
i see following 
"An error ocurred while starting the kernel"

### Paste Traceback/Error Below (if applicable)

```python-traceback


PASTE TRACEBACK HERE

```An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 287, in main
import_spydercustomize()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 17, in 
import pdb
File "/home/rahikalantari/anaconda3/lib/python3.7/pdb.py", line 76, in 
import code
File "/home/rahikalantari/code.py", line 36
parser.add_argument('‑‑log‑interval', type=int, default=10, metavar='N',
^
SyntaxError: invalid syntax


## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.0.2
* Operating System name/version: Ubuntu 18.04

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-02-03 17:41
Duplicate of #11402

**Closed by ccordoba12** 2020-02-03 17:41 UTC
