### ISSUE TITLE
Update translations for 4.1

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#11731] opened 2020-03-05 15:53 UTC
Hello translators! Spyder version 4.1 is soon to be released and we would like to ask for your help in updating the translated string.

We plan to release next week so if you could help us with this by Monday March 9th  12:00 am UTC it would be great. If you cannot make it on time it is ok and we can release the updates on subsequent version. 

We now use Crowdin https://crowdin.com/project/spyder which should make this process much much easier for everyone! (if you prefer to make a PR that is also fine)

This list might be outdated so feel free to ping if you can't help any longer with this. 

## French
@afvincent
@Nodd
@SylvainCorlay
@jnsebgosselin 

## Hungarian
@blackPantherOS
@martindurant

## Japanese
@sohnishi

## Portuguese (Brazilian)
@sehnem
@manipuladordedados

## Russian
@burrbull
@Qlogin

## Spanish
@ccordoba12
@goanpeca
@juanis2112 

## Simplified Chinese
@suokunlong
@kingmo888
@nnnewb
@gepcel

## German
@alexschw
@be-we

## Polish
@wojnilowicz

Cheers and thanks again!

**Comment by ccordoba12** [comment] 2020-03-11 16:13
Hey everyone, we added a couple of new strings for translation in PR #11715 and we updated our po files accordingly a couple of hours ago. So we'd appreciate your help to add translations for those strings.

We hope to finally do this release on Friday March 13, so you have time until 12:00 am UTC of that day to give us a hand with this.

Thanks!

**Comment by durack1** [comment] 2020-03-11 22:15
@ccordoba12 really looking forward to seeing v4.1.0 landing, this laggy editor (#11412) is starting to make me think about other editors

**Comment by ccordoba12** [comment] 2020-03-11 22:40
Almost there! I've been all day fighting to finish #11755, which is also very important to have (at least from my point of view).

**Comment by goanpeca** [comment] 2020-03-13 16:57
@jnsebgosselin @impact27 if you could take a quick look at the french translations over at https://crowdin.com/translate/spyder/33/en-fr it would be awesome. Thanks!

**Comment by jnsebgosselin** [comment] 2020-03-14 03:41
> @jnsebgosselin @impact27 if you could take a quick look at the french translations over at https://crowdin.com/translate/spyder/33/en-fr it would be awesome. Thanks!

Sure, I'll start working on this tomorrow.

**Comment by Prayforhanluo** [comment] 2020-03-16 01:48
https://groups.google.com/forum/#!msg/spyderlib/SauR-AiAeLg/tPdi6kDXAgAJ

**Comment by Prayforhanluo** [comment] 2020-03-16 01:48
https://groups.google.com/forum/#!msg/spyderlib/SauR-AiAeLg/tPdi6kDXAgAJ

**Comment by Prayforhanluo** [comment] 2020-03-16 01:51
https://groups.google.com/forum/#!msg/spyderlib/SauR-AiAeLg/tPdi6kDXAgAJ    This problem has puzzled me a lot

**Comment by Prayforhanluo** [comment] 2020-03-16 01:51
https://groups.google.com/forum/#!msg/spyderlib/SauR-AiAeLg/tPdi6kDXAgAJ This problem has puzzled me a lot @ccordoba12

**Comment by ccordoba12** [comment] 2020-03-16 01:59
@Prayforhanluo, it's a duplicate of #11222. It'll be fixed in our **4.1.0** version. Please wait until new conda packages are available for it, which should be done shortly.

**Closed** 2020-03-16 02:22 UTC
Labels: type:Task, v4.1.0

**Comment by cpkc** [comment] 2020-04-04 16:35
Greetings!

I find some issue here:

%HOME%\Anaconda3\Lib\site-packages\spyder\locale\pt_BR\LC_MESSAGES file spyder.mo won't let spyder start in Brazilian Portuguese! At least in Windows 10 64.

**Comment by ccordoba12** [comment] 2020-04-04 16:48
This should be fixed in our 4.1.2 version, to be released in a couple of days.
