### ISSUE TITLE
Could spyder support PyQt 5.15?

### ISSUE THREAD

**Issue by kevintsq** [spyder-ide/spyder#16338] opened 2021-09-02 17:30 UTC
### Issue Report Checklist

* [ - ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ - ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ - ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ - ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ - ] Tried basic troubleshooting (if a bug/error)
    * [ - ] Restarted Spyder
    * [ - ] Reset preferences with ``spyder --reset``
    * [ - ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ - ] Tried the other applicable steps from the Troubleshooting Guide
* [ - ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I've installed `pyqtchart` which requires `PyQt5>=5.15.4`. However, spyder requires `PyQt5<5.13`. To save my disk space, I don't want to create virtual environment for APPs that use `pyqtchart`. Could spyder support PyQt 5.15?

### What steps reproduce the problem?

1. `pip install pyqtchart`
2. Spyder won't start

### What is the expected output? What do you see instead?

Spyder shouldn't be interfered by other packages, especially installed by the official package manager.

### Paste Traceback/Error Below (if applicable)

```shell

> pip install pyqtchart
Requirement already satisfied: pyqtchart in c:\programdata\anaconda3\lib\site-packages (5.15.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\programdata\anaconda3\lib\site-packages (from pyqtchart) (12.9.0)
Collecting PyQt5>=5.15.4
  Downloading PyQt5-5.15.4-cp36.cp37.cp38.cp39-none-win_amd64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 731 kB/s
Requirement already satisfied: PyQtChart-Qt5>=5.15 in c:\programdata\anaconda3\lib\site-packages (from pyqtchart) (5.15.2)
Requirement already satisfied: PyQt5-Qt5>=5.15 in c:\programdata\anaconda3\lib\site-packages (from PyQt5>=5.15.4->pyqtchart) (5.15.2)
Installing collected packages: PyQt5
  Attempting uninstall: PyQt5
    Found existing installation: PyQt5 5.12.3
    Uninstalling PyQt5-5.12.3:
      Successfully uninstalled PyQt5-5.12.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency
conflicts.
spyder 5.1.2 requires pyqt5<5.13, but you have pyqt5 5.15.4 which is incompatible.
Successfully installed PyQt5-5.15.4

```

## Versions

* Spyder version: 5.1.2
* Python version: 3.8.6
* Qt version: 6.1.2/5.9.7
* PyQt version: 5.15.4
* Operating System name/version: Windows 10 20H2 19042.1165

### Dependencies

``` shell
  _anaconda_depends-2020.07-py38_0
  alabaster-0.7.12-pyhd3eb1b0_0
  anaconda-custom-py38_1
  anaconda-project-0.10.1-pyhd3eb1b0_0
  argh-0.26.2-py38_0
  arrow-0.13.1-py38_0
  asn1crypto-1.4.0-py_0
  astroid-2.6.6-py38haa95532_0
  astropy-4.3.1-py38hc7d831d_0
  atomicwrites-1.4.0-py_0
  autopep8-1.5.6-pyhd3eb1b0_0
  backports.shutil_get_terminal_size-1.0.0-pyhd3eb1b0_3
  bcrypt-3.2.0-py38he774522_0
  binaryornot-0.4.4-pyhd3eb1b0_1
  bitarray-2.3.0-py38h2bbff1b_1
  bkcharts-0.2-py38_0
  blosc-1.21.0-h19a0ad4_0
  bokeh-2.3.3-py38haa95532_0
  boto-2.49.0-py38_0
  bottleneck-1.3.2-py38h2a96729_1
  brotli-1.0.9-ha925a31_2
  cfitsio-3.470-he774522_6
  charls-2.2.0-h6c2663c_0
  cloudpickle-1.6.0-py_0
  comtypes-1.1.10-py38haa95532_1002
  conda-pack-0.6.0-pyhd3eb1b0_0
  contextlib2-0.6.0.post1-py_0
  cookiecutter-1.7.2-pyhd3eb1b0_0
  curl-7.78.0-h86230a5_0
  cycler-0.10.0-py38_0
  cytoolz-0.11.0-py38he774522_0
  dask-2021.8.0-pyhd3eb1b0_0
  dask-core-2021.8.0-pyhd3eb1b0_0
  diff-match-patch-20200713-py_0
  distributed-2021.8.0-py38haa95532_0
  docutils-0.17.1-py38haa95532_1
  et_xmlfile-1.1.0-py38haa95532_0
  fastcache-1.1.0-py38he774522_0
  flake8-3.9.0-pyhd3eb1b0_0
  fonttools-4.25.0-pyhd3eb1b0_0
  fsspec-2021.7.0-pyhd3eb1b0_0
  get_terminal_size-1.0.0-h38e98db_0
  gevent-21.8.0-py38h2bbff1b_1
  giflib-5.2.1-h62dcd97_0
  gmpy2-2.0.8-py38h7edee0f_3
  greenlet-1.1.1-py38hd77b12b_0
  heapdict-1.0.1-py_0
  html5lib-1.1-py_0
  imagecodecs-2021.6.8-py38h5da4933_0
  imageio-2.9.0-pyhd3eb1b0_0
  imagesize-1.2.0-pyhd3eb1b0_0
  inflection-0.5.1-py38haa95532_0
  iniconfig-1.1.1-pyhd3eb1b0_0
  intervaltree-3.1.0-py_0
  isort-5.9.3-pyhd3eb1b0_0
  jdcal-1.4.1-py_0
  jinja2-time-0.2.0-pyhd3eb1b0_2
  joblib-1.0.1-pyhd3eb1b0_0
  jupyter-1.0.0-py38_7
  jupyter_console-6.4.0-pyhd3eb1b0_0
  keyring-23.0.1-py38haa95532_0
  kiwisolver-1.3.1-py38hd77b12b_0
  krb5-1.19.2-h5b6d351_0
  lazy-object-proxy-1.6.0-py38h2bbff1b_0
  lcms2-2.12-h83e58a3_0
  lerc-2.2.1-hd77b12b_0
  libaec-1.0.4-h33f27b4_1
  libcurl-7.78.0-h86230a5_0
  libdeflate-1.7-h2bbff1b_5
  libllvm9-9.0.1-h21ff451_0
  libsodium-1.0.18-h62dcd97_0
  libspatialindex-1.9.3-h6c2663c_0
  libssh2-1.9.0-h7a1dbc1_1
  libxslt-1.1.34-he774522_0
  libzopfli-1.0.3-ha925a31_0
  llvmlite-0.36.0-py38h34b8924_4
  locket-0.2.1-py38haa95532_1
  lxml-4.6.3-py38h9b66d53_0
  lzo-2.10-he774522_2
  matplotlib-3.4.2-py38haa95532_0
  matplotlib-base-3.4.2-py38h49ac443_0
  mccabe-0.6.1-py38_1
  mock-4.0.3-pyhd3eb1b0_0
  more-itertools-8.8.0-pyhd3eb1b0_0
  mpc-1.1.0-h7edee0f_1
  mpfr-4.0.2-h62dcd97_1
  mpir-3.0.0-hec2e145_1
  mpmath-1.2.1-py38haa95532_0
  msgpack-python-1.0.2-py38h59b6b97_1
  multipledispatch-0.6.0-py38_0
  munkres-1.1.4-py_0
  networkx-2.6.2-pyhd3eb1b0_0
  nltk-3.6.2-pyhd3eb1b0_0
  nose-1.3.7-pyhd3eb1b0_1006
  numba-0.53.1-py38hf11a4ad_0
  numexpr-2.7.3-py38hb80d3ca_1
  numpydoc-1.1.0-pyhd3eb1b0_1
  openjpeg-2.4.0-h4fc8c34_0
  openpyxl-3.0.7-pyhd3eb1b0_0
  pandas-1.3.2-py38h6214cd6_0
  pandoc-2.12-haa95532_0
  paramiko-2.7.2-py_0
  partd-1.2.0-pyhd3eb1b0_0
  path-16.0.0-py38haa95532_0
  path.py-12.5.0-0
  pathlib2-2.3.6-py38haa95532_2
  pathtools-0.1.2-py_1
  patsy-0.5.1-py38_0
  pep8-1.7.1-py38_0
  pexpect-4.8.0-pyhd3eb1b0_3
  pluggy-0.13.1-py38haa95532_0
  ply-3.11-py38_0
  poyo-0.5.0-pyhd3eb1b0_0
  ptyprocess-0.7.0-pyhd3eb1b0_2
  py-1.10.0-pyhd3eb1b0_0
  pycodestyle-2.6.0-pyhd3eb1b0_0
  pycurl-7.43.0.6-py38h7a1dbc1_0
  pydocstyle-6.1.1-pyhd3eb1b0_0
  pyerfa-2.0.0-py38h2bbff1b_0
  pyflakes-2.2.0-pyhd3eb1b0_0
  pylint-2.9.6-py38haa95532_1
  pyls-black-0.4.6-hd3eb1b0_0
  pyls-spyder-0.3.2-pyhd3eb1b0_0
  pynacl-1.4.0-py38h62dcd97_1
  pyodbc-4.0.31-py38hd77b12b_0
  pytables-3.6.1-py38ha5be198_0
  pytest-6.2.4-py38haa95532_2
  python-jsonrpc-server-0.4.0-py_0
  python-language-server-0.36.2-pyhd3eb1b0_0
  python-slugify-5.0.2-pyhd3eb1b0_0
  pywavelets-1.1.1-py38he774522_2
  qdarkstyle-3.0.2-pyhd3eb1b0_0
  qstylizer-0.1.10-pyhd3eb1b0_0
  qtawesome-1.0.2-pyhd3eb1b0_0
  qtconsole-5.1.0-pyhd3eb1b0_0
  rope-0.19.0-pyhd3eb1b0_0
  rtree-0.9.7-py38h2eaa2aa_1
  scikit-image-0.18.1-py38hf11a4ad_0
  scikit-learn-0.24.2-py38hf11a4ad_1
  seaborn-0.11.2-pyhd3eb1b0_0
  simplegeneric-0.8.1-py38_2
  singledispatch-3.7.0-pyhd3eb1b0_1001
  snappy-1.1.8-h33f27b4_0
  snowballstemmer-2.1.0-pyhd3eb1b0_0
  sortedcollections-2.1.0-pyhd3eb1b0_0
  sphinx-4.0.2-pyhd3eb1b0_0
  sphinxcontrib-1.0-py38_1
  sphinxcontrib-applehelp-1.0.2-pyhd3eb1b0_0
  sphinxcontrib-devhelp-1.0.2-pyhd3eb1b0_0
  sphinxcontrib-htmlhelp-2.0.0-pyhd3eb1b0_0
  sphinxcontrib-jsmath-1.0.1-pyhd3eb1b0_0
  sphinxcontrib-qthelp-1.0.3-pyhd3eb1b0_0
  sphinxcontrib-serializinghtml-1.1.5-pyhd3eb1b0_0
  sphinxcontrib-websupport-1.2.4-py_0
  spyder-5.0.5-py38haa95532_2
  spyder-kernels-2.0.5-py38haa95532_0
  sqlalchemy-1.4.22-py38h2bbff1b_0
  statsmodels-0.12.2-py38h2bbff1b_0
  sympy-1.8-py38haa95532_0
  tbb-2020.3-h74a9793_0
  tblib-1.7.0-py_0
  text-unidecode-1.3-py_0
  textdistance-4.2.1-pyhd3eb1b0_0
  threadpoolctl-2.2.0-pyhbf3da8f_0
  three-merge-0.1.1-pyhd3eb1b0_0
  tifffile-2021.7.2-pyhd3eb1b0_2
  tinycss-0.4-pyhd3eb1b0_1002
  toolz-0.11.1-pyhd3eb1b0_0
  ujson-4.0.2-py38hd77b12b_0
  unicodecsv-0.14.1-py38_0
  unidecode-1.2.0-pyhd3eb1b0_0
  watchdog-2.1.3-py38haa95532_0
  whichcraft-0.6.1-pyhd3eb1b0_0
  win_unicode_console-0.5-py38_0
  xlrd-2.0.1-pyhd3eb1b0_0
  xlsxwriter-3.0.1-pyhd3eb1b0_0
  xlwings-0.24.7-py38haa95532_0
  xlwt-1.3.0-py38_0
  yapf-0.31.0-pyhd3eb1b0_0
  zeromq-4.3.4-hd77b12b_0
  zfp-0.5.5-hd77b12b_6
  zict-2.0.0-pyhd3eb1b0_0
  zope-1.0-py38_1
  zope.event-4.5.0-py38_0
  zope.interface-5.4.0-py38h2bbff1b_0
```

**Comment by ccordoba12** [comment] 2021-09-02 17:37
Hey @kevintsq, thanks for reporting. This is a duplicate of issue #12829, so I'm going to close it in favor of that one.

Please see the discussion there for our reasons.

**Closed by ccordoba12** 2021-09-02 17:37 UTC
