### ISSUE TITLE
BugReport: Can not set breakpoint

### ISSUE THREAD

**Issue by pythonokai** [spyder-ide/spyder#4228] opened 2017-03-05 07:03 UTC
## Description

**What steps will reproduce the problem?**

1. Can not set breakpoint.

**What is the expected output? What do you see instead?**
I set a breakpoint but it always running through

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```
same as[ #4214](https://github.com/spyder-ide/spyder/issues/4214)

**Comment by pythonokai** [comment] 2017-03-05 07:19
added 'sys.exit(0)' on where you want to set breakpoint, It seems just like set a breakpoint on that, it can temporary to fixed this problem

**Comment by ccordoba12** [comment] 2017-03-21 05:15
Closing as a duplicate of issue #4214.

**Closed by ccordoba12** 2017-03-21 05:15 UTC
Labels: component:Debugger, resolution:Duplicate, type:Bug
