### ISSUE TITLE
Rich text help with ctrl+I is broken when console working directory is set to D drive

### ISSUE THREAD

**Issue by woodknight** [spyder-ide/spyder#6850] opened 2018-03-27 23:12 UTC
## Problem Description
Rich text help with ctrl+I is broken when console working directory is set to D drive.

### What steps will reproduce the problem?

1.  lunch spyder
2.  make sure the  display type of the help pane is rich text
3. change the working directory to D drive or any drive other than C
4.  create or open a python script in the editor
5.  place the cursor on a function name that you want to get help doc for
6.  press ctrl+I

### What is the expected output? What do you see instead?
Expect to see the rich text help doc in the help pane. Instead, it shows the plain text help and pops out an error message saying "The following error occurred when calling Sphinx 1.7.1. Incompatible Sphinx version or doc string decoding failed. Error message: path is on mount 'C:', start on mount:'"

![spyder error](https://user-images.githubusercontent.com/4604977/37999791-55a80ae4-31d9-11e8-977f-dc6301d6ba32.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback
The following error occured when calling Sphinx 1.7.1. 
Incompatible Sphinx version or doc string decoding failed.

Error message:
path is on mount 'C:', start on mount 'D:'

```
## Package Versions

* Anaconda: 5.1
* Spyder: 3.2.8
* Python: 3.6.4 64bits
* Qt: 5.6.2
* PyQt5: 5.6
* Operating System: Windows 7 Professional SP1 64bit

### Dependencies

```
```

**Comment by CAM-Gerlach** [comment] 2018-03-27 23:39
Thanks for reporting. This is a duplicate of #6549 , which we are currently working to fix hopefully for the next release of Spyder in a month or so. In the meantime, you can just downgrade to Sphinx 1.6.6 with ``conda install sphinx=1.6.6`` from the Anaconda Prompt, assuming you'd rather keep your working directory on the same drive.

**Closed by CAM-Gerlach** 2018-03-27 23:39 UTC
