### ISSUE TITLE
Project one

### ISSUE THREAD

**Issue by MOSIMOS1** [spyder-ide/spyder#6895] opened 2018-04-04 12:11 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Nakaggwa Sandra.T\AppData\Local\conda\conda\envs\boom\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\Users\Nakaggwa Sandra.T\AppData\Local\conda\conda\envs\boom\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined
Traceback (most recent call last):
  File "C:\Users\Nakaggwa Sandra.T\AppData\Local\conda\conda\envs\boom\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\Users\Nakaggwa Sandra.T\AppData\Local\conda\conda\envs\boom\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7

**Comment by ccordoba12** [comment] 2018-04-04 15:07
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-04-09 01:52
Apparent duplicate of #5061 , which is apparently due to attempting to view a dataframe or an array in an environment without numpy or pandas.

**Closed by CAM-Gerlach** 2018-04-09 01:52 UTC
Labels: status:Awaiting Followup
