### ISSUE TITLE
Spyder has encountered a problem

### ISSUE THREAD

**Issue by Surichn** [spyder-ide/spyder#6809] opened 2018-03-21 09:38 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Suri\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Suri\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Suri\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Suri\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\Suri\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\Suri\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "C:\Users\Suri\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Suri\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Suri\Anaconda3\lib\

**Comment by ccordoba12** [comment] 2018-03-21 14:45
I think this problem is fixed in our latest version (3.2.8). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Closed by ccordoba12** 2018-03-21 14:45 UTC

**Comment by CAM-Gerlach** [comment] 2018-03-21 20:05
Thanks for reporting. For reference, this is an apparent duplicate of #4958 (and its more recent reincarnation, #6319), fixed in Spyder 3.2.7. You can update Spyder by running the command ``conda update spyder`` from the Anaconda Prompt.

**Comment by Surichn** [comment] 2018-03-22 06:00
Thanks for the quick response. it is resolved now
Regards,Suri
    On Thursday, March 22, 2018, 1:35:32 AM GMT+5:30, C.A.M. Gerlach <notifications@github.com> wrote:  
 
 
Thanks for reporting. For reference, this is an apparent duplicate of #4958 (and its more recent reincarnation, #6319), fixed in Spyder 3.2.7. You can update Spyder by running the command conda update spyder from the Anaconda Prompt.
