### ISSUE TITLE
spyder issue reporter froze program

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#11908] opened 2020-03-21 18:40 UTC
updated to spyder 4.1.1 python 3.7 on OS Catalina. 
Since updating, Spyder it has been VERY buggy. Always freezing, restarting, now the issue reporter froze the screen. (You became the thing you swore to destroy! -Obiwan or something)

**Comment by ccordoba12** [comment] 2020-03-21 18:49
It looks like a duplicate of #11846. It'll be fixed in our next version.

**Closed by ccordoba12** 2020-03-21 18:49 UTC
