### ISSUE TITLE
In debug mode, the windows opened by the Variable Explorer are hidden behind Spyder

### ISSUE THREAD

**Issue by CharlesVellutini** [spyder-ide/spyder#5406] opened 2017-10-06 07:44 UTC
## Description

**What steps will reproduce the problem?**

1. Unzip and run the code 
[bug variable explorer.zip](https://github.com/spyder-ide/spyder/files/1361915/bug.variable.explorer.zip)
2. Go to the Variable Explorer and click on the "df" object: it opens normally in front of you. So far so good.
3. Place a breakpoint at line 12 and run the code in **debug mode.**
4. Go to the Variable Explorer and click on the "df" object: the window is hidden behind Spyder

**What is the expected output? What do you see instead?**
Expected output is windows opening normally in front of Spyder
Instead, the window opens behind Spyder

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.1.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  4.2.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-10-06 14:05
Thanks for reporting. This is a duplicate of issue #5036.

**Closed by ccordoba12** 2017-10-06 14:05 UTC
