### ISSUE TITLE
Code completion removes first capitalized letters of function

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#3374] opened 2016-08-25 10:05 UTC
## Description of your problem

I try to type the following:

```
import cv2
cv2.GaussianBlur
```

instead I see:

```
import cv2
cv2.aussianBlur
```

**Please provide any additional information below**
This happens when the first letter is capitalized and is typed before the "Scrolling window" appears 
## Versions and main components
- Spyder Version: 3b5
- Python Version: Python 3.5.2 64bits, Qt 5.5.1, PyQt5 5.5.1 on Darwin
## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by impact27** [comment] 2016-08-25 10:14
I can even do:
`cv2.LKJHGFD`
and I get (if I am quick enough):
`cv2.HGFD`

**Comment by malliwi88** [comment] 2016-10-24 22:03
Hi, @impact27 

I try to reproduce your issue in my Linux machine and OpenCV Works fine. Only one difference with you, I test it on Spyder 3.0.1.

![capturadeepin20161024165708](https://cloud.githubusercontent.com/assets/5307894/19665526/f4e70dd4-9a0a-11e6-9e5a-855d18f2075a.png)

My questions are:
* Are you test it on V3.0.1 on your Mac?
* Are you install opencv from Anaconda distribution or compile it from sources?

## Some Details
I install OpenCV with
```bash
conda install opencv3
```
In the same conda environment where I have Spyder.

@ccordoba12 @mariacamilaremolinagutierrez Anyone has a Mac for test it and Close this issue.??

Thank's

**Comment by goanpeca** [comment] 2016-10-24 22:06
@malliwi88 I can test on mac

**Comment by malliwi88** [comment] 2016-10-24 22:07
Great!!! :) @goanpeca

**Comment by impact27** [comment] 2016-10-25 09:11
Python 3.5.2 64bits, Qt 5.5.1, PyQt5 5.5.1 on Darwin 
Spyder 3.0.1 installed from pip3

I still see this.

**Comment by ccordoba12** [comment] 2016-10-25 14:03
So the problem seems to be present in Macs only :-)

**Comment by ccordoba12** [comment] 2017-08-13 17:58
@impact27, is this still a problem for you?

**Comment by impact27** [comment] 2017-08-14 09:29
I can remember some instance where the first character was dropped just after a ".", but I can not reproduce the problem now and it is not as frequent as before. (I am not even sure if I saw it recently.)

**Comment by ccordoba12** [comment] 2017-08-14 11:31
Ok, I'm closing this for now. Please reopen if the problem reappears again.

**Closed by ccordoba12** 2017-08-14 11:31 UTC
Labels: component:Editor, OS:MacOS, type:Bug
