### ISSUE TITLE
Kernel died, res

### ISSUE THREAD

**Issue by Devarshkshah** [spyder-ide/spyder#8601] opened 2019-01-20 11:51 UTC
### What steps will reproduce the problem?

I created a new environment called sem8 and then installed spyder in that environment to run files. Now whenever I try to run the kernel it gives the message as kernel died, restarting. Firstly I thought it was problem of memory but it could not run simple Hello World. I tried solutions on the web like disabling inbound rules for python.exe and pythonw.exe but nothing worked. Please help at the earliest.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-01-20 16:34
It looks like a duplicate of issue #8581. Could you confirm it?

**Comment by ccordoba12** [comment] 2019-01-21 15:21
Please give us the command you used to create your `sem8` environment.

**Comment by Devarshkshah** [comment] 2019-01-23 16:59
I can't remember the exact command but it was like conda create - - name
sem8.....

**Comment by ccordoba12** [comment] 2019-01-23 17:01
Yeah, but what we need to know is what packages you installed on it.

**Comment by Devarshkshah** [comment] 2019-01-23 18:20
Many starting with tensor flow, opencv, keras, matplotlib, numpy, pandas etc.

**Comment by ccordoba12** [comment] 2019-01-23 18:34
Closing because you're not giving us a reproducible way to generate the error you're having. If you can give us a step by step way to do it, then we could help you.

**Closed by ccordoba12** 2019-01-23 18:34 UTC
Labels: status:Awaiting Followup

**Comment by Devarshkshah** [comment] 2019-01-23 18:43
I myself don't know how the error popped out. I was just setting up the
environment by installing different packages from anaconda prompt and all
of them are running fine from anaconda prompt. Then I tried to install
spyder from navigator in sem8 environment and also jupyter notebook and
then I tried to open it from there and since then this error is showing. I
tried all the steps but while updating spyder it gives an unknown error has
occurred.

**Comment by Devarshkshah** [comment] 2019-01-23 18:45
While running conda update spyder

**Comment by ccordoba12** [comment] 2019-01-23 18:51
As I said, if you can narrow down the specific things or packages that cause the kernel to die, then we could help you. Else, it's like trying to find a needle in a haystack, sorry.

In any case, your problem seems very similar to issue #8581 (as I said at the beginning), and we haven't found a solution for that yet.
