### ISSUE TITLE
view inner spatial join result

### ISSUE THREAD

**Issue by mhscott-usgs** [spyder-ide/spyder#21281] opened 2023-08-23 14:17 UTC
### What steps will reproduce the problem?

```python
import geopandas as gpd
import pandas as pd

df1 = pd.read_csv("df1.csv")	#point dataset
df2 = gpd_read_file("df2.gpkg")	#polygon dataset

df1['geometry'] = df1.apply(lambda row: Point(row.longitude, row.latitude), axis=1)
df1  = gpd.GeoDataFrame(df1, crs="EPSG:4269")
df1 = df1.to_crs("EPSG:5070")   
df1['geometry_buf'] = df1.geometry.buffer(400)          
df1 = df1.set_geometry('geometry_buf')

df2 = df2.to_crs("EPSG:5070")

df_innerjoin = df1.sjoin(df2, how="inner")

```

attempt to view `df_innerjoin` from VariableExplorer

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\mhscott\Anaconda3\envs\env_miningWU_v4\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 203, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\Users\mhscott\Anaconda3\envs\env_miningWU_v4\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 946, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\Users\mhscott\Anaconda3\envs\env_miningWU_v4\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "C:\Users\mhscott\Anaconda3\envs\env_miningWU_v4\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 244, in max_min_col_update
    for __, col in self.df.iteritems():
  File "C:\Users\mhscott\Anaconda3\envs\env_miningWU_v4\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GeoDataFrame' object has no attribute 'iteritems'. Did you mean: 'isetitem'?
```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.10.5
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.3.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  1.0.0 (OK)
jsonschema >=3.2.0            :  4.19.0 (OK)
keyring >=17.0.0              :  24.2.0 (OK)
nbconvert >=4.0               :  7.7.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.5 (OK)
pygments >=2.0                :  2.16.1 (OK)
pylint >=2.5.0                :  2.17.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.3.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.3 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.3.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  68.1.2 (OK)
sphinx >=0.6.6                :  7.2.2 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.2 (OK)
numpy >=1.7                   :  1.25.2 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.11.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment] 2023-08-23 20:12
Hi @mhscott-usgs  thank you for the feedback! Seems like the issue described is related to/a duplicate of https://github.com/spyder-ide/spyder/issues/20496 To get the fix you will need to update to at least Spyder 5.4.3

Let us know if updating helps!

**Comment by dalthviz** [comment] 2023-11-07 01:34
Closing as a duplicate of #20496

**Closed by dalthviz** 2023-11-07 01:34 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
