### ISSUE TITLE
Hangs when browse any directory or try to save

### ISSUE THREAD

**Issue by tazuddin90** [spyder-ide/spyder#4378] opened 2017-04-21 05:28 UTC
## Description

**What steps will reproduce the problem?**

1. Click on "Open file" / "save file as "
2. Error - Python has stopped working (snap is attached
![python](https://cloud.githubusercontent.com/assets/27842135/25264016/6cb5c67c-2681-11e7-995e-771c005d5870.JPG)
)
3. Then it automatically closed
![python](https://cloud.githubusercontent.com/assets/27842135/25264001/5968ce66-2681-11e7-9a85-17bf1405b0f9.JPG)

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4.dev0 
* Python Version: 3.6.1
* Qt Versions: 5.8.0, PyQt5 5.8.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment] 2017-04-21 21:57
Thanks for reporting. This is a duplicate of issue #3903. Please read the comments at the end to know how to fix it (it's not something we can do in Spyder).

**Closed by ccordoba12** 2017-04-21 21:57 UTC
