### ISSUE TITLE
Icons overlay text in pull-down menus (Windows)

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#15206] opened 2021-04-09 16:05 UTC
### What steps will reproduce the problem?

Spyder 5.0.0

Win10 x64. 

Click View on top menu bar. Observe that icons overlay menu text.

![menu](https://user-images.githubusercontent.com/9833299/114209222-64948d80-992c-11eb-9886-07b36bfcbb58.png)

**Comment by ccordoba12** [comment] 2021-04-09 17:39
Hey @nerdfever, thanks for reporting. This is a duplicate of issue #15116 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-09 17:39 UTC
