### ISSUE TITLE
Segmentation fault while visualizing a numpy array containing inf

### ISSUE THREAD

**Issue by Cesco14** [spyder-ide/spyder#10999] opened 2019-12-10 11:18 UTC
I report a strange segmentation fault error in visualizing a numpy array containing np.inf.

```python
import numpy as np
a = np.array([np.inf,np.inf])
```

If I try to visualize it in the variable explorer, I get a segmentation fault error.
I'm using Spyder 4.0.0 on Ubuntu 19.10.

Thanks

**Comment by ccordoba12** [comment] 2019-12-10 13:41
Duplicate of #8093

**Comment by ccordoba12** [comment] 2019-12-10 13:41
We'll fix this in our next version.

**Closed by ccordoba12** 2019-12-10 13:41 UTC
