### ISSUE TITLE
Python console not working properly on Spyder 3

### ISSUE THREAD

**Issue by ofajardo** [spyder-ide/spyder#3938] opened 2017-01-09 15:24 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Copy and paste the snippet below in the editor.
2. Open a new Python console (not IPython, but python)
3. Select the snippet in the editor and run with F9

Snippet:

import numpy as np

print "starting"

perspec_start = -2
perspec_bin_num = 80
perspec_stop = 0.56
time_bins = np.linspace(start=perspec_start, stop=perspec_stop, num=perspec_bin_num, endpoint=False)
dummy = 1+1
print dummy
>>> 

**What is the expected output? What do you see instead?**

Once the snippet gets executed I expect to see "2" printed in the console. Instead of that nothing comes out, just the prompt. If now you press enter again in the console, 2 finally comes. 

Expected (as seen in spyder 2.3.9 Python console):

\>>> import numpy as np
\>>> 
\>>> print "starting"
starting
\>>> 
\>>> perspec_start = -2
\>>> perspec_bin_num = 80
\>>> perspec_stop = 0.56
\>>> time_bins = np.linspace(start=perspec_start, stop=perspec_stop, num=perspec_bin_num, endpoint=False)
\>>> dummy = 1+1
\>>> print dummy
2
\>>>

Bug Seen in spyder 3.0.2

\>>> import numpy as np
\>>> 
\>>> print "starting"
starting
\>>> 
\>>> perspec_start = -2
\>>> perspec_bin_num = 80
\>>> 
\>>> perspec_stop = 0.56
\>>> time_bins = np.linspace(start=perspec_start, stop=perspec_stop, num=perspec_bin_num, endpoint=False)
dummy = 1+1
\>>> print dummy
\>>> 
(now you push enter)
2
\>>>

**Please provide any additional information below**

The snippet is the very minimum code I have found to reproduce the problem. When working with a larger script, this bug becomes an issue as the non-executed-waiting-for-enter-to-be-executed lines accumulate and makes very difficult to work with. You can try that by writing a second print dummy statement: first the empty prompt comes, after the first enter the first 2 comes, and then an empty prompt, and only after the second enter the second 2 comes.

This problem is not there in spyder 2.3.9.  The problem is also not seen with IPython, however, I am working with some libraries that do not play well with IPython and therefore I have to use the Python console.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7.13
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment] 2017-01-09 20:32
Thanks a lot for the reproducible example. We'll try to fix this in Spyder 3.1.1 (i.e. after we release Spyder 3.1 :-).

**Comment by ofajardo** [comment] 2017-01-10 10:22
thanks a lot! Just to get an idea: when would 3.1 and 3.1.1 be released aproximately?

**Comment by ccordoba12** [comment] 2017-01-10 12:36
3.1 is going to be released in January 17.

3.1.1 approximately a month after that :-)

**Comment by bioruffo** [comment] 2017-02-03 00:24
Thank you for keeping an eye on this issue... It's quite a bit uncomfortable. Can you share any info on why this is happening?

**Comment by ccordoba12** [comment] 2017-02-04 17:04
No idea, but we're going to finally remove the Python console in Spyder 3.2 because it has a lot of bugs and we don't know how to fix them. Sorry.

However, we'll be sure to migrate all its functionality to the IPython console before doing this.

**Comment by ofajardo** [comment] 2017-02-04 19:05
oh, tha's sad news! I am working with an application from which I pull and push data, it uses sockets as way of communication. For some reason the IPython console always cust the connection with the server, so it's impossible to work with it. Would you have any idea why?
When you say you are going to migrate all its functionallity to IPython console, what is the functionality to be migrated?
thanks!

**Comment by ccordoba12** [comment] 2017-02-04 19:32
> Would you have any idea why?

No, sorry.

> When you say you are going to migrate all its functionallity to IPython console, what is the functionality to be migrated?

* Evaluating a file in dedicated console.
* Inspecting `sys.path` and `os.environ` contents.

**Comment by ccordoba12** [comment] 2017-02-10 14:18
We'll add a warning so that users start to migrate to the IPython console before Spyder 3.2.

We're very sorry to do this. We've invested a lot of time to support this console, but given its many (and outstanding bugs) the time has come to remove it.

**Closed** 2017-02-10 14:19 UTC
Labels: component:Python Console, resolution:Wontfix, type:Bug

**Comment by jbeattie5768** [comment] 2017-03-19 12:25
I've been evaluating Spyder 3 (3.1.3)  so we can migrate from 2.3.8 and have this same problem with the console. Running scripts is fine, but we also do a lot of selection running and evaluation via the console that is problematic in 3. 
We will have to decide to either move to the IPython console (with the added overheads of graphics/backends, etc), stay with 2.3.8 or move to another IDE.
Most unfortunate.

**Comment by ofajardo** [comment] 2017-03-19 19:05
Very unfortunate indeed, I am sticking to 2.3.8 for the moment, but I guess I will have to move to another IDE in the future, as IPython is not an option for my project =(.

**Comment by andfoy** [comment] 2017-03-19 21:21
However, there's a new plugin that allows to execute system consoles, and therefore, you can execute Python inside it: https://github.com/spyder-ide/spyder-terminal

**Comment by ofajardo** [comment] 2017-03-19 21:41
Looks interesting. However the strength of spyder is the variable explorer. If that does not work, actually going to other IDEs sounds better. For example PyCharm has already a variable explorer but works only for pandas data frames and numpy arrays. For other types it has some viewer but is not as good as the spyder one. IEP also has a variable viewer, again not as good as spyder. But both those IDEs have the execute in thing. PyCharm has many other goodies like very good refactoring and version control integration.
If the spyder variable viewer is not usable, there is not much advantage in spyder anymore ...

**Comment by ccordoba12** [comment] 2017-03-21 01:27
> We will have to decide to either move to the IPython console (with the added overheads of graphics/backends, etc)

@jbeattie5768, we can't maintain two consoles. It's too much work for us because they have different implementations. The Python console was the work of Pierre Raybaut (Spyder's original author), but unfortunately he left the project more than 3 years ago.

Besides, I don't understand what you mean by *added overhads*. The backends stuff is a very simple thing to do once you understand what that's all about. I also think the IPython console is easier to use and more powerful, stable and easier to maintain.

> we also do a lot of selection running and evaluation via the console that is problematic in 3.

That works exactly the same (and even better) in the IPython console because we can correctly evaluate cells and selections there, whereas the Python console evaluate things line by line.

**Comment by felipeespic** [comment] 2017-03-27 00:06
Hi, I understand your reasons, but I think that removing the Python console will be a big mistake. The IPyhton console has a lot of drawbacks, for example:

- The debugger does not provide command history.
- Cannot do interactive plotting while debugging.

I spent so much time configuring the Pyhon console to make it work with similar debugging and plotting capabilities as MATLAB. It was impossible with IPython. 

Unfortunately, It seems that I will need to switch for another IDE.

**Comment by ccordoba12** [comment] 2017-03-27 03:23
We have good plans to significantly improve the debugging experience in the IPython console, and they are already underway. They will land in Spyder 4, and to fully concentrate on them (and release version 4 as soon as we can) we're not going to do more 3.x releases after 3.2 (just bugfixes).

If the Python console is essential for your work, then you can use still use Spyder 3.1.4 (to be released soon) until we release Spyder 4 (you can easily deactivate our updates dialog in Preferences). I don't see a problem with that, only that we're not going to fix any bug about the Python console from now on.

**Comment by felipeespic** [comment] 2017-03-27 23:45
Hi Carlos, thanks for your reply. I hope everything will work with Spyder in the future. I'll keep working with the current version that I have, for now.

**Comment by ajgpitch** [comment] 2017-08-21 09:53
Yes, seems it bit radical to me as well to ditch the Python console just because it has a few bugs. It does have a lot of very nice simple features - like hyperlinking the traceback. I think it would make more sense to keep a (very slightly) buggy Python console and leave to community to fix the bugs if they really bother them.

I use Spyder to develop and test code that I will then run on some cluster - that will run a Python (not IPython) interpreter. So I really want something that reflects the environment where my finished code will be run, by me and other users of the library.

I will give Spyder 4 a try when it comes out, but for now I will stick with 3.1.

In general I think Spyder is great - I spend more time inside it than any other application on my machine. I think the passion for the Python console in this thread is indicative of of the love many of us have for Spyder. Great work on the project folks.
