### ISSUE TITLE
segmentation fault on start in ubuntu 16.04 lts

### ISSUE THREAD

**Issue by notmyrealhandle** [spyder-ide/spyder#4457] opened 2017-05-10 18:08 UTC
## Description of your problem
spyder no longer starts.

The only error message I've seen comes from attempting to start from a bash shell: 
Segmentation fault (core dumped)

Suggestions for logs to check or other ways to get debugging info are appreciated.

**What steps will reproduce the problem?**

1. /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/spyder/app/start.py
2. 
3. 

**What is the expected output? What do you see instead?**
spyder to start.  see above.

**Please provide any additional information below**
spyder and all python packages installed/updated via pip3.  I don't use anaconda.  I had a long term spyder session open and tried to restart an ipython (6.0) kernel.  This reported back multiple failure attempts.  I attempted to restart spyder with the results above.  Removing ipython, reinstalling spyder, resetting (deleting all spyder configurations) has no effect.  Ipython works as expected elsewhere (emacs or command line).  

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.2
* Qt Version: 5.8.0
* PyQt Version: 5.8.2
* Operating system: up to date ubuntu 16.04 lts

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

wish I could...

updated just before this issue observed:
 pip3 install -U beautifulsoup4
 pip3 install -U Django
 pip3 install -U lazy-object-proxy
 pip3 install -U matplotlib
 pip3 install -U pandas
 pip3 install -U Pillow
 pip3 install -U requests
 pip3 install -U setuptools
 pip3 install -U urllib3

**Comment by notmyrealhandle** [comment] 2017-05-10 19:21
my brain turned on briefly
doing: python3 -m pdb start.py
causes pdb to crash at:
> /usr/local/lib/python3.5/dist-packages/spyder/app/start.py(14)<module>()
-> from spyder.config.main import CONF
(Pdb) n
Segmentation fault (core dumped)
and provides an ubuntu bug report in /var/crash...  I'd rather not post that publicly but will provide it privately to a spyder developer upon request.

**Comment by ccordoba12** [comment] 2017-05-10 21:37
I think this problem is caused by Pandas. Could you downgrade to Pandas 0.19.2 and try again?

**Comment by notmyrealhandle** [comment] 2017-05-10 21:48
Yes, that fixed it.  Thank you for responding so fast.

For the record, I am using my system python which I know is not recommended.  If my laziness caused this, my apologies for taking your time.  I'm looking at moving to a virtual environment now.

**Comment by goanpeca** [comment] 2017-05-10 22:06
@notmyrealhandle I would recommend to moving to a conda environment

**Closed** 2017-05-10 22:22 UTC
