### ISSUE TITLE
Viewer tab in Spyder to visualise intractive JavaScript based libraries in python 

### ISSUE THREAD

**Issue by dove88** [spyder-ide/spyder#19231] opened 2022-08-30 12:24 UTC
Hello Spyder,

Is there any possibility to view the JavaScript based intractive plots (Plot,Bokeh,Altair etc) in Spyder IDE?
As I understand we have only option for viewing such plots in default browser.
If there is an option, please advise me how to do it in 'plot' tab in Spyder.

Thank you,
Prigith.

**Comment by ccordoba12** [comment] 2022-08-30 15:26
Hey @dove88, thanks for reporting. Unfortunately this is not possible at the moment, but it's a high priority for us, so we'll try to include it in the next Spyder version (6.0), to be released next year.

**Comment by ccordoba12** [comment] 2022-08-30 15:26
I'm going to close this issue because it's a duplicate of issue #8367.

**Closed by ccordoba12** 2022-08-30 15:26 UTC

**Comment by mg3146** [comment] 2024-04-20 01:41
Hi - I was wondering if this ended up going anywhere?  I would love to have this feature

**Comment by ccordoba12** [comment] 2024-04-20 14:01
This is still top in our TODO list but we need additional funding to implement it because it's not an easy task. We asked for it this year and didn't get, so we'll try again next year.

**Comment by mg3146** [comment] 2024-04-20 19:46
Got it, thanks for the info.  I’m curious, is there somewhere I can see the funding / status of that kind of stuff ?

**Comment by ccordoba12** [comment] 2024-04-23 16:39
We're in conversations with different institutions about possible avenues for funding. When we have something more concrete to share with our community, we'll probably write a blog post about it: https://www.spyder-ide.org/blog/
