### ISSUE TITLE
Compatibility with Windows Server

### ISSUE THREAD

**Issue by abulgher** [spyder-ide/spyder#19079] opened 2022-08-16 12:12 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Installed the windows installer of the latest release (5.3.2) on a Windows Server 2016.
When starting the Spyder IDE, I get a message saying that spyder-terminal is not compatible with my operating system. It suggests that my OS is Win 7 and that I should update to a new version. 
Actually my OS is Win Server 2016. 
If I disable the terminal plugin, Spyder is starting.
Is spyder-terminal **not** compatible with Window server 2016? 

### What steps reproduce the problem?

1. Install 5.3.2 via the win installer on win server 2016
2. Manually modified app/mainwindow.py (see PR #19078) to have the error message window displayed. 
3. Start Spyder. 
4. The error message is shown and python is crashing

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.2
* Python version: (as provided by the window installer)
* Qt version: (as provided by the window installer)
* PyQt version: (as provided by the window installer)
* Operating System name/version: Windows Server 2016

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2022-08-16 16:55
Hey @abulgher, thanks for reporting. This error is a duplicate of issue #18901 and it'll be fixed in our next version (5.3.3), to be released in a couple of weeks.

> Is spyder-terminal not compatible with Window server 2016?

No, it's not. It's compatible with Windows 10 and above.

**Closed by ccordoba12** 2022-08-16 16:55 UTC

**Comment by GastaoDM** [comment] 2023-08-15 13:34
I just tried to install Spyder standalone 5.4.4 and got the same error.
![Windows 2016 - error](https://github.com/spyder-ide/spyder/assets/54849336/cea61194-ee23-4ee4-8b8f-b8c7db4677c9)

**Comment by ccordoba12** [comment] 2023-08-15 14:32
Hey @GastaoDM, thanks for reporting. Could you open a new issue about it? We'll try to take a look at it for Spyder 5.5, to be released in a couple of months.
