### ISSUE TITLE
Profiler results not found

### ISSUE THREAD

**Issue by gamselem** [spyder-ide/spyder#4434] opened 2017-05-06 09:37 UTC
Hi,

I'm trying to use the profiler in spyder. Here is what I do:
- Go to Run >Profile
- run code
- press "Stop" to stop profiling

I then get the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gabriel/.spyder-py3/profiler.results'
At the same time, the profiler says "Sorting data, please wait..."

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6
* Qt Version: 5.6.2     
* PyQt Version: 5.6.0 
* Operating system: MacOS Sierra 10.12.3 

## Dependencies

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

Thanks for your help

**Comment by ccordoba12** [comment] 2017-05-07 16:54
@andfoy, please take a look at this one.

**Comment by andfoy** [comment] 2017-08-17 21:46
I'm afraid I cannot reproduce this one:
![captura de pantalla de 2017-08-17 16-44-38](https://user-images.githubusercontent.com/1878982/29435185-9f15b40a-836b-11e7-9ee0-14cd3bb6e968.png)

**Comment by ccordoba12** [comment] 2017-08-18 21:48
Closing because we're not able to reproduce it, sorry.

**Closed by ccordoba12** 2017-08-18 21:48 UTC
Labels: component:Profiler, type:Bug

**Comment by gamselem** [comment] 2017-08-24 08:56
I've updated to the latest version and now the profiler works.

**Comment by ccordoba12** [comment] 2017-08-24 13:31
Great! Thanks for letting us know about it.

**Comment by Lemming0815** [comment] 2017-11-16 11:09
I have the same problem. Spyder version 3.2.4 on python 3.5.
You should be able to reproduce it, when you delete above mentioned profiler.results file. There seems to be no way of recreating the file. Even forced re-installation of spyder-ide didn't seem to help.
Can we re-open this, please?

**Comment by ccordoba12** [comment] 2017-11-16 14:11
We already fixed this one. The fix will be available in our 3.2.5 version.
