### ISSUE TITLE
why make this mistake and how to solve

### ISSUE THREAD

**Issue by WitLegend** [spyder-ide/spyder#4913] opened 2017-08-08 12:18 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Liang-PC\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 895, in set_working_directory
    refresh_console=False)
  File "C:\Users\Liang-PC\Anaconda2\lib\site-packages\spyder\plugins\workingdirectory.py", line 286, in chdir
    os.chdir( to_text_string(directory) )
WindowsError: [Error 3] : u'D:\\\ufffd\ufffd\ufffd\ufffd\\python'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.2 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-08 13:57
This is a duplicate of issue #4816. It's already fixed in it'll be part for Spyder **3.2.1**.

In the meantime, please use directories that only contain ascii characters to place your code.

**Closed by ccordoba12** 2017-08-08 13:57 UTC
Labels: resolution:Duplicate
