### ISSUE TITLE
Can't open or perform --reset

### ISSUE THREAD

**Issue by robintwhite** [spyder-ide/spyder#6362] opened 2018-02-01 19:10 UTC
## Description of your problem
Can't launch spyder (from navigator, command line or .exe)
When attempting to launch message  that spyder crashed during last session and should run spyder --reset and will remove configuration files, however upon trying to run this I get:
>spyder --reset
Traceback (most recent call last):
  File "C:\Users\Robin\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Robin\Anaconda3\lib\site-packages\spyder\app\start.py", line 155, in main
    from spyder.app import mainwindow
  File "C:\Users\Robin\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\Robin\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: DLL load failed: The specified procedure could not be found.

Checked update of conda and anaconda - all packages up-to-date
Tried uninstalling and reinstalling spyder, didn't help. 
I have another env for UI development which launches my PyQt5 GUI fine
Really don't want to have to do a full uninstall of anaconda and lose my other environments

**What steps will reproduce the problem?**

1. Windows crash while running spyder

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

.spyder-py3 and Anaconda3 location C:\Users\Robin

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by CAM-Gerlach** [comment] 2018-02-02 02:39
Thanks for reporting. Unfortunately, it seems very unlikely Spyder has any control over this problem, as it appears to be due to packages external to Spyder, quite possibly user installation issues with the same. You could try uninstalling and reinstalling related packages (``pyqt``, ``qtpy``, etc). Also, you can try installing Spyder into a fresh environment with just the required dependencies. Issue #5795 seems to be related, so also check there for more help.

Failing that, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. This includes uninstalling and reinstalling Anaconda; if all else fails, there isn't much else we can recommend since this appears to be outside of our control. Best of luck!

**Comment by ccordoba12** [comment] 2018-02-02 03:10
Did you use pip to install pyqt5 in your other env?

**Comment by robintwhite** [comment] 2018-02-02 03:18
I was successful in opening spyder in a separate env which I had previously installed spyder to work in. In my home env I have pyqt5-tools installed by pip, is that the problem? I was going to uninstall and reinstall pyqt,qtpy etc as suggested above by CAM

**Comment by robintwhite** [comment] 2018-02-02 03:34
I tried uninstalling pyqt5-tools by pip as well as qtpy and pyqt by conda, which uninstalled other packages with these dependencies - and reinstalling them, however I still get the same error with DLL load fail. For now I can use spyder in my other environment

**Comment by CAM-Gerlach** [comment] 2018-02-02 04:03
> I was successful in opening spyder in a separate env which I had previously installed spyder to work in

This suggests a particular package in the problem environment but not the other one might be to blame...

>  In my home env I have pyqt5-tools installed by pip, is that the problem?

Could very well be...can you try it?

> I tried uninstalling pyqt5-tools by pip as well as qtpy and pyqt by conda, which uninstalled other packages with these dependencies - and reinstalling them, however I still get the same error with DLL load fail.

Aside from a persistent configuration issue or something else esoteric, this would support the above hypothesis.

**Comment by ccordoba12** [comment] 2018-02-02 13:48
I'm afraid you broke your Anaconda installation by using pip to install pyqt5 and you'll have to reinstall it from scratch.

The problem is pip does not respect the symlinks conda uses in its environments and so it can break all of them at once.

Sorry, even if you manage to avoid a full reinstallation, this is not a Spyder problem, so I'm closing this issue.

**Closed by ccordoba12** 2018-02-02 13:48 UTC
Labels: status:AwaitingFollowup
