### ISSUE TITLE
Auto Suggestions not coming no suggestions for general functions and local variables 

### ISSUE THREAD

**Issue by gmmkmtgk** [spyder-ide/spyder#16680] opened 2021-10-30 18:10 UTC
Here are the screenshots 
![Screenshot from 2021-10-30 23-35-45](https://user-images.githubusercontent.com/51493190/139553746-eefe94c6-5e04-4dbe-b620-4f8932799f0c.png)
![Screenshot from 2021-10-30 23-35-52](https://user-images.githubusercontent.com/51493190/139553750-b3edc939-0e2b-41c4-a66a-8039acc3da47.png)

**Comment by ccordoba12** [comment] 2021-10-30 18:15
This is because you don't have the right dependencies of Jedi and Parso. So I'm going to close this issue as a duplicate of the one you just opened (#16679).

**Closed by ccordoba12** 2021-10-30 18:15 UTC
