### ISSUE TITLE
Download-Link of Spyder Windows leads to 404 error

### ISSUE THREAD

**Issue by eric-stumpe** [spyder-ide/spyder#22563] opened 2024-09-24 12:41 UTC
Hi,

I would like to try out the Windows standealone version.
However clicking on the "Download for Windows10+" button on the mainpage: https://www.spyder-ide.org/ directs me to: 
https://github.com/spyder-ide/spyder/releases/download/v6.0.1/Spyder-Windows-x86_64.exe, where I am getting a 404 error.

**Comment by mrclary** [comment] 2024-09-24 16:59
@eric-stumpe and @balazsan, thanks for reporting. This will be resolved asap, when the release assets are uploaded. Unfortunately we ran into a little hiccup 😬, and apologize for any inconvenience.

**Comment by mrclary** [comment] 2024-09-24 17:00
This is a duplicate of #22566

**Closed by mrclary** 2024-09-24 17:00 UTC
Labels: resolution:Duplicate

**Comment by dalthviz** [comment] 2024-09-24 21:23
Hi there, just in case, @eric-stumpe the download link for the Spyder installer from the website should be working now. For the moment you will get from it Spyder 6.0.0 though and most probably you will experience the issue mentioned by @balazsan (currently being followed over #22566) until we manage to upload the required assets to the GitHub release

**Comment by balazsan** [comment] 2024-09-25 08:56
I can confirm that I was able to update standalone Spyder to version 6.0.1. on Windows 10 using Spyder's update tool. Thanks for fixing this!
