### ISSUE TITLE
get_var_properties and get_namespace_view spyder call issue - related to numpy

### ISSUE THREAD

**Issue by nassayaglog** [spyder-ide/spyder#22365] opened 2024-08-21 16:11 UTC
### What steps will reproduce the problem?

at spyder start, spyder console is crashing in loop saying "Output from spyder call get_var_properties ( or get_namespace_view , alternating):
A module that was compiled using Numpy 1.x cannot be run in Numpy 2.0.1 as it may crash.

The background of this is that I have been trying to have a xgboost script run with some seaborn components and have started a brand new env for it installing everything w conda but somehow env seems to always get corrupted at some pt.

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\plugins\application\container.py", line 492, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\dependencies.py", line 458, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\dependencies.py", line 389, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\dependencies.py", line 331, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\matplotlib\__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\matplotlib\colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\matplotlib\ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\plugins\application\container.py", line 492, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\dependencies.py", line 458, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\dependencies.py", line 389, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\dependencies.py", line 331, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3\lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.9.19 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.15.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  72.1.0 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.0.1 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.13.1 (NOK)
sympy >=0.7.3                    :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\nassayag\Anaconda3\envs\tfminiconda-huggingface3:
#
# Name                    Version                   Build  Channel
absl-py                   2.0.0                    pypi_0    pypi
accelerate                0.31.0                   pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alabaster                 0.7.16           py39haa95532_0  
alembic                   1.13.2                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
arrow                     1.2.3            py39haa95532_1  
astroid                   2.14.2           py39haa95532_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
atomicwrites              1.4.0                      py_0  
attrs                     23.1.0           py39haa95532_0  
autopep8                  2.0.4              pyhd3eb1b0_0  
babel                     2.11.0           py39haa95532_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py39h2bbff1b_1  
beautifulsoup4            4.12.3           py39haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     24.4.2           py39haa95532_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blpapi                    3.23.0                   pypi_0    pypi
bottleneck                1.3.7            py39h9128911_0  
brotli                    1.0.9                h2bbff1b_8  
brotli-bin                1.0.9                h2bbff1b_8  
brotli-python             1.0.9            py39hd77b12b_8  
ca-certificates           2024.7.2             haa95532_0  
cachetools                5.3.2                    pypi_0    pypi
certifi                   2024.7.4         py39haa95532_0  
cffi                      1.16.0           py39h2bbff1b_1  
chardet                   4.0.0           py39haa95532_1003  
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7            py39haa95532_0  
cloudpickle               3.0.0            py39haa95532_0  
colorama                  0.4.6            py39haa95532_0  
colorlog                  6.8.2                    pypi_0    pypi
comm                      0.2.1            py39haa95532_0  
contourpy                 1.2.1                    pypi_0    pypi
cookiecutter              2.6.0            py39haa95532_0  
cpm-kernels               1.0.11                   pypi_0    pypi
cryptography              42.0.5           py39h89fc84f_1  
cudatoolkit               11.8.0               hd77b12b_0  
cudnn                     8.9.2.26               cuda11_0  
cycler                    0.11.0             pyhd3eb1b0_0  
datasets                  2.20.0                   pypi_0    pypi
debugpy                   1.6.7            py39hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.14                   pypi_0    pypi
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8            py39haa95532_0  
dm-tree                   0.1.8                    pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
docstring-to-markdown     0.11             py39haa95532_0  
docutils                  0.18.1           py39haa95532_3  
email-validator           2.2.0                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
exceptiongroup            1.2.0            py39haa95532_0  
exchange-calendars        4.5                      pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
fastapi                   0.111.0                  pypi_0    pypi
fastapi-cli               0.0.4                    pypi_0    pypi
filelock                  3.13.1           py39haa95532_0  
flake8                    7.0.0            py39haa95532_0  
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.51.0           py39h2bbff1b_0  
freetype                  2.12.1               ha860e81_0  
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.3.1         py39haa95532_0  
gast                      0.4.0                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3  
gmpy2                     2.1.2            py39h7f96b67_0  
google-auth               2.23.4                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  3.0.3                    pypi_0    pypi
grpcio                    1.59.2                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.23.4                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2  
icu                       73.1                 h6c2663c_0  
idna                      3.7              py39haa95532_0  
imagesize                 1.4.1            py39haa95532_0  
importlib-metadata        6.8.0                    pypi_0    pypi
importlib_metadata        7.0.1                hd3eb1b0_0  
importlib_resources       6.4.0            py39haa95532_0  
inflection                0.5.1            py39haa95532_0  
intel-openmp              2023.1.0         h59b6b97_46320  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.28.0           py39haa95532_0  
ipython                   8.15.0           py39haa95532_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.13.2           py39haa95532_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.19.1           py39haa95532_0  
jellyfish                 1.0.1            py39h36a85e1_0  
jinja2                    3.1.4            py39haa95532_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h827c3e9_3  
jsonschema                4.19.2           py39haa95532_0  
jsonschema-specifications 2023.7.1         py39haa95532_0  
jupyter_client            8.6.0            py39haa95532_0  
jupyter_core              5.7.2            py39haa95532_0  
jupyterlab_pygments       0.2.2            py39haa95532_0  
keras                     2.10.0                   pypi_0    pypi
keras-core                0.1.7                    pypi_0    pypi
keras-nlp                 0.6.3                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   24.3.1           py39haa95532_0  
kiwisolver                1.4.4            py39hd77b12b_0  
korean-lunar-calendar     0.3.1                    pypi_0    pypi
krb5                      1.20.1               h5b6d351_0  
lazy-object-proxy         1.10.0           py39h2bbff1b_0  
lcms2                     2.12                 h83e58a3_0  
lerc                      3.0                  hd77b12b_0  
libbrotlicommon           1.0.9                h2bbff1b_8  
libbrotlidec              1.0.9                h2bbff1b_8  
libbrotlienc              1.0.9                h2bbff1b_8  
libclang                  16.0.6                   pypi_0    pypi
libclang13                14.0.6          default_h8e68704_1  
libdeflate                1.17                 h2bbff1b_1  
libpng                    1.6.39               h8cc25b3_0  
libpq                     12.17                h906ac69_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libta-lib                 0.4.0                he774522_0    conda-forge
libtiff                   4.5.1                hd77b12b_0  
libuv                     1.48.0               h827c3e9_0  
libwebp                   1.3.2                hbc33d0d_0  
libwebp-base              1.3.2                h2bbff1b_0  
lightning                 2.3.3                    pypi_0    pypi
lightning-utilities       0.11.3.post0             pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_1  
mako                      1.3.5                    pypi_0    pypi
markdown                  3.5.1                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3            py39h2bbff1b_0  
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-base           3.8.4            py39h4ed8f06_0  
matplotlib-inline         0.1.6            py39haa95532_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdurl                     0.1.2                    pypi_0    pypi
mistune                   2.0.4            py39haa95532_0  
mkl                       2023.1.0         h6b88ed4_46358  
mkl-service               2.4.0            py39h2bbff1b_1  
mkl_fft                   1.3.8            py39h2bbff1b_0  
mkl_random                1.2.4            py39h59b6b97_0  
more-itertools            10.1.0           py39haa95532_0  
mpc                       1.1.0                h7edee0f_1  
mpfr                      4.0.2                h62dcd97_1  
mpir                      3.0.0                hec2e145_1  
mpmath                    1.3.0            py39haa95532_0  
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
munkres                   1.1.4                      py_0  
mypy_extensions           1.0.0            py39haa95532_0  
namex                     0.0.7                    pypi_0    pypi
nbclient                  0.8.0            py39haa95532_0  
nbconvert                 7.10.0           py39haa95532_0  
nbformat                  5.9.2            py39haa95532_0  
nest-asyncio              1.6.0            py39haa95532_0  
networkx                  3.2.1            py39haa95532_0  
ninja                     1.10.2               haa95532_5  
ninja-base                1.10.2               h6d14046_5  
numexpr                   2.8.7            py39h2cd9be0_0  
numpy                     2.0.1                    pypi_0    pypi
numpy-base                1.26.4           py39h65a83cf_0  
numpydoc                  1.7.0            py39haa95532_0  
oauthlib                  3.2.2                    pypi_0    pypi
openjpeg                  2.5.2                hae555c5_0  
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.0.14               h827c3e9_0  
opt-einsum                3.3.0                    pypi_0    pypi
optuna                    3.6.1                    pypi_0    pypi
optuna-integration        3.6.0                    pypi_0    pypi
orjson                    3.10.6                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.2                    pypi_0    pypi
pandas-market-calendars   4.3.1                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathspec                  0.10.3           py39haa95532_0  
patsy                     0.5.6                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.4.0           py39h827c3e9_0  
pip                       24.2             py39haa95532_0  
platformdirs              3.10.0           py39haa95532_0  
plotly                    5.18.0                   pypi_0    pypi
pluggy                    1.0.0            py39haa95532_1  
ply                       3.11             py39haa95532_0  
poyo                      0.5.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.43           py39haa95532_0  
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.0            py39h2bbff1b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   16.1.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycodestyle               2.11.1           py39haa95532_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydocstyle                6.3.0            py39haa95532_0  
pyflakes                  3.2.0            py39haa95532_0  
pygments                  2.15.1           py39haa95532_1  
pylint                    2.16.2           py39haa95532_0  
pylint-venv               3.0.3            py39haa95532_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyluach                   2.2.0                    pypi_0    pypi
pynacl                    1.5.0            py39h8cc25b3_0  
pyopenssl                 24.2.1           py39haa95532_0  
pyparsing                 3.0.9            py39haa95532_0  
pyqt                      5.15.10          py39hd77b12b_0  
pyqt5-sip                 12.13.0          py39h2bbff1b_0  
pyqtwebengine             5.15.10          py39hd77b12b_0  
pysocks                   1.7.1            py39haa95532_0  
python                    3.9.19               h1aa4202_1  
python-dateutil           2.9.0post0       py39haa95532_2  
python-dotenv             1.0.1                    pypi_0    pypi
python-fastjsonschema     2.16.2           py39haa95532_0  
python-lsp-black          2.0.0            py39haa95532_0  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-server         1.10.0           py39haa95532_0  
python-multipart          0.0.9                    pypi_0    pypi
python-slugify            5.0.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytoolconfig              1.2.6            py39haa95532_0  
pytorch-forecasting       1.0.0                    pypi_0    pypi
pytorch-lightning         2.3.3                    pypi_0    pypi
pytorch-optimizer         2.12.0                   pypi_0    pypi
pytz                      2024.1           py39haa95532_0  
pywin32                   305              py39h2bbff1b_0  
pywin32-ctypes            0.2.2            py39haa95532_0  
pyyaml                    6.0.1            py39h2bbff1b_0  
pyzmq                     25.1.2           py39hd77b12b_0  
qdarkstyle                3.2.3              pyhd3eb1b0_0  
qstylizer                 0.2.2            py39haa95532_0  
qt-main                   5.15.2              h19c9488_10  
qt-webengine              5.15.9               h5bd16bc_7  
qtawesome                 1.2.2            py39haa95532_0  
qtconsole                 5.5.1            py39haa95532_0  
qtpy                      2.4.1            py39haa95532_0  
referencing               0.30.2           py39haa95532_0  
regex                     2024.7.24        py39h827c3e9_0  
requests                  2.32.3           py39haa95532_0  
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
rope                      1.12.0           py39haa95532_0  
rpds-py                   0.10.6           py39h062c2fa_0  
rsa                       4.9                      pypi_0    pypi
rtree                     1.0.1            py39h2eaa2aa_0  
safetensors               0.4.1                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
seaborn                   0.13.2           py39haa95532_0  
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                72.1.0           py39haa95532_0  
shellingham               1.5.4                    pypi_0    pypi
sip                       6.7.12           py39hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.1                    pypi_0    pypi
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5              py39haa95532_0  
sphinx                    7.3.7            py39h827c3e9_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.10           py39haa95532_0  
spyder                    5.5.1            py39haa95532_3  
spyder-kernels            2.5.0            py39haa95532_0  
sqlalchemy                2.0.31                   pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
starlette                 0.37.2                   pypi_0    pypi
statsmodels               0.14.2                   pypi_0    pypi
sympy                     1.12             py39haa95532_0  
tabulate                  0.9.0            py39haa95532_0  
tbb                       2021.8.0             h59b6b97_0  
tenacity                  8.2.3                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.1                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-hub            0.15.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorflow-text           2.10.0                   pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             3.2.0                    pypi_0    pypi
three-merge               0.1.1              pyhd3eb1b0_0  
tia                       1.2.0                    pypi_0    pypi
tinycss2                  1.2.1            py39haa95532_0  
tk                        8.6.14               h0416ee5_0  
tokenizers                0.19.0                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py39haa95532_0  
tomlkit                   0.11.1           py39haa95532_0  
toolz                     0.12.0                   pypi_0    pypi
torchmetrics              1.4.0.post0              pypi_0    pypi
tornado                   6.4.1            py39h827c3e9_0  
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3           py39haa95532_0  
transformers              4.44.0                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing_extensions         4.11.0           py39haa95532_0  
tzdata                    2024a                h04d1e81_0  
ujson                     5.10.0           py39h5da7b33_0  
unicodedata2              15.1.0           py39h2bbff1b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   2.0.7                    pypi_0    pypi
uvicorn                   0.30.1                   pypi_0    pypi
vc                        14.40                h2eaa2aa_0  
vs2015_runtime            14.40.33807          h98bb1dd_0  
watchdog                  4.0.1            py39haa95532_0  
watchfiles                0.22.0                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39haa95532_1  
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
whatthepatch              1.0.2            py39haa95532_0  
wheel                     0.43.0           py39haa95532_0  
win_inet_pton             1.1.0            py39haa95532_0  
wrapt                     1.16.0                   pypi_0    pypi
xgboost                   2.1.1                    pypi_0    pypi
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.6                h8cc25b3_1  
yaml                      0.2.5                he774522_0  
yapf                      0.40.2           py39haa95532_0  
yarl                      1.9.4                    pypi_0    pypi
zeromq                    4.3.5                hd77b12b_0  
zipp                      3.17.0           py39haa95532_0  
zlib                      1.2.13               h8cc25b3_1  
zstd                      1.5.5                hd43e919_2  

```
</details>

**Comment by dalthviz** [comment] 2024-08-23 22:15
Hi @nassayaglog seems like you have matplotlib, pandas and numpy incompatible versions. Also, seems like you are mixing conda packages with pip packages. If you want to use packages/packages versions only available via pip I would suggest you to create a clean conda env installing only Python and then install any packages only via pip. For more info on that you can check https://docs.spyder-ide.org/current/faq.html#using-spyder

However, thinking about this, probably we should try to handle/capture this kind of errors @ccordoba12 ? Seems like this errors come from the dependencies detection logic?

**Comment by dalthviz** [comment] 2024-11-06 23:52
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/22187

**Closed by dalthviz** 2024-11-06 23:52 UTC
Labels: resolution:Duplicate, component:Variable Explorer, component:IPython Console, component:Main Window, status:Awaiting Followup
