### ISSUE TITLE
Spyder5 fail to launch. Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by blubye** [spyder-ide/spyder#20666] opened 2023-03-10 03:18 UTC
### What steps reproduce the problem?
Right after installing spyder5 as per instructions 
$ conda create -c conda-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy cython

Spyder5 fail to launch.

(spyder) [rubye@localhost ~]$ spyder
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
(spyder) [rubye@localhost ~]$ 

### Paste Traceback/Error Below (if applicable)

(base) [rubye@localhost ~]$ conda activate spyder
(spyder) [rubye@localhost ~]$ spyder
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
(spyder) [rubye@localhost ~]$ 

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.2
* Python version: Python 3.9.16 
* Qt version: 
* PyQt version:
# Name                    Version                   Build  Channel
pyqt                      5.15.7           py39h6a678d5_1  
pyqt5-sip                 12.11.0          py39h6a678d5_1  
pyqtwebengine             5.15.7           py39h6a678d5_1  
 
* Operating System name/version: rhel9.1 plow

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2023-03-10 17:29
Hey @blubye, thanks for reporting. This could be still be related to your usage of `LD_LIBRARY_PATH`, which makes Linux mix conda-forge and system packages.

Or it could be that you don't have the right system packages to run Qt. To check for that, please run the following command in a terminal and see if there are missing libraries reported by it:

    ldd ~/<path to miniconda>/envs/spyder/lib/libQt5XcbQpa.so

Conda-forge should provide most of what's needed, but it could be that you don't have Xorg or some of its dependencies installed (Spyder doesn't work on very thin Docker instances or machines without graphical support).

If `ldd` reports missing libraries, then you need to look what RPM package corresponds to them and install them with yum of dnf (I don't know exactly how to do that because I use Ubuntu, but a bit of googling should give you the answer).

**Comment by ccordoba12** [comment] 2023-03-10 17:38
In addition, as I mentioned in your previous issue, this is not a problem with Spyder but with your system. So, I'm going to close this issue because there's no more help we can offer you to solve it.

And since I think it is up to you to solve it (you wouldn't encounter issues like this in a regular desktop Linux system), I'm afraid our help goes up to this point. Any additional issue you open about it will be closed as "Won't fix".

I'm sorry but we're a very small team, we have tons of issues to address and this is a very specific problem that's not actually a bug in Spyder. With a bit of googling I'm sure you'll be able to figure it out yourself.

**Closed by ccordoba12** 2023-03-10 17:38 UTC

**Comment by rjtanner** [comment] 2023-03-10 18:08
I had this same problem and it took some time Googling it to figure it out. How to exactly address the problem is very unclear from all of the other answers out there. So to help anyone who comes looking for it, this is how to solve the problem from scratch.

This also works if you are getting errors such as:

`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

In a terminal set 

`export QT_DEBUG_PLUGINS=1`

and then try opening spyder

`spyder`

It will fail but it will spit out a bunch of info like this:

```
QFactoryLoader::QFactoryLoader() checking directory path "/home/rtanner2/anaconda3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqeglfs.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqminimal.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqminimalegl.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqoffscreen.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqvnc.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqwebgl.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqwebgl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "webgl"
        ]
    },
    "archreq": 0,
    "className": "QWebGLIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("webgl")
QFactoryLoader::QFactoryLoader() looking at "/home/rtanner2/anaconda3/plugins/platforms/libqxcb.so"
Found metadata in lib /home/rtanner2/anaconda3/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/rtanner2/anaconda3/bin/platforms" ...
Cannot load library /home/rtanner2/anaconda3/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/rtanner2/anaconda3/plugins/platforms/libqxcb.so" : "Cannot load library /home/rtanner2/anaconda3/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted
```

Near the end there will be a library listed which is the one failing. It will be listed on the line that starts with `Cannot load library`. In this case it was `libqxcb.so`. Use the command `ldd` to find out what libraries you are missing like this (change the path in the command to your ownpath):

`ldd /home/rtanner2/anaconda3/plugins/platforms/libqxcb.so | grep "not found"`

This will produce a list of missing libraries. In my case it was,

```
libxcb-icccm.so.4 => not found
libxcb-icccm.so.4 => not found
```

I was able to install the library using,
```
sudo apt-get update
sudo apt-get install libxcb-icccm4
```

If you are unsure about the exact name of the library you can find all of the relevant libraries by using this command:

`apt-cache search libxcb`

This command will produce the following output:

```
libpthread-stubs0-dev - pthread stubs not provided by native libc, development files
libxcb-composite0 - X C Binding, composite extension
libxcb-composite0-dev - X C Binding, composite extension, development files
libxcb-damage0 - X C Binding, damage extension
libxcb-damage0-dev - X C Binding, damage extension, development files
libxcb-doc - X C Binding, development documentation
libxcb-dpms0 - X C Binding, dpms extension
libxcb-dpms0-dev - X C Binding, dpms extension, development files
libxcb-dri2-0 - X C Binding, dri2 extension
libxcb-dri2-0-dev - X C Binding, dri2 extension, development files
libxcb-dri3-0 - X C Binding, dri3 extension
libxcb-dri3-dev - X C Binding, dri3 extension, development files
libxcb-ewmh-dev - utility libraries for X C Binding -- ewmh, development files
libxcb-ewmh2 - utility libraries for X C Binding -- ewmh
libxcb-glx0 - X C Binding, glx extension
libxcb-glx0-dev - X C Binding, glx extension, development files
libxcb-icccm4 - utility libraries for X C Binding -- icccm
libxcb-icccm4-dev - utility libraries for X C Binding -- icccm, development files
libxcb-image0 - utility libraries for X C Binding -- image
libxcb-image0-dev - utility libraries for X C Binding -- image, development files
libxcb-keysyms1 - utility libraries for X C Binding -- keysyms
libxcb-keysyms1-dev - utility libraries for X C Binding -- keysyms, development files
libxcb-present-dev - X C Binding, present extension, development files
libxcb-present0 - X C Binding, present extension
libxcb-randr0 - X C Binding, randr extension
libxcb-randr0-dev - X C Binding, randr extension, development files
libxcb-record0 - X C Binding, record extension
libxcb-record0-dev - X C Binding, record extension, development files
libxcb-render-util0 - utility libraries for X C Binding -- render-util
libxcb-render-util0-dev - utility libraries for X C Binding -- render-util
libxcb-render0 - X C Binding, render extension
libxcb-render0-dev - X C Binding, render extension, development files
libxcb-res0 - X C Binding, res extension
libxcb-res0-dev - X C Binding, res extension, development files
libxcb-screensaver0 - X C Binding, screensaver extension
libxcb-screensaver0-dev - X C Binding, screensaver extension, development files
libxcb-shape0 - X C Binding, shape extension
libxcb-shape0-dev - X C Binding, shape extension, development files
libxcb-shm0 - X C Binding, shm extension
libxcb-shm0-dev - X C Binding, shm extension, development files
libxcb-sync-dev - X C Binding, sync extension, development files
libxcb-sync1 - X C Binding, sync extension
libxcb-util-dev - utility libraries for X C Binding -- atom, aux and event
libxcb-util0-dev - dummy transitional package for utility libraries for X C Binding
libxcb-util1 - utility libraries for X C Binding -- atom, aux and event
libxcb-xf86dri0 - X C Binding, xf86dri extension
libxcb-xf86dri0-dev - X C Binding, xf86dri extension, development files
libxcb-xfixes0 - X C Binding, xfixes extension
libxcb-xfixes0-dev - X C Binding, xfixes extension, development files
libxcb-xinerama0 - X C Binding, xinerama extension
libxcb-xinerama0-dev - X C Binding, xinerama extension, development files
libxcb-xinput-dev - X C Binding, xinput extension, development files
libxcb-xinput0 - X C Binding, xinput extension
libxcb-xkb-dev - X C Binding, XKEYBOARD extension, development files
libxcb-xkb1 - X C Binding, XKEYBOARD extension
libxcb-xtest0 - X C Binding, xtest extension
libxcb-xtest0-dev - X C Binding, xtest extension, development files
libxcb-xv0 - X C Binding, xv extension
libxcb-xv0-dev - X C Binding, xv extension, development files
libxcb-xvmc0 - X C Binding, xvmc extension
libxcb-xvmc0-dev - X C Binding, xvmc extension, development files
libxcb1 - X C Binding
libxcb1-dev - X C Binding, development files
libx11-xcb-perl - perl bindings for libxcb
libxcb-cursor-dev - utility libraries for X C Binding -- cursor, development files
libxcb-cursor0 - utility libraries for X C Binding -- cursor
libxcb-imdkit-dev - XIM protocol implementation in XCB (development files)
libxcb-imdkit1 - XIM protocol implementation in XCB
libxcb-xrm-dev - utility functions for the X resource manager, development files
libxcb-xrm0 - utility functions for the X resource manager
```

There might be multiple libraries you have to install. Some of the common ones are:
```
sudo apt install libxcb-image0
sudo apt install libxcb-keysyms1
sudo apt install libxcb-render-util0
sudo apt install libxcb-xkb1
sudo apt install libxkbcommon-x11-0
```

Just keep going through all the libraries that are listed as `not found` until you have them all installed.

**Comment by Wind-177** [comment] 2023-08-30 10:13
spyder太难用了，莫名其妙的问题

**Comment by Oliver-Prislan** [comment] 2024-05-04 17:19
Actually the three lines provided by rjtanner helped me to resolve it:
# sudo apt install libxcb-image0
# sudo apt install libxcb-keysyms1
# sudo apt install libxcb-render-util0
 - as I didn't get the output of the command
