### ISSUE TITLE
I cannot debug the file !

### ISSUE THREAD

**Issue by andre5620** [spyder-ide/spyder#17480] opened 2022-03-13 02:17 UTC
### What steps will reproduce the problem?

> c:\users\dedeh\documents\documentos - organizacional\1 - cursos\coursera\introdução a ciencia da computação com python\ii\semana 1\multi_matriz.py(1)<module>()
----> 1 import sao_multiplicaveis
      2 import Matriz
      3 
      4 def multiple_matriz(A, B):
      5

**Comment by andre5620** [comment] 2022-03-13 02:18
I'm using the win11.

**Comment by ccordoba12** [comment] 2022-03-13 16:22
Hey @<>, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by ccordoba12** [comment] 2022-03-13 16:23
Please do that and let us know if it works for you.

**Comment by andre5620** [comment] 2022-03-13 22:10
Hey @ccordoba12 doesn't work the recommendation.

**Comment by ccordoba12** [comment] 2022-03-13 22:20
Could you explain what's problem you have right now?

**Comment by hannahbus** [comment] 2022-03-16 10:22
We have run into a similar issue in our team. The debugging tool does not work. We can start the debugger but then nothing happens. The issue extends to Windows and Mac OS.  

Configuration of Mac machine
Operation System: macOS Monterey - Version 12.1 
Spyder Version - 5.1.5 
IPython - 8.1.1  
Python - 3.8.12 

We have tested to update Python or Spyder, but the issue is not resolved. Happy to provide further details. Thanks in advance for your help. 

Best, 

Hannah

**Comment by freeboro** [comment] 2022-03-16 15:44
After stumbling over the same problem with Spyder-5.1.5 from the base conda environment, I updated by

```
conda config --add channels conda-forge
conda install --yes spyder-kernels spyder=5.2.2
```

NB: This is a miniconda-based container, so a separate conda-forge environment is not really needed ... which simplifies connecting to the kernel.

Now debugging works ;-)

My configuration:

* Spyder version: 5.2.2 None
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.10.104

**Comment by freeboro** [comment] 2022-03-16 15:47
... and IPython-7.32.0, which was downgraded by the conda-forge channel.

**Comment by hannahbus** [comment] 2022-03-25 09:34
Thanks, @freeboro comments did the magic; the debugging tool works now. Many thanks!

**Comment by ccordoba12** [comment] 2022-03-26 16:48
@hannahbus, great! Thanks for letting us know about it.

**Closed by ccordoba12** 2022-03-26 16:48 UTC
Labels: status:Awaiting Followup
