### ISSUE TITLE
Can't Stop Debugger

### ISSUE THREAD

**Issue by Davo36** [spyder-ide/spyder#4937] opened 2017-08-10 23:24 UTC
When I run the debugger on a script by pressing Ctrl-F5, it stops at the first breakpoint.  I can then not exit the debugger immediately - execution continues until the whole script is run.

**What steps will reproduce the problem?**

1. Running a script in it with a breakpoint set.  
2. The debugger does not exit straight away, the script keeps running.  So if this is a script that takes a long time to run then:
3. Trying to exit the debugger by typing 'q' in the iPython console.  Or clicking the stop button on the toolbar.  Or pressing Ctrl-Shift-F12.  Or choosing the stop option from the Debugging Control menu.

**What is the expected output? What do you see instead?**
Well normally the debugger would exit and the IPython console prompt would be there.  No line highlighted in editor etc. i.e. debugging mode has ended.

If I press 'q' and hit return, nothing happens, the caret just blinks next to the 'q'.  If I then repeatedly press Ctrl-c and press the stop button on the toolbar at the top, I get:

--KeyboardInterrupt--
For copying text while debugging, use Ctrl+Shift+C

I can only stop it by restarting the IPython kernel.

If I run a very short script, put a breakpoint in it, debug it, then hit 'q' the rest of the script is run and the debugger stops as per normal.  So the issue is that the debugger does not stop where it is when the 'q' is entered or the stop button pushed.

**Please provide any additional information below**
I have upgraded to 3.2 on 2 windows machines running Windows 10.  Both have the same issue.

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.0
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system: Windows 10.

## Dependencies

IPython >=4.0    :  5.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-08-11 02:27
Please post an example script that's failing for you.

**Comment by Davo36** [comment] 2017-08-11 02:40
Hi Carlos,

Nearly any script will do it I think.  For example:

```
for i in range(100):
    print(i)
```

If I put a breakpoint on the second line, then debug via Ctrl-F5, execution stops on the second line as it should.

But then if I type 'q' in the IPython console it prints out every number until 99.

**Comment by Davo36** [comment] 2017-08-11 03:47
@ccordoba12 

And here's a slightly different example Carlos:

i = 0
while i < 10000000000000000000:
    print(i)
    i += 1

Again, if you put a breakpoint on the print(i) line, then enter debugging with Ctrl-F5, it stops as required, but then if you type 'q' or push the stop button etc. it will attempt to complete the script.  Which in this case crashes Spyder... (but that will be another issue).

**Comment by ccordoba12** [comment] 2017-08-11 14:04
This is a duplicate of issue #4214. To fix it, you need to update IPython, so a simple

    conda update ipython

will do the job.

**Closed by ccordoba12** 2017-08-11 14:04 UTC
Labels: component:Debugger, type:Bug

**Comment by Davo36** [comment] 2017-08-11 20:27
@ccordoba12 And it does too!

Thanks very much Carlos.

**Comment by ccordoba12** [comment] 2017-08-11 23:52
No prob ;-)

**Comment by Severac** [comment] 2020-05-29 21:29
Hi,
I have the same problem : execution continues until the whole script is run.

ipython 7.8.0 and spyder 3.3.6

**Comment by notafox** [comment] 2022-02-04 20:09
I have spyder 5.1.5, it is not working. the problem is exactly the same as @Davo36 
ipykernel                 6.4.1            py38h06a4308_1  
ipython                   7.31.1           py38h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1

**Comment by notafox** [comment] 2022-02-05 08:18
Solved it: 
Spyder can be evoked from conda base environment, follow this https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach to set up the python interpreter. No need to install spyder in each conda virtual environment
