### ISSUE TITLE
Spyder 4.0.0rc2 cursor hover bug

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10790] opened 2019-11-21 09:17 UTC
Code to reproduce this issue:
```python
class MyException(TypeError):
    pass

a = 3
```

Save this as script. You don't even need to run it. Just use your mouse to hover over `MyException`, and "Issue reporter" shows up.

The detailed message is:

```
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1217, in handle_hover_response
    at_point=self._last_point)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\widgets\mixins.py", line 634, in show_hint
    inspect_word=inspect_word)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\widgets\mixins.py", line 474, in _check_signature_and_format
    name_plus_char = inspect_word + open_func_char
TypeError: can only concatenate tuple (not "str") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\spyder4\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Anaconda3\envs\spyder4\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Anaconda3\envs\spyder4\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Anaconda3\envs\spyder4\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Anaconda3\envs\spyder4\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\app\mainwindow.py", line 3716, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\app\mainwindow.py", line 3598, in run_spyder
    app.exec_()
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 349, in on_msg_received
    handler(resp['result'], req_id)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\languageserver\providers\document.py", line 169, in process_hover_result
    {'params': contents})
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 284, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\plugin.py", line 161, in _maybe_send_locked
    send()
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\completion\plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 921, in handle_response
    handler(params)
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1224, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "C:\Anaconda3\envs\spyder4\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 952, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)

```

**Comment by MrFuppes** [comment] 2019-11-21 13:33
related? https://github.com/spyder-ide/spyder/issues/10752

**Comment by ccordoba12** [comment] 2019-11-21 13:59
Duplicate of #10752

**Closed by ccordoba12** 2019-11-21 13:59 UTC
