### ISSUE TITLE
Improvements on display in file explorer

### ISSUE THREAD

**Issue by AaronX121** [spyder-ide/spyder#12930] opened 2020-06-02 09:04 UTC
## Problem Description
Fonts in the file explorer change when adjusting the length of column NAME to one size smaller than file name.

Thank you for developing this powerful IDE :-)

**Normal Case:**
![before](https://user-images.githubusercontent.com/22359569/83500937-01f38980-a4f2-11ea-8f75-ce55ba611555.png)

**Abnormal Case:**
![after](https://user-images.githubusercontent.com/22359569/83500975-0b7cf180-a4f2-11ea-8da2-aa7a5bf44b97.png)

### What steps reproduce the problem?

1.  Simply adjust the length of column NAME in file explorer.

### What is the expected output? What do you see instead?
I expect that fonts should remain the same for the sake of beauty.

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

#### Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

#### Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

**Comment by steff456** [comment] 2020-06-03 20:34
Hi @AaronX121,

I could not reproduce this issue in Windows, macOS or Linux. It is probably a problem with Qt that will be fixed once we bump to a latest version. I'm going to close this issue for now.

Thanks for reporting!

**Closed by steff456** 2020-06-03 20:34 UTC
