### ISSUE TITLE
error

### ISSUE THREAD

**Issue by prospero78** [spyder-ide/spyder#6915] opened 2018-04-08 17:52 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 890, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 111, in set_cwd
    self.silent_execute(code)
  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 273, in silent_execute
    self.kernel_client.execute(to_text_string(code), silent=True)
AttributeError: 'NoneType' object has no attribute 'execute'
Traceback (most recent call last):
  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\projects.py", line 233, in _create_project
    self.open_project(path=path)
  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\projects.py", line 269, in open_project
    self.restart_consoles()
  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\projects.py", line 386, in restart_consoles
    self.main.ipyconsole.restart()
  File "D:\coding\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py"

**Comment by ccordoba12** [comment] 2018-04-08 19:01
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-04-17 15:03
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-04-17 15:03 UTC
Labels: status:Awaiting Followup
