### ISSUE TITLE
variable view not in sync while debugging

### ISSUE THREAD

**Issue by mikhailo** [spyder-ide/spyder#17325] opened 2022-02-11 00:23 UTC
### What steps will reproduce the problem?

debug a function containing a matrix to be returned. During execution open the matrix view by double clicking it in variable explorer. Watch the variable by advancing in debug mode. 
Idia is to watch what happends while clicking, next, next next and see how values are changing in matrix view. However the matrix view ramains unchanged and the only way to see the updated values is to close the view and double click to open the content of the matrix again and again.
It is  suboptimal and clumsy, especially when I am in a for loop and watch the changes in my matrix.

Expected behavior: when I click next in debug mode, whatever matrix I am currently watching is getting updated. That is: not only variable explorer to be refreshed but also its children produced by double clicking on the variable view.

**Comment by ccordoba12** [comment] 2022-02-11 14:49
Hey @mikhailo, thanks for reporting. This is a current limitation and it has been brought to our attention several times before.

Unfortunately, this is not an easy problem to solve so it could take us I think more than a year to address it because there are several other things we're working on at the moment too.

**Comment by ccordoba12** [comment] 2022-02-11 14:49
I'm going to close this as a duplicate of issue #6325.

**Closed by ccordoba12** 2022-02-11 14:49 UTC
