### ISSUE TITLE
The code runs, but a error window with this error appears "SyntaxError: unexpected EOF while parsing"

### ISSUE THREAD

**Issue by lucaslampier** [spyder-ide/spyder#4907] opened 2017-08-07 03:43 UTC
## Description

I was working with the following libs:
"""
import pygame 
from pygame.locals import *

from OpenGL.GL import *
from OpenGL.GLU import *

import random
"""

  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 311, in handle_exec_method
    view = ast.literal_eval(data['text/plain'])
  File "C:\ProgramData\Anaconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 317, in handle_exec_method
    properties = ast.literal_eval(data['text/plain'])
  File "C:\ProgramData\Anaconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\ProgramData\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 9001
    ...}
       ^
SyntaxError: unexpected EOF while parsing
  File "C:\ProgramData\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 3989
    ...}
       ^
SyntaxError: unexpected EOF while parsing

**Comment by ccordoba12** [comment] 2017-08-07 04:00
This is a duplicate of issue #4873, which we plan to fix in 3.2.1.

For now please avoid using star imports (`from foo import *`)

**Closed by ccordoba12** 2017-08-07 04:00 UTC
