### ISSUE TITLE
curious upgrade or an intentional malware insertion

### ISSUE THREAD

**Issue by BCCozad817** [spyder-ide/spyder#13452] opened 2020-08-01 22:33 UTC
### What steps will reproduce the problem?

Spyder tutorial. hyper link "chunks of code that are separated by delimiters". My File Explorer is now overriding my search files. What is Downloading: Windows_Server_2016 6.4 GB python.exe downloading from OneDrive? Was code snuck in? Anyway Spyer 4.1.4 fixes it.

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.17.0 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by BCCozad817** [comment] 2020-08-01 22:43
"chunks of code that are separated by delimiters" Spyder tutorial opening subsection "What happen when you execute a program?" 
![SpyderCurious](https://user-images.githubusercontent.com/51197455/89111682-ce1bde00-d426-11ea-910b-699f31e26efd.png)

**Comment by steff456** [comment] 2020-08-04 20:16
Hi @BCCozad817,
I'm unable to reproduce your error in Linux, macOS and Windows. Can you please upload a gif with the error you are having?

**Comment by steff456** [comment] 2020-08-11 15:40
I'm closing this issue because there wasn't a follow-up response after a week

**Closed by steff456** 2020-08-11 15:40 UTC
Labels: status:Awaiting Followup

**Comment by BCCozad817** [comment] 2020-08-12 03:02
peace paz

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
