### ISSUE TITLE
Does not open the value of the variable. Says "could not pickle object as excessive deep recursion required

### ISSUE THREAD

**Issue by Mosin1987** [spyder-ide/spyder#11572] opened 2020-02-16 10:26 UTC
### What steps will reproduce the problem?

import pandas as pd
from bs4 import BeautifulSoup as bts
import urllib.request as ur

#%%

stock = "GAZP" #created a variable that goes into url
url_mfso = "https://smart-lab.ru/q/" + stock + "/f/y/MSFO/" #url with flexible variable

read_data = ur.urlopen(url_mfso).read() #open and read that url code
soup_mfso = bts(read_data,'lxml') #take the code and convert to lxlm view

mfso=[] #empty list

for l in soup_mfso.find_all('td'):
    mfso.append(l.string)

### Traceback
```python-traceback
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1037, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1386, in get_value
    return self.parent().get_value(name)
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1439, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 99, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 542, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 114, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 420, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 480, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_value:

  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    self._set_call_return_value(msg_dict, return_value)

  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 376, in _set_call_return_value
    comm_id=self.calling_comm_id)

  File "C:\Users\mikha\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 245, in _send_message
    data, protocol=self._comms[comm_id]['pickle_protocol'])]

  File "C:\Users\mikha\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 1125, in dumps
    cp.dump(obj)

  File "C:\Users\mikha\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 486, in dump
    raise pickle.PicklingError(msg)

_pickle.PicklingError: Could not pickle object as excessively deep recursion required.

```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.0 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-02-16 18:04
Duplicate of #11489

**Closed by ccordoba12** 2020-02-16 18:04 UTC

**Comment by ccordoba12** [comment] 2020-02-16 18:06
This error will be fixed in our next version by not showing our error report dialog and showing instead a warning. However, if objects can't be pickled (i.e. serialized in the kernel), there's nothing we can do about it to show them, sorry.
