### ISSUE TITLE
here is it gain

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#5420] opened 2017-10-07 17:46 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Miniconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /api/sessions?token=5f6f7a86b180146db49efd9cb56546f28e3ce2622a14e0df (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006637D58208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Miniconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Miniconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 221, in get_kernel_id
    sessions_req = requests.get(sessions_url).content.d

**Comment by ccordoba12** [comment] 2017-10-07 17:48
This is a duplicate of issue #5419, so I'm closing it. Please don't open more bugs about it.

**Closed by ccordoba12** 2017-10-07 17:48 UTC
