### ISSUE TITLE
Automatic display of documentation in help pane from editor not working

### ISSUE THREAD

**Issue by andrewpauling** [spyder-ide/spyder#11133] opened 2019-12-18 19:18 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After upgrading to spyder 4.0.0 the automatic documentation in the help pane when typing a left parenthesis after a function name in the editor does not work. I have made sure that the automatic connections for both the editor and console are enabled in Preferences. The documentation appears correctly when typing a left parenthesis in the console. When typing in the editor the "Source" in the help pane does not change to "Editor". I have verified that this is still not working after updating conda and installing spyder in a new environment. Any help is much appreciated.

### What steps reproduce the problem?

1. Open Spyder
2. Type a function name followed by a left parenthesis in the editor

### What is the expected output? What do you see instead?
Documentation for the function should appear in the help pane. It does not, and the Source in the help pane does not change to "Editor".

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Mojave 10.14.6

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by jsh9** [comment] 2019-12-20 09:45
I also observed this issue. My OS is Windows 10. And my Spyder is 4.0.0.

**Comment by ccordoba12** [comment] 2019-12-20 13:59
Duplicate of #10671

**Closed by ccordoba12** 2019-12-20 13:59 UTC
