### ISSUE TITLE
Question Why I reset color of Spyder

### ISSUE THREAD

**Issue by Derrickzc** [spyder-ide/spyder#16056] opened 2021-07-21 14:48 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\plugins\configdialog.py", line 213, in accept
    configpage.apply_changes()
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\plugins\configdialog.py", line 103, in apply_changes
    self.apply_callback()
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\plugins\configdialog.py", line 268, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\plugins\configdialog.py", line 1183, in apply_settings
    self.main.ipyconsole.apply_plugin_settings(['color_scheme_name'])
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\plugins\ipythonconsole.py", line 699, in apply_plugin_settings
    client.set_color_scheme(color_scheme_o)
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 380, in set_color_scheme
    self.shellwidget.set_color_scheme(color_scheme)
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 141, in set_color_scheme
    self._syntax_style_changed()
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 464, in _syntax_style_changed
    self._highlighter._style = create_style_class(self.syntax_style)
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\spyder\utils\ipython\style.py", line 171, in create_style_class
    class StyleClass(Style):
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\pygments\style.py", line 122, in __new__
    ndef[0] = colorformat(styledef)
  File "C:\software\clean_software\Anaconda3\envs\python35\lib\site-packages\pygments\style.py", line 79, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format '#ee67772'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.7
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.3.1 (OK)
pycodestyle >=2.3:  2.7.0 (OK)
pygments >=2.0   :  2.9.0 (OK)
pandas >=0.13.1  :  1.0.0 (OK)
numpy >=1.7      :  1.19.4 (OK)
sphinx >=0.6.6   :  4.1.1 (OK)
rope >=0.9.4     :  0.19.0 (OK)
jedi >=0.9.0     :  0.18.0 (OK)
nbconvert >=4.0  :  5.6.0 (OK)
sympy >=0.7.3    :  1.7.1 (OK)
cython >=0.21    :  0.29.16 (OK)
qtconsole >=4.2.0:  5.1.1 (OK)
IPython >=4.0    :  5.8.0 (OK)
pylint >=0.25    :  2.4.4 (OK)

```

**Comment by dalthviz** [comment] 2021-07-21 17:39
Hi @Derrickzc thanks for the feedback! Checking the value you entered (`#ee67772`) is not a valid hex maybe the actual value you want to use is `#e67772`?

Also, checking a little bit seems like this a duplicate of https://github.com/spyder-ide/spyder/issues/10269 so I will close this issue as duplicate but anyway let us know if putting a valid hex for the color helps!

**Closed** 2021-07-21 17:40 UTC
Labels: resolution:Duplicate
