### ISSUE TITLE
At spyder start, Kernel is said "dead and restarting" a lot of times (on a slow pc)

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3429] opened 2016-09-17 06:15 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. start Spyder on a slow pc while compiling things
2. spyder starts , but generates a lot of Kernel death messages (6)
3. in the finally stabilized Qtconsole, we see 6 "[1]" appearing

**What is the expected output? What do you see instead?**

report of Kernel death are widely exagerated (in numbers), just because kernel is probably slow to start. could we have less ?

**Please provide any additional information below**
![spyder-20160917_6death](https://cloud.githubusercontent.com/assets/4312421/18606389/e53d845e-7cae-11e6-9132-20f7b76e1f6f.PNG)

## Versions and main components

* Spyder Version: github 2016-09-16
* Python Version: 3.5
* Operating system: windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0b4 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.0rc1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-09-17 11:38
We're doing the exact same thing now that `qtconsole` does to start its consoles, so I don't know what we could do to improve this.

What are the messages reported in the terminal where Spyder is started before the kernel starts correctly?

**Comment by stonebig** [comment] 2016-09-17 15:04
well I don't anything else than a:
``````
Kernel dead, restarting
- - - - - - - - - - - - - - - - 
````

**Comment by gb119** [comment] 2016-09-23 19:39
On the Spyder internal console I just get:
>>> WARNING:root:kernel died: 3.00217294693
WARNING:root:kernel died: 3.00221180916
WARNING:root:kernel died: 3.00215601921
WARNING:root:kernel died: 3.00216698647
WARNING:root:kernel died: 3.00222110748
WARNING:root:kernel died: 3.00220489502
WARNING:root:kernel died: 3.00220894814
WARNING:root:kernel died: 3.00217604637
WARNING:root:kernel died: 3.00213980675
WARNING:root:kernel died: 3.00217103958
WARNING:root:kernel died: 3.00221610069
WARNING:root:kernel died: 2.9991838932
WARNING:root:kernel died: 3.00158214569
WARNING:root:kernel died: 3.00020694733
WARNING:root:kernel died: 3.00005888939
WARNING:root:kernel died: 3.00198888779
WARNING:root:kernel died: 3.00210404396
WARNING:root:kernel restarted
WARNING:root:kernel died: 2.99989295006
WARNING:root:kernel died: 3.00010085106
WARNING:root:kernel died: 2.99935388565
WARNING:root:kernel died: 3.00212907791
WARNING:root:kernel died: 3.00129199028
WARNING:root:kernel died: 3.00069618225
WARNING:root:kernel died: 3.00208187103
WARNING:root:kernel died: 2.99962306023
WARNING:root:kernel died: 2.99994015694
WARNING:root:kernel died: 2.99985098839
WARNING:root:kernel died: 3.0021469593
WARNING:root:kernel died: 3.00211596489
WARNING:root:kernel died: 3.00010895729
WARNING:root:kernel died: 2.99929094315
WARNING:root:kernel died: 3.00211000443
WARNING:root:kernel died: 3.00012087822
WARNING:root:kernel died: 2.99959087372
WARNING:root:kernel restarted
WARNING:root:kernel died: 3.00218296051
WARNING:root:kernel died: 3.00211691856
WARNING:root:kernel died: 3.00214886665
WARNING:root:kernel died: 3.00216007233
WARNING:root:kernel died: 2.99999403954
WARNING:root:kernel died: 3.00214409828
WARNING:root:kernel died: 3.00142908096
WARNING:root:kernel died: 3.00192785263
WARNING:root:kernel died: 3.00206398964
WARNING:root:kernel died: 3.00210881233
WARNING:root:kernel died: 3.0021340847
WARNING:root:kernel died: 2.99966788292
WARNING:root:kernel died: 3.0021071434
WARNING:root:kernel died: 2.99970197678
WARNING:root:kernel died: 3.00212478638
WARNING:root:kernel died: 3.0022110939
WARNING:root:kernel died: 3.00212097168

When I launch from a terminal, I'm getting this traceback (eventually)

Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/site-packages/spyder/utils/ipython/start_kernel.py", line 223, in <module>
    main()
  File "/opt/anaconda/lib/python2.7/site-packages/spyder/utils/ipython/start_kernel.py", line 212, in main
    kernel.initialize()
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 412, in initialize
    self.init_sockets()
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 245, in init_sockets
    self.init_iopub(context)
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 250, in init_iopub
    self.iopub_port = self._bind_socket(self.iopub_socket, self.iopub_port)
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 174, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Address already in use
Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/site-packages/spyder/utils/ipython/start_kernel.py", line 223, in <module>
    main()
  File "/opt/anaconda/lib/python2.7/site-packages/spyder/utils/ipython/start_kernel.py", line 212, in main
    kernel.initialize()
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 412, in initialize
    self.init_sockets()
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 245, in init_sockets
    self.init_iopub(context)
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 250, in init_iopub
    self.iopub_port = self._bind_socket(self.iopub_socket, self.iopub_port)
  File "/opt/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 174, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Address already in use

(Possibly related to Issue #3444 ?)

**Comment by ccordoba12** [comment] 2016-09-29 08:13
Closing as a duplicate of #3444

**Closed by ccordoba12** 2016-09-29 08:13 UTC
Labels: Comp-Console-IPython, Type-Enhancement
