### ISSUE TITLE
Variable explor

### ISSUE THREAD

**Issue by Andyferguson** [spyder-ide/spyder#21700] opened 2024-01-12 13:32 UTC
### What steps will reproduce the problem?

Attempting to open a dataframe in the variable editor in spyder.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\fergusona\Anaconda3\envs\geoprocessing\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 201, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\Users\fergusona\Anaconda3\envs\geoprocessing\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 940, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\Users\fergusona\Anaconda3\envs\geoprocessing\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "C:\Users\fergusona\Anaconda3\envs\geoprocessing\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 244, in max_min_col_update
    for dummy, col in self.df.iteritems():
  File "C:\Users\fergusona\AppData\Roaming\Python\Python39\site-packages\pandas\core\generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GeoDataFrame' object has no attribute 'iteritems'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.8.1 (OK)
numpy >=1.7                   :  1.26.1 (OK)
pandas >=1.1.1                :  2.1.2 (OK)
scipy >=0.17.0                :  1.11.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by GitKia1392** [comment] 2024-01-15 04:06
That's a bit advanced there but I'd recommend to fix your code - Its got an error in it because you had no `self` in the if statement.
Here's a simple example of a solution:
`class Andyferguson():`
`    def __init__(self, value):`
> Your code

**Comment by jitseniesen** [comment] 2024-01-15 15:30
Hey @Andyferguson, thanks for reporting. We fixed this problem for pandas in PR #20650 which is included in Spyder version 5.4.3 and later (the current version is 5.5.0). It looks like you are using geopandas instead of pandas but I'm pretty sure that the same fix will work for you. So please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

I don't understand the comment by @GitKia1392 so I don't know whether that's relevant for you.

Please let us know if updating did help and if not, we can investigate further.

**Comment by Andyferguson** [comment] 2024-01-15 17:44
Thanks @jitseniesen for your reply. I've updated anaconda by running the commands mentioned in the links you provided. The new base environment has spyder 5.1.5 installed. When I load spyder now I get the error message detailed in the attached picture.
![Spyder Error](https://github.com/spyder-ide/spyder/assets/64734318/807bb743-bf43-4b05-b9f5-71a89cfd752e)
Could you advise? Thanks

**Comment by jitseniesen** [comment] 2024-01-15 21:19
Hi @Andyferguson , I am confused on what happened here. You say that you updated, but that the new environment has Spyder 5.1.5 installed, while you had the same at the start? That means that Spyder has not been upgraded, correct? On the other hand, your error message inside Spyder indicated that you did update Spyder to version 5.4.4 or thereabouts, so that sounds good. We have [a table](https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-version-ref) showing how Spyder versions and versions of spyder-kernels relate. To fix the error message in Spyder, you need to update spyder-kernels in the geoprocessing environment, as the message says. Underneath the [same table](https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-version-ref), there are some more instructions on how to do, so I think your first task is to do that.

Hopefully that will solve the error message in Spyder and also the message "Entry point not found" which I don't understand.

However, in case it does not, here are some other things that I noticed which do not quite look right.

Firstly, I did not notice this before, but your original error message contains Spyder files inside `C:\Users\fergusona\Anaconda3\envs\geoprocessing` (this is the conda environment called "geoprocessing") but also pandas files inside `C:\Users\fergusona\AppData\Roaming\Python`. I'm not sure where the latter come from, but I believe you can get them if you do `pip install --user`. Unfortunately, mixing conda and pip packages is tricky and this might have been the root cause of your problem.

Secondly, your original error message showed that you had Spyder installed in the `geoprocessing` environment. As I said, I think that your new error message shows that Spyder is updated, but spyder-kernels did not update. I think this means that your new version of Spyder is not in the `geoprocessing` environment, and you say indeed that it is installed "in the new base environment". So how did you install it? Did you then couple it to your existing geoprocessing environment, as explained in [our FAQ on using an existing environment](https://docs.spyder-ide.org/current/faq.html#using-existing-environment)?

If you can't get everything easily to work, it is probably best to simply install everything from start. To do that, follow these steps:
1. First un-install everything to do with Python. 
2. Then use our standalone installer to install Spyder, as explained in [our installation guide](https://geopandas.org/en/stable/getting_started/install.html). 
3. Then install conda with all the geo packages that you need. For instance, for geopandas you can follow the instructions in [their installation guide](https://geopandas.org/en/stable/getting_started/install.html). As it says there, good practice is to install it [in a new environment](https://geopandas.org/en/stable/getting_started/install.html#creating-a-new-environment). 
4. Finally, you need to tell Spyder to [use the environment](https://docs.spyder-ide.org/current/faq.html#using-existing-environment) in which you installed geopandas.

**Comment by Andyferguson** [comment] 2024-01-15 23:55
Hi @jitseniesen. Thanks again for your prompt response. I uninstalled Anaconda then installed Spyder, then Anaconda, created my environment with required packages then amended the default environment in spyder to geoprocessing. However, although spyder was working fine when I reinstalled it, once I pointed it at the geoprocessing environment the kernel console stopped working again.
![Spyder Error 2](https://github.com/spyder-ide/spyder/assets/64734318/e9f81fdd-08c9-4bed-8d21-734b30fc3e55)

I tried to rectify this by installing spyder-kernels in the geoprocessing environment but this didn't seem to work either.

![Spyder Error 3](https://github.com/spyder-ide/spyder/assets/64734318/86acdf0a-418c-4130-85e7-bab136f83c6c)

Any advice would be appreciated.

Thanks again.

**Comment by GitKia1392** [comment] 2024-01-16 02:46
> I don't understand the comment by @GitKia1392 so I don't know whether that's relevant for you.

Ok I'm sorry if that was unrelevent for you but I don't know if this was mentioned earlier but maybe try Installing Spyder from the official website and using the `pip` instead of the good ol'  `conda` package manager instead. Or a simpler way is to change the part where mentioned below

https://github.com/spyder-ide/spyder/assets/134815567/0e7d4604-07ca-4e1b-8ea9-5606fd0c8c0b

**Comment by jitseniesen** [comment] 2024-01-16 09:42
> once I pointed it at the geoprocessing environment the kernel console stopped working again.

Hi @Andyferguson, sorry about this, you must feel like you are being led round in circles, but I think we are actually making progress as I think I understand this problem.

I forgot that Anaconda is running slightly behind. The current versions in Anaconda is Spyder 5.4.3 and spyder-kernels 2.4.4. What happened is that you installed Spyder 5.5.0, which is the latest version, and then you installed Anaconda with spyder-kernels 2.4.4 in the geocomputing environment. However, these are not compatible so the kernel stopped working. As you said, the solution would be to upgrade spyder-kernels in the geocomputing environment to 2.5, but this version is not available in Anaconda.

I can see two possible solutions:
1. Use Spyder 5.4.3 instead of Spyder 5.5.0, because that is compatible with Anaconda. To do this, uninstall Spyder and then go to our [https://github.com/spyder-ide/spyder/releases](Releases page). Scroll down to Spyder 5.4.3 and download the file called `Spyder_64bit_full.exe` (that's our stand-alone installer for Windows). I think that Spyder 5.4.4 and 5.4.5 will also work, but you should remember not to upgrade to Spyder 5.5.0 (even though Spyder may prompt you to) because that is not compatible with Anaconda.
2. Use conda-forge instead of Anaconda, as also mentioned in the geopandas installation guide. The cleanest way to achieve this is to uninstall Anaconda and then install [https://github.com/conda-forge/miniforge](Miniforge). That is a minimal conda installation that uses conda-forge instead of Anaconda. Then create a geocomputing environment, as before, and install spyder-kernels and whatever other packages you need (e.g., geopandas) in that environment.

**Comment by Andyferguson** [comment] 2024-01-16 14:50
Hi @jitseniesen. No problem at all. So I installed the previous version of spyder and also installed the latest version of anaconda. (I was previously using an older version ~2022 as the newer versions failed to install). The install of the latest version of anaconda was very troublesome with environmental variables missing, command prompt no longer working etc, however that's nothing to do with spyder. I then installed spyder kernels as prompted by the new installation of spyder and it is now working fine. We got there in the end. :) Thanks for your help. Greatly appreciated.

Cheers
Andy

**Comment by jitseniesen** [comment] 2024-01-16 20:44
Okay, I am very happy that at least you got your Spyder working again.

I tried to open a geodataframe in Spyder and I get the same error message as you. I think this is a limitation of Spyder at the moment and one that requires quite some work on our part to fix. I added a note to issue #20959 which looks like a good place to brainstorm solutions but at the moment I am afraid that it is just not possible to open a geodataframe in the variable explorer.

**Comment by jitseniesen** [comment] 2024-01-18 09:03
I am going to close this issue now because your Spyder works. If it is not actually fixed, feel free to comment here. The other issue I linked to is where we will (at some point) discuss how to solve the real problem, how to open a geodataframe.

**Closed by jitseniesen** 2024-01-18 09:03 UTC
Labels: status:Awaiting Followup

**Comment by Andyferguson** [comment] 2024-01-18 09:06
Hi @jitseniesen. No problem. Thanks again for your help. Much appreciated.
