### ISSUE TITLE
Variable Explorer generates an error while editing a DataFrame

### ISSUE THREAD

**Issue by zeehio** [spyder-ide/spyder#3084] opened 2016-03-24 16:01 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder 3.0.0b2 (from https://anaconda.org/spyder-ide/spyder ) using PyQt5
2. On the ipython terminal type

    ```python
    import pandas as pd
    df2 = pd.DataFrame([dict(a=1,b="test", c=False), dict(a=2, b="test2", c=False)])
    ```
3. Click on `Variable Explorer`, double click on `df2` to open the DataFrame editor
4. Right click on a number (last row, column "a" has a number=2 in the example), choose `To int`

**What is the expected output? What do you see instead?**
I expect nothing to happen (it's an int already).
Instead, Spyder closes and I see *Unhandled Python exception. Aborted*

**Please provide any additional information below**
This seems to happen with other conversions.

## Versions and main components

* Spyder Version: 3.0.0b2
* Python Version: 
```
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```
* Operating system: Linux Mint

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=3.0      :  4.0.2 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
numpy >=1.7        :  1.10.4 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.3.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=13.0.0       :  15.2.0 (OK)

I haven't checked other QT APIs (PyQt4/PySide).

**Comment by ccordoba12** [comment] 2016-03-24 16:27
What PyQt5 packages are you using?

**Comment by zeehio** [comment] 2016-03-24 16:36
According to conda list, I am using yours (spyder-ide)
```
 conda list | grep spyder-ide
glib                      2.43.0                        2    spyder-ide
gst-plugins-base          1.4.5                         0    spyder-ide
gstreamer                 1.4.5                         0    spyder-ide
icu                       56.1                          0    spyder-ide
libxcb                    1.11.1                        0    spyder-ide
pyqt5                     5.5.0                    py35_0    spyder-ide
qt5                       5.5.0                         0    spyder-ide
qtawesome                 0.2.0                      py_0    spyder-ide
qtpy                      0.1.3                      py_0    spyder-ide
spyder                    3.0.0b2                  py35_0    spyder-ide
```

**Comment by zeehio** [comment] 2016-03-24 16:42
Using pyqt (having removed pyqt5 and qt5 packages) I get a message on the console instead:

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "/home/soller/anaconda3/envs/smartims_dev/lib/python3.5/site-packages/spyderlib/widgets/variableexplorer/dataframeeditor.py", line 433, in <lambda>
    self.change_type(func),
  File "/home/soller/anaconda3/envs/smartims_dev/lib/python3.5/site-packages/spyderlib/widgets/variableexplorer/dataframeeditor.py", line 443, in change_type
    [model.setData(i, '', change_type=func) for i in index_list]
  File "/home/soller/anaconda3/envs/smartims_dev/lib/python3.5/site-packages/spyderlib/widgets/variableexplorer/dataframeeditor.py", line 443, in <listcomp>
    [model.setData(i, '', change_type=func) for i in index_list]
  File "/home/soller/anaconda3/envs/smartims_dev/lib/python3.5/site-packages/spyderlib/widgets/variableexplorer/dataframeeditor.py", line 300, in setData
    self.df.iloc[row, column - 1] = change_type(val)
TypeError: 'bool' object is not callable

```

**Comment by ccordoba12** [comment] 2016-03-24 17:10
I can reproduce your error in beta2 but this seems fixed in beta3 (I tested it several times :-).

So these are great news (because I don't remember when I fixed it!).

**Closed by ccordoba12** 2016-03-24 17:10 UTC
Labels: Bug, Variable-Explorer
