### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by BakalaBoi** [spyder-ide/spyder#6693] opened 2018-03-09 07:28 UTC
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
### What steps will reproduce the problem?

was experiencing problems with spyder start up "python has stopped working" right after splash screen.

did conda update qt and qtpy and spyder. did not solve problem.

ran the clear spyder settings, and ran spyder, it runs. 

Went over to preferences to change editor settings to manokai theme. this error.

**Comment by CAM-Gerlach** [comment] 2018-03-09 07:51
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed by CAM-Gerlach** 2018-03-09 07:51 UTC
