### ISSUE TITLE
Spyder 4.1.2 PermissionError: [WinError 5] Access denied - using setup.py build install

### ISSUE THREAD

**Issue by pthedens** [spyder-ide/spyder#12649] opened 2020-05-07 16:23 UTC
Hi there,

I am using Spyder 4.1.2 on Windows 10 to run and compile a cython library. When I try to run 

`runfile('path/to/setup.py', args='build install', wdir='path/to')`

the code compiles as intended, but when the code is being copied into Anaconda3/Lib/site-packages/my-lib I get the error:

`PermissionError: [WinError 5] Access denied`

I already gave read/write permission to my current user, and ran Spyder 4.1.2 as administrator. Still, I get the same error.

When I close Spyder after the error is thrown and re-open it to run the setup.py again, I don't get the error. Then again, when I recompile I have to restart Spyder.

**Comment by ccordoba12** [comment] 2020-05-07 17:07
Please provide us with a minimal reproducible example of a Cython code that is generating this error so we can debug this problem in our side.

**Comment by pthedens** [comment] 2020-05-07 17:12
Sure, here you go

`import os
import numpy
from glob import glob
from distutils.core import setup
from distutils.extension import Extension

useCython = True

APPNAME = "mem4py"
APPVERSION = "0.3"

cmdclass = dict()
if useCython:
    try:
        from Cython.Distutils import build_ext
        cmdclass.update({'build_ext': build_ext})
    except ImportError:
        print("WARNIG: No Cython installed, compiling from .cpp files")
        useCython = False

ext = '.pyx' if useCython else '.cpp'


files = glob('mem4py/*{}'.format(ext))
files.extend(glob('mem4py/*/*{}'.format(ext)))

def makeExtensionLinux(file, includeDird):
    extName = os.path.splitext(file)[0]
    extName = extName.replace(os.path.sep, '.')
    return Extension(extName, [file], include_dirs = includeDirs, language='c++')

def makeExtensionWindows(file, includeDirs):
    extName = file.replace('\\', '.')[:-4]
    return Extension(extName, [file], include_dirs=includeDirs, language='c++')

includeDirs = list(set([os.path.dirname(path) for path in files]))
if os.name == 'nt':
    includeDirs.append('C:\\Program Files\\eigen3')
    includeDirs.append(numpy.get_include())
    extensions = [makeExtensionWindows(path, includeDirs) for path in files]
elif os.name == 'posix':
    includeDirs.append('/usr/include/eigen3')
    includeDirs.append(numpy.get_include())
    extensions = [makeExtensionLinux(path, includeDirs) for path in files]

setup(
  name=APPNAME,
  version=APPVERSION,
  description="Python interface for membrane FEM solver.",
  ext_modules=extensions,
  cmdclass=cmdclass,
  packages=['mem4py', 'mem4py/assembler', 'mem4py/materialModels', 'mem4py/ceygen',
            'mem4py/solver', 'mem4py/helper', 'mem4py/elements']
)`

**Comment by ldoyle** [comment] 2020-07-14 20:23
I seem to remember a similar error message when uninstalling a package which contained `.dll`s while a console was still open that had imported the package. I.e. the file was still open by the python/IPython console in the eyes of Windows, thus denying the deletion when I uninstall the pacakge.
Maybe in your case the overwriting of the compiled `.dll`/`.pyd` while it is still loaded raises the same error?
* Try manually deleting the compiled module from /Lib/site-packages before re-running your setup script. This should fail with a similar error (although arguably "File is open" and "Access denied" are not the same thing and Python could improve the error message here)
* A quick search for "unloading DLL in Python" yielded mixed results, the safest bet is to restart the kernel in question.
* On a sidenote, did you know you can install packages in *develop* mode with pip/setuptools? It might not solve this particular problem, but saves you from re-running the setup script after each build

**Comment by ccordoba12** [comment] 2023-02-26 15:17
Closing because this is too old now.

**Closed by ccordoba12** 2023-02-26 15:17 UTC
Labels: status:Awaiting Followup
