### ISSUE TITLE
plt.plot does not work

### ISSUE THREAD

**Issue by Carl-H-GitHub** [spyder-ide/spyder#16759] opened 2021-11-06 21:58 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Using plt.plot (and executing) opens a window which crashes immediately

**Comment by ccordoba12** [comment] 2021-11-07 01:46
Hey @Carl-H-GitHub, thanks for reporting. This is a duplicate of issue #16659.

Please see the last comment there for the solution.

**Closed by ccordoba12** 2021-11-07 01:46 UTC
