### ISSUE TITLE
Application spyder launch may have produced errors.

### ISSUE THREAD

**Issue by vardhan-siramdasu** [spyder-ide/spyder#15440] opened 2021-04-27 03:38 UTC
### What steps will reproduce the problem?

Traceback (most recent call last):
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 1277, in setup
self.apply_shortcuts()
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3189, in apply_shortcuts
plugin_name))
File "D:\anaconda\lib\site-packages\spyder\config\manager.py", line 305, in get_shortcut
return config.get('shortcuts', context + '/' + name.lower())
File "D:\anaconda\lib\site-packages\spyder\config\user.py", line 976, in get
return config.get(section=section, option=option, default=default)
File "D:\anaconda\lib\site-packages\spyder\config\user.py", line 513, in get
raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'find_replace/find next' in section: 'shortcuts'

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  4.0.0 (OK)
cloudpickle >=0.5.0          :  1.6.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.22.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  6.0.7 (OK)
numpydoc >=0.6.0             :  1.1.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.8.0 (OK)
pygments >=2.0               :  2.8.1 (OK)
pylint >=0.25                :  2.5.3 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.9 (OK)
zmq >=17                     :  20.0.0 (OK)
qdarkstyle >=2.7             :  3.0.2 (OK)
qtawesome >=0.5.7            :  1.0.2 (OK)
qtconsole >=4.6.0            :  5.0.3 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.7 (OK)
sphinx >=0.6.6               :  3.5.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  1.20.1 (OK)
pandas >=0.13.1              :  1.1.3 (OK)
scipy >=0.17.0               :  1.6.2 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-04-27 05:10
Closing as a duplicate of issue #15438. Please don't open more issues about the same problem.

**Closed by ccordoba12** 2021-04-27 05:10 UTC
