### ISSUE TITLE
Code analysis entries collapsing after clicking one of them

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#13484] opened 2020-08-06 03:20 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After clicking one of the entries in the code analysis all the entries collapse after showing the line where the "warning" happened. 

![bug](https://user-images.githubusercontent.com/18587879/89486779-6dafd800-d769-11ea-8cd7-70740f9bc4b5.gif)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder 4.2.0.dev0
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment] 2020-08-06 03:20
I thought we talked about fixing this but it still remains a bug, not sure if it was addressed before. @ccordoba12

**Comment by ccordoba12** [comment] 2020-10-29 01:10
Thanks @juanis2112 for reporting. This has not been fixed yet.

I also this one is a duplicate of issue #13347, so I'm closing it in favor of that one.

**Comment by ccordoba12** [comment] 2020-10-29 01:11
I forgot to mention that I plan to solve this for 4.2.0

**Closed by ccordoba12** 2020-10-29 01:10 UTC
Labels: type:Bug
