### ISSUE TITLE
Spyder 4 Hangs/Freezes randomly when editing code

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11126] opened 2019-12-18 08:02 UTC
Usually occurs when backspacing in code editing, with Keras (TensorFlow) model training running in background; simple non-responsiveness, screen greys out upon clicking (screenshot at bottom), with mousewheel spinning infinitely. 

Interestingly, training continues seemingly unscathed, and model checkpoints itself as programmed (w/ files generated where expected) - nonetheless, it's problematic.

### Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

<hr>

**Screenshot**:

![image](https://user-images.githubusercontent.com/16495490/71067597-41b9f500-218e-11ea-859f-4b44157ec892.png)

**Comment by sbitzer** [comment] 2019-12-18 11:01
I see the same behaviour, but cannot pin it down to a particular reason. Right now I just edited the docstring of a function as seen below (I was about to add "rotated around <another>" in the screenshot below), when spyder froze. Happened a couple of times before and I don't see how to recover from this except for restarting spyder.

![grafik](https://user-images.githubusercontent.com/320128/71080616-cbb58e00-218d-11ea-9340-98ae7a78d2b1.png)

**Comment by ccordoba12** [comment] 2019-12-18 14:32
This could be caused by issue #10918, which is going to be fixed in our next version. So please wait until that release is out (hopefully next week) and report back.

**Comment by ccordoba12** [comment] 2020-01-09 14:30
I think this could also be caused by the problem reported on #11222, which was already fixed and it'll be part of our next release.

**Closed by ccordoba12** 2020-01-09 14:30 UTC
Labels: status:Awaiting Followup

**Comment by OverLordGoldDragon** [comment] 2020-01-09 23:27
@ccordoba12 To notify, reproduced in 4.0.1.

**Comment by ccordoba12** [comment] 2020-01-10 00:30
Yeah, this will be fixed in our next version.

**Comment by derekeden** [comment] 2020-01-27 19:18
any idea when the new release is coming? using 4.0.1 and this literally happens like every 20-30 minutes, makes it almost unusable

**Comment by ccordoba12** [comment] 2020-01-27 20:24
We'll try to release it i a two or three weeks.

**Comment by derekeden** [comment] 2020-01-27 20:35
thanks!

**Comment by OverLordGoldDragon** [comment] 2020-01-27 20:35
@derekeden My current workaround is to run code in one Spyder instance, and do editing in `spyder --new-instance` - this way running code is never interrupted, and unsaved code can be usually recovered.

**Comment by derekeden** [comment] 2020-01-27 20:38
@OverLordGoldDragon annoying :( but thanks for the suggestion! Will consider that.

**Comment by farznaj** [comment] 2020-01-27 22:12
Dealing with the same problem ... python 3.7; spyder 4.0.1 ; OS: linux ... soooooooo annoying ... what's the latest version of spyder that doesn't have this problem? perhaps we can go back to it? can you help with this? thanks.

**Comment by ccordoba12** [comment] 2020-01-27 23:12
@farznaj, Spyder 3.3.6 shouldn't have this problem.

Could you let us know under what circumstances this happens for you? According to our findings, this should only happen when you're editing big files (>1k lines of code) or making too many code completion requests in a very short amount of time (i.e. pressing the Tab key a lot of times).

**Comment by derekeden** [comment] 2020-01-27 23:19
@ccordoba12 this happens to me several times an hour. Scripts ranging from 10 to 500 lines of code at most. I don't actually use tab completion very often at all. Seems to happen randomly but definitely can say it's happened a few times when I was backscaping or using the down arrow to go down lines

**Comment by farznaj** [comment] 2020-01-27 23:45
> @ccordoba12 this happens to me several times an hour. Scripts ranging from 10 to 500 lines of code at most. I don't actually use tab completion very often at all. Seems to happen randomly but definitely can say it's happened a few times when I was backscaping or using the down arrow to go down lines

It is not a big file. But I am using tensor flow and keras in the script that I am running. It is unbearably annoying ... happens quite often, and freezes for several loooonnnngggg seconds....

**Comment by farznaj** [comment] 2020-01-28 00:12
Another quite annoying issue with spyder 4.0.1 is that it automatically opens a window with suggested words for completion, and the window keeps staying there on the editor! even though I don't want to use it!!!!! The biggest problem is that when, as a quite natural move, I try to move the cursor down, it moves down the "suggested words" window, instead of the editor ... this is very frustrating!!

**Comment by goanpeca** [comment] 2020-01-28 00:20
Have you tried disabling automatic completions on the `Completion and linting` `Preferences`?

**Comment by ccordoba12** [comment] 2020-01-28 16:05
@farznaj:

> But I am using tensor flow and keras in the script that I am running. It is unbearably annoying ... happens quite often, and freezes for several loooonnnngggg seconds....

Could you share your script with us? It'd really help us to debug this problem because none of us do machine learning so we don't use those kind of libraries.

If it contains private or sensitive information, you could send it to us via email.

> Another quite annoying issue with spyder 4.0.1 is that it automatically opens a window with suggested words for completion

That's called completion on the fly, and it was asked by several other users in past. However, if you dislike, you can deactivate it by going to

    Preferences > Completion and linting > Completion

and deactivating the option called `Show completions on the fly`.

**Comment by PierreCeteaud** [comment] 2020-01-29 21:35
> 
> 
> @farznaj, Spyder 3.3.6 shouldn't have this problem.
> 
> Could you let us know under what circumstances this happens for you? According to our findings, this should only happen when you're editing big files (>1k lines of code) or making too many code completion requests in a very short amount of time (i.e. pressing the Tab key a lot of times).

I have the same problem, on two different computers (Windows 7 and Windows 10)
The files are less than 1k long, but it happens often when going up or down with arrow auto-repetition.

I have also a small bug on both computers: sometimes a strange character is added to what I type  (a heart for example) not really annoying, but perhaps the reception of a non-legal character causes the freeze?

On both computers, spyder is installed with conda, and with version 4.0.1, spyder-kernels version is 1.8.1

**Comment by mariosgeo** [comment] 2020-02-04 15:22
I am report the same bug. Code is about 1k lines and now it freezes every 20min or so.

**Comment by AleksanderB** [comment] 2020-02-07 10:46
I am reporting the same bug. Code is spread in 6 different tabs, each tab around 350 lines.  It usually freezes when scrolling back quickly with arrows  in command history.

**Comment by derekeden** [comment] 2020-02-10 01:46
now freezes and must be killed every time I try to comment/uncomment a block a code..it's become unusable.. I sadly am going to have to switch to another IDE though I really do like spyder

**Comment by princyok** [comment] 2020-02-12 22:29
I am experiencing the same bug. The most recent was just 20 minutes ago. It crashes while just editing code. Nothing is running. And it happens often, every half hour to an hour. Spyder is up to date (4.0.1).

**Comment by riberyrobben** [comment] 2020-02-27 16:40
It seems the case is closed, but I am experiencing the same bug while editing a script less than 100 lines. It freezes several times so far. Below is the screenshot when it's freezing. It happened when I tried to type a space  I have imported pd, os and datetime, and have a big dataframe (186k * 45) in memory. 

Running on Spyder 4.0.1, with python 3.7.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 


![image](https://user-images.githubusercontent.com/13710056/75464097-b363ab80-5954-11ea-99d7-f44d252f7f9b.png)

**Comment by HeraldoAlmeida** [comment] 2020-02-29 22:23
It happens to me every 15-20 minutes, even when editing and testing a very simple python script with a few hundred lines of code that just reads a 17 MB Excel file into a Pandas dataframe and performs simple calculations using small numpy arrays (plenty of free RAM memory available during the whole processing). 
It seems to happen at the moments when I type too fast the tab and/or arrow keys.

**Comment by ccordoba12** [comment] 2020-02-29 23:23
This problem is a duplicate of #11222 and it'll be fixed in our next version, to be released in a couple of weeks.

If it reappears after that, please open a new issue.
