### ISSUE TITLE
importanttttt HELPPPPPPPP

### ISSUE THREAD

**Issue by busra125** [spyder-ide/spyder#5913] opened 2017-12-07 15:44 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\bsr\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1023, in create_client_for_kernel
    password)
  File "C:\Users\bsr\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1666, in _create_client_for_kernel
    kernel_client.load_connection_file()
  File "C:\Users\bsr\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 451, in load_connection_file
    with open(connection_file) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\bsr\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Python 3.6'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAMGerlach-Baron** [comment] 2017-12-07 19:28
Thanks for reporting. As some general, person to person advice, issue titles like the one above are likely to have an inverse effect on the quality and quantity of responses, as opposed to one that is clear, to the point, and specific regarding your problem.

In any case, hopefully someone else can offer more specific advice, but it appears that for whatever reason, jupyter is trying to load a shortcut from your start menu and failing to do so. Not sure if that's the path it is supposed to try it from and something's wrong with the shortcut, or it should be trying to load the actual executable, or that's the system python, or what, but does this error occur if you launch an iPython console e.g. from a standalone qtconsole or from the Anaconda Prompt? 

If so, then it wouldn't have anything to do with Spyder, and aside from doing a clean uninstall/reinstall of Anaconda (probably a good idea in any case), your best bet if it really is a bug is to report it to `jupyter`.

**Comment by ccordoba12** [comment] 2017-12-07 20:00
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAMGerlach-Baron** [comment] 2017-12-07 20:07
@ccordoba12 Loading the IDE, it would seem. Still, between the chances of it being a user-side issue (quite probable) and the fact that it occurs in the `jupyter` code, doesn't seem likely to be a (fixable) bug on Spyder's end, to take a naive guess.

**Comment by CAM-Gerlach** [comment] 2017-12-16 20:40
Closed due to lack of response.

**Closed by CAM-Gerlach** 2017-12-16 20:40 UTC
