### ISSUE TITLE
Spyder 4 Error...TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

### ISSUE THREAD

**Issue by akashuh** [spyder-ide/spyder#14729] opened 2021-02-10 06:56 UTC
Any code produces this problem. Literally print('Hello World') also throws the error. Only which running the script though. The console seems to be working fine

**Comment by impact27** [comment] 2021-02-10 09:44
Duplicate of https://github.com/spyder-ide/spyder/issues/13851

**Closed by impact27** 2021-02-10 09:44 UTC
