### ISSUE TITLE
Sorting file list

### ISSUE THREAD

**Issue by alexandrugrusu** [spyder-ide/spyder#6465] opened 2018-02-16 11:45 UTC
## Description

**What steps will reproduce the problem?**

1. Sorting file list
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/alexandru/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1083, in copy
    obj = self.delegate.get_value(idx)
  File "/home/alexandru/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1380, in get_value
    name = index.model().keys[index.row()]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-16 14:50
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2018-02-24 05:38
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-02-24 05:38 UTC
Labels: status:Awaiting Followup
