### ISSUE TITLE
Spyder 5.4.1 crashes directly on start with ValueError

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#20302] opened 2023-01-03 20:32 UTC
Spyder 5.4.1 crashes for me before even opening any panel.
When attempting to start from the command line, I get the following message
```
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 773, in setup
    PLUGIN_REGISTRY.register_plugin(self, PluginClass,
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/api/plugin_registration/registry.py", line 342, in register_plugin
    instance = self._instantiate_spyder5_plugin(
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/api/plugin_registration/registry.py", line 184, in _instantiate_spyder5_plugin
    plugin_instance = PluginClass(main_window, configuration=CONF)
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/api/plugins/new_api.py", line 331, in __init__
    container.setup()
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/plugins/pythonpath/container.py", line 55, in setup
    self._load_pythonpath()
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/plugins/pythonpath/container.py", line 136, in _load_pythonpath
    system_path = get_system_pythonpath()
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/plugins/pythonpath/utils.py", line 31, in get_system_pythonpath
    env = get_user_env()
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/utils/environ.py", line 71, in get_user_env
    env_dict = get_user_environment_variables()
  File "/home/userX/.anaconda3/envs/py/lib/python3.9/site-packages/spyder/utils/environ.py", line 63, in get_user_environment_variables
    k, v = kv.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
The operating system on which this happens is linux (opensuse, leap 15.4), with a fresh python3.9 environment set up from the current version of Anaconda/Conda
I've tried ``spyder --reset`` with no effect.

Since I cannot get into the main Spyder window, this is what I can at least list from conda
```
spyder                    5.4.1            py39hf3d152e_1    conda-forge
spyder-kernels            2.4.1           unix_pyhd8ed1ab_0    conda-forge

python                    3.9.15          hba424b6_0_cpython    conda-forge

pyqt                      5.15.7           py39h18e9c17_2    conda-forge
pyqt5-sip                 12.11.0          py39h5a03fae_2    conda-forge
pyqtwebengine             5.15.7           py39h18e9c17_2    conda-forge
qt-main                   5.15.6               hf6cd601_5    conda-forge
qt-webengine              5.15.4               h325cec9_3    conda-forge
qtawesome                 1.2.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.0              pyha770c72_0    conda-forge
qtpy                      2.3.0              pyhd8ed1ab_0    conda-forge
```

**Comment by xaverm** [comment] 2023-01-04 09:19
Since posting yesterday, I can add more info:

The issue is a "5.4.1 issue" and is not bound to a particular linux version.

This claim is based on the following: I have created dedicated "spyder environments" on several linux machines running various versions of opensuse leap 15.x (x=1...4) with various versions of Anaconda/Conda distros installed. These "spyder environments" were created solely with `conda create --name spY python=3.9`, with Y=40 and 41, and after their creation only doing `conda install spyder=5.4.Z` with Z=0 and 1.

The outcome was that on all machines, activating the `sp40` environment and calling spyder did start a valid spyder interface and on all machines, activating the `sp41` environment and calling spyder led to the error shown in my original post.

Your help would be most appreciated. ThX.

**Comment by ccordoba12** [comment] 2023-01-04 15:03
Hey @xaverm, thanks for reporting. This is a duplicate of issue #20097 and we'll fix it our next version (5.4.2) to be released next week due to the severity of this bug.

In the meantime, please use 5.4.0.

**Closed by ccordoba12** 2023-01-04 15:03 UTC

**Comment by ccordoba12** [comment] 2023-01-04 16:04
No problem, with more than 20k issues it's hard to pinpoint the right one.

**Comment by xaverm** [comment] 2023-01-31 21:10
Got back on track from 5.4.0 directly to 5.4.2 a couple of days ago and up to now, all seems good again. Thx.
