### ISSUE TITLE
Use the breakpoint() command for breakpoints in the gutter

### ISSUE THREAD

**Issue by ba-tno** [spyder-ide/spyder#17189] opened 2022-01-13 18:34 UTC
This is more of a feature request then an issue., that's why I truncated the checklist.

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
  * Slightly related to #13615

## Problem Description
I run [CherryPy](https://docs.cherrypy.dev/en/latest/) code that serves an endpoint which receives some JSON data, transforms it and then stores it. I would like to debug this code while the server is listening. Putting regular breakpoint in the code and debugging it does not break.  
However, when I write `breakpoint()` above the line where I want stop, Spyder *does* stop and I can use the debugger as desired.

Is it possible to make the gutter breakpoint functionality equivelent to writing `breakpoint()` above the line of interest?  
I can imagine that the Spyder settings would allow to choose between "default Spyder" debugging and `breakpoint()` debugging.

### What steps reproduce the problem?

1. Create [a basic CherryPy script](https://docs.cherrypy.dev/en/latest/tutorials.html#tutorial-1-a-basic-web-application) in Spyder
2. Place a breakpoint on the return statement
3. Start the debugger

### What is the expected output? What do you see instead?
I expect that when I visit the served page, Spyder breaks and brings me to the debugger. Instead, the page is served and Spyder does not stop and does not show the debugger in the console.

## Versions

* Spyder version: 5.2.1 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

<details>
<summary>Click to fold out dependencies</summary>

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)

```

</details>

**Comment by ccordoba12** [comment] 2022-01-13 21:22
Hey @ba-tno, thanks for the suggestion. I think that for this to work we'd need to preprocess your code to inject the `brekpoint` calls on it before evaluating it, which doesn't seem too easy for me.

@impact27, what do you about this?

**Comment by impact27** [comment] 2022-01-13 21:53
It should already be the case. Writing `breakpoint()` in your code should be equivalent to putting a breakpoint in the editor. 
Except for threads of course, in that case you need a `breakpoint()` because the editor breakpoints only work for the main thread.

**Comment by ba-tno** [comment] 2022-01-13 22:46
@impact27 thanks for the explanation. I tried setting the [`thread_pool`](https://docs.cherrypy.dev/en/latest/pkg/cherrypy._cpserver.html?highlight=thread#cherrypy._cpserver.Server.thread_pool) value in my CherryPy config to 1 (in the hope that this would result in a single thread), but the gutter breakpoint still did not work.

**Comment by impact27** [comment] 2022-01-13 23:36
I guess that even with 1 it is still running as a thread. I will close this as this is a duplicate of https://github.com/spyder-ide/spyder/issues/8801. https://github.com/spyder-ide/spyder-kernels/pull/164 should solve this problem but I am afraid it might introduce too many side effects.

**Closed by impact27** 2022-01-13 23:36 UTC
Labels: type:Enhancement, component:Debugger
