### ISSUE TITLE
Loosing focus on editor when help is shown

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder#3497] opened 2016-10-03 17:44 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Enter `import numpy as np` then type `x = np.linspace(`

**What is the expected output? What do you see instead?**
Expect: that the help panel shows document for that methods and focus is still inside the editor.
Reality: Editor lost focus immediately. The focus is now on help panel. Must click on editor to be able to code again.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3
* Python Version: 2.7.12
* Operating system: Mac 10.11

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  0.6.1 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  0.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-03 23:23
Thanks for reporting. This is a duplicate of issue #3317

**Closed by ccordoba12** 2016-10-03 23:23 UTC
