### ISSUE TITLE
Redundant error messages when running multiple editor panels

### ISSUE THREAD

**Issue by avylove** [spyder-ide/spyder#5249] opened 2017-09-16 02:46 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open a file with code warnings in the editor with more than one panel
2. Hover over the code warning

**What is the expected output? What do you see instead?**

Instead of seeing one error message, I'm seeing multiple messages. 

![screenshot from 2017-09-15 21-11-22](https://user-images.githubusercontent.com/16090444/30508443-f3b733dc-9a5c-11e7-8925-c81ffbac991c.png)

**Please provide any additional information below**

The number of error messages is related to the number of panels that are open plus the number of panels with the file being shown. In the example, the same file is shown on two panels at the time it was edited.

This is NOT new with 3.2.3

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.2
* Qt Version: 5.7.1
* PyQt Version: 5.8.1
* Operating system: Fedora 26

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment] 2017-09-16 03:19
Thanks for reporting. It's very annoying indeed.

We'll take a look at it in a future release.

**Comment by rlaverde** [comment] 2017-09-16 14:19
`EditorStack.data` has a `FileInfo` for each editor open, but different finfos with the same file open share the same editor(CodeEditor); then each finfo call the codeanalisis, and set the results to the editor, that results in many finfos assigning results to the same CodeEditor

I think the solution for this issue could be to move code_analisis calling and workers creation to `CodeEditor`

**Comment by goanpeca** [comment] 2019-12-04 03:50
I cannot reproduce this issue. Closing.

**Closed by goanpeca** 2019-12-04 03:50 UTC
Labels: component:Editor, type:Bug
