### ISSUE TITLE
Undefined error: 0 when runing spyder 

### ISSUE THREAD

**Issue by sriaz2** [spyder-ide/spyder#3988] opened 2017-01-18 09:27 UTC
Undefined error: 0 when runing spyder 
Platform: MacOS 10.12.2

**What steps will reproduce the problem?**

1. Install Anaconda 4.3 
2. Run spyder from terminal
 

## Versions and main components

* Spyder Version: 3.0.2
* Python Version:2.7.13.final.0
* Operating system:MacOS 10.12.2
* Conda version : 4.3.4

```bash
Sarmads-MacBook-Pro:~ sarmadriaz$ spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

**Comment by mrclary** [comment] 2017-01-29 02:10
This is a duplicate of #3730. There is no solution yet, to my knowledge. However there does seem to be a workaround:
`export EVENT_NOKQUEUE=1`

**Comment by mrclary** [comment] 2017-01-29 02:10
This is a duplicate of #3730. There is no solution yet, to my knowledge. However there does seem to be a workaround:
`export EVENT_NOKQUEUE=1`

**Comment by ccordoba12** [comment] 2017-01-29 07:38
Truth is the solution is not in Spyder hands.

**Closed by ccordoba12** 2017-01-29 07:38 UTC

**Comment by CoderCoderCoder** [comment] 2017-07-19 01:30
I fixed the issue with "brew reinstall libevent"
