### ISSUE TITLE
Spyder has encountered an internal problem: __new__() missing 1 required positional argument: 'hidden'

### ISSUE THREAD

**Issue by tracychenxy** [spyder-ide/spyder#20981] opened 2023-06-01 02:16 UTC
I tried to launch Spyder (python 3.7) from Anaconda navigator. However Spyder has this error pop out, and I can't proceed using it. Can someone help?
![Screenshot 2023-05-31 221629](https://github.com/spyder-ide/spyder/assets/60545084/eeb8acbd-31ff-4f1a-8e19-ac498df7f124)

**Comment by dalthviz** [comment] 2023-06-01 07:52
Hi @tracychenxy this seems like a duplicate of https://github.com/spyder-ide/spyder/issues/17452 In the linked issue some instructions regarding the qtconsole version installed, could help you to prevent the problem. Otherwise, I would suggest you to update Spyder to the latest release available (5.4.3) which also should help you prevent the issue.

Let us know if the info above helps!

**Comment by tracychenxy** [comment] 2023-06-02 04:11
I update Spyder to version 5 and start Spyder from Anaconda prompt and no error further pops out. Thank you for the quick help!!

**Comment by dalthviz** [comment] 2023-06-02 10:19
Awesome! Thank you for letting us know that updating worked for you @tracychenxy ! I'm closing this as a duplicate of #17452 then but good to know that the error is not present if you update to the latest Spyder version :+1:

**Closed by dalthviz** 2023-06-02 10:19 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
