### ISSUE TITLE
Feature Request: more syntax highlighting customization.

### ISSUE THREAD

**Issue by RodrigoTR04** [spyder-ide/spyder#21567] opened 2023-11-30 04:51 UTC
Feature request to add more customization to syntax highlighting.

As of version 5.5.0 of Spyder only a few types of text can be color customized, and at times two different types are attached to each other and can't be independently altered. (See images as examples).

Using the `Pastel` theme:
![image](https://github.com/spyder-ide/spyder/assets/65554156/1c5ee357-925c-456a-b904-6da7fa665598)

All variable `i`, parenthesis and operator `!=` are using the "normal text" color #f8f8f8.
![image](https://github.com/spyder-ide/spyder/assets/65554156/a6886844-b1b6-4d92-baab-2e35e382e871)
(Although very similar the values of strings and numbers are independent from one another, as per the first image).

Desirable behavior is to be able to customize them independently of one another, similar to what Notepad++ does. (See following images)
![image](https://github.com/spyder-ide/spyder/assets/65554156/9c3f36f7-99fa-448e-a53e-86db04425c9a)

Example of how it should show in the editor:
![image](https://github.com/spyder-ide/spyder/assets/65554156/efc86566-16c4-4fb7-b81d-3d604056022c)

* Spyder version: 5.5.0
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt version: 5.15.10
* Operating System name/version: Windows 10 (AMD64)

**Comment by dalthviz** [comment] 2023-12-05 00:13
Hi @RodrigoTR04 thank you for the feedback! Makes sense to me but what do you think @spyder-ide/core-developers ?

**Comment by ccordoba12** [comment] 2023-12-05 01:07
I think we'll have that once we add support for [PySyntect](https://github.com/spyder-ide/pysyntect) to the editor.

I'd also be in favor of closing this one as a duplicate of issue #1500 because we'll need to expand our syntax highlighting capabilities to solve that issue.

**Comment by dalthviz** [comment] 2023-12-05 15:44
> I'd also be in favor of closing this one as a duplicate of issue https://github.com/spyder-ide/spyder/issues/1500 because we'll need to expand our syntax highlighting capabilities to solve that issue.

Doing a quick check seems like there are a couple of issues related with syntax highlighting like: https://github.com/spyder-ide/spyder/issues/4683

Are those also worthy to be closed as duplicates of #1500 @ccordoba12 ?

**Comment by ccordoba12** [comment] 2023-12-05 17:49
Yeah, I think that's a good idea. Let's centralize everything related to syntax highlighting improvements in issue #1500.

But I'm not sure if our Pysyntect integration would be able to highlight differently docstrings from regular strings, so let's leave #295 open for now.

**Comment by dalthviz** [comment] 2023-12-06 16:19
Closing this as a duplicate of #1500 then

**Closed by dalthviz** 2023-12-06 16:19 UTC
Labels: resolution:Duplicate, type:Enhancement, component:Editor, component:Preferences, type:Discussion, status:Awaiting Followup
