### ISSUE TITLE
Spyder for remote debug

### ISSUE THREAD

**Issue by wuyingmm** [spyder-ide/spyder#2725] opened 2015-09-30 09:35 UTC
Hi,

I have problem and difficulty on using spyder to access a remote kernel. This is for remote debug.

So I install the anaconda on a remote server running Ubuntu 14.01 server. I can connect to the remote ubuntu server from my Windows local PC by SSH (Private key file). I want to connect to this remote python interpreter from my local Spyder IDE so that I can do remote debug. So I click Consoles->Connect to an Existing kernel->input remote server info. Then I get the error message to say the remote kernel died. Doesn't work if upgrade to the latest Spyder or start up the ipython server on the remote. 

My question are:

1. Whether I can do remote debug with Spyder
2. Does the "Existing kernel" mean a python interpreter or a ipython server?
3. How to connect to an existing remote kernel?
4. Whether I should open some particular ports in the firewall of local or remote?

Thank you very much.

Best wishes

**Comment by wuyingmm** [comment] 2015-09-30 09:41
The error message is "t seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console."

**Comment by ccordoba12** [comment] 2015-09-30 13:25
This is a duplicate of issue #2507.

**Closed by ccordoba12** 2015-09-30 13:25 UTC
Labels: duplicate

**Comment by Nodd** [comment] 2015-09-30 13:35
About 2., the kernel refers to IPython.

**Comment by fayeshine** [comment] 2015-10-30 09:26
I think this is not a duplicate with #2507 , Since this is about "it seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.", and #2507  is about crash. I also got this problem, I think there must some bug when connect to some remote ipython kernel using ssh keys.
