### ISSUE TITLE
Wrong indentation with parenthesis

### ISSUE THREAD

**Issue by faultrepeat** [spyder-ide/spyder#3856] opened 2016-12-18 23:13 UTC
## Description of your problem
Finishing a line with a complete set of parenthesis inside a set of brackets indents the next line as if you were continuing the line.

**What steps will reproduce the problem?**

1. test=[range(10)]
2. (hit enter key)

**What is the expected output? What do you see instead?**
I expect the indentation to be at the same level as previous line.
What I expect:
```
test=[range(10)]
<<<-- no indentation past the previous line.
```
What I see:
```
test=[range(10)]
      <<<-- indents to here
```
**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7.12
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-12-18 23:53
Thanks for reporting. This is a duplicate of issue #3700.

**Closed by ccordoba12** 2016-12-18 23:53 UTC
