### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by tol434** [spyder-ide/spyder#15201] opened 2021-04-09 01:48 UTC
### What steps will reproduce the problem?

Upgraded Spyder to 5.0.0 encountered error message saying that spyder_kernels >=2.0.1 was not installed. Uninstalled Spyder.  Reinstalled Spyder, issue remained.  Anaconda list shows spyder_kernels =2.0.1 installed.

# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.10.0                   py38_0
anyio                     2.2.0            py38haa95532_1
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38h2bbff1b_1
arrow                     0.13.1                   py38_0
astroid                   2.5              py38haa95532_1
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
autopep8                  1.5.6              pyhd3eb1b0_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.0                pyhd3eb1b0_2
backports.functools_lru_cache 1.6.3              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py38he774522_0
beautifulsoup4            4.9.3              pyha847dfd_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
blosc                     1.21.0               h19a0ad4_0
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.5           py38hcd4344a_0
chardet                   4.0.0           py38haa95532_1003
click                     7.1.2              pyhd3eb1b0_0
cloudpickle               1.6.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.4              pyhd3eb1b0_0
conda                     4.10.0           py38haa95532_0
conda-build               3.21.4           py38haa95532_0
conda-env                 2.6.0                         1
conda-package-handling    1.7.2            py38h76e460a_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
cookiecutter              1.7.2              pyhd3eb1b0_0
cryptography              3.4.7            py38h71e12ea_0
cycler                    0.10.0                   py38_0
decorator                 5.0.5              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713                   py_0
docutils                  0.17             py38haa95532_1
entrypoints               0.3                      py38_0
filelock                  3.0.12             pyhd3eb1b0_1
flake8                    3.9.0              pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
future                    0.18.2                   py38_1
glob2                     0.7                pyhd3eb1b0_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyhd3eb1b0_0
imagesize                 1.2.0              pyhd3eb1b0_0
importlib-metadata        3.10.0           py38haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
inflection                0.5.1            py38haa95532_0
intel-openmp              2020.2                      254
interpolation             2.2.1              pyhd8ed1ab_0    conda-forge
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.22.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
isort                     5.8.0              pyhd3eb1b0_0
jedi                      0.17.2           py38haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_2
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter-packaging         0.7.12             pyhd3eb1b0_0
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
jupyter_server            1.4.1            py38haa95532_0
jupyterlab                3.0.11             pyhd3eb1b0_1
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.4.0              pyhd3eb1b0_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keyring                   22.3.0           py38haa95532_0
kiwisolver                1.3.1            py38hd77b12b_0
lazy-object-proxy         1.6.0            py38h2bbff1b_0
libarchive                3.4.2                h5e25573_0
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libtiff                   4.2.0                hd0e1b90_0
libxml2                   2.9.10               hb89e7f3_3
llvmlite                  0.36.0           py38h34b8924_4
lz4-c                     1.9.3                h2bbff1b_0
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.4            py38haa95532_0
matplotlib-base           3.3.4            py38h49ac443_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.3              pyhd3eb1b0_0
mpmath                    1.2.1            py38haa95532_0
msys2-conda-epoch         20160418                      1
mypy_extensions           0.4.3                    py38_0
navigator-updater         0.2.1                    py38_0
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py38_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
nose                      1.3.7           pyhd3eb1b0_1006
notebook                  6.3.0            py38haa95532_0
numba                     0.53.1           py38hf11a4ad_0
numexpr                   2.7.3            py38hcbcaa1e_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
numpydoc                  1.1.0              pyhd3eb1b0_1
olefile                   0.46                       py_0
openssl                   1.1.1k               h2bbff1b_0
packaging                 20.9               pyhd3eb1b0_0
pandas                    1.2.3            py38hf11a4ad_0
pandoc                    2.12                 haa95532_0
pandocfilters             1.4.3            py38haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathspec                  0.7.0                      py_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0            py38h4fa10fc_0
pip                       21.0.1           py38haa95532_0
pkginfo                   1.7.0            py38haa95532_0
pluggy                    0.13.1           py38haa95532_0
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.10.0             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
psutil                    5.8.0            py38h2bbff1b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
py-lief                   0.10.1           py38ha925a31_0
pycodestyle               2.6.0              pyhd3eb1b0_0
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.20                       py_2
pydocstyle                6.0.0              pyhd3eb1b0_0
pyflakes                  2.2.0              pyhd3eb1b0_0
pygments                  2.8.1              pyhd3eb1b0_0
pylint                    2.7.4            py38haa95532_1
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38ha925a31_4
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
pytables                  3.6.1            py38ha5be198_0
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1              pyhd3eb1b0_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-libarchive-c       2.9                pyhd3eb1b0_1
python-slugify            4.0.1                      py_0
pytz                      2021.1             pyhd3eb1b0_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     20.0.0           py38hd77b12b_1
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.2              pyhd3eb1b0_0
qtconsole                 5.0.3              pyhd3eb1b0_0
qtpy                      1.9.0                      py_0
quantecon                 0.4.8                    py38_0
regex                     2021.4.4         py38h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
rope                      0.18.0                     py_0
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.100         py38h2bbff1b_0
scipy                     1.6.2            py38h14eb087_0
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py38haa95532_0
sip                       4.19.13          py38ha925a31_0
six                       1.15.0           py38haa95532_0
sniffio                   1.2.0            py38haa95532_1
snowballstemmer           2.1.0              pyhd3eb1b0_0
sortedcontainers          2.3.0              pyhd3eb1b0_0
soupsieve                 2.2.1              pyhd3eb1b0_0
sphinx                    3.5.3              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0
spyder                    5.0.0            py38haa95532_0
spyder-kernels            2.0.1            py38haa95532_0
sqlite                    3.35.4               h2bbff1b_0
sympy                     1.7.1            py38haa95532_0
tbb                       2020.3               h74a9793_0
tempita                   0.5.3dev         py38haa95532_1
terminado                 0.9.4            py38haa95532_0
testpath                  0.4.4              pyhd3eb1b0_0
text-unidecode            1.3                        py_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss                   0.4             pyhd3eb1b0_1002
tk                        8.6.10               he774522_0
toml                      0.10.2             pyhd3eb1b0_0
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.59.0             pyhd3eb1b0_1
traitlets                 5.0.5              pyhd3eb1b0_0
typed-ast                 1.4.2            py38h2bbff1b_1
typing_extensions         3.7.4.3            pyha847dfd_0
ujson                     4.0.2            py38hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.4             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  1.0.2            py38haa95532_1
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.36.2             pyhd3eb1b0_0
whichcraft                0.6.1              pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py38he774522_1
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0

**Comment by ccordoba12** [comment] 2021-04-09 01:59
Hey @tol434, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-09 01:59 UTC
