### ISSUE TITLE
lsp python: restarting problem.

### ISSUE THREAD

**Issue by hyuny223** [spyder-ide/spyder#15959] opened 2021-07-01 06:40 UTC
### What steps will reproduce the problem?

There is a problem about lsp pyhton.
it stays restarting and is not changed to ready.
how can I solve this problem?

**Comment by andfoy** [comment] 2021-07-02 15:51
Hi @hyuny223, thanks for reaching out. However, since the issue does not have the environment nor the operating system information that is required in order to try to understand this problem, we cannot do much with the information provided. I'm closing this one due to lack of reproduction information.

**Closed by andfoy** 2021-07-02 15:51 UTC

**Comment by hyuny223** [comment] 2021-07-04 05:10
Then, how can I show you information required?
