### ISSUE TITLE
Setuptools warning due to distutils being imported first

### ISSUE THREAD

**Issue by oldassagt** [spyder-ide/spyder#15093] opened 2021-04-03 08:18 UTC
### What steps will reproduce the problem?

c:\program files\python\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(

### Traceback
```python-traceback
c:\program files\python\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.3
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.5.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.3 (OK)
pygments >=2.0                :  2.7.2 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  49.2.1 (OK)
sphinx >=0.6.6                :  3.3.1 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.4 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by debajyoti1990** [comment] 2021-04-03 17:38
Duplicate of #15091

**Comment by ccordoba12** [comment] 2021-04-03 19:51
Thanks for noticing it @debajyoti1990. However, there seems to be another problem here (a warning emitted by `setuptools`).

@oldassagt, we'll try to fix the `spyder-kernels` problem in our next release and the warning in a future one. But for now you can safely ignore both.

**Comment by CAM-Gerlach** [comment] 2021-04-05 08:21
@ccordoba12 Given distutils' deprecation and forthcoming elimination, obsolescence in favor of setuptools, and the being essentially universally present with modern Python installs that are likely to be used with Spyder, its probably long past time to eliminate outdated references to it, and, for any non-setuptools-compatible features, find a modern, supported replacement.

I only see [three references to it](https://github.com/spyder-ide/spyder/search?q=distutils) to distutils in the codebase:

* Being called in `setup.py` for the `install_data` command [here](https://github.com/spyder-ide/spyder/blob/29fc09bac4268f9d82623ab49bd5a48c9382bdbb/setup.py#L117), which as far as I can tell is only used by a custom setup.py command to install the .desktop file for Linux, that must be manually called and is not used anywhere else, then only on non-wheel (and I presume non-distro) install methods. As I assume distro maintainers already handle this themselves via their own packaging systems, wheels are the modern standard for package installation, and the code has not been touched for 8 years (!!!) it probably isn't ever used by anyone anymore, so it can probably just be eliminated. Furthermore, modern setuptools does now support `install_data` (after deliberately excluding that feature for a while, due to the problems it could cause), so if we _really_ do need it for some reason, we could replace it with that, though given the near-certain lack of any meaningful usage, that likely isn't worth any extra effort.
* A handful of usages of `distutils.version.LooseVersion` here and in Spyder-Kernels, which is ancient, undocumented, and doesn't conform to the current spec for valid Python versions (PEP 440), not allowing some valid versions while allowing other invalid ones. It [can be substituted with](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python) with the modern replacement, `packaging.version.parse`, which has mostly-compatible behavior; `packaging` is a very small and lightweight package and a setuptools dependency so it should be implicitly required already, though we should specify it just in case.
* One [instance](https://github.com/spyder-ide/spyder/blob/01d9195b1a33d02f42faf3c8e0047412966a24ce/scripts/spyder_win_post_install.py#L137) of using `distutils.sysconfig.get_python_lib(plat_specific=1)` in the Windows post-install script, which can be replaced with the supported drop-in stdlib equivalent `sysconfig.get_path("platlib")`.

**Closed** 2021-04-16 04:59 UTC
Labels: type:Task, type:Techdebt
