### ISSUE TITLE
Next / previous cell keyboard shortcut

### ISSUE THREAD

**Issue by cjbe** [spyder-ide/spyder#4101] opened 2017-02-03 22:51 UTC
It would be really useful to have keyboard shortcuts to select the next or previous code cell, similar to the Matlab editor.

For exploratory data analysis one often ends up with distinct blocks of code that need to be run repeatedly, and in different orders. Code cells are great for this, and if one is executing the cells in order Shift+Enter is very useful. However if one wants to run code out of order there is no quick way to skip up and down the cells. If Ctrl+Up and Ctrl+Down selected the previous / next cell, this out of order cell execution could be dne without leaving the keyboard.

**Comment by ccordoba12** [comment] 2017-02-04 17:05
Thanks for reporting. This is duplicate of issue #1833.

**Closed by ccordoba12** 2017-02-04 17:05 UTC
Labels: resolution:Duplicate
