### ISSUE TITLE
ipython console and variable explorer are lagging or freezing

### ISSUE THREAD

**Issue by adrienchaton** [spyder-ide/spyder#9534] opened 2019-06-09 13:20 UTC
Hello everyone

I used Spyder IDE with python 3.5 on OSX 10.11 without problems.
I updated to OSX 10.12.6 and also updated python and packages/dependencies.

I am now on python 3.7.3 and IPython 7.5.0 with the updated Spyder 3.3.4.
I used pip3 for installing.

Since I am facing some recurrent issues. When I use the ipython console, after a bit it starts lagging. For instance, I type in a new variable (like a string) and it takes a good while to process after I hit enter. Then, when I type in new variables, hitting enter jumps the line or if I caps-lock it does enter but lags again or freezes. (the behavior of jumping lines instead of sending the command is recurrent too after the first lag of the console)
Similarly, when the ipython console starts not responding correctly, the variable explorer does not update correctly or is also lagging.

I tried re-installing spyder and ipython but it did not fix the problem.
Running the pip3 update also cannot help as it says everything is already up to date.
Ipython does launch from terminal and seems functioning correctly (outside of spyder).

I am unsure of where the problem could come from ...
The lags are not caused when calling functions imported from a specific package, they also happen when just defining string variables.

Did anyone face similar issues ? Or please, does anyone have some ideas for fixing this ?
I wish to keep using spyder which has great features but with this lag/crashing of the ipython console it becomes unpractical.

Thanks !

**Comment by ccordoba12** [comment] 2019-06-09 13:36
Thanks for reporting. This is a duplicate of issue #2902.

The current solutions to this problem are: 1) Using the Inline backend for Matplotlib plots, instead of the Automatic or Qt ones; or 2) Downgrading IPython to a 6.x version.

**Closed by ccordoba12** 2019-06-09 13:36 UTC

**Comment by adrienchaton** [comment] 2019-06-09 14:02
Thanks !!!
Spyder seems working fine now that I put the graphics backend to inline :-)
Which is minor limitation for me so no worries

**Comment by adrienchaton** [comment] 2019-06-11 15:34
Sorry, an other error, it seems minor and I can block this error not to show up but I report in case.

  File "/usr/local/lib/python3.7/site-packages/spyder/widgets/calltip.py", line 122, in hideEvent
    self._cursor_position_changed)
TypeError: 'method' object is not connected

do you know this one please ?
