### ISSUE TITLE
Autocomplete in ipdb

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9939] opened 2019-08-01 10:29 UTC
## Problem Description
When using the debugger, there is no autocomplete, unlike while otherwise using the console. 
I think it is surprising to the user that the console is behaving differently while debugging and while not debugging.

### What steps reproduce the problem?
1. type : `abba = 1` in the console
2. on the next line, `ab<tab>` gives a list of `abba` and `abs`
3. launch a debugger
4. type : `abba = 1`
5. on the next line, `ab<tab>` gives `ab    `

### What is the expected output? What do you see instead?
I would expect the autocomplete to work while debugging as well. 

## Versions

* Spyder version: 4.0.0.dev0 b7844ba66
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Darwin 18.7.0

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by impact27** [comment] 2019-08-01 10:33
Maybe relevant: https://github.com/ipython/ipython/blob/994d42dfba19206127e6a599669c625fef8886de/IPython/core/interactiveshell.py#L2133

**Comment by ccordoba12** [comment] 2019-08-01 13:02
This is a duplicate of issue #288.

**Closed by ccordoba12** 2019-08-01 13:02 UTC
