### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by NightFury10497** [spyder-ide/spyder#6127] opened 2018-01-04 07:17 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\andaconda\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "E:\andaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "E:\andaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "E:\andaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "E:\andaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "E:\andaconda\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "E:\andaconda\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "E:\andaconda\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "E:\andaconda\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "E:\andaconda\lib\s

**Comment by CAM-Gerlach** [comment] 2018-01-04 09:12
Thanks for reporting. This appears to be a duplicate of #4836 , which should be fixed in Spyder 3.2.2. Therefore, this issue will be closed. If updating to the latest version of Spyder (3.2.5) with ``conda update anaconda``  then ``conda update spyder`` in the Anaconda prompt doesn't do the trick for you, please follow our [troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the **Basic First Aid** and then **Emergency CPR** sections, and more than likely your problem will be resolved. In case you are still having trouble, please reopen and respond with the requested items under the **Calling for Help** heading, and we'll see what we can do. Best of luck!

**Closed by CAM-Gerlach** 2018-01-04 09:12 UTC
