### ISSUE TITLE
Open Project when one already open

### ISSUE THREAD

**Issue by marcusobrien** [spyder-ide/spyder#12967] opened 2020-06-07 06:48 UTC
### What steps will reproduce the problem?

Load a project
Then goto Projects->Open project

Then crashes

### Traceback
```python-traceback
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\projects\plugin.py", line 98, in <lambda>
    triggered=lambda v: self.open_project())
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\projects\plugin.py", line 289, in open_project
    self.notify_project_open(path)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\decorators.py", line 22, in wrapper
    self.emit_request(method, params, requires_response)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\projects\plugin.py", line 549, in emit_request
    self.main.completions.broadcast_notification(method, params)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\plugin.py", line 323, in broadcast_notification
    req_type, req)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 533, in broadcast_notification
    self.send_notification(language, request, params)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 524, in send_notification
    client.perform_request(request, params)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 452, in perform_request
    _id = handler(params)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\languageserver\decorators.py", line 41, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\languageserver\providers\workspace.py", line 46, in send_workspace_folders_change
    folder_uri = path_as_uri(folder)
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\site-packages\spyder\plugins\completion\languageserver\providers\utils.py", line 51, in path_as_uri
    path_obj = pathlib.Path(osp.abspath(path))
  File "C:\Users\marcu\anaconda3\envs\TF1CPU\lib\ntpath.py", line 548, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by goanpeca** [comment] 2020-06-08 18:16
Hi @marcusobrien, thanks for the report

I followed your steps but could not manage to reproduce it. Could you provide more details, or perhaps an animation with something like https://www.cockos.com/licecap/ to better understand the problem?

**Comment by ccordoba12** [comment] 2020-07-21 18:49
Closing as a duplicate of #13346.

**Closed by ccordoba12** 2020-07-21 18:49 UTC
Labels: status:Awaiting Followup
