### ISSUE TITLE
Run configuration doesn't persist: Cannot set run file to use console's namespace

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#20845] opened 2023-04-19 07:52 UTC
## Problem Description
 I want to use option "Run in console namespace instead of an empty one" from the menu "Run/Open Run Settings/Executor parameters/General options". When I check the option in the dialog box and close the dialog pressing 'ok', the modification is not taken into account. Indeed when I reopen the dialog, the option keeps unchecked.

I've checked also in debug mode, no special info is written!

The temporary countermeasure is to add `--current-namespace` at the end of the `%runfile foo.py --wdir` ipython command.

## Versions

* Spyder version: 6.0.0.dev0 46549dffa (pip)
* Python version: 3.10.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

**Comment by dalthviz** [comment] 2023-04-25 22:32
Hi @sylvain-bougnoux thank you for the feedback! I think you need for your custom config selection to persist to give it a name. So basically before clicking `Ok` you need to check the `Store current configuration as:` and put there a name. The UX/UI related to the run configuration after some refactoring done at https://github.com/spyder-ide/spyder/pull/17467 is something we need to improve for sure but using that option mentioned should be helpful I think.

Let us know if the info above helps!

Also pinging @ccordoba12 maybe this issue could be useful to get some feedback ideas about how the Run config should be exposed in the UI

**Comment by sylvain-bougnoux** [comment] 2023-05-04 11:11
OK it works then, thanks. Maybe to avoid confusion the 'ok' button should keep grey until a configuration name is filled?

**Comment by ccordoba12** [comment] 2023-07-29 15:01
This is basically a duplicate of issue #20700, so closing it in favor of that one.

**Closed by ccordoba12** 2023-07-29 15:01 UTC
Labels: type:Bug, type:Enhancement, User Experience (UX), component:Run
