### ISSUE TITLE
Reloaded modules: jupyter_client.session, zmq.eventloop, zmq.eventloop.ioloop, tornado.platform, tornado.platform.asyncio, tornado.gen, zmq.eventloop.zmqstream, jupyter_client.jsonutil, jupyter_client.adapter, spyder, spyder.pil_patch, PIL, PIL._version, PIL.Image, PIL.ImageMode, PIL.TiffTags, PIL._binary, PIL._util, PIL._imaging, cffi, cffi.api, cffi.lock, cffi.error, cffi.model

### ISSUE THREAD

**Issue by yatin1122** [spyder-ide/spyder#15740] opened 2021-05-31 03:55 UTC
### What steps will reproduce the problem?

what is this i am trying to just write import pandas as pd but it is showing this what to do

**Comment by ccordoba12** [comment] 2021-05-31 17:41
Hey @yatin1122, thanks for reporting. Sorry for the inconvenience. To disable that message for now, please go the menu

    Tools > Preferences

then to the section called `Python interpreter` and disable the option called `Show reloaded modules list`.

**Comment by ccordoba12** [comment] 2021-05-31 17:41
I'm going to close this issue because it's a duplicate of #15417.

**Closed by ccordoba12** 2021-05-31 17:41 UTC
