### ISSUE TITLE
can't show chinese character 

### ISSUE THREAD

**Issue by miaofu** [spyder-ide/spyder#6212] opened 2018-01-16 03:11 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/miaofu/spyder/spyder/plugins/ipythonconsole.py", line 889, in set_working_directory
    refresh_console=False)
  File "/Users/miaofu/spyder/spyder/plugins/workingdirectory.py", line 319, in chdir
    os.chdir( to_text_string(directory) )
OSError: [Errno 2] No such file or directory: '/Users/miaofu/Desktop/\xc3\xa5\xc2\x85\xc2\xac\xc3\xa5\xc2\x8f\xc2\xb8\xc3\xa5\xc2\x90\xc2\x8d\xc3\xa5\xc2\x8c\xc2\xb9\xc3\xa9\xc2\x85\xc2\x8d\xc3\xa7\xc2\xae\xc2\x97\xc3\xa6\xc2\xb3\xc2\x95'

## Version and main components

* Spyder Version: 4.0.0.dev0 0608076
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  0.7.6.1 (OK)
cython >=0.21     :  0.23.4 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-16 07:31
Thanks for reporting. This is a probable duplicate of #4816 , which was fixed around six months ago; your dev build is even older, so please update to fix. In any case, the fundamental source of the error is Python 2's lack of proper Unicode support, so you really should use Python 3, or else make do with ASCII paths, names, etc. Therefore, this issue will be closed.

**Closed by CAM-Gerlach** 2018-01-16 07:31 UTC
