### ISSUE TITLE
Incorrect setting of Qt API n°2

### ISSUE THREAD

**Issue by MatthieuDartiailh** [spyder-ide/spyder#2282] opened 2015-03-27 21:31 UTC
Even when the API n°2 is selected some Qt objects still use the API n°1. I typically get this type of warning each time I run one of my program (which use the enaml library which sets those to API n°2) :

Warning/PyQt4-Spyder (API 'QDate' has already been set to version 1)
Warning/PyQt4-Spyder (API 'QDateTime' has already been set to version 1)
Warning/PyQt4-Spyder (API 'QTextStream' has already been set to version 1)
Warning/PyQt4-Spyder (API 'QTime' has already been set to version 1)
Warning/PyQt4-Spyder (API 'QUrl' has already been set to version 1)

As we can ignore the sip setapi errors and that my program actually does not use those it is fine but still not ideal
If anybody can point me to the where this is set in Spyder I will be happy to do a PR to fix that.

**Comment by Nodd** [comment] 2015-03-27 23:31
:+1:

**Comment by ccordoba12** [comment] 2015-03-28 00:14
Is this happening in 2.3.4 or in master? Qt API 1 won't be supported since Spyder 3.0, and we are not going to release more bug fixes for 2.3.

So my recommendation would be to switch to master, and if you continue to see these errors, then we can see what we can do about them. Else, you should wait unitl 3.0 is released (hopefully in the summer :-)

**Comment by MatthieuDartiailh** [comment] 2015-03-29 15:05
I can confirm that this still happens into latest master.

**Comment by ccordoba12** [comment] 2015-03-29 18:31
Ok, I don't understand that can be happening in this case. So please give us a simple and reproducible example that we can use to test and fix this problem in our side.

**Comment by Nodd** [comment] 2015-03-30 09:28
I have the same problem. With a `grep setapi` I found:

    spyderlib/qt/__init__.py:34:        sip.setapi('QString', 2)
    spyderlib/qt/__init__.py:35:        sip.setapi('QVariant', 2)

There are other apis that are not set to version 2, see http://pyqt.sourceforge.net/Docs/PyQt4/incompatible_apis.html
The fix is very easy, it's only a matter of using `setapi` on missing values.

**Comment by ccordoba12** [comment] 2015-03-31 14:15
Thanks @Nodd for the reference and @MatthieuDartiailh for the PR. That's definitely the way to go as a team!!

**Closed** 2015-04-01 00:03 UTC
Labels: bug, Easy, Python-Console
