### ISSUE TITLE
Resetting kernel does not clear variables in explorer

### ISSUE THREAD

**Issue by bfdb** [spyder-ide/spyder#14271] opened 2020-11-20 08:27 UTC
### What steps will reproduce the problem?

When resetting the kernel, variables are not cleared from the variable explorer.

Moreover, clearing all variables using the eraser icon does not seem to work.

Lastly, I selected all variables and pressed the 'delete' key on my keyboard which raised this issue.

### Traceback
```python-traceback
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'd_cntr_redii2exio_iso3'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_eu_va_p_2030_base_ielcb_nuts2'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_out_nuts2'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_base'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_base_na'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_base_s_bm'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_base_s_bm_r'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_delta_r_s_bm'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_delta_s_bm'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_scen'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_scen_s_bm'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_prod_nuts2_2030_scen_s_bm_r'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_base'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_base_ielcb_nuts2'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_cntr_base'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_cntr_delta'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_cntr_delta_r'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_cntr_scen'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_delta'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_delta_ielcb_nuts2'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_delta_r'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_delta_r_ielcb_nuts2'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_scen'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'df_va_p_2030_scen_ielcb_nuts2'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'gdf_eu'
Exception in comms call remove_value:
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\bfdeboer\anaconda3\envs\gdx\lib\site-packages\spyder_kernels\console\kernel.py", line 180, in remove_value
    ns.pop(name)
KeyError: 'gdf_world'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.6.12
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by juanis2112** [comment] 2020-11-21 00:32
Hi @bfdb thanks for reporting this. Can you tell me how are you resetting the kernel?

**Comment by bfdb** [comment] 2020-11-30 15:30
Hey @juanis2112 thanks for picking this up. I reset by pressing ctrl+.

**Comment by ccordoba12** [comment] 2020-11-30 16:17
Hey @bfdb, could you give us a simple and reproducible example that generates your error?

**Comment by bfdb** [comment] 2020-12-01 15:19
Hey @ccordoba12, 


I am able to reproduce the error as follows:

1. Open spyder.
2. Execute the following script:
```
spam = 'hello'
ham = 'world'
eggs = ' '.join([spam, ham])
print(eggs)
```
3. highlight console
4. press ctrl + .

Based on previous performance, I expected all variables to be removed from the variable explorer. However, the variables are still shown. 

When trying to open a variable by double clicking, I get an error message that Spyder was unable to retrieve the value of this variable from the console. 

When attempting to manually delete a variable by selecting and pressing delete, I first get a pop up asking 
whether i want to remove the selected item. Finally, when pressing OK i get the error message upon which this issue is raised.

Please note that after submitting this issue, Spyder seized to boot beyond showing the splash screen. I removed anaconda (including spyder), and installed the latest version of anaconda (1.10.0). Unfortunately, Spyder still did not boot. Based on the following [instruction ](https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#spyder-errors-or-failure-to-launch-on-windows) I deleted the folder .spyder-py3 from my user folder. This resolved the error and Spyder now boots as expected.

However, the issue regarding the variable explorer still persists in the new Spyder version (4.1.5).

Finally, please not that I'm using Python 3.6 due to dependency on an old package.

**Comment by zach-morris** [comment] 2021-03-21 21:14
I came here to write this same issue, but found this old one.  Reproducing on OSX 10.14.6 / Spyder 4.2.1 / Python 3.7.10 is fairly easy:

Start Spyder
Enter a random variable into the ipython console:
```
test = 123
```
Restart Kernel (Apple + . on OSX)
Verify ipython console prompt did reset the Kernel
Note that the variable is still listed in the variable explorer.
Verify the variable is no longer present:
```
test

Traceback (most recent call last):

  File "<ipython-input-1-4e1243bd22c6>", line 1, in <module>
    test

NameError: name 'test' is not defined
```

image
<img width="717" alt="Screen Shot 2021-03-21 at 2 10 17 PM" src="https://user-images.githubusercontent.com/12554283/111921046-b47be500-8a4f-11eb-908f-fd99d9fb56af.png">

**Comment by ccordoba12** [comment] 2021-03-25 17:45
This is a duplicate of issue #14481. We'll try to fix it in a future release.

**Closed by ccordoba12** 2021-03-25 17:45 UTC
Labels: status:Awaiting Followup

**Comment by zvikafik** [comment] 2023-11-25 05:21
I still encounter the same problem
