### ISSUE TITLE
Matplotlib windows are not shown in front of Spyder on OS X

### ISSUE THREAD

**Issue by ghost** [spyder-ide/spyder#2530] opened 2015-07-12 19:49 UTC
I updated to Anaconda 2.3.0 (OS X 64 bit, Python 2.7) with Spyder 2.3.5.2. I configured Spyder with interactive graphics but then no graphic window is shown. Only inline graphics work.

I deleted the Anaconda installation and the Anaconda configuration folders with `rm -rf .conda/ .spyder2/ .ipython/ .matplotlib/` and installed Anaconda 2.3.0 again. But that didn't help.

Any idea how to get interactive graphics in Anaconda 2.3.0 with Spyder back again?

**Comment by ccordoba12** [comment] 2015-07-12 21:01
Questions:
1. What's the exact name of the option you're using to set interactive graphics?
2. Are you doing it for Python or IPython consoles?

**Comment by kvico** [comment] 2015-07-13 08:54
Steps to reproduce:

1.) Start Spyder 2.3.5.2 from Anaconda Launcher
2.) Go to preferences -> IPython console -> Graphics -> Backend: changed to "Automatic"
3.) Select "Apply" and close preferences 
3.) Restart IPython kernel
4.) Show simple graphic like sin(x)
=>  No interactive window pops up or is open in the background

Also quit Spyder and restart after change in preferences didn't shows the interactive graphic window.

**Comment by ccordoba12** [comment] 2015-08-24 17:03
I can reproduce this issue and I'll fix it in 2.3.6

The problem with the automatic backend on Mac is that new plot windows are generated behind Spyder, and no new entries are shown in the Dock to select them. So the only way to see those windows is by minimizing Spyder.

I'm going to change that so that at least a new entry is generated in the dock (by using a different backend), although new windows will still be generated behind Spyder.

**Comment by ccordoba12** [comment] 2015-08-24 17:18
Sorry, I just found out that I can't do the fix I mentioned because it won't work for external Python interpreters.

@kvico, the only solution for now is for you to select the Qt backend instead of the Automatic one.

**Comment by ccordoba12** [comment] 2015-08-24 17:22
This is related to issue #2085 and #2054.

**Comment by kvico** [comment] 2015-08-26 19:32
@ccordoba12 thanks for your investigation and workaround!

**Comment by rantanplan77** [comment] 2017-03-23 17:23
```
fig = pylab.gcf()
fig.canvas.manager.window.raise_()
```

This works for me for the automatic backend.

**Comment by goanpeca** [comment] 2019-11-28 02:07
![macplot](https://user-images.githubusercontent.com/3627835/69771184-e7fb7780-1159-11ea-925a-59ebf96517e9.gif)

I cannot reproduce this on latest master on mac. Closing

**Closed by goanpeca** 2019-11-28 02:07 UTC
Labels: OS:MacOS, component:IPython Console, type:Bug

**Comment by psomdeb25** [comment] 2022-07-26 10:27
![Screenshot_SpyderIDE_macOS](https://user-images.githubusercontent.com/24921395/180983995-12793602-2f3b-40a8-99f4-a90680e87997.png)

`# x and y given as array_like objects
import plotly.express as px
fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
fig.show()`

I am on Spyder (Python 3.8). I tried changing under "Preferences" > IPython console > Graphics > Graphics backend. I changed between Automatic, Qt5 and Inline and then restarted Spyder. Yet, the plot doesn't appear in the "Plots" pane. However when I run the code in Jupiter notebook. I can see my plot. What might be the issue? Can anyone suggest?

**Comment by ccordoba12** [comment] 2022-07-26 14:18
Hey @psomdeb25, I think this error is fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

**Comment by psomdeb25** [comment] 2022-07-27 11:33
> Hey @psomdeb25, I think this error is fixed in our latest version (5.3.2).
> 
> Since it's still not available in Anaconda, you have two options:
> 
> 1. Use our Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
> 2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:
>    ```
>     conda create -n spyder-cf -c conda-forge spyder
>     conda activate spyder-cf
>     spyder
>    ```

Thank you for the response. I will try this out.

**Comment by ccordoba12** [comment] 2022-07-27 15:50
@psomdeb25, sorry, I just saw that you're using Plotly. In that case, Spyder can't show its plots because they are meant to be displayed in the Jupyter notebook or JupyterLab.
