### ISSUE TITLE
Help pane not responding to editor inputs

### ISSUE THREAD

**Issue by 1313e** [spyder-ide/spyder#14683] opened 2021-02-03 03:04 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I think this is an issue that is in all Spyder v4.x versions, not just the one I am currently using.
In the settings, I can set that whenever I write a left parenthesis next to an object in either the editor or the IPython console, it will show its docstring in the Help pane.
In Spyder v3, that worked brilliantly and I really like that feature.
However, in Spyder v4, it works fine for the IPython console, but refuses to work for the editor.
I have tried a large range of different settings, but no matter what I do, the Help pane will not respond to me writing the left parenthesis.
It works just fine whenever I press CTRL + I for example (which I also use often), but the automatic showing of the docstring is non-functional for me.

### What steps reproduce the problem?

1. Enable automatic Help connections for editor;
2. Type a left parenthesis next to any object.

### What is the expected output? What do you see instead?
I expect the Help pane to show me the docstring of the associated object, but it does not change its current contents at all.

## Versions

* Spyder version: 4.2.1
* Python version: 3.7.4
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.5.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.17.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.3.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.5.3 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.3.1.post20200810 (OK)
sphinx >=0.6.6                  :  3.2.0 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.2.0 (OK)
numpy >=1.7                     :  1.19.1 (OK)
pandas >=1.1.1                  :  1.1.0 (NOK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)

```

**Comment by dalthviz** [comment] 2021-02-03 17:36
Hi @1313e thanks for the feedback! I think this is a known issue. @ccordoba12 is there any issue already tracking this?

**Comment by dalthviz** [comment] 2021-02-03 19:51
Duplicate of #10671

**Closed** 2021-02-03 19:51 UTC
Labels: resolution:Duplicate
