### ISSUE TITLE
Spyder 6.0.0 hangs while starting when "Loading Code Analysis"

### ISSUE THREAD

**Issue by bjsilver** [spyder-ide/spyder#22429] opened 2024-09-04 14:01 UTC
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I open a fresh install of Spyder 6.0.0 from the command line, and it hangs forever at the 'Loading Code Analysis..." stage

### What steps reproduce the problem?

1. Installed Spyder 6 in a fresh conda environment (using mamba)
2. Open spyder from command line
3. Spyder hangs

### What is the expected output? What do you see instead?

Spyder to open. Spyder does not open

## Versions

* Spyder version: 6.0.0
* Python version: 3.12.5
* Qt version: 5.15.8
* PyQt version: 2.4.1
* Operating System name/version:  CentOS Linux version 7

**Comment by ccordoba12** [comment] 2024-09-04 15:57
Hey @bjsilver, thanks for reporting. This is a duplicate of issue #22415, so I'm going to close it in favor of that one.

In the meantime, please read that issue for a possible workaround.

**Closed** 2024-09-04 15:58 UTC
