### ISSUE TITLE
cannot search a string in all files inside a project

### ISSUE THREAD

**Issue by praveen-14** [spyder-ide/spyder#11583] opened 2020-02-18 11:55 UTC
### What steps will reproduce the problem?

Using default hot keys, ctrl+shft+f gives this error. Search pane is there but gives a error when search starts.

### Traceback
```python-traceback
  File "/home/praveen/anaconda3/envs/pytorch_mpi/lib/python3.7/site-packages/spyder/plugins/findinfiles/widgets.py", line 123, in run
    self.find_files_in_path(self.rootpath)
  File "/home/praveen/anaconda3/envs/pytorch_mpi/lib/python3.7/site-packages/spyder/plugins/findinfiles/widgets.py", line 141, in find_files_in_path
    for path, dirs, files in os.walk(path):
  File "/home/praveen/anaconda3/envs/pytorch_mpi/lib/python3.7/os.py", line 337, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-76-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-02-18 14:01
> Search pane is there but gives a error when search starts.

Please post a screenshot of the search you're trying to run because I don't understand how this error was generated.

**Comment by praveen-14** [comment] 2020-02-19 11:34
It went away after selecting a directory for "search in". I remember as it was not needed and the default directory is current working directory. Anyway, sorry for the false alarm.

**Comment by ccordoba12** [comment] 2020-02-19 16:00
Ok, closing because there's no clear way to reproduce this.

**Closed by ccordoba12** 2020-02-19 16:00 UTC
Labels: status:Awaiting Followup
