### ISSUE TITLE
Spyder Crash

### ISSUE THREAD

**Issue by SibasishTripathyy** [spyder-ide/spyder#6031] opened 2017-12-21 08:21 UTC
## Description of your problem
I wrote this piece of code to import SVC class from svm library.
`from sklearn.svm import SVC`
`classifier = SVC()`
Now, when i place my cursor just before the parenthesis in front of the letter C and press

_Control + I_

to inspect, instead of showing me the parameters/documentation and other info(as it does with other classes), spyder crashes with the following error message on my terminal

> Segmentation fault (core dumped)

**What steps will reproduce the problem?**

1. Type sklearn.svm import SVC
2. Then type, classifier = SVC()
3. Press Control + I to inspect SVC class for parameters. (It then crashes)

**What is the expected output? What do you see instead?**
Expect to see the SVC class documentation.
I see spyder crashing and an error message:- Segmentation fault (core dumped)

**Please provide any additional information below**

## Versions and main components

* Python Version: 3.6.2
* Operating system: Fedora OS

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-12-21 14:08
Thanks for reporting. This looks like a duplicate of issue #5514 and it'll be fixed in our 3.2.5 version, to be released soon.

**Closed by ccordoba12** 2017-12-21 14:08 UTC
