### ISSUE TITLE
Spyder not working with IPython 8.17.1

### ISSUE THREAD

**Issue by mondjef** [spyder-ide/spyder#21472] opened 2023-10-30 16:18 UTC
## Problem Description
Get the following error when any python module is loaded...

```
Error in callback <bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x0000022C42EA4B20>> (for pre_run_cell):
Traceback (most recent call last):

  File ~\AppData\Roaming\Python\Python310\site-packages\IPython\core\events.py:82 in trigger
    func(*args, **kwargs)

TypeError: AutoreloadMagics.pre_run_cell() takes 1 positional argument but 2 were given
```
If I downgrade IPython to 8.17.0 Spyder fails to load, if I downgrade IPython to 8.16.0 Spyder runs fine and can load modules again.

Note, if I open IPython 8.17.1 directly outside of Spyder it runs fine and can load modules.

### What steps reproduce the problem?

1. install Spyder along side IPython 8.17.1
2. load a module either from script or from interactive console within Spyder

### What is the expected output? What do you see instead?
modules should load without issues

### Paste Traceback/Error Below (if applicable)

```python-traceback

Error in callback <bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x0000022C42EA4B20>> (for pre_run_cell):
Traceback (most recent call last):

  File ~\AppData\Roaming\Python\Python310\site-packages\IPython\core\events.py:82 in trigger
    func(*args, **kwargs)

TypeError: AutoreloadMagics.pre_run_cell() takes 1 positional argument but 2 were given

```

## Versions
* Spyder version: 5.4.5
* Python version: 3.10.11
* Qt version: 5.15.2
* PyQt version:  5.15.10
* Operating System name/version: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  3.0.0 (OK)
cookiecutter >=1.6.0                                                        :  2.4.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.17.1 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.1 (OK)
jsonschema >=3.2.0                                                          :  4.19.2 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.10.0 (OK)
numpydoc >=0.6.0                                                            :  1.6.0 (OK)
paramiko >=2.4.0                                                            :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.6 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.7 (OK)
pylint_venv >=3.0.2                                                         :  3.0.3 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.4 (OK)
qtpy >=2.1.0                                                                :  2.4.1 (OK)
rtree >=0.9.7                                                               :  1.1.0 (OK)
setuptools >=49.6.0                                                         :  68.2.2 (OK)
sphinx >=0.6.6                                                              :  7.2.6 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.6.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.4 (OK)
matplotlib >=3.0.0                                                          :  None (NOK)
numpy >=1.7                                                                 :  None (NOK)
pandas >=1.1.1                                                              :  None (NOK)
scipy >=0.17.0                                                              :  None (NOK)
sympy >=0.7.3                                                               :  None (NOK)

```

**Comment by dzalf** [comment] 2023-10-30 17:57
Wow. I cannot believe that we are facing the same issue:

![image](https://github.com/spyder-ide/spyder/assets/3759916/92a2f977-cc39-491b-9fc8-96477f680537)

Spyder: 5.4.5
IPython: 8.17.1
Python: 3.12
OS: Win 11

all dependencies installed:

![image](https://github.com/spyder-ide/spyder/assets/3759916/a22170f0-764f-4d2c-9833-26bc0d709617)

**Comment by dalthviz** [comment] 2023-10-30 23:26
Hi @mondjef and @dzalf for the feedback! I was able to reproduce this and it is likely to be an incompatibility with some changes that came with IPython 8.17.1. I think 8.17.0 had even more incompatibilities (like https://github.com/jupyter/qtconsole/issues/588) causing that version to be yanked.

Probably we should try to fix this for 5.5.0 :thinking: What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment] 2023-10-31 05:12
>  it is likely to be an incompatibility with some changes that came with IPython 8.17.1

That's right. IPython 8.17 broke the `%autoreload` magic, which we use by default in our kernel and causes this error. That was reported in https://github.com/ipython/ipython/issues/14230 by a VSCode maintainer.

> Probably we should try to fix this for 5.5.0 🤔 What do you think @ccordoba12 ?

There's little we can do on our side because this requires a fix in IPython.

**Comment by ccordoba12** [comment] 2023-10-31 05:13
The only thing I can think of is pinning IPython to 8.16 in our installers. What do you think @dalthviz?

**Comment by dzalf** [comment] 2023-10-31 13:47
Hi guys @ccordoba12 @dalthviz 

I just want to confirm that I did uninstall IPython 8.17.1: `pip uninstall ipython`

then proceeded to install IPython 8.16: `pip install ipython==8.16`

which worked like a charm:

![image](https://github.com/spyder-ide/spyder/assets/3759916/c5836e03-faa9-49ba-beae-1c026180d9ac)

🍻

**Comment by dalthviz** [comment] 2023-10-31 20:05
> The only thing I can think of is pinning IPython to 8.16 in our installers. What do you think @dalthviz?

That would prevent the 5.5.0 installers to have a broken console indeed :+1: However, 5.5.0 pip installations, or at least new ones, will still experience this issue since they will try to get the most up to date IPython version, rigth? And the same could happen to conda installations, or at least new installations, when the IPython feedstock gets updated to 8.17.1 (currently the latest version is still 8.16.1 but that probably will change soon), no?

**Comment by ccordoba12** [comment] 2023-11-01 00:57
> However, 5.5.0 pip installations, or at least new ones, will still experience this issue since they will try to get the most up to date IPython version, rigth?

Correct.

> And the same could happen to conda installations, or at least new installations, when the IPython feedstock gets updated to 8.17.1 (currently the latest version is still 8.16.1 but that probably will change soon), no?

Yep, that's true too.

However, it seems that bug is fixed now, so we only need to wait for a new release.

**Comment by dalthviz** [comment] 2023-11-01 19:15
> However, it seems that bug is fixed now, so we only need to wait for a new release.

So maybe we should add `ipython!=8.17.1` to the  `spyder-kernels` dependencies restrictions to mark this as fixed?

**Comment by ccordoba12** [comment] 2023-11-01 22:33
8.17.2 is out! https://pypi.org/project/ipython/8.17.2

@dalthviz, could you check this problem is fixed in that version? Thanks!

**Comment by dalthviz** [comment] 2023-11-02 23:06
> @dalthviz, could you check this problem is fixed in that version? Thanks!

Checking seems like IPython 8.17.2 fixes the issue @ccordoba12 :+1:

**Comment by ccordoba12** [comment] 2023-11-05 23:59
That's great! Then I'm going to increase our minimal required IPython version to 8.17.2 in order to prevent this error.

**Closed** 2023-11-06 16:04 UTC
Labels: type:Bug, component:IPython Console, upstream
