### ISSUE TITLE
Autocomplete, function help, function signature not working

### ISSUE THREAD

**Issue by Anurag-Chaudhary** [spyder-ide/spyder#6142] opened 2018-01-05 19:02 UTC
## Description
Autocomplete, function help, function signature not working in the editor. iPython console works fine.

**What steps will reproduce the problem?**

1. Start coding
2. Press ctrl-K to auto-complete variable name.
3. Press ctrl-I on any external library function

**What is the expected output? What do you see instead?**
Auto-complete should work.
Ctrl-I should show help on the function

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-05 22:57
Thanks for reporting. There are a number of reasons why this could be—certain packages aren't supported by Python's third party completion libraries, ``jedi`` and ``rope``; if you leave the editor open too long, particularly after sleep, locking the screen, etc. completion will stop working (I'm currently trying to work on temporary fix until a new completion architecture is rolled out in Spyder 4); sometimes dependency conflicts can occur, something can be funky with your install, etc. How did you install Spyder? Via Anaconda, or with ``pip``/your distribution? If you did the latter, please try the former since user install issues are common with those methods. 

Also, please try the steps listed in the [Basic First Aid section](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) of the Spyder troubleshooting guide as well as the the [Code Completion section](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#complete-health-autocompletionhelp-anomalies), and if it still doesn't work, provide the additional information requested under the [Calling for Help](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#calling-for-help-still-have-a-problem) section. If we don't hear from you, we'll close this issue after 1 week (7 days). Thanks!

**Comment by CAM-Gerlach** [comment] 2018-01-05 23:58
Also, this appears to be a duplicate of #5782 . Read that issue for more suggestions, and if you have further information to add, please add it over there. Thanks.

**Closed by CAM-Gerlach** 2018-01-05 23:58 UTC
Labels: status:AwaitingFollowup
