### ISSUE TITLE
Code formatter style per project

### ISSUE THREAD

**Issue by ba-tno** [spyder-ide/spyder#16004] opened 2021-07-12 15:45 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

(not an actual issue, but a feature request, hence I've deleted some parts of the template).

## Problem Description

I work on two projects: project A and project B.  
Both have their own Spyder project.
In project A I don't want to apply any autoformatting rules on save.  
In project B I want to apply `black` code autoformatting on save.

Currently I have to remember to switch this setting in Spyder preferences whenever I switch project. 

Ideally this setting would be settable on a project basis such that whenever I open project A no autoformatting is applied on save, and when I open project B `black` autoformatting is applied.

## Versions

* Spyder version: 5.0.5 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.24.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.5 (OK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by steff456** [comment] 2021-07-12 19:28
Hi @ba-tno,

This is an issue we've discussed previously and we are thinking how is the best way to break down our preferences so we can enable preferences per project. We have this present for the future, because the current backend doesn't enable to do this in an easier way. In case you are interested to help us with this refactoring, please let us know.

**Comment by ccordoba12** [comment] 2021-07-13 01:53
This is really a duplicate of issue #9804, so I'm closing it in favor of that one.

As @steff456 pointed out, we'll try to fix this in the future and any help is welcomed.

**Closed by ccordoba12** 2021-07-13 01:53 UTC
Labels: component:Projects, type:Enhancement
