### ISSUE TITLE
code completion can't work in editor

### ISSUE THREAD

**Issue by TFDeeplearner** [spyder-ide/spyder#7428] opened 2018-07-11 08:58 UTC
I can auto complete all coding in ipython console using 'Tab',but I can't auto complete in editor.
And "Go to definition" also can't work.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Linux 4.15.0-24-generic

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.5 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
psutil >=0.3     :  5.4.5 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-11 13:22
Thanks for reporting. This is a duplicate of #5782.

Please see there for possible solutions.

**Closed by ccordoba12** 2018-07-11 13:22 UTC
