### ISSUE TITLE
Wrong autoindentation with lists that contains strings with parenthesis

### ISSUE THREAD

**Issue by ibackus** [spyder-ide/spyder#3700] opened 2016-11-17 21:54 UTC
EDIT: Also found more bad behavior when using shift+tab or backspace to unindent

## Description of your problem

**What steps will reproduce the problem?**

1. Type a line of code and press Enter 
2. Backspace or Shift+Tab on new line

**What is the expected output? What do you see instead?**
I expect the indentation to follow the previous line, instead I get random behavior (sometimes).   In the case of a new line I expect shift+tab or backspace to unindent one level, not go all the way back.  Here are a few example images:

Wrong:
![screenshot from 2016-11-17 13-34-09](https://cloud.githubusercontent.com/assets/6054037/20409012/cad5e5c2-accc-11e6-8c13-3995bcd20431.png)

Wrong:
![screenshot from 2016-11-17 13-34-20](https://cloud.githubusercontent.com/assets/6054037/20409011/cad27ca2-accc-11e6-83d5-ae848e4a109c.png)

Correct:
![screenshot from 2016-11-17 13-34-47](https://cloud.githubusercontent.com/assets/6054037/20409013/cad860f4-accc-11e6-9a04-6a305a59ee58.png)

Wrong:
![screenshot from 2016-11-17 14-07-44](https://cloud.githubusercontent.com/assets/6054037/20409769/b7ce3c7e-accf-11e6-972a-be81eb19ff15.png)

Correct:
![screenshot from 2016-11-17 14-07-59](https://cloud.githubusercontent.com/assets/6054037/20409770/b7e2f632-accf-11e6-9fc5-565fc3ec52d4.png)

**Please provide any additional information below**
This only started happening to me after upgrading to spyder 3.0.1 from 2.x (I forget which version I had), using pip.

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 2.7.12
* Operating system:
Using Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux (Ubuntu 16.04)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.16.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  0.7.6 (OK)
```

**Comment by ccordoba12** [comment] 2016-11-17 23:43
@rlaverde, could you take a look at this one to see if it's fixed with the PRs you have developed?

**Comment by rlaverde** [comment] 2016-11-18 17:21
@ccordoba12 I wasn't able to reproduce any of them with the current 3.x branch (although I can reproduce them with v3.0.1), I think they were solved in #3576

@ibackus please wait some days to spyder 3.0.2 release and test if this bugs are still present.

**Comment by ccordoba12** [comment] 2016-11-18 23:23
@rlaverde is right. This is going to be fixed in 3.0.2.

About your 4th screenshot, we don't consider it a bug because a new line is created and indented to start at the same level as `line[i] = ''` so that user can keep writing code for the same `if` block.

**Comment by ibackus** [comment] 2016-11-21 21:10
@ccordoba12 I accidentally put my 4th screenshot in the wrong order.   This has been corrected and did appear to be an error.  shift tabbing should unindent one level, not all the levels, but appears to have been fixed by 3.0.2.

@ccordoba12
I have downloaded spyder 3.0.2 but the problem in the 1st screenshot persists.

**Comment by ccordoba12** [comment] 2016-11-21 21:15
I tested it locally and it doesn't fail for me :-/

**Comment by ccordoba12** [comment] 2016-11-22 02:46
Sorry, you're right. The key to your problem is the parenthesis inside the strings.

@rlaverde, please try this code to see that it's failing:

```python
def f():
    tags = ['(a)', '(b)', '(c)']<Enter>
            <cursor ends up here>
```

@rlaverde, I'm going to assign this one to you since you've been working on this stuff lately :-)

**Closed** 2017-01-07 21:23 UTC
