### ISSUE TITLE
Debug mode not working on win10

### ISSUE THREAD

**Issue by mirekslouf** [spyder-ide/spyder#17264] opened 2022-01-30 12:54 UTC
### Issue Report Checklist

* [Y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [Y] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [Y] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [Spyder specific] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [Y] Tried basic troubleshooting (if a bug/error)
    * [Y] Restarted Spyder
    * [Y] Reset preferences with ``spyder --reset``
    * [Y, Miniconda with Spyder & others] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/) 
    * [Y] Tried the other applicable steps from the Troubleshooting Guide
* [Y] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

**Debugger freezes for any code**, such as:

```
m = 1
n = m + 1
print(m,n)
```

When I run the debugger [Debug file = Ctrl+F5], it freezes at the very first command. No response after [Run current line = Ctrl+F10] or other command (such as Ctrl+F11, Ctrl+F12, Ctrl+Shift+F12]). The console is frozen, even [Stop current command does not work] and the only way is to close the console (the new console that is opened automatically, works - but it freezes again after [Ctrl+F5]):

![spyder_degugging-frozen](https://user-images.githubusercontent.com/22853864/151700035-4abab0e9-92e8-4a2a-ba23-0c3c131850ca.png)

### Note

* Similar issue has already been reported (and closed):

 Debug mode not working on win10 for any code #14380 

### What steps reproduce the problem?

1.  Write any code.
2.  Press [Ctrl+F5] and see...

### What is the expected output? What do you see instead?

See image above.

### Paste Traceback/Error Below (if applicable)

See image above.

## Versions

```
* Spyder version: 5.1.5 None
* Python version: 3.9.5 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10
```
### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  8.0.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.1 (OK)
pandas >=1.1.1                :  1.4.0 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2022-01-30 20:52
Hey @mirekslouf, thanks for reporting. I think this is fixed in our latest version (5.2.2), released last week. Please update to it and let us know if that fixes the problem for you.

**Comment by mirekslouf** [comment] 2022-01-30 21:29
* Thank you for your super-fast response & recommendation.
* After the update (`conda install spyder=5.2.2`) the debugger works fine.
* Conclusion: Spyder is great, problem is fixed, everything's gonna be alright :-)

**Comment by ccordoba12** [comment] 2022-01-30 21:59
Great! I'm glad the problem is fixed in 5.2.2 (was not totally sure about that).

**Closed by ccordoba12** 2022-01-30 21:59 UTC
Labels: status:Awaiting Followup

**Comment by M-Nassir** [comment] 2022-02-15 07:55
Will Spyder version 5.2.2 be available in anaconda anytime soon so that I can update and hopefully be a able to run debug mode?

**Comment by mirekslouf** [comment] 2022-02-17 08:22
As mentioned above, in my version of Miniconda (Anaconda should be the same, I suppose), the following command worked:
* `conda install spyder=5.2.2`
* you may want to install Spyder in its own environment, but for me it worked even like this

**Comment by M-Nassir** [comment] 2022-02-17 09:45
This solution worked for me: 

in the base environment of anaconda install latest version of Spyder using "conda install -c conda-forge spyder=5.2.2"

Unfortunately when I installed it onto a local conda environment, Spyder would close after start up. However, the local environment can still be used in Spyder by specifying the python interpreter under the Preferences->Python interpreter options.

**Comment by handsomedavid123** [comment] 2022-06-05 02:24
@ccordoba12 @mirekslouf 
hello i'm new in this feild. could you teach me how to install spyder=5.2.2 on anaconda navigator? my latest version is 5.1.5. i also tried to use conda install spyder=5.2.2 in anaconda prompt, but it still didn't work.

![image](https://user-images.githubusercontent.com/106008662/172032270-d7ce46c9-be81-4ea0-80d0-e6263152fbdf.png)

**Comment by ccordoba12** [comment] 2022-06-05 16:55
Hey @handsomedavid123, you need to open the Anaconda Prompt and run there the following commands:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder

Then, every time you want to start Spyder, you need to open the Anaconda Prompt again and run

    conda activate spyder-cf
    spyder
