### ISSUE TITLE
Missing spyder‑kernels -- reinstalling to no avail

### ISSUE THREAD

**Issue by DSLituiev** [spyder-ide/spyder#12709] opened 2020-05-13 04:04 UTC
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
Issue #7842  is very similar.
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am getting following after having reinstalled `spyder‑kernels` in the appropriate environment.
The spyder and python interpreter are also is in the same environment

``` 
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.1 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.
...
```

### What steps reproduce the problem?

1.  Install spyder in the base conda environment on Ubuntu 18, Python 3.7 / conda
2.  Install spyder in another non-base conda environment per [this instruction](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder)
3. Start Spyder

### What is the expected output? What do you see instead?

working console 

### Paste Traceback/Error Below (if applicable)

```python-traceback
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
```

## Versions

Python 3.7.7 64-bit | 
Qt 5.9.6 | 
PyQt5 5.9.2 | 
Linux 5.3.0-51-generic 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.3 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment] 2020-05-13 15:12
Hi @DSLituiev sorry to hear that. What version of `spyder` and `spyder-kernels` are you using in your environments? Could you provide the `conda list` output of the envs you're using? And what is the value of the selected interpreter in your preferences?

Any new info in order to understand what is happening here is greatly appreciated. Thanks!

**Comment by dalthviz** [comment] 2020-05-13 15:50
Note: Running `conda install spyder-kernels=1.9.1` in the env where the selected interpreter is located and restarting Spyder (or opening a new console) should enable a normal initialization of a kernel.

## Dependencies between Spyder and Spyder-kernels (note the patch version difference):
* Spyder `4.1.3` uses Spyder-kernels `>=1.9.1`
* Spyder `4.1.2` uses Spyder-kernels `>=1.9.0`

**Comment by DSLituiev** [comment] 2020-05-16 00:27
Hi @dalthviz , thank you for prompt response. 

python interpreter: default (same as spyder).

`conda list`:

<details>
```
# packages in environment at C:\tools\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  2020.02                  py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.12                   py37_0
anaconda-project          0.8.4                      py_0
appnope                   0.1.0                    pypi_0    pypi
argh                      0.26.2                   py37_0
asn1crypto                1.3.0                    py37_0
astroid                   2.3.3                    py37_0
astropy                   4.0              py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.1.0                   pypi_0    pypi
autopep8                  1.4.4                      py_0
awscli                    1.16.221                 pypi_0    pypi
babel                     2.8.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.5                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.1.7            py37he774522_0
beautifulsoup4            4.8.2                    py37_0
bitarray                  1.2.1            py37he774522_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               h7bd577a_0
bokeh                     1.4.0                    py37_0
boto                      2.49.0                   py37_0
botocore                  1.12.211                 pypi_0    pypi
bottleneck                1.3.2            py37h2a96729_0
bzip2                     1.0.8                he774522_0
ca-certificates           2020.1.1                      0
catalogue                 1.0.0                    pypi_0    pypi
certifi                   2019.11.28               py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
cloudpickle               1.3.0                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.3.9                    pypi_0    pypi
coloredlogs               10.0                     py37_0
comtypes                  1.1.7                    py37_0
conda                     4.8.3                    py37_0
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              2.8              py37h7a1dbc1_0
curl                      7.68.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.29.15          py37ha925a31_0
cytoolz                   0.10.1           py37he774522_0
dask                      2.11.0                     py_0
dask-core                 2.11.0                     py_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
distributed               2.11.0                   py37_0
docutils                  0.16                     py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
fastcache                 1.1.0            py37he774522_0
filelock                  3.0.12                     py_0
flake8                    3.7.9                    py37_0
flask                     1.1.1                      py_0
freetype                  2.9.1                ha9979f8_1
fsspec                    0.6.2                      py_0
future                    0.18.2                   py37_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glmnet-py                 0.1.0b2                  pypi_0    pypi
glob2                     0.7                        py_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
humanfriendly             6.1                      py37_0
hypothesis                5.5.4                      py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.2.0                      py_0
importlib_metadata        1.5.0                    py37_0
intel-openmp              2020.0                      166
intervaltree              3.0.2                      py_0
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.12.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4.1                      py_0
jedi                      0.14.1                   py37_0
jinja2                    2.11.1                     py_0
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.14.1                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.1                      py_0
jsonschema                3.2.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.2.6              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
keyring                   21.1.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.17.1               hc04afaa_0
lazy-object-proxy         1.4.3            py37he774522_0
libarchive                3.3.3                h0643e63_5
libcurl                   7.68.0               h2a8f88b_0
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
llvmlite                  0.31.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.5.0            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37h64f37c6_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
mock                      4.0.1                      py_0
more-itertools            8.2.0                      py_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
networkx                  2.4                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.3                    py37_0
numba                     0.48.0           py37h47e9c7a_0
numexpr                   2.7.1            py37h25d0782_0
numpy                     1.16.5                   pypi_0    pypi
numpy-base                1.18.1           py37hc3f5095_1
numpydoc                  0.9.2                      py_0
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py37_0
openpyxl                  3.0.3                      py_0
openssl                   1.1.1d               he774522_4
packaging                 20.1                       py_0
pandas                    1.0.1            py37h47e9c7a_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py37_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py37_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py37_0
pep8                      1.7.1                    py37_0
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    7.0.0            py37hcc1f983_0
pip                       20.0.2                   py37_1
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
psutil                    5.6.7            py37he774522_0
py                        1.8.1                      py_0
py-lief                   0.9.0            py37ha925a31_2
pyasn1                    0.4.6                    pypi_0    pypi
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.5         py37h7a1dbc1_0
pydicom                   1.3.0                      py_0    conda-forge
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.5.2                      py_0
pylint                    2.4.4                    py37_0
pymongo                   3.10.1                   pypi_0    pypi
pynacl                    1.3.0            py37h62dcd97_0
pyodbc                    4.0.30           py37ha925a31_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.15.7           py37he774522_0
pysocks                   1.7.1                    py37_0
pytables                  3.6.1            py37h1da0976_0
pytest                    5.3.5                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.8.0                      py_0
pytest-astropy-header     0.1.2                      py_0
pytest-doctestplus        0.5.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.7                   py37_0
python-libarchive-c       2.8                     py37_13
pytz                      2019.3                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1000
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3              py37he774522_0
pyzmq                     18.1.1           py37ha925a31_0
qdarkstyle                2.8                        py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.1                      py_0
qtconsole                 4.6.0                      py_1
qtpy                      1.9.0                      py_0
requests                  2.22.0                   py37_1
rope                      0.16.0                     py_0
rsa                       3.4.2                    pypi_0    pypi
rtree                     0.9.3            py37h21ff451_0
ruamel_yaml               0.15.87          py37he774522_0
s3transfer                0.2.1                    pypi_0    pypi
scikit-image              0.16.2           py37h47e9c7a_0
scikit-learn              0.22.1           py37h6288b17_0
scipy                     1.4.1            py37h9439919_0
seaborn                   0.10.0                     py_0
send2trash                1.5.0                    py37_0
setuptools                45.2.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.14.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.5                    py37_0
sphinx                    2.4.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.2.0                      py_0
spyder                    4.0.1                    py37_0
spyder-kernels            1.8.1                    py37_0
spyder-terminal           0.3.0                    py37_0    spyder-ide
sqlalchemy                1.3.13           py37he774522_0
sqlite                    3.31.1               he774522_0
statsmodels               0.11.0           py37he774522_0
sympy                     1.5.1                    py37_0
tbb                       2020.0               h74a9793_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
torch                     1.4.0+cpu                pypi_0    pypi
torchvision               0.5.0+cpu                pypi_0    pypi
tornado                   6.0.3            py37he774522_3
tqdm                      4.36.1                   pypi_0    pypi
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.25.3                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.10.2                   py37_0
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.0                      py_0
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xgboost                   1.0.2                    pypi_0    pypi
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.7                      py_0
xlwings                   0.17.1                   py37_0
xlwt                      1.3.0                    py37_0
xmltodict                 0.12.0                     py_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zict                      1.0.0                      py_0
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```
</details>

**Comment by dalthviz** [comment] 2020-05-20 13:35
Hi again @DSLituiev sorry for the late response. Could you try to update to the current release of Spyder with something like `conda install spyder=4.1.3` in all the environments you use with Spyder? Let us know if that helps :)

**Comment by james231231** [comment] 2020-05-21 09:23
Hi @dalthviz, I seem to be having the same issue here. I updated Spyder using `conda install spyder=4.1.3` which worked but then there is an error with the kernel - see image below:

![image](https://user-images.githubusercontent.com/65279092/82543450-766e1600-9b4b-11ea-8a48-bfc0ebdb23ea.png)

I followed the instructions on screen and tried to install the kernel in anaconda using `conda install spyder-kernels` but it returned the following message:

`Collecting package metadata (current_repodata.json): done`
`Solving environment: done`
`# All requested packages already installed.`

**Comment by dalthviz** [comment] 2020-05-21 15:07
Thanks for the feedback @james231231, are you using a custom path for the interpreter or you have the default one selected in your preferences?:

![image](https://user-images.githubusercontent.com/16781833/82572495-06ab5b80-9b4a-11ea-96c9-eb6f6cb678e8.png)

If you are using a custom one you will need to update the spyder-kernels version there too. Could you try to use `conda install spyder-kernels=1.9.1` in the appropriate env to check if that makes the update possible?

Let us know if that helps :)

**Comment by james231231** [comment] 2020-05-21 16:32
Thanks for your reply @dalthviz.

I was using a custom path linking to Python version 3.8 so that I could use that version of Python from within the Spyder console, as the default version with Spyder appears to be 3.7? Not sure if that is advised or whether it is best to use the default interpreter?

I have updated the kernel as you suggested and it has worked.

**Comment by dalthviz** [comment] 2020-05-21 17:05
Glad you make it work @james231231, and I think is ok to use a different version of Python in your interpreter (as long as you are not mixing mayor versions of Python i.e 2 and 3)

**Comment by ccordoba12** [comment] 2020-05-21 17:59
If you consider this one is fixed, please close it @dalthviz.

**Comment by dalthviz** [comment] 2020-05-21 19:19
Closing this since seems like enough info has been added to properly handle the `spyder-kernels` version update needed to use `spyder 4.1.3`. As a summary:

* For spyder version 4.1.3 you need `spyder-kernels >=1.9.1 and <1.10.0`
* The interpreter selected in the preference needs to meet the  spyder-kernels version requirement i.e if you use `spyder 4.1.3` the env of the selected interpreter needs to have installed `spyder-kernels 1.9.1`.
* To update spyder-kernels to the needed version for `spyder 4.1.3` you need to run (if using conda) `conda install spyder-kernels=1.9.1` in the corresponding env of the custom selected interpreter.

**Closed by dalthviz** 2020-05-21 19:19 UTC
Labels: status:Awaiting Followup

**Comment by gratzt** [comment] 2020-12-10 22:49
I ran into a similar issue, but was running the suggested version of Spyder and Spyder-Kernels in my virtual environment, see the relevant package list below. I updated Spyder-kernels to 1.9.4. Everything is working now.

spyder                     4.1.3                    py38_0
spyder-kernels         1.9.1                   py38_0

**Comment by albert-mathews** [comment] 2021-04-06 15:53
I had Pyder 4.x.x, it was working fine. but every launch, i was prompted to upgrade to 5.0.0. 

I get the problem below after doing `pip install --upgrade spyder`
![spyder kernel error](https://user-images.githubusercontent.com/80334291/113739944-46315680-96ce-11eb-88dd-95bf3d68cde1.png)

i did set the interpreter path per the instructions to C:\Users\alber\AppData\Local\Programs\Python\Python39 which is where i find python.exe

the `conda install spyder-kernels=1.9.1` help does not apply to me because I'm not using conda, and the kernel version is too old.

any help for me?

**Comment by ccordoba12** [comment] 2021-04-06 16:19
> I had spyder 4.x.x, it was working fine. but every launch, i was prompted to upgrade to 5.0.0.

You can select not showing that message again in the dialog that prompts to update. We inform users about new versions because (usually) they fix important problems present in previous ones. But it's not mandatory to update.

> I get the problem below after doing pip install --upgrade spyder

That's a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1). You can safely ignore that message for now, it's a false alarm.

**Comment by albert-mathews** [comment] 2021-04-06 16:56
thanks. i could not have hoped for better help. thank you.

**Comment by flutterq** [comment] 2021-04-12 17:12
[[solved] Spyder 5 missing dependencies - spyder_kernels version error](https://exerror.com/spyder-5-missing-dependencies-spyder-kernels-version-error/)

**Comment by ZedTDean** [comment] 2021-05-20 04:57
we are strongly with this issue, every fresh new installation with anaconda has the same issue
