### ISSUE TITLE
Just opened spyder

### ISSUE THREAD

**Issue by mscott3** [spyder-ide/spyder#21722] opened 2024-01-19 13:04 UTC
### What steps will reproduce the problem?

    conda create -n test-spyder python=3.12 spyder
    conda activate test-spyder
    spyder

console reports:
    
    fromIccProfile: failed minimal tag size sanity

paged through the demo
got this *Issue reporter* dialog

Near as I can tell, spyder is working just fine.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\MSCOTT3\AppData\Local\miniforge3\envs\test-spyder\Lib\site-packages\spyder\workers\updates.py", line 130, in start
    page.raise_for_status()
  File "C:\Users\MSCOTT3\AppData\Local\miniforge3\envs\test-spyder\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://progressive.jfrog.io/artifactory/api/conda/pgr-conda/channeldata.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSCOTT3\AppData\Local\miniforge3\envs\test-spyder\Lib\site-packages\spyder\workers\updates.py", line 157, in start
    error_msg = HTTP_ERROR_MSG.format(page.status_code)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'status_code'
```

## Versions

* Spyder version: 5.5.0  (conda)
* Python version: 3.12.1 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.21.0 (OK)
keyring >=17.0.0                 :  24.3.0 (OK)
nbconvert >=4.0                  :  7.14.2 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
paramiko >=2.4.0                 :  3.4.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.7 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.3 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.3.0 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  69.0.3 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  None (NOK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2024-01-19 15:18
Hey @mscott3, thanks for reporting. This is a duplicate of issue #21546 and it'll be fixed in our next version (5.5.1), to be released shortly.

**Closed by ccordoba12** 2024-01-19 15:18 UTC
