### ISSUE TITLE
Feature Request: Automatic Import of System Variables in Spyder

### ISSUE THREAD

**Issue by OyiboRivers** [spyder-ide/spyder#20989] opened 2023-06-01 17:15 UTC
Dear Spyder Development Team,

I am writing to request a feature enhancement in Spyder that would improve the management of environment variables within the application, specifically targeting Linux users.
The requested feature is the automatic import of system variables when launching Spyder. Currently, Spyder does not automatically import system variables defined outside of the application's environment, such as those set in the .profile or .bashrc files (Linux). This can lead to inconsistencies between the system environment and the Spyder environment.

By implementing the automatic import of system variables, Spyder would ensure a seamless integration between the user's system environment and the Spyder runtime environment. This would eliminate the need for manual configuration or duplication of settings, providing a more consistent and convenient user experience.

Spyder has a tool for user environment variables management.
Under Spyder's "Tools" > "Current user environment variables" window, users can view the user environment variables. However, it appears that under the Linux environment, this window is not editable, preventing users from adding, modifying, or deleting user environment variables within the Spyder interface.

To work around this limitation, users currently have the option to utilize the "Console Startup" feature. By navigating to "Tools" > "Preferences" > "IPython Console" > "Startup" > "Run code (lines)," users can specify custom code snippets or scripts to execute during the console startup process. This provides a workaround to import necessary environment variables or execute any required code during the console initialization.

I kindly request your consideration of this feature. If you require any further information or clarification, please feel free to reach out to me. Thank you for your attention to this matter, and I appreciate your ongoing efforts to improve Spyder.

Sincerely, Oyibo

## Versions
* Spyder version: 5.4.3  (conda)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-73-generic

**Comment by ccordoba12** [comment] 2023-06-04 18:32
Hey @OyiboRivers, thanks for reporting. This has been requested for a long time (see issue #3891), but unfortunately we haven't had time to implement it. 

I'm going to close this issue as a duplicate of #3891 but I'll ping you there to better understand why you need this functionality.

**Closed by ccordoba12** 2023-06-04 18:32 UTC
