### ISSUE TITLE
It happened after  installing anaconda. So sad....

### ISSUE THREAD

**Issue by Michaelhuagang** [spyder-ide/spyder#7011] opened 2018-04-24 03:26 UTC
File "D:\anaconda but no tensorflow\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "D:\anaconda but no tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "D:\anaconda but no tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "D:\anaconda but no tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "D:\anaconda but no tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "D:\anaconda but no tensorflow\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "D:\anaconda but no tensorflow\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "D:\anaconda but no tensorflow\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwar

**Comment by CAM-Gerlach** [comment] 2018-04-24 20:02
Thanks for reporting. This is probably a duplicate of #4958 (and its more recent reincarnation, #6319), fixed in Spyder 3.2.7, since if you just installed Anaconda you'd presumably still be running 3.2.6. Therefore, you can update Spyder by running the command ``conda update spyder`` from the Anaconda Prompt.

**Closed by CAM-Gerlach** 2018-04-24 20:02 UTC
