### ISSUE TITLE
outline view display variables and attributes

### ISSUE THREAD

**Issue by avery12** [spyder-ide/spyder#14499] opened 2020-12-24 19:46 UTC
### What steps will reproduce the problem?

Clicked on this and got this error - ctr -shift O then try to display the vars and attrbs 
BTW the outline doesn't show the functions as it did prior to 4.2

### Traceback
```python-traceback
  File "c:\users\avery\winpython\wpy64-3860\python-3.8.6.amd64\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 413, in toggle_variables
    self.update_editor(editor.info, editor)
  File "c:\users\avery\winpython\wpy64-3860\python-3.8.6.amd64\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 595, in update_editor
    update = self.update_tree(items, editor_id, language)
  File "c:\users\avery\winpython\wpy64-3860\python-3.8.6.amd64\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 626, in update_tree
    for symbol in items:
TypeError: 'NoneType' object is not iterable
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.6
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.4.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  51.1.0 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment] 2020-12-24 22:56
Hey @avery12, thanks for reporting. You said:

> Clicked on this and got this error - ctr -shift O then try to display the vars and attrbs

We'll catch and pass on that error in our next version (4.2.2), to released on mid February.

> BTW the outline doesn't show the functions as it did prior to 4.2

For that, please read our Troubleshooting Guide:

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by avery12** [comment] 2020-12-25 18:04
Thanks for the quick response- just so you know- I’m moving to pycharm- it works!

**Comment by dalthviz** [comment] 2021-01-28 18:05
Duplicate of #14413

**Closed by dalthviz** 2021-01-28 18:05 UTC
Labels: resolution:Duplicate
