### ISSUE TITLE
redundancy in keyboard shortcuts

### ISSUE THREAD

**Issue by aleksejsk** [spyder-ide/spyder#12268] opened 2020-04-10 18:59 UTC
is it possible to have redundancy in keyboard shortcuts? (i.e. use more than one shortcut for a specific Spyder command)

**Comment by jnsebgosselin** [comment] 2020-04-10 20:04
No yet. We are working on it though. Please see https://github.com/spyder-ide/spyder/pull/11694.

**Comment by ccordoba12** [comment] 2020-04-10 23:43
Let's close this one as a duplicate of the issues that PR solves.

**Closed by ccordoba12** 2020-04-10 23:43 UTC
