### ISSUE TITLE
Variable explorer doesn't show variables on remote kernel

### ISSUE THREAD

**Issue by BCArg** [spyder-ide/spyder#11538] opened 2020-02-12 10:40 UTC
### Issue Report Checklist

- [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
> did not solve the issue
- [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
- [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
> Spyder was update from 3.3.6 to 4.0.1
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
> Not console-related
* [x] Tried basic troubleshooting (if a bug/error)
    - [x] Restarted Spyder
    - [x] Reset preferences with ``spyder --reset``
    - [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    - [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Variable explorer works for a local kernel.

When connected to a remote kernel, the variables only show up in the variable explorer after I shutdown the remote kernel and connect to it again. Clicking the 'Refresh variables' did not solve the issue.

The proposed solutions described [here](https://github.com/spyder-ide/spyder/issues/7850) and [here](https://stackoverflow.com/questions/55354020/spyder-variable-explorer-does-not-show-variable-for-connected-remote-kernel) did not solve the problem

### What steps reproduce the problem?

1. Install `spyder-kernels` on both local machine and remote host
2. `python -m spyder_kernels.console` on the remote host
3. launch spyder on the local machine
1. connect to the remote host following the information from the [official documentation](python -m spyder_kernels.console)
    1. The connection works i.e. I can run and assign variables on from within the remote host using the spyder installed locally. Variables will only be displayed in the variable explorer if I restart the remote kernel
1. close the remote kernel session
1. open it again, as described above

### What is the expected output? What do you see instead?
Produced variables should be displayed on the variable explorer, on the same remote kernel session, not after restarting the remote kernel

### Paste Traceback/Error Below (if applicable)

```python-traceback

NA - no error message displayed

```

## Versions

* Spyder version: 4.0.1 (local)
* Python version: 3.7.6 (remote host) and 3.7.3 (local)
* Qt version: 5.9.7 (local and remote host)
* PyQt version: 5.9.2 (local and remote host)
* Operating System name/version: 
Ubuntu 18.04 LTS

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.0 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-02-23 03:32
What operating system is your local version of Spyder running?

**Comment by BCArg** [comment] 2020-02-24 08:07
Ubuntu 18.04.04 LTS

**Comment by ccordoba12** [comment] 2020-02-24 14:32
And are you using spyder-kernels 1.8.1 in your remote server?

**Comment by BCArg** [comment] 2020-02-24 14:51
precisely

**Comment by ccordoba12** [comment] 2020-02-24 15:06
This is not so easy to test for us, but we'll try to take a look at it as soon as we can.

**Comment by BCArg** [comment] 2020-02-24 15:08
great thanks for the feedback

**Comment by harshal-c** [comment] 2020-02-27 13:48
I'm facing a similar issue. I'm using the similar versions of packages as OP but can't see to get the remote kernel vars in the variable explorer. Would be great if someone can take a look at replicating this. Perhaps a sandbox local dockerized env which has kernel (remote) and connecting to that from spyder should replicate this issue.

**Comment by gussmith** [comment] 2020-07-22 09:24
Same here. 
I updated to latest conda and latest spyder (spyder-4.1.4). I can run local files onto a remote kernel, here a docker container (NVIDIA PyTorch). 
The Variables Explorer shows the variables when using the local IPython console, but not when using the remote console on the docker container. Real bummer, that functionality is really useful. Thanks.

**Comment by CAM-Gerlach** [comment] 2020-08-05 19:02
Hey @BCArg , can you explain exactly what steps you performed to restart the remote kernel that got the variable explorer workingl? Did you run a particular command in Spyder? Ctrl-C the kernel on the remote and start enough one? We had another user who experienced this, who tried

```python
import os; os._exit(00)
```

which restarts the kernel when run locally in Spyder, and instead it just made the console hang. Thanks!

@impact27 Any insight?

**Comment by BCArg** [comment] 2020-08-06 07:13
@CAM-Gerlach it was simply CTRL-C on the terminal where the kernel had been started

**Comment by CAM-Gerlach** [comment] 2020-08-06 18:09
Thanks @BCArg And then you started another kernel in the same terminal, reconnected and the Variable Explorer worked? Or are you saying the variable explorer only worked after the kernel was already dead?

**Comment by BCArg** [comment] 2020-08-07 06:47
the variable explorer worked after a new kernel was started, but as far as I recall, it was displaying only the variables assigned in the previous session. I am not sure whether the variables assigned in that new session were being displayed on the variable explorer

**Comment by CAM-Gerlach** [comment] 2020-08-07 15:23
Okay, thanks @BCArg . If it was displayed the previous variables, then my guess is most likely it wasn't displaying the new ones since the previous ones wouldn't have existed anymore once the kernel was killed, but I can't be sure. We appreciate your help!

**Comment by andyrevell** [comment] 2020-08-15 20:01
I am having this issue too with Spyder 4. When I connect to a remote kernel, the variable explorer is empty. When connected to a local kernel, the variable explorer is fine

Running the same code with access to the same data:
Local
![image](https://user-images.githubusercontent.com/43831513/90320570-6a0e1500-df10-11ea-9ffd-89db12014ed4.png)

Remote
![image](https://user-images.githubusercontent.com/43831513/90320576-75f9d700-df10-11ea-82ad-0f40b75a3c85.png)

**Comment by CAM-Gerlach** [comment] 2020-08-17 23:11
Yep, thanks @andyrevell . As I understand it, we've tracked down the cause and its in the queue to be fixed. @ccordoba12 or @impact27 would know more specifics on that.

**Comment by selahlynch** [comment] 2020-10-05 20:47
Do I understand correctly that "restarting the session" is NOT a solution to this problem?

**Comment by selahlynch** [comment] 2020-10-12 18:00
Does anyone know a version of spyder/spyder-kernels where the variable explorer worked with remote kernels?  I hope to downgrade to that combo until this issue is fixed.

**Comment by beanslel** [comment] 2020-11-04 07:08
> Does anyone know a version of spyder/spyder-kernels where the variable explorer worked with remote kernels? I hope to downgrade to that combo until this issue is fixed.

The variable explorer for remote kernels is broken for me from spyder version 4.0.0 and upwards. The last working version for me is spyder 3.3.6 with spyder-kernels 0.5.2. 

Any news on this bug?

**Comment by ccordoba12** [comment] 2020-11-04 21:03
We'll take a look at it in our 4.2.1 version, to be released just before Christmas.

**Comment by JDYG** [comment] 2020-11-22 12:06
Keep paying attention because I have the same problem.

**Comment by Sigmun** [comment] 2020-12-16 09:59
Please make it works. It did failed for me also. Spyder 4.2.0 running on Windows10, `python2.7 -m spyder_kernels.console --matplotlib='inline' -f=./kernel.json` running on remote CentOS7

**Comment by impact27** [comment] 2020-12-17 07:50
Maybe the comm port is blocked by the firewall? You can ge it by "get_ipython().kernel.frontend_comm.comm_port"

**Comment by impact27** [comment] 2020-12-17 10:51
I fixed it, the comm port was not tunnelled.

**Comment by ccordoba12** [comment] 2020-12-17 18:43
@impact27, thanks a lot for your help! Unfortunately, this came when we're about to release 4.2.1 tomorrow.

However, we'll review and merge your work for 4.2.2, to be released in mid February.

**Comment by selahlynch** [comment] 2021-01-15 14:54
SO EXCITED for this fix!!  Thank you @ccordoba12 @impact27

**Closed** 2021-02-14 17:17 UTC
Labels: component:IPython Console, type:Bug

**Comment by ccordoba12** [comment] 2021-02-14 17:20
Hey guys, this is finally solved and it'll be part of our 4.2.2 version, to be released in February 22nd.

Sorry that it took us so long to fix it, but we hope you enjoy this terrific improvement.

**Comment by selahlynch** [comment] 2021-02-17 16:20
Thank you!!!  Yaaaay!!! (hope you don't mind me cluttering the ticket with such a statement)

**Comment by DanteSung** [comment] 2021-02-26 03:55
> Hey guys, this is finally solved and it'll be part of our 4.2.2 version, to be released in February 22nd.
> 
> Sorry that it took us so long to fix it, but we hope you enjoy this terrific improvement.

Thanks for this useful feature. Do I have to update Spyder both on my remote server (Ubuntu) and local client(MacOS)? Currently, on my Mac it shows:
# Name                    Version                   Build  Channel
spyder                    4.1.5                    py38_0  
spyder-kernels            1.9.4                    py38_0

**Comment by ccordoba12** [comment] 2021-02-26 04:06
You need to update the Spyder version in your client (macOS) to 4.2.2 and install a compatible spyder-kernels version in your server (version 1.10.1 or 1.10.2 will do).

**Comment by DanteSung** [comment] 2021-02-26 04:47
> You need to update the Spyder version in your client (macOS) to 4.2.2 and install a compatible spyder-kernels version in your server (version 1.10.1 or 1.10.2 will do).

@ccordoba12 Thanks a lot for your quick reply. I also have another question about restarting the kernel from my remote server. 
Currently, I'm using `python -m spyder_kernels.console` to start a kernel from my server and then copy the generated `kernel-PID.json` file to my local client (macOS).

For the lack of VRAM on my graphic card, I have to restart the kernel every time I run my python script. But from the terminal, all I could do is to shut down the running kernel with `Ctrl-\` and start another one with a new `json` file and reconnect to it again, which is really time-consuming. 

Is it possible that I could restart the operating kernel directly in my remote server?

**Comment by ccordoba12** [comment] 2021-02-26 05:08
Unfortunately that's not possible at the moment, sorry.

**Comment by DanteSung** [comment] 2021-02-26 07:13
Thanks for your kind help! @ccordoba12

**Comment by CAM-Gerlach** [comment] 2021-02-26 22:01
@DanteSung Not super familiar with GPU-accelerated computation and not sure what you're using, but if its not possible to clear objects from GPU VRAM by `del`, `with` statements, `.close()` calls or dedicated commands, you could consider running your code in in sub process with Python's `multiprocessing` library, `subprocess` module or other methods and then killing that when you're done.

**Comment by DanteSung** [comment] 2021-02-27 02:10
> @DanteSung Not super familiar with GPU-accelerated computation and not sure what you're using, but if its not possible to clear objects from GPU VRAM by `del`, `with` statements, `.close()` calls or dedicated commands, you could consider running your code in in sub process with Python's `multiprocessing` library, `subprocess` module or other methods and then killing that when you're done.


@CAM-Gerlach Thanks for your help. I'm actually using PyTorch to train a neural network. I'm using `del` and `torch.cuda.empty_cache()` to free all the unneeded tensors after backpropagation, but there is always some VRAM that I cannot free 😞 and I have to restart the kernel.

**Comment by fohria** [comment] 2021-11-24 12:31
yep, same here. remote kernel is running in WSL2 on same machine, so perhaps in my case it would be fixed by #14894?

**Comment by CAM-Gerlach** [comment] 2021-11-24 18:33
Seems quite likely, thanks for the ping over there @fohria !

**Comment by Abhinav-IIRS** [comment] 2022-07-11 08:48
It works sometimes and sometimes it won't. If I reconnect to existing kernel after closing it in local client then sometimes it may show variables just prior to closing. Both Remote and Local have same Spyder (5.3.1) and spyder-kernels (2.3.1)

**Comment by ccordoba12** [comment] 2022-07-12 16:02
@Abhinav-IIRS, you can also click on the Refresh button for that:

![imagen](https://user-images.githubusercontent.com/365293/178539332-cededd36-00ff-4835-8f62-1f62d43dcde8.png)

**Comment by Abhinav-IIRS** [comment] 2022-07-13 04:47
> @Abhinav-IIRS, you can also click on the Refresh button for that:
> 
> ![imagen](https://user-images.githubusercontent.com/365293/178539332-cededd36-00ff-4835-8f62-1f62d43dcde8.png)

I tried but it does not work. Sometimes closing the kernel and reconnecting does the job.
