### ISSUE TITLE
trouble in killing infinite loop

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1203] opened 2015-02-17 17:22 UTC
_From [Eswara.A...@gmail.com](https://code.google.com/u/113167602413046981774/) on 2012-12-06T19:39:15Z_

Spyder Version:  2.1.6
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v1) 4.9.1 on Linux 

What steps will reproduce the problem?

 1.Running the attached simple program test1.py will freeze the program till the execution is completed. cntrl+c will not terminate.
The program has a wrong indentation with x = x+1 under while loop 2. 3. What is the expected output? What do you see instead? 

Please provide any additional information below

.

**Attachment:** [test1.py](http://code.google.com/p/spyderlib/issues/detail?id=1203)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1203_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:22
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:45:31Z_

**Labels:** Cat-Console MS-v2.4

**Comment by ccordoba12** [comment] 2015-07-13 05:39
Closing as duplicate of issue #1431.

**Closed by ccordoba12** 2015-07-13 05:39 UTC
Labels: 2–5 stars, bug, duplicate, Python-Console
