### ISSUE TITLE
ipython console slow response in Spyder

### ISSUE THREAD

**Issue by znadrich** [spyder-ide/spyder#7049] opened 2018-05-02 01:23 UTC
Hi,

I am attempting to use Spyder that came with my new install of Anaconda, but the ipython console within Spyder is extremely slow for anything, such as starting takes 1-2 minutes and even something such as 5+5 has a 5-10 second delay to get a response. If I run jupyter qtconsole from the Anaconda prompt, it will say kernel died a few times, but eventually start and then work normally e.g. 5+5 has an instant response.

If I do jupyter qtconsole and then connect to the .json that was created from that using the "Connect to an existing kernel" it looks like my ipython terminal in Spyder works fine, minus the variable explorer which is less than ideal.

I am using Windows 7 Enterprise

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by znadrich** [comment] 2018-05-02 14:49
I am receiving the following error when running that command

(base) C:\Users\u51pzn>conda update spyder qt pyqt
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pk
gs/msys2/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443
): Max retries exceeded with url: /pkgs/msys2/win-64/repodata.json.bz2 (Caused b
y ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407
Proxy Authentication Required',)))",),)

**Comment by ccordoba12** [comment] 2018-05-02 15:10
Are you behind a proxy?

**Comment by znadrich** [comment] 2018-05-02 15:28
Most likely, I'm unsure of the details but this is a work PC. I'm fairly new to Python, is there a way to manually update these packages?

**Comment by ccordoba12** [comment] 2018-05-02 20:15
> is there a way to manually update these packages?

No, there's no easy way to perform a manual update.

By the way, your problem could be related to restricted internet access. The thing each IPython console runs code in an external process called a kernel. And kernel communications (to send code and receive the outcome) is handled with sockets, which require to open local ports in your PC.

So perhaps your firewall and/or antivirus is interfering with that and causing the slowness you're experiencing.

**Comment by znadrich** [comment] 2018-05-04 13:35
Unfortunately it remains the same

**Comment by ccordoba12** [comment] 2018-05-04 14:18
The `python.exe` you use to start kernels.

**Comment by CAM-Gerlach** [comment] 2018-05-11 05:14
@znadrich Any updates? If we don't hear from you, we'll go ahead and close this soon. Thanks!

**Comment by CAM-Gerlach** [comment] 2018-05-15 01:59
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-05-15 01:59 UTC
Labels: status:Awaiting Followup

**Comment by SciHuber** [comment] 2018-11-30 07:33
Hi, I am using spyder 3.3.2 on mac OS and it works really slowly. It is not like this when I use previous version......

**Comment by CAM-Gerlach** [comment] 2018-11-30 07:41
Can you be more specific? What runs slowly? How long does that take? What is the relative slowdown from the previous version? Does it disappear if you downgrade again? Unfortunately we don't have any more developers on macOS to actively test this.

**Comment by SciHuber** [comment] 2018-11-30 07:46
It waits for a few seconds or longer in the console to get a command answer. It works normal when I downgrade to version 3.2.8

**Comment by CAM-Gerlach** [comment] 2018-11-30 08:41
Okay, thanks. Did 3.3.1 (and 3.3.0), the actual previous versions, also have the problem? Does downgrading to 3.2.8 change any other dependencies besides Spyder?

**Comment by SciHuber** [comment] 2018-11-30 12:40
I re-installed the anaconda and the newest spyder in it. It now seems to react very fast...... The previous versions are OK.
One problem is the "x" of besides the files name of the editor is gone..
<img width="364" alt="2018-11-30 8 37 06" src="https://user-images.githubusercontent.com/45441891/49289841-08114000-f4e0-11e8-8698-a86bd303a178.png">

**Comment by CAM-Gerlach** [comment] 2018-11-30 15:53
@SciHuber Okay, thanks. I assume some third-party dependency was updated which resulted in the primary problem being unresolved. As for that issue, that's presumably unrelated but my guess is that its an issue with the particularly third-party GUI library Spyder uses, Qt. Are you using High Sierra? Mojave? Dark mode? Only until recently was Qt properly compatible with High Sierra, and Mojave compatibility definitely isn't assured at this point, and I've heard a number of UI bugs being reported with Dark Mode and Qt. If the issue persists, open another issue about it and @ me so we can take a look. You can do so easily with ``Help > Report Issue``, and make sure to edit the issue report once its submitted to Github to add a full screenshot of the UI. Thanks!

**Comment by petermattia** [comment] 2018-12-12 01:45
Same problem for me. Not sure exactly when, but both 3.3.1 and 3.3.2 have extremely long lag times (many seconds to evaluate 1+1 in ipython). The problem existed before and after upgrading from Mojave to High Sierra. I'll probably try a full reinstall and see how that goes

**Comment by ccordoba12** [comment] 2018-12-12 06:02
@petermattia, please issue #2902 for a temporal solution.

**Comment by CAM-Gerlach** [comment] 2018-12-12 07:41
@petermattia For clarity (since that's a long thread), that being ``conda install ipykernel=4.10``.

**Comment by silveiralucas** [comment] 2019-01-08 19:09
I have started having the same problem, i.e. the IPython under Spyder takes several seconds to take any action, even 1+1. It started a week ago when I updated anaconda on High Sierra. Since my computer was already very buggy, I installed a clean version of macOS Mojave and Anaconda three days ago. The system performed ok for three days, but now I started having the same problem again.

**Comment by marcel-goldschen-ohm** [comment] 2019-01-11 18:00
Same problem here.

**Comment by ccordoba12** [comment] 2019-01-11 18:07
@marcel-goldschen-ohm, please see my comment above.

**Comment by renatoviolin** [comment] 2019-01-29 16:51
Downgrade ipykernel from 5.10 to 4.10 solved my problem here.
conda install ipykernel=4.10.

**Comment by ilkayisik** [comment] 2019-02-04 10:20
I was having a similar issue and the above suggestion [conda install ipykernel=4.10] worked for me too.

**Comment by ChristianMichelsen** [comment] 2019-02-15 10:11
Had the same problem when using a new, fresh environment with Spyder 4 (dev build). Using ipykernel=4.10 worked for me as well.

**Comment by burbanom3** [comment] 2019-03-06 18:52
I was having the same problem and sing ipykernel=4.10 solved it!

**Comment by bagardo** [comment] 2019-05-10 13:20
Had the exact same issue with the latest version, installed ipykernel=4.10 and now works like a charm!

**Comment by ChristianMichelsen** [comment] 2019-05-10 14:00
Anyone who knows why this is happening and whether or not a proper fix is on the way?

**Comment by ccordoba12** [comment] 2019-05-10 14:25
Please subscribe to issue #2902, which has the most complete discussion.

What several users have suggested is that this is only seen if you select `Automatic` as your graphics backend.

**Comment by PabloRR100** [comment] 2019-10-24 10:51
> Please update to our 3.2.8 version and try again. Also, please update Qt/PyQt to their latest version. For that, please open the Anaconda Prompt and run there
> 
> ```
> conda update spyder qt pyqt
> ```
> 
> Let us know if that fixes the problem for you.

That worked for me 100%

**Comment by xhain** [comment] 2019-10-28 16:40
This is still a thing for me - each time I update "all" I have to manually downgrade the iPython kernel via `conda install ipykernel=4.10`

**Comment by CAM-Gerlach** [comment] 2019-10-28 20:02
@xhain What OS version are you using? Did you try any of the other fixes listed here or on #2902 (esp. if you are using macOS)? What version of Spyder and Spyder-Kernels are you using?

> each time I update "all"

In general, this is not a good idea since it has a high chance of breaking things for often not much real gain. Instead, it is generally a good idea to only upgrade packages a unit when new Anaconda releases come out because these are tested to work together without major issues (with ``conda update anaconda``) other than Spyder and specific packages where there is a significant benefit to your workflow to upgrade or is needed to fix a problem, e.g. a bugfix or performance improvement in Qt/PyQt, a new feature in Pandas, etc.

**Comment by xhain** [comment] 2019-10-28 20:13
@CAM-Gerlach Thank you for the hint. I understand the problems of updating "all" and how it can break things. I usually go with seperate environments on a different machine.

OSX 10.13.6.
Spyder 3.3.6
IPython 7.8.0
Python 3.7.0

**Comment by CAM-Gerlach** [comment] 2019-10-28 20:27
@xhain Thanks. As stated in @ccordoba12 's comment right above yours, #2902 is the canonical issue and this one is closed. As you can see from that, the cause is well known (AppNap), there are multiple straightforward workarounds and it is fixed in Spyder 4. Please see that issue for more details. Thanks.

**Comment by ccordoba12** [comment] 2019-10-28 20:35
I'm locking this issue so people can see @CAM-Gerlach's answer above.
