### ISSUE TITLE
Monitor scale change detected keeps poppin up

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#11871] opened 2020-03-19 12:40 UTC
### What steps will reproduce the problem?

Monitor scale change detected keeps popping up.

<img width="529" alt="Screen Shot 2020-03-19 at 8 37 50 AM" src="https://user-images.githubusercontent.com/14086031/77068707-673ce180-69bd-11ea-823d-a6a022155743.png">

## Versions

* Spyder version: 4.1.0 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.7 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-19 15:36
Duplicate of #11846

**Comment by ccordoba12** [comment] 2020-03-19 15:37
It seems a problem with macOS only. We're investigating the issue.

**Closed by ccordoba12** 2020-03-19 15:36 UTC

**Comment by juanis2112** [comment] 2020-03-20 03:13
@ccordoba12  just submitted the same issue. (sorry about it, didn't know it was reported before) But anyways, I have the same problem

**Comment by ccordoba12** [comment] 2020-03-20 13:55
No worries, that's fine.
