### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9438] opened 2019-05-27 14:29 UTC
### What steps will reproduce the problem?

1. Use spyder to run code
2. ????
3. Error

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 271, in m_text_document__hover
    return self.hover(textDocument['uri'], position)
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 215, in hover
    return self._hook('pyls_hover', doc_uri, position=position) or {'contents': ''}
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 122, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in __call__
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/local/lib/python3.7/site-packages/pluggy/_tracing.py", line 78, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/pyls/plugins/hover.py", line 10, in pyls_hover
    definitions = document.jedi_script(position).goto_definitions()
  File "/usr/local/lib/python3.7/site-packages/jedi/api/__init__.py", line 220, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, context, leaf)
  File "/usr/local/lib/python3.7/site-packages/jedi/api/helpers.py", line 143, in evaluate_goto_definition
    return evaluator.goto_definitions(context, leaf)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 240, in goto_definitions
    return helpers.evaluate_call_of_leaf(context, name)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/helpers.py", line 77, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "/usr/local/lib/python3.7/site-packages/jedi/_compatibility.py", line 274, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/base_context.py", line 162, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/usr/local/lib/python3.7/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/usr/local/lib/python3.7/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/filters.py", line 102, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 555, in tree_name_to_contexts
    types = _remove_statements(evaluator, context, node, tree_name)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 497, in _remove_statements
    return eval_expr_stmt(context, stmt, seek_name=name)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 284, in eval_expr_stmt
    return _eval_expr_stmt(context, stmt, seek_name)
  File "/usr/local/lib/python3.7/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 300, in _eval_expr_stmt
    context_set = context.eval_node(rhs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 146, in eval_node
    return eval_or_test(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 357, in eval_or_test
    context.eval_node(right))
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/usr/local/lib/python3.7/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 85, in eval_node
    context_set = eval_atom(context, first_child)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 262, in eval_atom
    context = iterable.SequenceLiteralContext(context.evaluator, context, atom)
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/context/iterable.py", line 293, in __init__
    self.array_type = SequenceLiteralContext.mapping[atom.children[0]]
WARNING:traitlets:kernel died: 18.000514030456543
WARNING:traitlets:kernel died: 18.00384783744812
WARNING:traitlets:kernel died: 17.99958038330078
WARNING:traitlets:kernel died: 18.002798795700073
WARNING:traitlets:kernel died: 18.004103899002075
WARNING:traitlets:kernel died: 18.00445795059204
```

## Versions

* Spyder version: 4.0.0.dev0 5e53214cb
* Python version: 3.7.3
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Darwin 18.5.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.5 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.5.0  :  4.5.0.dev0 (NOK)
IPython >=4.0      :  7.3.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-05-27 14:32
What object were you hovering when this happened?

**Comment by impact27** [comment] 2019-05-27 15:07
most likely the editor

**Comment by ccordoba12** [comment] 2019-05-27 15:13
I meant, what object name in your code you put the mouse on top of that generated this traceback. For instance, you could have in the editor

```python
import numpy as np
np.arange
```

and when you put the mouse over `arange` you got the error.

We need the object name to replicate this error in our end. Else, we can't fix this problem.

**Comment by goanpeca** [comment] 2019-05-27 15:45
@ccordoba12 when user request info (`Ctrl+I`) internally we are calling hover, so it does not necessarily mean the user was actually hovering.

**Comment by ccordoba12** [comment] 2019-05-27 15:57
Right, I forgot about it. The error could be caused by either actual hovering or `Ctrl+I`.

**Comment by ccordoba12** [comment] 2019-06-03 07:49
@impact27, what if you run

    spyder --reset

? Does that fix this error?

**Comment by impact27** [comment] 2019-06-03 08:10
I can't reproduce the error. I just posted the trackback in the hope it would be useful for someone to understand. I will let you know if I notice a pattern, but these errors are quite infrequent (1 / week).

**Comment by ccordoba12** [comment] 2019-06-10 08:21
This is a problem with Jedi being unable to parse the file ast at some point.

We have a reproducible error at issue #9492 so I'm closing this one in favor of that one.

**Closed by ccordoba12** 2019-06-10 08:21 UTC
Labels: status:Awaiting Followup
