### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by karimnorouzi** [spyder-ide/spyder#4600] opened 2017-06-13 14:01 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. code folding is missing

2.  code folding is missing
3.  code folding is missing..
I really cant understand why there is no code folding in the spyder. it is such an important feature. plz
 fold code.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-06-13 14:14
Code folding is *not* missing :-) It's already working in our master branch and it'll be part of Spyder 4.

Closing as a duplicate of issue #706.

**Closed by ccordoba12** 2017-06-13 14:14 UTC
Labels: resolution:Duplicate

**Comment by JohnRobson** [comment] 2019-11-23 02:56
I'm using Spyder 4.0.0.dev0 and Code Folding Disappeared...
