### ISSUE TITLE
can not open spyder

### ISSUE THREAD

**Issue by solueverest** [spyder-ide/spyder#7050] opened 2018-05-02 05:37 UTC
### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:
* Python:
* Qt:
* PyQt:
* Operating System:

### Dependencies

```
PASTE DEPENDENCIES HERE
```
Traceback (most recent call last):
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3126, in main
mainwindow = run_spyder(app, options, args)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3023, in run_spyder
main.setup()
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1182, in setup
self.setup_layout(default=False)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1452, in setup_layout
self.setup_default_layouts('default', settings)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1628, in setup_default_layouts
widget.toggle_view(True)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
self.create_new_client(give_focus=False)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
self.connect_client_to_kernel(client)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1059, in connect_client_to_kernel
stderr_file)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1477, in create_kernel_manager_and_kernel_client
config=None, autorestart=True)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 958, in __new__
inst.setup_instance(*args, **kwargs)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 986, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 977, in setup_instance
value.instance_init(self)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1691, in instance_init
self._resolve_classes()
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1696, in _resolve_classes
self.klass = self._resolve_string(self.klass)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1507, in _resolve_string
return import_item(string)
File "/home/tesla/anaconda3/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 34, in import_item
module = __import__(package, fromlist=[obj])
File "/home/tesla/anaconda3/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "/home/tesla/anaconda3/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 28, in 
datetime.strptime("1", "%d")
File "/home/tesla/anaconda3/lib/python3.6/_strptime.py", line 280, in 
_TimeRE_cache = TimeRE()
File "/home/tesla/anaconda3/lib/python3.6/_strptime.py", line 194, in __init__
self.locale_time = LocaleTime()
File "/home/tesla/anaconda3/lib/python3.6/_strptime.py", line 72, in __init__
self.lang = _getlang()
File "/home/tesla/anaconda3/lib/python3.6/_strptime.py", line 31, in _getlang
return locale.getlocale(locale.LC_TIME)
File "/home/tesla/anaconda3/lib/python3.6/locale.py", line 581, in getlocale
return _parse_localename(localename)
File "/home/tesla/anaconda3/lib/python3.6/locale.py", line 490, in _parse_localename
raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: bho_NP

**Comment by ccordoba12** [comment] 2018-05-02 14:09
This is a duplicate of issue #7051.

**Closed by ccordoba12** 2018-05-02 14:09 UTC
