### ISSUE TITLE
NameError: name 'Schema' is not defined

### ISSUE THREAD

**Issue by TMCG123** [spyder-ide/spyder#14924] opened 2021-03-13 08:52 UTC
### What steps will reproduce the problem?

from marshmallow import Schema resulted in this error
marshmallow is in the environment.

### Traceback
```python-traceback
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'fbfda83683d611eb97537071bc175aa3'
ERROR:traitlets:Exception in comm_msg for fbfda83683d611eb97537071bc175aa3
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'fbfda83683d611eb97537071bc175aa3'
ERROR:traitlets:Exception in comm_msg for fbfda83683d611eb97537071bc175aa3
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'fbfda83683d611eb97537071bc175aa3'
ERROR:traitlets:Exception in comm_msg for fbfda83683d611eb97537071bc175aa3
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Hp\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'fbfda83683d611eb97537071bc175aa3'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  54.0.0 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment] 2021-03-13 17:15
Hey @TMCG123, thanks for reporting. This is a duplicate of issue #14886 and we're trying to understand how to fix it.

**Closed by ccordoba12** 2021-03-13 17:15 UTC
