### ISSUE TITLE
Spyder 4.1.5 not showing yellow/red warning marks

### ISSUE THREAD

**Issue by adrienchaton** [spyder-ide/spyder#13746] opened 2020-09-09 17:08 UTC
Hello,

I updated to Spyder 4.1.5 and now I cannot have yellow warning marks, such as when a variable has not been declared inside a function.

I run it inside a virtual environment, with Python 3.7.9 and IPython 7.18.1, with previous Spyder it worked and stopped working with the new version .. I tried to change the checked options in the "source" tab or to change settings but I cannot get back these warnings.

Any idea please ?

**Comment by dalthviz** [comment] 2020-09-09 20:00
Hi @adrienchaton checking this in an env with Python 3.7.9, IPython 7.18.1 and Spyder 4.1.5 on Windows I was able to see the warning marks (although in the case of the example you describe what I see is a red error mark):

![warnings](https://user-images.githubusercontent.com/16781833/92646448-12af5a80-f2ac-11ea-9263-f475d6f449a8.png)

Just in case this is the list of packages in my testing env:

<details>


```
# packages in environment at C:\Users\Daniel\Anaconda3\envs\s4.1.5:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
argh                      0.26.2                   py37_0
astroid                   2.4.2                    py37_0
atomicwrites              1.4.0                      py_0
attrs                     20.1.0                     py_0
autopep8                  1.5.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
bcrypt                    3.2.0            py37he774522_0
bleach                    3.1.5                      py_0
brotlipy                  0.7.0           py37he774522_1000
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py37_0
cffi                      1.14.2           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
cloudpickle               1.6.0                      py_0
colorama                  0.4.3                      py_0
cryptography              3.1              py37h7a1dbc1_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
flake8                    3.8.3                      py_0
future                    0.18.2                   py37_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.18.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
isort                     5.4.2                    py37_0
jedi                      0.17.1                   py37_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py37_1
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
keyring                   21.4.0                   py37_0
lazy-object-proxy         1.4.3            py37he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
markupsafe                1.1.1            py37hfa6e2cd_1
mccabe                    0.6.1                    py37_1
mistune                   0.8.4           py37hfa6e2cd_1001
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
numpydoc                  1.1.0                      py_0
openssl                   1.1.1g               he774522_1
packaging                 20.4                       py_0
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathtools                 0.1.2                      py_1
pexpect                   4.8.0                    py37_1
pickleshare               0.7.5                 py37_1001
pip                       20.2.2                   py37_0
pluggy                    0.13.1                   py37_0
prompt-toolkit            3.0.7                      py_0
psutil                    5.7.2            py37he774522_0
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pylint                    2.6.0                    py37_0
pynacl                    1.4.0            py37h62dcd97_1
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.16.0           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py37_0
pytz                      2020.1                     py_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1001
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.6                      py_0
qtpy                      1.9.0                      py_0
requests                  2.24.0                     py_0
rope                      0.17.0                     py_0
rtree                     0.9.4            py37h21ff451_1
setuptools                49.6.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.2.2                      py_0
sphinx                    3.2.1                      py_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.1.5                    py37_0
spyder-kernels            1.9.4                    py37_0
sqlite                    3.33.0               h2a8f88b_0
testpath                  0.4.4                      py_0
toml                      0.10.1                     py_0
tornado                   6.0.4            py37he774522_1
traitlets                 4.3.3                    py37_0
typed-ast                 1.4.1            py37he774522_0
ujson                     1.35             py37hfa6e2cd_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py37_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.35.1                     py_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
wrapt                     1.11.2           py37he774522_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4

```

</details>

Could you provide a more detailed description of your specs (OS, dependencies, etc.) and a code example of the issue? From what version of Spyder you did the update? Also, did you check if the `Preferences > Completion and linting > Linting > Enable basic linting` option is checked?

![image](https://user-images.githubusercontent.com/16781833/92646793-936e5680-f2ac-11ea-897e-7d2e040a0d2c.png)

Maybe our [Basic first aid steps](https://docs.spyder-ide.org/current/basic-first-aid.html) could be useful here

Let us know if the info above helps :)

**Comment by adrienchaton** [comment] 2020-09-09 20:40
Hi @dalthviz 

Thank you for checking up and answering.

I had enabled "Enable basic linting".
I tried reseting spyder and updating its dependencies as proposed in the first aid.
Restarting spyder, and still the error marks yellow or red don't appear.

I just do the same code as you, on purpose calling undeclared variables. Running the script naturally throws the error, though the warning marks don't show up.

I am on MacOS 10.12.6 and I use pip to to install package, the freeze yields:

alabaster==0.7.12
appdirs==1.4.4
applaunchservices==0.2.1
appnope==0.1.0
astroid==2.4.2
atomicwrites==1.4.0
attrs==20.2.0
audioread==2.1.8
autopep8==1.5.4
Babel==2.8.0
backcall==0.2.0
bleach==3.1.5
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
cloudpickle==1.6.0
crepe==0.0.11
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20200713
docutils==0.16
entrypoints==0.3
flake8==3.8.3
future==0.18.2
h5py==2.10.0
helpdev==0.7.1
hmmlearn==0.2.3
idna==2.10
imageio==2.9.0
imagesize==1.2.0
importlib-metadata==1.7.0
intervaltree==3.1.0
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
isort==5.5.1
jedi==0.17.1
Jinja2==2.11.2
joblib==0.16.0
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.6.3
keyring==21.4.0
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
librosa==0.8.0
llvmlite==0.34.0
MarkupSafe==1.1.1
matplotlib==3.3.1
mccabe==0.6.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.7
nnAudio==0.1.1
numba==0.51.2
numpy==1.19.1
numpydoc==1.1.0
packaging==20.4
pandocfilters==1.4.2
parso==0.7.0
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
pluggy==0.13.1
pooch==1.1.1
prompt-toolkit==3.0.7
psutil==5.7.2
ptyprocess==0.6.0
PyAudio==0.2.11
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==5.1.1
pyflakes==2.2.0
Pygments==2.6.1
pylint==2.6.0
pyobjc==6.2.2
pyobjc-core==6.2.2
pyobjc-framework-Accounts==6.2.2
pyobjc-framework-AddressBook==6.2.2
pyobjc-framework-AppleScriptKit==6.2.2
pyobjc-framework-AppleScriptObjC==6.2.2
pyobjc-framework-ApplicationServices==6.2.2
pyobjc-framework-Automator==6.2.2
pyobjc-framework-AVFoundation==6.2.2
pyobjc-framework-AVKit==6.2.2
pyobjc-framework-CalendarStore==6.2.2
pyobjc-framework-CFNetwork==6.2.2
pyobjc-framework-CloudKit==6.2.2
pyobjc-framework-Cocoa==6.2.2
pyobjc-framework-Collaboration==6.2.2
pyobjc-framework-Contacts==6.2.2
pyobjc-framework-ContactsUI==6.2.2
pyobjc-framework-CoreAudio==6.2.2
pyobjc-framework-CoreAudioKit==6.2.2
pyobjc-framework-CoreBluetooth==6.2.2
pyobjc-framework-CoreData==6.2.2
pyobjc-framework-CoreLocation==6.2.2
pyobjc-framework-CoreMedia==6.2.2
pyobjc-framework-CoreMediaIO==6.2.2
pyobjc-framework-CoreServices==6.2.2
pyobjc-framework-CoreText==6.2.2
pyobjc-framework-CoreWLAN==6.2.2
pyobjc-framework-CryptoTokenKit==6.2.2
pyobjc-framework-DictionaryServices==6.2.2
pyobjc-framework-DiscRecording==6.2.2
pyobjc-framework-DiscRecordingUI==6.2.2
pyobjc-framework-DiskArbitration==6.2.2
pyobjc-framework-DVDPlayback==6.2.2
pyobjc-framework-EventKit==6.2.2
pyobjc-framework-ExceptionHandling==6.2.2
pyobjc-framework-FinderSync==6.2.2
pyobjc-framework-FSEvents==6.2.2
pyobjc-framework-GameCenter==6.2.2
pyobjc-framework-GameController==6.2.2
pyobjc-framework-GameKit==6.2.2
pyobjc-framework-GameplayKit==6.2.2
pyobjc-framework-ImageCaptureCore==6.2.2
pyobjc-framework-IMServicePlugIn==6.2.2
pyobjc-framework-InputMethodKit==6.2.2
pyobjc-framework-InstallerPlugins==6.2.2
pyobjc-framework-InstantMessage==6.2.2
pyobjc-framework-Intents==6.2.2
pyobjc-framework-IOSurface==6.2.2
pyobjc-framework-iTunesLibrary==6.2.2
pyobjc-framework-LatentSemanticMapping==6.2.2
pyobjc-framework-LaunchServices==6.2.2
pyobjc-framework-libdispatch==6.2.2
pyobjc-framework-LocalAuthentication==6.2.2
pyobjc-framework-MapKit==6.2.2
pyobjc-framework-MediaAccessibility==6.2.2
pyobjc-framework-MediaLibrary==6.2.2
pyobjc-framework-MediaPlayer==6.2.2
pyobjc-framework-MediaToolbox==6.2.2
pyobjc-framework-Metal==6.2.2
pyobjc-framework-MetalKit==6.2.2
pyobjc-framework-ModelIO==6.2.2
pyobjc-framework-MultipeerConnectivity==6.2.2
pyobjc-framework-NetFS==6.2.2
pyobjc-framework-NetworkExtension==6.2.2
pyobjc-framework-NotificationCenter==6.2.2
pyobjc-framework-OpenDirectory==6.2.2
pyobjc-framework-OSAKit==6.2.2
pyobjc-framework-Photos==6.2.2
pyobjc-framework-PhotosUI==6.2.2
pyobjc-framework-PreferencePanes==6.2.2
pyobjc-framework-PubSub==6.2.2
pyobjc-framework-QTKit==6.2.2
pyobjc-framework-Quartz==6.2.2
pyobjc-framework-SafariServices==6.2.2
pyobjc-framework-SceneKit==6.2.2
pyobjc-framework-ScreenSaver==6.2.2
pyobjc-framework-ScriptingBridge==6.2.2
pyobjc-framework-SearchKit==6.2.2
pyobjc-framework-Security==6.2.2
pyobjc-framework-SecurityFoundation==6.2.2
pyobjc-framework-SecurityInterface==6.2.2
pyobjc-framework-ServiceManagement==6.2.2
pyobjc-framework-Social==6.2.2
pyobjc-framework-SpriteKit==6.2.2
pyobjc-framework-StoreKit==6.2.2
pyobjc-framework-SyncServices==6.2.2
pyobjc-framework-SystemConfiguration==6.2.2
pyobjc-framework-VideoToolbox==6.2.2
pyobjc-framework-WebKit==6.2.2
pyparsing==2.4.7
PyQt5==5.12.3
PyQt5-sip==12.8.1
PyQtWebEngine==5.12.1
pyrsistent==0.17.1
python-dateutil==2.8.1
python-jsonrpc-server==0.4.0
python-language-server==0.34.1
python-osc==1.7.4
pytz==2020.1
pyworld==0.2.11.post0
pyzmq==19.0.2
QDarkStyle==2.8.1
QtAwesome==0.7.2
qtconsole==4.7.7
QtPy==1.9.0
requests==2.24.0
resampy==0.2.2
rope==0.17.0
scikit-learn==0.23.2
scipy==1.5.2
six==1.15.0
snowballstemmer==2.0.0
sortedcontainers==2.2.2
SoundFile==0.10.3.post1
Sphinx==3.2.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==4.1.5
spyder-kernels==1.9.4
testpath==0.4.4
threadpoolctl==2.1.0
toml==0.10.1
torch==1.6.0
torchvision==0.7.0
tornado==6.0.4
traitlets==5.0.4
typed-ast==1.4.1
ujson==1.35
urllib3==1.25.10
watchdog==0.10.3
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.12.1
wurlitzer==2.0.1
yapf==0.30.0
zipp==3.1.0

**Comment by dalthviz** [comment] 2020-09-09 22:10
Thanks for the info @adrienchaton that's quite strange, are you being able to see any side panel in the Editor (line numbers, debug, etc?) Maybe some how Qt is not rendering the side panels of the Editor? Could you try to create an env with only Spyder to see if the behavior persists?

**Comment by ccordoba12** [comment] 2020-09-10 01:12
> python-jsonrpc-server==0.4.0

The problem is with this version. Please downgrade to version 0.3.4 of that package and try again.

On a side note. this is why we *strongly* recommend to use Anaconda instead of pip, i.e. because Anaconda packages are more curated than pip ones. So unless you have a strong reason to not use Anaconda, you should definitely switch to it.

**Comment by adrienchaton** [comment] 2020-09-10 08:04
Thank you @ccordoba12 and @dalthviz !

Downgrading to python-jsonrpc-server==0.3.4 fixed the issue, now warnings are shown on the side of the editor.
Besides this issue with upgrading spyder, I am very satisfied with virtualenv so I would like to keep it.

And good job for version 4, the ipython console is much faster, the black appearance is good too !

**Comment by ccordoba12** [comment] 2020-09-10 12:14
Thanks for your kind words @adrienchaton!

I'm closing this issue since your problem is fixed now.

**Closed by ccordoba12** 2020-09-10 12:14 UTC
Labels: status:Awaiting Followup
