### ISSUE TITLE
Not getting correct output in Python console

### ISSUE THREAD

**Issue by abhisheksingh-in** [spyder-ide/spyder#3537] opened 2016-10-14 07:22 UTC
## Description

**What steps will reproduce the problem?**

_1. When running the program-_
str1 = 'hello'
str2 = ','
str3 = 'world'

print(str1)

print(str1[0])
**What is the expected output? What do you see instead?**
hello
h
BUT I AM SEEING 
hell>>> o
h
**Please provide any additional information below**
last letter of str1 is not coming together

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 2.7.12
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2016-10-14 23:34
The Python console is broken at the moment on Windows. Please use the IPython console instead :-)

Closing this as a duplicate of issue #3533 because it's more or less the same bug.

**Closed by ccordoba12** 2016-10-14 23:34 UTC
