### ISSUE TITLE
Unchecking "Check for new versions on startup" is not remembered

### ISSUE THREAD

**Issue by mghansen256** [spyder-ide/spyder#16466] opened 2021-09-21 19:05 UTC
### What steps will reproduce the problem?

1. Start Spyder
2. Spyder shows a dialog box "A new version is available"
3. Uncheck "Check for new versions on startup"
4. Re-start Spyder
5. Dialog box is shown again, with "Check for new versions on startup" still checked.

Expected behavior: Spyder should not check for updates.

The actual wording of the checkbox may be different, but I already closed the dialog box.

Version: 5.1.5
Python 3.8.10 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Linux 5.8.0-63-generic 
Installed via pip

**Comment by dalthviz** [comment] 2021-09-22 09:13
Hi @mghansen256 thank you for the feedback! I was able to reproduce this with the Windows installer too. For the moment, you can uncheck the preference with the Preference dialog (`Preferences > Application > Advanced settings > Check for updates on start up`). Let us know if that helps :)

**Comment by angelasofiaremolinagutierrez** [comment] 2023-02-19 03:03
I found the error:
the `spyder.ini` configuration file does not change the `check_updates_on_startup` option to False, it always stays True, see the following video:

https://user-images.githubusercontent.com/10239480/219907147-7f8d959f-b77d-491f-8908-3855da94bc4f.mp4

But when trying to reproduce this error in the development environment, the bug does not occur. The option **DOES** change to False.

https://user-images.githubusercontent.com/10239480/219906424-23e9377d-634c-4c16-9aef-81c68debc365.mp4

In order for the message to appear on the screen, there must be a new version of Spyder available, so the only thing I changed in my branch were those conditions, so the dialog box could pop up. You can see it in this [commit](https://github.com/angelasofiaremolinagutierrez/spyder/commit/baa398280ecb24cfc11f2056c85bdcf7f716de21) of my branch

This doesn't solve the bug, but I'm not able to reproduce it in development environment. @dalthviz I would like to ask you if there is a way to generate an executable file out of a branch to add some custom debug logs in the version where the bug occurs and also to make sure if the bug occurs only when its's not running in develop mode. I will also try to implement a pytest test, to assert that the file is being written with 'False' when the box is unchecked.

**Comment by dalthviz** [comment] 2023-02-20 16:10
Thank you @angelasofiaremolinagutierrez for all the effort checking this! Regarding generating an executable, I think you could submit a PR here using your branch adding there the debugging logs you mentioned and also changing the Spyder version to be for example 5.4.1 by changing this line: 

https://github.com/angelasofiaremolinagutierrez/spyder/blob/baa398280ecb24cfc11f2056c85bdcf7f716de21/spyder/__init__.py#L31-L33

to be able to trigger the dialog without having to change the validation lines or the worker code.

When submitting a PR a Github Action will generate a Windows installer that you can download from the action artifacts:

![image](https://user-images.githubusercontent.com/16781833/220151142-53171788-035d-4390-8db5-100fbfef9b0f.png)

Clicking `details` should take you to a page where a `Summary` button is available and clicking that you should be able to find the generated artifacts/Windows installers:

![image](https://user-images.githubusercontent.com/16781833/220151867-0ec09f11-8499-4660-804a-425a023f9c05.png)

Adding some sort of test for this functionality sounds like a great idea :+1:

Also, could you check if with Spyder latest release (Spyder 5.4.2) you can reproduce this? I think you tested with 5.1.5 but since you can reproduced it when launching from develop mode maybe this was fixed already somehow? For that you will need to create a new conda environment using the conda-forge channel. Something like the following from an Anaconda prompt should work to create the env and launch Spyder from it: 

```
conda create -n spyder-cf python=3.9 spyder=5.4.2
conda activate spyder-cf
spyder
```

Thank you again for taking the time to check this and if you have any other question let us know!

**Comment by angelasofiaremolinagutierrez** [comment] 2023-02-21 04:25
Thank you @dalthviz for your answer, it was really helpful! 
I could not change the `version_info` variable as you suggested to, because when I tried to run it changing it, the 'New Spyder version' dialog did **not** showed up. And then when I clicked in `help > check for updates...` option, it resulted in a dialog box saying "Spyder is up to date.". I think to check this I have to change the function 'check_updates' so I just left the commit as I showed you before, to test it like that.

I have submitted the PR to generate the installer. It needs aproval from one of the maintainers to do the checks
![image](https://user-images.githubusercontent.com/10239480/220244914-73110e4a-a203-4bd0-b0fa-da2b9d790b37.png)
Could you please aprove it? #20570

And about this:
> Also, could you check if with Spyder latest release (Spyder 5.4.2) you can reproduce this? From your videos seems like you tested with 5.1.5 but since you can reproduced it when launching from develop mode maybe this was fixed already somehow? For that you will need to create a new conda environment using the conda-forge channel. Something like the following from an Anaconda prompt should work to create the env and launch Spyder from it:

I didn't test it with the latest release, because for the dialog to show up it needs to be a newer release out.

**Comment by jitseniesen** [comment] 2023-02-21 09:01
> Could you please aprove it?

@angelasofiaremolinagutierrez I approved it, everything is running now.

**Comment by angelasofiaremolinagutierrez** [comment] 2023-02-21 13:09
Thank you! @jitseniesen 
The bug does not reproduce with the installer either. Maybe @dalthviz is right and the bug was some how fixed from 5.1.5 to 5.4.2. I would like to make sure is truly fixed but I don't know how to test it because of what I said earlier:

> I didn't test it with the latest release, because for the dialog to show up, there must be a newer version out.

Do you have any ideas?

**Comment by dalthviz** [comment] 2023-02-21 20:10
> I didn't test it with the latest release, because for the dialog to show up, there must be a newer version out.

Totally right! Sorry for the confussion there 😅 Could you check with Spyder 5.4.1 please? With that the dialog should trigger in the same way as when you tested with Spyder 5.1.5 @angelasofiaremolinagutierrez

**Comment by angelasofiaremolinagutierrez** [comment] 2023-02-21 22:25
I just tested it with Spyder 5.4.1, you were right, this is already solved. The bug did not reproduce. I think this issue can be closed @dalthviz 

https://user-images.githubusercontent.com/10239480/220472334-0b7ead38-61fe-4f33-a0fd-b9e2952ed478.mp4

**Comment by dalthviz** [comment] 2023-02-21 22:35
Awesome! Thank you so much again @angelasofiaremolinagutierrez for all your help checking this issue! I will close it then :+1:

**Closed by dalthviz** 2023-02-21 22:35 UTC
Labels: type:Bug, resolution:Completed
