### ISSUE TITLE
problem of Spyder

### ISSUE THREAD

**Issue by dsammy** [spyder-ide/spyder#6877] opened 2018-04-01 06:41 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "f:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "f:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "f:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "f:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1044, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "f:\ProgramData\Anaconda3\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "f:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 209, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "f:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\client.py", line 141, in shell_channel
    socket = self.connect_shell(identity=self.session.bsession)
  File "f:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 516, in connect_shell
    r

**Comment by ccordoba12** [comment] 2018-04-01 16:38
This problem is fixed in our latest version (3.2.8). Please update by opening the Anaconda prompt and running there

    conda update spyder

**Closed by ccordoba12** 2018-04-01 16:38 UTC

**Comment by CAM-Gerlach** [comment] 2018-04-01 17:54
For reference, this is an apparent duplicate of #4958 (and its more recent reincarnation, #6319), fixed in Spyder 3.2.7.
