### ISSUE TITLE
Some package update makes Spyder unable to connect to iPython console

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#6453] opened 2018-02-14 11:12 UTC
## Description of your problem

Today I updated 35 Python packages using Anaconda Navigator. Afterwards Spyder was unable to connect to the iPython console, it would get stuck with the "Connecting to kernel..." message. No crashes, no error messages. After I rolled back all packages the problem disappeared.

I did not test each of the 35 libraries I updated, I can only say that the problem didn't seem to be caused by:

- curl
- libcurl
- jupyterlab
- pyopengl
- pywinpty

That leaves one of the following 30 libraries as the possible culprit:

- anaconda-client
- astroid
- astropy
- ca-certificates
- conda
- conda-build
- coverage
- dask
- dask-core
- distributed
- gensim
- greenlet
- hypothesis
- menuinst
- notebook
- numba
- numpy
- olefile
- openpyxl
- orange3
- pylint
- pytest
- pytz
- pyzmq
- setuptools
- sphinx
- sqlite
- terminado
- typing
- xlwings

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.4
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

EDIT: I took the dependencies AFTER I downgraded the aforementioned libraries.

**Comment by Jerry-kiwi** [comment] 2018-02-14 17:10
https://github.com/spyder-ide/spyder/issues/6452
just the same
I've  overcomed problem by swithing graphics mode to TK

**Comment by ccordoba12** [comment] 2018-02-15 12:59
Closing as a duplicate of #6452. @Khris777, I'll let you know there the cause of this problem.

**Closed by ccordoba12** 2018-02-15 12:59 UTC

**Comment by marynabort** [comment] 2020-08-13 22:24
How did you roll back all the packages?
