### ISSUE TITLE
Some shortcuts changes don't work in 3.0b2

### ISSUE THREAD

**Issue by AlexLuya** [spyder-ide/spyder#2951] opened 2016-01-24 04:07 UTC
Ubuntu 14.04 64bit + Spyder 3.0b2 is used in my laptop,and I have asked a question about shortcut in v2.3.8 here:https://github.com/spyder-ide/spyder/issues/2947.
      With 3.0b2,some change works,for example,change tagcomments to "ctrl+/" works,but change

          Code completion............... to..........'shift+space'............................still,blank space got input
          Save all..............................to...........'ctrl+s'.....................................nothing happened after press this combination within editor

**Comment by jitseniesen** [comment] 2016-01-24 16:54
@AlexLuya regarding the "Save all" short cut, can you please check that after you change the shortcut, when you press Ctrl+S and nothing happens, the "Save all" item in the "File" menu does work?

I cannot reproduce the "Save all", but I did find something strange. "Save all" seems to be disabled if you have only one file open, whether you have edited that file or not. The code for this is https://github.com/spyder-ide/spyder/blob/master/spyderlib/plugins/editor.py#L1339 which seems pretty deliberate and long standing. However, I find this quite unexpected.

Regarding the "code completion" part, I can reproduce it but it seems to be specific to "shift+space". If you change it to something else (I tried Ctrl+Alt+C) it does work.

**Comment by ccordoba12** [comment] 2016-01-24 20:16
@AlexLuya, you can't easily reassign a current shortcut to another action, as it was reported on issue #2941 (Ctrl+S is used to save the current file). That's a problem that will be solved before 3.0 is finally released.

----

@jitseniesen:

> "Save all" seems to be disabled if you have only one file open, whether you have edited that file or not

You can submit a pull request if you want to change that :-) I didn't know that was the case because I never use "Save all".

> Regarding the "code completion" part, I can reproduce it but it seems to be specific to "shift+space"

Yes, that's the problem. i don't think Shift+escape could work as a shortcut.

**Comment by ccordoba12** [comment] 2016-01-24 20:17
I'm closing this issue as a duplicate of issue #2941 because it's very similar to it.

**Closed by ccordoba12** 2016-01-24 20:17 UTC
