### ISSUE TITLE
python crashed when I clicked open file button in spyder3

### ISSUE THREAD

**Issue by yipukangda** [spyder-ide/spyder#3602] opened 2016-10-26 08:59 UTC
## Description

python crashed when I clicked open file button in spyder3
**What steps will reproduce the problem?**
1. load spyder
2. click the open file button

**What is the expected output? What do you see instead?**
I want to open file manger and load a script but python crashed immediately.

**Please provide any additional information below**
I can still run script form "%run" command.
## Version and main components
- Spyder Version: 3.0.1 
- Python Version: 3.5.2
- Qt Versions: 5.6.0, PyQt5 5.6 on Windows 10
## Dependencies

```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2016-10-26 16:15
@spyder-ide/junior-developers, someone has a Windows 10 computer/VM to test this issue?

**Comment by malliwi88** [comment] 2016-10-26 21:05
Hi @yipukangda, What Win10 version do you have? 32 or 64 bits??

**Comment by yipukangda** [comment] 2016-10-27 02:10
@malliwi88 64 bits

**Comment by stonebig** [comment] 2016-10-28 16:57
I have no issue on Win10 64bit, Q
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

and PyQt5 (5.7), current 3.0.2-pre version

**Comment by malliwi88** [comment] 2016-10-31 02:46
Yeah!!! @ccordoba12 
I didn't have any problem on my win10 (64bits) machine.

I think you must check your anaconda, @yipukangda

**Comment by yipukangda** [comment] 2016-10-31 02:58
@malliwi88 I have tried to reinstall anaconda and check it again, but it still remained. 
But thanks anyway, I will try on another computer.

**Comment by malliwi88** [comment] 2016-10-31 03:21
@yipukangda 

How you remove anaconda? You use remove programs tool on windows or removing Anaconda directory directly?

**Comment by yipukangda** [comment] 2016-10-31 03:36
@malliwi88 I used remove programs tool

**Comment by malliwi88** [comment] 2016-10-31 03:46
@yipukangda

If you remember the path where Anaconda was installed, please find and remove it manually

And try again installing anaconda and spyder.

**Comment by yipukangda** [comment] 2016-10-31 08:21
@malliwi88 I tried, but the problem is still there, I guess if it is related to the leastest 1607 for x64-based Systems windows version.

**Comment by ccordoba12** [comment] 2016-10-31 14:34
It seems this is a bug in Qt. Do you have some special drives or mounted directories in your PC?

**Comment by ccordoba12** [comment] 2016-11-10 18:12
Since we were unable to reproduce this error, I'm afraid I'm going to close it.

**Closed by ccordoba12** 2016-11-10 18:12 UTC
Labels: OS-Windows, Type-Bug

**Comment by rportron** [comment] 2017-08-30 15:16
Hi I have the same issue on Spyder 3.2.1 and Windows 10
If I click on Open or Save As, SPyder3 crashes
