### ISSUE TITLE
'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'

### ISSUE THREAD

**Issue by chaitusyn** [spyder-ide/spyder#6604] opened 2018-03-05 08:20 UTC
## Description
Hi , I commented this section of the code in sitecustomize.py
 Still its not working.Could you please help me proceed with this.I am new to Python and still learning stuff
**What steps will reproduce the problem?**

1. Hi , I commented this section of the code in sitecustomize.py
 Still its not working.Could you please help me proceed with this.I am new to Python and still learning stuff
 #if HAS_PYXIMPORT:

#if HAS_PYXIMPORT:

# Add Numpy include dir to pyximport/distutils

try:

import numpy

pyx_setup_args['include_dirs'] = numpy.get_include()

except:

pass
# Setup pyximport and enable Cython files reload

pyximport.install(setup_args=pyx_setup_args, reload_support=True)

#try:

# Import cython_inline for runfile function

from Cython.Build.Inline import cython_inline

HAS_CYTHON = True

#except:

HAS_CYTHON = False
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

I already referred #5299#5299, 
Please help me resolve this

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-03-05 08:33
Sorry you're having difficulties, but you already created an issue about this as you mentioned just a few days ago, and as you state this is a duplicate of that (#6568 ) which is in turn, a duplicate of #5299 . Please do not create new duplicate issues, as this is a bug tracker, not a help forum, and posting multiple duplicate reports makes it more difficult for us to help you and keep track of everything. Instead, post there or be patient for a response. Thanks.

**Closed by CAM-Gerlach** 2018-03-05 08:33 UTC

**Comment by CAM-Gerlach** [comment] 2018-03-05 08:35
Also, you should enclose your blocks of code in triple backticks, as I've edited your post above to include. Otherwise, crazy and almost unreadible formatting results as you can clearly see in all your posts, which not only makes it much harder for us to read them but makes it impossible to copy and paste the code into Python and have it run. Thanks.
