### ISSUE TITLE
Ctrl+Click on the name of a module doesn't open it

### ISSUE THREAD

**Issue by robobobeng** [spyder-ide/spyder#15924] opened 2021-06-23 12:37 UTC
### Issue Report Checklist

* [ x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x ] Tried basic troubleshooting (if a bug/error)
    * [ x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When using control + click on the name of a module, Spyder used to open that module in another tab. But for some reason this doesn't work anymore for me.

### What steps reproduce the problem?

Create a script `test1.py` and save it:

    #test1.py
    print("a")

In the same folder, create the following script `test2.py`:

    #test2.py
    import test1

### What is the expected output? What do you see instead?

Now, when working on test2.py, ctrl+clicking on the word "test1" should open the script `test1.py` in another tab... but that doesn't happen as it should be.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.3
* Python version: 3.7.10 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by dalthviz** [comment] 2021-06-23 16:53
Hi @robobobeng thanks for the feedback! I was trying to check this but the last version of 4.x `4.2.5` doesn't allow to do it neither (unless you either are working inside a spyder project or using relative imports i.e `.untitled1`). Previously it worked for you without having and active project? Let us know!

**Comment by robobobeng** [comment] 2021-06-24 06:11
> Hi @robobobeng thanks for the feedback! I was trying to check this but the last version of 4.x `4.2.5` doesn't allow to do it neither (unless you either are working inside a spyder project or using relative imports i.e `.untitled1`). Previously it worked for you without having and active project? Let us know!

Before updating to 5.0.3 I had not been using Spyder for a while (several months), so I don't remember the version number of the Spyder I was using before that. But I know that it used to work. I never use projects, I only write Python scripts outside of any Spyder project.

**Comment by dalthviz** [comment] 2021-06-24 16:46
Thanks for the info @robobobeng checking a little bit more I think the problem is that at some point we removed adding the current working directory to the `PYTHONPATH` automatically. If you want to have again such type of navigation with `Ctrl + Click` you will need to add first with the PYTHONPATH manager (Python icon in the toolbar) the directory were your scripts are or use a Spyder project to wrap everything.

Let us know if the info above helps

**Comment by ccordoba12** [comment] 2021-07-13 01:50
Closing due to lack of response.

**Comment by ccordoba12** [comment] 2021-07-15 00:21
I think we can fix this without adding directories to our PYTHONPATH manager. I'll take a look at that for 5.1.0

**Comment by ccordoba12** [comment] 2021-07-28 05:05
Closing as a duplicate of issue #13358.

**Closed by ccordoba12** 2021-07-28 05:05 UTC
Labels: component:Code Completion, type:Bug
