### ISSUE TITLE
problem with ZMQStream

### ISSUE THREAD

**Issue by ballpien** [spyder-ide/spyder#20518] opened 2023-02-11 21:04 UTC
### What steps will reproduce the problem?

open spyder
close project
sometimes error occurs here
open another project
error occurs

spyder is started by using 'start spyder'

Contents of command window:

fromIccProfile: failed minimal tag size sanity
C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.SUB, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.SUB, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)

### Traceback
```python-traceback
Exception in callback functools.partial(<function ThreadedZMQSocketChannel.send.<locals>.thread_send at 0x00000224687D3F40>)
Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\tornado\ioloop.py", line 740, in _run_callback
    ret = callback()
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\threaded.py", line 113, in thread_send
    self.session.send(self.stream, msg)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\session.py", line 859, in send
    stream.send_multipart(to_send, copy=copy)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\eventloop\zmqstream.py", line 401, in send_multipart
    self._add_io_state(zmq.POLLOUT)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\eventloop\zmqstream.py", line 690, in _add_io_state
    self._update_handler(self._state)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\eventloop\zmqstream.py", line 702, in _update_handler
    if state & self.socket.events:
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\sugar\attrsettr.py", line 56, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\sugar\attrsettr.py", line 68, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 512, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 270, in zmq.backend.cython.socket._getsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: not a socket
Exception in callback functools.partial(<function ThreadedZMQSocketChannel.send.<locals>.thread_send at 0x000002245B07BAC0>)
Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\tornado\ioloop.py", line 740, in _run_callback
    ret = callback()
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\threaded.py", line 113, in thread_send
    self.session.send(self.stream, msg)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\jupyter_client\session.py", line 859, in send
    stream.send_multipart(to_send, copy=copy)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\eventloop\zmqstream.py", line 401, in send_multipart
    self._add_io_state(zmq.POLLOUT)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\eventloop\zmqstream.py", line 690, in _add_io_state
    self._update_handler(self._state)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\eventloop\zmqstream.py", line 702, in _update_handler
    if state & self.socket.events:
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\sugar\attrsettr.py", line 56, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "C:\Users\Owner\anaconda3\envs\work310\lib\site-packages\zmq\sugar\attrsettr.py", line 68, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 512, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 270, in zmq.backend.cython.socket._getsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: not a socket
```

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.9.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.1.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment] 2023-02-12 00:18
Hi @ballpien thank you for the feedback! This seems related with https://github.com/spyder-ide/spyder/issues/20381 Could you try to downgrade PyZQM to version 24.0 a see if that helps? Let us know if that helps!

**Comment by ballpien** [comment] 2023-02-12 16:17
Hi Daniel,

 

I downgraded and the error messages no longer occur. Thanks.

 

Kirk

**Comment by dalthviz** [comment] 2023-02-13 20:39
Awesome, glad downgrading PyZMQ worked for you @ballpien ! I will close this issue then as a duplicate of #20381

**Closed by dalthviz** 2023-02-13 20:39 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
