### ISSUE TITLE
I can not find the problem

### ISSUE THREAD

**Issue by sefakarabas** [spyder-ide/spyder#5001] opened 2017-08-18 14:46 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/sefa/.local/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 142, in icon
    if osp.isdir(fname):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/sefa/.local/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 142, in icon
    if osp.isdir(fname):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/sefa/.local/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 142, in icon
    if osp.isdir(fname):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/sefa/.local/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 142, in icon
    if osp.isdir(fname):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-13: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 2.7.13
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-18 15:09
Closing as a duplicate of issue #5000 because the problem is esentially the same.

**Closed by ccordoba12** 2017-08-18 15:09 UTC
