### ISSUE TITLE
Crash on restart after changing Icon theme

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#4253] opened 2017-03-12 08:39 UTC
Old icon theme was not perfect, but the new one is just ugly. YMMV anyway. As long as I switch to the Spyder 2 theme, everything is fine, but Spyder 3.0.2 (stable one from Ubuntu16.10) crashes while trying to restart itself after changing the setting.

**What steps will reproduce the problem?**

![image](https://cloud.githubusercontent.com/assets/515889/23830248/68bbddba-0717-11e7-88ec-072d151c6379.png)

```
Segmentation fault (core dumped)
$ Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/app/restart.py", line 279, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/spyder/app/restart.py", line 232, in main
    restarter.launch_error_message(error_type=CLOSE_ERROR)
  File "/usr/lib/python2.7/dist-packages/spyder/app/restart.py", line 152, in launch_error_message
    raise RuntimeError(message)
RuntimeError: It was not possible to close the previous Spyder instance.
Restart aborted.
```
Parent window becomes closed, but both preferences and restart dialog stay on screen while new splash screen appears with a "closing spyder" message.

![image](https://cloud.githubusercontent.com/assets/515889/23830284/53f1bd04-0718-11e7-9926-ab1033a9f46a.png)

Ubuntu bug reporting window is not resizeable and doesn't allow to copy contents, but that's the only clue there.

## Versions and main components

* Spyder Version: 3.0.2 (Ubuntu 16.10)

**Comment by ccordoba12** [comment] 2017-03-12 13:35
What happens if you press `No` and manually restart Spyder?

**Comment by techtonik** [comment] 2017-03-12 18:44
If I press `No` and manually restart, it work as expected - icons change without crashes.

**Comment by rlaverde** [comment] 2017-05-31 23:49
I wasn't able to reproduce this error 😞

**Comment by ccordoba12** [comment] 2018-12-06 21:10
Closing because we were unable to reproduce this error.

**Closed by ccordoba12** 2018-12-06 21:10 UTC
Labels: component:Main Window, type:Bug

**Comment by techtonik** [comment] 2018-12-28 15:12
I am not using Spyder anymore.
