### ISSUE TITLE
spyder-terminal not starting up

### ISSUE THREAD

**Issue by pradumn26** [spyder-ide/spyder#6885] opened 2018-04-02 12:28 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Pradumn\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 317, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\Pradumn\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 330, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-04-02 14:36
Thanks for reporting. This is a duplicate of spyder-ide/spyder-terminal#123. Unfortunately, we don't know how to fix it.

**Closed by ccordoba12** 2018-04-02 14:36 UTC

**Comment by pradumn26** [comment] 2018-04-07 13:32
is it because i installed spyder-teminal via pip in anaconda environment??

**Comment by CAM-Gerlach** [comment] 2018-04-09 03:28
Possibly; ``pip`` is well known to break installs and cause all kinds of weird issues in ``conda`` environments.
