### ISSUE TITLE
spyder running problem

### ISSUE THREAD

**Issue by xue127128** [spyder-ide/spyder#5892] opened 2017-12-05 03:26 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 2872: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 117: invalid continuation byte

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-05 04:48
Thanks for reporting. What were you doing when you got this error? Please let us know; otherwise we won't  be able to figure out what's going on or help you solve the issue, and so this will probably get closed within a week or so.

**Comment by ccordoba12** [comment] 2017-12-05 16:02
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2017-12-16 20:41
Closed due to lack of response.

**Closed by CAM-Gerlach** 2017-12-16 20:41 UTC
