### ISSUE TITLE
Profiler not working

### ISSUE THREAD

**Issue by thejesusbr** [spyder-ide/spyder#12577] opened 2020-05-02 16:53 UTC
### What steps will reproduce the problem?

Just tried to run the profiler and got this error.

### Traceback
```python-traceback
  File "/home/wendell/oldwendell/anaconda3/lib/python3.7/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 267, in <lambda>
    self.finished(ec, es))
  File "/home/wendell/oldwendell/anaconda3/lib/python3.7/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 335, in finished
    self.show_errorlog()  # If errors occurred, show them.
  File "/home/wendell/oldwendell/anaconda3/lib/python3.7/site-packages/spyder/plugins/profiler/widgets/profilergui.py", line 240, in show_errorlog
    readonly=True, size=(700, 500), parent=self).exec_()
TypeError: __init__() got an unexpected keyword argument 'size'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-65-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.1 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment] 2020-05-04 01:48
Hi @thejesusbr, thanks for the report. This seems to be a duplicate of #11875

Closing

**Closed by goanpeca** 2020-05-04 01:48 UTC
