### ISSUE TITLE
Spyder using  increasingly more CPU & memory while idling when using the Tkinter backend

### ISSUE THREAD

**Issue by fdarvas** [spyder-ide/spyder#19874] opened 2022-10-17 23:20 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am using Spyder 5.3.3 on WSL2 Ubuntu 20.04, installed via pip.
Just having Spyder sitting idle for a while leads to increasing CPU & memory use, eventually reaching 100% of CPU.

![image](https://user-images.githubusercontent.com/14614249/196300967-53915d73-0919-4225-8c3b-4ab8b7b98213.png)

### What steps reproduce the problem?

1.  Start spyder
2.  wait
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.3
* Python version: 3.8.10 IPython 7.31.1
* Qt version: 
* PyQt version: 
* Operating System name/version: WSL2 Ubuntu 20.04 on Windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2022-10-18 21:47
Hey @fdarvas, thanks for reporting. As you can see from your screenshot, the problem is not with Spyder (which consumes very little memory). It has to do with an external process created that seems created by Spyder.

So please post the full command of that `python3` process that is consuming a lot of memory in your PC to see what is related to.

**Comment by fdarvas** [comment] 2022-10-18 22:24
There is no external process - If I start spyder from the terminal with `spyder`, this python3 process show up in top and starts accumulating memory and CPU time. 

When I close spyder, the process goes away too. 
So I presume it is started along with spyder?

I see this , even if dont run any code inside spyder.

**Comment by ccordoba12** [comment] 2022-10-19 16:06
> There is no external process

We open several external processes when Spyder starts, e.g. to run code and provide code completion in the editor. That's why that process is not labeled as `spyder` in the `top` screenshot you posted, but as `python3`. And this is for you to understand that the bug you're reporting is not related directly to Spyder but to that external process.

Furthermore, that's the reason why we need the full command of that process, so we understand which one is causing the memory leak in your machine. So, instead of arguing with me about it, please get that command from `top` (by pressing `c` after it starts) and post it here.

**Comment by fdarvas** [comment] 2022-10-19 17:13
I thought community feedback was actually a valuable and welcome process to make this software better. Sorry to have apparently irritated you, so will stop that right here.

**Comment by ccordoba12** [comment] 2022-10-19 22:08
Sorry, I apologize, I know I was harsh. If you're able to provide the piece of info I asked for, then we could continue seeing what your problem is about.

If you don't feel comfortable with doing it, I can only let you know that this bug seems very similar to issue #19026, which should be fixed in our next version (5.4.0), to be released next week. You can also find there more info about how to solve this problem for now.

**Comment by fdarvas** [comment] 2022-10-19 22:28
No problem, apology accepted.  - Some of us are just users, and so not necessarily always deep diving into the problem right away - I was just hoping to get this kind of dialogue, by providing the initial information. I actually enjoy Spyder quite a bit, so naturally have an interest in getting this sorted out.

I did a reset to spyder factory defaults, which seems to have fixed the problem (unclear how and why). Possibly because the graphics backend changed? 
It is back to inline. 
Reading through that other thread I suspect it could be the same issue.  

Switching from inline to Tkinter, brings the problem back. So I think it is the same issue.

The python3 process in top is this one I believe:

8971 felix     20   0 3501796 217088  60740 S   0.7   0.3   0:07.51 /usr/bin/python3 -m spyder_kernels.console -f /home/felix/.local/share/jupyter/runtime/kernel-619aec1fb775.json

**Comment by ccordoba12** [comment] 2022-10-20 02:47
> Switching from inline to Tkinter, brings the problem back. So I think it is the same issue.

Right, but the thing is that we fixed the memory leak issue only for the Automatic/Qt backends, not for Tkinter. So, I'll reopen your issue to see if we can fix it in a later version (we're very close to release the next one).

> The python3 process in top is this one I believe

Thanks! That confirms that this bug happens in the process we use to run code, which is precisely the one where we set the Tkinter backend.

**Comment by ccordoba12** [comment] 2022-10-20 02:49
@impact27, perhaps you have some free time to take a look at this one?

**Comment by impact27** [comment] 2022-10-20 06:42
It is probably a leak in https://github.com/ipython/ipykernel that is triggered each time a comm message comes.

**Comment by impact27** [comment] 2022-10-20 07:27
fixed by https://github.com/ipython/ipykernel/pull/1008

**Comment by fdarvas** [comment] 2022-10-20 18:21
It looks like I can upgrade the ipython kernel and spyder still works (despite protesting that the ipython kernel has to be <=7.31)???  Because between this issue and this one https://github.com/spyder-ide/spyder/issues/19551 , it looks like tkinter & Qt5 are both off the table for plotting right now - and the inline option is mostly not great for producing nice figures

**Comment by ccordoba12** [comment] 2022-10-20 19:01
Fantastic! Thanks a lot @fdarvas for the confirmation and for your patience in dealing with me. I'm glad everything turned out well in the end.

We'll make sure Spyder picks up the version of IPykernel that has this fix in our next version.

**Closed** 2022-10-31 22:16 UTC
Labels: type:Bug, OS:Linux, component:IPython Console, upstream
