### ISSUE TITLE
No code completion in editor

### ISSUE THREAD

**Issue by mikeyford** [spyder-ide/spyder#6306] opened 2018-01-26 21:36 UTC
Thanks very much for all of your hard work in Spyder. It's really turning into an amazing tool!

**What steps will reproduce the problem?**

1.  Open new file in spyder and in 
2.  `import numpy as np` (c-[RET] to evaluate in ipython console)
3.  `np.[TAB]`
or `a = np.array([]) ` (c-[RET])
`a.[TAB]`

**What is the expected output? What do you see instead?**
No code completion in Spyder editor. The same code produces suggestions in the ipython console.

## Versions and main components
* Spyder Version: 3.2.6 
* Python Version: 3.6.2
* Qt Versions: 5.10.0, PyQt5 5.10 on Darwin
* Operating system: MacOS 10.12.6

## Dependencies

pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.8.2 (OK)

**Comment by CAM-Gerlach** [comment] 2018-01-26 23:59
Thanks for reporting. This is a duplicate of #5782 , so please see that issue for more help; the most common solution was removing the ``enum34`` package if you have it; it could also be a number of other things listed there. Therefore, this one will be closed.

**Closed by CAM-Gerlach** 2018-01-26 23:59 UTC
