### ISSUE TITLE
Starting Spyder for the first time after a new installation of Anaconda

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder#6603] opened 2018-03-05 06:32 UTC
## Description

**What steps will reproduce the problem?**

1. Launch Spyder from Anaconda Navigator.  
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2489, in execute_in_external_console
    console.execute_code(lines)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 970, in execute_code
    sw.execute(to_text_string(lines))
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 632, in execute
    self._execute(source, hidden)
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-03-05 08:28
Thanks for reporting. This is a duplicate of #6308 , which was fixed in Spyder 3.2.7. Please update with ``conda update spyder`` from the Anaconda Prompt.

**Closed by CAM-Gerlach** 2018-03-05 08:28 UTC
