### ISSUE TITLE
i have no idea about this error, and the spyder just open this page automaticly.

### ISSUE THREAD

**Issue by Dashu-Xu** [spyder-ide/spyder#7066] opened 2018-05-04 17:33 UTC
## Description

**What steps will reproduce the problem?**

1. it shows by accident, i have no idea how to make it show again.
2. i have write a test1.py file and import it in another test2.py file, then i ran the code in test2.py, after that, i move test1.py from one fold to another , then this error occurd.
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Users\keltsing\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1660, in current_changed
    self.current_file_changed.emit(self.data[index].filename,
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by paulgureghian** [comment] 2018-05-04 18:35
update anaconda to the current version (1.8.4), then update spyder to 3.2.8  put sypder shortcut on desktop

**Comment by CAM-Gerlach** [comment] 2018-05-06 19:45
As @paulgureghian suggests, your version of Spyder is over a year old, and this is likely a duplicate of #5157 . Please update everything and try again; otherwise, this issue will be closed after one week (7 days) if we don't hear from you. Thanks.

> update anaconda to the current version (1.8.4)

Latest version of Anaconda is 5.1.0, btw

> put sypder shortcut on desktop

???

**Comment by CAM-Gerlach** [comment] 2018-05-06 22:57
These questions are neither germane to this issue nor have anything to do with the Spyder IDE, but I'll do my best the briefly answer them since it seems they are a common point of confusion for new/beginner users like yourself and presumably the OP...

> I have navigator 1.8.4 from anaconda.org

Well, then I'm not sure how I understand how the version of navigator you have is in any way relevant to the OP's issue...

>  what is 5.1.0. anaconda from anaconda.com

I don't understand what you're asking; you appear to have answered your own question.

> what is the difference ?

Anaconda Navigator is a simple GUI for doing some of the ``conda`` and ``conda-env`` tasks that normally require the command line (incidentally, our very own spyder-ide/conda-manager project was the basis for it, and we plan to incorporate similar functionality inside of Spyder directly as part of Spyder 4). Anaconda, meanwhile, is the Python distribution, with a standalone GUI installer, package manager (``conda``), environment manager (``conda-env``) and other utilities and conveniences, along with a large suite of common scientific packages. Your version of navigator is basically irrelevant to anything else, while your version of Anaconda as a whole specifies exactly what packages and versions you have installed, at least as a baseline.

> why is there .org and .com ?

You'll have to ask Anaconda for their reasons for separating them; tangentially it appears for SEO reasons they've set .org to be the primary on their search bot configuration such that the .com site is impossible to find by searching for it.

> which one should I install?

Navigator is a component of the Anaconda distribution, and comes installed by default. It is not really meaningful, if even possible, to have or use it without Anaconda (or Miniconda) itself, so that question is sort of like asking "Should I install Windows/macOS/Linux or Windows Update/Software Update/Aptitude?"

**Comment by paulgureghian** [comment] 2018-05-06 23:44
I downloaded and installed 5.1.0 and nothing happened. no new shortcut, no indication of anything new being installed.

**Comment by CAM-Gerlach** [comment] 2018-05-06 23:54
Again, this really isn't the place for that, sorry. As mentioned before, this is the Spyder bug tracker, not an Anaconda help forum, and none of this has anything to do with the OP's issue, nor Spyder, nor a bug with the code. Therefore, please try Google or one of the many resources for getting help with Anaconda instead in order to best solve your problem, assuming you have one. Best of luck.

**Comment by Dashu-Xu** [comment] 2018-05-07 01:41
i will have a try , thank you .
btw, can i colse this issue?
i mean it seems like you have some other questions...

**Comment by CAM-Gerlach** [comment] 2018-05-07 01:44
Sure; thanks for the followup. Hope updating everything fixes the issue, and let us know if it doesn't. Best of luck!

**Closed by CAM-Gerlach** 2018-05-07 01:45 UTC
Labels: status:Awaiting Followup
