### ISSUE TITLE
Spyder 3.0.0dev + qt5.5 crashes on Mac (Segmentation fault)

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#3059] opened 2016-03-13 12:27 UTC
## Description

**What steps will reproduce the problem?**

1. Start Spyder (from Terminal cmd in my case)
2. Use Spyder for some time, from 30min to a few hours.
3. Spyder crashes (Segmentation fault).

I couldn't find out what exactly triggered the crash, but it happened repeatedly in the past week.

## Version and main components

* Spyder Version: 3.0.0dev 
* Python Version: 2.7.11
* Qt Versions: 5.5.1, PyQt5 5.5.1 on Darwin

## Dependencies
```
pyflakes >=0.5.0:  1.0.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
numpy >=1.7     :  1.10.4 (OK)
sphinx >=0.6.6  :  1.3.3 (OK)
psutil >=0.3    :  3.4.2 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  1.5.2 (OK)

```

## Other observations:

As Spyder is started from Terminal, it outputs logs like the following to the terminal:

```
2016-03-13 16:57:40.937 python[89775:4286586] inOptions: {
    "is.flipped" = 1;
    kCUIOrientationKey = kCUIOrientVertical;
    kCUIPartMaskKey = 768;
    kCUIThumbProportionKey = 0.1180400890868597;
    state = normal;
    value = 0.2398989898989899;
    widget = scrollbar;
}
2016-03-13 16:57:40.937 python[89775:4286586] outHitPart = -1
Segmentation fault: 11
```

Also, here is the crash report generated by Mac:
https://gist.github.com/ShenggaoZhu/86c3616354e5551d9a1c

**Comment by ccordoba12** [comment] 2016-03-13 15:54
@ShenggaoZhu, I almost sure this is a duplicate of issue #3041. It will be fixed by pull request #3049.

**Closed by ccordoba12** 2016-03-13 15:54 UTC
Labels: Duplicate

**Comment by ahishsh** [comment] 2016-06-27 07:43
I get the same error on mac using Spyder 3.0.0.beta3. 
**/Users/Me/anaconda2/bin/python.app: line 3: 79864 Segmentation fault: 11  /Users/anders/anaconda2/python.app/Contents/MacOS/python "$@"**

It happens when I am temporarily using some other  window (like chrome). Sometimes I also get this error -- it might be related but don't seem to be the thing causing spyder to crash.
QTextCursor::setPosition: Position '13389' out of range
QTextCursor::setPosition: Position '13389' out of range
QTextCursor::setPosition: Position '29147' out of range
QTextCursor::setPosition: Position '29147' out of range
QTextCursor::setPosition: Position '29147' out of range
QTextCursor::setPosition: Position '29147' out of range

I'd love to provide more info on system etc but not sure how to do it? (new to osx...)

**Comment by ccordoba12** [comment] 2016-06-27 07:54
Beta3 has some freezing and crashing issues that will be fixed in Beta4.

**Comment by hasakura511** [comment] 2017-02-23 05:13
Hello,
Spyder crashes sometimes. Here is the error.

/Users/me/anaconda/bin/python.app: line 3: 56546 Segmentation fault: 11  /Users/me/anaconda/python.app/Contents/MacOS/python "$@"


I am using
Spyder 3.1.3 
Python 2.7.13 64bits, Qt 5.6.2, PyQt5 5.6 on Darwin
