### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by lm2018** [spyder-ide/spyder#6734] opened 2018-03-12 16:08 UTC
attempt to change preferences->syntax coloring: changed sheme to Scintila   

File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\envs\an2\lib\site-packages\spyder\plugins\configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\envs\an2\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\Users\xxxx\AppData\Local\Continuum\Anaconda3\envs\an2\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\envs\an2\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\Users\xxxx\AppData\Local\Continuum\Anaconda3\envs\an2\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by CAM-Gerlach** [comment] 2018-03-12 16:45
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed by CAM-Gerlach** 2018-03-12 16:45 UTC
