### ISSUE TITLE
Editor Widget IndexError: list index out of range

### ISSUE THREAD

**Issue by rba2124** [spyder-ide/spyder#8746] opened 2019-02-11 00:52 UTC
### What steps will reproduce the problem?

I saved the file, clicked 'run' button, dialog box appeared asking me to save the file, even though I already had saved it. In the dialog box, I selected the file name, and clicked save. Dialog box  closed. I clicked 'run' button. Issue reporter dialog box appeared.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2443, in run_file
    self.re_run_file()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2463, in re_run_file
    self.save_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2037, in save_all
    self.get_current_editorstack().save_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1804, in save_all
    if self.data[index].editor.document().isModified():
IndexError: list index out of range
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-11 15:08
Thanks for reporting. This is a duplicate of issue #8749.

**Closed by ccordoba12** 2019-02-11 15:08 UTC

**Comment by ccordoba12** [comment] 2019-02-11 15:18
Sorry, this is duplicate of issuer #5996 and we'll look at it in our next version.

**Comment by ccordoba12** [comment] 2019-02-17 13:12
@rba2124, do you still have this problem? I've tried several ways to reproduce it but failed completely (and without a way to reproduce it, I can't fix it).

If that's the case, please post on issue #5996 what message appears on the file dialog that asks you to save your file (an screenshot showing that would be fine too). Thanks!

**Comment by rba2124** [comment] 2019-02-17 13:19
So far, it seems to have been a one time aberration.

**Comment by ccordoba12** [comment] 2019-02-17 13:26
Was your file placed in a Dropbox or OneDrive directory?

**Comment by rba2124** [comment] 2019-02-17 13:54
No.

**Comment by ccordoba12** [comment] 2019-02-17 13:55
Ok, thanks. If you're able to reproduce this problem, please let us know.
