### ISSUE TITLE
Feature Request: Column Mode/Multi cursor support

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#15558] opened 2021-05-09 12:35 UTC
**Feature Request: Column Mode/Multi cursor support**

Is it able to use column editing via `Alt/Ctrl` like in VS Code?

**Comment by ccordoba12** [comment] 2021-05-09 19:28
Hey @1900011604, thanks for reporting. This has been asked many times in the past and we'll try to implement in Spyder 6, to be released next year.

Closing as a duplicate of issue #2112.

**Closed by ccordoba12** 2021-05-09 19:28 UTC
