### ISSUE TITLE
Environment variables are not picked up by the IPython console

### ISSUE THREAD

**Issue by jwruss** [spyder-ide/spyder#3586] opened 2016-10-24 00:01 UTC
## Description of your problem

When attempting to access the [pyROOT module](https://root.cern.ch/pyroot) using "import ROOT" in Spyder's IPython console, Spyder doesn't pick up the module. This error does not happen when using Spyder's Python console. This error also does not occur when either Python or IPython are called from terminal.

**What is the expected output? What do you see instead?**

The expected output would be for the module to be imported. Issuing the command "import ROOT" using a Spyder IPython console results in the output

Traceback (most recent call last):

  File "<ipython-input-1-b332e25ada1f>", line 1, in <module>
    import ROOT

  File "<$ROOTSYS>/lib/ROOT.py", line 614, in <module>
    import JupyROOT

  File "<$ROOTSYS$>/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, _args, *_kwds )

  File "<$ROOTSYS>/lib/JupyROOT/**init**.py", line 1, in <module>
    import JupyROOT.utils

  File "<$ROOTSYS>/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, _args, *_kwds )

  File "<$ROOTSYS>/lib/JupyROOT/utils.py", line 17, in <module>
    import handlers

  File "<$ROOTSYS>/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, _args, *_kwds )

ImportError: No module named 'handlers' 

**Please provide any additional information below**

Spyder and its dependencies installed using pip3 (tried both with and without sudo), not through a Python Scientific Distribution.

Searching online to see if the problem is due to ROOT, [this thread](https://root.cern.ch/phpBB3/viewtopic.php?t=17947) suggests the problem is that Spyder doesn't detect the environment variable LD_LIBRARY_PATH. This variable is appended in my home directory's .bashrc file. Several [options](https://groups.google.com/forum/#!topic/spyderlib/oK8wlcqtV2c) [have](https://groups.google.com/forum/#!topic/spyderlib/zUPW9O-wViM) [been](https://ubuntuforums.org/archive/index.php/t-466808.html) [reviewed](http://stackoverflow.com/questions/31162021/why-do-the-environment-variables-set-in-command-prompt-have-no-effect-when-i-sta), but either they don't work or appear too dated to be applicable. Attempted usage of both shell and/or Python commands under
'Tools > PYTHONPATH manager',
'Tools > Preferences > Python interpreter > User Module Reloader (UMR)',
and
'Tools > Preferences > IPython console > Startup > Run code'
also don't appear to address the problem.
## Versions and main components
- Spyder Version: 3.0.1
- Python Version: 3.5.2 [GCC 5.4.0 20160609] on linux
- Operating system: Ubuntu 16.04 LTS
- ROOT Version: 6.09/01
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.0 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.4.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  0.7.6.1 (OK)

**Comment by jwruss** [comment] 2016-10-24 00:10
This was not a problem under Ubuntu 14.04 when using Anaconda Python. Rather than downgrading to an earlier version of GCC and sticking with Anaconda Python while compiling ROOT, I chose to upgrade to ROOT 6.09/01. The previous 6.06/08 version of ROOT seems to have difficulty with GCC 3.5.2.

**Comment by ccordoba12** [comment] 2016-10-24 02:29
Does this happen if you start Spyder from the command line?

**Comment by jwruss** [comment] 2016-10-24 18:32
When accessing Spyder, I enter into the terminal "spyder", then <enter>. Your question made me think to instead try "sudo -i spyder" or "sudo spyder", then <enter>. In both Spyder's Python and IPython consoles, when I enter the command "import ROOT" I now instead get the output

Traceback (most recent call last):

  File "<ipython-input-1-b332e25ada1f>", line 1, in <module>
    import ROOT

ImportError: No module named 'ROOT'

**Comment by ccordoba12** [comment] 2016-10-24 20:44
Using sudo is not necessary. This just means that we're not grabbing environment variables for our IPython consoles.

We're working on this for Spyder 3.2 :-)

**Comment by jwruss** [comment] 2016-10-24 21:06
Thank you! I eagerly await its release. :)

**Comment by ccordoba12** [comment] 2016-10-24 21:11
Please don't close it, we need it open to not forget to fix it :-)

**Comment by jwruss** [comment] 2016-10-24 21:14
Ah, my apologies. Didn't know that. Thank you again!

**Comment by jwruss** [comment] 2016-10-25 18:20
Hello Carlos,

When accessing Spyder, I enter into the terminal "spyder", then <enter>.
Your question made me think to instead try "sudo -i spyder" or "sudo
spyder", then <enter>. In both Spyder's Python and IPython consoles, when I
enter the command "import ROOT" I now instead get the output

Traceback (most recent call last):

  File "<ipython-input-1-b332e25ada1f>", line 1, in <module>
    import ROOT

ImportError: No module named 'ROOT'

Thank you for your help,
John

**Comment by ccordoba12** [comment] 2016-10-25 18:33
No worries ;-)

**Comment by david-july1991** [comment] 2017-02-17 04:45
Same problem here! I've installed python3, spyder, root and jupyroot using dnf package manager on fedora 25.

**Comment by david-july1991** [comment] 2017-02-17 04:51
I've got the same error on jupyter notebook, but ipython which is lunched on terminal.

**Comment by ccordoba12** [comment] 2017-08-13 17:51
This is a duplicate of issue #3891.

**Closed by ccordoba12** 2017-08-13 17:51 UTC
