### ISSUE TITLE
Online Help: Unable to Load Page

### ISSUE THREAD

**Issue by HJLBX** [spyder-ide/spyder#9070] opened 2019-03-30 07:02 UTC
### What steps will reproduce the problem?

Using the Online Help, all I get is "Unable to load page."

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-03-30 10:16
Please post a screenshot of what you're seeing.

@CAM-Gerlach, is "Online Help" working for you?

**Comment by CAM-Gerlach** [comment] 2019-03-30 18:58
@ccordoba12 Nope, its not and hasn't been for a long time. Duplicate of #5533 , where I discuss this further. I can't test in Spyder 4 because ``View > Panes > Online Help`` is missing, even though ``spyder/plugins/onlinehelp`` is still present in the codebase.

**Comment by ccordoba12** [comment] 2019-03-30 19:07
Closing then as a duplicate of #5533.

**Closed by ccordoba12** 2019-03-30 19:07 UTC
Labels: status:Awaiting Followup
