### ISSUE TITLE
Spyder  iPython console slow using 4.0.0beta2 with Automatic graphics backend

### ISSUE THREAD

**Issue by maruskinmz** [spyder-ide/spyder#9519] opened 2019-06-05 20:37 UTC
### What steps will reproduce the problem?

I am running Spyder 4.0.0 beta2 on a macbook pro.  The iPython console is extremely slow when I set back-end graphics to Automatic.  

However, I need the pop-out graphics so that I can plot multiple things on the same plot, edit plots, zoom in, etc.  I had the same issue in Spyder 3.3.4.  

Is there a work-around for this?  E.g., downgrading ipython kernel or something?  Or using an alternate back-end graphics opttion?  Or perhaps another setting, e.g., code correct frequency?  

Any help you can give is most appreciated. 

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pygments >=2.0     :  2.2.0 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  1.7.4 (OK)
psutil >=0.3       :  5.4.5 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.3.1 (OK)
pandas >=0.13.1    :  0.23.4 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  1.1.1 (OK)
cython >=0.21      :  0.28.2 (OK)
qtconsole >=4.2.0  :  4.3.1 (OK)
IPython >=4.0      :  6.4.0 (OK)
matplotlib >=2.0.0 :  2.2.2 (OK)
pylint >=0.25      :  1.8.4 (OK)
```

**Comment by bcolsen** [comment] 2019-06-06 07:07
On issue #2902 people have had success with changing the graphics backend from Automatic to Tkinter.

**Comment by ccordoba12** [comment] 2019-06-06 11:21
Yes, this is basically a duplicate of issue #2902 and the problem only happens with the Automatic backend. So please use Tkinter in the meantime.

**Closed by ccordoba12** 2019-06-06 11:21 UTC
