### ISSUE TITLE
Editor slowdown on Mac after ballon tip appers

### ISSUE THREAD

**Issue by isaacyeaton** [spyder-ide/spyder#2798] opened 2015-11-04 18:34 UTC
## Description

**What steps will reproduce the problem?**
1. np.a [Tab] in the editor window
2. ballon tip(?) appears with possible completions
3. 

**What is the expected output? What do you see instead?**
The editor should not slow down and affect typing speed. 

**Please provide any additional information below**
There seems to be no way to disable this ballon tip from appearing. I have disabled the checkbox in both Editor -> Code Introspection/Analysis -> Introspection and in Console -> Introspection -> Source code.
## Version and main components
- Spyder Version: 2.3.7 
- Python Version: 2.7.10
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.16.2 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.10.2 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by nbara** [comment] 2015-11-12 10:35
Slowdown also occurs simply when opening an existing *.py file from File Explorer.

**Comment by nbara** [comment] 2015-11-20 14:36
Is this the same issue as #2817  ?

https://github.com/spyder-ide/spyder/issues/2817

**Comment by isaacyeaton** [comment] 2015-11-20 14:58
Probably. I had this issue in Yosemite as well, but Spyder is still usable for me with the lagging cursor.

**Comment by ccordoba12** [comment] 2017-06-25 15:58
Closing as a duplicate of #2817.

**Closed by ccordoba12** 2017-06-25 15:58 UTC
Labels: component:Editor, type:Bug
