### ISSUE TITLE
failure with musicgen from huggingface

### ISSUE THREAD

**Issue by LucienPhilia** [spyder-ide/spyder#22920] opened 2024-11-09 19:10 UTC
### What steps will reproduce the problem?

Trying to run the example code for facebook/musicgen-stereo-medium on huggingface.co.uk in the repo folder

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/spyder/plugins/run/container.py", line 305, in process_run_dialog_result
    executor.exec_run_configuration(run_conf, ext_params)
  File "/usr/lib/python3.11/site-packages/spyder/plugins/run/api.py", line 503, in exec_run_configuration
    return method(input, conf)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 795, in exec_files
    self.run_script(
  File "/usr/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 878, in run_script
    self.get_widget().run_script(
  File "/usr/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 2334, in run_script
    client = self.create_client_for_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1852, in create_client_for_file
    client.allow_rename = False
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'allow_rename'
```

## Versions

* Spyder version: 6.0.1  (openSUSE RPM)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.15
* PyQt5 version: 5.15.10
* Operating System: Linux-6.11.50-luc1enf0rge-h3x-x86_64-with-glibc2.40

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.10 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.5.0 (OK)
importlib_metadata >=4.6.0       :  7.1.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.1 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  72.1.0 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
xdg >=0.26                       :  0.28 (OK)
yarl >=1.9.4                     :  1.14.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.2 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package            Version
------------------ ---------
argcomplete        3.5.1
autocommand        2.2.2
bcrypt             4.2.0
beautifulsoup4     4.12.3
Brotli             1.1.0
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
click              8.1.7
cryptography       43.0.3
Cython             3.0.11
docopt             0.6.2
faust-cchardet     2.1.19
ffmpeg-python      0.2.0
h2                 4.1.0
hpack              4.0.0
html2text          2024.2.26
hyperframe         6.0.1
idna               3.10
importlib_metadata 7.1.0
markdown-it-py     3.0.0
mdurl              0.1.2
packaging          24.1
path               17.0.0
pip                24.3.1
pip-api            0.0.30
pip-run            8.8.2
pipreqs            0.4.13
pipx               1.7.1
platformdirs       4.2.2
pycairo            1.26.1
pycparser          2.22
Pygments           2.18.0
PyGObject          3.50.0
pyOpenSSL          24.2.1
pypi-search        1.2.1
PySocks            1.7.1
requests           2.32.3
rich               13.7.1
shellingham        1.5.4
soupsieve          2.6
tqdm               4.66.4
typer              0.12.5
typer-slim         0.12.5
typing_extensions  4.12.2
urllib3            2.2.3
userpath           1.9.2
yarg               0.1.9
zipp               3.19.2
zstandard          0.22.0

```
</details>

**Comment by dalthviz** [comment] 2024-11-11 20:28
Hi @LucienPhilia thank you for the report! I think this is a duplicate of #21884. Over https://github.com/spyder-ide/spyder/issues/21884#issuecomment-1994594310 you can check a detailed explanation of what is happening, but basically to workaround this issue you need to install `spyder-kernels` over the Python environment that corresponds to the current selected Python interpreter in preferences. Also, you can check more info on how to work with custom interpreters/existing envs on the Spyder docs FAQ page: https://docs.spyder-ide.org/current/faq.html#using-spyder

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2024-12-12 00:28
Closing as a duplicate of #21884

**Closed by dalthviz** 2024-12-12 00:28 UTC
Labels: resolution:Duplicate, component:IPython Console, status:Awaiting Followup
