### ISSUE TITLE
variable explorer

### ISSUE THREAD

**Issue by bitmaster137** [spyder-ide/spyder#17053] opened 2021-12-19 14:54 UTC
### What steps will reproduce the problem?

variable explorer crashes frequently . i cant understand that how to save my variables in file.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 124, in comm_channel_manager
    yield
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 238, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 275, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'02cb55d5fb8040bebb6fa832eef64fb9': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 236, in <lambda>
    triggered=lambda x: self.save_data(),
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 569, in save_data
    nsb.save_data()
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 255, in save_data
    error_message = self.shellwidget.save_namespace(self.filename)
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 176, in save_namespace
    return self.call_kernel(
  File "C:\Anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 127, in comm_channel_manager
    self._comms[comm_id]['comm']._send_channel = (
KeyError: '09f3684a60d911ecb8d834cff6fbf9fe'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2021-12-19 16:12
Hey @bitmaster137, thanks for reporting. Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our Troubleshooting Guide:

http://docs.spyder-ide.org/current/troubleshooting/first-steps.html

to see if you are able to fix this problem by following it.

**Comment by ccordoba12** [comment] 2021-12-27 18:47
Closing due to lack of response.

**Closed by ccordoba12** 2021-12-27 18:47 UTC
Labels: status:Awaiting Followup
