### ISSUE TITLE
run python 2.7 in spyder 5.4.5

### ISSUE THREAD

**Issue by jorisfellinger** [spyder-ide/spyder#21387] opened 2023-09-29 17:09 UTC
### What steps will reproduce the problem?

IN anaconda powerstell prompt:
conda create spyder-27
conda activate spyder-27
pip install spyder-kernels

IN spyder 5.4.5:
change environment via tools => preferences => python interpreter => use following python interpreter => select file => 
c:\users\jif\.conda\envs\spyder-27\python.exe
activate new environment in the console via: consoles => restart kernel

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "C:\Users\jif\.conda\envs\spyder-27\lib\site-packages\spyder_kernels\comms\commbase.py", line 346, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\jif\.conda\envs\spyder-27\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 267, in _remote_callback
    thread_id = threading.get_ident()
AttributeError: 'module' object has no attribute 'get_ident'
Exception in comms call get_var_properties:
  File "C:\Users\jif\.conda\envs\spyder-27\lib\site-packages\spyder_kernels\comms\commbase.py", line 346, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\jif\.conda\envs\spyder-27\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 267, in _remote_callback
    thread_id = threading.get_ident()
AttributeError: 'module' object has no attribute 'get_ident'
Exception in comms call is_special_kernel_valid:
  File "C:\Users\jif\.conda\envs\spyder-27\lib\site-packages\spyder_kernels\comms\commbase.py", line 346, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\jif\.conda\envs\spyder-27\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 267, in _remote_callback
    thread_id = threading.get_ident()
AttributeError: 'module' object has no attribute 'get_ident'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.10.11 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20230430 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.5.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.2.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.5 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.17.4 (OK)
pylint_venv >=2.1.1                              :  3.0.2 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.3 (OK)
pylsp_black >=1.2.0                              :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.3 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.7.2 (OK)
sphinx >=0.6.6                                   :  7.0.1 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  0.29.35 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.2 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\jif\.conda\envs\spyder-27:
#
# Name                    Version                   Build  Channel
backports-abc             0.5                      pypi_0    pypi
backports-functools-lru-cache 1.6.6                    pypi_0    pypi
backports-shutil-get-terminal-size 1.0.0                    pypi_0    pypi
ca-certificates           2023.08.22           haa95532_0  
certifi                   2020.6.20          pyhd3eb1b0_3  
cloudpickle               1.3.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
enum34                    1.1.10                   pypi_0    pypi
futures                   3.4.0                    pypi_0    pypi
ipykernel                 4.10.1                   pypi_0    pypi
ipython                   5.10.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jupyter-client            5.3.5                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
pathlib2                  2.3.7.post1              pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       19.3.1                   py27_0  
prompt-toolkit            1.0.18                   pypi_0    pypi
pygments                  2.5.2                    pypi_0    pypi
python                    2.7.18               hfb89ab9_0  
python-dateutil           2.8.2                    pypi_0    pypi
pywin32                   228                      pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
scandir                   1.10.0                   pypi_0    pypi
setuptools                44.0.0                   py27_0  
simplegeneric             0.8.1                    pypi_0    pypi
singledispatch            3.7.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
spyder-kernels            2.4.4                    pypi_0    pypi
sqlite                    3.30.1               h0c8e037_0  
tornado                   5.1.1                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
typing                    3.10.0.0                 pypi_0    pypi
vc                        9                    h2eaa2aa_6  
vs2008_runtime            9.00.30729.1         haa95532_6  
wcwidth                   0.2.7                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
win-unicode-console       0.5                      pypi_0    pypi
wincertstore              0.2              py27hf04cefb_0  

```
</details>

**Comment by ccordoba12** [comment] 2023-09-29 19:33
Hey @jorisfellinger, thanks for reporting. This is a duplicate of issue #21310 and we'll fix it in our next version (5.5.0), to be released next month.

**Closed by ccordoba12** 2023-09-29 19:33 UTC
