### ISSUE TITLE
Profiler crashes when accessing cv2.VideoCapture

### ISSUE THREAD

**Issue by mherzog01** [spyder-ide/spyder#12500] opened 2020-04-26 13:51 UTC
### What steps will reproduce the problem?

The Spyder Profiler crashes when running the module https://gist.github.com/mherzog01/db5c446cec8da9569ca2cfbbf66edd92.

The module runs fine when executed within Spyder, not using the Profiler.

When run via the profiler, the module runs fine if line 62 is commented out:

            cap = cv2.VideoCapture(STREAM_NUM)  # Change only if you have more than one webcams

This makes me wonder if the Profiler is not able to handle results of the cv2.VideoCapture function.

### Traceback
```python-traceback
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\site-packages\spyder\plugins\profiler\widgets\profilergui.py", line 267, in <lambda>
    self.finished(ec, es))
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\site-packages\spyder\plugins\profiler\widgets\profilergui.py", line 335, in finished
    self.show_errorlog()  # If errors occurred, show them.
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\site-packages\spyder\plugins\profiler\widgets\profilergui.py", line 240, in show_errorlog
    readonly=True, size=(700, 500), parent=self).exec_()
TypeError: __init__() got an unexpected keyword argument 'size'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.16 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-04-26 17:51
Duplicate of #11875

**Comment by ccordoba12** [comment] 2020-04-26 17:51
It'll be fixed in our next version.

**Closed by ccordoba12** 2020-04-26 17:51 UTC
