### ISSUE TITLE
Could not Initialize GLX after Conda Update --All

### ISSUE THREAD

**Issue by lucis13** [spyder-ide/spyder#7152] opened 2018-05-19 19:41 UTC
## Problem Description
I'm using Spyder on a remote server by SSH and X11 forwarding. After I use `conda update --all` , spyder stopped launching and has the error: Could not initialize GLX.
I have tried adding these lines in start.py
```
import ctypes
ctypes.CDLL("libGL.so.1", mode=ctypes.RTLD_GLOBAL)
from PyQt5 import QtWebEngineWidgets
```

and also  

`export __GLX_VENDOR_LIBRARY_NAME=nvidia`

but none of them works.

I also tried

`conda install qt=5.6.2`

but then I  encounter the segmentation fault.

### What steps reproduce the problem?

1. Create a new environment 
2. Install keras, keras gpu, tensorflow, tensorflow gpu, cudatoolkit and dependencies
3. Conda update --all

## Versions

* Spyder version: 3.2.8
* Python version: 3.6
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: CentOS 7

**Comment by ccordoba12** [comment] 2018-05-19 23:50
Thanks for reporting. This is a duplicate of issue #6968 and it'll be fixed in Spyder 3.3.

> I also tried
>
> conda install qt=5.6.2
>
> but then I encounter the segmentation fault.

The right command is

    conda install qt=5.6* pyqt=5.6*

**Closed by ccordoba12** 2018-05-19 23:50 UTC

**Comment by arnonerba** [comment] 2018-07-20 18:43
This does not appear to be fixed in Spyder 3.3.0. Could this be a Qt issue as noted in #7447?

`conda install qt=5.6* pyqt=5.6*` still works as a temporary fix with Spyder 3.3.0.

**Comment by ccordoba12** [comment] 2018-07-20 18:54
The problem was fixed only for local installations, not for connections over ssh. I think we can't do anything about it.

**Comment by arnonerba** [comment] 2018-07-20 18:56
Darn. I am going to follow up with @bscipio and see if this can be brought to the attention of the Qt maintainers.

**Comment by kentaroy47** [comment] 2019-04-01 02:31
I don't know why, but Spyder 3.3.3(Python 3.6) works ok with ssh -X connections
but fails with the same error with Spyder 3.3.1 (Python3.5)
