### ISSUE TITLE
theano 

### ISSUE THREAD

**Issue by yilye** [spyder-ide/spyder#4827] opened 2017-07-27 14:13 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/ipythonconsole.py", line 895, in set_working_directory
    refresh_console=False)
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/workingdirectory.py", line 286, in chdir
    os.chdir( to_text_string(directory) )
OSError: [Errno 2] No such file or directory: '/home/gln/\xc3\xa6\xc2\x96\xc2\x87\xc3\xa6\xc2\xa1\xc2\xa3/theano'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.17.1 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by dalthviz** [comment] 2017-07-27 17:03
I think this is a duplicate of #4816

**Closed** 2017-07-27 19:53 UTC
Labels: resolution:Duplicate
