### ISSUE TITLE
Variable definitions in help plane with Numpy docstring style is incorrectly displayed

### ISSUE THREAD

**Issue by AJJLagerweij** [spyder-ide/spyder#11232] opened 2020-01-06 08:06 UTC
### What steps will reproduce the problem?

Using a fresh conda environment with spyder the problem can be reproduced by.
1. Import scipy, numpy or create a function with Numpy documentation yourself.
2. Use "Ctrl-i" to obtain the docstring in the help plane.
3. Look at the way the Parameters section is shown.

Example code:

```python
    def example(a):
    """
    Summary of the function.
    
    Explanation of what the function does including method.
    
    Parameters
    ----------
    a : float
        This is a dummy input.
        
    Returns
    -------
    b : float
        This is a dummy output, equal to a.
    """
    b = a
    return b
```

Under the section "Parameters" or "Returns" in the help plane, I see the variable name and its type written together without white space. Like;

Parameters
----------------
**a**float
&nbsp;&nbsp;&nbsp;&nbsp; This is a dummy input.

Returns
-----------
**b**float
&nbsp;&nbsp;&nbsp;&nbsp; This is a dummy output, equal to a.

I can't imagine that it is meant that way.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-24-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-06 14:34
Duplicate of #9888

**Closed by ccordoba12** 2020-01-06 14:34 UTC
