### ISSUE TITLE
Spyder 4.1.2 compatibility issues

### ISSUE THREAD

**Issue by DTKx** [spyder-ide/spyder#12586] opened 2020-05-03 14:00 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Everything started when i trie to debug my code, the debug mode is not being enabled when clicking on the Debug of pressing crtl + f5. 
Alternativelly i have tried to update the Spyder to the latest version thorugh the prompt "conda install spyder=4.1.2" ,however Anaconda presents an issue. and when i try to open again spyder it is not updated.
Then i tried to update conda, and tried to install spyder but there was several compatibility issues

### What steps reproduce the problem?

1. Trying to debug code 
2. Trying to update Spyder through th prompt command "conda install spyder=4.1.2"
3. 

### What is the expected output? What do you see instead?

1. The debug mode
I expect to enter in the debug mode, but the following message appears, instead of the debug mode console:
![image](https://user-images.githubusercontent.com/63344441/80914562-8fee2000-8d4c-11ea-9d8e-7c7ab2fc48d4.png)

1. Trying to update spyder
I was expecting the message update successful, however the following message appeared in the prompt. (Attached)

[prompt_error.txt](https://github.com/spyder-ide/spyder/files/4570571/prompt_error.txt)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder 4.0.1 
* Python version: Version form Anaconda Navigator 1.9.12
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

```

**Comment by goanpeca** [comment] 2020-05-04 01:09
Thanks for reporting @DTKx. This seems to be a duplicate of #https://github.com/spyder-ide/spyder/issues/11986

Closing

**Closed by goanpeca** 2020-05-04 01:09 UTC
