### ISSUE TITLE
numpydocs conventions not rendered in spyder anymore

### ISSUE THREAD

**Issue by ibackus** [spyder-ide/spyder#5240] opened 2017-09-14 21:16 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Write a doc-string following the [numpydocs conventions](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) with sections.  As an example, here is a doc-string I just wrote:
  ```python
    """
    write_table(x, (x1, x2, ...), **kwargs) saves a human-readable ASCII table
    from arrays/SimArrays.
    
    Parameters
    ----------
    x, (x1, x2, ...) : array-like or SimArray or dict
        Data to save.  Must be 1-D or 2-D.  The length of all arrays must
        be the same.  Must be shape (nrow,) or (nrow, ncol).
        x can optionally be a dict of arrays.  The optional args will be
        ignored.
    kwargs 
    ------
    file : str or filepointer
        File or filename to save the table to.
    col_labels : list-like, optional
        Names of the columns.  If x is a dict, then x.keys() is used.  
        Defaults to 0, 1, 2...
    row_labels : list or array-like, optional
        Labels of the rows.  Defaults to 0, 1, 2...
    
    Notes
    -----
    This is NOT optimized for large arrays
    """
  ```
2. View it with the object inspector

**What is the expected output? What do you see instead?**
In spyder, the section heads used to be rendered nicely as a heading.  Now they don't show up at all, e.g.:
![spyder-screen-grab](https://user-images.githubusercontent.com/6054037/30456040-ec8c4c98-9956-11e7-9cc7-0182758df4e1.png)

I'm not sure exactly when this broke.

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.16.2 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.3.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  0.7.6 (OK)
cython >=0.21     :  0.22.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-20 13:27
Closing because we can't reproduce this.

**Closed by ccordoba12** 2017-09-20 13:27 UTC
