### ISSUE TITLE
Treated file as is it had not been previously saved, but it had been. Crashed on overwrite attempt

### ISSUE THREAD

**Issue by asbrownbird** [spyder-ide/spyder#9722] opened 2019-07-01 05:25 UTC
### What steps will reproduce the problem?

(Bug might need to be re-attempted for reproduction)

1. Temporary file is already active in editor.
2. New File is created (via selecting 'New File')
3. Upon first executing script, gets prompt to save the file twice.
4. Script will work if you save the first time, but cancel the second prompt, but will ask to sae upon re-running script.
5. If one tries to overwrite the first save, the program crashes with 'Spyder encountered an internal problem' with a prompt to report the problem.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2450, in run_file
    self.re_run_file()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2471, in re_run_file
    self.save_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2031, in save_all
    self.get_current_editorstack().save_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1799, in save_all
    if self.data[index].editor.document().isModified():
IndexError: list index out of range
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by asbrownbird** [comment] 2019-07-01 05:53
I can confirm the above process will repeat the issue and it was still active at least as of Spyder 3.3.4 (Spyder 3.3.5 is not being found by Anaconda for some reason). The net effect is that it will overwrite the second temporary file with the first temporary file, even though the second one is active, and then simply function as usual after that. I just had an issue where I didn't realise I had an unsaved temporary script and tried to create and save another script.

**Comment by ccordoba12** [comment] 2019-07-01 09:42
This is a duplicate of issue #5996. It only happens on Windows and unfortunately we don't know how to fix it.

**Closed by ccordoba12** 2019-07-01 09:42 UTC
