### ISSUE TITLE
Autoformat uses black instead of autopep8, even if autopep8 is selected.

### ISSUE THREAD

**Issue by felixchenier** [spyder-ide/spyder#17525] opened 2022-03-22 17:16 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [no] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Autoformat uses black instead of autopep8, even if autopep8 is selected.

### What steps reproduce the problem?

1. Select some text
2. Source -> Format file or selection using autopep8

### What is the expected output? What do you see instead?

For the following code, which is pep8 compliant, I would expect no change:

```
def get_impulse(
        participant: str,
        session: str,
        trial: str,
        push: int) -> float:
    """Return the impulses on the specific push."""
    for signal in [
        'Ftot', 'Ftan', 'Frad', 'Fmed', 'Mprop',
        'Anterior', 'Superior', 'Lateral',
        'Flexion', 'Adduction', 'InternalRotation',
    ]:
        pass
```

instead, the code is formatted to:

```
def get_impulse(participant: str, session: str, trial: str, push: int) -> float:
    """Return the impulses on the specific push."""
    for signal in [
        "Ftot",
        "Ftan",
        "Frad",
        "Fmed",
        "Mprop",
        "Anterior",
        "Superior",
        "Lateral",
        "Flexion",
        "Adduction",
        "InternalRotation",
    ]:
        pass
```

which is black format.

## Versions

* Spyder version: 5.1.5
* Python version: 3.8.10
* Qt version: 5.12.9
* PyQt version: 5.12.13
* Operating System name/version: macOS Catalina

### Dependencies

# Mandatory:
```
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  8.1.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.10.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ba-tno** [comment] 2022-03-22 22:04
When I put your example in the [Black Playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHRAPxdAD2IimZxl1N_WlbvK5V9WjpHaG2hkHgbx8D_4AjgK_DvnGpoXhLI5gB0H8JWf0V-DF4PaylYFfnd_VILk_0DIayNi3slK85vgLa_4BHKgxWxbo_5bVfFZzWkctkh0R9dui_7Eg9aBRlpYcvLTEXDQZ3c44TgObNi5ZgP0gxQKkJFW82Tb9TOudLX_EWczSUPukqW1tq9CDqyVbz2xolAvQEDAh9FLymcWthMIU7tMg9N-Fy9Vr-KmvphqCAfeNle2nHPvM1K8UyESTkPo_P0KGj0JtOscCYYXtgKzvOmJQS1FPlWPNkepwUQ5TLuU8E5F0B7fAZZGa4957UqAAAX86RDD2w6cAABmALSAwAA2Ny7xrHEZ_sCAAAAAARZWg==) with the default settings I get the same formatting transformation you see. Is it perhaps expected behaviour of black?

**Comment by ccordoba12** [comment] 2022-03-23 00:31
Hey @felixchenier, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Closed by ccordoba12** 2022-03-23 00:31 UTC

**Comment by felixchenier** [comment] 2022-03-24 02:12
Thank you @ccordoba12 for your detailed answer and commitment. It worked perfectly.

**Comment by ccordoba12** [comment] 2022-03-26 16:43
Great! I'm glad it worked for you.
