### ISSUE TITLE
Run selection (F9) doesn't work with ipdb - but copy/paste from editor to console does

### ISSUE THREAD

**Issue by esskov** [spyder-ide/spyder#2896] opened 2016-01-03 14:17 UTC
When debug execution has stopped at a breakpoint it is common to try out different variations of the code at/after the breakpoint. In doing so it would be very convenient if the Run selection (F9) function was available. I understand this function was made for the IPython console, not ipdb. However, I am able to copy the lines of interest in the editor, then shift focus to the ipdb console and manually paste the lines into the console - where they will execute. It would of course be much more convenient being able to simply press F9, to achieve the same thing. Similarly, the Run cell function would also be very handy when debugging.

Spyder 2.3.8, Windows 64 bit.

**Comment by ccordoba12** [comment] 2016-01-04 03:27
I'm sorry, but not all Python code can be evaluated in `ipdb`. That's the reason we can't activate this option by default.

We'll try to improve the situation for Spyder 4.0. i know this sounds like a long time but we are working on the initial steps to solve this for Spyder 3.0 ;-)

**Comment by bcolsen** [comment] 2017-07-01 06:47
Duplicate of #1073

**Comment by ccordoba12** [comment] 2017-07-01 21:32
Thanks.

**Closed by ccordoba12** 2017-07-01 21:32 UTC
Labels: component:Debugger
