### ISSUE TITLE
how to update spyder4.0 on windows

### ISSUE THREAD

**Issue by MrCrazyCrab** [spyder-ide/spyder#11038] opened 2019-12-12 03:47 UTC
i have update the anoconda to the latest version(1.9.7) on windows10, but i still can not to update spyder to 4.0. However, i can use spder 4.0 on ubunto16.04 when i use the anoconda navigator1.9.7.
So i want to know how to solve the problem?

**Comment by ccordoba12** [comment] 2019-12-12 04:08
Duplicate of #10964

**Closed by ccordoba12** 2019-12-12 04:08 UTC
