### ISSUE TITLE
Cannot connect to remote Kernel from .json

### ISSUE THREAD

**Issue by PascPeli** [spyder-ide/spyder#12137] opened 2020-04-04 13:44 UTC
### What steps will reproduce the problem?

Create a remote kernel on a server.
$ python -m spyder_kernels.console -matplotlib=’inline’ -f=./remotekernel.json

Copy the .json to local machine
$ scp '$username'@'$server':remotekernel.json $HOME/.local/share/jupyter/runtime/

Try to connect to the remote server from Spyder GUI

### Traceback
```python-traceback
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 726, in create_client_for_kernel
    password)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1546, in _create_client_for_kernel
    self.register_client(client)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 918, in register_client
    shellwidget.set_cwd(cwd_path)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/home/ppelitaris/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/home/ppelitaris/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 3.0022647380828857
WARNING:traitlets:kernel died: 3.0000596046447754
WARNING:traitlets:kernel died: 2.9995102882385254
WARNING:traitlets:kernel died: 2.9998650550842285
WARNING:traitlets:kernel died: 2.9992799758911133
WARNING:traitlets:kernel died: 3.0013411045074463
WARNING:traitlets:kernel died: 3.002429485321045
WARNING:traitlets:kernel died: 3.00197434425354
WARNING:traitlets:kernel died: 3.0022332668304443
WARNING:traitlets:kernel died: 3.002182960510254
WARNING:traitlets:kernel died: 3.0022799968719482
WARNING:traitlets:kernel died: 3.0021920204162598
WARNING:traitlets:kernel died: 3.001797914505005
WARNING:traitlets:kernel died: 2.9991555213928223
WARNING:traitlets:kernel died: 2.9999661445617676
WARNING:traitlets:kernel died: 2.9992809295654297
WARNING:traitlets:kernel died: 3.002115488052368
WARNING:traitlets:kernel died: 3.000375509262085
WARNING:traitlets:kernel died: 2.999584674835205
WARNING:traitlets:kernel died: 2.999351739883423
WARNING:traitlets:kernel died: 2.9991843700408936
WARNING:traitlets:kernel died: 2.9995555877685547
WARNING:traitlets:kernel died: 2.9995501041412354
WARNING:traitlets:kernel died: 3.0001375675201416
WARNING:traitlets:kernel died: 3.0015974044799805
WARNING:traitlets:kernel died: 3.0008034706115723
WARNING:traitlets:kernel died: 2.9997174739837646
WARNING:traitlets:kernel died: 3.0020837783813477
WARNING:traitlets:kernel died: 3.0004003047943115
WARNING:traitlets:kernel died: 3.0022246837615967
WARNING:traitlets:kernel died: 2.9993529319763184
WARNING:traitlets:kernel died: 3.0014235973358154
WARNING:traitlets:kernel died: 2.9994380474090576
WARNING:traitlets:kernel died: 3.0021543502807617
WARNING:traitlets:kernel died: 3.0022127628326416
WARNING:traitlets:kernel died: 3.0009682178497314
WARNING:traitlets:kernel died: 2.9993345737457275
WARNING:traitlets:kernel died: 3.002166271209717
WARNING:traitlets:kernel died: 3.0021660327911377
WARNING:traitlets:kernel died: 2.9998674392700195
WARNING:traitlets:kernel died: 2.999384880065918
WARNING:traitlets:kernel died: 3.0012848377227783
WARNING:traitlets:kernel died: 3.001585006713867
WARNING:traitlets:kernel died: 3.001018762588501
WARNING:traitlets:kernel died: 3.002180337905884
WARNING:traitlets:kernel died: 2.999699831008911
WARNING:traitlets:kernel died: 3.002190351486206
WARNING:traitlets:kernel died: 3.0020787715911865
WARNING:traitlets:kernel died: 3.0012519359588623
WARNING:traitlets:kernel died: 2.9995055198669434
WARNING:traitlets:kernel died: 2.9995803833007812
WARNING:traitlets:kernel died: 2.99932599067688
WARNING:traitlets:kernel died: 2.999662399291992
WARNING:traitlets:kernel died: 3.002051591873169
WARNING:traitlets:kernel died: 3.0009069442749023
WARNING:traitlets:kernel died: 2.9994587898254395
WARNING:traitlets:kernel died: 2.9995901584625244
WARNING:traitlets:kernel died: 2.999332904815674
WARNING:traitlets:kernel died: 2.9996514320373535
WARNING:traitlets:kernel died: 2.9995453357696533
WARNING:traitlets:kernel died: 3.0012435913085938
WARNING:traitlets:kernel died: 2.9996273517608643
WARNING:traitlets:kernel died: 2.999335527420044
WARNING:traitlets:kernel died: 2.9995272159576416
WARNING:traitlets:kernel died: 2.9995579719543457
WARNING:traitlets:kernel died: 3.0021886825561523
WARNING:traitlets:kernel died: 3.001490592956543
WARNING:traitlets:kernel died: 3.001624345779419
WARNING:traitlets:kernel died: 3.0014336109161377
WARNING:traitlets:kernel died: 2.999593734741211
WARNING:traitlets:kernel died: 2.99943470954895
WARNING:traitlets:kernel died: 3.0023114681243896
WARNING:traitlets:kernel died: 2.9996166229248047
WARNING:traitlets:kernel died: 2.999677896499634
WARNING:traitlets:kernel died: 2.999323606491089
WARNING:traitlets:kernel died: 3.002199649810791
WARNING:traitlets:kernel died: 2.999814033508301
WARNING:traitlets:kernel died: 3.0007858276367188
WARNING:traitlets:kernel died: 2.9994800090789795
WARNING:traitlets:kernel died: 3.0017685890197754
WARNING:traitlets:kernel died: 3.002173662185669
WARNING:traitlets:kernel died: 3.0021731853485107
WARNING:traitlets:kernel died: 3.0017058849334717
WARNING:traitlets:kernel died: 3.0022034645080566
WARNING:traitlets:kernel died: 3.001851797103882
WARNING:traitlets:kernel died: 2.9994354248046875
WARNING:traitlets:kernel died: 2.9996306896209717
WARNING:traitlets:kernel died: 3.0008952617645264
WARNING:traitlets:kernel died: 3.002063751220703
WARNING:traitlets:kernel died: 3.001530170440674
WARNING:traitlets:kernel died: 3.0021109580993652
WARNING:traitlets:kernel died: 3.002129316329956
WARNING:traitlets:kernel died: 2.9998884201049805
WARNING:traitlets:kernel died: 3.001793622970581
WARNING:traitlets:kernel died: 2.999478816986084
WARNING:traitlets:kernel died: 3.00173020362854
WARNING:traitlets:kernel died: 3.001260280609131
WARNING:traitlets:kernel died: 3.001042366027832
WARNING:traitlets:kernel died: 2.9994003772735596
WARNING:traitlets:kernel died: 2.999471664428711
WARNING:traitlets:kernel died: 2.9995169639587402
WARNING:traitlets:kernel died: 3.001405715942383
WARNING:traitlets:kernel died: 2.9996612071990967
WARNING:traitlets:kernel died: 3.000066041946411
WARNING:traitlets:kernel died: 3.0018036365509033
WARNING:traitlets:kernel died: 2.999539375305176
WARNING:traitlets:kernel died: 3.001415967941284
WARNING:traitlets:kernel died: 3.002213954925537
WARNING:traitlets:kernel died: 3.0017430782318115
WARNING:traitlets:kernel died: 2.999412775039673
WARNING:traitlets:kernel died: 3.0023510456085205
WARNING:traitlets:kernel died: 2.9996068477630615
WARNING:traitlets:kernel died: 3.00144624710083
WARNING:traitlets:kernel died: 2.999587059020996
WARNING:traitlets:kernel died: 2.9995453357696533
WARNING:traitlets:kernel died: 3.001201868057251
WARNING:traitlets:kernel died: 2.999526262283325
WARNING:traitlets:kernel died: 2.9995651245117188
WARNING:traitlets:kernel died: 2.999666690826416
WARNING:traitlets:kernel died: 2.9995481967926025
WARNING:traitlets:kernel died: 3.002223014831543
WARNING:traitlets:kernel died: 3.001443386077881
WARNING:traitlets:kernel died: 3.000673294067383
WARNING:traitlets:kernel died: 3.001185894012451
WARNING:traitlets:kernel died: 2.99953556060791
WARNING:traitlets:kernel died: 3.0004749298095703
WARNING:traitlets:kernel died: 3.0013272762298584
WARNING:traitlets:kernel died: 2.999542474746704
WARNING:traitlets:kernel died: 2.99959397315979
WARNING:traitlets:kernel died: 2.9995579719543457
WARNING:traitlets:kernel died: 3.0022101402282715
WARNING:traitlets:kernel died: 3.0005245208740234
WARNING:traitlets:kernel died: 3.000674247741699
WARNING:traitlets:kernel died: 2.9998042583465576
WARNING:traitlets:kernel died: 2.9992897510528564
WARNING:traitlets:kernel died: 2.999614953994751
WARNING:traitlets:kernel died: 3.0013585090637207
WARNING:traitlets:kernel died: 2.9995105266571045
WARNING:traitlets:kernel died: 3.002202033996582
WARNING:traitlets:kernel died: 2.9995884895324707
WARNING:traitlets:kernel died: 3.0014491081237793
WARNING:traitlets:kernel died: 2.999490737915039
WARNING:traitlets:kernel died: 3.0017831325531006
WARNING:traitlets:kernel died: 3.0021140575408936
WARNING:traitlets:kernel died: 3.0007376670837402
WARNING:traitlets:kernel died: 3.0021812915802
WARNING:traitlets:kernel died: 2.9998772144317627
WARNING:traitlets:kernel died: 2.999265193939209
WARNING:traitlets:kernel died: 2.9995954036712646
WARNING:traitlets:kernel died: 3.001075029373169
WARNING:traitlets:kernel died: 2.999904155731201
WARNING:traitlets:kernel died: 3.001344680786133
WARNING:traitlets:kernel died: 2.9995651245117188
WARNING:traitlets:kernel died: 3.000056743621826
WARNING:traitlets:kernel died: 3.000866413116455
WARNING:traitlets:kernel died: 3.002180337905884
WARNING:traitlets:kernel died: 2.999756336212158
WARNING:traitlets:kernel died: 2.999516487121582
WARNING:traitlets:kernel died: 3.0021567344665527
WARNING:traitlets:kernel died: 3.0003178119659424
WARNING:traitlets:kernel died: 2.9994285106658936
WARNING:traitlets:kernel died: 2.9996771812438965
WARNING:traitlets:kernel died: 3.001774311065674
WARNING:traitlets:kernel died: 2.9995510578155518
WARNING:traitlets:kernel died: 3.00128436088562
WARNING:traitlets:kernel died: 2.9994091987609863
WARNING:traitlets:kernel died: 3.0002031326293945
WARNING:traitlets:kernel died: 2.9995503425598145
WARNING:traitlets:kernel died: 2.9994688034057617
WARNING:traitlets:kernel died: 2.9996707439422607
WARNING:traitlets:kernel died: 2.99930739402771
WARNING:traitlets:kernel died: 2.999920606613159
WARNING:traitlets:kernel died: 3.002197742462158
WARNING:traitlets:kernel died: 2.9998085498809814
WARNING:traitlets:kernel died: 2.9995503425598145
WARNING:traitlets:kernel died: 3.0010933876037598
WARNING:traitlets:kernel died: 2.9994804859161377
WARNING:traitlets:kernel died: 2.999605417251587
WARNING:traitlets:kernel died: 2.9993743896484375
WARNING:traitlets:kernel died: 3.001293897628784
WARNING:traitlets:kernel died: 2.9996650218963623
WARNING:traitlets:kernel died: 2.999540328979492
WARNING:traitlets:kernel died: 3.001103162765503
WARNING:traitlets:kernel died: 3.001185655593872
WARNING:traitlets:kernel died: 2.999528408050537
WARNING:traitlets:kernel died: 3.000739812850952
WARNING:traitlets:kernel died: 3.0020413398742676
WARNING:traitlets:kernel died: 3.0018577575683594
WARNING:traitlets:kernel died: 3.002192497253418
WARNING:traitlets:kernel died: 3.001441240310669
WARNING:traitlets:kernel died: 2.9995813369750977
WARNING:traitlets:kernel died: 3.0006449222564697
WARNING:traitlets:kernel died: 3.0012729167938232
WARNING:traitlets:kernel died: 3.0013186931610107
WARNING:traitlets:kernel died: 2.9991846084594727
WARNING:traitlets:kernel died: 2.9995298385620117
WARNING:traitlets:kernel died: 2.999434232711792
WARNING:traitlets:kernel died: 3.002145290374756
WARNING:traitlets:kernel died: 3.001979351043701
WARNING:traitlets:kernel died: 3.001244068145752
WARNING:traitlets:kernel died: 2.999441385269165
WARNING:traitlets:kernel died: 2.9995505809783936
WARNING:traitlets:kernel died: 2.9992740154266357
WARNING:traitlets:kernel died: 2.9995176792144775
WARNING:traitlets:kernel died: 3.0022215843200684
WARNING:traitlets:kernel died: 3.0013933181762695
WARNING:traitlets:kernel died: 2.9994802474975586
WARNING:traitlets:kernel died: 2.999519109725952
WARNING:traitlets:kernel died: 2.99945330619812
WARNING:traitlets:kernel died: 2.9994988441467285
WARNING:traitlets:kernel died: 2.999591112136841
WARNING:traitlets:kernel died: 3.0022013187408447
WARNING:traitlets:kernel died: 3.0021939277648926
WARNING:traitlets:kernel died: 2.9999351501464844
WARNING:traitlets:kernel died: 2.999887704849243
WARNING:traitlets:kernel died: 3.0021095275878906
WARNING:traitlets:kernel died: 3.000410556793213
WARNING:traitlets:kernel died: 2.999683380126953
WARNING:traitlets:kernel died: 3.0003747940063477
WARNING:traitlets:kernel died: 3.002295970916748
WARNING:traitlets:kernel died: 2.9996232986450195
WARNING:traitlets:kernel died: 2.999464750289917
WARNING:traitlets:kernel died: 2.9995217323303223
WARNING:traitlets:kernel died: 2.999894380569458
WARNING:traitlets:kernel died: 3.000178575515747
WARNING:traitlets:kernel died: 3.0004396438598633
WARNING:traitlets:kernel died: 3.002178907394409
WARNING:traitlets:kernel died: 3.001538038253784
WARNING:traitlets:kernel died: 3.002173662185669
WARNING:traitlets:kernel died: 2.999506711959839
WARNING:traitlets:kernel died: 3.001845121383667
WARNING:traitlets:kernel died: 3.0009539127349854
WARNING:traitlets:kernel died: 3.0022149085998535
WARNING:traitlets:kernel died: 3.0004684925079346
WARNING:traitlets:kernel died: 2.9995100498199463
WARNING:traitlets:kernel died: 2.9994637966156006
WARNING:traitlets:kernel died: 3.0012667179107666
WARNING:traitlets:kernel died: 3.0010828971862793
WARNING:traitlets:kernel died: 2.999562978744507
WARNING:traitlets:kernel died: 3.001342535018921
WARNING:traitlets:kernel died: 3.001509428024292
WARNING:traitlets:kernel died: 3.0018310546875
WARNING:traitlets:kernel died: 3.0004963874816895
WARNING:traitlets:kernel died: 2.9994888305664062
WARNING:traitlets:kernel died: 2.9995152950286865
WARNING:traitlets:kernel died: 2.9995670318603516
WARNING:traitlets:kernel died: 3.0011367797851562
WARNING:traitlets:kernel died: 3.0010387897491455
WARNING:traitlets:kernel died: 2.999507188796997
WARNING:traitlets:kernel died: 3.002187728881836
WARNING:traitlets:kernel died: 3.0015249252319336
WARNING:traitlets:kernel died: 2.9994571208953857
WARNING:traitlets:kernel died: 3.001014232635498
WARNING:traitlets:kernel died: 2.999657154083252
WARNING:traitlets:kernel died: 2.999437093734741
WARNING:traitlets:kernel died: 2.99957537651062
WARNING:traitlets:kernel died: 2.9993491172790527
WARNING:traitlets:kernel died: 2.999866247177124
WARNING:traitlets:kernel died: 3.0010902881622314
WARNING:traitlets:kernel died: 3.00216007232666
WARNING:traitlets:kernel died: 3.001479387283325
WARNING:traitlets:kernel died: 2.9995687007904053
WARNING:traitlets:kernel died: 2.9995036125183105
WARNING:traitlets:kernel died: 2.9994912147521973
WARNING:traitlets:kernel died: 3.001401424407959
WARNING:traitlets:kernel died: 2.999234437942505
WARNING:traitlets:kernel died: 2.999358892440796
WARNING:traitlets:kernel died: 3.4116151332855225
WARNING:traitlets:kernel died: 3.001436233520508
WARNING:traitlets:kernel died: 2.9995219707489014
WARNING:traitlets:kernel died: 3.0000572204589844
WARNING:traitlets:kernel died: 3.002122163772583
WARNING:traitlets:kernel died: 3.0002951622009277
WARNING:traitlets:kernel died: 2.999539375305176
WARNING:traitlets:kernel died: 3.002196788787842
WARNING:traitlets:kernel died: 2.999785900115967
WARNING:traitlets:kernel died: 2.9994263648986816
WARNING:traitlets:kernel died: 2.9995882511138916
WARNING:traitlets:kernel died: 3.0005791187286377
WARNING:traitlets:kernel died: 2.99935245513916
WARNING:traitlets:kernel died: 3.0015296936035156
WARNING:traitlets:kernel died: 3.0014865398406982
WARNING:traitlets:kernel died: 3.0016520023345947
WARNING:traitlets:kernel died: 3.002207040786743
WARNING:traitlets:kernel died: 2.999647855758667
WARNING:traitlets:kernel died: 2.999375343322754
WARNING:traitlets:kernel died: 3.001357316970825
WARNING:traitlets:kernel died: 3.0014002323150635
WARNING:traitlets:kernel died: 3.0009655952453613
WARNING:traitlets:kernel died: 2.999664545059204
WARNING:traitlets:kernel died: 2.999537706375122
WARNING:traitlets:kernel died: 3.0013341903686523
WARNING:traitlets:kernel died: 2.9996371269226074
WARNING:traitlets:kernel died: 2.999387264251709
WARNING:traitlets:kernel died: 3.0006327629089355
WARNING:traitlets:kernel died: 3.0022075176239014
WARNING:traitlets:kernel died: 2.999570846557617
WARNING:traitlets:kernel died: 2.9994921684265137
WARNING:traitlets:kernel died: 3.001697063446045
WARNING:traitlets:kernel died: 2.999335765838623
WARNING:traitlets:kernel died: 2.99953031539917
WARNING:traitlets:kernel died: 3.001983880996704
WARNING:traitlets:kernel died: 3.0013198852539062
WARNING:traitlets:kernel died: 3.0022075176239014
WARNING:traitlets:kernel died: 3.000689744949341
WARNING:traitlets:kernel died: 3.002234935760498
WARNING:traitlets:kernel died: 2.999485492706299
WARNING:traitlets:kernel died: 2.9995622634887695
WARNING:traitlets:kernel died: 2.9992573261260986
WARNING:traitlets:kernel died: 2.999727725982666
WARNING:traitlets:kernel died: 3.000488042831421
WARNING:traitlets:kernel died: 3.0009279251098633
WARNING:traitlets:kernel died: 3.0010523796081543
WARNING:traitlets:kernel died: 2.9995651245117188
WARNING:traitlets:kernel died: 3.002124309539795
WARNING:traitlets:kernel died: 2.999772548675537
WARNING:traitlets:kernel died: 2.9995598793029785
WARNING:traitlets:kernel died: 2.9996111392974854
WARNING:traitlets:kernel died: 2.9994943141937256
WARNING:traitlets:kernel died: 3.0021448135375977
WARNING:traitlets:kernel died: 3.0005300045013428
WARNING:traitlets:kernel died: 2.99957275390625
WARNING:traitlets:kernel died: 2.9994890689849854
WARNING:traitlets:kernel died: 2.9996588230133057
WARNING:traitlets:kernel died: 2.999509572982788
WARNING:traitlets:kernel died: 2.999764919281006
WARNING:traitlets:kernel died: 2.999420404434204
WARNING:traitlets:kernel died: 2.9999098777770996
WARNING:traitlets:kernel died: 2.999459981918335
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-45-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by PascPeli** [comment] 2020-04-04 14:16
Let me know if I can delete great part of the warnings that I think contribute little to the report

**Comment by ccordoba12** [comment] 2020-04-04 16:51
No problem. This is a duplicate of #11889

**Closed by ccordoba12** 2020-04-04 16:51 UTC
