### ISSUE TITLE
code completion inserting () for attribute

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#15118] opened 2021-04-05 17:20 UTC
### What steps will reproduce the problem?

NumPy uses .T for the transpose of an array. 

    r @ p @ r.T
    
When I type the T the editor immediately pops up code completion for this attribute. If you just hit return the editor inserts (), which is incorrect:

    r @ p @ r.T()

So, two things. The parens is wrong, but so is the immediate pop up. You are just typing, and it happens so fast that invalid stuff gets inserted.

Maybe this should be a separate issue, but there is no documentation for the Preferences dialog (that I can find). I can't figure out what set of choices I should use in the completions tab. What is "on the fly" for example? I don't have it turned on, yet this is popping up. I don't get pop ups in other situations, so I can't tell if the pop up for the numpy array is a bug or just what is expected. A few of the choices in the Preferences dialog have hover help, but nothing in the Completion tab has hover help. 

Back to the issue - I also have the "Set completion detail after keyboard idle" set to 500ms. Shouldn't this stop that pop up from happening? It's just not clear to me. 

## Versions

* Spyder version: 4.2.3 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by rlabbe** [comment] 2021-04-05 17:22
![image](https://user-images.githubusercontent.com/5308143/113603366-b8d00280-95f8-11eb-9b36-16fdbaf41827.png)

**Comment by ccordoba12** [comment] 2021-04-05 18:23
Hey @rlabbe, thanks for reporting. This is a duplicate of issue #14307.

**Closed by ccordoba12** 2021-04-05 18:23 UTC

**Comment by rlabbe** [comment] 2021-04-05 18:31
@ccordoba12 Okay, thanks, but that issues doesn't address the lack of documentation, or why the pop up appears instantly. 

In comparison, if I type np.diag on a blank line, the pop up shows up after several seconds - hard to give exact timing since I am using AnyDesk on a remote machine, and things get drawn with a delay sometimes. But it is definitely > 500ms. 

With code snippets turned off, the pop up in the image above still appears instantly.

**Comment by ccordoba12** [comment] 2021-04-05 21:12
Sorry, I just skimmed through the issue too fast.

> but that issue doesn't address the lack of documentation

Please open an issue about that in this repo: https://github.com/spyder-ide/spyder-docs. However, it can take us several months until we address it.

> What is "on the fly" for example?

It means "as you type". You can submit a pull request to change if you find it not clear enough.

> I don't have it turned on, yet this is popping up.

I think the problem is related to the automatic introduction of parenthesis. Please leave a comment about that on issue #14307 so we don't forget to address it as part of that issue.

> With code snippets turned off, the pop up in the image above still appears instantly.

This is strange too. Please also mention it on issue #14307.
