### ISSUE TITLE
Windows 10 Spyder 4.2.0 Launch hangs on "Starting code completion manager..."

### ISSUE THREAD

**Issue by hobosock** [spyder-ide/spyder#14522] opened 2021-01-01 15:06 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 4.2.0 hangs on splash screen at launch (Windows 10), hangs on message "Starting code completion manager...".  Occurs when launching from start menu and from console using "spyder".  When launching with "spyder --debug-info verbose", it hangs on the following line: [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:46624

I have tried launching with Windows Firewall and my anti-virus disabled and the problem still persists.  I have the same version of Anaconda installed on a laptop connected to the same network and Spyder runs just fine.

### What steps reproduce the problem?

1. launch Spyder using start menu shortcut or "spyder" command in console

### What is the expected output? What do you see instead?
Expected Sypder to launch.  Instead, it hangs on splash screen.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Home Version 2004 build 19041.630

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2021-01-01 18:50
Hey @hobosock, thanks for reporting. Do you have a VPN manager or something similar that could be interfering with Spyder trying to open in your computer?

**Comment by hobosock** [comment] 2021-01-01 18:59
No, no VPNs.  This PC is connected by Ethernet cable to my router.

--
Seth Loveall

**Comment by ccordoba12** [comment] 2021-01-01 22:51
Sorry but this is caused by something related to your computer. So you need to keep investigating (I don't have more ideas for you, sorry).

**Comment by yuyahagi** [comment] 2021-02-06 01:32
@hobosock, I had Spyder 4.2.1 hang on the splash screen with "Starting code completion manager..." on Windows 10 too. In my case, uninstalling Kite from Control Panel made Spyder launch again, as discussed in #11597.

The debug info printed some logs about Kite a few lines before `DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:46624`. If you see a similar logs about Kite, you might consider giving it a shot.

~~~
>spyder --debug-info verbose --safe-mode
2021-02-05 17:14:29,363 [INFO] [spyder.app.mainwindow] -> Start of MainWindow constructor
2021-02-05 17:14:29,411 [INFO] [spyder.app.mainwindow] -> appusermodelid: 0
2021-02-05 17:14:29,433 [INFO] [spyder.app.mainwindow] -> End of MainWindow constructor
2021-02-05 17:14:29,859 [INFO] [spyder.app.mainwindow] -> *** Start of MainWindow setup ***
2021-02-05 17:14:29,859 [INFO] [spyder.app.mainwindow] -> Updating PYTHONPATH
2021-02-05 17:14:29,861 [INFO] [spyder.app.mainwindow] -> Applying theme configuration...
2021-02-05 17:14:29,869 [DEBUG] [qdarkstyle] -> Reading QSS file in: :qdarkstyle\style.qss
2021-02-05 17:14:29,871 [INFO] [qdarkstyle] -> QSS file sucessfuly loaded.
2021-02-05 17:14:29,871 [DEBUG] [qdarkstyle] -> Checking patches for being applied.
2021-02-05 17:14:29,876 [INFO] [qdarkstyle] -> Found application patches to be applied.
2021-02-05 17:14:29,954 [INFO] [spyder.app.mainwindow] -> Creating core actions...
2021-02-05 17:14:29,955 [INFO] [spyder.app.mainwindow] -> Creating toolbars...
2021-02-05 17:14:29,958 [INFO] [spyder.app.mainwindow] -> Creating Tools menu...
2021-02-05 17:14:29,979 [INFO] [spyder.app.mainwindow] -> Creating guidata and sift entries...
2021-02-05 17:14:29,983 [INFO] [spyder.app.mainwindow] -> Loading switcher...
2021-02-05 17:14:29,996 [INFO] [spyder.app.mainwindow] -> Loading internal console...
2021-02-05 17:14:30,037 [INFO] [spyder.plugins.console.plugin] -> Initializing...
2021-02-05 17:14:30,617 [INFO] [spyder.app.mainwindow] -> Starting code completion manager...
2021-02-05 17:14:30,793 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering lsp
2021-02-05 17:14:30,793 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering fallback
2021-02-05 17:14:30,795 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Fallback plugin starting...
2021-02-05 17:14:30,837 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering kite
2021-02-05 17:14:30,979 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering snippets
2021-02-05 17:14:30,979 [DEBUG] [spyder.plugins.completion.kite.plugin] -> Kite was found on the system: C:\Program Files\Kite\kited.exe
2021-02-05 17:14:31,792 [DEBUG] [spyder.plugins.completion.kite.utils.status] -> Kite process already running with PID 19744
2021-02-05 17:14:31,793 [DEBUG] [spyder.plugins.completion.kite.client] -> Starting Kite HTTP session...
2021-02-05 17:14:31,797 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:46624
~~~

**Comment by ccordoba12** [comment] 2021-02-06 15:53
Thanks for your help @yuyahagi!

**Comment by ccordoba12** [comment] 2021-02-06 15:54
I'm going to close this issue because there was no answer from @hobosock.

Hopefully @yuyahagi's advice will help to fix the error.

**Closed by ccordoba12** 2021-02-06 15:54 UTC
Labels: status:Awaiting Followup
