### ISSUE TITLE
Editor tabs moving position at edit/save

### ISSUE THREAD

**Issue by LINAK-thlu** [spyder-ide/spyder#22652] opened 2024-10-09 07:38 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have noticed a detail in the user interface that annoys me when i have many files open in the editor. 

Editor tabs move to the right when editing or saving a file. This happens when you have many tabs open and tab scrolling is active. 

When * is added or removed from tab name on edit or save, tab scroll position moves to have the active tab in the rightmost position.

### What steps reproduce the problem?

Screen capture:
https://github.com/user-attachments/assets/ac2d807b-3346-404d-8335-44dac8627de5

### What is the expected output? What do you see instead?

Keep tab scroll position where it is. This is specially annoying when working on and switching between the two last opened files, which I often find myself doing.

## Versions

* Spyder version: 6.0.1  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

**Comment by ccordoba12** [comment] 2024-10-09 16:08
Hey @LINAK-thlu, thanks for reporting. This is a limitation of Qt (the graphical toolkit on top of which Spyder is built) and it's not easy to solve.

We'll try to fix it in a few months, but you can find some workarounds on issue #5459 in the meantime. In addition, since this is basically a duplicate of that issue, I'm going to close it.

**Closed by ccordoba12** 2024-10-09 16:08 UTC

**Comment by LINAK-thlu** [comment] 2024-10-10 06:35
Thank you for quick feedback!

I did not manage to find #5459 when searching the issue list. Sorry for that.
Have implemented the fix to change color in stead of text as suggested. That is perfect for me.

**Comment by ccordoba12** [comment] 2024-10-10 15:26
Great! Glad to know you find that workaround useful.
