### ISSUE TITLE
The kernel is not started!

### ISSUE THREAD

**Issue by kihyungkim** [spyder-ide/spyder#11890] opened 2020-03-19 23:56 UTC
### What steps will reproduce the problem?

Starting Spyder using desktop shortcut.

The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 267, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, env=env, **kw)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 211, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\launcher.py", line 135, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 228, in request_syspath
    interrupt=True, callback=self.sig_show_syspath.emit).get_syspath()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 3.000781297683716
WARNING:traitlets:kernel died: 3.0127196311950684
WARNING:traitlets:kernel died: 3.0052947998046875
WARNING:traitlets:kernel died: 3.0076489448547363
WARNING:traitlets:kernel died: 3.004485845565796
WARNING:traitlets:kernel died: 3.0138072967529297
WARNING:traitlets:kernel died: 3.000969171524048
WARNING:traitlets:kernel died: 3.0016276836395264
WARNING:traitlets:kernel died: 3.000331401824951
WARNING:traitlets:kernel died: 3.004977226257324
ERROR:traitlets:Failed to run command:
['C:\\ProgramData\\Anaconda3\\lib\\site-packages\\spyder\\plugins\\ipythonconsole\\scripts\\conda-activate.bat', 'C:/ProgramData/Anaconda3/Scripts/activate', 'C:/ProgramData/Anaconda3', 'C:\\ProgramData\\Anaconda3\\pythonw.exe', 'C:\\Users\\kimkihy\\AppData\\Roaming\\jupyter\\runtime\\kernel-e5c1b0a316c2.json']
    PATH='C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\PharosSystems\\Core;C:\\Users\\kimkihy\\AppData\\Local\\Microsoft\\WindowsApps;C:\\texlive\\2019\\bin\\win32;'
    with kwargs:
{'close_fds': False, 'stdin': -1, 'stdout': <_io.TextIOWrapper name='nul' mode='w' encoding='cp1252'>, 'stderr': <codecs.StreamReaderWriter object at 0x0000028E93248A08>, 'cwd': None, 'creationflags': 134217728}

WARNING:traitlets:kernel died: 3.010348320007324
ERROR:traitlets:Failed to run command:
['C:\\ProgramData\\Anaconda3\\lib\\site-packages\\spyder\\plugins\\ipythonconsole\\scripts\\conda-activate.bat', 'C:/ProgramData/Anaconda3/Scripts/activate', 'C:/ProgramData/Anaconda3', 'C:\\ProgramData\\Anaconda3\\pythonw.exe', 'C:\\Users\\kimkihy\\AppData\\Roaming\\jupyter\\runtime\\kernel-e449e8c89e3e.json']
    PATH='C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\PharosSystems\\Core;C:\\Users\\kimkihy\\AppData\\Local\\Microsoft\\WindowsApps;C:\\texlive\\2019\\bin\\win32;'
    with kwargs:
{'close_fds': False, 'stdin': -1, 'stdout': <_io.TextIOWrapper name='nul' mode='w' encoding='cp1252'>, 'stderr': <codecs.StreamReaderWriter object at 0x0000028E93221488>, 'cwd': None, 'creationflags': 134217728}

```

## Versions

* Spyder version: 4.1.0 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.8 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-20 02:01
Duplicate of #11819

**Comment by ccordoba12** [comment] 2020-03-20 02:01
Please update to 4.1.1 to get the fix.

**Closed by ccordoba12** 2020-03-20 02:01 UTC
