### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by young-acecrc** [spyder-ide/spyder#6717] opened 2018-03-11 07:46 UTC
### What steps will reproduce the problem?

Launched Spyder in Anaconda2
Opened Tutorial in Help pane,
Opened Tools > Preferences > Help
Selected IPython Console
clicked Apply
Get Spyder has encounteredt an internal problem

### Traceback
```python-traceback
  File "C:\Users\young\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\plugins\configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "C:\Users\young\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\Users\young\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Users\young\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 2.7.13
* Qt 5.6.2
* PyQt5 5.6
* Windows 10

### Dependencies

```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)
```

**Comment by CAM-Gerlach** [comment] 2018-03-11 09:59
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed by CAM-Gerlach** 2018-03-11 09:59 UTC
