### ISSUE TITLE
Kernels fail to start because they can't create stderr files in non-ascii accounts on Windows

### ISSUE THREAD

**Issue by xiaodongxiexie** [spyder-ide/spyder#4836] opened 2017-07-28 06:43 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda2\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 695, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 974, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 995, in connect_client_to_kernel
    stderr_file)
  File "C:\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1384, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Anaconda2\lib\sub

**Comment by ccordoba12** [comment] 2017-07-28 14:06
It seems there's content missing in your error report. Please post the entire error.

**Comment by ccordoba12** [comment] 2017-07-30 15:13
This is probably a duplicate of issue #4816. So I'm closing this issue for now.

**Comment by ccordoba12** [comment] 2017-07-30 15:17
On a second thought, this maybe is caused because you have a user name with non-ascii characters.

We'll take a look at it in a future release.

**Comment by ccordoba12** [comment] 2017-08-19 18:30
@dalthviz, please work on this one.

**Comment by ccordoba12** [comment] 2017-08-19 18:31
I think the idea is (as a test) make the directory where stderr files are created a non-ascii one and see if IPython consoles can start or not using Python 2 (I think they will fail).

Then you need to fix this error.

**Comment by dalthviz** [comment] 2017-08-20 00:38
@ccordoba12  after testing no error appear for the console. It starts normally. 

A screenshot of the path for some of the stderr files of the consoles I created while testing:

![imagen](https://user-images.githubusercontent.com/16781833/29491065-bb6c51c6-8515-11e7-8744-9d76eeec1fb2.png)

**Comment by ccordoba12** [comment] 2017-08-20 02:13
Ok, then please add a test for this please. For the test, please a non-ascii dir with Chinese and Arabic characters.

**Closed** 2017-08-28 21:54 UTC
Labels: component:IPython Console, OS:Windows, type:Bug
