### ISSUE TITLE
Dark syntax coloring  causes printouts to be dark also

### ISSUE THREAD

**Issue by DavidBMartin** [spyder-ide/spyder#13859] opened 2020-09-25 16:27 UTC
## Description

**What steps will reproduce the problem?**

1. Change syntax **coloring** to Spyder Dark
2. print preview only so you don't waste toner
3. Don't print

**What is the expected output? What do you see instead?**
I expect a printout to not have a black background

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.2 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by juanis2112** [comment] 2020-09-25 22:57
Hi @DavidBMartin. Thanks for reporting this. In spyder 4 when printing the preview, I see that the printout doesn't have a dark background. Please update your spyder to our latest version so you can fix your problem.
In your terminal run: 
```
conda update anaconda
conda install spyder=4.1.5
```

**Comment by juanis2112** [comment] 2020-09-27 17:26
Hi @DavidBMartin thanks for opening this. This issue is a duplicate of https://github.com/spyder-ide/spyder/issues/2521. We will take care of this soon.

**Closed by juanis2112** 2020-09-27 17:26 UTC
Labels: status:Awaiting Followup
