### ISSUE TITLE
Python console printing issue

### ISSUE THREAD

**Issue by jaxankey** [spyder-ide/spyder#3867] opened 2016-12-20 21:28 UTC
## Description of your problem

The python console is printing some things incorrectly:

**What steps will reproduce the problem?**

In the python console (not ipython), type
`>>> print("a\nb")`

**What is the expected output? What do you see instead?**

One should see this
```
>>> print("a\nb")
a
b
>>>
```

but I see this:

```
>>> print('a\nb')
a
b>> >


>>> 
```

**Please provide any additional information below**

This issue also leads to strange behavior whenever an exception is raised (sometimes it is only partially printed and I must hit enter a few times to see the rest). This behavior is reproducible across several Windows computers, but behaves correctly on my Linux Mint box (though on linux, the little >>>'s aren't red).

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: Python 3.5 (Anaconda3-4.2.0, 64-bit)
* Operating system: Windows 10

**Comment by ccordoba12** [comment] 2016-12-20 21:29
This is sort of a duplicate of issue #1831.

Please use the IPython Console instead because we're planning to remove the Python console in a future release.

**Closed by ccordoba12** 2016-12-20 21:29 UTC
