### ISSUE TITLE
not able to open the spyder ide after updating to v -5.0 

### ISSUE THREAD

**Issue by gargabhishek100** [spyder-ide/spyder#15122] opened 2021-04-05 20:29 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
the ide should open instead this error shown to me 

(base) C:\Users\hp>spyder
C:\Users\hp\anaconda3\lib\site-packages\spyder\utils\image_path_manager.py:45: UserWarning: The icon located in C:\Users\hp\anaconda3\lib\site-packages\spyder\images\dark\kite.svg is overriding the existing kite
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\hp\anaconda3\lib\site-packages\spyder\app\start.py", line 210, in main
    from spyder.app import mainwindow
  File "C:\Users\hp\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 72, in <module>
    from spyder.app import tour
  File "C:\Users\hp\anaconda3\lib\site-packages\spyder\app\tour.py", line 37, in <module>
    from spyder.utils.qthelpers import add_actions, create_action
  File "C:\Users\hp\anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 34, in <module>
    from spyder.utils.icon_manager import ima
  File "C:\Users\hp\anaconda3\lib\site-packages\spyder\utils\icon_manager.py", line 23, in <module>
    from spyder.utils.palette import QStylePalette, SpyderPalette
  File "C:\Users\hp\anaconda3\lib\site-packages\spyder\utils\palette.py", line 12, in <module>
    from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by gargabhishek100** [comment] 2021-04-05 20:31
just downloaded the anaconda from the website and thereafter used the command 
"conda update anaconda" 
thereafter not able to open the ide

**Comment by gargabhishek100** [comment] 2021-04-05 20:31
in windows 10

**Comment by matheger** [comment] 2021-04-05 20:36
This is already being discussed in #15113

**Comment by ccordoba12** [comment] 2021-04-05 21:00
Hey @gargabhishek100, thanks for reporting. As @matheger said, this is a duplicate of issue #15113.

**Comment by ccordoba12** [comment] 2021-04-05 21:00
The solution for now is to downgrade to Spyder 4.2.5 with the following command

    conda install spyder=4.2.5

**Closed by ccordoba12** 2021-04-05 21:00 UTC
