### ISSUE TITLE
try close empty notebook

### ISSUE THREAD

**Issue by juanodecc** [spyder-ide/spyder#9253] opened 2019-05-02 11:56 UTC
### What steps will reproduce the problem?

I try to close an empty notebook in spyder-notebook. The notebook do not close

### Traceback
```python-traceback
  File "/usr/local/lib/python3.6/dist-packages/spyder_notebook/notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/jpp/.local/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/spyder-jpp/notebooks/untitled1.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/spyder_notebook/notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/jpp/.local/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/spyder-jpp/notebooks/untitled1.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/spyder_notebook/notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/jpp/.local/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/spyder-jpp/notebooks/untitled1.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/spyder_notebook/notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/jpp/.local/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/spyder-jpp/notebooks/untitled1.ipynb'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.7
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Linux 4.15.0-48-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-05-02 15:25
Thanks for reporting. This is a duplicate of https://github.com/spyder-ide/spyder-notebook/issues/194

**Closed by ccordoba12** 2019-05-02 15:25 UTC
