### ISSUE TITLE
Fix SymPy equations being black rather than white with dark theme

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9545] opened 2019-06-10 17:01 UTC

**Comment by oscargus** [comment] 2019-07-30 12:51
Identical to #3798 ?

I have pretty good knowledge how to fix this. But I would need some input on what the best way to fix it from a Spyder perspective (and probably other use cases) is, as it can be done in three different ways which to some extent all will interact. Please see https://github.com/spyder-ide/spyder/issues/3798#issuecomment-514329902.

**Comment by ccordoba12** [comment] 2019-08-16 11:35
Right. Closing as a duplicate of #3798.

**Closed by ccordoba12** 2019-08-16 11:35 UTC
Labels: component:IPython Console, tag:Ui, tag:Ux-usability, type:Bug
