### ISSUE TITLE
Crash while ordering variables

### ISSUE THREAD

**Issue by sebastiancepeda** [spyder-ide/spyder#14789] opened 2021-02-20 21:59 UTC
### What steps will reproduce the problem?

Hi!
This crash happened while ordering the variables in the "Variable explorer" by "Size".
The types of the variables included:
- DataFrame (Pandas)
- str
- _logger.Logger (Loguru)
- ensemble._gb.GradientBoostingClassifier
- tuple
- list
- dict

Regards.

Sebastian Cepeda

### Traceback
```python-traceback
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/envs/data_science/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1675, in lessThan
    return leftData < rightData
TypeError: '<' not supported between instances of 'int' and 'str'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.6.12
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.8.0-43-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.4 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.4.3 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.27 (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.4 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2021-02-21 01:14
Hey @sebastiancepeda, thanks for reporting. This is a duplicate of issue #14527 and it'll be fixed in our next version (4.2.2) to be released this Monday (although it could take a couple of weeks until it's part of Anaconda).

**Closed by ccordoba12** 2021-02-21 01:14 UTC
