### ISSUE TITLE
? wrecks IPython

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14274] opened 2020-11-20 10:25 UTC
[demo.mp4](https://puu.sh/GPpeW/03f9138a0c.mp4) -- also `??`, but not `help()` or `inspect.getsource()`.

**Comment by ccordoba12** [comment] 2020-11-20 14:19
Thanks for reporting @OverLordGoldDragon. You need to press Q to get out of the console's pager (it works the same as a regular terminal pager). 

This is also a duplicate of #14192 and will be fixed in 4.2.1.

**Closed by ccordoba12** 2020-11-20 14:19 UTC
