### ISSUE TITLE
The output of Python console in Spyder error 

### ISSUE THREAD

**Issue by Radiosan** [spyder-ide/spyder#3950] opened 2017-01-12 13:43 UTC
## Description of your problem
The output of Python console in Spyder got strange output

**What steps will reproduce the problem?**

1. Install Anaconda2-4.2.0-Windows-x86.exe
2. Start Spyder
3. Use Python Console

**What is the expected output? What do you see instead?**
Type "55" should be ">>>55", but the result shows "5>> >5",
and type " print "hello" " becomes "hell>> >o".

**Please provide any additional information below**
![2017-01-10 1](https://cloud.githubusercontent.com/assets/25080552/21891858/9af9e604-d90f-11e6-8f32-be399b7d1b30.png)

1.The computer that have output problem it has been installed Python(x,y), then I uninstall it and install Anaconda.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 2.7.12
* Operating system: Win10 64bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-01-12 16:39
Thanks for reporting. This is a duplicate of issue #3938.

**Closed by ccordoba12** 2017-01-12 16:39 UTC
