### ISSUE TITLE
it crashed

### ISSUE THREAD

**Issue by Zwenjay** [spyder-ide/spyder#6225] opened 2018-01-17 01:02 UTC
## Description
 ```python
# Imputer nan in a dataframe, if it is string then replace nan by mode else replace nan by mean
def imputerNan(df):
    col = df.columns
    for c in col:
        if type(df[c][0]) == str:
            replacement = df[c].mode()
        else:
            replacement = df[c].mean
        df[c].fillna(replacement, inplace=True) 


# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('train.csv')
useful_col_train = [2, 4, 5, 6, 7, 9, 11]
useful_col_test = [1, 3, 4, 5, 6, 8, 10]
result_col = 1

X = dataset.iloc[:,  useful_col_train]
y = dataset.iloc[:, result_col]


# Prediction input
X_pred = pd.read_csv('test.csv')
X_pred = X_pred.iloc[:, useful_col_test]

# Imputer Nan
imputerNan(X)
imputerNan(X_pred)
 ```
Run this code and try to look at X in Variable and it crashed

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\printing.py", line 229, in pprint_thing
    result = as_escaped_unicode(thing)
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\printing.py", line 192, in as_escaped_unicode
    result = compat.text_type(thing)  # we should try this first
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\base.py", line 72, in __repr__
    return str(self)
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\base.py", line 51, in __str__
    return self.__unicode__()
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\series.py", line 988, in __unicode__
    max_rows=max_rows, length=show_dimensions)
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\series.py", line 1032, in to_string
    result = formatter.to_string()
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 251, in to_string
    fmt_values = self._get_formatted_values()
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 241, in _get_formatted_values
    float_format=self.float_format, na_rep=self.na_rep)
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1761, in format_array
    return fmt_obj.get_result()
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1781, in get_result

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-17 02:59
Thanks for reporting, although please do not post duplicate reports in the future.

Although I took the time to run your code, including generating a suitable dummy dataset, I was not surprised to be unable to reproduce the error as there appears to be no obvious manipulation that would cause it; rather, it seems to depend entirely on some properties of the training/test csvs which were not provided. Therefore, please provide them or we will not be able to replicate it, and thus this issue will be closed after one week (7 days). 

Also please update to Spyder 3.2.6 to make sure the bug wasn't fixed in that version.

**Comment by CAM-Gerlach** [comment] 2018-01-17 03:04
Furthermore, from the traceback that was provided, it seems to most proximatly be something in pandas, so likely the most we'll be able to do is catch the error, though again, there is no way to know for sure until we can replicate it with your data.

Also, I note that the code as posed above reproduces a ``SettingWithCopy`` warning, which can be fixed by e.g. ``df = df.copy()`` in the first line of your ``imputerNan()`` function. Finally, note that packages like ``scikit-learn`` already provide capable ``Imputer`` infrastructure so you may not want to reinvent the wheel...but that's getting a bit off topic.

**Comment by CAM-Gerlach** [comment] 2018-01-27 00:01
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-01-27 00:01 UTC
Labels: status:AwaitingFollowup
