### ISSUE TITLE
Add support for .editorconfig

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2464] opened 2015-06-02 11:35 UTC
I think it would be a good idea to add native support for editor config using the already existing [python module](https://github.com/editorconfig/editorconfig-core-py). We could bundle the module within spyder in the `external-py...` dirs

I know we could add this as a plugin for spyder, but I think having built-in support would  give Spyder more visibility perhaps?

http://editorconfig.org/#download

**Comment by ccordoba12** [comment] 2015-06-02 13:27
I think @techtonik was interested on this too.

**Comment by techtonik** [comment] 2015-06-03 02:22
Duplicate of #2336. =)

**Comment by Nodd** [comment] 2015-06-03 06:49
I think it fits well as a core functionnality, more than a plugin.
Closing since it's a duplicate.

**Closed by Nodd** 2015-06-03 06:49 UTC
Labels: enhancement
