### ISSUE TITLE
Code Completion and Linting options menu not working properly.

### ISSUE THREAD

**Issue by bw-mutley** [spyder-ide/spyder#16092] opened 2021-07-28 01:43 UTC
### Issue Report Checklist

* [ v ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ v ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ v ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ N/A ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ v ] Tried basic troubleshooting (if a bug/error)
    * [ v ] Restarted Spyder
    * [ v ] Reset preferences with ``spyder --reset``
    * [ v ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ v ] Tried the other applicable steps from the Troubleshooting Guide
* [ v ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I tried to work without completions, but changing the options at the preferences menu didn't work properly.
1) Checking the box "Enable code completion and linting in the editor" makes the menu disappear from Preferences afterwars - had to use spyder --reset to make it reappear. 
2) Clearing Completitions check boxes either has no effect - the completitions menu keeps appearing at the editor - or disables linting.

### What steps reproduce the problem?

1. Open the preferences menu, clear the "enable code completion and linting in the editor", the corresponding submenu will disappear from the preferences menu; In the terminal prompt from which I called the spyder executable, had an warning or error message: 
```
Pruned plugin: outline_explorer
Missing requirement: completions
Restart plugins pruning by REQUIRES check 
```

2. Even before that, unchecking the Completion boxes in the Completions and Linting submenu made the Linting to stop.

### What is the expected output? What do you see instead?
For problem 1), I was expecting the option to be avaialable the Completion and Linting option again;
For problem 2), I was expecting to be able to use code linting without completion.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.5
* Python version: 3.7 and 3.8 (Problem happened with both, in two different environments.
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Linux 4.19.0-9-amd64

### Dependencies

```
PASTE DEPENDENCIES HERE

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.25.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.5 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.18.4 (OK)
pandas >=1.1.1                :  1.0.3 (NOK)
scipy >=0.17.0                :  1.4.1 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment] 2021-07-28 03:11
Hey @bw-mutley, thanks for reporting. You said

> For problem 1), I was expecting the option to be avaialable the Completion and Linting option again;

We're aware of this bug (see issue #15594) and right now we're working to fix it. Unfortunately, it requires a significant overhauling of the way we load and unload plugins in Spyder (see PR 16012), so it'll be available in a couple of months.

> For problem 2), I was expecting to be able to use code linting without completion.

You can do that right now by deactivating the option called `Show completions on the fly`:

![imagen](https://user-images.githubusercontent.com/365293/127257461-b21460fa-95cc-4275-a8f2-f175e4b3161c.png)

That way completions will only appear when you press `Tab` or `Ctrl+Space` in the editor. It's not ideal, but it's the best that we can do at the moment.

**Comment by ccordoba12** [comment] 2021-07-28 03:11
I'm going to close this as a duplicate of #15594 because it's basically the same problem.

**Closed by ccordoba12** 2021-07-28 03:11 UTC

**Comment by bw-mutley** [comment] 2021-07-28 23:37
thanks for the reply, and sorry for not finding it among the reported issues. Just as side note, your suggestion of deactivating "Show completions on the fly" didn't work for me, completions kept appearing. But that's ok, I can change the other options in order for now.
