### ISSUE TITLE
Can't copy & paste within Spyder

### ISSUE THREAD

**Issue by rgrigonis** [spyder-ide/spyder#2705] opened 2015-09-21 17:43 UTC
I'm using Spyder with the latest 64bit WinPython. 
I highlight a line of code, copy it, but it won't paste anywhere inside Spyder. 
However, if I switch to Notepad, I can paste it there. 
Even more strangely, if I now switch back to Spyder, I can hit Ctrl-V and the code will now successfully paste in Spyder!  
Also, anything I hightlight and copy outside of Spyder can be pasted in Spyder. Odd.

**Comment by ccordoba12** [comment] 2015-09-21 19:27
@stonebig, any input on this one?

**Comment by stonebig** [comment] 2015-09-21 19:33
Hi @rgrigonis. Please specify:
- the exact version of Winpython you are using, (latest is not enough)
- the exact version of your OS.
- a screenshot of the action, to be sure I understand well what you mean.

**Comment by rgrigonis** [comment] 2015-09-21 20:18
Okay,

The version of WinPython I'm using is...:

*WinPython-64bit-3.4.3.5Qt5.exe   Modified 2015-08-09*

The version of Windows I am using is....:

*Windows 7 Professional*
*Service Pack1*

Running on a Dell Optiplex 9010 with an Intel Core i7-3770 CPU @ 3.40 GHz
8.00 GB RAM
64-bit operating system

Here is some code loaded into Spyder:

[image: Inline image 1]

*Let's highlight and copy a line of code (line 16)...*

[image: Inline image 2]


Let's place the cursor on line 18 and Paste, but nothing happens...

[image: Inline image 3]

Let's highlight and copy line 16 again, but this time instead of trying to
Paste within Spyder,
let's go to another window with Notepad running and Paste over there and
see what happens...

[image: Inline image 4]

and there it is!

Now, having successfully pasted the code copyied from Spyder into Notepad,
let's switch
back to Notepad and try to paste that same code in the clipboard into line
18 like we wanted
to do to begin with....

[image: Inline image 5]

And there it is!

Spyder will let me copy code but not paste it within Spyder, *unless* I
paste it somewhere else (e.g. Notepad) first...!

Strange but true.










Richard Grigonis
Newsmax Media, Inc.
www.newsmax.com

 P.O. Box 20989
West Palm Beach, FL 33416
(561) 686-1165 ext. 7740
(561) 886-1064 Fax

**Comment by stonebig** [comment] 2015-09-22 05:29
That was made with spyder3.0 dev of July 31th.
Trying with current winpython + more recent spyder 3.0 dev  I don't reproduce yet.
==> can you paste your exact code on github (instead of a screenshot) ?

**Comment by rgrigonis** [comment] 2015-09-22 16:34
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
from urllib.request import urlopen
from urllib.error import HTTPError
from bs4 import BeautifulSoup

websource = [["Test", "http://www.pythonscraping.com/pages/page1.html"]]

websource.append(["The Hill", "http://www.thehill.com"])


for x in websource:
    current_name=x[0]
    current_HTML=x[1]
#    print(current_name)
#    print(current_HTML)

    try:
        HTML = urlopen(current_HTML)
    except HTTPError as e:
        print(e)
        #return null, break, or do someother "Plan B"
    else:
        #program continues. Note: if you return or break in the
        #exception catch, you do not need to use the "else" statement
        bsObj = BeautifulSoup(HTML.read(), "lxml")
        title = bsObj.h1
        if title == None:
            print ("Title could not be found")
            print ("There is a problem with"+ current_name)
        #print the title of the webpage
        else:
            print(title)


Richard Grigonis
Newsmax Media, Inc.
www.newsmax.com

 P.O. Box 20989
West Palm Beach, FL 33416
(561) 686-1165 ext. 7740
(561) 886-1064 Fax

**Comment by stonebig** [comment] 2015-09-22 16:52
well... apparently it works on my PC with same configuration.... didn't you activate an syntax analyzer or something ?

**Comment by rgrigonis** [comment] 2015-09-22 17:06
Interestingly it took me a few tries to paste it in gmail. Much easier to
paste it into Notepad, for what's that worth. Perhaps I should just
retrofit the latest Spyder in WinPython, if that's possible.

Richard Grigonis
Newsmax Media, Inc.
www.newsmax.com

 P.O. Box 20989
West Palm Beach, FL 33416
(561) 686-1165 ext. 7740
(561) 886-1064 Fax

**Comment by stonebig** [comment] 2015-09-22 17:07
ah, if you pasted it via gmail, that could explain

**Comment by stonebig** [comment] 2015-09-22 17:24
Spyder dev. wheel  of September 19th
//
// File Checksum Integrity Verifier version 2.05.
//
        MD5                SHA-1
-------------------------------------------------------------------------
b9a1465be5d5d72bee2757e972070517 d72d5eaa2de77bb754a8ac67ae634d28e4b08058  spyder-3.0.0.dev0-py2.py3-none-any.whl

https://groups.google.com/group/winpython/attach/fc8a79c99f4a3/spyder-3.0.0.dev0-py2.py3-none-any.whl?part=0.1&authuser=0

**Comment by stonebig** [comment] 2015-09-22 17:25
then remove spyder and install the new wheel. I'm not sure it will resolve your 'strange' issue

**Comment by rgrigonis** [comment] 2015-09-22 17:45
The new Spyder didn't resolve it, but I'm becoming adept at pasting into
Notepad first <ho-ho>.

Richard Grigonis
Newsmax Media, Inc.
www.newsmax.com

 P.O. Box 20989
West Palm Beach, FL 33416
(561) 686-1165 ext. 7740
(561) 886-1064 Fax

**Comment by stonebig** [comment] 2015-09-22 17:51
sorry I've no more clue. The Qt5 branch and associated Spyder 3.0dev may have some rough corner cases, but I don't see what could make your pc so special. maybe we have to wait someone else complain of the same thing to get more inputs

**Comment by rgrigonis** [comment] 2015-09-22 17:56
I've got three monitors here on my corporate LAN PC, maybe clipboard memory
is being stolen / interfered with somehow.

Richard Grigonis
Newsmax Media, Inc.
www.newsmax.com

 P.O. Box 20989
West Palm Beach, FL 33416
(561) 686-1165 ext. 7740
(561) 886-1064 Fax

**Comment by stonebig** [comment] 2015-09-22 18:11
that's an easy test: unplug 2 of them and retry.

**Comment by kztd** [comment] 2017-01-26 17:44
Same problem here.  I think all was fine before I started working with a big file in pandas (about 5mb).

I restarted spyder, and the problem persisted until I tried using edit->copy and edit->paste from the menu and it started working again.

---------------------------
About Spyder
---------------------------
<b>Spyder 3.0.2</b> 
            <br>The Scientific PYthon Development EnviRonment
            <br>Copyright &copy; The Spyder Project Contributors
            <br>Licensed under the terms of the MIT License
            <p>Created by Pierre Raybaut.
            <br>Developed and maintained by the
            <a href="https://github.com/spyder-ide/spyder/blob/master/AUTHORS">Spyder Project Contributors</a>.
            <br>Many thanks to all the Spyder beta testers and regular users.
            <p>For bug reports and feature requests, please go
            to our <a href="https://github.com/spyder-ide/spyder">Github website</a>. For discussions around the
            project, please go to our <a href="http://groups.google.com/group/spyderlib">Google Group</a>
            <p>This project is part of a larger effort to promote and
            facilitate the use of Python for scientific and engineering
            software development. The popular Python distributions
            <a href="http://continuum.io/downloads">Anaconda</a>,
            <a href="https://winpython.github.io/">WinPython</a> and
            <a href="http://python-xy.github.io/">Python(x,y)</a>
            also contribute to this plan.
            <p>Python 2.7.12 64bits, Qt 5.6.0, PyQt5 5.6 on Windows
            <p><small>Most of the icons for the Spyder 2 theme come from the Crystal
            Project (&copy; 2006-2007 Everaldo Coelho). Other icons for that
            theme come from <a href="http://p.yusukekamiyamane.com/"> Yusuke
            Kamiyamane</a> (all rights reserved) and from
            <a href="http://www.oxygen-icons.org/">
            The Oxygen icon theme</a></small>.
            
---------------------------
OK   
---------------------------

**Comment by goanpeca** [comment] 2017-01-26 17:48
@andfoy ?

**Comment by chandanshikhar1** [comment] 2017-03-20 03:44
It is same problem for me with mac os

**Comment by ccordoba12** [comment] 2017-08-13 18:04
Closing because we're unable to reproduce this, sorry.

**Closed by ccordoba12** 2017-08-13 18:04 UTC
Labels: component:Editor, type:Bug

**Comment by Metete** [comment] 2018-11-25 12:17
I am having the same problem on linux mint

**Comment by evemilano** [comment] 2019-11-18 08:57
Same problem for 64 bit version.
Holy shit a ide that has problem with copy-paste...

**Comment by breannashi** [comment] 2022-12-15 01:37
same issue linux

**Comment by Rahman2206** [comment] 2023-04-22 09:33
Got sanme issue on Windows 11

**Comment by AntoonGa** [comment] 2023-09-18 11:23
same issue win11

**Comment by lhfy127** [comment] 2023-12-15 04:05
same issue with win11. But it does not happen all the time. Just sometimes it shows up and stay, then it is able again after a while

**Comment by mihirus** [comment] 2023-12-29 14:40
Same issue on Ubuntu 22.04. Occurs specifically for jupyter notebooks. I copy text from a notebook cell but cannot paste into any notebook cell. I'm having to paste into a regular editor, then copy from there and paste into the desired notebook cell.
