### ISSUE TITLE
Spyder 5: Code folding triangle disappeared

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#15230] opened 2021-04-10 16:42 UTC
This only happened once and I can't reproduce it, but it's a serious enough bug that I ought to report it.

Some of my code accidentally got folded in the Spyder editor, probably because I clicked on the fold-code triangle when meaning to set a breakpoint.

But the little triangle that's supposed to indicate invisible (folded) code didn't show up, or disappeared later.

Took me 2 hours to figure out what was wrong with my code - it was hidden code doing stuff. Eventually I opened the file in another editor and figured it out. (Exiting and restarting Spyder fixed it.)

**Comment by ccordoba12** [comment] 2021-04-10 16:53
Hey @nerdfever, thanks for reporting. Please let us know if you're able to come up with a reproducible use case. Otherwise we'll have to close this issue because there's not enough information to fix it.

**Comment by nerdfever** [comment] 2021-04-10 16:53
I know. I wanted to warn others, in case it happens to them. Try re-loading the file into the editor.

**Comment by steveSchneider2** [comment] 2021-04-10 20:33
I also have code folding issue. The triangles are not visible in ANY of my files.  I AM able to turn on/off the code folding 'column'  via the Source menu.  This happened the first time i install 5.0.  It happens with every attempt to use 5.0.  I can and have switched back to 4.25... (where folding works), then back to 5.0 where it doesn't.
Spyder 4.15 is in my base(root) configuration...and the code folding triangles are there and they operate.
Upon opening 5.0, i get the "Spyder_kernels >=2.0 ... (NOK)" message, but am ignoring that based on someone's comment in another thread.  
I am running Windows 10 Pro, Anaconda, Python 3.8 & Python 3.9
To fix this i tried uninstall & re-install anaconda, to no avail.  Can i provide any further information?

![image](https://user-images.githubusercontent.com/46175807/114283824-c7b01e00-9a19-11eb-90e8-89a20e85f04c.png)

**Comment by VittorioGiammarino** [comment] 2021-04-12 13:55
I get the same problem

**Comment by ccordoba12** [comment] 2021-04-19 01:22
Although it's not the same problem, I'm going to close this issue as a duplicate of #15139 because I think it's related to Kite.

For now, please deactivate Kite in

    Tools > Preferences > Completion and linting > General

That should help.

**Closed by ccordoba12** 2021-04-19 01:22 UTC
Labels: status:Awaiting Followup

**Comment by ahuard0** [comment] 2021-09-09 10:49
I don't have Kite installed and I still get the code folding issue.

**Comment by Whiax** [comment] 2021-09-19 22:19
> I don't have Kite installed and I still get the code folding issue.


Ok I had the same issue and checked the code of Spyder, it seems that you need to activate LSP. 

```
Tools > Preferences > Completion and Linting > Providers > Enable LSP
Reboot Spyder
```

Maybe it could write "Show code folding (requires LSP)" or display an error message when activate code folding with LSP desactivated

**Comment by ahuard0** [comment] 2021-09-20 10:42
I did a full reinstall to resolve the problem (including reset spyder settings), and my fresh install does have "Enable Language Server Protocol (LSP) provider" checked.  Code folder is working normally for me after my fresh reinstall.

**Comment by ccordoba12** [comment] 2021-09-20 14:10
@Whiax, I totally agree with you. The LSP control's several elements that you wouldn't consider related to code completion and linting at first sight: code folding, indent guides and symbols in the Outline pane.

Please open a new issue so we don't forget to address that in a future release.
