### ISSUE TITLE
Se bloquea Spyder

### ISSUE THREAD

**Issue by jaosunitagithub** [spyder-ide/spyder#11454] opened 2020-02-02 09:21 UTC
### What steps will reproduce the problem?

With some files opened with Spyder, Spyder goes slowly and then, crack.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: 'C:\\Users\\Usuario\\.spyder-py3\\autosave\\numpy_08_matrices.py'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.10.2 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5 (OK)
```

**Comment by ccordoba12** [comment] 2020-02-02 12:16
Did you remove this file outside Spyder? 

    numpy_08_matrices.py

**Comment by jaosunitagithub** [comment] 2020-02-02 13:34
Yes, I removed it ! Spyder crashed when I was coding with "numpy_08_matrices.py".

**Comment by ccordoba12** [comment] 2020-02-03 18:08
I can't reproduce this problem on Linux. @dalthviz, could you try this on Windows?

**Comment by dalthviz** [comment] 2020-02-03 19:10
@ccordoba12 I'm also unable to reproduce this but, while I was trying, #11447 poped up

**Comment by ccordoba12** [comment] 2020-02-03 22:49
Closing for now then.

@jaosunitagithub, please reopen if/when you can give us a simple and way to reproduce this.

**Closed by ccordoba12** 2020-02-03 22:49 UTC
Labels: status:Awaiting Followup
