### ISSUE TITLE
Completion and linting not working

### ISSUE THREAD

**Issue by pachu-um** [spyder-ide/spyder#16098] opened 2021-07-28 16:49 UTC
### Issue Report Checklist

* [* ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ *] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ *] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ *] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [* ] Reset preferences with ``spyder --reset``
    * [* ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [* ] Tried the other applicable steps from the Troubleshooting Guide
* [ *] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Completion and linting in the editor for python files will not work in the current session or stopped working
To try to fix this please verify that your firewall or antivirus allows python processes to open ports or restart spyder

### What steps reproduce the problem?

1. open spyder 
2. 
3. 

### What is the expected output? What do you see instead?
Completion is not working

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
<!--- Copy from error dialog or View > Panes > Internal Console --->
Completion and linting in the editor for python files will not work in the current session or stopped working
To try to fix this please verify that your firewall or antivirus allows python processes to open ports or restart spyder
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.10 64 bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64 bit

### Dependencies

```
PASTE DEPENDENCIES HERE

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.5 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment] 2021-07-28 17:46
Hi @pachu-um thank you for the feedback, as the message says there is most probably a problem with your firewall or antivirus preventing the process used for Spyder to give completions to start. Did you try to check already your firewall/antivirus to allow python process as the message says? A simple way to test if the problem is actually related to your firewall or antivirus is to disable them **momentarily** and launch again Spyder. If completions work then you need to add the exceptions rules for either your firewall, your antivirus or both. 

Also, you could check some documentation we have regarding completion or help not working and a way to try to restart the service from a running Spyder instance: https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#completion-help-not-working

Let us know if something of the above helps :)

**Comment by pachu-um** [comment] 2021-07-28 18:22
Dear Daniel Althviz More,
       thanks for the reply... I did set the firewall access..i don't have any antivirus installed.
But i noticed that the LSP Python is down... If i try to restart, it kind of hangs... it doesnt get restarted. 
When i restart spyder, it try to restart the LSP and fails and show the message "LSP Python down", post this, i get the completion and linting error box
As per the link shared above i try to update the python-language-server, but i got the message saying , all packages required are already installed.

thanks and regards

**Comment by dalthviz** [comment] 2021-07-29 07:28
Thank you for the info @pachu-um maybe you need to check [Windows Security/Defender then (the built-in element that includes an 'antivirus' on Windows 10)](https://support.microsoft.com/en-us/windows/stay-protected-with-windows-security-2ae0363d-0ada-c064-8b56-6a39afb6a963). Also, did you install Spyder with the Anaconda distribution and a normal user or a user with administrator rights?

Let us know!

**Comment by pachu-um** [comment] 2021-07-29 08:48
Dear Daniel,
      I have attached the firewall picture... the firewall is turned off
And regarding anaconda installation, i guess i was logged in as admin when i installed. But is there a way to check it ? 

![Windows Firewall](https://user-images.githubusercontent.com/24447684/127461806-7aa23ba5-48e3-4c39-a929-5c98671a8665.PNG)

**Comment by dalthviz** [comment] 2021-07-29 09:52
Thanks for the screenshot @pachu-um however besides the firewall configuration that you showed there is another view related with the security and the built-in antivirus that is included with Windows 10: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus?view=o365-worldwide could you check there is there is more settings you need to put in place? 

Regarding the admin rights then maybe you could try to launch Spyder with admin privileges but I think in the long term will be better to check the proper configuration to allow the completion process (firewall and antivirus exceptions).

Let us know :)

**Comment by pachu-um** [comment] 2021-07-30 16:57
Dear Daniel,
        I took some time, discussed with our IT team and got it checked, there seems to be no blocking in firewalls or antivirus. 
Not sure how to proceed now... any other logs that i could share ? 
please do let me know ,
thanks and regards

**Comment by dalthviz** [comment] 2021-07-30 17:17
@pachu-um maybe you could try to run in debug mode and send us the logs.

For that please run from an Anaconda Prompt (with the env were you have Spyder activated) Spyder with the `debug-info` and `debug-output` flags. 

Something like: 
* To see the log in the console:
    
          spyder --debug-info verbose

* To see the log in the console and save it in a `spyder-debug.log` file in the current directory were the console is:
    
          spyder --debug-info verbose --debug-output file

That should let you see a log and maybe a traceback will appear regarding the completion process not being able to start

**Comment by pachu-um** [comment] 2021-07-30 17:29
Dear Daniel,
      I found something in another post
https://github.com/spyder-ide/spyder/issues/12904
i ran a conda list and found that some of the packages are installed using pip
So i created a new environment and install spyder using conda list . Now the completion and linting error does not come and am also able to see the completion... 
thanks for your support... 
Best regards

**Comment by dalthviz** [comment] 2021-08-01 14:23
Thanks for the feedback @pachu-um ! Indeed mixing packages (pip installed vs conda installed) can cause things to not work properly. Glad is working for you now, will close this then :)

**Closed by dalthviz** 2021-08-01 14:23 UTC
Labels: resolution:Completed
