### ISSUE TITLE
No autocompletion - suggestion on spyder 3.2.0

### ISSUE THREAD

**Issue by yaceben** [spyder-ide/spyder#4951] opened 2017-08-12 23:42 UTC
Autocompletion does not work for any libraries for me, precompiled or otherwise, e.g. hashlib, numpy, pattern, numpy, nltk, etc.

Furthermore, CTRL+i does not work in editor window.

**What steps will reproduce the problem?**

1. `import somelib`
2. `somelib.` nothing shows up

**What is the expected output? What do you see instead?**
autocompletion/intellisence suggestions

## Versions and main components

* Spyder Version: 3.2.0 installed through pip
* Python Version: 2.7.13 64bits
* Qt Version: 5.6.2
* PyQt Version: 5 5.6 
* Operating system: Linux 64bits (Fedora 24)

IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
numpy >=1.7       :  1.11.0 (OK)
pandas >=0.13.1   :  0.18.0 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.0 (OK)

Did not try Python 3.5 yet as pattern library is incompatible.

**Comment by ccordoba12** [comment] 2017-08-13 03:16
Sorry, I don't know what's happening in your case.

**Comment by Alex-89** [comment] 2017-08-14 11:08
Hello I have a similar problem in Anaconda.

I have problems only with the library Pyomo. At any other library working the autocomplete function.

My configuration in Anaconda shows like  following:

- to create a virtuell envirnoment in anaconda (with: conda create -n oemof python=3.4 pip)
-to call the oemof envirnoment in the anaconda promp(with: "activate oemof")
-to install spyder (with: "conda install spyder")
-to install oemof (with: "pip install oemof")
-to install the cbc-Solver (put the cbc.exe in the oemof path)
-to install oemof.db (with "pip install -e git://github.com/oemof/oemof.db.git@master#egg=oemof.db"
-to install pyomo (with: "conda install -c conda-forge pyomo")

It's is how i decripe, only the library Pyomo don't find by Spyder. Variables and any other libarys haven't any problem.

Gives any configuration in Spyder that I have to set up?

Regards
Alex

**Comment by ccordoba12** [comment] 2017-08-14 13:43
@Alex-89, code completion in the Editor doesn't work for all modules (unfortunately). This is not a bug in Spyder but a limitation in Python itself, sorry.

I'm closing this issue as a duplicate of issue #4410.

**Closed by ccordoba12** 2017-08-14 13:43 UTC
Labels: resolution:Duplicate
