### ISSUE TITLE
Spyder unresponsive, requires forced quit (OS X)

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3306] opened 2016-07-19 22:31 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder 3.0.0beta4 (anaconda installation on OS X 10.11.5)
2. Start using the console
3. Stop input for the machine so that the screensaver/lockout occurs
4. Upon login the Spyder console is unresponsive and I get a rainbow spinning wheel of death
5. The only option is to terminate the inactive session (force quit on OS X)
![deadspyder](https://cloud.githubusercontent.com/assets/3229632/16968764/beebce22-4dc5-11e6-8203-16a5decd6a04.png)

## Versions and main components

* Spyder Version: 3.0.0beta4
* Python Version: Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)
* Operating system: OS X 10.11.5

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.9.2 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  None (NOK)
PyQt = 5.6
Qt = 5.6.0

**Comment by Keou0007** [comment] 2016-07-22 01:20
I have experienced the exact same issue repeatedly. Something I can add is that when I'm using matplotlib, there is an extra icon that shows up in the dock (just named "python") which is where the figure windows go. When I checked thismorning after sleeping the computer overnight, I had the spinning wheel issue, but I also had three instances of the matplotlib icon in the dock for some reason.

**Comment by ccordoba12** [comment] 2016-07-22 14:34
This was supposedly fixed in beta4, but that doesn't seem to be the case.

Something you can do to help us solve this problem is to open Spyder from a terminal, but *not* as a background process, i.e. as

    spyder

instead of

    spyder &

Then when the freeze occurs, you need to press `Ctrl+C` in the terminal. This should generate a traceback in Spyder's internal console, which you can copy and paste here.

**Comment by qingkaikong** [comment] 2016-07-23 16:05
This is the traceback after I press Ctrl+C, but due to the IDE frozen, I can not scroll up, so I just took a screenshot here:

<img width="599" alt="screen shot 2016-07-23 at 9 02 37 am" src="https://cloud.githubusercontent.com/assets/1621324/17078888/941adc1e-50b4-11e6-8cf7-3214857f30db.png">

**Comment by ccordoba12** [comment] 2016-07-23 16:07
@blink1073, could you take a look at this one? This is the same problem as before :-)

**Comment by Keou0007** [comment] 2016-07-24 08:51
I got exactly the same traceback, using 3.0.0b4
Same deal, spinning wheel meant I couldn't scroll or copy/paste the traceback.

Also, I got this error in the terminal after the first ctrl-c

`^CJul 24 18:43:24  python[92786] <Warning>: void CGSUpdateManager::log() const: conn 0x31c9f: spurious update.`

**Comment by blink1073** [comment] 2016-07-26 00:19
I am unable to reproduce this from either the latest master or `v3.0.0b4`.  I can hit Ctrl+C just fine in the terminal when run as `bootstrap.py` or using the `spyder` command, and a forced sleep/wake up has no effect.  I am using Python 3.4.5 anaconda on OSX 10.11.6.  My pyzmq is `v15.3.0`.

**Comment by blink1073** [comment] 2016-07-26 00:23
Also tried with Python 2.7.11.  @ccordoba12, can you reproduce?

**Comment by Keou0007** [comment] 2016-07-26 00:42
My experience is that this behaviour takes a bit of time to kick in. If you can't reproduce from a sleep/wake, my suggestion would be to leave spyder running overnight in the background and check it in the morning. My reproducible steps are:
1. Open spyder
2. sleep computer overnight
3. wake computer in morning
4. spinning wheel on spyder, if run from terminal, ctrl-c in terminal produces the traceback above in the internal console window in spyder, and then the spinning wheel comes back.

I'm running 3.0.0b4 with python 3.5.2 and ipython 4.2.0 (latest anaconda update) on OSX 10.11.5

**Comment by blink1073** [comment] 2016-07-26 00:54
Thanks @Keou0007, I'll try that tonight.

**Comment by ccordoba12** [comment] 2016-07-26 01:16
Hey guys, could you update to Spyder master and try again? We just merged pull request #3325, which could help to solve this problem.

Thanks ;-)

**Comment by blink1073** [comment] 2016-07-26 10:19
I ran it overnight with #3325 applied.  The program was still responsive, but the introspection itself was not working, and repeatedly printing the message below.   I'm not yet sure what to do about it.

```
Resource temporarily unavailable
Errored rope
b''
b''
Resource temporarily unavailable
Errored jedi
b''
b''
Resource temporarily unavailable
Errored fallback
b''
b''
```

**Comment by Keou0007** [comment] 2016-07-26 12:49
I'm on beta 4, installed via conda. I can't seem to find a way to install the github master through conda. Am I missing something?

**Comment by blink1073** [comment] 2016-07-26 13:10
Hi @Keou0007, conda is for released bundles only.  Using a git checkout is an entirely different process.   You `git clone` this repository, then run `python bootstrap.py` from the repository directory to run that version of spyder.

**Comment by Keou0007** [comment] 2016-07-26 13:27
I figured it would be something like that, thanks. Done it now. I'll leave it overnight and see what happens.

**Comment by jiangxiluning** [comment] 2016-07-28 01:59
I tried to launch spyder directly in terminal. Sometime it gave me
`QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)`

**Comment by ccordoba12** [comment] 2016-07-28 04:25
That's unimportant and not relevant to this issue.

**Comment by jiangxiluning** [comment] 2016-07-28 04:30
all right, I will keep tracking it.

**Comment by ccordoba12** [comment] 2016-07-28 14:29
Could anyone else confirm that this issue is fixed in master?

**Comment by jiangxiluning** [comment] 2016-07-28 14:32
I can't sure. Because some lags happened when I launched it within the anaconda navigator, but not in terminal.

**Comment by massimocaccia** [comment] 2016-07-28 17:33
I was experiencing this bug on beta3.
Got beta4 yesterday, and it seems to be fine now :)

**Comment by Keou0007** [comment] 2016-07-28 23:29
I have left the master overnight and come back to it responsive. This is an obvious improvement over beta 4, BUT I've had problems loading scipy with the master, so I haven't been able to do any actual work with it, just open it and let it sit. As such, I'd be hesitant to say for certain that it's fixed, incase it is something else I usually load up (scipy, Numpy, matplotlib, seaborn, etc) that's also causing the issue.

**Comment by ccordoba12** [comment] 2016-07-28 23:47
> BUT I've had problems loading scipy with the master

Please open a new issue about this.

**Comment by ccordoba12** [comment] 2016-07-29 00:21
> I have left the master overnight and come back to it responsive.

Given this confirmation (besides the one from @blink1073), I consider this issue solved.

**Closed by ccordoba12** 2016-07-29 00:21 UTC
Labels: OS-MacOS, Type-Bug

**Comment by blink1073** [comment] 2016-07-29 00:44
The behavior I'm seeing is that the introspection can fail, but it is no longer bringing down the application.  At least you can save state and restart to get introspection back. I'll dig some more to see if I can eke out more stability.

**Comment by ccordoba12** [comment] 2016-07-29 00:50
Thanks @blink1073! I hope you can find time to work on this soon because I'm thinking to release beta5 after you solve the bug about introspection not working on Mac after resumes (I can confirm this is not a problem on Windows and Linux).

There are already important issues already solved in master (e.g. profiler is missing in beta4) that deserve a new beta :-)

**Comment by mrntidu** [comment] 2018-03-28 17:01
are you sure that it is an error  ? It seems to me more like a warning

**Comment by mrntidu** [comment] 2018-03-28 17:04
I've got a similar one while syncing  a digibyte-qt on my mac  : 

DigiByte-Qt[86726] <Warning>: void CGSUpdateManager::log() const: conn 0x1020b: spurious update
