### ISSUE TITLE
KeyError after failed import in debugger

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14886] opened 2021-03-07 18:54 UTC
[demo.mp4](https://puu.sh/HmOva/5ac30bfee4.mp4), with latest Spyder in minimal environment. Not reproduced if replacing `b` with `a`. The message  also recurs even on regular `F5` (after the error is first produced), but not on `runcell`. The exact steps are:

 1. Ctrl + F5 with a breakpoint in same file
 2. Import fails
 3. Rerun Ctrl + F5 with failed import removed, without restarting kernel
 4. Restart kernel

Not reproduced if skipping step 3. Also the clip was inconsistent with previous runs in that the message should show after step 4, but only shows after I `F5` + restart kernel, so behavior is intermittent. Windows 10 x64.

<details>
  <summary><b>conda list</b></summary>

```
# packages in environment at D:\Anaconda\envs\test-env-name:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py38_0
astroid                   2.5              py38haa95532_1
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
autopep8                  1.5.5              pyhd3eb1b0_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
bcrypt                    3.2.0            py38he774522_0
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hcd4344a_0
chardet                   4.0.0           py38haa95532_1003
click                     7.1.2              pyhd3eb1b0_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.3.1            py38hcd4344a_1
decorator                 4.4.2              pyhd3eb1b0_0
defusedxml                0.7.0              pyhd3eb1b0_0
diff-match-patch          20200713                   py_0
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
flake8                    3.8.4                      py_0
future                    0.18.2                   py38_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyhd3eb1b0_0
imagesize                 1.2.0              pyhd3eb1b0_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2020.2                      254
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.21.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.7.0              pyhd3eb1b0_0
jedi                      0.17.2           py38haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                      py_2
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.1            py38haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keyring                   22.3.0           py38haa95532_0
lazy-object-proxy         1.5.2            py38h2bbff1b_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
markupsafe                1.1.1            py38he774522_0
mccabe                    0.6.1                    py38_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
mypy_extensions           0.4.3                    py38_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py38_0
nbformat                  5.1.2              pyhd3eb1b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
numpydoc                  1.1.0              pyhd3eb1b0_1
openssl                   1.1.1j               h8ffe710_0    conda-forge
packaging                 20.9               pyhd3eb1b0_0
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.3            py38haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathspec                  0.7.0                      py_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.0.1           py38haa95532_0
pluggy                    0.13.1                   py38_0
prompt-toolkit            3.0.8                      py_0
psutil                    5.8.0            py38h2bbff1b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
pycodestyle               2.6.0              pyhd3eb1b0_0
pycparser                 2.20                       py_2
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0              pyhd3eb1b0_0
pygments                  2.8.0              pyhd3eb1b0_0
pylint                    2.7.2            py38haa95532_1
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38ha925a31_4
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1              pyhd3eb1b0_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd3eb1b0_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     20.0.0           py38hd77b12b_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.1                      py_0
qtconsole                 5.0.2              pyhd3eb1b0_0
qtpy                      1.9.0                      py_0
regex                     2020.11.13       py38h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
rope                      0.18.0                     py_0
rtree                     0.9.4            py38h21ff451_1
setuptools                52.0.0           py38haa95532_0
sip                       4.19.13          py38ha925a31_0
six                       1.15.0           py38haa95532_0
snowballstemmer           2.1.0              pyhd3eb1b0_0
sortedcontainers          2.3.0              pyhd3eb1b0_0
sphinx                    3.5.1              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0
spyder                    4.2.3            py38haa244fe_0    conda-forge
spyder-kernels            1.10.2           py38haa95532_0
sqlite                    3.33.0               h2a8f88b_0
testpath                  0.4.4              pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
toml                      0.10.1                     py_0
tornado                   6.1              py38h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
typed-ast                 1.4.2            py38h2bbff1b_1
typing_extensions         3.7.4.3            pyha847dfd_0
tzdata                    2020f                h52ac0ba_0
ujson                     4.0.2            py38hd77b12b_0
urllib3                   1.26.3             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  1.0.2            py38haa95532_1
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
wrapt                     1.12.1           py38he774522_1
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
```
</details>

### Traceback
```python-traceback
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '43083f597f7611ebbbbdf48c50704486'
ERROR:traitlets:Exception in comm_msg for 43083f597f7611ebbbbdf48c50704486
Traceback (most recent call last):
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '43083f597f7611ebbbbdf48c50704486'
ERROR:traitlets:Exception in comm_msg for 43083f597f7611ebbbbdf48c50704486
Traceback (most recent call last):
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '43083f597f7611ebbbbdf48c50704486'
ERROR:traitlets:Exception in comm_msg for 43083f597f7611ebbbbdf48c50704486
Traceback (most recent call last):
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "D:\Anaconda\envs\test-env-name\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '43083f597f7611ebbbbdf48c50704486'
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-03-13 17:28
@impact27, could this be a side effect of PR #14805?

**Comment by impact27** [comment] 2021-03-15 09:12
I could reproduce by just restarting the kernel a few times. It also fails on `_set_pickle_protocol`.  PR #14805 might be the curlpit.

**Comment by impact27** [comment] 2021-03-15 09:43
The issue is that `_finalise_restart` is called twice, so if it had time to open a comm, it will cole it while the kernel is still running.

**Comment by impact27** [comment] 2021-03-15 10:38
Fixed in https://github.com/jupyter/qtconsole/pull/474

**Closed** 2021-03-15 21:18 UTC
Labels: component:IPython Console, type:Bug
