### ISSUE TITLE
Odd behaviour once I add a matplotlib command into a python program

### ISSUE THREAD

**Issue by wpfan1000** [spyder-ide/spyder#2967] opened 2016-02-03 15:16 UTC
Hi,

Once I add matplotlib command to a program, and run that program once, succesfully, then Spyder:

- Does not run program when Run file is pressed again - I just see ">>> runfile" with the path to the file...
- If I click Run file several times, the program runs BUT it is NOT the code in the editor, it is code that existed before some recent changes
- Does not save program

I press Exit Debug to try and resolve this - pressing this multiple times sometimes results in the program running multiple times.

Also this odd behaviour seems to change - ie there is no consistent bad behaviour, so sorry if my description is not clear.

The only way I have found to resolve this is to completely exit and re-start Spyder.

Please help.

**Comment by ccordoba12** [comment] 2016-02-03 15:56
Questions:

1. Spyder version?
2. Python version?
3. Operating system?

**Comment by wpfan1000** [comment] 2016-02-03 16:33
Sorry, I should have included that in my OP:

Python 3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 15:00:12) 
[MSC v.1900 64 bit (AMD64)] on win32

Windows 7 64 bit

Thanks

**Comment by wpfan1000** [comment] 2016-02-04 14:09
I thought I would try and write a simple program to eliminate issues due to my complex code.
Even this code causes the issue:

```
import pandas
import matplotlib.pyplot as plt


# Read Yahoo data csv file into dataframe:
symbol_historical_data_frame = pandas.read_csv('symbol_historical_data_frame.csv')


# Debug:
# print (symbol_historical_data_frame)

symbol_historical_data_frame[['Open','High','Low','Close']].plot()
plt.show()
```

Please please help

**Comment by ccordoba12** [comment] 2016-02-04 14:12
I forgot to ask: what's your Matplotlib backend?

**Comment by ccordoba12** [comment] 2016-02-04 14:13
In the mean time you can use the IPython console, which doesn't have this problem.

**Comment by wpfan1000** [comment] 2016-02-04 14:17
HI, thanks for your response.
I do not know what a backend is and so I googled it - I see a lot of info about how to set it like
http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
but I do not see how to get the current backend...
Could you explain how to do that?
Thanks

**Comment by wpfan1000** [comment] 2016-02-04 14:20
I switched to the IPython console as you recommended and it does work consistently - thanks.
However my plot is now shown inside the console as quite a small image - in Spyder the plot was rendedered in a separate window so I can see it full screen - is there a way to do that in IPython console

**Comment by ccordoba12** [comment] 2016-02-07 20:04
You need to change your backend in

    Preferences > IPython Console > Graphics

from `Inlne` to `Automatic`

**Comment by ccordoba12** [comment] 2016-02-07 20:36
This is almost a duplicate of issue #1831, so I'm closing it.

**Closed by ccordoba12** 2016-02-07 20:36 UTC
Labels: Duplicate
