### ISSUE TITLE
IPython console stuck restarting kernel when using different interpreter

### ISSUE THREAD

**Issue by aberrington** [spyder-ide/spyder#20658] opened 2023-03-08 13:22 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

IPython console is stuck 'Restarting kernel' when using interpreter of python environment separate to Spyder default installation. 

### What steps reproduce the problem?

1. Install Spyder from standalone Windows executable
2. Create new conda environment `spydertest` and install latest spyder-kernels in this environment
3. In Spyder, select 'Preferences -> Use following Python interpreter' and then point to this dummy environment, i.e. 
`...Miniconda3/envs/spydertest/python.exe`

### What is the expected output? What do you see instead?

Using default interpreter, the IPython Console starts up and can execute code as normal. 

Using the alternative python interpreter, in a separate conda environment, console doesn't initialize and is stuck at Restarting kernel ... 

![image](https://user-images.githubusercontent.com/17913587/223723479-cdf018e1-58b1-458d-8dfa-f25fe389518e.png)

## Versions

* Spyder version: 5.4.2
* Python version: (default in Spyder install = 3.8.10, in development env = 3.10.9)
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10, 22H2

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<9.0.0              :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.3 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.2.8 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.12.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.4 (OK)
pygments >=2.0                       :  2.14.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.10 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                 :  1.7.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.3.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  66.0.0 (OK)
sphinx >=0.6.6                       :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0        :  2.4.2 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.2.1 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.33 (OK)
matplotlib >=3.0.0                   :  3.6.3 (OK)
numpy >=1.7                          :  1.24.1 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.10.0 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)

```

**Comment by ccordoba12** [comment] 2023-03-08 16:21
Hey @aberrington, thanks for reporting. This could be a duplicate of issue #20242, so please check [the advice](https://github.com/spyder-ide/spyder/issues/20242#issuecomment-1453888803) we provided there to see if that solves your problem.

**Comment by aberrington** [comment] 2023-03-08 19:58
Thanks for your reply @ccordoba12. Looking at the PYTHONPATH manager it seems to be completely empty by default, so nothing to unselect.

![image](https://user-images.githubusercontent.com/17913587/223830404-694be1b3-b021-46fd-8076-3b32b25d04e8.png)

**Comment by ccordoba12** [comment] 2023-03-08 23:18
Ok, no problem. What commands did you use to do this?

> Create new conda environment spydertest and install latest spyder-kernels in this environment

**Comment by aberrington** [comment] 2023-03-09 13:04
I created the environment using the following command

`conda create -n spydertest conda spyder-kernels`

**Comment by ccordoba12** [comment] 2023-03-09 14:50
I see. Perhaps that command installed an old Spyder-kernels version that it's not compatible with our 5.4.2 version.

Please try then

    conda create -n test-1 -c conda-forge spyder-kernels

That will give you the latest Spyder-kernels version in a new environment and should solve your problem.

**Comment by aberrington** [comment] 2023-03-09 15:10
Hi, thanks. Sadly, that still doesn't work for me. Kernel is still stuck restarting when pointing to the newly created environment. 

In either environment, the spyder-kernels version installed is the same 2.4.2 

with conda-forge
`spyder-kernels            2.4.2           win_pyhd8ed1ab_0    conda-forge`
with conda
`spyder-kernels            2.4.2           py310haa95532_0`

**Comment by ccordoba12** [comment] 2023-03-09 19:32
Ok, then please open the Anaconda Prompt, run

    conda activate test-1
    python -m spyder_kernels.console

and post the text printed in the console after that.

**Comment by aberrington** [comment] 2023-03-09 20:35
```
(test-1) PS C:\Users\[]> python -m spyder_kernels.console
0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-27932.json

```

**Comment by aberrington** [comment] 2023-03-10 16:39
> To connect another client to this kernel, use:
    --existing kernel-27932.json

Interestingly, I can connect to this kernel using 'Connect to existing kernel' function in the IDE.

**Comment by ccordoba12** [comment] 2023-03-12 17:27
Ok, thanks for the extra testing @aberrington.

Now, please open the following file

     ...Miniconda3/envs/test-1/lib/site-packages/spyder_kernels/console/start.py

and add the following at the beginning of its `main` function (i.e. around line `279`):

```python
os.environ['PYDEVD_DISABLE_FILE_VALIDATION'] = 1
```

and try to start a new console in Spyder. That (hopefully) should fix your problem.

**Comment by aberrington** [comment] 2023-03-13 10:42
Thanks @ccordoba12. I had to write the integer in that command as string variable otherwise there was an error.

At line 280 of `../Miniconda3/envs/test-1/lib/site-packages/spyder_kernels/console/start.py`, I put:
```
def main():
     # Remove this module's path from sys.path:
     os.environ['PYDEVD_DISABLE_FILE_VALIDATION'] = '1' 
```

IPython Console is still caught in a restart kernel loop when using test-1 interpreter - `...\Miniconda3\envs\test-1\python.exe`

![image](https://user-images.githubusercontent.com/17913587/224677977-1951149e-0b2a-42b9-9df9-74a2f1a1db75.png)



Output now from following command: 

```
conda activate test-1
python -m spyder_kernels.console
```
is 

```
(test-1) PS C:\...> python -m spyder_kernels.console
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-24092.json
```

**Comment by ccordoba12** [comment] 2023-03-13 18:15
Ok, thanks for your continued help and patience @aberrington. Let's try something else.

Please open the Anaconda Prompt, run there the following commands:

    conda activate test-1
    conda install pyzmq=24

and try again.

**Comment by aberrington** [comment] 2023-03-14 11:52
Sorry, @ccordoba12. It still doesn't work even with the downgraded pyzmq package. 

`pyzmq                              25.0.1-py311h7b3f143_0 --> 24.0.1-py311h7b3f143_1`

**Comment by ccordoba12** [comment] 2023-03-14 15:24
Ok, no problem. This still baffles me, but given that my proposed solutions didn't work, let's go with proper debugging.

For that, please go to this entry in the File menu:

![imagen](https://user-images.githubusercontent.com/365293/138761482-598fa96c-13f8-4dde-ae9a-e18ac20a7c69.png)

and select `Verbose`:

![imagen](https://user-images.githubusercontent.com/365293/138761597-e833892d-888c-4e93-99fd-6acf98dde1cc.png)

After Spyder restarts, go to the `Tools > Debug logs` menu

![imagen](https://user-images.githubusercontent.com/365293/138761756-2af03a24-21c6-47bb-8354-1f2ec87a1e83.png)

open the first file and upload it here.

**Comment by aberrington** [comment] 2023-03-14 15:38
Yes - it is quite strange and frustrating behaviour!

Now, when I restart Spyder using those instructions, the 'Restarting...' window appears briefly and then disappears but Spyder doesn't start. 

![image](https://user-images.githubusercontent.com/17913587/225054555-f85fb558-44de-4773-90e1-f824023773c8.png)

It doesn't start even when restarting normally using File -> Restart.

**Comment by dalthviz** [comment] 2023-03-15 22:35
@aberrington to launch the standalone installer application in debug mode you should run from a cmd something like:

```
"<installer root directory path location>\Spyder\Python\python.exe" "<installer root directory path location>\Spyder\Spyder.launch.pyw" --debug-info verbose
```

**Comment by ccordoba12** [comment] 2023-03-17 18:41
@dalthviz, and what about the restart functionality? Is it working for you in our Windows app?

**Comment by dalthviz** [comment] 2023-03-17 20:33
Checked and the restart functionality is not working with the standalone installer

**Comment by ccordoba12** [comment] 2023-03-20 18:32
Thanks @aberrington. Now, please open the Anaconda Prompt and run there the following command there:

    C:\Users\bbzapb\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\scripts\conda-activate.bat C:/Users/bbzapb/AppData/Local/Programs/Spyder/pkgs/spyder/bin/micromamba.exe C:/Users/bbzapb/AppData/Local/miniconda3/envs/test-1 C:\Users\bbzapb\AppData\Local\miniconda3\envs\test-1\python.exe C:\Users\bbzapb\AppData\Roaming\jupyter\runtime\kernel-f44176ec4f40.json

and post its output here.

**Comment by aberrington** [comment] 2023-03-22 12:21
Hi @ccordoba12. When I run that command, there is no output at all. 

I am wondering if it is something to do with my system administrator, not allowing .bat files to be executed perhaps.

**Comment by aberrington** [comment] 2023-03-24 12:41
@ccordoba12

I have been looking into this .bat issue on my system. It seems something may have been corrupted at some point in my Windows registry when uninstalling/installing Anaconda versions which introduced an 'AutoRun' entry to the command processor. This meant that I was unable to run cmd.exe without AutoRun and causing issues running .bat files.

I followed the steps outlined in the answer here:

https://stackoverflow.com/questions/66335300/cmd-crashes-with-exit-code-1-after-uninstalling-anaconda/66836989#66836989?newreg=d1a0080e93834699a82850420bf1672d

`C:\Windows\System32\reg.exe DELETE "HKCU\Software\Microsoft\Command Processor" /v AutoRun /f
`

Essentially, deleted that registry entry for the Command Processor and now I am able to connect to a different interpreter no problem!

This has now appeared to have fixed my Spyder issue with kernel restarting when using different interpreter.

Thanks again for all your help and patience with this.

**Comment by ccordoba12** [comment] 2023-03-24 15:52
Great! I'm really glad you were finally able to solve your problem.

Closing this issue then.

**Closed by ccordoba12** 2023-03-24 15:52 UTC
Labels: status:Awaiting Followup
