### ISSUE TITLE
Cannot connect to remote ipython kernel

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#2787] opened 2015-10-30 04:10 UTC
I can use "ipython console --existing kernel.json --ssh user@server" to connect to the server kernel
but I cannot use the spyder's connect to an existing kernel function to connect.
It got stuck for some time and show a blank window and continue to print "kernel died unexpectly, please restart kernel"

**Comment by fayeshine** [comment] 2015-10-30 09:27
I found this is the same to #2725 , please solve this, thanks!

**Comment by igor25** [comment] 2015-11-06 19:38
I have this exact same issue. On client I am running Win 10, Spyder 2.3.2 with Python(x,y) distribution and the server is CentOS 7.1.1503. I can connect to the remote server using password authentication just fine. If it would help, I could attach a log file or something, just let me know where it is. :)

**Comment by ccordoba12** [comment] 2015-11-06 20:15
Closing as duplicate of issue #2507.

**Closed by ccordoba12** 2015-11-06 20:15 UTC

**Comment by LaDilettante** [comment] 2016-07-15 14:45
This is not the same problem as #2507 because it doesn't crash but keep saying that kernel dies unexpectedly. I also experience this on Ubuntu and not just Windows like #2507
