### ISSUE TITLE
Request: let 'tab' switch between fields in search/replace

### ISSUE THREAD

**Issue by luciansmith** [spyder-ide/spyder#6143] opened 2018-01-05 22:39 UTC
## Description of your problem
It would be nice if you could hit 'tab' when entering what you're searching for, and have it switch to the 'replace' field, and visa versa.

**What steps will reproduce the problem?**

1. Select Search/Replace Text.
2. Type something that you want to search for.
3. Hit 'tab'.
4. Cry.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)
```

**Comment by CAM-Gerlach** [comment] 2018-01-05 23:01
Thanks for reporting. This is a duplicate of #3674 , and as it bothered me too, I actually just fixed it in #6094 , which you'll get when Spyder 3.2.6 comes out this Monday. Therefore, this issue will be closed.

**Closed by CAM-Gerlach** 2018-01-05 23:01 UTC

**Comment by luciansmith** [comment] 2018-01-05 23:08
Man, I even did a search and everything.  Thanks for the fix!

**Comment by CAM-Gerlach** [comment] 2018-01-05 23:26
No problem; a few months ago I actually did the exact same thing and posted it as a duplicate :) and there have been several others as well. No problem; it was a pretty easy one (minus my newb-ness, haha).
