### ISSUE TITLE
Spyder + conda: slow when not using the 'base' environment

### ISSUE THREAD

**Issue by andbiz** [spyder-ide/spyder#14752] opened 2021-02-15 14:07 UTC
Code auto-completion (kite disabled) is very slow when using spyder installed in a custom conda environment.
Also, code error checking is possibly related but I did not test specifically this issue.

### What steps reproduce the problem?
1. install spyder in the 'base' conda environment
2. create another (e.g. 'custom') conda environment and install spyder
3. run (base) spyder and open a ~200 lines file, try autocompletion --> it works fine
4. run (custom) spyder and open a ~200 lines file, try autocompletion --> ... no response
5. also, run (base) spyder but using (custom) python interpreter and open a ~200 lines file --> ... no response

### What is the expected output? What do you see instead?
I would expect spyder auto-completion to work fine independently on the conda environment it is installed into.
Also I would expect the selection of a different python interpreter would not affect the auto-completion performance.

## Versions
```
(base) [(custom) below]
# packages in environment at /home/.../miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                   py37_0  
appdirs                   1.4.4                      py_0  
argh                      0.26.2                   py37_0  
argon2-cffi               20.1.0           py37h27cfd23_1  
astroid                   2.4.2                    py37_0  
async_generator           1.10             py37h28b3542_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.5              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
black                     19.10b0                    py_0  
bleach                    3.3.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py37h27cfd23_1003  
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py37h06a4308_0  
cffi                      1.14.5           py37h261ae71_0  
chardet                   4.0.0           py37h06a4308_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
colorama                  0.4.4              pyhd3eb1b0_0  
conda                     4.9.2            py37h06a4308_0  
conda-package-handling    1.7.2            py37h03888b9_0  
cryptography              3.3.1            py37h3c74f83_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.6.0              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
docutils                  0.16                     py37_1  
entrypoints               0.3                      py37_0  
expat                     2.2.10               he6710b0_2  
flake8                    3.8.4                      py_0  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   py37_1  
glib                      2.67.3               h36276a3_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.20.0           py37hb070fc8_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
isort                     5.7.0              pyhd3eb1b0_0  
jedi                      0.17.2           py37h06a4308_1  
jeepney                   0.6.0              pyhd3eb1b0_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.7.1            py37h06a4308_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keyring                   22.0.1           py37h06a4308_0  
lazy-object-proxy         1.4.3            py37h27cfd23_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
markupsafe                1.1.1            py37h14c3975_1  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4           py37h14c3975_1001  
mypy_extensions           0.4.3                    py37_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.3              pyhd3eb1b0_0  
notebook                  6.2.0            py37h06a4308_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
openssl                   1.1.1i               h27cfd23_0  
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py37h06a4308_1  
parso                     0.7.0                      py_0  
pathspec                  0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       20.3.3           py37h06a4308_0  
pluggy                    0.13.1                   py37_0  
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
psutil                    5.8.0            py37h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py37h27cfd23_0  
pycparser                 2.20                       py_2  
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.7.4              pyhd3eb1b0_0  
pylint                    2.6.0                    py37_0  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.0              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.17.3           py37h7b6447c_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
pytz                      2021.1             pyhd3eb1b0_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.4.1            py37h27cfd23_1  
pyzmq                     20.0.0           py37h2531618_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 5.0.2              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h27cfd23_0  
regex                     2020.11.13       py37h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py37_1  
ruamel_yaml               0.15.87          py37h7b6447c_1  
secretstorage             3.3.0            py37h06a4308_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py37h06a4308_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0           py37h06a4308_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
sphinx                    3.4.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
spyder                    4.2.1            py37h06a4308_1  
spyder-kernels            1.10.1           py37h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
terminado                 0.9.2            py37h06a4308_0  
testpath                  0.4.4              pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.56.0             pyhd3eb1b0_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py37h27cfd23_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py37h2531618_0  
urllib3                   1.26.3             pyhd3eb1b0_0  
watchdog                  1.0.2            py37h06a4308_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
wurlitzer                 2.0.1                    py37_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3

(custom)
# packages in environment at /home/.../miniconda3/envs/custom:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12             pyhd3eb1b0_0  
appdirs                   1.4.4                      py_0  
argh                      0.26.2                   py38_0  
astroid                   2.4.2                    py38_0  
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.5              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py38h27cfd23_1003  
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
cffi                      1.14.5           py38h261ae71_0  
chardet                   4.0.0           py38h06a4308_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
colorama                  0.4.4              pyhd3eb1b0_0  
cryptography              3.3.1            py38h3c74f83_0  
cycler                    0.10.0                   py38_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.6.0              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
docutils                  0.16                     py38_1  
entrypoints               0.3                      py38_0  
expat                     2.2.10               he6710b0_2  
flake8                    3.8.4                      py_0  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   py38_1  
glib                      2.67.3               h36276a3_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.20.0           py38hb070fc8_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.7.0              pyhd3eb1b0_0  
jedi                      0.17.2           py38h06a4308_1  
jeepney                   0.6.0              pyhd3eb1b0_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    1.0.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.7                      py_0  
jupyter_core              4.7.1            py38h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
keyring                   22.0.1           py38h06a4308_0  
kiwisolver                1.3.1            py38h2531618_0  
lazy-object-proxy         1.4.3            py38h27cfd23_2  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
littleutils               0.2.2                      py_0    conda-forge
lz4-c                     1.9.3                h2531618_0  
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.3.2                h06a4308_0  
matplotlib-base           3.3.2            py38h817c723_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
mpmath                    1.1.0                    py38_0  
mypy_extensions           0.4.3                    py38_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.3              pyhd3eb1b0_0  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                       py_0  
openssl                   1.1.1i               h27cfd23_0  
outdated                  0.2.0                      py_0    conda-forge
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.1            py38ha9443f7_0  
pandas-flavor             0.2.0                      py_0    conda-forge
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py38h06a4308_1  
parso                     0.7.0                      py_0  
pathspec                  0.7.0                      py_0  
patsy                     0.5.1                    py38_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.0            py38he98fc37_0  
pingouin                  0.3.9              pyhd8ed1ab_0    conda-forge
pip                       20.3.3           py38h06a4308_0  
pluggy                    0.13.1                   py38_0  
prompt-toolkit            3.0.8                      py_0  
psutil                    5.8.0            py38h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycparser                 2.20                       py_2  
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.7.4              pyhd3eb1b0_0  
pylint                    2.6.0                    py38_0  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.0              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
pytz                      2021.1             pyhd3eb1b0_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.4.1            py38h27cfd23_1  
pyzmq                     20.0.0           py38h2531618_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 5.0.2              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h27cfd23_0  
regex                     2020.11.13       py38h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py38_1  
scikit-learn              0.23.2           py38h0573a6f_0  
scipy                     1.6.0            py38h91f5cce_0  
seaborn                   0.11.1             pyhd3eb1b0_0  
secretstorage             3.3.0            py38h06a4308_0  
setuptools                52.0.0           py38h06a4308_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
sphinx                    3.4.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
spyder                    4.2.1            py38h06a4308_1  
spyder-kernels            1.10.1           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
statsmodels               0.12.1           py38h27cfd23_0  
tabulate                  0.8.7                    py38_0  
testpath                  0.4.4              pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
tornado                   6.1              py38h27cfd23_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py38h27cfd23_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py38h2531618_0  
urllib3                   1.26.3             pyhd3eb1b0_0  
watchdog                  1.0.2            py38h06a4308_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.11.2           py38h7b6447c_0  
wurlitzer                 2.0.1                    py38_0  
xarray                    0.16.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0
```

* Operating System name/version: Gentoo

**Comment by steff456** [comment] 2021-02-15 17:21
Hi @andbiz,

How many packages are you installing and importing in those files? Also, what are the extra packages that you are installing in the `custom` environment?

**Comment by andbiz** [comment] 2021-02-16 08:25
Hi @steff456 
Thanks for checking!
Both envs used for reproducing the issue were created "from zero" and are quite similar:
as you can see from the conda list of packages there are only 15 packages more in (custom), due to a
```conda install -c conda-forge pingouin```

The python script used to test the auto-completion was the same for both (base) and (custom).
Standard python packages are imported, some functions defined...nothing too complicated.
```pingouin``` was not imported.

However, this issue seems quite strange to me... I will try to reproduce this on another machine and let you know!

**Comment by ccordoba12** [comment] 2021-05-03 16:28
Closing as a duplicate of issue #15042 (we're consolidating all related problems there).

**Closed by ccordoba12** 2021-05-03 16:28 UTC
Labels: status:Awaiting Followup
