### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by LEOLI3** [spyder-ide/spyder#6035] opened 2017-12-21 19:05 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/LZQ/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2463, in execute_in_external_console
    console.execute_code(lines)
  File "/Users/LZQ/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 954, in execute_code
    sw.execute(to_text_string(lines))
  File "/Users/LZQ/anaconda3/lib/python3.6/site-packages/qtconsole/history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "/Users/LZQ/anaconda3/lib/python3.6/site-packages/qtconsole/console_widget.py", line 632, in execute
    self._execute(source, hidden)
  File "/Users/LZQ/anaconda3/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-12-21 23:50
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by LEOLI3** [comment] 2017-12-22 00:42
Once I start the spyder, this error window pops up.  And it cannot connect to the kernel.

But I already fixed it by resetting everything. Thank u so much for consideration.

Sent from my iPhone

On Dec 21, 2017, at 17:50, Carlos Cordoba <notifications@github.com<mailto:notifications@github.com>> wrote:


Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2017-12-23 00:38
In that case, I guess I'll close this one. If it reoccurs, and you can isolate the cause, then please reopen and provide those details to it can be fixed for other users, if it is a bug in Spyder. Thanks!

**Closed by CAM-Gerlach** 2017-12-23 00:38 UTC
Labels: status:AwaitingFollowup
