### ISSUE TITLE
Spyder crashes when loading a netcdf dataset using netCDF4 library

### ISSUE THREAD

**Issue by malapradej** [spyder-ide/spyder#2303] opened 2015-04-07 17:51 UTC
Spyder crashes when loading a netCDF4 dataset. The code below:

    fn = 'myfile.nc'
    import netCDF4 as nc
    dataset = nc.Dataset(fn, 'r')
    
It seems to hang at the last line. When I run a command line instance of Spyder and close it after the crash the following error is printed to the terminal:

    (process:15767): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

I am using Spyder version 2.2.5, on Ubuntu 14.04 LTS. 

I am able to run the same script in ipython and run it through the terminal. Problem must be with Spyder.

**Comment by ccordoba12** [comment] 2015-04-07 21:06
This is a duplicate of issue #1711. Please add more comments there.

Also, please upload `myfile.nc` (or the `nc` file you want) so we can test things in our side.

**Closed** 2015-04-07 21:06 UTC
Labels: duplicate

**Comment by malapradej** [comment] 2015-04-08 09:16
I actually found the same issue here #2303 and amended the solution as it did not work for me.

**Comment by ccordoba12** [comment] 2015-04-08 15:20
Maybe you could upload it to Dropbox and provide a link here.

Another thing is that 2.2.5 is unmaintained now. Please upgrade to 2.3.4

**Comment by malapradej** [comment] 2015-04-08 16:08
Does this mean I have to switch to python 3?

**Comment by ccordoba12** [comment] 2015-04-08 16:18
Nop, Spyder supports (and it's going to keep supporting) both Python 2 and 3.
