### ISSUE TITLE
ValueError: (Filepath) is not in list apparently occurs when attempting to close a file

### ISSUE THREAD

**Issue by masaki-murata** [spyder-ide/spyder#6004] opened 2017-12-18 05:41 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\murata\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1356, in close_file_in_all_editorstacks
    index = editorstack.get_index_from_filename(filename)
  File "C:\Users\murata\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1345, in get_index_from_filename
    return filenames.index(filename)
ValueError: 'E:\\TOM\\BreaKHis_v1\\python_files\\bh_tl_70p.py' is not in list

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-18 05:51
Please describe step by step how you got this error so we can reproduce it in our side. If we don't hear from you, we'll have to close this issue in a week (7 days) from now. Thanks.

**Comment by CAM-Gerlach** [comment] 2017-12-25 18:54
Closed due to lack of response.

**Closed by CAM-Gerlach** 2017-12-25 18:54 UTC
Labels: status:AwaitingFollowup
