### ISSUE TITLE
Spyder console doesn't scroll properly

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#3281] opened 2016-07-07 18:56 UTC
When multiple lines are written to the console, the console doesn't scroll up to show all written lines.

Try this:

```
import time
iteration = 0
while (True):
    iteration += 1
    print("Iteration:", iteration)
    print("This is the 2nd line")
    print("This is the 3rd line")
    print("This is the 4th line")
    print("====================")
    time.sleep(2)
```

When you run it, watch the console. For the whole 2 seconds of time.sleep(2), the last line shown on the screen is "Iteration:", not the last line written.

The missing lines _can_ be seen if you drag the scroll bar.

This makes it needlessly difficult to see the Python console output in real time.

Spyder: 3.0.0dev
WinPython: 3.4.4.2 (64 bit)
OS: Windows 10 Pro

**Comment by ccordoba12** [comment] 2016-07-08 20:38
Which console? Python or IPython?

**Comment by nerdfever** [comment] 2016-07-09 17:11
iPython.

The default console that appears in the lower right of Sypder.

**Comment by nerdfever** [comment] 2016-07-21 18:36
@ccordoba12 Has anyone been able to reproduce this? 

![screenshot](https://cloud.githubusercontent.com/assets/9833299/17034351/52da98ee-4f50-11e6-8100-f73e427e859b.png)

**Comment by jitseniesen** [comment] 2016-07-22 08:48
> Has anyone been able to reproduce this? 

Yes, I can see the same issue. Spyder 3.0.0b4, Python 3.5.2 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux. The Python console works fine, only the IPython exhibits the issue.

**Comment by Nodd** [comment] 2016-07-22 12:01
> The Python console works fine, only the IPython exhibits the issue.

Ha ! (Sorry, private joke)

**Comment by ccordoba12** [comment] 2016-07-22 14:43
This is an upstream problem (i.e. a problem with qtconsole itself), so there's nothing we can do about it on the Spyder side.

**Comment by ccordoba12** [comment] 2016-07-22 14:44
Besides, this is a duplicate of issue #1773.

**Closed by ccordoba12** 2016-07-22 14:44 UTC
Labels: Comp-Console-IPython, Type-Bug, Type-Duplicate

**Comment by ACTCB** [comment] 2018-12-20 05:39
As a workaround, try this:
`import time
print("Line to print")
# Delay needed to print out the previous line
time.sleep(1)
print(' ')`
