### ISSUE TITLE
Spyder hangs when saving empty file

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#14926] opened 2021-03-13 13:52 UTC
Spyder hangs when saving an empty file.

### What steps reproduce the problem?

1.  Create new file.
2.  Delete everything from the template.
3.  Click save.

### What is the expected output? What do you see instead?

Spyder hangs and has to be terminated externally.

### Paste Traceback/Error Below (if applicable)
No traceback output.

## Versions
* Spyder version: 4.2.3 None
* Python version: 3.6.12 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.97-1-MANJARO

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.8.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  21.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  1.4 (OK)
```

**Comment by steff456** [comment] 2021-03-15 20:08
Hi @gerazov,

I'm unable to reproduce this issue on macOS, can you please post a gift of the behavior you are having?

**Comment by gerazov** [comment] 2021-03-20 21:45
Hi @steff456 - it might be a broken environment at the end. Let's close this if no one else complains :slightly_smiling_face:

**Comment by ccordoba12** [comment] 2021-03-21 00:12
I can't reproduce it either. Closing then.

**Closed by ccordoba12** 2021-03-21 00:12 UTC
Labels: status:Awaiting Followup
