### ISSUE TITLE
RuntimeError on import

### ISSUE THREAD

**Issue by 2yan** [spyder-ide/spyder#6072] opened 2017-12-27 19:16 UTC
## Importing certian libraries don't work in Spyder while working normally in the jupyter notebook and also in a python prompt. 

**What steps will reproduce the problem?**

1. Open Spyder IDE
2. Have googles api client installed $ pip install --upgrade google-api-python-client
3. from apiclient.discovery import build

**What is the expected output? What do you see instead?**
Expected output: None, just a nice import
actual:
RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

**Please provide any additional information below**
This issue seems to be paticular only to the Spyder IDE, it does not happen in any other enviornment. Extra weird is that it works in a jupyter notebook, but not in the IPython Console in Spyder. 

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 7 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment] 2017-12-28 00:59
Thanks for reporting. Unfortunately, due to the many problems with a `pip` install as you have seen, we only officially support the Anaconda distribution and `conda` for installing Spyder and related packages, though you are welcome to try to get it working on your own. Therefore, this issue will have to be closed. Best of luck!

**Comment by 2yan** [comment] 2017-12-28 04:02
It is a Anaconda distribution of Python, I'll find a way to install the package via conda and report back.

**Comment by ccordoba12** [comment] 2017-12-28 06:06
Dkd you install google-api-python-client from within Spyder?

**Comment by 2yan** [comment] 2017-12-28 18:14
I re-installed it via conda and it's still the same problem. This is contininuing to look like a spyder thing.

**Comment by CAM-Gerlach** [comment] 2017-12-28 20:16
Can you try the `import` in `qtconsole` (and bare IPython, if you haven't) as well? That's Spyder's console that actually runs the code, and so if it happens there too, then the problem is almost certainly with their code and can't be directly resolved from here.

**Comment by ccordoba12** [comment] 2017-12-28 20:45
Please post a screenshot of the moment you're getting the error you reported.

**Comment by CAM-Gerlach** [comment] 2018-01-04 11:47
@2yan Please let us know; otherwise this issue will have to be closed (again). Thanks.

**Comment by 2yan** [comment] 2018-01-04 17:06
Sorry about the delay:

Importing in QTConsole works just fine:
![image](https://user-images.githubusercontent.com/14183988/34575106-6b6bd7f2-f12e-11e7-9c21-ca6d513a49fc.png)

Here's the error from Spyder:
![image](https://user-images.githubusercontent.com/14183988/34575150-889c50ae-f12e-11e7-9df3-95e1b15c437b.png)

**Comment by ccordoba12** [comment] 2018-01-17 14:41
Please update to Spyder 3.2.6 and try again. I think this should be fixed by now.

**Comment by 2yan** [comment] 2018-01-17 17:41
That fixed it! Thank you for the help!

**Closed** 2018-01-17 19:20 UTC

**Comment by CAM-Gerlach** [comment] 2018-01-17 19:29
Thanks @2yan
