### ISSUE TITLE
computers dont like trippy times IM JUST DOING MY THING MANNNNNNNNNNNNNN

### ISSUE THREAD

**Issue by ISOSIRIS** [spyder-ide/spyder#21775] opened 2024-02-08 03:21 UTC
### What steps will reproduce the problem?

WELL GROW UP!!!NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

### Traceback
```python-traceback
Exception in callback functools.partial(<function ThreadedZMQSocketChannel.send.<locals>.thread_send at 0x0000016B80D7B740>)
Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\Lib\site-packages\tornado\ioloop.py", line 738, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "C:\Users\Owner\anaconda3\Lib\site-packages\jupyter_client\threaded.py", line 113, in thread_send
    self.session.send(self.stream, msg)
  File "C:\Users\Owner\anaconda3\Lib\site-packages\jupyter_client\session.py", line 859, in send
    stream.send_multipart(to_send, copy=copy)
  File "C:\Users\Owner\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 397, in send_multipart
    self.on_send(callback)
  File "C:\Users\Owner\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 350, in on_send
    self._check_closed()
  File "C:\Users\Owner\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 685, in _check_closed
    raise OSError("Stream is closed")
OSError: Stream is closed
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  1.7.3 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.21.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  0.9.0 (OK)
jsonschema >=3.2.0               :  4.17.3 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  6.5.4 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.0.0 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.7.1 (OK)
numpy >=1.7                      :  1.24.3 (OK)
pandas >=1.1.1                   :  1.5.3 (OK)
scipy >=0.17.0                   :  1.10.1 (OK)
sympy >=0.7.3                    :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment] 2024-02-08 16:20
Closing as basically a duplicate of issue #21773.

**Closed by ccordoba12** 2024-02-08 16:20 UTC
