### ISSUE TITLE
Spyder raising "AttributeError" window at a Python error

### ISSUE THREAD

**Issue by fchirono** [spyder-ide/spyder#5210] opened 2017-09-12 10:41 UTC
Hi,

I've been using Anaconda/Spyder for a few years by now, and last week this problem showed up seemingly out of nowhere: whenever I make an error in Python - say, calling a variable that doesn't exist - Spyder brings an Error window with the message shown below (in the "additional information" section). 

I can confirm this problem repeats itself for AttributeError, TypeError and NameError, always with the same error message in the Spyder window. Neither restarting the kernel nor restarting Spyder seems to change this behaviour. Unfortunately I don't recall whether this showed up after a particular update :/ sorry

**What steps will reproduce the problem?**
Apparently, making any errors in Python; some examples:

1. Calling `numpy` functions without importing Numpy first, or calling variables that don't exist
```python
np.abs(1)
print(a)
```

2. Trying to access an attribute that does not exist
```python
a=1
a.len
```

3. Trying to mix variable types
```python
a = 1
a+ 'b'
```

All the above snippets raised the same error window in Spyder.

**What is the expected output? What do you see instead?**
I expected to see only an error message int the IPython console, without the Spyder error window.

**Please provide any additional information below**
The error message in the Spyder window is:
```
  File "/home/fch1g10/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/fch1g10/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'
```

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.5.3
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by rlaverde** [comment] 2017-09-12 11:09
This is a duplicate of issue #5158 and it was fixed in Spyder 3.2.3. Please update.

**Closed by rlaverde** 2017-09-12 11:09 UTC
