### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by dikodiko** [spyder-ide/spyder#15041] opened 2021-03-28 17:41 UTC
### What steps will reproduce the problem?

my workinfg directory does not browse any txt, png or any other downloaded files. 

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment] 2021-03-29 02:22
Hey @dikodiko, thanks for reporting. I don't understand very well your problem. Could you post a screenshot of what you mean to see what's happening in your case?

**Comment by dikodiko** [comment] 2021-03-30 00:41
Hello, thank you for your response. I am sending two screenshots, one tehm
is the files that downloaded on my computer and the second one is the
working directory of spyder that is not giving an option to browse those
files

**Comment by dikodiko** [comment] 2021-03-30 00:43
I need to browse .txt, .png files, but the working directory is not giving
an option. It is letting me to browse only File Folders

**Comment by ccordoba12** [comment] 2021-03-30 01:10
Hey @dikodiko, you can't send images via email because Github doesn't allow it. Instead, you need to drag and drop them here.

**Comment by dikodiko** [comment] 2021-03-30 02:03
![Screenshot (4)](https://user-images.githubusercontent.com/81528341/112922274-361be480-90da-11eb-8e72-111688200fec.png)
![Screenshot (3)](https://user-images.githubusercontent.com/81528341/112922310-48961e00-90da-11eb-9ab4-58b8c4af3284.png)
![Screenshot (5)](https://user-images.githubusercontent.com/81528341/112922472-898e3280-90da-11eb-9cb4-b54a23c2003e.png)

**Comment by ccordoba12** [comment] 2021-05-30 23:24
Closing because I was unable to reproduce this.

**Closed by ccordoba12** 2021-05-30 23:24 UTC
Labels: status:Awaiting Followup
