### ISSUE TITLE
kernel died,restarting

### ISSUE THREAD

**Issue by xiechuanqi0222** [spyder-ide/spyder#17863] opened 2022-05-12 02:08 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
import numpy as np 
import pandas as pd  
import os 
from pathlib import Path 
import glob
import zipfile 
import random 

import seaborn as sns 
import matplotlib.pyplot as plt 

import tensorflow as tf  
from tensorflow.keras import layers
from tensorflow.keras import Model  
import keras_preprocessing
from keras_preprocessing import image   
from tensorflow.keras.optimizers import RMSprop
from keras_preprocessing.image import ImageDataGenerator

**Comment by ccordoba12** [comment] 2022-05-12 15:06
Hey @xiechuanqi0222, thanks for reporting. Usually, this kind of problems is not related to Spyder but to the way you installed the libraries you're trying to use (i.e. Tensorflow, Matplotlib, etc).

If you used pip and conda in the same environment to do that, then that could be the cause of your problem and you'd need to reinstall Anaconda to fix it. Please refer to [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that properly.

Since you didn't give any more details, I'm going to close this issue.

**Closed by ccordoba12** 2022-05-12 15:06 UTC

**Comment by xiechuanqi0222** [comment] 2022-05-12 15:11
Thank you!



---- Replied Message ----
| From | Carlos ***@***.***> |
| Date | 05/12/2022 23:06 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [spyder-ide/spyder] kernel died,restarting (Issue #17863) |

Hey @xiechuanqi0222, thanks for reporting. Usually, this kind of problems is not related to Spyder but to the way you installed the libraries you're trying to use (i.e. Tensorflow, Matplotlib, etc).

If you used pip and conda in the same environment to do that, then that could be the cause of your problem and you'd need to reinstall Anaconda to fix it. Please refer to our video to learn how to do that properly.

Since you didn't give any more details, I'm going to close this issue.
