### ISSUE TITLE
Editor: number of lines and lines position are not matching

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2168] opened 2015-02-17 23:34 UTC
_From [mauric...@gmail.com](https://code.google.com/u/116590549482682789218/) on 2015-02-08T05:15:40Z_

Spyder Version:  2.3.2
Python Version:  2.7.9
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Darwin
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 

Please provide any additional information below

. When I use the software, the number of lines (on the left) and the real position of the lines, are misplaced.

**Attachment:** [Screen Shot 2015-02-08 at 11.14.35.png](http://code.google.com/p/spyderlib/issues/detail?id=2168)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2168_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T10:50:20Z_

Thanks for reporting, we'll see what we can do about it for 2.3.4

**Summary:** Editor: number of lines and lines position are not matching  \<span class="oldvalue"> (was: GUI problem: number of lines and lines not matching) \</span>  
  **Labels:** Cat-Editor MS-v2.3.4

**Comment by ccordoba12** [comment] 2015-04-02 21:25
This is a duplicate of issue #2296

**Closed by ccordoba12** 2015-04-02 21:26 UTC
Labels: 1 star, bug, duplicate, Editor
