### ISSUE TITLE
Spyder will not load "jit" from "numba"

### ISSUE THREAD

**Issue by Deewrat** [spyder-ide/spyder#4517] opened 2017-05-29 01:48 UTC
## Description of your problem
         import numba
         from numba import jit

gives an error.
I am using anaconda, and have updated spyder, numba. Also uninstalled/installed spyder.

In a separate (non-Spyder) command-line console it works.

**What steps will reproduce the problem?**

1.as above 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: latest
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-05-29 15:24
Thanks for reporting. This looks like a duplicate of issue #3969.

**Closed by ccordoba12** 2017-05-29 15:24 UTC
Labels: resolution:Duplicate
