### ISSUE TITLE
Unreadable Console Text with No Way to Change

### ISSUE THREAD

**Issue by Elliptica1** [spyder-ide/spyder#8148] opened 2018-10-26 23:40 UTC
## Description

**What steps will reproduce the problem?**

1. Opening the editor
2. Running anything in iPython console

**What is the expected output? What do you see instead?**

I expect the syntax coloring of the iPython console to be the same as the editor. Instead, it's super bright colors with no way to change (that I've discovered). Even the coloring _within_ the iPython console is not consistent (e.g. filepaths show in two different colors, one very painful to look at). The syntax coloring options available in preferences only affect the editor, not the console. 

**Please provide any additional information below**

![example](https://user-images.githubusercontent.com/24662122/47596790-a76d7100-d93d-11e8-881b-42c41aa1fcc7.png)

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by jnsebgosselin** [comment] 2018-10-27 02:28
Thanks for your report.

I'm closing this as a duplicate of https://github.com/spyder-ide/spyder/issues/6270.

**Closed by jnsebgosselin** 2018-10-27 02:28 UTC
Labels: resolution:Duplicate
