### ISSUE TITLE
Code folding interferes with linting

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12397] opened 2020-04-19 17:29 UTC
[demo.mp4](https://puu.sh/FzEMf/8028b89eef.mp4); note LSP is restarted. Total file length (unfolded): 635 lines.

**Comment by ccordoba12** [comment] 2020-04-19 22:08
Duplicate of #12321

**Closed by ccordoba12** 2020-04-19 22:08 UTC
