### ISSUE TITLE
Spyder 4.1.4 autocomplete issue

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#13523] opened 2020-08-13 05:13 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

If I have `script_1.py` and `script_2.py` that are in the same directory, and I want to call a function in `script_2.py` from `script_1.py`, autocomplete and "go to definition" does not work.

Btw I made sure the current working directory is pointed to where `script_1.py` and `script_2.py` are stored.

I noticed that this only happens for Spyder 4.1.4, not 4.1.3.  And this issue seems to only occur for scripts that you have in your custom directories, not for autocompleting functions from installed libraries.

(Turning on/off Kite doesn't help.)

### What steps reproduce the problem?

See "Problem Description" above.

### What is the expected output? What do you see instead?

The expected behavior: (1) should autocomplete, (2) pressing "ctrl + I" should display the docstring of the function (if applicable), (3) "ctrl + G" should go to that function.

But I'm seeing none of the above.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.4
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: both Ubuntu 18.04 and macOS Catalina

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-08-13 15:49
@jsh9, thanks for reporting. A lot of things changed in Jedi 0.17, so that's probably why your use case is not working anymore.

**Comment by ccordoba12** [comment] 2020-08-13 15:50
Note: Perhaps this is solved by setting this option in Jedi's projects:

https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Project.smart_sys_path

**Comment by stonebig** [comment] 2020-08-14 18:12
small request: would it be possible to move Spyder to jedi-0.17.2 ? for Python-3.9 compatibility (see https://github.com/microsoft/vscode-python/commit/f26d2dd22172cf95568b1e72b2b0a34e3df1e47a)

**Comment by ccordoba12** [comment] 2020-08-14 22:05
It will come when we release 4.2 in a couple of months, sorry.

**Comment by ccordoba12** [comment] 2020-10-24 23:01
After carefully considering this issue, I found it's really a duplicate of issue #11118. And we plan to fix that one for 4.2.0

Thanks for your patience @jsh9.

**Closed by ccordoba12** 2020-10-24 23:01 UTC
Labels: component:Code Completion, type:Bug
