### ISSUE TITLE
Spyder 4 Code folding not working

### ISSUE THREAD

**Issue by guenter55** [spyder-ide/spyder#11904] opened 2020-03-21 12:18 UTC
I'm using spyder with winpython and upgraded to the latest version.
The behaviour is the same in all the versions 4.0.1, 4.1.0, 4.1.1
I am not able to make code folding working (small files/big files, def, """, ...)
Are the specific conditions to fulfill (option, source style)?
Environment: WinPython 3.8.2, a view extensions (selenium,googletrans).
Upgrade spyder with pip install --upgrade spyder (4.1.1 in "about spyder").

**Comment by ccordoba12** [comment] 2020-03-21 16:20
Duplicate of #11869

**Comment by ccordoba12** [comment] 2020-03-21 16:20
It'll be fixed in 4.1.2

**Closed by ccordoba12** 2020-03-21 16:20 UTC
