### ISSUE TITLE
Windows command prompts pop up when executing pypandoc function calls in IPython console

### ISSUE THREAD

**Issue by wtheis** [spyder-ide/spyder#4932] opened 2017-08-10 07:39 UTC
## Description

**What steps will reproduce the problem?**

In IPython console execute the following commands:

1. import pypandoc
2. pypandoc.convert_text('hello', format='markdown', to='html')

Windows command prompts pop up and disappear again (stealing the focus every time, making it impossible to work while a script using pypandoc runs in spyder).

**What is the expected output? What do you see instead?**

pypandoc.convert_text() should execute without command prompts popping up.
 
**Please provide any additional information below**

These commands execute in an external python console and an external IPython console as expected without displaying additional windows.
Spyder was installed as part of Anaconda. pypandoc 1.4 was installed from conda-forge, yielding pandoc 1.19.2.1 in conda list.

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-10 15:42
@andfoy, please take a look at this one. I think we can redefine `subprocess.Popen` in our sitecustomize, so that all calls to `subprocess` include [these flags](https://github.com/spyder-ide/spyder-notebook/blob/master/spyder_notebook/utils/nbopen.py#L65), which prevent cmd windows to appear.

**Comment by andfoy** [comment] 2017-08-17 22:05
@ccordoba12 How do I include that modifications on sitecustomize?

**Comment by ccordoba12** [comment] 2017-08-17 23:36
I forgot about it, but this is a duplicate of issue #3529.

**Closed by ccordoba12** 2017-08-17 23:36 UTC
Labels: component:IPython Console, type:Enhancement
