### ISSUE TITLE
huge icons and text misaligned with spyder3

### ISSUE THREAD

**Issue by Ticonderoga** [spyder-ide/spyder#3417] opened 2016-09-13 13:08 UTC
## Description of your problem
I tried to start start spyder3 with python bootstrap.py and the ui is not working properly
have look ... http://i63.tinypic.com/33mwo6s.png

Executing Spyder from source checkout
Revision 3556172, Branch: master
01. Patched sys.path with /home/phil/src-install/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0.dev0
    [Python 3.5.2 64bits, Qt 5.7.0, PyQt5 5.7 on Linux]
04. Running Spyder

I have a laptop and a desktop and both have the same distrib (archlinux) and the same packages. Both are synchronized. I even try with a clean new user (to wipe any .config/ problem) but for some reason the laptop is not rendering the ui the same way as the desktop
here it is : http://i68.tinypic.com/2wnxv76.png

**Comment by Ticonderoga** [comment] 2016-09-13 13:23
I fixed my problem by commenting these 2 lines in mainwindow.py 

if hasattr(Qt, 'AA_EnableHighDpiScaling'):
    QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)

I don't know why the HighDpiScaling is enabled on my laptop ...

**Comment by ccordoba12** [comment] 2016-09-13 14:14
Thanks for reporting.

@goanpeca, does this mean that we need to add an option to enable/disable HighDpi?

**Comment by goanpeca** [comment] 2016-09-13 16:30
Hmmm, dont know, @SylvainCorlay ?

**Comment by ccordoba12** [comment] 2016-09-30 21:08
Closing as a duplicate of #3489

**Closed** 2016-09-30 21:08 UTC
Labels: Design-UI, Type-Bug
