### ISSUE TITLE
Incorrect dependency reporting for iPython in 3.0.0b1

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#2686] opened 2015-09-10 21:42 UTC
I've got `iPython 3.0.0` installed, and it says that `3.0` is the minimum required, but it's flagged as a problem in the screengrab..
![spyder3 0 0b1-invalidoptionaldependencyreports](https://cloud.githubusercontent.com/assets/3229632/9801781/2c12a4c8-57ca-11e5-8856-f48d79442d38.png)

**Comment by ccordoba12** [comment] 2015-09-10 22:21
This is a duplicate of issue #2612.

@goanpeca you introduced this bug when you changed the way we detect package versions in `utils/programs.py` to check for Spyder updates.

**Closed by ccordoba12** 2015-09-10 22:21 UTC
Labels: bug, duplicate
