### ISSUE TITLE
Spyder IDE seems stuck after a while 

### ISSUE THREAD

**Issue by qingkaikong** [spyder-ide/spyder#3318] opened 2016-07-22 21:02 UTC
## Description of your problem
I installed 3.0.0.dev0 on my mac, but somehow I experienced spyder IDE stuck there twice from yesterday. It all happens when I have some script opened in the editor, then I go to have lunch, after I come back, it stuck there with the cursor becomes busy, and I can not type or use it. I have to restart it to use it. 

**What steps will reproduce the problem?**

1. I don't know how to reproduce it, but it seems I just leave the IDE running there for a 1 hour or so, it will stuck there, that I can not do anything with it. 

## Versions and main components

* Spyder Version: 3.0.0.dev0
* Python Version: 2.7.11 
* Operating system: OS X Yosemite, 10.10.5

**Comment by ccordoba12** [comment] 2016-07-22 21:27
This is a duplicate of issue #3306

**Closed by ccordoba12** 2016-07-22 21:27 UTC
Labels: Type-Duplicate
