### ISSUE TITLE
Linting is not respecting pycodestyle.cfg

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#13110] opened 2020-06-26 04:16 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Linting no longer respects pycodestyle.cfg after #12812

### What steps reproduce the problem?

1. Bootstrap with a8565a1f1df017b38a34c4cf7ea4e603cb22b7ff (last good 4.x commit); observe that linting respects pycodestyle.cfg
2. Bootstrap with a4d9ae4a4aede506737b71b9426e4f5d7afb0d04; observe that linting does not respect pycodestyle.cfg

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.0dev
* Python version: 3.7.7
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Darwin 18.7.0

### Dependencies
<details><summary>Dependencies</summary>

```
# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.17.0                   :  0.17.1 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.33.0;<0.34.0          :  v4.1.3+298.ga4d9ae4a4 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.10.0.dev0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.4 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```
</details>

**Comment by ccordoba12** [comment] 2020-06-26 04:29
Any ideas on why this is happening? I didn't even know we were loading `pycodestyle.cfg` until now.

**Comment by mrclary** [comment] 2020-06-26 06:17
According to the [description|https://github.com/palantir/python-language-server#configuration], the Python Language Server looks for configurations in ~/.config/pycodestyle, setup.cfg, tox.ini and pycodestyle.cfg. Should I be using a different config file? Did we switch from pycodestyle to flake8? It appears not to discover them now. I haven't looked closely yet, but I'll see if I can isolate the cause.

**Comment by ccordoba12** [comment] 2020-06-26 06:39
> the Python Language Server looks for configurations in ~/.config/pycodestyle, setup.cfg, tox.ini and pycodestyle.cf

We removed all environment variables from the process that controls the server and made it start in an empty directory. That was done in order to prevent that those things could make the process crash.

That could be the cause of this regression, but since you have the possibility to configure pycodestyle from our Preferences, I don't think it's worth to support a file base configuration.

> Did we switch from pycodestyle to flake8?

No, we didn't.

**Comment by mrclary** [comment] 2020-06-26 14:54
> but since you have the possibility to configure pycodestyle from our Preferences, I don't think it's worth to support a file base configuration

Except that projects/repositories have different style requirements. Am I missing something here?

**Comment by mrclary** [comment] 2020-06-26 21:49
@ccordoba12 @andfoy , 
The critical lines of code seem to be introduced in a976b7d67c85076bfb950fe465352f66a581553f, `spyder/plugins/completion/languageserver/plugin.py` starting with line 245.
I don't believe that the issue is caused by removed environment variables or making the server start in an empty directory.
It seems that the `LSPClient.watched_folders` is not respected.

```python
@Slot()
def project_path_update(self, project_path, update_kind):
    """
    Send a new initialize message to each LSP server when the project
    path has changed so they can update the respective server root paths.
    """
    for language in self.clients:
        language_client = self.clients[language]
        if language_client['status'] == self.RUNNING:
            instance = language_client['instance']
            if (instance.supports_multiple_workspaces and
                    instance.supports_workspace_update):
                logger.debug('{0}: LSP supports multiple '
                              'workspaces'.format(instance.language))
                logger.debug('Project path {0}: {1}'.format(
                    project_path, update_kind))
                instance.send_workspace_folders_change({
                    'folder': project_path,
                    'instance': self.main.projects,
                    'kind': update_kind
                })
            else:
                logger.debug('{0}: LSP does not support multiple '
                              'workspaces, restarting'.format(
                                  instance.language))
                self.main.projects.stop_lsp_services()
                self.main.editor.stop_completion_services(language)
                folder = self.get_root_path(language)
                instance.folder = folder
                self.close_client(language)
                self.start_client(language)
```

Running from bootstrap, before `instance.send_workspace_folders_change` I have the following values:
```python
self.clients[language]['instance'].folder -> /Users/rclary/.spyder-py3-dev/lsp_root_path
self.clients[language]['instance'].watched_folders -> {}
```
and after I have:
```python
self.clients[language]['instance'].folder -> /Users/rclary/.spyder-py3-dev/lsp_root_path
self.clients[language]['instance'].watched_folders -> {'/Users/rclary/Documents/Python/c2w': {'uri': 'file:///Users/rclary/Documents/Python/c2w', 'instance': <spyder.plugins.projects.plugin.Projects object at 0x12b984190>}}
```
In this case, `/Users/rclary/Documents/Python/c2w/pycodestyle.cfg` is not respected (or found?) and the linting is incorrect.
However, if I copy the same `pycodestyle.cfg` file to `/Users/rclary/.spyder-py3-dev/lsp_root_path`, then linting is correct. So it seems to be honoring `self.clients[language]['instance'].folder` instead of `self.clients[language]['instance'].watched_folders`.

Indeed, prior to this commit, it was `self.clients[language]['instance'].folder` that was assigned. I think it is intended that this behavior be retained for client instances that do not support multiple workspaces (after the `else` statement). However, linting fails for this as well unless both `self.close_client(language)` and `self.start_client(language)` are removed and replaced with `instance.initialize({'pid': instance.stdio_pid})`

For the case of supported multiple workspaces, linting works under the following separate scenarios of code _between_ `send_workspace_folder_change` and `else`.
```python
instance.folder = project_path
instance.initialize({'pid': instance.stdio_pid})
```
or
```python
self.close_client(language)
```
or
```python
self.close_client(language)
import pdb; pdb.set_trace()  # c 
```
The first case seems to work just fine.
The second case works only after closing and reopening the document.
In the last case, it seems that enough time passes between closing the client and my "continue" command that the client has auto-restarted resulting in a new client instance with the `self.clients[language]['instance'].folder` set to the `project_path`.

Is there a problem with adopting the first case? or is something wrong with `send_workspace_folder_change`? or should the behavior be independent of `self.clients[language]['instance'].folder` and something else is wrong and not respecting `self.clients[language]['instance'].watched_folders`?

**Comment by mrclary** [comment] 2020-06-28 01:53
Oh, I guess I neglected to clarify that I'm working in the context of a Spyder project.

**Comment by ccordoba12** [comment] 2020-06-28 02:33
Yep, we got that. @andfoy got a fix for this already, but I need to test it manually to see if it really fixes the problem.

**Comment by mrclary** [comment] 2020-06-28 06:44
https://github.com/palantir/python-language-server/pull/827 did not fix the problem

**Closed** 2020-07-01 02:13 UTC
Labels: component:Code Completion, type:Bug
