### ISSUE TITLE
crash when starting fresh install of Spyder Anaconda 4.3!

### ISSUE THREAD

**Issue by randomgambit** [spyder-ide/spyder#4087] opened 2017-02-01 17:19 UTC
Hello everyone,

Just installed the new Anaconda 4.3 (Python 2.7 version WIN64 installer) and I am not even able to start Spyder,

I am getting the cryptic message:

![image](https://cloud.githubusercontent.com/assets/8282510/22517880/9f0c6af0-e878-11e6-970d-d4ccb094f841.png)

I am so sad. What is going on here? 
Rebooted and reinstalled. Still the same. :(

**Comment by randomgambit** [comment] 2017-02-01 17:33
@ccordoba12 @goanpeca please tell me everything is under control here! I want to use that version :D

**Comment by ccordoba12** [comment] 2017-02-01 19:25
@randomgambit, some questions for you:

1. Did you install Anaconda in a directory with spaces or non-ascii characters on it (like tildes or non-english characters)?
2. Did you install Anaconda for all users in your computer or just you?

**Comment by randomgambit** [comment] 2017-02-01 19:28
@ccordoba12 some answers for you:

1) I dont think so. my path is `"C:\Users\mylogin\AppData\Local\Continuum\Anaconda2\pythonw.exe"`
2) just for me

**Comment by ccordoba12** [comment] 2017-02-01 19:41
And what is the output of

    qmake -query

?

**Comment by randomgambit** [comment] 2017-02-01 20:20
```

(C:\Users\m1hxb02\AppData\Local\Continuum\Anaconda2) C:\Users\mylogin>qmake -que
ry
QT_SYSROOT:
QT_INSTALL_PREFIX:C:/Users/ray/qtb-2.7-64/_b_env/Library
QT_INSTALL_ARCHDATA:C:/Users/ray/qtb-2.7-64/_b_env/Library
QT_INSTALL_DATA:C:/Users/ray/qtb-2.7-64/_b_env/Library
QT_INSTALL_DOCS:C:/Users/ray/qtb-2.7-64/_b_env/Library/doc
QT_INSTALL_HEADERS:C:/Users/ray/qtb-2.7-64/_b_env/Library/include/qt
QT_INSTALL_LIBS:C:/Users/ray/qtb-2.7-64/_b_env/Library/lib
QT_INSTALL_LIBEXECS:C:/Users/ray/qtb-2.7-64/_b_env/Library/bin
QT_INSTALL_BINS:C:/Users/ray/qtb-2.7-64/_b_env/Library/bin
QT_INSTALL_TESTS:C:/Users/ray/qtb-2.7-64/_b_env/Library/tests
QT_INSTALL_PLUGINS:C:/Users/ray/qtb-2.7-64/_b_env/Library/plugins
QT_INSTALL_IMPORTS:C:/Users/ray/qtb-2.7-64/_b_env/Library/imports
QT_INSTALL_QML:C:/Users/ray/qtb-2.7-64/_b_env/Library/qml
QT_INSTALL_TRANSLATIONS:C:/Users/ray/qtb-2.7-64/_b_env/Library/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:C:/Users/ray/qtb-2.7-64/_b_env/Library/examples
QT_INSTALL_DEMOS:C:/Users/ray/qtb-2.7-64/_b_env/Library/examples
QT_HOST_PREFIX:C:/Users/ray/qtb-2.7-64/_b_env/Library
QT_HOST_DATA:C:/Users/ray/qtb-2.7-64/_b_env/Library
QT_HOST_BINS:C:/Users/ray/qtb-2.7-64/_b_env/Library/bin
QT_HOST_LIBS:C:/Users/ray/qtb-2.7-64/_b_env/Library/lib
QMAKE_SPEC:win32-msvc2008
QMAKE_XSPEC:win32-msvc2008
QMAKE_VERSION:3.0
QT_VERSION:5.6.2

(C:\Users\mylogin\AppData\Local\Continuum\Anaconda2) C:\Users\mylogin>
```

**Comment by ccordoba12** [comment] 2017-02-01 21:06
Ok, so that's the problem.

@mingwandroid, what if we use a default `qt.conf` for the root environment to avoid this problem for most users? And use our post-install script when people wants to use install Qt in a different environment?

I mean, I know that's not a real solution but I really don't know how else to improve this situation.

**Comment by randomgambit** [comment] 2017-02-01 21:07
thanks @ccordoba12 ! Does your answer imply there is a quick fix for that problem (which is pretty radical --> I cannot even start Spyder once)

**Comment by ccordoba12** [comment] 2017-02-01 21:08
By default `qt.conf` I mean a file whose paths are fixed and not computed depending on the installation directory.

**Comment by ccordoba12** [comment] 2017-02-01 21:14
@randomgambit, I'm looking into it :-)

**Comment by randomgambit** [comment] 2017-02-01 21:15
please post it there ASAP !!!!! :D hehe

**Comment by mingwandroid** [comment] 2017-02-01 22:31
Need to figure out what's going on here..

**Comment by ccordoba12** [comment] 2017-02-01 23:05
Ray, I have a solution for this, but I'll post it tomorrow (I've got to go to sleep :-)

**Comment by randomgambit** [comment] 2017-02-01 23:08
whaaat!!! Cannot wait bro ! :D

**Comment by ccordoba12** [comment] 2017-02-02 09:25
@mingwandroid, the solution is to work with relative paths in `qt.conf` and get rid of our post install script on Windows (and possibly other OSes, but Windows would be fine to start with because it's the one that's giving us more headaches :-).

So our `qt` package would install a `qt.conf` in `Library\bin` with these contents

```ini
[Paths] 
Prefix = .. 
Binaries = . 
Libraries = ../Library/lib
Headers = ../Library/include/qt
```

and our `pyqt` package would install another `qt.conf` in the root of the environment (i.e. next to `python.exe` and `pythonw.exe`) with these contents:

```ini
[Paths] 
Prefix = Library 
Binaries = Library/bin 
Libraries = Library/lib 
Headers = Library/include/qt
```

Since the contents of those files are fixed, we don't need our post install script anymore!

I tried those files in one of my environments and they seem to work as expected (at least Spyder and qtconsole start without problems). Unfortunately, I don't have time to test if `pyqt` compiles with these changes, but you could help me to try that :-)

**Comment by ccordoba12** [comment] 2017-02-02 09:26
@randomgambit, the solution for you is to create a file named `qt.conf`using a text editor in

    C:\Users\m1hxb02\AppData\Local\Continuum\Anaconda2

with these contents

```ini
[Paths] 
Prefix = Library 
Binaries = Library/bin 
Libraries = Library/lib 
Headers = Library/include/qt
```

**Comment by ccordoba12** [comment] 2017-02-02 09:29
@mingwandroid, sorry for not have thought about this before, but it just occurred to me last night!

**Comment by mingwandroid** [comment] 2017-02-02 11:42
OK that's cool and I'm +1 on it so long as it works for hardlinked and symlinker environments but I need to know why post install scripts are not being run for some people with the 4.3 release.

It seems pretty urgent to get that fixed.

**Comment by randomgambit** [comment] 2017-02-02 12:41
@mingwandroid @ccordoba12 whoa is it that simple?? great! nut cant you have some sort of update via conda so that people can have the right file automatically?

**Comment by randomgambit** [comment] 2017-02-02 13:31
@mingwandroid @ccordoba12 it worked! cannot believe it! that s great. Is there any way this fix can mess up with my packages or the overall functioning of the program?

**Comment by mingwandroid** [comment] 2017-02-02 14:29
> @mingwandroid @ccordoba12 whoa is it that simple?? great! but can't you have some sort of update via conda so that people can have the right file automatically?

The installer already does try to write this file.

> Is there any way this fix can mess up with my packages or the overall functioning of the program?

No.

**Comment by mingwandroid** [comment] 2017-02-02 14:45
OK I found the problem. I'll add it to the agenda for the team meeting today.

**Comment by ccordoba12** [comment] 2017-02-02 18:52
So are we going to have Anaconda 4.3.1 to fix this?

**Comment by goanpeca** [comment] 2017-02-02 18:58
Yep, new release coming I bleieve

**Comment by ccordoba12** [comment] 2017-02-02 19:29
Ray, we should try to add to that release my proposed fix for qt.conf

Do you think it is feasible?

**Comment by ccordoba12** [comment] 2017-02-02 21:34
I'm closing this one as it is fixed.

**Closed by ccordoba12** 2017-02-02 21:34 UTC

**Comment by mingwandroid** [comment] 2017-02-02 21:54
Hey @ccordoba12, since I got to the root cause of the problem (it was an issue in constructor where it attempted to do binary prefix replacement on Windows causing the post install to not even run).

Now the post install gets run and it does the right thing so I think we are fine. It was decided to make the only the least amount of changes necessary to fix this issue for the new release as we didn't want to run it through the complete QA cycle so the only change is literally 2 lines of Python to `_install.py`.

**Comment by randomgambit** [comment] 2017-02-06 16:08
@ccordoba12 @mingwandroid @goanpeca Hello there. 

Unfortunately I just discovered a fatal bug in this new release. Just clicking on `maximize current pane` will **crash** Spyder beyond repair. 

This is the message I get when I clink on the pane button

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel died: 6.01600003242
WARNING:traitlets:kernel died: 6.0110001564
WARNING:traitlets:kernel died: 6.00899982452
WARNING:traitlets:kernel died: 6.00600004196
WARNING:traitlets:kernel died: 6.00599980354
WARNING:traitlets:kernel died: 6.00999999046
Traceback (most recent call last):
  File "C:\Users\mylogin\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2202, in maximize_dockwidget
    self.last_plugin.dockwidget.toggleViewAction().setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'dockwidget'

```

Any ideas?
Thanks!!

**Comment by goanpeca** [comment] 2017-02-06 16:11
@randomgambit I think this has been solved by https://github.com/spyder-ide/spyder/pull/4109

And will come in the next bugfix release

**Comment by randomgambit** [comment] 2017-02-06 16:13
thanks that s good to know. Is there any quick and dirt fix for that like the small txt file @ccordoba12 created for the original bug above? Maximizing the pane is pretty important to me... Thanks!

**Comment by nbmehar** [comment] 2017-02-11 07:20
I can't fix it. I made the file qt.conf with the exact contents you have mentioned. 
![capture](https://cloud.githubusercontent.com/assets/25382206/22851964/f0611c3e-f057-11e6-949b-3b56be68fb19.PNG)
But I couldn't find the folder continuum anywhere. 
![capture2](https://cloud.githubusercontent.com/assets/25382206/22851970/07c6313e-f058-11e6-900d-a5267ba56587.PNG)
I did find these files which are from anaconda.So I pasted the file here.
![capture4](https://cloud.githubusercontent.com/assets/25382206/22851979/4f735926-f058-11e6-8a1a-202c8f7c07de.PNG)
and also in the installed directory over here, but when I pasted the file, it asked me to replace the existing file. I replaced it. 
![capture1](https://cloud.githubusercontent.com/assets/25382206/22851997/a6e025cc-f058-11e6-8371-0a3ec4d504a3.PNG)
I still couldn't run it
![capture3](https://cloud.githubusercontent.com/assets/25382206/22852000/b21aea80-f058-11e6-853f-bb2c5b8eefe3.PNG)
