### ISSUE TITLE
Some error when open the variable to explore the value

### ISSUE THREAD

**Issue by Zeroto521** [spyder-ide/spyder#6258] opened 2018-01-21 01:32 UTC
## Description

**What steps will reproduce the problem?**

1. different to before interface 
liike this
![image](https://user-images.githubusercontent.com/25895405/35189831-2e58f22e-fe8e-11e7-88a6-36bb86eb35ba.png)

2.  click  the **Value**
3.  it happended

**Please provide any additional information below**

  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 513, in createEditor
    readonly=readonly)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1308, in setup
    readonly=readonly, remote=remote)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1260, in __init__
    title)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1145, in __init__
    minmax=minmax)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 110, in __init__
    self.set_data(data)
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 158, in set_data
    self.set_size_and_type()
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 178, in set_size_and_type
    for index in range(start, stop) ]
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 178, in <listcomp>
    for index in range(start, stop) ]
  File "C:\Software\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 78, in __getitem__
    return getattr(self.__obj__, key)
  File "C:\Software\Anaconda3\lib\site-packages\pandas\core\generic.py", line 206, in _constructor_sliced
    raise AbstractMethodError(self)
pandas.core.common.AbstractMethodError: This method must be defined in the concrete class of Series

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-21 04:51
@Prikers, could you take a look at this one, please?

**Comment by CAM-Gerlach** [comment] 2018-01-21 05:43
It seems what's happening is sporadically, CollectionsEditor as for a generic object is getting launched instead of DataFrameEditor, under unknown specific circumstances. However, it may be difficult to reproduce, as another user got the same or similar error on a minimal/toy dataframe, restarted, and then didn't see it again. Strange.

**Comment by Prikers** [comment] 2018-01-21 19:58
> @Prikers, could you take a look at this one, please?

Sure. I just need to find a way to reproduce the problem as I have never been able to do so... As mentionned by @CAM-Gerlach it was already reported in #6140 but at that time I could not find a way to reproduce the problem.

@Zeroto521 does it occur for a dataframe as simple as `df = pd.DataFrame({'Col1':[1,2,3],'col2':['a','b','c']})`?

@Zeroto521 did you try updating spyder?

**Comment by CAM-Gerlach** [comment] 2018-01-21 20:33
@Prikers There's also a chance it could be related to #3527 , based on the limited information we have, since we know detection of the correct type (in order to open the correct ``Editor``) fails at some point.

**Comment by Prikers** [comment] 2018-01-21 21:58
@CAM-Gerlach : exactly. For some reason the script fails to enter in the following condition ([here](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/variableexplorer/collectionseditor.py#L467)):
```python
elif isinstance(value, (DataFrame, DatetimeIndex, Series)) and DataFrame is not FakeObject:
```
This is possible if `DataFrame` is a `FakeObjet`, which happens if there is an error during the import of pandas classes or if pandas is outdated (<0.13.1) [(here)](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/variableexplorer/utils.py#L87). But @Zeroto521 seems to have pandas 0.21.1 installed... :confused: 

@Zeroto521 could you try running?
```
from pandas import DataFrame, DatetimeIndex, Series
```

**Comment by Zeroto521** [comment] 2018-01-22 06:10
@Prikers 
I updated my spyder(now is  v3.2.6)  yesterday,  it still occurs just..._(:3」∠)_


> df = pd.DataFrame({'Col1':[1,2,3],'col2':['a','b','c']})

I don't know, but what I meeting is dealing large data. And it comes from excel or csv.

**Comment by ccordoba12** [comment] 2018-01-22 06:16
@Zeroto521, we need a way to reproduce this in our side. Else we won't be able to fix it, sorry.

**Comment by CAM-Gerlach** [comment] 2018-01-22 06:32
> I don't know, but what I meeting [_sic_] is dealing [_sic_] large data. And it comes from excel or csv [_sic_].

So, does it happen with

> df = pd.DataFrame({'Col1':[1,2,3],'col2':['a','b','c']})

yes or no? If not, and only with particular large dataframes from excel or csv, please provide us (privately, if necessary) a csv it occurs with. If it happens with all dataframes including the above, then please try creating a new ``conda`` environment and installing just the latest version of Spyder into it, to ensure the problem doesn't have anything to do with other packages; if that works, we might be able to at least guess at which package if you post your ``conda list`` output. Furthermore, have you used Spyder successfully without this problem before? If so, what changed between then and when the problems started occurring? Anything else unusual about the packages you've installed or your system/environment? Anything installed with ``pip``, or any Spyder plugins?

Other things you can try, to rule out any installation or other user-side problems, are the other steps in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections.

**Comment by CAM-Gerlach** [comment] 2018-01-22 06:34
@Zeroto521 And did you try

``from pandas import DataFrame, DatetimeIndex, Series``

as @Prikers asked you to previously? If so, what occurred? Thanks.

**Comment by Zeroto521** [comment] 2018-01-22 09:18
@CAM-Gerlach 
> from pandas import DataFrame, DatetimeIndex, Series

It‘s no any different between using it directly  by `DataFrame` and using it by `pd.DataFrame`.
I will try to use it, but it requires time to wait for error  occurring.

> large dataframes 

I have sent a email to you.  

> df = pd.DataFrame({'Col1':[1,2,3],'col2':['a','b','c']})

I may use it to test  package Pandas function, at sometimes.  However, it never occurs error. ¯\\_(ツ)_/¯

**Comment by Prikers** [comment] 2018-01-23 21:45
@Zeroto521 can you send it to my mail? I will have a look at this issue. 
Thanks!

**Comment by Zeroto521** [comment] 2018-01-24 03:15
@Prikers 
Sorry, I can't find your email. ¯\\_(ツ)_/¯

**Comment by Zeroto521** [comment] 2018-01-29 07:37
Ok, this time it happened.
I am using that data set, it has some warning as following.
![tim 20180129153214](https://user-images.githubusercontent.com/25895405/35498528-a9ff4942-0509-11e8-91aa-2cb6d7ba2b59.png)
Already it has, but still useful. This time, it happened that.

## Detailing warning as following
```
runfile('D:/xxx/Preprocess.py', wdir='D:/xxx')
C:\Software\Anaconda3\lib\site-packages\pandas\core\ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
C:\Software\Anaconda3\lib\site-packages\pandas\core\generic.py:4355: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
D:/xxx/Preprocess.py:81: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  lambda x: replace_value[indx] if x == 'PrivacySuppressed' else x)
D:/xxx/Preprocess.py:114: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_notPotential.drop(income_label[0] + income_label[1], axis=1, inplace=True)
```

**Comment by CAM-Gerlach** [comment] 2018-01-29 07:45
Its quite unclear from what you've shown us what is triggering the error/warning, but from the fact you censored the module/directory paths, and Spyder has no module to my knowledge named ``Preprocess.py``, it looks to be a pandas error thrown by your code. I.e. you're trying to set a value using an indexer like ``loc``, ``iloc`` or ``[]`` instead of ``at``. Beyond that, I'm not sure we can draw any particular conclusions with regard to Spyder's behavior, unless it is an interaction between what appears to be a bug/bad practice in your code, and Spyder's variable explorer/console.

In any case, did you send @Prikers a/the dataset that's triggering the original bug? It seems unlikely we'll be able to make substantial progress fixing this without that. Thanks.

**Comment by CAM-Gerlach** [comment] 2018-02-03 20:06
@Zeroto521 Hey, any updates? If we aren't given the data and have no other way to reproduce this issue, it will probably have to be closed unless we hear from you or @Prikers was able to. Thanks!

**Comment by Prikers** [comment] 2018-02-03 21:12
Did not receive anything...

**Comment by Zeroto521** [comment] 2018-02-04 01:39
@Prikers 

What I can say about to you...
No EMAIL address in you home page.
_(:3」∠)_

**Comment by Prikers** [comment] 2018-02-04 19:20
@Zeroto521 I emailed you about this topic so that you can have my contact. Anyway here is where you can contact me: melaine.euzenat@gmail.com

**Comment by Prikers** [comment] 2018-02-06 21:32
I received the data. I tried playing around with it but did not manage to reproduce the problem. Will try tomorrow on my laptop (which has a slightly different python config).

**Comment by CAM-Gerlach** [comment] 2018-02-25 23:12
I tried reading in the data as well and despite open and closing it a half dozen times by different methods on Spyder 3.2.6/Python 3.6.4 on Windows 8.1, I too was unable to reproduce the error.

**Comment by ccordoba12** [comment] 2018-06-25 16:20
Closing because we were unable to reproduce this.

**Closed by ccordoba12** 2018-06-25 16:20 UTC
Labels: component:Variable Explorer, status:Awaiting Followup
