### ISSUE TITLE
Spyder crashes on "save as"

### ISSUE THREAD

**Issue by ekist85** [spyder-ide/spyder#6914] opened 2018-04-08 16:33 UTC
## Problem Description
When I go to "save as" in Spyder 3.2.8 it crashes (python included).  I have tried uninstalling and reinstalling Anaconda (and also specifically updating to the newest Spyder version).

I am running Ananconda3 (64bit)

### What steps will reproduce the problem?

1. Going to file "save as"
2. 
3. 

### What is the expected output? What do you see instead?
I need the program to work so I can save my work going forward

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:
* Python:
* Qt:
* PyQt:
* Operating System:

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2018-04-08 17:13
It looks like a duplicate of issue #3903. Please see there for a possible solution.

**Closed by ccordoba12** 2018-04-08 17:13 UTC

**Comment by ekist85** [comment] 2018-04-08 17:30
Carlos,

you are the man!  I really appreciate the guidance.  What a help
community!  Very encouraged to continue learning.

Eva


Evan Kist, CFA
e: *ekist85@gmail.com <ekist85@gmail.com>*
c: 917-930-4669

**Comment by ccordoba12** [comment] 2018-04-08 18:59
No problem, glad you were able to fix this problem with our help.

**Comment by CAM-Gerlach** [comment] 2018-04-09 03:44
Can confirm, @ccordoba12 is the man.
