### ISSUE TITLE
add option "don't check line <79 chars" in "check PEP8 compliance" in Preferences

### ISSUE THREAD

**Issue by ilrico** [spyder-ide/spyder#2558] opened 2015-07-22 15:23 UTC
PEP8 rule "line < 80 char" shouldn't be so strict (a line 82 is ok/better in most situation)
so we should be able do turn off PEP8 line-length check if needed

**Comment by bilderbuchi** [comment] 2015-07-23 07:34
related: #2359

**Comment by ccordoba12** [comment] 2015-07-23 12:09
Oh yeah! Closing as duplicate of issue #2359

**Closed by ccordoba12** 2015-07-23 12:09 UTC
Labels: duplicate, Editor, enhancement
