### ISSUE TITLE
How can I off right alt? 

### ISSUE THREAD

**Issue by koreanraichu** [spyder-ide/spyder#16862] opened 2021-11-19 07:23 UTC
### Issue Report Checklist

* [V] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [V] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Greetings. 
I use spyder first time today, but some problem occured. 
As you know saw my ID, I am korean. so I using right alt for change English-Korean input. 
I am using spyder at Ubuntu 20.04 LTS, so set right alt deactivates its original function and uses it as a Korean-English key.
It works at Pycharm, Python IDLE, chrome, gedit, and other programs except settings. (lannguage change is freely!)

But when I use spyder, it works by right alt key. 
No other key input to switch to the input period, so I cannot add footnotes. 
can you help me about deactive right alt key work as left alt key? 

+PS. 
I deactivated ALT_R function, but I still cannot Korean-English change. 

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
input language changes between English-Korean(this function that I set right alt key's)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.5
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: Ubuntu 20.04 LTS

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2021-11-19 22:01
Hey @koreanraichu, thanks for reporting. I don't understand very well: what happens in other application after you press right alt? If you can post a video or animated gif of that (using Peek, for example), it'd be great. Thanks!

**Comment by dalthviz** [comment] 2021-11-22 17:52
Hi @koreanraichu thank you for the feedback! I was trying to check this in a virtual machine but then I'm not totally sure to how to reproduce the problem you are having. 

Checking, seems like the default system shortcut to change languages is `Super + Space` which works for me when using Spyder. However, seems like you set the `Switch input source` shortcut to be the `AltGr` key, right? I tried doing that but I was unable to set the shortcut just to `AltGr` or a combination containing `AltGr`. 

Regarding Spyder my guess is that we are handling `AltGr` keystrokes as `Ctrl+Alt` at least in the Editor but not totally sure. What happens if you try to use the shortcut to change input having the focus in the IPython Console, for example?

Let us know

**Comment by koreanraichu** [comment] 2021-11-23 02:38
@ccordoba12 
![스크린샷_-2021년-11월-23일-11시-29분-50초](https://user-images.githubusercontent.com/48960370/142963270-edff71bb-8b80-4ad3-a2f7-ac0856e2711b.gif)
Since the main language is Korean, I am writing while switching between Korean and English inputs. As you can see from this gif file, the right alt key plays a role in changing the input method. Usually, there is a separate key to change the language input, which is recognized as the right alt key on Linux.

![스크린샷_-2021년-11월-23일-11시-31분-28초](https://user-images.githubusercontent.com/48960370/142963430-2bbd0755-88f0-4857-a518-706ced4c6bae.gif)
This function works normally when input in programs such as pycharm, Google Chrome, and gedit, but it is not only available in spyder. If you look at the gif above, it says Hangul every time I change the input language, but the spelling does not show the sign Hangul and the language does not change. I solved the recognition with the right alt key, but the input language is not changing.

**Comment by koreanraichu** [comment] 2021-11-23 02:50
Hi.

Thanks for your fast feedback.

I tried super+space but It doesn't work. and, I set input scroll key for 
alt+shift, but it doesn't works in spyder too.

Thanks.

**Comment by ok97465** [comment] 2021-11-23 12:18
@koreanraichu
Spyder는 qt 환경에서 실행 되는데 Spyder가 실행되는 환경에 QT 한글 입력기가 설치되지 않아서 발생하는 문제 같습니다. 이런 경우 리눅스 내부에 설치된 한글 입력 Library를 Spyder가 설치된 Python 환경에 복사해 주면 보통 해결됩니다.

저는 한글 입력을 위해 fcitx를 사용하고 Python은 anaconda를 이용하고 있어서 다음과 같은 명령어로 문제를 해결할 수 있었습니다.

```bash
cp /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so ~/anaconda3/plugins/platforminputcontexts
```

사용중인 한글 입력기(ibus, nimf, fcitx)환경과 Python 환경을 확인하시고 위의 명령어를 조금 수정하시면 Spyder에서 한글 입력이 가능할 겁니다.

좋은 하루 되세요.

**Comment by koreanraichu** [comment] 2021-11-24 02:13
@ok97465 복사해봤는데 안되네요... 저도 fcitx 쓰고 anaconda 쓰는 중이라서 복사했는데 안 먹힙니다.

**Comment by ccordoba12** [comment] 2021-11-24 03:51
@koreanraichu, did you install Spyder and fcitx-qt5 from conda-forge? As far as I understand, that's the only way to have Korean/Japanese/Chinese input for Spyder when using it through Anaconda on Linux.

**Comment by koreanraichu** [comment] 2021-11-26 03:04
@ccordoba12 I installed spyder by 'pip install spyder'. fcitx-qt5 from conda-forge mean install fcitx by 'conda install~' command? if this is right, I will try it.

**Comment by ccordoba12** [comment] 2021-11-26 03:20
I meant that you need to install Spyder by running the following commands in a terminal:

    conda create -n spyder-env -c conda-forge python=3.8 spyder fcitx-qt5
    conda activate spyder-env
    spyder

That Spyder version should behave as the other Linux apps in your system.

**Comment by koreanraichu** [comment] 2021-11-26 06:24
Oh, that's what I understood.

I will try that and I will reply if problem not solved.

thanks for your answer!

**Comment by koreanraichu** [comment] 2021-11-26 08:25
@ccordoba12 OMG Thanks! you solved this problem!!!

**Comment by ccordoba12** [comment] 2021-11-26 14:08
No problem and glad you can use Korean input in Spyder now.

Closing this issue then since it's solved.

**Closed by ccordoba12** 2021-11-26 14:08 UTC
Labels: status:Awaiting Followup
