### ISSUE TITLE
Error while saving a file

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#8926] opened 2019-03-12 11:17 UTC
### What steps will reproduce the problem?

I was saving a new file. I guess it could be solved by adding a None test?

### Traceback
```python-traceback
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/plugin.py", line 1241, in file_renamed_in_data_in_editorstack
    editorstack.rename_in_data(original_filename, filename)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/editor.py", line 1287, in rename_in_data
    finfo.editor.oe_proxy, finfo.filename)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 690, in file_renamed
    self.treewidget.file_renamed(editor, new_filename)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 298, in file_renamed
    editor_id = editor.get_id()
AttributeError: 'NoneType' object has no attribute 'get_id'
```

## Versions

* Spyder version: 4.0.0.dev0 86bc6c0d0
* Python version: 3.7.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
pyls >=0.19.0     :  0.21.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-03-12 12:17
> I guess it could be solved by adding a None test?

What do you mean?

**Comment by impact27** [comment] 2019-03-12 16:09
I don't know what happened. maybe this error can be avoided with a `if editor is not None`

**Comment by ccordoba12** [comment] 2019-03-12 17:29
I see, sure, that's a good idea. Would you like to create a PR for this?

**Comment by CAM-Gerlach** [comment] 2019-03-13 16:37
Duplicate of #8813 and your very own #8268 . Closed in favor of the former, since it has the most detailed error report isolating the exact cause of the error as well as including a directly related one.

**Closed by CAM-Gerlach** 2019-03-13 16:37 UTC
Labels: component:Editor, type:Bug
