### ISSUE TITLE
missing dependencies jedi

### ISSUE THREAD

**Issue by Soumya2020** [spyder-ide/spyder#12065] opened 2020-03-31 13:42 UTC
### What steps will reproduce the problem?

While starting spyder an error pop up appearing saying "missing dependencies jedi = 0.15.2 : 0.16.0

### Traceback
```python-traceback
  File "C:\Users\Soumyashree Sahoo\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 986, in setup
    plugin = mod.PLUGIN_CLASS(self)
TypeError: 'bool' object is not callable
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.3
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.16.0 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  None (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.12 (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-31 18:11
> While starting spyder an error pop up appearing saying "missing dependencies jedi = 0.15.2 : 0.16.0

Please read the message carefully: you have the wrong version of Jedi and you need to correct that.

> TypeError: 'bool' object is not callable

This is a duplicate of #11847. We still don't know why it happens.

**Closed by ccordoba12** 2020-03-31 18:11 UTC
