### ISSUE TITLE
Spyder5 Upgrade: Have Missing Dependencies

### ISSUE THREAD

**Issue by robert99** [spyder-ide/spyder#15169] opened 2021-04-07 15:03 UTC
### What steps will reproduce the problem?

Python 3.83, Windows 10
I upgraded to Spyder 5 using your suggested method - conda update anaconda etc

Spyder 5 upgraded and runs.
When I ran it an eror message appeared "Have Missing Dependencies" install spyder kernels >= 2.01.

Anaconda Navigator confirms I already have spyder-kernels 2.01 installed (which are the latest available). I ran conda search which confirms.

Is the error message bogus?

**Comment by dalthviz** [comment] 2021-04-07 16:30
Hi @robert99 thanks for the feedback! And yep it was a bug but a fix was added in PR #15100 (the fix will be available with Spyder 5.0.1), so you can ignore it for now.

Note: This is a duplicate of https://github.com/spyder-ide/spyder/issues/15091

**Closed by dalthviz** 2021-04-07 16:30 UTC
Labels: resolution:Duplicate
