### ISSUE TITLE
TimeoutError on switching projects

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12644] opened 2020-05-07 13:39 UTC
I don't notice any buggy behavior afterwards, but the Issue reporter still pops up with below error; latest Spyder via `conda install`, Win 10 OS.

```
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\projects\plugin.py", line 359, in close_project
    self.restart_consoles()
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\projects\plugin.py", line 516, in restart_consoles
    self.main.ipyconsole.restart()
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1068, in restart
    self.create_new_client(give_focus=False)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 703, in create_new_client
    self.register_client(client)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 918, in register_client
    shellwidget.set_cwd(cwd_path)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "D:\Anaconda\envs\viz\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "D:\Anaconda\envs\viz\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
```

<img src="https://user-images.githubusercontent.com/16495490/81301045-93a1df80-9089-11ea-9a70-a5bbf305153c.png" width="200">

**Comment by andfoy** [comment] 2020-05-07 16:10
Hi @OverLordGoldDragon, thanks for reporting this issue, however, this is a duplicate of https://github.com/spyder-ide/spyder/issues/11889, which is going to be fixed on Spyder 4.1.4, to come out on the first days of June.

**Closed by andfoy** 2020-05-07 16:10 UTC
