### ISSUE TITLE
Error when opening spydata files

### ISSUE THREAD

**Issue by mwm534** [spyder-ide/spyder#17583] opened 2022-03-30 19:57 UTC
### What steps will reproduce the problem?

Tried to open a spydata file, and was met with an error. At some point I uninstalled and reinstalled anaconda, so this is likely related to that.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 222, in <lambda>
    triggered=lambda x: self.import_data(),
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 564, in import_data
    nsb.import_data(filenames=filenames)
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 218, in import_data
    error_message = self.shellwidget.load_data(self.filename, ext)
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 155, in load_data
    return self.call_kernel(
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\commbase.py", line 437, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\commbase.py", line 493, in _sync_error
    error_wrapper.raise_error()
  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call load_data:

  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\commbase.py", line 340, in _handle_remote_call
    return_value = self._remote_callback(

  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 271, in _remote_callback
    return super(FrontendComm, self)._remote_callback(

  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    return self._remote_call_handlers[call_name](

  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\console\kernel.py", line 238, in load_data
    data, error_message = load_func(filename)

  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\spyder_kernels\utils\iofuncs.py", line 387, in load_dictionary
    data = pickle.loads(fdesc.read())

  File "C:\ProgramData\Anaconda3\envs\spyder-env\lib\site-packages\matplotlib\__init__.py", line 649, in __setitem__
    raise KeyError(

KeyError: 'animation.avconv_args is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.11
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.1.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment] 2022-03-30 20:54
Hi @mwm534 thank you for the feedback. This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/17315 so as mentioned there this could be caused do to incompatibilities between the version of matplotlib used to create the .spydata file and the version of matplotlib available in your setup when loading the .spydata file.

Could you check if the .spydata file was generated in a setup with a different version of matplotlib that the one you have installed? Let us know

**Comment by dalthviz** [comment] 2022-04-21 17:42
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/17315

**Closed by dalthviz** 2022-04-21 17:42 UTC
Labels: resolution:Duplicate
