### ISSUE TITLE
Autocomplete after colons make coding difficult

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#10996] opened 2019-12-10 02:49 UTC
After I write something like

    try: 

Spyder's autocomplete tries to give me suggestions and then I end up putting something nonsense at the end of the colon when I hit return. Insted I find myself typing 
    
    try: (then right arrow key)

and that takes up some extra time. Can we not have autocomplete after the colons? 

Cheers,

Trav

**Comment by bcolsen** [comment] 2019-12-11 00:27
Should be related to #10833

**Comment by ccordoba12** [comment] 2020-01-27 20:44
Closing as a duplicate of #10540.

**Closed by ccordoba12** 2020-01-27 20:44 UTC
