### ISSUE TITLE
try

### ISSUE THREAD

**Issue by aptlo10** [spyder-ide/spyder#5846] opened 2017-11-28 11:33 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "C:\Anaconda\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "C:\Anaconda\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope

**Comment by CAM-Gerlach** [comment] 2017-11-28 15:34
Thanks for reporting. It looks like you have one or more non-ASCII characters, perhaps in your data frame index, which Python 2 doesn't natively handle well without specific mitigations. Upgrading to Python 3 or using only ASCII characters in your df indices (probably a good practice anywhere for interoperability, since df indices should generally be kept "clean") would fix it, though it may be possible for Spyder to handle it in the next version.

**Comment by CAMGerlach-Baron** [comment] 2017-11-28 17:13
Also, this is an explicit duplicate of #5833 , which confirms the above information, so this issue can be closed.

**Closed** 2017-11-29 02:30 UTC
