### ISSUE TITLE
No text in balloon tips (in Ubuntu)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#986] opened 2015-02-17 01:00 UTC
_From [a.gupta....@gmail.com](https://code.google.com/u/115229113915800809674/) on 2012-04-04T16:00:42Z_

I installed spyder some while ago.. and from the start i cannot see text in balloon tips. The title of balloon tips is rendered in green, the box is yellow colored but there is no text in balloon tips What version of the product are you using? On what operating system? 2.1.8

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=986_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-05T13:21:45Z_

This Is the kind of bug which is platform-related: please specify your OS and window manager (Linux).

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [a.gupta....@gmail.com](https://code.google.com/u/115229113915800809674/) on 2012-04-05T21:29:56Z_

I am on Ubuntu using Gnome-shell, and window manager is compiz

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [chrisd...@gmail.com](https://code.google.com/u/106800960091976647260/) on 2012-08-27T18:03:49Z_

I have the same issue using Ubuntu 12.04 and Unity, spyder 2.1.9.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [digitale...@googlemail.com](https://code.google.com/u/103659936327272807355/) on 2013-08-13T07:39:18Z_

Same here with Ubuntu 12.04 and Gnome, Spyder 2.1.9.
But my yellow box displays the error message in white.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [ostrok...@gmail.com](https://code.google.com/u/115488699546891761023/) on 2013-09-20T16:59:24Z_

same issue
using Ubuntu 12.04 and Spyder 2.2.4

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [anmolj...@gmail.com](https://code.google.com/u/103588896585352982212/) on 2014-01-17T10:42:38Z_

I was having the same trouble after I installed Spyder today for the first time.
Then I figured out that it happens after I change "QT Windows style" under "General" settings in "Preferences" to Cleanlooks from the default GTK+.
Hopefully this will help the developers to reproduce the bug !! 

P.S. - I am using Spyder version 2.2.1 on Ubuntu 13.10 .

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [flusht...@gmail.com](https://code.google.com/u/106674403500927033956/) on 2014-04-06T09:23:46Z_

It seems that the text color of balloon tips is white make it invisible, I can't find how to change the color.
BTW: My OS is 64bit Ubuntu 14.04.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-16T09:29:30Z_

What theme are you using?

**Summary:** No text in balloon tips (in Ubuntu)  \<span class="oldvalue"> (was: no text in balloon tips) \</span>  
  **Labels:** Cat-SpyderGUI MS-v2.3.1 OpSys-Linux

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:52:50Z_

**Labels:** -MS-v2.3.1 MS-v2.3.2

**Comment by spyder-issues-migrator** [comment] 2015-02-17 01:00
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-26T10:35:21Z_

**Labels:** -MS-v2.3.2 MS-v2.4

**Comment by filippomandu** [comment] 2015-05-02 09:59
Had same issue on Ubuntu 14.04, Spyder 2.3.4

Solved following anmolj's suggestion:
in Tools\Preferences\General:
set QT Window style to GTK+
![screenshot from 2015-05-02 11 58 27](https://cloud.githubusercontent.com/assets/11250564/7440673/a465ec74-f0c2-11e4-80f0-c8c789a19c8a.png)

**Comment by ccordoba12** [comment] 2015-05-02 19:52
Thanks for letting us know about it @filippomandu, we'll see what we can do about it.

I'm closing this issue because it's a duplicate of issue #2036.

**Closed by ccordoba12** 2015-05-02 19:52 UTC
Labels: 2–5 stars, bug, duplicate, Linux, Spyder-Gui
