### ISSUE TITLE
Have Spyder offer to install spyder-kernels in virtual environments

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#16482] opened 2021-09-23 15:47 UTC
### What steps will reproduce the problem?

When a user does not have the appropriate version of `spyder-kernels` installed, the IPython console fails to start with the following message:
```
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels=2.1

or

pip install spyder‑kernels==2.1.*
```

It would be convenient if Spyder provided a dialog window offering to install the appropriate version of `spyder-kernels` (and possibly `pyqt`) for the user.

**Comment by mrclary** [comment] 2021-09-23 15:52
@spyder-ide/core-developers, what do you think of this enhancement?

**Comment by dalthviz** [comment] 2021-09-23 16:08
I think it could be nice :+1: (in that way without going outside Spyder the users can update their environments/custom interpreters to be compatible when updating Spyder). Although, we will need to detect the kind of environment (to use conda or pip) and in case of conda environments maybe the channel (main, conda-forge, other)?

**Comment by steff456** [comment] 2021-09-23 16:13
So, this dialog will pop up at the startup of Spyder? And I agree with @dalthviz, we will have to detect how to install it maybe using conda-forge channel for conda.

**Comment by ccordoba12** [comment] 2021-09-23 16:29
Although interesting, I doubt that this could work in a robust way because people can have many different kinds of environments. And even in conda envs, they could install everything with pip if they want to have the latest Pytorch or Tensorflow.

**Comment by mrclary** [comment] 2021-09-23 16:35
> Although, we will need to detect the kind of environment (to use conda or pip) and in case of conda environments maybe the channel (main, conda-forge, other)?

Yeah, I don't think that should be an issue since we already detect the environment (conda, pyenv, venv) with the python executable selected. This will directly determine whether to use a conda or pip command. 

> So, this dialog will pop up at the startup of Spyder? And I agree with @dalthviz, we will have to detect how to install it maybe using conda-forge channel for conda.

I would have it pop up only when the error occurs starting the kernel for IPython console. Maybe the user changes environments, or Spyder was updated, etc.

The channel for conda is a different question: either (a) always assume main channel, in which case we would have to always ensure that the latest spyder-kernels is on main, or (b) always install from a specific channel that is always up-to-date (e.g. spyder-dev or conda-forge) without depending on Anaconda to catch up.

> Although interesting, I doubt that this could work in a robust way because people can have many different kinds of environments. And even in conda envs, they could install everything with pip if they want to have the latest Pytorch or Tensorflow.

Regardless of the environment (conda, pyenv, venv), spyder-kernels shouldn't conflict with any packages. It could always be installed with the standard environment command (either `conda install` or `python -m pip install` or `pip install`). If we offered to install other packages (e.g. pyqt), then, yes, I can see potential issues with package conflicts. Of course, it would make sense to limit our offering to just spyder-kernels, since that is the minimum requirement for Spyder to work with the virtual environment; any other package feature (Qt backends for matplotlib) are entirely separate from Spyder and should be the user's responsibility.

**Comment by mrclary** [comment] 2021-09-23 16:49
Of course, with the dialog window, the user can always decline the offer to install spyder-kernels (or any other offerings) and take actions themselves in a terminal. If we use `--upgrade-strategy only-if-needed` for pip and `--freeze-installed` for conda to minimize any changes to the user's environment, the user should be able to revert if something breaks.

**Comment by CAM-Gerlach** [comment] 2021-09-23 19:10
As an aside, we do need error handling for cases where the user is using a system-installed Python, Anaconda, etc. where they don't have permission to install packages (not uncommon in some corporate/research environments) or the install otherwise fails. Maybe match against a list of a few known "user" errors (permissions error, unsatisfiable error, etc) with "friendly" error messages suggesting what to do, and decide whether to open an error report dialog for the rest (given the chance they may represent a solvable bug in Spyder's implementation, or at least worthy of a friendly error message), or just dump the output and continue. The former gives us insight into common failure cases we can fix, but conversely if we do miss a common case, may temporarily result in a lot of reports (though that does mean it is a case that should merit some friendlier error message at least).

> I would have it pop up only when the error occurs starting the kernel for IPython console. 

Agreed. The dialog should be shown when and only when it is actually relevant. Also, at least with the current architecture (as of our last meeting), starting the kernel is the only time we have all the information about the environment the user is starting in (as opposed to just whatever the user's current default is) readily available. 

> The channel for conda is a different question: either (a) always assume main channel, in which case we would have to always ensure that the latest spyder-kernels is on main, or (b) always install from a specific channel that is always up-to-date (e.g. spyder-dev or conda-forge) without depending on Anaconda to catch up.

I'm a bit confused; what do you mean by "main" channel? Do you mean `defaults`? The channel used by the plurality of packages in the environment? The channel used by `python`? The default channel of the `conda` executable (*conda, miniforge)? The first channel in the user's current channel config? I feel this very ambiguity, never mind trying to determine the desired channel in a particular user environment, (given, realistically, how often they contain lots of mixing channels and pip/conda packages) brings up way too much confusion and too many edge/corner cases, both with respect to what choice will maximize the chance of success and minimize further problem's in the user's environment, and also guarantee that the desired version of Spyder-Kernels is present in said channel.

We could just always installing from the `spyder-ide` channel, since we control it and can guarantee it has the appropriate versions, and it doesn't bring in a bunch of stuff that conflicts with other channels. But we'd still need to set the second fallback channel appropriately, and there is no highly reliable way to know that channel that should be (`defaults`, `conda-forge` or something else) without resorting to guessing via hueristics (like those mentioned above), or offering the user a choice (and risking them picking the wrong one).

**Comment by ccordoba12** [comment] 2021-09-23 20:09
> Regardless of the environment (conda, pyenv, venv), spyder-kernels shouldn't conflict with any packages

This assumption is incorrect. Although spyder-kernels is pure Python, it depends on IPykernel, which in turn depends on Pyzmq. And Pyzmq is a binary dependency and hence incompatible between pip, conda and conda-forge.

Therefore, I'd suggest that instead of trying to solve this problem (which would be a nightmare to get it right in all cases), we should focus on adding an env and package manager to Spyder (I know that's harder but, in my opinion, it's the right solution). At the beginning, this should be implemented only for our installers using micromamba.

**Comment by mrclary** [comment] 2021-09-23 20:13
> I'm a bit confused; what do you mean by "main" channel? 

I mean https://repo.anaconda.com/pkgs/main. This is what most users have configured for their "defaults" channel in conda config, but it does not have to be. We should not rely on a user's configuration of default channels or channel search priority.

In principle, it should not matter which channel a package comes from, as long as the dependency requirements are met. So we can install from any channel that we want. I agree that keeping it simple and using spyder-ide is preferred.

**Comment by mrclary** [comment] 2021-09-23 20:49
> > Regardless of the environment (conda, pyenv, venv), spyder-kernels shouldn't conflict with any packages
> 
> This assumption is incorrect. Although spyder-kernels is pure Python, it depends on IPykernel, which in turn depends on Pyzmq. And Pyzmq is a binary dependency and hence incompatible between pip, `defaults` and conda-forge.

Yes, I stand corrected. However, there should not be a problem between the conda main channel and conda-forge, should there? As long as the dependency versions are the same? Certainly, if `pyzmq` must be up/downgraded as a result of installing spyder-kernels, then this _may_ cause a problem for the user. However, I'd argue that:
* the user is not required to let Spyder install spyder-kernels, he can decline the offer. If one has a sensitive environment, by all means, click cancel and handle it manually.
* for either pip or conda, limiting changes to the environment is prudent (`--upgrade-strategy only-if-needed`, `--freeze-installed`)
* if this is a real issue, then it must have already manifested for users that launch Spyder from terminal, without using a separate external environment. Has this been a problem?
* It seems to me that the most common reason for a user to experience an IPython kernel error, by far, is that the appropriate version of spyder-kernels is not installed.

> Therefore, I'd suggest that instead of trying to solve this problem (which would be a nightmare to get it right in all cases), we should focus on adding an env and package manager to Spyder (I know that's harder but, in my opinion, it's the right solution). At the beginning, this should be implemented only for our installers using micromamba.

Whatever the merits may be of Spyder having its own environment and package manager, this problem would still be there. The user may still have a mix of pip and conda, etc. An environment and package manager will only move the user from the Terminal to another Spyder interface, which won't address this issue. Either Spyder will automatically install spyder-kernels in environments created by Spyder, in which this problem will certainly still exist, or Spyder will not install spyder-kernels automatically and user's will still experience kernel errors and the hassle of installing spyder-kernels in external environments.

I suppose the _real_ issue, here, is that `spyder-kernels` is required in external environments. I don't know if there is a way to get around that or not...

**Comment by CAM-Gerlach** [comment] 2021-09-23 23:48
As a disclaimer, I had been on an extended absence from Spyder for personal and family reasons so I may not be as up to date as you all on things, sorry. I've also been intimately involved in dealing with these issues for many years (along with @ccordoba12 ) so my opinion may be a bit skewed by that.

> This assumption is incorrect. Although spyder-kernels is pure Python, it depends on IPykernel, which in turn depends on Pyzmq. And Pyzmq is a binary dependency and hence incompatible between pip, defaults and conda-forge.

Yeah. I started my reply above assuming this could be mostly avoided by always using `spyder-ide`, but I realized after thinking about it (thus my last paragraph) that we'd still have to specify a fallback channel to install the rest of the dependency stack from, which would still run into almost all the same problems (even if we could guarantee availability of a specific version of Spyder-Kernels, the same would not be nessesarily true of dependencies), and I'm not sure of a straightforward way to overcome this. 

While a simple "best-effort" approach to address at least the most common cases sounds appealing and workable on the surface, mixed channel and package-type environments seem to be more the norm than the exception (particularly among users least equipt to deal with any problems) and the large number and variety of edge/corner cases this entails, and if anything going wrong with the Spyder-Kernels install may not only cause it to fail, but also break the user's existing environment. Therefore, while I'm hesitant to reject "good enough" approaches in favor of a solution (Spyder package management) that we've promised for many years and two Spyder versions but that we've as of yet been unable to secure time, developer resources and funding for, I must share @ccordoba12 's concerns toward this given the limited number of common cases it will work in, the potentially far reaching and difficult to reverse consequences of things going wrong.

> I mean https://repo.anaconda.com/pkgs/main. This is what most users have configured for their "defaults" channel in conda config, but it does not have to be. We should not rely on a user's configuration of default channels or channel search priority.

Ah, I was wondering if this is what you meant; the `defaults` channel is a superset of `pkgs/main` but not equivalent to it, and I was unaware its mapping was user re-configurable (I've never seen this in practice, and in discussions with the Conda folks `defaults` == AD == pkgs/main + pkgs/free + pkgs/r etc. was always assumed), as opposed to the distinct concept of a "default" channel (i.e. the channel assumed if not passing `-c <channel-name>`) which is designed to be user-configurable.

> In principle, it should not matter which channel a package comes from, _as long as the dependency requirements are met._

And therein lies the rub :wink: 

 > However, there should not be a problem between the conda main channel and conda-forge, should there?
 
 Oh, if only that were true...issues with mixing `defaults` and `conda-forge` (never mind the unspeakable horror that is `pip` and conda) have plagued Spyder users since the beginning, with a constant stream of issues on our tracker and elsewhere due to related issues. In fact, for this reason @ccordoba12 , @juanis2112 and I have spent months worth of time and energy writing guides, FAQs, tutorials and producing whole videos to try to educate users on how to avoid this problem and how to recover from it if it happens, due to the amount of user and dev time consumed with it.

The ever-increasing burden from this, along with other dependency/environment issues, also played a primary role in convincing @ccordoba12 to throw the organization's full official support behind creating standalone installers for the major platforms (and which we ultimately have you to thank for initiating and leading!) in an effort to avoid it, at least for Spyder itself.
 
> As long as the dependency versions are the same? Certainly, if pyzmq must be up/downgraded as a result of installing spyder-kernels, then this may cause a problem for the user.
 
Depending on the user's environment, channel settings and conda version, this can pull in a whole long tail of dependencies from whatever we select as the fallback channel, or even worse switch existing deps to a different channel. Never mind if something in the stack is already installed with pip which can mean duplicate packages get installed, as is not uncommon and is a virtual guarantee of future problems.

> the user is not required to let Spyder install spyder-kernels, he can decline the offer. If one has a sensitive environment, by all means, click cancel and handle it manually.

The problem, as I allude to above, is that the set of users who would most benefit from this (beginner-intermediate who have ventured outside the confines of the `base` environment, which has a compatible version of Spyder installed by default and upgraded when Spyder is, and those using standalone Spyder with a separate Anaconda install) tend to be (in my experience assisting users IRL and online) most likely to have environments with mixed channels/install methods, are least able to determine whether their environment is "sensitive", and are least able to recover from something going wrong (as they are likely  to copy/paste install commands they find online, don't yet understand the complexities of pip, conda, CF, channels, etc, and are adventurous enough to install lots of different packages but want things to "just work" and don't necessarily (want to) know _how_).

> for either pip or conda, limiting changes to the environment is prudent (--upgrade-strategy only-if-needed, --freeze-installed)

This would help, but this still doesn't really solve the issue of mixed channels or mixed package types, as either those packages would be left untouched, potentially breaking Spyder-Kernels, or modified, breaking other current/future installed packages. Nor does either solve the problem of reliably determining which channel to install from/install method to use.

> if this is a real issue, then it must have already manifested for users that launch Spyder from terminal, without using a separate external environment. Has this been a problem?

As you've probably gathered by now...the answer is a resounding "yes". Its driven a large proportion of our documentation, troubleshooting and user education efforts, as well as the big push toward standalone installers, built-in env management and exploration of other ways to help mitigate these issues.

> It seems to me that the most common reason for a user to experience an IPython kernel error, by far, is that the appropriate version of spyder-kernels is not installed.

It is a relatively common, but we provide step by step guidance on how to address it in the error message itself, in our docs, in our website/FAQs, on our issue tracker, on our Youtube channel, etc, and it only takes a couple minutes to do so, either with or without our help. At least in my past experience, most of the reports related to this were edge cases where the basic/recommended approach didn't work, bugs in Spyder, or due to some other issue, none of which a simple best-effort install command could easily handle. Conversely, reports of users with broken environments due to mixed channels, packages, deps, etc have been an ever-present issue, and often took far longer both in terms of dev and user time/effort to resolve. The serious concern here is that unless done carefully and part of a comprehensive system, a simple/best-effort approach could turn many of the former into the latter.

> Whatever the merits may be of Spyder having its own environment and package manager, this problem would still be there.

Yeah, the problem would still exist and it is certainly no magic bullet. However, more complete package management features would have two primary benefits here.

First, it would inherently have much more robust and comprehensive facilities for diagnosing the user's existing environment, determining the installation strategy that would be least likely to negatively affect other packages, and offer effective, user-friendly means for troubleshooting and recovering from a problem if one occurs, whether by the user themselves or under the direction of Spyder/sysadmin personnel. In fact, the primary motivation for us adding such support is not just be adding an oft-requested a user-facing feature, but _specifically_ to try to address this core underlying problem.

Second, if and when users (especially those with lesser experience with package and environment management that are more likely to want and gravitate toward built-in, officially supported GUI functionality over external CLI tools) use Spyder's package management to create and manage environments, by defaulting to and enforcing good package management practices, this can greatly reduce the chance of problematic or indeterminate environments to begin with, while detailed logging, a higher-level of abstraction/intention and full Spyder control over/awareness of the environment and its contents will enable more reliable determination of the optimal channel and install method, and easier recovery should something still go awry.

> I suppose the real issue, here, is that spyder-kernels is required in external environments. I don't know if there is a way to get around that or not...

Even if it was theoretically feasible (before spyder-kernels, the standard approach was to just install Spyder itself in the environment you wanted to run it in), it would at the very least not be possible to use many of Spyder's core features, e.g. Variable Explorer, Plotting, etc. without some kind of bespoke dependency in the target environment, and more importantly would still require significant dependencies in the target envs (e.g. ipykernel, ipython, etc), at least without bringing back the obsolete (non-I) python console pane from the days of Spyder 2, which uses a totally different architecture and wouldn't be able to use basically any of modern Spyder's features.

**Comment by mrclary** [comment] 2021-09-24 01:51
>>  if this is a real issue, then it must have already manifested for users that launch Spyder from terminal, without using a separate external environment. Has this been a problem?

> As you've probably gathered by now...the answer is a resounding "yes".

I believe this is the result of trying to install packages in the same environment as Spyder, with much more overlapping problematic dependencies. I think this problem is almost entirely eliminated by having separate environments for Spyder and IPython consoles. Standalone applications certainly match this paradigm. But the fundamental issue is that the connection between the Spyder environment and the IPython console environment cannot be _completely_ severed because we still need spyder-kernels there, but this is a _much_ smaller problem compared to running Spyder in the same environment.

I understand that you're saying that Spyder, if it has its own package management, can better control this issues. I say it cannot. We will be left with exactly the same problem. If a user, whether using a Spyder package manager or not, installs stuff (in an external environment) with pip, conda-forge, defaults (main), from source, etc., the problem is still there and Spyder will not be any better equipped to deal with it than if it did not have its own package manager. 

The only way to "better control" the situation is to have Spyder _limit_ which and how packages can be installed. But then we don't need a package manager for that. All we need is a dedicated conda channel with versions that are all compatible with spyder-kernels. But then we'll always get requests for "why don't you have package x version y?", which will greatly increase the maintenance time for developers anytime a version gets bumped.

begin soap-box...
I don't think IPython consoles should ever use Spyder's internal environment. I don't think it should even be an option in the preferences. I think it is best to always run IPython consoles in separate virtual environments. It would be awesome, especially for newbies, if Spyder "automagically" created such environments for them behind the scenes. But a "package manager" will not alleviate potential problems between packages the user wants and spyder-kernels. The only way to alleviate that is to provide a "gate-keeper" that determines what packages can and cannot be installed and from where. This is orthogonal to a package manager. That is, you can have any combination of [package manager/no package manager] and [gate-keeping/no gate-keeping]; it is only the gate-keeping that will provide a solution to this problem. But that is a trade-off between spending time addressing package management issues from users and maintaining a (boundless) curated list of compatible packages.

This all seems like a lot of hassle, just for a few dependencies.
...end soap-box

I think this warrants a deeper discussion at a developer meeting.

**Comment by CAM-Gerlach** [comment] 2021-09-25 00:06
> I believe this is the result of trying to install packages in the same environment as Spyder, with much more overlapping problematic dependencies. 

This definitely was the biggest problem area, and was the main reason for moving toward standalone installable packages with a locked down runtime environment as the primary, officially supported Spyder install method. But there is still significant potential for issues so long as Spyder requires a non-trivial dependency stack (spyder_kernels/jupyter_client/core/ipython/ipykernel/pyzmq, etc) to be present in the working environment that Spyder doesn't have control over, and indeed many are still reported. Having Spyder try to guess the safest way of installing Spyder-Kernels in an arbitrary, likely mixed/fragile environment that could potentially bork it beyond the user's capability to easily recover adds substantially to that risk. While it is always possible the user could do so themselves, either following our guides or using their typical approach for installing packages is, on the whole, less likely to break things than Spyder guessing an approach, and avoids Spyder being responsible for doing so.

> If a user, whether using a Spyder package manager or not, installs stuff (in an external environment) with pip, conda-forge, defaults (main), from source, etc., the problem is still there and Spyder will not be any better equipped to deal with it than if it did not have its own package manager.

I'm not sure I feel the same. As I explained above, with package management support, Spyder could diagnose the environment for potential problems (e.g. mixed channel or conda/pip for packages in the critical dependency stack for spyder-kernels), make a better informed decision on the install method least likely to break it, and offer options for recovering the environment (uninstall, rollback, etc) should problems result. Furthermore, Spyder managing the user's environments (e.g. auto-creating a new environment per project, as you suggest, and installing requested packages into it) can either refuse to mix channels/package types (at least for critical dependencies, or at the very least offer users a warning so they understand what they're doing may break things and is at their own risk.

> The only way to "better control" the situation is to have Spyder limit which and how packages can be installed. 

What I'm suggesting is that the package manager would default to best practices (e.g. install from a specific channel per environment without tedious low-level conda config or remember it for every command) and limit bad ones, by preventing or warning the user when they were executing an operation that is potentially unsafe (e.g. mixing channels or pip/conda for packages that are dependents of existing packages, particularly those of Spyder). For advanced users who want to work outside these constraints, they could either disable them or use their own package management tools, but they are the very sort of users best aware of and equipt to resolve any problems that result.

> I don't think IPython consoles should ever use Spyder's internal environment. I don't think it should even be an option in the preferences. I think it is best to always run IPython consoles in separate virtual environments. 

Personally, I never use the internal environment and always use an array of per-project envs, and this was considered when creating the installers. However, given this makes Spyder usable out of box without additional installations and configuration (just like it is with Anaconda), and given the environment contains a wide variety of basic scientific packages, it is useful for beginners whose code likely won't need more than what is already built in, at least at first, whereas they would have to install, configure and select a whole other Python environment to do so otherwise despite a fully functional one being available. As Spyder is a particularly popular tool for beginners, students and scientists that may not be as familiar with environment management, this would be a significant loss for those populations (never mind it means it wouldn't work in online mode on Binder). Conversly, the internal environment is frozen and it is impossible to directly access or install/uninstall packages in it, and is reproducible across Spyder installs of the same version, I'm not sure I understand the harm in leaving it accessible, though once we have package management support, users will be guided away from it.

> This is orthogonal to a package manager.

To be clear, when we're talking about "package management functionality", we're not talking about writing our own low level package manager, but rather a high-level, friendlier, safer wrapper for existing package/environment managers integrated with Spyder projects, something generally analogous to Aptitude or Anaconda Navigator (which actually started, as I recall, as a project by the Spyder team to bring this functionality to Spyder), to make good practices for package and environment as simple as practical. Naturally, like any such tool, this would come at the expense of some of the power and flexibility of the low-level CLI commands (i.e. `pip` and `conda`), but for many or even most Spyder users, this tradeoff would be acceptable and a net positive in terms of enabling and encouraging good package and environment management practices with minimal friction.

**Comment by CAM-Gerlach** [comment] 2021-09-25 00:07
> I think this warrants a deeper discussion at a developer meeting.

I'd be totally on board to participate, if @ccordoba12 is interested. @mrclary has been such a great person to have at the UX meetings (not sure if those are still happening) and I'd think it would be a valuable discussion to have at some point.

**Comment by ccordoba12** [comment] 2021-09-25 20:58
> However, there should not be a problem between the conda main channel and conda-forge, should there? As long as the dependency versions are the same?

There is. `defaults` and conda-forge are mostly incompatible with respect to binary packages.

> the user is not required to let Spyder install spyder-kernels, he can decline the offer. If one has a sensitive environment, by all means, click cancel and handle it manually.

If users find this functionality useful, they'll force us (by filling bug report after bug report) to make it work under a lot of scenarios and as robustly and reliably as possible. Only users that understand how envs really work could decide when it's a good idea to handle the installation manually, but those are very few and probably don't need something like that. I'm almost sure the rest would like to see something that just works.

> for either pip or conda, limiting changes to the environment is prudent (--upgrade-strategy only-if-needed, --freeze-installed)

The problem is to reliably identify when a user used pip, defaults or conda-forge to install their packages. I think that's simply impossible because people usually mix the three of them as if they were interchangeable, when actually they are not. Furthermore, in some cases conda can get stuck for hours trying to update an env due to odd constraints.

> Whatever the merits may be of Spyder having its own environment and package manager, this problem would still be there.

Yes and no. Yes, for envs not created by Spyder's manager, but for those envs there's no hope that we could detect and use the appropriate tool to install spyder-kernels. So, it'll continue to be the user's responsibility, as it is now, to use pip or conda/conda-forge to manage their envs. And no, for envs created by our manager because we will always use conda-forge. I expect people wouldn't mess with their envs by installing packages manually, if we give them a graphical tool for that. But if they do, we can remove and recreate any env and start all over again.

> I suppose the real issue, here, is that spyder-kernels is required in external environments. I don't know if there is a way to get around that or not...

No, there isn't. The minimal requirement for any application that uses the Jupyter architecture to run Python code in an external interpreter is IPykernel. And Spyder-kernels is just a subclass of it with a lot of extra functionality to connect the kernel to Spyder.

> the problem is still there and Spyder will not be any better equipped to deal with it than if it did not have its own package manager.

I disagree. The problem wouldn't be there (or at least it'd be greatly minimized) because we will control how spyder-kernels is installed. Trying to guess how to install it in a random env is simply an ill-posed problem (as @CAM-Gerlach explained quite clearly above).

> The only way to alleviate that is to provide a "gate-keeper" that determines what packages can and cannot be installed and from where

The package manager would be the gate-keeper by only allowing to install packages from conda-forge. We could even keep a list of packages installed by the manager in the env and run a check against the current list of packages. If we detect they are different, we could show a warning to users telling them that problems would be likely to show up and it's not our responsibility to fix them.

**Comment by ccordoba12** [comment] 2021-09-25 21:13
I think @CAM-Gerlach and I clearly understand what's at stake here and I agree with all comments he posted above. This is particularly relevant:

> To be clear, when we're talking about "package management functionality", we're not talking about writing our own low level package manager, but rather a high-level, friendlier, safer wrapper for existing package/environment managers integrated with Spyder projects, something generally analogous to Aptitude or Anaconda Navigator.

> I think this warrants a deeper discussion at a developer meeting.

@mrclary, unfortunately I have very little free time these days, so I couldn't make it. But you could meet with @CAM-Gerlach and other members of the core team to talk about this.

However, I think there's little else to discuss. I think your proposal is unfeasible for the reasons @CAM-Gerlach and I explained above.

**Comment by ccordoba12** [comment] 2021-09-25 21:18
The good news is that our main sponsor (TDK-Micronas) could fund the development of a package manager next year (they are very interested in having it for their users). If that doesn't crystallize, we could also apply to Numfocus development grants to get this done.

In any case, after releasing the installers last year, I knew this will become a pressing issue. The problem is we created this new API for Spyder 5 and all our free time has been consumed by it. Hopefully we will finish the migration to it early next year.

**Comment by mrclary** [comment] 2021-09-25 23:33
@ccordoba12 @CAM-Gerlach, thank you both for your patience and willingness to discuss this issue. I now agree that providing this small functionality will open a pandora's box before we're ready to provide the superior solution. I do think that Spyder's own environment and package manager will be a welcome and worthwhile feature and I look forward to contributing to its development.

**Closed** 2021-09-25 23:34 UTC
Labels: type:Enhancement, type:Feature

**Comment by ccordoba12** [comment] 2021-09-26 00:47
Thanks for understanding @mrclary! We will try hard to create a package manager for Spyder next year.

**Comment by CAM-Gerlach** [comment] 2021-09-26 04:05
FWIW, @ccordoba12 basically said everything I wanted to say, but more clearly and eloquently and in half the words, heh.

@mrclary Thanks for understanding, and even better for offering to pitch in on the package management support—I'm sure that would be a huge help in finally implementing a feature we've always wanted to add but hadn't yet been able to fully scrape together all the dev time for given the other priorities that kept coming up.

Sidenote @ccordoba12 —why did @spyder-bot re-open the issue?

**Comment by ccordoba12** [comment] 2021-09-26 13:44
Removing the "awaiting followup" label makes the bot think we decided the issue is a big and we want to solve it.

**Comment by CAM-Gerlach** [comment] 2021-09-27 06:57
@ccordoba12 Given that any core dev with triage perms who is able to remove the label can also re-open the issue just as easily in a second or two, whereas there are plenty of concievable circumstances where that label was removed after the issue was rightfully closed, I'm not sure the rationale for having the bot override a core dev's decision and re-open it. But maybe there's something I'm missing here.
