### ISSUE TITLE
Over-aggressive auto-completion?

### ISSUE THREAD

**Issue by capitanevs** [spyder-ide/spyder#21292] opened 2023-08-28 09:36 UTC
Hello,

I wanted to share some feedback regarding the new autocompletion feature.

While using the autocompletion, I've noticed a behavior that has led to a few unintended mistakes in my code. For instance, consider the following cell:

```
#%% test cell 
variable_50_name = 10

print('=' * 40)

```
In a scenario where I intend to change "40" to "50" and rerun the cell, I found that the autocompletion occasionally interrupts my workflow. Specifically, when attempting to modify "4" to "5," the autocompletion feature can inadvertently trigger, causing unexpected behavior when I press Ctrl+Enter to run the cell. See pics below:

**I edit 4 into 5...**
![immagine](https://github.com/spyder-ide/spyder/assets/13431660/6b3d3872-c476-4946-9cc2-2eefdd5239cd)

**I just do not realise the autocompletion suggestion and I press ctrl+enter**
![immagine](https://github.com/spyder-ide/spyder/assets/13431660/0edde9df-175c-40e4-a3bb-fc0dd2bedd26)

I believe a smoother experience could be achieved if the autocompletion were to be more seamlessly integrated during editing, avoiding unintended interactions during code modification and execution. Actually, now, I have to pay more attention to IGNORE autocompletion advices than before. I think that most of the conflict is due to the fact that {enter} is used both for autocompletion (instead of TAB) and for cell running.

A similar unwanted behavior happens when I want to write hust the name of a function , say `foo`, then go to a new line. 
When I press enter, `foo` is automatically replaced into `foo()`, which is not what I want.

Thank you for considering this feedback. It's intended to foster a more user-friendly experience for all users.

BEsts,
Mike

EDIT 
Spyder IDE version 5.4.3

**Comment by dalthviz** [comment] 2023-08-28 22:20
Hi @capitanevs thank you for the feedback! Actually, I think the autocompletion when you do `Ctrl +Enter` is a bug 🤔 Since a modifier is being used alongside `Enter`, I would say that the completion widget should be dismissed and instead the action with an associated shortcut triggered. But in general, what do you think @spyder-ide/core-developers ?

**Comment by bcolsen** [comment] 2023-08-29 04:29
Would this be fixed if #12728 was implemented? 

As a cell user this one gets me too from time to time.

**Comment by dalthviz** [comment] 2023-08-30 20:48
Hi @bcolsen ! Actually this seems like a duplicate of #12728 indeed :+1:

**Comment by dalthviz** [comment] 2023-08-31 19:28
Thank you for checking #12728 and confirming that both issues are asking for the same option @capitanevs ! I will close this as a duplicate of #12728 then but feel free to provide further feedback over #12728 :)

**Closed by dalthviz** 2023-08-31 19:28 UTC
Labels: resolution:Duplicate, type:Enhancement, component:Editor, component:Code Completion and linting, type:Discussion, status:Awaiting Followup
