### ISSUE TITLE
Open file

### ISSUE THREAD

**Issue by patrmccormack** [spyder-ide/spyder#5933] opened 2017-12-09 10:26 UTC
## Description

**What steps will reproduce the problem?**

1. Open spyder under Python 3.6
2. Click on open file icon 
3. Error

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/spyder/plugins/editor.py", line 1841, in load
    self.edit_filetypes = get_edit_filetypes()
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/spyder/config/utils.py", line 124, in get_edit_filetypes
    supported_exts = _get_pygments_extensions()
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/spyder/config/utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (/home/pat/apps/anaconda2/envs/py3mqtt/lib/python3.6/site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-09 20:44
Thanks for reporting; this is a duplicate of e.g. #5673. As the error message states, Jedi is only compatible with `parso` 0.1.0, not, 0.1.1. Therefore, please downgrade to 0.1.0 to fix this, and this issue can be closed.

**Comment by ccordoba12** [comment] 2017-12-10 00:59
You can also update Jedi with

    conda update jedi

to fix this problem.

**Closed by ccordoba12** 2017-12-10 00:59 UTC

**Comment by patrmccormack** [comment] 2017-12-10 10:23
thanks

“A goal without a plan is just a wish.”
― Antoine de Saint-Exupéry
<http://www.goodreads.com/author/show/1020792.Antoine_de_Saint_Exup_ry>
