### ISSUE TITLE
variations problem

### ISSUE THREAD

**Issue by casnj** [spyder-ide/spyder#9797] opened 2019-07-09 09:29 UTC
### What steps will reproduce the problem?

the parameter can't be explorered via the variable explorer

### Traceback
```python-traceback
  File "D:\PythonIDE\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 476, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "D:\PythonIDE\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.5.2
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.9.4-1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  1.7.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-09 09:48
Duplicate of issue #9794.

**Closed by ccordoba12** 2019-07-09 09:48 UTC
