### ISSUE TITLE
spyder says to public on github

### ISSUE THREAD

**Issue by Spash194** [spyder-ide/spyder#6480] opened 2018-02-19 22:57 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\User\Anaconda2\lib\site-packages\spyder\widgets\findreplace.py", line 283, in show
    self.refresh()
  File "C:\Users\User\Anaconda2\lib\site-packages\spyder\widgets\findreplace.py", line 320, in refresh
    self.find()
  File "C:\Users\User\Anaconda2\lib\site-packages\spyder\widgets\findreplace.py", line 441, in find
    total_matches=number_matches)
  File "C:\Users\User\Anaconda2\lib\site-packages\spyder\widgets\findreplace.py", line 575, in change_number_matches
    total_matches)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2018-02-20 14:58
Thanks for reporting. This is a duplicate of issue #6187 and it'll be fixed in our 3.2.7 version.

**Closed by ccordoba12** 2018-02-20 14:58 UTC
