### ISSUE TITLE
Cannot start spyder

### ISSUE THREAD

**Issue by zihanw4** [spyder-ide/spyder#13045] opened 2020-06-17 03:50 UTC
I'm pretty new to python, and just starting learning it with some books. One of the books recommended me to install anaconda, so I followed. When I was exploring the functions, I found that every time I try to turn on the Spyder, it comes up something like this.

Traceback (most recent call last):
File "D:\ANACONDA3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "D:\ANACONDA3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "D:\ANACONDA3\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "D:\ANACONDA3\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "D:\ANACONDA3\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 141, in start
self.kite_process = run_program(path)
File "D:\ANACONDA3\lib\site-packages\spyder\utils\programs.py", line 214, in run_program
return subprocess.Popen(fullcmd, **subprocess_kwargs)
File "D:\ANACONDA3\lib\subprocess.py", line 800, in init
restore_signals, start_new_session)
File "D:\ANACONDA3\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Pretty confused and hopefully can get some guidance.

Thanks

**Comment by dalthviz** [comment] 2020-06-17 16:31
Hi @zihanw4 I think this is a duplicate of #11597.

What version of Spyder are you running? If needed, please update Spyder by running from an Anaconda Prompt:
```
conda install spyder=4.1.3
```

Also, the way to fix this is explained here: https://github.com/spyder-ide/spyder/issues/11597#issuecomment-588392485

Basically a faulty installation of Kite could cause this. If that's the case, you need to manually remove the folder created by Kite since it probably doesn't have a uninstaller available.

Closing this as a duplicate for now, but let us know if the info provided helps you start Spyder :)

**Closed by dalthviz** 2020-06-17 16:31 UTC
