### ISSUE TITLE
RunTimeError when splitting the window 

### ISSUE THREAD

**Issue by Geodude-93** [spyder-ide/spyder#20148] opened 2022-12-03 15:12 UTC
### What steps will reproduce the problem?

While splitting the window (both vertically or horizontally) I get the following runtime Error over and over again until I close the second window again. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1897, in update_code_analysis_actions
    editor = self.get_current_editor()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1754, in get_current_editor
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1909, in update_todo_actions
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 2689, in current_editor_cursor_changed
    code_editor = self.get_current_editor()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1754, in get_current_editor
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1881, in opened_files_list_changed
    editor = self.get_current_editor()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1754, in get_current_editor
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1799, in refresh_save_all_action
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1449, in save_focused_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/pylint/plugin.py", line 171, in _set_filename
    self.get_widget().set_filename(editor.get_current_filename())
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1764, in get_current_filename
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1897, in update_code_analysis_actions
    editor = self.get_current_editor()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1754, in get_current_editor
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1909, in update_todo_actions
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 2689, in current_editor_cursor_changed
    code_editor = self.get_current_editor()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1754, in get_current_editor
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1881, in opened_files_list_changed
    editor = self.get_current_editor()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1754, in get_current_editor
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1799, in refresh_save_all_action
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1449, in save_focused_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/pylint/plugin.py", line 171, in _set_filename
    self.get_widget().set_filename(editor.get_current_filename())
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1764, in get_current_filename
    editorstack = self.get_current_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "/home/keving/.conda/envs/kgdas/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
```

## Versions

* Spyder version: 5.4.0  (conda)
* Python version: 3.9.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.11.0-36-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.0 (OK)
keyring >=17.0.0              :  23.11.0 (OK)
nbconvert >=4.0               :  7.2.5 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.6 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.3 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.5.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment] 2022-12-03 16:03
Hey @Geodude-93, thanks for reporting. This is a duplicate of issue #20144 and we'll fix it in our next version (5.4.1), to be released before the end of the year.

In the meantime, please don't open new editor windows.

**Closed by ccordoba12** 2022-12-03 16:03 UTC
