### ISSUE TITLE
The button to interrupt the kernel does not work

### ISSUE THREAD

**Issue by analyticssolvers** [spyder-ide/spyder#20660] opened 2023-03-08 18:59 UTC
### What steps will reproduce the problem?

Recurringly, Spyder stops working after running a code. It is impossible to interrupt the kernel using the console button or using CTrl-c. I have to reboot the kernel. When I restart it, it first prints to the console the result it was calculating and then totally resets. It is very annoying because it has been a recurring theme for several years, which disappears for seasons. I don't know the real cause of this problem. While the code is running and without being able to interrupt the channel, I can use all the menus of the IDE

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.1 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Martin\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
_py-xgboost-mutex         2.0                       cpu_0  
_tflow_select             2.3.0                       mkl  
abseil-cpp                20211102.0           hd77b12b_0  
absl-py                   1.3.0            py39haa95532_0  
adal                      1.2.7              pyhd3eb1b0_0  
aiohttp                   3.8.3            py39h2bbff1b_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
amply                     0.1.5              pyhd8ed1ab_0    conda-forge
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.2            py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
astroid                   2.14.1           py39hcbf5309_0    conda-forge
astunparse                1.6.3                      py_0  
async-timeout             4.0.2            py39haa95532_0  
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0           py39haa95532_0  
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.11.0           py39haa95532_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.2            py39hb82d6ee_0    conda-forge
beautifulsoup4            4.11.1           py39haa95532_0  
binaryornot               0.4.4                      py_1    conda-forge
black                     23.1.0           py39hcbf5309_0    conda-forge
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.4              py39haa95532_0  
bottleneck                1.3.5            py39h080aedc_0  
brotli                    1.0.9                h2bbff1b_7  
brotli-bin                1.0.9                h2bbff1b_7  
brotlipy                  0.7.0           py39h2bbff1b_1003  
bzip2                     1.0.8                he774522_0  
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h2bbff1b_3  
chardet                   4.0.0           py39haa95532_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py39haa95532_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2            py39haa95532_1  
colorama                  0.4.6            py39haa95532_0  
comm                      0.1.2            py39haa95532_0  
conda                     23.1.0           py39haa95532_0  
conda-build               3.23.3           py39haa95532_0  
conda-content-trust       0.1.3            py39haa95532_0  
conda-env                 2.6.0                haa95532_1  
conda-package-handling    2.0.2            py39haa95532_0  
conda-package-streaming   0.7.0            py39haa95532_0  
conda-repo-cli            1.0.27           py39haa95532_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         4  
contourpy                 1.0.5            py39h59b6b97_0  
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              38.0.4           py39h21b164f_0  
cssselect                 1.1.0              pyhd3eb1b0_0  
custom-inherit            2.4.0              pyhd8ed1ab_0    conda-forge
cvxpy                     1.3.0                    pypi_0    pypi
cx_oracle                 8.3.0            py39h8cc25b3_0  
cycler                    0.11.0             pyhd3eb1b0_0  
daal4py                   2021.4.0         py39h8cb3d55_0  
dal                       2021.4.0           haa95532_729  
dcor                      0.6                pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1            py39hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.13           py39haa95532_0  
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docstring-to-markdown     0.11               pyhd8ed1ab_0    conda-forge
docutils                  0.18.1           py39haa95532_3  
dtw                       1.4.0                    pypi_0    pypi
ecos                      2.0.12                   pypi_0    pypi
emd                       0.5.5              pyhd8ed1ab_0    conda-forge
entrypoints               0.4              py39haa95532_0  
et_xmlfile                1.1.0            py39haa95532_0  
fastparquet               0.5.0            py39h080aedc_2  
fftw                      3.3.9                h2bbff1b_1  
filelock                  3.9.0            py39haa95532_0  
flake8                    6.0.0              pyhd8ed1ab_0    conda-forge
flatbuffers               2.0.0                h6c2663c_0  
flit-core                 3.6.0              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               ha860e81_0  
frozenlist                1.3.3            py39h2bbff1b_0  
future                    0.18.2           py39haa95532_1  
gast                      0.5.3              pyhd3eb1b0_0  
geographiclib             1.52                     pypi_0    pypi
geopy                     2.2.0                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_1  
gitdb                     4.0.7              pyhd3eb1b0_0  
gitpython                 3.1.30           py39haa95532_0  
glib                      2.69.1               h5dc1a3c_2  
glob2                     0.7                pyhd3eb1b0_0  
glpk                      4.65                 h2bbff1b_3  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
grpcio                    1.42.0           py39hc60d5dd_0  
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
h5py                      3.7.0            py39h3de5c98_0  
hdf5                      1.10.6               h1756f20_1  
icc_rt                    2022.1.0             h6049295_2  
icu                       58.2                 ha925a31_3  
idna                      3.4              py39haa95532_0  
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
imbalanced-learn          0.7.0                      py_1    conda-forge
importlib-metadata        4.11.3           py39haa95532_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.4.0          haa95532_3556  
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.19.2           py39hd4e2768_0  
ipython                   7.31.1           py39haa95532_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
jedi                      0.18.1           py39haa95532_1  
jellyfish                 0.9.0            py39hb82d6ee_1    conda-forge
jinja2                    3.1.2            py39haa95532_0  
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
joblib                    1.1.1            py39haa95532_0  
jpeg                      9e                   h2bbff1b_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.16.0           py39haa95532_0  
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.1            py39haa95532_0  
jupyter_server            1.23.4           py39haa95532_0  
jupyterlab                3.5.3            py39haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.16.5           py39haa95532_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keras                     2.9.0            py39haa95532_0  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
keyring                   23.4.0           py39haa95532_0  
kiwisolver                1.4.4            py39hd77b12b_0  
lazy-object-proxy         1.6.0            py39h2bbff1b_0  
lerc                      3.0                  hd77b12b_0  
libarchive                3.6.2                hebabd0d_0  
libbrotlicommon           1.0.9                h2bbff1b_7  
libbrotlidec              1.0.9                h2bbff1b_7  
libbrotlienc              1.0.9                h2bbff1b_7  
libclang                  12.0.0          default_h627e005_2  
libcurl                   7.87.0               h86230a5_0  
libdeflate                1.8                  h2bbff1b_5  
libffi                    3.4.2                hd77b12b_6  
libiconv                  1.16                 h2bbff1b_2  
liblief                   0.12.3               hd77b12b_0  
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.20.3               h23ce68f_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libssh2                   1.10.0               hcd4344a_0  
libtiff                   4.5.0                h6c2663c_1  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.4                h2bbff1b_0  
libwebp-base              1.2.4                h2bbff1b_0  
libxgboost                1.7.3                hd77b12b_0  
libxml2                   2.9.14               h0ad7f3c_0  
libxslt                   1.1.35               h2bbff1b_0  
llvmlite                  0.39.1           py39h23ce68f_0  
lxml                      4.9.1            py39h1985fb9_0  
lz4-c                     1.9.4                h2bbff1b_0  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
markdown                  3.4.1            py39haa95532_0  
markupsafe                2.1.1            py39h2bbff1b_0  
matplotlib                3.6.2            py39haa95532_0  
matplotlib-base           3.6.2            py39h1094b8e_0  
matplotlib-inline         0.1.6            py39haa95532_0  
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
menuinst                  1.4.19           py39h59b6b97_0  
mistune                   0.8.4           py39h2bbff1b_1000  
mkl                       2021.4.0           haa95532_640  
mkl-service               2.4.0            py39h2bbff1b_0  
mkl_fft                   1.3.1            py39h277e83a_0  
mkl_random                1.2.2            py39hf11a4ad_0  
mpmath                    1.2.1            py39haa95532_0  
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.2            py39h2bbff1b_0  
munkres                   1.1.4                      py_0  
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
navigator-updater         0.3.0            py39haa95532_0  
nbclassic                 0.4.8            py39haa95532_0  
nbclient                  0.5.13           py39haa95532_0  
nbconvert                 6.5.4            py39haa95532_0  
nbformat                  5.7.0            py39haa95532_0  
nest-asyncio              1.5.6            py39haa95532_0  
notebook                  6.5.2            py39haa95532_0  
notebook-shim             0.2.2            py39haa95532_0  
numba                     0.56.4           py39hf11a4ad_0  
numexpr                   2.8.4            py39h5b0cc5e_0  
numpy                     1.21.5           py39h7a0a035_3  
numpy-base                1.21.5           py39hca35cd5_3  
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
oauthlib                  3.2.1            py39haa95532_0  
openpyxl                  3.0.10           py39h2bbff1b_0  
openssl                   1.1.1s               h2bbff1b_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
optbinning                0.17.2                   pypi_0    pypi
ortools                   9.5.2237                 pypi_0    pypi
osqp                      0.6.2.post8              pypi_0    pypi
packaging                 22.0             py39haa95532_0  
pandas                    1.5.2            py39hf11a4ad_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  3.0.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0  
pathlib                   1.0.1              pyhd3eb1b0_1  
pathspec                  0.11.0             pyhd8ed1ab_0    conda-forge
pcre                      8.45                 hd77b12b_0  
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.3.0            py39hd77b12b_2  
pip                       22.3.1           py39haa95532_0  
pkginfo                   1.8.3            py39haa95532_0  
platformdirs              2.5.2            py39haa95532_0  
pluggy                    1.0.0            py39haa95532_1  
ply                       3.11             py39haa95532_0  
powershell_shortcut       0.0.1                         3  
prettytable               3.5.0            py39haa95532_0  
prometheus_client         0.14.1           py39haa95532_0  
prompt-toolkit            3.0.36           py39haa95532_0  
protobuf                  4.21.12                  pypi_0    pypi
psutil                    5.9.0            py39h2bbff1b_0  
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulp                      2.7.0            py39hcbf5309_0    conda-forge
py-lief                   0.12.3           py39hd77b12b_0  
py-xgboost                1.7.3            py39haa95532_0  
pyarrow                   8.0.0                    pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.10.0             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.4            py39h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydocstyle                6.2.3              pyhd8ed1ab_0    conda-forge
pyflakes                  3.0.1              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.4.0            py39haa95532_0  
pylint                    2.16.1             pyhd8ed1ab_0    conda-forge
pylint-venv               2.3.0              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py39hb3671d1_1    conda-forge
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py39haa95532_0  
pyqt                      5.15.7           py39hd77b12b_0  
pyqt5-sip                 12.11.0          py39hd77b12b_0  
pyqtwebengine             5.15.7           py39hd77b12b_0  
pyquery                   1.4.3            py39haa95532_0  
pyrsistent                0.18.0           py39h196d8e1_0  
pysocks                   1.7.1            py39haa95532_0  
python                    3.9.16               h6244533_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py39haa95532_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.7.1                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.7.1              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.0              pyhd8ed1ab_0    conda-forge
python-snappy             0.6.1            py39hd77b12b_0  
python_abi                3.9                      2_cp39    conda-forge
pytoolconfig              1.2.5              pyhd8ed1ab_0    conda-forge
pytz                      2022.7           py39haa95532_0  
pywin32                   305              py39h2bbff1b_0  
pywin32-ctypes            0.2.0           py39hcbf5309_1006    conda-forge
pywinpty                  2.0.2            py39h5da7b33_0  
pyxlsb                    1.0.9                    pypi_0    pypi
pyyaml                    6.0              py39h2bbff1b_1  
pyzmq                     23.2.0           py39hd77b12b_0  
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qdldl                     0.1.5.post2              pypi_0    pypi
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.2               he8e5bd7_7  
qt-webengine              5.15.9               hb9a9bb5_5  
qtawesome                 1.2.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.0              pyha770c72_0    conda-forge
qtpy                      2.2.0            py39haa95532_0  
qtwebkit                  5.212                h3ad3cdb_4  
requests                  2.28.1           py39haa95532_0  
requests-oauthlib         1.3.0                      py_0  
rope                      1.7.0              pyhd8ed1ab_0    conda-forge
ropwr                     1.0.0                    pypi_0    pypi
rsa                       4.7.2              pyhd3eb1b0_1  
rtree                     1.0.1            py39h2eaa2aa_0  
ruamel.yaml               0.17.21          py39h2bbff1b_0  
ruamel.yaml.clib          0.2.6            py39h2bbff1b_1  
scikit-criteria           0.8.3              pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.0            py39hd77b12b_1  
scikit-learn-intelex      2021.4.0         py39haa95532_0  
scipy                     1.7.3            py39h7a0a035_2  
scs                       3.2.2                    pypi_0    pypi
seaborn                   0.12.2           py39haa95532_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                64.0.2                   pypi_0    pypi
sip                       6.6.2            py39hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
smmap                     4.0.0              pyhd3eb1b0_0  
snappy                    1.1.9                h6c2663c_0  
sniffio                   1.2.0            py39haa95532_1  
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1      py39haa95532_0  
sparse                    0.13.0             pyhd8ed1ab_0    conda-forge
sphinx                    5.0.2              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.4.2            py39hcbf5309_0    conda-forge
spyder-kernels            2.4.2           win_pyhd8ed1ab_0    conda-forge
sqlite                    3.40.1               h2bbff1b_0  
sympy                     1.11.1           py39haa95532_0  
tabulate                  0.8.10           py39haa95532_0  
tbb                       2021.6.0             h59b6b97_1  
tensorboard               2.9.0            py39haa95532_0  
tensorboard-data-server   0.6.1            py39haa95532_0  
tensorboard-plugin-wit    1.8.1            py39haa95532_0  
tensorflow                2.9.1           mkl_py39hc9ebea8_1  
tensorflow-base           2.9.1           mkl_py39h6a7f48e_1  
tensorflow-estimator      2.9.0            py39haa95532_0  
termcolor                 2.1.0            py39haa95532_0  
terminado                 0.17.1           py39haa95532_0  
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
thrift                    0.17.0           py39hd77b12b_0  
tinycss2                  1.2.1            py39haa95532_0  
tk                        8.6.12               h2bbff1b_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py39haa95532_0  
tomlkit                   0.11.6             pyha770c72_0    conda-forge
toolz                     0.12.0           py39haa95532_0  
tornado                   6.2              py39h2bbff1b_0  
tqdm                      4.64.1           py39haa95532_0  
traitlets                 5.7.1            py39haa95532_0  
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0            py39haa95532_0  
typing_extensions         4.4.0            py39haa95532_0  
tzdata                    2022g                h04d1e81_0  
ujson                     5.4.0            py39hd77b12b_0  
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
unidip                    0.1.1                    pypi_0    pypi
urllib3                   1.26.14          py39haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  2.2.1            py39hcbf5309_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39haa95532_1  
websocket-client          0.58.0           py39haa95532_4  
werkzeug                  2.2.2            py39haa95532_0  
whatthepatch              1.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py39haa95532_0  
win_inet_pton             1.1.0            py39haa95532_0  
wincertstore              0.2              py39haa95532_2  
winpty                    0.4.3                         4  
wrapt                     1.14.1           py39h2bbff1b_0  
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                3.0.3              pyhd3eb1b0_0  
xz                        5.2.10               h8cc25b3_1  
yaml                      0.2.5                he774522_0  
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
yarl                      1.8.1            py39h2bbff1b_0  
zeromq                    4.3.4                hd77b12b_0  
zipp                      3.11.0           py39haa95532_0  
zlib                      1.2.13               h8cc25b3_0  
zstandard                 0.18.0           py39h2bbff1b_0  
zstd                      1.5.2                h19a0ad4_0  

```
</details>

**Comment by ccordoba12** [comment] 2023-03-09 00:22
Hey @analyticssolvers, thanks for reporting. I'm sorry but there's very little information in your bug report to take action about it. In other words, there's no reproducible and simple code example that leads to the error, nor a clear description on how to regenerate it in other people's computers. There is only anecdotic evidence, which is simply not enough. Furthermore, I can see that you're mixing pip, conda and conda-forge packages in your environment, which you probably know is a very bad practice because all of them are binary incompatible.

So, first regenerate your environment using only conda-forge packages or pip ones, if all the packages you need are not available in conda-forge. And then, please try to come up with a description that reproduces your problem. Otherwise, I'm afraid I'll have to close this issue for lack of proper info.

**Comment by analyticssolvers** [comment] 2023-03-09 09:56
Thanks for your answer. There is no example code because the bug is produced randomly and without depending on a specific code. It does it erratically. The problem is not in the existence of a single environment. I had this problem 1.5 years ago, it disappeared and reappeared, always in the same environment.

I see how I solve it or if I change the IDE. Thank you!!

**Comment by ccordoba12** [comment] 2023-03-09 12:08
Ok, closing then because, as I said, there's not enough information for us to address this. It could be solved in Spyder 6 though, thanks to some changes in our kernel architecture.

**Closed by ccordoba12** 2023-03-09 12:08 UTC
Labels: status:Awaiting Followup

**Comment by analyticssolvers** [comment] 2023-03-09 16:17
De: Carlos Cordoba ***@***.***> 
Enviado el: jueves, 9 de marzo de 2023 9:08
Para: spyder-ide/spyder ***@***.***>
CC: analyticssolvers ***@***.***>; Mention ***@***.***>
Asunto: Re: [spyder-ide/spyder] The button to interrupt the kernel does not work (Issue #20660)

 

Ok, closing then because, as I said, there's not enough information for us to address this. It could be solved in Spyder 6 though, thanks to some changes in our kernel architecture.
