### ISSUE TITLE
Scientific Python Development Environment SPYDER

### ISSUE THREAD

**Issue by akkalbist55** [spyder-ide/spyder#7268] opened 2018-06-08 06:42 UTC
## Description

**What steps will reproduce the problem?**

1. crash on my ubuntu 18.04 lts bionic server
2. not support properly
3. not run properly

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/plugins/__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1477, in create_kernel_manager_and_kernel_client
    config=None, autorestart=True)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1691, in instance_init
    self._resolve_classes()
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1696, in _resolve_classes
    self.klass = self._resolve_string(self.klass)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1507, in _resolve_string
    return import_item(string)
  File "/usr/lib/python3/dist-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
  File "/usr/lib/python3/dist-packages/jupyter_client/session.py", line 61, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/usr/lib/python3/dist-packages/jupyter_client/jsonutil.py", line 28, in <module>
    datetime.strptime("1", "%d")
  File "/usr/lib/python3.6/_strptime.py", line 280, in <module>
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python3.6/_strptime.py", line 194, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python3.6/_strptime.py", line 72, in __init__
    self.lang = _getlang()
  File "/usr/lib/python3.6/_strptime.py", line 31, in _getlang
    return locale.getlocale(locale.LC_TIME)
  File "/usr/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: bho_NP

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.5
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2018-06-09 00:00
Thanks for reporting. This is a duplicate of issue #7051 and it'll be fixed in our next version.

**Comment by ccordoba12** [comment] 2018-06-09 00:00
In #7051 you can find a temporary solution.

**Closed by ccordoba12** 2018-06-09 00:00 UTC
