### ISSUE TITLE
close variable explorer windows

### ISSUE THREAD

**Issue by zaher88abd** [spyder-ide/spyder#5334] opened 2017-09-26 15:23 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Zaher\Anaconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 607, in setModelData
    self.get_value(index),
  File "C:\Users\Zaher\Anaconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1364, in get_value
    name = index.model().keys[index.row()]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by zaher88abd** [comment] 2017-09-26 15:25
![image](https://user-images.githubusercontent.com/11011876/30868644-9825d83c-a2b5-11e7-8ce2-ba2986082b46.png)

**Comment by ccordoba12** [comment] 2017-09-26 15:32
Closing as duplicate of issue #5322.

@zaher88abd, please continue the discussion on that issue instead of opening new ones. Thanks!

**Closed by ccordoba12** 2017-09-26 15:32 UTC
