### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by alabd14313** [spyder-ide/spyder#3924] opened 2017-01-06 10:24 UTC
Hello !

* Spyder Version: Git version (4dev)
* Python Version: 3.5
* Operating system: Arch Linux

I can't click on "File" and "Edit" menus, unless I open another menu like "Search" and backward to open that two menus.

**Comment by ccordoba12** [comment] 2017-01-06 15:09
Thanks for reporting. This is a duplicate of issue #3887.

**Closed by ccordoba12** 2017-01-06 15:09 UTC
