### ISSUE TITLE
"IndexError: list index out of range" when changing files

### ISSUE THREAD

**Issue by ChingShan86** [spyder-ide/spyder#5140] opened 2017-09-06 05:52 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\清山\AppData\Local\conda\conda\envs\opencvtest\lib\site-packages\spyder\widgets\editor.py", line 1677, in current_changed
    self.current_file_changed.emit(self.data[index].filename,
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-07 15:31
Closing as a duplicate of issue #5157.

**Closed by ccordoba12** 2017-09-07 15:31 UTC
Labels: component:Editor, type:Bug
