### ISSUE TITLE
Maximizing Spyder Ruins Orientation

### ISSUE THREAD

**Issue by tpradeep** [spyder-ide/spyder#6185] opened 2018-01-10 08:24 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Maximise spyder
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Happens in RHEL on the latest update of Spyder. Full screen works fine

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 2.7.14
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Red Hat Enterprise Linux Server release 6.8 (Santiago)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0;<6.0: 5.4.1 (OK)
cython >=0.21 : None (NOK)
jedi >=0.9.0 : 0.11.0 (OK)
nbconvert >=4.0 : 5.3.1 (OK)
numpy >=1.7 : 1.13.3 (OK)
pandas >=0.13.1 : 0.22.0 (OK)
psutil >=0.3 : 5.4.1 (OK)
pycodestyle >=2.3 : 2.3.1 (OK)
pyflakes >=0.5.0 : 1.6.0 (OK)
pygments >=2.0 : 2.2.0 (OK)
pylint >=0.25 : 1.7.4 (OK)
qtconsole >=4.2.0 : 4.3.1 (OK)
rope >=0.9.4 : 0.10.7 (OK)
sphinx >=0.6.6 : 1.6.3 (OK)
sympy >=0.7.3 : None (NOK)

![image](https://user-images.githubusercontent.com/3501439/34762395-9f7e615c-f60d-11e7-999d-95d310fe1607.png)

**Comment by ccordoba12** [comment] 2018-01-10 16:53
I don't understand what your problem is. Please explain it better.

**Comment by ccordoba12** [comment] 2018-01-10 16:53
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by tpradeep** [comment] 2018-01-11 03:07
In the attached image above, the toolbar goes below the black bar at the top and at the bottom, its all gibberish (It might look like there's another window behind it but its actually the maximized Spyder). This is how it looks when not maximised which is fine. This started happening on recent update in RHEL.

![image](https://user-images.githubusercontent.com/3501439/34806690-8b65cff0-f6aa-11e7-9d81-f2283d3cf7bd.png)

**Comment by tpradeep** [comment] 2018-01-11 03:11
This is Spyder 3.2.5 where the window is maximizing properly

![image](https://user-images.githubusercontent.com/3501439/34806794-23d8fb86-f6ab-11e7-8474-3785c457f6f0.png)

**Comment by ccordoba12** [comment] 2018-01-11 07:08
I can't reproduce this in a CentOS 6 VM. Please run

    spyder --reset

in a terminal. I'm sure that will fix your problem.

**Closed by ccordoba12** 2018-01-11 07:08 UTC
Labels: status:AwaitingFollowup

**Comment by tpradeep** [comment] 2018-01-12 04:53
The problem remains. I think there is some issue with one of the dependencies. Can you please share yours in CentOS.
