### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by nishank974** [spyder-ide/spyder#6711] opened 2018-03-10 11:02 UTC
### What steps will reproduce the problem?

1 Enter tools
2 preferences
3 syntax coloring

**Comment by csabella** [comment] 2018-03-10 12:17
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed by csabella** 2018-03-10 12:17 UTC
