### ISSUE TITLE
Panes not showing

### ISSUE THREAD

**Issue by marekprachar** [spyder-ide/spyder#17645] opened 2022-04-08 11:22 UTC
### What steps will reproduce the problem?

When going into View -> Panes nothing rools out.
I am trying to access the Terminal after installing it through iTerm.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/mprachar/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/plugins/layout/container.py", line 118, in <lambda>
    self._plugin.toggle_lock(),
  File "/Users/mprachar/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/plugins/layout/plugin.py", line 834, in toggle_lock
    plugin.dockwidget.set_title_bar()
AttributeError: 'NoneType' object has no attribute 'set_title_bar'
Traceback (most recent call last):
  File "/Users/mprachar/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/plugins/layout/container.py", line 118, in <lambda>
    self._plugin.toggle_lock(),
  File "/Users/mprachar/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/plugins/layout/plugin.py", line 829, in toggle_lock
    if plugin.dockwidget.isFloating():
AttributeError: 'NoneType' object has no attribute 'isFloating'
Traceback (most recent call last):
  File "/Users/mprachar/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/plugins/layout/container.py", line 118, in <lambda>
    self._plugin.toggle_lock(),
  File "/Users/mprachar/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/plugins/layout/plugin.py", line 834, in toggle_lock
    plugin.dockwidget.set_title_bar()
AttributeError: 'NoneType' object has no attribute 'set_title_bar'
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.9.12
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Darwin 21.3.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.5 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.13.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.0.0 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.7 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment] 2022-04-08 15:43
Hi @marekprachar thank you for the feedback! Does your env have all the packages from the conda-forge channel? Also, what version of the Terminal (I think you are refering to the [spyder-terminal plugin](https://github.com/spyder-ide/spyder-terminal), right?) are you trying to install? Be sure to install the latest version available (1.2.2) .

Let us know if something of the above helps!

**Comment by marekprachar** [comment] 2022-04-12 09:29
Hi @dalthviz, I did add the conda-forge channel. Yes, I was referring to the spyder-terminal plugin. Actually, the whole installation through Anaconda seems to be faulty/corrupted so I have downloaded the .dmg and going from there (all is working). Nevertheless, the Anaconda installation remains unusable.

**Comment by dalthviz** [comment] 2022-04-12 15:18
Glad to hear that the MacOS standalone Spyder is working for you :+1:

Regarding your Anaconda installation, maybe your base enviroment got faulty/corrupted due to the mix of conda channels (defaults vs conda-forge). If that is the case there is not much to do but reinstalling Anaconda or maybe checking if creating a new environment can help.

Just in case, the command to create a new env using only the conda-forge channel to install there Spyder and spyder-terminal using Python 3.9.12 looks something like this:

     conda create -n spyder-env -c conda-forge python=3.9.12 spyder=5.3.0 spyder-terminal=1.2.2

**Comment by dalthviz** [comment] 2022-05-12 22:28
Closing this one since seems like the issue is not related with Spyder but with the Anaconda installation

**Closed by dalthviz** 2022-05-12 22:28 UTC
Labels: component:Plugins, resolution:NotSpyder
