### ISSUE TITLE
problem after using: conda install spyder-terminal -c spyder-ide

### ISSUE THREAD

**Issue by Chuckecheese** [spyder-ide/spyder#5926] opened 2017-12-08 16:54 UTC
## Description

**What steps will reproduce the problem?**

1. I'm not shore I copied the conda install spyder-terminal -c spyder-ide line into conda.
2. 
3. 

**What is the expected output? What do you see instead?**
To be able to use a terminal inside spyder.

**Please provide any additional information below**

  File "C:\Users\E6430\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 317, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\E6430\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 330, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-08 17:07
Thanks for reporting. Not sure what you mean by 

> I'm not shore I copied the conda install spyder-terminal -c spyder-ide line into conda

In any case, this appears to be a duplicate of, e.g. #5873 , and presumably belongs on the `spyder-terminal` repo like that one did. Check out, e.g. [#123 over there](https://github.com/spyder-ide/spyder-terminal/issues/123), and this issue can be closed.

**Closed** 2017-12-08 20:48 UTC
