### ISSUE TITLE
Go to definition and help shortcut are not working

### ISSUE THREAD

**Issue by MakarevichDmitry** [spyder-ide/spyder#14987] opened 2021-03-23 10:46 UTC
### What steps will reproduce the problem?

1. Create a working directory, _C:\wdir_, for example
1. Create a module, _C:\wdir\module.py_. Module contain a simple function for printing "Hello!"
1. Create a script _C:\wdir\main.py_. Script import module and call function from module.

### Problems

1. **Go to definition** (Ctrl + G) not worked for module and function from module.
1. **Help shortcut** (Ctrl + I) not worked for module and function from module.

### Additional information
1. Autocomplete work well for function from module.

### Workaround
1. Create Project with _Projects -> New Project..._
2. **Go to definition** (Ctrl + G) and **Help shortcut** (Ctrl + I) work well for module inside Spyder project

## Versions

* Spyder version: 4.2.4 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  54.1.2 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by steff456** [comment] 2021-03-23 16:44
Hi @MakarevichDmitry,

I'm unable to reproduce this issue but can you please let me know if you used the windows installers?

**Comment by MakarevichDmitry** [comment] 2021-03-23 17:38
> Hi @MakarevichDmitry,
> 
> I'm unable to reproduce this issue but can you please let me know if you used the windows installers?

I used installer for spyder 4.2.4

**Comment by MakarevichDmitry** [comment] 2021-03-24 06:54
@steff456 I found Workaround and wrote about it in issue description

**Comment by ccordoba12** [comment] 2021-03-24 18:14
@MakarevichDmitry, glad you were able to find a workaround.

This is a duplicate of issue #14236.

**Closed by ccordoba12** 2021-03-24 18:14 UTC
Labels: status:Awaiting Followup
