### ISSUE TITLE
Plot viewer extension

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9751] opened 2019-07-04 18:04 UTC
Would using something like panel https://panel.pyviz.org/reference/index.html make the plot viewer extension a more future proof implementation?

Thoughts @spyder-ide/core-developers ?

**Comment by bcolsen** [comment] 2019-07-04 19:34
I think we will need a html viewer of some type that shows the output one would expect in a Jupyter Notebook. 

Most(all?) of the new visualization libraries are now web based and interactive. If we had an html viewer then we wouldn't need to rely on the notebook-plugin for these.

**Comment by ccordoba12** [comment] 2019-07-05 07:32
We had already discussed this @goanpeca. The Plots plugin can't be extended to accommodate plots generated with web technologies.

@bcolsen is right: we need to add a new plugin (called Viewer in RStudio) to display those kind of plugins and any other web content generated when running code.

**Comment by ccordoba12** [comment] 2019-07-05 07:34
Closing as a duplicate of issue #9423.

**Comment by ccordoba12** [comment] 2019-07-05 07:34
Last note: this is work for Spyder 5.

**Closed by ccordoba12** 2019-07-05 07:34 UTC
