### ISSUE TITLE
spyder crashed after installing pyqtgraph

### ISSUE THREAD

**Issue by Dipanjan-Barman** [spyder-ide/spyder#22136] opened 2024-05-30 03:27 UTC
### What steps will reproduce the problem?

after installing pyqtgraph, spyder started crashing frequently.
Also if I keep spyder open but idle for too long then also Spyder crashes.

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\dipan\anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dipan\anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\dipan\anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\dipan\anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.8.1 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=8.12.2,<8.13.0      :  8.12.2 (OK)
jedi >=0.17.2,<0.20.0         :  0.18.1 (OK)
jellyfish >=0.7               :  1.0.1 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.3.1 (OK)
nbconvert >=4.0               :  7.10.0 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.15.1 (OK)
pylint >=2.5.0,<3.1           :  2.16.2 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0        :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.1 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  69.5.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0 :  2.5.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.2 (OK)
numpy >=1.7                   :  1.24.3 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

**Comment by ccordoba12** [comment] 2024-05-30 18:01
Hey @Dipanjan-Barman, thanks for reporting. Please post the exact command you used to install pyqtgraph. That would help us to better understand your problem.

**Comment by Dipanjan-Barman** [comment] 2024-05-30 19:34
conda install conda-forge::pyqtgraph

**Comment by ccordoba12** [comment] 2024-05-31 01:45
Ok, that's not good because your traceback shows that you're using your base conda env instead of a different one.

The problem is that conda and conda-forge packages are binary incompatible, so you can't mix them in a single environment. And that means that you basically broke your base env and now you'll need to reinstall Anaconda.

After doing that, you need to create a separate env to work with pyqtgraph, like this:

    conda create -n pyqtgraph-env -c conda-forge python=3.10 pyqtgraph

Finally, you need to connect Spyder to that env by following these instructions in our docs:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if that works for you.

**Comment by Dipanjan-Barman** [comment] 2024-05-31 21:20
Thank you very much.  This was helpful.

**Comment by ccordoba12** [comment] 2024-05-31 21:42
Great! I'm going to close this issue for now, but you're welcome to post additional comments if you find problems related to this.

**Closed by ccordoba12** 2024-05-31 21:42 UTC
Labels: status:Awaiting Followup
