### ISSUE TITLE
IPython not Connecting to Kernel

### ISSUE THREAD

**Issue by ekazubuike** [spyder-ide/spyder#6366] opened 2018-02-02 05:18 UTC
## Description

**What steps will reproduce the problem?**

1. Start Anaconda Navigator
2. Launch Spyder
3. 

**What is the expected output? What do you see instead?**
Expected to connect to kernel and launch session, instead Spyder's IPython never connects to kernel and crashes program.

**Please provide any additional information below**

  File "/Users/Ollieboy/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 950, in update_working_directory
    shellwidget.get_cwd()
  File "/Users/Ollieboy/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/Users/Ollieboy/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 340, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/Ollieboy/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/Ollieboy/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-02-02 06:52
Thanks for reporting. This is a problem with Anaconda, not Spyder, and is a duplicate of #6335 . Please see that thread for more information and a solution.

**Closed by CAM-Gerlach** 2018-02-02 06:52 UTC
