### ISSUE TITLE
Kernel not restarting sometimes

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#13336] opened 2020-07-19 15:31 UTC
`import tensorflow` is one way to reproduce: [clip](https://puu.sh/G8JDR/1f888759cb.mp4). Further, 4.1.4 prints INFO-level messages (also shown), which didn't occur in 4.1.3, now needing manually setting `os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'` to disable.

It also doesn't _always_ reproduce; still unsure how it works exactly.

**Comment by texadactyl** [comment] 2020-07-19 20:54
I have the same symptom in the IDE.
Now, when I try it interactively with python3, I see this (Linux):
```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Illegal instruction (core dumped)
```

Tensorflow is HUGE.  My RAM is limited to 8GB.  Also, there might be something going on in the tensorflow package.  In any case, this is not a Spyder bug.  I realize that this is not the reply you hoped for.

How much RAM do you have?  What is your OS?

**Comment by texadactyl** [comment] 2020-07-19 20:56
Have a look here: https://github.com/tensorflow/tensorflow/issues

**Comment by texadactyl** [comment] 2020-07-19 20:59
Also, you could try this in case pypi is out of date:
```pip3 install git+https://github.com/tensorflow/tensorflow```

I am doing it myself.

**Comment by OverLordGoldDragon** [comment] 2020-07-19 21:31
@texadactyl It's not a TensorFlow bug; this didn't occur in Spyder 4.1.3. So it's either Spyder or its dependencies. And TensorFlow doesn't eat much RAM from simply being imported.

**Comment by texadactyl** [comment] 2020-07-19 21:33
How do you explain crashing in python3 when Spyder is not involved?

**Comment by OverLordGoldDragon** [comment] 2020-07-19 21:40
@texadactyl Bad install or dependencies, most likely. My Task Manager shows a 120MB increase in RAM usage from it - so unless your device can't afford it, `import tensorflow` alone shouldn't fail.

**Comment by texadactyl** [comment] 2020-07-19 21:42
Have you tried running python3 interactively in a terminal window.
Just do this:
```import tensorflow```

What happens?

**Comment by texadactyl** [comment] 2020-07-19 21:44
This issue looks similar to yours:  https://github.com/spyder-ide/spyder/issues/12768

**Comment by texadactyl** [comment] 2020-07-19 21:46
Also, have you tried this in a Jupyter notebook?

**Comment by OverLordGoldDragon** [comment] 2020-07-19 21:58
@texadactyl My RAM figure is from running Python in Anaconda Powershell Prompt. The linked issue has an unrelated exception (I don't have any exception). Jupyter works fine.

**Comment by texadactyl** [comment] 2020-07-19 22:02
So, ```import tensorflow``` works fine in Juypter.  Also, it works fine from a DOS command line.
You could try this:  In Anaconda, uninstall Spyder then reinstall it.

**Comment by ccordoba12** [comment] 2020-07-21 04:18
@OverLordGoldDragon, please share with us the specs of your conda environment, so I can try to reproduce this problem on my side.

For that, please run the following command from the Anaconda prompt:

    conda env export -n my-env > env.txt

replacing `my-env` with your env name. Afterwards, please upload the file called `env.txt` here, which should have been created in the same directory where you run the previous command.

**Comment by OverLordGoldDragon** [comment] 2020-07-21 15:38
@ccordoba12 Better yet, I'll give the exact steps for recreating the environment; `base` is unchanged from a fresh Anaconda install with `Anaconda3-2020.02-Windows-x86_64.exe`. To note, this _isn't_ reproduced with TensorFlow 1.14.0, but 2.2.0 isn't installed with `conda`; regardless, it was a non-issue with Spyder 4.1.3.

```
conda create --name tf2_env --clone base
conda activate tf2_env
conda install anaconda
conda update --all
pip install tensorflow==2.2.0
```
Run `spyder`, then `import tensorflow`, and try to restart kernel. My [env.yml](https://puu.sh/G9qjx/78db83e1d7.yml).

**Comment by ccordoba12** [comment] 2020-07-21 17:25
> pip install tensorflow==2.2.0

This is not correct because you're mixing pip and conda packages, and that's what's probably making the kernel crash. Please create a new environment, install tensorflow with conda and try again.

**Comment by OverLordGoldDragon** [comment] 2020-07-21 17:56
@ccordoba12 I understand it's not recommended to do so, but some necessary packages are unavailable with Anaconda and I've been using pip for a long time; currently conda supports only up to TF 2.1.0 on Windows. This same install (and much more pip's) worked fine with Spyder 4.1.3. I'm fine downgrading, but [unsure how](https://github.com/spyder-ide/spyder/issues/13329).

**Comment by ccordoba12** [comment] 2020-07-21 18:10
> I'm fine downgrading, but unsure how.

You can create a new env with

    conda create -n my-env spyder=4.1.3

**Comment by OverLordGoldDragon** [comment] 2020-08-01 18:45
It... fixed itself? Haven't seen it in past two days despite intensive use, and I haven't installed / uninstalled anything in the env. I'd give it more time to be sure, but still strange.

**Comment by OverLordGoldDragon** [comment] 2020-08-13 12:20
@ccordoba12 Nevermind, it's been back - on and off, sometimes off for hours straight, otherwise on for hours straight... no clue what the deal is. Not a bother so long as I can keep spawning more console windows though. Reproduced with TF 2.2.0 and 2.3.0.

**Comment by OverLordGoldDragon** [comment] 2020-10-24 17:09
@ccordoba12 Found a different way to reproduce: importing a compiled `.c` module (`.pyd`) and calling its method.

<details>
  <summary>C code</summary>

```C
#define PY_SSIZE_T_CLEAN
#include <Python.h>

static PyObject *
spam_system(PyObject *self, PyObject *args)
{
    const char *command;
    int sts;

    if (!PyArg_ParseTuple(args, "s", &command))
        return NULL;
    sts = system(command);
    return PyLong_FromLong(sts);
}

static PyMethodDef SpamMethods[] = {
    {"system",  spam_system, METH_VARARGS,
     "Execute a shell command."},
    {NULL, NULL, 0, NULL}        /* Sentinel */
};

static struct PyModuleDef spammodule = {
    PyModuleDef_HEAD_INIT,
    "spam",   /* name of module */
    NULL,     /* module documentation, may be NULL */
    -1,       /* size of per-interpreter state of the module,
                 or -1 if the module keeps state in global variables. */
    SpamMethods
};

PyMODINIT_FUNC
PyInit_spam(void)
{
    return PyModule_Create(&spammodule);
}
```

</details>


<details>
  <summary>setup.py</summary>

```python
from distutils.core import setup, Extension

module1 = Extension('spam',
                    sources = ['spammodule.c'])

setup (name = 'PackageName',
       version = '1.0',
       description = 'This is a demo package',
       ext_modules = [module1])
```

</details>

Run `python setup.py build`, then drag the proper `.pyd` out of `build` so that it's visible to Python, then 

```python
import spam
spam.system('h')
```

TensorFlow does import from `.pyd`, so this might explain the problem.

**Comment by loewenm** [comment] 2021-03-29 21:00
Update as of 2021/03/29

This issue still persists.  I realize that there's likely a ton of other bugs to squish and we really appreciate the work you guys are doing.

That said, the latest versions of Tensorflow/Keras have some really nice features that I (we'd) love to take advantage of... As far as I can tell, the latest conda build does not have the latest TF/Keras build and still requires pip to install.

Here's my dependencies, which is _mostly_ the latest conda build plus pip-installed TF/keras, SHAP, XGBoost and upgraded qtconsole from 5.0.2 to 5.0.3 (which isn't available in conda either).

name: python3.8
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_1
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=1.10.0=py38_0
  - anaconda-project=0.9.1=pyhd3eb1b0_1
  - anyio=2.2.0=py38haa95532_0
  - appdirs=1.4.4=py_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - asn1crypto=1.4.0=py_0
  - astroid=2.5=py38haa95532_1
  - astropy=4.2=py38h2bbff1b_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.6=pyhd3eb1b0_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=pyhd3eb1b0_2
  - backports.functools_lru_cache=1.6.1=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py38he774522_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - bitarray=1.8.0=py38h2bbff1b_1
  - bkcharts=0.2=py38_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blosc=1.21.0=h19a0ad4_0
  - bokeh=2.3.0=py38haa95532_0
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py38haa95532_0
  - cffi=1.14.5=py38hcd4344a_0
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.1.0=h33f27b4_2
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - comtypes=1.1.9=py38haa95532_1002
  - conda-package-handling=1.7.2=py38h76e460a_0
  - conda-verify=3.4.2=py_1
  - console_shortcut=0.1.1=4
  - contextlib2=0.6.0.post1=py_0
  - cryptography=3.4.6=py38h71e12ea_0
  - curl=7.71.1=h2a8f88b_1
  - cycler=0.10.0=py38_0
  - cython=0.29.22=py38hd77b12b_0
  - cytoolz=0.11.0=py38he774522_0
  - dask=2021.3.0=pyhd3eb1b0_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=py_0
  - distributed=2021.3.0=py38haa95532_0
  - docutils=0.16=py38_1
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.0.1=py_1001
  - fastcache=1.1.0=py38he774522_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - flake8=3.9.0=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=0.8.7=pyhd3eb1b0_0
  - future=0.18.2=py38_1
  - get_terminal_size=1.0.0=h38e98db_0
  - gevent=21.1.2=py38h2bbff1b_0
  - giflib=5.2.1=h62dcd97_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmpy2=2.0.8=py38h7edee0f_3
  - greenlet=1.0.0=py38hd77b12b_2
  - h5py=2.10.0=py38h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=py_0
  - html5lib=1.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - imagecodecs=2021.1.11=py38h5da4933_1
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=3.7.3=py38haa95532_1
  - importlib_metadata=3.7.3=hd3eb1b0_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.21.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - isort=5.8.0=pyhd3eb1b0_0
  - itsdangerous=1.1.0=pyhd3eb1b0_0
  - jdcal=1.4.1=py_0
  - jedi=0.17.2=py38haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.3.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38haa95532_0
  - jupyter_server=1.4.1=py38haa95532_0
  - jupyterlab=3.0.11=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.3.0=pyhd3eb1b0_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=22.3.0=py38haa95532_0
  - kiwisolver=1.3.1=py38hd77b12b_0
  - krb5=1.18.2=hc04afaa_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lcms2=2.11=hc51a39a_0
  - lerc=2.2.1=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libarchive=3.4.2=h5e25573_0
  - libcurl=7.71.1=h2a8f88b_1
  - libdeflate=1.7=h2bbff1b_5
  - libiconv=1.15=h1df5818_7
  - liblief=0.10.1=ha925a31_0
  - libllvm9=9.0.1=h21ff451_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.2.0=hd0e1b90_0
  - libxml2=2.9.10=hb89e7f3_3
  - libxslt=1.1.34=he774522_0
  - libzopfli=1.0.3=ha925a31_0
  - llvmlite=0.36.0=py38h34b8924_4
  - locket=0.2.1=py38haa95532_1
  - lxml=4.6.3=py38h9b66d53_0
  - lz4-c=1.9.3=h2bbff1b_0
  - lzo=2.10=he774522_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.3.4=py38haa95532_0
  - matplotlib-base=3.3.4=py38h49ac443_0
  - mccabe=0.6.1=py38_1
  - menuinst=1.4.16=py38he774522_1
  - mistune=0.8.4=py38he774522_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.3.0=py38h46781fe_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.2.1=py38haa95532_0
  - msgpack-python=1.0.2=py38h59b6b97_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py38_0
  - mypy_extensions=0.4.3=py38_0
  - navigator-updater=0.2.1=py38_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - nltk=3.5=py_0
  - nose=1.3.7=pyhd3eb1b0_1006
  - notebook=6.3.0=py38haa95532_0
  - numba=0.53.0=py38hf11a4ad_0
  - numexpr=2.7.3=py38hcbcaa1e_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py_0
  - openjpeg=2.3.0=h5ec785f_1
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.3=py38hf11a4ad_0
  - pandoc=2.12=haa95532_0
  - pandocfilters=1.4.3=py38haa95532_1
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - path=15.1.2=py38haa95532_0
  - path.py=12.5.0=0
  - pathlib2=2.3.5=py38haa95532_2
  - pathspec=0.7.0=py_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py38_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py38h4fa10fc_0
  - pip=21.0.1=py38haa95532_0
  - pkginfo=1.7.0=py38haa95532_0
  - pluggy=0.13.1=py38haa95532_0
  - ply=3.11=py38_0
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - psutil=5.8.0=py38h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py38ha925a31_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h2bbff1b_0
  - pycparser=2.20=py_2
  - pycurl=7.43.0.6=py38h7a1dbc1_0
  - pydocstyle=6.0.0=pyhd3eb1b0_0
  - pyerfa=1.7.2=py38h2bbff1b_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pylint=2.7.2=py38haa95532_1
  - pyls-black=0.4.6=hd3eb1b0_0
  - pyls-spyder=0.3.2=pyhd3eb1b0_0
  - pynacl=1.4.0=py38h62dcd97_1
  - pyodbc=4.0.30=py38ha925a31_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyreadline=2.1=py38_1
  - pyrsistent=0.17.3=py38he774522_0
  - pysocks=1.7.1=py38haa95532_0
  - pytables=3.6.1=py38ha5be198_0
  - pytest=6.2.2=py38haa95532_2
  - python=3.8.8=hdbf39b2_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38he774522_2
  - pywin32=227=py38he774522_1
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.4.1=py38h2bbff1b_1
  - pyzmq=20.0.0=py38hd77b12b_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - regex=2021.3.17=py38h2bbff1b_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rope=0.18.0=py_0
  - rtree=0.9.4=py38h21ff451_1
  - ruamel_yaml=0.15.100=py38h2bbff1b_0
  - scikit-image=0.17.2=py38h1e1f486_0
  - scikit-learn=0.24.1=py38hf11a4ad_0
  - scipy=1.6.2=py38h14eb087_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38haa95532_0
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.6.1=pyhd3eb1b0_1001
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py38haa95532_0
  - snappy=1.1.8=h33f27b4_0
  - sniffio=1.2.0=py38haa95532_1
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - soupsieve=2.2.1=pyhd3eb1b0_0
  - sphinx=3.5.3=pyhd3eb1b0_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.2.4=py38haa95532_0
  - spyder-kernels=1.10.2=py38haa95532_0
  - sqlalchemy=1.3.23=py38h2bbff1b_0
  - sqlite=3.35.2=h2bbff1b_0
  - statsmodels=0.12.2=py38h2bbff1b_0
  - sympy=1.7.1=py38haa95532_0
  - tbb=2020.3=h74a9793_0
  - tblib=1.7.0=py_0
  - terminado=0.9.3=py38haa95532_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.3.17=pyhd3eb1b0_1
  - tk=8.6.10=he774522_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typed-ast=1.4.2=py38h2bbff1b_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - ujson=4.0.2=py38hd77b12b_0
  - unicodecsv=0.14.1=py38_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=1.0.2=py38haa95532_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - win_unicode_console=0.5=py38_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=1.3.7=pyhd3eb1b0_0
  - xlwings=0.23.0=py38haa95532_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.3=ha925a31_3
  - zfp=0.5.5=hd77b12b_4
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.3.0=py38h2bbff1b_0
  - zstd=1.4.5=h04227a9_0
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cachetools==4.2.1
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - qtconsole==5.0.3
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - shap==0.39.0
    - slicer==0.0.7
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - xgboost==1.3.3

**Comment by loewenm** [comment] 2021-04-05 18:26
@ccordoba12 

I realize that the team is busy with the 5.0 release, which won't load due to an issue with [No module named 'qdarkstyle.colorsystem'](https://stackoverflow.com/questions/66955080/spyder-modulenotfounderror). Consequently, I have found a solution to this thread.

After testing the install of Tensorflow with Conda (instead of pip), the kernel continues to hang/not restart when requested. **The solution to this is to explicitly call _exit()_ in console. This seems to work (i.e. restart the kernel) in Spyder, using Tensorflow/Keras.**

I hope this helps someone else.

**Comment by muriloasouza** [comment] 2022-02-06 12:04
Problem still persists with Spyder 5.2.0.

@loewenm Good advice! You can also close the console tab (clicking on X) instead of typing exit() in the console window.

**Comment by impact27** [comment] 2022-09-24 09:39
Fixed by https://github.com/spyder-ide/spyder/pull/19411

If the frontend receives an error while restarting, it will abort. But if the kernel sends an error while closing, then the frontend aborts, even though the new kernel is fine.

**Closed** 2022-11-05 22:05 UTC
Labels: type:Bug, component:IPython Console
