### ISSUE TITLE
Add workspace bookmark manager

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1164] opened 2015-02-17 17:20 UTC
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2012-10-04T14:55:30Z_

For different work contexts there may be different workspaces:

* scientific work
* Web-development
* other bug squashing...

So the user may keep the workspaces separated.

It would be nice to have a workspace bookmark list that allows easily switching between these.
Sessions shall be saved on a per workshop bases.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1164_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:20
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-10-08T09:54:10Z_

What do you mean by workspaces? The variables that are currently defined in the console and shown on the variable explorer? or something like a project, i.e. an associated directory with a certain set of preferences?

If you mean the second, you probably know that Spyder has some project facilities right now, but they are not so good. We'll try to improve them for 2.3, incorporating something similar to your suggestion, i.e. adding a list of the last opened projects.

If you mean the first, we could save the current variables when a project is closed (as RStudio does). This way, next time a user opens his/her project, its session will be restored. But again this is work for 2.3 :-)

**Labels:** MS-v2.3 Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:20
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2012-10-09T12:55:25Z_

\>or something like a project, i.e. an associated directory with a certain set of >preferences?
Yes, this one.
The one you set on the top of the project explorer.

\>i.e. adding a list of the last opened projects.
Exactly!
Any project works used may be added to this list until the user presses a button to clear it.
Nice.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:20
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-10-10T09:04:05Z_

Ok, I'm glad I understood what you meant!

This will definite improve Spyder to let our users work on different large scale projects at the same time. I'm really hoping to see this soon too (hopefully in the next 6/8 months).

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:20
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T13:17:47Z_

**Summary:** Add workspace bookmark manager  
  **Labels:** -Type-Defect Type-Enh

**Comment by spyder-issues-migrator** [comment] 2015-02-17 17:20
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:51:31Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by bilderbuchi** [comment] 2015-04-24 08:00
It would also be great if not all the projects in a given workspace have to reside in a subfolder of siad workspace, e.g. when you work on two projects which are connected, but reside in different places (like on a network folder, or in a site-packages folder,...)

**Comment by ccordoba12** [comment] 2015-07-13 05:43
This is basically session management. So closing as duplicate of #1704

**Closed by ccordoba12** 2015-07-13 05:43 UTC
Labels: 1 star, duplicate, enhancement, Project-Explorer, Spyder-Gui
