### ISSUE TITLE
spyder5.0.0 update with constant missing dependency report of spyder-kernels 2.0.1

### ISSUE THREAD

**Issue by jarodgeng** [spyder-ide/spyder#15228] opened 2021-04-10 12:58 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
constant report missing dependency spyder-kernels 2.0.1 after spyder 5.0.0 update. 
even after reinstall spyder-kernels package, missing dependency issue still reports.

### What steps reproduce the problem?

1.  re-install spyder,  issue still exists
2.  upgrade all conda package, issue still exists.
3.  pip install or conda install of spyder-kernels 2.0.1 both tried, issue still exists

### What is the expected output? What do you see instead?
please provide a solution to clean this issue

### Paste Traceback/Error Below (if applicable)

```python-traceback




```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 
# packages in environment at C:\Users\jarod\miniconda3:
#
# Name                    Version                   Build  Channel
aiocometd                 0.4.5                    pypi_0    pypi
aiohttp                   3.7.3                    pypi_0    pypi
alabaster                 0.7.12             pyhd3eb1b0_0  
appdirs                   1.4.4                    pypi_0    pypi
argh                      0.26.2                   py38_0  
arrow                     0.17.0                   pypi_0    pypi
astroid                   2.5              py38haa95532_1  
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py38he774522_0  
beautifulsoup4            4.9.3                    pypi_0    pypi
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py38h2bbff1b_1003  
bs4                       0.0.1                    pypi_0    pypi
ca-certificates           2021.1.19            haa95532_1  
certifi                   2020.12.5        py38haa95532_0  
cffi                      1.14.5           py38hcd4344a_0  
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
colorama                  0.4.4              pyhd3eb1b0_0  
comtypes                  1.1.7                    pypi_0    pypi
conda                     4.10.0           py38haa95532_0  
conda-package-handling    1.7.2            py38h76e460a_0  
console_shortcut          0.1.1                         4  
cookiecutter              1.7.2              pyhd3eb1b0_0  
cryptography              3.4.7            py38h71e12ea_0  
cssselect                 1.1.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dash-core-components      1.13.0                   pypi_0    pypi
dash-html-components      1.1.1                    pypi_0    pypi
dash-renderer             1.8.3                    pypi_0    pypi
dash-table                4.11.0                   pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
distlib                   0.3.1                    pypi_0    pypi
docutils                  0.17             py38haa95532_1  
entrypoints               0.3                      py38_0  
et-xmlfile                1.0.1                    pypi_0    pypi
fake-useragent            0.1.11                   pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
finnhub-python            2.3.0                    pypi_0    pypi
flake8                    3.9.0              pyhd3eb1b0_0  
flask-compress            1.8.0                    pypi_0    pypi
freetype                  2.10.4               hd328e21_0  
funcy                     1.15                     pypi_0    pypi
future                    0.18.2                   py38_1  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha925a31_3  
idna                      2.10               pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
img2pdf                   0.4.0                    pypi_0    pypi
importlib-metadata        3.10.0           py38haa95532_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
inflection                0.5.1                    pypi_0    pypi
intel-openmp              2020.2                      254  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.22.0           py38hd4e2768_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
itsdangerous              1.1.0                    pypi_0    pypi
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.17.2           py38haa95532_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_2  
jpeg                      9b                   hb83a4c4_2  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_core              4.7.1            py38haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
keyring                   22.3.0           py38haa95532_0  
kiwisolver                1.3.1            py38hd77b12b_0  
lazy-object-proxy         1.6.0            py38h2bbff1b_0  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libtiff                   4.2.0                hd0e1b90_0  
logzero                   1.6.3                    pypi_0    pypi
lxml                      4.6.2                    pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_0  
markupsafe                1.1.1            py38he774522_0  
matplotlib                3.3.2                    pypi_0    pypi
matplotlib-base           3.3.2            py38hba9282a_0  
mccabe                    0.6.1                    py38_1  
menuinst                  1.4.16           py38he774522_1  
mistune                   0.8.4           py38he774522_1000  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38h196d8e1_0  
mkl_fft                   1.3.0            py38h46781fe_0  
mkl_random                1.1.1            py38h47e9c7a_0  
more-itertools            8.6.0                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
multitasking              0.0.9                    pypi_0    pypi
mypy_extensions           0.4.3                    py38_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
numpy                     1.19.2           py38hadc3359_0  
numpy-base                1.19.2           py38ha3acd2a_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                       py_0  
openpyxl                  3.0.5                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.1.3            py38ha925a31_0  
pandas-ta                 0.2.23b0                 pypi_0    pypi
pandoc                    2.12                 haa95532_0  
pandocfilters             1.4.3            py38haa95532_1  
paramiko                  2.7.2                      py_0  
parse                     1.18.0                   pypi_0    pypi
parso                     0.7.0                      py_0  
pathspec                  0.7.0                      py_0  
patsy                     0.5.1                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pikepdf                   1.19.3                   pypi_0    pypi
pillow                    8.2.0            py38h4fa10fc_0  
pip                       20.2.4                   pypi_0    pypi
plotly                    4.12.0                   pypi_0    pypi
plotly-orca               1.3.1                         1    plotly
pluggy                    0.13.1           py38haa95532_0  
powershell_shortcut       0.0.1                         3  
poyo                      0.5.0              pyhd3eb1b0_0  
praw                      7.1.4                    pypi_0    pypi
prawcore                  1.5.0                    pypi_0    pypi
prompt-toolkit            3.0.17             pyh06a4308_0  
psutil                    5.8.0            py38h2bbff1b_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.9.0                    pypi_0    pypi
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py38h2bbff1b_0  
pycparser                 2.20                       py_2  
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyee                      7.0.4                    pypi_0    pypi
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  

Note: you may need to restart the kernel to use updated packages.
pylint                    2.7.4            py38haa95532_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pymongo                   3.11.0                   pypi_0    pypi
pynacl                    1.4.0            py38h62dcd97_1  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyppeteer                 0.2.2                    pypi_0    pypi
pyqt                      5.9.2            py38ha925a31_4  
pyqt5                     5.12.1                   pypi_0    pypi
pyqt5-sip                 4.19.19                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyquery                   1.4.1                    pypi_0    pypi
pyrsistent                0.17.3           py38he774522_0  
pysocks                   1.7.1            py38haa95532_0  
python                    3.8.5                h5fd99cc_1  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-slugify            4.0.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pywin32                   227              py38he774522_1  
pywin32-ctypes            0.2.0                 py38_1000  
pywinauto                 0.6.8                    pypi_0    pypi
pyyaml                    5.4.1            py38h2bbff1b_1  
pyzmq                     20.0.0           py38hd77b12b_1  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.9.7            vc14h73c81de_0  
qt5-applications          5.15.2.2.1               pypi_0    pypi
qt5-tools                 5.15.2.1.0.1             pypi_0    pypi
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
quandl                    3.5.3                    pypi_0    pypi
quantstats                0.0.26                   pypi_0    pypi
regex                     2021.4.4         py38h2bbff1b_0  
requests                  2.25.1             pyhd3eb1b0_0  
requests-html             0.10.0                   pypi_0    pypi
retry                     0.9.2                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rope                      0.18.0                     py_0  
rtree                     0.9.4            py38h21ff451_1  
ruamel_yaml               0.15.100         py38h2bbff1b_0  
scipy                     1.5.3                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
setuptools                52.0.0           py38haa95532_0  
simplejson                3.17.2                   pypi_0    pypi
sip                       4.19.13          py38ha925a31_0  
six                       1.15.0           py38haa95532_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
soupsieve                 2.0.1                    pypi_0    pypi
sphinx                    3.5.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
spyder                    5.0.0            py38haa95532_0  
spyder-kernels            2.0.1            py38haa95532_0  
sqlalchemy                1.2.14                   pypi_0    pypi
sqlite                    3.35.4               h2bbff1b_0  
statsmodels               0.12.1           py38h347fdf6_0    conda-forge
sympy                     1.6.2                    pypi_0    pypi
ta-lib                    0.4.19                   pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tastyworks                4                        pypi_0    pypi
testpath                  0.4.4              pyhd3eb1b0_0  
text-unidecode            1.3                        py_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.10               he774522_0  
toml                      0.10.2             pyhd3eb1b0_0  
tornado                   6.1              py38h2bbff1b_0  
tosdb                     0.9                      pypi_0    pypi
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py38h2bbff1b_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py38hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
update-checker            0.18.0                   pypi_0    pypi
urllib3                   1.26.4             pyhd3eb1b0_0  
vc                        14.2                 h21ff451_1  
virtualenv                20.4.1                   pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2  
w3lib                     1.22.0                   pypi_0    pypi
watchdog                  1.0.2            py38haa95532_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
websocket-client          0.57.0                   pypi_0    pypi
websockets                8.1                      pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
whichcraft                0.6.1              pyhd3eb1b0_0  
win-unicode-console       0.5                      pypi_0    pypi
win_inet_pton             1.1.0            py38haa95532_0  
wincertstore              0.2                      py38_0  
wrapt                     1.12.1           py38he774522_1  
xlsxwriter                1.3.7                    pypi_0    pypi
xz                        5.2.5                h62dcd97_0  
yahoo-fin                 0.8.6                    pypi_0    pypi
yahoo-finance             1.4.0                    pypi_0    pypi
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
yarl                      1.6.3                    pypi_0    pypi
yfinance                  0.1.55                   pypi_0    pypi
zeromq                    4.3.3                ha925a31_3  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h62dcd97_4  
zstd                      1.4.5                h04227a9_0  
### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.2 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.1.3 (OK)
scipy >=0.17.0                :  1.5.0 (OK)
sympy >=0.7.3                 :  1.6.2 (OK)

```

**Comment by stonebig** [comment] 2021-04-10 13:49
it's a duplicate of https://github.com/spyder-ide/spyder/issues/15091. wait spyder-5.0.1, coming in a few days at most.

**Comment by ccordoba12** [comment] 2021-04-10 15:46
Yes, that's right. Thanks @stonebig for mentioning it.

**Closed by ccordoba12** 2021-04-10 15:46 UTC
