### ISSUE TITLE
Automatic error report - Crashing and closing every time I open it

### ISSUE THREAD

**Issue by boerseun** [spyder-ide/spyder#7095] opened 2018-05-09 21:16 UTC
See image for error message:

![screen shot 2018-05-09 at 5 14 07 pm](https://user-images.githubusercontent.com/209445/39840152-6e602b80-53ac-11e8-9970-3da04da7524f.png)

**Comment by ccordoba12** [comment] 2018-05-09 21:35
This is a duplicate of issue #6335. To fix it you need to run in Terminal.app

    conda update python python.app

**Closed by ccordoba12** 2018-05-09 21:35 UTC
