### ISSUE TITLE
I was working with a python file ICE - MEP.py that is about Formula 1 engines and when closing the app a issue reporter:

### ISSUE THREAD

**Issue by ricbenmar** [spyder-ide/spyder#17126] opened 2021-12-31 13:14 UTC
I was working with a python file ICE - MEP.py that is about Formula 1 engines and when closing the app a issue reporter: 
Spyder has encountered an internal error

_Originally posted by @ricbenmar in https://github.com/spyder-ide/spyder/issues/17123#issuecomment-1003373998_

**Comment by ccordoba12** [comment] 2022-01-01 19:10
Closing as a duplicate of issue #17123. Please don't open more issues about the same problem.

**Closed by ccordoba12** 2022-01-01 19:10 UTC
