### ISSUE TITLE
Newline auto-indentation can be wrong due to comments

### ISSUE THREAD

**Issue by DStauffman** [spyder-ide/spyder#4145] opened 2017-02-14 22:03 UTC
## Newline auto-indentation can be wrong due to comments

**What steps will reproduce the problem?**
File contents:

    def func():
        foo = 1
        bar = 2 # comment (some parentheses) more comment

1.  Hit enter, line is indented by four spaces, as expected.
2.  Hit enter again, expect 4 spaces, instead line is indented by 22 spaces (to match open parenthesis sign from right hand side comment).

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6.0
* Qt Version: 5.7.1
* PyQt Version: 5.7.1
* Operating system: Win 7, 64 bit

Installed via WinPython 64 bit 3.6.0.1Qt5

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-02-15 13:20
Thanks for reporting. This is a duplicate of issue #4096.

**Closed by ccordoba12** 2017-02-15 13:20 UTC
Labels: resolution:Duplicate
