### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by analyticssolvers** [spyder-ide/spyder#17073] opened 2021-12-22 17:20 UTC
### What steps will reproduce the problem?

Traceback (most recent call last):
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\spyder_kernels\console\start.py", line 316, in main
kernel.initialize()
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\traitlets\config\application.py", line 88, in inner
return method(app, *args, **kwargs)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 632, in initialize
self.init_sockets()
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 282, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 229, in _bind_socket
return self._try_bind_socket(s, port)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 205, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\zmq\sugar\socket.py", line 214, in bind
super().bind(addr)
File "zmq\backend\cython\socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)

Traceback (most recent call last):
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\spyder_kernels\console\start.py", line 316, in main
kernel.initialize()
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\traitlets\config\application.py", line 88, in inner
return method(app, *args, **kwargs)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 632, in initialize
self.init_sockets()
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 282, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 229, in _bind_socket
return self._try_bind_socket(s, port)
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\ipykernel\kernelapp.py", line 205, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "C:\Users\Martin\anaconda3\envs\spyder‑env\lib\site‑packages\zmq\sugar\socket.py", line 214, in bind
super().bind(addr)
File "zmq\backend\cython\socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address i

**Comment by dalthviz** [comment] 2021-12-22 17:44
Hi @analyticssolvers thank you for the feedback. This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/14739 What version of Spyder are you using? Let us know!

**Closed** 2021-12-22 18:00 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
