### ISSUE TITLE
Automatic error report I cant open any directory using open in spyder

### ISSUE THREAD

**Issue by tarunbhavnani** [spyder-ide/spyder#8247] opened 2018-11-15 09:18 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment] 2018-11-15 15:31
This is a possible duplicate of #3903, so please look there for a possible solution.

**Closed by ccordoba12** 2018-11-15 15:31 UTC
