### ISSUE TITLE
Unable to launch spyder 5.0.0

### ISSUE THREAD

**Issue by LazyTrader** [spyder-ide/spyder#15137] opened 2021-04-06 10:07 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Upon attempting to boot up spyder 5.0.0 a message "Traceback (most recent call last):
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\app\start.py", line 210, in main
from spyder.app import mainwindow
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\app\mainwindow.py", line 72, in 
from spyder.app import tour
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\app\tour.py", line 37, in 
from spyder.utils.qthelpers import add_actions, create_action
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\utils\qthelpers.py", line 34, in 
from spyder.utils.icon_manager import ima
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\utils\icon_manager.py", line 23, in 
from spyder.utils.palette import QStylePalette, SpyderPalette
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\utils\palette.py", line 12, in 
from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'
" was dispalyed.

### What steps reproduce the problem?

1. Launch Anaconda
2. Navigate to environment with spyder 5.0.0
3. Click on launch spyder

### What is the expected output? What do you see instead?

Spyder should be booted up.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\app\start.py", line 210, in main
from spyder.app import mainwindow
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\app\mainwindow.py", line 72, in 
from spyder.app import tour
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\app\tour.py", line 37, in 
from spyder.utils.qthelpers import add_actions, create_action
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\utils\qthelpers.py", line 34, in 
from spyder.utils.icon_manager import ima
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\utils\icon_manager.py", line 23, in 
from spyder.utils.palette import QStylePalette, SpyderPalette
File "C:\Users\Ron_c\anaconda3\envs\DeepLearning\lib\site-packages\spyder\utils\palette.py", line 12, in 
from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'


```

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.2
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Home 2019

### Dependencies

NA

**Comment by BOZHENG001** [comment] 2021-04-06 11:53
Same issue for me after updating the spyder to 5.0.0, let's wait for the reply and solution.

**Comment by gbugn** [comment] 2021-04-06 12:33
Same issue too.

**Comment by steveSchneider2** [comment] 2021-04-06 12:42
I had the same issue.  I uninstalled Spyder from Anaconda.  re-installed.  This time Spyder came up... albeit with this error: Mandatory:
spyder_kernels >=2.0.1, <2.1.0 : 2.0.1  (NOK) (by the way...what is the meaning of 'NOK' ??)
It has reduced functionality.  Not useable.  :(

**Comment by jeremymatt** [comment] 2021-04-06 14:09
duplicate of this issue I think:
https://github.com/spyder-ide/spyder/issues/15113

**Comment by ccordoba12** [comment] 2021-04-06 14:44
That's correct, this is a duplicate of issue #15113. Thanks for noticing it @jeremymatt. And the solution is to install 4.2.5 in the meantime.

**Closed by ccordoba12** 2021-04-06 14:44 UTC

**Comment by ccordoba12** [comment] 2021-04-06 14:45
@steveSchneider2, your problem is a duplicate of issue #15091 and it'll be fixed in our next version, to be released shortly.

**Comment by steveSchneider2** [comment] 2021-04-06 18:01
Thanks!  ... I don't know how you're rewarded for all the work you do on this...but your work is highly appreciated.  Have a great day!

**Comment by ccordoba12** [comment] 2021-04-06 19:00
Thanks! Fortunately, most of us are hired by @Quansight to work  on Spyder.

**Comment by jeremymatt** [comment] 2021-04-07 20:32
Well, it's very much appreciated!  Spyder is a fantastic IDE and you give
great customer service.  It's a wonderful feeling to be able to reach
someone if there's a problem.

Best,
-J
