### ISSUE TITLE
textdistance is very slow

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#14468] opened 2020-12-20 22:31 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder is very slow when editing complex files since #13783

### What steps reproduce the problem?

1. open https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/codeeditor.py
2. go to line https://github.com/spyder-ide/spyder/blob/a47660b44e5e446acac6e23aef72e76b7f60ece9/spyder/plugins/editor/widgets/codeeditor.py#L3551
3. type `def a(self):`

### What is the expected output? What do you see instead?
typing `def a(self):` takes almost a minute.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-12-21 00:34
This was fixed several weeks ago. Could you update your clone and try again?

**Comment by impact27** [comment] 2020-12-21 07:01
This is with the latest 4.x

**Comment by ccordoba12** [comment] 2021-01-11 02:47
Closing as a duplicate of #14570 (I forgot about this issue, sorry).

**Closed by ccordoba12** 2021-01-11 02:47 UTC
