### ISSUE TITLE
Can't open/Broken installation

### ISSUE THREAD

**Issue by orionpilot** [spyder-ide/spyder#5510] opened 2017-10-19 18:40 UTC
## Description of your problem
Can't launch Spyder. Problem started after changing firewalls.

**What steps will reproduce the problem?**

1. Starting Spyder
2. Splash screen freezes on "loading editor"
3. Crashes

**What is the expected output? What do you see instead?**
Expect Spyder to launch. Crashes instead.

**Please provide any additional information below**
The `spyder --show-console` command gives:
`Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)`
Already uninstalled and reinstalled Anaconda/Spyder. Tried disabling the firewall. Tried `conda install pyzmq`. Tried Force Reinstall Package with Anaconda. Nothing worked and the error stays the same. Also have IDLE installed and not working.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
Can't access the menu.

**Comment by Jeroendevr** [comment] 2017-10-20 09:39
Thanks for reporting the issue. Strange that the installation does not work after a firewall change since Spyder does not need an internet connection (at least I think so). 
If I understand you correctly you say that the default IDLE which comes with Python does not work? Could you post your error when launching IDLE? Possibly we are dealing with two bugs.

**Comment by ccordoba12** [comment] 2017-10-20 14:20
This is a duplicate of issue #4645

**Closed by ccordoba12** 2017-10-20 14:20 UTC

**Comment by orionpilot** [comment] 2017-10-21 00:02
I have followed the steps on the issue you mentioned (adding code to `spyder/app/start.py`). Still no improvement. I have manually added python.exe, pythonw.exe from both Anaconda3 and IDLE, and spyder.exe to the Windows Firewall allowed applications list and no change. Same error message as always, `Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)`. Are there more executables/scripts I need to add to the list?

Also here is the error message from IDLE:
![idle error](https://user-images.githubusercontent.com/32915653/31845670-575a824c-b5d1-11e7-8995-8c5b8b3e38c5.PNG)

It definitely seems to be a firewall issue but I am not sure how to fix it if adding the executables to the allowed applications list does not fix it.

**Comment by ccordoba12** [comment] 2017-10-22 21:14
@orionpilot, could you change `localhost` for `127.0.0.1` here:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/introspection/plugin_server.py#L30

and see if that solves the problem for you? Thanks!

**Comment by orionpilot** [comment] 2017-10-23 14:55
Unfortunately that did nt solve the problem. Still have the same Assertion Failed message. Weirdly enough I can edit .py files with IDLE but I can't run them. I tried opening something directly with Spyder and it failed again.

**Comment by ccordoba12** [comment] 2017-10-23 20:14
Sorry to hear that. Unfortunately, I'm out of ideas here.

**Comment by orionpilot** [comment] 2017-10-23 22:23
Thanks for trying! I had one last idea: I uninstalled IDLE and Anaconda and made sure to remove all relevant registry entries (that I could find). Then I reinstalled only Anaconda fresh. That still did not fix it. I looked at my allowed apps for Windows Firewall and Spyder/Python was not there! So the problem is definitely with the Firewall. There was no auto-detect to let it through and adding manually did not fix it either. I'm going to have to talk to Microsoft whenever I have the chance. I will update this issue whenever I get a fix. Thanks again!

**Comment by ccordoba12** [comment] 2017-10-23 22:53
Ok, thanks a lot for your efforts. Please let us know if you find a fix for this, so we can inform others users about it.

**Comment by orionpilot** [comment] 2017-10-25 02:50
So it seems I had to revert to my previous firewall (Comodo Firewall to be precise) and that fixed it. I was able to open Spyder no problem. Microsoft's help was not super helpful so I returned to Comodo. Still weird that everything worked on one of my computer's but not the other.  Hopefully nothing else breaks. Thanks again!

**Comment by csabella** [comment] 2017-10-25 21:52
The doc page for IDLE explains a little about firewalls.  Nothing to help you, except maybe an understanding.  Please see the third paragraph.
[IDLE startup failure](https://docs.python.org/3/library/idle.html#startup-failure)
