### ISSUE TITLE
intellisense not working

### ISSUE THREAD

**Issue by shashidharsunkari** [spyder-ide/spyder#5106] opened 2017-09-01 20:06 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**
Intellisense on winpython is not working

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4.dev0 
* Python Version: 3.5.3
* Qt Versions: 5.8.0, PyQt5 5.8.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-01 20:12
This is a duplicate of issue #4410 and it will be fixed in Spyder 3.2.2

**Closed by ccordoba12** 2017-09-01 20:12 UTC
