### ISSUE TITLE
Trying to see my pymc_env kernel

### ISSUE THREAD

**Issue by ThanksCheersHrng** [spyder-ide/spyder#20721] opened 2023-03-22 17:52 UTC
### What steps will reproduce the problem?

I was following the instructions for the third option on this website, but I left out the bit where I activated the environment in which Spyder is installed, because I downloaded Spyder with pip before I downloaded Mamba so I could access PyMC, and thus I presume I don't *have* an environment for Spyder. I assume this is why Spyder is so confused now; I will uninstall and reinstall with mamba. *sigh.* 

### Traceback
```python-traceback
Exception in callback AddThreadSelectorEventLoop._handle_select([6700], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([6700], [])>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\platform\asyncio.py", line 647, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\platform\asyncio.py", line 661, in _handle_event
    callback()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\platform\asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\zmq\eventloop\zmqstream.py", line 614, in _handle_events
    zmq_events = self.socket.EVENTS
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\zmq\sugar\attrsettr.py", line 56, in __getattr__
    return self._get_attr_opt(upper_key, opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\zmq\sugar\attrsettr.py", line 68, in _get_attr_opt
    return self.get(opt)
           ^^^^^^^^^^^^^
  File "zmq\backend\cython\socket.pyx", line 512, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 270, in zmq.backend.cython.socket._getsockopt
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: not a socket
```

## Versions

* Spyder version: 5.4.2  (pip)
* Python version: 3.11.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.11.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  3.0.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.3.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\user\mambaforge\envs\pymc_env:
#
# Name                    Version                   Build  Channel
arviz                     0.15.1             pyhd8ed1ab_0    conda-forge
asttokens                 2.0.5              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py311ha68e1ae_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.01.10           haa95532_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h7d9ee11_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6           py311haa95532_0  
comm                      0.1.2           py311haa95532_0  
cons                      0.4.5              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7           py311h005e61a_0    conda-forge
cryptography              39.0.2          py311h28e9c30_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1           py311hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
entrypoints               0.4             py311haa95532_0  
etuples                   0.3.8              pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd3eb1b0_0  
fastprogress              1.0.3              pyhd8ed1ab_0    conda-forge
filelock                  3.10.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.39.2          py311ha68e1ae_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
h5netcdf                  1.1.0              pyhd8ed1ab_1    conda-forge
h5py                      3.8.0           nompi_py311hfbc32a6_101    conda-forge
hdf5                      1.14.0          nompi_h918d9b7_103    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
ipykernel                 6.19.2          py311h86cfffd_0  
ipython                   8.10.0          py311haa95532_0  
jedi                      0.18.1          py311haa95532_0  
jupyter_client            7.4.9           py311haa95532_0  
jupyter_core              5.2.0           py311haa95532_0  
kiwisolver                1.4.4           py311h005e61a_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.88.1               h68f0423_1    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpython                 2.2             py311h1ea47a8_2    conda-forge
libsodium                 1.0.18               h62dcd97_0  
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.5.0                hc3b8658_5    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_6    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
logical-unification       0.4.5              pyhd8ed1ab_0    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-toolchain_win-64    2.5.0                h57928b3_0    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
matplotlib-base           3.7.1           py311h6e989c2_0    conda-forge
matplotlib-inline         0.1.6           py311haa95532_0  
minikanren                1.0.3              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
mkl-service               2.4.0           py311hb3aad17_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nest-asyncio              1.5.6           py311haa95532_0  
numpy                     1.24.2          py311h0b4df5a_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py311hf63dbb6_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0           py311hc67b2de_2    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.1.1              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_1    conda-forge
prompt-toolkit            3.0.36          py311haa95532_0  
psutil                    5.9.0           py311h2bbff1b_0  
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd3eb1b0_0  
pymc                      5.1.2                hd8ed1ab_0    conda-forge
pymc-base                 5.1.2              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytensor                  2.10.1          py311hfb14a36_0    conda-forge
pytensor-base             2.10.1          py311h12c1d0e_0    conda-forge
python                    3.11.0          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pywin32                   305             py311h2bbff1b_0  
pyzmq                     23.2.0          py311hd77b12b_0  
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1          py311h37ff6ca_0    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyder-kernels            2.4.2           py311haa95532_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tbb                       2021.8.0             h91493d7_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py311h2bbff1b_0  
traitlets                 5.7.1           py311haa95532_0  
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xarray                    2023.2.0           pyhd8ed1ab_0    conda-forge
xarray-einstats           0.5.1              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zeromq                    4.3.4                hd77b12b_0  
zstd                      1.5.2                h12be248_6    conda-forge

```
</details>

**Comment by dalthviz** [comment] 2023-03-22 21:23
Hi @ThanksCheersHrng thank you for the feedback I think this is a duplicate of https://github.com/spyder-ide/spyder/issues/20381 . It is caused due to an incompatibility with PyZMQ 25.0.0. 

Could you try to update PyZMQ to the latest release (25.0.2) or downgrade it to 24.0?

Let us know if the info above helps!

**Comment by ThanksCheersHrng** [comment] 2023-03-23 10:45
Dear Daniel,

Thanks for your suggestion- it set me on the right track. isntalling pyzmc=25.0.2 didn't help, but installing pyzmc=24.0 reduced the error notice to just "fromIccProfile: failed minimal tag size sanity" when starting up spyder from Command Prompt (Windows10), which seems functional, at least<https://github.com/spyder-ide/spyder/issues/18026>.

The issue with no communication between the pymc environment and the spyder environment (as suggested by the third option from this page<https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach>) ended up getting sorted when I added the spyder-kernels PATH to both my variable environments and PTYHONPATH manager.

Hope those solutions might help someone else- pay it forward. :)
[https://opengraph.githubassets.com/5cf19b1aed4937850a06c394faa7ebab1e812372ed9113a773fffe94b9be005f/spyder-ide/spyder/issues/18026]<https://github.com/spyder-ide/spyder/issues/18026>
something wrong when start · Issue #18026 · spyder-ide/spyder<https://github.com/spyder-ide/spyder/issues/18026>
Description What steps will reproduce the problem? I got some issue when start spyder in terminal,'fromIccProfile: failed minimal tag size sanity' after that ,every thing gos well. I just be curiou...
github.com


Cheers,
(no more Hrng)

-T
________________________________

**Comment by dalthviz** [comment] 2023-03-23 18:52
Glad to hear you where able to make everything work @ThanksCheersHrng ! I will close this then as a duplicate of https://github.com/spyder-ide/spyder/issues/20381

**Closed by dalthviz** 2023-03-23 18:52 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
