### ISSUE TITLE
Figures not showing up after upgrade to matplotlib 2.0.0

### ISSUE THREAD

**Issue by ibackus** [spyder-ide/spyder#4323] opened 2017-04-03 23:43 UTC
## Description of your problem
After upgrading to matplotlib 2.0.0, figure windows no longer show up in spyder.  I can change the backend to `inline`, and that will properly render figures in the ipython console, but if I change the backend to `Automatic` or anything else, matplotlib figures will not appear when I plot.  Matplotlib works fine when I run ipython from a normal bash terminal.

**What steps will reproduce the problem?**

1. Upgrade to matplotlib 2.0.0
2. plot something.  e.g. `plt.plot(range(10))`
3. Try drawing, showing, etc...: `plt.show(); plt.draw();`

**What is the expected output? What do you see instead?**
A figure window should raise.  Nothing shows up at all.

## Versions and main components
Spyder 3.1.3 , Python 2.7.12 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux 

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.16.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  0.7.6 (OK)

## EDIT
@ccordoba12, I've done a little more investigating.  I downgraded to matplotlib 1.5.3 via pip (pip uninstall and pip install matplotlib==1.5.3) and the problem persists.  In spyder I have matplotlib loaded by default with ipython consoles.  When I restart a kernel, I get the following error message:
```python
Traceback (most recent call last):

  File "<ipython-input-1-7719dcbc6cfe>", line 1, in <module>
    get_ipython().magic(u'matplotlib qt4')

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2158, in magic
    return self.run_line_magic(magic_name, magic_arg_s)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2079, in run_line_magic
    result = fn(*args,**kwargs)

  File "<decorator-gen-104>", line 2, in matplotlib

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/magics/pylab.py", line 100, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2954, in enable_matplotlib
    self.enable_gui(gui)

  File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 451, in enable_gui
    real_enable_gui(gui)

  File "/usr/local/lib/python2.7/dist-packages/ipykernel/eventloops.py", line 284, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")

RuntimeError: Cannot activate multiple GUI eventloops
```
Another change I recently made (which might be causing this) is I recently installed the ubuntu python-tk package via apt-get.

## EDIT 2
@ccordoba12: After some more looking, I found a solution (albeit not a desirable one).  I had an ipython startup script located at `~/.ipython/profile_default/startup/00-istartup.py`.  Not sure if its relevant, but the script imported packages which themselves import matplotlib.  I commented the code in that script, created a new startup script, and had spyder run it by going to `Tools -> Preferences -> IPython console -> Startup -> Run Code`.  

I'm really not sure why my old method stopped working.

**Comment by ccordoba12** [comment] 2017-04-04 00:17
How did you install Spyder?

**Comment by ibackus** [comment] 2017-04-04 01:47
I installed via pip on the command line using sudo pip install spyder originally and using pip to update spyder.

**Comment by h4k1m0u** [comment] 2017-04-05 17:07
I'm encountering the same issue (`matplotlib` works only with the `inline` backend, otherwise it hangs), although on different versions of `python` and `matplotlib`:
- `Python`: 3.6.0
- `Matplotlib`: 1.5.3

**Comment by callegar** [comment] 2017-04-07 21:52
Same issue here. It is not an issue with matplotlib 2.0.0, as: (i) this also happens with matplotlib 1.5.3; (ii) until not long ago it did not happen with matplotlib 2.0.0.

This is something caused by some dependency of spyder that recently got upgraded. Do not know exactly which one.

Two possible hacks to work around the problem:

1) Run your scripts from a python console rather than an ipython console in spyder.

2) Invoking plot.pause(x) in the ipython console, with x being some small integer. This lets the plots appear and allows the plots interface to work (e.g. to save a plot) for a few seconds.

**Comment by callegar** [comment] 2017-04-07 22:25
@ibackus Unclear what you mean by your solution regarding ~/.ipython/profile_default/startup/00-istartup.py I have no ipython startup file and still experience the issue. Can you clarify.

@ccordoba12 This looks like a very important bug for all those who use non-inline graphics (e.g. to be able to use the interactive tools on them, or to enable saving by pressing a button). Is there any chance to try to diagnose it in order to get a fix soon (e.g. as spyder 3.1.4?).

Apparently, a script as easy as

```
import numpy as np
from matplotlib import pyplot as plt

plt.figure()
plt.plot(np.array([1,200]),np.array([1,100]))

#plt.pause(1)
plt.show()
```
Is enough to reliably trigger the issue. Note the `pause` in the script to work it around for 1 second.

**Comment by callegar** [comment] 2017-04-07 22:28
More info: downgrading ipykernel to 4.5.0 is enough to fix the issue.

**Comment by ccordoba12** [comment] 2017-04-07 22:31
So the problem is in ipykernel, not in Spyder, which is good news.

@minrk, do you know something about this?

**Comment by callegar** [comment] 2017-04-07 22:33
ipykernel 4.5.2 is also OK. So the change breaking spyder is in the ipykernel 4.5.x -> 4.6.0 transition.

**Comment by callegar** [comment] 2017-04-07 22:40
There is an item in the changelog of ipykernel 4.6.0 that looks suspicious:

Add active event loop setting to GUI, which enables the correct response to IPython’s `is_event_loop_running_xxx`

Also... can this be related? https://github.com/ipython/ipykernel/issues/240

**Comment by ibackus** [comment] 2017-04-07 22:50
@callegar: to explain my solution...basically I had my ipython installation configured to run a script (which was  `~/.ipython/profile_default/startup/00-istartup.py`) at startup, independent of spyder.  Then, whenever a spyder ipython console was started, this script would run.  For some reason I cannot understand, moving the contents of that start-up script to a different file and then having spyder run that file (rather than having ipython run it) fixed my issue.

**Comment by callegar** [comment] 2017-04-07 23:30
@ibakus: do you still use an ipython console in spyder or a python one now? If you still use ipython, which version of ipykernel do you have? You get it with `import ipykernel` and then `ipykernel __version__`

Asking because it seems strange that the change you describe can so substantially alter things.

**Comment by ibackus** [comment] 2017-04-07 23:38
@callegar I'm still using ipython console in spyder.  The ipykernel version is 4.5.2

**Comment by callegar** [comment] 2017-04-08 00:19
@ibackus OK, thanks. If you are using ipykernel 4.5.2, then there may be 2 different bugs. One is yours, preventing figures to appear, even on ipykernel 4.5.2, with the startup file workaround you found. The other one is mine (and possibly h4k1m0u's one), caused by ipykernel 4.6.0.

Sorry for having hijacked your bug report. @ccordoba12: should I open a new report?

**Comment by ccordoba12** [comment] 2017-04-10 19:12
@callegar's issue should be fixed in ipykernel **4.6.1**.

@ibackus, I can't reproduce your problem. You probably have your backend set in your `matplotlibrc` file, which takes precedence over Spyder preferences. This part of your message

> Another change I recently made (which might be causing this) is I recently installed the ubuntu python-tk package via apt-get.

seems to confirm it. You (most probably) have an old `matplotlibrc` somewhere, that sets `Tk` as the default backend.

So you just need to find it and remove that option.

**Closed by ccordoba12** 2017-04-10 19:12 UTC

**Comment by ibackus** [comment] 2017-04-10 20:23
@ccordoba12: I've figured it out, but I still think there is an issue here.

I did not have a user defined `matplotlibrc` anywhere.  What I believe happened is that I updated to matplotlib 2.0.0 which changed the matplotlib default backend to TkAgg.  This required me to install tk.  For some reason Tk doesn't play well here with spyder.  I was able to fix my issues by creating a user defined `matplotlibrc` file and setting the backend to Qt4Agg.  From a user perspective, upgrading matplotlib can break spyder, and requires a roundabout fix.

**Comment by ccordoba12** [comment] 2017-04-10 23:36
> What I believe happened is that I updated to matplotlib 2.0.0 which changed the matplotlib default backend to TkAgg.

@tacaswell, is this possible?

**Comment by ibackus** [comment] 2017-04-10 23:49
All I know is that after upgrading to matplotlib 2.0.0, matlab crashed with some message (that I've lost) which indicated that tk was missing.  I'd never had this issue before matplotlib 2.0.0.

**Comment by ccordoba12** [comment] 2017-04-10 23:51
@ibackus, it is very strange. I just want some confirmation from @tacaswell to see if something changed in MPL 2.0, because (again) I can't reproduce it locally.

**Comment by tacaswell** [comment] 2017-04-13 15:12
The default backend is set at build time (by looking at what is available) with some order of preference (iirc) so this is very dependent on how things were installed.

 - pip from source -> looks at what you have installed and picks on
 - pip from wheels (on linux) -> tk or Agg
 - pip from wheels (on mac / win) -> do not know off the top of my head
 - anaconda (defaults) -> pyqt5 (hard coded in the recipe)
 - anaconda (conda-forge) -> pyqt4 (hard-coded in the recipe)
 - OS level package manager -> what ever they fell like doing ;) 

spyder should probably aggressively set the Matplotlib backend to match the qt version it is running

```python
try:
    import matplotlib
except ImportError:
    pass
else:
    if spyder_is_qt4:
        matplotlib.use('qt4agg')
   elif spyder_is_qt5:
       matplotlib.use('qt5agg')
   else:
       raise RuntimeError('unsupported version of qt')
```

as early as possible in it's start up.

**Comment by ccordoba12** [comment] 2017-04-13 16:19
Thanks a lot for the detailed answer Thomas!

> pip from wheels (on linux) -> tk or Agg

I didn't know that. This seems the cause of the problem @ibackus is experiencing here.

> spyder should probably aggressively set the Matplotlib backend to match the qt version it is running

Thanks, we'll try to do that in our next version.

**Comment by ccordoba12** [comment] 2017-04-13 17:08
@ibackus, you also said:

> I had an ipython startup script located at ~/.ipython/profile_default/startup/00-istartup.py. Not sure if its relevant, but the script imported packages which themselves import matplotlib.

I think this was really the problem. If you imported `matplotlib.pyplot` or `matplotlib.pylab` in that script, then that was setting automatically your backend to `TkAgg`.

So what you did, i.e.

> I commented the code in that script, created a new startup script, and had spyder run it by going to Tools -> Preferences -> IPython console -> Startup -> Run Code

was the right solution because Spyder first sets your backend and then runs your startup code.
