### ISSUE TITLE
unicode error  

### ISSUE THREAD

**Issue by manojbuddha** [spyder-ide/spyder#12289] opened 2020-04-12 12:03 UTC
### What steps will reproduce the problem?

while running the code in spyder i get the below error, the same code is running without any error in jupyter and anaconda prompt
"runfile('E:/Python/Corona_tracker.py', wdir='E:/Python')
  File "E:\Python\Corona_tracker.py", line 8
    """
      ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 40-41: truncated \UXXXXXXXX escape"

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment] 2020-04-12 12:26
@manojbuddha what code? Please provide a reproducible example (it does not need to be you complete code) but we do need something to run on our side and check what is going on.

Thanks

**Comment by manojbuddha** [comment] 2020-04-15 02:36
Hi goanpeca,

Please find below the code I was trying to run, it was running fine without any errors in jupyter notebook.

# -*- coding: utf-8 -*-
"""
Created on Sun Mar 22 23:30:44 2020

C:\Users\Manoj\Documents

@author: Manoj
"""
import requests_html
from requests_html import HTMLSession
from tkinter import *
from tkinter.ttk import *
import tkinter as tk
import os
import getpass
import datetime
from time import sleep
import matplotlib.pyplot as plt

def plotting():
    
     logpath=r"C:\Users\Manoj\documents\clog.txt"
     count=[]
     timestamp=[]
     reader=open(logpath,"r")
     for ele in reader:
            ele=ele.split()
            count.append(ele[0].replace(',',""))
            timestamp.append(datetime.datetime.fromtimestamp(float(ele[1])))
     reader.close()
     plt.plot(timestamp,count)
     plt.gcf().autofmt_xdate()
     plt.show()


        


def logger(confirmed):
    plotting()        
    date=datetime.datetime.now().timestamp()
    #date=date.strftime("%d-%m-%y %H-%M-%S")
    logpath="C:\\Users\\"+str(user_name)+"\\documents\\clog.txt"
    data=[]
    log_reader=open(logpath,"r")
    for ele in log_reader:
         data.append(str(ele).strip())
    log_reader.close()
    data.append(confirmed+"  "+str(date))
    log_writer=open(logpath,"w")
    for ele in data:
        log_writer.write(str(ele))
        log_writer.write("\n")
    
    log_writer.close()



def web_scrapper():
      
    status.configure(text="Please wait, loading" )
      
    progress['value'] = 0
    window.update_idletasks() 
        
    progress['value'] = 10
    window.update_idletasks() 
        
    progress['value'] = 40
    window.update_idletasks() 
    
    session=HTMLSession()
    r=session.get("https://www.worldometers.info/coronavirus/")
    progress['value'] = 80
    window.update_idletasks()   
    r.html.links
    confirmed=r.html.find('.maincounter-number',first=True)
    confirmed=confirmed.text
    l3=confirmed
    l4="Not Available"
    title2=l3.center(text_width," ")+l4.center(text_width," ")
    values.configure(text=title2)
    status.configure(text="")
    logger(confirmed)
    
    progress['value'] = 100
    window.update_idletasks() 
    sleep(1)
        
    progress['value'] = 0
    window.update_idletasks() 

user_name=getpass.getuser()
logpath="C:\\Users\\"+str(user_name)+"\\documents\\clog.txt"

if not os.path.exists(logpath):
   
    write=open(logpath,"w")
    write.close()
    print("log file created")

window=Tk()
window.title("Covid-Tracker")
text_width=20
l1="Global Cases"
l2="India Cases"
l3="--"
l4="--"
title1=l1.center(text_width," ")+l2.center(text_width," ")
title2=l3.center(text_width," ")+l4.center(text_width," ")
title=Label(window, text=title1)
values=Label(window, text=title2)
status=Label(window,text="Status not available")
progress = Progressbar(window, orient = HORIZONTAL,length = 100, mode = 'determinate') 
refresh_button=Button(window,text="Refresh",command=web_scrapper)
plot_button=Button(window,text="Plot",command=plotting)

title.pack(padx=5,pady=5)
values.pack(padx=5,pady=5)
status.pack(anchor=CENTER)
refresh_button.pack(side='left',anchor=CENTER,padx=5,pady=5)
plot_button.pack(side='right',anchor=CENTER,padx=5,pady=5)
progress.pack(anchor=CENTER,padx=5,pady=5)

window.mainloop()

**Comment by ccordoba12** [comment] 2020-04-22 17:41
Closing because this seems a bug in your code and not in Spyder itself, sorry.

**Closed by ccordoba12** 2020-04-22 17:41 UTC
Labels: status:Awaiting Followup

**Comment by manojbuddha** [comment] 2020-07-16 14:13
> Closing because this seems a bug in your code and not in Spyder itself, sorry.

thanks, issue fixed after changing the spyder terminal to the source file directory.
