### ISSUE TITLE
Spyder fails to launch from clean Anaconda install (Python 2.7 env)

### ISSUE THREAD

**Issue by rblue2** [spyder-ide/spyder#14637] opened 2021-01-23 00:08 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [NA] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder fails to launch from Anaconda Navigator, terminal or Start menu. This is a clean environment (Python 2.7) on a clean Anaconda installation: I am trying to set up a 2.7 environment to work with 3rd party code. Launching Spyder for the base (Python 3.8) env seems to work. 

Suggested troubleshooting steps (reset spyder settings, restart computer, reinstall anaconda, update spyder, etc.) don't help.

### What steps reproduce the problem?

1. Install latest Anaconda from anaconda.org (64-bit installer)
2. Launch Anaconda Navigator, create new Python 2.7 environment.
3. Install Spyder via Navigator GUI.
4. Attempt to launch Spyder via {Navigator | Start menu | Anaconda prompt terminal}

### What is the expected output? What do you see instead?
Expect Spyder GUI to launch. Instead:
Navigator 'Application launch error' message window appears with traceback. On subsequent launch attempts, a Spyder error window appears instead of Anaconda Navigator window with standard troubleshooting suggestions.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\spyder\app\mainwindow.py", line 3557, in run_spyder
main = MainWindow(options)
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\spyder\app\mainwindow.py", line 426, in __init__
from spyder.preferences.runconfig import RunConfigPage
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\spyder\preferences\runconfig.py", line 482, in 
class RunConfigPage(GeneralConfigPage):
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\spyder\preferences\runconfig.py", line 487, in RunConfigPage
ICON = ima.icon('run')
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\spyder\utils\icon_manager.py", line 394, in icon
directory=_resource['directory'])
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\qtawesome\__init__.py", line 178, in load_font
return _instance().load_font(prefix, ttf_filename, charmap_filename, directory)
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\qtawesome\__init__.py", line 54, in _instance
'materialdesignicons-webfont-charmap.json')
File "C:\Users\ryan.blumenstein\.conda\envs\ixgen\lib\site-packages\qtawesome\iconic_font.py", line 206, in __init__
super().__init__()
TypeError: super() takes at least 1 argument (0 given)

```

## Versions

* Anaconda Navigator 1.10.0
* Spyder version: 4.0.1
* Python version: 2.7.18
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Windows 10 Pro, 10.0.18362

### Dependencies

Had to extract from conda (Spyder GUI won't open). Think I did this correctly, not positive.
```
  - atomicwrites
  - chardet >=2.0.0
  - cloudpickle
  - diff-match-patch
  - intervaltree
  - jedi 0.14.1.*
  - keyring
  - nbconvert
  - numpydoc
  - paramiko
  - pexpect
  - pickleshare
  - psutil >=5.2
  - pygments >=2.0
  - pylint
  - pyqt >=5.6,<5.13
  - python >=2.7,<2.8.0a0
  - python-language-server >=0.31.2,<0.32.0
  - pyzmq
  - qdarkstyle >=2.7
  - qtawesome >=0.5.7
  - qtconsole >=4.6.0
  - qtpy >=1.5.0
  - rtree
  - sphinx
  - spyder-kernels >=1.8.1,<1.9.0
  - watchdog
  - parso 0.5.2.*```

**Comment by juanis2112** [comment] 2021-01-26 05:08
Hi @rblue2 thanks for reporting this. This is a duplicate of #13962 which was fixed in our 4.1.6 release. Please upgrade to this version and let us know if your issue is fixed.

**Comment by rblue2** [comment] 2021-01-26 18:28
Hi @juanis2112 , thanks very much for the response -- sorry I missed the duplicate ticket.
I've tried installing spyder 4.1.6 via pip according to #13962. Installation appears to complete with errors:

    ERROR: python-language-server 0.36.2 has requirement jedi<0.18.0,>=0.17.2, but you'll have jedi 0.17.1 which is incompatible.
    ERROR: spyder-kernels 1.9.4 has requirement ipykernel>=5.1.3; python_version > "2", but you'll have ipykernel 4.10.1 which is incompatible.

Spyder launches (from command prompt) and GUI opens, but it appears to crash out almost immediately (before opening files, executing commands, etc.). I'm assuming this is related to the dependency conflicts? Is there a way to resolve them?

**Comment by juanis2112** [comment] 2021-01-28 03:43
Hi @rblue2 I think if you mixed pip and conda packages, you might have broken your anaconda installation. I suggest uninstalling and reinstalling it again to avoid problems in your environment. 

After this, to get spyder 4.1.6 working with pip it is better to create a new environment with the packages necessary. In your anaconda prompt please run the following commands:
```
conda create -n py27 python=2.7
conda activate py27
conda install pyqt
pip install spyder
pip install python-language-server==0.36.1
pip install jedi==0.17.1
```

**Comment by rblue2** [comment] 2021-01-28 17:09
No luck -- I uninstalled Anaconda (and deleted any related environment/config files, etc. I found -- but I didn't dig through AppData, etc. closely). Then reinstalled, ran the commands you provided, and I'm seeing the same behavior: Spyder launches then almost immediately (within ~10 seconds) quits/crashes without any user input or apparent error messages.

**Comment by ccordoba12** [comment] 2021-01-28 17:50
@rblue2, perhaps it's an issue with Qt/PyQt. Please run these commands instead:

    conda create -n py27-new python=2.7
    conda install spyder

That should work, but it'll install a very old and buggy Spyder version.

**Comment by rblue2** [comment] 2021-01-28 22:58
Thanks for the support. This installs Spyder 4.0.1?

Trying to launch gives following traceback:

```
Traceback (most recent call last):
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\spyder\app\mainwindow.py", line 3557, in run_spyder
    main = MainWindow(options)
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\spyder\app\mainwindow.py", line 426, in __init__
    from spyder.preferences.runconfig import RunConfigPage
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\spyder\preferences\runconfig.py", line 482, in <module>
    class RunConfigPage(GeneralConfigPage):
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\spyder\preferences\runconfig.py", line 487, in RunConfigPage
    ICON = ima.icon('run')
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\spyder\utils\icon_manager.py", line 394, in icon
    directory=_resource['directory'])
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\qtawesome\__init__.py", line 178, in load_font
    return _instance().load_font(prefix, ttf_filename, charmap_filename, directory)
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\qtawesome\__init__.py", line 54, in _instance
    'materialdesignicons-webfont-charmap.json')
  File "C:\Users\ryan.blumenstein\Anaconda3\envs\py27-new\lib\site-packages\qtawesome\iconic_font.py", line 206, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by ccordoba12** [comment] 2021-01-29 02:29
Ok, now please run the following commands

    conda activate py27-new
    conda install qtawesome=0.7.2

That should fix your problem.

**Comment by ccordoba12** [comment] 2021-01-29 02:30
> This installs Spyder 4.0.1?

Yeah, that installs that version.

**Comment by rblue2** [comment] 2021-02-01 16:41
With qtawesome=0.7.2, I'm seeing similar behavior as before: Spyder launches then almost immediately (within ~10 seconds) quits/crashes without any user input or apparent error messages.

**Comment by ccordoba12** [comment] 2021-02-01 21:55
That's too bad to hear @rblue2, but unfortunately we stopped supporting Python 2 in last November.

If you need this to run Python 2 code in Spyder, please create a conda env with Python 2 and the packages you need to use on it (but not Spyder), and then follow the instructions in [our FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) to learn how to connect that env to a Python 3 Spyder version.

**Closed by ccordoba12** 2021-02-01 21:55 UTC
Labels: status:Awaiting Followup

**Comment by rblue2** [comment] 2021-02-01 21:57
Understood, I appreciate the support.

**Comment by ccordoba12** [comment] 2021-02-01 22:09
No problem, hopefully you'll find a way to continue using Spyder.
