### ISSUE TITLE
I upgraded to the latest version but it says something went wrong

### ISSUE THREAD

**Issue by yanyudong1993** [spyder-ide/spyder#11844] opened 2020-03-18 04:48 UTC
I upgraded to the latest version but it says something went wrong with iPython.
![微信图片_20200318124751](https://user-images.githubusercontent.com/62321854/76926181-b2e88000-6916-11ea-9ae4-87ad55ae6591.png)

**Comment by nevzat** [comment] 2020-03-18 06:46
I have the same issue after upgrading to 4.1.0 on Windows. I even factory reset settings but it didn't solve the issue

**Comment by MaartenBransen** [comment] 2020-03-18 07:58
I am working on Windows with Anaconda and I have the same problem, both after doing:

`conda update spyder`
and
`conda remove spyder
conda install spyder=4.1.0`

removing and installing 4.0.1 resolved the issue

**Comment by Tribute27** [comment] 2020-03-18 08:44
@MaartenBransen try it but already not works

any suggestion?

**Comment by sylm21** [comment] 2020-03-18 08:53
Try this and install the old version
conda remove spyder
conda insatll spyder=4.0.1
It's ok for me

**Comment by dcasasor-purdue** [comment] 2020-03-18 13:51
So the solution is going back to 4.0.1. Any news on solving this problem? I want to be able to upgrade to the 4.1.0 version. Btw, this is related with issue #11848

**Comment by ccordoba12** [comment] 2020-03-18 15:19
Duplicate of #11819

**Comment by ccordoba12** [comment] 2020-03-18 15:19
This will be fixed in 4.1.1, to be released later today or tomorrow.

**Closed by ccordoba12** 2020-03-18 15:19 UTC
