### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by mfilipav** [spyder-ide/spyder#6620] opened 2018-03-06 20:58 UTC
Internal error traceback: changed font to Monaco, clicked "apply". Next, changed theme to Solarized Dark, and clicked OK --> and then I got this error

**Comment by CAM-Gerlach** [comment] 2018-03-06 22:04
Sorry, but you didn't provide an error report. However, this is almost certainly a duplicate of issue #6519, which is already fixed and will be released with the next Spyder version (3.2.8).  Therefore, this issue will be closed.

**Closed by CAM-Gerlach** 2018-03-06 22:04 UTC
