### ISSUE TITLE
Why are tab bars aligned to center adjusted?

### ISSUE THREAD

**Issue by BJWiley233** [spyder-ide/spyder#20507] opened 2023-02-09 11:40 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.2
* Python version: 3.9.14
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Darwin 21.6.0

### Dependencies

```
PASTE DEPENDENCIES HERE
```

Not sure if this is new in Spyder but the file tabs in the tab bar are "center aligned".  They used to be "left aligned".  Not a huge quirk but no other IDEs have their tabs center aligned so I would like to revert this somehow in the Spyder settings.  The same thing also occurs for Console tabs.

Spyder version: 5.4.2
![image](https://user-images.githubusercontent.com/26236052/217802550-9e338687-4446-46dd-8d14-5597ca871b0e.png)

Last used Spyder version: 5.3.1
![image](https://user-images.githubusercontent.com/26236052/217802925-2e5eb942-f962-46e6-b52e-f6f73c68ed4d.png)

**Comment by ccordoba12** [comment] 2023-02-09 15:09
Hey @BJWiley233, thanks for reporting. This was reported before on issue #20504 and we'll try to fix it in our next version (5.4.3), to be released next month.

**Comment by ccordoba12** [comment] 2023-02-09 15:09
I'm going to close your issue as a duplicate of that one.

**Closed by ccordoba12** 2023-02-09 15:09 UTC

**Comment by BJWiley233** [comment] 2023-02-09 15:32
Ah ok they called it "pane tabs" instead of "tab bar" so couldn't find it in my search 😄.  Thanks.
