### ISSUE TITLE
[Feature Request] Collapse cells

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11199] opened 2019-12-30 22:24 UTC
Would be very useful, as `__main__` code is largely organized by cells, not functions or classes.

**Comment by ccordoba12** [comment] 2019-12-31 03:40
Duplicate of #8090

**Comment by ccordoba12** [comment] 2019-12-31 03:40
There it was suggested to collapse cells too.

**Closed by ccordoba12** 2019-12-31 03:40 UTC
