### ISSUE TITLE
dismissing the updates notification dialog ( and disabling automatic check for updates)

### ISSUE THREAD

**Issue by ctigaret** [spyder-ide/spyder#22580] opened 2024-09-26 12:56 UTC
### What steps will reproduce the problem?

start spyder; "updates available " notification dialog appears; turn off automatic check for updates; close the dialog

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 230, in _process_check_update
    self.start_update()
  File "/usr/lib/python3.11/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 314, in start_update
    self, self.latest_release, self.update_worker.channel
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WorkerUpdate' object has no attribute 'channel'
```

## Versions

* Spyder version: 6.0.0  (openSUSE RPM)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.15
* PyQt5 version: 5.15.10
* Operating System: Linux-6.10.11-1-default-x86_64-with-glibc2.40

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.15.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.1.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.6 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.1 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  72.1.0 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
xdg >=0.26                       :  0.28 (OK)
yarl >=1.9.4                     :  1.9.4 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.0 (OK)
numpy >=1.7                      :  2.1.1 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment] 2024-09-26 15:53
Hey @ctigaret, thanks for reporting. This is a duplicate of issue #22572 and we'll fix it in our 6.0.2 version, to be released in a couple of weeks.

**Closed by ccordoba12** 2024-09-26 15:53 UTC
