### ISSUE TITLE
Open project error

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#16243] opened 2021-08-19 07:47 UTC
My version is 5.1.1. The Open project error doesn't seem to have been solved yet.

**Comment by Vincent0706** [comment] 2021-08-19 07:48
I have reporter the error in #16242.

**Comment by ccordoba12** [comment] 2021-08-21 01:20
Closing as a duplicate of issue #16242 (see my answers there).

**Closed by ccordoba12** 2021-08-21 01:20 UTC
