### ISSUE TITLE
Spyder has encountered an internal problem- comms.py file

### ISSUE THREAD

**Issue by zahramazhar9** [spyder-ide/spyder#11797] opened 2020-03-15 02:48 UTC
### What steps will reproduce the problem?

initializing the kernel gives this pop up message:

Spyder has encountered an internal problem

### Traceback
```python-traceback
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 1caac48e666611ea8316f218981c8b86
Traceback (most recent call last):
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 1caac48e666611ea8316f218981c8b86
Traceback (most recent call last):
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/Users/zahramazhar/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.0
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.3.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.8.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  None (NOK)
sphinx >=0.6.6               :  2.2.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.2 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-15 17:16
Duplicate of #11798

**Closed by ccordoba12** 2020-03-15 17:16 UTC
