### ISSUE TITLE
Installation Anaconda 3 x64 on Ubuntu 16.04: Weird Window Style

### ISSUE THREAD

**Issue by ckaldemeyer** [spyder-ide/spyder#3671] opened 2016-11-10 12:19 UTC
## Description of your problem

**What steps will reproduce the problem?**

I have installed Spyder via Anaconda (Python3/64 Bit) as descibed in the manual on my Ubuntu 16.04 machine.

But when I start Spyder via:

    cord@cord-Laptop:~$ .anaconda3/bin/spyder

It looks weird as you can see here: http://pasteboard.co/pwxeSsurj.png

So I thought this comes from files, caches, etc. from remaining installations and deleted them e.g. everything spyder-related that's not within the anaconda3-folder.

But still the same result..

Additionally, I created a new user account on the system, signed on and did a fresh install of Anaconda. But it still leads to the same result. So to me it looks as this is an error/bug with spyder on Ubuntu 16.04.

**What is the expected output? What do you see instead?**

A "normal" looking Spyder

**Please provide any additional information below**

## Versions and main components

* Spyder Version: Latest
* Python Version: 3
* Operating system: Ubuntu 16.04 64-Bit (Unity)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ckaldemeyer** [comment] 2016-11-10 12:21
Already the starting screen is much bigger than it was in all my previous installations on different machines. This seems to me somehow related to the screen resolution/window manager..

**Comment by ckaldemeyer** [comment] 2016-11-10 12:23
And resetting the window layout also doesn't work. Only in the beginning, the starting screen is smaller (as expected) and then it gets much too big as described

**Comment by ckaldemeyer** [comment] 2016-11-10 12:25
And also the panes look weird: http://pasteboard.co/pxtqSPO5t.png

Is this somehow QT related?

**Comment by ckaldemeyer** [comment] 2016-11-10 12:44
Also a manual setting of the resolution does not show effect (bzw. the resolution was something like 900*800) before:

       ->close spyder
       cord@cord-Laptop:~$ vim /home/cord/.config/spyder-py3/spyder.ini
       -> window/size = (1920, 1080)
       -> save results
       -> restart spyder (cord@cord-Laptop:~$ .anaconda3/bin/spyder)
       -> same results

**Comment by ccordoba12** [comment] 2016-11-10 15:49
Yes, this is a Qt problem, and it's a duplicate of issue #3489.

It'll be fixed in Spyder 3.0.2, to be released this weekend. Thanks for your patience :-)

**Closed by ccordoba12** 2016-11-10 15:49 UTC

**Comment by ckaldemeyer** [comment] 2016-11-10 16:23
Thanks for your answer! I'll wait then ;)

**Comment by ckaldemeyer** [comment] 2016-11-15 09:25
Is there any progress on this? I couldn't find anything on PyPi: https://libraries.io/pypi/spyder

:-)

**Comment by ccordoba12** [comment] 2016-11-15 14:19
We're waiting for @goanpeca to update the French translations. Everything else is ready now :-)

**Comment by ckaldemeyer** [comment] 2016-11-21 07:39
I have seen that you have released on PiPy yesterday. Will there also be an update of the conda package?

**Comment by ccordoba12** [comment] 2016-11-21 14:47
Yes, that usually takes a couple of days :-)
