### ISSUE TITLE
Spyder editor does not open previously opened files in a project

### ISSUE THREAD

**Issue by jhoutword** [spyder-ide/spyder#8375] opened 2018-12-06 06:02 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder editor does not open previously opened files in a project.

At any time, I may switch between projects. I would close project A, and open project B. But if I want to return to work on project A, I find that the editor does not automatically open all the files that was opened before I closed project A the last time.

Only when I close Spyder entirely, then will the project state be saved.

### What steps reproduce the problem?

1. Install anaconda
2. Open spyder
3. Create a project with files in them. 
4. Open the project, open some saved file Z in editor. Close all other files.
5. Close project.
6. Open project again.
7. Check if file Z is opened in editor.

### What is the expected output? What do you see instead?
File Z should be opened. It is not opened.

* Spyder version: 3.3.1
* Python version: 3.5.4 64 bits
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Windows 8.1

**Comment by jnsebgosselin** [comment] 2018-12-12 15:02
Thanks for reporting @jhoutword. I think I can reproduce this in master also. I will investigate and see if I can fix this quickly.

**Comment by jnsebgosselin** [comment] 2018-12-12 15:03
@ccordoba12 Milestone?

**Comment by jnsebgosselin** [comment] 2018-12-12 22:03
I think this was introduced here: https://github.com/spyder-ide/spyder/commit/3d7a94278f7bb5d58d35b9ff0e33e00519dfc594#diff-271b198d60769127e85929e3fcd8f61a, so in version 3.2.7.

The problem is that calling `self.set_project_filenames(self.editor.get_open_filenames())` at the end of the method `close_project`  is too late because the files that were opened for the project that is being closed are already closed due to the slots called by `self.sig_project_closed.emit(path)`.

To fix that, I think that we need to call `self.set_project_filenames(self.editor.get_open_filenames())`  before we emit `sig_project_closed`. So the method `close_project` should look something like this in master instead:

```python
def close_project(self):
    """
    Close current project and return to a window without an active
    project
    """
    if self.current_active_project:
        self.switch_to_plugin()
        path = self.current_active_project.root_path
        if self.main.editor is not None:
            self.set_project_filenames(
                self.main.editor.get_open_filenames())
        self.current_active_project = None
        self.set_option('current_project_path', None)
        self.setup_menu_actions()

        self.sig_project_closed.emit(path)
        self.sig_pythonpath_changed.emit()

        if self.dockwidget is not None:
            self.set_option('visible_if_project_open',
                            self.dockwidget.isVisible())
            self.dockwidget.close()

        self.explorer.clear()
        self.restart_consoles()
```

@ccordoba12 What do you think? Was there any reason to move `self.set_project_filenames(self.editor.get_open_filenames())` at the end of the `close_project` method when you did your changes?

**Comment by jnsebgosselin** [comment] 2018-12-12 22:12
I've updated the reason why the changes are causing the bug in my post above, but the proposed fix remain the same.

**Comment by jnsebgosselin** [comment] 2018-12-12 22:19
Note that this bug does not occur when **switching** projects, only when closing, then re-opening a given project.

**Comment by ccordoba12** [comment] 2018-12-13 03:19
> Was there any reason to move self.set_project_filenames(self.editor.get_open_filenames()) at the end of the close_project method when you did your changes?

I was trying to make the plugin easier to test (at least that's what I recall from the commit message). But iterated a lot over that during the last months, so the things I changed in 3.2.7 could be reverted (just guessing).

**Comment by jnsebgosselin** [comment] 2018-12-13 05:10
That is what I thought, I just wanted to be sure. I'll submit a PR against Master to fix this and maybe add a regression test to cover this.

**Closed** 2018-12-15 15:39 UTC
Labels: component:Projects, in progress, severity:4-Low, type:Bug

**Comment by jupihes** [comment] 2021-02-17 14:56
In Windows, look to find .ini file like "C:\Users\username\.spyder-py3\spyder.ini"/
In that file, you can find following 2 lists 
"recent_files"
"filenames"
