### ISSUE TITLE
ubuntu spyder when I run code 2nd time TypeError: Type already registered for SparseTensorValue

### ISSUE THREAD

**Issue by Alpha2Cool** [spyder-ide/spyder#8379] opened 2018-12-06 08:12 UTC
when I run code on spyder the 2nd time, console report these:

-------------------------------------------------
pywrap_tensorflow.RegisterType("SparseTensorValue", SparseTensorValue)

TypeError: Type already registered for SparseTensorValue

-------------------------------------------------
ubuntu18.04 tensorflow spyder

**Comment by ccordoba12** [comment] 2018-12-06 13:33
Sorry, closing because a) you don't bother to fill out our template with the basic information we ask and we don't have time to ask you for that info again; and b) you don't even what code or program that error comes from.

**Closed by ccordoba12** 2018-12-06 13:33 UTC

**Comment by zsq15584453673** [comment] 2018-12-27 15:07
same error ,how to deal with?

**Comment by dsmic** [comment] 2019-02-03 09:41
Hi, 

I can reproduce this problem with a python file containing only one line:

import tensorflow


obviously you need tensorflow installed. just start it two times from spyder3 ide and it will throw:
a lot reload messages ending with:
ed_model.experimental, tensorflow._api.v1.saved_model.loader, tensorflow._api.v1.saved_model.main_op, tensorflow._api.v1.saved_model.signature_constants, tensorflow._api.v1.saved_model.signature_def_utils, tensorflow._api.v1.saved_model.tag_constants, tensorflow._api.v1.saved_model.utils, tensorflow._api.v1.sets, tensorflow._api.v1.signal, tensorflow._api.v1.sparse, tensorflow._api.v1.spectral, tensorflow._api.v1.strings, tensorflow._api.v1.summary, tensorflow._api.v1.sysconfig, tensorflow._api.v1.test, tensorflow._api.v1.train, tensorflow._api.v1.train.queue_runner, tensorflow._api.v1.user_ops, tensorflow._api.v1.version
Traceback (most recent call last):

  File "<ipython-input-2-977b58f2cd2d>", line 1, in <module>
    runfile('/home/detlef/prolog/PythonProlog/test.py', wdir='/home/detlef/prolog/PythonProlog')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/detlef/prolog/PythonProlog/test.py", line 4, in <module>
    import tensorflow

  File "/home/detlef/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "/home/detlef/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin

  File "/home/detlef/.local/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph

  File "/home/detlef/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 44, in <module>
    from tensorflow.python.framework import composite_tensor

  File "/home/detlef/.local/lib/python3.6/site-packages/tensorflow/python/framework/composite_tensor.py", line 95, in <module>
    pywrap_tensorflow.RegisterType("CompositeTensor", CompositeTensor)

TypeError: Type already registered for CompositeTensor
