### ISSUE TITLE
spyder 3.3.3 icon theme Spyder 3 problem with PyQt 5.12

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#8748] opened 2019-02-11 09:51 UTC
## Problem Description
After updating to Spyder 3.3.3 (on Linux, with Python 3.6.7 64-bit |  |  Qt 5.12.1 | PyQt5 5.12 ) spyder icon theme "Spyder 3" stopped working (because of coming with this version PyQt upgrade probably) . Only the "Spyder 2" icon theme is working.
Below the look of Spyder3 icon theme
![screenshot from 2019-02-11 10-36-08](https://user-images.githubusercontent.com/7980381/52555605-7e88c300-2dea-11e9-8236-f7ab0b4accd7.png)

After reverting to PyQt 5.9.2 the icon set Spyder3 is working again.

**Comment by ccordoba12** [comment] 2019-02-11 15:02
Yeah, we noticed that too but we don't know what could be causing this. I think it's a problem with PyQt5 because QtAwesome (the library we use to display our Spyder 3 icon theme) is working fine with PySide2 5.12.

**Comment by ccordoba12** [comment] 2019-02-11 15:04
For now please downgrade PyQt5 to its 5.11 version with

    pip install pyqt5==5.11.*

**Comment by stonebig** [comment] 2019-02-11 19:34
I confirm @hiccup7 remark, that Spyder2 theme of icons is working, to the opposite of Spyder3 theme

**Comment by ccordoba12** [comment] 2019-02-12 09:52
That's right, the spyder2 icon theme works ok.

**Comment by Gra55h0pper** [comment] 2019-02-12 19:17
Posting here as it seems to be related and may help. I was facing an issue on Windows-10 where after upgrading to Spyder3.3.3 it wouldn't start anymore. Calling spyder3.exe would simply return with the PowerShell prompt without anything else happening.

Downgrading to pyqt5 5.11 as per above fixed the issue.

**Comment by jcafhe** [comment] 2019-02-14 16:59
> Posting here as it seems to be related and may help [...] Downgrading to pyqt5 5.11 as per above fixed the issue.

 @Gra55h0pper  I've just had the same issue and I think this is related to the missing PyQtWebEngine package which was part of PyQt5 until [5.12](https://www.riverbankcomputing.com/news/pyqt-512).
On linux, I've got a nice error in QtPy `ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'`  but on win7, it silently returns to shell. So basically you have to `pip install PyQtWebEngine` (or conda).

**Comment by danieltomasz** [comment] 2019-02-14 17:30
Unfortunately installing it is not helping, the problem with missing icons stays. 
 I got `ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'`  when Spyder fails to starts, which disappear after uninstalling and installing again the aforementioned package but there is still Spyder3 icon set problem.

**Comment by jcafhe** [comment] 2019-02-14 17:45
Yes, you are right, sorry for my misleading comment, I was telling to Gra55hOpper that his issue may be not related to the icon problem. 
In fact, after installing myself the missing package, I ran into the icon problem too. This is how I've came to this particular issue and to the Gra55hOpper's comment.

**Comment by stonebig** [comment] 2019-02-14 19:15
@ccordoba12  is there any problem if using PyQt5-5.12 with the Spyder2 theme ?

**Comment by stonebig** [comment] 2019-02-14 20:08
there is a PyQt5-5.12-5.12.1_a today, adding  libQt5QuickShapes.so.5 that was  missing in PyQt 5.12.

**Comment by Gra55h0pper** [comment] 2019-02-15 01:34
@jcafhe, TNX! Indeed `pip install PyQtWebEngine` fixed the startup problem I was facing. 
And it's indeed not a solution for the Spyder3 icon theme problem in this thread as I'm facing the same thing myself now.

**Comment by stonebig** [comment] 2019-02-17 09:16
moving to Spyder 2 icon them is a 5 second switch: Tools->Preferences->General, then see Icon Them dropdown box

![image](https://user-images.githubusercontent.com/4312421/52910804-0d8b5480-329d-11e9-9f72-2962d04e5ba9.png)

**Comment by stonebig** [comment] 2019-02-17 11:29
is the icon issue  related to this ? https://bugreports.qt.io/browse/QTBUG-68853

**Comment by ccordoba12** [comment] 2019-02-17 12:01
@stonebig, this is a bug in PyQt, please read my https://github.com/spyder-ide/spyder/issues/8748#issuecomment-462359260 above:

>  QtAwesome (the library we use to display our Spyder 3 icon theme) is working fine with PySide2 5.12.

**Comment by hiccup7** [comment] 2019-02-17 20:05
Spyder v3.3.4 has already fixed a number of important issues with v3.3.3.  I don't want to see this issue block a quick release of v3.3.4.  Here are my suggestions to resolve this issue:

1) Define the problem as an incompatibility between QtAwesome and PyQt 5.12.  Thus, the problem is not a problem with Spyder, but instead a problem between two upstream packages.
2) To provide a good Spyder experience for inexperienced Python users, maximize Spyder's compatibility with a variety of upstream packages.  Specifically, make the Spyder 2 icon theme the default on the first run of Spyder.
3) Change the preference labels of the icon themes: Spyder 2 -> Standard, Spyder 3 -> QtAwesome.  This helps users to understand the Spyder 2 icon theme is not deprecated and to consider QtAwesome issues if the Spyder 3 icon theme fails.
4) Create a new issue for the incompatibility at https://github.com/spyder-ide/qtawesome  List it in the known Spyder issues so as to avoid duplicates by Spyder users.  Invite Riverbank Computing Limited to discuss the best way to resolve the incompatibility.  The resolution may be after the Spyder v3.3.4 release, so Spyder users need only update the upstream package when available.

**Comment by ccordoba12** [comment] 2019-03-03 17:14
Pinging @mingwandroind about this problem since you said you're about to update the Qt/PyQt conda packages to 5.12.

Ray, it seems this is a problem with PyQt5 only because QtAwesome (the library behind our icons) is working fine with PySide2. We reported this problem upstream but haven't received an answer so far.

**Comment by xu-kai-xu** [comment] 2019-03-05 09:26
when i use conda to update spyder to 3.3.3, a removeError occurred: `'setuptools' is a dependency of conda and cannot be removed from  conda's operating environment.` And i can not update it by ananconda directly, it says multiple error occurred.

**Comment by ccordoba12** [comment] 2019-03-05 09:29
@xu-kai-xu, that's a different issue from this one. Please don't post anymore here and open a new issue instead.

**Closed** 2019-03-07 12:29 UTC
Labels: tag:Ui, type:Bug

**Comment by SurajMeena** [comment] 2019-06-22 06:49
I solved this issue by downloading qt bindings from conda web page, [https://anaconda.org/anaconda/pyqt](url)

**Comment by UJJWAL-1711** [comment] 2020-05-25 05:51
> Posting here as it seems to be related and may help. I was facing an issue on Windows-10 where after upgrading to Spyder3.3.3 it wouldn't start anymore. Calling spyder3.exe would simply return with the PowerShell prompt without anything else happening.
> 
> Downgrading to pyqt5 5.11 as per above fixed the issue.

how to delete the newer one , do I have to ???

**Comment by SurajMeena** [comment] 2020-05-25 10:12
> > Posting here as it seems to be related and may help. I was facing an issue on Windows-10 where after upgrading to Spyder3.3.3 it wouldn't start anymore. Calling spyder3.exe would simply return with the PowerShell prompt without anything else happening.
> > Downgrading to pyqt5 5.11 as per above fixed the issue.
> 
> how to delete the newer one , do I have to ???

I don't think you need to delete the updated one....just install specified version normally.
