### ISSUE TITLE
Make Variable/File explorers to follow the color scheme of the Editor

### ISSUE THREAD

**Issue by nchlis** [spyder-ide/spyder#3814] opened 2016-12-09 09:58 UTC
Hi,

first of all thanks for the great IDE.

I've changed the editor and python console dark color schemes.
However, there is no option to change the background color of the variable/file explorer,
which ends up making it distracting. It would be useful if you could add such a feature in a
future release.

**Comment by ccordoba12** [comment] 2016-12-09 21:33
Thanks for reporting. This is in our plans for Spyder 3.2 :-)

**Comment by talkaminker** [comment] 2017-01-10 09:11
also the Help panel should be probably have a background color option.
Also, I can already guess that in the Help there might be problem when latex is rendered. (in dark background latex should also be rendered white)

**Comment by ccordoba12** [comment] 2017-08-13 17:41
This is a duplicate of issue #2350.

**Closed by ccordoba12** 2017-08-13 17:41 UTC
