### ISSUE TITLE
unable to launch Spyder, and new version of spyder is not supporting python 2.7

### ISSUE THREAD

**Issue by yashu0008** [spyder-ide/spyder#8106] opened 2018-10-19 23:31 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Unable to launch Spyder for python 2.7 and upgraded or new version of Spyder not supporting python 2.7

### What steps reproduce the problem?

1. Launch Spyder in windows
2. 
3. 

### What is the expected output? What do you see instead?
Spyder application should open

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: from anaconda2
* Python version: 2.7
* Qt version: 
* PyQt version: 
* Operating System name/version:  Windows 7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2018-10-19 23:48
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by ccordoba12** [comment] 2018-10-26 13:44
Closing because of lack of response.

**Closed by ccordoba12** 2018-10-26 13:44 UTC
Labels: status:Awaiting Followup
