### ISSUE TITLE
Python stops working randomly because of ZMQ issues

### ISSUE THREAD

**Issue by VanitarNordic** [spyder-ide/spyder#4645] opened 2017-06-24 05:21 UTC
Hello,

I've installed the Python and related packages in accompany with the `Spyder` using Anaconda on Windows 10. But sometimes during use of the Spyder, I see the message that Python stopped working. 

I can say it happens when I don't type something inside Spyder or when I don't use it for sometime, but it happens randomly, not by a logical order. Besides, "stopped working" window is not one, an unknown crash creates several identical "python stopped working" windows which when I close them all, then the Spyder closes.

Python version is 3.5 on the Anaconda environment.

Please make a fix.

**Comment by ccordoba12** [comment] 2017-06-24 13:31
Sorry to hear that this happening to you, but without a way to reproduce this bug, it's not possible for us to help you.

**Comment by VanitarNordic** [comment] 2017-06-24 13:47
Just install the Anaconda on Windows 10 and make a virtual environment for Python 3.5. activate that environment and install required packages. then run Spyder and let it run for some time and touch nothing. I guarantee you will face this.

**Comment by ccordoba12** [comment] 2017-06-24 18:46
If that would be the case, we would be hearing a lot of complaints about this, but we're not.

So I think there should be something special about your setup. Sorry for not being more helpful.

**Comment by VanitarNordic** [comment] 2017-06-24 20:18
No, your comment is also helpful which pushes me to investigate more. thanks.

**Comment by ccordoba12** [comment] 2017-06-25 15:42
Please let us know if you manage to find the cause of your problem. My guess is that this has something to do with your firewall/antivirus interrupting local network communications, which are needed by Spyder to do several things.

Closing for now because we can't be of more help.

**Comment by VanitarNordic** [comment] 2017-10-05 12:35
I forgot to mention the reason of this, but the problem was because of the Firewall settings. Spyder must be listed inside the Windows firewall Allowed apps, even if it does not handle a warning at the launch time to be added automatically.

**Comment by ccordoba12** [comment] 2017-10-05 15:11
Thanks a lot for letting us know about the solution to your problem! From now on it'll be easier for us to let other people know about it.

**Comment by VanitarNordic** [comment] 2017-10-08 15:09
Un fortunately I have to change my word, the problem still persists. I was mistaken.

But now I know something for sure. the problem does not happen when I use Python2 environment. it happens when I install the Spyder in the Python3 environment.

**Comment by ccordoba12** [comment] 2017-10-09 14:02
You probably need to also add `python3` and the Spyder executable or script of your Python 3 environment to the Windows firewall Allowed apps.

**Comment by VanitarNordic** [comment] 2017-10-10 13:03
@ccordoba12 

I've done that before but no improvement.

This time I run the Spyder by `spyder --show-console` and got these errors when the crash happened:

```
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:181)
```

**Comment by ccordoba12** [comment] 2017-10-10 16:47
Please apply locally the fix present in #5356 and try again. Maybe that fixes your problem.

**Comment by VanitarNordic** [comment] 2017-10-10 17:10
it seems you have applied that already, isn't it?

**Comment by ccordoba12** [comment] 2017-10-10 19:39
It's here on Github, but it's not part of any official version yet.

**Comment by VanitarNordic** [comment] 2017-10-10 20:02
Okay, thank you. So I should install the Spyder from the source. 

May I ask you when will you release the new version?

**Comment by ccordoba12** [comment] 2017-10-10 20:35
> Okay, thank you. So I should install the Spyder from the source.

You can simply copy/paste the change to `spyder/app/start.py`, given that it's so simple. But I really don't know if that fix will solve your problem.

Please test it and let us know about it.

> May I ask you when will you release the new version?

Hopefully this weekend.

**Comment by VanitarNordic** [comment] 2017-10-15 00:00
@ccordoba12 

I think the error must be solved in this way: https://stackoverflow.com/questions/37962472/why-python-raised-an-assertionerror-on-some-failed-assumption-in-a-zeromq-client

Have you used the ZeroMQ for sending messages? it says that we must use a numeric address (such as  `tcp://127.0.0.1:5555`) instead of the `"localhost"`

**Comment by ccordoba12** [comment] 2017-10-15 16:34
Thanks for the information. We'll change to use the numeric address of the loopback interface in our next release.

**Comment by VanitarNordic** [comment] 2017-10-15 18:56
I appreciate if you include within 3.2.4 release, otherwise no problem.

**Comment by VanitarNordic** [comment] 2017-11-06 18:59
Yes, it still exist, after around 2 hours of continues working, Spyder crashes with the same conditions. I can be sure it will get fixed by this as it seems to be a known issue with ZeroMQ

**Comment by ccordoba12** [comment] 2018-03-03 20:17
I investigated this and the suggested solution doesn't change anything, according to ZMQ docs. So I'm closing this issue.

**Closed by ccordoba12** 2018-03-03 20:17 UTC
Labels: component:Code Completion, type:Bug
