### ISSUE TITLE
3.2   Warn if PEP 8 code style guidelines are violated 

### ISSUE THREAD

**Issue by sgilmour14** [spyder-ide/spyder#13057] opened 2020-06-18 19:47 UTC
Hi,
I am following the Spyder: The Scientific Python Development Environment

3.2   Warn if PEP 8 code style guidelines are violated
Go to Preferences --> Editor --> Code Introspection/Analysis and tick the checkbox next to Real-time code style analysis.  How do I do this in the new version Spyder (Python 3.7) 
I do not see the Code Introspection/Analysis tab. Is there a new way to set the preference.

**Comment by ccordoba12** [comment] 2020-06-18 21:41
Thanks for reporting. This is a duplicate of issue #13043.

**Closed by ccordoba12** 2020-06-18 21:41 UTC
