### ISSUE TITLE
Spyder can't start because of socket issues

### ISSUE THREAD

**Issue by Wuffalo** [spyder-ide/spyder#4366] opened 2017-04-15 21:49 UTC
I am using Anaconda 1.5. Created a new environment for Py3.6. Spyder won't open from Navigator when new environment is selected and the spyder is the one in that environment. 

`(C:\ProgramData\Anaconda2\envs\Python36) C:\Users\Wuffalo\AnacondaProjects>spyder
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\Python36\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\ProgramData\Anaconda2\Lib\site-packages\spyder\app\start.py", line 7, in <module>
    import socket
  File "C:\ProgramData\Anaconda2\envs\Python36\lib\socket.py", line 53, in <module>
    from enum import IntEnum, IntFlag
ImportError: cannot import name 'IntFlag'`

And now when I switch back to my 2.7 environment I cannot open Spyder there without using terminal.
Is this a python installation problem? I have tried restarting but haven't tried reinstalling python yet. 

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 
* Operating system: Win10

**Comment by ccordoba12** [comment] 2017-04-23 23:57
It seems an error with the sockets module. We'll try to add a workaround for this in Spyder 3.2

**Comment by ccordoba12** [comment] 2017-05-07 23:23
Closing as a duplicate of #4132.

**Closed by ccordoba12** 2017-05-07 23:23 UTC
Labels: component:Main Window, resolution:Duplicate, type:Bug
