### ISSUE TITLE
Spyder crashed when loading a large .npz or .npy file

### ISSUE THREAD

**Issue by ProtossProbe** [spyder-ide/spyder#3103] opened 2016-04-11 02:07 UTC
## Description

**What steps will reproduce the problem?**
1. Load a large (62.7MB) .npz or .npy numpy array file with np.load or Variable explorer.
2. Spyder crash.

**What is the expected output? What do you see instead?**
I expected to import my data, but Spyder crashed.

**Please provide any additional information below**
It was successful to load a small .npy file in Spyder. 
## Version and main components
- Spyder Version: 3.0.0b2 
- Python Version: 2.7.11
- Qt Versions: 5.5.0, PyQt5 5.5 on Darwin
## Dependencies

```
pyflakes >=0.5.0:  1.1.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
IPython >=3.0   :  4.1.2 (OK)
zmq >=13.0.0    :  15.2.0 (OK)
qtconsole >=4.0 :  4.2.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
numpy >=1.7     :  1.10.4 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
psutil >=0.3    :  4.1.0 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  1.5.5 (OK)

```

**Comment by goanpeca** [comment] 2016-04-11 02:09
@ProtossProbe thanks for reporting. Do you think you can provide a test file, so we can reproduce the error you are experiencing?

**Comment by ProtossProbe** [comment] 2016-04-11 02:15
OK, I'm uploading the file.

**Comment by ccordoba12** [comment] 2016-04-11 02:37
@ProtossProbe, does your file has strings on it?

**Comment by ProtossProbe** [comment] 2016-04-11 02:40
@ccordoba12 No strings.
But this file is not an np.array. It is a tuple whose element is np.array with different size.

**Comment by Nodd** [comment] 2016-04-12 08:24
Looks like another case of "string representation too big". Does the problem still occur if you disable the variable explorer ?

**Comment by ProtossProbe** [comment] 2016-04-12 10:06
@Nodd 
Yeah. I close the variable explorer and load the data successfully.

**Comment by ccordoba12** [comment] 2016-04-12 16:12
@Nodd, thanks for pointing that out. If that's the case (which I'll test later), then I think this problem is fixed in master.

**Comment by goanpeca** [comment] 2019-11-30 00:24
```python
import tempfile
import numpy as np

fh, outfile  = tempfile.mkstemp(suffix='.npz')
print(outfile)
x = np.arange(10000000)
y = np.sin(x)
a = (x, y)
np.savez(outfile, a)

a = np.load(outfile)
arr_0 = a['arr_0']
```

This seems to work fine. Closing

**Closed by goanpeca** 2019-11-30 00:24 UTC
Labels: component:Variable Explorer, type:Bug
