### ISSUE TITLE
Spyder Mac app laggy in 5.2.0

### ISSUE THREAD

**Issue by andyrevell** [spyder-ide/spyder#16910] opened 2021-11-28 21:35 UTC
## Problem Description

Hi,

Just letting you guys know that this problem is pretty pervasive. In an academic setting at my university, multiple labs across campus are realizing independently the turn for the worse Spyder is becoming, especially with the lag across Mac users. It's affecting a lot of undergrads who come through our labs too, and most now go to PyCharm as their python IDE for data science. I suspect most of these new users will never touch Spyder. I'm just the messenger here and letting you guys know that after seeing the trend for the last year, people are beginning to have an unfavorable opinion of Spyder across my university, including multiple PIs and professors that used to use Spyder in their courses. This problem seems not fixed yet, and despite implementations of bloated bells and whistles (like integration of Kite), the one thing that actually may affect user growth at its root is not being addressed.

**Comment by ccordoba12** [comment] 2021-11-29 04:52
Hey @andyrevell, thanks a lot for reporting this problem and for voicing your concerns. We're aware of these issues and right now are working really hard to fix them.

A lot of improvements in this area were included in 5.1.5 (the latest version available in Anaconda), some more were added in 5.2.0 (our latest version), and right now we're working in even more improvements for 5.2.1 (see PR #16864).

Please try 5.2.0 by installing our [Mac app](https://github.com/spyder-ide/spyder/releases) and let us know how it behaves for you. Feedback from our community is very valuable and appreciated, and it's also crucial to understand how we should invest our time and efforts in the future.

**Comment by ghost711** [comment] 2021-12-01 15:33
5.1.5 mostly fixed the lag issues on Mac for me.  It was the best Spyder had run for me in at least a year, and much appreciated, so thanks for that. 

The lag seems to be back in full force with 5.2.0 though.  
Just as with versions < 5.1.5, the lag goes away if I disable the Python Language Server, but then there's no linting.

**Comment by ccordoba12** [comment] 2021-12-01 16:24
> The lag seems to be back in full force with 5.2.0 though.

Hey @ghost711, thanks for chiming in! That's really bad news.

Some questions for you:

* Are you also using a Mac?
* If that's the case, are you on an M1 or Intel?
* How did you install Spyder?
* Could you upload your Spyder configuration to check what options are you using that cause the lag? You can find it in `~/.spyder-py3/config/spyder.ini` if you're on Mac.

**Comment by ccordoba12** [comment] 2021-12-01 16:25
@mrclary, @impact27, have you noticed any regressions when typing on 5.2.0?

**Comment by mrclary** [comment] 2021-12-01 17:01
Yep, I definitely see a regression...

![latency-regression](https://user-images.githubusercontent.com/9618975/144278993-f4b7a6cf-9441-4a3b-b07d-dd85a0c46611.gif)

**Comment by ccordoba12** [comment] 2021-12-01 17:07
Ok, that's really frustrating. I don't really know why the sluggishness reappeared again.

@mrclary, could you use `git bisect` between 5.1.5 and 5.2.0 to track down the faulty commit? As soon as you let me know about it, I'll try to fix the problem so we can include it in 5.2.1, to be released next week.

**Comment by mrclary** [comment] 2021-12-01 17:09
There does not seem to be a problem with the latest 5.x bootstrap, though. That is weird. I'll do some digging and report what I find.

**Comment by impact27** [comment] 2021-12-01 17:12
I have seen this as well, but I think this is fixed by https://github.com/spyder-ide/spyder/pull/16864. It would however make sense to add a test to avoid this kind of regression and keep track of the evolution of spyder speed. I am not sure what the best way of doing that is though.

**Comment by ccordoba12** [comment] 2021-12-01 17:24
> There does not seem to be a problem with the latest 5.x bootstrap, though. That is weird. I'll do some digging and report what I find.

Oh, that's really weird! I mean, we haven't touched many things related to the editor after 5.2.0 was released, and the few shouldn't be related to performance in the editor (as far as I can tell).

> I have seen this as well, but I think this is fixed by #16864

Ok, then the best course of action is to wait until #16884 to release 5.2.1

> I am not sure what the best way of doing that is though.

Yeah, me neither, that's why I haven't added a test for that yet. What if we use `timeit` as you did in #16884? I mean, we could use the value reported by CIs in that PR as our baseline (plus a small offset to account for differences), and then `assert` that new changes don't make that value higher.

**Comment by ccordoba12** [comment] 2021-12-01 17:33
Sorry, that's right, I meant PR #16864.

**Comment by mrclary** [comment] 2021-12-01 17:40
The latest artifact from #16864 shows bad latency, but bootstrap from the latest commit 0b104325d29ef64f6d6ad80accebb30371f40381 on impact27/fast_spyder branch does _not_ show latency.

I suspect a difference in python packages between the build environment and the conda environment. I'll keep looking.

**Comment by impact27** [comment] 2021-12-01 17:43
If you have a profiler run which shows latency I could have a look. 
`python -m cProfile -o output.prof bootstrap.py`

**Comment by ghost711** [comment] 2021-12-01 17:47
Update: I tried switching to Python 3.10, and now the lag appears to be gone!  
Answers to your previous questions:

> * Are you also using a Mac? 
Yes
> * If that's the case, are you on an M1 or Intel? 
Intel
> * How did you install Spyder?
.dmg installer.
> * Could you upload your Spyder configuration to check what options are you using that cause the lag? You can find it in `~/.spyder-py3/config/spyder.ini` if you're on Mac.
[spyder.ini.zip](https://github.com/spyder-ide/spyder/files/7636095/spyder.ini.zip)

**Comment by mrclary** [comment] 2021-12-01 18:50
@ccordoba12, I cannot check the artifacts from the last two merged merge requests #16915 and #16925. The MR were merged with mac installer failures:
```
Error: -01 15:32:43,990 [ERROR] [Installer] -> Missing dependencies
  # Mandatory:
  spyder_kernels >=2.2.0;<2.3.0 :  3.0.0.dev0 (NOK)
```
I've seen this before when attempting to merge into master instead of 5.x, so I don't know what is happening here.

**Comment by mrclary** [comment] 2021-12-01 20:02
Okay, I found the issue. It is not a regression, rather #16446 did not completely resolve #14823 for the macOS installer because `jellyfish` did not get packaged with the installer. I consider this a failure on the installer since it copies the egg-info into the installer, so Spyder thinks it is installed (but it really isn't) and is not caught by the installer test.

I will submit a PR that (a) ensures that `jellyfish` is packaged with the installer and (b) ensures a more robust treatment of egg-info for the installer so that dependency tests are not fooled.

**Comment by ghost711** [comment] 2021-12-01 20:19
I did a `conda install jellyfish` and now the behavior seems better but not quite fixed. Is that what you expected?
I'm just doing the simplest test possible: Holding in the `d` key and watching the characters attempt to print at the repeat rate for the key.  
Before installing jellyfish: 
- Prints in bursts of decent speed, with periodic pauses (approx 0.5 secs every 2 secs).
After:
- Prints continuously, but seems to be at a slower rate than during the bursts before installing jellyfish.

In both cases, CPU goes nuts both during and for a long time after (several minutes).

**Comment by mrclary** [comment] 2021-12-01 20:22
@ghost711, installing jellyfish locally will not resolve the issue. It must be packaged inside the Spyder.app application, not part of an external environment.

**Comment by ghost711** [comment] 2021-12-01 20:24
Ok, I thought that might be the case.  The difference I saw might have just been due to unrelated system state then.

**Comment by ccordoba12** [comment] 2021-12-01 21:54
> I will submit a PR that (a) ensures that jellyfish is packaged with the installer and (b) ensures a more robust treatment of egg-info for the installer so that dependency tests are not fooled.

Thanks for your help with this @mrclary!

**Closed** 2021-12-02 20:25 UTC
Labels: type:Bug, component:Editor
