### ISSUE TITLE
Add a second set of shortcuts for easy use with macOS

### ISSUE THREAD

**Issue by castielle** [spyder-ide/spyder#4551] opened 2017-06-03 08:42 UTC
For the Mac touch bar, the function keys are off by default.

Make it so Spyder can be registered with Keyboard preferences to always show function keys  by default.

**Comment by ccordoba12** [comment] 2017-06-03 13:54
Thanks for reporting. This is going to be addressed in Spyder 4.

**Comment by goanpeca** [comment] 2019-11-25 19:21
@jnsebgosselin this is probably related to your work

**Comment by ccordoba12** [comment] 2019-12-25 15:44
Duplicate of #10854

**Closed by ccordoba12** 2019-12-25 15:44 UTC
Labels: OS:MacOS, component:Preferences, type:Enhancement
