### ISSUE TITLE
Trying to copy variable from variable explorer raises internal error

### ISSUE THREAD

**Issue by colorizer** [spyder-ide/spyder#16420] opened 2021-09-14 06:02 UTC
### What steps will reproduce the problem?

1. Run python code in debugging mode
2. try to copy any variable during debugging using variable explorer --> right click --> copy.

Note that I'm running the python code with custom python version.

### Traceback
```python-traceback
  File "/usr/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/main_widget.py", line 636, in copy
    self._current_editor.copy()
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 1096, in copy
    obj = self.delegate.get_value(idx)
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 1437, in get_value
    return self.parent().get_value(name)
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 1495, in get_value
    value = self.shellwidget.get_value(name)
  File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 102, in get_value
    return self.call_kernel(
  File "/usr/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "/usr/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 437, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "/usr/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 493, in _sync_error
    error_wrapper.raise_error()
  File "/usr/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_value:

  File "/usr/lib/python3.9/site-packages/spyder_kernels/comms/commbase.py", line 340, in _handle_remote_call
    return_value = self._remote_callback(

  File "/usr/lib/python3.9/site-packages/spyder_kernels/comms/frontendcomm.py", line 271, in _remote_callback
    return super(FrontendComm, self)._remote_callback(

  File "/usr/lib/python3.9/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    return self._remote_call_handlers[call_name](

  File "/usr/lib/python3.9/site-packages/spyder_kernels/console/kernel.py", line 203, in get_value
    return ns[name]

KeyError: 'end_node'

```

## Versions

* Spyder version: 5.1.3 
* Python version: 3.8.11
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Linux 5.14.1-1-default

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.25.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.0 (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by steff456** [comment] 2021-09-14 20:51
Hi @colorizer,

Can you please upload a snippet of code to try to reproduce this issue? I tried with a very simple code and wasn't able to reproduce it.

**Comment by colorizer** [comment] 2021-09-15 03:32
Okay, I'm not able to reproduce this issue either. It was repeatable during that session. I was trying to copy a 3D array. Its still not possible to copy a 3D array but I get a warning now instead of the error message. 

![image](https://user-images.githubusercontent.com/64630824/133366067-fd81a437-5c0b-4db0-bedf-26d354547f24.png)

```python
import numpy as np

a = np.random.rand(3,4,5)
````

I guess this is expected behaviour for 3D arrays?

**Comment by ccordoba12** [comment] 2021-09-18 18:32
Yes, it is. Closing because there's no way to reproduce this.

**Closed by ccordoba12** 2021-09-18 18:32 UTC
Labels: status:Awaiting Followup
