### ISSUE TITLE
Cannot update Anaconda - bot incorrectly diagnosed

### ISSUE THREAD

**Issue by lillelur** [spyder-ide/spyder#21176] opened 2023-07-23 19:56 UTC
Thanks for reporting. To fix this error, please close Spyder, open the Anaconda Prompt and run there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

_Originally posted by @spyder-bot in https://github.com/spyder-ide/spyder/issues/21174#issuecomment-1646895989_
            
I've already tried this. It gives the same error. I sent the exact message in my previous post.

**Comment by ccordoba12** [comment] 2023-07-24 02:08
Closing as a duplicate of issue #21174.

**Closed by ccordoba12** 2023-07-24 02:08 UTC
