### ISSUE TITLE
Launching spyder reports missing dependencies for spyder_kernel 2.0.1

### ISSUE THREAD

**Issue by shimpimohit** [spyder-ide/spyder#15140] opened 2021-04-06 12:03 UTC
### What steps will reproduce the problem?

Launch Spyder 5.0.0.
It launches and throws an error saying missing dependencies for spyder_kernels 2.0.1 inspite of spyder_kernel 2.0.1 being already installed

**Comment by ChuangRoy** [comment] 2021-04-06 13:27
I have the same problum, like this.
![image](https://user-images.githubusercontent.com/53178918/113717670-6ee13c80-971e-11eb-832f-0cdc648ba6c3.png)

This is the packages that I installed:

> alabaster==0.7.12
anyio==2.2.0
appdirs==1.4.4
argon2-cffi==20.1.0
arrow==1.0.3
astroid==2.5.2
async-generator==1.10
atomicwrites==1.4.0
attrs==20.3.0
autopep8==1.5.5
Babel==2.9.0
backcall==0.2.0
bcrypt==3.2.0
binaryornot==0.4.4
black==20.8b1
bleach==3.3.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
coloredlogs==15.0
cookiecutter==1.7.2
cryptography==3.4.7
decorator==4.4.2
defusedxml==0.7.1
diff-match-patch==20200713
docutils==0.17
entrypoints==0.3
flake8==3.8.4
helpdev==0.7.1
humanfriendly==9.1
idna==2.10
imagesize==1.2.0
importlib-metadata==3.10.0
inflection==0.5.1
intervaltree==3.1.0
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
isort==5.8.0
jedi==0.17.2
Jinja2==2.11.3
jinja2-time==0.2.0
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-packaging==0.7.12
jupyter-server==1.5.1
jupyterlab==3.0.12
jupyterlab-pygments==0.1.2
jupyterlab-server==2.4.0
keyring==23.0.1
lazy-object-proxy==1.6.0
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
mypy-extensions==0.4.3
nbclassic==0.2.6
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
numpydoc==1.1.0
packaging==20.9
pandocfilters==1.4.3
paramiko==2.7.2
parso==0.7.0
pathspec==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
poyo==0.5.0
prometheus-client==0.10.0
prompt-toolkit==3.0.18
psutil==5.8.0
ptyprocess==0.7.0
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==6.0.0
pyflakes==2.2.0
Pygments==2.8.1
pylint==2.7.4
pyls-black==0.4.6
pyls-spyder==0.3.2
PyNaCl==1.4.0
pyparsing==2.4.7
PyQt5==5.12.3
pyqt5-plugins==5.15.2.2.1.0
PyQt5-sip==12.8.1
pyqt5-tools==5.15.2.3.0.2
PyQtWebEngine==5.12.1
pyreadline==2.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.17.0
python-jsonrpc-server==0.4.0
python-language-server==0.36.2
python-slugify==4.0.1
pytz==2021.1
pywin32==300
pywin32-ctypes==0.2.0
pywinpty==0.5.7
pyzmq==22.0.3
QDarkStyle==3.0.2
qstylizer==0.1.10
qt5-applications==5.15.2.2.1
qt5-tools==5.15.2.1.0.1
QtAwesome==1.0.2
qtconsole==5.0.3
QtPy==1.9.0
regex==2021.3.17
requests==2.25.1
rope==0.18.0
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
snowballstemmer==2.1.0
sortedcontainers==2.3.0
Sphinx==3.5.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==5.0.0
spyder-kernels==2.0.1
terminado==0.9.4
testpath==0.4.4
text-unidecode==1.3
textdistance==4.2.1
three-merge==0.1.1
tinycss==0.4
toml==0.10.2
tornado==6.1
traitlets==5.0.5
typed-ast==1.4.2
typing-extensions==3.7.4.3
ujson==4.0.2
urllib3==1.26.4
watchdog==1.0.2
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.12.1
yapf==0.31.0
zipp==3.4.1

**Comment by vigneshgarrapally** [comment] 2021-04-06 14:03
Yes, Even I am Having the same issue. I have installed it today

**Comment by ccordoba12** [comment] 2021-04-06 14:49
This problem is a duplicate of issue #15091 and it'll be fixed in our next version, to be released shortly.

**Comment by ccordoba12** [comment] 2021-04-06 14:50
You can safely ignore this message in the meantime, it's a false alarm.

**Closed by ccordoba12** 2021-04-06 14:49 UTC
