### ISSUE TITLE
File path no longer shown in Editor pane on 3.1.3

### ISSUE THREAD

**Issue by joshburnett** [spyder-ide/spyder#4264] opened 2017-03-16 12:14 UTC
## Description
In 3.1.2, the Editor pane displays the full path to the current file:
![image](https://cloud.githubusercontent.com/assets/12973799/23995519/52dc95aa-0a20-11e7-9257-87e32271cabb.png)

After updating to 3.1.3, the pane title simply shows 'Editor':
![image](https://cloud.githubusercontent.com/assets/12973799/23995546/6f18c306-0a20-11e7-8f35-1854ba752909.png)

There do not appear to be any options in the Preferences dialog to change this behavior.

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.11
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.10.4 (OK)
sphinx >=0.6.6   :  1.5a1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by goanpeca** [comment] 2017-03-16 18:06
Duplicate of https://github.com/spyder-ide/spyder/issues/4259

**Closed by goanpeca** 2017-03-16 18:06 UTC
Labels: resolution:Duplicate
