### ISSUE TITLE
Unintuitive arrow behavior in editor

### ISSUE THREAD

**Issue by luciansmith** [spyder-ide/spyder#12706] opened 2020-05-12 23:58 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ *] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The arrow key behavior in the editor is unintuitive, and different from what it used to be in spyder 3 (and possibly earlier versions of spyder 4)

### What steps reproduce the problem?

1. Create a file with the following program in it:
 
     for i in range(10):
          print(i)
          print(i+1)
          print(i+2)

2. Now we decide that we want to change the indenting by removing one space on every line.  Move the cursor to the leftmost position in line 2, under the 'f'.

3. Hit 'Delete'.

4. Hit the down arrow.

5. Notice that instead of being in the far left column, I'm now one column over, for some reason.

6. Hit 'Delete' again.

7. Hit the down arrow.

8. We've moved over to the right once more.  Argh!

### What is the expected output? What do you see instead?

I would expect the down arrow key to track with the *leftmost* relative position it used to be in, not the *rightmost*, when using the 'delete' key.

Note that the correct behavior is observed with 'backspace':

1. Create:
      for i in range(10):
          print(i)
          print(i+1)
          print(i+2)

2. Move the cursor to the left of the first 'p' in 'print'.

3. Hit 'backspace'

4. Hit the down arrow.

5. We're next to the 'p' again.  This is correct!

In other words, 'backspace' deletes from the right, and up/down should line up with with where the cursor was, relative to the right of the selection. But 'delete' deletes from the left, and up/down should line up with where the cursor was relative to the *left* of the selection.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Spyder 4.1.3 
Python 3.7.7 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by remisalmon** [comment] 2020-05-13 00:08
Looks like a duplicate of #12663

**Comment by goanpeca** [comment] 2020-05-13 00:16
Hi @luciansmith , thanks for your report. Indeed it is an issue and I can reproduce it.

@remisalmon it is duplicate of #12663 so closing in favor of that one.

Cheers!

**Closed by goanpeca** 2020-05-13 00:16 UTC
Labels: component:Editor, type:Bug

**Comment by luciansmith** [comment] 2020-05-13 00:27
Ah!  My search fu failed me.  Thanks!

**Comment by goanpeca** [comment] 2020-05-13 00:29
>Ah! My search fu failed me

Been there 🙃!

No prob!

One final question. Was a previous 4.x version displaying the same behavior? As in this is a regression from 3 -> 4, or from 4.1 -> 4.1.3

That could help us narrow the issue!

**Comment by luciansmith** [comment] 2020-05-13 03:31
Phew; I'm not entirely sure.  I feel like I just saw this behavior show up the last time I updated, so maybe... 4 months ago?  That's more an intuition than actual data, but I hope it helps.
