### ISSUE TITLE
cannot open remote kernel

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#7528] opened 2018-07-22 15:57 UTC
```
File "/Users/wenjian/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1060, in create_client_for_kernel
    password)
  File "/Users/wenjian/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1782, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "/Users/wenjian/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 57, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'
```

**Comment by ccordoba12** [comment] 2018-07-22 17:54
This is a duplicate of #7082 and it'll be fixed in our next version. The process to connecting to external kernels has also changed:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#2-the-modular-approach

**Closed by ccordoba12** 2018-07-22 17:54 UTC
