### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by cjltctc** [spyder-ide/spyder#6136] opened 2018-01-05 00:03 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "E:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "E:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "E:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "E:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "E:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 6: ordinal not in range(128)
Traceback (most

**Comment by CAM-Gerlach** [comment] 2018-01-05 00:42
Thanks for reporting. This issue is a duplicate of #5833 , as it looks like you have one or more non-ASCII characters in your data frame index, which Python 2 doesn't natively handle well without specific mitigations. Upgrading to Python 3 or using only ASCII characters in your df indices (probably a good practice anywhere for interoperability, since df indices should generally be kept "clean" and can be rather picky about what they're set to anyway) should fix it, though it looks like it may be possible for Spyder to handle it in the a future version. In any case, this issue will be closed. Best of luck!

**Closed by CAM-Gerlach** 2018-01-05 00:42 UTC
