### ISSUE TITLE
Spyder freezes if you continuously press profiler action 'Expand one level down'

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13001] opened 2020-06-11 17:53 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Profile a file which content is for example:
```python
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 7.0, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t, s)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.savefig("test.png")
plt.show()
```
2. After the profile process finishes click multiple times the option `Expand one level down` 
![image](https://user-images.githubusercontent.com/16781833/84422393-8fb23180-abe2-11ea-9292-cbd2b6160521.png)

3. Freeze and possible crash.

### What is the expected output? What do you see instead?

![profile3](https://user-images.githubusercontent.com/16781833/84422207-4b269600-abe2-11ea-99d1-eed53f498c11.gif)

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by oscargus** [comment] 2020-06-23 16:36
Same as #9719? I believe continuously parsing the strings when sorting contributes significantly to this. Better to keep sorting data separately. (I haven't checked the code recently though.) Also, the tree view is not really that fast in itself when there are many items.

**Comment by ccordoba12** [comment] 2020-06-24 17:49
> Same as #9719?

Yes, let's close this one as a duplicate of that issue.

> I believe continuously parsing the strings when sorting contributes significantly to this. Better to keep sorting data separately

Good point, we should that in a thread.

**Closed** 2020-06-24 17:50 UTC
Labels: component:Profiler, type:Bug
