### ISSUE TITLE
Can't catch Ctrl + C in user input

### ISSUE THREAD

**Issue by Nishant-Ingle** [spyder-ide/spyder#9528] opened 2019-06-07 07:56 UTC
### What steps will reproduce the problem?

Just execute the below code in Spyder:

```
    try:
        while True:
            line = input()
            print(line)
    except:
            pass
    print("Exiting)
    
```
    
When the user enters Ctrl + C, it fails to catch it and console hangs. I have tried using signals, except KeyboardInterrupt, etc. but nothing works. Only way to stop execution is restarting kernel. 
    
It would be helpful if signal handling is done properly in upcoming versions of Spyder.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-07 09:09
Closing as a duplicate of #5401. Sorry but we don't know how to fix this and it only happens on Windows.

**Closed by ccordoba12** 2019-06-07 09:09 UTC
