### ISSUE TITLE
Walrus operator incorrectly shows error on Windows app

### ISSUE THREAD

**Issue by iamlevis** [spyder-ide/spyder#17472] opened 2022-03-11 15:17 UTC
### What steps will reproduce the problem?

The walrus operator (:=) is valid in python 3.8.  The following code is valid, but Spyder puts an error icon in the gutter.  That error is incorrect!
print(foo:="hello")
hello

print(foo)
hello

More info at: https://docs.python.org/3/whatsnew/3.8.html

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by iamlevis** [comment] 2022-03-11 15:21
This is interesting:  I submitted this issue through Spyder and I see that it's reporting the Python as version 3.7.9.  However, in the console it says 3.9.6 (which I'm expecting).  Maybe this is caused by the editor and the console being in disagreement?
sys.version
Out[6]: '3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]'

**Comment by dalthviz** [comment] 2022-03-11 19:09
Hi @iamlevis thank you for the feedback! Are you using the window installer with a custom interpreter? Could you try to see if restarting the Python Language Server helps?

For that you can check https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#lsp-has-stopped-working

Let us know if something of the above helps

**Comment by iamlevis** [comment] 2022-03-12 17:39
I'm afraid that restarting the LSP server didn't change anything.
[image: image.png]

**Comment by dalthviz** [comment] 2022-03-14 14:46
Could you submit the image directly on github @iamlevis ? Email answers doesn't support showing attachments on the GitHub interface. Thanks!

**Comment by dalthviz** [comment] 2022-03-14 17:49
@iamlevis I was able to reproduce this. For our next release (5.3.0) we will be building the Windows installers with Python 3.8.10 so I think this should be fixed with that. However, I though that the linting was dependant on the interpreter preference but maybe I was wrong. Pinging @ccordoba12 and @andfoy since maybe they know better

**Comment by ccordoba12** [comment] 2022-03-17 16:43
I can't reproduce this in an environment with Python 3.8. I think it is flagged as an error in our current Windows installer because it's built with Python 3.7 and the Walrus operator was added in 3.8.

So, I'm going to close this issue as fixed and link it to the PR that updated our Windows for our next version (5.3.0).

**Closed** 2022-03-17 16:45 UTC
Labels: type:Bug, OS:Windows, tag:Installer
