### ISSUE TITLE
Closing quotes not inserted within square braces

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#7906] opened 2018-09-16 12:28 UTC
**Steps to reproduce:**
* Go to Tools -> Preferences -> Editor -> Advanced settings.
* Tick "Automatic insertion of parentheses, braces and brackets" and "Automatic insertion of closing quotes".
* Go to the editor pane.
* Type, in this order: `a`, `[`, `"` (one or more letters, an opening square bracket, and  quote marks).

**Expected behavior:**
* Should automatically add a closing square bracket and a closing quote, i.e. `a[""]`

**Actual behavior:**
* The closing bracket is added, but not the closing quote, i.e. `a["]`.

**Setup info:** Spyder 3.3.1, Python 3.6.6 (anaconda), running on Linux with KDE.

**Comment by bcolsen** [comment] 2019-01-28 17:04
more or less a Duplicate of #6827

**Closed** 2019-01-28 17:04 UTC
Labels: component:Editor, type:Bug
