### ISSUE TITLE
IPython console does not show up server returned message, but Python console does.

### ISSUE THREAD

**Issue by dfg445** [spyder-ide/spyder#5364] opened 2017-09-29 18:28 UTC
## Description of your problem
When I use pycurl package to upload files to our server at "http:// xxx.xx.xx.xxx/upload", the server will return a message about the upload status. This message will show up in Python console before the ">>>". A example of the message is: "{"message2":"OK","success":169406}>>> "

But this message never show up in the IPython console after version 3.2.

**What steps will reproduce the problem?**
The following code could reproduce the problem. The returning message from the server should be shown in the console after "c.perform()" executed.

c = pycurl.Curl()
c.setopt(c.URL, "http://xxx.xx.xx.xxx/upload")
c.setopt(c.POST, 1)
c.setopt(c.HTTPPOST, [('uploadedfile', (c.FORM_FILE, file_dir))])
c.setopt(pycurl.HTTPHEADER, ['Content-Type: multipart/form-data', 'Accept: application/json'])
c.perform()
c.close()

**What is the expected output? What do you see instead?**
Expect to see the server returned message such as "{"message2":"OK","success":169406}" in the console. The Python console before Spyder 3.2 could show this message, but the IPython console in any version will not shown the server returned message.

**Please provide any additional information below**
This issue involves in using pycurl package to upload files to server.

## Versions and main components

* Spyder Version: 3.2.3, 3.2.2, 3.2.1, 3.2.0 all have this issue
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Mac OS 10.12.6

## Dependencies

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-09-29 19:50
This is (most probably) a duplicate of issue #3777.

**Closed by ccordoba12** 2017-09-29 19:50 UTC
