### ISSUE TITLE
Static code analysis in Ubuntu throwing an error.

### ISSUE THREAD

**Issue by paragrastogi** [spyder-ide/spyder#5427] opened 2017-10-09 10:25 UTC
## Description

**What steps will reproduce the problem?**

1. I ran Static Code Analysis in Spyder 3.2.3 py36he38cbf7_1 . The problem occurs with any file.

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**What is the expected output? What do you see instead?**
Expected to see code analysis in the window - saw error popup instead.

**Please provide any additional information below**

KeyError: None

## Complete error message
[pasted from pop-up window]

---------------------------------------

> No config file found, using default configuration
> Traceback (most recent call last):
> File "/home/rasto/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
> File "/home/rasto/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 837, in _do_check
    for descr in self.expand_files(files_or_modules):
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 876, in expand_files
    self.add_message(key, args=message)
> File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/utils.py", line 386, in add_message
    self.stats['by_module'][self.current_name][msg_cat] += 1
> KeyError: None
---------------------------------

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by Jeroendevr** [comment] 2017-10-09 12:09
OS Windows 10
Spyder version 4.0.0 0d4f0a370
I can run a static code analysis on a file with and without code without any problem. So mabe a linux problem, Does it happen with different files?

**Comment by paragrastogi** [comment] 2017-10-09 13:27
Yes, the problem occurs for any file. I updated my original comment to include OS version. Thanks!

**Comment by ccordoba12** [comment] 2017-10-09 14:07
> Expected to see code analysis in the window - saw error popup instead.

Please post the entire error message.

**Comment by paragrastogi** [comment] 2017-10-09 14:14
Sorry, updated the original issue again. Thanks @ccordoba12 .

**Comment by ccordoba12** [comment] 2017-10-09 14:17
Thanks! It looks like an incompatibility with the latest Pylint.

Could you downgrade to Pylint 1.6.2 and try again?

**Comment by paragrastogi** [comment] 2017-10-09 14:48
Error persists @ccordoba12 . I couldn't go down to pylint-1.6.2 (didn't see it in my conda cache). Instead, I tried with pylint-1.6.4.

> No config file found, using default configuration
> Traceback (most recent call last):
> File "/home/rasto/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rasto/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/__main__.py", line 8, in <module>
    pylint.run_pylint()
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 1310, in __init__
    linter.check(args)
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 732, in check
    self._do_check(files_or_modules)
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 843, in _do_check
    for descr in self.expand_files(files_or_modules):
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/lint.py", line 884, in expand_files
    self.add_message(key, args=message)
  File "/home/rasto/miniconda3/lib/python3.6/site-packages/pylint/utils.py", line 415, in add_message
    self.stats['by_module'][self.current_name][msg_cat] += 1
KeyError: None

**Comment by csabella** [comment] 2017-10-09 20:28
I run Ubuntu 16.04 too and I can't recreate this issue.  However, I was having other problems with conda, so I uninstalled it, then reinstalled it and that fixed my other issue.  So you may want to remove miniconda and reinstall the newest version and see if that helps.  If it doesn't work for you, then I can try to install miniconda and see if it's a difference between the 2 versions.

**Comment by paragrastogi** [comment] 2017-10-09 21:28
Thanks for your input @csabella . Re-installing miniconda might be too drastic right now since I'm on a deadline. I tried to reinstall spyder and pylint though, but the error persists.

**Comment by ccordoba12** [comment] 2017-11-06 16:53
This is a duplicate of issue #5640 and it was already fixed. It'll be part of our 3.2.5 version.

**Closed by ccordoba12** 2017-11-06 16:53 UTC
Labels: component:Pylint, type:Bug
