### ISSUE TITLE
Indentation errors for fuction calls with `#` in a string

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#7377] opened 2018-07-02 18:20 UTC
Using Spyder 3.2.8 and reset to default settings.
Running on Xubuntu 18.04.

Situation: For an on-line Physics course, I am creating Python code that has no control statements at all. Just straight down executable statements beginning in column 1.  Call it a fancy calculator.

I find, in this situation, that Spyder automatically indents when I enter a newline after a Python print statement.  Sample code follows.
```
# Weight on Earth
m = 79 # kg
g = 9.8 # m/s^2
w = m * g # N
print("#1 w(Earth) =", w)
```
When I am positioned at the end of the print statement and press Enter, Spyder inserts a line immediately after the print line with exactly 6 spaces.  Since I had reset to default settings, the tab-indent uses 4 spaces so it doesn't seem to be a false tab.

**Comment by bcolsen** [comment] 2018-07-03 16:40
I can confirm this bug.

This line produces a a tab on the next line:
```python
print("#1 w(Earth) =", w)
```

While this line doesn't:

```python
print("1 w(Earth) =", w)
```

This erroneously produces an indent of 13 spaces on the next line:
```python
 print("1 wEarth) =", w)
```
It seem the indent code doesn't recognize strings and sees the `#` in the string a comment and misses the closing parentheses of the print function.

**Comment by texadactyl** [comment] 2018-07-03 17:06
Wow, that was an eye-opener. What a strange anomaly!  Thank you.  Omitting the '#' character inside the quoted-string of the print statement worked for me.  It never occurred to me that a '#' might be the cause.

But why exactly 6 spaces when my tab indent = 4?  Just curious.

I just coded print("#ABC") and the same thing happened.  Then, I began backspacing:
Backspace number 1 - one space removed
Backspace number 2 - one space removed
Backspace number 2 - 4 spaces removed i.e. positioned all the way left to 1st column

**Comment by bcolsen** [comment] 2018-07-03 17:21
@texadactyl  There is 6 indentations here because if you were to write a print function that continues over multiple lines the style guide(aka PEP8) states that the indentation should go the the beginning of the function on the previous line.  In this case `print(` is 6 characters.

Like this:
```python
my_function(this='that',
            what='the like',
            other='good')
```

I wouldn't worry about "style" too much if you're just starting out and writing small scripts, but once a project becomes large and has multiple authors then it's nice to have every one on the same page.

**Comment by texadactyl** [comment] 2018-07-04 01:23
Not just starting out.  My context where this occurs is in using Spyder as I described above.

**Comment by CAM-Gerlach** [comment] 2018-07-14 18:07
> I wouldn't worry about "style" too much if you're just starting out and writing small scripts, but once a project becomes large and has multiple authors then it's nice to have every one on the same page.

On the other hand, its much easier to start small with a best-practice, consistent style right from the get-go, then convert a large project after the fact. Right now, in Spyder's own codebase, anything older than a few years is a real mess style-wise (maybe PEP8 didn't exist back then or something?), but even if we had the spare time to go through 10,000s or 100,000s of lines of code and comments to fix it all, it would break every existing PR and be a nightmare to merge between ``3.x`` and ``master``. The earlier you start with good style, the easier it is to start doing, the more you are able to benefit from it, and the more you just get used to doing things the "right" way so it builds into your muscle memory and you don't even have to think about it any more.

**Closed** 2019-08-21 14:42 UTC
Labels: component:Editor, type:Bug
