### ISSUE TITLE
Help pane doesn't render Rich Text

### ISSUE THREAD

**Issue by KevinNadar** [spyder-ide/spyder#17771] opened 2022-04-27 03:12 UTC
### What steps will reproduce the problem?

The Help Pane doesn't render any documentation when set to display it in Rich Text. It can render it in plain text.

## Note

This line of text was displayed when I set to view the help pane in plain text
> Please consider installing Sphinx to get documentation rendered in rich text.

But according to the below mentioned **Dependencies**, a compatible version of `Sphinx` is already installed.

# Version info

* Spyder version: 5.1.5 None
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.17.4-2-cacule

# Dependencies

-  Mandatory:

| Package | Version |
| - | :-: |
| atomicwrites >=1.2.0 | 1.4.0 (OK) |
chardet >=2.0.0               |  4.0.0 (OK)
cloudpickle >=0.5.0           |  2.0.0 (OK)
cookiecutter >=1.6.0          |  1.7.3 (OK)
diff_match_patch >=20181111   |  20200713 (OK)
intervaltree >=3.0.2          |  3.1.0 (OK)
IPython >=7.6.0               |  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         | 0.18.1 (OK)
jsonschema >=3.2.0            |  4.4.0 (OK)
keyring >=17.0.0              |  23.4.0 (OK)
nbconvert >=4.0               |  6.4.4 (OK)
numpydoc >=0.6.0              |  1.2 (OK)
parso >=0.7.0;<0.9.0          |  0.8.3 (OK)
pexpect >=4.4.0               |  4.8.0 (OK)
pickleshare >=0.4             |  0.7.5 (OK)
psutil >=5.3                  |  5.8.0 (OK)
pygments >=2.0                |  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        |  2.9.6 (OK)
pyls_spyder >=0.4.0           |  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          |  1.2.4 (OK)
pylsp_black >=1.0.0           |  None (OK)
qdarkstyle =3.0.2             |  3.0.2 (OK)
qstylizer >=0.1.10            |  0.1.10 (OK)
qtawesome >=1.0.2             |  1.0.3 (OK)
qtconsole >=5.1.0             | 5.3.0 (OK)
qtpy >=1.5.0                  |  2.0.1 (OK)
rtree >=0.9.7                 |  0.9.7 (OK)
setuptools >=49.6.0           |  61.2.0 (OK)
sphinx >=0.6.6                |  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 |  2.1.3 (OK)
textdistance >=4.2.0          |  4.2.1 (OK)
three_merge >=0.1.1           |  0.1.1 (OK)
watchdog >=0.10.3             |  2.1.6 (OK)
xdg >=0.26                    |  0.27 (OK)
zmq >=17                      |  22.3.0 (OK)

-  Optional:

| Package | Version | 
| - | :-: |
cython >=0.21                 |  0.29.28 (OK)
matplotlib >=2.0.0            |  3.5.1 (OK)
numpy >=1.7                   |  1.21.5 (OK)
pandas >=1.1.1                |  1.4.2 (OK)
scipy >=0.17.0                |  1.7.3 (OK)
sympy >=0.7.3                 |  1.10.1 (OK)

**Comment by ccordoba12** [comment] 2022-04-27 14:51
Hey @KevinNadarm thanks for reporting. This is a duplicate of issue #17751 and it's probably introduced by and incompatibility between our code and the latest Sphinx.

So, please downgrade Sphinx for now until you find that the problem is solved for now. We'll try to fix this in our next version (5.3.1), to be released in mid May.

**Closed by ccordoba12** 2022-04-27 14:51 UTC
