### ISSUE TITLE
Request: function arguments colors

### ISSUE THREAD

**Issue by Amged-Elsheikh** [spyder-ide/spyder#11891] opened 2020-03-20 03:03 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Is it possible to change the colors of function argument when they are called, to make reading of the code easier?

Example

![Screenshot (18)](https://user-images.githubusercontent.com/62318395/77132425-cc1e3780-6aa2-11ea-8070-2e654019c90e.png)

VS

![Screenshot (19)](https://user-images.githubusercontent.com/62318395/77132438-d6d8cc80-6aa2-11ea-935d-51f5411cf134.png)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-03-20 14:00
Duplicate of #2172

**Comment by ccordoba12** [comment] 2020-03-20 14:00
We'll try to implement this for Spyder 5, to be released next year.

**Closed by ccordoba12** 2020-03-20 14:00 UTC
