### ISSUE TITLE
QtWebEngine Error on startup (macOS)

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#8819] opened 2019-02-21 07:54 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Reset preferences with ``spyder --reset``

## Problem Description
On a clean install with pip, Spyder won't start. The final error is
```
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```
This seems to be related to #8747. However, I did install `pip install pyqtwebengine` which does not fix the error for me. 

### What steps reproduce the problem?

1. Clean python install
2. `pip install spyder`
3. `spyder3`

### What is the expected output? What do you see instead?
Spyder should start, error see traceback below

### Paste Traceback/Error Below (if applicable)

```python-traceback

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/spyder3", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spyder/app/start.py", line 178, in main
    from spyder.app import mainwindow
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.2
* Qt version: ?
* PyQt version: 5.12 
* Operating System name/version: macOS 10.14.x

**Comment by ccordoba12** [comment] 2019-02-21 10:03
Duplicate of #8747. It'll be fixed in 3.3.4

**Closed by ccordoba12** 2019-02-21 10:03 UTC
