### ISSUE TITLE
Icon colors

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2908] opened 2016-01-07 09:52 UTC
I activated the spyder3 theme for icons. The unification of all the icons is really great, but some lack of colors make it harder to grasp the information conveyed by the icon rapidely. Examples:

* The icon indicating an error in the line in the editor margin should be red, not black
* The icons for both private and public methods in the Outline are both round, white on green. It's harder to distinguish between the to with a quick glance. Also the icon for private methods looks like a green no entry sign, that's disturbing. The hyphen could be at least a bit to the bottom so that it looks more like an underscore.
* The stop icon on consoles could be redish
* The parameter icons could be dark grey instead of full black
* TODO checkmarks in the margins have the same orange as the warning icon. The blue of the old icons was good.
* Quit icon should be red
* A propos should be blue (the `i`)
* Documentation should be red (the buoy)
* the rotation arrow for reboot is usually blue

The main point is that color conveys lots information in addition to the shape. Some color are more or less standard, and reusing these standard colors help finding the correct entry quickly. Too many icons are plain black by default: each one look great, but as a whole there's just black everywhere. Nothing looks more like a round icon than another round icon :)

**Comment by ccordoba12** [comment] 2016-01-08 21:41
Closing as a duplicate of issue #2490. @Nodd, i moved your comment there.

**Closed by ccordoba12** 2016-01-08 21:41 UTC
Labels: Duplicate, Enhancement, UI

**Comment by Nodd** [comment] 2016-01-08 22:34
You're right, thanks.
