### ISSUE TITLE
Terminal error in Spyder 3.2.3

### ISSUE THREAD

**Issue by pgsg00** [spyder-ide/spyder#5440] opened 2017-10-11 02:51 UTC
## Description

**What steps will reproduce the problem?**

1. Create a new terminal window in Spyder

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/x/anaconda/lib/python2.7/site-packages/spyder_terminal/terminalplugin.py", line 315, in create_new_term
    font=font.family())
  File "/Users/x/anaconda/lib/python2.7/site-packages/spyder_terminal/widgets/terminalgui.py", line 63, in __init__
    self.view = TermView(self, term_url=url, handler=self.handler)
  File "/Users/x/anaconda/lib/python2.7/site-packages/spyder_terminal/widgets/terminalgui.py", line 147, in __init__
    self.document.profile().clearHttpCache()
AttributeError: 'QWebEngineProfile' object has no attribute 'clearHttpCache'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.2.0 (NOK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
psutil >=0.3      :  5.3.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-10-11 16:08
Thanks for reporting. This is a duplicate of issue spyder-ide/spyder-terminal#114.

**Closed by ccordoba12** 2017-10-11 16:08 UTC

**Comment by sanjeethboddi** [comment] 2017-10-16 17:46
can you say how to use  terminal from spyder
