### ISSUE TITLE
I cannot save array as numpy files

### ISSUE THREAD

**Issue by IlariaFichera** [spyder-ide/spyder#22121] opened 2024-05-24 12:02 UTC
### What steps will reproduce the problem?

I run the simulation, then the variable appear on the variable explorer, I select one variable and I try to open it. It does tell me that the variable is too big to open and that an error encountered. However, the variable is only of shape (79,24000) and therefore not too big. 
In addition if I try to save this variable in a npy file, it doe give me that spyder has encountered a problem.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 105, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder_kernels\comms\commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 224, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder_kernels\comms\commbase.py", line 435, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 246, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 283, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'4de814b0a3d24b128f1b62328d32c750': (True, None), '578385719292469cb196c5b9b2db6237': (True, None), 'ebe8418bab8141b886256a05b0a32064': (True, None), '54db4ddebafe4daaa050b74676f88713': (True, None), 'e385ab1402b143bab01cabf6682c2410': (True, None), 'fff9fdc854d64f6fb78183024d949932': (True, None), '9c48237ca740451d800b7d07d089847e': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 576, in save_array
    self._current_editor.save_array()
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\widgets\collectionseditor.py", line 1199, in save_array
    data = self.delegate.get_value(self.currentIndex())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\widgets\collectionseditor.py", line 1553, in get_value
    return self.parent().get_value(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\widgets\collectionseditor.py", line 1612, in get_value
    value = self.shellwidget.get_value(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20225533\Anaconda3\envs\diff_enviornm\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 107, in get_value
    raise ValueError(msg % reason_big)
ValueError: <br><i>The variable is too big to be retrieved.</i><br><br><br><b>Note</b>: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.5.4  (conda)
* Python version: 3.12.1 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.21.1 (OK)
keyring >=17.0.0                 :  24.3.0 (OK)
nbconvert >=4.0                  :  7.14.2 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
paramiko >=2.4.0                 :  3.4.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=3.1,<4                  :  3.2.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  69.0.3 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.1,<2.6.0    :  2.5.1 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.2 (OK)
numpy >=1.7                      :  1.26.3 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2024-10-02 16:47
Hey @IlariaFichera, thanks for reporting and sorry for not paying attention to your problem before (we were quite busy trying to finish Spyder 6.0).

This is basically a duplicate of issue #12913, which we'll try to fix it in a future version (probably 6.0.3 or 6.0.4).

**Closed by ccordoba12** 2024-10-02 16:47 UTC
