### ISSUE TITLE
resetting views

### ISSUE THREAD

**Issue by robsomething** [spyder-ide/spyder#8812] opened 2019-02-20 17:48 UTC
### What steps will reproduce the problem?

No idea.  I clicked the window title and some of my windows got rearranged.  When I clicked on windows layout to reset them it crashed.

### Traceback
```python-traceback
TypeError: _start_server() missing 1 required positional argument: 'port'
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.11.0     :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by bcolsen** [comment] 2019-02-21 06:51
This bug is fixed in the current development master version and the latest release 3.2.3.

Closing as duplicate of #7721

**Closed by bcolsen** 2019-02-21 06:51 UTC
