### ISSUE TITLE
IPython console breaks after python file run.

### ISSUE THREAD

**Issue by foul-ole-ron** [spyder-ide/spyder#5319] opened 2017-09-22 18:25 UTC
## Description

**What steps will reproduce the problem?**

1. Run Python file (F5)
2. After (1), any action in the IPython console will trigger this
3. 

**What is the expected output? What do you see instead?**
Output is as expected, except for the error screen (which has a button directing me to this error fom)

**Please provide any additional information below**
This behaviour started after installing 3.2.3.

  File "/home/marc/tf/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/marc/tf/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 220, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "/home/marc/tf/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 351, in handle_exec_method
    view = ast.literal_eval(literal)
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 62, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.5/ast.py", line 61, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.5/ast.py", line 62, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.5/ast.py", line 61, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x7f9064efa978>

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-22 21:39
Please post the Python file that you're running so we can reproduce this on our side.

**Comment by foul-ole-ron** [comment] 2017-09-23 12:53
It seems to have to do with the path library (attached, rename .txt to .py).
A minimal script using path that crashes the console is:

from path import path
if __name__ == "__main__":
    logdir = path('~')

[path.txt](https://github.com/spyder-ide/spyder/files/1326549/path.txt)

**Comment by ccordoba12** [comment] 2017-09-23 15:00
Thanks a lot for posting this! We'll take a look at it for 3.2.4

**Comment by ccordoba12** [comment] 2017-11-01 23:05
Closing as a duplicate of #5636.

**Closed by ccordoba12** 2017-11-01 23:05 UTC
Labels: component:IPython Console, type:Bug
