### ISSUE TITLE
spyder_kernels version problem.

### ISSUE THREAD

**Issue by gvizkelethy** [spyder-ide/spyder#15119] opened 2021-04-05 17:51 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I have just installed Spyder 5 and I am getting the following warning at every startup:

_**You have missing dependencies!

# Mandatory:
spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)

Please install them to avoid this message.**_

I have the rigt version (2.0.1) which is >= 2.0.1 and < 2.1.0 and spyder still complains. I guess in the code there is a > instead of >=.

**Comment by ccordoba12** [comment] 2021-04-05 18:01
Hey @gvizkelethy, thanks for reporting. This is a duplicate of issue #15091 and we'll fix it in our next version, to be released later today.

**Closed by ccordoba12** 2021-04-05 18:01 UTC
