### ISSUE TITLE
problems about sys.stdin.read() in ipython console

### ISSUE THREAD

**Issue by DuanYuFi** [spyder-ide/spyder#16990] opened 2021-12-09 15:57 UTC
## Problem Description
These days I am trying to write a remote shell with python. I used winpwn module, which based on threading and standard io. Now I want to improve these things and found a quesion:

`sys.stdin.read() is unavaliable in IPython Console.`

this problem might relate to another quesion:

`Unsupported operation sys.stdout.fileno() in IPython Console`

because of these questions, I cannot use standard io by os.read or os.write in IPython Console, which is meaningful to my continued work

Now I am using Spyder 5.1.5 | Python 3.9.7 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10 | IPython 7.29.0

I tried the same operations above in pycharm's IPython Console (7.29.0), and it all work in pycharm.

### What steps reproduce the problem?

1. import sys and input "sys.stdin.read()"
2. input "sys.stdout.fileno()"

### What is the expected output? What do you see instead?

1. it should be like input function but I got flash and no input.
2. it should return an integer about file descriptor (1 if stdout) according to pycharm but I got Exception.

### Paste Traceback/Error Below (if applicable)

```python-traceback
import sys

sys.stdin.read()
Out[2]: ''

```

```python-traceback
In [3]: sys.stdout.fileno()
Traceback (most recent call last):

  File "C:\Users\10310\AppData\Local\Temp/ipykernel_24744/2810973561.py", line 1, in <module>
    sys.stdout.fileno()

  File "C:\Users\10310\anaconda3\lib\site-packages\ipykernel\iostream.py", line 308, in fileno
    raise io.UnsupportedOperation("fileno")

UnsupportedOperation: fileno
```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by dalthviz** [comment] 2021-12-09 18:25
Hi @DuanYuFi thank you for the feedback! I'm not totally sure what could be happening but I was able to reproduce this :+1:

Pinging @ccordoba12 and @impact27 (maybe they could have ideas about what is happening here)

**Comment by impact27** [comment] 2021-12-09 18:37
I think this has to do with the ipykernel redefining stdin and stdout so they can be sent over the network. I therefore wouldn’t expect to have a fileno. I would recommend to run your code in python directly if you want to develop a console application, or to use the input function.

**Comment by ccordoba12** [comment] 2021-12-09 18:50
> I would recommend to run your code in python directly if you want to develop a console application, or to use the input function.

I agree with @impact27. It's not possible to develop a console app using our IPython console. The only way would be going to the menu

    Run > Configuration per file

and selecting there the option called

    Execute in an external system terminal

**Comment by ccordoba12** [comment] 2021-12-09 18:51
I'm going to close this as "Won't fix" because there's nothing else we can do about this, sorry.

**Closed by ccordoba12** 2021-12-09 18:51 UTC
Labels: type:Bug, component:IPython Console, resolution:Wontfix, status:Reproduced

**Comment by DuanYuFi** [comment] 2021-12-10 00:02
Thankyou guys for generousing helps! I will take deep considerations about them.

**Comment by DuanYuFi** [comment] 2021-12-10 01:03
> > I would recommend to run your code in python directly if you want to develop a console application, or to use the input function.
> 
> I agree with @impact27. It's not possible to develop a console app using our IPython console. The only way would be going to the menu
> 
> ```
> Run > Configuration per file
> ```
> 
> and selecting there the option called
> 
> ```
> Execute in an external system terminal
> ```

Hi ccordoba12, it is a nice solution to my demand. Thanks!
