### ISSUE TITLE
Anaconda with spyder problem

### ISSUE THREAD

**Issue by praveenkumarchandaliya** [spyder-ide/spyder#6880] opened 2018-04-01 16:38 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/client.py", line 259, in stop_button_click_handler
    self.interrupt_kernel()
  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/client.py", line 448, in interrupt_kernel
    self.shellwidget.request_interrupt_kernel()
  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 345, in request_interrupt_kernel
    self.interrupt_kernel()
  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 638, in interrupt_kernel
    self.kernel_manager.interrupt_kernel()
  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/site-packages/jupyter_client/manager.py", line 421, in interrupt_kernel
    self.signal_kernel(signal.SIGINT)
  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/site-packages/jupyter_client/manager.py", line 446, in signal_kernel
    self.kernel.send_signal(signum)
  File "/home/praveen/anaconda3/envs/tensorflow/lib/python2.7/subprocess.py", line 1247, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
WARNING:traitlets:kernel died: 18.0165879726

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2018-04-01 16:42
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

Finally, please update Qt/PyQt to their latest versions to see if that helps.

**Comment by CAM-Gerlach** [comment] 2018-04-10 23:39
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-04-10 23:39 UTC
Labels: status:Awaiting Followup
