### ISSUE TITLE
Dark theme doesn't work with variable explorer

### ISSUE THREAD

**Issue by EulerFaria** [spyder-ide/spyder#5671] opened 2017-11-06 08:59 UTC
## Description

**What steps will reproduce the problem?**

1. Change to dark theme
2. 
3. 

**What is the expected output? What do you see instead?**
Expected to see full layout in the dark theme, but only the editor and the Ipython console change themes. 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-11-06 14:41
Thanks for reporting. This is a duplicate of #2350.

**Closed by ccordoba12** 2017-11-06 14:41 UTC
