### ISSUE TITLE
ImportError: cannot import name 'ensure_future'

### ISSUE THREAD

**Issue by Starichokrz** [spyder-ide/spyder#11964] opened 2020-03-24 20:16 UTC
### What steps will reproduce the problem?

1) When run Spyder4, I get ImportError: cannot import name 'ensure_future' from Console 

### Traceback
```python-traceback
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/base.py", line 331, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 207, in toggle_view
    self.create_new_client(give_focus=False)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 703, in create_new_client
    self.register_client(client)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 918, in register_client
    shellwidget.set_cwd(cwd_path)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 45.04406476020813
Traceback (most recent call last):
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 547, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 45.01566171646118
Traceback (most recent call last):
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 569, in update_path
    shell.update_syspath(path_dict, new_path_dict)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 223, in update_syspath
    blocking=False).update_syspath(path_dict, new_path_dict)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/home/octopus/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.6.9
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.0-42-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.16.0 (NOK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.6.2 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-03-25 00:12
Duplicate of #11889

**Closed by ccordoba12** 2020-03-25 00:12 UTC
