### ISSUE TITLE
Spyder Help Tab Crash

### ISSUE THREAD

**Issue by DominicAntonacci** [spyder-ide/spyder#5951] opened 2017-12-10 20:45 UTC
## Description of your problem
Spyder crashes (segmentation fault) when trying to automatically display the help documentation for plt.plot() when typed in the console.

**What steps will reproduce the problem?**

1. Open a fresh Spyder. Ensure the the help documentation is enabled for the iPython console (Tools -> Preferences -> Help -> Check IPython console.
2. In the IPython console type `import matplotlib.pyplot as plt`
3. Next, type `plt.plot(`

**What is the expected output? What do you see instead?**
I expect to see the plot documentation. Spyder instead crashes.

**Please provide any additional information below**
This seems to be something specific to changing the name of the import. The following example does not crash
`import matplotlib.pyplot`
`matplotlib.pyplot.plot(`

It does not trigger on all imports. The following example does not crash
```
import matplotlib.pyplot as plt
plt.figure()
```

It does not trigger in the editor.
## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3 64 bits
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Linux Mint 17.3 MATE

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-12-10 21:35
This is a duplicate of issue #5514 and it'll be fixed in our 3.2.5 version, to be released in the next few days.

**Closed by ccordoba12** 2017-12-10 21:35 UTC
