### ISSUE TITLE
Icon of standalone application on Big Sur is not displayed

### ISSUE THREAD

**Issue by Jacques2101** [spyder-ide/spyder#14464] opened 2020-12-19 10:04 UTC
Hi, 
I just installed Spyder as a standalone application and I have questions. 

- why in my launch bar (I am on macOS ) I don't have the Spyder icon by python one without picture (cf. picture) but it works 
<img width="139" alt="Capture d’écran 2020-12-19 à 10 52 15" src="https://user-images.githubusercontent.com/49912455/102686582-f1ce9d80-41e8-11eb-8a65-bd8ed3bc8683.png">

- How to install the extension notebook  ? I have it when I run Spyder from anaconda but not here. 
- is there code formatter in Spyder ? (it would be great - I ask because I am relatively new in Spyder)

Thx. 

## Versions
* Spyder version: 4.2
* Python version: 3.8.6
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: macOS big sur 

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.5.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  51.0.0 (OK)
sphinx >=0.6.6                  :  3.3.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  1.5.4 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-12-19 21:53
Hey @Jacques2101, thanks for reporting.

> why in my launch bar (I am on macOS ) I don't have the Spyder icon by python one without picture (cf. picture) but it works

I don't know why that's happening. @mrclary, any ideas about this problem? Are you seeing it in Catalina?

> How to install the extension notebook ? I have it when I run Spyder from anaconda but not here

That plugin is not included as part of the application because it's in beta state. We'll see if we can include it next year.

> is there code formatter in Spyder ? (it would be great - I ask because I am relatively new in Spyder)

Yes, it is. Please click on the menu `Source > Format file or selection with Autopep8`.

**Comment by mrclary** [comment] 2020-12-19 22:18
I don't know what could be happening. @Jacques2101, can you try updating to 4.2.1?

**Comment by Jacques2101** [comment] 2020-12-20 12:03
I updated to 4.2.1 but same result but it works fine except this strange problem !

**Comment by mrclary** [comment] 2021-01-20 20:30
I cannot reproduce this issue using Spyder 4.2.1 standalone release on macOS 11.1.

**Comment by ccordoba12** [comment] 2021-01-20 22:52
Closing then because we won't be able to fix this without a way to reproduce it.

**Closed by ccordoba12** 2021-01-20 22:52 UTC
Labels: OS:MacOS, tag:Installer, type:Bug
