### ISSUE TITLE
first startup, fresh install

### ISSUE THREAD

**Issue by digikwondo** [spyder-ide/spyder#20468] opened 2023-02-03 13:03 UTC
### What steps will reproduce the problem?

- first startup, fresh install. installed via pip on arch linux

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/spyder/plugins/application/container.py", line 331, in _check_updates_ready
    msg = header + content + footer
UnboundLocalError: local variable 'content' referenced before assignment
```

## Versions

* Spyder version: 5.4.1  (pip)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.8
* Operating System: Linux 5.15.88-2-lts

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1              :  8.9.0 (OK)
jedi >=0.17.2                 :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.1 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0                 :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.16.1 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0                 :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2            :  3.1 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0             :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.1.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=3.0.0            :  3.6.3 (OK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------------
abydos                        0.5.0
aiofiles                      22.1.0
aiohttp                       3.8.3
aiohttp-socks                 0.7.1
aiorpcX                       0.22.1
aiosignal                     1.3.1
aiosqlite                     0.18.0
alabaster                     0.7.13
anaconda                      0.0.1.1
anyio                         3.6.2
anytree                       2.8.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.1
asttokens                     2.2.1
async-generator               1.10
async-timeout                 4.0.2
atomicwrites                  1.4.1
attrs                         22.2.0
autocommand                   2.2.2
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
beautifulsoup4                4.11.2
binaryornot                   0.4.4
bitstring                     4.0.1
black                         23.1.0
bleach                        6.0.0
breezy                        3.3.2
Brlapi                        0.8.4
btrfsutil                     6.1.3
certifi                       2022.12.7
cffi                          1.15.1
chardet                       5.1.0
charset-normalizer            3.0.1
click                         8.1.3
cloudpickle                   2.2.1
colorama                      0.4.6
comm                          0.1.2
ConfigArgParse                1.5.3
configobj                     5.1.0.dev0
construct                     2.10.68
contourpy                     1.0.7
cookiecutter                  2.1.1
cryptography                  39.0.0
cssselect                     1.2.0
cycler                        0.11.0
Cython                        0.29.33
debugpy                       1.6.6
decorator                     5.1.1
defusedxml                    0.7.1
deprecation                   2.1.0
diff-match-patch              20200713
dill                          0.3.6
distlib                       0.3.6
dnspython                     2.3.0
docstring-to-markdown         0.11
docutils                      0.19
dulwich                       0.21.2
ecdsa                         0.18.0
entrypoints                   0.4
eventlet                      0.33.3
executing                     1.2.0
fastbencode                   0.1
fastimport                    0.9.14
fastjsonschema                2.16.2
filelock                      3.9.0
flake8                        6.0.0
fonttools                     4.38.0
fqdn                          1.5.1
frozenlist                    1.3.3
future                        0.18.3
gevent                        22.10.2
greenlet                      2.0.2
guake                         3.9.1.dev0
gunicorn                      20.1.0
helpdev                       0.7.1
html5lib                      1.1
httplib2                      0.21.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
inflect                       6.0.2
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.21.1
ipython                       8.9.0
ipython-genutils              0.2.0
isodate                       0.6.1
isoduration                   20.11.0
isort                         5.12.0
jaraco.classes                3.2.3
jaraco.context                4.3.0
jaraco.functools              3.5.2
jaraco.text                   3.11.1
jarowinkler                   1.2.3
jedi                          0.18.2
jeepney                       0.8.0
jellyfish                     0.9.1
Jinja2                        3.1.2
jinja2-time                   0.2.0
json5                         0.9.12
jsonpointer                   2.3
jsonrpclib-pelix              0.4.3.2
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.2.0
jupyter-events                0.5.0
jupyter_packaging             0.12.3
jupyter_server                2.2.1
jupyter_server_fileid         0.6.0
jupyter_server_terminals      0.4.4
jupyter_server_ydoc           0.7.0
jupyter-ydoc                  0.3.1
jupyterlab-pygments           0.2.2
jupyterlab_server             2.19.0
keyring                       23.13.1
kiwisolver                    1.4.4
lazy-object-proxy             1.9.0
lensfun                       0.3.3
Levenshtein                   0.20.9
libfdt                        1.6.1
lit                           16.0.0rc1
louis                         3.24.0
lxml                          4.9.2
Markdown                      3.4.1
markdown-it-py                2.1.0
MarkupSafe                    2.1.2
matplotlib                    3.6.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
merge3                        0.0.12
meson                         1.0.0
mistune                       2.0.4
mock                          5.0.1
monotonic                     1.6
more-itertools                9.0.0
multidict                     6.0.4
mypy-extensions               0.4.3
nbclient                      0.7.2
nbconvert                     7.2.9
nbformat                      5.7.3
ndg-httpsclient               0.5.1
nest-asyncio                  1.5.6
netsnmp-python                1.0a1
notebook_shim                 0.2.2
numpy                         1.24.1
numpydoc                      1.5.0
ordered-set                   4.1.0
packaging                     23.0
pandas                        1.5.3
pandocfilters                 1.5.0
parsedatetime                 2.6
parso                         0.8.3
pathspec                      0.11.0
patiencediff                  0.2.12
pbkdf2                        1.3
pbr                           5.11.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           22.3.1
platformdirs                  2.6.2
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.16.0
prompt-toolkit                3.0.36
protobuf                      4.21.12
psutil                        5.9.4
ptyprocess                    0.7.0
pure-eval                     0.2.2
pwquality                     1.4.5
pyaes                         1.6.1
pyasn1                        0.4.8
pybind11                      2.10.3
pycairo                       1.23.0
pycodestyle                   2.10.0
pycparser                     2.21
pycryptodome                  3.17
pycryptodomex                 3.17
pydantic                      1.10.4
pydocstyle                    6.2.3
pyflakes                      3.0.1
Pygments                      2.14.0
PyGObject                     3.42.2
pykeepass                     4.0.3
pyliblo                       0.10.0
pylint                        2.16.1
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
pyOpenSSL                     23.0.0
pyotp                         2.8.0
pyparsing                     3.0.9
pypng                         0.20220715.0
PyQt5                         5.15.8
PyQt5-sip                     12.11.1
PyQtWebEngine                 5.15.6
pyRFC3339                     1.1
pyrsistent                    0.19.3
PySide2                       5.15.8
PySocks                       1.7.1
python-augeas                 1.1.0
python-dateutil               2.8.2
python-json-logger            2.0.4
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.1
python-slugify                8.0.0
python-socks                  2.1.1
python-xlib                   0.33
pythondialog                  3.5.3
pytoolconfig                  1.2.5
pytz                          2022.7.1
pyxDamerauLevenshtein         1.7.1
pyxdg                         0.28
PyYAML                        6.0
pyzmq                         25.0.0
QDarkStyle                    3.1
qrcode                        7.4.1
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.0
QtPy                          2.3.0
ranger-fm                     1.9.3
rapidfuzz                     2.13.7
rdflib                        6.2.0
Reflector                     2021.11.20.2.41.3
requests                      2.28.2
requests-unixsocket           0.3.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.3.1
rope                          1.7.0
Rtree                         1.0.1
SecretStorage                 3.3.3
Send2Trash                    1.8.0
setproctitle                  1.3.2
setuptools                    67.1.0
shiboken2                     5.15.8
simplejson                    3.18.1
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soundconverter                4.0.3
soupsieve                     2.3.2.post1
Sphinx                        6.1.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.1
spyder-kernels                2.4.2
stack-data                    0.6.2
tbb                           2021.8.0
team                          1.0
terminado                     0.17.1
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.6
tornado                       6.2
traitlets                     5.9.0
trove-classifiers             2023.1.20
typing_extensions             4.4.0
uc-micro-py                   1.0.1
ufw                           0.36.1
ujson                         5.7.0
uri-template                  1.2.0
urllib3                       1.26.14
validate                      5.1.0.dev0
validate-pyproject            0.12.1
validators                    0.20.0
virtualenv                    20.17.1
watchdog                      2.2.1
wcwidth                       0.2.6
webcolors                     1.12
webencodings                  0.5.1
websocket-client              1.5.0
websockets                    10.4
Werkzeug                      2.2.2
whatthepatch                  1.0.4
wheel                         0.38.4
wrapt                         1.14.1
wurlitzer                     3.0.3
y-py                          0.5.5
yapf                          0.32.0
yarl                          1.8.2
youtube-dl                    2021.12.17
ypy-websocket                 0.8.2
zipp                          3.12.0
zope.component                5.1.0
zope.deferredimport           4.4
zope.deprecation              4.4.0
zope.event                    4.6
zope.hookable                 5.4
zope.interface                5.5.2
zope.proxy                    5.0.0
zxcvbn                        4.4.28

```
</details>

**Comment by ccordoba12** [comment] 2023-02-03 15:45
Hey @digikwondo, thanks for reporting. This is a duplicate of issue #20406. You can find there a workaround until we have time to fix this problem in our next version (5.4.2), to be released in March.

**Closed by ccordoba12** 2023-02-03 15:45 UTC
