### ISSUE TITLE
Spyder extremely slow after mojave update and latest conda installation

### ISSUE THREAD

**Issue by jayavenkat** [spyder-ide/spyder#8675] opened 2019-01-31 16:02 UTC
### Issue Report Checklist

* [yes ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ yes] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [yes ] Restarted Spyder
    * [ yes] Reset preferences with ``spyder --reset``
    * [ yes] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi, 
I recently updated to mojave and re-installed the latest version of anaconda. Spyder console is extremely slow and hangs several times even when I do something simple like print('hello')

Conda version: 4.6.1
spyder : 3.3.2
python : 3.7.2
numpy : 1.15.4
matplotlib : 3.0.2
scipy : 1.2.0
cython: 0.29.2

### What steps reproduce the problem?

1. Restarting spyder several times
2. uninstalling and reinstalling anaconda
3. 

### What is the expected output? What do you see instead?

The expected output is sometimes not printed. It is sometimes printed after hitting enter several times.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.2
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Mac OS Mojave 10.14.3

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2019-01-31 16:05
This is a duplicate of issue #2902. Please see there for possible solutions.

**Closed by ccordoba12** 2019-01-31 16:05 UTC
