### ISSUE TITLE
"An error ocurred while starting the kernel" when opening Spyder

### ISSUE THREAD

**Issue by Lawrenzz** [spyder-ide/spyder#5154] opened 2017-09-07 08:26 UTC
## Description

Spyder crashes when i opened a new ipython console within the software. However it did work when i opened it for the first time.

  File "C:\Users\lawre\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 884, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "C:\Users\lawre\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 930, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "C:\Users\lawre\Anaconda2\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Users\lawre\Anaconda2\lib\site-packages\qtconsole\console_widget.py", line 632, in execute
    self._execute(source, hidden)
  File "C:\Users\lawre\Anaconda2\lib\site-packages\qtconsole\frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6

**Comment by ccordoba12** [comment] 2017-09-07 15:46
Please post a screenshot of how the console looks when this error appears for you.

**Comment by marcelotduarte** [comment] 2017-09-09 21:13
## Description
Creating project do the same.

**Please provide any additional information below**

  File "s:\workspace\venv\spyder\lib\site-packages\spyder\plugins\ipythonconsole.py", line 898, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "s:\workspace\venv\spyder\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 112, in set_cwd
    self.silent_execute(code)
  File "s:\workspace\venv\spyder\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 274, in silent_execute
    self.kernel_client.execute(to_text_string(code), silent=True)
AttributeError: 'NoneType' object has no attribute 'execute'


## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.2
* Qt Versions: 5.8.0, PyQt5 5.8.2 on Windows

## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-13 22:32
Sorry, I don't know why this occurs but it's a duplicate of issue #5053.

**Closed by ccordoba12** 2017-09-13 22:32 UTC
