### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by A138824** [spyder-ide/spyder#5805] opened 2017-11-20 23:52 UTC
## Description

**What steps will reproduce the problem?**

1. Just upgraded from Spyder 3.1.2 to 3.2.4
2. Error pops up at startup as well as the first time I run a script by pressing F5
3. If I run the script again, the error message does not show up

**What is the expected output? What do you see instead?**
In the previous version of spyder, nothing like this happened

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
WARNING:traitlets:kernel died: 17.99892568588257

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-11-21 04:47
Thanks for reporting. This is duplicate of #5080.

**Closed by ccordoba12** 2017-11-21 04:47 UTC
