### ISSUE TITLE
Numpy array open issue

### ISSUE THREAD

**Issue by pancookie** [spyder-ide/spyder#8614] opened 2019-01-21 18:42 UTC
### What steps will reproduce the problem?

I am using pandas and numpy

pandas used to read information from csv file and then convert it into numpy array. The error occurs when I try to open the object (numpy array) in the Variable explorer

### Traceback
```python-traceback
  File "/Users/yxp8158/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/Users/yxp8158/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by bcolsen** [comment] 2019-01-22 17:11
Thanks for reporting. This is a duplicate of issue #8582.

**Closed by bcolsen** 2019-01-22 17:11 UTC
