### ISSUE TITLE
IPython doesn't reset matplotlib figures

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#4614] opened 2017-06-16 07:40 UTC
## Description

Hello, long time no see ! ;)

I'm trying to switch from the python console I loved so much to the IPython console. One problem I have is that clearing variables when I run a script does not close matplotlib figures. So if I run a script multiple time to debug it, the number of matplotlib windows keeps growing.
The best would be a true reset of the interpreter, but this operation is very slow with IPython.

I understand that you want to get rid of the python console, but right now I don't have a useful workflow without it. I want each run of my script to be completely independant.

**What steps will reproduce the problem?**

1. create a script:
```python
import matplotlib.pylot as plt
plt.figure()
plt.plot(range(10))
plt.show()
```
2. configure script as "run in current IPython console" and "clear variables on run"
3. use autobamick backend to get an external window
4. run script multiple times

**What is the expected output? What do you see instead?**
I expect to see a unique matplotlib window with my beautiful plot. Instead I see multiple windows.

**Please provide any additional information below**
It gets worse if `plt.figure()` is removed from the script: in that case the plots are all stacked in one figure.

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by goanpeca** [comment] 2017-06-16 15:38
@Nodd it will get fixed. We will add the open in new ipython interpreter that will start a barebones ipython console and then t should be faster and work as expected. @ccordoba12 is working on that

**Comment by ccordoba12** [comment] 2017-06-16 15:44
Hey, glad to see you!

As @goanpeca said, we will provide an option to execute in a dedicated IPython console and that will start a new (minimal) kernel every time. That will solve your problem ;-)

Closing as a duplicate of issue #4418.

**Closed by ccordoba12** 2017-06-16 15:44 UTC
