### ISSUE TITLE
i cannot type anything with my keyboard in spyder

### ISSUE THREAD

**Issue by superman97** [spyder-ide/spyder#4823] opened 2017-07-27 06:23 UTC
## Description

**What steps will reproduce the problem?**

1. i cannot type anything with my keyboard in spyder3.2.0
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-07-27 14:00
Are you using Spyder through SSH or VNC?

**Comment by superman97** [comment] 2017-07-28 01:13
Yes, I use VNC. Is there anything I can do to solve it?

**Comment by ccordoba12** [comment] 2017-07-28 02:44
This is duplicate of issue #3713. Please see the comments there for a possible answer.

Unfortunately, there's nothing we can about it on our side.

**Closed by ccordoba12** 2017-07-28 02:44 UTC
