### ISSUE TITLE
math in sphinxify has become huge

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#5597] opened 2017-10-28 22:30 UTC
Hello,

After some recent updates the formulas have become too big.

![image](https://user-images.githubusercontent.com/17322580/32139065-da986fb0-bc3f-11e7-8162-2dd06ae51ca8.png)

**Comment by ccordoba12** [comment] 2017-10-28 22:40
Please report all things we ask for in our issue template:

https://github.com/spyder-ide/spyder/blob/master/.github/ISSUE_TEMPLATE.md

Else, I'll simply close this issue for lack of info, sorry.

**Comment by kklmn** [comment] 2017-10-28 23:14
## Versions and main components

* Spyder Version:  3.2.3
* Python Version: 3.6.1 64-bit
* Qt Version: 5.8.0
* PyQt Version: 5.8.1
* Operating system: Windows 10 64-bit

**Comment by goanpeca** [comment] 2019-11-29 02:02
@dalthviz could you check if you can reproduce this issue?

**Comment by ccordoba12** [comment] 2019-11-29 04:21
This was probably caused by the old MathJax version we were using until some months ago. Now this should be fixed.

**Closed by ccordoba12** 2019-11-29 04:21 UTC
Labels: component:Help, type:Bug
