### ISSUE TITLE
autocompletition does not work within the editor, but its works in the console (Spyder 3 last version, Mac Sierra OS)

### ISSUE THREAD

**Issue by fuentelacasa** [spyder-ide/spyder#4328] opened 2017-04-05 15:31 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.2.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment] 2017-04-05 15:33
This is a duplicate of issue #2162. Please read the discussion there to understand what works and what not regarding auto-completion in the Editor.

**Closed by ccordoba12** 2017-04-05 15:33 UTC
