### ISSUE TITLE
Hi all

### ISSUE THREAD

**Issue by JuanCML** [spyder-ide/spyder#5615] opened 2017-10-30 18:20 UTC
## Description of your problem
Spyder crashes. I thought it was because my user name/profile in Windows had a space but after I rename my user/profile and install anaconda again I keep having the issue.
When I try to open a file spyder crashes
**What steps will reproduce the problem?**

1. File --> Open
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.2.4
* Python Version:3.6.3
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system:Windows 7

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-10-30 18:26
Thanks for reporting. This seems a duplicate of issue #3903, please see there for a solution to this problem.

**Closed by ccordoba12** 2017-10-30 18:26 UTC
