### ISSUE TITLE
Spyder does not support code-completion and does not show help since update to version 3.1.4

### ISSUE THREAD

**Issue by msgnaf** [spyder-ide/spyder#4476] opened 2017-05-15 08:41 UTC
## Description of your problem

I'm experiencing issues with the interactive help pane (View -> Panes -> Help). Before updating Anaconda I was able to show object documentation for any object pressing Ctrl+I (inspect current object). This was especially important for me since I also was able to see my own docstrings for my modules in this pane. I am also no more able to use code-completion (I checked that I use the correct keyboard-shortcut Ctrl+space).

**What steps will reproduce the problem?**

1. Simple code sample that was previously shown nicely formatted in the help pane when pressing Ctrl+I to inspect the function (with the cursor between the braces of test_fun() ):

       def test_fun():
           """This is my testfunction.
           
           Parameters:
               None
           Returns:
               ret : The return value.
                   str
           """
           ret = "MyTestFunction"
           return ret

**What is the expected output? What do you see instead?**

I expect the help pane to properly show me the docstring in a nice format. I also expect auto-completion when pressing Ctrl+Space. Current behaviour when pressing Ctrl+I to inspect an object: The help pane switches to a blank screen and the source dropdown switches to "Editor". Behavior when pressing Ctrl+Space when the cursor is behind a string like "test_fu": Nothing happens. There is also no dropdown for possible completions.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1 (Anaconda version 4.3.17)
* Qt Version: 5.6.2
* PyQt Version: PyQt5 5.6
* Operating system: Windows 7

## Dependencies

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-05-15 21:07
Thanks a lot for your report. This is essentially a duplicate of issue #4410.

**Closed by ccordoba12** 2017-05-15 21:07 UTC
