### ISSUE TITLE
Problem  auto-completion with OpenCV on Linux

### ISSUE THREAD

**Issue by andreperesnl** [spyder-ide/spyder#5914] opened 2017-12-07 17:03 UTC
## Description

Hi, I'm having trouble with Auto-completion and Opencv, when a press TAB or CTRL+SPACE Spyder sagest the auto-completion like the image below and not the function and constants of the module.

Problem seems to be restricted to the OpenCV, other modules (Numpy, matplotlib, etc...) works fine.

I'm using Linux Mint 18.3, Spyder and the dependencies were installed using pip3.

![image](https://user-images.githubusercontent.com/29657690/33727273-a92f8858-db5e-11e7-83d5-f3a0660b597e.png)

Thanks!!.
## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  3.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAMGerlach-Baron** [comment] 2017-12-07 19:33
Thanks for reporting. This is a known issue (duplicate of #4859 ), and unfortunately there's nothing Spyder can do about it, as not only is this the domain of the autocompletion libraries used by Spyder (`rope` and `jedi`), but is a specific issue related to the packaging of `opencv`. As the latter is distributed in binary form, there is no way for those libraries to infer the functions, methods etc. `opencv` exposes, so unfortunately this cannot be fixed except by `opencv`. Therefore, this issue can be closed.

**Closed** 2017-12-07 20:03 UTC

**Comment by andreperesnl** [comment] 2017-12-08 14:09
Hi, thanks for the response, however, I had recompiled opencv3 from sources, the problem persists, and in iPyhton(even the embedded one), the auto-complete works fine, I've tested Jedi in Spyder console and it also worked, returning the correct completions, you can see in the image below.

![image](https://user-images.githubusercontent.com/29657690/33769217-7ab4e790-dc10-11e7-8bac-ead6d7136f78.png)

Thanks!!

**Comment by CAMGerlach-Baron** [comment] 2017-12-08 17:59
Hmm, interesting. Thanks for investigating further. That's the same behavior (works in console but not editor) reported in the canonical issue as well, but seems if the source really is plain python (which may not actually be the case), it should work. However, there is probably some complexity with it I'm neglecting in my n00bishness. Other than that, it could still be trying to read the binary/compiled form of the package, or there is always a chance it involves an issue with the `pip` installer which is prone to misconfiguration (though probably its more likely to be one of the former, or something above my pay grade).

@ccordoba12 Expert opinion?
