### ISSUE TITLE
Create a python plugin that extends all core plugins with python functionality

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#12530] opened 2020-04-28 21:51 UTC
In order to correctly decouple widgets from its python only and python specific origins, we need to create a new plugin

`spyder/plugins/python/...` that will extend all plugins to provide specific functionality. By doing this we are going to become the consumers of the external API internally (keeping things consistent and tested) and we will also enable the possibility for Spyder 5 to extend Spyder to other languages.

Things this plugins must accomplish
- File explorer: Add python specific actions to menu
- Project explorer: Add python basic project
- Ipython console: Handle IPython Path
- Editor console: Handle Python specific extensions
- Variable Explorer: TBD

**Comment by ccordoba12** [comment] 2020-04-28 23:39
Duplicate of #12531

**Closed by ccordoba12** 2020-04-28 23:39 UTC
