### ISSUE TITLE
Changed colors of Notepad++ theme on Mac. Spyder menu goes unresponsive and encounters problem finally

### ISSUE THREAD

**Issue by Rayapur** [spyder-ide/spyder#11112] opened 2019-12-16 23:12 UTC
### What steps will reproduce the problem?

I have customized colors of Notepad++ theme and encountered issues. 

### Traceback
```python-traceback
  File "/Users/udayarayapur/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor/utils/autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "/Users/udayarayapur/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor/utils/autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "/Users/udayarayapur/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor/utils/autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: '/Users/udayarayapur/untitled0.py'
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.1.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-17 01:18
Duplicate of #11058

**Comment by ccordoba12** [comment] 2019-12-17 01:18
It'll be fixed in our next version.

**Closed by ccordoba12** 2019-12-17 01:18 UTC
