### ISSUE TITLE
Can't resize right-hand panel vertically

### ISSUE THREAD

**Issue by BlankAdventure** [spyder-ide/spyder#22586] opened 2024-09-26 20:05 UTC
### Problem Description: 

Can't resize history window larger vertically. Expected behavior is that I can pull it farther up to expose more history. Just observed this upon upgrading from 5.5.5.

See movie here:

https://github.com/user-attachments/assets/808df86a-912c-4e77-a31c-4347bf49f631

Notice the very restricted range of vertical sizing. This is very annoying as it severely limits the ability to see longer command histories, and/or resize to show larger plots when using the plots tab (the particular active tab does not change the behaviour).

## Versions
* Spyder version: 6.0.1
* Python version: 3.11
* Qt version: 5.15.2
* PyQt version: 5.15.10
* Operating System name/version: Windows 10

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                      :  3.9.3 (OK)
asyncssh >=2.14.0,<3.0.0             :  2.17.0 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.1 (OK)
cookiecutter >=1.6.0                 :  2.5.0 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
github >=2.3.0                       :  2.4.0 (OK)
importlib_metadata >=4.6.0           :  7.0.1 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1     :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  1.0.1 (OK)
jsonschema >=3.2.0                   :  4.19.2 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.10.0 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.15.1 (OK)
pylint >=3.1,<4                      :  3.3.1 (OK)
pylint_venv >=3.0.2                  :  3.0.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0               :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0           :  2.0.0 (OK)
pyuca >=1.2                          :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0            :  3.2.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0             :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0             :  5.6.0 (OK)
qtpy >=2.4.0                         :  2.4.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  68.2.2 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0        :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0               :  0.6.7 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
yarl >=1.9.4                         :  1.12.1 (OK)
zmq >=24.0.0                         :  25.1.2 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  3.8.0 (OK)
numpy >=1.7                          :  1.24.4 (OK)
pandas >=1.1.1                       :  1.5.3 (OK)
scipy >=0.17.0                       :  1.11.4 (OK)
sympy >=0.7.3                        :  1.12 (OK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.6.1 :  0.6.1 (OK)

```

**Comment by ccordoba12** [comment] 2024-09-27 01:06
Hey @BlankAdventure, thanks for reporting. This is basically a duplicate of of issue #21197, so I'm going to close it in favor of that one.

The problem is that the message shown in the Debugger, Plots and Find when they are empty prevents the Variable Explorer to be resized because they have a minimum height that is fairly big.

We'll solve this in 6.1.0, to be released in six months or so, because it requires changes to our API. In the meantime you can hide those other panes to avoid this.

**Closed by ccordoba12** 2024-09-27 01:06 UTC
