### ISSUE TITLE
preference fail

### ISSUE THREAD

**Issue by Liq-sup** [spyder-ide/spyder#10390] opened 2019-10-13 05:13 UTC
### What steps will reproduce the problem?

click into preference and change the theme, it fails

### Traceback
```python-traceback
  File "/Users/liq/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 2741, in edit_preferences
    widget.initialize()
  File "/Users/liq/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 78, in initialize
    self.setup_page()
  File "/Users/liq/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1244, in setup_page
    self.scheme_editor_dialog.add_color_scheme_stack(name, custom=True)
  File "/Users/liq/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1571, in add_color_scheme_stack
    value = self.parent.get_option(option)
  File "/Users/liq/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 57, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/Users/liq/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 375, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'custom-0/normal' in section: 'color_schemes'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-10-14 01:36
Thanks for reporting. This is a duplicate of issue #5790.

**Closed by ccordoba12** 2019-10-14 01:36 UTC
