### ISSUE TITLE
The code editor is very slowly responsive

### ISSUE THREAD

**Issue by rgcucu** [spyder-ide/spyder#16032] opened 2021-07-16 14:30 UTC
### What steps will reproduce the problem?

1) Open the spyder editor window;
2) Type code.

The editor window updates very slowly.

**Comment by juanis2112** [comment] 2021-07-16 22:00
Hello @rgcucu can you provide information about your OS and the version of Spyder you are using? Please fill the template we provide for our issues so that we can help you.

**Comment by ccordoba12** [comment] 2021-07-19 01:43
This is a duplicate of issue #15631. Please read it for the different things you can do to improve performance for now.

**Closed by ccordoba12** 2021-07-19 01:43 UTC
Labels: status:Awaiting Followup
