### ISSUE TITLE
Spyder has encountered a problem when trying to open Preferences

### ISSUE THREAD

**Issue by anstragal** [spyder-ide/spyder#5138] opened 2017-09-05 17:16 UTC
## Description

**What steps will reproduce the problem?**

1. Try to open Preferences from Tools/Preferences
2. 
3. 

**What is the expected output? What do you see instead?**

![screenshot_1](https://user-images.githubusercontent.com/4498367/30073614-1b7a631e-9277-11e7-9776-4385040a2245.png)

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2579, in edit_preferences
    widget.initialize()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 75, in initialize
    self.load_from_conf()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 379, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1

**Comment by ccordoba12** [comment] 2017-09-06 12:31
We've seen this error before but we don't know how to reproduce it. What was the last change you did in Preferences before this error occurred?

**Comment by rlaverde** [comment] 2017-09-06 13:27
I think we could catch that error and print the current variables, so we will have more information the next time it happen.

**Comment by ccordoba12** [comment] 2017-09-06 13:34
The thing is I really don't understand why `get_option` can return `None` here. There seems to be a problem with how we are saving color schemes.

**Comment by anstragal** [comment] 2017-09-06 16:35
Well, as I can see from my history the last things I searched were the links below. I encountered the errors of every topic. I remember applying the suggestions. I also updated to spyder 6.2.2 from anaconda prompt, uninstall it several times, and reinstall it, and the error still remains.

The link:
https://stackoverflow.com/questions/38250361/spyder-runfile-is-not-defined
https://github.com/spyder-ide/spyder/issues/3428
https://github.com/spyder-ide/spyder/issues/2812
https://stackoverflow.com/questions/15367760/unboundlocalerror-local-variable-referenced-before-assignment-when-reading-from

**Comment by ccordoba12** [comment] 2017-09-06 16:42
So did this error occur for you simply after installing Anaconda and starting Spyder? I mean, did it appear the first time you started Spyder?

**Comment by anstragal** [comment] 2017-09-06 16:52
Firstly appeared the errors above, and finally the error with the preferences. However, now after reinstalling that  error appears from the very first time I start Spyder.

**Comment by ccordoba12** [comment] 2017-09-06 16:55
Do you have a user name with non-ascii characters? I mean, characters like ñ or á or non-latin ones?

**Comment by anstragal** [comment] 2017-09-06 16:59
If you referring to my Anaconda username, it has only latin character.

**Comment by anstragal** [comment] 2017-09-06 17:34
Wow, I have clicked Tools/Reset Spyder to factory defaults and the error disappeared !

Thanks for your support anyway!

**Comment by ccordoba12** [comment] 2017-10-26 14:23
Closing as a duplicate of issue #5578.

**Closed by ccordoba12** 2017-10-26 14:23 UTC
Labels: component:Preferences, type:Bug
