### ISSUE TITLE
Spyder 4.0 Variable explorer slow to display dataframe

### ISSUE THREAD

**Issue by warren55555** [spyder-ide/spyder#11125] opened 2019-12-17 22:49 UTC
### What steps will reproduce the problem?

I have a DataFrame of size (7438, 44) with a datetime index. When I double-click on this DataFrame in the Variable Explorer of Spyder 4.0, it takes more than 6 seconds to display. When I do the same thing in Spyder 3.3.6, it is displayed immediately.

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.3.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.14.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.17.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.10.2 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-17 22:55
Duplicate of #11060

**Closed by ccordoba12** 2019-12-17 22:55 UTC
