### ISSUE TITLE
Spyder cannot connect to kernel

### ISSUE THREAD

**Issue by Jerry-kiwi** [spyder-ide/spyder#6452] opened 2018-02-14 09:44 UTC
## Description of your problem

**What steps will reproduce the problem?**
1. Fresh install of Xubuntu
2. pip3 install spyder
3. pip3 install matplotlib

**What is the expected output? What do you see instead?**
After step 2 spyder is starting normaly
I'me getting:
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
Type "copyright", "credits" or "license" for more information.
IPython 6.2.1 -- An enhanced Interactive Python.

After step 3 spyder cannot connect to kernel.
Graphics backend is set to "Auto"
I'm getting "connecting to kernel..." message

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: Python 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] on linux
* Qt Version:5.10
* PyQt Version: 5.10
* Operating system: XUbuntu 16.04.2 (Linux v01 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

## Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  3.4.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
sympy >=0.7.3    :  None (NOK)

# pip3 freeze 

<details>
alabaster==0.7.10
astroid==1.6.1
Babel==2.5.3
beautifulsoup4==4.4.1
bleach==2.1.2
catfish==1.4.2
chardet==2.3.0
cloudpickle==0.5.2
command-not-found==0.3
cycler==0.10.0
decorator==4.2.1
defer==1.0.6
docutils==0.14
entrypoints==0.2.3
html5lib==1.0.1
imagesize==0.7.1
ipykernel==4.8.1
ipython==6.2.1
ipython-genutils==0.2.0
isort==4.3.4
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.2
jupyter-core==4.4.0
language-selector==0.1
lazy-object-proxy==1.3.1
lightdm-gtk-greeter-settings==1.2.1
lxml==3.5.0
MarkupSafe==1.0
matplotlib==2.1.2
mccabe==0.6.1
menulibre==2.1.3
mistune==0.8.3
mugshot==0.3.1
nbconvert==5.3.1
nbformat==4.4.0
numpy==1.14.0
numpydoc==0.7.0
onboard==1.2.0
packaging==16.8
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.0.1
pickleshare==0.7.4
Pillow==3.1.2
prompt-toolkit==1.0.15
psutil==3.4.2
ptyprocess==0.5
pycodestyle==2.3.1
pycups==1.9.73
pycurl==7.43.0
pyflakes==1.6.0
Pygments==2.2.0
pygobject==3.20.0
pylint==1.8.2
PyOpenGL==3.1.0
pyparsing==2.2.0
PyQt5==5.10
python-apt==1.1.0b1
python-dateutil==2.6.1
python-debian==0.1.27
python-systemd==231
pytz==2018.3
pyxdg==0.25
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
reportlab==3.3.0
requests==2.9.1
rope==0.10.7
sessioninstaller==0.0.0
simplegeneric==0.8.1
sip==4.19.7
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.7.0
sphinxcontrib-websupport==1.0.1
spyder==3.2.6
testpath==0.3.1
tornado==4.5.3
traitlets==4.3.2
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.10.11
xkit==0.0.0
</details>

**Comment by Jerry-kiwi** [comment] 2018-02-14 17:10
I've  overcomed problem by swithing graphics mode to TK

**Comment by ccordoba12** [comment] 2018-02-15 13:05
This problem is caused by two things:

1. Having the Automatic backend set in our Preferences.
2. Having pyzmq **17.0.0** installed in your system.

I already reported the problem [upstream](https://github.com/zeromq/pyzmq/issues/1140) and there's [a fix](https://github.com/ipython/ipykernel/pull/307) for it that (I hope) soon will be part of a new release of `ipykernel`.

**Comment by IgnacioRubioScola** [comment] 2018-02-16 15:31
I had install dev version of `ipykernel` and solved the problem:
`pip install git+https://github.com/ipython/ipykernel.git`

**Comment by jrast** [comment] 2018-02-19 10:41
Meanwhile, a downgrade to pyzmq 16.0.4 seems to fix the problem.

**Comment by s7jones** [comment] 2018-02-20 20:05
Latest version of `ipykernel` from pip fixed this for me.

Run `pip install ipykernel --upgrade` in a console of your choice (e.g. cmd.exe or terminal).

**Comment by ccordoba12** [comment] 2018-02-20 20:47
Or

    conda upgrade ipykernel

for those that are using Anaconda. Please remember that pip and conda are **not** interchangeable and you must always use conda instead of pip if possible (i.e. if the package is available through conda).

**Comment by curiositycurve** [comment] 2019-03-28 11:07
I'm on Ubuntu 18.10. Using Spyder & installed the dependencies via pip. This is what is being shown in my console. Please tell how to solve this. It was running well but I upgraded Spyder & installed numpy, scipy, pandas & matplotlib libraries via pip. Opened Spyder after doing all this & got this error.

Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython.spyder_kernel'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython.spyder_kernel'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython.spyder_kernel'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython.spyder_kernel'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython.spyder_kernel'

**Comment by ccordoba12** [comment] 2019-03-28 12:17
@curiositycurve, you need to uninstall the Spyder version you installed with `apt-get` for things to work with pip.

**Comment by AntaRed** [comment] 2019-10-16 10:01
![image](https://user-images.githubusercontent.com/56631885/66909232-0cb9e680-f015-11e9-8b27-4c48741e6567.png)

**Comment by ccordoba12** [comment] 2019-10-16 16:01
@AntaRed, please report your error here:

https://github.com/jupyter/jupyter_client

**Comment by ccordoba12** [comment] 2019-10-16 16:01
Closing this issue because it's very old.

**Closed by ccordoba12** 2019-10-16 16:01 UTC

**Comment by vaishnavi8701** [comment] 2020-02-23 07:17
receiving an errror like this when i execute conda update --all

- DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\python.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\python.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']

**Comment by vaishnavi8701** [comment] 2020-02-23 07:17
wht should i do
