### ISSUE TITLE
Add file search functionality for the Switcher

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#11269] opened 2020-01-08 18:09 UTC
Add a mode for the Switcher to enable searching files by name (under the current working directory) to open them in the Editor

**Comment by maurerle** [comment] 2022-11-19 08:33
I think this is a duplicate of #3860

**Comment by ccordoba12** [comment] 2022-11-19 14:35
Right, closing this one then.

**Closed by ccordoba12** 2022-11-19 14:35 UTC
Labels: type:Enhancement, component:File Switcher, v5.0beta1
