### ISSUE TITLE
In Spyder 2.3.3 on Ubuntu 14.04.2 LTS, the Python console when undocked and used outside the Spyder IDE does not provide the ability for auto-completion

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2261] opened 2015-03-23 18:49 UTC
Hi,

In Spyder 2.3.3 on Ubuntu 14.04.2 LTS, the Python console when undocked and used outside the Spyder IDE does not provide the ability for auto-completion history tracking etc.  Is this intentionally built or is this a bug?  I wish I could undock the Python console from the Spyder IDE and use it in another monitor, but that deprives me of all the cool features I just mentioned above.

Best Regards,
Srini

**Comment by ccordoba12** [comment] 2015-03-23 23:12
This is a duplicate of issue #1338

**Closed by ccordoba12** 2015-03-23 23:12 UTC
Labels: duplicate

**Comment by s0r2637** [comment] 2015-03-24 00:45
I still didnt get it.  How to fix this issue if a fix exists.

Srini

**Comment by ccordoba12** [comment] 2015-03-24 00:49
What I meant is that this issue was reported before, in issue #1338. So 
it makes no sense to have two open issues that refer to the same problem.

**Comment by s0r2637** [comment] 2015-03-24 00:50
So the problem still exists.  Are u guys still trying to fix the issue?
Thanks in advance.

Srini

**Comment by ccordoba12** [comment] 2015-03-24 00:52
Nop, I haven't had time to see what the problem is about it.
