### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by tdbowman** [spyder-ide/spyder#6687] opened 2018-03-08 22:38 UTC
File "/Users/name/anaconda/lib/python3.6/site-packages/spyder/widgets/editor.py", line 2387, in dropEvent
    files = [f for f in files if encoding.is_text_file(f)]
TypeError: 'NoneType' object is not iterable

**Comment by ccordoba12** [comment] 2018-03-08 23:32
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if it helps.

**Comment by CAM-Gerlach** [comment] 2018-03-18 03:15
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-03-18 03:15 UTC
Labels: status:Awaiting Followup
