### ISSUE TITLE
Crash while rapidly closing tabs

### ISSUE THREAD

**Issue by MayeulC** [spyder-ide/spyder#7002] opened 2018-04-21 22:03 UTC
## Problem Description

Spyder crashed when i was closing several tabs using the middle mouse click.

### What steps will reproduce the problem?

Not sure it will always reproduce it, but I had a lot of tabs open at that point (I added a shebang header to each file, then committed), and was closing them all by rapidly mashing my scrollwheel button. Maybe I clicked a second time on a tab that was technically closed, but still displaying a close animation.

Edit: as it happens, I still had a few tabs open after this, and was able to reproduce the bug the same way: rapidly middle mouse click in the middle of the tab bar, without aiming for a specific one.

### Traceback
```python-traceback
  File "/usr/lib/python3.6/site-packages/spyder/widgets/editor.py", line 1416, in close_file
    filename = self.data[index].filename
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/editor.py", line 1416, in close_file
    filename = self.data[index].filename
IndexError: list index out of range
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.10.1
* PyQt5 version: 5.10.1
* Operating system: Linux 4.16.2-2-ARCH

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.5 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.3.1 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by CAM-Gerlach** [comment] 2018-04-21 22:46
Thanks for the report. I couldn't reproduce while closing over a dozen files by rapidly tapping or holding down Ctrl-W or by mapping a button on my mouse to button three on either Win 8.1 with PyQt 5.6 or Win 10 with PyQt 5.9. Maybe its something specific to Linux, PyQt5.10 or a ``pip`` install, or I'm just not doing the procedure quite right? @ccordoba12 ?

**Comment by MayeulC** [comment] 2018-04-22 08:42
I was not able to reproduce after a full reboot, the the problem might lie elsewhere.

**Comment by ccordoba12** [comment] 2018-04-23 14:08
@MayeulC, please post again here if you find a way to reproduce this. I'm closing this for now.

**Closed by ccordoba12** 2018-04-23 14:08 UTC
Labels: component:Editor, status:Awaiting Followup

**Comment by ccordoba12** [comment] 2018-04-23 19:26
No worries. Thanks for taking the time to make Spyder better.
