### ISSUE TITLE
Search from Online help freezes Spyder

### ISSUE THREAD

**Issue by rsmaior** [spyder-ide/spyder#2458] opened 2015-06-01 23:23 UTC
Spyder Version:  2.3.0
Python Version:  3.4.0
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.2.1 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.1.0 (OK)

What steps will reproduce the problem?
1. Check the option View -> Panes -> Online help 
2. Fill Search box with any word and click Search button

What is the expected output? What do you see instead?
I would expect search results to click on. Spyder freezes instead and I have to force quit.

Please provide any additional information below.
Get box is working ok.

**Comment by ccordoba12** [comment] 2015-06-01 23:47
Thanks for reporting. I'll take a look at this error for our next release.

**Comment by ccordoba12** [comment] 2015-06-03 21:48
I can't reproduce this error. It takes some time until a search is done, but it returns the expected result.

Please update to 2.3.4 and try again :-)

**Comment by rudregues** [comment] 2015-06-04 22:55
@ccordoba12 , even after updating 2.3.4 the bug remains. Bellow is the output generated by 2.3.4 "Report issue..." wizard:

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=1.0   :  1.2.1 (OK)
zmq >=2.1.11    :  14.0.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  None (NOK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
jedi >=0.8.1    :  (0, 7, 0) (NOK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.1.0 (OK)

I don't know if this helps, but I'm under Ubuntu 14.04 64 bits. The 2.3.4 Spyder was installed by pip and returned the following warning:
```
~$ sudo pip install -U spyder
The directory '/home/rodrigo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rodrigo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting spyder
  Downloading spyder-2.3.4.zip (3.7MB)
    100% |████████████████████████████████| 3.7MB 110kB/s 
Installing collected packages: spyder
  Found existing installation: spyder 2.3.0
    DEPRECATION: Uninstalling a distutils installed project (spyder) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling spyder-2.3.0:
      Successfully uninstalled spyder-2.3.0
  Running setup.py install for spyder
Successfully installed spyder-2.3.4

**Comment by ccordoba12** [comment] 2015-06-04 23:26
Thanks for posting this error. It means we need to update our installer :-) But it doesn't have anything to do with your problem.

Besides that, I'm using the exact same configuration as you are, but I'm unable to reproduce it.

@picca, could you help to take a look at this problem using the official Ubuntu packages? Thanks :-)

**Comment by goanpeca** [comment] 2019-11-25 18:44
I do not think this is relevant anymore @ccordoba12

**Comment by ccordoba12** [comment] 2019-11-25 19:33
Right, it was fixed by @dalthviz.

**Closed by ccordoba12** 2019-11-25 19:33 UTC
Labels: type:Bug
