### ISSUE TITLE
scroll + ctrl causing crash and losing of all unsaved work

### ISSUE THREAD

**Issue by MAFiA303** [spyder-ide/spyder#8401] opened 2018-12-09 20:08 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. open spyder
2. scroll on touch pad
3. press ctrl and scroll the other way

### What is the expected output? What do you see instead?
change of workspace size, instead the app crashes and i lost all my precious work

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.6.7.final.0
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: windows 10 1809

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.2 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

**Comment by jnsebgosselin** [comment] 2018-12-10 13:06
Thanks for reporting and we are sorry for the work you lost. Spyder4 will have an autosave feature (see PR #7660) that should mitigate this kind of bad situation in the future. Maybe you can check the history.py file to see if you could salvage some part of your code as some have reported in Issue https://github.com/spyder-ide/spyder/issues/4409

This is a duplicate of https://github.com/spyder-ide/spyder/issues/8271, so I'm going to close this one.

**Closed by jnsebgosselin** 2018-12-10 13:06 UTC
