### ISSUE TITLE
error

### ISSUE THREAD

**Issue by manoja328** [spyder-ide/spyder#6249] opened 2018-01-19 14:38 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/manojacharya/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 524, in <lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "/Users/manojacharya/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 546, in editor_accepted
    self.set_value(index, conv_func(value))
  File "/Users/manojacharya/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 461, in <lambda>
    conv_func = lambda arr: Image.fromarray(arr, mode=value.mode)
AttributeError: type object 'Image' has no attribute 'fromarray'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-19 15:12
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2018-01-19 17:22
For reference, this error was reported once before, as  #6093 , on Linux/Py2/Pysder 3.2.3, but was closed due to lack of response.

**Comment by CAM-Gerlach** [comment] 2018-01-28 21:06
...And now this one is closed for the same reason.

**Closed by CAM-Gerlach** 2018-01-28 21:06 UTC
Labels: status:AwaitingFollowup
