### ISSUE TITLE
[Question] - Help panel - searching for package

### ISSUE THREAD

**Issue by emilmirzayev** [spyder-ide/spyder#8943] opened 2019-03-14 11:33 UTC
Hi, I have a question regarding the help panel. I recently noticed that now I can not easily type a package name there in order to see its help. There two sources afaik: Console, which allows you to call for a package help when your cursor is on it in the editor, or object, which is the one where you can type. 
However, I can only type it one letter at a time. In order to type for example `len` I have type l, then press arrow key, then type e, then press arroy key again and then n. I cant just continously type.
Is there a way to solve this, or this is a feature?
![image](https://user-images.githubusercontent.com/25964049/54353843-4ed11300-4655-11e9-8704-c4f2a467f653.png)

-----
Spyder 3.3.3|Python 3.7.2 32-bit | Qt 5.12.1 | PyQt5 5.12 | Windows 10

**Comment by ccordoba12** [comment] 2019-03-15 09:19
Thanks for reporting. This is a duplicate of issue #8762 and it'll be fixed in our next version (3.3.4).

**Closed by ccordoba12** 2019-03-15 09:19 UTC

**Comment by emilmirzayev** [comment] 2019-03-15 11:02
Thank you!
