### ISSUE TITLE
Improve file reloading

### ISSUE THREAD

**Issue by dmitriia** [spyder-ide/spyder#7215] opened 2018-05-28 14:01 UTC
Hi,

My scipts are located on a big shared drive, which today experienced free space problems. Normal workflow wasn't affected at first, but then on a next File Run command (F5) Spyder asked whether it should reload the file and on positive answer its content dissappeared, file on disk now has 0 bytes length. Apparently on file saving file was deleted, but its new version couldn't be saved due to lack of space. Can you check the mechanics and possibly implement more failsafe logic - say do not delete old file until new one is saved?

Kind regards,

Dmitry

**Comment by ccordoba12** [comment] 2018-05-28 17:43
Thanks for reporting. We'll try to address this after we release our next version.

**Comment by CAM-Gerlach** [comment] 2018-06-02 22:27
Somewhat related: #6901 .

On another note, could this be a likely cause of the reports we've been occasionally getting about Spyder wiping their files to 0 byte length?

**Comment by goanpeca** [comment] 2019-11-29 02:01
>Apparently on file saving file was deleted, but its new version couldn't be saved due to lack of space. Can you check the mechanics and possibly implement more failsafe logic - say do not delete old file until new one is saved?

@jitseniesen how do you think we could handle this case?

**Comment by CAM-Gerlach** [comment] 2019-11-29 02:19
@goanpeca This is presumably (one of) the cause(s) of the originally reported issues where Spyder truncated users files to 0 bytes if saving failed. However, the fix was already implemented a year ago as I proposed in #8237 and @dalthviz implemented in #8347 by using `atomicwrites` to overwrite files atomically and robustly at the filesystem/OS level, so it shouldn't be possible for this to happen anymore. Ergo, you should be able to close this now.

**Closed** 2019-11-29 02:19 UTC
Labels: component:Editor, type:Bug
