### ISSUE TITLE
Spyder - Inspect Object Shortcut Not Working

### ISSUE THREAD

**Issue by user905** [spyder-ide/spyder#6014] opened 2017-12-19 15:26 UTC
## Description of your problem
The command-I shortcut does not work in the editor. When using the combo, nothing happens.
**What steps will reproduce the problem?**

1. Open Spyder 3.2.4
2. Create a new .py file
3. Write basic code and begin using a function that can be inspected. (Ex. 

import pandas as pd
dataset = pd.read_csv('x.csv')
)
**What is the expected output? What do you see instead?**
A definition of the object, with all expected parameters, appears in the Help window.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: macOS High Sierra (10.13.2 (17C88))

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
psutil >=0.3     :  5.4.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment] 2017-12-19 18:59
Thanks for reporting. Your specific example appears to be a duplicate of #5998 , which is a specific problem with `pandas` and `jedi`, not Spyder. Therefore, this issue will be closed. If this occurs on anything you try to complete from a variety of packages, then please reopen and provide any pertinent details unique to your setup, as well as try `spyder --reset` and reinstalling Anaconda.

**Closed by CAM-Gerlach** 2017-12-19 19:00 UTC
