### ISSUE TITLE
Splitted editor window, deleted source file

### ISSUE THREAD

**Issue by MaxAmmon** [spyder-ide/spyder#8033] opened 2018-10-08 17:18 UTC
### What steps will reproduce the problem?

1) Split editor in two windows
2) open some files, such that they are sshown in tabs on both "splits" 
3) delete one of the files in explorer

Sypder realizes the vanished source and offer to close the tab, but it closes only the tab in the the first split. The tab in the second split stays ope. This error raises while clicking on the second still opened tab.

### Traceback
```python-traceback
  File "C:\Software\WinPython\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\spyder\plugins\editor.py", line 1368, in close_file_in_all_editorstacks
    index = editorstack.get_index_from_filename(filename)
  File "C:\Software\WinPython\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\spyder\widgets\editor.py", line 1372, in get_index_from_filename
    return filenames.index(filename)
ValueError: 'X:\\SoftwareDev\\Python\\spmgut\\source\\spmgut\\io\\import_image.py' is not in list
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.6
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.7 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.14.5 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-10-08 17:30
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment] 2019-02-24 18:57
This is a duplicate of issue #8814, which has a much better way to reproduce this problem.

**Closed by ccordoba12** 2019-02-24 18:57 UTC
Labels: component:Editor, type:Bug
