### ISSUE TITLE
bug when writing [:,0] inside a len() statement in editor

### ISSUE THREAD

**Issue by SergioLordano** [spyder-ide/spyder#10458] opened 2019-10-18 18:53 UTC
### What steps will reproduce the problem?

just as the title says, some internal error arises when I try to   slice an array `ar` inside a `len()` statement, like:

```
len(ar[:,0])
``` 

### Traceback
```python-traceback
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1134, in process_signatures
    parameter_data = parameters[parameter_idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/ABTLUS/sergio.lordano/spyder-beta/bin/spyder3", line 10, in <module>
    sys.exit(main())
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/app/start.py", line 195, in main
    mainwindow.main()
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3646, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3529, in run_spyder
    app.exec_()
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/plugins/completion/plugin.py", line 138, in receive_response
    self.gather_and_send(request_responses)
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/plugins/completion/plugin.py", line 189, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 915, in handle_response
    handler(params)
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1151, in process_signatures
    self.log_lsp_handle_errors("Error when processing signature")
  File "/home/ABTLUS/sergio.lordano/spyder-beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 946, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.6.7
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-65-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.2 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.12 (OK)
IPython >=4.0                :  7.6.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.15.1 (OK)
scipy >=0.17.0               :  1.3.0 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by ccordoba12** [comment] 2019-10-20 17:49
Duplicate of #10453.

**Closed by ccordoba12** 2019-10-20 17:49 UTC
