### ISSUE TITLE
Some issues when connectiing to external kernels

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#3478] opened 2016-09-29 00:57 UTC
I'm using mac
1.at before, when I put kernel-100.json in the kernel folder, I can type 100 in connect existing kernel and got connected. But when I updated to 3.0, when I type 100, it said that cannot find the kernel file.

2.when I connect to a remote kernel it says that the namespacebrowser cannot refresh since the entity namespacebrowser is None, I need to comment these several code to avoid the bug

**Comment by ccordoba12** [comment] 2016-09-29 07:29
> when I put kernel-100.json in the kernel folder

What is your kernel folder?

**Comment by fayeshine** [comment] 2016-09-29 07:37
@ccordoba12 
````
./.ipython/profile_default/security/kernel-100.json
./Library/Jupyter/runtime/kernel-100.json
```

**Comment by ccordoba12** [comment] 2016-09-29 07:40
Ok, thanks :-) The first one doesn't work anymore because it's used by IPython 3.0 or less and we don't support those versions anymore.

The second one should work, so that's a bug in Spyder :-)

**Comment by ccordoba12** [comment] 2016-10-06 01:55
I consider this is a duplicate of Issue #3472. That's why I'm closing it :-)

**Closed by ccordoba12** 2016-10-06 01:55 UTC
Labels: Comp-Console-IPython, Type-Bug
