### ISSUE TITLE
gdal autocomplete 

### ISSUE THREAD

**Issue by ali1100** [spyder-ide/spyder#6902] opened 2018-04-05 14:51 UTC
## Problem Description
autocomplete function not working when using gdal package on variables. when using IPython it works.
![untitled](https://user-images.githubusercontent.com/34811116/38373396-6dace360-3906-11e8-9af5-9e307f29238f.png)
![untitled222](https://user-images.githubusercontent.com/34811116/38373406-76105e88-3906-11e8-8340-e5456c643b16.png)

### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:3.2.8
* Python:2.7
* Qt:5.6
* PyQt:5 5.6

* Operating System:win8.1

### Dependencies

```
IPython >=4.0;<6.0:  5.1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
numpy >=1.7       :  1.13.1 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.5.0 (OK)
pygments >=2.0    :  2.1.3 (OK)
pylint >=0.25     :  1.6.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
sympy >=0.7.3     :  1.0 (OK)

```

**Comment by ccordoba12** [comment] 2018-04-05 16:44
Thanks for reporting. This is a duplicate of issue #2162.

Please see the following link for an explanation:

https://stackoverflow.com/q/42777430/438386

**Closed by ccordoba12** 2018-04-05 16:44 UTC
