### ISSUE TITLE
"Internal Error" & "Cannot connect to Kernel" 

### ISSUE THREAD

**Issue by ATFromGA** [spyder-ide/spyder#6754] opened 2018-03-14 00:55 UTC
## Problem Description
I downloaded and installed anaconda with Spyder 3.2.7 on Mac High Sierra. Each time I open spyder, it gives me an internal error message after a few minutes, and the whole spyder application closes. The IPython interpreter panel gives me the message "connecting to kernel" followed by the message "kernel died." 

Is anyone else running into this issue, and any ideas how to fix it?

### What steps will reproduce the problem?

1. Download Anaconda 5.1 Python 3.6 version
2. Open Anaconda and Python

### What is the expected output? What do you see instead?
Expected Output --> Code editor and interpreter panel 

Current Output /

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.7
* Python: 
* Qt:
* PyQt:
* Operating System: Mac OS High Sierra Version 10.13.3

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2018-03-14 14:47
> it gives me an internal error message

Please post this error message. Else, we can't help you, sorry.

**Comment by ATFromGA** [comment] 2018-03-14 22:26
File "/Users/XXXXXXXX/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 950, in update_working_directory
    shellwidget.get_cwd()
  File "/Users/XXXXXXXXXXXX/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/Users/XXXXXXXXX/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 340, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/XXXXXXXXXX/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/XXXXXXXXXX/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
WARNING:traitlets:kernel died: 18.000191926956177
WARNING:traitlets:kernel died: 17.99885892868042

These are the details to my error message, and the warning at the end of the message continues until the the SPYDER application crashes. I hope it helps! I am a complete novice, so forgive me if this isn't the message you were asking for.

**Comment by ccordoba12** [comment] 2018-03-15 00:03
Thanks for reporting. This is a duplicate of #6335. Please see there for a solution.

**Closed by ccordoba12** 2018-03-15 00:03 UTC
Labels: status:Awaiting Followup

**Comment by ATFromGA** [comment] 2018-03-15 02:50
Thank you!
