### ISSUE TITLE
Control C in console causes system to hang rather than break execution

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1658] opened 2015-02-17 20:26 UTC
_From [jacob.ba...@gmail.com](https://code.google.com/u/103806280181391043582/) on 2013-11-29T18:14:19Z_

Pressing control C in the console window while running a file with F5 can cause spyder to hang and to loss of work 

What steps will reproduce the problem?

 1. Run a program with long computation time by pressing F5
2. Focus on the console window running the code and press Control C What is the expected output? What do you see instead? The system should process a break and stop execution. Instead it hangs so that it is impossible to focus on another window. The user has to kill Spyder so work is lost. What version of the product are you using? On what operating system? Spyder 2.2.0 on Windows 7 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1658_

**Comment by ccordoba12** [comment] 2015-07-13 05:39
Closing as duplicate of issue #1431.

**Closed by ccordoba12** 2015-07-13 05:39 UTC
Labels: 1 star, bug, duplicate
