### ISSUE TITLE
Tabs cannot be re-arranged.

### ISSUE THREAD

**Issue by SHZ66** [spyder-ide/spyder#2717] opened 2015-09-25 21:28 UTC
## Description

**What steps will reproduce the problem?**

1. Open multiple files in spyder IDE (e.g. having file A.py and B.py opened)
2. The tab of B.py cannot be moved before A.py
3. 

**What is the expected output? What do you see instead?**
The tabs cannot be dragged by mouse.

**Please provide any additional information below**
Spyder is the ideal IDE for scientific computing - the best part is its debugging is almost as good as the other software-developing based IDE (the console in debug mode is somewhat hard to use though, I can't even use up and down arrows to navigate history). I sincerely hope this IDE can get better and better.

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  1.0.0 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by goanpeca** [comment] 2015-09-25 21:39
Duplicate of #564

**Closed by goanpeca** 2015-09-25 21:39 UTC
