### ISSUE TITLE
Apple integration

### ISSUE THREAD

**Issue by jowe19** [spyder-ide/spyder#11083] opened 2019-12-13 22:16 UTC
I would like to use the new feature of Spyder 4.0 : the opening of a .py file directly with Spyder. Unfortunately the option is not accessible in the preference pane.
<img width="1028" alt="Capture d’écran 2019-12-13 à 23 09 58" src="https://user-images.githubusercontent.com/19306526/70835576-c9ee7200-1dfd-11ea-9630-4378049a744a.png">

How could I fix it ?

Thank you very much, 
Jonathan 

* Spyder version: 4.0
* Python version: 3.7.0
* Operating System name/version: Mac OS Catalina

**Comment by ccordoba12** [comment] 2019-12-13 23:10
@impact27, how could we simplify this process? Perhaps by changing the scripts that run Spyder in macOS?

**Comment by goanpeca** [comment] 2019-12-14 00:35
@jowe19 did you launch spyder using `python.app` as the message suggests?

**Comment by jowe19** [comment] 2019-12-14 00:40
I'm afraid but I don't really understand the meaning of the message.

**Comment by goanpeca** [comment] 2019-12-14 00:42
@impact27 we then need probably to provide more information.

If you open a terminal and type 

`python.app` what do you see? On mac we have `python` executable and you can install (with anaconda for example) `python.app` which provides some functionalities within OSX that are not possible with just `python` so running spyder with `python.app` enables this.

**Comment by jowe19** [comment] 2019-12-14 00:54
Result of `python.app` in a terminal :
<img width="606" alt="Capture d’écran 2019-12-14 à 01 53 45" src="https://user-images.githubusercontent.com/19306526/70840744-a7b41e80-1e14-11ea-905b-29dc0cc62ed3.png">

**Comment by ccordoba12** [comment] 2019-12-14 01:06
@goanpeca, I think this is possible when you run Spyder from `bootstrap.py`, with

    python.app bootstrap.py

But unless we change things in the executable scripts that start Spyder, I don't think this is something can easily have access to.

**Comment by jowe19** [comment] 2019-12-14 09:42
I get the message `(null): can't open file 'bootstrap.py': [Errno 2] No such file or directory`

**Comment by impact27** [comment] 2019-12-14 12:03
The problem is that you can not choose which python you use from the python script. We vould however modify the message to say `python.app` instead of `python`?

How do you launch spyder?

> `(null): can't open file 'bootstrap.py': [Errno 2] No such file or directory`

You have to run this command in the folder where bootstrap.py is. alternatively create a new python file with:
```
from spyder.app import start
start.main()
```
And run it with `python.app`

**Comment by jowe19** [comment] 2019-12-14 15:05
@impact27  I use the command `spyder3` in a terminal, or an app created with the following tutorial https://stackoverflow.com/questions/20723977/ways-to-invoke-python-and-spyder-on-osx

Apple integration is finally OK, if Spyder is already opened. But if I click on a `.py` file if Spyder is turned off, nothing is happening.

**Comment by goanpeca** [comment] 2019-12-14 15:13
> Apple integration is finally OK, if Spyder is already opened. But if I click on a .py file if Spyder is turned off, nothing is happening.

Is this expected @impact27 ?

**Comment by ccordoba12** [comment] 2019-12-14 16:12
Yeah, I think Spyder needs to be started first to register itself with Apple services.

**Comment by impact27** [comment] 2019-12-14 16:18
Launching when spyder is closed would only work if you have a `spyder.app`, while launching while running also works with python.app

**Comment by jowe19** [comment] 2019-12-14 17:28
Thank you for answering to all my questions.

> Launching when spyder is closed would only work if you have a `spyder.app`, while launching while running also works with python.app

So currently we are not able to open `py` files when Spyder is closed.

**Comment by impact27** [comment] 2019-12-14 17:42
> So currently we are not able to open py files when Spyder is closed.

I think it might work with the Spyder bundle? See https://github.com/spyder-ide/mac-application/issues/2

**Comment by jowe19** [comment] 2019-12-16 13:46
> > So currently we are not able to open py files when Spyder is closed.
> 
> I think it might work with the Spyder bundle? See [spyder-ide/mac-application#2](https://github.com/spyder-ide/mac-application/issues/2)

I followed the steps to create the bundle : [Spyder.zip](https://github.com/spyder-ide/spyder/files/3968277/Spyder.zip). I successfully opened a file with this app, but Spyder does not open anymore after a second try, and I get the following error message. 
<img width="420" alt="Capture d’écran 2019-12-16 à 14 40 49" src="https://user-images.githubusercontent.com/19306526/70911715-c122b980-2012-11ea-9d25-58bb54ff437f.png">

**Comment by impact27** [comment] 2019-12-16 13:52
Well if you have this message then spyder is launching. You can try:
`python3 /path/to/Spyder.app/Spyder.app/Contents/MacOS/Spyder`
And see if there is an error as well

**Comment by jowe19** [comment] 2019-12-17 21:01
The command `python3 /path/to/Spyder.app/Contents/MacOS/Spyder` gives an error : 
`/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file '/path/to/Spyder.app/Contents/MacOS/Spyder': [Errno 2] No such file or directory`

**Comment by impact27** [comment] 2019-12-17 21:16
You have to replace path/to by the actual path

**Comment by jowe19** [comment] 2019-12-17 21:24
Sorry, I am a little bit tired. I get also an error with the good path 
```
python3 /Applications/Spyder.app/Contents/MacOS/Spyder 
  File "/Applications/Spyder.app/Contents/MacOS/Spyder", line 3
    if [[ -e /etc/profile ]]; then
                            ^
SyntaxError: invalid syntax
```

Spyder unix file in the contents folder is 
```
#!/bin/bash

if [[ -e /etc/profile ]]; then
    source /etc/profile
fi
if [[ -e ~/.bash_profile ]]; then
    source ~/.bash_profile
fi

source /Library/Frameworks/Python.framework/Versions/3.8/bin spyder3
/Library/Frameworks/Python.framework/Versions/3.8/bin/spyder3 $@
```

**Comment by ccordoba12** [comment] 2022-05-21 16:24
I think this should be fixed when we can depend on the latest version of Applaunchservices.

**Closed by ccordoba12** 2022-05-21 16:24 UTC
Labels: type:Enhancement, component:Preferences
