### ISSUE TITLE
Anaconda (Pyside / PyQt is required)

### ISSUE THREAD

**Issue by brainiac122** [spyder-ide/spyder#2765] opened 2015-10-13 15:21 UTC
Hi,

Having an issue getting Spyder to work in the Anaconda / Python 3.4 distribution on Windows. I have the same setup on my Linux and Spyder runs fine, however when I try to run Spyder in windows the following things happen:

1 - Through Anaconda Launcher, it aims to launch and then does nothing (or once it popped up telling me it was incompatible with my windows version even though I am running 32 bit and it's a 32 bit PC)

2 - If I try to run Spyder from CMD I get the below error. Pyside is incompatible with Python 3.4, however, PyQt is already installed with ananconda (I have tried to update it and know it's there and everything is up to date) so I am unsure where to go from here.

I have also tried sypder --reset and the same error message just pops up.

<code>C:\windows\system32>spyder
Traceback (most recent call last):
  File "C:\Programs\Python34\lib\site-packages\spyderlib\qt\__init__.py", line 4
8, in <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Python34\lib\site-packages\spyderlib\requirements.py", line
40, in check_qt
    from spyderlib import qt
  File "C:\Programs\Python34\lib\site-packages\spyderlib\qt\__init__.py", line 5
0, in <module>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Python34\Scripts\spyder", line 3, in <module>
    start_app.main()
  File "C:\Programs\Python34\lib\site-packages\spyderlib\start_app.py", line 114
, in main
    from spyderlib import spyder
  File "C:\Programs\Python34\lib\site-packages\spyderlib\spyder.py", line 48, in
 <module>
    requirements.check_qt()
  File "C:\Programs\Python34\lib\site-packages\spyderlib\requirements.py", line
50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "C:\Programs\Python34\lib\site-packages\spyderlib\requirements.py", line
25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.</code>

Please advise.

**Comment by brainiac122** [comment] 2015-10-13 15:43
Update on this issue, multiple installs of python itself was causing confusion for the IDE. With just the Anaconda install however I still get that the version is incompatible despite 32-bit anaconda being installed on a 32-bit windows 7 machine.

Thoughts?

**Comment by ccordoba12** [comment] 2015-10-13 20:24
Please put here the new message (about 32 bit incompatibility) you're seeing.

Also, what are your Spyder and Anaconda versions?

**Comment by brainiac122** [comment] 2015-10-14 11:15
![error](https://cloud.githubusercontent.com/assets/14842045/10482022/c14317fa-726c-11e5-80b2-d37d68311079.png)

Versions:
Anaconda 3.18.2 (latest)
Spyder - Latest version too, can't see the version number but "conda update --all" returns no updates for spyder and I fully updated it with that command yesterday.

Can definitely confirm the system is Win 7 Enterprise 32, and the installed Anaconda is 32bit. Have tried the 64bit installer and it fails to run stating that my system is 32 bit.

**Comment by brainiac122** [comment] 2015-10-14 11:23
Also it's the Python 3.4 version of Anaconda if that helps you.

Found the exact Spyder version on the Anaconda GUI launcher, 2.3.7

**Comment by ccordoba12** [comment] 2015-10-14 14:10
I'll check on a Windows 32 machine to see what's happening.

**Comment by brainiac122** [comment] 2015-10-14 21:19
Were you able to reproduce the error so? I have a second distribution running on Ubuntu 13.04 and it works fine. So it's strange that it only errors out in my Win32.

**Comment by epitopy** [comment] 2015-10-21 17:29
Hello,

I have the same issue: Spyder cannot be launched since updating to 2.3.7, and the error says the version is incompatible with my Windows version (same as above, except my Windows is in French).

I use Windows 7 32 bits and Anaconda with Python 3.4.3. I reproduced the error by uninstalling all Python installs on my machine, and reinstalling everything through Anaconda. After installation, everything worked fine. Then I updated Spyder, and it stopped working again.

The error appears both when lauching from Anaconda and from the cmd.

Thank you for any advice on this.

**Comment by tico-tico** [comment] 2015-10-25 23:16
About x32 vs x64
https://github.com/ContinuumIO/anaconda-issues/issues/491

>We are moving to new build systems for Python 3.5, and have encountered a packaging issue in which 64-bit exe's were somehow built instead of 32-bit. We are working to resolve this as soon as possible, and will post back soon.

**Comment by onlyjus** [comment] 2015-10-29 15:32
I think this issue is really caused by PyQt4.

I update to the latest PyQt4. Since then:
``` from PyQt4 import QtGui```
fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.
```
Which causes the spyder issue.

Uninstalling PyQt4 and using pyside works:

```
conda uninstall pyqt
conda install pyside
```

OS: Windows 7, 64bit
Anaconda: 3.18.3
Python: 2.7.10 - 64bit
PyQt4: 4.11.4

**Comment by brauliobarahona** [comment] 2015-10-30 15:49
Thanks @onlyjus ! -- I had the same issue, not sure what the source is but I did need to add `pyside`, though it was not necessary to uninstall `pyqt`.

As far as I could understand, in my case the `requirements.py` fails to find `qt` and bounces to `pyside`.

My setup:
    Windows 7 Professional, 64-bit
    ipython-qtconsole         4.0.1                    py27_1
    pyqt                              4.11.4                   py27_0
    qt                                  4.8.7                     vc9_2
    qtconsole                      4.1.0                    py27_0
    pyside                           1.2.1                    py27_0
    Python 2.7.10-3 |Anaconda 2.3.0

**Comment by tico-tico** [comment] 2015-10-30 16:13
I can't say anything about anaconda distribution, but I can explain what happens with miniconda. With the last update the guys from Continuum moved all required Qt dll's out of PyQt4 folder to /Library/bin, so linked PyQt4's pyd's can't find them. This issue can be easily fixed by adding Qt's dll folder to the PATH env. var. (*C:/Miniconda/Library/bin* in my case).
You can check maybe your anaconda has the same issue.

**Comment by Twizzledrizzle** [comment] 2015-11-02 13:45
Thank you, windows here, adding to my Path

C:\Anaconda\Library\bin

solved it!

**Comment by onlyjus** [comment] 2015-11-05 18:16
@Twizzledrizzle That worked for me too. Had an issue with matplotlib finding the png DLL as well. This fixed it. Did Anaconda change the path to these DLLs?

**Comment by Twizzledrizzle** [comment] 2015-11-05 19:33
Yeah they released the new 2.4 two days ago, moving the bin folder. I guess they have been having some problems

The new installation gets bad again if I try to install some packages, seaborn for example, which needs another version of scipy and matplot, anyone else having problems?

**Comment by sergeyf** [comment] 2015-11-05 19:35
I completely uninstalled my previous 2.2 installation, and installed 2.4
from a fresh .exe and everything is working (including Seaborn).

**Comment by Twizzledrizzle** [comment] 2015-11-05 20:20
Good to hear! I will try a fresh install on Monday and try as well, only tried the update through conda

**Comment by ilovepandas** [comment] 2015-12-03 09:45
Thanks @onlyjus  all that wasted time reinstalling etc...

**Closed** 2015-12-06 02:44 UTC
Labels: Bug

**Comment by jordanlui** [comment] 2018-04-10 04:26
Not sure if I should follow-up here (since this is closed) or somewhere else. 

I am still having the same issues with this in 2018 with Win 10.

I have Anaconda 2 installed, v 5.1
My base python install allows me to run Spyder from Windows Start menu, Win Cmd Prompt or Git Bash.

However I can't get a Spyder instance to run properly and execute code with a separate environment srunning 3.4, 3.5, or 3.6.

If I try to run it from Win Cmd Prompt I get the following error. And if I try to install PySide, I run into errors.

```
(mypy36) C:\Users\Jordan>spyder
Traceback (most recent call last):
  File "C:\Users\Jordan\Anaconda2\envs\mypy36\lib\site-packages\qtpy\__init__.py", line 163, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\Anaconda2\envs\mypy36\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Jordan\Anaconda2\envs\mypy36\lib\site-packages\spyder\app\start.py", line 159, in main
    from spyder.app import mainwindow
  File "C:\Users\Jordan\Anaconda2\envs\mypy36\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\Jordan\Anaconda2\envs\mypy36\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\Jordan\Anaconda2\envs\mypy36\lib\site-packages\qtpy\__init__.py", line 169, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

Thanks!
Jordan

**Comment by navneetjuneja26** [comment] 2018-08-28 04:56
Thanks a lot

**Comment by olashile** [comment] 2018-10-26 15:14
When I try to install pyside with  `conda install pyside`  i get the below error.
`olving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - jupyterlab_server
  - pyside
Use "conda info <package>" to see the dependencies for each package.`

Still having issues starting my Anaconda from my MacOS.

**Comment by shekyu01** [comment] 2019-01-18 09:57
Just run below in cmd:

pip install pyqt5==5.9

**Comment by micahlbray** [comment] 2019-02-08 23:13
@Twizzledrizzle that also worked for me! Solid call and thanks!

**Comment by kr-praveen** [comment] 2019-03-09 19:22
This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
Try:
pip uninstall PyQt5
Then update conda:
conda update conda
conda update anaconda-navigator

It will surely resolve your problem

**Comment by Liu-Shengjie** [comment] 2019-03-12 04:00
> This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
> Try:
> pip uninstall PyQt5
> Then update conda:
> conda update conda
> conda update anaconda-navigator
> 
> It will surely resolve your problem

Thanks a lot. Actually I install anaconda-navigator by "conda install anaconda-navigator" after "pip uninstall PyQt5" because the anaconda-navigator is broken.

**Comment by manbobo2002** [comment] 2019-04-27 01:10
> This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
> Try:
> pip uninstall PyQt5
> Then update conda:
> conda update conda
> conda update anaconda-navigator
> 
> It will surely resolve your problem

u really save my life, thanks!

**Comment by salmanea** [comment] 2019-04-28 20:21
> This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
> Try:
> pip uninstall PyQt5
> Then update conda:
> conda update conda
> conda update anaconda-navigator
> 
> It will surely resolve your problem

Thank you so much kr-praveen. I have been wrestling with this issue now for a week! Now it's working. Thanks!

**Comment by prasahu** [comment] 2019-05-02 03:49
> 
> 
> I think this issue is really caused by PyQt4.
> 
> I update to the latest PyQt4. Since then:
> `from PyQt4 import QtGui`
> fails with:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: DLL load failed: %1 is not a valid Win32 application.
> ```
> 
> Which causes the spyder issue.
> 
> Uninstalling PyQt4 and using pyside works:
> 
> ```
> conda uninstall pyqt
> conda install pyside
> ```
> 
> Or switch to an older version of PyQt4
> 
> ```
> conda install pyqt=4.10 -f
> ```
> 
> OS: Windows 7, 64bit
> Anaconda: 3.18.3
> Python: 2.7.10 - 64bit
> PyQt4: 4.11.4

I tried with all these steps. However, I found that It's working as Python 2.7 but I would prefer Python 3.7 in 32 bit windows with spyder. But I can't able to install it. Can you suggest something?

**Comment by Astik-Sachan** [comment] 2019-06-18 11:34
In Conda Command Promt for Environment (base in my case) run 

**Solution :** `conda install -c defaults pyqt=5 qt`





# Environment Dump #


### Package Plan ###

```
  environment location: C:\Users\mobis\AppData\Local\Continuum\miniconda3

  added / updated specs:
    - pyqt=5
    - qt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.5.15  |                0         166 KB
    certifi-2019.3.9           |           py37_0         155 KB
    conda-4.6.14               |           py37_0         2.1 MB
    openssl-1.1.1c             |       he774522_1         5.7 MB
    pyqt-5.9.2                 |   py37h6538335_2         4.2 MB
    qt-5.9.7                   |   vc14h73c81de_0        92.3 MB
    sip-4.19.8                 |   py37h6538335_0         281 KB
    ------------------------------------------------------------
                                           Total:       104.9 MB

The following packages will be UPDATED:

  openssl            conda-forge::openssl-1.1.1b-hfa6e2cd_2 --> pkgs/main::openssl-1.1.1c-he774522_1
  pyqt                  anaconda::pyqt-5.9.2-py37ha878b3d_0 --> pkgs/main::pyqt-5.9.2-py37h6538335_2

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2019.6.1~ --> pkgs/main::ca-certificates-2019.5.15-0
  certifi                                       conda-forge --> pkgs/main
  conda                                         conda-forge --> pkgs/main
  qt                       conda-forge::qt-5.9.7-hc6833c9_1 --> pkgs/main::qt-5.9.7-vc14h73c81de_0
  sip                  anaconda::sip-4.19.13-py37ha925a31_0 --> pkgs/main::sip-4.19.8-py37h6538335_0
```


# Error Dump #

```
Traceback (most recent call last):
  File "C:\Users\mobis\AppData\Local\Continuum\miniconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())

  File "C:\Users\mobis\AppData\Local\Continuum\miniconda3\lib\site-packages\spyder\app\start.py", line 186, in main
    from spyder.app import mainwindow

  File "C:\Users\mobis\AppData\Local\Continuum\miniconda3\lib\site-packages\spyder\app\mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore

  File "C:\Users\mobis\AppData\Local\Continuum\miniconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'`
```

**Comment by hkncl** [comment] 2019-12-03 08:20
I had the same issue. I downgraded the spyder version then I installed to comply with anaconda and python version.  It worked for me.

**Comment by piniit** [comment] 2020-04-23 14:23
> C:\Anaconda\Library\bin

Thanks.
 It is really working good.

**Comment by promise20** [comment] 2020-04-29 03:28
Thanks.

conda install -c defaults pyqt=5 qt

It really worked for me too about below problem!!

-------------------------------------------------------------
  File "/Users/anaconda3/lib/python3.7/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

**Comment by bhartendudubey** [comment] 2020-05-05 06:15
> 
> 
> This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
> Try:
> pip uninstall PyQt5
> Then update conda:
> conda update conda
> conda update anaconda-navigator
> 
> It will surely resolve your problem

Thanks a lot! It helped me to resolve my problem.

**Comment by IronicFreedom** [comment] 2020-06-18 14:34
I had this problem as well under Windows with the most recent versino of Anaconda/Spyder.
What solved it for me was to delete all Python/Anaconda/Spyder relevant folders in C:/Users/username/AppData/Roaming

**Comment by jesp1506** [comment] 2020-09-14 12:37
Desintalé PqQt5
update conda
update conda anaconda-navigator

anaconda-navigator
funcionó muy bien !
Gracias !
