### ISSUE TITLE
Spyder throws AttributeError: 'NoneType' object has no attribute 'modules' when importing DBSCAN 3 times

### ISSUE THREAD

**Issue by mlmr** [spyder-ide/spyder#8442] opened 2018-12-14 21:37 UTC
## Problem Description

The third time I try to import DBSCAN I get a AttributeError: 'NoneType' object has no attribute 'modules'.

### What steps reproduce the problem?

1. Use Spyder 3.3.2 and scikit-learn Version: 0.20.1.
2. run a script with the line: `from sklearn.cluster import DBSCAN` 3 times.

### What is the expected output? 

The first two times the output is as expected: a module DBSCAN ready to be used.

### What do you see instead?

However,the third time I invariably get:

```python-traceback

PASTE TRACEBACK HERE

Traceback (most recent call last):

File "<ipython-input-3-f629b84de3e3>", line 1, in <module>
runfile('/home/mario/Documents/python_machine_learning_projects/test_for_question.py', wdir='/home/mario/Documents/python_machine_learning_projects')

File "/home/mario/.local/lib/python2.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
execfile(filename, namespace)

File "/home/mario/.local/lib/python2.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 100, in execfile
builtins.execfile(filename, *where)

File "/home/mario/Documents/enerchemtek/python_machine_learning_projects/test_for_question.py", line 9, in <module>
from sklearn.cluster import DBSCAN

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
from .spectral import spectral_clustering, SpectralClustering

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/cluster/spectral.py", line 15, in <module>
from ..metrics.pairwise import pairwise_kernels

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
from .ranking import auc

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/metrics/ranking.py", line 36, in <module>
from ..preprocessing import label_binarize

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
from ._function_transformer import FunctionTransformer

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
from ..utils.testing import assert_allclose_dense_sparse

File "/home/mario/.local/lib/python2.7/site-packages/sklearn/utils/testing.py", line 54, in <module>
from nose.tools import raises as _nose_raises

File "/home/mario/.local/lib/python2.7/site-packages/nose/__init__.py", line 1, in <module>
from nose.core import collector, main, run, run_exit, runmodule

File "/home/mario/.local/lib/python2.7/site-packages/nose/core.py", line 11, in <module>
from nose.config import Config, all_config_files

File "/home/mario/.local/lib/python2.7/site-packages/nose/config.py", line 9, in <module>
from nose.plugins.manager import NoPlugins

File "/home/mario/.local/lib/python2.7/site-packages/nose/plugins/__init__.py", line 185, in <module>
from nose.plugins.manager import *

File "/home/mario/.local/lib/python2.7/site-packages/nose/plugins/manager.py", line 418, in <module>
import pkg_resources

File "/home/mario/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 55, in <module>
from pkg_resources.extern import six

File "/home/mario/.local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 44, in load_module
mod = sys.modules[extant]

AttributeError: 'NoneType' object has no attribute 'modules'

```

## Versions

* Spyder version: 3.3.2
* Python version: 2.7
* scikit-learn Version: 0.20.1.

**Comment by ccordoba12** [comment] 2019-01-26 10:08
Thanks for reporting. We'll take a look at it in a future release.

**Comment by ccordoba12** [comment] 2019-01-26 10:09
Note to self: relates SO question:

https://stackoverflow.com/questions/53734064/bug-in-spyder-when-networkx-imported

**Comment by ccordoba12** [comment] 2019-02-02 17:56
I don't know where this error is coming and I can't reproduce either using pip or Anaconda, sorry.

**Comment by ccordoba12** [comment] 2020-03-12 15:14
Closing because this is quite old now.

**Closed by ccordoba12** 2020-03-12 15:14 UTC
Labels: component:IPython Console, type:Bug
