### ISSUE TITLE
Crashing when trying to view variables

### ISSUE THREAD

**Issue by bdwilson24** [spyder-ide/spyder#8721] opened 2019-02-07 02:43 UTC
### What steps will reproduce the problem?

-Ran my script which compiles strings and floats into a DataFrame
-Tried to open the compiled DataFrame in the variable explorer by double-clicking on it
-Sometimes, the DataFrame opens, but if I attempt to scroll or close the DataFrame window, it becomes unresponsive and quits

This issue has been occuring regardless of how much data I have stored in the variable explorer. It even crashes when opening a DataFrame of size (82,4). Memory typically stays <50%

### Traceback
```python-traceback
  File "C:\Users\Ben\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 560, in <lambda>
    lambda eid=id(editor): self.editor_rejected(eid))
  File "C:\Users\Ben\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 585, in editor_rejected
    self._editors.pop(editor_id)
KeyError: 2144538734024
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-08 11:04
Thanks for reporting. This is a duplicate of #8557, which was fixed for Spyder, but I'll backport the fix so it can be available in our next stable version (3.3.3).

**Closed by ccordoba12** 2019-02-08 11:04 UTC
