### ISSUE TITLE
Crash after changing settings and restarting

### ISSUE THREAD

**Issue by letconex** [spyder-ide/spyder#8047] opened 2018-10-10 10:56 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "F:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "F:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "F:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "F:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "F:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "F:\WinPython\python-3.6.3.amd64\lib\site-packages\jupyter_client\manager.py", line 234, in start_kernel
    "Currently valid addresses are: %s" % local_ips()
RuntimeError: Can only launch a kernel on a local interface. Make sure that the '*_address' attributes are configured properly. Currently valid addresses are: ['192.168.0.102', '192.168.56.1', '192.168.99.1', '192.168.159.1', '192.168.206.1', '0.0.0.0', '']

**Comment by ccordoba12** [comment] 2018-10-10 13:41
This is caused by an old version of WinPython. Please use a more recent version to get a fix for this.

**Closed by ccordoba12** 2018-10-10 13:41 UTC

**Comment by letconex** [comment] 2018-10-17 15:41
Thank you, I will try installing a newer version.
