### ISSUE TITLE
Split screen layout is incorrectly restored

### ISSUE THREAD

**Issue by arman00** [spyder-ide/spyder#5031] opened 2017-08-23 10:35 UTC
## Description
Split screen layout is incorrectly restored if there is a vertical split nested in one horizontal split. Each time I restart Spyder I have to close the panels and split them again manually to have the same split layout, which is a bit annoying.

**What steps will reproduce the problem?**

1. Split the editor panel horizontally
2. Split the second panel vertically
3. Close Spyder
4. Run Spyder

**What is the expected output? What do you see instead?**
The same split layout is expected after restarting Spyder. However, instead of the vertical split in the second panel, it restores it as horizontal split. So I get 3 horizontal splits in total.

**Please provide any additional information below**
If I do only one vertical split, it restores it correctly.

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-23 12:22
Please post screenshots of the expected and actual results.

**Comment by arman00** [comment] 2017-08-23 14:09
Expected:
![spltscrn_expected](https://user-images.githubusercontent.com/23243866/29620134-5d651daa-881d-11e7-834d-a73f3d80e32e.jpg)

Actual:
![spltscrn_actual](https://user-images.githubusercontent.com/23243866/29620148-676b2c22-881d-11e7-9932-11ba928fb9cd.jpg)

**Comment by ccordoba12** [comment] 2017-08-23 14:32
Thanks! We'll work on this after **3.2.2**.

**Comment by jnsebgosselin** [comment] 2017-09-08 07:16
@ccordoba12 possible duplicate of Issue #1872

**Comment by ccordoba12** [comment] 2017-09-08 15:31
Thanks @jnsebgosselin!

**Closed by ccordoba12** 2017-09-08 15:31 UTC
Labels: component:Editor, resolution:Duplicate, type:Bug
