### ISSUE TITLE
Repeated error message: "Completion and linting in the editor..." keeps appearing

### ISSUE THREAD

**Issue by jeremymatt** [spyder-ide/spyder#11981] opened 2020-03-25 19:07 UTC
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
More of a feature request than a "problem".  Might be adjacent to issue #11476.  I was working with some large files and may have been low on memory (similar to issue #11976), but this seems like a different issue to me.

The following error message is popping up repeatedly.  The frequency of seems to be approximately 500ms (what I have "show completion detail after keyboard idle (ms)" option set to), but that's just a guess on my part.  A restart of spyder seems to have fixed the issue.  However, I was right in the middle of something and would have preferred to continue working without completion rather than interrupt my train of thought for a restart.  

Would it be possible to have the state of this warning remembered?  IE, show it once and then remember that the user dismissed the error and continued working anyway if future errors relating to linting/completion are encountered.

![image](https://user-images.githubusercontent.com/32210294/77574609-a92bc300-6ea8-11ea-9440-be63fafeb5ec.png)

### What steps reproduce the problem?

1. Once the error first appears, close it and then type something and wait about 1/2 a second

### What is the expected output? What do you see instead?
I'd like to be warned once only

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.7 64 bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

```

**Comment by ccordoba12** [comment] 2020-03-25 19:22
Duplicate of #11026

**Comment by ccordoba12** [comment] 2020-03-25 19:23
We're working on a fix for this right now.

**Closed by ccordoba12** 2020-03-25 19:22 UTC
