### ISSUE TITLE
Menu of the Object Explorer window: check boxes are overlapping the text

### ISSUE THREAD

**Issue by Serge-45** [spyder-ide/spyder#15146] opened 2021-04-06 20:13 UTC
### What steps will reproduce the problem?

Open Variable Explorer pane, select one variable, right-click for contextual menu, choose "View with the Object Explorer".
In the Object Explorer window, click on the menu icon on top right corner.
The checkboxes in the menu are overlapping the text label of the menu entries.

Low priority: menu is usable nevertheless

**Comment by steff456** [comment] 2021-04-06 20:32
Hi @Serge-45,

This is a duplicate of #15116 that is fixed by #15127. We will release Spyder 5.0.1 shortly with this fix.

Thanks for reporting!

**Comment by ccordoba12** [comment] 2021-04-07 02:26
Hey @steff456, this was not fixed by PR #15127. To solve this this case we need to name the menu @Serge-45 is referring to, for the changes we did in that PR to take effect.

**Closed** 2021-04-08 03:15 UTC
Labels: component:Variable Explorer, type:Bug
