### ISSUE TITLE
spyder-terminal issue

### ISSUE THREAD

**Issue by dinhe878** [spyder-ide/spyder#5428] opened 2017-10-09 13:21 UTC
## Description

**What steps will reproduce the problem?**

1. Launch anaconda navigator.
2. Launch spyder.

**What is the expected output? What do you see instead?**
Expecting an integrated terminal window, instead only an empty terminal tab appears.

**Please provide any additional information below**

  File "/anaconda2/lib/python2.7/site-packages/spyder_terminal/terminalplugin.py", line 165, in __wait_server_to_start
    self.create_new_term(give_focus=False)
  File "/anaconda2/lib/python2.7/site-packages/spyder_terminal/terminalplugin.py", line 315, in create_new_term
    font=font.family())
  File "/anaconda2/lib/python2.7/site-packages/spyder_terminal/widgets/terminalgui.py", line 63, in __init__
    self.view = TermView(self, term_url=url, handler=self.handler)
  File "/anaconda2/lib/python2.7/site-packages/spyder_terminal/widgets/terminalgui.py", line 147, in __init__
    self.document.profile().clearHttpCache()
AttributeError: 'QWebEngineProfile' object has no attribute 'clearHttpCache'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-10-09 14:09
Thanks for reporting. This is a duplicate of spyder-ide/spyder-terminal#114

**Closed by ccordoba12** 2017-10-09 14:09 UTC
