### ISSUE TITLE
Hide donate window - already a donator!

### ISSUE THREAD

**Issue by jmoraispk** [spyder-ide/spyder#22959] opened 2024-11-12 18:37 UTC
Dear Spyder team,

Great job with 6.0. Here's a small feature request.

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The donate button always appears at the start, but I'm already a donator

### What steps reproduce the problem?

1. Open Spyder

### What is the expected output? What do you see instead?

I'd like a way to tell spyder that I'm already a donator and hide it. 

## Versions

* Spyder version: 6.0.2

**Comment by dalthviz** [comment] 2024-11-12 21:02
Hi @jmoraispk thank you for your feedback! Seems like you are using the latest Spyder release (6.0.2) which should have fixed some issues related with the donation dialog/message appearing more times than needed but seems then that the dialog keeps being triggered for you? :thinking:

Also, pinging @ccordoba12 just in case

**Comment by jmoraispk** [comment] 2024-11-12 22:11
Ah, you are right. It didn't pop up when reopening. I updated and didn't realize the issue could have been fixed during the update! 
Thank you. This can be closed.

**Comment by ccordoba12** [comment] 2024-11-12 23:31
Ok, thanks for the update @jmoraispk. I'm going to close this issue then.

**Closed by ccordoba12** 2024-11-12 23:31 UTC
Labels: component:Main Window, status:Awaiting Followup

**Comment by dalthviz** [comment] 2024-11-18 22:36
Just for tracebility, this is a duplicate of https://github.com/spyder-ide/spyder/issues/22457
