### ISSUE TITLE
Add support for bokeh and interactive matplotlibs in plot viewer

### ISSUE THREAD

**Issue by Illviljan** [spyder-ide/spyder#9423] opened 2019-05-24 22:18 UTC
### matplotlib:
The plot viewer can't be used in interactive mode which limits the possibility to
* Zoom in my plots and scroll along x-axis. 
* Use classes that displays animated plots.

Switch between Automatic and Inline graphics backend. Spyder will switch between a separate, interactive window and showing plots in the plot viewer. Having all the figs in separate windows gets annoying when rerunning your script over and over making small changes.

### bokeh/holoviews:
No plots are displayed in the plot viewer. It works in the (very bright) notebook plugin however. 

## Versions
* Spyder version: 4.0.0b2
* Python version: 3.7.3

**Comment by goanpeca** [comment] 2019-05-24 22:22
Thoughts @jnsebgosselin ?

**Comment by ccordoba12** [comment] 2019-05-25 09:39
That's not possible right now. It requires to build a different kind of viewer, i.e. a viewer for web content. I'm afraid that will come in Spyder 5 because our plate for Spyder 4 is full now.

**Comment by ccordoba12** [comment] 2019-07-05 07:33
Closing as a duplicate of issue #8367.

**Closed by ccordoba12** 2019-07-05 07:33 UTC
Labels: component:Plots, type:Enhancement
