### ISSUE TITLE
Spyder is not opening after updating by conda update

### ISSUE THREAD

**Issue by srvmig** [spyder-ide/spyder#15114] opened 2021-04-05 16:03 UTC
When I am trying to update the conda with ```conda update --all```, spyder 5 is being installed with it. But after updating the Spyder is not opening. I needed to revert the update.

**Comment by axs5489** [comment] 2021-04-05 16:20
Having the same issue, using Win10 and python 3.7.10

**Comment by ccordoba12** [comment] 2021-04-05 18:15
Hey @srvmig, this is a duplicate of issue #15113. It happens because the Anaconda team is doing a very lousy job lately when updating Spyder.

It depends on them to fix it.

**Closed by ccordoba12** 2021-04-05 18:15 UTC
