### ISSUE TITLE
Sypder tutorial does not launch

### ISSUE THREAD

**Issue by gabrieloscaro** [spyder-ide/spyder#3054] opened 2016-03-11 18:32 UTC
It does not open when I click on the help tab on Windows. I use the fr language.

**Comment by Nodd** [comment] 2016-03-11 20:54
Just clicking on the help tab is not enough. You have to go to Help menu > Spyder tutorial so that the documentation is displayed in the help tab.
I'll close this issue, please reopen it there is still a problem.

**Comment by ccordoba12** [comment] 2016-03-11 23:38
@gabrieloscaro, are you clicking on the tutorial hyperlink on the Help text and it's not working?

Also, please don't dismiss the issue template because I now have to ask you:

1. What's your Python version?
2. What's your Spyder version?
3. Are you using PyQt4 or PyQt5 (through WinPython)?

**Comment by gabrieloscaro** [comment] 2016-03-14 08:41
Hi Carlos,

Python 3.5.1 64 bits
Spyder 2.3.8
PyQt4

Yes, using the tutorial hyperlink in the help menu:
[cid:image002.jpg@01D17DD5.9F978B30]

[cid:image003.jpg@01D17DD5.9F978B30]

De : Carlos Cordoba [mailto:notifications@github.com]
Envoyé : samedi 12 mars 2016 00:39
À : spyder-ide/spyder <spyder@noreply.github.com>
Cc : Gabriel GAUTRON <gabriel.gautron@oscaro.com>
Objet : Re: [spyder] Sypder tutorial does not launch (#3054)


@gabrieloscaro<https://github.com/gabrieloscaro>, are you clicking on the tutorial hyperlink on the Help text and it's not working?

Also, please don't dismiss the issue template because I now have to ask you:

  1.  What's your Python version?
  2.  What's your Spyder version?
  3.  Are you using PyQt4 or PyQt5 (through WinPython)?

**Comment by Nodd** [comment] 2016-03-14 09:04
I can't see the images in your post.

Also I can't reproduce the bug (I use the fr locale too, with the same configuration).

**Comment by sylvain-bougnoux** [comment] 2016-03-15 11:15
The tutorial works for me (fr as well), **but I don't have any image**. 
Works mean that it is open and "reSTed" by sphinx. The images appear as a rectangle with a "?" icon. I've checked the path, the images are in "spyder-master\spyderlib\utils\help\static\images" it seems that the path is correctly given (see below)?
http://www.sphinx-doc.org/en/stable/rest.html#images
An image should be visible in section eg "Documentation string formatting".

Maybe the path is given twice? eg in the tutorial
`.. image:: static/images/spyder-nice-docstring-rendering.png`
and in help.py l.767
`img_path = osp.join(tutorial_path, 'static', 'images')`
possibly yielding "tutorial_path/static/images/static/images/*.png"
I've tried to fix this but it didn't work either.

spyder 2.3.8 & dev.
python 2.7.10 32bits
sphinx 1.3.6
sphinx-rtd-theme 0.1.9
PyQt4 4.11.4
windows7

**Comment by sylvain-bougnoux** [comment] 2016-03-16 09:37
I could fix the missing images by removing the img_path or set it to null. Then I saw from the inspect contextual menu (on the tutorial) that the generated html contained twice the folder static in the given path. Therefore by removing "static/" from the tutorial, I could see the images.

Fix in help/tutorial.rst
`.. image:: images/spyder-nice-docstring-rendering.png`
Fix in plugins/help.py l.767
`img_path = '' #osp.join(tutorial_path, 'static', 'images')`

Maybe there is a better way by specifying sphinx the starting directory? Therefore I've not committed this solution.

**Comment by ccordoba12** [comment] 2016-11-01 15:37
This was already fixed in Spyder 3.0

**Closed by ccordoba12** 2016-11-01 15:37 UTC
