### ISSUE TITLE
Dataframe or table viewer defaults to "%.3g" and needs to be editable.

### ISSUE THREAD

**Issue by AlexanderConnelly** [spyder-ide/spyder#3265] opened 2016-06-27 17:00 UTC
## Description of your problem
Issue is with the data frame display that pops out of the variable explorer. I always have to change the float formatting manually every time i wish to view my data as it defaults to "%.3g". i need it in "%.3f" every time i wish to view my data. A default formatting option would be ideal to suit this issue.
**What steps will reproduce the problem?**

1. Create a pandas data frame or numpy array and fill with random values
2. view the data in the variable explorer and pop it open to view the table or dataframe
3. click on format in the bottom left hand screen and notice it defaults to "%.3g"

**What is the expected output? What do you see instead?**
I would expect there to be an option for the variable explorer to input a default format other than "%.3g" this is a common problem with debugging work and needing to see into a few decimal places for accurate results.

**Please provide any additional information below**
please fix/ add desired functionality to Spyder thanks.

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7
* Operating system: Windows 7 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment] 2016-06-27 21:41
This is a duplicate of issue #2728, so I'm closing it.

**Closed by ccordoba12** 2016-06-27 21:41 UTC
Labels: Type-Duplicate
