### ISSUE TITLE
Spyder internal error (beta7)

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#10503] opened 2019-10-23 22:46 UTC
### What steps will reproduce the problem?

I was working with Spyder and this error popped up. I have no idea what triggered it.

### Traceback
```python-traceback
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1134, in process_signatures
    parameter_data = parameters[parameter_idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\logging\__init__.py", line 994, in emit
    msg = self.format(record)
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\logging\__init__.py", line 840, in format
    return fmt.format(record)
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\logging\__init__.py", line 577, in format
    record.message = record.getMessage()
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\app\start.py", line 196, in main
    mainwindow.main()
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\app\mainwindow.py", line 3646, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\app\mainwindow.py", line 3529, in run_spyder
    app.exec_()
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\plugins\completion\plugin.py", line 138, in receive_response
    self.gather_and_send(request_responses)
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\plugins\completion\plugin.py", line 189, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 915, in handle_response
    handler(params)
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1151, in process_signatures
    self.log_lsp_handle_errors("Error when processing signature")
  File "C:\Users\Amin\Anaconda3\envs\pmeal-3.6\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 946, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.6.9
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.15.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-10-23 23:31
Duplicate of #10439. It'll be fixed in our next version.

**Closed by ccordoba12** 2019-10-23 23:31 UTC

**Comment by ccordoba12** [comment] 2019-10-23 23:33
Sorry, it's really a duplicate of issue #10453, but it'll fixed in our next version.
