### ISSUE TITLE
A simple error

### ISSUE THREAD

**Issue by TT70** [spyder-ide/spyder#21612] opened 2023-12-13 06:40 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I would like to run a simple commands:

total = 0
for  num  in   (-22.0, 3.5, 8.1, -10, 0.5):
               if num > 0:
                total = total + num

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

for  num  in   (-22.0, 3.5, 8.1, -10, 0.5):
  Cell In[3], line 1
    for  num  in   (-22.0, 3.5, 8.1, -10, 0.5):
                                               ^
SyntaxError: incomplete input

if num > 0:
  Cell In[4], line 1
    if num > 0:
               ^
SyntaxError: incomplete input

total = total + num
Traceback (most recent call last):

  Cell In[5], line 1
    total = total + num

NameError: name 'num' is not defined

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  Spyder IDE 5.4.3
* Python version: Python 3.11.5 64-bit | Qt 5.15.2 | PyQt5 5.15.10 | Windows 10 
* Qt version: 
* PyQt version: 
* Operating System name/version:  Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.8.0 (OK)
numpy >=1.7                                      :  1.26.2 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  1.11.4 (OK)
sympy >=0.7.3                                    :  1.12 (OK)


```

**Comment by dalthviz** [comment] 2023-12-13 22:48
Hi @TT70 thank you for the feedback! Seems like you are trying to run line by line the code you posted, most probably via the F9 shortcut or the `Run selection or current line` button, right? If that is the case I would say this is related with https://github.com/spyder-ide/spyder/issues/4431 

This is something we will try to tackle in s future Spyder release but for the moment some suggestions for you to run snippets of code could be to use code cell definitions. For more info on that you can check the related Spyder docs page: https://docs.spyder-ide.org/current/faq.html#using-code-cells

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2024-07-06 00:12
Closing as a duplicate of #4431

**Closed by dalthviz** 2024-07-06 00:12 UTC
Labels: resolution:Duplicate, component:Editor, component:IPython Console, status:Awaiting Followup
