### ISSUE TITLE
Anaconda Spyder crash on Windows 10

### ISSUE THREAD

**Issue by melodyun** [spyder-ide/spyder#4784] opened 2017-07-21 02:38 UTC
## Description of your problem
Python stopped working when click "Open Folder" after lunching Spyder.![python stopped](https://user-images.githubusercontent.com/30331740/28446950-919cf34e-6d93-11e7-89ef-ced70560beb5.png)

**What steps will reproduce the problem?**

1. Install Anaconda3, with Python 3.6 on Windows 10
2. Launch Spyder
3. Click "Open Folder"

**Please provide any additional information below**
I had installed python 3.3 and spyder on my computer before.  Before installing anaconda3, I've uninstalled both previous versions, but still not able to use Spyder to open previous python scripts. 

Here is an issue that is exactly the same as mine, but not solved
https://github.com/spyder-ide/spyder/issues/3042

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Win 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by melodyun** [comment] 2017-07-21 02:39
I saw the same issue reported below, but not solved.
https://github.com/spyder-ide/spyder/issues/3042

**Comment by melodyun** [comment] 2017-07-21 03:13
Here's another case, which is the same as I got.
https://github.com/spyder-ide/spyder/issues/3903

Seems the problem is not solved in Spyder 3.1.4

**Comment by andfoy** [comment] 2017-07-21 03:19
@melodyun Thanks for your report, however as you mentioned, this is a Duplicate of #3903

**Comment by ccordoba12** [comment] 2017-07-21 03:28
Closing then.

@melodyun, please read this https://github.com/spyder-ide/spyder/issues/3903#issuecomment-287233402 to know how to fix this problem.

**Comment by ccordoba12** [comment] 2017-07-21 03:28
There's nothing we can do in Spyder to fix it.

**Closed by ccordoba12** 2017-07-21 03:28 UTC
Labels: resolution:Duplicate

**Comment by melodyun** [comment] 2017-07-24 03:15
Hi Carlos,

Thanks for your reply.  I've read case 3903, but it actually didn't solve
the problem.  I've tried to down grade spyder through Anaconda Navigator to
2.x, and anaconda installed another spyder under ~root\Anaconda3\envs\,
 then I update the spyder to version 3.14 again through Anaconda
Navigator.  Now I need to open this new installed spyder from
~root\Anaconda3\envs\spyder\Scripts\spyder.exe.  However, this spyder is
based on python 3.5, not python 3.6.  And all the packages/libraries I
installed with python 3.6 are not there.  Is there any setting I can change
to make the new installed spyder pointing the original python 3.6?

Thanks very much,
Melody

**Comment by ccordoba12** [comment] 2017-07-24 03:37
You need to change your Python interpreter to point to the 3.6 one in

    Preferences > Python intrepreter

**Comment by melodyun** [comment] 2017-07-24 14:32
By changing back to python 3.6, the old problem comes back to. :(  Thanks a
lot.  I'll try other ways.

Thanks,
Melody

**Comment by ccordoba12** [comment] 2017-07-24 15:04
You can install everything you had in your 3.6 in your new 3.5 environment instead.

**Comment by melodyun** [comment] 2017-07-24 15:15
I guess so, but that's gonna be the same as installing a python and a
spyder, nothing benefited from Anaconda.  Thanks!
