### ISSUE TITLE
Missing Dependencies in Anaconda Installation

### ISSUE THREAD

**Issue by JARC99** [spyder-ide/spyder#15267] opened 2021-04-13 13:16 UTC
### What steps will reproduce the problem?

I updated the Spyder version from using the anaconda terminal, once it was done and I openned spyder i got a warning message taht said I was missing this dependency and that I should install it befor using spyder

spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)

**Comment by pythonic2020** [comment] 2021-04-13 14:19
I saw this also using spyder 5 in a conda env running python 3.8.8 with most packages derived from conda-forge.

**Comment by stonebig** [comment] 2021-04-13 14:26
duplicate of https://github.com/spyder-ide/spyder/issues/15091
fixed in Spyder-5.0.1 coming very soon

patch yourself (of the one character typo) if you're in a hurry https://github.com/spyder-ide/spyder/pull/15097/files

**Comment by ccordoba12** [comment] 2021-04-13 14:33
That's correct, this is a duplicate of issue #15091 and it'll be fixed in our next version.

**Closed by ccordoba12** 2021-04-13 14:33 UTC
