### ISSUE TITLE
Outline does not show functions depending on source file path

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#14465] opened 2020-12-19 20:37 UTC
## Problem Description

A code file with special comments, some demarking functions, will not show functions in the outline depending on the path to the source file. The exact same file loaded from a different path into the current project will show functions in the outline. Other files loaded from the current project directory do not show functions in outline.

## code
```
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 26 15:15:14 2020

@author Blaine Bateman
"""
#
# %% libraries
#
#
# %% timestamp
#
# method to generate a string with the date/time in a format
# that is useful to timestamp files
#
def ts(ms = False):
    from datetime import datetime
    ts_str = str(datetime.now())
    ts = ts_str[0:10] + '_' + ts_str[11:13] + '_' + ts_str[14:16] + '_' + ts_str[17:19]
    if ms:
        ts = ts + '_' + str(int(round(int(ts_str[20:30]) / 1000, 0))).zfill(3)
    return ts
#

#
# %% main code
#
print('main code reached')
```

### What steps reproduce the problem?

1.  Open project with path C:\EAF LLC\aa-Analytics and BI\Autonet (Torsten Ostervall)\Autonet\
2.  Load code file C:\EAF LLC\aa-Analytics and BI\Autonet (Torsten Ostervall)\Autonet\no_function_expansion.py
3.  Function in this code is not shown in outline
![image](https://user-images.githubusercontent.com/30508983/102697322-33b01180-41f2-11eb-8000-43df2c749305.png)

4.  Load same code file from C:\EAF LLC\aa-Analytics and BI\Spyder_issues\no_function_expansion.py
5. Function is shown in outline
![image](https://user-images.githubusercontent.com/30508983/102697332-41fe2d80-41f2-11eb-8724-9498fffb278c.png)

### What is the expected output? What do you see instead?

Function should be shown in outline in both cases

```python-traceback

None

```

## Versions

Spyder 4.2.0
Python 3.7.4 64-bit
Qt 5.12.9
PyQt5 5.12.3
Windows 10 

## dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.3.0 (OK)
diff_match_patch >=20181111     :  20181111 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  0.9.2 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.5.2 (OK)
pylint >=1.0                    :  1.9.4 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.2.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.3 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  41.0.0 (OK)
sphinx >=0.6.6                  :  1.8.5 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.14 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.1.4 (OK)
scipy >=0.17.0                  :  1.4.1 (OK)
sympy >=0.7.3                   :  None (NOK)

```

**Comment by Dan-Patterson** [comment] 2020-12-21 01:53
related [https://github.com/spyder-ide/spyder/issues/14413](url) it has 4.2.2 attached to it

**Comment by ccordoba12** [comment] 2020-12-21 02:33
Thanks @Dan-Patterson. Closing then as a duplicate of #14413.

**Closed by ccordoba12** 2020-12-21 02:33 UTC
