### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Fullhealth** [spyder-ide/spyder#5222] opened 2017-09-13 02:55 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "F:\Program Files\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 890, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "F:\Program Files\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 936, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "F:\Program Files\Anaconda3\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "F:\Program Files\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 631, in execute
    self._execute(source, hidden)
  File "F:\Program Files\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6

**Comment by ccordoba12** [comment] 2017-09-13 17:20
What were you doing when this error appeared?

**Comment by ccordoba12** [comment] 2017-09-20 13:27
This is a duplicate of issue #5053.

**Closed by ccordoba12** 2017-09-20 13:27 UTC
