### ISSUE TITLE
CommError upon opening existing console

### ISSUE THREAD

**Issue by benspect** [spyder-ide/spyder#22194] opened 2024-06-22 05:19 UTC
### What steps will reproduce the problem?

error upon opening existing console. existing console is running in WSL
spyder is running as standalone installation in windows 11

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\spyder-6b\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\status.py", line 106, in <lambda>
    lambda sw=shellwidget: self.on_kernel_start(sw)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\spyder-6b\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\status.py", line 134, in on_kernel_start
    mpl_backend = shellwidget.get_matplotlib_backend()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\spyder-6b\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 734, in get_matplotlib_backend
    blocking=True).get_matplotlib_backend()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\spyder-6b\envs\spyder-runtime\Lib\site-packages\spyder_kernels\comms\commbase.py", line 537, in __call__
    raise CommError("The comm is not connected.")
spyder_kernels.comms.commbase.CommError: The comm is not connected.
```

## Versions

* Spyder version: 6.0.0b1  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                   :  3.9.5 (OK)
asyncssh >=2.0.0,<3.0.0           :  2.14.1 (OK)
atomicwrites >=1.2.0              :  1.4.1 (OK)
chardet >=2.0.0                   :  5.2.0 (OK)
cloudpickle >=0.5.0               :  3.0.0 (OK)
cookiecutter >=1.6.0              :  2.6.0 (OK)
diff_match_patch >=20181111       :  20230430 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1  :  8.24.0 (OK)
jedi >=0.17.2,<0.20.0             :  0.19.1 (OK)
jellyfish >=0.7                   :  1.0.3 (OK)
jsonschema >=3.2.0                :  4.22.0 (OK)
keyring >=17.0.0                  :  25.2.1 (OK)
nbconvert >=4.0                   :  7.16.4 (OK)
numpydoc >=0.6.0                  :  1.7.0 (OK)
paramiko >=2.4.0                  :  3.4.0 (OK)
parso >=0.7.0,<0.9.0              :  0.8.4 (OK)
pexpect >=4.4.0                   :  4.9.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.9.8 (OK)
pygments >=2.0                    :  2.18.0 (OK)
pylint >=3.1,<4                   :  3.2.0 (OK)
pylint_venv >=3.0.2               :  3.0.3 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0            :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0        :  2.0.0 (OK)
pyuca >=1.2                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0         :  3.2.3 (OK)
qstylizer >=0.2.2                 :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0          :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0          :  5.5.2 (OK)
qtpy >=2.4.0                      :  2.4.1 (OK)
rtree >=0.9.7                     :  1.2.0 (OK)
setuptools >=49.6.0               :  69.5.1 (OK)
sphinx >=0.6.6                    :  7.3.7 (OK)
spyder_kernels >=3.0.0b6,<3.0.0b7 :  3.0.0b6 (OK)
superqt >=0.6.1,<1.0.0            :  0.6.4 (OK)
textdistance >=4.2.0              :  4.6.2 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  4.0.0 (OK)
yarl >=1.9.4                      :  1.9.4 (OK)
zmq >=24.0.0                      :  26.0.3 (OK)

# Optional:
cython >=0.21                     :  3.0.10 (OK)
matplotlib >=3.0.0                :  3.8.4 (OK)
numpy >=1.7                       :  1.26.4 (OK)
pandas >=1.1.1                    :  2.2.2 (OK)
scipy >=0.17.0                    :  1.13.0 (OK)
sympy >=0.7.3                     :  1.12 (OK)
```

**Comment by ccordoba12** [comment] 2024-06-25 15:45
Hey @benspect, thanks for reporting. This is basically a duplicate of issue #22179, but with a different error.

So, I'm going to close it in favor of that one but we'll be sure to fix it before the first stable version of Spyder 6 is released.

**Comment by benspect** [comment] 2024-06-26 01:07
UNOFFICIAL

No problem, thanks Carlos.
Interestingly, despite the error I can still run the external kernel,  albeit without the variable explorer functioning.

**Comment by ccordoba12** [comment] 2024-07-07 01:23
I found this error is different from #22179, so I'm going to reopen this issue.

**Closed** 2024-07-09 03:23 UTC
Labels: type:Bug, component:IPython Console
