### ISSUE TITLE
Variables explorator

### ISSUE THREAD

**Issue by Reinaldo64** [spyder-ide/spyder#11521] opened 2020-02-11 05:43 UTC
### What steps will reproduce the problem?

CTRL-C in variables explorator after mark all. I want to list every variables, and your contained, for documment the program.

### Traceback
```python-traceback
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1037, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1386, in get_value
    return self.parent().get_value(name)
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1439, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 99, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 542, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 114, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 420, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 480, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_value:

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    self._set_call_return_value(msg_dict, return_value)

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 376, in _set_call_return_value
    comm_id=self.calling_comm_id)

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 245, in _send_message
    data, protocol=self._comms[comm_id]['pickle_protocol'])]

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 1148, in dumps
    cp.dump(obj)

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 491, in dump
    return Pickler.dump(self, obj)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 437, in dump
    self.save(obj)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 518, in save
    self.save_global(obj)

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 899, in save_global
    self.save_dynamic_class(obj)

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 708, in save_dynamic_class
    save(clsdict)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 566, in save_function
    return self.save_function_tuple(obj)

  File "C:\Users\rei8core\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 780, in save_function_tuple
    save(state)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)

  File "C:\Users\rei8core\Anaconda3\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)

TypeError: can't pickle TextCtrl objects

```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.3
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by goanpeca** [comment] 2020-02-11 16:21
@impact27 should we catch this error? this is a perfectly valid thing but should not trigger the dialog. 

If the object is unpickable 🤷‍♂, not much we can do.

**Comment by ccordoba12** [comment] 2020-02-11 17:25
Duplicate of #11489

**Comment by ccordoba12** [comment] 2020-02-11 17:25
> this is a perfectly valid thing but should not trigger the dialog.

Agreed. We need to solve this for 4.1.0

**Closed by ccordoba12** 2020-02-11 17:25 UTC
