### ISSUE TITLE
Spyder dark theme for windows?

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#5826] opened 2017-11-24 20:06 UTC
I'm not sure if the issues are for asking questions, so sorry in advance if we're not supposed to ask questions here. I wonder if I can apply the dark theme to the whole Spyder IDE rather than just the editor.

**Comment by ccordoba12** [comment] 2017-11-25 05:42
Thanks for reporting. This is a duplicate of issue #2350.

**Closed by ccordoba12** 2017-11-25 05:42 UTC
