### ISSUE TITLE
Folding doesn't work proplerly in case we split statement

### ISSUE THREAD

**Issue by MandarSadye** [spyder-ide/spyder#10157] opened 2019-09-08 10:45 UTC
### What steps will reproduce the problem?

Following code is just example code. In this code assigned value of code can be big statement and to manage it people might consider splitting into multiple line

```
def mandar():
    i = 8
    print(i)
    k=  np.zeros((1,
                     2))
    return k
```

This code folds to 
```
def mandar(){
    return k // notice this shouldn't be visible
```

wherelse if I write

```
def mandar():
    i = 8
    print(i)
    k=  np.zeros((1,2))
    return k
```

Then fold works correctly

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by bcolsen** [comment] 2019-09-09 05:26
@MandarSadye Thank you for the bug report!

I am losing this as a duplicate of #9956. Feel free to join the discussion on that thread if you have anything helpful to add.

**Closed by bcolsen** 2019-09-09 05:26 UTC
