### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by Cristian1911** [spyder-ide/spyder#5769] opened 2017-11-15 23:38 UTC
## Description

**What steps will reproduce the problem?**

1. I ran a code in profile mode.
2. I stopped it.
3. It crashed.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\ANA\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "C:\Users\ANA\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "C:\Users\ANA\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "C:\Users\ANA\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "C:\Users\ANA\Anaconda3\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "C:\Users\ANA\Anaconda3\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "C:\Users\ANA\Anaconda3\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ANA\\.spyder-py3\\profiler.results'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
p

**Comment by ccordoba12** [comment] 2017-11-17 00:45
Thanks for reporting. This is duplicate of issue #5587.

We fixed it already, and the fix will be part of our 3.2.5 version.

**Closed by ccordoba12** 2017-11-17 00:45 UTC
