### ISSUE TITLE
Outline exporer items auto expands to follow cursor position in latest 4.x

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#13896] opened 2020-09-30 19:12 UTC
## Problem Description

After PR #13109, the outline explorer is expanded automatically to follow where the cursor is in the editor. I think this is a UX regression to what was done in PR #7962. 

I think that it is ok that the highlight in the Outline explorer follows the cursor position if the item is already visible, but it should not expand items automatically. That is why we have the `Go to cursor position` button.

![outline_explorer_navig](https://user-images.githubusercontent.com/10170372/94729039-1e33f580-032f-11eb-87de-cb96f1f52145.gif)

## Versions

* Spyder version: 4.2.0.dev0 2b8b7f669
* Python version: 3.7.6 64-bit
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by dalthviz** [comment] 2020-09-30 20:24
Thanks @jnsebgosselin for checking into this with the latest changes done! @ccordoba12 @andfoy what do you guys think?

**Comment by andfoy** [comment] 2020-09-30 21:22
I think we can add an option to disable cursor following on the editor

**Comment by jnsebgosselin** [comment] 2020-09-30 21:28
> 
> 
> I think we can add an option to disable cursor following on the editor

Is auto-expanding the outline explorer's item to actively follow the cursor position something that was requested by the users?

**Comment by andfoy** [comment] 2020-09-30 21:30
I migrated that function since it was already on the tests and on the previous codebase

**Comment by andfoy** [comment] 2020-09-30 21:31
Also, I think it makes sense to actively navigate the symbols while the editor cursor is moved

**Comment by jnsebgosselin** [comment] 2020-09-30 21:32
Ah ok, so you can activate/disable it as you whish? It is just a matter of exposing it in the UI? If that is the case, that would be great then. Because the way I'm using the Outline explorer in my workflow, the new behaviour is a real deal breaker for me.

**Comment by andfoy** [comment] 2020-09-30 21:37
Yes, don't worry, I can add an option on PR https://github.com/spyder-ide/spyder/pull/13885

**Comment by jnsebgosselin** [comment] 2020-09-30 21:37
Thanks! 👍

**Comment by jnsebgosselin** [comment] 2020-09-30 21:43
Also, this is only a suggestion, but in order to preserve UX experience across the 4.x series, I would disable the auto-follow/auto-expand feature by default.

Just to clarify, before the changes, the cursor position was reflected in the outline explorer down to the lowest visible item in the tree. The tree would not get auto-expended though.


![outline_explorer_autofollow](https://user-images.githubusercontent.com/10170372/94742805-4c700000-0344-11eb-94fb-b9f20e46d964.gif)

**Comment by ccordoba12** [comment] 2020-09-30 23:36
I think we should preserve the behavior @andfoy added of automatically following the cursor (I find it more useful), but with an option to revert back to the previous behavior.

**Comment by jnsebgosselin** [comment] 2020-10-01 00:11
That is ok, I think it really depends how and for what you use the outline explorer. I use it to navigate between files and class/methods within a file. So if I end up with the items expanded automatically, it becomes impossible to do that, especially if the variables and attributes are shown, since this adds a lot of clutter to the explorer.

**Comment by ccordoba12** [comment] 2020-10-01 00:39
Ok, glad you agreed with my idea!

**Comment by jnsebgosselin** [comment] 2020-10-01 02:58
I would have personally tried to preserve UX consistency in the 4.x series and introduce the new behaviour as default in spyder 5 instead, but that is not a big deal really, especially since you are adding an option. I'm happy with that.

**Comment by jitseniesen** [comment] 2020-10-01 08:17
I agree with @jnsebgosselin , the auto-expand does not look like an improvement for me, and it makes sense not to change the UX in a minor update if it's a change that some users will like and some won't. Just to iterate what he said, the issue is not so much that the outline explorer follows the cursor, but that it expands everything. If the outline explorer would follow the cursor but not expand anything, or it would auto-collapse what it auto-expanded after you move out, it would in my opinion be much less of an issue.

**Comment by ccordoba12** [comment] 2020-11-02 00:53
This was fixed by #13885 by adding an option that prevents following the cursor, so users need to expand the tree automatically.

> it makes sense not to change the UX in a minor update if it's a change that some users will like and some won't. Just to iterate what he said, the issue is not so much that the outline explorer follows the cursor, but that it expands everything.

Unfortunately, it seems that the Outline is broken if we leave that option deactivated (especially if there are cells in the file). So it was my decision to leave it on by default.

**Closed by ccordoba12** 2020-11-02 00:53 UTC
Labels: component:Outline Explorer

**Comment by jnsebgosselin** [comment] 2020-11-05 14:41
> Unfortunately, it seems that the Outline is broken if we leave that option deactivated (especially if there are cells in the file). So it was my decision to leave it on by default.

What do you mean by "broken"? What is broken exactly. That would help me to know this in my testings.

**Comment by ccordoba12** [comment] 2020-11-05 14:45
If you have at least one cell in the file, the Outline will appear with its tree collapsed by that cell and it doesn't display any other content.
