### ISSUE TITLE
Cant view vars

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [spyder-ide/spyder#8611] opened 2019-01-21 06:54 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.7
* Qt Versions: 5.11.1, PyQt5 5.11.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.16.0 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.13.2 (OK)
psutil >=0.3     :  5.4.6 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  1.3 (OK)
cython >=0.21    :  0.29.2 (OK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.2.0 (OK)
pylint >=0.25    :  2.2.2 (OK)

```

**Comment by ccordoba12** [comment] 2019-01-21 13:43
This is a duplicate of #8582.

**Closed by ccordoba12** 2019-01-21 13:43 UTC
