### ISSUE TITLE
Warning on startup for rtree missing and .wer file on Windows when using PyQt 5.15

### ISSUE THREAD

**Issue by Dominiquini** [spyder-ide/spyder#17021] opened 2021-12-14 16:27 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm receiving this error when I start the IDE about missing dependecies (rtree >=0.9.7 : None (NOK))

### What steps reproduce the problem?

1. Start the IDE form the Start menu
2. Wait some time
3. 
### What is the expected output? What do you see instead?
I shouldn't receive any error, becauso I have rtree installed (0.9.7). The package is named "Rtree", maybe this is causing the error???

### Paste Traceback/Error Below (if applicable)
```
You have missing dependencies!

# Mandatory:
rtree >=0.9.7 : None (NOK)

Please install them to avoid this message.

Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you to install all the listed missing dependencies.

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.
```

## Versions

* Spyder version: 5.2.1
* Python version: 3.10.1
* Qt version: 
* PyQt version: 5.15.6
* Operating System name/version: Windows 10 x64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.6.0                      :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.8.9 (OK)
jsonschema >=3.2.0                   :  4.2.1 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.3.0 (OK)
numpydoc >=0.6.0                     :  1.1.0 (OK)
paramiko >=2.4.0                     :  2.8.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.8.0 (OK)
pygments >=2.0                       :  2.10.0 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0                 :  1.3.3 (OK)
pylsp_black >=1.0.0                  :  1.0.1 (OK)
qdarkstyle =3.0.3                    :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.2 (OK)
qtpy >=1.5.0                         :  1.11.3 (OK)
rtree >=0.9.7                        :  None (NOK)
setuptools >=49.6.0                  :  59.6.0 (OK)
sphinx >=0.6.6                       :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0        :  2.2.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.25 (OK)
matplotlib >=2.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.21.4 (OK)
pandas >=1.1.1                       :  1.3.5 (OK)
scipy >=0.17.0                       :  1.7.3 (OK)
sympy >=0.7.3                        :  1.9 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.1.0 :  1.1.0 (OK)


```

**Comment by dalthviz** [comment] 2021-12-15 14:42
Hi @Dominiquini thank you for the feedback. How did you install Spyder? Also, it could be possible for you to reinstall or update `rtree`? This could be a duplicate of #14466 

Let us know if something of the above helps

**Comment by dalthviz** [comment] 2021-12-15 16:55
Thanks for the new info @Dominiquini . That message usually happens due to missing .dlls for `spatialindex`. Checking again your setup seems like you are using Python 3.10, right? Checking PyPI I think there is no wheel for `rtree` for Python 3.10 there so maybe you will need for the reinstall to use as the wheel something like the unofficial one here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree 

My guess is that since there is no wheel in PyPI for Python 3.10 you are getting a `rtree` installation without the .dlls which ends up in a faulty installation of the package and Spyder not being able to recognize it.

Let us know if something of the above helps!

**Comment by Dominiquini** [comment] 2021-12-15 17:05
Thanks for the reply!

I'm using Python 3.10.1 that I recently updated!

I checked and found this 2 dlls in the directory "C:\Developing\Python\Lib\site-packages\rtree\lib":
- spatialindex_c.dll
- spatialindex-64.dll

I uninstalled the 'rtree' that I have installed here and downloaded the version you linked and installed it. The installation appears to have worked, but Spyder continue to throw the same error!

Could the fact that pip lists this extension like 'Rtree' instead of 'rtree' be a problem?

Thanks.

**Comment by dalthviz** [comment] 2021-12-15 17:09
This is quite strange, what happens when you try to import `rtree` inside the Spyder internal console (to see the internal console you can go to `View > Panes` and check `Internal Console`)?

**Comment by Dominiquini** [comment] 2021-12-15 17:25
Appears to be working:
![pythonw_pGvwAmwUX0](https://user-images.githubusercontent.com/1180808/146234035-cf729c21-e372-4504-9472-a48bf8db8c5e.png)

I found another problem: After I closed the IDE, it continue running, but hidden (no visible windows, but listed on the task manager). And exceptions are being created on the "..\WER\ReportArchive\" folder...
![Untitled](https://user-images.githubusercontent.com/1180808/146234620-2b81be88-ace7-4368-b674-3edf968e2260.png)

Is there some log that I can attach here to help?

Thanks

**Comment by dalthviz** [comment] 2021-12-15 17:35
From the cmd you can run spyder with the `--debug-info verbose --debug-output file` flags (the flags while create a `spyder-debug.log` file in the current working directory). So running something like:

    spyder --debug-info verbose --debug-output file

**Comment by Dominiquini** [comment] 2021-12-15 17:54
Log:
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/7721692/spyder-debug.log)

Thanks.

**Comment by dalthviz** [comment] 2021-12-16 16:31
I'm not seeing anything strange in the debug log :/ 

However checking again the info for your setup seems like you are using PyQt 5.15.6 (which is not totally supported right now - PR #16409 is working on that). Not totally sure if could be related with the false positive of `rtree` but just in case could you create an environment with Spyder and PyQt < 5.13? 

Also maybe you could check our [standalone Windows installer (although it comes with Python 3.7.9 bundled)](https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe) and check our docs to [use it with specific packages besides the ones bundled by using the interpreter preference](https://docs.spyder-ide.org/current/faq.html#using-packages-installer)

Let us know if something of the above helps!

**Comment by Dominiquini** [comment] 2021-12-16 16:42
It's weird, but the problem with "rtree" has stopped! I don't remember doing anything but restarting the computer!
But the problem with the IDE staying active after I close it remains! And every time it creates a ".wer" file, that I imagined is a indication of a bug...

Thanks.

**Comment by dalthviz** [comment] 2021-12-16 16:58
> It's weird, but the problem with "rtree" has stopped! I don't remember doing anything but restarting the computer!

Glad that is working now for you @Dominiquini  :+1:

> But the problem with the IDE staying active after I close it remains! And every time it creates a ".wer" file, that I imagined is a indication of a bug..

I think this is related with the usage of PyQt > 5.13 in your setup. Hopefully for the next release we will add support for PyQt 5.15 and prevent that :+1:

Just in case, could you share with us the `.wer` to check why when closing Spyder using PyQt 5.15 the OS is somehow taking the app as crashing?

Thanks !

Pinging @ccordoba12 just in case

**Comment by dalthviz** [comment] 2021-12-16 17:00
Also, just in case, the issue tracking the PyQt 5.15 support is https://github.com/spyder-ide/spyder/issues/12829

**Comment by Dominiquini** [comment] 2021-12-16 17:13
I will try later downgrade my PyQT version!

[Report.wer.txt](https://github.com/spyder-ide/spyder/files/7729196/Report.wer.txt)
I renamed the file so I can upload it here!

Thanks.

**Comment by ccordoba12** [comment] 2022-02-21 22:22
As far as we know, this is a problem with Rtree wheels and it should be solved once their maintainers release a new version. Until then, there's nothing we can do about it, sorry.

**Closed by ccordoba12** 2022-02-21 22:22 UTC
Labels: status:Awaiting Followup
