### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by euchcat** [spyder-ide/spyder#6565] opened 2018-03-01 12:45 UTC
_I Apply the Theme changing from spyder to Zenburn !!_
"self.apply_settings(self.changed_options))
  File "C:\WinPython352_32b\python-3.5.2\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\WinPython352_32b\python-3.5.2\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
"

**Comment by ccordoba12** [comment] 2018-03-01 13:43
Thanks for reporting. This is a duplicate of issue #6519.

**Closed by ccordoba12** 2018-03-01 13:43 UTC

**Comment by euchcat** [comment] 2018-03-01 21:59
thanx for your work ! ;)
