### ISSUE TITLE
Images in docstrings don't render in Help window

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#10849] opened 2019-11-26 15:05 UTC
## Problem Description
The images in my project's docstrings are not rendered in Spyder "Help" window.

### What steps reproduce the problem?
Here's a piece of the docstring in my code:
```
    Which can be quickly visualized using:

    >>> fig = op.topotools.plot_connections(network=gn)

    .. image:: /../docs/static/images/delaunay_network_given_points.png
        :align: center
```

### What is the expected output? What do you see instead?
1. What I got:
![image](https://user-images.githubusercontent.com/14086031/69645164-b9837c80-1033-11ea-8109-3f252c50a158.png)
2. What I expected:
![image](https://user-images.githubusercontent.com/14086031/69645291-f3548300-1033-11ea-918e-b2c8837c9502.png)

## Versions
* Spyder version: 4.0.0b7
* Python version: 3.6.9 64-bit
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 64-bit

### Dependencies
```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.15.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-11-26 15:59
I think you can't use relative paths for your images, just absolute ones. Please try that to see if it fixes your problem.

**Comment by ma-sadeghi** [comment] 2019-11-26 16:39
I tried both absolute wrt my own computer, and relative to the top folder of the project, and neither worked.

**Comment by ccordoba12** [comment] 2019-12-05 21:41
Ok, we'll take a look at this in a future release.

**Comment by steff456** [comment] 2020-08-06 19:46
Hi @ma-sadeghi, I was unable to reproduce your issue in both macOS and Windows,

Please note that the path to the image has to be relative to Spyder's basedir (shown in the top right of the screen)
![image](https://user-images.githubusercontent.com/20992645/89575503-7baa3b00-d7f3-11ea-8222-794290bbdfb2.png)

**Comment by ccordoba12** [comment] 2020-08-07 17:11
@ma-sadeghi, also, this functionality is easier to use if you work with Spyder projects because the basedir is not expected to change.

As a matter of fact, we plan to make this functionality only work with projects in Spyder 5 because it's extremely brittle without them. That's why I'm going to close this issue, so @steff456 can open a new one describing all tasks we need to implement in Spyder 5 to make this functionality work consistently.

**Closed by ccordoba12** 2020-08-07 17:11 UTC
Labels: component:Help, type:Bug

**Comment by ma-sadeghi** [comment] 2020-09-19 14:09
> Hi @ma-sadeghi, I was unable to reproduce your issue in both macOS and Windows,
> 
> Please note that the path to the image has to be relative to Spyder's basedir (shown in the top right of the screen)
> ![image](https://user-images.githubusercontent.com/20992645/89575503-7baa3b00-d7f3-11ea-8222-794290bbdfb2.png)

Thanks for looking into this. Actually, by "project" I meant the "library". 

From the conversations in this thread, I gather that what I want is currently not possible. Is that right?

The reason I ask for this feature is that the way I use Spyder projects is for personal projects in which I use different public libraries. In this case, it's super handy to access the documentation of those libraries including the embedded images, which requires Spyder to look them up relative to the library's path.

Is that something on your radar?

**Comment by ccordoba12** [comment] 2020-09-19 15:05
Could you provide an example of those libraries?

**Comment by ma-sadeghi** [comment] 2020-09-21 19:16
> Could you provide an example of those libraries?

Yep, for instance [here](https://github.com/PMEAL/OpenPNM/blob/46ed0fd6e9521612e8e90658927cfe6e98acc54d/openpnm/network/Cubic.py#L84).

**Comment by ccordoba12** [comment] 2020-09-24 03:36
Ok, thanks for the example. The real problem is that the pages we show in Help are auto-generated in a temporary directory using Sphinx. So Sphinx is unable to find images associated with your docstrings when they contain relative paths.

The only solution that occurs to me is get the `__file__` attribute of the object you're trying to get its docstring for and replace relative paths for absolute ones in its `image` roles. However, that's not an easy task at all and we don't have time to implement it, sorry.

**Comment by ma-sadeghi** [comment] 2020-09-24 13:07
> Ok, thanks for the example. The real problem is that the pages we show in Help are auto-generated in a temporary directory using Sphinx. So Sphinx is unable to find images associated with your docstrings when they contain relative paths.
> 
> The only solution that occurs to me is get the `__file__` attribute of the object you're trying to get its docstring for and replace relative paths for absolute ones in its `image` roles. However, that's not an easy task at all and we don't have time to implement it, sorry.

No worries, thanks for the follow up anyway.
