### ISSUE TITLE
Spyder console cannot print colors

### ISSUE THREAD

**Issue by peendebak** [spyder-ide/spyder#15496] opened 2021-05-04 06:57 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In the Spyder console text does not show any colors. 

### What steps reproduce the problem?

Run the following minimal example in the spyder console (it does require the packages `rich` and `colorama`)
```
# https://pypi.org/project/rich/

from rich import print
print("Hello, [bold magenta]World[/bold magenta]!", ":vampire:", locals())

# https://pypi.org/project/colorama/

from colorama import init
init()

from colorama import Fore, Back, Style
print(Fore.RED + 'some red text')
print(Back.GREEN + 'and with a green background')
print(Style.RESET_ALL)
print('back to normal now')
```

### What is the expected output? What do you see instead?

One would expect to see colored output. For example in `jupyter console` the output is

![image](https://user-images.githubusercontent.com/17724047/116969233-364d6800-acb6-11eb-8de9-5c08e5d12fdb.png)

In the spyder console we have
![image](https://user-images.githubusercontent.com/17724047/116969318-5d0b9e80-acb6-11eb-9e39-5aaea1ebb5e5.png)

(note: the input code is syntax highlighted, but the output does not have color)

### Paste Traceback/Error Below (if applicable)

No traceback available.

## Versions

* Spyder version: 5.0.1
* Python version: 3.8
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.5.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.3 (OK)
pygments >=2.0                :  2.7.2 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  50.3.2 (OK)
sphinx >=0.6.6                :  3.3.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.4 (OK)
zmq >=17                      :  22.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.3 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.1.4 (OK)
scipy >=0.17.0                :  1.6.1 (OK)
sympy >=0.7.3                 :  1.6.2 (OK)

```

**Comment by steff456** [comment] 2021-05-04 18:19
Hi @peendebak,

This seems to be a duplicate of https://github.com/spyder-ide/spyder/issues/1917, you can see in the discussion that there's some instructions on what are the changes that need to be made. This is something low priority to us, so I encourage you to go ahead and contribute to the project with this enhancement.

Thanks for reporting!

**Closed by steff456** 2021-05-04 18:19 UTC
