### ISSUE TITLE
Syntax highlighting for modules

### ISSUE THREAD

**Issue by ReadtheDocumentation** [spyder-ide/spyder#14338] opened 2020-11-29 20:10 UTC
## Problem Description
Spyder is not highlighting anything from external packages

### What steps reproduce the problem?

1. Just open Spyder
2.  Start coding with something like numpy
3.  see that there is no syntax highlighting

### What is the expected output? What do you see instead?
I would expect to see colors for functions and things but I only see the default text color. This is very irritating for me as It decreases the speed at which I can navigate.

**Comment by ccordoba12** [comment] 2020-11-29 23:45
Hey @ReadtheDocumentation, thanks for reporting. This is duplicate of issue #1500 and it'll be fixed in Spyder 5.

**Closed by ccordoba12** 2020-11-29 23:45 UTC
