### ISSUE TITLE
error on kernel restart

### ISSUE THREAD

**Issue by systemd1** [spyder-ide/spyder#14964] opened 2021-03-19 21:56 UTC
### What steps will reproduce the problem?

I reset the kernelI reset the kernel
 self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '625b004c88fd11eb9971107b44927add'

### Traceback
```python-traceback
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '625b004c88fd11eb9971107b44927add'
ERROR:traitlets:Exception in comm_msg for 625b004c88fd11eb9971107b44927add
Traceback (most recent call last):
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '625b004c88fd11eb9971107b44927add'
ERROR:traitlets:Exception in comm_msg for 625b004c88fd11eb9971107b44927add
Traceback (most recent call last):
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '625b004c88fd11eb9971107b44927add'
ERROR:traitlets:Exception in comm_msg for 625b004c88fd11eb9971107b44927add
Traceback (most recent call last):
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "/home/cam/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '625b004c88fd11eb9971107b44927add'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.7.7
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-67-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.18.5 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by juanis2112** [comment] 2021-03-20 00:33
Hi @systemd1 seems like this could be a duplicate of #14886.  To fix it please update qtconsole to version 5.0.3 (a fix for our next release was done by bumping up the required qtconsole version at #14941). Let us know if that solves your issue.

**Comment by richdevboston** [comment] 2021-03-24 00:21
I got the same error Spyder crash dump after restarting the kernel from the Consoles menu in Spyder.   I am running Spyder 4.2.3 on Windows 10, Python 3.7.8, with iPython kernel 7.21.0. 

I will update as you suggested to see if that fixes it.  Thank you.

ERROR:traitlets:Exception in comm_msg for 9d3f4e3e8c3511eb8cb5e4b97a48f811
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\ProgramData\Anaconda3\envs\topss_py37\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '9d3f4e3e8c3511eb8cb5e4b97a48f811'

**Comment by ccordoba12** [comment] 2021-03-25 17:02
This problem will be fixed once Anaconda releases packages for our 4.2.5 version.

**Closed by ccordoba12** 2021-03-25 17:02 UTC
Labels: status:Awaiting Followup
