### ISSUE TITLE
Auto-Completion not invokable after dot (.) operator in v5.4.1

### ISSUE THREAD

**Issue by Tertium-H3GE** [spyder-ide/spyder#20314] opened 2023-01-06 01:11 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Auto-completion cannot be invoked after a dot (.) operator.
Problem occurs in 5.4.1, works fine in 5.4.0.

### What steps reproduce the problem?
1. Create any object, e.g. "foo = 'someText'"
2. Write object's name + dot, e.g. "foo."
3. Try to invoke auto-completion.

### What is the expected output? What do you see instead?
Auto-completion should be invoked and show object's methods.

## Versions

* Spyder version: 5.4.1
* Python version: 3.11 if external, or Spyder's internal interpreter (no change in outcome)
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment] 2023-01-06 16:03
Hey @Tertium-H3GE, thanks for reporting. This is a duplicate of issue #20285 and will be fixed in our next version (5.4.2), to be released in a week and a half due to this a some other regressions.

**Closed by ccordoba12** 2023-01-06 16:03 UTC
