### ISSUE TITLE
Suggestion: Option to rename Consoles

### ISSUE THREAD

**Issue by mat2py** [spyder-ide/spyder#3786] opened 2016-12-05 20:36 UTC
At the moment the consoles are named "Console 1/A", "Console 2/A" etc

It would be good to be able to rename these, i.e. "Testing function", "Converting Data" etc

**Comment by ccordoba12** [comment] 2016-12-06 02:23
Thanks for for reporting, this is a duplicate of issue #1962.

**Closed by ccordoba12** 2016-12-06 02:23 UTC
Labels: Community-Help-wanted, Comp-Console-IPython, Comp-Console-Python, Type-Enhancement
