### ISSUE TITLE
tkinter problem 

### ISSUE THREAD

**Issue by kevenc547** [spyder-ide/spyder#19782] opened 2022-10-10 23:58 UTC
### What steps will reproduce the problem?

tkinter wont be imported in sypderThe Python environment or installation whose interpreter is located at
    /Users/keven/opt/anaconda3/bin/python
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.3.0 and < 2.4.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    conda install spyder-kernels=2.3
or
    pip install spyder-kernels==2.3.*

### Traceback
```python-traceback
Error initializing plugin EntryPoint(name='KWallet', value='keyring.backends.kwallet', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 204, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.kwallet'
Error initializing plugin EntryPoint(name='SecretService', value='keyring.backends.SecretService', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 204, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.SecretService'
Error initializing plugin EntryPoint(name='Windows', value='keyring.backends.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 204, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.Windows'
Error initializing plugin EntryPoint(name='chainer', value='keyring.backends.chainer', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 204, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint(name='libsecret', value='keyring.backends.libsecret', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 204, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.libsecret'
Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 204, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.macOS'
```

## Versions

* Spyder version: 5.3.3 43b5344e5 (standalone)
* Python version: 3.9.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 21.6.0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.14.0 (OK)
keyring >=17.0.0                     :  23.8.2 (OK)
nbconvert >=4.0                      :  7.0.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  65.3.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.4.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2022-10-11 03:50
Hey @kevenc547, thanks for reporting. This is a duplicate of issue #19499 and it'll be fixed in our next version (5.4.0), to be released in a couple of weeks.

**Closed by ccordoba12** 2022-10-11 03:50 UTC
