### ISSUE TITLE
Running user-defined functions on console return only when stopped manually

### ISSUE THREAD

**Issue by yuvalwas** [spyder-ide/spyder#16881] opened 2021-11-21 14:19 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hello,
When calling various user-defined functions or creating instances of user-defined classes from console, it will run indefinitely until I press Stop debugging (Ctrl+Shift+F12) twice, although I wasn't even in debugging mode, just running commands from the console. Furthermore, for some reason the command won't start to run until I press Shift+Enter (pressing Enter will do nothing). When printing the running time at various locations in the function, the times are printed only after pressing Stop debugging twice. Also, the times correspond to regular running time, i.e. very short. So I figure that the function runs and then gets stuck before returning for some reason. This does not happen for every user defined function or class, and I could not identify the pattern. However, when it does happen for some function, it is quite consistent. It always happens only at first call to the function with some set of inputs. If I run the same again, it will run normally. But if I change the inputs to the function, it is stuck again. 
When running the cell/file, this problem does not occur. It also does not occur when running ipython from terminal. It does occur when running it from a jupyter qtconsole. Please tell me If I should delete this and post it on jupyter qtconsole issues instead.
I know this might seem like a strange and maybe ill-described problem, but this problem is bugging me for a very long time, through different versions of anaconda and spyder and on different computers. I appreciate any help.

### What steps reproduce the problem?

1. Define some function
2. Run it from console

### What is the expected output? What do you see instead?
Expected: Normal execution of the command after pressing Enter. Instead the command won't start to run upon Enter and when pressing Shift+Enter it will run indefinitely until pressing Stop debugging twice which will make the function return. Sometimes Ctrl+C also makes the function return.

## Versions

* Spyder version: 5.1.5 None
* Python version: 3.8.12 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-90-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)```

**Comment by ccordoba12** [comment] 2021-11-21 17:21
Hey @yuvalwas, thanks for reporting. You said

> This does not happen for evey user defined function or class, and I could not identify the pattern. However, when it does happen for some function, it is quite consistent

We haven't seen reports of problems like this before, so it's really hard to know what's happening. The problem is that without a clear way to reproduce it, it won't be possible for us or someone else to track it down and fix it.

> It does occur when running it from a jupyter qtconsole

That means the problem is not specific to Spyder, but to the Jupyter architecture.

> Please tell me If I should delete this and post it on jupyter qtconsole issues instead

There's no need of that because we also maintain qtconsole.

> I know this might seem like a strange and maybe ill-described problem, but this problem is bugging me for a very long time, through different versions of anaconda and spyder and on different computers. I appreciate any help.

If you have this problem in other computers, then it could be related to a specific configuration that you're copying from system to system. Do you have configuration files for IPython, IPykernel or another Jupyter project?

**Comment by yuvalwas** [comment] 2021-11-22 08:20
> If you have this problem in other computers, then it could be related to a specific configuration that you're copying from system to system. Do you have configuration files for IPython, IPykernel or another Jupyter project?

No.

I tried isolating what makes the function behave like this. First of all, I think it only happens when the function reads data from some variable which contains all of my data. Sometimes, when I stop a function running after it got stuck, it would return some traceback. For some functions that I use for plotting, it would return the following traceback:

```
Error in callback <function flush_figures at 0x7ff4540bc670> (for post_execute):
Traceback (most recent call last):

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/PIL/ImageFile.py", line 504, in _save
    fh = fp.fileno()

AttributeError: '_idat' object has no attribute 'fileno'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib_inline/backend_inline.py", line 121, in flush_figures
    return show(True)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib_inline/backend_inline.py", line 41, in show
    display(

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/display.py", line 320, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 341, in __call__
    return printer(obj)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/pylabtools.py", line 151, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/image.py", line 1616, in imsave
    image.save(fname, **pil_kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/PIL/Image.py", line 2240, in save
    save_handler(self, fp, filename)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1348, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/PIL/ImageFile.py", line 518, in _save
    l, s, d = e.encode(bufsize)

KeyboardInterrupt
```
or 
```
Error in callback <function flush_figures at 0x7f2f6c4cb670> (for post_execute):
Traceback (most recent call last):

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib_inline/backend_inline.py", line 121, in flush_figures
    return show(True)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib_inline/backend_inline.py", line 41, in show
    display(

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/display.py", line 320, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 341, in __call__
    return printer(obj)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/IPython/core/pylabtools.py", line 151, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    self.figure.draw(renderer)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 2790, in draw
    mimage._draw_list_compositing_images(

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2921, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/collections.py", line 1012, in draw
    super().draw(renderer)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/collections.py", line 389, in draw
    extents = paths[0].get_extents(combined_transform)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/path.py", line 631, in get_extents
    _, dzeros = curve.axis_aligned_extrema()

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/bezier.py", line 295, in axis_aligned_extrema
    Cj = self.polynomial_coefficients

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/matplotlib/bezier.py", line 273, in polynomial_coefficients
    prefactor = (-1)**(i + j) * _comb(j, i)  # j on axis 0, i on axis 1

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2113, in __call__
    return self._vectorize_call(func=func, args=vargs)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2194, in _vectorize_call
    inputs = [array(a, copy=False, subok=True, dtype=object)

  File "/home/yuval/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2194, in <listcomp>
    inputs = [array(a, copy=False, subok=True, dtype=object)

KeyboardInterrupt
```
However, I should note again that this also happen for non-plotting functions and many times does not produce any traceback, just upon manually stopping the function it returns normally.

**Comment by ccordoba12** [comment] 2021-12-01 02:23
> As far as I have noticed, it only happens when the function reads data from some variable I have which contains all of my data

Ok, to me (and also seeing your tracebacks) this implies that the problem is not caused by Spyder. Instead, it seems to be triggered by the libraries you're using in your code. Since you already said that you're also seeing it in Qtconsole, that's the most logical conclusion too.

Sorry for not being more helpful, but I don't know what else we could do for you.

**Comment by ccordoba12** [comment] 2021-12-06 05:09
Closing because I don't think we can do something else about this.

**Closed by ccordoba12** 2021-12-06 05:09 UTC
Labels: status:Awaiting Followup

**Comment by yuvalwas** [comment] 2021-12-06 08:14
Thank you anyway, really appreciate your work. Hopefully you'll also support Julia someday.
