### ISSUE TITLE
Help pane not showing rich text

### ISSUE THREAD

**Issue by raviola** [spyder-ide/spyder#20434] opened 2023-01-25 16:10 UTC
### What steps will reproduce the problem?

1. Install Spyder in a conda environment (using Mambaforge) via `mamba create -n spyder-env spyder -y`
2. Click on an object to instpect then press `Ctrl-I`

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-57-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  66.1.1 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=3.0.0            :  3.6.3 (OK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment] 2023-01-25 17:13
Hey @raviola, thanks for reporting. If you're using this functionality from the editor, then you need to be aware that help can't be retrieved for all objects due to some technical limitations that we hope to sort out in the future. Instead, you can use `Ctrl+I` in the IPython console for the same object, which should work as expected.

Let us know if this is helpful or you need something else from us.

**Comment by raviola** [comment] 2023-01-25 17:53
> Hey @raviola, thanks for reporting. If you're using this functionality from the editor, then you need to be aware that help can't be retrieved for all objects due to some technical limitations that we hope to sort out in the future. Instead, you can use `Ctrl+I` in the IPython console for the same object, which should work as expected.

Hi @ccordoba12! Sadly, I have the same issue when inspecting an object from the IPython console.

**Comment by ccordoba12** [comment] 2023-01-27 04:35
Ok, then this seems like a duplicate of issue #20358. There's a workaround on it, so please follow it and let us if it works for you.

**Comment by tlunet** [comment] 2023-02-03 15:26
Got exactly the same problem on my Ubuntu 22.04 (Python 3.10.8, Spyder 5.4.2). Reverting to Python 3.9 and Spyder 5.3.3 made the problem go away. However, I do have the same installation (Python 3.10.8, Spyder 5.4.2) on my office compute (OpenSuse 15.4), which has exactly the same packages version for all spyder dependencies and no issue with rich text help there. 

So it's maybe OS-related ... (Ubuntu 22.04 uses Linux 5.15.0 kernal, while OpenSuse 15.4 uses 5.14.21)

**Comment by ccordoba12** [comment] 2023-02-03 15:54
Thanks for the additional details @tlunet. There seems to be a problem with the Conda-forge packages but not with the conda ones.  There are more details about that on issue #20358, so please continue the discussion there (I'm going to close this issue and reopen that one).

**Closed by ccordoba12** 2023-02-03 15:54 UTC
Labels: status:Awaiting Followup

**Comment by tlunet** [comment] 2023-02-03 15:56
> Thanks for the additional details @tlunet. There seems to be a problem with the Conda-forge packages but not with the conda ones. There are more details about that on issue #20358, so please continue the discussion there (I'm going to close this issue and reopen that one).

:laughing: did that at first, but realized I may have more success commenting on this one ...

**Comment by ccordoba12** [comment] 2023-02-03 15:56
No problem 👍🏽
