### ISSUE TITLE
Dataframe editor should have a reload button

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#10431] opened 2019-10-16 15:42 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The dataframe editor, which can become out of sync with the displayed variable, should have a "sync" button to update its content without losing scroll position, after the variable has changed.

### What steps reproduce the problem?

I have got a large dataframe open during debugging, and scrolled to an interesting position.
After single-stepping in the code, the dataframe has changed, and I want to see the changes in the editor.

### What is the expected output? What do you see instead?
I would expect a button to reload the variable into the dataframe editor without losing scroll position.
Now, I have to close and reopen the dataframe editor, losing all its state.

## Versions

* Spyder version: 3.2.6
* Python 3.6.8 64bits, Qt 5.9.5, PyQt5 5.10.1 on Linux

**Comment by ccordoba12** [comment] 2019-10-16 16:17
Duplicate of #6325

**Closed by ccordoba12** 2019-10-16 16:17 UTC
Labels: component:Variable Explorer, type:Enhancement
