### ISSUE TITLE
Shortcut to toggle case

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2601] opened 2015-08-08 14:05 UTC
Ctrl + U = convert selected case to upper
Ctrl + shift + u = covert selected case to lower

**Comment by ccordoba12** [comment] 2015-08-08 15:07
Someone will have to implement it :-)

**Comment by thewhitetulip** [comment] 2015-08-09 07:30
I can implement but I just can't understand how spyder works, I went through the entire codebase, I want to also work on the issue about reopening last tabs, if @goanpeca or you can guide me, I'll submit a PR as soon as possible.

**Comment by Nodd** [comment] 2015-09-23 09:03
This is a duplicate of #1669, I'll close this one.
Working with the editor is quite complicated because there is a lot of code around it, but the functionality itself is not that hard. You have to understand how QTextCursor works in Qt first, however.

**Closed by Nodd** 2015-09-23 09:03 UTC
Labels: Editor, enhancement, help wanted

**Comment by gamesbook** [comment] 2016-10-30 07:56
What is the status of this?  #2601 and #1669 cross-reference each but both are closed?
