### ISSUE TITLE
Listing of definitions and classes in outline pane  not working in spyder 5.2.1 if a python file in Project mode is open

### ISSUE THREAD

**Issue by arul67800** [spyder-ide/spyder#17041] opened 2021-12-16 18:22 UTC
Steps to Reproduce:
If we open a python file in a project

Description:
Outline pane is listing the definitions and classes if open as a individual file, but if we try to add a folder as a project or create as project, and open the same file by clicking it from the project tab, the definitions and classes were not listed in outline pane

**Comment by ccordoba12** [comment] 2021-12-16 22:03
Hey @arul67800, thanks for reporting. This is probably a duplicate of issue #16406; we'll try to fix it soon (i.e. in the next couple of months).

**Closed by ccordoba12** 2021-12-16 22:03 UTC

**Comment by arul67800** [comment] 2021-12-17 05:07
Ok..The problem occurs only when we select a python file in the project pane at the secondary level, ie when we select a file from a folder in folder..keep a note of it..my project a very big and uses a folder in folder approach and its very much annoying to find functions in it without outline pane
