### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#9581] opened 2019-06-14 20:03 UTC
## Description
Issue reporter opens upon running Spyder. Note that I've already tried updating jedi as recommended by previously reported issues with the same title. Indeed, attempting to update jedi 0.13.3 actually _removes_ spyder without changing jedi the version.

### What steps will reproduce the problem?
Start spyder form terminal
```
>> conda activate spyder-beta
>> spyder
```
spyder-beta anaconda environment has only spyder 4.0.0.b2 installed from the spyder-ide anaconda channel.

### Traceback
```python-traceback
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/python_ls.py", line 160, in m_initialize
    self.config = config.Config(rootUri, initializationOptions or {}, processId)
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/config/config.py", line 63, in __init__
    self._update_disabled_plugins()
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/config/config.py", line 140, in _update_disabled_plugins
    plugin for name, plugin in self.plugin_manager.list_name_plugin()
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/config/config.py", line 141, in <listcomp>
    if not self.settings().get('plugins', {}).get(name, {}).get('enabled', True)
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/config/config.py", line 102, in settings
    source_conf = source.user_config()
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/config/pycodestyle_conf.py", line 24, in user_config
    config = self.read_config_from_files(USER_CONFIGS)
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/site-packages/pyls/config/source.py", line 42, in read_config_from_files
    found_files.extend(config.read(filename))
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/Users/rclary/anaconda3/envs/spyder-beta/lib/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pygments >=2.0     :  2.4.0 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
psutil >=0.3       :  5.6.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  None (NOK)
numpy >=1.7        :  None (NOK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.4.4 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  None (NOK)
pylint >=0.25      :  2.3.1 (OK)
```

### Environment list

```
# packages in environment at /Users/rclary/anaconda3/envs/spyder-beta:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0  
appnope                   0.1.0                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.2.5                    py37_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
autopep8                  1.4.4                      py_0  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
bcrypt                    3.1.6            py37h1de35cc_0  
bleach                    3.1.0                    py37_0  
ca-certificates           2019.5.15                     0  
certifi                   2019.3.9                 py37_0  
cffi                      1.12.3           py37hb5b8e2f_0  
chardet                   3.0.4                    py37_1  
cloudpickle               1.0.0                      py_0  
cryptography              2.6.1            py37ha12b0ac_0  
dbus                      1.13.6               h90a0687_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.6.0                      py_0  
docutils                  0.14                     py37_0  
entrypoints               0.3                      py37_0  
expat                     2.2.6                h0a44026_0  
future                    0.17.1                   py37_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imagesize                 1.1.0                    py37_0  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.5.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
isort                     4.3.19                   py37_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.0.1                    py37_0  
jupyter_client            5.2.4                    py37_0  
jupyter_core              4.4.0                    py37_0  
keyring                   18.0.0                   py37_0  
lazy-object-proxy         1.4.1            py37h1de35cc_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
markupsafe                1.1.1            py37h1de35cc_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
numpydoc                  0.9.1                      py_0  
openssl                   1.1.1c               h1de35cc_1  
packaging                 19.0                     py37_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
paramiko                  2.4.2                    py37_0  
parso                     0.4.0                      py_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pip                       19.1.1                   py37_0  
pluggy                    0.11.0                     py_0  
prompt_toolkit            2.0.9                    py37_0  
psutil                    5.6.2            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
pyasn1                    0.4.5                      py_0  
pycodestyle               2.5.0                    py37_0  
pycparser                 2.19                     py37_0  
pydocstyle                3.0.0                    py37_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.4.0                      py_0  
pylint                    2.3.1                    py37_0  
pynacl                    1.3.0            py37h1de35cc_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.14.11          py37h1de35cc_0  
pysocks                   1.7.0                    py37_0  
python                    3.7.3                h359304d_0  
python-dateutil           2.8.0                    py37_0  
python-jsonrpc-server     0.1.2                      py_0    spyder-ide
python-language-server    0.24.0                   py37_0    spyder-ide
python.app                2                        py37_9  
pytz                      2019.1                     py_0  
pyzmq                     18.0.0           py37h0a44026_0  
qdarkstyle                2.6.8                      py_0    spyder-ide
qt                        5.9.7                h468cd18_1  
qtawesome                 0.5.7                    py37_1  
qtconsole                 4.4.4                      py_0  
qtpy                      1.7.1                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.21.0                   py37_0  
rope                      0.14.0                     py_0  
setuptools                41.0.1                   py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
snowballstemmer           1.2.1                    py37_0  
sphinx                    2.0.1                      py_0  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
spyder                    4.0.0b2                  py37_0    spyder-ide
spyder-kernels            1.2.0                    py37_0    spyder-ide
sqlite                    3.28.0               ha441bb4_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.2            py37h1de35cc_0  
traitlets                 4.3.2                    py37_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.33.4                   py37_0  
wrapt                     1.11.1           py37h1de35cc_0  
wurlitzer                 1.0.2                 py37_1000    spyder-ide
xz                        5.2.4                h1de35cc_4  
yapf                      0.27.0                     py_0  
zeromq                    4.3.1                h0a44026_3  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by ccordoba12** [comment] 2019-06-14 20:30
Thanks for reporting. This is a duplicate of issue #9493.

**Closed by ccordoba12** 2019-06-14 20:30 UTC
