### ISSUE TITLE
Error when trying to access Preferences dialog the first time

### ISSUE THREAD

**Issue by DManowitz** [spyder-ide/spyder#19136] opened 2022-08-21 18:21 UTC
### What steps will reproduce the problem?

1. Open Spyder
2. Try to open Preference dialog via button or Tools / Preferences menu item
3. Observe error

NOTE: This is the same error as reported in issue #19134, but with a slightly different Python & Spyder configuration

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\manow\miniconda3\envs\py38_ml_test_TfGpuMain\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "C:\Users\manow\miniconda3\envs\py38_ml_test_TfGpuMain\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "C:\Users\manow\miniconda3\envs\py38_ml_test_TfGpuMain\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 63, in create_dialog
    page.initialize()
  File "C:\Users\manow\miniconda3\envs\py38_ml_test_TfGpuMain\lib\site-packages\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "C:\Users\manow\miniconda3\envs\py38_ml_test_TfGpuMain\lib\site-packages\spyder\api\plugin_registration\_confpage.py", line 78, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.3.2  (conda)
* Python version: 3.8.13 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                         :  1.4.1 (OK)
chardet >=2.0.0                              :  5.0.0 (OK)
cloudpickle >=0.5.0                          :  2.1.0 (OK)
cookiecutter >=1.6.0                         :  2.1.1 (OK)
diff_match_patch >=20181111                  :  20200713 (OK)
intervaltree >=3.0.2                         :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0                      :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                        :  0.18.1 (OK)
jellyfish >=0.7                              :  0.9.0 (OK)
jsonschema >=3.2.0                           :  3.2.0 (OK)
keyring >=17.0.0                             :  18.0.1 (OK)
nbconvert >=4.0                              :  6.5.1 (OK)
numpydoc >=0.6.0                             :  1.4.0 (OK)
paramiko >=2.4.0                             :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                         :  0.8.3 (OK)
pexpect >=4.4.0                              :  4.8.0 (OK)
pickleshare >=0.4                            :  0.7.5 (OK)
psutil >=5.3                                 :  5.9.1 (OK)
pygments >=2.0                               :  2.12.0 (OK)
pylint >=2.5.0;<3.0                          :  2.13.9 (OK)
pyls_spyder >=0.4.0                          :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                         :  1.5.0 (OK)
pylsp_black >=1.2.0                          :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0                    :  3.0.3 (OK)
qstylizer >=0.1.10                           :  0.2.1 (OK)
qtawesome >=1.0.2                            :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0                     :  5.3.1 (OK)
qtpy >=2.1.0                                 :  2.1.0 (OK)
rtree >=0.9.7                                :  1.0.0 (OK)
setuptools >=49.6.0                          :  59.8.0 (OK)
sphinx >=0.6.6                               :  5.1.1 (OK)
spyder_kernels >=2.3.2;<2.4.0                :  2.3.2 (OK)
textdistance >=4.2.0                         :  4.3.0 (OK)
three_merge >=0.1.1                          :  0.1.1 (OK)
watchdog >=0.10.3                            :  2.1.9 (OK)
zmq >=22.1.0                                 :  23.2.0 (OK)

# Optional:
cython >=0.21                                :  0.29.32 (OK)
matplotlib >=3.0.0                           :  3.4.3 (OK)
numpy >=1.7                                  :  1.21.4 (OK)
pandas >=1.1.1                               :  1.3.5 (OK)
scipy >=0.17.0                               :  1.7.3 (OK)
sympy >=0.7.3                                :  1.10.1 (OK)

# Spyder plugins:
spyder_line_profiler.spyder.plugin 0.3.1     :  0.3.1 (OK)
spyder_modelx.plugins.analyzer_plugin 0.13.0 :  0.13.0 (OK)
spyder_modelx.plugins.dataview_plugin 0.13.0 :  0.13.0 (OK)
spyder_modelx.plugins.mxplugin 0.13.0        :  0.13.0 (OK)
spyder_screencast.plugin 0.0.17              :  0.0.17 (OK)
spyder_terminal.terminalplugin 1.2.2         :  1.2.2 (OK)
spyder_unittest.unittestplugin 0.5.0         :  0.5.0 (OK)
```

**Comment by ccordoba12** [comment] 2022-08-21 18:54
Closing as a duplicate of issue #19134.

**Closed by ccordoba12** 2022-08-21 18:54 UTC
