### ISSUE TITLE
LSP Python broke

### ISSUE THREAD

**Issue by CrimsonNightZero** [spyder-ide/spyder#13368] opened 2020-07-24 02:51 UTC
### What steps will reproduce the problem?

LSP Python keep restarting.LSP Python keep restarting.

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.7
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  None (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.3 (OK)
pyls >=0.31.9;<0.32.0          :  None (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.17.0 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

# Spyder plugins:
spyder_unittest                :  0.4.0 (OK)
```

**Comment by andfoy** [comment] 2020-07-24 03:45
Hi @CrimsonNightZero, some initialization errors with the PyLS were fixed on Spyder 4.1.4, please update your Spyder using 

```bash
conda update anaconda
conda install spyder=4.1.4
```

Please report here if your errors were fixed

**Comment by CrimsonNightZero** [comment] 2020-07-25 11:58
Already update Spyder.

Error message:

(base) C:\Users\micke>spyder
Traceback (most recent call last):
  File "C:\Users\micke\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3638, in run_spyder
    main.setup()
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 984, in setup
    plugin = module.PLUGIN_CLASS(self)
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\plugins\pylint\plugin.py", line 60, in __init__
    top_max_entries=MAX_HISTORY_ENTRIES)
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 252, in __init__
    self.set_filename(f)
  File "C:\Users\micke\anaconda3\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 279, in set_filename
    self.curr_filenames.pop(index)
IndexError: pop index out of range

**Comment by ccordoba12** [comment] 2020-07-26 16:33
Please close Spyder, open the Anaconda Prompt and run there

    spyder --reset

and try again. That should fix your problem.

**Comment by CrimsonNightZero** [comment] 2020-07-26 22:12
Spyder --reset is work.
LSP Python status is down.

<img width="252" alt="擷取" src="https://user-images.githubusercontent.com/31186669/88490714-1f177680-cfd0-11ea-9988-4e71b3bed30e.PNG">

**Comment by ccordoba12** [comment] 2020-07-27 00:16
That's most probably caused by installation issues on your side. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to fix them.

**Comment by CrimsonNightZero** [comment] 2020-07-28 15:38
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/4989404/spyder-debug.log)

**Comment by ccordoba12** [comment] 2020-07-28 20:41
@CrimsonNightZero, did you uninstall and reinstall Anaconda following the instructions in our video?

**Comment by CrimsonNightZero** [comment] 2020-08-01 07:45
@ccordoba12 Yes, I create test envs, still has the same problem.
conda create -n test python=3.7.7
conda activate test
pip install spyder 
pip install package

**Comment by ccordoba12** [comment] 2020-08-01 14:10
Please see the video. It's title is "Spyder says: Don't mix pip and conda". And that's what you're doing above.

Besides, if you're using Anaconda, you don't need to use pip to install Spyder.

**Comment by CrimsonNightZero** [comment] 2020-08-01 15:21
This is not working.
conda create -n test python=3.7.7
conda activate test2
Execute spyder

Finally reinstall conda, LSP Python is work.

**Comment by ccordoba12** [comment] 2020-08-01 16:14
I'm really glad you finally found a way to solve your problem!

**Closed by ccordoba12** 2020-08-01 16:14 UTC
Labels: status:Awaiting Followup
