### ISSUE TITLE
Popup telling me there is a new version has no hyperlinks, and ok button also doesn't work.

### ISSUE THREAD

**Issue by KidPluto** [spyder-ide/spyder#3914] opened 2017-01-05 04:14 UTC
## Description

**What steps will reproduce the problem?**

1. Open the program
2. I get this popup
![capture01](https://cloud.githubusercontent.com/assets/13398044/21668798/38eeb3e6-d2d3-11e6-8ab0-921ad018719d.PNG)
3. The two words in blue & underlined are not hyperlinks, and the OK button does nothing

**What is the expected output? What do you see instead?**
Underlined works in blue are hyperlinks.  Ok buttons do something.

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by jitseniesen** [comment] 2017-01-05 08:38
Thanks for your report. This problem is fixed in the latest version (Spyder 3.0.2) but of course you need to install that version to see this!

In case you need information on how to upgrade, the links in the window should point to https://github.com/spyder-ide/spyder/releases and http://pythonhosted.org/spyder/installation.html

I am closing this as a duplicate of #3609.

**Closed by jitseniesen** 2017-01-05 08:38 UTC
