### ISSUE TITLE
Low resolution in matplotlib graphs

### ISSUE THREAD

**Issue by Mark531** [spyder-ide/spyder#11409] opened 2020-01-27 15:21 UTC
## Problem Description
The matplotlib graphs are created in low resolution. It's just a problem of display since the copy/paste of the image is good.

### What steps reproduce the problem?
1. Create a graph with matplotlib

### What is the expected output? What do you see instead?
I expect a correct resolution but I hardly see the labels and figures. I tried to change the configuration of backend figures in the Preferences menu, to no avail.

### Paste Traceback/Error Below (if applicable)
![image](https://user-images.githubusercontent.com/17707763/73186825-b0d92080-4120-11ea-8b14-94ff6d46ee2a.png)

## Versions
* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Win10

### Dependencies
```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-27 15:46
Duplicate of #9148

**Comment by ccordoba12** [comment] 2020-01-27 15:46
We'll try to fix this in a future release.

**Closed by ccordoba12** 2020-01-27 15:46 UTC
