### ISSUE TITLE
Kernel constant Crash

### ISSUE THREAD

**Issue by Stasello21** [spyder-ide/spyder#7484] opened 2018-07-17 16:30 UTC
Dear Sir Madam,

I have recently noticed that my Kernel at some point simply stops resonding and I got nothing else but to restart the kernel, loosing all the data
It happens usually when I go into debugger mode placing this line in the text "import pdb; pdb.set_trace()"

at some point i can move my cursor in the kernel after some operation in debugger was done but hitting enter does not do anything nor does any other command like "Cntrl - C".  

When I try to press the red square on top right force it to stop - it darkens but the procedure is not stopped and it continues to be stalled. Only after clicking red "x" in the consoles tab - does it reload and I can try again. It crashed almost every 3rd time i run kernel - quite annoying if you got to run it 60 times. 

What to do in this case?

thank you
Stas

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-17 16:35
You have to give us a very simple (please don't send us your entire simulation/data analysis stuff) and reproducible code example that always shows this problem, so we can test it and reproduce it in our side

Else, we can't help you, sorry.

**Comment by Stasello21** [comment] 2018-07-25 12:06
Hello Carlos! 
now I see your reply. Is there a way I could send you the link to the code in some sort of personal message or email?  I am a bit worried of sending around codes that I have been working on for long time.

**Comment by ccordoba12** [comment] 2018-07-25 14:32
> Is there a way I could send you the link to the code in some sort of personal message or email?

Sure, please look at my Github profile page, there's my email.

> but in practice it can even et stich with very small code as well but I need to think how to find the small version of what I have

Please do, it'll make easier for me to help you.

**Comment by Stasello21** [comment] 2018-07-27 10:52
Dear Carlos, 
I actually think I found the issue but I am not sure at which stage it forces spyder kernel to stall. 
It has to do with Cntrl-C pressing during debugging. The reason is that Cntrl-C is assigned to kernel halt, if I am not mistaken, but some people like me use it also to copy paste parts of text in and out of many windows. So using Cntrl-Shift -C would be a solution during use of debugging to copy text. Is there another solution? maybe right click copy Raw text?

**Comment by ccordoba12** [comment] 2018-07-27 15:08
> I actually think I found the issue

Great!

> So using Cntrl-Shift -C would be a solution during use of debugging to copy text. Is there another solution? maybe right click copy Raw text?

Yes, that's the only other solution.

I'm closing this because it's solved now.

**Closed by ccordoba12** 2018-07-27 15:08 UTC
Labels: status:Awaiting Followup
