### ISSUE TITLE
dependencies warning with Spyder5

### ISSUE THREAD

**Issue by ctdarwell** [spyder-ide/spyder#15153] opened 2021-04-07 06:41 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Install Spyder5
2. 
3. 

### What is the expected output? What do you see instead?
I get a warning about missing dependencies: `spyder_kernels >=2.0.1,2.1.0 : 2.0.1 (NOK)`

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by 93chanle** [comment] 2021-04-07 07:39
I have the same issue after installing Spyder 5.0.0, also ``rtree >=0.8.3 : None (NOK)``

**Comment by dkmj** [comment] 2021-04-07 08:04
I have same issue, on both Mac and windows. Spyder 5.0 started fine one time on windows, but failed 2nd time. On mac the issue is persistent, but I have yet to understand the impact.  

"I get a warning about missing dependencies: spyder_kernels >=2.0.1,2.1.0 : 2.0.1 (NOK)"

if I were to try to resolve, how/where?

**Comment by thistlillo** [comment] 2021-04-07 08:55
I get the same message even if 
- I installed those kernels with pip
- I updated conda
- I installed those kernels with conda

**Comment by ccordoba12** [comment] 2021-04-07 16:27
Hey all, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

In the meantime, please ignore that message, it's a false alarm.

**Closed by ccordoba12** 2021-04-07 16:27 UTC
