### ISSUE TITLE
MacOS Preferences option not available

### ISSUE THREAD

**Issue by lukeallpress** [spyder-ide/spyder#15656] opened 2021-05-19 18:06 UTC
## Problem Description
When I open a new instance of Spyder (and sometimes even after it's been open for awhile) the Preferences menu item isn't available. If I scroll over all menus with my cursor, Preferences shows up but isn't clickable. After selecting away from menus, then trying again, I can access Preferences. The keyboard shortcut also doesn't work until I scroll over all menus.

### What steps reproduce the problem?
See screen recording.
![spyder_preferences](https://user-images.githubusercontent.com/22620095/118861849-d77d1680-b891-11eb-86a9-7078e63d550b.gif)

## Versions

* Spyder version: 5.0.3 (has been happening since at least 5.0)
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Darwin 20.3.0 (Big Sur 11.2.3)

### Dependencies

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  56.2.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by dalthviz** [comment] 2021-05-19 19:00
Hi @lukeallpress for the feedback! I was able to reproduce this. We will check it in a future release :+1:

Also, just in case, @steff456 @juanis2112 is this something that has been already reported/you are able to reproduce?

**Comment by steff456** [comment] 2021-05-19 19:03
I made a change in the Qt roles for preventing this from happening, but I'm not sure why it is still an issue. @lukeallpress are you using anaconda installation or the mac installer?

**Comment by dalthviz** [comment] 2021-05-19 19:10
Just in case, testing this I used the mac installer and I was able to reproduce it (in a virtual machine)

**Comment by ccordoba12** [comment] 2021-05-23 19:19
This is a duplicate of #14917.

**Closed by ccordoba12** 2021-05-23 19:19 UTC
Labels: OS:MacOS, type:Bug
