### ISSUE TITLE
Starting a new console loses `PYTHONPATH` in Spyder 5.3.2

### ISSUE THREAD

**Issue by drlakecoder** [spyder-ide/spyder#18942] opened 2022-08-04 20:55 UTC
## Problem Description
In 5.3.2, if you open a new Ipython console, it will NOT carry the PYTHONPATH environment variable which we need for custom projects/packages.  The environment variables work in the first console that was opened when spyder starts, but it goes missing when you open more console (default setting), see screenshot
<img width="753" alt="image" src="https://user-images.githubusercontent.com/93505316/182950777-6c8d8492-092c-4fa2-83de-7b9da37470fb.png">

The same issue does NOT exist in 5.3.1 (see screenshot)
<img width="1749" alt="image" src="https://user-images.githubusercontent.com/93505316/182950573-a04e7cbd-1792-430a-88e1-3631c4c26028.png">

### What steps reproduce the problem?

1. start spyder 5.3.2
2. import os; os.environ['PYTHONPATH']  # this works
3. open another console with default settings
4. import os; os.environ['PYTHONPATH'] throws KeyError 'PYTHONPATH'

### What is the expected output? What do you see instead?
PYTHONPATH variable 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by drlakecoder** [comment] 2022-08-04 22:38
btw: I can confirm downgrading 5.3.2 back to 5.3.1 solves this problem, so it does look like a new bug introduced in 5.3.2

**Comment by dalthviz** [comment] 2022-08-05 15:54
Hi @drlakecoder thank you for the feedback! I think this is indeed an issue and I think this was mentioned at https://github.com/spyder-ide/spyder/issues/18821#issuecomment-1197438944 . We will try to come with a fix for a future release 👍🏼

**Comment by drlakecoder** [comment] 2022-08-06 14:33
Thank you!

**Comment by mrclary** [comment] 2022-08-27 04:23
@drlakecoder, can you tell us which operating system you are using and whether you are installing Spyder via conda or our standalone installers?

**Comment by mrclary** [comment] 2022-08-27 18:32
For macOS standalone application 5.3.2 and bootstrap from latest source, I cannot reproduce the OP. There is no difference for `sys.path` or `PYTHONPATH` environment variable between the first IPython Console and new ones. However, I do see a rogue path injected into both `sys.path` and `PYTHONPATH` environment variable for _all_ IPython Consoles; this is coming from `spyder_pythonpath` in Spyder's `transient.ini` config file. Likely PYTHONPATH Manager is not correctly updating this configuration value and it should be fixed.

**Comment by mrclary** [comment] 2022-08-27 18:51
@drlakecoder, additionally, are you running in the default Spyder environment or are you using an external python environment for your IPython Console?

Just to let you know what is should be happening with PYTHONPATH since 5.3.2. The system PYTHONPATH environment variable should not be automatically injected into `sys.path` and `PYTHONPATH` environment variables in the IPython Console. PYTHONPATH handling was inconsistent previous to 5.3.2 and was intended to be handled in a much more uniform and transparent way for 5.3.2. All PYTHONPATH paths are sourced from Spyder's PYTHONPATH Manager. Whatever is in there is what you should always get in your IPython Consoles. For those who also need to use paths from the system PYTHONPATH environment variable, the PYTHONPATH Manager has an import feature to bring those in. You should only have to import once; the PPM paths should persist across Spyder sessions (although there may be a bug with the configuration write as I mentioned in a previous comment).

I am still curious about how your `sys.path` is different for the initial IPython Console than subsequently open Consoles. You may want to try resetting Spyder to factory defaults and test if this still occurs. You can do this by renaming your configuration directory (don't delete it in case you have settings you want to keep), located at `~/.spyder-py3` (Windows, macOS) or `~/spyder-py3` (Linux), if I'm not mistaken.

**Comment by mrclary** [comment] 2022-09-04 04:52
I cannot reproduce the OP.

In my Windows VM, working from the latest commit (948f2ebf), launching from conda, with `PYTHONPATH` defined in both "User variables" and "System variables", I do not have `PYTHONPATH` defined in `os.environ` in the first console, or any subsequent consoles. This is consistent with the intended behavior beginning with 5.3.2. `PYTHONPATH` is importable into the PYTHONPATH Manager, after which it will be injected into all IPython Consoles.

If the issue still persists for @drlakecoder, I suggest renaming Spyder's configuration directory (`.spyder-py3`) to see if that resolves the discrepency, or upgrading to 5.3.3 if the issue has inadvertently been fixed.

Nevertheless, I believe that Spyder 5.4.0 (the next release) will restore the previous behavior of automatically importing the user's `PYTHONPATH`.

I will close this issue. However, @drlakecoder, if you need further assistance, or have additional information that can help to reproduce the problem, please reopen the issue.

**Closed by mrclary** 2022-09-04 04:52 UTC
Labels: type:Bug, component:IPython Console

**Comment by iyer** [comment] 2024-01-14 03:42
I'm encountering this problem too. I recently downloaded the latest version from MiniConda on Python 3.11.
Version info is below 

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Linux 4.18.0-372.32.1.el8_6.x86_64


Prior to this I was on the below version and this works fine
* Spyder version: 5.4.2  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 4.18.0-372.32.1.el8_6.x86_64


I notice that in the menu Tools | Current User environment variables, PYTHONPATH is missing. All the other environment variables are still in place. It appears that Spyder deliberately drops the PYTHONPATH environment variable

**Comment by dalthviz** [comment] 2024-01-15 22:55
Hi @iyer thank you for the feedback! Could it be possible for you to check creating a new env using the conda-forge channel to be able to install the latest Spyder version (5.5.0) and check again? Let us know!

**Comment by iyer** [comment] 2024-01-16 08:00
I won't be able to do that. I'll wait for Spyder 5.5.0 to be updated on the conda channel and upgrade then and let you know then.
