### ISSUE TITLE
spyder bug

### ISSUE THREAD

**Issue by demeiyan** [spyder-ide/spyder#5883] opened 2017-12-03 12:24 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "F:\tools\anaconda\envs\py3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-12-03 16:38
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2017-12-03 18:42
Appears to be a duplicate of #5700 ; clearly, has something to do with non-ASCII/Unicode characters in some data object in the variable explorer not playing nice with Python2 like with other similar bugs, but unclear what exactly is triggering it, without which it can't be fixed. Mitigations would be avoiding non-ASCII characters or switching to Python3, but better to fix the bug for everyone on Spyder's side, which the devs can't do without your help. Thanks.

**Comment by CAM-Gerlach** [comment] 2017-12-16 20:46
Closing due to lack of response.

**Closed by CAM-Gerlach** 2017-12-16 20:46 UTC
