### ISSUE TITLE
5.1.1: Invalid Sytax Error (pyflakes E)

### ISSUE THREAD

**Issue by sharon92** [spyder-ide/spyder#16157] opened 2021-08-05 12:49 UTC
### What steps will reproduce the problem?

1. Load a python script into the editor
2. Invalid Syntax Error appears on the first line of the editor.

![image](https://user-images.githubusercontent.com/51754340/128353337-de444d60-b92e-41e8-b17f-31e48fe58abd.png)

![image](https://user-images.githubusercontent.com/51754340/128352813-6055463f-9f86-4942-a194-3905db3f13b9.png)

![image](https://user-images.githubusercontent.com/51754340/128353201-e9de5d42-73cc-4205-938b-31204bf27b56.png)

**Comment by ccordoba12** [comment] 2021-08-05 13:21
Hey @sharon92, thanks for reporting. According to this post in StackOverflow:

https://stackoverflow.com/questions/49582183/pythonl-invalid-syntax-file-fstring-line-1

this error is shown when you have an f-string in your code that is not valid.

So please look for your f-strings and see if they are declared correctly.

**Comment by sharon92** [comment] 2021-08-05 13:29
@ccordoba12 I forgot to mention that I checked this link beforehand and couldn't find an error. The script runs without any problem in the console.

I made a small script to collect all the f-strings with blank spaces inside them in my script:

```
file = "jobManagerHAS.py"

with open(file) as r: lines = r.readlines()

collect =[]
for n,i in enumerate(lines):
    fs = i.strip()
    
    if 'f"' in i:
        fs = i.strip().split('f"')[1].split('"')[0]
    elif "f'" in i:
        fs = i.strip().split("f'")[1].split("'")[0]
    else: continue
    
    if ' ' in fs:
        collect += [f'{n}: {fs}']
```
![image](https://user-images.githubusercontent.com/51754340/128357936-1e650c8f-e73e-4880-9f0a-51ee800ee310.png)

**Comment by ccordoba12** [comment] 2021-08-05 15:42
I searched a bit more and it seems the error is reported for any incorrectly formatted f-string (not just the ones with blank spaces).

So my guess is that when you run your code there's a bad f-string that doesn't get executed. But it's still there and so caught both by Pyflakes and Pylint (which powers our `Code analysis` pane).

**Comment by sharon92** [comment] 2021-08-06 07:09
@ccordoba12 Thanks for the info. So I guess they should make an update which points to correct line number.

**Comment by ccordoba12** [comment] 2021-08-09 13:04
I read a bit more and it seems that won't happen. The problem is Pyflakes and Pylint require a file free of f-string issues in order to give warnings and error about it. Otherwise, you'll always get the error message you're seeing now.

So you'll have to go through every f-string in your file and see if it's correct or not, sorry.

**Comment by ccordoba12** [comment] 2021-08-09 13:05
I'm going to close this issue because this is the best we can do for you and it's not something we can fix here.

**Closed by ccordoba12** 2021-08-09 13:05 UTC
Labels: status:Awaiting Followup

**Comment by sharon92** [comment] 2021-08-09 14:06
@ccordoba12 found the error here:

```
            if os.path.exists(self.def_dict['lockpath']):
                time.sleep(2)
                self.statusBar.setText('Job Liste ist nicht erreichbar.'+
                                              f' {versuch=}')
                versuch += 1
```

Pyflakes doesn't support python > 3.8

f'{variable=}' is a python 3.9 syntax.

I used these commands to locate the error, incase anyone needs to find this in future.

```
from pyflakes import api
api.check(input_python_file) 
```

**Comment by ccordoba12** [comment] 2021-08-09 14:32
> I used these commands to locate the error, incase anyone needs to find this in future.

Thanks a lot for the tip @sharon92!
