### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by Esman07** [spyder-ide/spyder#5501] opened 2017-10-18 17:22 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\SMAN\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "C:\Users\SMAN\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 202, in _get_code_info
    editor = self.editor_widget.get_current_editor()
  File "C:\Users\SMAN\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1145, in get_current_editor
    return self.tabs.currentWidget()
RuntimeError: wrapped C/C++ object of type BaseTabs has been deleted

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (

**Comment by ccordoba12** [comment] 2017-10-18 20:14
Thanks for reporting, This is a duplicate of issue #5484.

**Closed by ccordoba12** 2017-10-18 20:14 UTC
