### ISSUE TITLE
Aren't there filter like vscode in dataframe Variable explorer?

### ISSUE THREAD

**Issue by opticaloptical** [spyder-ide/spyder#17037] opened 2021-12-16 15:06 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
 there are not filter like vscode in dataframe Variable Explorer?

### What steps reproduce the problem?

1. run pandas code to built a dataframe
2. open the dataframe by Variable Explorer
3. can't find filter on table head as vs code does
![image](https://user-images.githubusercontent.com/6635193/146396362-ba9c68e8-5f56-40cc-ad91-8e7a186e5153.png)

### What is the expected output? What do you see instead?
 there are  filter like vscode in dataframe Variable Explorer.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5 None
* Python version: 3.8.12 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment] 2021-12-16 17:35
Hi @opticaloptical thank you for the feedback! I think we don't have a filter for the dataframe editor (or collections editors in general) althoug that sounds like something quite useful. What do you think @spyder-ide/core-developers ?

**Comment by steff456** [comment] 2021-12-16 18:42
The idea of the filter is for the dataframe values for all the columns?

**Comment by CAM-Gerlach** [comment] 2021-12-16 22:01
I seem to remember @jnsebgosselin (I believe) created a pretty nifty set of enhancements with per-column search and filtering, but IIRC it ran into some UX issues and debates and stalled before it was implemented.

**Comment by ccordoba12** [comment] 2021-12-28 17:10
This is a duplicate of issue #6008, so I'm going to close it in favor of that one.

**Closed by ccordoba12** 2021-12-28 17:10 UTC
Labels: type:Enhancement, component:Variable Explorer
