### ISSUE TITLE
Very slow line execution using IPython 7.7.0 in macOS mojave 10.14.6

### ISSUE THREAD

**Issue by bustundag** [spyder-ide/spyder#10101] opened 2019-08-28 20:19 UTC
## Problem Description
First a couple of runs are performed normally but afterwards even running simple commands takes too much time. 

After running a simple code, even only entering a variable and getting the result takes around 20-25 seconds. Examples are the lines given in the following. (In [2], In [3], In [4])

Problem looks very much like the one which is explained in Issue #2902.

### What steps reproduce the problem?

1. Performing an update after 4 or 5 months.
2. 
3. 

### What is the expected output? What do you see instead?
Expectation is to get the result and new command line nearly immediately. Instead it takes 20-25 seconds to get a result and 10-15 seconds to get a new command line.

### Paste Traceback/Error Below (if applicable)
```python-traceback

Python 3.7.0 (default, Jun 28 2018, 07:39:16)
Type "copyright", "credits" or "license" for more information.

IPython 7.7.0 -- An enhanced Interactive Python.

In [1]: runfile('/Users/burakustundag//01 Pulsating Sphere/02 Python Codes')

In [2]: Jac
Out[2]: 4.0

In [3]:coor4
Out[3]: 
matrix([[ 1,  1, -1,  0],
        [ 2,  1,  1,  0],
        [ 3, -1,  1,  0],
        [ 4, -1, -1,  0]])

In [4]:topl4
Out[4]: array([1, 1, 2, 3, 4])

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS Mojave 10.14.6

### Dependencies
```
IPython >=4.0     :  7.7.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.4 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2019-08-29 08:40
> Problem looks very much like the one which is explained in Issue #2902.

Yes, I'm afraid it is. So I'm closing this issue as a duplicate of that one.

**Closed by ccordoba12** 2019-08-29 08:40 UTC
