### ISSUE TITLE
PyQt program stop on spyder

### ISSUE THREAD

**Issue by takumi601** [spyder-ide/spyder#5359] opened 2017-09-29 09:57 UTC
## Description of your problem
My PyQt Program crash  when push QUIT button.

**What steps will reproduce the problem?**

1. run program
2. push QUIT button

**What is the expected output? What do you see instead?**
program quit normally

**Please provide any additional information below**
QUIT button works fine on ipython console (command prompt) .

## Versions and main components

* Spyder Version: 3.2.1
* Python Version : 3.6.2
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows7 x64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```python
# -*- coding: utf-8 -*-
import sys

import PyQt5.QtCore as QtCore
import PyQt5.QtGui as QtGui
import PyQt5.QtWidgets as QtWidgets

class CountDownWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)
        self.interval = 10
        self.setup_ui()


    def update_display(self):
        self.lcd_number.display("%6.2f" % (self.count / 100))
        self.lcd_number.update()


    def do_countdown(self):
        self.count -= 1
        self.update_display()
        if self.count <= 0:
            self.stop_countdown()


    def start_countdown(self):
        if self.count > 0.0:
            self.timer.start()


    def stop_countdown(self):
        self.timer.stop()


    def reset_count(self):
        self.count = 18000
        self.update_display()


    def setup_ui(self):
        self.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)

        self.timer = QtCore.QTimer(parent=self)
        self.timer.setInterval(self.interval)
        self.timer.timeout.connect(self.do_countdown)
        #self.connect(self.timer, QtCore.SIGNAL("timeout()"), self.do_countdown) Qt4のスタイル

        self.lcd_number = QtWidgets.QLCDNumber(parent=self)
        self.lcd_number.setSizePolicy(QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Expanding)

        self.lcd_number.setFrameStyle(QtWidgets.QFrame.NoFrame)
        self.lcd_number.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_number.setDigitCount(6)
        
        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(self.lcd_number)
        self.setLayout(layout)

        self.reset_count()


class ButtonBoxWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)
        self.setup_ui()


    def setup_ui(self):
        self.start_button = QtWidgets.QPushButton("START", parent=self)
        self.stop_button = QtWidgets.QPushButton("STOP", parent=self)
        self.reset_button = QtWidgets.QPushButton("RESET", parent=self)
        self.quit_button = QtWidgets.QPushButton("QUIT", parent=self)

        layout = QtWidgets.QGridLayout()
        layout.addWidget(self.start_button, 0, 0)
        layout.addWidget(self.stop_button, 0, 1)
        layout.addWidget(self.reset_button, 1, 0)
        layout.addWidget(self.quit_button, 1, 1)

        self.setLayout(layout)
        
def main():
    app = QtWidgets.QApplication.instance()
    if app is None:
        app = QtWidgets.QApplication(sys.argv)

    panel = QtWidgets.QWidget()

    countdown_widget = CountDownWidget(parent=panel)
    button_box_widget = ButtonBoxWidget(parent=panel)

    panel_layout = QtWidgets.QVBoxLayout()
    panel_layout.addWidget(countdown_widget)
    panel_layout.addWidget(button_box_widget)
    panel.setLayout(panel_layout)
    panel.setFixedSize(320, 200)

    main_window = QtWidgets.QMainWindow()
    main_window.setWindowTitle("Ramen Timer")
    main_window.setCentralWidget(panel)

    main_window.show()

    button_box_widget.start_button.clicked.connect(
        countdown_widget.start_countdown)
    
    button_box_widget.stop_button.clicked.connect(
        countdown_widget.stop_countdown)
    
    button_box_widget.reset_button.clicked.connect(
        countdown_widget.reset_count)

    button_box_widget.quit_button.clicked.connect(
        app.quit)
    
    app.exec_()
    
    return main_window


if __name__ == "__main__":
    
    window = main()
```

**Comment by ccordoba12** [comment] 2017-09-29 15:20
@dalthviz, please help @takumi601 with this problem.

**Comment by jnsebgosselin** [comment] 2017-09-29 17:32
@dalthviz FYI, it works as expected for me in Windows 7 64bit 3.2.4-dev.

![timer](https://user-images.githubusercontent.com/10170372/31028069-98c7704a-a51a-11e7-9f64-a14a7a97c6bb.gif)

**Comment by dalthviz** [comment] 2017-09-30 04:18
Thanks @jnsebgosselin for testing this one :+1:. @ccordoba12 I also tested in Spyder 3.2.1 with Python 3.6.2 and 3.6.1 and in Spyder 3.2.3 with Python 3.6.1 in Windows 8.1. It worked as expected.

@takumi601 did you do something more than push the QUIT button?

**Comment by ccordoba12** [comment] 2017-09-30 18:41
@takumi601, please update to 3.2.3 and try again.

I'm closing this issue because we're unable to reproduce this problem but feel free to keep posting comments here to let us know how we could reproduce your problem.

**Closed by ccordoba12** 2017-09-30 18:41 UTC

**Comment by takumi601** [comment] 2017-10-02 00:27
Thank you for checking the problem.
Doing the same thing as jnsebgosselin,
The program freezes.
I updated spyder to 3.2.3, but it did not fix it.
Maybe there is a problem unique to my environment.
I will write it here if I understand.

**Comment by jnsebgosselin** [comment] 2017-10-02 00:40
@takluyver Upgrading my PyQt and Qt version would be the first thing I would try.
