### ISSUE TITLE
TimeoutError: Timeout while waiting for 'run_cell' reply

### ISSUE THREAD

**Issue by on5off** [spyder-ide/spyder#11273] opened 2020-01-08 23:53 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I try to select some part of the code and right click to run cell. It gives me this error. I was able to run it in 3.7 version. I do not think that it's related to remapping the keys. somehow run cell function through selecting code with mouse/trackpad is gone or is there a way to enable this function again? I was able to run current cell without creating cells with #%% previously.

**Comment by ccordoba12** [comment] 2020-01-09 00:07
Duplicate of #11137

**Closed by ccordoba12** 2020-01-09 00:07 UTC
