### ISSUE TITLE
Internal problem dialog popup

### ISSUE THREAD

**Issue by tomviolin** [spyder-ide/spyder#12064] opened 2020-03-31 10:00 UTC
### What steps will reproduce the problem?

when hitting final "." of "tf1.logging."

maybe autocompletion interface w/kite to blame?

### Traceback
```python-traceback
  File "/home/tomh/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/fallback/actor.py", line 155, in handle_msg
    msg['current_word'])
  File "/home/tomh/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/fallback/actor.py", line 62, in tokenize
    valid = is_prefix_valid(text, offset, language)
  File "/home/tomh/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/fallback/utils.py", line 122, in is_prefix_valid
    current_pos_text = text[offset - 1]
IndexError: string index out of range
```

## Versions

* Spyder version: 4.1.0 
* Python version: 3.7.6
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.0-42-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.8 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-31 17:50
Duplicate of #11862

**Comment by ccordoba12** [comment] 2020-03-31 17:51
It'll be fixed in our next version (4.1.2), to be released in the next couple of days.

**Closed by ccordoba12** 2020-03-31 17:50 UTC

**Comment by tomviolin** [comment] 2020-03-31 19:34
Thank you for the very fast and personal feedback.

I have Spyder 4.1.0 installed in Anaconda3 on Ubuntu 18.04. I tried to upgrade to 4.1.1, and it spent literally hours trying to compute an upgrade path.  It finally gave me what seemed to be hundreds of screens full of a proposed solution.  I of course aborted it and am still stuck on 4.1.0.  Is there any chance that the upgrade path for Anaconda3 on Linux will be cleaned up?

Thank you!!



Tom Hansen

Senior Information Processing Consultant

UWM School of Freshwater Sciences

Great Lakes WATER Institute

tomh@uwm.edu

"Nothing in life is to be feared, it is only to be understood."

   -Marie Curie

________________________________

**Comment by ccordoba12** [comment] 2020-04-01 02:05
> Thank you for the very fast and personal feedback.

No problem. Glad that you appreciated it!

> I have Spyder 4.1.0 installed in Anaconda3 on Ubuntu 18.04. I tried to upgrade to 4.1.1, and it spent literally hours trying to compute an upgrade path

Please try to run first `conda update anaconda` and then `conda install spyder=4.1.1`
