### ISSUE TITLE
Don't show "No documentation available" tooltip on hover

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#11346] opened 2020-01-19 15:50 UTC
## Problem Description

hold the mouse cursor over almost anything in the editor. a "No ducumentation available" tooltip will appear. which is extremely distracting and sometomes the tooltip will appear over other windows.

example code:
  ``` a = "Asd" ```
  hold cursor over the "Asd". the tooltip will appear.
This is not a helpfull tooltip, It appears all the time just by having the mouse cursor over almost anything in the editor
  
## Versions
(this is a spyder 4 problem)
4.0.1
(tested on two machines, one spyder 4.0.0 another 4.0.1)

Python 3.7.5 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 
### Dependencies
```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2020-01-19 16:15
I agree with your suggestion. @goanpeca, please take a look at this one.

**Comment by goanpeca** [comment] 2020-01-21 03:21
I canot reproduce this @ccordoba12

**Comment by ccordoba12** [comment] 2020-01-21 14:01
@talkaminker, please post a screenshot of what you're seeing.

@dalthviz, can you reproduce this one on Windows?

**Comment by dalthviz** [comment] 2020-01-21 14:21
@ccordoba12 I can't reproduce this. Maybe something else, besides the `a = "Asd"`, is needed?:

![hover](https://user-images.githubusercontent.com/16781833/72812258-30518600-3c2f-11ea-81d4-eb1ac519d61f.gif)

**Comment by ccordoba12** [comment] 2020-01-21 15:12
But there's the case of `paren_example` in your screenshot above, whose hover shouldn't be displayed because it's pointless.

@goanpeca, please take care of those cases for now.

**Comment by goanpeca** [comment] 2020-01-21 17:55
Fixed!

**Comment by talkaminker** [comment] 2020-02-02 14:16
![image](https://user-images.githubusercontent.com/13932998/73609541-6865ab00-45d7-11ea-975d-145408cd746a.png)

**Comment by matheger** [comment] 2020-02-08 16:14
Here's an example of the popup appearing over other windows. It was actually persistent too, I could move that explorer window around without the help note disappearing. Only went away after switching back to Spyder.

![popup](https://user-images.githubusercontent.com/34485360/74088356-f667e880-4a52-11ea-826e-357c05d23e3d.png)

Spyder 4.0.1, Python 3.7.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by dalthviz** [comment] 2020-02-11 15:10
@talkaminker I think this issue will be fixed with PR #11377 (which hasn't being merged yet).

@matheger I think maybe the behavior you're describing is related with #11244 which was fixed with PR #11271 

Take into account that the fixes will be available with Spyder `4.1.0` (the current installable version is `4.0.1` ).

Hope this clarifies the state of the issues and fixes :)

**Closed** 2020-02-13 02:56 UTC
Labels: component:Editor, type:Enhancement

**Comment by warren55555** [comment] 2020-04-17 17:14
Will this be fixed in the near future? This is still happening in **v4.1.2**

**Comment by ba-tno** [comment] 2021-06-06 19:30
This issue is back in Spyder 5.

### Steps to reproduce
1. Open Spyder.
2. Create a string, list or dictionary variable and assign content to it.
3. Hover your mouse over the variable.

### Expected output
No tooltip is shown.

### Actual input
A tooltip with the the following text appears:

> No documentation available  
> Click anywhere in this tooltip for additional help

#### String
![image](https://user-images.githubusercontent.com/52008464/120937528-4077e180-c70e-11eb-930e-77d65d8610b0.png)

#### List
![image](https://user-images.githubusercontent.com/52008464/120937540-4d94d080-c70e-11eb-911a-22445425d07b.png)

#### Dictionary
![image](https://user-images.githubusercontent.com/52008464/120937552-5c7b8300-c70e-11eb-9340-636cac31d44f.png)


### Versions
```log
* Spyder version: 5.0.3 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10
```

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  56.2.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by ccordoba12** [comment] 2021-06-06 23:38
@ba-tno, please open a new issue about it.

**Comment by ZaamlamLeung** [comment] 2021-08-18 08:03
try this
Tools > Preferences > Completion and linting > Introspection
and deactivate the option called Enable hover hints.

ref: https://stackoverflow.com/questions/59225879/how-to-hide-hover-tooltips-on-spyder-4
