### ISSUE TITLE
how to install Spyder-Notebook and Spyder-Terminal in Spyder 5 standalone installation? 

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder#15907] opened 2021-06-19 22:59 UTC
I cannot find instructions for installing Spyder-Notebook and Spyder-Terminal in my Spyder 5 standalone installation.  

First of all, do these 2 plugins work in Spyder 5 stand alone?  

If so, can someone please provide these instructions on the Spyder 5 Home Page?  

How do I point conda to the Spyder 5 standalone directory to install these plugins?    What is the command line syntax to do this?

Do I have to use setup.py or some other tool to install these packages into the pkgs directory?  

![image](https://user-images.githubusercontent.com/9345711/122657267-17087e00-d130-11eb-9b70-bd094265fcff.png)

#### This is a suggestion for the next release of documentation ##### 

Thank you.

Rich Lysakowski

**Comment by ccordoba12** [comment] 2021-06-20 18:41
Hey @richdevboston, thanks for reporting. You said

> I cannot find instructions for installing Spyder-Notebook and Spyder-Terminal in my Spyder 5 standalone installation.

You're totally right. For now I added a note to the Readme of both projecs:

https://github.com/spyder-ide/spyder-notebook/pull/368
https://github.com/spyder-ide/spyder-terminal/pull/270

We don't have documentation for those plugins at the moment, but we'll try to add it in the coming months.

> First of all, do these 2 plugins work in Spyder 5 stand alone?

No, they don't.

> How do I point conda to the Spyder 5 standalone directory to install these plugins? What is the command line syntax to do this?

It is not possible to add install any other package (including these plugins) in our installers. That was by design, i.e. to avoid that installing a package that can break Spyder itself.

If you want to run code with packages that don't come with our installers, such as Scikit-learn or PyTorch, please read [our FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) about it.

> Do I have to use setup.py or some other tool to install these packages into the pkgs directory?

No, it won't work either.

For now, the only way to use our plugins is by installing Spyder and them with pip or conda.

> This is a suggestion for the next release of documentation

Thanks! @juanis2112 is our docs maintainer and now she's aware of that.

**Comment by ccordoba12** [comment] 2021-06-20 18:42
I'm going to close this issue because I think I've answered your questions.

**Closed by ccordoba12** 2021-06-20 18:42 UTC

**Comment by richlysakowski** [comment] 2022-02-18 01:15
Thank you !!
