### ISSUE TITLE
Error copying variable value 复制变量值出错

### ISSUE THREAD

**Issue by Aegis1863** [spyder-ide/spyder#13549] opened 2020-08-16 09:18 UTC
### What steps will reproduce the problem?

When I right-click in the variable area and select copy function, Spyder reports an error, but the software does not crash or quit. By the way, Spyder language I use is Chinese.

我在变量区右键并选择复制功能时，Spyder报错，但软件并未崩溃退出，我使用的软件语言是中文。

### Traceback
```python-traceback
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1038, in copy
    obj = self.delegate.get_value(idx)
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1373, in get_value
    return self.parent().get_value(name)
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1431, in get_value
    value = self.shellwidget.get_value(name)
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 100, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 152, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 488, in _sync_error
    error_wrapper.raise_error()
  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_value:

  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])

  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)

  File "D:\Users\LiSunBowen\anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 157, in get_value
    return ns[name]

KeyError: 'y'

```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.7
* Qt version: 5.15.0
* PyQt5 version: 5.15.0
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```

**Comment by ccordoba12** [comment] 2020-08-16 16:58
Hey @LeeSunBowen, thanks for reporting. Please provide us with a step by step description to reproduce your problem.

Otherwise, we won't be able to fix it, sorry.

**Comment by LeeSunBowen** [comment] 2020-08-16 17:53
![image](https://user-images.githubusercontent.com/46989391/90339967-4093dd00-e027-11ea-8b2d-8c861bef25d5.png)
I think it's a rare situation and I've only encountered it once so far.
When I have finished running a program, I'm in variable In the Explorer ribbon, right-click a variable, click Copy (like my screenshot), and Spyder prompts me to submit the error to GitHub. After I submit, spyder does not crash or exit, and there is no such error after I restart the software.
So I think it may also be due to the problem of my computer. Maybe there is not enough RAM at that time. This is such a rare situation. Therefore, it may not be a serious bug. 
Of course, you can close this issue. Thank you for your support!

**Comment by ccordoba12** [comment] 2020-08-16 17:58
Thanks for your help @LeeSunBowen! Could you share with us the program that you're running in the console, which generates the variables displayed in the Variable Explorer?

**Comment by LeeSunBowen** [comment] 2020-08-16 18:44
**Here is the code, you can run it directly as long as you have Numpy and matplotlib, and that variable is t or y. I've forgotten the exact variable, but it must be t or y.**

```
"""
Python 3.7
Gray Model
"""

import numpy as np
from numpy.linalg import *
import math
import matplotlib.pyplot as plt
y = np.array([31.87,32.87,31.77,31.5,30.44,30.77,29.69,29.69,29.13,27.68,29.79,25.19])  # Original sequence y
pv = 3 # Three values will predict forward
n = len(y)
yy = np.ones((n,1))
yy[0] = y[0]
for i in range(1,n):
    yy[i] = yy[i-1] + y[i]  # Accumulate the original sequence y
B = np.ones((n-1,2))
for i in range(0,n-1):
    B[i][0] = - (yy[i] + yy[i+1])/2  # Generating the nearest neighbor mean for YY
    B[i][1] = 1
    # B is a data matrix
BT = B.T
yn = np.ones((n-1,1))
for j in range(0,n-1):
    yn[j] = y[j+1]
A = np.dot(np.dot(inv(np.dot(BT,B)),BT),yn) # least square method
a = A[0]  # Development coefficient
u = A[1]  # Grey parameter
t = u/a
i = np.array([i for i in range(n+pv)]) #pv=3
yys = []
for j in range(len(i)):
    yys = (y[0]-t)*np.array([math.exp(-a*j) for j in i])+t  # response sequence
    yys[0] = 1
yys[0] = y[0] # Follow up data
ys=[i for i in range(n+pv-1)]
for j in range(n+pv-2,0,-1):
    ys[j] = yys[j] - yys[j-1]  # Reduce yys one by one to generate predicted value
ys[0] = y[0]

# forecast done .statistics analysis is going to start
x = [i for i in range(1,n+1)]
xs = [i for i in range(2,n+pv)]
yn = ys[1:n+pv] 
det = 0
sum1 = 0
sumpe = 0
for i in range(n):
    sumpe = sumpe+y[i]
pe = sumpe/n  
for i in range(n):
    sum1= sum1+(y[i]-pe)**2  
s1 = math.sqrt(sum1/n) # standard deviation
sumce = 0
h = ys[:len(y)]
eps = h - y
# Relative residual
delta = abs(eps/y)
Q = delta.mean()
# Variance ratio
C = eps.std()/y.std()
#P-test
S1 = y.std()
temp = np.sum((abs(eps-eps.mean()) < 0.6745 * S1) == True)
P = temp/n
# Posteriori error ratio
for i in range(1,n):
    sumce = sumce+(y[i]-yn[i])
ce = sumce/(n-1)
sum2 = 0;
for i in range(1,n):
    sum2 = sum2+(y[i]-yn[i]-ce)**2;
s2 = math.sqrt(sum2/(n-1))
c = s2/s1
print('\n>> Relative residual Q = {:.5f}'.format(Q))
print('>> Variance ratio C = {:.5f}'.format(C))
print('>> P-test：{:.3f}'.format(P))
print('>> Posteriori error ratio = {:.5f}'.format(c))
if c < 0.35:
    print('\n===prediction accuracy good!===')
elif c < 0.5:
    print('===prediction accuracy qualified===')
elif c < 0.65:
    print('===prediction accuracy limited!===')
else:
    print('===prediction accuracy unqualified!===')
print('\nThe next fitting value is %.3f'%ys[n])
print('And the next fitting value is %.3f'%ys[n+1])
print('All fitting values are：\n',ys[n:])
plt.plot(x,y,linestyle='',color = 'red',marker='D')
plt.plot(xs,yn,linestyle='--',color = 'green')
plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']
plt.title('Prediction curve')
plt.grid()
plt.show()

```

**Comment by ccordoba12** [comment] 2020-08-19 15:55
Thanks @LeeSunBowen! I'll try to reproduce your error this weekend.

**Closed** 2020-12-27 00:32 UTC
Labels: status:Awaiting Followup
