### ISSUE TITLE
Linting error locks up Spyder, forcing a restart

### ISSUE THREAD

**Issue by jgrooviest** [spyder-ide/spyder#12054] opened 2020-03-30 22:59 UTC
### What steps will reproduce the problem?

Once every day or two, I get a repeated error saying something about autofinish and linting, which suggests that I disable some setting of my computer's firewall. It effectively locks me out of Spyder, forcing me to close and restart. I am using Kite, which might have to do with the problem, but that's as much information as I have.

### Traceback
```python-traceback
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 98, in <lambda>
    triggered=lambda v: self.open_project())
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 333, in open_project
    self.restart_consoles()
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 516, in restart_consoles
    self.main.ipyconsole.restart()
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1068, in restart
    self.create_new_client(give_focus=False)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 703, in create_new_client
    self.register_client(client)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 918, in register_client
    shellwidget.set_cwd(cwd_path)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "C:\Users\jmgro\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "C:\Users\jmgro\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.10.2 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.6.0 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  2.3.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.17.4 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.3.2 (OK)
sympy >=0.7.3                  :  1.5 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-30 23:08
> Once every day or two, I get a repeated error saying something about autofinish and linting, which suggests that I disable some setting of my computer's firewall. It effectively locks me out of Spyder, forcing me to close and restart. I am using Kite, which might have to do with the problem, but that's as much information as I have.

This error is a duplicate of issue #11026 and it'll be fixed in our next version, to be released in a couple of days.

> TimeoutError: Timeout while waiting for comm port.

This error is a duplicate of issue #11889 and we still don't know why it happens, sorry.

**Closed by ccordoba12** 2020-03-30 23:08 UTC
