### ISSUE TITLE
Spyder 4 hangs indefinitely during startup and does not open (Win10 w. Conda)

### ISSUE THREAD

**Issue by Nate28** [spyder-ide/spyder#11430] opened 2020-01-29 23:22 UTC
## Problem Description
When starting Spyder, the program hangs indefinitely upon trying to open the GUI. 

### What steps reproduce the problem?

1. Create a fresh Conda environment and activate
```
conda create -n spyderTest python=3 spyder
conda activate spyderTest
```
2. Launch Spyder
```
spyder
```
3. The splash screen appears and goes through the motions of starting up Spyder, but the GUI window that appears does not respond or show anything other than a white window.

4. Reset Spyder preferences
```
spyder --reset
```
5. Try to start Spyder again
```
spyder
```

6. Now the splash screen itself hangs on "Setting up main window" 
7. Close non-responsive Anaconda prompt window and retry
```
conda activate spyderTest
spyder
```
Same result: a hanging splash screen that gets stuck on "Setting up main window"

### What is the expected output? What do you see instead?
I expect Spyder to open and connect to an IPython kernel.  Instead, the main window fails to initialise properly.

### Paste Traceback/Error Below (if applicable)

The only text that appears in the command prompt upon trying to start Spyder is:
```
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
```

### OS
Windows 10 Home
Version 10.0.17763 Build 17763

### spyderTest environment
Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2                py38_1001    conda-forge
astroid                   2.3.3                    py38_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5                        py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.7            py38hfa6e2cd_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cffi                      1.13.2           py38hb32ad35_0    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.8              py38hb32ad35_1    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20181111                   py_0    conda-forge
docutils                  0.16                     py38_0    conda-forge
entrypoints               0.3                   py38_1000    conda-forge
flake8                    3.7.9                    py38_0    conda-forge
future                    0.18.2                   py38_0    conda-forge
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                   py38_1000    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib_metadata        1.5.0                    py38_0    conda-forge
inflect                   4.0.0                    py38_1    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.1.4            py38h5ca1d4c_0    conda-forge
ipython                   7.11.1           py38h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py38_0    conda-forge
jaraco.itertools          5.0.0                      py_0    conda-forge
jedi                      0.14.1                   py38_0  
jinja2                    2.11.0                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.2.0                    py38_0    conda-forge
jupyter_client            5.3.4                    py38_1    conda-forge
jupyter_core              4.6.1                    py38_0    conda-forge
keyring                   21.1.0                   py38_0    conda-forge
lazy-object-proxy         1.4.3            py38hfa6e2cd_1    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_1    conda-forge
markupsafe                1.1.1            py38hfa6e2cd_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38hfa6e2cd_1000    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
nbconvert                 5.6.1                    py38_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.1                    py38_0    conda-forge
parso                     0.6.0                      py_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pexpect                   4.8.0                    py38_0    conda-forge
pickleshare               0.7.5                 py38_1000    conda-forge
pip                       20.0.2                   py38_0    conda-forge
pluggy                    0.13.1                   py38_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
psutil                    5.6.7            py38hfa6e2cd_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py38_1    conda-forge
pydocstyle                5.0.2                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pylint                    2.4.4                    py38_0    conda-forge
pynacl                    1.3.0           py38h2fa13f4_1001    conda-forge
pyopenssl                 19.1.0                   py38_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py38h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py38hfa6e2cd_0    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.1                he1f5543_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4                      py_0    conda-forge
python-language-server    0.31.7                   py38_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   225              py38hfa6e2cd_0    conda-forge
pywin32-ctypes            0.2.0                 py38_1000    conda-forge
pyyaml                    5.3              py38hfa6e2cd_0    conda-forge
pyzmq                     18.1.1           py38h16f9016_0    conda-forge
qdarkstyle                2.8                        py_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.6.1                      py_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.22.0                   py38_1    conda-forge
rope                      0.16.0                     py_0    conda-forge
rtree                     0.9.3            py38hbf79ddb_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    2.3.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
spyder                    4.0.1                    py38_0    conda-forge
spyder-kernels            1.8.1                    py38_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tornado                   6.0.3            py38hfa6e2cd_0    conda-forge
traitlets                 4.3.3                    py38_0    conda-forge
ujson                     1.35            py38hfa6e2cd_1001    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_1  
watchdog                  0.10.0                   py38_1    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
wrapt                     1.11.2           py38hfa6e2cd_0    conda-forge
yaml                      0.2.2                hfa6e2cd_1    conda-forge
yapf                      0.28.0                     py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      2.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge

### Base environment
Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py27_0  
alabaster                 0.7.12                   py27_0  
anaconda                  2019.07                  py27_0  
anaconda-client           1.7.2                    py27_0  
anaconda-navigator        1.9.7                    py27_0  
anaconda-project          0.8.3                      py_0  
asn1crypto                0.24.0                   py27_0  
astroid                   1.6.5                    py27_0  
astropy                   2.0.9            py27hc997a72_0  
atomicwrites              1.3.0                    py27_1  
attrs                     19.1.0                   py27_1  
babel                     2.7.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.5                        py_2  
backports.os              0.1.1                    py27_0  
backports.shutil_get_terminal_size 1.0.0                    py27_2  
backports.shutil_which    3.5.2                    py27_0  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
backports_abc             0.5              py27h0ec6b72_0  
beautifulsoup4            4.7.1                    py27_1  
bitarray                  0.9.2            py27h0c8e037_0  
bkcharts                  0.2              py27h92b6de3_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py27_0  
blosc                     1.16.3               hc65f11a_0  
bokeh                     1.2.0                    py27_0  
boto                      2.49.0                   py27_0  
bottleneck                1.2.1            py27hc997a72_1  
bzip2                     1.0.8                h0c8e037_0  
ca-certificates           2019.5.15                     0  
cdecimal                  2.3              py27h0c8e037_3  
certifi                   2019.6.16                py27_0  
cffi                      1.12.3           py27hcfb25f9_0  
chardet                   3.0.4                    py27_1  
click                     7.0                      py27_0  
cloudpickle               1.2.1                      py_0  
clyent                    1.2.2                    py27_1  
colorama                  0.4.1                    py27_0  
comtypes                  1.1.7                    py27_0  
conda                     4.8.1                    py27_0  
conda-build               3.18.9                   py27_3  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.0            py27h3cc03e0_0  
conda-verify              3.4.2                      py_1  
configparser              3.7.4                    py27_0  
console_shortcut          0.1.1                         3  
contextlib2               0.5.5            py27h42efda5_0  
cryptography              2.4.2            py27hc64555f_0  
curl                      7.64.0               h7a46e7a_2  
cycler                    0.10.0           py27h59acbbf_0  
cython                    0.29.12          py27hc56fc5f_0  
cytoolz                   0.10.0           py27h0c8e037_0  
dask                      1.2.2                      py_0  
dask-core                 1.2.2                      py_0  
decorator                 4.4.0                    py27_1  
defusedxml                0.6.0                      py_0  
distributed               1.28.1                   py27_0  
docutils                  0.14             py27h8652d09_0  
entrypoints               0.3                      py27_0  
enum34                    1.1.6                    py27_1  
et_xmlfile                1.0.1            py27h1de5d23_0  
fastcache                 1.1.0            py27h0c8e037_0  
filelock                  3.0.12                     py_0  
flask                     1.1.1                      py_0  
freetype                  2.9.1                h4d385ea_1  
funcsigs                  1.0.2            py27h8885ae1_0  
functools32               3.2.3.2                  py27_1  
future                    0.17.1                   py27_0  
futures                   3.3.0                    py27_0  
get_terminal_size         1.0.0                h38e98db_0  
gevent                    1.4.0            py27h0c8e037_0  
glob2                     0.7                        py_0  
greenlet                  0.4.15           py27h0c8e037_0  
grin                      1.2.1                    py27_4  
h5py                      2.9.0            py27hb721d18_0  
hdf5                      1.10.4               h530792d_0  
heapdict                  1.0.0                    py27_2  
html5lib                  1.0.1                    py27_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 h2aa20d9_1  
idna                      2.8                      py27_0  
imageio                   2.5.0                    py27_0  
imagesize                 1.1.0                    py27_0  
importlib_metadata        0.17                     py27_1  
intel-openmp              2019.4                      245  
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.10.0                   py27_0  
ipython                   5.8.0                    py27_0  
ipython_genutils          0.2.0            py27hbe997df_0  
ipywidgets                7.5.0                      py_0  
isort                     4.3.21                   py27_0  
itsdangerous              1.1.0                    py27_0  
jdcal                     1.4.1                      py_0  
jedi                      0.13.3                   py27_0  
jinja2                    2.10.1                   py27_0  
jpeg                      9b                   ha175dff_2  
jsonschema                3.0.1                    py27_0  
jupyter                   1.0.0                    py27_7  
jupyter_client            5.3.1                      py_0  
jupyter_console           5.2.0                    py27_1  
jupyter_core              4.5.0                      py_0  
jupyterlab                0.33.11                  py27_0  
jupyterlab_launcher       0.11.2           py27h28b3542_0  
keyring                   18.0.0                   py27_0  
kiwisolver                1.1.0            py27hc56fc5f_0  
krb5                      1.16.1               hb4d044e_6  
lazy-object-proxy         1.4.1            py27h0c8e037_0  
libarchive                3.3.3                h96cdc4e_5  
libcurl                   7.64.0               h7a46e7a_2  
libiconv                  1.15                 hda2e4ec_7  
libpng                    1.6.37               h7a46e7a_0  
libsodium                 1.0.16               h8b3e59e_0  
libssh2                   1.8.0                h77a7533_4  
libtiff                   4.0.10               h1c3b264_2  
libxml2                   2.9.9                h325896a_0  
libxslt                   1.1.33               h803002f_0  
linecache2                1.0.0                    py27_0  
llvmlite                  0.29.0           py27hc56fc5f_0  
locket                    0.2.0            py27h1ca288a_1  
lxml                      4.3.4            py27h31b8cb8_0  
lz4-c                     1.8.1.2              h3cc03e0_0  
lzo                       2.10                 h0bb7fe3_2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markupsafe                1.1.1            py27h0c8e037_0  
matplotlib                2.2.3            py27h263d877_0  
mccabe                    0.6.1                    py27_1  
menuinst                  1.4.16           py27h0c8e037_0  
mistune                   0.8.4            py27h0c8e037_0  
mkl                       2019.4                      245  
mkl-service               2.0.2            py27h0c8e037_0  
mkl_fft                   1.0.12           py27h44c1dab_0  
mock                      3.0.5                    py27_0  
more-itertools            5.0.0                    py27_0  
mpmath                    1.1.0                    py27_0  
msgpack-python            0.6.1            py27hdc96acc_1  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.6.0                    py27_0  
navigator-updater         0.2.1                    py27_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0            py27hf49b375_0  
networkx                  2.2                      py27_1  
nltk                      3.4.4                    py27_0  
nose                      1.3.7                    py27_2  
notebook                  5.7.8                    py27_0  
numba                     0.44.1           py27h39f3610_0  
numexpr                   2.6.9            py27haac76bc_0  
numpy                     1.16.3           py27h5fc8d92_0  
numpy-base                1.16.3           py27hb1d0314_0  
numpydoc                  0.9.1                      py_0  
olefile                   0.46                     py27_0  
openpyxl                  2.6.2                      py_0  
openssl                   1.0.2s               h0c8e037_0  
packaging                 19.0                     py27_0  
pandas                    0.24.2           py27hc56fc5f_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py27_1  
parso                     0.5.0                      py_0  
partd                     1.0.0                      py_0  
path.py                   11.5.0                   py27_0  
pathlib2                  2.3.4                    py27_0  
patsy                     0.5.1                    py27_0  
pep8                      1.7.1                    py27_0  
pickleshare               0.7.5                    py27_0  
pillow                    6.1.0            py27h5b88493_0  
pip                       19.1.1                   py27_0  
pkginfo                   1.5.0.1                  py27_0  
pluggy                    0.12.0                     py_0  
ply                       3.11                     py27_0  
powershell_shortcut       0.0.1                         2  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            1.0.15           py27h3a8ec6a_0  
psutil                    5.6.3            py27h0c8e037_0  
py                        1.8.0                    py27_0  
pycodestyle               2.5.0                    py27_0  
pycosat                   0.6.3            py27h0c8e037_0  
pycparser                 2.19                     py27_0  
pycrypto                  2.6.1            py27h0c8e037_9  
pycurl                    7.43.0.2         py27hc64555f_0  
pyflakes                  2.1.1                    py27_0  
pygments                  2.4.2                      py_0  
pylint                    1.9.2                    py27_0  
pyodbc                    4.0.26           py27hc56fc5f_0  
pyopenssl                 19.0.0                   py27_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.6.0            py27h6e61f57_6  
pyreadline                2.1                      py27_1  
pyrsistent                0.14.11          py27h0c8e037_0  
pysocks                   1.7.0                    py27_0  
pytables                  3.5.2            py27h6a9b274_1  
pytest                    4.6.2                    py27_0  
python                    2.7.16               hcb6e200_0  
python-dateutil           2.8.0                    py27_0  
python-libarchive-c       2.8                     py27_11  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py27hc997a72_1  
pywin32                   223              py27h0c8e037_1  
pywinpty                  0.5.5                 py27_1000  
pyyaml                    5.1.1            py27h0c8e037_0  
pyzmq                     18.0.0           py27hc56fc5f_0  
qt                        5.6.2            vc9hc26998b_12  
qtawesome                 0.5.7                    py27_1  
qtconsole                 4.5.1                      py_0  
qtpy                      1.8.0                      py_0  
requests                  2.22.0                   py27_0  
rope                      0.14.0                     py_0  
ruamel_yaml               0.15.46          py27h0c8e037_0  
scandir                   1.10.0           py27h0c8e037_0  
scikit-image              0.14.2           py27hc56fc5f_0  
scikit-learn              0.20.3           py27hf381715_0  
scipy                     1.2.1            py27h4c3ab11_0  
seaborn                   0.9.0                    py27_0  
send2trash                1.5.0                    py27_0  
setuptools                41.0.1                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3          py27h3f9d112_0  
sip                       4.18.1           py27hc56fc5f_2  
six                       1.12.0                   py27_0  
snappy                    1.1.7                he46498f_3  
snowballstemmer           1.9.0                      py_0  
sortedcollections         1.1.2                    py27_0  
sortedcontainers          2.1.0                    py27_0  
soupsieve                 1.8                      py27_0  
sphinx                    1.8.5                    py27_0  
sphinxcontrib             1.0                      py27_1  
sphinxcontrib-websupport  1.1.2                      py_0  
spyder                    3.3.6                    py27_0  
spyder-kernels            0.5.1                    py27_0  
sqlalchemy                1.3.5            py27h0c8e037_0  
sqlite                    3.29.0               h0c8e037_0  
ssl_match_hostname        3.7.0.1                  py27_0  
statsmodels               0.10.0           py27hc997a72_0  
subprocess32              3.5.4            py27h0c8e037_0  
sympy                     1.4                      py27_0  
tblib                     1.4.0                      py_0  
terminado                 0.8.2                    py27_0  
testpath                  0.4.2                    py27_0  
tk                        8.6.8                h0c8e037_0  
toolz                     0.10.0                     py_0  
tornado                   5.1.1            py27h0c8e037_0  
tqdm                      4.32.1                     py_0  
traceback2                1.4.0                    py27_0  
traitlets                 4.3.2            py27h1b1b3a5_0  
typing                    3.7.4                    py27_0  
unicodecsv                0.14.1           py27h0bf7bb0_0  
unittest2                 1.1.0                    py27_0  
urllib3                   1.24.2                   py27_0  
vc                        9                    h7299396_1  
vs2008_runtime            9.00.30729.1         hfaea7d5_1  
vs2015_runtime            14.15.26706          h3a45250_4  
wcwidth                   0.1.7            py27hb1a0d82_0  
webencodings              0.5.1                    py27_1  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py27_0  
widgetsnbextension        3.5.0                    py27_0  
win_inet_pton             1.1.0                    py27_0  
win_unicode_console       0.5              py27hc037021_0  
wincertstore              0.2              py27hf04cefb_0  
winpty                    0.4.3                         4  
wrapt                     1.11.2           py27h0c8e037_0  
xlrd                      1.2.0                    py27_0  
xlsxwriter                1.1.8                      py_0  
xlwings                   0.15.8                   py27_0  
xlwt                      1.3.0            py27h2271735_0  
xz                        5.2.4                h3cc03e0_4  
yaml                      0.1.7                h3e6d941_2  
zeromq                    4.3.1                h2880e7c_3  
zict                      1.0.0                      py_0  
zipp                      0.5.1                      py_0  
zlib                      1.2.11               h3cc03e0_3  
zstd                      1.3.7                h1b0e4d7_0

**Comment by goanpeca** [comment] 2020-01-29 23:24
Duplicate of https://github.com/spyder-ide/spyder/issues/11227. Closing

**Closed by goanpeca** 2020-01-29 23:24 UTC

**Comment by Nate28** [comment] 2020-01-30 13:40
Thanks for identifying the issue so quickly.  So if I'm understanding correctly, you need to make sure that your Qt version is 5.9 for Spyder to load properly?

**Comment by ccordoba12** [comment] 2020-01-30 13:51
It could be, due to incompatibilities between your graphics driver and Qt.

**Comment by Nate28** [comment] 2020-02-01 13:39
Okay, I've got it working by forcing installation of Qt version 5.9 instead of the most up to date one. Thanks for your help!
