### ISSUE TITLE
Spyder crash when locking screen

### ISSUE THREAD

**Issue by pj1989** [spyder-ide/spyder#8942] opened 2019-03-14 11:28 UTC
## Problem Description

Spyder keep crashing when the locking/unlocking the pc

### What steps reproduce the problem?

1.  Start Spyder
2.  Lock the PC (win+L)
3.  Unlock the PC
4. Spyder is no longer open (or it's open and closes immediately) 

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.1 64-bit
* Qt version: 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Window 10 Enterprise (version 1803 build 17134.523)

### Dependencies
```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-03-14 12:11
Please start Spyder in a terminal (cmd.exe) and report back any errors you're seeing there.

**Comment by pj1989** [comment] 2019-03-14 12:31
Unfortunately spyder.exe (in anaconda3\Scripts\spyder.exe) does not run in cmd.

However it does run in conda prompt.

If I run it in conda prompt I can reproduce the error, but no error message is generated. It just goes to a new terminal line like I just closed the program

**Comment by ccordoba12** [comment] 2019-03-14 12:47
Sorry but without an error message is not possible for us to help you. My only recommendation is for you to update DirectX and your graphics card drivers. That could help.

**Comment by pj1989** [comment] 2019-03-14 13:06
I understand that without an error message is difficult to make a diagnosis. 

Nonetheless such behavior is clearly a bug and don't agree that ignoring it is the correct thing to do. I can perform more tests if you have any suggestion and digging around, maybe there's an error message or a log somewhere.

Unfortunately my knowledge of Spyder/conda is limited and I can't do it myself.

**Comment by ccordoba12** [comment] 2019-03-14 13:47
> I can perform more tests if you have any suggestion

That's the problem, I have almost no more suggestions. My last one is try to downgrade Qt with by running these commands in the Anaconda prompt

    conda install qt=5.6 pyqt=5.6

> maybe there's an error message or a log somewhere.

There are none, as far as I'm aware. And nobody else has reported an error like yours before. So we're even more in the dark.

**Comment by ccordoba12** [comment] 2019-03-15 11:44
@CAM-Gerlach, I don't know if you want to chime in to help @pj1989 here.

**Comment by pj1989** [comment] 2019-03-15 11:48
@ccordoba12 Unfortunatelly I downgraded Qt with the command you told me, but the problem still occurs

**Comment by ccordoba12** [comment] 2019-03-15 11:58
Ok, @CAM-Gerlach has more experience dealing with this kind of problems, so let's wait for he to give you more advice.

**Comment by CAM-Gerlach** [comment] 2019-03-15 16:53
@pj1989 I'm baffled; maybe some edge case in your graphics stack. I cannot reproduce the problem on Win 8.1 Pro x64 with the same versions of Python, Qt, PyQt, and Spyder. We've had reported issues in the past (which I was able to reproduce at the time) with autocompletion/help/introspection/real-time analysis crashing in the past when the user locked the screen or put to computer to sleep, but I can't recall a specific instance where that happened with Spyder itself. I seem to distantly remember *someone* reporting *somewhere* about *something* similar happening with the lock screen, but I can't seem to find it anywhere.

Since you've already tried the most likely fix (downgrading Qt), you should upgrade it again with ``conda update qt pyqt`` and then try the following potential steps that have a chance of resolving this particular issue. Before you do, run ``set SPYDER_DEBUG=3`` in Anaconda prompt to enable debug output for Spyder. If none of the above work, copy and paste any messages that look like errors, as well as the last 20 lines or so before them (or just the last 20 lines, if there are no obvious error messages) here inside a literal block (with triple backticks, `` ``` ``, above and below it). Then, try each of the following in order, stopping if one of them fixes the issue:

1. Temporarily disable any security, antivirus, firewall, etc. software and try again
2. Install PyOpenGL with ``conda install pyopengl``
3. Update your OS and any graphics/GPU drivers
4. If you have multiple GPU (e.g. integrated + discrete), try disabling/forcing one or the other
5. Run ``spyder --reset``, just in case. If you value your preferences (e.g. a custom syntax theme or shortcuts), make a copy of the ``spyder-py3`` directory in your user/home folder and restore if it resetting fails to fix the issue.
6. Create a new, clean conda environment, and see if the problem still persists:

```
conda create -n spyder-env -c defaults spyder=3 python=3.6
conda activate spyder-env
spyder
```

If that *does* work while previous steps have failed, provide me the output of ``conda list`` to see if I can spot an obvious culprit. Otherwise, try doing a clean uninstall and reinstall of Anaconda. Thanks, and hope this works.

**Comment by pj1989** [comment] 2019-03-18 14:48
@CAM-Gerlach 
Few updates. I followed the instructions at point 2. 3. 4. 5. and 6. Unfortunately, being a work PC, I cannot disable the antivirus as it's locked by IT. 

Unfortunately the problem seams to persist and I could not find any obvious error message in the console, even with SPYDER_DEBUG set to 3. 

The problem seams to occur **only** when I lock the PC with the WIN+L keys combination, while it doesn't occur if I lock it from Start>[User]>Lock

I'm now going to perform a clean Anaconda installation.

What I did not mention in the original post, is that I received this PC brand new from IT just 10 days ago. The number of rubbish on it should be very limited and I did not install any strange software that customize the Windows environment any-how.

Anyway... below is a copy of the full output on the terminal from the activation of the environment, up to the crash. I cannot honestly find anything anomalous in it, but you know probably better than me what should and what should not be there.

I'll proceed now with a clean uninstall and reinstall of Anaconda and see if this solve the mystery...

```
(base) C:\Users\Luca.amerio>conda activate spyder-env

(spyder-env) C:\Users\Luca.amerio>set SPYDER_DEBUG=3

(spyder-env) C:\Users\Luca.amerio>spyder
Start of MainWindow constructor
appusermodelid: 0
End of MainWindow constructor
*** Start of MainWindow setup ***
  ..core actions
  ..toolbars
  ..tools
  ..sift?
  ..plugin: internal console
    ..internal console: initializing
  ..plugin: working directory
Loading help...
Loading outline explorer...
Loading editor...
Introspection Plugin Loaded: rope
Introspection Plugin Loaded: jedi
Introspection Plugin Loaded: fallback
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x000001A6F9594E58>
current_changed: 0 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x000001A6F9594E58> 1816659578456
Added thread <spyder.widgets.editor.AnalysisThread object at 0x000001A6F9594DC8> to queue
Added thread <spyder.widgets.editor.AnalysisThread object at 0x000001A6F95A9DC8> to queue
  ..widgets
Loading file explorer...
Loading history plugin...
Updating queue:
    started: 0
    pending: 2
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x000001A6F9594DC8>
Updating queue:
    started: 0
    pending: 1
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x000001A6F95A9DC8>
Updating queue:
    started: 0
    pending: 0
Loading online help...
Updating queue:
    started: 0
    pending: 0
Loading project explorer...
Loading namespace browser...
Loading IPython console...
Setting up main window...
Setting up window...
*** End of MainWindow setup ***
Call to 'close_threads'
Initialized fallback
Initialized jedi
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x000001A6F95A9AF8>
current_changed: 0 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x000001A6F95A9AF8> 1816659663608
Added thread <spyder.widgets.editor.AnalysisThread object at 0x000001A6F95A98B8> to queue
Added thread <spyder.widgets.editor.AnalysisThread object at 0x000001A6FF682288> to queue
Updating queue:
    started: 0
    pending: 2
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x000001A6F95A98B8>
Updating queue:
    started: 1
    pending: 1
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x000001A6FF682288>
Updating queue:
    started: 0
    pending: 0
Updating queue:
    started: 0
    pending: 0
```
HERE I PRESSED WIN+L. When I logged in back (2 seconds after) Spyder wasn't open anymore
```
(spyder-env) C:\Users\Luca.amerio>
```

**Comment by CAM-Gerlach** [comment] 2019-03-18 15:26
Sorry all that didn't fix it for you, and hopefully reinstallation does. I can't find anything suspicious in that output either, so I'm not sure why its happening other than being a security software issue or a conflict with something else.

> Unfortunately, being a work PC, I cannot disable the antivirus as it's locked by IT.

Then tell IT it may be falsely causing a problem with one of the programs vital to your work, and they can do it themselves. If it resolves the problem, then they can add an appropriate exclusion/exception/rule for Spyder.

> The problem seems to occur only when I lock the PC with the WIN+L keys combination, while it doesn't occur if I lock it from Start>[User]>Lock

That's really strange, and I have no idea what's causing that difference in behavior. If you can't resolve it any other way, maybe try using AHK or something to bind a hotkey to ``Start > User > Lock``?

**Comment by pj1989** [comment] 2019-03-18 16:17
@CAM-Gerlach 
Neither the clean installation worked.
At this point I'm completely roaming in the dark.

Thank you for the help. I'll keep you posted just in case I find a culprit.

**Comment by CAM-Gerlach** [comment] 2019-03-18 17:23
@pj1989 Sorry that didn't work. In the meantime, I recommend just binding a hotkey or other shortcut to that command instead.

The only thing I can think of is your AV, firewall, or other security software is causing issues. I recommend speaking to your IT department about it, since they have much more control over whatever is happening than Spyder (we can't actually crash Python like that from within Spyder; it would have to be at the Qt/C++ level). Again, sorry about this.

**Comment by ccordoba12** [comment] 2019-03-22 17:27
Closing because there's no more we can do about this.

**Closed by ccordoba12** 2019-03-22 17:27 UTC
Labels: status:Awaiting Followup

**Comment by pj1989** [comment] 2019-03-27 15:07
The culprit ended up being a faulty Wacom driver service called: _Wacom Tablet Service for ISD_

Disabling that solved the issue. The fun part is that I don't use touch-screen features, nor have a Wacom tablet. Nonetheless, this solved the issue.

Sorry for bothering you for this issue. The first thing I obviously thought of was a problem with spyder, but this ended up being completely innocent.

Thank you for the support
Luca

**Comment by ccordoba12** [comment] 2019-03-27 15:31
Glad you found the culprit and thanks for letting us know about it.

I guess you fought a lot to finally uncover the real cause.

**Comment by jsh9** [comment] 2019-06-10 08:03
I just encountered the same issue.

Spyder 3.3.3 | Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 

I used git bash to open spyder (by typing `spyder` in git bash), and lock the screen, then log back in. Spyder disappears, and the stdout in the git bash window says "Segmentation fault".

I do not have any Wacom driver in my system.

Would you be able to relate to any of the known bugs that you know?

**Comment by ccordoba12** [comment] 2019-06-10 08:31
Sorry, I have no idea.

**Comment by jsh9** [comment] 2019-06-10 08:47
Can you think of any possible reason for the error message "Segmentation fault" showing in the terminal?

**Comment by vipish2804** [comment] 2019-10-18 14:11
> The culprit ended up being a faulty Wacom driver service called: _Wacom Tablet Service for ISD_
> 
> Disabling that solved the issue. The fun part is that I don't use touch-screen features, nor have a Wacom tablet. Nonetheless, this solved the issue.
> 
> Sorry for bothering you for this issue. The first thing I obviously thought of was a problem with spyder, but this ended up being completely innocent.
> 
Even am struggling with same issue after locking the screen my spyder is getting crashed , how did you find the faulty driver ?

**Comment by CAM-Gerlach** [comment] 2019-10-18 19:51
@vipish2804 You could try Spyder 4 bet a7 and see if the issue persists...

**Comment by vipish2804** [comment] 2019-10-21 07:37
> @vipish2804 You could try Spyder 4 bet a7 and see if the issue persists...

Issue got resolved after upgrading Spyder to 3.3.6

**Comment by Elly-78** [comment] 2020-01-04 18:11
this is now happening to me. it is driving me crazy I have reinstalled down graded etc and nothing worked. how do I find what is causing this? thanks

**Comment by jsh9** [comment] 2020-01-04 20:47
@Elly-78 Have you tried to update your Spyder and your operating system to the newest versions possible?

**Comment by CAM-Gerlach** [comment] 2020-01-04 21:01
> how do I find what is causing this? 

@Elly-78 We're going to need to know some more information. Please copy and paste your Spyder version string and all the other versions listed there and provide that here, for starters, as well as a list of _specifically_ step by step everything you've tried thus far. Spyder itself cannot normally cause crashes directly, since its a pure Python application; typically these bugs are due to an issue in Qt, the GUI library Spyder uses.

First, make sure you're using the latest version of everything by running `conda install spyder=4.0.1 spyder-kernels=1 pyqt=5.9.2 qt=5.9.7 qtpy qtawesome qtconsole` in the Anaconda environment in which Spyder is installed (and if you haven't installed with Anaconda, that is what is recommended to reduce the change of errors like these).

Then, your ensure your OS and drivers are up to date, particularly your GPU drivers, and if you have multiple GPUs (e.g. Nvidia Optimus) try disabling or forcing one or the other. You can also try the settings under `Preferences -> General -> Advanced Settings -> Rendering engine` and see if they help, as well as disabling any system security software you may have running that can conflict with Spyder.

Other than that, I would refer you to the [Spyder troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ)

**Comment by Elly-78** [comment] 2020-01-04 21:26
I am ruining spider 4.0 when I tried to install 4.0.1 I get this:
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=4.0.1

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by CAM-Gerlach** [comment] 2020-01-04 21:48
@Elly-78 Anaconda must not have uploaded it yet to their main channel; it usually takes them a few days. Just be patient on that. Just drop `spyder` from the list of specs and have it update everything else. Other than that, please provide all the information requested previously as well as the other steps you've taken as recommended above:

> Please copy and paste your Spyder version string and all the other versions listed there and provide that here, for starters, as well as a list of specifically step by step everything you've tried thus far. Spyder itself cannot normally cause crashes directly, since its a pure Python application; typically these bugs are due to an issue in Qt, the GUI library Spyder uses.

Finally, as a sidenote, make sure to include any program output inside triple backticks, like this (quote my post to see the formatting) so it displays properly:

```
Output here
```

**Comment by Elly-78** [comment] 2020-01-04 22:02
I hope this is what you meant I am totally new to this
(((conda list
# packages in environment at C:\Users\ellyo\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py37_0
asn1crypto                1.2.0                    py37_0
astroid                   2.3.3                    py37_0
astropy                   3.2.3            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.7.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
bcrypt                    3.1.7            py37he774522_0
beautifulsoup4            4.8.1                    py37_0
bitarray                  1.2.0            py37he774522_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               h7bd577a_0
bokeh                     1.4.0                    py37_0
boto                      2.49.0                   py37_0
bottleneck                1.3.1            py37h8c2d366_0
bzip2                     1.0.8                he774522_0
ca-certificates           2019.11.27                    0
certifi                   2019.11.28               py37_0
cffi                      1.13.2           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                    py37_0
conda                     4.8.0                    py37_1
conda-build               3.17.8                   py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h62dcd97_0
conda-verify              3.1.1                    py37_0
console_shortcut          0.1.1                         3
contextlib2               0.6.0.post1                py_0
cryptography              2.8              py37h7a1dbc1_0
curl                      7.67.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.29.14          py37ha925a31_0
cytoolz                   0.10.1           py37he774522_0
dask                      2.9.0                      py_0
dask-core                 2.9.0                      py_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
distributed               2.9.0                      py_0
docutils                  0.15.2                   py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
fastcache                 1.1.0            py37he774522_0
filelock                  3.0.12                     py_0
flake8                    3.7.9                    py37_0
flask                     1.1.1                      py_0
freetype                  2.9.1                ha9979f8_1
fsspec                    0.6.2                      py_0
future                    0.18.2                   py37_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glob2                     0.7                        py_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
hypothesis                4.54.2                   py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        1.3.0                    py37_0
intel-openmp              2019.4                      245
intervaltree              3.0.2                      py_0
ipykernel                 5.1.3            py37h39e3cac_0
ipython                   7.10.2           py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4.1                      py_0
jedi                      0.14.1                   py37_0
jinja2                    2.10.3                     py_0
joblib                    0.14.1                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.8.5                      py_0
jsonschema                3.2.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.2.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
keyring                   20.0.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.4               hc04afaa_0
lazy-object-proxy         1.4.3            py37he774522_0
libarchive                3.3.3                h0643e63_5
libcurl                   7.67.0               h2a8f88b_0
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
llvmlite                  0.30.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.4.2            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.1            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
mock                      3.0.5                    py37_0
more-itertools            8.0.2                      py_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_0
nbformat                  4.4.0                    py37_0
networkx                  2.4                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.2                    py37_0
numba                     0.46.0           py37hf9181ef_0
numexpr                   2.7.0            py37hdce8814_0
numpy                     1.17.4           py37h4320e6b_0
numpy-base                1.17.4           py37hc3f5095_0
numpydoc                  0.9.1                      py_0
olefile                   0.46                     py37_0
openpyxl                  3.0.2                      py_0
openssl                   1.1.1d               he774522_3
packaging                 19.2                       py_0
pandas                    0.25.3           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.6.0                    py37_0
parso                     0.5.2                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py37_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py37_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py37_0
pep8                      1.7.1                    py37_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.1            py37hdc69c19_0
pip                       19.3.1                   py37_0
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.10                     py_0
psutil                    5.6.7            py37he774522_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.3         py37h7a1dbc1_0
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.5.2                      py_0
pylint                    2.4.4                    py37_0
pympler                   0.7                        py_0
pynacl                    1.3.0            py37h62dcd97_0
pyodbc                    4.0.27           py37ha925a31_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.5                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.15.6           py37he774522_0
pysocks                   1.7.1                    py37_0
pytables                  3.6.1            py37h1da0976_0
pytest                    5.3.2                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.7.0                      py_0
pytest-astropy-header     0.1.1                      py_0
pytest-doctestplus        0.5.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.3                h8c8aaf0_1
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.2                      py_0
python-language-server    0.31.2                   py37_0
python-libarchive-c       2.8                     py37_13
pytz                      2019.3                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_0
pywin32-ctypes            0.2.0                    py37_0
pywinpty                  0.5.7                    py37_0
pyyaml                    5.2              py37he774522_0
pyzmq                     18.1.0           py37ha925a31_0
qdarkstyle                2.7                        py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.0                      py_0
qtconsole                 4.6.0                      py_0
qtpy                      1.9.0                      py_0
requests                  2.22.0                   py37_1
rope                      0.14.0                     py_0
rtree                     0.8.3                    py37_0
ruamel_yaml               0.15.87          py37he774522_0
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.22             py37h6288b17_0
scipy                     1.3.2            py37h29ff71c_0
seaborn                   0.9.0              pyh91ea838_1
send2trash                1.5.0                    py37_0
setuptools                42.0.2                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.13.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.5                    py37_0
sphinx                    2.3.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    4.0.0                    py37_0
spyder-kernels            1.8.1                    py37_0
sqlalchemy                1.3.11           py37he774522_0
sqlite                    3.30.1               he774522_0
statsmodels               0.10.1           py37h8c2d366_0
sympy                     1.5                      py37_0
tbb                       2019.4               h74a9793_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37he774522_0
tqdm                      4.40.2                     py_0
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.25.7                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.9.0                    py37_1
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.6                      py_0
xlwings                   0.16.3                   py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zict                      1.0.0                      py_0
zipp                      0.6.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
)))

I have uninstalled and reinstalled anacoda I have updated spider and anaconda I have updated windows.

**Comment by CAM-Gerlach** [comment] 2020-01-04 22:13
No, I thought I was very clear but I guess not, but that still works, however, as I said before, please put it inside a verbatim block and that inside a details block so it doesn't clog the thread. Just copy/paste the following and then paste everything in the above post inside the inner backticks. You can check that you did it properly by using the "Preview" function.

~~~
<details>

```

PASTE YOUR OUTPUT HERE

```

</details>
~~~

In any case, I suspect it may be some sort of GPU issue, or some other software on your system (antivirus, security, firewall, etc) that is interfering. Please try the remaining steps above as well as those in the troubleshooting guide. Thanks and best of luck.

**Comment by Elly-78** [comment] 2020-01-04 23:32
first you were clear, this is my first time writing here and i misunderstood.  also thanks for your time and patience.


```
conda install  pyqt=5.9.2 qt=5.9.7 qtpy qtawesome qtconsole
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


```
I can't find the "Rendering engine" in ```Preferences -> General -> Advanced Settings ->```
I have only one GPU the driver is  up to date 
installing spider in a new environment did not help

**Comment by Elly-78** [comment] 2020-01-04 23:39
just realized that if Anaconda is in the foreground when I lock the screen then it crashes.
I get a 
```

python has stopped working

```

**Comment by CAM-Gerlach** [comment] 2020-01-05 00:19
You don't see it here? I'm running 4.0.1 (technically via dev build, but it should be the same as the release version) so maybe they changed the name in 4.0.1; UI design and text was one of my areas of expertise but I'm not a Spyder core dev anymore so I don't keep careful track. 

![image](https://user-images.githubusercontent.com/17051931/71773193-d9f20100-2f26-11ea-922d-83aec2bf8838.png)

> just realized that if Anaconda is in the foreground

What do you mean, Anaconda? Anaconda is an entire Python distribution. Do you mean Anaconda prompt, or maybe Anaconda Navigator? On Windows, you shouldn't ever use Navigator and instead always launch Spyder via the shortcut, since its far faster, easier and doesn't involve any number of Navigator-specific bugs.

**Comment by Elly-78** [comment] 2020-01-05 05:42
I meant the Navigator, the rendering engine setting was right in front of me but it dose not help.
The problem appears on the window in the foreground if that is the Navigator or Spider. It also happens when I launch spider without the Navigator (as I will do from now on).
Thanks again for taking the time!

**Comment by Alex-Chervony** [comment] 2020-05-01 00:07
> The culprit ended up being a faulty Wacom driver service called: _Wacom Tablet Service for ISD_
> 
> Disabling that solved the issue. The fun part is that I don't use touch-screen features, nor have a Wacom tablet. Nonetheless, this solved the issue.
> 
> Sorry for bothering you for this issue. The first thing I obviously thought of was a problem with spyder, but this ended up being completely innocent.
> 
> Thank you for the support
> Luca

This worked for me, thanks!
Wacom driver seemed to be at fault. (Device Manager -> Human Interface Devices -> Wacom Device -> either click properties and update under driver or click the "Update device driver" button on the top.

The Wacom driver was not showing as faulty, but manually running a driver update on it seems to have solved the issue.


My system:
Lenovo IdeaPad Flex (Touch screen which I never use)
Spyder 4.0.1
Windows 10 
![image](https://user-images.githubusercontent.com/17322680/80769989-cc7b0b00-8b03-11ea-83d1-7dfa4865bb3d.png)
![image](https://user-images.githubusercontent.com/17322680/80770202-81152c80-8b04-11ea-80eb-37f2e7e4f357.png)
