### ISSUE TITLE
Help fails to produce Rich Text on annotated functions

### ISSUE THREAD

**Issue by silentquasar** [spyder-ide/spyder#3571] opened 2016-10-20 20:36 UTC
# Description of your problem
## What steps will reproduce the problem?
1. Create a function and use function annotations, à la [PEP-3107](https://www.python.org/dev/peps/pep-3107/) and save the module (in this case to `doc_check.py`). For example:

``` python
def test_function(value: int) -> int:
    """This is a very boring function

    This function just returns whatever you put into it.

    Parameters
    ----------
    value
        This is an integer

    Returns
    -------
    test_function
        This is the same as whatever we put in the function
    """
    return value
```
1. Import the module in the command window
2. Type the module.function name and press Ctrl+I. 
### Expected Output

I expect to see Rich Text help in the Help pane, similar to that generated from a sphinx-quickstart html output:
![test_function_html_output](https://cloud.githubusercontent.com/assets/7116641/19576672/b716b0d0-96c8-11e6-9af8-8d8523888b99.png)

(It should be noted that in general section headers are handled well in the Help pane--I'm not sure why they're not showing up in my basic Sphinx setup. Napoleon handles them well:
![test_function_html_output_napoleon](https://cloud.githubusercontent.com/assets/7116641/19576782/3f40769e-96c9-11e6-8b77-dfe531d83984.png)
### What I see

In the Spyder Help pane I just get **No documentation available**
## Versions and main components
- Spyder Version: 3.0.1
- Python Version: 3.4.5
- Operating system: Windows 7 Enterprise 64-bit
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by malliwi88** [comment] 2016-10-22 01:22
Hi @silentquasar.

I reproduce your indications and obtain this:

![seleccion_003](https://cloud.githubusercontent.com/assets/5307894/19615790/a6d2dc46-97ca-11e6-9783-b925d25aafd3.png)

Is it accord with  your expected output?

# My Details
## versions and OS
* Spyder 3.1
* Python 3.5.2 :: Anaconda custom (64-bit)
* Linux Deepin 15.03

## Dependences
> jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

## My recommendation

I think @silentquasar can wait a little bit for  release v3.1. What do you think @ccordoba12  @goanpeca @rlaverde

**Comment by ccordoba12** [comment] 2016-10-22 15:16
@malliwi88, yes, please try things on Windows to double check :-) If the problem is not present there, we could close this issue because we can't reproduce it.

**Comment by stonebig** [comment] 2016-10-22 16:51
hi,

I'm not sure if it's truly an error but applying the procedure on windows I get a no documentation.
![test_function](https://cloud.githubusercontent.com/assets/4312421/19620989/83be73e6-9888-11e6-8660-43173981bd8a.PNG)

**Comment by stonebig** [comment] 2016-10-22 16:56
and then applying the patch, closing and restarting Spyder, I get the "nice " behavior.

**Comment by stonebig** [comment] 2016-10-22 16:59
and then REMOVING the patch, closing and restarting Spyder, I get the "bad" no documentation again.
==> the patch **does** something on windows

**Comment by ccordoba12** [comment] 2016-10-22 17:19
@stonebig, what do you mean by your last comment? I don't get it :-/

**Comment by stonebig** [comment] 2016-10-22 17:27
If I remove the patch, I'm back to a bad behavior. so it help ensure that it doesn't work just because I start Spyder a second time

**Comment by malliwi88** [comment] 2016-10-22 17:57
Hi Guys, these are my results on windows machine (Win 7 64 bits)

@ccordoba12 @silentquasar @stonebig My suggestion is no longer needed, it already works in the Spyder 3.0.1.

As you can see, `A picture is worth a thousand words.`

![test win seleccion_004](https://cloud.githubusercontent.com/assets/5307894/19621383/309ca0f2-9856-11e6-983f-b8df53a2f44b.png)

# Additional details

## Install anaconda

![test win anaconda installation seleccion_005](https://cloud.githubusercontent.com/assets/5307894/19621414/06f20cbe-9857-11e6-855b-3464d073f445.png)

## DEPENDENCES!!

>jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by silentquasar** [comment] 2016-10-22 18:28
Perhaps this has something to do with Python 3.4 vs 3.5? I hadn't tried with Python 3.5. You'll notice @malliwi88, that your output still lacks the return type annotation in the function definition. With the patch applied, I get this: 
![patch_applied](https://cloud.githubusercontent.com/assets/7116641/19621610/2fdda456-984a-11e6-8565-f80bf79bf233.png)

If I get a chance I'll try to figure out why it partly works as-is in Python 3.5.

**Closed** 2017-01-08 21:24 UTC
Labels: Comp-Help, Type-Bug
