### ISSUE TITLE
Problems pop out when changing __repr__ in a class inherent str class

### ISSUE THREAD

**Issue by plinypan** [spyder-ide/spyder#6087] opened 2017-12-29 16:20 UTC
## Description

**What steps will reproduce the problem?**

1. Create a class with parent str
2. Define __repr or __str__ in the class otherwise
3. Create an instance of this new class and try to print it

**What is the expected output? What do you see instead?**
Return of the newly defined __repr__ should be printed instead

**Please provide any additional information below**
I was using Anaconda3.6
  File "D:\Coding\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "D:\Coding\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 220, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "D:\Coding\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 354, in handle_exec_method
    view = ast.literal_eval(literal)
  File "D:\Coding\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "D:\Coding\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    {'a': {'type': 'tp', 'size': 1, 'color': '#800000', 'view': tp:2016}}
                                                                  ^
SyntaxError: invalid syntax

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :

**Comment by ccordoba12** [comment] 2017-12-29 17:48
Thanks for reporting. This is a duplicate of issue #5636 and it'll be fixed in our next release (3.2.6).

**Closed by ccordoba12** 2017-12-29 17:48 UTC
