### ISSUE TITLE
Startup warning every time in Spyder 5.0.0 on Win10 using Python 3.9.2

### ISSUE THREAD

**Issue by pythagorus2** [spyder-ide/spyder#15123] opened 2021-04-05 21:57 UTC
### What steps will reproduce the problem?

1) Originally had Python 3.9.2 which comes with older Spyder 4.2.2. Then downloaded official Windows 64bit installer for newer Spyder 4.2.5 which ended up downloading to different folder than orignal binaries. That worked great though still had old version with Python base install.
2) Later noticed Spyder 5.0.0 avail when used Help, Check for updates. So downloaded official Windows64-bit installer on 4/5/2021 and ran that. 
3) Tried tidy up by running 'pip uninstall spyder-4.2.2' to remove original 4.2.2. That seemed to work okay.
3) UNFORTUNATELY, now every time I start up Spyder 5.0.0 (no other versions exist on my machine now), it gives the following warning popup message:
-------------------------------------
Error
You have missing dependencies!

# Mandatory:
spyder_kernels >=2.0.1,<2.1.0 :
2.0.1 (NOK)

Please install them to avoid this message.
----------------------------------------

4) Tried running 'pip uninstall spyder_kernels' to remove an outdated 1.10 version, which it said was successful. 
5) Then ran 'pip install spyder_kernels' to get the latest 2.0.1 installed right back into the base Python install. (NOTE: I checked  and only saw 2.0.0 and 2.0.1 available) and the warning said to only use greater than or equal to 2.0.1. 
NOW even after having updated the spyder_kernels, I'm still getting the same warning popup every time I open Spyder 5.0.0. Wonder why it just is not seeing that I do have spyder_kernels?

NOTE: Prior Spyder version 4.2.5 never showed that warning. I did do the update on spyder_kernels as the popup advised. Other than that, the Spyder editor did open up and seem to run okay...but sure would like that warning popup to get resolved! ;)

**Comment by ccordoba12** [comment] 2021-04-05 22:11
Hey @pythagorus2, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-05 22:11 UTC
