### ISSUE TITLE
Spyder editor keeps crashing

### ISSUE THREAD

**Issue by xiaoyuejin** [spyder-ide/spyder#6085] opened 2017-12-29 08:29 UTC
## Description

**What steps will reproduce the problem?**

1. Updated to spyder 3.2.4
2. In the editor, type in, for example, "numpy.", OR
3. type in "(" and autocomplete to "()"

Note: I have
parso 0.1.0
jedi 0.10.2
But the problem remains.

**What is the expected output? What do you see instead?**
Popup window: [Spyder has encountered a problem]

**Please provide any additional information below**

  File "c:\python27\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "c:\python27\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "c:\python27\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "c:\python27\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "c:\python27\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "c:\python27\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "c:\python27\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "c:\python27\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2354, in load

**Comment by ccordoba12** [comment] 2017-12-29 17:41
The error is not complete. Please copy it from our error dialog and paste it in full here.

**Comment by CAM-Gerlach** [comment] 2017-12-29 20:44
It still looks very much like the `parso` error; e.g. #5673 , the part of the traceback we can see fits the signature exactly. Most importantly, what does the last line of the error message say? 

Also, given it looks like you are using `pip`, it could be some arcane issue with that. Due to the frequency of such problems, we can only recommend that you use the Anaconda distribution instead, though you're welcome to try to get it on your own. Also, you can try updating both `parso` and `jedi` to their latest versions, which _should_ now work well together.

 Finally, if we don't hear from you in one week (7 days), we'll have to close this error report. Best of luck!

**Comment by xiaoyuejin** [comment] 2017-12-29 21:20
I am using pythonxy 2.7.10, i.e. Python 2.7.10.

I had upgraded both parso and jedi to the latest version, then had this problem. I was digging in github and found that sometimes the latest versions of parso and jedi cause problems. That's why I downgraded both them. But the problem remains.

And, my spyder does NOT show error message in full. The pop-up window only says "Spyder has encountered a problem", then "report to GITHUB" or "OK". Where can I load/find the full error message?

**Comment by ccordoba12** [comment] 2017-12-29 21:24
Please press the button that says `Show details` (or something like that) and copy the text that appears below.

**Comment by CAM-Gerlach** [comment] 2017-12-29 21:24
> I had upgraded both parso and jedi to the latest version, then had this problem. 

What versions, precisely?

> Where can I load/find the full error message?

You can also try the Spyder internal console. View > Panes > Internal Console.

Not sure why the full error message isn't getting copied...I've seen this very frequently in people's posts, but I've never understood why since I've never been able to reproduce it on my machine.

**Comment by xiaoyuejin** [comment] 2017-12-29 21:25
I just uploaded a screenshot of the popup window. There is no place where I can click for "more details"...

![untitled](https://user-images.githubusercontent.com/1095914/34447760-1ba36606-eca4-11e7-864d-200a72cd38f4.png)

**Comment by xiaoyuejin** [comment] 2017-12-29 21:27
But I found the internal console now. Here is the full error:

>>> Traceback (most recent call last):
  File "c:\python27\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "c:\python27\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "c:\python27\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "c:\python27\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "c:\python27\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "c:\python27\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "c:\python27\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "c:\python27\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 18.0.1 (c:\python27\lib\site-packages), Requirement.parse('setuptools>=18.5'))

I will try to upgrade setuptools now and will report back. Thanks guys!

**Comment by CAM-Gerlach** [comment] 2017-12-29 21:27
> I just uploaded a screenshot of the popup window. There is no place where I can click for "more details"...

You can't see the full thing when you "Submit to Github"? Also, try the internal console as mentioned before.

**Comment by xiaoyuejin** [comment] 2017-12-29 21:28
No, I can't see the full thing when I submit to github... There is only a popup window but no text panel in it.

**Comment by ccordoba12** [comment] 2017-12-29 21:31
Please try to use a more recent version of, well, everything, Python, setuptools, PyQt. etc.

Closing because this is why we don't give support to installations other than Anaconda.

**Closed by ccordoba12** 2017-12-29 21:31 UTC
Labels: status:AwaitingFollowup

**Comment by CAM-Gerlach** [comment] 2017-12-29 21:33
> Closing because this is why we don't give support to installations other than Anaconda.

Yup...
