### ISSUE TITLE
Spyder crash when I use "Go to Definition" for some times

### ISSUE THREAD

**Issue by gansaihua** [spyder-ide/spyder#4324] opened 2017-04-04 13:04 UTC
## Description

**What steps will reproduce the problem?**

1. Writing scripts 
2. Or open a file by "Go to definition"

**What is the expected output? What do you see instead?**

Spyder exits, with a diagram saying python exit unexpectedly,
I have to reopen it with all my scripts missing

line 3: 30318 Segmentation fault: 11  
/anaconda2/python.app/Contents/MacOS/python "$@"

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by ccordoba12** [comment] 2017-04-04 19:09
This is known issue, but unfortunately we don't know how to fix it because it's not reproducible all the time (as you say).

Closing it as a duplicate of issue #3940.

**Closed by ccordoba12** 2017-04-04 19:09 UTC
Labels: resolution:Duplicate
