### ISSUE TITLE
ipykernel not found with Anaconda python interpreter

### ISSUE THREAD

**Issue by Earthson** [spyder-ide/spyder#3881] opened 2016-12-23 02:54 UTC
## Console start failed with ipykernel not found on Anaconda python interpreter

python environment or installation doesn't have the ipykernel module installed on it.

but `python -m ipykernel` just works fine.

1. use latest dmg version spyder
2. set python interpreter to anaconda python like "/Users/earthson/.opt/anaconda/bin/python"
3. start new console: failed with ipykernel not found

* Spyder Version: 3.0.2 macOS dmg version
* Python Version: 3.5.2 use Anaconda
* Operating system: macOS 12.12

**Comment by ccordoba12** [comment] 2016-12-23 14:16
Thanks for reporting. This is a duplicate of issue #3819.

**Closed by ccordoba12** 2016-12-23 14:16 UTC
