### ISSUE TITLE
Ctrl + I not functioning for any Object

### ISSUE THREAD

**Issue by akanksha64** [spyder-ide/spyder#6318] opened 2018-01-28 17:56 UTC
## CTRL + I not performing

What steps will reproduce the problem?

1. Type an object
2. Select the object or put the cursor on object
3. Press Ctrl + I
4. No result on help tab

**What is the expected output? What do you see instead?**
Help Tab to return the definition of Object along with description of arguments for that object.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-28 19:00
This is a duplicate of issue #5782. Please see there for possible solutions.

**Closed by ccordoba12** 2018-01-28 19:00 UTC
