### ISSUE TITLE
custom-dark

### ISSUE THREAD

**Issue by GalaChen** [spyder-ide/spyder#20858] opened 2023-04-20 17:17 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\configdialog.py", line 213, in accept
    configpage.apply_changes()
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\configdialog.py", line 103, in apply_changes
    self.apply_callback()
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\configdialog.py", line 268, in <lambda>
    self.apply_settings(self.changed_options))
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\configdialog.py", line 1183, in apply_settings
    self.main.ipyconsole.apply_plugin_settings(['color_scheme_name'])
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 699, in apply_plugin_settings
    client.set_color_scheme(color_scheme_o)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 380, in set_color_scheme
    self.shellwidget.set_color_scheme(color_scheme)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 141, in set_color_scheme
    self._syntax_style_changed()
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 464, in _syntax_style_changed
    self._highlighter._style = create_style_class(self.syntax_style)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\ipython\style.py", line 171, in create_style_class
    class StyleClass(Style):
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\pygments\style.py", line 101, in __new__
    ndef[0] = colorformat(styledef)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\pygments\style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format '#5b0b0'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.15.2, PyQt5 5.15.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.2.0 (OK)
pycodestyle >=2.3:  2.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.17.1 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.0.3 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by dalthviz** [comment] 2023-04-20 22:37
Hi @GalaChen thank you for the feedback! This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/20485

Let us know if the info in the linked issue above helps!

**Comment by dalthviz** [comment] 2023-05-19 20:03
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/10269

**Closed by dalthviz** 2023-05-19 20:03 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
