### ISSUE TITLE
Running SPyder script throws an error

### ISSUE THREAD

**Issue by chaseplastic** [spyder-ide/spyder#5173] opened 2017-09-08 17:59 UTC
## Description

**What steps will reproduce the problem?**

1. Upgrading Spyder to 3.2.2
2. Running a script
3. Expecting an outcome

**What is the expected output? What do you see instead?**
Error message and the outcome :)

**Please provide any additional information below**

  File "/Users/davkenda1/anaconda/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/davkenda1/anaconda/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by rlaverde** [comment] 2017-09-08 18:34
Closing as duplicate of #5158

**Closed by rlaverde** 2017-09-08 18:34 UTC
