### ISSUE TITLE
"code completion" can not work

### ISSUE THREAD

**Issue by jhlf** [spyder-ide/spyder#6139] opened 2018-01-05 12:18 UTC
## Description of your problem

The "Code completion" couldn't work in editor, but work in "IPython console".

**What steps will reproduce the problem?**

1. anytime

## Versions and main components

* Spyder Version: 3.2.4, 3.2.5
* Python Version: 3.6
* Operating system: Windows 10

## Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2018-01-05 16:17
This is a duplicate of issue #5782. Please read that issue for possible fixes for this problem.

**Closed by ccordoba12** 2018-01-05 16:17 UTC
