### ISSUE TITLE
Removed the Debugger from the topbar? How can I fix this? What is going on? 

### ISSUE THREAD

**Issue by Leohanhart** [spyder-ide/spyder#22682] opened 2024-10-16 15:39 UTC
![image](https://github.com/user-attachments/assets/a77bf017-a5f6-4954-8743-860a7967db43)

![image](https://github.com/user-attachments/assets/3ff7d2ab-1679-4b2d-9245-9c48b15242aa)
![image](https://github.com/user-attachments/assets/70bf21d0-2743-4117-90d2-4f7b6638bdd3)

Okey, there is a very big mistake in your new release 6.2. 
Like you can see there is no Next or Stop button on the debugger on the debugger of the topbar. 
This means that there is no possiblity to debug/check the varibles at the same time. This is a big problem! 
I use this menu 500 times a day, every day. This means I need to press 2000 times a day for nothing. 

Can you please fix this ASAP. PLEASE!

**Comment by Leohanhart** [comment] 2024-10-16 15:43
Like the button from to the next breakpoint is removed from the topbar. This the most important button
I press it 50 times a day. You disrupt my work verybad. Unbelievable.

**Comment by Leohanhart** [comment] 2024-10-16 15:44
It's bizar, sorry if this sound ragy but I cant believe that such an important organisation like you guys makes such big mistakes.

**Comment by Leohanhart** [comment] 2024-10-16 15:45
Now I need to switch back to version 5. Lol

**Comment by Leohanhart** [comment] 2024-10-17 10:39
@ccordoba12 Do you already know a fix or is there an answer on this question?
Love, 
Leo Hanhart

**Comment by ccordoba12** [comment] 2024-10-17 14:15
Hey @Leohanhart, thanks for reporting. This is a duplicate of issue #22434, which will be fixed in our next version (6.0.2), to be released in a week and a half.

The solution will involve restoring the debugger controls to the top toolbar but hidden by default to no show repeated functionality in there and the Debugger pane. However, they'll be easily accessible by going to the menu entry `View > Toolbars > Control debugger toolbar`.

**Closed by ccordoba12** 2024-10-17 14:15 UTC

**Comment by Leohanhart** [comment] 2024-10-21 10:25
@ccordoba12  I have to admit I'm not very sure how it will look like. But I'm very gradfull for your reply and the re-adding of this feature.Without it I can't use spyder anymore and I love it so much. I'm scared that I can work without. Below is a picture of my normal setup and I think it's one of the best once around. 
Thank you for maintaining this project.

![image](https://github.com/user-attachments/assets/0c782bbc-721f-4e2f-9659-77b0f5f404de)

**Comment by Leohanhart** [comment] 2024-10-21 10:28
@ccordoba12 What I also think is a general problem. I lot of spyder user I know don't use the debugger function at all. Or don't use all features. But these programmers should never become leading in developing. I am a very specialised developer and I really use all functionality's all the time. Removing these because people in general not use it the wrong direction I think. 

People started using spider because specialists started using them. You see what I mean.

**Comment by ccordoba12** [comment] 2024-10-21 15:23
> Thank you for maintaining this project.

No problem, and thanks for your kind words about Spyder!

> Removing these because people in general not use it the wrong direction I think.

We didn't remove the buttons that control the debugger, we just move them to the new Debugger pane, as can be seen in https://github.com/spyder-ide/spyder/issues/22434#issuecomment-2347895999 (see the top left buttons there).
