### ISSUE TITLE
Not Able to open DataFrame variable

### ISSUE THREAD

**Issue by vaishguru** [spyder-ide/spyder#14524] opened 2021-01-02 03:33 UTC
### What steps will reproduce the problem?

I am using Python version 3.8 ad Spyder 4.2. Not able to open DataFrame objects. Getting error

### Traceback
```python-traceback
  File "C:\Users\vaish\anaconda3\lib\site-packages\pandas\core\generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "C:\Users\vaish\anaconda3\lib\site-packages\pandas\core\generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "C:\Users\vaish\anaconda3\lib\site-packages\pandas\core\generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  [Previous line repeated 993 more times]
  File "C:\Users\vaish\anaconda3\lib\site-packages\pandas\core\generic.py", line 493, in _info_axis
    return getattr(self, self._info_axis_name)
  File "C:\Users\vaish\anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas\_libs\properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
  File "C:\Users\vaish\anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.15.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  47.3.0.post20200616 (OK)
sphinx >=0.6.6                  :  3.4.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  18.1.1 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.2.2 (OK)
numpy >=1.7                     :  1.19.1 (OK)
pandas >=1.1.1                  :  1.0.5 (NOK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-01-02 16:06
Hey @vaishguru, thanks for reporting. According to your report above, you're using Pandas 1.0.5, while Spyder requires Pandas 1.1.1.

So please update to that version by closing Spyder, opening the Anaconda Prompt and running there

    conda install pandas=1.1.1

That should fix your problem.

**Comment by vaishguru** [comment] 2021-01-02 18:56
Hi, Thanks for your support.
I have installed pandas 1.1.1 but still not able to open DataFrame.

below is outcome of pd.show_versions() to give more detail on versions installed.
INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : English_United States.1252

pandas           : 1.1.1
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 49.6.0.post20200814
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.17.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.16.2
xlrd             : None
xlwt             : None
numba            : None

**Comment by ccordoba12** [comment] 2021-01-03 16:09
Ok, please post a simple dataframe that generates this error so we can try to reproduce and fix it in our side.

**Comment by ccordoba12** [comment] 2021-02-07 18:31
Closing due to lack of response.

**Closed by ccordoba12** 2021-02-07 18:31 UTC
Labels: status:Awaiting Followup

**Comment by vaishguru** [comment] 2021-02-08 16:55
I was able to get this worked but only with python 3.7 and spyder 4.15
version.
