### ISSUE TITLE
Run selection switches focus to the Console

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#12623] opened 2020-05-06 07:52 UTC
Maybe this is intended behaviour, in which case it would be useful to have the option to switch it off.

I use F9 often to cherry-pick lines to run from the Editor and see what happens in the Variable explorer. Thus, I don't really need to enter code in the console. In fact, I rarely need to type code in the console - I write most of the code in the Editor and run it from there.

I'm on Spyder 4.1.2

**Comment by dalthviz** [comment] 2020-05-06 16:52
Hi @gerazov I think that an option for that already exits:

![image](https://user-images.githubusercontent.com/16781833/81205134-e39c7b80-8f8f-11ea-92e8-e6ac12404528.png)

Although if that isn't working let us know :)

**Comment by bcolsen** [comment] 2020-05-06 17:18
@gerazov Is either your console or editor undocked(in a separate window)?

**Comment by dalthviz** [comment] 2020-05-06 17:21
Good catch @bcolsen if that's the case then this could be a duplicate of #11283

**Comment by gerazov** [comment] 2020-05-06 17:47
Hi @dalthviz thanks for the tip - I wasn't aware of it being there. The weird thing is it is checked in my settings and still I loose focus. 
@bcolsen it actually happens when I activate a New window for the Editor. When I close the New window it works as expected. So maybe this transfers to #11283?

**Comment by dalthviz** [comment] 2020-05-06 18:07
Duplicate of #11283
Thanks @gerazov for the clarifications! then I think we should close this in favor of #11283

**Closed** 2020-05-06 18:07 UTC
Labels: status:Awaiting Followup
