### ISSUE TITLE
Don't know how to solve "Error" 

### ISSUE THREAD

**Issue by Vio-Chan** [spyder-ide/spyder#15221] opened 2021-04-10 03:42 UTC
### What steps will reproduce the problem?

When I open spyder, it tells me "You have missing dependencies" and tells me "spyder_kernels>=2.0.1,<2.1.0:2.0.1(NOK)". But spyder_kernels on my computer is 2.0.1, I don't konw how to solve this problem. Looking forward to answer, thanks!

**Comment by ccordoba12** [comment] 2021-04-10 16:30
Hey @Vio-Chan, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-10 16:30 UTC
