### ISSUE TITLE
TypeError: _show_prompt() got an unexpected keyword argument 'separator'

### ISSUE THREAD

**Issue by yuting0817** [spyder-ide/spyder#19635] opened 2022-09-27 19:25 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
* Spyder version: 5.1.5 None
* Python version: 3.9.12 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

**Comment by dalthviz** [comment] 2022-09-27 19:33
Hi @yuting0817 could you describe the problem you are experiencing? Also, how did you install Spyder? Seems like you are using Spyder 5.1.5 so I would suggest you to update to at least Spyder 5.2.2.

Let us know if updating helps

**Comment by yuting0817** [comment] 2022-09-27 19:50
![螢幕擷取畫面 2022-09-28 034923](https://user-images.githubusercontent.com/114524710/192621876-0080e72e-0bbe-4a13-a48e-b5c1039775e2.png)

Ｉ　ｄｏｎｏｔ　ｋｎｏｗ

**Comment by dalthviz** [comment] 2022-09-27 19:52
Could you please click the `Show details` button and paste here the extra information that appears?

**Comment by yuting0817** [comment] 2022-09-27 19:54
![螢幕擷取畫面 2022-09-28 035412](https://user-images.githubusercontent.com/114524710/192622824-f7f72887-fd50-4b24-aa6a-f0fa7884936c.png)

**Comment by dalthviz** [comment] 2022-09-28 14:45
You will need to update @yuting0817 to at least 5.2.2 then. This seems like a duplicate of #17616 and follow the instructions to update at https://github.com/spyder-ide/spyder/issues/17616#issuecomment-1219701036

Let us know if updating helps

**Comment by dalthviz** [comment] 2022-10-19 16:07
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/17616

**Closed by dalthviz** 2022-10-19 16:07 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
