### ISSUE TITLE
Show selector for classes and functions not working

### ISSUE THREAD

**Issue by muondude** [spyder-ide/spyder#17194] opened 2022-01-14 18:48 UTC
### What steps will reproduce the problem?

I have turned on Show selector for classes and functions.
In some project files it works and other it does not.
If I turn it off, apply, then turn it back on, it works in some open files but not others.  If I close the file and then reopen it works. Inconsistent behaviour.

I am unable to share my code.

**Comment by ccordoba12** [comment] 2022-01-15 17:13
Hey @muondude, thanks for reporting. Unfortunately you didn't report your Spyder version, but I think this is a duplicate of issue #16406, which we'll try to fix in the coming months.

If you're not using at least Spyder 5.1.5, please update to it because it fixes several issues with the Outline and the selector for classes and functions (both use the same info). The bugs left are the ones reported on issue #16406.

**Closed by ccordoba12** 2022-01-15 17:13 UTC

**Comment by muondude** [comment] 2022-01-16 17:27
I’m running:

 

* Spyder version: 5.1.5 None

* Python version: 3.9.7 64-bit

* Qt version: 5.12.9

* PyQt5 version: 5.12.3

* Operating System: Darwin 21.2.0

 

-- Sam

------------------------------

Samuel Gasster, PhD

------------------------------

 

From: Carlos Cordoba ***@***.***>
Reply-To: spyder-ide/spyder ***@***.***>
Date: Saturday, January 15, 2022 at 9:13 AM
To: spyder-ide/spyder ***@***.***>
Cc: Samuel Gasster ***@***.***>, Mention ***@***.***>
Subject: Re: [spyder-ide/spyder] Show selector for classes and functions not working (Issue #17194)

 

Hey @muondude, thanks for reporting. Unfortunately you didn't report your Spyder version, but I think this is a duplicate of issue #16406, which we'll try to fix in the coming months.

If you're not using at least Spyder 5.1.5, please update to it because it fixes several issues with the Outline and the selector for classes and functions (both use the same info). The bugs left are the ones reported on issue #16406.

**Comment by bpruess** [comment] 2024-11-12 20:05
Hey Spyder devs, this has been an on going problem for me, across multiple versions of Spyder on Windows and Mac OS. It seems like the selector for classes and functions work for a while, then "breaks" and no longer works. For example I am on Windows 10, Python 3.9, Spyder 5.4.3, and the selector only displays <None>.

**Comment by ccordoba12** [comment] 2024-11-13 16:29
@bpruess, no one has reported that before but please update to Spyder 5.5.1 (if you're in Anaconda) and try again.

I think that version comes with some improvements related to that functionality.

**Comment by bpruess** [comment] 2025-03-19 21:13
> [@bpruess](https://github.com/bpruess), no one has reported that before but please update to Spyder 5.5.1 (if you're in Anaconda) and try again.
> 
> I think that version comes with some improvements related to that functionality.

Hi Ccordoba, thank you for your reply, and developing the great software Spyder!! The issue persisted regardless of Spyder version, across multiple computers and OS's for me (Windows 10 and mac os). I figured out the solution using the help of LLM's, chat gpt suggested i try deleting the .spyder-py3 folder, and this worked in all cases to restore the functionality of Classes and Function selector. I've noticed that if I try to change the Preferences, then the problem comes back, so I just have to use Spyder with default preferences ., which is ok.
