### ISSUE TITLE
Content Assistants

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#82] opened 2015-02-16 23:19 UTC
_From [mproel...@googlemail.com](https://code.google.com/u/105494983286078857315/) on 2009-10-19T01:56:57Z_

Hi there,

A contant assistant (as in pydev http://pydev.org/manual_adv_assistants.html ) would help a lot as well,

especially the "create docstring" or "Surround code with try..except or 
try..finally" is very useful.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=82_

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:19
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-04-15T06:51:43Z_

**Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:19
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:05:06Z_

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:19
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-29T04:11:55Z_

**Status:** ContributorNeeded

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:19
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:06:49Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:19
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:16:53Z_

**Status:** HelpNeeded

**Comment by goanpeca** [comment] 2015-03-02 23:23
I think this is a cool idea to implement

**Comment by goanpeca** [comment] 2015-04-20 17:11
Do you find this useful @spyder-ide/collaborators ?

**Comment by ccordoba12** [comment] 2015-04-20 19:37
This is a duplicate of issue #588. Someone else try to implement it on Bitbucket, so take a look at it first :-)

**Closed by ccordoba12** 2015-04-20 19:37 UTC
Labels: 2–5 stars, duplicate, Editor, enhancement, help wanted

**Comment by goanpeca** [comment] 2015-04-20 19:57
The code snippets stuff?

**Comment by ccordoba12** [comment] 2015-04-20 19:57
Yep
