### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shivam0712** [spyder-ide/spyder#6553] opened 2018-02-28 13:03 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 2040, in <lambda>
    (lambda x: pprint_thing(x, escape_chars=('\t', '\r', '\n'))))
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\printing.py", line 228, in pprint_thing
    result = as_escaped_unicode(thing)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\printing.py", line 191, in as_escaped_unicode
    result = compat.text_type(thing)  # we should try this first
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\base.py", line 67, in __repr__
    return str(self)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\base.py", line 46, in __str__
    return self.__unicode__()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\series.py", line 984, in __unicode__
    max_rows=max_rows)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\series.py", line 1025, in to_string
    dtype=dtype, name=name, max_rows=max_rows)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\series.py", line 1053, in _get_repr
    result = formatter.to_string()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 225, in to_string
    fmt_values = self._get_formatted_values()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 215, in _get_formatted_values
    float_format=self.float_format, na_rep=self.na_rep)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 2007, in format_array
    return fmt_obj.get_result()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 2026, in get_result
    fmt_values = self._format_strings()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 2069, in _format_strings
    fmt_values.append(' %s' % _format(v))
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 2053, in _format
    return '%s' % formatter(x)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\format.py", line 2040, in <lambda>
    (lambda x: pprint_thing(x, escape_chars=('\t', '\r', '\n'))))
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\printing.py", line 228, in pprint_thing
    result = as_escaped_unicode(thing)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\formats\printing.py", line 191, in as_escaped_unicode
    result = compat.text_type(thing)  # we should try this first
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\base.py", line 67, in __repr__
    return str(self)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\base.py", line 46, in __str__
    return self.__unicode__()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\series.py", line 984, in __unicode__
    max_rows=max_rows)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-28 19:12
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2018-02-28 20:37
Some more information in #6225 but they never followed up.

As Carlos mentioned, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can.

**Comment by CAM-Gerlach** [comment] 2018-03-08 08:44
Closed due to lack of response.

**Closed by CAM-Gerlach** 2018-03-08 08:44 UTC
Labels: status:Awaiting Followup
