### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by PraveerNarwelkar** [spyder-ide/spyder#5856] opened 2017-11-30 05:28 UTC
## Description
I use a high end laptop, with a 8 GB RAM and yet I'm facing freezing issues. I tried Spyder from WinPython (v3.5 as well as v3.6) and Anaconda3 both. Running a 100 MB dataframe makes the memory full, and completely freezes up the laptop. 

Can someone please fix this issue? I really need this IDE for my course project due next week.

**What is the expected output? What do you see instead?**
It didn't have such a problem last month.

**Please provide any additional information below**
Right now I prefer using an IDE with pre-installed python libraries.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-11-30 06:11
Thanks for reporting. This is a duplicate of issue #5830.

Please read that issue for a workaround to avoid this problem until we solve it.

**Closed by ccordoba12** 2017-11-30 06:11 UTC
