### ISSUE TITLE
Number of matches in Find panel is wrong

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#6521] opened 2018-02-26 08:52 UTC
## Problem Description

The number of matches displayed in the Find panel underneath the editor is sometimes wrong.

### What steps will reproduce the problem?

1. Create a new file
2. Enter the text `xdoc.doc` in the file
3. Press Ctrl+F
4. Enter `.doc` in the search field

### What is the expected output? What do you see instead?

To the right of the search field, the text `2 of 2` appears, indicating 2 matches. However, there is only one match. It is not possible to go to match "1 of 2" using the "Find previous" and "Find next" buttons.

It may be that the search field is considered as a regular expression when counting the matches but not when traversing the matches.

## Package Versions

Spyder 4.0.0.dev0 (Commit: 5e38070ac), Python 3.6.4 64bits, Qt 5.6.2, PyQt5 5.6 on Linux

**Comment by ccordoba12** [comment] 2018-02-26 17:47
If you're using regular expressions (the default), then `xdoc` is a match for `.doc`.

Should we disable regexps by default?

**Comment by jitseniesen** [comment] 2018-02-26 18:04
I'm not sure whether regexp is turned on or off, it's not clear to me from the UI. But I expect the number of matches to be counted to be the same as the number of matches that you can go to with the "Find previous" and "Find next" buttons.

This may actually be a duplicate of #5680 and fixed by the proposed PR #6526 .

**Comment by ccordoba12** [comment] 2018-02-27 00:21
Ok, great! Closing this one as a duplicate of #5680 then.

**Closed by ccordoba12** 2018-02-27 00:21 UTC
Labels: component:Find and Replace, type:Bug
