### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by rahulbhatkar690** [spyder-ide/spyder#15566] opened 2021-05-09 20:26 UTC
### What steps will reproduce the problem?

1. Spyder downloaded and installed
2. When opened for the first time, "An error ocurred while starting the kernel"
3. The error is:

Traceback (most recent call last):
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\traitlets\traitlets.py", line 535, in get
value = obj._trait_values[self.name]
KeyError: 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 1498, in create_kernel_manager_and_kernel_client
env=kernel_spec.env)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
self.post_start_kernel(**kw)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 60, in post_start_kernel
super().post_start_kernel(**kw)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 323, in post_start_kernel
self._connect_control_socket()
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 255, in _connect_control_socket
self._control_socket = self._create_connected_socket('control')
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\jupyter_client\connect.py", line 548, in _create_connected_socket
sock = self.context.socket(socket_type)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\traitlets\traitlets.py", line 575, in __get__
return self.get(obj, cls)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\traitlets\traitlets.py", line 538, in get
default = obj.trait_defaults(self.name)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\traitlets\traitlets.py", line 1578, in trait_defaults
return self._get_trait_default_generator(names[0])(self)
File "C:\Users\rahul\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 64, in _context_default
return zmq.Context()
File "zmq\backend\cython\context.pyx", line 48, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: timed out

4. Spyder was uninstalled and reinstalled couple of times, but returns the same error everytime.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\code.py", line 90, in runcode
  File "<console>", line 2, in <module>
NameError: name 'obj' is not defined
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment] 2021-05-09 20:36
Closing as a duplicate of issue #15495, which was opened by you and reports the same error.

Please don't open more issues about the same thing. Instead, please follow the conversation on issue #15495.

**Closed by ccordoba12** 2021-05-09 20:36 UTC
