### ISSUE TITLE
there's something wrong with my spyder

### ISSUE THREAD

**Issue by kuranatsu** [spyder-ide/spyder#6307] opened 2018-01-27 02:58 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\Users\ASUS\Anaconda2\envs\Python36\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\Us

**Comment by CAM-Gerlach** [comment] 2018-01-28 08:02
Thanks for reporting. The error traceback that was posted is incomplete. However, it is likely a duplicate of e.g. #5673 , an error that's been reported numerous times now. As the full error message likely states, Jedi is only compatible with `parso` 0.1.0, not 0.1.1. Therefore, you can update `jedi` to the latest version with `conda update jedi` (or with `pip`, if you use that instead); (you can also downgrade to `parso` 0.1.0 with e.g. `conda install parso=0.1.0` ) and so this issue will be closed.

**Closed by CAM-Gerlach** 2018-01-28 08:02 UTC
