### ISSUE TITLE
Spyder does not autocomplete user-made functions across different files when not imported.

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#10922] opened 2019-12-03 23:24 UTC
I will write a function in one file, run it so it is in my environment, and then switch tabs to another file and try to run the same function. I am not importing this new function, so I can see why the autocomplete does not recognize it. But it would be a nice feature to have!

**Comment by bcolsen** [comment] 2019-12-05 00:25
The current default in Spyder 4 is run python scripts in a new clean namespace to prevent difficult to detect bugs.

With that in mind this likely would only be fixed when we get fallback completions from IPython. 
So I am going to close this as a duplicate of #2162

**Closed by bcolsen** 2019-12-05 00:25 UTC
