### ISSUE TITLE
spyder3.2.4

### ISSUE THREAD

**Issue by fwujia** [spyder-ide/spyder#5670] opened 2017-11-06 07:57 UTC
## Description

**What steps will reproduce the problem?**

1. open software
2. click menu item tool->preferences

**What is the expected output? What do you see instead?**

the settting of preferences item , err show up

**Please provide any additional information below**

  File "c:\python35\lib\site-packages\spyder\app\mainwindow.py", line 2610, in edit_preferences
    dlg.add_page(widget)
  File "c:\python35\lib\site-packages\spyder\plugins\configdialog.py", line 234, in add_page
    widget.apply_button_enabled.connect(self.apply_btn.setEnabled)
AttributeError: 'NoneType' object has no attribute 'setEnabled'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by fwujia** [comment] 2017-11-06 07:58
Think you!

**Comment by ccordoba12** [comment] 2017-11-06 14:42
Thanks for reporting. This is a duplicate of issue #5649.

**Closed by ccordoba12** 2017-11-06 14:42 UTC
