### ISSUE TITLE
Automatically restart the PyLS if it fails

### ISSUE THREAD

**Issue by UniqASL** [spyder-ide/spyder#11897] opened 2020-03-20 15:12 UTC
### What steps will reproduce the problem?

I'm running Spyder 4.1.1 and after some random time (few minutes to more than an hour) I get the following Error message:

"Completion and linting in the editor for Python files will not work during the current session, or stopped working.

To fix this, please verify that your firewall or antivirus allows python processes to open ports in your system, or restart Spyder."

I close the Error message, but I soon as I start typing again it pops-up again, so I have to restart Spyder.

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-20 15:27
Duplicate of #11026

**Comment by ccordoba12** [comment] 2020-03-20 15:27
There's nothing we can do about it for now, but we'll try to fix it in a future release.

**Closed by ccordoba12** 2020-03-20 15:27 UTC
Labels: component:Code Completion, type:Bug

**Comment by ccordoba12** [comment] 2020-03-20 15:29
> I close the Error message, but I soon as I start typing again it pops-up again, so I have to restart Spyder.

We decided to do this so people is forced to do the restart and not to report with us that code completion and linting are failing.
