### ISSUE TITLE
Editor: implement rectangular block selection

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#569] opened 2015-02-16 23:57 UTC
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-02T15:41:52Z_

In spyderlib/codeeditor/base.py (or codeeditor.py), implement the rectangular block selection as described here: http://en.wikipedia.org/wiki/File:Kwrite_block_selection.png

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=569_

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:57
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-03-02T16:04:03Z_

Yes, this is an awesome feature to have!  I always switch back to notepad++ when I need it.

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:57
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:28:37Z_

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:57
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-02T02:39:21Z_

issue #719 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:57
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:10:54Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment] 2015-02-16 23:57
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-27T07:02:53Z_

issue #1282 has been merged into this issue.

**Comment by hellter** [comment] 2016-08-17 19:11
Is there a chance that this feature will be added in the next releases of Spyder?

**Comment by ccordoba12** [comment] 2016-08-17 20:55
Maybe, we'll see :-)

**Comment by ccordoba12** [comment] 2016-12-08 00:22
This is a duplicate of issue #2112.

**Closed by ccordoba12** 2016-12-08 00:22 UTC
Labels: 6–10 stars, Comp-Editor, Type-Enhancement
