### ISSUE TITLE
test_mainwindow.py opens too many file descriptors and sockets

### ISSUE THREAD

**Issue by bnavigator** [spyder-ide/spyder#12328] opened 2020-04-14 20:48 UTC
Hi,

First, I want to clarify that I am fully aware of the fact, that you do not support running unit tests outside of your own development environments and CIs. However, because I think this might be related to what happens in #12247, I am reporting anyway. Please, don't feel obliged to dig too much into it if you feel this does not apply to the scenarios you are officially supporting.

In my endeavor to stabilize Spyder for the OpenSUSE Linux distro package which I am maintaining, I try to run as many unit tests as possible in order to detect possible package incompatibilites.

Fact is, the execution of `python3 runtests.py --run-slow` always fails with a segfault or breakpoint trap. This happens not always at the same test but consistently a few dozen tests into the test_mainwindow.py suite. *Sometimes* there is a `Too many open files` error message associated with it.

I added a few debug statements to the `main_window` fixture and found out that for each test, the number of open files and sockets increases. Specifically the `pdb_history.sqlite` file is opened many times but not closed at teardown of the test. I suspect this is because of the reuse of the window as introduced in #10444. This could also be the reason why #12247 cannot open any new connections.

I will dig more into this, but any hints would be appreciated.

**Comment by ccordoba12** [comment] 2020-04-14 22:39
> Specifically the pdb_history.sqlite file is opened many times but not closed at teardown of the test

Interesting. @impact27, could you take a look at this one?

**Comment by impact27** [comment] 2020-04-15 05:12
I can confirm there is a leak:
 - `pdb_history.sqlite` is a file open on the frontend, not the kernel, so I am not sure it is related.

In the internal console after closing the ipyconsole 100 times:
```
import psutil
proc = psutil.Process()
len(proc.open_files())
```
shows that `pdb_history.sqlite` is open 100 times

**Comment by impact27** [comment] 2020-04-15 05:38
I fixed it in #12134 because I was already separating the pdb_history work there.

**Comment by bnavigator** [comment] 2020-04-15 12:40
Thanks for looking into this!

I will check if I can apply the whole PR to the 4.1.2 package or whether just the last two commits are enough.

**Comment by impact27** [comment] 2020-04-15 15:05
If you need to fix that now:
In `spyder/plugins/ipythonconsole/widgets/client.py` find `def shutdown(self):`
Under
```
self.shellwidget._pdb_history_file.save_thread.stop() 
```
Add
```
self.shellwidget._pdb_history_file.db.close()
```

**Comment by ccordoba12** [comment] 2020-04-15 18:26
> If you need to fix that now:

@impact27, I think this is important enough to have it in 4.1.3 (our next release). Could you make a PR for that?

**Comment by impact27** [comment] 2020-04-15 20:22
Done in  #12340

**Closed** 2020-05-21 20:56 UTC
Labels: type:Task
