### ISSUE TITLE
Mayavi 4.5.0 mlab.show does not work in Spyder 3.1.0

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4212] opened 2017-02-28 16:35 UTC
## Description
Hi, I am using Python 2.X on Ubuntu 16.04 LTS with Spyder 3.1.0.  What I am finding is that when I use Mayavi.mlab.show(), the console hangs.  I tried it on IPython Console as well, which gives the following error: 
Changing backend to Qt for Mayavi
Kernel died, restarting
**What steps will reproduce the problem?**
1. Please try the example shown in the following website:
http://docs.enthought.com/mayavi/mayavi/mlab.html#d-plotting-functions-for-numpy-arrays
2. 
3. 

**What is the expected output? What do you see instead?**
The expected output is a 3D mesh plot, but instead my console hangs.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.1.3 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by s0r2637** [comment] 2017-03-03 19:17
Any updates on this bug?  I badly need to run Mayavi for 3D point cloud visualization.  Could you please suggest any alternatives?

**Comment by ccordoba12** [comment] 2017-03-03 19:26
We'll take a look at it for 3.1.4, to be released in a couple of weeks.

**Comment by s0r2637** [comment] 2017-03-03 19:55
What do you think is the problem?  Can Spyder 3.1.3 work with earlier
Mayavi versions?

**Comment by ccordoba12** [comment] 2017-03-05 17:50
I can't reproduce your problem.

Before running your code, please run this in an IPython console

    %gui qt

and try again.

**Comment by ccordoba12** [comment] 2017-03-05 18:03
By the way, I used the conda packages for VTK and Mayavi, so maybe the problem is in the Ubuntu packages.

**Comment by s0r2637** [comment] 2017-03-05 18:05
I ran it in IPython console inside Spyder, and I got the following error:


"Changing back end to Qt for Mayavi

Kernel died, restarting."

What do you think might be going on?  Any help would be highly appreciated.

Srini


On Mar 5, 2017 12:50 PM, "Carlos Cordoba" <notifications@github.com> wrote:

I can't reproduce your problem.

Before running your code, please run this in an IPython console

%gui qt

and try again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spyder-ide/spyder/issues/4212#issuecomment-284246742>,
or mute the thread

**Comment by s0r2637** [comment] 2017-03-05 18:07
I used pip packages for Mayavi and VTK. could you try the packages through
pip?

Srini

On Mar 5, 2017 1:03 PM, "Carlos Cordoba" <notifications@github.com> wrote:

By the way, I used the conda packages for VTK and Mayavi, so maybe the
problem is in the Ubuntu packages.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spyder-ide/spyder/issues/4212#issuecomment-284247684>,
or mute the thread

**Comment by ccordoba12** [comment] 2017-03-05 18:12
VTK doesn't have pip packages.

**Comment by s0r2637** [comment] 2017-03-05 18:18
I installed VTK THROUGH either Gihub development branch or Ubuntu apt-get
packages.  I don't quite remember which one.  What do you think might be
the problem going on?  Btw, I installed ipython separately through pip and
ran the same set of commands.  I got the following error.  Any idea what
could be going wrong?

*In [1]: % gui qt*

*In [2]: from numpy import pi, sin, cos, mgrid*
*   ...: dphi, dtheta = pi/250.0, pi/250.0*
*   ...: [phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]*
*   ...: m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;*
*   ...: r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 +
cos(m6*theta*
*   ...: )**m7*
*   ...: x = r*sin(phi)*cos(theta)*
*   ...: y = r*cos(phi)*
*   ...: z = r*sin(phi)*sin(theta)*
*   ...: *

*In [3]: from mayavi import mlab*
*   ...: s = mlab.mesh(x, y, z)*
*   ...: mlab.show()*
*   ...: *
*---------------------------------------------------------------------------*
*ValueError                                Traceback (most recent call
last)*
*<ipython-input-3-d13af8b5e18a> in <module>()*
*----> 1 from mayavi import mlab*
*      2 s = mlab.mesh(x, y, z)*
*      3 mlab.show()*

*/usr/local/lib/python2.7/dist-packages/mayavi/mlab.py in <module>()*
*     25 *
*     26 # Mayavi imports*
*---> 27 from mayavi.tools.camera import view, roll, yaw, pitch, move*
*     28 from mayavi.tools.figure import figure, clf, gcf, savefig, \*
*     29     draw, sync_camera, close, screenshot*

*/usr/local/lib/python2.7/dist-packages/mayavi/tools/camera.py in
<module>()*
*     23 # We can't use gcf, as it creates a circular import in camera
management*
*     24 # routines.*
*---> 25 from .engine_manager import get_engine*
*     26 *
*     27 *

*/usr/local/lib/python2.7/dist-packages/mayavi/tools/engine_manager.py in
<module>()*
*     10 *
*     11 # Local imports*
*---> 12 from mayavi.preferences.api import preference_manager*
*     13 from mayavi.core.registry import registry*
*     14 from mayavi.core.engine import Engine*

*/usr/local/lib/python2.7/dist-packages/mayavi/preferences/api.py in
<module>()*
*      2 *
*      3 # The global PreferenceManager instance*
*----> 4 from .preference_manager import preference_manager*
*      5 from .bindings import set_scene_preferences, get_scene_preferences*

*/usr/local/lib/python2.7/dist-packages/mayavi/preferences/preference_manager.py
in <module>()*
*     27 from traits.etsconfig.api import ETSConfig*
*     28 from traits.api import HasTraits, Instance*
*---> 29 from traitsui.api import View, Group, Item*
*     30 from apptools.preferences.api import (ScopedPreferences,
IPreferences,*
*     31         PreferencesHelper)*

*/usr/local/lib/python2.7/dist-packages/traitsui/api.py in <module>()*
*     34 *
*     35 try:*
*---> 36     from .editors.api import ArrayEditor*
*     37 except ImportError:*
*     38     # ArrayEditor depends on numpy, so ignore if numpy is not
present.*

*/usr/local/lib/python2.7/dist-packages/traitsui/editors/__init__.py in
<module>()*
*     21 *
*     22 try:*
*---> 23     from .api import ArrayEditor*
*     24 except ImportError:*
*     25     pass*

*/usr/local/lib/python2.7/dist-packages/traitsui/editors/api.py in
<module>()*
*     22 from .button_editor import ButtonEditor*
*     23 from .check_list_editor import CheckListEditor*
*---> 24 from .code_editor import CodeEditor*
*     25 from .color_editor import ColorEditor*
*     26 from .compound_editor import CompoundEditor*

*/usr/local/lib/python2.7/dist-packages/traitsui/editors/code_editor.py in
<module>()*
*     34
#-------------------------------------------------------------------------------*
*     35 *
*---> 36 class ToolkitEditorFactory ( EditorFactory ):*
*     37     """ Editor factory for code editors.*
*     38     """*

*/usr/local/lib/python2.7/dist-packages/traitsui/editors/code_editor.py in
ToolkitEditorFactory()*
*     46 *
*     47     # Background color for marking lines*
*---> 48     mark_color = Color( 0xECE9D8 )*
*     49 *
*     50     # Object trait containing the currently selected line
(optional)*

*/usr/local/lib/python2.7/dist-packages/traits/traits.pyc in __call__(self,
*args, **metadata)*
*    520 *
*    521     def __call__ ( self, *args, **metadata ):*
*--> 522         return self.maker_function( *args, **metadata )*
*    523 *
*    524 class TraitImportError ( TraitFactory ):*

*/usr/local/lib/python2.7/dist-packages/traits/traits.pyc in Color(*args,
**metadata)*
*   1234     from traitsui.toolkit_traits import ColorTrait*
*   1235 *
*-> 1236     return ColorTrait( *args, **metadata )*
*   1237 *
*   1238 Color = TraitFactory( Color )*

*/usr/local/lib/python2.7/dist-packages/traitsui/toolkit_traits.pyc in
ColorTrait(*args, **traits)*
*      5 *
*      6 def ColorTrait ( *args, **traits ):*
*----> 7     return toolkit().color_trait( *args, **traits )*
*      8 *
*      9 def RGBColorTrait ( *args, **traits ):*

*/usr/local/lib/python2.7/dist-packages/traitsui/toolkit.pyc in
toolkit(*toolkits)*
*    159             try:*
*    160                 with provisional_toolkit(toolkit_name):*
*--> 161                     _toolkit = _import_toolkit(toolkit_name)*
*    162                     return _toolkit*
*    163             except (AttributeError, ImportError) as exc:*

*/usr/local/lib/python2.7/dist-packages/traitsui/toolkit.pyc in
_import_toolkit(name)*
*     81 *
*     82 def _import_toolkit ( name ):*
*---> 83     return __import__( name, globals=globals(), level=1 ).toolkit*
*     84 *
*     85 *

*/usr/local/lib/python2.7/dist-packages/traitsui/qt4/__init__.py in
<module>()*
*     16 # import pyface.qt before anything else is done so the sipapi*
*     17 # can be set correctly if needed*
*---> 18 import pyface.qt*
*     19 *
*     20
#----------------------------------------------------------------------------*

*/usr/local/lib/python2.7/dist-packages/pyface/qt/__init__.py in <module>()*
*     31     except ImportError:*
*     32         try:*
*---> 33             prepare_pyqt4()*
*     34             import PyQt4*
*     35             qt_api = 'pyqt'*

*/usr/local/lib/python2.7/dist-packages/pyface/qt/__init__.py in
prepare_pyqt4()*
*     15     # Set PySide compatible APIs.*
*     16     import sip*
*---> 17     sip.setapi('QDate', 2)*
*     18     sip.setapi('QDateTime', 2)*
*     19     sip.setapi('QString', 2)*

*ValueError: API 'QDate' has already been set to version 1*

**Comment by ccordoba12** [comment] 2017-03-05 18:39
I don't know, sorry. We set PyQt4 API to `#2` here:

https://github.com/spyder-ide/spyder/blob/master/spyder/utils/site/sitecustomize.py#L261

and yet you have an error about that.

----

I'm sorry, but since you're using a non-standard installation (using a mix of pip and system packages), it's up to you to figure this problem out.

My recommendation: simply install Anaconda/Miniconda and resume your work.

**Closed by ccordoba12** 2017-03-05 18:39 UTC
Labels: component:IPython Console, type:Bug

**Comment by s0r2637** [comment] 2017-03-06 21:21
Hi Carlos,

I installed Conda and ran the set of codes.  It worked fine. One thing is
that I had to use iPython to set %gui qt.  How do I do that in the normal
Python console with Spyder?  What can I do in Python console to get the
same effect as doing "%gui qt" in iPython console.?

Thanks,
Srini

**Comment by ccordoba12** [comment] 2017-03-06 22:05
You don't need to execute `%gui qt` in a Python console. Running your code without it should work fine.

But let me warn you that the Python console is going to be removed in Spyder 3.2, so please keep using the IPython console instead.

**Comment by s0r2637** [comment] 2017-03-07 00:04
It does not work in Python console.  It gives me the following error:

*RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'*

Where do I set the Qt API value?  Btw, what exactly does sitecustomize.py
do?  I never cared to know it until now.

Srini

**Comment by s0r2637** [comment] 2017-03-07 22:53
Hi Carlos,

I found out what the problem was.  It seems like Mayavi 4.5.0 is not
compatible with PyQt 5.x.  Conda automatically downgrades the PyQt from 5
to 4 when we install Mayavi 4.5.0.  That's why Mayavi runs on Conda
distribution.  Apparently, pip packages don't care about compatibility.
However, the downside is that now I can't install matplotlib 2.x without
PyQt being 5.x.  At least, this is the configuration enforced in Conda
environment.

Srini

**Comment by ccordoba12** [comment] 2017-03-08 00:00
> However, the downside is that now I can't install matplotlib 2.x without PyQt being 5.x

We're working to fix that in Continuum.
