### ISSUE TITLE
Holding Alt Gr lets me insert certain characters into already entered input lines in the iPython console

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#6976] opened 2018-04-17 13:37 UTC
## Problem Description

Certain symbols on my keyboard with german layout are entered using the Alt Gr-key: ²³{[]}\~€@|

Lets say I just type the command `s="abcdefg"` and press Enter.

I then see something like this:

```
In [1]: s="abcdefg"
In [2]:
```

I'm able to put the text cursor anywhere into the entered command e.g. to mark and copy it.

When I put the cursor into the middle of the string, press Alt Gr and any of the mapped special characters it turns out I can actually enter those characters, leading to e.g. this:

```
In [1]: s="abc\\\\\\defg"
In [2]:
```

Of course `s` is not altered by this, but I don't think it should be possible to change past input.

This odd behaviour is neither reproducible in iPython in Windows Terminal nor in Jupyterlab.

## Package Versions

* Spyder: 3.2.8
* Python: 3.6
* Qt: 5.6.2
* PyQt: 5.6
* Operating System: Windows 10

### Dependencies
```
IPython >=4.0    :  6.3.1 (OK)
cython >=0.21    :  0.28.1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2018-04-17 23:50
I can't reproduce this on Linux. As soon as I press `Alt Gr` the focus goes to the next `In [ ]` entry.

> Of course s is not altered by this, but I don't think it should be possible to change past input.

Right, it shouldn't. I'll try it on Windows to see if I can reproduce it there.

**Comment by CAM-Gerlach** [comment] 2018-04-18 00:45
> As soon as I press Alt Gr the focus goes to the next In [ ] entry. I'll try it on Windows to see if I can reproduce it there.

I had tried it on Windows and got the same result, but I assumed it was because I didn't have whatever i18n enabled that the OP had.

**Comment by goanpeca** [comment] 2019-11-27 23:28
I cannot reproduce this either. Closing

**Closed by goanpeca** 2019-11-27 23:28 UTC
Labels: component:IPython Console, type:Bug
