### ISSUE TITLE
Internal Problem

### ISSUE THREAD

**Issue by Okroshiashvili** [spyder-ide/spyder#8826] opened 2019-02-22 09:11 UTC
### What steps will reproduce the problem?

I opend spyder and after 5 minute I encountered this problem

### Traceback
```python-traceback
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 327, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 340, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.7
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-22 10:29
Duplicate of spyder-ide/spyder-terminal#123. Please uninstall `spyder-terminal` if you don't want to see this error in the future because right now we don't have the resources to fix it.

**Closed by ccordoba12** 2019-02-22 10:29 UTC

**Comment by Okroshiashvili** [comment] 2019-02-22 12:41
Thanks @ccordoba12
