### ISSUE TITLE
Improve Session manager like Kate (KDE)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1433] opened 2015-02-17 19:18 UTC
_From [haibison...@gmail.com](https://code.google.com/u/113711635639566759007/) on 2013-06-07T01:15:57Z_

Spyder Version:  2.2.0
Python Version:  2.7.3
Qt Version:      4.8.4, PyQt4 (API v1) 4.10.1 on Linux

If you use Kate, you can configure to choose a session at startup (screenshot `#1`), or you can switch between sessions while working (screenshot `#2`). A session in Kate stores all working files.

It would be great if you could improve Spyder's session module like the Kate's one. I have some suggestions too:

 - Let the user to be able to save session without exiting the app.

 - If a session has lots of files opened, then next time when you open that session, the UI can be hung for some seconds. So I suggest to just attach the file names to be opened to the tabs that display the file contents. If the tabs are not visible then they don't need to load the file content. When the user navigates to a tab, it loads the file content.

Thank you,
Hai

**Attachment:** [Screenshot from 2013-06-07 12:44:02.png Screenshot from 2013-06-07 12:46:37.png](http://code.google.com/p/spyderlib/issues/detail?id=1433)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1433_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [haibison...@gmail.com](https://code.google.com/u/113711635639566759007/) on 2013-06-06T23:21:27Z_

And add the option to let Spyder store session names in its own internal DB. (Beside current option is to let the user store session to an external file.)

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-07T07:34:09Z_

I'm +1 on multisession idea - Spyder has some support for that, but I am unlikely to visit that part anyoime soon.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-10T07:24:02Z_

**Labels:** MS-v2.4

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [mas...@scaryhits.com](https://code.google.com/u/112246939082556816811/) on 2014-01-27T10:30:10Z_

I am starting to work on it , please check : https://code.google.com/p/spyderlib/issues/detail?id=1704 Please input your ideas too.

Right now , i will start with Session Management UI and then Implement Stored states of interpreters using Dill.

Next will be attaching porjects with session , and toolbar for switching between projects and sessions.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [haibison...@gmail.com](https://code.google.com/u/113711635639566759007/) on 2014-01-30T04:07:18Z_

Thank you, it's great.

I'm just familiar with Kate's Session Manager. Attaching projects with sessions sounds cool to me too.

Also currently when I refactor my project tree, then Kate fails to load the session saved before. Then I have to close all files manually and open them again. It would be great if you could show the list of file paths saved and I can search & replace the paths -- it'll be easier.

For example, this is old session:

/data/projects/a/b/c/...
/data/projects/a/b/c/...
/data/projects/a/b/c/...

If I refactor folder "b" to "d", then the IDE will fail to load the session. I think the simple way is to show the list of paths to me, and I'll change the list myself.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:19
_From [haibison...@gmail.com](https://code.google.com/u/113711635639566759007/) on 2014-01-30T04:10:17Z_

Another note, if you attach projects with sessions, then using relative paths might be better than absolute paths.

Thanks again.

**Comment by ccordoba12** [comment] 2015-07-13 05:16
Closing as duplicate of issue #1704

**Closed by ccordoba12** 2015-07-13 05:16 UTC
Labels: duplicate
