### ISSUE TITLE
Crt + left clic

### ISSUE THREAD

**Issue by Mantxurreta** [spyder-ide/spyder#10469] opened 2019-10-20 09:19 UTC
### What steps will reproduce the problem?

Hold LHS Ctr and left clic in the editor. An issue report pops up.

### Traceback
```python-traceback
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1221, in handle_go_to_definition
    def_range = position['range']
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/aritz/virtualenvs/spyder_beta/bin/spyder3", line 10, in <module>
    sys.exit(main())
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/app/start.py", line 195, in main
    mainwindow.main()
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3646, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3529, in run_spyder
    app.exec_()
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/completion/languageserver/client.py", line 343, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 198, in process_go_to_definition
    {'params': result})
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 279, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/completion/plugin.py", line 138, in receive_response
    self.gather_and_send(request_responses)
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/completion/plugin.py", line 189, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 915, in handle_response
    handler(params)
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1238, in handle_go_to_definition
    "Error when processing go to definition")
  File "/home/aritz/virtualenvs/spyder_beta/lib/python3.6/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 946, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.6.8
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.1-050301-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.7.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by ccordoba12** [comment] 2019-10-20 17:43
Duplicate of #10439.

**Closed by ccordoba12** 2019-10-20 17:43 UTC
