### ISSUE TITLE
Profiler Sort Order

### ISSUE THREAD

**Issue by MarkCWirt** [spyder-ide/spyder#4308] opened 2017-03-30 13:35 UTC
## Description of your problem

About two years ago there was an [issue](https://github.com/spyder-ide/spyder/issues/2074) with the sort order in the profiler being lexical, as opposed to numeric. It appears that this has been reintroduced into spyder at some point.

**What steps will reproduce the problem?**

1. Profile a program
2. Sort on total time

**What is the expected output? What do you see instead?**

I would expect to see the sorting by numeric values, not lexical. For example, in the file I just profiled  92.47 ms is considered a longer time than 11.51 seconds

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7.12
* Qt Version: 5.6.0
* PyQt Version: 5.6
* Operating system: Linux

## Dependencies

* jedi :  0.9.0 
* matplotlib :  1.5.3 
* nbconvert :  4.2.0 
* numpy :  1.11.3 
* pandas :  0.19.0 
* pep8 :  1.7.0 
* psutil :  4.4.2 
* pyflakes :  1.3.0 
* pygments :  2.1.3 
* pylint :  1.5.4 
* qtconsole :  4.2.1 
* rope :  0.9.4 
* sphinx :  1.4.8 
* sympy :  1.0

**Comment by MarkCWirt** [comment] 2017-03-30 13:53
Sample output:

![sorter](https://cloud.githubusercontent.com/assets/1943356/24507522/a874f28c-152e-11e7-9768-9bdbd1d77f4d.jpg)

**Comment by markusr** [comment] 2017-03-30 14:24
Duplicate of #4039

**Closed** 2017-03-30 14:57 UTC
Labels: resolution:Duplicate
