### ISSUE TITLE
Anaconda 64-bit (Python 2.7) Spyder not working

### ISSUE THREAD

**Issue by DCaloya** [spyder-ide/spyder#6550] opened 2018-02-28 09:53 UTC
## Description

**What steps will reproduce the problem?**

I simply installed Anaconda 5.1, python 2.7 version, 64-bit and get the message below whenever I open Spyder.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "C:\Users\ga94giv\AppData\Local\Continuum\anaconda2\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\

**Comment by ccordoba12** [comment] 2018-02-28 19:14
This error was fixed in our 3.2.7 version. Please update.

**Closed by ccordoba12** 2018-02-28 19:14 UTC

**Comment by CAM-Gerlach** [comment] 2018-02-28 20:51
For reference, this is an apparent duplicate of #4958 (and its more recent reincarnation, #6319). You can update Spyder by running the command ``conda update spyder`` from the Anaconda Prompt.
