### ISSUE TITLE
Spyder Dark Theme 

### ISSUE THREAD

**Issue by Borthralla** [spyder-ide/spyder#6742] opened 2018-03-13 08:53 UTC
Went to preferences and picked spyder dark theme syntax coloring, got this error:
  File "D:\Anaconda\lib\site-packages\spyder\plugins\configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "D:\Anaconda\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "D:\Anaconda\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "D:\Anaconda\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "D:\Anaconda\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by ccordoba12** [comment] 2018-03-13 15:03
Thanks for reporting. This is a duplicate of issue #6519 and it'll be fixed in our next version.

**Closed by ccordoba12** 2018-03-13 15:03 UTC
