### ISSUE TITLE
Problem decoding source (Spyder 4.1.3)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12732] opened 2020-05-13 23:09 UTC
File has had the header as shown since creation, and always had the "UTF-8" encoding shown on bottom (as far as I can tell); haven't had this ever occur in 4.1.2 or 4.1.1.

<img src="https://user-images.githubusercontent.com/16495490/81874928-1e09a800-9590-11ea-8cd0-35b032afc66e.png" width="400">

<hr>

 - Unlike before, cut-pasting the entire file _does not_ make the mark disappear
 - Removing the header doesn't work either
 - Reopening the file does make it go away

**Comment by andfoy** [comment] 2020-05-14 15:32
Hi @OverLordGoldDragon, I think this is a duplicate of https://github.com/spyder-ide/spyder/issues/11154

**Closed** 2020-05-14 15:54 UTC
Labels: resolution:Duplicate
