### ISSUE TITLE
Problem, sending this by sugestion of spyder. Greetings

### ISSUE THREAD

**Issue by borcabar** [spyder-ide/spyder#6476] opened 2018-02-19 11:43 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "C:\Users\boris.cabrera.baran1\AppData\Local\Continuum\anaconda3\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\boris.cab

**Comment by ccordoba12** [comment] 2018-02-20 14:30
I think this is going to be fixed in our upcoming version (3.2.7), which is going to be released in one week. Please update to that version when ready and let us know if it fixes this problem for you.

**Comment by CAM-Gerlach** [comment] 2018-02-28 21:08
Closed due to lack of response, as this is an assumed duplicate of #6220 fixed in Spyder 3.2.7.

**Closed by CAM-Gerlach** 2018-02-28 21:08 UTC
Labels: status:Awaiting Followup
