### ISSUE TITLE
Started spyder after a reset of all settings

### ISSUE THREAD

**Issue by endolith** [spyder-ide/spyder#15765] opened 2021-06-02 15:14 UTC
### What steps will reproduce the problem?

`spyder --reset`

Then started spyder

I don't know what else to say

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jonathan\anaconda3\lib\logging\__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Jonathan\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\Jonathan\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\Jonathan\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Jonathan\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\Jonathan\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.0,)
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.10
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment] 2021-06-02 16:26
Hi @endolith thanks for the feedback! This error is already fixed in our latest version (5.0.3) however the release is still not available in Anaconda (the default channel). Taking into account this a couple of options you can check:

* Use our Windows installer, which you can find here: https://github.com/spyder-ide/spyder/releases

* Create a new environment with `conda-forge` packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

      conda create -n spyder-cf -c conda-forge spyder
      conda activate spyder-cf
      spyder

There is nothing much we can do, but let us know if something of the above helps :)

**Comment by endolith** [comment] 2021-06-03 01:50
Yeah the Windows installer seems easier for dealing with all the packaging issues, but seems more difficult to use it with different environments?  You have to change the settings each time? http://docs.spyder-ide.org/current/faq.html#using-existing-environment  https://gitter.im/spyder-ide/public?at=60a330a52ee2b13d95b5d3d8

**Comment by dalthviz** [comment] 2021-06-03 16:19
Yep that's one of the trade-offs that it has (if you want to use other packages not bundle with it). Regarding the interpreter setting, I think that it doesn't affect already running consoles unless you restart their kernel but for other elements probably you will need to change it, do you have some suggestion of how this could be improved @endolith ?

Also, we added a way to access the interpreter settings by clicking the status bar, maybe this could help a little bit:

![interpreter](https://user-images.githubusercontent.com/16781833/120678041-fede0100-c497-11eb-824d-65984b163d44.gif)


Pinging @ccordoba12 just in case to add more info regarding the current behavior and plans for the interpreter setting

**Comment by ccordoba12** [comment] 2021-06-03 17:22
> Pinging @ccordoba12 just in case to add more info regarding the current behavior and plans for the interpreter setting

There's work in progress to add a new menu to open consoles for each detected environment. Hopefully that will be available in the next couple of months.

**Comment by ccordoba12** [comment] 2021-06-03 17:32
I'm going to close this one as a duplicate of issue #15768. We're investigating why this problem happens and we'll try to fix it soon.

**Closed by ccordoba12** 2021-06-03 17:32 UTC
Labels: status:Awaiting Followup
