### ISSUE TITLE
Cannot change font size in the Editor on macOS (only decreasing font works)

### ISSUE THREAD

**Issue by MarKo9** [spyder-ide/spyder#4416] opened 2017-04-30 04:33 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. open spyder (through navigator in my case)
2. use the command + '+' or command + '=' shortcut

**What is the expected output? What do you see instead?**
expected:
in the case of  [command + '+'] : increase fond size
in the case of  [command + '='] : decrease size

actual:
in the case of  [command + '+'] : nothing happens
in the case of  [command + '='] : decrease size

**Please provide any additional information below**

## Versions and main components

* Spyder Version: Spyder 3.1.3 (tried to upgrade it to the 3.1.4 but did not work either)
* Python Version: 3.6 (same happens for 2.7)
* Qt Version: 5.6.2
* PyQt Version:PyQt5 5.6
* Operating system: Mac

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by goanpeca** [comment] 2019-11-25 19:13
This is actually an issue for a loong time, I thought it had to do with something I changed on my system, but setting another shortcut does work, so looking into this.

**Comment by goanpeca** [comment] 2019-11-25 19:16
<img width="728" alt="Screen Shot 2019-11-25 at 14 16 35" src="https://user-images.githubusercontent.com/3627835/69570657-38be7500-0f8e-11ea-813f-2a4fdc9760a3.png">

Zoom in 1
Zoom in 2 

@ccordoba12 ?

**Comment by ccordoba12** [comment] 2019-11-25 19:27
Yeah, closing.

**Comment by goanpeca** [comment] 2019-11-25 19:28
This is still an issue :-|

**Comment by goanpeca** [comment] 2019-11-25 21:21
My question was more why we have

```
              'editor/zoom in 1': "Ctrl++",
              'editor/zoom in 2': "Ctrl+=",
...
              'editor/close file 1': "Ctrl+W",
              'editor/close file 2': "Ctrl+F4",
```

**Comment by jnsebgosselin** [comment] 2019-11-26 15:26
On my keyboard, `Ctrl++` and `Ctrl+=` are actually on the same key. To reach `Ctrl++`  I need to actually do `Ctrl+Shift++`, while `-` can be accessed directly with `Ctrl+-` and `=` with `Ctrl+=`.

![image](https://user-images.githubusercontent.com/10170372/69647214-159bd000-1037-11ea-99e9-debd368864fb.png)

So maybe the second keybind for zoom in was added to make the keybinds between zoom in and zoom out more uniform UX wise?

**Comment by goanpeca** [comment] 2019-11-26 15:29
Maybe, but o my mac `Commad+=` which is the normal zoom command on every program is busted and I am not sure why...

**Comment by jnsebgosselin** [comment] 2019-11-26 15:31
> 
> 
> Maybe, but o my mac `Commad+=` which is the normal zoom command on every program is busted and I am not sure why...

`Commad+=` is supposed to make the text increase or decrease?

**Comment by goanpeca** [comment] 2019-11-26 15:34
>Command+= is supposed to make the text increase or decrease?

Zoom in (so increase)

But all my apps (including browsers) dont work, I have no idea what the issue is... 🤷‍♂

**Comment by jnsebgosselin** [comment] 2019-11-26 15:43
Ok I understand. 

I think I can help with that one. I'll try to take a look at it after the french translation is done.

**Comment by goanpeca** [comment] 2019-11-30 03:15
Update on this issue. It works if I press `Cmd+=` and then release the `Cmd` button while holding the `=`. If I do it like this it works.

**Closed by goanpeca** 2019-11-30 03:15 UTC
Labels: OS:MacOS, component:Editor, type:Bug

**Comment by gehergyuri** [comment] 2021-03-22 11:11
I also found a solution for this rather frustrating problem - it took me a while. I'm sharing this, because for some reason goanpeca's solution doesn't work on my mac. 
When you are in IDLE, press "cmd" + "," (or alternativel, click on IDLE next to the apple icon, then Preferences..). A window will pop up where you can change the font size and more.
