### ISSUE TITLE
Opening Masked Array

### ISSUE THREAD

**Issue by matte980** [spyder-ide/spyder#19932] opened 2022-10-26 13:12 UTC
### What steps will reproduce the problem?

Opening a "Masked Array" in the Variable explorer triggers this error

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/matteomonzali/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/variableexplorer/widgets/collectionsdelegate.py", line 181, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/Users/matteomonzali/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/variableexplorer/widgets/arrayeditor.py", line 773, in setup_and_check
    btn_layout_top.addWidget(self.shape_label)
AttributeError: 'ArrayEditor' object has no attribute 'shape_label'
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.12 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 21.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment] 2022-10-26 15:46
Hi @matte980 thank you for the feedback! I think this is a duplicate of https://github.com/spyder-ide/spyder/issues/16796

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2022-12-20 19:36
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/16796

**Closed by dalthviz** 2022-12-20 19:36 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
