### ISSUE TITLE
Icons are very small on a laptop

### ISSUE THREAD

**Issue by ahbushnell** [spyder-ide/spyder#2667] opened 2015-09-05 17:27 UTC
## Description
On a laptop with very high resolution screen in windows 10 the icons are very small in the development system.  the text font size is ok.  Also the launcher is all screwed up.  it's very small and I can't read anything.  I can just see where the launch icon for spyder is so I can start the GUI.

Thanks

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  2.4.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.4.3 (OK)

```

**Comment by ccordoba12** [comment] 2015-09-05 19:34
This is a duplicate of issue #2210, and it's already fixed in Spyder 3.0 beta1.

The final version of Spyder 3 will be released at the end of the year :-)

**Closed by ccordoba12** 2015-09-05 19:34 UTC
Labels: duplicate
