### ISSUE TITLE
Sypder update problem

### ISSUE THREAD

**Issue by aryankhatana01** [spyder-ide/spyder#11570] opened 2020-02-16 02:56 UTC
I updated my anaconda but it downgraded my Spyder version from 4.0.1 to 3.3.6. Now I am trying to update just Spyder by conda update spyder, it says that #All required packages installed but is still on spyder 3

**Comment by ccordoba12** [comment] 2020-02-16 04:49
Duplicate of #11550

**Closed by ccordoba12** 2020-02-16 04:49 UTC

**Comment by aryankhatana01** [comment] 2020-02-16 05:19
Hello, I had a look at the issue #11550 but couldn't find the solution...how do I fix it??

**Comment by dalthviz** [comment] 2020-02-16 13:53
@aryankhatana01 try running `conda install spyder=4.0.1` as https://github.com/spyder-ide/spyder/issues/11550#issuecomment-586645800 suggests. If you need more info or you want to give some feedback regarding this, please add a comment in #11550
