### ISSUE TITLE
i am not able to update the current version of spyder with newer version

### ISSUE THREAD

**Issue by shivamy241** [spyder-ide/spyder#9692] opened 2019-06-26 18:18 UTC
### What steps will reproduce the problem?

Solving environment: failed UnsatisfiableError: The following specifications were found to be incompatible with each other: - anaconda==2019.03=py37_0 -> importlib_metadata==0.8=py37_0 -> zipp[version='>=0.3.2'] - anaconda==2019.03=py37_0 -> mkl-service==1.1.2=py37hb782905_5 - anaconda==2019.03=py37_0 -> spyder==3.3.3=py37_0 -> spyder-kernels[version='>=0.4.2,<1'] - pkgs/main/win-64::importlib_metadata==0.8=py37_0 -> zipp[version='>=0.3.2'] - pkgs/main/win-64::mkl-service==1.1.2=py37hb782905_5 - pkgs/main/win-64::path.py==11.5.0=py37_0 -> importlib_metadata[version='>=0.5'] - pkgs/main/win-64::zipp==0.3.3=py37_1 - spyder-kernels - spyder=3.3.4 -> spyder-kernels[version='>=0.4.3,<1']

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-26 18:44
What conda command are you running to do the update?

**Comment by turnipski** [comment] 2019-06-27 09:28
I'm getting exact same issue with `conda 4.7.5`

```
(base) PS C:\Users\david> conda update qt pyqt
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) PS C:\Users\david> conda install -c spyder-ide spyder=4.0.0b2
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - anaconda==2019.03=py37_0 -> importlib_metadata==0.8=py37_0 -> zipp[version='>=0.3.2']
  - anaconda==2019.03=py37_0 -> spyder==3.3.3=py37_0 -> spyder-kernels[version='>=0.4.2,<1']
  - importlib_metadata
  - pkgs/main/win-64::path.py==11.5.0=py37_0 -> importlib_metadata[version='>=0.5']
  - spyder-kernels
  - spyder=4.0.0b2 -> spyder-kernels[version='>=1.2,<1.4']
  - zipp
```
However, I get the same issue trying to install spyder 3.3.4, so I suppose that suggests an issue with the version of Anaconda?

```
(base) PS C:\Users\david> conda install spyder=3.3.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - anaconda==2019.03=py37_0 -> importlib_metadata==0.8=py37_0 -> zipp[version='>=0.3.2']
  - anaconda==2019.03=py37_0 -> spyder==3.3.3=py37_0 -> spyder-kernels[version='>=0.4.2,<1']
  - pkgs/main/win-64::importlib_metadata==0.8=py37_0 -> zipp[version='>=0.3.2']
  - pkgs/main/win-64::path.py==11.5.0=py37_0 -> importlib_metadata[version='>=0.5']
  - pkgs/main/win-64::zipp==0.3.3=py37_1
  - spyder-kernels
  - spyder=3.3.4 -> spyder-kernels[version='>=0.4.3,<1']
```

**Comment by ccordoba12** [comment] 2019-06-27 10:02
@turnipski, what's your current Spyder version?

**Comment by turnipski** [comment] 2019-06-27 10:05
I've not got any version of Spyder installed, I've only just installed Anaconda today.

I tried installing Anaconda3-2018.12-Windows-x86_64 (previous was Anaconda3-2019.03-Windows-x86_64) and I get a slightly different issue:

```
(base) C:\Users\david>conda install -c spyder-ide spyder=4.0.0b2
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - anaconda==2018.12=py37_0 -> importlib_metadata==0.6=py37_0
  - anaconda==2018.12=py37_0 -> qtawesome==0.5.3=py37_0
  - anaconda==2018.12=py37_0 -> spyder==3.3.2=py37_0 -> spyder-kernels[version='>=0.1,<1']
  - importlib_metadata
  - pkgs/main/win-64::path.py==11.5.0=py37_0 -> importlib_metadata[version='>=0.5']
  - qtawesome
  - spyder-kernels
  - spyder=4.0.0b2 -> qtawesome[version='>=0.5.7']
  - spyder=4.0.0b2 -> spyder-kernels[version='>=1.2,<1.4']
```

**Comment by turnipski** [comment] 2019-06-27 10:07
Oh, I didn't realise that Anaconda came with Spyder 3.3.2 pre-installed, perhaps that is the issue? Trying to run install command when should be running update?

**Comment by ccordoba12** [comment] 2019-06-27 11:30
Please uninstall spyder and spyder-kernels and try again.

**Comment by ccordoba12** [comment] 2019-07-05 09:52
Closing as a duplicate of #9705.

**Closed by ccordoba12** 2019-07-05 09:52 UTC
Labels: status:Awaiting Followup
