### ISSUE TITLE
Another KeyError on autosave

### ISSUE THREAD

**Issue by mereshow** [spyder-ide/spyder#10997] opened 2019-12-10 10:02 UTC
### What steps will reproduce the problem?

I saw no problem, but Issue reporter indicates one.
I tried to save a file, cancelled the process and issue reporter appeared.

### Traceback
```python-traceback
  File "/home/alberto/Develop/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "/home/alberto/Develop/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "/home/alberto/Develop/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: '/home/alberto/untitled1.py'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-24-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by goanpeca** [comment] 2019-12-10 12:50
@jitseniesen any thoughts?

**Comment by ccordoba12** [comment] 2019-12-10 13:38
I think we should pass on that KeyError.

**Comment by jitseniesen** [comment] 2019-12-10 14:28
I tried to reproduce this. I pressed Ctrl-N to create a new file called untitled0.py, then pressed Ctrl-S to save it, and then the Cancel button. The save is cancelled, but I get an error saying "untitled0.py is unavailable (this file may have been removed, moved or renamed outside Spyder). Do you want to close it?" If an autosave is triggered while the error dialog is open, then the exception reported occurs.

The traceback is the same as in #10038, so my guess is that I made a mistake in fixing that issue.

**Comment by jitseniesen** [comment] 2019-12-13 15:37
The newly created issue #11058 is a duplicate of this. I don't know which issue to close as a duplicate because the new issue is already refered to in a PR.

**Comment by ccordoba12** [comment] 2019-12-13 17:56
Let's close this one as a duplicate of #11058.

**Closed by ccordoba12** 2019-12-13 17:56 UTC
Labels: component:Editor, type:Bug
