### ISSUE TITLE
[WinError 1005] The volume does not contain a recognized file system (Cryptomator related)

### ISSUE THREAD

**Issue by hoanthanhnguyen** [spyder-ide/spyder#21625] opened 2023-12-18 04:17 UTC
### What steps will reproduce the problem?

Spyder cannot save any python file that is located in a Cryptomator driver. Edit the file using other editor like notepad++ work well.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\utils\encoding.py", line 236, in write
    absolute_path_filename = pathlib.Path(filename).resolve()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 710, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1960, in <lambda>
    lambda: self._save_file(finfo))
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1986, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1886, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\utils\encoding.py", line 242, in write
    absolute_filename = osp.realpath(filename)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 710, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'
Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\utils\encoding.py", line 236, in write
    absolute_path_filename = pathlib.Path(filename).resolve()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 710, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1960, in <lambda>
    lambda: self._save_file(finfo))
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1986, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1886, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\utils\encoding.py", line 242, in write
    absolute_filename = osp.realpath(filename)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 710, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'
Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\utils\encoding.py", line 236, in write
    absolute_path_filename = pathlib.Path(filename).resolve()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 710, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1960, in <lambda>
    lambda: self._save_file(finfo))
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1986, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1886, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\210235\AppData\Local\miniconda3\envs\geo\Lib\site-packages\spyder\utils\encoding.py", line 242, in write
    absolute_filename = osp.realpath(filename)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 710, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'X:\\python\\delft3d\\grid.py'
```

## Versions

* Spyder version: 5.5.0  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.20.0 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.12.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.5 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.3 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.2.1 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.0 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.2 (OK)
numpy >=1.7                      :  1.26.2 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2023-12-18 14:36
Hey @hoanthanhnguyen, thanks for reporting. This is basically a duplicate of issue #16752, so I'm going to close it in favor of that one.

And just so you know, we don't have the resources to address this at the moment, sorry.

**Closed by ccordoba12** 2023-12-18 14:36 UTC
