### ISSUE TITLE
error1

### ISSUE THREAD

**Issue by TakahashiJumpei** [spyder-ide/spyder#6026] opened 2017-12-20 19:16 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\editor.py", line 1709, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "C:\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\WinPython-64bit-3.5.4.0Qt5\\settings\\.spyder-py3\\template.py'

## Version and main components

* Spyder Version: 3.2.1.dev0 
* Python Version: 3.5.4
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-21 00:09
Thanks for reporting. It seems your new file template was moved, deleted, renamed, or otherwise made inaccessible to Spyder. This is an apparent duplicate of #5717 ; see my and ccordoba's comments there, and therefore this one will be closed. In summary, possibly either a mangled install (thus do a clean uninstall and reinstall the latest version of Anaconda), or something to do with your antivirus or other security software messing with the file.

Additionally, you are using an older development version, and with WinPython, rather than the latest version of Anaconda, which can cause problems as well and isn't officially supported. Therefore, you can also try installing Anaconda, which is usually the best option for non-experts.

**Closed by CAM-Gerlach** 2017-12-21 00:09 UTC
