### ISSUE TITLE
Spyder 3.2.0 crashes when Opening or Saving file

### ISSUE THREAD

**Issue by KMac0615** [spyder-ide/spyder#4896] opened 2017-08-04 19:25 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Trying to open a file using File+Open or Ctrl+O
2. Trying to save a file using File+Save.
3. 

**What is the expected output? What do you see instead?**
I would expect to be able open or save a file.  Instead, a window pops up saying "Python has stopped working.  A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

**Please provide any additional information below**
I have tried uninstalling and reinstalling Anaconda twice.  Per other posts, I have uninstalled Dell Backup and Recovery, which didn't work.  I have made sure that all of the below packages are up to date.  As of right now, the only way to open a file is to use the File explorer tab in Spyder and the only way to save is to use Ctrl+S.

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 8.1 (64-bit)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-08-05 03:35
Thanks for reporting. This is a duplicate of issue #3903.

Unfortunately I don't think we can do anything on the Spyder side to fix this. Too bad that uninstalling Dell Backup and Recovery didn't work for you.

You can check if you have other Qt5 libraries installed in your system, because that could interfere with Spyder and cause this error too.

**Closed by ccordoba12** 2017-08-05 03:35 UTC
Labels: resolution:Duplicate

**Comment by zhangjingying8** [comment] 2017-10-28 16:48
I face the exact same problem. How to check whether or not I have other Qt5 libraries installed?
