### ISSUE TITLE
Hidden folders not shown in Files pane

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#11019] opened 2019-12-11 08:12 UTC
**Steps to reproduce:**
* Configure the file explorer to show all files (Tools -> Preferences -> Files -> General -> tick "Show all files").
* Create some folder with hidden files (windows-style hidden, rather than names starting with `.`).
* Browse that folder in the `Files` pane.

**Expected behavior:** should show hidden files and folders.

**Actual behavior:** hidden folders are not shown.

**Setup:** Spyder 4.0.0, running on windows 10.

**Comment by MuellerSeb** [comment] 2019-12-11 10:16
Related: #10883

**Comment by david-cortes** [comment] 2019-12-11 11:01
Not sure if it's related, those files like `.gitignore` show up when I browse the folders.

**Comment by ccordoba12** [comment] 2019-12-11 14:42
> Create some folder with hidden files (windows-style hidden

I understand your request is a bit different @david-cortes, but let's unify things in a single place. So I'm going to close this one as a duplicate of #10883.

By the way, I don't know if we can solve your request here because showing hidden files or directories on Windows requires modifying the registry. But please post your comment on that issue so we don't forget to take a look at it in the future.

**Comment by ccordoba12** [comment] 2019-12-11 14:42
Duplicate of #10883

**Closed by ccordoba12** 2019-12-11 14:42 UTC
