### ISSUE TITLE
Can spyder‘s theme be transparent

### ISSUE THREAD

**Issue by CangHaiQingYue** [spyder-ide/spyder#5178] opened 2017-09-09 02:09 UTC
## Versions and main components

* Spyder Version:3.X
* Python Version:3.X

**Comment by ccordoba12** [comment] 2017-09-09 15:41
Thanks for reporting. We consider this request as a duplicate of issue #2350, and we're working to fix it in Spyder 4, to be released next year.

**Closed by ccordoba12** 2017-09-09 15:41 UTC
