### ISSUE TITLE
Launch Spyder Problem

### ISSUE THREAD

**Issue by YufanZheng** [spyder-ide/spyder#4795] opened 2017-07-23 21:16 UTC
## Description of your problem

Launch Spyder problem

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Traceback (most recent call last):
File "/Users/yufan/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3011, in main
mainwindow = run_spyder(app, options, args)
File "/Users/yufan/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2913, in run_spyder
main.setup()
File "/Users/yufan/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 873, in setup
from spyder.plugins.ipythonconsole import IPythonConsole
File "/Users/yufan/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 60, in 
from spyder.widgets.ipythonconsole import ClientWidget
File "/Users/yufan/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in 
from .debugging import DebuggingWidget
File "/Users/yufan/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/debugging.py", line 16, in 
from qtconsole.rich_jupyter_widget import RichJupyterWidget
File "/Users/yufan/anaconda/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 14, in 
from .jupyter_widget import JupyterWidget
File "/Users/yufan/anaconda/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 19, in 
from IPython.lib.lexers import IPythonLexer, IPython3Lexer
File "/Users/yufan/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/Users/yufan/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in 
from IPython.core import release, crashhandler
File "/Users/yufan/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in 
from IPython.core import ultratb
File "/Users/yufan/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "/Users/yufan/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

**Comment by dalthviz** [comment] 2017-07-23 22:02
I think this is a duplicate of #4605

**Comment by ccordoba12** [comment] 2017-07-23 23:38
Thanks @dalthviz!

@YufanZheng, please take a look at the last comment on that issue to see how to fix this problem.

**Closed by ccordoba12** 2017-07-23 23:38 UTC
Labels: resolution:Duplicate
