### ISSUE TITLE
How to Add a path to the  Environment Variables of a project in Spyder 

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#13642] opened 2020-08-27 19:35 UTC
I would like to add an Environment Variables and path to my  Environment Variables for a project in spyder.

 can I do it? if so how?
If I open spyder from the terminal the project runs fine. but if I just open spyder (not from the terminal) it shows me that `Please add the following line to .bashrc:`. I do have the path already added to `.bashrc`. I also tried to do  `conda-develop /mypath/`, but it did not help.
Any suggestions will be so much appreciated.

I also saw the same problem in the following issue, as I mentioned opening spyder from terminal solve it, but I am wondering if I can add the environment variable in my project so I don't have to open spyder from the terminal

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/675#issuecomment-447615380_

Im using the latest version of spyder at the time (4.1.4) and ubuntu 16.04 and python 3

**Comment by andfoy** [comment] 2020-08-28 17:52
@seyeeet, thanks for suggesting this feature, we will take it into account for Spyder 5. In the meantime, you can modify the launcher of Spyder (.desktop) in order to add your variables to it: https://askubuntu.com/questions/144968/set-variable-in-desktop-file, that should enable your variables from the launcher of Spyder directly.

**Comment by seyeeet** [comment] 2020-08-28 17:57
@andfoy Thank you, the linked that you shared solved my problem
Yeah, would be great if also add this to spyder

**Comment by seyeeet** [comment] 2020-08-28 21:24
@andfoy thanks for your suggestion. I tried that link but I guess due to lack of my knowledge i could not solve the problem.
In details here is what is happening
when I run the code from spyder (when spyder is not opened from the terminal) it shows me: 

```
Please add following line to .bashrc:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/sam/.mujoco/mujoco200/bin
```

but I already have it in my `.bashrc` and when I open spyder from the terminal it works fine.

So I tried to add it using ` Exec=env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/sam/.mujoco/mujoco200/bin` but it still is not working. I also tried to change the `/home/sam/anaconda3/bin/activate `  I opened the `sudo gedit /home/sam/anaconda3/bin/activate 
` 
and it shows
```
#!/bin/sh
_CONDA_ROOT="/home/sam/anaconda3"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
```
 but I was not sure where and how I should add what.

Can you please let me know what you think I can do?
Thanks

**Comment by ccordoba12** [comment] 2020-08-31 19:59
Thanks for reporting @seyeeet. This is a duplicate of issue #3891.

**Closed by ccordoba12** 2020-08-31 19:59 UTC
Labels: type:Enhancement

**Comment by BJWiley233** [comment] 2020-12-19 04:35
So you can or can't add `Exec=env LD_LIBRARY_PATH=$LD_LIBRARY_PATH...` to the .desktop file?

**Comment by BJWiley233** [comment] 2020-12-19 05:31
@seyeeet I found [this](https://unix.stackexchange.com/questions/101620/how-to-load-bashrc-from-bash-c) worked.  Adding `Exec=bash -i -c "/home/coyote/anaconda3/bin/spyder %F"` So that it will run like executing from terminal which will call ~/.bashrc
