### ISSUE TITLE
Open Project Error

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#13338] opened 2020-07-20 14:59 UTC
### What steps will reproduce the problem?

Doing Projects > Open Project Automatically triggers this error.

### Traceback
```python-traceback
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 98, in <lambda>
    triggered=lambda v: self.open_project())
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 288, in open_project
    self.notify_project_open(path)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\decorators.py", line 22, in wrapper
    self.emit_request(method, params, requires_response)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 553, in emit_request
    self.main.completions.broadcast_notification(method, params)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 323, in broadcast_notification
    req_type, req)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 578, in broadcast_notification
    self.send_notification(language, request, params)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 569, in send_notification
    client.perform_request(request, params)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 527, in perform_request
    _id = handler(params)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\decorators.py", line 41, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\providers\workspace.py", line 46, in send_workspace_folders_change
    folder_uri = path_as_uri(folder)
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\providers\utils.py", line 51, in path_as_uri
    path_obj = pathlib.Path(osp.abspath(path))
  File "C:\Users\Lenovo_student\Anaconda3\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by kaleb-keny** [comment] 2020-07-20 15:12
Interesting I restarted my pc, and I don't have a problem anymore, but basically how I triggered it is that I just press on "projects" then press "Open Project" and the report github message is triggered... I even tried earlier closing and opening spyder back up, but the problem persisted... However, the restart seems to have done the trick.. I'll post an update with an animation if this issue shows up again...

**Comment by goanpeca** [comment] 2020-07-20 15:14
Ok, thanks for the heads up. Cheers.

**Comment by ccordoba12** [comment] 2020-07-21 18:47
Closing as a duplicate of #13346.

**Closed by ccordoba12** 2020-07-21 18:47 UTC
Labels: status:Awaiting Followup
