### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zjlal5753** [spyder-ide/spyder#5076] opened 2017-08-28 19:19 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 872, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "/usr/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 919, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "/usr/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "/usr/lib/python2.7/site-packages/qtconsole/console_widget.py", line 631, in execute
    self._execute(source, hidden)
  File "/usr/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.3 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-28 21:39
Duplicate of issue #5053.

**Comment by ccordoba12** [comment] 2017-08-28 21:40
Please post in that issue an screenshot of how your IPython console looks when this error is generated.

**Closed by ccordoba12** 2017-08-28 21:39 UTC
