### ISSUE TITLE
go to definition shows error in internal console

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#10463] opened 2019-10-19 12:35 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Paste in a new file
```python
from qtpy.QtCore import Qt
Qt.FramelessWindowHint
```
2. Cmd + click on `FramelessWindowHint`
3. The following traceback is produced

### What is the expected output? What do you see instead?
`FramelessWindowHint` is defined in a c file, so I don't really expect anything, but there is an error

### Paste Traceback/Error Below (if applicable)

```python-traceback

--- Logging error ---
Traceback (most recent call last):
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 1221, in handle_go_to_definition
    def_range = position['range']
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "bootstrap.py", line 186, in <module>
    start.main()
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/start.py", line 209, in main
    mainwindow.main()
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 3646, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 3529, in run_spyder
    app.exec_()
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/completion/languageserver/client.py", line 343, in on_msg_received
    handler(resp['result'], req_id)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/completion/languageserver/providers/document.py", line 198, in process_go_to_definition
    {'params': result})
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/completion/languageserver/plugin.py", line 279, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/completion/plugin.py", line 138, in receive_response
    self.gather_and_send(request_responses)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/completion/plugin.py", line 189, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 915, in handle_response
    handler(params)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 1238, in handle_go_to_definition
    "Error when processing go to definition")
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 946, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)

```

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: 37f7df783) 
* Python version: Python 3.7.4 64-bit 
* Qt version:  Qt 5.12.4
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Darwin 19.0.0

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2019-10-19 18:03
Duplicate of #10439.

**Closed by ccordoba12** 2019-10-19 18:03 UTC
