### ISSUE TITLE
Cannot plot inline in IPython console on Linux

### ISSUE THREAD

**Issue by petebachant** [spyder-ide/spyder#2257] opened 2015-03-18 05:01 UTC
Using 2.3.3 with Python 3.4.3 installed via Conda. Attempting to plot via matplotlib inline in the IPython console kills the kernel. I am not having this problem on Windows.

**Comment by blink1073** [comment] 2015-03-18 05:08
I can confirm:

```python
%matplotlib inline

import matplotlib.pyplot as plt

plt.plot([1,2,3])
Out[3]: [<matplotlib.lines.Line2D at 0x7fc1e46c5f60>]It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
```

**Comment by blink1073** [comment] 2015-03-18 05:10
Works fine with Py2.7.

**Comment by blink1073** [comment] 2015-03-18 05:12
...and it works fine from a standalone IPython QtConsole with Py3.4.

**Comment by blink1073** [comment] 2015-03-18 05:14
I used IPython 3.0.0 in both cases.

**Comment by ccordoba12** [comment] 2015-03-18 05:16
I was about to release 2.3.4 tomorrow but this seems pretty serious.

I can't reproduce it on my end with pip installed mpl 1.4.3 and Python 3.4.0. It seems to be an issue with mpl or Anaconda or both.

**Comment by ccordoba12** [comment] 2015-03-18 05:18
Is `%matplotlib qt` working for you?

**Comment by petebachant** [comment] 2015-03-18 05:20
`%matplotlib qt` does work for me.

**Comment by blink1073** [comment] 2015-03-18 05:21
Also for me.

**Comment by ccordoba12** [comment] 2015-03-18 05:21
What about mpl 1.4.2 and/or Python 3.4.2?

**Comment by petebachant** [comment] 2015-03-18 05:26
Tried both (one at a time) and kernel is still dying.

**Comment by blink1073** [comment] 2015-03-18 05:27
Ditto.

**Comment by ccordoba12** [comment] 2015-03-18 05:31
@stonebig, have you seen this problem on WinPython?

This really seems a compilation bug to me. I don't understand what we can be doing to make the kernel crash.

What if you try to use 2.3.4dev or 2.4dev? I made some changes to change how we set the mpl backend that could help in this case...

**Comment by ccordoba12** [comment] 2015-03-18 05:34
Checking older Spyder versions (in the 2.3 series) would be useful too :-)

**Comment by petebachant** [comment] 2015-03-18 05:36
Works fine in 2.3.2.

**Comment by ccordoba12** [comment] 2015-03-18 05:38
@petebachant, great, some progress!! Could you use `git bisect` to detect the faulty commit?

**Comment by petebachant** [comment] 2015-03-18 05:49
I don't know how to do that; sorry! I did, however get the console to plot SVGs, and noticed this commit: https://github.com/spyder-ide/spyder/commit/ac52a4adb046ba8a9a13e5b70f436165bdc8be3b. Maybe the dpi for PNGs is being set incorrectly?

**Comment by petebachant** [comment] 2015-03-18 05:51
I just noticed that spinbox does not work in 2.3.3.

**Comment by ccordoba12** [comment] 2015-03-18 05:52
I'll take a look at that tomorrow. Thanks a lot for the feedback @petebachant, perfect timing!

**Comment by stonebig** [comment] 2015-03-18 17:21
Well, I don't see the problem on winpython with  python3.4.3 32 bit + Spyder 2.3.3 + windows 7 64bit.
(+all wheel packages prepared by Christoph Gohlke)

![spyder233_check](https://cloud.githubusercontent.com/assets/4312421/6714889/1b8dd69a-cd9b-11e4-9055-74687929b749.GIF)

**Comment by petebachant** [comment] 2015-03-18 20:13
I also do not have the problem on Windows, and have tried on multiple systems with different graphics drivers. An IPython Qt console can plot inline externally without a problem. I think this is a Spyder issue.

**Comment by ccordoba12** [comment] 2015-03-18 20:19
So this is on Linux? It's true that the issue title says it, but the description mentions Windows. That's why I asked @stonebig about it.

@petebachant, are you using Kubuntu, or KDE as your main desktop, by any chance?

**Comment by petebachant** [comment] 2015-03-18 20:20
This is on Linux only (for me anyway). I have had the problem on both XFCE and Cinnamon desktops.

**Comment by ccordoba12** [comment] 2015-03-18 20:24
Could you create a new conda environment and install the new PyQt packages I'm working on? For that you need to run this command after creating the env:

    conda install -c ccordoba12 pyqt

Then you need to install IPython and Spyder with

    conda install pygments ipython
    conda install --no-deps spyder

Try to see if this error happens in that env too

**Comment by petebachant** [comment] 2015-03-18 21:44
I gave that a try. Could not load Spyder without some additional dependencies. Once I got to that point I didn't have the IPython Qt console, which wants to downgrade Qt to install.

**Comment by ccordoba12** [comment] 2015-03-18 23:07
@blink1073, help me out here, please. Since you're able to reproduce this error, could you run `git bisect` or `git blame` to locate the faulty commit between 2.3.2 and 2.3.3?

**Comment by ccordoba12** [comment] 2015-03-19 00:40
Ok, I fixed the problem with the inability to change our dpi value. This will be part of 2.3.4

**Comment by blink1073** [comment] 2015-03-19 01:27
Sorry Carlos, I was travelling today.

**Comment by blink1073** [comment] 2015-03-19 01:42
Found it:  

```
commit 08596df5a484cce6852e193a7b938e5c200aec43
Author: Carlos Cordoba <ccordoba12@gmail.com>
Date:   Sun Feb 8 22:17:15 2015 -0500

    External Console: Fix plotting with Matplolib Tk and Gtk backends
    
    Fixes issue 2022
    Fixes issue 1946
    Fixes issue 1987
    
    - This also lets users to set their preferred mpl backend on Mac *again* when
    using PySide.
    - To solve this we moved to handle input hooks using code from IPython.
    - We also carefully decide what input hook to use according to the mpl backend
    and operating system.
```

**Comment by blink1073** [comment] 2015-03-19 01:45
Quicklink: https://github.com/spyder-ide/spyder/commit/08596df5a484cce6852e193a7b938e5c200aec43

**Closed** 2015-03-21 20:29 UTC
Labels: IPython-Console

**Comment by ccordoba12** [comment] 2015-03-21 20:31
Thanks @blink1073! It was easier to narrow down the problem after that :-)
