### ISSUE TITLE
Plots pane keeps coming back

### ISSUE THREAD

**Issue by lukecherveny** [spyder-ide/spyder#15467] opened 2021-04-29 20:04 UTC
### What steps will reproduce the problem?

With in-line plotting checked in Spyder 5.0, plotting from editor or console still switches to the plots pane.  If the plots pane is closed, it just comes back.

Basically, I want to plot in-line and never deal with or see the Plots panel, as was possible in Spyder 4.0.

**Comment by andfoy** [comment] 2021-04-30 03:36
Hi @lukecherveny, thanks for opening this bug. This issue is a regression from Spyder 4 and we'll take a look at it.

**Comment by ccordoba12** [comment] 2021-04-30 17:55
I'll take a look at this one for 5.0.2 because it's a serious regression. Thanks for reporting @lukecherveny!

**Comment by JohnRobson** [comment] 2021-05-01 17:26
Another problem with the Plots Pane related to this problem is that the options "Undock" and "Close" are Disable, only after you plot something they become enabled.

**Comment by ccordoba12** [comment] 2021-05-01 18:37
That was fixed in our 5.0.1 version, released two weeks ago.

**Closed** 2021-05-01 19:29 UTC
Labels: component:Plots, type:Bug
