### ISSUE TITLE
Variable Explorer "Type" is not right

### ISSUE THREAD

**Issue by maurice74** [spyder-ide/spyder#3527] opened 2016-10-12 14:10 UTC
In the Variable Explorer window, I see a wrong "Type" for certain variables
You can see in the screenshot attached: the variable data is a numpy array containing doubles, but it is identified as an int

![screen shot 2016-10-12 at 16 06 43](https://cloud.githubusercontent.com/assets/5611231/19313286/40cfd448-9096-11e6-9e7f-edc15d8d891c.png)
## Versions and main components
- Spyder Version: Spyder 3.0.0 
- Python Version: 3.5
- Operating system: Mac OSx El Capitan
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-12 15:17
Thanks for reporting. Could you give us a reproducible example of the array you're generating, so we can test and fix this problem in our side?

Thanks :-)

**Comment by malliwi88** [comment] 2016-10-26 22:27
HI @ccordoba12 

This does not seem to be a problem since version 3.0.0. as you can see here.
![seleccion_008](https://cloud.githubusercontent.com/assets/5307894/19747473/67efeafc-9ba1-11e6-9d14-da46252ec787.png)

If you want to make a this simple test on your Mac machine:

```python
import numpy as np
data = np.array(np.random.normal(1,3, (1,3)), dtype='f')
```

So, we could close this issue.

**Comment by Pretender451** [comment] 2017-12-14 15:49
This happens a lot for me too and has been limiting on our use of Spyder 3.2.4 with Python 3.5.4.
I've especially noticed it with Pandas Dataframes.
It is important to us as the Variable Explorer is the main reason we use Spyder over another IDE.

**Comment by ccordoba12** [comment] 2017-12-14 15:51
@Pretender451, please give us a simple and reproducible example that's failing for you, so we can test it in our side.

**Comment by Pretender451** [comment] 2017-12-14 16:03
Thanks @ccordoba12.
I would like to protect the data if possible, including the 29 column names. Do you need anything other than the following?:

type(dvdf)
Out[18]: pandas.core.frame.DataFrame

dvdf.shape
Out[19]: (8706, 29)

![image](https://user-images.githubusercontent.com/32776962/34001463-587ec832-e0f0-11e7-89f9-4c53d1d7c944.png)

There are other dataframes listed correctly.
There are other types listed incorrectly, eg dictionary as module.

**Comment by ccordoba12** [comment] 2017-12-14 16:06
@Pretender451, you can send me your data privately, if you prefer, along with the code you used to create your Dataframe.

Or you have to come up with a simple example where Type is incorrectly identified.

**Comment by Pretender451** [comment] 2017-12-14 16:07
Sorry i didn't try this before but it seems to be resolved by deselecting "Exclude private references". 
This is a workable if not ideal workaround for us.

**Comment by ccordoba12** [comment] 2017-12-14 16:16
Well, that's not really a solution but a workaround. Are all Dataframes you generate misidentified as lists?

**Comment by Pretender451** [comment] 2017-12-14 16:31
Actually while "Exclude private references" corrects some it does not correct others. Another dataframe is listed as dict with it selected, for example, and int64 with it deselected. Also have arrays listed as int64 (similar to OP) and dictionaries as lists.

Have also noticed that with "Exclude private references" deselected the order by 'Type column' does not list the same types together, so the workaround has other costs too.

**Comment by ccordoba12** [comment] 2017-12-14 16:33
Ok, but we still need a way to reproduce this because I'm not seeing myself.

**Comment by Pretender451** [comment] 2017-12-14 16:45
That dataframe (shape only 559x2) which was listed as both dict then list, is now listed as a datetime, even though it's two columns are float and the index is int.

**Comment by CAM-Gerlach** [comment] 2018-01-01 12:24
@Pretender451 Assuming this is still an issue on the latest Spyder version (3.2.5, as of this writing, though 3.2.6 is tentatively scheduled for an early release tomorrow), I could try to take a look at it myself, though I'm still new so no promises I'll be able to fix it. 

I'm unsure how the "29 column names" fits with only having two columns, but regardless, you can trivially set them to something else (*e.g.* something like `df.columns = [str(i) for i in range(1, len(df) + 1)]` should work), pickle it, make sure you can reproduce the issue when you unpickle it into another DataFrame, and (assuming so) send it over. 

To be quite candid, presently I too do data analysis with Spyder for a private company with a non-disclosure, etc. and while I need not go into any detail, some the data I work with (for better or for worse) is indeed proprietary/trade secret, and perhaps even national security related (e.g. it is a matter of public knowledge that at least one of the radars used by the US GMD missile defense system was designed/built and is supported by this company). However, unless this particular dataset is actually classified top secret or the like where its the blind principle of the thing that matters, I can't imagine a couple hundred arbitrary `floats` with a simple integer index are going to have much of any meaning to anyone someone who didn't already know exactly what they were looking at, particularly without the revealing column names, as you mention. 

If you're still concerned, just subset it to 1/10 the size, or do an in-place replace of the data with random float32s, so long as it still reproduces the issue. Otherwise, unless Mr. Córdoba or one of the other devs stumbles upon it by sheer luck, it seems quite unlikely, to say the least, that we will be able to solve this problem that you mention is important to you.

**Comment by Pretender451** [comment] 2018-01-06 08:37
@CAM-Gerlach Thanks for answering and for the offer of help. 

Firstly, yes this is still an issue on Spyder 3.2.5.

"I'm unsure how the "29 column names" fits with only having two columns... " This was actually the point: shape showed 29, whereas Variable Explorer showed 2.

When i try to save the workspace to send either of you (@ccordoba12 @CAM-Gerlach) then i get error, "Unable to save current workspace

Error message:
Can't pickle: attribute lookup module on builtins failed"

Could this be a clue to the main problem?

**Comment by CAM-Gerlach** [comment] 2018-01-06 08:45
Might this be related to #6140 ?

> "I'm unsure how the "29 column names" fits with only having two columns... " This was actually the point: shape showed 29, whereas Variable Explorer showed 2.

Ah, thanks.

> When i try to save the workspace to send either of you (@ccordoba12 @CAM-Gerlach) then i get error, "Unable to save current workspace
Error message:
Can't pickle: attribute lookup module on builtins failed"

Useful to know, but that error message probably isn't related. What we asked was for you to send us the just the pickled dataframe, not your whole workspace. You can pickle it with e.g. ``df.to_pickle("path/to/save/location.pkl")``. Just make sure the problem still occurs when you reload the dataframe (e.g. with ``df_pickled = read_pickle("path/to/dataframe.pkl")``, otherwise we won't see it either. Thanks.

**Comment by Pretender451** [comment] 2018-01-06 11:01
@CAM-Gerlach Thanks again.

**_Current example:_**
dvdf is currently showing as an int.
`dvdf2 = dvdf.copy()`
dvdf2 shows correctly as Dataframe (although it's size is incorrectly listed and i see another unrelated variable in the Explorer which has dvdf2's size). So i don't think pickling and sending the data will help will it?

The fact that the attributes Name, Type, Size and Value all seem to be there but each without seeming to be correctly linked to each other (as they change, for example, depending on 'Gear icon -> "Exclude..." settings') suggests that this is an issue with the Explorer rather than the data doesn't it? In fact, Name and Value are correctly linked but not Type and Size.

Are there any thresholds to numbers of variables above which there are issues in Variable Explorer? Above 100, for example?

Thanks for the suggestion but this is not the same symptoms as #6140

**Comment by Pretender451** [comment] 2018-01-06 11:09
Although not fully tested, i get the impression that Type&Size are linked, and Name&Value are linked but these two groups are not correctly tied together.

**Comment by CAM-Gerlach** [comment] 2018-01-06 17:04
> So i don't think pickling and sending the data will help will it?

We appreciate you following up, but unless one of us stumbles upon it in daily use, which so far has not apparently occurred, ultimately we're just blindly guessing at what's going on unless we have a way to reproduce what you're seeing ourselves. Considering it should only take a minute or two to type/paste the code to confirm this either way, and as we've stated this is a crucial piece of information needed to solve your problem, I'm not sure what the downside is to simply trying it.

Whether or not this reproduces it by itself, it would also be very helpful (and quite possibly necessary) if you could send/post a minimal reproducible example of the code you are using to process your data, immediatly before the error occurs. I.e., can you write an example, as minimal as practicable, that reproduces the error from a clean console? Also, how are you reading in your data, and does a particular data file/source/format trigger this error? If so, then a minimized example of one of the same would likely be very helpful in allowing us to reproduce it. Thanks.

> Are there any thresholds to numbers of variables above which there are issues in Variable Explorer? Above 100, for example?

I'm not directly aware or nor experienced one, at least working with at least many dozen, likely well over a hundred counting hidden items, and I just tested it with around 150-200 visible variables, and was able to open and copy several dataframes with no issues.

**Comment by Pretender451** [comment] 2018-01-07 10:11
Right, i isolated the cause of this (in this specific case) to a `pass` at the end of a `try:` `except:` block which was in place to deal with a known issue in SciKit Learn. 

While the `pass` did not seem to cause a problem for SciKit Learn, whenever a list was initialised after that point in the code, in any scope, it messed up some variable types in Variable Explorer. I think it is a step forward to just be aware of this. 

Is it also by design in Variable Explorer that numpy arrays show the type they contain, eg 'int', rather than 'ndarray'?

**Comment by CAM-Gerlach** [comment] 2018-01-07 16:14
> I think it is a step forward to just be aware of this.

Yes indeed, it would be.

> Right, i isolated the cause of this (in this specific case) to a pass at the end of a try: except: block which was in place to deal with a known issue in SciKit Learn.

From your code? If so, and presuming the problem is indeed with Variable Explorer not handling it properly versus it being something intrinsic to the code, you'll need to include a snippet and basic explanation here if we're to do anything about it. Or, with our code? If so, we'll need the file and line number.

> Is it also by design in Variable Explorer that numpy arrays show the type they contain, eg 'int', rather than 'ndarray'?

I didn't design it, but I would presume yes, since one can directly infer the array type from the fact that a numpy type is used, and also from the formatting of the "Value" field.

**Comment by Pretender451** [comment] 2018-01-10 15:29
>> Right, i isolated the cause of this (in this specific case) to a pass at the end of a try: except: block which was in place to deal with a known issue in SciKit Learn.

> From your code? 

Yes. The following is inside a loop but it causes the problem if just run once:

```
                    if occurrences > 0:
                        try:
                            SKOutput.fit(
                                fullSubWindfname[IVs],
                                fullSubWindfname['movedCorrectly'])
                            if model == 'both':
                                coefSum = SKOutput.coef_[0][0] + SKOutput.coef_[0][1]
                            else:
                                coefSum = SKOutput.coef_[0][0]
                            sumParams = SKOutput.intercept_ + coefSum
                            trend = round(math.exp(SKOutput.intercept_) /
                                          (math.exp(SKOutput.intercept_) + 1), 2)
                            ivOnly = round(math.exp(coefSum) /
                                           (math.exp(coefSum) + 1), 2)
                            p = round(math.exp(sumParams) / (math.exp(sumParams) + 1), 2)
                        except ValueError:
                            trend = 0.5
                            ivOnly = 0.5
                            if ((fullSubWindfname[IVs].count()[0] == 0) &
                                    (fullSubWindfname['movedCorrectly'].count() > 0)):
                                p = 0.5
                            elif ((fullSubWindfname[IVs].count()[0] > 0) &
                                    (fullSubWindfname['movedCorrectly'].count() == 0)):
                                p = 0

                            else:
                                p = 0.5
                            pass # What was this <pass> for originally?
                            # Causes mess up of var types in Variable Explorer.
                    else:
                        p = 0.5
```
My solution is to comment out the pass which i think was just there as a placeholder which should have been removed already.

>> Is it also by design in Variable Explorer that numpy arrays show the type they contain, eg 'int', rather than 'ndarray'?

> I didn't design it, but I would presume yes, since one can directly infer the array type from the fact that a numpy type is used, and also from the formatting of the "Value" field.

Yes, i presumed too, and , it increases the confidence in my assumptions to hear it from someone who i judge to know more about it than i do. Thanks for this.

**Comment by CAM-Gerlach** [comment] 2018-01-11 08:06
So is it ``fullSubWindfname`` that that the problem is occurring with? This code snippit doesn't actually appear to modify it, or anything else that appears to be a data frame, so not sure what's going on. Does it happen with any ``df``, or only those with specific properties? Either way, can you provide a minimal dataframe that reproduces the problem when run just with that code snippet?

``pass`` should be a no-op, essentially, so not sure why it has any effect anyway...but I'm no expert.

**Comment by goanpeca** [comment] 2019-11-25 19:06
I think this has been already solved @ccordoba12 ?

**Comment by ccordoba12** [comment] 2019-11-25 19:29
Yes, I think so.

**Closed by ccordoba12** 2019-11-25 19:29 UTC
Labels: component:Variable Explorer, status:Awaiting Followup, type:Bug
