### ISSUE TITLE
With Anaconda 1.6.11, spyder crashes on startup

### ISSUE THREAD

**Issue by btglau** [spyder-ide/spyder#6624] opened 2018-03-06 23:11 UTC
## Problem Description

On the latest Anaconda version, starting up Spyder immediately crashes.

### What steps will reproduce the problem?

1.  Use Anaconda on Windows
2. Try to launch Spyder from the conda console
3. Crash!

### What is the expected output? What do you see instead?

Expected spyder to start up

### Paste Traceback/Error Below (if applicable)

```python-traceback

>spyder
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1172, in setup
    self.setup_layout(default=False)
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1457, in setup_layout
    self.setup_default_layouts('default', settings)
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1633, in setup_default_layouts
    widget.toggle_view(True)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Anaconda3\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Anaconda3\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Anaconda3\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError

```

## Package Versions

anaconda Command line client (version 1.6.11)
* Spyder: spyder                    3.2.7                    py36_0
* Python:python                    3.6.4                h6538335_1
* Qt:qt                        5.6.2           vc14h6f8c307_12  [vc14]
* PyQt:pyqt                      5.6.0            py36hb5ed885_5
* Operating System:Windows 10

### Dependencies
Can't load spyder ...

**Comment by btglau** [comment] 2018-03-06 23:12
I have already tried `spyder --reset`

**Comment by csabella** [comment] 2018-03-07 00:39
Looks like #6623.  Please try the suggestion there to change the version of Tornado.

**Comment by CAM-Gerlach** [comment] 2018-03-07 03:23
Indeed looks identical, so I'm closing as a duplicate. If you have further issues after following the suggested advice, please post more information in that thread. Thanks.

**Closed by CAM-Gerlach** 2018-03-07 03:23 UTC

**Comment by CAM-Gerlach** [comment] 2018-03-07 03:32
Technically speaking, more canonically a duplicate of #6627 , which is not a spyder issue to begin with.

**Comment by btglau** [comment] 2018-03-07 16:09
Downgrading tornado worked, thanks!
