### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by Guozeqi** [spyder-ide/spyder#5887] opened 2017-12-04 07:40 UTC
## Description

**What steps will reproduce the problem?**

1. Start spyder
2. Open an IPython console
3. 

**What is the expected output? What do you see instead?**

An error ocurred while starting the kernel
Traceback (most recent call last):
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 229, in main
kernel.initialize()
File "", line 2, in initialize
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 238, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 180, in _bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
Traceback (most recent call last):
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 229, in main
kernel.initialize()
File "", line 2, in initialize
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 238, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 180, in _bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
Traceback (most recent call last):
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 229, in main
kernel.initialize()
File "", line 2, in initialize
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 238, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 180, in _bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
Traceback (most recent call last):
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 229, in main
kernel.initialize()
File "", line 2, in initialize
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 238, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 180, in _bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
Traceback (most recent call last):
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 229, in main
kernel.initialize()
File "", line 2, in initialize
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 238, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "E:\Anaconda3\envs\tensorflow\lib\site‑packages\ipykernel\kernelapp.py", line 180, in _bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use**

**Please provide any additional information below**

when i restart the kernel,there will be no faults

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-12-04 13:46
@minrk, have you seen this problem before? I really don't understand why it's happening...

**Comment by CAM-Gerlach** [comment] 2017-12-04 18:42
@minrk If you open up iPython, or qtconsole, etc. standalone, do they function normally, or do you get the same/similar bug either immediately or upon trying to run a command? If so, then it is not a Spyder bug. Check out [this issue thread ](https://github.com/ipython/ipython/issues/6109)on the iPython repo discussing it in more detail, with some potential solutions. In summary, ZMQ/the multiprocessing backend can't open a socket to talk to the process it needs to because it is already in use, whether by another instance of itself or another process.

**Comment by minrk** [comment] 2017-12-05 10:25
@ccordoba12 this can have various causes, but ultimately it tends to be caused by forked subprocesses (e.g. multiprocessing) failing to release the sockets held their parent, the kernel, when it restarts. If an entire process *group* is shutdown, it should be fixed. There are unfortunately lots of ways to cause this, and various ways to fix it, depending on precisely which failed cleanup is responsible.

**Comment by ccordoba12** [comment] 2017-12-05 16:52
Thanks for the explanation Min!

@Guozeqi, does this also happen for the Spyder version installed in your root environment?

**Comment by CAM-Gerlach** [comment] 2017-12-05 17:44
As an aside, an advanced task manager like Sysinternals Process Explorer may be helpful here, it clearly shows the processes tree with child processes and groups, and you can kill a process along with all its children all in one stroke if need be.

**Comment by Guozeqi** [comment] 2017-12-08 06:59
@ccordoba12  yes....this also happen when i start Spyder in my root environment

**Comment by Guozeqi** [comment] 2017-12-08 07:04
@CAM-Gerlach  when i open QtConsole alone it will show me "Kernek died,restarting".........

**Comment by Guozeqi** [comment] 2017-12-08 07:04
@CAM-Gerlach when i open QtConsole alone it will show me "Kernel died,restarting".........

**Comment by ccordoba12** [comment] 2017-12-08 13:49
> There are unfortunately lots of ways to cause this, and various ways to fix it

@minrk, could you be more specific here? What are the ways to fix this problem?

**Comment by Guozeqi** [comment] 2017-12-14 09:56
at present the error does not happen anymore after i updating the Anaconda Navigator from version 1.6.9 to 1.6.10

**Comment by ccordoba12** [comment] 2017-12-14 15:25
Great! Thanks for letting us know about it.

**Closed by ccordoba12** 2017-12-14 15:25 UTC
