### ISSUE TITLE
Error in display of tabulator in editor

### ISSUE THREAD

**Issue by feichtinger** [spyder-ide/spyder#7432] opened 2018-07-12 08:39 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The Spyder editor does not display tabulators right.

### What steps reproduce the problem?

1. open Spyder with default settings
2. load the attached file into Spyder editor
[temp.txt](https://github.com/spyder-ide/spyder/files/2187784/temp.txt)

3. see it?

### What is the expected output? What do you see instead?
A Tab should be EXACTLY 4 spaces wide, as configured in the settings. But in appears more like ~4.5 spaces making lines not aligned

## Versions

* Spyder version: 3.2.6
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.10.1
* Operating System name/version: Ubuntu 18.04 LTS

### Dependencies
```
IPython >=4.0    :  5.5.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.4.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by ccordoba12** [comment] 2018-07-12 13:56
> But in appears more like ~4.5 spaces making lines not aligned

Please post a screenshot because I don't understand what you mean by `4.5` spaces.

**Comment by feichtinger** [comment] 2018-07-12 14:58
Sceenshot:

![bildschirmfoto von 2018-07-12 16-56-54](https://user-images.githubusercontent.com/10723283/42641403-ca02fc22-85f4-11e8-820c-7ee7e79857f9.png)

**Comment by feichtinger** [comment] 2018-07-12 15:01
The same file with a different editor (Geany):

![bildschirmfoto von 2018-07-12 16-59-23](https://user-images.githubusercontent.com/10723283/42641571-1d833394-85f5-11e8-830d-6b53aa737da5.png)

**Comment by ccordoba12** [comment] 2018-07-12 21:35
I can't reproduce this

![seleccion_006](https://user-images.githubusercontent.com/365293/42660644-743ae474-85f1-11e8-945d-7bb1f30954f4.png)

so it looks like a problem with the font you choose.

**Comment by ccordoba12** [comment] 2018-07-13 21:42
Mixing spaces and tabs is a very bad idea, so I'd be in favor of closing this one. Realistically we also don't have time to invest in fixing this one.

What do you say @bcolsen?

**Comment by bcolsen** [comment] 2018-07-13 22:03
>Mixing spaces and tabs is a very bad idea, so I'd be in favor of closing this one.

This is not really a case of mixing spaces and tabs. The bug is there when you just use tabs (also a bad idea) The current way tabs are drawn would make it quite difficult to use the editor. The spacing can be off by 1.5 spaces depending on the font and size(Monospace 12) :

![tabs](https://user-images.githubusercontent.com/10513354/42715672-408467e4-86b5-11e8-9de7-0c9ed7809e85.png)

The two sections should be identical. Notice how the guides don't work either. This is a rendering bug that could impact code readability if you use tabs.

>Realistically we also don't have time to invest in fixing this one.

This is true, but this bug should be kept as reference to the issue.  I don't use tabs so it's low on my priorities

**Comment by feichtinger** [comment] 2018-07-14 08:15
> The bug is there when you just use tabs (also a bad idea)
Well, in my opinion it is a bad idea to use SPACES to indent, but that's a different discussion. Everyone should have the choice of using tabs OR spaces. It is true that mixing spaces and tabs does not make sense, I just used them in the example to make the problem clear.

The point is, that a program editor has to use a monospace font and render it correctly in order to make things line up. But in Spyder editor this does not work when using tabs. So in my opinion this is a SEVERE bug.

I mean, this is a text editor. If this was a MINOR bug, what are your SEVERE bugs that you have to fix first??? Not being able to load a text file?


@bcolsen: Did you find a combination of font and font size so that the editor is usable again?

**Comment by ccordoba12** [comment] 2018-07-14 13:15
> So in my opinion this is a SEVERE bug.

You're welcome to fix it. I consider this low priority because you're the first person to report it.

**Comment by feichtinger** [comment] 2018-07-14 16:31
> You're welcome to fix it.
OK, I will give it a try. Can you give me a hint where to start? Which file is responsible for rendering the editor window content?

**Comment by CAM-Gerlach** [comment] 2018-07-14 19:14
For the record, I can reproduce it on Spyder 3.3.0 on Win8.1/Python 3.6.6/Qt 5.6 as well. 

I'm not as familiar with the details of the underpinnings as some, but the [Editor widget](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/editor.py) would be one place to start. Since this is a low-level bug, if it ends up being straightforward you could probably justify fixing this on ``3.x``.

**Closed** 2018-07-16 13:19 UTC
Labels: component:Editor, type:Bug

**Comment by ccordoba12** [comment] 2018-07-16 13:20
@feichtinger, the fix for this should be available in our **3.3.1** version.

**Comment by feichtinger** [comment] 2018-07-19 08:20
Thanks for investigating this bug. Unfortunately the issue is still not fixed on my system. 
![bildschirmfoto von 2018-07-19 10-13-46](https://user-images.githubusercontent.com/10723283/42930190-a22f8858-8b3c-11e8-9d0c-0f25ecf00534.png)

I pulled the latest 3.x branch from github (commit: a2c60d714) and used the bootstrap.py script.

**Comment by feichtinger** [comment] 2018-07-19 10:37
This should fix it:
https://github.com/spyder-ide/spyder/pull/7502
