### ISSUE TITLE
Variable explorer is not working

### ISSUE THREAD

**Issue by caiogirao** [spyder-ide/spyder#9923] opened 2019-07-30 17:25 UTC
### What steps will reproduce the problem?

I can not see anything on variable explorer. I already installed all dependencies required. Except for pyls, I can't install pyls==0.19, the last version avaliable that appears on my prompr is pyls==0.1.6

### Traceback
```python-traceback
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\ipythonconsole\plugin.py", line 742, in <lambda>
    lambda c=client: self.process_started(c))
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\ipythonconsole\plugin.py", line 1378, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\variableexplorer\plugin.py", line 138, in add_shellwidget
    nsb.setup(**self.get_settings())
TypeError: setup() got an unexpected keyword argument 'show_callable_attributes'
Traceback (most recent call last):

```

## Versions

* Spyder version: 4.0.0.dev0 e49611571
* Python version: 3.6.5
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.1.2 (OK)
pyls >=0.19.0;<0.25:  0.1.6 (NOK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.25.0 (OK)
numpy >=1.7        :  1.17.0 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.2 (OK)
qtconsole >=4.2.0  :  4.4.4 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.1 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-31 09:39
Duplicate of #9922.

**Closed by ccordoba12** 2019-07-31 09:39 UTC

**Comment by ccordoba12** [comment] 2019-07-31 09:52
> pyls >=0.19.0;<0.25:  0.1.6 (NOK)

This is still totally wrong (and I don't know how you ended up with that version). To fix this you need to do

    pip install python-language-server==0.27
