### ISSUE TITLE
After updating python now I am having issues with Spyder

### ISSUE THREAD

**Issue by dantheman3232** [spyder-ide/spyder#6952] opened 2018-04-12 18:32 UTC
After updating python to solve an earlier issue I am now receiving this launch error when I try to open spyder. The error prevents me from even opening the application. 

## Problem Description
Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 27, in 
from spyder.config.main import CONF
File "/anaconda3/lib/python3.6/site-packages/spyder/config/main.py", line 22, in 
from spyder.config.user import UserConfig
File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 26, in 
from spyder.utils.programs import check_version
File "/anaconda3/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in 
import subprocess
File "/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:
* Python:
* Qt:
* PyQt:
* Operating System:

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment] 2018-04-12 20:12
Thanks for reporting. This is a duplicate of #6876 which apparently is a problem with Python itself, and there isn't much we can do about it. Therefore, you can solve it for now by downgrading to Python 3.6.4 with ``conda install python=3.6.4``.

**Closed by CAM-Gerlach** 2018-04-12 20:12 UTC

**Comment by ccordoba12** [comment] 2018-04-12 21:14
This is supposed to be fixed by downgrading to Python 3.6.4, but you that version was giving you issue #6335, so I don't know how to help you further. In any case, both problems are not related to Spyder directly, but they are Python problems.

@mingwandroid, have you seen the problem above with Python 3.6.5 in macOS?

**Comment by ccordoba12** [comment] 2018-04-12 21:15
Ups, I didn't see @CAM-Gerlach's comment before publishing my own. @dantheman3232, please follow his advice.

@mingwandroid, sorry for the unnecessary ping.

**Comment by CAM-Gerlach** [comment] 2018-04-12 22:37
> Ups, I didn't see @CAM-Gerlach's comment before publishing my own. @dantheman3232, please follow his advice.

I actually said the same thing you did above in my comment before I saw the issue I linked to, heh.

**Comment by mingwandroid** [comment] 2018-04-13 12:10
No problem; we need to stop building `python.app` the way we are building it. Frequently when we bump Python versions we forget to update `python.app` and this is really bad. I will try to get time scheduled to address this properly.

**Comment by tykavanaugh** [comment] 2018-12-22 18:05
Just want to update that I had the same error, so it seems been have forgotten, but it was fixed via conda update python.app
