### ISSUE TITLE
"Ctrl I" Help Error

### ISSUE THREAD

**Issue by ManInWhite** [spyder-ide/spyder#6011] opened 2017-12-19 00:00 UTC
## Description

**What steps will reproduce the problem?**

1.  Press Control-I
2. 
3. 

**What is the expected output? 
__doc__ info

What do you see instead?**
Nothing or error message

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 855, in inspect_current_object
    self.introspector.show_object_info(position, auto=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for

**Comment by CAM-Gerlach** [comment] 2017-12-19 00:08
Thanks for reporting. The error traceback that was posted is incomplete. However, it is very likely a duplicate of e.g. #5673 , an error that's been reported numerous times now. As the full error message states, Jedi is only compatible with `parso` 0.1.0, not 0.1.1. Therefore, you can update `jedi` to the latest version with `conda update jedi` (or with `pip`, if you use that instead); (you can also downgrade to `parso` 0.1.0 with e.g. `conda install parso=0.1.0` ) and so this issue will be closed.

**Closed by CAM-Gerlach** 2017-12-19 00:08 UTC
