### ISSUE TITLE
Autocomple not working

### ISSUE THREAD

**Issue by salihsahin45** [spyder-ide/spyder#13101] opened 2020-06-25 05:29 UTC
### What steps will reproduce the problem?

Spyder 4.1.3
autocomplete never working.

Conda List:
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0
argh                      0.26.2                   py38_0
astroid                   2.4.1                    py38_0
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.1.0                    py38_0
bcrypt                    3.1.7            py38he774522_0
blas                      1.0                         mkl
bleach                    3.1.4                      py_0
ca-certificates           2020.1.1                      0
certifi                   2020.6.20                py38_0
cffi                      1.14.0           py38h7a1dbc1_0
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.4.1                      py_0
colorama                  0.4.3                      py_0
console_shortcut          0.1.1                         4
cryptography              2.9.2            py38h7a1dbc1_0
cycler                    0.10.0                   py38_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
docutils                  0.16                     py38_0
entrypoints               0.3                      py38_0
flake8                    3.7.9                    py38_0
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   py38_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.9                        py_1
imagesize                 1.2.0                      py_0
importlib-metadata        1.6.0                    py38_0
importlib_metadata        1.6.0                         0
intel-openmp              2020.1                      216
intervaltree              3.0.2                      py_0
ipykernel                 5.1.4            py38h39e3cac_0
ipython                   7.13.0           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
isort                     4.3.21                   py38_0
jedi                      0.15.2                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.15.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py38_0
jupyter_client            6.1.3                      py_0
jupyter_core              4.6.3                    py38_0
keyring                   21.1.1                   py38_2
kiwisolver                1.2.0            py38h74a9793_0
lazy-object-proxy         1.4.3            py38he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py38he774522_0
matplotlib                3.1.3                    py38_0
matplotlib-base           3.1.3            py38h64f37c6_0
mccabe                    0.6.1                    py38_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.0.15           py38h14836fe_0
mkl_random                1.1.1            py38h47e9c7a_0
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.6                      py_0
nltk                      3.5                        py_0
notebook                  6.0.3                    py38_0
numpy                     1.18.1           py38h93ca92e_0
numpy-base                1.18.1           py38hc3f5095_1
numpydoc                  0.9.2                      py_0
olefile                   0.46                       py_0
openssl                   1.1.1g               he774522_0
packaging                 20.3                       py_0
pandas                    1.0.3            py38h47e9c7a_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py38_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
pathtools                 0.1.2                      py_1
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.1.2            py38hcc1f983_0
pip                       20.0.2                   py38_3
plotly                    4.7.1                      py_0
pluggy                    0.13.1                   py38_0
prometheus_client         0.7.1                      py_0
prompt-toolkit            3.0.4                      py_0
prompt_toolkit            3.0.4                         0
psutil                    5.7.0            py38he774522_0
pycodestyle               2.5.0                    py38_0
pycparser                 2.20                       py_0
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py38_0
pygments                  2.6.1                      py_0
pylint                    2.5.2                    py38_0
pynacl                    1.3.0            py38h62dcd97_0
pyopenssl                 19.1.0                   py38_0
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py38ha925a31_4
pyrsistent                0.16.0           py38he774522_0
pysocks                   1.7.1                    py38_0
python                    3.8.3                he1778fa_0
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.10                  py38_0
pytz                      2020.1                     py_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38he774522_0
pyzmq                     18.1.1           py38ha925a31_0
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.0                      py_0
qtconsole                 4.7.4                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.5.14        py38he774522_0
requests                  2.23.0                   py38_0
retrying                  1.3.3                      py_2
rope                      0.17.0                     py_0
rope-py3k                 0.9.4.post1              pypi_0    pypi
rtree                     0.9.4            py38h21ff451_1
scikit-learn              0.22.1           py38h6288b17_0
scipy                     1.4.1            py38h9439919_0
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py38_0
setuptools                46.4.0                   py38_0
sip                       4.19.13          py38ha925a31_0
six                       1.14.0                   py38_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.1.0                    py38_0
sphinx                    3.0.3                      py_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.1.3                    py38_0
spyder-kernels            1.9.1                    py38_0
sqlite                    3.31.1               h2a8f88b_1
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
tk                        8.6.10               he774522_0
toml                      0.10.0             pyh91ea838_0
tornado                   6.0.4            py38he774522_1
tqdm                      4.46.1                     py_0
traitlets                 4.3.3                    py38_0
ujson                     1.35             py38he774522_0
urllib3                   1.25.8                   py38_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
watchdog                  0.10.2                   py38_0
wcwidth                   0.1.9                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.34.2                   py38_0
win_inet_pton             1.1.0                    py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py38he774522_0
xz                        5.2.5                h62dcd97_0
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.4                ha9fde0e_3

Dependencies: 
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

## Versions

* Spyder version: 4.1.3 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-06-27 17:25
This problem should be fixed in our next version (4.1.4), to be released next week. Please update to that version once it's out and open a new issue about this in case the problem is still present.

**Closed by ccordoba12** 2020-06-27 17:25 UTC
