### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by sayounan** [spyder-ide/spyder#16356] opened 2021-09-03 17:59 UTC
**Error message pasted below**

Possible relevant information:

Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro14,3
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 3.1 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 429.140.8.0.0

System Software Overview:

      System Version: macOS 11.5.2 (20G95)
      Kernel Version: Darwin 20.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 8 days 2:36

<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

      Traceback (most recent call last):
      File "runpy.pyc", line 197, in _run_module_as_main
      File "runpy.pyc", line 87, in _run_code
      File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/console/__main__.py", line 23, in 
      start.main()
      File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/console/start.py", line 282, in main
      from ipykernel.kernelapp import IPKernelApp
      File "", line 1007, in _find_and_load
      File "", line 986, in _find_and_load_unlocked
      File "", line 664, in _load_unlocked
      File "", line 627, in _load_backward_compatible
      File "", line 259, in load_module
      File "ipykernel/kernelapp.pyc", line 42, in 
      File "", line 1007, in _find_and_load
      File "", line 986, in _find_and_load_unlocked
      File "", line 664, in _load_unlocked
      File "", line 627, in _load_backward_compatible
      File "", line 259, in load_module
      File "ipykernel/ipkernel.pyc", line 20, in 
      File "", line 1007, in _find_and_load
      File "", line 986, in _find_and_load_unlocked
      File "", line 664, in _load_unlocked
      File "", line 627, in _load_backward_compatible
      File "", line 259, in load_module
      File "ipykernel/debugger.pyc", line 17, in 
      File "", line 1007, in _find_and_load
      File "", line 986, in _find_and_load_unlocked
      File "", line 664, in _load_unlocked
      File "", line 627, in _load_backward_compatible
      File "", line 259, in load_module
      File "debugpy/server/__init__.pyc", line 9, in 
      File "", line 1007, in _find_and_load
      File "", line 986, in _find_and_load_unlocked
      File "", line 664, in _load_unlocked
      File "", line 627, in _load_backward_compatible
      File "", line 259, in load_module
      File "debugpy/_vendored/__init__.pyc", line 18, in 
      NotADirectoryError: [Errno 20] Not a directory:               '/Applications/Spyder.app/Contents/Resources/lib/python39.zip/debugpy/_vendored'

**Comment by ccordoba12** [comment] 2021-09-03 18:03
Hey @sayounan, thanks for reporting. This is a duplicate of issue #16336 and it'll be fixed in our next version (5.1.3), to be released in a couple of days.

**Closed by ccordoba12** 2021-09-03 18:03 UTC
