### ISSUE TITLE
IPython kernel 'no return' problem

### ISSUE THREAD

**Issue by PierrotLC** [spyder-ide/spyder#3087] opened 2016-03-25 17:12 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. type 'a = 2', then 'a' in the iPython console
2. restart the kernel of the same console
3. type 'a = 2'

**What is the expected output? What do you see instead?**

2
Nothing. No return

**Please provide any additional information below**
XCode CLT 7.3 and Theano Git 0.8.0

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 3.5
* Operating system: Mac OSX El Capitan

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below

IPython >=1.0      :  4.0.3 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  3.4.2 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment] 2016-03-25 22:13
Thanks for reporting, this is a duplicate of issue #2696.

**Closed by ccordoba12** 2016-03-25 22:14 UTC
