### ISSUE TITLE
when I update spyder from 4.0.1 to 4.1.0, it show the debug message and I can't use console

### ISSUE THREAD

**Issue by Sola-AIGithub** [spyder-ide/spyder#11843] opened 2020-03-18 03:59 UTC
![1](https://user-images.githubusercontent.com/58946682/76923914-c04e3c00-690f-11ea-9f45-c949a297aad7.PNG)
![2](https://user-images.githubusercontent.com/58946682/76923915-c17f6900-690f-11ea-9af0-4c1d25a2f3c4.PNG)

only I can do is back to the 4.0.1
if I type conda update spyder, it will show the error message again...

**Comment by ccordoba12** [comment] 2020-03-18 04:05
Duplicate of #11819

**Comment by ccordoba12** [comment] 2020-03-18 04:05
We'll fix it in our next version (4.1.1) to be released tomorrow.

**Closed by ccordoba12** 2020-03-18 04:05 UTC
