### ISSUE TITLE
Spyder 4.0.0 hangs when closing file dialogues

### ISSUE THREAD

**Issue by jonbornes** [spyder-ide/spyder#11063] opened 2019-12-13 02:05 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Using either the 'Open', 'Save', 'Save as' or any file dialogue hangs Spyder 4.0.0

### What steps reproduce the problem?

1. Start Spyder
2. Open any file dialogue
3. Either cancel/close or select file/filename and press 'Open' or 'Save'.

### What is the expected output? What do you see instead?
The file dialogue never closes and Spyder 4.0.0 hangs indefinitely.
Loading a file via drag-&-drop works fine. Also Saving via '_ctrl + s_' works fine. All other dialogues/menus work fine.
The internal console does not show any errors except the ever present 
> inotify_add_watch("/home/xxx") failed: "No space left on device"

which is not related but also turns up in a fully working Spyder 3.3.6 setup.
When starting with
> spyder --debug-info verbose --debug-output terminal

Spyder 4.0.0 does not freeze anymore and loads/saves the files as expected while also closing the dialogues correctly. The errors thrown in _verbose_ debug-mode are pasted below where the _sequence_ and _resource id_ differ every time, while _major_ and _minor code_ always stay the same.

### Paste Traceback/Error Below (if applicable)

```python-traceback
QXcbConnection: XCB error: 3 (BadWindow), sequence: 9715, resource id: 35652779, major code: 40 (TranslateCoords), minor code: 0

```

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.4 64-bit (installed via Anaconda (conda): 4.8.0)
* Qt version: 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Ubuntu 18.04 LTS | Linux 4.15.0-72-generic

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2019-12-13 02:12
> inotify_add_watch("/home/xxx") failed: "No space left on device"

Well, that seems the problem. Please free some space in your home and try again.

**Comment by jonbornes** [comment] 2019-12-13 02:15
Unfortunately this does not solve the issue. From my experience it is very much unrelated. I have 160 GB free in my /home/xxx an no quotas. Spyder 3.3.6 also shows the 
> inotify_add_watch("/home/xxx") failed: "No space left on device"

and works just fine.

**Comment by ccordoba12** [comment] 2019-12-13 02:25
I'm sorry but I have no idea what's happening in your case. Therefore I'm going to close this one because triaging issues afterwards is really time consuming.

Please feel free to post more comments in case you can give us more info or narrow down the issue to something we can reproduce in our side.

By the way, I use Linux (Kubuntu 18.10) and Anaconda, and I haven't seen this problem before.

**Closed by ccordoba12** 2019-12-13 02:25 UTC
Labels: status:Awaiting Followup
