### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by linlin98126** [spyder-ide/spyder#5956] opened 2017-12-11 08:40 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "E:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "E:\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "E:\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "E:\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "E:\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "E:\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "E:\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "E:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2404, in l

**Comment by Dan-Patterson** [comment] 2017-12-11 10:34
It got me too... https://github.com/spyder-ide/spyder/issues/5929 downgrade parso

**Comment by CAM-Gerlach** [comment] 2017-12-11 13:27
Thanks for reporting. The error traceback that was posted is apparently incomplete. However, it is very likely a duplicate of e.g. #5673 , an error that's been reported at least a half dozen times just today. As the full error message states, Jedi is only compatible with parso 0.1.0, not, 0.1.1. Therefore, please downgrade to 0.1.0 to fix this, and this issue can be closed. You can also update `jedi` with `conda update jedi` which should also fix it.

**Closed** 2017-12-11 14:59 UTC
