### ISSUE TITLE
Feedback/Improvement: Plot pane resolution is too low and missing matplotlib functionalities

### ISSUE THREAD

**Issue by pj1989** [spyder-ide/spyder#12041] opened 2020-03-30 10:39 UTC
Spyder version: 4.1.1

As per title, the plot quality of the plots in the plots pane is much lower than the quality in the normal matplotlib figure. This seems to be due to the resolution of the plot not getting increased when you scale the plot pane (and I didn't find a way to change the default resolution). 

Here is a small comparison of the same plot with the same dimension in the two version side-by-side

![image](https://user-images.githubusercontent.com/7668531/77901666-4bb8bd00-7280-11ea-9b86-ee1c84665e10.png)

Moreover, in the plot pane there isn't (or I can't find) a way to use matplotlib toolbar commands, such as "pan", "zoom", "configure subplots" and "Edit axes, curves and image parameters". 

My personal opinion is that the Plot pane (despite being a great idea) is not currently usable in its current form due to the two issues above.

**Comment by ccordoba12** [comment] 2020-03-30 16:21
> As per title, the plot quality of the plots in the plots pane is much lower than the quality in the normal matplotlib figure. This seems to be due to the resolution of the plot not getting increased when you scale the plot pane

For this see #9148. We'll try to fix it in one of our next releases but it's tricky because we have to automatically detect and adjust the resolution for high DPI monitors and inform that to the kernel.

> (and I didn't find a way to change the default resolution)

You didn't look hard enough. That option is in

    Tools > Preferences > IPython console > Graphics > Inline backend > Resolution

> Moreover, in the plot pane there isn't (or I can't find) a way to use matplotlib toolbar commands, such as "pan", "zoom", "configure subplots" and "Edit axes, curves and image parameters".

We're not embedding plots generated by an interactive Matplotlib backend in the Plots pane. Instead, we're showing there plots generated by the Inline backend (static png or svg images).

> My personal opinion is that the Plot pane (despite being a great idea) is not currently usable in its current form due to the two issues above.

That's your opinion. If you don't like, don't use it.

----

I'm closing this as a duplicate of #9148 because I think there's nothing else to talk about here.

**Closed by ccordoba12** 2020-03-30 16:21 UTC

**Comment by FRPProject** [comment] 2022-04-21 21:46
Use this to increase the resolution :)

plt.rcParams['figure.dpi'] = 300

Ref: https://blakeaw.github.io/2020-05-25-improve-matplotlib-notebook-inline-res/

**Comment by dragante** [comment] 2023-07-01 10:29
> Use this to increase the resolution :)
> 
> plt.rcParams['figure.dpi'] = 300
> 
> Ref: https://blakeaw.github.io/2020-05-25-improve-matplotlib-notebook-inline-res/

This works perfectly, thanks a lot! :)
