### ISSUE TITLE
Go to definition (right-click or Cmd+G) not working on Mac

### ISSUE THREAD

**Issue by sensharma** [spyder-ide/spyder#8498] opened 2018-12-27 21:00 UTC
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Go to definition (by right-clicking and selecting or with Cmd+G) does not work.

### What steps reproduce the problem?

1. conda install spyder
2. Cmd+G (or right-click and select option)

### What is the expected output? What do you see instead?

Go to definition. No action.

## Versions

* Spyder version: 3.3.2
* Python version: 3.6.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS High Sierra 10.13.6

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.8 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment] 2018-12-28 17:14
Please report what object are trying to inspect its source code with `Cmd+G`.

**Comment by sensharma** [comment] 2019-01-06 00:20
Tried with functions, class methods and class instances. 
I'm facing worse problems now. Auto-completion has stopped functioning (was working when I had raised the issue), changes I had made to the keyboard shortcuts have been reset to defaults, and I can't customise the keyboard shortcuts any longer.

**Comment by ccordoba12** [comment] 2019-01-07 19:55
This is a duplicate of issue #5782 because autocompletion and go to definition are provided by the same libraries.

Please see that issue for possible solutions.

**Closed by ccordoba12** 2019-01-07 19:55 UTC
Labels: status:Awaiting Followup
