### ISSUE TITLE
spyder 3.2 bug

### ISSUE THREAD

**Issue by lnuminer** [spyder-ide/spyder#5845] opened 2017-11-28 06:17 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda3\envs\Tensorflow\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    Traceback (most recent call last):
  File "C:\Anaconda3\envs\Tensorflow\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Anaconda3\envs\Tensorflow\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\Anaconda3\envs\Tensorflow\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 317, in handle_exec_method
    properties = ast.literal_eval(data['text/plain'])
  File "C:\Anaconda3\envs\Tensorflow\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Anaconda3\envs\Tensorflow\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 9001
    ...}
       ^
SyntaxError: unexpected EOF while parsing
handler(msg)
  File "C:\Anaconda3\envs\Tensorflow\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\Anaconda3\envs\Tensorflow\lib

**Comment by CAM-Gerlach** [comment] 2017-11-28 08:21
Thanks for reporting. The error code looks incomplete; if so, can you paste the whole thing? Under what circumstances did this occur? This looks similar to #4873  which is fixed in Spyder 3.2.1—what version of Spyder are you running? 3.2.0? If so, it is almost certainly a duplicate of that error, and so please update to fix.

**Comment by ccordoba12** [comment] 2017-11-29 02:28
Yep, this was fixed already. Please update.

**Closed by ccordoba12** 2017-11-29 02:28 UTC
