### ISSUE TITLE
open .mat with scipy.io.loadmat #2

### ISSUE THREAD

**Issue by elap2** [spyder-ide/spyder#8759] opened 2019-02-12 21:23 UTC
### What steps will reproduce the problem?

I've upgraded the libraries as indicated. How can I verify the .mat file to prevent some reading failure?

thanks 

### Traceback
```python-traceback
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 661, in setup_and_check
    readonly, xlabels, ylabels))
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 540, in __init__
    ylabels=ylabels, readonly=readonly, parent=self)
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 154, in __init__
    self.vmin = np.nanmin(self.color_func(data))
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py", line 305, in nanmin
    res = _copyto(res, np.nan, mask)
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py", line 112, in _copyto
    a = a.dtype.type(val)
AttributeError: 'float' object has no attribute 'dtype'
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.0
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-13 09:19
Duplicate of (your own) issue #8757. Please don't make us waste our time opening the same issue again and wait until we have time to answer you.

**Closed by ccordoba12** 2019-02-13 09:19 UTC
