### ISSUE TITLE
having troubles with "Restart kernel" in IPython console

### ISSUE THREAD

**Issue by bouillonbaptiste** [spyder-ide/spyder#13382] opened 2020-07-25 07:57 UTC
### What steps will reproduce the problem?

Just upgraded from `spyder 4.1.3` to `spyder 4.1.4`

## case 1

```python
import os
```

right click `Console 1/A` in IPython console then `Restart kernel`.
It's working (indeed much slower than with `spyder 4.1.3`)

## case 2

```python
import tensorflow as tf
```
right click `Console 1/A` in IPython console then `Restart kernel`.
It's not working anymore, even after waiting 10 mins.

## case 3

Closing the console will open another one, but this solution is not beautiful.

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.4
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.19.0 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-07-27 18:33
Hey @bouillonbaptiste, thanks for reporting. This is a duplicate of #13336 and it appears to happen only with tensorflow.

**Closed by ccordoba12** 2020-07-27 18:33 UTC
