### ISSUE TITLE
[UX] Pane with tabs don't really need a panel bar

### ISSUE THREAD

**Issue by gagarine** [spyder-ide/spyder#7755] opened 2018-08-23 19:44 UTC
Spyder's pane can be improved to take less space.

![screen shot 2018-08-23 at 21 27 02](https://user-images.githubusercontent.com/164074/44547588-ea338280-a71b-11e8-9843-ff97788fb036.png)

For exemple pysharm pane don't add a pane bar:
![screen shot 2018-08-23 at 21 34 54](https://user-images.githubusercontent.com/164074/44547795-75ad1380-a71c-11e8-8285-d7560203bf24.png)

## Versions

* Spyder version: 3.6
* Operating System name/version:  MacOS

**Comment by jnsebgosselin** [comment] 2018-08-23 20:08
@ccordoba12 related to https://github.com/spyder-ide/spyder/issues/2855

**Comment by ccordoba12** [comment] 2018-08-23 20:14
Sure, we can say this is a duplicate of #2855.

@jnsebgosselin, do you plan to work on that one eventually?

**Closed by ccordoba12** 2018-08-23 20:14 UTC

**Comment by jnsebgosselin** [comment] 2018-08-23 20:43
Yes... but I really don't know when. If someone else could do it, like Daniel for example, that would be great. He already did the work to undock the plugins in new window, so it would be a continuity to his work...

Otherwise it will have to wait for Beta3 I think, after I finish the multi-cursor extension for the editor. This one is hard, so I don't know how long it will take and I want to help you guy make the Beta2 more stable with smaller PR that fix specific issues.

**Comment by ccordoba12** [comment] 2018-08-23 21:11
Don't worry, for beta3 is fine. Unfortunately Daniel is quite busy right now implementing an `ipdb` kernel for our consoles.

**Comment by jnsebgosselin** [comment] 2018-08-24 22:20
This is all good then. It is going to be done eventually then :D

**Comment by jnsebgosselin** [comment] 2018-08-25 16:25
No problem, I see it as a friendly reminder that this needs to be done... :)
