### ISSUE TITLE
Keyboard Shortcut Change Causes Segmentation Fault

### ISSUE THREAD

**Issue by michaelwooley** [spyder-ide/spyder#5517] opened 2017-10-20 15:00 UTC
## Description of your problem

Hello! I just updated to Spyder 3.2.4 and ran into a slight issue when trying to change my keyboard shortcuts. In short, it will appear that the new shortcut is set (a check mark appears) and then you hit enter. At that point a segmentation fault occurs.

When I played around with it a bit more I realized that the segmentation fault won't occur if you "unfocus"/grey out the new shortcut box (by hitting Enter) before clicking "Ok".

Thanks for putting out a great piece of software! Let me know if you have any other questions or if I could help. Michael

**What steps will reproduce the problem?**

1. Open keyboard shortcuts settings: Tools -> Preferences -> Keyboard Shortcuts
2. Double click on action name to open new shortcut dialogue.
3. Enter new shortcut with keyboard.
4. Click "Ok" to exit shortcut editor dialogue box.

**What steps will _not_ reproduce the problem?**

Replace the last two steps from above with:

- 4.' Wait for check mark to appear next to "New Shortcut" input. Press "Enter". (The "New Shortcut" input box background color will switch from white to the dialogue box color [grey-ish?].)
- 5.' Click "Ok" to exit shortcut editor dialogue box.
- 6.' Click "Ok"/"Apply" to save settings and exit the "Preferences" dialogue box.

**What is the expected output? What do you see instead?**

I expect that the dialogue box to close, the program to keep running, and for the new shortcut to work. (Sorry, I know that that is vague but I think it is sort of clear what should happen?)

Instead, when I hit "Ok" in the shortcut editor dialogue box (step 4 above) the program closes and my terminal shows a segmentation fault has occurred.

**Please provide any additional information below**
![spyder_will_crash](https://user-images.githubusercontent.com/8423171/31827448-c6041920-b585-11e7-89c0-bbc1442be446.png)
![spyder_will_not_crash](https://user-images.githubusercontent.com/8423171/31827464-cf969940-b585-11e7-9652-5365e105a56e.png)
![spyder_crash_terminal](https://user-images.githubusercontent.com/8423171/31827466-d1a1935c-b585-11e7-8b48-6acf8eca248c.png)

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.2
* Qt Version: 5.6.3
* PyQt Version: 5.6
* Jupyter Notebook Version: 5.0.0
* Operating system: ubuntu 16.04 LTS

## Dependencies

IPython >=4.0 : 6.1.0 (OK)
cython >=0.21 : 0.26.1 (OK)
jedi >=0.9.0 : 0.10.2 (OK)
nbconvert >=4.0 : 5.3.1 (OK)
numpy >=1.7 : 1.13.1 (OK)
pandas >=0.13.1 : 0.20.3 (OK)
psutil >=0.3 : 5.2.2 (OK)
pycodestyle >=2.3: 2.3.1 (OK)
pyflakes >=0.6.0 : 1.5.0 (OK)
pygments >=2.0 : 2.2.0 (OK)
pylint >=0.25 : 1.7.2 (OK)
qtconsole >=4.2.0: 4.3.1 (OK)
rope >=0.9.4 : 0.10.5 (OK)
sphinx >=0.6.6 : 1.6.3 (OK)
sympy >=0.7.3 : 1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-10-22 21:53
@rlaverde, please take a look at this one.

**Comment by rlaverde** [comment] 2017-10-23 16:55
I'm not able to reproduce this issue, maybe is something gtk-related

**Comment by michaelwooley** [comment] 2017-10-23 17:44
I've heard of GTK but am not familiar with it otherwise. Is there something I could do (e.g. an update) to see if it goes away?

**Comment by ccordoba12** [comment] 2017-11-06 17:25
Closing as a duplicate of issue #5426.

**Closed by ccordoba12** 2017-11-06 17:25 UTC
