### ISSUE TITLE
Spyder crash when saving variables on local machine

### ISSUE THREAD

**Issue by SirBusistan** [spyder-ide/spyder#21632] opened 2023-12-19 08:17 UTC
### What steps will reproduce the problem?

Running a file containing a PyPSA Network and saving the variables locally

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 123, in comm_channel_manager
    yield
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 224, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 435, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 246, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 283, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'b0de185bf1ef41799af31713318ee3b2': (True, None), '4e6f3952500d466ab04a09ff3308358f': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 184, in <lambda>
    triggered=lambda x: self.save_data(),
                        ^^^^^^^^^^^^^^^^
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 494, in save_data
    nsb.save_data()
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 281, in save_data
    error_message = self.shellwidget.save_namespace(self.filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 187, in save_namespace
    timeout=CALL_KERNEL_TIMEOUT).save_namespace(filename)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 222, in _get_call_return_value
    with self.comm_channel_manager(
  File "C:\Users\MariusK\anaconda3\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MariusK\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 127, in comm_channel_manager
    self._comms[comm_id]['comm']._send_channel = (
    ~~~~~~~~~~~^^^^^^^^^
KeyError: '5558f1309e4411eeafcf00f48dc94056'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  3.0.6 (OK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by dalthviz** [comment] 2024-02-14 21:49
Hi @SirBusistan thank you for the feedback and sorry for the late response! I think this seems related/could be a duplicate of https://github.com/spyder-ide/spyder/issues/17199 Basically operations related with the console kernel have a timeout (if an operation takes too much time before giving a response/return it timeouts)

**Closed** 2024-07-06 00:34 UTC
Labels: resolution:Duplicate, component:Variable Explorer, component:IPython Console, status:Awaiting Followup
