### ISSUE TITLE
Spyder doesn't work with QtWebEngine

### ISSUE THREAD

**Issue by TPeterW** [spyder-ide/spyder#3073] opened 2016-03-21 00:09 UTC
## Description of your problem
I tried to launch spyder 3.0.0 beta2 from command line with qt5 installed from homebrew, sip and pyqt5 install from source code and spyder preview installed from pip, when I launched it, the error log said

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/spyderlib/spyder.py", line 3119, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/lib/python3.5/site-packages/spyderlib/spyder.py", line 3005, in run_spyder
    main.setup()
  File "/usr/local/lib/python3.5/site-packages/spyderlib/spyder.py", line 822, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/local/lib/python3.5/site-packages/spyderlib/plugins/console.py", line 79, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/local/lib/python3.5/site-packages/spyderlib/widgets/findreplace.py", line 250, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/local/lib/python3.5/site-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage, QWebView      # analysis:ignore
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/PyQt5/QtWebKitWidgets.so, 2): Library not loaded: /usr/local/opt/qt5/lib/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
  Referenced from: /usr/local/lib/python3.5/site-packages/PyQt5/QtWebKitWidgets.so
  Reason: image not found

* Spyder Version: 3.0.0 beta2
* Python Version: 3.5.1
* Operating system: OS X 10.11 El Cap

**Comment by ccordoba12** [comment] 2016-03-21 13:31
This is probably caused because the latest Qt5 version (5.6) deprecated the QtWebKit module in favor of QtWebEngine.

This problem will be fixed in beta3.

**Comment by TPeterW** [comment] 2016-03-21 13:33
Yeah, it worked again when I downgraded qt5 back to 5.5.1-2

**Closed** 2016-06-05 04:31 UTC
Labels: Type-Bug, Type-Maintainability

**Comment by rdsalemi** [comment] 2016-06-29 12:31
I'm seeing this issue today. 

I ran the following commands

     %  conda update qt pyqt
     %  conda install -c spyder-ide spyder=3.0.0b3
     %  spyder

Get this result: 

      Traceback (most recent call last):
      File "/Users/raysalemi/anaconda/bin/spyder", line 3, in <module>
       start.main()
     File "/Users/raysalemi/anaconda/lib/python2.7/site-packages/spyderlib/app/start.py", line 118, in main
    from spyderlib.app import spyder
     File "/Users/raysalemi/anaconda/lib/python2.7/site-packages/spyderlib/app/spyder.py", line 91, in    <module>
       from qtpy import QtWebEngineWidgets
     File "/Users/raysalemi/anaconda/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 32, in <module>
       from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
     ImportError: dlopen(/Users/raysalemi/anaconda/lib/python2.7/site-packages/PyQt5/QtWebKitWidgets.so, 2): Library not loaded: @rpath/./libQt5WebKitWidgets.5.dylib
     Referenced from: /Users/raysalemi/anaconda/lib/python2.7/site-packages/PyQt5/QtWebKitWidgets.so
     Reason: image not found

It looks like this bug may still exist.

**Comment by ccordoba12** [comment] 2016-06-29 14:23
This is caused by another problem. We're discussing about it in #3267.

**Comment by rdsalemi** [comment] 2016-06-29 16:27
Thanks for the pointer.  I'm over there now.
