### ISSUE TITLE
Crash when using turtle graphics in Spyder (Python 3.9)

### ISSUE THREAD

**Issue by bphusted** [spyder-ide/spyder#16885] opened 2021-11-22 14:13 UTC
### What steps will reproduce the problem?

I am using a freshly installed Anaconda 3 (64 bit).
Spyder IDE 5.1.5
Python 3.9.7 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10 

When I run this code below, it crashes. I have tried using different graphics setup in preferences, -> Ipython console -> Graphics -> Graphics backend, but it all leads to an crash. I an older installation of spyder (5.0.5) using python 3.8.8 it runs without any error, also when doing repeating runs.

The error is:
**Tcl_AsyncDelete: async handler deleted by the wrong thread**

The code to reproduce the problem is below:
import turtle

screen1 = turtle.Screen()
screen1.setup(800, 600)  # Dimensions

tu = turtle.Turtle('square', visible=False)
tu.color('black', 'white')  # pencolor, fillcolor
tu.penup()
tu.stamp()

screen1.mainloop()

turtle.bye()

**Comment by steff456** [comment] 2021-11-22 22:07
Hi @bphusted,

I couldn't reproduce the crash of Spyder in my end, but the new window do freezes. I tried your code in a Python interpreter outside Spyder and the same behavior appears, so maybe you have an error in your code. If you have another snippet I could try to get the same error you are experiencing please let me know.

**Comment by bphusted** [comment] 2021-11-24 14:58
Hi @steff456
I do not have another snippet. I now went back to using an earlier release of python (python 3.8.8) were the problem does not occur. I think the problem is related to how the memory is freed, when the turtle window is closed, but I must admit that I do not fully understand, what is going on. 
Doing a search on the problem, - brought up a number of pages, but no of them had a good explanation.

**Comment by steff456** [comment] 2021-11-24 23:26
Ok, so for now I'm going to close this issue. If you see a pattern, please re-open this issue and post the case here to see if we can dig into the issue.

Thanks a lot for opening this!

**Closed by steff456** 2021-11-24 23:26 UTC
Labels: status:Awaiting Followup
