### ISSUE TITLE
Can not start spyder

### ISSUE THREAD

**Issue by yanyu2015** [spyder-ide/spyder#16908] opened 2021-11-28 09:45 UTC
version 5.1.5

```
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "D:\DataScience\PythonSet\IDES\Anacondanew\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\app\start.py", line 237, in main
    mainwindow.main(options, args)
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\app\mainwindow.py", line 1992, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\app\utils.py", line 292, in create_window
    main.post_visible_setup()
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\app\mainwindow.py", line 1222, in post_visible_setup
    self.projects.reopen_last_project()
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\plugins\projects\plugin.py", line 578, in reopen_last_project
    self.open_project(path=current_project_path,
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\plugins\projects\plugin.py", line 433, in open_project
    project_type_class = self._load_project_type_class(path)
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\site-packages\spyder\plugins\projects\plugin.py", line 864, in _load_project_type_class
    config.read(fpath)
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "D:\DataScience\PythonSet\IDES\Anacondanew\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 185: illegal multibyte sequence

```
It seems I copy a existed project and I can be open, however，after closimng， when reopen it ，the spyder crashed(the windows can be show and after seconds it disappears).

**Comment by yanyu2015** [comment] 2021-11-29 01:22
additional remarks:
I have checked that the path(not project name) of project which has chinese may cause this problem.

**Comment by steff456** [comment] 2021-11-29 18:29
Hi @yanyu2015,

Can you walk me through the process to see if I can reproduce this on my end? It is highly probable that chinese characters are causing this problem. Did this work in previous versions?

**Comment by yanyu2015** [comment] 2021-11-30 02:05
1 create a directory whose name is yanyu, its path is `D:\example\测试\yanyu\`
2 create project with this existed directory
3 create py file in this project,such as `bug复现.py`
4 write some code
5 cloase the spyder
6 reopen spyder，then this problem appears( windows is open but after some second it close automatically).
   you can also use anaconda prompt and type `spyder` in order to see details.

This work in previous versions which is `version  4.2.5`

**Comment by yanyu2015** [comment] 2021-12-02 02:40
can you explain the meaning of this command
```
conda create -n spyder-env -c conda-forge spyder python=3.8
```
so I need to substitute `3.8` to `3.9`?(my python of anaconda is 3.9)
```
you'll always need to run the last two commands to start 5.2.0
```
is there something wrong? is `5.2.0` really `right now version`?
I need to confirm for fear that it disturb my normal work again.

**Comment by ccordoba12** [comment] 2021-12-03 18:29
> can you explain the meaning of this command

That command will install the latest version of Spyder (5.2.0) in a new environment (i.e. an isolated Python installation) from the Conda-forge channel, i.e. a set of conda packages maintained by the community (not Anaconda) which is much more up to date.

> so I need to substitute 3.8 to 3.9?(my python of anaconda is 3.9)

Yes, you can change `python=3.8` to `python=3.9` if you prefer to do it.

> is there something wrong? is 5.2.0 really right now version?

5.2.0 is the version that contains the fix for the problem you reported here. The thing is that lately it takes several months for the Anaconda team to update Spyder, so we have to advice people to use Conda-forge instead if they want to use our latest version.

> I need to confirm for fear that it disturb my normal work again.

I understand and don't worry, you won't break your Anaconda installation by following the instructions I posted above. That's the beauty of [conda environments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html): they are totally isolated.

**Comment by yanyu2015** [comment] 2021-12-04 10:45
You are so kind ,and It seems work well. Howvere, this version of python doesn‘t have lots of packages. I am confuse of installing new version of spyder and connect it with current anaconda which has been installed.

**Comment by ccordoba12** [comment] 2021-12-04 14:15
> I am confuse of installing new version of spyder and connect it with current anaconda which has been installed.

That's the next step you need to do so you don't need to install everything again in your environment. To learn how to connect this new Spyder to your previous environment, please read this FAQ in our docs:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by yanyu2015** [comment] 2021-12-05 09:07
sorry to tell you a bad message.
after I change the interpreter as follew.
![image](https://user-images.githubusercontent.com/11142054/144740427-49fb91b0-0ec3-49c7-a38c-f5064f8a2986.png)

this version of spyder also has a error.
```
(spyder-env) C:\Users\xuanQS>spyder
QWindowsWindow::setGeometry: Unable to set geometry 2520x1480+32+66 (frame: 2542x1536+21+21) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY4". Resulting geometry: 2520x1050+32+66 (frame: 2542x1106+21+21) margins: 11, 45, 11, 11 minimum size: 384x362 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=790,780 maxtrack=0,0)
Traceback (most recent call last):
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\app\start.py", line 237, in main
    mainwindow.main(options, args)
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\app\mainwindow.py", line 2036, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\app\utils.py", line 300, in create_window
    main.post_visible_setup()
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\app\mainwindow.py", line 1232, in post_visible_setup
    projects.reopen_last_project()
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\projects\plugin.py", line 616, in reopen_last_project
    self.open_project(path=current_project_path,
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\projects\plugin.py", line 514, in open_project
    self.restart_consoles()
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\projects\plugin.py", line 708, in restart_consoles
    self.ipyconsole.restart()
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 803, in restart
    self.get_widget().restart()
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1822, in restart
    self.close_client(client=client, ask_recursive=False)
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1746, in close_client
    client.shutdown(last_client)
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 585, in shutdown
    self.shellwidget.shutdown(shutdown_kernel)
  File "D:\DataScience\PythonSet\IDES\anaconda\envs\spyder-env\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 176, in shutdown
    self.kernel_manager.stop_restarter()
AttributeError: 'NoneType' object has no attribute 'stop_restarter'
```
windows can be open but close automatically

**Comment by ccordoba12** [comment] 2021-12-06 05:16
I think that happens because you don't have Spyder-kernels 2.2.0 in your base environment. Unfortunately, you won't be able to install it until Anaconda releases a package for it (you can't install is using conda-forge or pip because it'll break your installation).

So you can either all packages you need in your `spyder-env` environment or wait until Anaconda upgrades Spyder to 5.2.0 to start using it. If you go for the first option, you need to close Spyder, open the Anaconda prompt and run the following commands

    conda activate spyder-env
    conda install -c conda-forge pandas matplotlib <any other package that you need>

**Comment by ccordoba12** [comment] 2021-12-06 05:17
I'm going to close this issue because there's nothing else we can do in our side.

**Closed by ccordoba12** 2021-12-06 05:17 UTC
Labels: status:Awaiting Followup

**Comment by yanyu2015** [comment] 2021-12-06 09:16
Thank you again,I understand why I was strictly operating, but wasn't able to successfully switch python versions, and it boils down to poor compatibility support for anaconda.
