### ISSUE TITLE
Editor line number font size does not increase as you increase the code font size on Mac system

### ISSUE THREAD

**Issue by febtree** [spyder-ide/spyder#2397] opened 2015-05-04 02:19 UTC
## Description

* *What steps will reproduce the problem?*
1. Increase the code editor font size on preference panel -> Editor -> Font

* *What is the expected output? What do you see instead?*
Code font size will increase, and line number size should increase at the same time.
but it doesn't, which leads to the result that the line number and the corresponding line don't match.

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Mac OSX

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment] 2015-05-04 23:24
@goanpeca, would you mind to take a look at this one, given that you were the last one to work with the line number area?

**Comment by ccordoba12** [comment] 2015-06-01 14:37
@goanpeca, please try to solve this soon. I'd like to include it in 2.3.5 (to be ready in two weeks or so :-)

**Comment by goanpeca** [comment] 2015-06-01 14:45
Hmmm this is going to be tricky cause at this point it seems to be a Mac related issue and hmm I do not have a mac!

**Comment by ccordoba12** [comment] 2015-06-01 14:48
Right, this is not an issue with fonts. It's just a duplicate of issue #2296.

**Closed by ccordoba12** 2015-06-01 14:48 UTC
Labels: bug, duplicate, Editor
