### ISSUE TITLE
Spyder error

### ISSUE THREAD

**Issue by AldoMaine** [spyder-ide/spyder#5644] opened 2017-11-02 14:10 UTC
## Description
Get this weird error when running scripts.

**Please provide any additional information below**
Windows 7 64bit
Running in iPython console in Spyder

  File "C:\Users\username\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: need more than 1 value to unpack

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-11-02 20:14
Thanks for reporting. This is a duplicate of issue #5080.

**Closed by ccordoba12** 2017-11-02 20:14 UTC
