### ISSUE TITLE
google docstrings in help window

### ISSUE THREAD

**Issue by peendebak** [spyder-ide/spyder#6371] opened 2018-02-02 15:21 UTC
Methods with a google style docstring will not render properly in the help window if it is set to rich text.

What can I do to add support for this in spyder?

Also see #2046

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2018-02-02 15:55
Let's merge this as a duplicate of #2046. We're aware of this limitation and we'll try to solve it in the future. When? Hard to say while we continue unfunded, sorry.

**Closed by ccordoba12** 2018-02-02 15:55 UTC

**Comment by CAM-Gerlach** [comment] 2018-02-03 01:55
> What can I do to add support for this in spyder?

We're always happy to get pull requests from new contributors, and since Spyder is written in the very same Python language you write your programs in, it shouldn't be too hard to get started. Thanks for your interest! Also, you can help support us at [OpenCollective](https://opencollective.com/spyder) to help fund continued development.
