### ISSUE TITLE
Folding code

### ISSUE THREAD

**Issue by bigO6377** [spyder-ide/spyder#2928] opened 2016-01-14 20:09 UTC
Hi, is there a way to collapse code blocks (like function definitions, classes, long if-statements, etc.)?  I currently have Spyder 3.0.0dev.

**Comment by ccordoba12** [comment] 2016-01-14 20:29
Nop, there is no way to do it currently. But we hope to have code folding before 3.0 is finally released.

**Comment by ccordoba12** [comment] 2016-01-14 20:30
By the way, this issue is a duplicate of issue #706, so I'm closing it.

**Closed by ccordoba12** 2016-01-14 20:30 UTC
