### ISSUE TITLE
"Preferences" high DPI problems (Spyder 6.0.0, 2560x1600)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#22455] opened 2024-09-06 22:08 UTC
Nothing important to me, just FYI.

### 1. Trimmed side-bar, no way to un-trim

![image](https://github.com/user-attachments/assets/d694adbd-0a23-4a50-bda4-4ac3eedf9af7)

### 2. Editor -> Display is squeezed (but can unsqueeze by expanding vertically)

![image](https://github.com/user-attachments/assets/f5903ce5-64e9-49cb-abc6-8113db1ddcfe)

### 3. Appearance -> Preview is trimmed

![image](https://github.com/user-attachments/assets/e79adfa2-b797-4267-8e39-c1ee93c52748)

**Comment by ccordoba12** [comment] 2024-09-06 23:28
After activating your environment in a Anaconda Prompt, please run

    set QT_AUTO_SCREEN_SCALE_FACTOR=1

and then start Spyder as usual.

Let us know if that fixes the error for you.

**Comment by OverLordGoldDragon** [comment] 2024-09-06 23:37
This seems to mimic `Enable auto high DPI scaling` (in `Preferences > Application > Interface > Screen resolution`). It fixes everything I mentioned, but also makes everything oversized.

![image](https://github.com/user-attachments/assets/cb1ad170-2373-4a2a-8cbe-97e980cfffde)

![image](https://github.com/user-attachments/assets/c8f2359e-0b49-4eda-9cfd-bce898d17c02)

**Comment by ccordoba12** [comment] 2024-09-06 23:50
But I think that's how Spyder should look (I don't have a high DPI screen to test). Could you post a screenshot with another Windows application next to it to compare?

Also, if you want to decrease the application font size, you can do that in `Preferences > Appearance > Fonts > Interface`.

**Comment by OverLordGoldDragon** [comment] 2024-09-07 00:14
Hmm, the UI certainly feels bloated to me, over-padded, relative to other apps also. Here's vs Github Desktop

![image](https://github.com/user-attachments/assets/17cc56dd-88db-4d51-8c43-7a74120e0204)

That's the thickest scrollbar I've seen in 2024. 

Everything's also significantly bloated relative to what I recall with non-high DPI monitor. If all this is intended... well, it's certainly not for me, but I did find what works for me.

**Comment by ccordoba12** [comment] 2024-09-07 00:58
> Everything's also significantly bloated relative to what I recall with non-high DPI monitor.

That's the design we decided to implement in Spyder 5 for accessibility reasons. We'll try to provide a slimmer design in the future.

> If all this is intended... well, it's certainly not for me, but I did find what works for me.

Ok, we don't have a problem if you want to use Spyder in normal DPI mode. But that also means that this is not a bug because you're choosing not to use Spyder with high DPI enabled in a high resolution screen.

In addition, I don't think there's a simple way to solve this problem from the technical point of view (heck, I don't even know if it's doable at all). So, I'm going to close this issue.

**Closed by ccordoba12** 2024-09-07 00:58 UTC
Labels: status:Awaiting Followup

**Comment by OverLordGoldDragon** [comment] 2024-09-07 22:33
Fair enough. Just as FYI, maybe not a bug, but # 2 in my OP is at least anomalous, I've not seen other Spyder UI elements behave this way. (Reproduced only without auto high DPI)

**Comment by ccordoba12** [comment] 2024-09-08 05:18
> Just as FYI, maybe not a bug, but # 2 in my OP is at least anomalous, I've not seen other Spyder UI elements behave this way. (Reproduced only without auto high DPI)

Could you post a screenshot about that?

**Comment by OverLordGoldDragon** [comment] 2024-09-08 05:31
By "# 2 in OP" I meant this in the original post (image right below it)

 > 2. Editor -> Display is squeezed (but can unsqueeze by expanding vertically)

and by "Display" I mean the "Display" section

**Comment by ccordoba12** [comment] 2024-09-09 01:54
Ok, could post a screenshot with high DPI enabled that shows the Editor preferences page squeezed and unsqueezed?

**Comment by OverLordGoldDragon** [comment] 2024-09-09 22:20
No problem with high DPI enabled.
