### ISSUE TITLE
Python 3.7, Spyder 3.32  Failure On MAC

### ISSUE THREAD

**Issue by GeorgeJub** [spyder-ide/spyder#8694] opened 2019-02-03 02:27 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Cant access a variable in variable explorer. An error message pops saying Spyder encountered an internal problem

### What steps reproduce the problem?

1. everytime I try to access an array variable this mesage pops 
2. 
3. 

### What is the expected output? What do you see instead?

I can see the variable in the output console but not in the variable explorer wondow. 

### Paste Traceback/Error Below (if applicable)

 FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/georgejubran/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
```python-traceback

PASTE TRACEBACK HERE
File "/Users/georgejubran/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/Users/georgejubran/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
![python-spyder error screen shot](https://user-images.githubusercontent.com/47254991/52171784-d868f900-2717-11e9-8c21-fe95fb7f0fee.png)
![x array in output console](https://user-images.githubusercontent.com/47254991/52171813-31d12800-2718-11e9-9ab9-2d8a0ad377e6.png)
![python-spyder error screen shot](https://user-images.githubusercontent.com/47254991/52171814-3564af00-2718-11e9-89e8-dff1636da8de.png)



```

## Versions

* Spyder version: 3.32
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: OSC10.11.6

### Dependencies

pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.5.0 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2019-02-03 09:15
Duplicate of #8692. Please don't open the same issue again.

**Closed by ccordoba12** 2019-02-03 09:15 UTC
