### ISSUE TITLE
Console problem

### ISSUE THREAD

**Issue by FelipeGarridoM** [spyder-ide/spyder#9475] opened 2019-05-30 16:41 UTC
### What steps will reproduce the problem?

I click anywhere on the console and this pops up...

### Traceback
```python-traceback
  File "/anaconda3/envs/my_env2/lib/python3.6/site-packages/qtconsole/console_widget.py", line 428, in eventFilter
    event.button() == QtCore.Qt.MidButton and \
AttributeError: 'QContextMenuEvent' object has no attribute 'button'
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-05-30 16:46
Thanks for reporting. @goanpeca, can you reproduce it on macOS?

**Comment by goanpeca** [comment] 2019-05-30 20:15
>can you reproduce it on macOS?

No sir

**Comment by ccordoba12** [comment] 2019-05-31 09:51
@FelipeGarridoM, this is very odd and we don't know how to help you.

Could you install Spyder in new conda environment and try again? Thanks!

**Comment by ccordoba12** [comment] 2019-06-10 08:23
Closing because we were unable to reproduce this, sorry.

**Closed by ccordoba12** 2019-06-10 08:23 UTC
Labels: status:Awaiting Followup
