### ISSUE TITLE
Crash while working with CustomBusinessDay

### ISSUE THREAD

**Issue by gflores87** [spyder-ide/spyder#6417] opened 2018-02-08 13:32 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 516, in createEditor
    readonly=readonly)
  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1327, in setup
    remote=remote)
  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1275, in __init__
    title)
  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1152, in __init__
    minmax=minmax)
  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 110, in __init__
    self.set_data(data)
  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 158, in set_data
    self.set_size_and_type()
  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 178, in set_size_and_type

**Comment by ccordoba12** [comment] 2018-02-08 14:25
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by gflores87** [comment] 2018-02-08 15:08
Hi,

I'm working with a holidays calendar and tried to open an unsupported type in the variable explorer. So it is natural for spyder to crash. You can mark it as closed. Sorry for the trouble

**Comment by CAM-Gerlach** [comment] 2018-02-09 00:44
Thanks for the response. Well, I suppose from one point of view, but the error should be handled more gracefully, i.e. by either not opening an editor, poping up a proper message dialog, or actually working around it if easily fixable. If you can provide us with the full traceback (the above version is cut off, a known problem with certain browsers that will be fixed in the next version of Spyder), and perhaps some code to easily replicate it, then we can try to do that. Thanks!

**Comment by CAM-Gerlach** [comment] 2018-02-17 18:44
Closed due to lack of response and user request.

**Closed by CAM-Gerlach** 2018-02-17 18:44 UTC
Labels: component:Variable Explorer, severity:4-Low, status:Awaiting Followup
