### ISSUE TITLE
Automatic selection Interpeter 

### ISSUE THREAD

**Issue by Leohanhart** [spyder-ide/spyder#22109] opened 2024-05-21 20:25 UTC
Dear Reader, 

Could it be possible to add a function that when you switch projects, the python interpeter switchs automaticly. 

Best regards, 
Leo Hanhart

**Comment by dalthviz** [comment] 2024-08-23 23:29
Hi @Leohanhart thank you for the feedback! I think this is related with https://github.com/spyder-ide/spyder/issues/11362 and indeed is something that we are aiming to implement for a future Spyder release. Just in case, as a workaround for this, in the upcoming major version release (Spyder 6) a menu to launch a console using a specific interpreter/environment will be available (for more info you can check https://github.com/spyder-ide/spyder/pull/20421 and https://github.com/spyder-ide/spyder/pull/22200)

Let us know if the info above helps!

**Comment by Leohanhart** [comment] 2024-08-25 10:14
@dalthviz I dont know to be fair. But very nice that you are picking this up. It will save me a lot of time and hedic. 
- Is there already clarity about when the Yupiter notebook outlook will be available for all users?

**Comment by dalthviz** [comment] 2024-08-27 21:45
> I dont know to be fair. But very nice that you are picking this up. It will save me a lot of time and hedic.

If you want to try the envs menu functionality mentioned above [you could wait a little bit for Spyder 6 to be released](https://github.com/spyder-ide/spyder/issues/22378) or you can check [Spyder 6rc2](https://github.com/spyder-ide/spyder/releases/tag/v6.0.0rc2) 

> Is there already clarity about when the Yupiter notebook outlook will be available for all users?

You mean like being able to use [the spyder-notebook plugin](https://github.com/spyder-ide/spyder-notebook)? If that is the case, I think you should be able to use it if you install Spyder 5 and then spyder-notebook package via pip or conda. We still need to check a way to install plugins with Spyder from the installers. Also, I think there are some changes/release needed for the plugin to be [compatible with Spyder 6](https://github.com/spyder-ide/spyder-notebook/issues/456) 🤔 

Or maybe you were referring to something else? Let us know!

**Comment by dalthviz** [comment] 2024-11-06 23:43
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/11362

**Closed by dalthviz** 2024-11-06 23:43 UTC
Labels: resolution:Duplicate, component:Projects, component:IPython Console, status:Awaiting Followup
