### ISSUE TITLE
Can't use apostrophe in a keyboard shortcut

### ISSUE THREAD

**Issue by joshburnett** [spyder-ide/spyder#2495] opened 2015-06-20 02:02 UTC
## Description

*Steps to reproduce the problem:*

1. Open up preferences
2. Go to the Keyboard Shortcuts section
3. Set 'Editor: Toggle comment' to Cmd + Apostrophe
4. Click OK
5. Go to the editor, press Cmd+Apostrophe

The line with the cursor should toggle between commented and un-commented status.  Instead, nothing happens.

With the default keyboard shortcut of Cmd+1, the desired behavior occurs.

## Additional information
Also tested on Windows w/ Control+Apostrophe, which does not work either.

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.10
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.3   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

**Comment by joshburnett** [comment] 2015-06-20 02:11
Looks like issue #478 needs to be fixed first.

**Comment by ccordoba12** [comment] 2015-07-12 22:30
This is basically a duplicate of issue #478, which was already solved :-)

**Closed** 2015-07-12 22:31 UTC
Labels: duplicate
