### ISSUE TITLE
Scrollbar not displaying correctly

### ISSUE THREAD

**Issue by ajayrathore** [spyder-ide/spyder#6806] opened 2018-03-20 21:25 UTC
## Problem Description
Scroll bar seems very weird in spyder 3.2.8. I can see a double looking scroll bar in the code editor on both macOSand windows 

### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.8
* Python: 3.6
* Qt:
* PyQt:
* Operating System: MacOS and Windows
![capture](https://user-images.githubusercontent.com/1130197/37683660-3cc19efe-2c85-11e8-98b3-6bdbe5456036.PNG)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2018-03-20 22:11
Thanks for reporting. This was already fixed and it'll be part of Spyder 4, to be released in a year or less.

**Closed by ccordoba12** 2018-03-20 22:11 UTC

**Comment by jnsebgosselin** [comment] 2018-03-20 22:46
Duplicate of Issue https://github.com/spyder-ide/spyder/issues/5085 that was fixed by PR https://github.com/spyder-ide/spyder/pull/5215
