### ISSUE TITLE
Seemingly random error

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#14207] opened 2020-11-12 20:15 UTC
### What steps will reproduce the problem?

Seemingly random error popped up out of nowhere...

### Traceback
```python-traceback
  File "C:\Users\Amin\Anaconda3\lib\site-packages\spyder\plugins\completion\snippets\actor.py", line 92, in handle_msg
    if language_snippets[current_word]:
  File "C:\Users\Amin\Anaconda3\lib\site-packages\spyder\plugins\completion\snippets\trie.py", line 81, in __getitem__
    if len(sequence) == 0:
TypeError: object of type 'NoneType' has no len()
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.5.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.5.3 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.2.0.post20200714 (OK)
sphinx >=0.6.6                  :  3.1.2 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.1 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.2.2 (OK)
numpy >=1.7                     :  1.18.5 (OK)
pandas >=1.1.1                  :  1.0.5 (NOK)
scipy >=0.17.0                  :  1.5.0 (OK)
sympy >=0.7.3                   :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-11-13 02:57
Thanks for reporting @ma-sadeghi. This is a duplicate of #14183 and we'll fix it on our next release.

**Closed by ccordoba12** 2020-11-13 02:57 UTC
