### ISSUE TITLE
file is not open

### ISSUE THREAD

**Issue by rajesh016** [spyder-ide/spyder#5910] opened 2017-12-07 05:30 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\pooja singh\ana\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\Users\pooja singh\ana\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined
Traceback (most recent call last):
  File "C:\Users\pooja singh\ana\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\Users\pooja singh\ana\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0

**Comment by CAM-Gerlach** [comment] 2017-12-07 06:33
Thanks for reporting. This is a duplicate of #5061 , and occurs because `numpy` is not installed in your enviroment. To resolve it (i.e. to view a `numpy` array in variable explorer), you need to install `numpy` (and possibly `pandas`, if you want dataframes). Therefore, this issue should be closed.

**Closed** 2017-12-07 14:08 UTC
