### ISSUE TITLE
issue in seaborn

### ISSUE THREAD

**Issue by YuvanPrakashM** [spyder-ide/spyder#14589] opened 2021-01-14 14:21 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>i have an error in seaborn which is i get 'no module named as seaborn'(after the installation of seaborn via pip).kindly help with the issue

**Comment by ccordoba12** [comment] 2021-01-14 15:07
Duplicate of #14590.

**Closed by ccordoba12** 2021-01-14 15:07 UTC
