### ISSUE TITLE
missing dependencies spyder_kernels on startup,but i have this model.

### ISSUE THREAD

**Issue by cailongli** [spyder-ide/spyder#15132] opened 2021-04-06 03:28 UTC
### What steps will reproduce the problem?

---------------------------
Error
---------------------------
<b>You have missing dependencies!</b><br><br><tt><br># Mandatory:<br>spyder_kernels >=2.0.1,&lt;2.1.0 :  2.0.1 (NOK)<br></tt><br><b>Please install them to avoid this message.</b><br><br><i>Note</i>: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we <i>strongly</i> recommend you to install all the listed missing dependencies.<br><br>Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.
---------------------------
OK   
---------------------------

**Comment by ccordoba12** [comment] 2021-04-06 03:42
Hey @cailongli, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version.

**Closed by ccordoba12** 2021-04-06 03:42 UTC
