### ISSUE TITLE
os._exit(1) causes kernel crash

### ISSUE THREAD

**Issue by JonathanBlixt** [spyder-ide/spyder#11970] opened 2020-03-25 09:54 UTC
### What steps will reproduce the problem?

import os
os._exit(1)

Erasing this call made the code run properly again.

### Traceback
```python-traceback
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\_pswindows.py", line 716, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\_pswindows.py", line 935, in create_time
    return cext.proc_create_time(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\__init__.py", line 473, in _init
    self.create_time()
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\__init__.py", line 823, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=4380)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\manager.py", line 361, in restart_kernel
    self.shutdown_kernel(now=now, restart=True)
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\manager.py", line 321, in shutdown_kernel
    self._kill_kernel()
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 78, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 44, in kill_proc_tree
    parent = psutil.Process(pid)
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\__init__.py", line 446, in __init__
    self._init(pid)
  File "C:\Users\SETUJBAA\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\__init__.py", line 486, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 4380
WARNING:traitlets:kernel died: 45.00793647766113
WARNING:traitlets:kernel died: 45.00542855262756
WARNING:traitlets:kernel died: 45.005892515182495
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.6.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.8.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.1.2 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.12 (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  0.24.2 (OK)
scipy >=0.17.0                 :  1.2.1 (OK)
sympy >=0.7.3                  :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-25 11:28
Duplicate of #11872

**Closed by ccordoba12** 2020-03-25 11:28 UTC
