### ISSUE TITLE
Feature Request: Embed Kite Sidekick In Spyder

### ISSUE THREAD

**Issue by dbirdflyshi** [spyder-ide/spyder#11029] opened 2019-12-11 20:22 UTC
Instead of having a window show what's going on, is it possible to have it show up in spyder itself somewhere like a tab next to Help, Variable Explorer, Plots, and Files. Maybe an enhancement to help since help doesnt always have what you need.

**Comment by bcolsen** [comment] 2019-12-11 21:30
That's going to be too difficult unfortunately.

Closing as a duplicate of #10904

**Closed by bcolsen** 2019-12-11 21:30 UTC
