### ISSUE TITLE
Menus aren't displayed properly

### ISSUE THREAD

**Issue by bsumlin** [spyder-ide/spyder#15669] opened 2021-05-21 18:37 UTC
### What steps will reproduce the problem?

Open a menu that has icons alongside text. Icons will overlap text.

**Comment by bsumlin** [comment] 2021-05-21 18:38
![sypderBug](https://user-images.githubusercontent.com/30328179/119183487-29649e80-ba42-11eb-8d65-1f0df38ce798.PNG)

Screenshot of the issue.

**Comment by juanis2112** [comment] 2021-05-21 18:47
Hi @bsumlin thanks for reporting this. This issue is a duplicate of #15404  and was fixed in Spyder 5.0.1. Unfortunately it is not available in Anaconda yet. You can download it from our standalone installers https://www.spyder-ide.org/#section-download

**Closed** 2021-05-21 18:48 UTC
