### ISSUE TITLE
I'm not entirely sure what went wrong! this dialouge box just popped up!

### ISSUE THREAD

**Issue by MiiKaa3** [spyder-ide/spyder#13943] opened 2020-10-07 12:51 UTC
### What steps will reproduce the problem?

I copied pasted this code: 
https://raw.githubusercontent.com/jonnyhyman/Chaos/master/logistic_interactive.py

and ran it. Installed the one package i need to run the code, and then saved the .py file into a seperate directery (I was getting an error related to the fact that the program wasn't saved) and then ran again, before receiving the error message

### Traceback
```python-traceback
  File "C:\Users\mkasu\anaconda3\lib\site-packages\spyder\plugins\editor\utils\editor.py", line 161, in _exec_requested_job
    self._job(*self._args, **self._kwargs)
  File "C:\Users\mkasu\anaconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 451, in _highlight_block
    end_line = self.folding_regions[block_line]
KeyError: 226
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.4.1 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.5.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.10 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.4 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  3.0.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.17 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.5 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by dalthviz** [comment] 2020-10-08 05:23
Hi @MiiKaa3 seems like this is a duplicate of #13779 . Also, seems like you aren't using our latest version (`4.1.5`). In case you want, to update, you can run something like `conda install spyder=4.1.5` from an Anaconda prompt.

**Closed by dalthviz** 2020-10-08 05:23 UTC
Labels: resolution:Duplicate
