### ISSUE TITLE
Would it be possible to use Spyder with a kernel in a different language (Julia)?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [spyder-ide/spyder#12766] opened 2020-05-16 14:49 UTC
The IDE is great. I've used it with my Python projects. Hence, I can see how attractive it might be not to have to switch IDEs when switching languages.

**Comment by goanpeca** [comment] 2020-05-17 23:07
Hi @PetrKryslUCSD, thanks for your suggestion.

Updating Spyder internals to provide easier and better support for additional languages will como for Spyder5 and that work should be available to test (on master) in some 4-6 months.

This issues seems to be a duplicate of #1976, so I am closing in favor of that one.

Cheers!

**Closed by goanpeca** 2020-05-17 23:07 UTC
