### ISSUE TITLE
Windows Spyder: taskbar duplication error

### ISSUE THREAD

**Issue by jihoon90** [spyder-ide/spyder#2297] opened 2015-04-02 16:17 UTC
## Description

* *What steps will reproduce the problem?*
1. When I execute the spyder, it generates another tab in the taskbar.
2.
3.

* *What is the expected output? What do you see instead?*
They should be on the same icon like the other programs

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.8
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.2 (OK)

**Comment by ccordoba12** [comment] 2015-04-02 17:12
Thanks for reporting. This is a duplicate of issue #1983, and @cjrh is trying to solve it on pull request #2185.

**Closed by ccordoba12** 2015-04-02 17:12 UTC
Labels: duplicate

**Comment by benjaminpaik** [comment] 2015-11-06 21:54
It looks like this issue was closed.  However, I am still experiencing it with Spyder 2.3.7 on Windows 7 64-bit and Windows 10 64-bit.

**Comment by ccordoba12** [comment] 2015-11-07 00:28
It was closed because it's a duplicate of issue #1983, as I mentioned above and which is still open.
