### ISSUE TITLE
"clear" command in iPython console produces "The system cannot find the path specified"

### ISSUE THREAD

**Issue by jennirinker** [spyder-ide/spyder#4530] opened 2017-06-01 08:29 UTC
## Description of your problem
Entering "clear" (and a variety of other aliases) into iPython results in "The system cannot find the path specified" with my new Spyder setup on Windows 10.

**What steps will reproduce the problem?**

1. Type "clear", "cls", "!CLS", "!clear", or "%clear" into an iPython console.
2. Hit enter.
3. Hate Windows.

**What is the expected output? What do you see instead?**
The screen is supposed to clear. This works on my new Spyder on Windows 7 with the exact same Spyder/Qt/PyQt options.

**Please provide any additional information below**
Newly upgraded Spyder to 3.1.4 on a new laptop running Windows 10.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-06-01 21:43
Are you sure `%clear` generates an error? It should work without problems (although it does nothing).

The other commands can't be run in the IPython console.

**Comment by jennirinker** [comment] 2017-06-15 08:34
Unfortunately, I have since reinstalled Windows 7 because I was having several issues installing packages, so I can no longer test this issue. However, yes. I was sure that nothing worked.

Also, for the record, at least on my current installation of Spyder on Windows 7, all of the commands except "!clear" do work successfully in an iPython console. (I just tested them.)

**Comment by ccordoba12** [comment] 2017-06-15 19:35
The command is `%clear`, not `!clear`. Closing as this is a duplicate of #3110.

**Closed by ccordoba12** 2017-06-15 19:35 UTC

**Comment by jennirinker** [comment] 2019-02-06 17:06
I have since reinstalled anaconda several times for a variety of reasons and can't reproduce the issue. So, in short...I have no idea. Sorry I can't be more helpful. :(

**Comment by RuslanBergenov** [comment] 2019-05-28 15:53
I'm having the same issue on at work, not at home. I'm only observing it when my Spyder project is located on a drive different from where Anaconda is installed (That's my understanding). 

C:\Users\MYNAME\AppData\Local\Continuum\anaconda3\Scripts\anaconda.exe - this is my local drive. This is where Anaconda is installed. I CANNOT access these the files in this directory from another machine in my organization. 

\\MYORGNAME\MyDocs\R\MYNAME\directory. I think that's another drive? This is where my Spyder project is. I CAN access these files from any machine in my organization. My understanding is that this is a different drive from where Anaconda is installed. 

In this situation, I am having two issues. 1) %clear generated this error: The system cannot find the path specified. 2) Spyder project explorer is blank.

Both issues go away if i move my Spyder project here: C:\Users\MYNAME - in any of the subfolders.

This is a bit inconvenient, because there was a reason I was putting my Spyder project in \\MYORGNAME\MyDocs\R\MYNAME\directory - I wanted to access them from another machine (laptop, tablet etc.)

![image](https://user-images.githubusercontent.com/45578394/58492507-45245b00-812e-11e9-9c82-b66cd9d650ac.png)

Hope it makes sense.

**Comment by ccordoba12** [comment] 2019-05-29 09:16
@RuslanBergenov, I think your problems (i.e. both the `Project explorer` and `%clear` ones) are due to the fact that you're using a network drive on Windows.

This is a different problem to the one reported here, so please open a new issue about it so we can take a look at it for Spyder 4.

**Comment by m-leal** [comment] 2019-11-15 21:28
I have confirmed the same behavior when attempting to use clear, %clear, and cls on my work Windows machine. The "Path not specified" error appears when I try to work on a project stored/located in a directory on my organization's network. 

If I change my working directory to a location on my local machine, then I am able to use the clear commands again.

Just for reference, I am not using an anaconda installation for various reasons. Using Spyder 3.3.6 and qtconsole 4.5.5

**Comment by RuslanBergenov** [comment] 2019-11-16 08:14
Yes, I

> I have confirmed the same behavior when attempting to use clear, %clear, and cls on my work Windows machine. The "Path not specified" error appears when I try to work on a project stored/located in a directory on my organization's network.
> 
> If I change my working directory to a location on my local machine, then I am able to use the clear commands again.
> 
> Just for reference, I am not using an anaconda installation for various reasons. Using Spyder 3.3.6 and qtconsole 4.5.5

Yes, exactly! I'm having the same issue, but I wasn't able to open an issue yet.

**Comment by ccordoba12** [comment] 2019-11-16 12:44
@RuslanBergenov, please open a new issue about it.

**Comment by RuslanBergenov** [comment] 2019-11-28 22:51
> @RuslanBergenov, please open a new issue about it.

Done! https://github.com/spyder-ide/spyder/issues/10879
