### ISSUE TITLE
Hungarian  keyboard layout problem  in Spyder editor. (ALTGR+F don't displays the '[')

### ISSUE THREAD

**Issue by StJosy** [spyder-ide/spyder#16075] opened 2021-07-25 04:32 UTC
### What steps will reproduce the problem?

ccordoba12 closed my issue without fix it. 
So i had to reopen.

Original issues (#16073,#15654):

I have been unable to write the first square brackets on QWERTZ (Hungarian) keyboard layout in Spyder editor. (ALTGR+F must be displays the '[')

My comment: 
I hope you agree this is an awkward issue. If you don't agree, please switch to the Hungarian layout and try to code then you will see it. :)

Suggested solution:
You have to publish an unofficial hint on how we can tweak Spyder to disable the default AltGr + F keymapping. Thank you!

**Comment by ccordoba12** [comment] 2021-07-25 05:06
Hey @StJosy, please don't reopen this issue anymore. As I told you in your previous issue, this is a duplicate of issue #15654 and we don't know yet how to fix it.

If you additional comments you'd like to do, please post them there.

**Comment by ccordoba12** [comment] 2021-07-25 05:07
> You have to publish an unofficial hint on how we can tweak Spyder to disable the default AltGr + F keymapping. Thank you!

We have no idea how to fix this problem, I'm sorry.

**Closed by ccordoba12** 2021-07-25 05:06 UTC
