### ISSUE TITLE
installed the spyder-notebook plugin

### ISSUE THREAD

**Issue by c-dhawan** [spyder-ide/spyder#8827] opened 2019-02-22 09:48 UTC
### What steps will reproduce the problem?

closed the ide

installed the spyder-notebook plugin from conda

opened the ide and encounted the following problem

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 329, in create_new_client
    server_info = nbopen(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\utils\nbopen.py", line 56, in nbopen
    server_info = find_best_server(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\utils\nbopen.py", line 40, in find_best_server
    servers = [si for si in notebookapp.list_running_servers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\utils\nbopen.py", line 40, in <listcomp>
    servers = [si for si in notebookapp.list_running_servers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1767, in list_running_servers
    info = json.load(f)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-22 10:18
Duplicate of spyder-ide/spyder-notebook#120. We still don't know how to fix it, sorry.

**Closed by ccordoba12** 2019-02-22 10:18 UTC
