### ISSUE TITLE
python3.4 console dies after first command

### ISSUE THREAD

**Issue by DSLituiev** [spyder-ide/spyder#2525] opened 2015-07-10 00:01 UTC
installed latest dev version. [ debugging is hardly possible with `ipython`](https://github.com/spyder-ide/spyder/issues/2395). and unfortunately the plain python console dies after first command, e.g. 

    print('hello')

**Comment by DSLituiev** [comment] 2015-07-10 00:03
the same with the `python2.7.6`
installed with `pip3`

**Comment by ccordoba12** [comment] 2015-07-10 12:23
What operating system are you using?

**Comment by ccordoba12** [comment] 2015-07-10 12:24
Closing because this is a duplicate of issue #2308.

**Closed by ccordoba12** 2015-07-10 12:24 UTC
Labels: duplicate
