### ISSUE TITLE
Layout broken in master branch when using 4.x settings

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#13629] opened 2020-08-25 19:36 UTC
## Problem Description

If I don't start Spyder with `safe-mode` in master then I will get the following layout,

![image](https://user-images.githubusercontent.com/20992645/91219346-1c4b9680-e6e0-11ea-873e-bd25a8d1a096.png)

### What steps reproduce the problem?

1. Go to master branch
2. Start spyder without safe mode

### What is the expected output? What do you see instead?

The same layout as 4.x branch

**Comment by goanpeca** [comment] 2020-08-28 16:24
This will be fixed on https://github.com/spyder-ide/spyder/pull/13479

**Comment by dalthviz** [comment] 2021-02-22 19:43
Note: Since this seems to be caused by the hexstate of the window not being able to map the `objectNameId` of the migrated plugins (since the name is set based on the class name [here](https://github.com/spyder-ide/spyder/blob/9f0e60500f09ed21560e44dbff8e163d09cd268c/spyder/plugins/base.py#L253)) so probably the windows state will need to be set to defaults to prevent this when changing from `4.x` to `master/5.x` or implement a way to map the migrated plugins object names to have the same object name as before

**Comment by ccordoba12** [comment] 2021-02-23 01:06
> or implement a way to map the migrated plugins object names to have the same object name as before

This sounds like an interesting idea but I don't know how hard it could be to implement. What are your thoughts about it @dalthviz?

**Comment by dalthviz** [comment] 2021-02-23 17:50
No idea for now @ccordoba12 just putting the note to think about it later

**Closed** 2021-03-25 19:55 UTC
Labels: tag:Ui, tag:Ux-usability, type:Bug
