### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by paskino** [spyder-ide/spyder#6531] opened 2018-02-27 14:14 UTC
just changed the coloring scheme

  File "C:\Apps\miniconda3\envs\cil35\lib\site-packages\spyder\plugins\configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "C:\Apps\miniconda3\envs\cil35\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\Apps\miniconda3\envs\cil35\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Apps\miniconda3\envs\cil35\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\Apps\miniconda3\envs\cil35\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by ccordoba12** [comment] 2018-02-27 14:48
Thanks, this is a duplicate of issue #6519.

**Closed by ccordoba12** 2018-02-27 14:48 UTC
