### ISSUE TITLE
Buggy toolbar buttons

### ISSUE THREAD

**Issue by VossAlexander** [spyder-ide/spyder#8844] opened 2019-02-25 11:31 UTC
### What steps will reproduce the problem?

The toolbar buttons are not correctly displayed. I decided to toggle the toolbars off and on again. During this process the interal problem appeared.

### Traceback
```python-traceback
TypeError: _start_server() missing 1 required positional argument: 'port'
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.2
* Qt version: 5.12.1
* PyQt5 version: 5.12
* Operating System: Linux 4.20.12-arch1-1-ARCH

### Dependencies

```
pyflakes >=0.6.0  :  2.1.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.5.0 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.16.1 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.5 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-25 11:43
The error above is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder

And the icons bug is a duplicate of issue #8748.

**Closed by ccordoba12** 2019-02-25 11:43 UTC
