### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by tiam94** [spyder-ide/spyder#6979] opened 2018-04-18 07:17 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/code/cnn-text-classification\\.spyproject\\workspace.ini'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 234, in _create_project
    self.open_project(path=path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 261, in open_project
    self.set_project_filenames(self.editor.get_open_filenames())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 325, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\projects\type\__init__.py", line 74, in set_recent_files
    list(OrderedDict.fromkeys(recent_files)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 448, in set
    self._save()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
    raise(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 120, in _save
    _write_file(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/code/cnn-text-classification\\.spyproject\\workspace.ini'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-04-18 14:41
Thanks for reporting. This error appears to be a duplicate of #5765 , which is currently being looked at, and so this one can be closed. If you have more details about the circumstances in which it occurs, it would be helpful to post that over there. If it is indeed a Spyder bug, it should hopefully get fixed soon. In the meantime, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Closed** 2018-04-18 14:41 UTC
Labels: resolution:Duplicate
