### ISSUE TITLE
Menu items don't show in full-screen mode

### ISSUE THREAD

**Issue by svenhsia** [spyder-ide/spyder#4291] opened 2017-03-22 21:03 UTC
## Description

**What steps will reproduce the problem?**

1. In full-screen mode
2. Click on menu buttons
3. Menu items won't show

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.6.0
* Qt Versions: 5.7.1, PyQt5 5.7.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment] 2017-03-22 22:04
Not a priority for us to make this work, sorry.

**Comment by ccordoba12** [comment] 2018-05-25 22:56
This is a duplicate of #4821. Its (temporary) solution is to close the Help pane.

**Comment by jasonsross** [comment] 2018-08-01 17:56
@ccordoba12 it seems you can keep the help pane open if you switch the text to plain text instead of rich text. Only problem is spyder doesn't remember this setting up closing. Is there any way to change that?

**Comment by jnsebgosselin** [comment] 2018-08-17 22:25
@ccordoba12 I believe this is not a duplicate of #4821. This is actually a known QT bug with documented workarounds. I will take a look at it when I have the time.

See:
https://bugreports.qt.io/browse/QTBUG-47156
https://bugreports.qt.io/browse/QTBUG-41309
https://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows

**Comment by ccordoba12** [comment] 2018-08-18 01:51
This could be fixed by a new option I added to select the OpenGL implementation used by Qt, which will appear in 3.3.2.

@jasonsross, could you help us to test that? For that, you'd need to download the Spyder source code with git, then `git checkout 3.x` and finally run `python bootstrap.py -- --opengl software` in the root of your repo.

**Comment by jasonsross** [comment] 2018-08-18 05:09
@ccordoba12 I tried it and, if I did it right, no change. Problem persists. Was there some setting to choose in spyder? Here's some screenshots of my attempt:

![image](https://user-images.githubusercontent.com/30841951/44296017-fd50d900-a269-11e8-91f1-1f61f64d3a70.png)

![image](https://user-images.githubusercontent.com/30841951/44296025-2f623b00-a26a-11e8-94c4-b5b57d60a919.png)

**Comment by jasonsross** [comment] 2018-08-18 05:26
@jnsebgosselin Ah I see they are different issues now. I was assuming they were the same. Anyway, the 3.3.2 build also does not fix the full screen menu bars, still unclickable for me. Any plans to reopen the other issue?

**Comment by jnsebgosselin** [comment] 2018-08-18 05:35
>@jnsebgosselin Ah I see they are different issues now. I was assuming they were the same. Anyway, the 3.3.2 build also does not fix the full screen menu bars, still unclickable for me. Any plans to reopen the other issue?

I do not know, I wish I could help with that one too, but I have not been able to reproduce the problem yet :/ I'll see what I can do.

**Closed** 2018-08-21 13:28 UTC
Labels: component:Main Window, type:Bug
