### ISSUE TITLE
Line length is not remembered

### ISSUE THREAD

**Issue by fairyqiqi** [spyder-ide/spyder#14546] opened 2021-01-06 02:48 UTC
### What steps will reproduce the problem?

Tools->Preferences->Completion and linting->Code style and formatting->Line length->Change "Maximum allowed length" to 119->OK

->You can see the vertical line in editor is moved to col 119
->Restart Spyder
->You can see the vertical line in editor is moved back to col 79, although it's till showing 119 in the settings.

## Versions

* Spyder version: 4.2.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.5.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.1 (NOK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.2.1 (NOK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0 (OK)
sphinx >=0.6.6                  :  3.3.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.4 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment] 2021-01-06 17:15
Hey @fairyqiqi, thanks for reporting. This is very odd indeed.

@steff456, could you take a look at this one and see if you're able to reproduce it? Thanks!

**Comment by steff456** [comment] 2021-01-06 17:19
Hi @fairyqiqi,

I'm able to reproduce this behavior, we will work in fixing this for our future release. 

Thanks for reporting!

**Comment by justin76tan** [comment] 2021-03-27 07:46
各位，请问下这个bug大概什么时候可以修复，有安排吗？

**Comment by mrclary** [comment] 2021-11-01 15:06
This is a duplicate of #14188. Closing.

**Closed by mrclary** 2021-11-01 15:06 UTC
Labels: type:Bug, component:Code Completion
