### ISSUE TITLE
Closing multiple deleted files

### ISSUE THREAD

**Issue by toma78** [spyder-ide/spyder#21716] opened 2024-01-17 17:25 UTC
### What steps will reproduce the problem?

Opened dozen py files in Spyder. Deleted them in file explorer. Returned on Spyder, answered dialog to close currently opened deleted file with yes. Tried to "close all but this" on one of remaining opened files. Another dialog popped up, replied "yes" and here we are.  

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\spyder-cf\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1737, in close_all_but_this
    self.close_all_right()
  File "C:\ProgramData\Anaconda3\envs\spyder-cf\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1733, in close_all_right
    self.close_file(num+1)
  File "C:\ProgramData\Anaconda3\envs\spyder-cf\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1640, in close_file
    self.data[index].filename) if self.parent() else True
IndexError: list index out of range
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  7.1.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.2 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  65.4.1 (OK)
sphinx >=0.6.6                :  5.2.3 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.1 (OK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by GitKia1392** [comment] 2024-01-17 23:12
Yo @toma78, I think you accidentally clicked  "`F5`" which is a shortcut for run in Spyder btw. There must be a error while deleting the truckload of files the Windows didn't bother to show you what it was or so.

Thx

**Comment by toma78** [comment] 2024-01-18 07:47
Hey. Yes, possible. In any case I did the same actions many time
(deleting/closing opened files) and usually it all goes fine.

čet, 18. sij 2024. 00:12 GitKia1392 ***@***.***> je napisao:

**Comment by ccordoba12** [comment] 2024-01-19 16:12
Hey @toma78, thanks for reporting. This problem should be fixed in our latest version (5.5.0) because I was unable to reproduce it with it.

Since it seems you're using Spyder through conda-forge, please run the following commands to get it:

    conda activate spyder-cf
    conda install -c conda-forge spyder=5.5.0

Let us know if that works for you.

**Comment by toma78** [comment] 2024-01-19 17:53
Hey, no problem. As I replied to someone yesterday... it happened only this
time and I have done it similarly many times without any problem. So it
could be caused by windows, rather than Spyder.

Cheers!

pet, 19. sij 2024. 17:12 Carlos Cordoba ***@***.***> je
napisao:

**Comment by ccordoba12** [comment] 2024-01-19 20:51
Ok, no problem. I'm going to close this one for now then, but in case the error reappears, please update to our latest version before reporting again.

**Closed by ccordoba12** 2024-01-19 20:51 UTC
Labels: status:Awaiting Followup
