### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by cz9785** [spyder-ide/spyder#13159] opened 2020-07-02 01:45 UTC
### Issue Report Checklist

* 
[1 ]Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [1 ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [1] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I just installed anaconda, and it worked well the first time I opened it. However, once I clicked 'launch' and nothing happened for a while, so I clicked 'launch' again, then the problem happened. It showed that Spyder crashed during last seesion. I tried to reopen anaconda for several times, and spyder suddenly opened.
After I finished my work, I closed Spyder. Then, after several hours, I tried to launch it and the same problem showed again.

Jupyter notebook works well during this time.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Traceback (most recent call last):
File "C:\Users\Chenxi Zhao\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\Chenxi Zhao\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "C:\Users\Chenxi Zhao\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "C:\Users\Chenxi Zhao\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "C:\Users\Chenxi Zhao\anaconda3\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 144, in start
self.client.start()
File "C:\Users\Chenxi Zhao\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 62, in start
self.sig_client_started.emit(self.languages)
TypeError: KiteClient.sig_client_started[list].emit(): argument 1 has unexpected type 'str'

```

## Versions

Anaconda Navigator 1.9.12
* Spyder version: 4.0.1
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment] 2020-07-02 03:49
Hi @cz9785 this seems like a duplicate of #12410. Please update to spyder 4.1.3 to get the fix :)

To update you can run something like  `conda install spyder=4.1.3`

**Closed by dalthviz** 2020-07-02 03:49 UTC
