### ISSUE TITLE
just installed Spyder-Terminal (after Spyder-Notebook) and Spyder started crashing.  

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder#17115] opened 2021-12-29 04:27 UTC
## Description of your problem

I want to use Spyder with Spyder-Notebook and Spyder-Terminal.   I really want to use Spyder (instead of VSCode or Pycharm), and having an integrated Notebook and Terminal are really great.  

I have tried several different Spyder configurations (4.2.1 and 5.2.1) in both brand new and existing conda environments.   This is frustrating because I had it working once last year and cannot reproduce it in a working conda environment.  

I get the following error and then a traceback when I try to enable the Terminal.  Installing Spyder-Notebook works fine, but then when Terminal is added, Spyder stops showing the View Menu options and throws the errors below.  

```<class 'spyder_terminal.terminalplugin.TerminalPlugin'>: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information```

**What steps will reproduce the problem?**

1.  Create new conda environment with Spyder v5.2.1 and other recommended packages:

```c:\Users\richadmin>conda create --name spyder5quant python=3.8 spyder=5 numpy scipy pandas matplotlib sympy cython```

2. Activate new conda environment: 

```c:\Users\richadmin>conda activate spyder5quant
(spyder5quant) c:\Users\richadmin>start spyder
(spyder5quant) c:\Users\richadmin>conda install spyder-notebook -c spyder-ide```

2. Install Spyder-Notebook:

```(spyder5quant) c:\Users\richadmin>conda install spyder-notebook -c spyder-ide```

3. Install Spyder-Terminal: 

```(spyder5quant) c:\Users\richadmin>conda install spyder-terminal -c spyder-ide```

**What is the expected output? What do you see instead?**

Installation succeeds for Spyder and all the recommended packages (from https://docs.spyder-ide.org/current/installation.html).

Spyder-Notebook and Spyder-Terminal both install without throwing errors.  

However, when I start Spyder (from a Windows Administrator Command Console using `start spyder`), it starts okay, but the View Menu does not dropdown completely and is missing most submenus.  I also get this traceback in the Console Window:

> <class 'spyder_terminal.terminalplugin.TerminalPlugin'>: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information
> Traceback (most recent call last):
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\app\mainwindow.py", line 902, in setup
>     plugin_instance = PLUGIN_REGISTRY.register_plugin(
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\api\plugin_registration\registry.py", line 342, in register_plugin
>     instance = self._instantiate_spyder5_plugin(
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\api\plugin_registration\registry.py", line 193, in _instantiate_spyder5_plugin
>     plugin_instance.initialize()
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\api\plugins\new_api.py", line 625, in initialize
>     self.on_initialize()
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\api\plugins\new_api.py", line 720, in on_initialize
>     raise SpyderAPIError(
> spyder.api.exceptions.SpyderAPIError: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information
> Traceback (most recent call last):
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder_terminal\widgets\main_widget.py", line 303, in __wait_server_to_start
>     self.create_new_term(give_focus=False)
>   File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder_terminal\widgets\main_widget.py", line 360, in create_new_term
>     self, self.port, path=path, font=self.font.family(),
> AttributeError: 'NoneType' object has no attribute 'family'
> 

**Please provide any additional information below**


## Versions and main components

* Terminal Version:
  spyder-terminal    spyder-ide/win-64::spyder-terminal-1.0.0-py38haa244fe_1

* Spyder Version:  Version 5.2.1

>>> spyder.get_versions()
{'spyder': '5.2.1', 'python': '3.8.12', 'bitness': 64, 'qt': '5.12.9', 'qt_api': 'PyQt5', 'qt_api_ver': '5.12.3', 'system': 'Windows', 'release': '10', 'revision': None, 'branch': None}

* Spyder-Notebook Version: 0.1.4

  notebook           conda-forge/noarch::notebook-6.4.6-pyha770c72_0
  spyder-notebook    spyder-ide/noarch::spyder-notebook-0.1.4-py_0

* Python Version:   Python 3.8.12
* Operating system:  Windows 10 Pro Version 21H1 OS Build 19043.1415

Here's a complete list of package installations in this new environment built today:

(spyder5quant) c:\Users\richadmin>conda list --revisions

2021-12-28 20:24:04  (rev 0)
    +alabaster-0.7.12 (conda-forge/noarch)
    +argh-0.26.2 (conda-forge/noarch)
    +arrow-1.2.1 (conda-forge/noarch)
    +astroid-2.9.0 (conda-forge/win-64)
    +async_generator-1.10 (conda-forge/noarch)
    +atomicwrites-1.4.0 (conda-forge/noarch)
    +attrs-21.2.0 (conda-forge/noarch)
    +autopep8-1.6.0 (conda-forge/noarch)
    +babel-2.9.1 (conda-forge/noarch)
    +backcall-0.2.0 (conda-forge/noarch)
    +backports-1.0 (conda-forge/noarch)
    +backports.functools_lru_cache-1.6.4 (conda-forge/noarch)
    +bcrypt-3.2.0 (conda-forge/win-64)
    +binaryornot-0.4.4 (conda-forge/noarch)
    +black-21.12b0 (conda-forge/noarch)
    +bleach-4.1.0 (conda-forge/noarch)
    +brotli-1.0.9 (conda-forge/win-64)
    +brotli-bin-1.0.9 (conda-forge/win-64)
    +brotlipy-0.7.0 (conda-forge/win-64)
    +ca-certificates-2021.10.8 (conda-forge/win-64)
    +certifi-2021.10.8 (conda-forge/win-64)
    +cffi-1.15.0 (conda-forge/win-64)
    +chardet-4.0.0 (conda-forge/win-64)
    +charset-normalizer-2.0.9 (conda-forge/noarch)
    +click-8.0.3 (conda-forge/win-64)
    +cloudpickle-2.0.0 (conda-forge/noarch)
    +colorama-0.4.4 (conda-forge/noarch)
    +cookiecutter-1.6.0 (conda-forge/win-64)
    +cryptography-36.0.1 (conda-forge/win-64)
    +cycler-0.11.0 (conda-forge/noarch)
    +cython-0.29.26 (conda-forge/win-64)
    +dataclasses-0.8 (conda-forge/noarch)
    +debugpy-1.5.1 (conda-forge/win-64)
    +decorator-5.1.0 (conda-forge/noarch)
    +defusedxml-0.7.1 (conda-forge/noarch)
    +diff-match-patch-20200713 (conda-forge/noarch)
    +docutils-0.15.2 (conda-forge/win-64)
    +entrypoints-0.3 (conda-forge/noarch)
    +flake8-4.0.1 (conda-forge/noarch)
    +fonttools-4.28.5 (conda-forge/win-64)
    +freetype-2.10.4 (conda-forge/win-64)
    +future-0.18.2 (conda-forge/win-64)
    +icu-68.2 (conda-forge/win-64)
    +idna-3.1 (conda-forge/noarch)
    +imagesize-1.3.0 (conda-forge/noarch)
    +importlib-metadata-4.10.0 (conda-forge/win-64)
    +importlib_metadata-4.10.0 (conda-forge/noarch)
    +importlib_resources-5.4.0 (conda-forge/noarch)
    +inflection-0.5.1 (conda-forge/noarch)
    +intel-openmp-2022.0.0 (conda-forge/win-64)
    +intervaltree-3.0.2 (conda-forge/noarch)
    +ipykernel-6.4.1 (defaults/win-64)
    +ipython-7.30.1 (conda-forge/win-64)
    +ipython_genutils-0.2.0 (conda-forge/noarch)
    +isort-5.10.1 (conda-forge/noarch)
    +jbig-2.1 (conda-forge/win-64)
    +jedi-0.18.1 (conda-forge/win-64)
    +jellyfish-0.8.9 (conda-forge/win-64)
    +jinja2-3.0.3 (conda-forge/noarch)
    +jinja2-time-0.2.0 (conda-forge/noarch)
    +jpeg-9d (conda-forge/win-64)
    +jsonschema-4.3.2 (conda-forge/noarch)
    +jupyter_client-7.1.0 (conda-forge/noarch)
    +jupyter_core-4.9.1 (conda-forge/win-64)
    +jupyterlab_pygments-0.1.2 (conda-forge/noarch)
    +keyring-23.4.0 (conda-forge/win-64)
    +kiwisolver-1.3.2 (conda-forge/win-64)
    +lazy-object-proxy-1.7.1 (conda-forge/win-64)
    +lcms2-2.12 (conda-forge/win-64)
    +lerc-3.0 (conda-forge/win-64)
    +libblas-3.9.0 (conda-forge/win-64)
    +libbrotlicommon-1.0.9 (conda-forge/win-64)
    +libbrotlidec-1.0.9 (conda-forge/win-64)
    +libbrotlienc-1.0.9 (conda-forge/win-64)
    +libcblas-3.9.0 (conda-forge/win-64)
    +libclang-11.1.0 (conda-forge/win-64)
    +libdeflate-1.8 (conda-forge/win-64)
    +liblapack-3.9.0 (conda-forge/win-64)
    +libpng-1.6.37 (conda-forge/win-64)
    +libsodium-1.0.18 (conda-forge/win-64)
    +libspatialindex-1.9.3 (conda-forge/win-64)
    +libtiff-4.3.0 (conda-forge/win-64)
    +libzlib-1.2.11 (conda-forge/win-64)
    +lz4-c-1.9.3 (conda-forge/win-64)
    +m2w64-gcc-libgfortran-5.3.0 (conda-forge/win-64)
    +m2w64-gcc-libs-5.3.0 (conda-forge/win-64)
    +m2w64-gcc-libs-core-5.3.0 (conda-forge/win-64)
    +m2w64-gmp-6.1.0 (conda-forge/win-64)
    +m2w64-libwinpthread-git-5.0.0.4634.697f757 (conda-forge/win-64)
    +markupsafe-2.0.1 (conda-forge/win-64)
    +matplotlib-3.5.1 (conda-forge/win-64)
    +matplotlib-base-3.5.1 (conda-forge/win-64)
    +matplotlib-inline-0.1.3 (conda-forge/noarch)
    +mccabe-0.6.1 (conda-forge/noarch)
    +mistune-0.8.4 (conda-forge/win-64)
    +mkl-2021.4.0 (conda-forge/win-64)
    +mpmath-1.2.1 (conda-forge/noarch)
    +msys2-conda-epoch-20160418 (conda-forge/win-64)
    +munkres-1.1.4 (conda-forge/noarch)
    +mypy_extensions-0.4.3 (conda-forge/win-64)
    +nbclient-0.5.9 (conda-forge/noarch)
    +nbconvert-6.3.0 (conda-forge/win-64)
    +nbformat-5.1.3 (conda-forge/noarch)
    +nest-asyncio-1.5.4 (conda-forge/noarch)
    +numpy-1.21.5 (conda-forge/win-64)
    +numpydoc-1.1.0 (conda-forge/noarch)
    +olefile-0.46 (conda-forge/noarch)
    +openjpeg-2.4.0 (conda-forge/win-64)
    +openssl-1.1.1l (conda-forge/win-64)
    +packaging-21.3 (conda-forge/noarch)
    +pandas-1.3.5 (conda-forge/win-64)
    +pandoc-2.16.2 (conda-forge/win-64)
    +pandocfilters-1.5.0 (conda-forge/noarch)
    +paramiko-2.9.1 (conda-forge/noarch)
    +parso-0.8.3 (conda-forge/noarch)
    +pathspec-0.9.0 (conda-forge/noarch)
    +pexpect-4.8.0 (conda-forge/noarch)
    +pickleshare-0.7.5 (conda-forge/noarch)
    +pillow-8.4.0 (conda-forge/win-64)
    +pip-21.3.1 (conda-forge/noarch)
    +platformdirs-2.3.0 (conda-forge/noarch)
    +pluggy-1.0.0 (conda-forge/win-64)
    +poyo-0.5.0 (conda-forge/noarch)
    +prompt-toolkit-3.0.24 (conda-forge/noarch)
    +psutil-5.8.0 (conda-forge/win-64)
    +ptyprocess-0.7.0 (conda-forge/noarch)
    +pycodestyle-2.8.0 (conda-forge/noarch)
    +pycparser-2.21 (conda-forge/noarch)
    +pydocstyle-6.1.1 (conda-forge/noarch)
    +pyflakes-2.4.0 (conda-forge/noarch)
    +pygments-2.10.0 (conda-forge/noarch)
    +pylint-2.12.2 (conda-forge/noarch)
    +pyls-spyder-0.4.0 (conda-forge/noarch)
    +pynacl-1.4.0 (conda-forge/win-64)
    +pyopenssl-21.0.0 (conda-forge/noarch)
    +pyparsing-3.0.6 (conda-forge/noarch)
    +pyqt-5.12.3 (conda-forge/win-64)
    +pyqt-impl-5.12.3 (conda-forge/win-64)
    +pyqt5-sip-4.19.18 (conda-forge/win-64)
    +pyqtchart-5.12 (conda-forge/win-64)
    +pyqtwebengine-5.12.1 (conda-forge/win-64)
    +pyrsistent-0.18.0 (conda-forge/win-64)
    +pysocks-1.7.1 (conda-forge/win-64)
    +python-3.8.12 (conda-forge/win-64)
    +python-dateutil-2.8.2 (conda-forge/noarch)
    +python-lsp-black-1.0.1 (conda-forge/noarch)
    +python-lsp-jsonrpc-1.0.0 (conda-forge/noarch)
    +python-lsp-server-1.3.3 (conda-forge/noarch)
    +python_abi-3.8 (conda-forge/win-64)
    +pytz-2021.3 (conda-forge/noarch)
    +pywin32-303 (conda-forge/win-64)
    +pywin32-ctypes-0.2.0 (conda-forge/win-64)
    +pyyaml-6.0 (conda-forge/win-64)
    +pyzmq-22.3.0 (conda-forge/win-64)
    +qdarkstyle-3.0.2 (defaults/noarch)
    +qstylizer-0.2.1 (conda-forge/noarch)
    +qt-5.12.9 (conda-forge/win-64)
    +qtawesome-1.1.1 (conda-forge/noarch)
    +qtconsole-5.2.2 (conda-forge/noarch)
    +qtpy-2.0.0 (conda-forge/noarch)
    +requests-2.26.0 (conda-forge/noarch)
    +rope-0.22.0 (conda-forge/noarch)
    +rtree-0.9.7 (conda-forge/win-64)
    +scipy-1.7.3 (conda-forge/win-64)
    +setuptools-60.1.0 (conda-forge/win-64)
    +six-1.16.0 (conda-forge/noarch)
    +snowballstemmer-2.2.0 (conda-forge/noarch)
    +sortedcontainers-2.4.0 (conda-forge/noarch)
    +sphinx-4.3.2 (conda-forge/noarch)
    +sphinxcontrib-applehelp-1.0.2 (conda-forge/noarch)
    +sphinxcontrib-devhelp-1.0.2 (conda-forge/noarch)
    +sphinxcontrib-htmlhelp-2.0.0 (conda-forge/noarch)
    +sphinxcontrib-jsmath-1.0.1 (conda-forge/noarch)
    +sphinxcontrib-qthelp-1.0.3 (conda-forge/noarch)
    +sphinxcontrib-serializinghtml-1.1.5 (conda-forge/noarch)
    +spyder-5.2.1 (conda-forge/win-64)
    +spyder-kernels-2.2.0 (conda-forge/win-64)
    +sqlite-3.37.0 (conda-forge/win-64)
    +sympy-1.9 (conda-forge/win-64)
    +tbb-2021.5.0 (conda-forge/win-64)
    +testpath-0.5.0 (conda-forge/noarch)
    +textdistance-4.2.2 (conda-forge/noarch)
    +three-merge-0.1.1 (conda-forge/noarch)
    +tinycss2-1.1.1 (conda-forge/noarch)
    +tk-8.6.11 (conda-forge/win-64)
    +toml-0.10.2 (conda-forge/noarch)
    +tomli-1.2.2 (conda-forge/noarch)
    +tornado-6.1 (conda-forge/win-64)
    +traitlets-5.1.1 (conda-forge/noarch)
    +typed-ast-1.5.1 (conda-forge/win-64)
    +typing-extensions-4.0.1 (conda-forge/noarch)
    +typing_extensions-4.0.1 (conda-forge/noarch)
    +ucrt-10.0.20348.0 (conda-forge/win-64)
    +ujson-5.1.0 (conda-forge/win-64)
    +unicodedata2-14.0.0 (conda-forge/win-64)
    +urllib3-1.26.7 (conda-forge/noarch)
    +vc-14.2 (conda-forge/win-64)
    +vs2015_runtime-14.29.30037 (conda-forge/win-64)
    +watchdog-2.1.6 (conda-forge/win-64)
    +wcwidth-0.2.5 (conda-forge/noarch)
    +webencodings-0.5.1 (conda-forge/noarch)
    +wheel-0.37.1 (conda-forge/noarch)
    +whichcraft-0.6.1 (conda-forge/noarch)
    +win_inet_pton-1.1.0 (conda-forge/win-64)
    +wrapt-1.13.3 (conda-forge/win-64)
    +xz-5.2.5 (conda-forge/win-64)
    +yaml-0.2.5 (conda-forge/win-64)
    +yapf-0.31.0 (conda-forge/noarch)
    +zeromq-4.3.4 (conda-forge/win-64)
    +zipp-3.6.0 (conda-forge/noarch)
    +zlib-1.2.11 (conda-forge/win-64)
    +zstd-1.5.1 (conda-forge/win-64)

2021-12-28 22:47:19  (rev 1)
    +argon2-cffi-21.1.0 (conda-forge/win-64)
    +notebook-6.4.6 (conda-forge/noarch)
    +prometheus_client-0.12.0 (conda-forge/noarch)
    +pywinpty-1.1.6 (conda-forge/win-64)
    +send2trash-1.8.0 (conda-forge/noarch)
    +spyder-notebook-0.1.4 (spyder-ide/noarch)
    +terminado-0.12.1 (conda-forge/win-64)
    +winpty-0.4.3 (conda-forge/win-64)

2021-12-28 22:48:34  (rev 2)
    +coloredlogs-15.0.1 (conda-forge/win-64)
    +humanfriendly-10.0 (conda-forge/win-64)
    +pyreadline3-3.3 (conda-forge/win-64)
    +spyder-terminal-1.0.0 (spyder-ide/win-64)


### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 62, in create_dialog
    page.initialize()
  File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "c:\ProgramData\Anaconda3\envs\spyder5quant\lib\site-packages\spyder\api\plugin_registration\_confpage.py", line 71, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.8.12
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.3.2 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.1.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2021-12-29 17:50
> I get the following error and then a traceback when I try to enable the Terminal

You need to install Spyder-terminal 1.2.0 along with Spyder 5.2.1 to avoid that error. Unfortunately, 1.2.0 packages for Spyder-rerminal are still not available (see https://github.com/conda-forge/spyder-terminal-feedstock/pull/25), but they will be tomorrow.

After that, you need to run the following command:

    conda create --name spyder5quant -c conda-forge python=3.8 spyder=5.2 spyder-terminal=1.2 numpy scipy pandas matplotlib sympy cython

**Comment by ccordoba12** [comment] 2021-12-29 17:54
> I want to use Spyder with Spyder-Notebook and Spyder-Terminal. I really want to use Spyder (instead of VSCode or Pycharm), and having an integrated Notebook and Terminal are really great.

This is basically a duplicate of issue #17114.

> I have tried several different Spyder configurations (4.2.1 and 5.2.1) in both brand new and existing conda environments. This is frustrating because I had it working once last year and cannot reproduce it in a working conda environment.

As I said on issue #17114, open source advances very fast so that's not possible anymore but it will be once we update Spyder-notebook to work with Spyder 5 in a couple of months.

**Comment by ccordoba12** [comment] 2021-12-29 17:55
I'm going to close this one there's no more to talk about here.

**Closed by ccordoba12** 2021-12-29 17:55 UTC
