### ISSUE TITLE
 'An erorr ocurred while starting the kernel'

### ISSUE THREAD

**Issue by Rabijns** [spyder-ide/spyder#11562] opened 2020-02-15 13:00 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
For a certain conda environment, console will not properly start but gives  an error titled 'An erorr ocurred while starting the kernel': 
 

Traceback (most recent call last):

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\runpy.py", line 193, in _run_module_as_main

"__main__", mod_spec)

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\runpy.py", line 85, in _run_code

exec(code, run_globals)

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in

start.main()

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main

import_spydercustomize()

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize

import spydercustomize

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in

from spyder_kernels.comms.frontendcomm import CommError, frontend_request

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\spyder_kernels\comms\frontendcomm.py", line 17, in

from jupyter_client.localinterfaces import localhost

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\jupyter_client\__init__.py", line 4, in

from .connect import *

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\jupyter_client\connect.py", line 24, in

import zmq

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\zmq\__init__.py", line 47, in

from zmq import backend

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\zmq\backend\__init__.py", line 40, in

reraise(*exc_info)

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise

raise value

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\zmq\backend\__init__.py", line 27, in

_ns = select_backend(first)

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\zmq\backend\select.py", line 28, in select_backend

mod = __import__(name, fromlist=public_api)

File "C:\Users\RMT7801\.conda\envs\pdal3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in

from . import (constants, error, message, context,

ImportError: DLL load failed: The specified module could not be found. 

### What steps reproduce the problem?

1. create a new environment via

 ``` conda create --name pdal3 --channel conda-forge python=3.7 spyder-kernels python-pdal geopandas ``` 

 

2. start spyder and set interpreter to new environment 

3. close spyder and restart it (or simply start new console)

### What is the expected output? What do you see instead?

expected: console using python from new environment

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.3 64 bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: windows10

(tested on two differnet PCs)

### Dependencies
 

```
atomicwrites >=1.2.0         :  1.3.0 (OK) 

chardet >=2.0.0              :  3.0.4 (OK) 

cloudpickle >=0.5.0          :  1.3.0 (OK) 

diff_match_patch >=20181111  :  20181111 (OK) 

intervaltree                 :  None (OK) 

IPython >=4.0                :  7.12.0 (OK) 

jedi =0.14.1                 :  0.14.1 (OK) 

nbconvert >=4.0              :  5.6.1 (OK) 

numpydoc >=0.6.0             :  0.9.2 (OK) 

pexpect >=4.4.0              :  4.8.0 (OK) 

pickleshare >=0.4            :  0.7.5 (OK) 

psutil >=0.3                 :  5.6.7 (OK) 

pygments >=2.0               :  2.5.2 (OK) 

pylint >=0.25                :  2.4.4 (OK) 

pyls >=0.31.2;<0.32.0        :  0.31.7 (OK) 

zmq >=17                     :  18.1.1 (OK) 

qdarkstyle >=2.7             :  2.8 (OK) 

qtawesome >=0.5.7            :  0.6.1 (OK) 

qtconsole >=4.6.0            :  4.6.0 (OK) 

qtpy >=1.5.0                 :  1.9.0 (OK) 

rtree >=0.8.3                :  0.9.3 (OK) 

sphinx >=0.6.6               :  2.4.0 (OK) 

spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK) 

watchdog                     :  None (OK) 

cython >=0.21                :  0.29.15 (OK) 

matplotlib >=2.0.0           :  3.1.3 (OK) 

numpy >=1.7                  :  1.18.1 (OK)  
```

**Comment by ccordoba12** [comment] 2020-02-15 15:08
Duplicate of #9077

**Comment by ccordoba12** [comment] 2020-02-15 15:08
This error will be fixed in our next version.

**Closed by ccordoba12** 2020-02-15 15:08 UTC

**Comment by Rabijns** [comment] 2020-03-21 13:49
I can confirm the issue is no longer present in Spyder 4.1.1
Thanks for all the work you are putting into Spyder.
