### ISSUE TITLE
error in the Spyder 5.0.0 preferences

### ISSUE THREAD

**Issue by Marco-130** [spyder-ide/spyder#15231] opened 2021-04-10 17:11 UTC
### What steps will reproduce the problem?

after modifying some settings, it doesn't let me apply them neither click on the "OK" button.

EDIT: after closing and re-opening the preferences window it works. But it seems that you can't click the "Apply" botton more than two times without close and reopen step.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/marco/anaconda3/envs/Astronomy/lib/python3.8/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "/home/marco/anaconda3/envs/Astronomy/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 110, in apply_changes
    self.apply_callback()
  File "/home/marco/anaconda3/envs/Astronomy/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "/home/marco/anaconda3/envs/Astronomy/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "/home/marco/anaconda3/envs/Astronomy/lib/python3.8/site-packages/spyder/api/preferences.py", line 101, in wrapper
    opts = self.previous_apply_settings()
TypeError: apply_settings() missing 1 required positional argument: 'options'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.8.0-48-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.8.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.2 (OK)
pygments >=2.0                :  2.7.4 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  51.1.2.post20210112 (OK)
sphinx >=0.6.6                :  3.4.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.4 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-04-10 18:06
Hey @Marco-130, thanks for reporting. This is a duplicate of issue #15090 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-10 18:06 UTC
