### ISSUE TITLE
Spyder 5.0.0 key type slow without external monitor - 16" Macbook Pro

### ISSUE THREAD

**Issue by Nixcelsior** [spyder-ide/spyder#15535] opened 2021-05-07 01:41 UTC
## Problem Description
I am running Spyder 5.0.0 through Anaconda on my 2019 16" Macbook Pro. If I have an external monitor connected to the computer with Spyder displayed on that monitor, it works fine. Once I either move Spyder to the Macbook screen or disconnect the monitor, Spyder runs very bad. There is latency in the key strokes and some of the buttons on the tool bar are blacked out unless you hover the mouse curser over it. Sometimes it does work fine, but for the most part, it does not.

I am new to python and would like use anaconda because it has all the packages pre installed and makes my life (and the people I annoy for help) easier. 

### What steps reproduce the problem?

1. open Spyder through Anaconda
2. disconnect external screen
3. 

### What is the expected output? What do you see instead?

Keystroke latenancy, sometimes a black screen until the house hovers over.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.7
* Qt version: Not sure how
* PyQt version: Not sure how
* Operating System name/version: 

-  MacBook Pro (16-inch, 2019)
- Processor 2.4 GHz 8-Core Intel Core i9
- Memory 64 GB 2667 MHz DDR4
- Graphics AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2021-05-10 04:43
Closing as a duplicate of issue #15548.

**Closed by ccordoba12** 2021-05-10 04:43 UTC
