### ISSUE TITLE
can't new an project

### ISSUE THREAD

**Issue by zsash** [spyder-ide/spyder#5993] opened 2017-12-16 06:46 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 114, in _save
    _write_file(fname)
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/media/ashley/My Passport/linux/xray/code/project/xray/.spyproject/workspace.ini'

Traceback (most recent call last):
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 233, in _create_project
    self.open_project(path=path)
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 260, in open_project
    self.set_project_filenames(self.editor.get_open_filenames())
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 324, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/widgets/projects/type/__init__.py", line 74, in set_recent_files
    list(OrderedDict.fromkeys(recent_files)))
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 448, in set
    self._save()
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 124, in _save
    raise(e)
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 120, in _save
    _write_file(fname)
  File "/home/ashley/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/media/ashley/My Passport/linux/xray/code/project/xray/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-16 15:19
Thanks for reporting. This error appears to be a duplicate of #5765 , which is currently being looked at. If you have more details about the circumstances in which it occurs, it would be helpful to post that over there. If it is indeed a Spyder bug, it should hopefully get fixed soon, but in the meantime some workarounds for you to try:
* Restarting Spyder
* Trying to create the project somewhere else
* `spyder --reset` at the terminal/command line
* Clean uninstall and reinstall of Anaconda

Best of luck!

**Closed by CAM-Gerlach** 2017-12-16 15:19 UTC
