### ISSUE TITLE
I just tried to change the color of the background to spyder dark

### ISSUE THREAD

**Issue by finexthecat** [spyder-ide/spyder#6566] opened 2018-03-01 13:16 UTC
\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\FelixSoftware\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder\plugins\configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "C:\FelixSoftware\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by ccordoba12** [comment] 2018-03-01 13:43
Thanks for reporting. This is a duplicate of #6519.

**Closed by ccordoba12** 2018-03-01 13:43 UTC
