### ISSUE TITLE
UnicodeEncodeError when using "copy" on variable explorer.

### ISSUE THREAD

**Issue by NegativeDearc** [spyder-ide/spyder#4912] opened 2017-08-08 03:35 UTC
**What is the expected output? What do you see instead?**
Hi,
I'm using "Copy" at the variable explorer, but crashed.
I know the .to_csv() method will use "ascii" as default on py2, Can you fix this, using "utf-8"?

**Please provide any additional information below**

  File "C:\Users\datin_000\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 626, in copy
    obj.to_csv(output, sep='\t', index=index, header=header)
  File "C:\Users\datin_000\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1413, in to_csv
    formatter.save()
  File "C:\Users\datin_000\Anaconda2\lib\site-packages\pandas\io\formats\format.py", line 1583, in save
    self._save()
  File "C:\Users\datin_000\Anaconda2\lib\site-packages\pandas\io\formats\format.py", line 1670, in _save
    self._save_header()
  File "C:\Users\datin_000\Anaconda2\lib\site-packages\pandas\io\formats\format.py", line 1638, in _save_header
    writer.writerow(encoded_labels)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :

**Comment by ccordoba12** [comment] 2017-08-08 04:28
Thanks for reporting. This is a duplicate of issue #4833.

I'm sure you'll have much better luck by using Python 3 to handle Unicode data.

**Closed by ccordoba12** 2017-08-08 04:28 UTC
Labels: component:Variable Explorer, resolution:Duplicate, type:Bug
