### ISSUE TITLE
Crash of spyder when displaying the doc of some pyplot functions.

### ISSUE THREAD

**Issue by mmontarges** [spyder-ide/spyder#5774] opened 2017-11-16 14:20 UTC
## Description

**What steps will reproduce the problem?**

1. Open spyder with the help detecting the call to functions + "Render mathematical equations"
2. Try with scatter, plot or errorbars from matplotlib
3. The help displays briefly and spyder crashes
4. When running Spyder from the terminal, I just have a "Segmentation fault" message.
5. The crash triggers several SE Linux policy warnings from eu-unstrip

**What is the expected output? What do you see instead?**

The help should appear and Spyder should not crash.

**Please provide any additional information below**

For now I have only been able to trigger the crash on some functions of matplotlib.pyplot : scatter, errorbar, plot but not on imshow, matshow or subplots.

I am using Anaconda 5.0.1 on Fedora 25. Yesterday afternoon everything was ok. I tried to reinstall anaconda (hence Spyder) but the problem remains. It is happening on both my Python 2.7 and Python 3.6 environments. I am using matplotlib 2.1.0.

_The problem disappears when disabling the "Render mathematical equations" option_

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by mmontarges** [comment] 2017-11-16 14:56
Actually, opening a variable using the variable explorer causes spyder to crash too.

**Comment by ccordoba12** [comment] 2017-11-17 00:39
Thanks for reporting. This is a duplicate of issue #5514.

**Closed by ccordoba12** 2017-11-17 00:39 UTC
