### ISSUE TITLE
python crashes.. mkl_core.dll error (APP crash)

### ISSUE THREAD

**Issue by NavinSinghsays** [spyder-ide/spyder#7627] opened 2018-08-06 11:39 UTC
### What steps will reproduce the problem?

I am learning machine learning and I wam making a simple linear regression model but APPCRASH error is poping up

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-08-06 13:48
Please see issue #7357 for a solution. I'm closing this because it's not a bug in Spyder.

**Closed by ccordoba12** 2018-08-06 13:48 UTC
