### ISSUE TITLE
Support PyTorch tensors on variable explorer

### ISSUE THREAD

**Issue by dajcs** [spyder-ide/spyder#5375] opened 2017-10-02 19:24 UTC
## Description

**What steps will reproduce the problem?**

1. creating a pytorch tensor
import torch
t1 = torch.Tensor([[1,2],[3,4]])

2. viewing t1 in the variable explorer
3. scrolling down to the last attribute

**What is the expected output? What do you see instead?**
the t1 variable explorer window crashes with the error messages below

**Please provide any additional information below**

  File "/home/dajcs/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 250, in fetchMore
    self.rows_loaded + items_to_fetch)
  File "/home/dajcs/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 179, in set_size_and_type
    for index in range(start, stop) ]
  File "/home/dajcs/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 179, in <listcomp>
    for index in range(start, stop) ]
  File "/home/dajcs/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 78, in __getitem__
    return getattr(self.__obj__, key)
  File "/home/dajcs/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 374, in data
    raise RuntimeError('cannot call .data on a torch.Tensor: did you intend to use autograd.Variable?')
RuntimeError: cannot call .data on a torch.Tensor: did you intend to use autograd.Variable?

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by andfoy** [comment] 2017-10-02 20:25
@dajcs Sorry, but we currently don't support PyTorch tensors. However this is to be done on a future release of Spyder.

**Comment by ccordoba12** [comment] 2017-10-02 20:31
@andfoy, we should avoid giving this error for now.

**Comment by andfoy** [comment] 2017-10-02 20:32
@ccordoba12 Should we display a message informing that the requested data type is not supported? Or just a temporary solution for PyTorch?

**Comment by thecortex** [comment] 2018-02-04 13:22
Yes, I am having the same issue trying to run:

```

def stepfunct(x):
    inspect.getmembers(x)
    return x  # .apply(lambda i: -0.5 if x < 128 else 0.5)


kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Lambda(stepfunct)
                   ])),
    batch_size=100, shuffle=True, **kwargs)
```

```
raise RuntimeError('cannot call .data on a torch.Tensor: did you intend to use autograd.Variable?')
RuntimeError: cannot call .data on a torch.Tensor: did you intend to use autograd.Variable?

```

**Comment by goanpeca** [comment] 2020-05-05 15:36
Duplicate of #7042. Closing

**Closed by goanpeca** 2020-05-05 15:36 UTC
Labels: component:Variable Explorer, type:Enhancement
