### ISSUE TITLE
case #11316, said it will be fixed. But after 3 releases, still not fixed. 

### ISSUE THREAD

**Issue by yomoko** [spyder-ide/spyder#12688] opened 2020-05-11 00:38 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
[https://github.com/spyder-ide/spyder/issues/11316](url)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-05-11 01:50
Sorry, you're right. It's still not fixed but we'll try to do it in our next version (4.1.4), to be released in a month or so.

**Closed by ccordoba12** 2020-05-11 01:50 UTC

**Comment by ccordoba12** [comment] 2020-05-11 01:52
By the way, the real duplicate of this problem is issue #10702. So please subscribe to that issue if you want to get notifications about it.
