### ISSUE TITLE
I need to press many times return key to display output in Python Console

### ISSUE THREAD

**Issue by augustosisa** [spyder-ide/spyder#3712] opened 2016-11-20 05:45 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder and a Python Console
2. Write a simple script and run it:
    def main():
        print('First line')
        print('Second line')

    if __name__ == '__main__':
        main()
3. In Ipython console this run succesfully, but in the same spyder session I need to press many times the return key to get a result depending of the size of the scripts and the number of scripts run in the console recently

>>> runfile('E:/googledrive/problem_spyder.py', wdir='E:/googledrive')
>>> 
First line
Second line
>>> 

**What is the expected output? What do you see instead?**

In a previous version I get the output without press return key.

**Please provide any additional information below**

I just update Anaconda and Spyder, yesterday everithing was fine. So, I suppose that this issue is caused by the new version of spyder or Anaconda

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 2.7.12 (Anaconda 32)
* Operating system: Windows 8.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by augustosisa** [comment] 2016-11-20 05:59
UPDATE:

The number of return keystrokes increases when you execute multiple times the script. After run ten times the script is needed you press ten times the returnkey.

**Comment by ccordoba12** [comment] 2016-11-20 21:49
This is basically a duplicate of issue #1831. Please use the IPython console instead because we're going to disable the Python console on Windows for Spyder 3.1.

**Closed by ccordoba12** 2016-11-20 21:49 UTC
