### ISSUE TITLE
Spyder error messages

### ISSUE THREAD

**Issue by michaelgtadesse** [spyder-ide/spyder#10018] opened 2019-08-14 12:30 UTC
### What steps will reproduce the problem?

Spyder is continuously spitting back a dialogue box with the following message: 
"spyder has encountered an internal problem!
Actually I dont see any problem, Spyder just doesn't allow me to work, since I have to close the dialogue box every time it pops up.

### Traceback
```python-traceback
  File "C:\Users\mi292519\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 140, in process_signature
TypeError: 'NoneType' object is not subscriptable
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-08-14 12:34
Duplicate of #9993. For now you need to uninstall Kite to avoid seeing this error message.

**Closed by ccordoba12** 2019-08-14 12:34 UTC
