### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by jacobitosuperstar** [spyder-ide/spyder#5448] opened 2017-10-12 01:01 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Family\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1370, in close_file
    self.remove_from_data(index)
  File "C:\Users\Family\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1163, in remove_from_data
    self.update_fileswitcher_dlg()
  File "C:\Users\Family\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 822, in update_fileswitcher_dlg
    self.fileswitcher_dlg.setup()
  File "C:\Users\Family\Anaconda3\lib\site-packages\spyder\widgets\fileswitcher.py", line 757, in setup
    current_path = self.current_path
  File "C:\Users\Family\Anaconda3\lib\site-packages\spyder\widgets\fileswitcher.py", line 346, in current_path
    return self.paths_by_widget[self.get_widget()]
KeyError: None

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :

**Comment by ccordoba12** [comment] 2017-10-12 02:20
Thanks for reporting. This is a duplicate of issue #5317 and it'll be fixed in our **3.2.4** version.

**Closed by ccordoba12** 2017-10-12 02:20 UTC
