### ISSUE TITLE
Dask delayed and Spyder show errors

### ISSUE THREAD

**Issue by arthurrinaldi** [spyder-ide/spyder#17018] opened 2021-12-14 11:24 UTC
### What steps will reproduce the problem?

Read parquet files using dask delayed in the function below and then compute the dataframe.

After this, just printing the columns names in the IPython console show this error window.

```
def ddf_from_parquet(pattern, slct_run_id=None, as_df=False, columns=None):
    '''Read all parquet files of a certain file name pattern with certain run_ids'''
    @delayed
    def load_chunk(pth, columns):
        return ParquetFile(pth).to_pandas(columns=columns)#.set_index('run_id')

    files = get_file_list(glob(sc_out + pattern), slct_run_id)
    assert len(files) > 0, f'Pattern {sc_out + pattern} yields empty file list.'
    ddf = dd.from_delayed([load_chunk(f, columns=columns) for f in files])
    if as_df:
        ddf = ddf.compute()
    
    return ddf
```
    
 

### Traceback
```python-traceback
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 236, in _handle_remote_call_reply
    super(KernelComm, self)._handle_remote_call_reply(
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 473, in _handle_remote_call_reply
    callback(buffer)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 74, in set_namespace_view
    self.namespacebrowser.process_remote_view(view)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 399, in process_remote_view
    self.set_data(remote_view)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 408, in set_data
    if data != self.editor.source_model.get_data():
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/dask/delayed.py", line 573, in __bool__
    raise TypeError("Truth of Delayed objects is not supported")
TypeError: Truth of Delayed objects is not supported
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.1
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.29.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.10.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  3.0.3 (OK)
qtawesome >=0.5.7               :  1.1.1 (OK)
qtconsole >=5.0.1               :  5.2.1 (OK)
qtpy >=1.5.0                    :  1.11.3 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.3.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.1.6 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.1 (OK)
numpy >=1.7                     :  1.20.3 (OK)
pandas >=1.1.1                  :  1.1.2 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by dalthviz** [comment] 2021-12-15 14:49
Hi @arthurrinaldi thank you for the feedback! I think this could be a duplicate of https://github.com/spyder-ide/spyder/issues/16844

Basically we don't yet handle the delayed representation that Dask uses when we interact with the namespace of the kernel to show it in the Variable Explorer. I think the update logic of the namespace representation gets triggered always after you try to run anything in the console to update the representation of the namespace) but it's something we will try to check in a future release :+1:

Let us know if that makes sense!

Also pinging @ccordoba12 just in case (maybe he has a better explanation of what is happening)

**Comment by arthurrinaldi** [comment] 2021-12-15 17:10
Hi @dalthviz, thanks a lot for your answer.  

It's kind of make sense to me but the thing is that I used before dask delayed representation with Spyder 3 (I don't remeber which version exactly) and it was working perfectly fine.

So maybe the way to interact with the namespace of the kernel to show it in the Variable Explorer changed from Spyder 3 to Spyder 4 and maybe it wasn't triggered every time we run something in the console.

Hope this helps.
Arthur

**Comment by ccordoba12** [comment] 2021-12-15 17:16
As @dalthviz mentioned, this is a duplicate of issue #16844, so I'm going to close it in favor of that one. We'll try to fix it in our next release.

> So maybe the way to interact with the namespace of the kernel to show it in the Variable Explorer changed from Spyder 3 to Spyder 4

Yes, it did, and in a lot of very important ways.

**Closed by ccordoba12** 2021-12-15 17:16 UTC
Labels: component:Variable Explorer, component:IPython Console, status:Awaiting Followup
