### ISSUE TITLE
Crash on start because of problems with the PyQt 5.7 wheels

### ISSUE THREAD

**Issue by domingues** [spyder-ide/spyder#3520] opened 2016-10-10 15:17 UTC
## Description of your problem

**What steps will reproduce the problem?**
1. $ pip3 install spyder pyqt5
2. $ spyder

**What is the expected output? What do you see instead?**
Starting Spyder shows a splash screen and then crashes.

**Please provide any additional information below**

> [1010/161255:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
> Segmentation fault (core dumped)
## Versions and main components
- Spyder Version: 3.0.0
- Python Version: 3.5.2
- Operating system: up-to-date Ubuntu 16.04

**Comment by ccordoba12** [comment] 2016-10-10 19:46
Please take a look at this comment

https://github.com/electron/electron/issues/1482#issuecomment-95766560

This seems to be caused by a failure in your video drivers.

----

This other answer explains how to remove the sandbox error:

http://askubuntu.com/questions/329320/chromium-running-without-the-suid-sandbox-error

**Comment by aloerch** [comment] 2016-10-15 20:36
I am also receiving this error. The above suggestion and link, that says this is related to video drives, seems unlikely. First, the person stating it was because of virtualbox video drivers did NOT provide details and furthermore, I'm using Ubuntu 16.04 as my primary installation (not virtual) with the nvidia drivers for my card. Everything with the drivers works fine, including cuda, cudnn, and things like tensorflow with GPU support.

"[1015/133052:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Segmentation fault
"

**Comment by ccordoba12** [comment] 2016-10-15 20:47
Did you try the second answer?

**Comment by aloerch** [comment] 2016-10-15 20:59
The second answer is related to the sandbox, correct? I do not care really whether the sandbox is on or off, the problem is the segmentation fault followed by spyder failing to run. The splash screen appears, and the program crashes. It works OK with python 2.7 and spyder 2.3.8.

**Comment by ccordoba12** [comment] 2016-10-15 21:18
But the segmentation fault could be caused by the sandbox problem too, so please try that answer.

**Comment by aloerch** [comment] 2016-10-15 21:33
I understand what you are saying about the sandbox problem, however, the 2nd answer above that deals with the sandbox error specifically deals with this:
"'I've downloaded and unpacked a fresh copy of Chromium (Linux_x64), and when I try to run the chrome binary, this happens:" 
followed by the sandbox error (when running the chrome binary).

I do not have that problem. When I run my chrome binary from command line, it runs without any error. The suggested solutions involve downloading some random version of chrome (chrome-linux.zip) and changing it's (the random version's) permissions... I'm not going to do THAT.

I'm not sure why running spyder utlizes chrome at all... I'm also not sure why it works fine with python 2.7 and spyder 2.3.8...

I have production work to do, so I'm going to go back to using Vim for now... I'll keep my eyes on spyder's github for a fix down the road.

**Comment by ccordoba12** [comment] 2016-10-15 21:35
Qt 5 comes with bindings for Chromium, that's why that answer applies here too.

**Comment by karlTUM** [comment] 2016-10-16 15:34
How to solve that problem? I met the same problem.

**Comment by domingues** [comment] 2016-10-16 23:52
I don't think that the issue is related to the Chromium sandbox. I had installed Spyder in a Xubuntu VM it show the same warning about the sandbox but no segmentation fault, it starts.

**Comment by ccordoba12** [comment] 2016-10-17 02:47
@domingues, good to know! Then it seems to be a drivers problem :-)

**Comment by aloerch** [comment] 2016-10-17 03:08
A drivers problem that literally affects only Spyder 3.0, and no other program and no other earlier version of Spyder? ok......

If you aren't interested in taking this bug seriously and resolving the issue in Spyder, then you should close the issue as resolved, and mark the resolution as "some unique driver problem affecting only Spyder 3.0".

I'm not sure how else to make it clear that the drivers (at least in my case) are fine...  Spyder 2.3.8 opens no problem, I have the latest stable nvidia driver install and working, as demonstrated by the simple fact that KDE 5 runs smoothly and looks great, as does tensorflow with GPU (which requires working nvidia driver, working installation of CUDA 7.5, and working installation of cuDNN 5.1. Given that all of the above = True, I find it difficult to believe and understand how you can insist this is either a non-existent issue with chrome sandbox or a display driver.

**Comment by aloerch** [comment] 2016-10-17 03:53
Because I've found some spare time:

Running the Spyder 3.0 "mainwindow.py" from within a running instance of Spyder 2.3.8 causes Spyder 3.0 to load perfectly fine! 

What I noticed about this is that when running Spyder 3.0's "mainwindow.py" from within Spyder 2.3.8, is that the new instance of Spyder (3.0) is using Qt 4.8.7, and PyQt4 NOT QT 5-5. Doing this, there are no "SEGMENTATION FAULT" errors. 

I would say that Spyder 3.0 is NOT compatible with QT5-5.7.

**Comment by ccordoba12** [comment] 2016-10-17 04:56
@aloerch, I'm taking this bug seriously (else I'd have closed it as *Won't fix*), But (I'm almost sure) the bug is not in Spyder, it's in the interaction between the PyQt 5.7 wheels and your video drivers.

Look,  by your comments it's clear you don't understand all issues involved in this problem:

> Spyder 2.3.8 opens no problem

Spyder 2.3 is only compatible with PyQt4, and this problem is related to the fact that Qt/PyQt **5.6+** comes with bindings for Chromium, and Chromium uses OpenGL to accelerate web page rendering.

> KDE 5 runs smoothly and looks great

KDE 5 uses Qt 5.5 (at least in Kubuntu 16.04), not Qt/PyQt 5.7. The new Chromium-based web backend for Qt was made the default in 5.6 (although it was introduced in Qt 5.4 as a technology preview, but not used over the Webkit-based backend until 5.6, and Webkit didn't have this problem).

> What I noticed about this is that when running Spyder 3.0's "mainwindow.py" from within Spyder 2.3.8, is that the new instance of Spyder (3.0) is using Qt 4.8.7

Nonsense again because you're running Spyder 3.0 with Qt 4, which doesn't have this problem.

> I would say that Spyder 3.0 is NOT compatible with QT5-5.7.

It is, I tested it last week with PyQt 5.7 and it's running perfectly fine. But I did it using the Intel drivers, not the Nvidia ones.

----

> I find it difficult to believe and understand how you can insist this is either a non-existent issue

Please take a look at all the comments I posted on this issue and tell me in what place I said that this is *a non-existent issue*. Nonsense again :-p

Look man, if you don't understand what you're talking about, please avoid posting throlling comments.

**Comment by ccordoba12** [comment] 2016-10-17 04:57
So I'll test Spyder with Nvidia drivers and come to you guys to let you know what I find :-)

But in the mean time, please use Anaconda, which comes with Qt 5.6 and doesn't have this problem because it uses the Webkit-based backend :-)

**Comment by aloerch** [comment] 2016-10-17 05:30
Can you please explain, since I'm clearly ignorant ("if you don't understand what you're talking about"), how it is that if webkit was used and worked in 5.6, and how if you're confident Spyder 3.0 would work with 5.6, that the problem is my display driver? My display driver does not change between 5.6 and 5.7, only the QT version does... and since you think it may be an OpenGL issue with my graphics driver, I've provided additional info below. For the record, I routinely use Agisoft Photoscan on this machine, which makes HEAVY use of my 3 nvidia cards using OpenGL (not CUDA). 

Here's some more info for you:

I'm using Chrome v 54

I've enabled WebGL hardware acceleration in the browser just now to show that it works (from chrome://gpu):
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Software only, hardware acceleration unavailable
Video Encode: Hardware accelerated
VPx Video Decode: Software only, hardware acceleration unavailable
WebGL: Hardware accelerated

When I run /usr/bin/google-chrome-stable from command line, chrome launches with WebGL enabled with no problem. 

Output of lshw -c video:
```
*-display               
       description: VGA compatible controller
       product: GM204 [GeForce GTX 970]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:03:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
```

Output of nvidia-smi:
```
Oct 16 22:25:05 2016       
| NVIDIA-SMI 370.28                 Driver Version: 370.28
```

**Comment by ccordoba12** [comment] 2016-10-17 05:47
@aloerch, sorry, I didn't want to be harsh or rude, but it seems my comments (for not being comprehensive enough) generated confusion in your side from the beginning :-)

I don't think the problem is related to your drivers *per se*. I think the problem is in the PyQt 5.7 wheels and how they interact with your Nvidia drivers.

As you said, your drivers are working correctly and I can't deny that. Even Chrome is working fine you (which is great).

So the problem is most probably in how the PyQt 5.7 wheels are linked (or try to load?) your Nvidia drivers. That's my best hypothesis and to confirm it, could I ask you to use your Intel drivers and try to start again?

**Comment by karlTUM** [comment] 2016-10-17 08:10
I use ubuntu16.10. I uninstall the PyQt5.7 and reinstall PyQt4. The problem does not come out.

**Comment by ccordoba12** [comment] 2016-10-17 14:20
@karlTUM, yes, the problem only appears with PyQt5.7 (it seems), so using PyQt4 is a temporal solution :-)

**Comment by domingues** [comment] 2016-10-18 11:27
We are in the right direction. I installed PyQt5.6 (pip install pyqt5==5.6) and Spyder starts. So the problem is with PyQt5.7.

I swapped the Nvidia drivers with the open source Nouveau, and now the things get weird.

In the first try:
> [1018/121819:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
> Segmentation fault (core dumped)

In the second:
> [1018/120807:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See 
> https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
> nouveau: kernel rejected pushbuf: No such file or directory
> nouveau: ch6: krec 0 pushes 0 bufs 2 relocs 0
> nouveau: ch6: buf 00000000 00000002 00000004 00000004 00000000
> nouveau: ch6: buf 00000001 00000006 00000004 00000000 00000004
> nouveau: ch6: buf 00000002 00000018 00000002 00000002 00000000
> nouveau: ch6: buf 00000003 00000007 00000002 00000002 00000000
> nouveau: ch6: buf 00000004 00000008 00000002 00000002 00000000
> nouveau: ch6: buf 00000005 0000000b 00000002 00000002 00000000
> nouveau: ch6: buf 00000006 0000000a 00000002 00000002 00000002
> nouveau: ch6: buf 00000007 00000029 00000002 00000000 00000002
> nouveau: ch6: buf 00000008 0000002a 00000002 00000000 00000002
> Segmentation fault (core dumped)

In the third:
Same chromium warning but **it runs!**

Fourth attempt:
> [1018/121826:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
> python3: ../../nouveau/pushbuf.c:727: nouveau_pushbuf_data: Assertion `kref' failed.
> Aborted (core dumped)

**Comment by kuo000** [comment] 2016-12-17 23:11
I ran into this exact same problem. Even using PyQt 5.6 does not work for me. What is the current status of this issue? Has there been a workaround?

I cannot swap the graphics drive for Nvidia card since I use CUDA and gpu computing on a regular basis. Thanks.

**Comment by ccordoba12** [comment] 2016-12-17 23:15
@kuo000, there's a simple solution: don't use PyQt wheels and use instead Continuum's Anaconda distribution (which doesn't have this problem).

**Comment by kuo000** [comment] 2016-12-17 23:27
OK. Thanks @ccordoba12 . I don't really use Anaconda since I had some bad experience of messing things up installing two versions of python on my system, but I might give it a try here.

BTW, do you see this problem to be fixed soon?

**Comment by ccordoba12** [comment] 2016-12-17 23:30
We can't do anything about it in our side. It's a problem with PyQt or even Qt itself.

I think it could be fixed once Qt/PyQt 5.8 is released.

**Comment by kuo000** [comment] 2016-12-17 23:35
Alright. Thanks. Hopefully it will be fixed soon.

**Comment by ccordoba12** [comment] 2017-08-14 13:56
Closing because we haven't heard about this problem in a long time.

**Closed by ccordoba12** 2017-08-14 13:56 UTC
