### ISSUE TITLE
viewing an enum instance in the variable explorer

### ISSUE THREAD

**Issue by SimonDeRidder** [spyder-ide/spyder#7943] opened 2018-09-24 11:32 UTC
### What steps will reproduce the problem?

I defined a class, which inherits from the Enum class in package enum, with only class objects defined, as one would for an enum.
During debugging of my code I wanted to view an object of this class.
The type was listed as 'None' in the variable explorer, though the value indicated it was on object of the enum class.
On double-clicking, this error was produced.

### Traceback
```python-traceback
  File "d:\program files\python3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 544, in createEditor
    readonly=readonly)
  File "d:\program files\python3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1356, in setup
    remote=remote)
  File "d:\program files\python3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1302, in __init__
    title)
  File "d:\program files\python3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1179, in __init__
    minmax=minmax)
  File "d:\program files\python3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 135, in __init__
    self.set_data(data)
  File "d:\program files\python3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 175, in set_data
    self.title += data_type
TypeError: Can't convert 'NoneType' object to str implicitly
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.5.1
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.5.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.14.5 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  1.5.1 (NOK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-09-24 15:14
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment] 2018-12-05 20:45
Closing as a duplicate of #8169.

**Closed by ccordoba12** 2018-12-05 20:45 UTC
Labels: component:Variable Explorer, type:Bug
