### ISSUE TITLE
Rebooting kernel

### ISSUE THREAD

**Issue by jvbmov** [spyder-ide/spyder#15343] opened 2021-04-19 08:18 UTC
### What steps will reproduce the problem?

Clicking the close kernel (py 3.6.13, ipython 7.13.0) button resulted in this crash

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\boekej\Miniconda3\envs\arcgis26\lib\logging\__init__.py", line 996, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\boekej\Miniconda3\envs\arcgis26\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\boekej\Miniconda3\envs\arcgis26\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "C:\Users\boekej\Miniconda3\envs\arcgis26\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\boekej\Miniconda3\envs\arcgis26\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "C:\Users\boekej\Miniconda3\envs\arcgis26\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.00092339515686,)
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.6.13
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.13.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.2.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.0 (OK)
pygments >=2.0                :  2.6.1 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  46.1.3.post20200330 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  19.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.2.1 (OK)
numpy >=1.7                   :  1.18.5 (OK)
pandas >=1.1.1                :  1.1.5 (OK)
scipy >=0.17.0                :  1.4.1 (OK)
sympy >=0.7.3                 :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2021-04-19 16:12
Hey @jvbmov, thanks for reporting. Please close Spyder, open the Anaconda prompt and run there

    conda install jupyter_client=6.1.12

That should solve your problem.

**Comment by jvbmov** [comment] 2021-04-20 12:25
That version of jupyter_client was already part of the env :)

![afbeelding](https://user-images.githubusercontent.com/41989690/115395421-275db480-a1e4-11eb-8462-fe64595a947e.png)

**Comment by ccordoba12** [comment] 2021-04-20 14:06
@jvbmov, ok, thanks for checking that.

@impact27, any ideas about this?

**Comment by impact27** [comment] 2021-04-20 15:03
Is this reproducible or a one off? Maybe there is a race when closing the kernel

**Comment by ccordoba12** [comment] 2021-04-22 17:03
Closing as a duplicate of issue #15356. It's not exactly the same problem, but the cause is the same.

**Closed by ccordoba12** 2021-04-22 17:03 UTC
Labels: status:Awaiting Followup
