### ISSUE TITLE
Online Help Error

### ISSUE THREAD

**Issue by Ajacks222** [spyder-ide/spyder#8743] opened 2019-02-09 23:50 UTC
### What steps will reproduce the problem?

1. Launch Spyder
2. Click Online Help
3. Click Any Library for Details
4. Recieve the Error "Unable to load"

I have the trouble shoots and have not had any luck. What might be causing this issue?

Sincerely,
Adrian

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  2.1.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-12 17:02
@CAM-Gerlach, are you able to reproduce this one?

**Comment by CAM-Gerlach** [comment] 2019-02-12 19:32
@ccordoba12 Yup; I already did so on #5533 , a duplicate of this one, which you closed with the message:

> Sorry, this is not a Spyder issue. The only thing we do is to render what the pydoc module provides.

**Comment by ccordoba12** [comment] 2019-02-13 08:42
Ok, sorry for the hassle.

**Closed by ccordoba12** 2019-02-13 08:42 UTC

**Comment by CAM-Gerlach** [comment] 2019-02-13 22:59
No worries; you know how often I forget/miss other issues being open and hassle you about things, heh.
