### ISSUE TITLE
This "iteritems()" is deprecated

### ISSUE THREAD

**Issue by dan123456-eng** [spyder-ide/spyder#20652] opened 2023-03-07 16:54 UTC
## Problem Description
![erro1](https://user-images.githubusercontent.com/61120620/223492673-d4d47122-cdc0-4189-8978-7090869d50ad.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.3.2
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows10

**Comment by ccordoba12** [comment] 2023-03-07 17:08
Hey @dan123456-eng, thanks for reporting. This is a duplicate of issue #20496, so I'm going to close it in favor of that one.

**Closed by ccordoba12** 2023-03-07 17:08 UTC

**Comment by dan123456-eng** [comment] 2023-03-07 18:42
Hi @ccordoba12, tks!
