### ISSUE TITLE
Help in editor not working

### ISSUE THREAD

**Issue by kibbutzelot** [spyder-ide/spyder#6407] opened 2018-02-07 21:10 UTC
## Description

**What steps will reproduce the problem?**

1. press CTRL + I in editor
2. 
3. 

**What is the expected output? What do you see instead?**
help is shown

**Please provide any additional information below**
- "object" in help pane stays empty
- help working in Console..
- code completion not working as well

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-07 21:17
This is a duplicate of issue #5782. Please read that a issue for a fix.

**Closed by ccordoba12** 2018-02-07 21:17 UTC

**Comment by kibbutzelot** [comment] 2018-02-07 21:41
this does not solve the issue, no enum installed..

**Comment by ccordoba12** [comment] 2018-02-07 21:47
It's `enum34`.

**Comment by kibbutzelot** [comment] 2018-02-07 21:48
enum34 ist not installed..

**Comment by ccordoba12** [comment] 2018-02-07 21:50
Sorry, we don't have other explanations for this problem.

**Comment by kibbutzelot** [comment] 2018-02-07 21:52
its just the standard anaconda installation didnt do anything special to it, all packages are up to date, there must be a solution..

**Comment by kibbutzelot** [comment] 2018-02-07 21:52
is there some kind of log i could provide to fix it?

**Comment by ccordoba12** [comment] 2018-02-07 22:00
You can open a terminal, run

    set SPYDER_DEBUG "3"
    spyder

and check the output for errors.

**Comment by kibbutzelot** [comment] 2018-02-07 22:07
the environment variable ist not defined thus
set spyder_debug "3" 
does not work

**Comment by kibbutzelot** [comment] 2018-02-07 22:10
after i do spyder --reset, help shows the file name of the file in editor :)

**Comment by kibbutzelot** [comment] 2018-02-07 22:30
here i give the output of debug 3 startup, seems there is an issue with jedi

Start of MainWindow constructor
appusermodelid: 0
End of MainWindow constructor
*** Start of MainWindow setup ***
  ..core actions
  ..toolbars
  ..tools
  ..sift?
  ..plugin: internal console
    ..internal console: initializing
  ..plugin: working directory
Loading help...
Loading outline explorer...
Loading editor...
Introspection Plugin Loaded: rope
Introspection Plugin Loaded: jedi
Introspection Plugin Loaded: fallback
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x0000019ED0A0B948>
current_changed: 0 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x0000019ED0A0B948> 1781616654664
Added thread <spyder.widgets.editor.AnalysisThread object at 0x0000019ED0A0B8B8> to queue
Added thread <spyder.widgets.editor.AnalysisThread object at 0x0000019ED0A358B8> to queue
  ..widgets
Loading file explorer...
Loading history plugin...
Updating queue:
    started: 0
    pending: 2
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x0000019ED0A0B8B8>
Updating queue:
    started: 1
    pending: 1
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x0000019ED0A358B8>
Loading online help...
Updating queue:
    started: 0
    pending: 0
Updating queue:
    started: 0
    pending: 0
Loading project explorer...
Loading namespace browser...
Loading IPython console...
Setting up main window...
Setting up window...
*** End of MainWindow setup ***
Call to 'close_threads'
Initialized fallback
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x0000019ED0A1BF78>
current_changed: 0 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x0000019ED0A1BF78> 1781616721784
Errored rope
b''
b'Traceback (most recent call last):\r\n  File "plugin_server.py", line 127, in <module>\r\n    plugin = PluginServer(*args)\r\n  File "plugin_server.py", line 27, in __init__\r\n    self.object = self.initialize(*args)\r\n  File "plugin_server.py", line 115, in initialize\r\n    fromlist=[mod_name])\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\spyder\\utils\\introspection\\rope_plugin.py", line 29, in <module>\r\n    rope_patch.apply()\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\spyder\\utils\\introspection\\rope_patch.py", line 54, in apply\r\n    from rope.base import pycore\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\rope\\base\\pycore.py", line 6, in <module>\r\n    import rope.base.libutils\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\rope\\base\\libutils.py", line 6, in <module>\r\n    from rope.base import pyobjectsdef\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\rope\\base\\pyobjectsdef.py", line 5, in <module>\r\n    import rope.base.oi.soi\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\rope\\base\\oi\\soi.py", line 11, in <module>\r\n    from rope.base.oi.type_hinting.factory import get_type_hinting_factory\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\rope\\base\\oi\\type_hinting\\factory.py", line 2, in <module>\r\n    from rope.base.oi.type_hinting.providers import (\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\rope\\base\\oi\\type_hinting\\providers\\numpydocstrings.py", line 11, in <module>\r\n    from numpydoc.docscrape import NumpyDocString\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\numpydoc\\__init__.py", line 5, in <module>\r\n    from .numpydoc import setup\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\numpydoc\\numpydoc.py", line 31, in <module>\r\n    from .docscrape_sphinx import get_doc_object, SphinxDocString\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\numpydoc\\docscrape_sphinx.py", line 11, in <module>\r\n    from jinja2 import FileSystemLoader\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jinja2\\__init__.py", line 82, in <module>\r\n    _patch_async()\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jinja2\\__init__.py", line 78, in _patch_async\r\n    from jinja2.asyncsupport import patch_all\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jinja2\\asyncsupport.py", line 13, in <module>\r\n    import asyncio\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\asyncio\\__init__.py", line 21, in <module>\r\n    from .base_events import *\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\asyncio\\base_events.py", line 17, in <module>\r\n    import concurrent.futures\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\concurrent\\futures\\__init__.py", line 8, in <module>\r\n    from concurrent.futures._base import (FIRST_COMPLETED,\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\concurrent\\futures\\_base.py", line 381\r\n    raise exception_type, self._exception, self._traceback\r\n                        ^\r\nSyntaxError: invalid syntax\r\n'
Errored jedi
b''
b'Traceback (most recent call last):\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\spyder\\utils\\introspection\\jedi_plugin.py", line 27, in <module>\r\n    jedi = jedi_patch.apply()\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\spyder\\utils\\introspection\\jedi_patch.py", line 29, in apply\r\n    raise ImportError("jedi not =0.9.0 or 0.10.0, can\'t be patched")\r\nImportError: jedi not =0.9.0 or 0.10.0, can\'t be patched\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "plugin_server.py", line 127, in <module>\r\n    plugin = PluginServer(*args)\r\n  File "plugin_server.py", line 27, in __init__\r\n    self.object = self.initialize(*args)\r\n  File "plugin_server.py", line 115, in initialize\r\n    fromlist=[mod_name])\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\spyder\\utils\\introspection\\jedi_plugin.py", line 29, in <module>\r\n    import jedi\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\__init__.py", line 41, in <module>\r\n    from jedi.api import Script, Interpreter, set_debug_function, \\\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\api\\__init__.py", line 23, in <module>\r\n    from jedi.api import classes\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\api\\classes.py", line 15, in <module>\r\n    from jedi.evaluate import imports\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\evaluate\\__init__.py", line 81, in <module>\r\n    from jedi.evaluate.context import ClassContext, FunctionContext, \\\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\evaluate\\context\\__init__.py", line 3, in <module>\r\n    from jedi.evaluate.context.function import FunctionContext, FunctionExecutionContext\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\evaluate\\context\\function.py", line 8, in <module>\r\n    from jedi.evaluate import docstrings\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jedi\\evaluate\\docstrings.py", line 46, in <module>\r\n    from numpydoc.docscrape import NumpyDocString\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\numpydoc\\__init__.py", line 5, in <module>\r\n    from .numpydoc import setup\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\numpydoc\\numpydoc.py", line 31, in <module>\r\n    from .docscrape_sphinx import get_doc_object, SphinxDocString\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\numpydoc\\docscrape_sphinx.py", line 11, in <module>\r\n    from jinja2 import FileSystemLoader\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jinja2\\__init__.py", line 82, in <module>\r\n    _patch_async()\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jinja2\\__init__.py", line 78, in _patch_async\r\n    from jinja2.asyncsupport import patch_all\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\jinja2\\asyncsupport.py", line 13, in <module>\r\n    import asyncio\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\asyncio\\__init__.py", line 21, in <module>\r\n    from .base_events import *\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\asyncio\\base_events.py", line 17, in <module>\r\n    import concurrent.futures\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\concurrent\\futures\\__init__.py", line 8, in <module>\r\n    from concurrent.futures._base import (FIRST_COMPLETED,\r\n  File "C:\\Users\\sknue\\AppData\\Local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\concurrent\\futures\\_base.py", line 381\r\n    raise exception_type, self._exception, self._traceback\r\n                        ^\r\nSyntaxError: invalid syntax\r\n'
Added thread <spyder.widgets.editor.AnalysisThread object at 0x0000019ED0A1BB88> to queue
Added thread <spyder.widgets.editor.AnalysisThread object at 0x0000019ED3754288> to queue
Updating queue:
    started: 0
    pending: 2
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x0000019ED0A1BB88>
Updating queue:
    started: 1
    pending: 1
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x0000019ED3754288>
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x0000019ED3754798>
current_changed: 1 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x0000019ED3754798> 1781664139160
Updating queue:
    started: 0
    pending: 0
Updating queue:
    started: 0
    pending: 0
info request
No valid responses acquired

**Comment by ccordoba12** [comment] 2018-02-07 22:53
> File "C:\Users\sknue\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\concurrent\futures\_base.py", line 381\r\n raise exception_type, self._exception, self._traceback\r\n ^\r\nSyntaxError: invalid syntax\r\n'

You're getting a SyntaxError from the `concurrent.futures` package. That usually happens when you installed a Python 2 package in Python 3, or viceversa.

**Comment by kibbutzelot** [comment] 2018-02-09 19:04
ho can i find out which package i is the problem?

**Comment by kibbutzelot** [comment] 2018-02-09 19:05
how can i find out which package is python 2?

**Comment by ccordoba12** [comment] 2018-02-09 20:01
I told you: `concurrent.futures`

**Comment by kibbutzelot** [comment] 2018-02-09 20:36
fuck its working now :) its pip, not visible in anaconda environment.. seems the tensorflow environment loads an old version of "futures" which ruins spyder :( tx for your support!!!!!!!!!!!! 🥇

**Comment by kibbutzelot** [comment] 2018-02-09 20:39
thanks for your patience, hope this will help others as well, the debuging was working fine in the end 👍

**Comment by ccordoba12** [comment] 2018-02-09 20:45
Great, nice to know you were able to solve this problem!

**Comment by VanitarNordic** [comment] 2018-05-13 07:25
You can use  `conda install -c hesi_m keras ` to install the latest version of Keras (2.1.6) and Tensorflow(1.8) for you. Unfortunately some Anaconda packages are outdated and people have to install them by the `Pip` which causes package conflicts with the conda and pip.
