### ISSUE TITLE
run python issue

### ISSUE THREAD

**Issue by elaine15999** [spyder-ide/spyder#5623] opened 2017-10-31 16:18 UTC
## Description

**What steps will reproduce the problem?**

1. No IPython console is currently available to run XXX.py Please open a new one and try again
2. I don't solve it
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 838, in toggle_plain_text
    self.force_refresh()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 750, in force_refresh
    self.set_object_text(None, force_refresh=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 765, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 928, in show_help
    shell = self.get_shell()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 890, in get_shell
    if not hasattr(self.shell, 'get_doc') or not self.shell.is_running():
AttributeError: 'InternalShell' object has no attribute 'is_running'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.

**Comment by ccordoba12** [comment] 2017-10-31 17:00
Thanks for reporting. This is a duplicate of issue #5559.

**Closed by ccordoba12** 2017-10-31 17:00 UTC
