### ISSUE TITLE
Completion Linting Error

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#11976] opened 2020-03-25 13:43 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The warning message can be seen below, to reproduce the error it just appears whenever the memory runs low on my pc when I'm manipulating large tables in Pandas. I read in previous related issues on the same to give the firewall exceptions to spyder.exe.. I did this also and restarted and still it appears every once in a while... I never had this issue when I was using the 3.7 version of spyder, but in 4.0 this issue is showing up everyday.

<img width="244" alt="Issue" src="https://user-images.githubusercontent.com/62237347/77541374-e2623400-6ea4-11ea-9706-3cafbff9caa4.PNG">

![image](https://user-images.githubusercontent.com/62237347/77541816-8055fe80-6ea5-11ea-825d-70a3c1fe9651.png)

### What steps reproduce the problem?

1. working with spyder for a bit and using a lot of processing with pandas, happens randomly, but when it starts you cannot stop it until you restart spyder. Then the issue happens again.

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.4 64 bit
* Qt version: 5.9.6
* PyQt version:  5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-25 17:24
Duplicate of #11026

**Closed by ccordoba12** 2020-03-25 17:24 UTC

**Comment by ccordoba12** [comment] 2020-03-25 17:26
We're working on a fix for this right now and it'll be part of 4.1.2, to be released this weekend or next week at most. Sorry for the inconvenience.

Besides, you need to give permissions to the `python.exe` and `pythonw.exe` executables present in the Anaconda installation or the same conda environment from which Spyder is started.
