### ISSUE TITLE
Outline pane not following the right module after module renaming?

### ISSUE THREAD

**Issue by capitanevs** [spyder-ide/spyder#20583] opened 2023-02-22 12:29 UTC
I post this, as it seems to be a not reported issue. Please, redirect the thread in case I am wrong, or in the case it has been solved in recent updates (being up-to date is anyway a cost and a risk, so I am not always up to date:)

Spyder IDE 5.1.5
Python 3.9.12 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10 (in Anaconda)

**Issue:**
The outline pane is not always linking to the right module. The issue caused a lot of trouble to me, because I happened to edit a certain module, thinking it was another one.

**Example**
1) I am working on `diffraction_from_slit_simple_simple.py`
2) I click on a given bookmark in the outline pane (which reports the RIGHT filename on it)
3) The editor OPENS the previous version of the file `diffraction_from_slit_simple.py`, and make me edit this.
See picture belows.
![immagine](https://user-images.githubusercontent.com/13431660/220618671-ab123c25-5766-422c-8dd5-ca48f64f583d.png)
![immagine](https://user-images.githubusercontent.com/13431660/220619088-cabf166a-143b-4c1f-8d3f-5ef7a73fbc39.png)

**The same is happening with `mymodule.py`**
![immagine](https://user-images.githubusercontent.com/13431660/220619268-d62bfe7f-1fb0-4640-9055-6b888a1bc0df.png)
After clicking on "x" function, the editor throws me to `untitled0.py`
![immagine](https://user-images.githubusercontent.com/13431660/220619450-e8cd0544-44f3-4490-83bc-05bd6eee456a.png)

**How to reproduce it**
I have not spent time on this yet. It happens after renaming, but not all of the times.
If this issue is not known, I can further investigate this.

Thanks for your cooperation,
Mike

**Comment by ccordoba12** [comment] 2023-02-22 14:55
Hey @capitanevs, thanks for reporting. This is a duplicate of issue #15517 and it's fixed in our latest version (5.4.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, you need to close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-env -c conda-forge spyder
        conda activate spyder-env
        spyder

**Closed by ccordoba12** 2023-02-22 14:55 UTC
