### ISSUE TITLE
Autocomplete  extra words 

### ISSUE THREAD

**Issue by MH-Dev20** [spyder-ide/spyder#19040] opened 2022-08-12 22:26 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
Hi,
I have installed Spyder IDE 5.2.2. I have an issue with Autocomplete. It is not deleting the words that I typed at the first. For example I have the following code:

import pandas as pd 
df = pd.read_csv('Name of CSV file')

if I type "pd.rea" then it start showing me a list of possible items. Let's say I pick "read_csv" then it shows the following code for me.
df= pd.reread_csv(). As you can see it doesn't remove the words that I typed and I need back and correct it.

Thank you in advance for your help.

**Comment by MH-Dev20** [comment] 2022-08-12 22:53
Hi,
I found that the problem exists only on my old files if I open them for edit but if I open a new file there is no issue.

Regards,

**Comment by dalthviz** [comment] 2022-08-15 16:46
Hi @MH-Dev20 thank you for the feedback! I was unable to reproduce this with Spyder latest version (5.3.2). Since seems like you are using the Anaconda distribution and the default anaconda channel, if you want to install the latest Spyder version you will need to either:

* Install Spyder with our standalone installers (if you are on Windows or MacOS) from our release page: https://github.com/spyder-ide/spyder/releases/latest 
* Create a new conda environment using the conda-forge channel to get the packages (you will also need to install alongside Spyder in the new environment any packages you want to use as for example `pandas`) running from an Anaconda prompt something like:

        conda create -n spyder-cf -c conda-forge spyder pandas
        conda activate spyder-cf
        spyder

Also, please share more info about your setup (OS, Python version, dependencies version, etc). Any new info in order to reproduce this is greatly appreciated. Let us know!

**Comment by MH-Dev20** [comment] 2022-08-16 16:34
Hi dalthviz,

Thank you for responding.
My setup is as follows,
OS: Virtual Windows server 2016
Python version: 3.9.12
Anaconda Version: 4.12.0

**Comment by dalthviz** [comment] 2022-08-16 17:56
Checked this again locally but now with Spyder 5.2.2 and I was still unable to reproduce this :/

Is this happening for you consistently (always with the `pd.read_csv` completion?). Maybe a LSP restart could help. For that you can check out the Spyder docs FAQ page: https://docs.spyder-ide.org/current/faq.html#troubleshooting-completion

Let us know if that or updating to the latest Spyder release (from 5.2.2 to 5.3.2) helps!

**Comment by MH-Dev20** [comment] 2022-08-17 03:25
Hi,
Thank you for your time and effort in fixing this issue. As I mentioned in my second post I found the issue exists only when I open my old codes and It is not just for pd.read_csv. It is for all autocompletion. If I make a new file in spyder there is no issue. Everything goes well in new files. Even I can't reproduce the issue on new files. It seems there is something wrong with my old codes. Please close this item since it is not common and doesn't worth you spending time on it.
Regards,

**Comment by dalthviz** [comment] 2022-08-17 15:21
I see, thank you for taking the time to explain the situation! Then I guess is quite a specific issue, maybe something related with line endings in the file or file codification. I will close this one then but if you find out more info let us know!

**Closed by dalthviz** 2022-08-17 15:21 UTC
Labels: status:Awaiting Followup
