### ISSUE TITLE
Another KeyError when computing folding

### ISSUE THREAD

**Issue by hasakura511** [spyder-ide/spyder#10889] opened 2019-11-30 04:19 UTC
### What steps will reproduce the problem?

it keeps popping up

### Traceback
```python-traceback
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 256, in paintEvent


Traceback (most recent call last):
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 256, in paintEvent
    self._draw_fold_region_background(block, painter)
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 300, in _draw_fold_region_background
    end = self.folding_regions[start]
KeyError: 135

QPainter::setCompositionMode: Painter not active
Traceback (most recent call last):
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 256, in paintEvent
    self._draw_fold_region_background(block, painter)
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 300, in _draw_fold_region_background
    end = self.folding_regions[start]
KeyError: 135

QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
Traceback (most recent call last):
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 256, in paintEvent
    self._draw_fold_region_background(block, painter)
  File "/Users/hidemiasakura/anaconda/envs/py37/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 300, in _draw_fold_region_background
    end = self.folding_regions[start]
KeyError: 135
```

## Versions

* Spyder version: 4.0.0rc3 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.8.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.1;<0.32.0        :  0.31.1 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-11-30 04:30
Please don't write non-sense in our error report dialog for next time. Instead, please try to describe what's causing the problem.

**Comment by ccordoba12** [comment] 2019-12-04 23:47
Closing as a duplicate of #10918.

**Closed by ccordoba12** 2019-12-04 23:47 UTC
