### ISSUE TITLE
Dragged to Spyder

### ISSUE THREAD

**Issue by steven5clu884** [spyder-ide/spyder#16493] opened 2021-09-25 21:31 UTC
### What steps will reproduce the problem?

I have 5 python files open I dragged shadow-removal-based-on-YCbCr-color-space.py to Spyder this error came up

OS Ubuntuu 20.4

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/wizzerking/develop/anaconda3/envs/u2net/lib/python3.7/site-packages/spyder/plugins/help/widgets.py", line 855, in handle_link_clicks
    self.rich_text.load_url(url)
  File "/home/wizzerking/develop/anaconda3/envs/u2net/lib/python3.7/site-packages/spyder/plugins/help/widgets.py", line 188, in load_url
    self.load(qurl)
AttributeError: 'RichText' object has no attribute 'load'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.7.11
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.8.0-63-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment] 2021-09-27 02:32
Hey @steven5clu884, thanks for reporting. This is a duplicate of issue #16477 and it'll be fixed in our next version (5.2.0), to be released next month,

**Closed by ccordoba12** 2021-09-27 02:32 UTC
