### ISSUE TITLE
keyboard shortcut for 'run selection' in Spyder

### ISSUE THREAD

**Issue by alextournier** [spyder-ide/spyder#9264] opened 2019-05-04 15:04 UTC
Been trying to set keyboard shortcut for 'run selection' in Spyder and
a) it keeps losing it, so have to go back, reset shortcuts and redeclare it
b) changing the shortcuts now seems to have crashed the whole thing (see report below)
c) sometimes the action (run selection) from the menu works but the declared shortcut (in the menu) does something else

Running:
Spyder 3.3.4 
Mac OS 10.13.6
Anaconda 1.9.7

Details of crash:
```
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 225, in button_clicked
    configpage.apply_changes()
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 106, in apply_changes
    self.apply_callback()
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 271, in <lambda>
    self.apply_settings(self.changed_options))
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/plugins/shortcuts.py", line 890, in apply_settings
    self.table.save_shortcuts()
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/plugins/shortcuts.py", line 760, in save_shortcuts
    shortcut.save()
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/plugins/shortcuts.py", line 498, in save
    set_shortcut(self.context, self.name, self.key)
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/config/gui.py", line 100, in set_shortcut
    CONF.set('shortcuts', '%s/%s' % (context, name), keystr)
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 445, in set
    self._save()
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 110, in _save
    _write_file(fname)
  File "/Users/alexandertournier/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 107, in _write_file
    self.write(configfile)
  File "/Users/alexandertournier/anaconda3/lib/python3.7/configparser.py", line 918, in write
    self._sections[section].items(), d)
  File "/Users/alexandertournier/anaconda3/lib/python3.7/configparser.py", line 930, in _write_section
    fp.write("{}{}\n".format(key, value))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc23' in position 38: surrogates not allowed
```

**Comment by ccordoba12** [comment] 2019-05-05 07:31
What shortcut were you trying to set when this error occurred?

**Comment by goanpeca** [comment] 2019-05-05 16:03
It seems an invalid character

https://www.charbase.com/dc23-unicode-invalid-character

**Comment by alextournier** [comment] 2019-05-06 07:03
I was setting Alt+return, which was previously on 're-run previous cell' 
I reallocate 're-run previous cell' to something  else as I never use  that one and then allocate 'Alt+Return' to 'Run selection'
The odd behaviour does not seem to be linked  to the key combo  as it also failed when I had it on 'Alt+shift+return'.
My impression is that there is some somewhere in the code something  that thinks  it should  be the old key combo and then a clash appears.

**Comment by ccordoba12** [comment] 2019-05-06 17:26
@goanpeca, this looks a macOS specific issue. Can you replicate it?

**Comment by goanpeca** [comment] 2019-05-06 17:32
I will check

**Comment by alextournier** [comment] 2019-05-07 08:57
Yes I can replicate it. Indeed it seems to be a Mac issue.
The issue is quite clear when one tries to change the 'run cell' shortcut: it changes it but then won't  allow changing it back to cmd+return - the only way then is to reset defaults.
Thanks for looking into  this!

**Comment by goanpeca** [comment] 2019-05-07 18:20
Is this fixed aimed at 3.x @ccordoba12 ?

**Comment by ccordoba12** [comment] 2019-05-07 18:30
It depends. If the change is relatively simple to implement, then yes. If it involves changing too much code, then it's for master.

**Comment by ccordoba12** [comment] 2019-12-25 15:51
Duplicate of #10854

**Closed by ccordoba12** 2019-12-25 15:51 UTC
Labels: OS:MacOS, component:Preferences, type:Bug
