### ISSUE TITLE
preference can not be open

### ISSUE THREAD

**Issue by George614** [spyder-ide/spyder#5653] opened 2017-11-04 16:39 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\george\appdata\local\programs\python\python35\lib\site-packages\spyder\app\mainwindow.py", line 2610, in edit_preferences
    dlg.add_page(widget)
  File "c:\users\george\appdata\local\programs\python\python35\lib\site-packages\spyder\plugins\configdialog.py", line 234, in add_page
    widget.apply_button_enabled.connect(self.apply_btn.setEnabled)
AttributeError: 'NoneType' object has no attribute 'setEnabled'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.4
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-11-04 16:43
Thanks for reporting. This is a duplicate of issue #5649.

**Comment by ccordoba12** [comment] 2017-11-04 16:43
In the meantime, you can downgrade PyQt5 to its previous version to fix this error.

**Closed by ccordoba12** 2017-11-04 16:43 UTC
