### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by csediwanshu** [spyder-ide/spyder#9105] opened 2019-04-04 10:19 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    symlink(str(os.getpid()), self.name)
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\diwanshu\\.spyder-py3\\spyder.lock.1554373052787.newlink' -> 'C:\\Users\\diwanshu\\.spyder-py3\\spyder.lock'

Traceback (most recent call last):
    kill(int(pid), 0)
    raise OSError(errno.ESRCH, None)
ProcessLookupError: [Errno 3] None

Traceback (most recent call last):
    lock_created = lock.lock()
    rmlink(self.name)
    os.remove(os.path.join(filename, 'symlink'))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\diwanshu\\.spyder-py3\\spyder.lock\\symlink'

Traceback (most recent call last):
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.8
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2019-04-04 10:52
This is duplicate of issue #9093.

**Closed by ccordoba12** 2019-04-04 10:52 UTC
