### ISSUE TITLE
"Directly enter debugging when errors appear" - how does it work?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12293] opened 2020-04-12 16:37 UTC
[demo.mp4](https://puu.sh/FwzHm/265f6b7f4a.mp4) - I expect it to stop at the offending line and jump into the debugger. Is this a bug, or does it work differently? It'd be very convenient to have this instead of needing to plant breakpoints each time.

**Comment by ccordoba12** [comment] 2020-04-12 17:52
Duplicate of #11986

**Comment by ccordoba12** [comment] 2020-04-12 17:53
This functionality is broken at the moment and we'll fix it in our next release.

**Closed by ccordoba12** 2020-04-12 17:52 UTC
