### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Msabih** [spyder-ide/spyder#6956] opened 2018-04-13 08:21 UTC
Spyder crashes while closing jupyter notebook. 
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment] 2018-04-13 15:57
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-04-14 15:47
> Spyder crashes while closing jupyter notebook.

Jupyter notebook *within Spyder*, i.e. the ``spyder-notebook`` plugin? If so, this belongs in that repo, and be aware it currently has known issues and isn't maintained for lack of funds.

**Comment by CAM-Gerlach** [comment] 2018-04-21 22:59
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed** 2018-04-23 14:08 UTC
Labels: resolution:NoResponce
