### ISSUE TITLE
TODO tag problem

### ISSUE THREAD

**Issue by HannaLochOlszewska** [spyder-ide/spyder#12025] opened 2020-03-28 11:35 UTC
### What steps will reproduce the problem?

The "TODO" tag after one # as a comment breaks the static code analysis

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_pylint\widgets\pylintgui.py", line 336, in read_output
    text = to_text_string(qba.data(), encoding='utf-8')
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\py3compat.py", line 148, in to_text_string
    return str(obj, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 64: invalid continuation byte
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment] 2020-03-28 14:53
> The "TODO" tag after one # as a comment breaks the static code analysis

Please post the code you're passing to static code analysis to reproduce this problem in our side.

**Comment by HannaLochOlszewska** [comment] 2020-03-30 11:00
In the meantime I did one more test - it seems that the polish diacritical marks (in line starting with TODO) cause the problem.

`from fbm import FBM

# TODO: zamienić fbm na stochastic, żeby ładować jeden pakiet
# from stochastic.continuous import FractionalBrownianMotion

def fbm_generator(N, H, sigma=1.0, dt=1.0):
    """
    Function generates the 2D vector of fractional Brownian motion
    :param N: int, number of steps
    :param H: float, Hurst parameter
    :param sigma: float, scale parameter
    :param dt: float, time between steps
    :return: 2D vector of fBm
    """
    T = N * dt
    f = FBM(n=int(N), hurst=H, length=T, method='daviesharte')
    x = f.fbm() * sigma
    y = f.fbm() * sigma
    return x[:N], y[:N]
`

**Comment by ccordoba12** [comment] 2020-03-30 16:05
Ok, thanks for the reproducible example. That was really good!

This problem was fixed in Spyder 4. If you don't want to update yet (which is understandable because Spyder 4 is still a bit unstable), at least you know how to deal with the problem.

**Closed by ccordoba12** 2020-03-30 16:05 UTC
Labels: status:Awaiting Followup

**Comment by HannaLochOlszewska** [comment] 2020-03-30 19:26
Great, thanks a lot!
