### ISSUE TITLE
Spyder bombs out when I try to save a file

### ISSUE THREAD

**Issue by Taiko1969** [spyder-ide/spyder#6724] opened 2018-03-11 17:35 UTC
## Problem Description
I want to save my Spyder file in a directory other than the default directory. When I try to do so, I get a message that says "Python has stopped working". I am using Anaconda 5.6, 64-bit version, on a Windows 10 system.

### What steps will reproduce the problem?

1. Open Spyder (I have tried this several ways: 1) from the Anaconda prompt, 2) opening Spyder directly from the Windows menu, 3) bringing up the Anaconda prompt and opening Spyder with the "spyder" command
2. Click on the menu File, Save As ...
3. Go to a different directory
4. Before I can do anything else, I get a window with the following message (there is no follow-up information provided):
Python has stopped working

A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:
* Python:
* Qt:
* PyQt:
* Operating System:

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment] 2018-03-11 19:32
Thanks for reporting. This looks like a potential duplicate of #3903 , or at least directly related. Its not a Spyder bug but rather one with your Qt install, though its possible we could work around it in the future. For the meantime, please read through and try all the workarounds listed on that thread, as well as the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, fill out the missing sections of the template above (package versions and dependencies) and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment] 2018-03-19 23:52
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-03-19 23:52 UTC
Labels: status:Awaiting Followup
