### ISSUE TITLE
No linting sidebar

### ISSUE THREAD

**Issue by sammyred58** [spyder-ide/spyder#12743] opened 2020-05-14 10:49 UTC
### What steps will reproduce the problem?

It's always there. With basic linting ticked, unticked and then reticked. Spyder reset and anaconda updated, laptop restarted, the linting sidebar, where occurrences and errors are highlighted, is never there.

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by andfoy** [comment] 2020-05-14 15:37
Hi @sammyred58, thanks for posting this issue, however, the description that you provided is not enough to understand which is the problem. Could you please provide a screenrecord or a set of screenshots that help us to reproduce your error?

**Comment by ccordoba12** [comment] 2020-05-15 03:48
@sammyred58, @andfoy, this is a duplicate of issue #12637. It seems to be a problem only on macOS and we don't know yet why it happens.

**Closed by ccordoba12** 2020-05-15 03:48 UTC
Labels: status:Awaiting Followup

**Comment by sammyred58** [comment] 2020-05-15 09:00
Well, at least it's a known problem! Thanks! :)
