### ISSUE TITLE
spyder 6.0.1 does not open file dialog windows

### ISSUE THREAD

**Issue by thomas-goetz** [spyder-ide/spyder#22589] opened 2024-09-27 10:06 UTC
### What steps will reproduce the problem?

File / Open... does not open a dialog window to open a file
File / Save As... does not open a dialog window to save source code under a to be specified file name

Platform Spyder 6.0.1 (standalone)
Python 3.11.9 64-bit | Qt 5.15.8 | PyQt5 5.15.9 
macOS 14.7 (x86_64) 

## Versions

* Spyder version: 6.0.1  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: macOS-14.7-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.4.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.0 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  74.1.2 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.2 (OK)
yarl >=1.9.4                     :  1.9.4 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.1 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```

**Comment by ccordoba12** [comment] 2024-09-27 16:06
Hey @thomas-goetz, thanks for reporting. Unfortunately, I can't reproduce your problem in an M1.

@mrclary, could you check if this is a problem for you?

**Comment by thomas-goetz** [comment] 2024-09-27 16:18
Dear Carlos,

forgot to mention that the problem appears on an intel mac…
Thanks for taking care!


> Am 27.09.2024 um 18:06 schrieb Carlos Cordoba ***@***.***>:
> 
> 
> Hey @thomas-goetz, thanks for reporting. Unfortunately, I can't reproduce your problem in an M1.
> @mrclary, could you check if this is a problem for you?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

-- 
Prof.Dr. Thomas Goetz
Mathematical Institute
University of Koblenz

**Comment by ccordoba12** [comment] 2024-09-27 16:21
Yep, I saw that but I don't have access to one. However, I think @mrclary does.

**Comment by mrclary** [comment] 2024-09-27 17:40
I cannot reproduce on my machine, macOS 14.7 (x86_64).

Perhaps a screencast would be helpful?
https://www.cockos.com/licecap/licecap132.dmg

**Comment by thomas-goetz** [comment] 2024-09-27 17:50
Strange, after re-installing spyder 6.0.1 on my intel mac the problem seemingly haas disappeared. 
no idea why…
Nevertheless, if it works - fine.
Regards

Thomas

> Am 27.09.2024 um 19:40 schrieb Ryan Clary ***@***.***>:
> 
> 
> I cannot reproduce on my machine, macOS 14.7 (x86_64).
> Perhaps a screencast would be helpful?
> https://www.cockos.com/licecap/licecap132.dmg
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

-- 
Prof.Dr. Thomas Goetz
Mathematical Institute
University of Koblenz

**Comment by mrclary** [comment] 2024-09-27 17:52
Thanks for reporting back, @thomas-goetz. I'll close this issue, but please reopen if the problem reemerges.

**Closed by mrclary** 2024-09-27 17:52 UTC
Labels: status:Awaiting Followup
