### ISSUE TITLE
spyder crashes after some time

### ISSUE THREAD

**Issue by pelekhs** [spyder-ide/spyder#11071] opened 2019-12-13 10:27 UTC
### What steps will reproduce the problem?

Mainly when exploring the editor by using the keybord arrow buttons

### Traceback
```python-traceback
  File "C:\Users\spele\Miniconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "C:\Users\spele\Miniconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "C:\Users\spele\Miniconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: 'C:\\Users\\spele\\.spyder-py3\\autosave\\untitled1.py'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by brc-dd** [comment] 2019-12-13 12:27
I am also experiencing the same problem (the main window of Spyder shows, and crashes after 1-2 second), though my system configuration is quite different. I am using Anaconda on Windows 10 x64 and below is the list of installed packages\:

```
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
_low_priority             1.0                           0  
_r-mutex                  1.0.0               anacondar_1  
alabaster                 0.7.12                   py37_0  
anaconda                  custom                   py37_1  
anaconda-clean            1.1.0                    py37_1  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py37_0  
asn1crypto                1.2.0                    py37_0  
astroid                   2.3.3                    py37_0  
astropy                   3.2.3            py37he774522_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.3.0                     py_0  
autopep8                  1.4.4                      py_0  
babel                     2.7.0                      py_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.1.7            py37he774522_0  
beautifulsoup4            4.8.1                    py37_0  
bitarray                  1.1.0            py37he774522_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blosc                     1.16.3               h7bd577a_0  
bokeh                     1.4.0                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.3.1            py37h8c2d366_0  
bzip2                     1.0.8                he774522_0  
ca-certificates           2019.11.27                    0  
certifi                   2019.11.28               py37_0  
cffi                      1.13.2           py37h7a1dbc1_0  
chardet                   3.0.4                 py37_1003  
click                     7.0                      py37_0  
cloudpickle               1.2.2                      py_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
comtypes                  1.1.7                    py37_0  
conda                     4.8.0                    py37_0  
conda-build               3.18.11                  py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.0            py37h62dcd97_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         3  
contextlib2               0.6.0.post1                py_0  
cryptography              2.3.1            py37h74b6da3_0  
curl                      7.64.0               h2a8f88b_2  
cycler                    0.10.0                   py37_0  
cython                    0.29.14          py37ha925a31_0  
cytoolz                   0.10.1           py37he774522_0  
dask                      2.9.0                      py_0  
dask-core                 2.9.0                      py_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20181111                   py_0  
distributed               2.9.0                      py_0  
docutils                  0.15.2                   py37_0  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
fastcache                 1.1.0            py37he774522_0  
filelock                  3.0.12                     py_0  
flake8                    3.7.9                    py37_0  
flask                     1.1.1                      py_0  
font-ttf-dejavu-sans-mono 2.37                 h6964260_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                h7457263_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fonts-anaconda            1                    h8fa9717_0  
freetype                  2.9.1                ha9979f8_1  
fsspec                    0.6.0                      py_0  
future                    0.18.2                   py37_0  
get_terminal_size         1.0.0                h38e98db_0  
gevent                    1.4.0            py37he774522_0  
glob2                     0.7                        py_0  
greenlet                  0.4.15           py37hfa6e2cd_0  
h5py                      2.9.0            py37h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.0.1                    py37_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
idna                      2.8                      py37_0  
imageio                   2.6.1                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        1.2.0                    py37_0  
intel-openmp              2019.4                      245  
intervaltree              3.0.2                      py_0  
ipykernel                 5.1.3            py37h39e3cac_0  
ipython                   7.10.1           py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py37_0  
itsdangerous              1.1.0                    py37_0  
jdcal                     1.4.1                      py_0  
jedi                      0.14.1                   py37_0  
jinja2                    2.10.3                     py_0  
joblib                    0.14.0                     py_0  
jpeg                      9b                   hb83a4c4_2  
json5                     0.8.5                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.6.1                    py37_0  
jupyterlab                1.2.3              pyhf63ae98_0  
jupyterlab_server         1.0.6                      py_0  
keyring                   19.2.0                   py37_0  
kiwisolver                1.1.0            py37ha925a31_0  
krb5                      1.16.1               h038dc86_6  
lazy-object-proxy         1.4.3            py37he774522_0  
libarchive                3.3.2                h798a506_7  
libcurl                   7.64.0               h2a8f88b_2  
libiconv                  1.15                 h1df5818_7  
liblief                   0.9.0                ha925a31_2  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.16               h9d3ae62_0  
libspatialindex           1.9.3                h33f27b4_0  
libssh2                   1.8.0                hd619d38_4  
libtiff                   4.1.0                h56a325e_0  
libxml2                   2.9.9                h464c3ec_0  
libxslt                   1.1.33               h579f668_0  
llvmlite                  0.30.0           py37ha925a31_0  
locket                    0.2.0                    py37_1  
lxml                      4.4.2            py37h1350720_0  
lz4-c                     1.8.1.2              h2fa13f4_0  
lzo                       2.10                 h6df0209_2  
m2-bash                   4.3.042                       5  
m2-coreutils              8.25                        102  
m2-findutils              4.6.0                         2  
m2-gcc-libs               5.3.0                         4  
m2-gmp                    6.1.0                         3  
m2-heimdal                1.5.3                        10  
m2-heimdal-libs           1.5.3                        10  
m2-icu                    56.1                          2  
m2-libcrypt               1.3                           2  
m2-libdb                  5.3.28                        3  
m2-libedit                3.1                    20150326  
m2-libiconv               1.14                          3  
m2-libintl                0.19.7                        4  
m2-libopenssl             1.0.2.g                       2  
m2-libreadline            6.3.008                       8  
m2-libsqlite              3.10.0.0                      2  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-ncurses                6.0.20160220                  2  
m2-openssh                7.1p2                         2  
m2-openssl                1.0.2.g                       2  
m2-zlib                   1.2.8                         4  
m2w64-bwidget             1.9.10                        2  
m2w64-bzip2               1.0.6                         6  
m2w64-c-ares              1.11.0                        2  
m2w64-ca-certificates     20150426                    104  
m2w64-curl                7.48.0                        2  
m2w64-diffutils           3.3.2                         2  
m2w64-expat               2.1.1                         2  
m2w64-fftw                3.3.4                         6  
m2w64-flac                1.3.1                         3  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gettext             0.19.7                        2  
m2w64-gmp                 6.1.0                         2  
m2w64-gnutls              3.4.11                        2  
m2w64-grep                2.24                          2  
m2w64-gsl                 2.1                           2  
m2w64-jansson             2.7                           3  
m2w64-libffi              3.2.1                         4  
m2w64-libiconv            1.14                          6  
m2w64-libidn              1.32                          4  
m2w64-libjpeg-turbo       1.4.2                         3  
m2w64-libmetalink         0.1.3                         2  
m2w64-libogg              1.3.2                         3  
m2w64-libpng              1.6.21                        2  
m2w64-libsndfile          1.0.26                        2  
m2w64-libsodium           1.0.10                        2  
m2w64-libssh2             1.7.0                         2  
m2w64-libsystre           1.0.1                         3  
m2w64-libtasn1            4.7                           2  
m2w64-libtiff             4.0.6                         2  
m2w64-libtre-git          122.c2f5d13                   5  
m2w64-libvorbis           1.3.5                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
m2w64-libxml2             2.9.3                         4  
m2w64-mpfr                3.1.4                         4  
m2w64-nettle              3.1.1                         4  
m2w64-nghttp2             1.9.2                         2  
m2w64-openblas            0.2.19                        1  
m2w64-openssl             1.0.2.g                       2  
m2w64-p11-kit             0.23.2                        3  
m2w64-pcre                8.38                          2  
m2w64-rtmpdump-git        499.a107cef                   4  
m2w64-speex               1.2rc2                        3  
m2w64-speexdsp            1.2rc3                        3  
m2w64-tcl                 8.6.5                         3  
m2w64-tk                  8.6.5                         3  
m2w64-tktable             2.10                          5  
m2w64-wineditline         2.101                         5  
m2w64-xz                  5.2.2                         2  
m2w64-zeromq              4.1.4                         2  
m2w64-zlib                1.2.8                        10  
markupsafe                1.1.1            py37he774522_0  
matplotlib                2.2.2            py37had4c4a9_2  
mccabe                    0.6.1                    py37_1  
menuinst                  1.4.16           py37he774522_0  
mistune                   0.8.4            py37he774522_0  
mkl                       2019.4                      245  
mkl-service               2.3.0            py37hb782905_0  
mkl_fft                   1.0.15           py37h14836fe_0  
mkl_random                1.1.0            py37h675688f_0  
mock                      3.0.5                    py37_0  
more-itertools            7.2.0                    py37_0  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.6.1            py37h74a9793_1  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  4.4.0                    py37_0  
networkx                  2.4                        py_0  
nltk                      3.4.5                    py37_0  
nose                      1.3.7                    py37_2  
notebook                  6.0.2                    py37_0  
numba                     0.46.0           py37hf9181ef_0  
numexpr                   2.7.0            py37hdce8814_0  
numpy                     1.17.4           py37h4320e6b_0  
numpy-base                1.17.4           py37hc3f5095_0  
numpydoc                  0.9.1                      py_0  
olefile                   0.46                     py37_0  
openjdk                   8.0.152              h7382acf_1  
openpyxl                  3.0.2                      py_0  
openssl                   1.0.2t           vc14h62dcd97_0  
packaging                 19.2                       py_0  
pandas                    0.25.3           py37ha925a31_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
paramiko                  2.4.2                    py37_0  
parso                     0.5.1                      py_0  
partd                     1.1.0                      py_0  
path.py                   12.0.2                     py_0  
pathlib2                  2.3.5                    py37_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py37_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.2.1            py37hdc69c19_0  
pip                       19.3.1                   py37_0  
pkginfo                   1.5.0.1                  py37_0  
pluggy                    0.13.1                   py37_0  
ply                       3.11                     py37_0  
powershell_shortcut       0.0.1                         2  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            2.0.10                     py_0  
psutil                    5.6.7            py37he774522_0  
py                        1.8.0                    py37_0  
py-lief                   0.9.0            py37ha925a31_2  
pyasn1                    0.4.8                      py_0  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37hfa6e2cd_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37hfa6e2cd_9  
pycurl                    7.43.0.2         py37h74b6da3_0  
pydocstyle                4.0.1                      py_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.5.2                      py_0  
pylint                    2.4.4                    py37_0  
pympler                   0.7                        py_0  
pynacl                    1.3.0            py37h62dcd97_0  
pyodbc                    4.0.27           py37ha925a31_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.5                      py_0  
pyqt                      5.6.0            py37ha878b3d_6  
pyreadline                2.1                      py37_1  
pyrsistent                0.15.6           py37he774522_0  
pysocks                   1.7.1                    py37_0  
pytables                  3.6.1            py37h1da0976_0  
pytest                    5.3.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.6.0                      py_0  
pytest-astropy-header     0.1.1                      py_0  
pytest-doctestplus        0.5.0                      py_0  
pytest-openfiles          0.4.0                      py_0  
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.1                h33f27b4_4  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.2                      py_0  
python-language-server    0.31.2                   py37_0  
python-libarchive-c       2.8                     py37_13  
pytz                      2019.3                     py_0  
pywavelets                1.1.1            py37he774522_0  
pywin32                   223              py37hfa6e2cd_1  
pywin32-ctypes            0.2.0                    py37_0  
pywinpty                  0.5.5                 py37_1000  
pyyaml                    5.1.2            py37he774522_0  
pyzmq                     18.1.0           py37ha925a31_0  
qdarkstyle                2.7                        py_0  
qt                        5.6.2           vc14h6f8c307_12  
qtawesome                 0.6.0                      py_0  
qtconsole                 4.6.0                      py_0  
qtpy                      1.9.0                      py_0  
r-askpass                 1.0                       r36_0  
r-assertthat              0.2.1             r36h6115d3f_0  
r-backports               1.1.4             r36h6115d3f_0  
r-base                    3.6.1                hf18239d_1  
r-base64enc               0.1_3             r36h6115d3f_4  
r-bh                      1.69.0_1          r36h6115d3f_0  
r-bit                     1.1_14            r36h6115d3f_0    r
r-bit64                   0.9_7             r36h6115d3f_0    r
r-bitops                  1.0_6             r36h6115d3f_4    r
r-blob                    1.1.1             r36h6115d3f_0    r
r-boot                    1.3_20            r36h6115d3f_0  
r-broom                   0.5.2             r36h6115d3f_0  
r-callr                   3.2.0             r36h6115d3f_0  
r-caret                   6.0_83            r36h6115d3f_0  
r-catools                 1.17.1.2          r36h6115d3f_0    r
r-cellranger              1.1.0             r36h6115d3f_0  
r-class                   7.3_15            r36h6115d3f_0  
r-cli                     1.1.0             r36h6115d3f_0  
r-clipr                   0.6.0             r36h6115d3f_0  
r-cluster                 2.0.8             r36h6115d3f_0  
r-codetools               0.2_16            r36h6115d3f_0  
r-colorspace              1.4_1             r36h6115d3f_0  
r-config                  0.3               r36h6115d3f_0    r
r-crayon                  1.3.4             r36h6115d3f_0  
r-curl                    3.3               r36h6115d3f_0  
r-data.table              1.12.2            r36h6115d3f_0  
r-dbi                     1.0.0             r36h6115d3f_0  
r-dbplyr                  1.4.0             r36h6115d3f_0  
r-dichromat               2.0_0             r36h6115d3f_4  
r-digest                  0.6.18            r36h6115d3f_0  
r-dplyr                   0.8.0.1           r36h6115d3f_0  
r-ellipsis                0.1.0             r36h6115d3f_0  
r-essentials              3.6.0                     r36_0  
r-evaluate                0.13              r36h6115d3f_0  
r-fansi                   0.4.0             r36h6115d3f_0  
r-forcats                 0.4.0             r36h6115d3f_0  
r-foreach                 1.4.4             r36h6115d3f_0  
r-foreign                 0.8_71            r36h6115d3f_0  
r-forge                   0.2.0             r36h6115d3f_0    r
r-formatr                 1.6               r36h6115d3f_0  
r-fs                      1.2.7             r36h6115d3f_0  
r-generics                0.0.2             r36h6115d3f_0  
r-ggplot2                 3.1.1             r36h6115d3f_0  
r-glmnet                  2.0_16            r36h6115d3f_0  
r-glue                    1.3.1             r36h6115d3f_0  
r-gower                   0.2.0             r36h6115d3f_0  
r-gtable                  0.3.0             r36h6115d3f_0  
r-haven                   2.1.0             r36h6115d3f_0  
r-hexbin                  1.27.2            r36h6115d3f_0  
r-highr                   0.8               r36h6115d3f_0  
r-hms                     0.4.2             r36h6115d3f_0  
r-htmltools               0.3.6             r36h6115d3f_0  
r-htmlwidgets             1.3               r36h6115d3f_0  
r-httpuv                  1.5.1             r36h6115d3f_0  
r-httr                    1.4.0             r36h6115d3f_0  
r-ipred                   0.9_8             r36h6115d3f_0  
r-irdisplay               0.7.0             r36h6115d3f_0  
r-irkernel                0.8.15                    r36_0  
r-iterators               1.0.10            r36h6115d3f_0  
r-jsonlite                1.6               r36h6115d3f_0  
r-kernsmooth              2.23_15           r36h6115d3f_4  
r-knitr                   1.22              r36h6115d3f_0  
r-labeling                0.3               r36h6115d3f_4  
r-later                   0.8.0             r36h6115d3f_0  
r-lattice                 0.20_38           r36h6115d3f_0  
r-lava                    1.6.5             r36h6115d3f_0  
r-lazyeval                0.2.2             r36h6115d3f_0  
r-lubridate               1.7.4             r36h6115d3f_0  
r-magrittr                1.5               r36h6115d3f_4  
r-maps                    3.3.0             r36h6115d3f_0  
r-markdown                0.9               r36h6115d3f_0  
r-mass                    7.3_51.3          r36h6115d3f_0  
r-matrix                  1.2_17            r36h6115d3f_0  
r-mgcv                    1.8_28            r36h6115d3f_0  
r-mime                    0.6               r36h6115d3f_0  
r-miniui                  0.1.1.1           r36h6115d3f_0    r
r-modelmetrics            1.2.2             r36h6115d3f_0  
r-modelr                  0.1.4             r36h6115d3f_0  
r-mongolite               2.0.1             r36h6115d3f_0    r
r-munsell                 0.5.0             r36h6115d3f_0  
r-nlme                    3.1_139           r36h6115d3f_0  
r-nnet                    7.3_12            r36h6115d3f_0  
r-numderiv                2016.8_1          r36h6115d3f_0  
r-odbc                    1.1.5                     r36_0    r
r-openssl                 1.3               r36h6115d3f_0  
r-packrat                 0.5.0             r36h6115d3f_0    r
r-pbdzmq                  0.3_3             r36h6115d3f_0  
r-pillar                  1.3.1             r36h6115d3f_0  
r-pkgconfig               2.0.2             r36h6115d3f_0  
r-pki                     0.1_5.1           r36h6115d3f_1    r
r-plogr                   0.2.0             r36h6115d3f_0  
r-plyr                    1.8.4             r36h6115d3f_0  
r-prettyunits             1.0.2             r36h6115d3f_0  
r-processx                3.3.0             r36h6115d3f_0  
r-prodlim                 2018.04.18        r36h6115d3f_0  
r-profvis                 0.3.5             r36h6115d3f_0    r
r-progress                1.2.0             r36h6115d3f_0  
r-promises                1.0.1             r36h6115d3f_0  
r-ps                      1.3.0             r36h6115d3f_0  
r-purrr                   0.3.2             r36h6115d3f_0  
r-quantmod                0.4_14            r36h6115d3f_0  
r-r2d3                    0.2.3             r36h6115d3f_0    r
r-r6                      2.4.0             r36h6115d3f_0  
r-randomforest            4.6_14            r36h6115d3f_0  
r-rappdirs                0.3.1             r36h6115d3f_0    r
r-rbokeh                  0.6.3                     r36_0  
r-rcolorbrewer            1.1_2             r36h6115d3f_0  
r-rcpp                    1.0.1             r36h6115d3f_0  
r-rcpproll                0.3.0             r36h6115d3f_0  
r-rcurl                   1.95_4.12         r36h6115d3f_0    r
r-readr                   1.3.1             r36h6115d3f_0  
r-readxl                  1.3.1             r36h6115d3f_0  
r-recipes                 0.1.5             r36h6115d3f_0  
r-recommended             3.6.0                     r36_0  
r-rematch                 1.0.1             r36h6115d3f_0  
r-repr                    0.19.2            r36h6115d3f_0  
r-reprex                  0.2.1             r36h6115d3f_0  
r-reshape2                1.4.3             r36h6115d3f_0  
r-rjava                   0.9_11            r36h6115d3f_0    r
r-rjdbc                   0.2_7.1           r36h6115d3f_0    r
r-rjsonio                 1.3_1.1           r36h6115d3f_0    r
r-rlang                   0.3.4             r36h6115d3f_0  
r-rmarkdown               1.12              r36h6115d3f_0  
r-rpart                   4.1_15            r36h6115d3f_0  
r-rprojroot               1.3_2             r36h6115d3f_0    r
r-rsconnect               0.8.13            r36h6115d3f_0    r
r-rstudioapi              0.10              r36h6115d3f_0  
r-rvest                   0.3.3             r36h6115d3f_0  
r-scales                  1.0.0             r36h6115d3f_0  
r-selectr                 0.4_1             r36h6115d3f_0  
r-shiny                   1.3.2             r36h6115d3f_0  
r-sourcetools             0.1.7             r36h6115d3f_0  
r-sparklyr                1.0.0             r36h6115d3f_0    r
r-spatial                 7.3_11            r36h6115d3f_4  
r-squarem                 2017.10_1         r36h6115d3f_0  
r-stringi                 1.4.3             r36h6115d3f_0  
r-stringr                 1.4.0             r36h6115d3f_0  
r-survival                2.44_1.1          r36h6115d3f_0  
r-sys                     3.2               r36h6115d3f_0  
r-tibble                  2.1.1             r36h6115d3f_0  
r-tidyr                   0.8.3             r36h6115d3f_0  
r-tidyselect              0.2.5             r36h6115d3f_0  
r-tidyverse               1.2.1             r36h6115d3f_0  
r-timedate                3043.102          r36h6115d3f_0  
r-tinytex                 0.12              r36h6115d3f_0  
r-ttr                     0.23_4            r36h6115d3f_0  
r-utf8                    1.1.4             r36h6115d3f_0  
r-uuid                    0.1_2             r36h6115d3f_4  
r-viridislite             0.3.0             r36h6115d3f_0  
r-whisker                 0.3_2             r36h6115d3f_4  
r-withr                   2.1.2             r36h6115d3f_0  
r-xfun                    0.6               r36h6115d3f_0  
r-xml2                    1.2.0             r36h6115d3f_0  
r-xtable                  1.8_4             r36h6115d3f_0  
r-xts                     0.11_2            r36h6115d3f_0  
r-yaml                    2.2.0             r36h6115d3f_0  
r-zoo                     1.8_5             r36h6115d3f_0  
requests                  2.22.0                   py37_1  
rope                      0.14.0                     py_0  
rstudio                   1.1.456          vc14h1ad3211_1  [vc14]  r
rtree                     0.8.3                    py37_0  
ruamel_yaml               0.15.46          py37hfa6e2cd_0  
scikit-image              0.15.0           py37ha925a31_0  
scikit-learn              0.21.3           py37h6288b17_0  
scipy                     1.3.2            py37h29ff71c_0  
seaborn                   0.9.0              pyh91ea838_1  
send2trash                1.5.0                    py37_0  
setuptools                42.0.2                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.18.1           py37h6538335_2  
six                       1.13.0                   py37_0  
snappy                    1.1.7                h777316e_3  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.9.5                    py37_0  
sphinx                    2.2.2                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
sphinxcontrib-websupport  1.1.2                      py_0  
spyder                    4.0.0                    py37_0  
spyder-kernels            1.8.1                    py37_0  
sqlalchemy                1.3.11           py37he774522_0  
sqlite                    3.30.1               he774522_0  
statsmodels               0.10.1           py37h8c2d366_0  
sympy                     1.4                      py37_0  
tbb                       2019.4               h74a9793_0  
tblib                     1.5.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.3            py37he774522_0  
tqdm                      4.40.0                     py_0  
traitlets                 4.3.3                    py37_0  
ujson                     1.35             py37hfa6e2cd_0  
unicodecsv                0.14.1                   py37_0  
urllib3                   1.25.7                   py37_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_1  
watchdog                  0.9.0                    py37_1  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
win_inet_pton             1.1.0                    py37_0  
win_unicode_console       0.5                      py37_0  
wincertstore              0.2                      py37_0  
winpty                    0.4.3                         4  
wrapt                     1.11.2           py37he774522_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.2.6                      py_0  
xlwings                   0.16.1                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
yapf                      0.28.0                     py_0  
zeromq                    4.3.1                h33f27b4_3  
zict                      1.0.0                      py_0  
zipp                      0.6.0                      py_0  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  
```

## Detailed Description

I had updated Spyder to 4.0.0 from 3.3.6 using Anaconda Navigator where it prompted me that the software cannot be installed on base (root) environment, so I made a separate environment to install the newer version. After installation Spyder was running perfectly, but somewhere Anaconda has crashed forcing me to install every new application on a new environment, so I ran `anaconda-clean` and uninstalled anaconda from my device using standard windows installer, and manually clearing the qt registries and .spider folders. Then I made a fresh install followed by `conda update --all`, which ran successfully and installed Spyder 4.0.0 on base environment. Later I installed r-essentials and rstudio which downgraded Python from v 3.7.5 to 3.7.1 (some more packages were also downgraded, like qt, pyqt). Since this event I am experiencing crashing of Spyder just after the loading of main window. \
\
(I haven't started Spyder before installing R-Studio, so I can't comment over if it was working then or not. I'll try uninstalling R packages and R-Studio then again updating Python and all packages.) \
\
To me, this issue appears similar to issue #8082, and probably one of the installed packages is conflicting with Spyder.
\
PS: Keyboard events are not triggering the crash, at least in my case.

**Comment by ccordoba12** [comment] 2019-12-13 18:12
@pelekhs, your error is a duplicate of #11058 and it'll be fixed in our next version.

**Comment by ccordoba12** [comment] 2019-12-13 18:14
@brc-dd, you said

> (some more packages were also downgraded, like qt, pyqt)

This is the main culprit of your errors because you were left with very old versions of Qt and PyQt. I recommend you to not install everything in the base env but use different envs for the different packages you want to use (e.g. one for R packages, etc).

**Closed by ccordoba12** 2019-12-13 18:14 UTC
