### ISSUE TITLE
"Stop Debugging" continues execution in IPython console

### ISSUE THREAD

**Issue by shekhovt** [spyder-ide/spyder#4404] opened 2017-04-26 13:52 UTC
## Description of your problem

When debugging in IPython console, pressing "Stop Debugging" actually runs the remainder of the code, i.e. it is doing what the "Debug Continue" is supposed to do.
The expected behaviour is to terminate execution at current point and return from debug session

## Versions and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.13 64bits
* Qt Version: 5.6.2 
* PyQt Version: 5 5.6
* Anaconda 4.3.16
* Operating system: Mac OS 10.10.5 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-04-26 15:44
This is a duplicate of issue #4214.

**Closed by ccordoba12** 2017-04-26 15:44 UTC
