### ISSUE TITLE
On open any file

### ISSUE THREAD

**Issue by kai3341** [spyder-ide/spyder#9946] opened 2019-08-01 18:23 UTC
### What steps will reproduce the problem?

* Open any file in project
* Create new file (and then open it, haha)

### Traceback
```python-traceback
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 302, in report_open_file
    language.lower()])
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 326, in lsp_server_ready
    editorstack.notify_server_ready(language, configuration)
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/editor.py", line 1557, in notify_server_ready
    editor.start_lsp_services(config)
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 871, in start_lsp_services
    self.parse_lsp_config(config)
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 888, in parse_lsp_config
    self.will_save_notify = sync_options['willSave']
KeyError: 'willSave'
Traceback (most recent call last):
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 302, in report_open_file
    language.lower()])
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 326, in lsp_server_ready
    editorstack.notify_server_ready(language, configuration)
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/editor.py", line 1557, in notify_server_ready
    editor.start_lsp_services(config)
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 871, in start_lsp_services
    self.parse_lsp_config(config)
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 888, in parse_lsp_config
    self.will_save_notify = sync_options['willSave']
KeyError: 'willSave'
Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'}}
```

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.7.3
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.19.0-5-amd64

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.0 :  4.5.2 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-08-01 22:10
Duplicate of #9908

**Closed by ccordoba12** 2019-08-01 22:10 UTC
