### ISSUE TITLE
UI elements overlap after screen resolution change

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#11106] opened 2019-12-16 09:15 UTC
**Steps to reproduce:**
* Set the screen resolution to maximum available.
* Launch spyder, maximize its window.
* Lower screen resolution.
* Go back to the spyder window.
* Optionally try un-maximizing and maxmizing the spyder window again.

**Expected behavior:** UI should adjust itself to the new resolution.

**Actual behavior:** Some elements appear on top of each other despite there being enough space for them:
![overlapping_buttons](https://user-images.githubusercontent.com/11860098/70894243-50b96f80-1ff5-11ea-8973-8d12269d39a0.png)

**Setup:** Spyder 4.0.0, running on windows 10.

**Comment by ccordoba12** [comment] 2019-12-16 14:10
@jnsebgosselin, any idea what could be causing this? And, do you think there's a way to fix it?

I read Qt 5.14 has several improvements for Hi-DPI screens, so that could help.

**Comment by dalthviz** [comment] 2020-01-17 20:36
Hi @david-cortes I was unable to reproduce this, did you change anything else besides the screen resolution, like the scale for example? If you changed the scale maybe this could be related with #6181 and the solving PR #11322 

This is what I'm getting by just changing the resolution:

* From 1360x768 to 800x600 
![resolution](https://user-images.githubusercontent.com/16781833/72643455-b70b1800-393c-11ea-8631-430488f055d7.gif)

* From 1920x1080 to 800x600
![resolution2](https://user-images.githubusercontent.com/16781833/72644205-80ce9800-393e-11ea-82b2-9ae64afa6d0b.gif)

**Comment by david-cortes** [comment] 2020-01-18 08:07
I think in windows 10 sometimes the zoom changes automatically along with the resolution, but I no longer have access to the computer in which this used to happen, so cannot confirm it. Perhaps it could have been due to an automatic zoom change

**Comment by dalthviz** [comment] 2020-01-18 13:38
Thanks for the feedback @david-cortes ! For now I will close this one. The fix I mentioned will be available with Spyder 4.0.2,

**Closed by dalthviz** 2020-01-18 13:38 UTC
Labels: OS:Windows, tag:Ui, type:Bug
