### ISSUE TITLE
pip install ipynb-py-convert

### ISSUE THREAD

**Issue by tkannan1985** [spyder-ide/spyder#14947] opened 2021-03-17 16:53 UTC
### What steps will reproduce the problem?

pip install ipynb-py-convert

Error while trying to convert ipynb to py 

### Traceback
```python-traceback
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'f4e2bc6a874011eb8bb1c8f750535287'
ERROR:traitlets:Exception in comm_msg for f4e2bc6a874011eb8bb1c8f750535287
Traceback (most recent call last):
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'f4e2bc6a874011eb8bb1c8f750535287'
ERROR:traitlets:Exception in comm_msg for f4e2bc6a874011eb8bb1c8f750535287
Traceback (most recent call last):
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'f4e2bc6a874011eb8bb1c8f750535287'
ERROR:traitlets:Exception in comm_msg for f4e2bc6a874011eb8bb1c8f750535287
Traceback (most recent call last):
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "c:\users\kannan.t\appdata\local\programs\python\python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: 'f4e2bc6a874011eb8bb1c8f750535287'
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.9.2
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  49.2.1 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by dalthviz** [comment] 2021-03-17 18:03
Hi @tkannan1985 seems like this could be a duplicate of https://github.com/spyder-ide/spyder/issues/14886 to fix it you need to update `qtconsole` to version 5.0.3 (a fix for our next release was done by bumping up the required `qtconsole` version at https://github.com/spyder-ide/spyder/pull/14941). Let us know if that helps :)

**Comment by ccordoba12** [comment] 2021-03-25 17:01
Closing due to lack of response.

**Closed by ccordoba12** 2021-03-25 17:01 UTC
Labels: status:Awaiting Followup
