### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by giraldon** [spyder-ide/spyder#7446] opened 2018-07-13 18:23 UTC
### What steps will reproduce the problem?

Very simple...I tried to save a file and it gave me an error

### Traceback
```python-traceback
  File "/anaconda3/lib/python3.5/site-packages/spyder/plugins/editor.py", line 2014, in save_as
    if editorstack.save_as():
  File "/anaconda3/lib/python3.5/site-packages/spyder/widgets/editor.py", line 1711, in save_as
    filename = self.select_savename(original_filename)
  File "/anaconda3/lib/python3.5/site-packages/spyder/widgets/editor.py", line 1656, in select_savename
    self.edit_filetypes = get_edit_filetypes()
  File "/anaconda3/lib/python3.5/site-packages/spyder/config/utils.py", line 124, in get_edit_filetypes
    supported_exts = _get_pygments_extensions()
  File "/anaconda3/lib/python3.5/site-packages/spyder/config/utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/anaconda3/lib/python3.5/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/anaconda3/lib/python3.5/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (prompt-toolkit 1.0.5 (/anaconda3/lib/python3.5/site-packages/prompt_toolkit-1.0.5-py3.5.egg), Requirement.parse('prompt-toolkit<2.0.0,>=1.0.15'))
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.5.4
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 14.5.0

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
psutil >=0.3     :  5.4.6 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by dalthviz** [comment] 2018-07-13 19:00
Hi @giraldon this is a duplicate of #7193 you could try to update prompt-toolkit to fix this:
```
conda update prompt_toolkit
```

**Comment by ccordoba12** [comment] 2018-07-13 19:15
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Closed by ccordoba12** 2018-07-13 19:15 UTC
