### ISSUE TITLE
Spyder - internal problem

### ISSUE THREAD

**Issue by KaterinaTik** [spyder-ide/spyder#11032] opened 2019-12-11 21:15 UTC
Selecting the text as highlighted in the screenshot, throws the error

![image](https://user-images.githubusercontent.com/22517642/70660995-67b63580-1c74-11ea-8bff-cb66c6a04a87.png)

    at_point=self._last_point)
  File "//anaconda3/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 634, in show_hint
    inspect_word=inspect_word)
  File "//anaconda3/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 474, in _check_signature_and_format
    name_plus_char = inspect_word + open_func_char
TypeError: can only concatenate tuple (not "str") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "//anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3716, in main
    mainwindow = run_spyder(app, options, args)
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3598, in run_spyder
    app.exec_()
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 921, in handle_response
    handler(params)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1224, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 952, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1217, in handle_hover_response
    at_point=self._last_point)
  File "//anaconda3/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 634, in show_hint
    inspect_word=inspect_word)
  File "//anaconda3/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 474, in _check_signature_and_format
    name_plus_char = inspect_word + open_func_char
TypeError: can only concatenate tuple (not "str") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "//anaconda3/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "//anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3716, in main
    mainwindow = run_spyder(app, options, args)
  File "//anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3598, in run_spyder
    app.exec_()
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 349, in on_msg_received
    handler(resp['result'], req_id)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 169, in process_hover_result
    {'params': contents})
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 284, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 921, in handle_response
    handler(params)
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1224, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "//anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 952, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)

**Comment by ccordoba12** [comment] 2019-12-11 22:14
Thanks for reporting. We'll try to fix this problem in our next release.

**Comment by mvbentes** [comment] 2020-06-23 00:14
I have got a similar error message, but with a seemingly different source. It just happened when I dragged a few lines of code from notepad++ into spyder editor.

It was the first and only opened file in the editor. And was a just created temp file. I have tried to reproduce just after aknowledging the error, but it did not repeat.

Running spyder 4.1.3 - Python 3.6.5 32-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 

The traceback is as follows:

	File "C:\Anaconda\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1385, in handle_hover_response
			self._request_hover_clicked)
	TypeError: CodeEditor.sig_display_object_info[str, bool].emit(): argument 1 has unexpected type 'list'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
		File "C:\Anaconda\lib\logging\__init__.py", line 992, in emit
			msg = self.format(record)
		File "C:\Anaconda\lib\logging\__init__.py", line 838, in format
			return fmt.format(record)
		File "C:\Anaconda\lib\logging\__init__.py", line 575, in format
			record.message = record.getMessage()
		File "C:\Anaconda\lib\logging\__init__.py", line 338, in getMessage
			msg = msg % self.args
	ValueError: incomplete format
	Call stack:
		File "C:\Anaconda\Scripts\spyder-script.py", line 10, in <module>
			sys.exit(main())
		File "C:\Anaconda\lib\site-packages\spyder\app\start.py", line 205, in main
			mainwindow.main()
		File "C:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3748, in main
			mainwindow = run_spyder(app, options, args)
		File "C:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3664, in run_spyder
			app.exec_()
		File "C:\Anaconda\lib\site-packages\spyder\plugins\completion\plugin.py", line 302, in <lambda>
			lambda: self.receive_timeout(req_id))
		File "C:\Anaconda\lib\site-packages\spyder\plugins\completion\plugin.py", line 136, in receive_timeout
			self.howto_send_to_codeeditor(req_id)
		File "C:\Anaconda\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
			self.skip_and_send_to_codeeditor(req_id)
		File "C:\Anaconda\lib\site-packages\spyder\plugins\completion\plugin.py", line 205, in skip_and_send_to_codeeditor
			self.gather_and_send_to_codeeditor(request_responses)
		File "C:\Anaconda\lib\site-packages\spyder\plugins\completion\plugin.py", line 273, in gather_and_send_to_codeeditor
			response_instance.handle_response(req_type, responses)
		File "C:\Anaconda\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1019, in handle_response
			handler(params)
		File "C:\Anaconda\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1398, in handle_hover_response
			self.log_lsp_handle_errors("Error when processing hover")
		File "C:\Anaconda\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1050, in log_lsp_handle_errors
			logger.error('%', 1, stack_info=True)
	Message: '%'
	Arguments: (1,)

**Comment by ccordoba12** [comment] 2020-06-23 01:22
@mvbentes, could you upload an animated gif of your problem? You can generate it with the Licecap program and it'd be really useful to try to reproduce it in our side.

**Comment by ccordoba12** [comment] 2020-07-11 04:16
Closing because there's not enough info to fix this, sorry.

**Closed by ccordoba12** 2020-07-11 04:16 UTC
Labels: component:Code Completion, type:Bug
