### ISSUE TITLE
Macos : Edit variable "window" in Variable Explorer always goes behind Spyder main window

### ISSUE THREAD

**Issue by sebma** [spyder-ide/spyder#5499] opened 2017-10-18 12:44 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder3
2. In the Spyder IPython console, run "%run -d myScript.py -d myDir -q -r"
3. Edit a variable in `Variable Explorer`

**What is the expected output? What do you see instead?**
A new "window" for the variable edition is supposed to appear but it goes to the back of Spyder main window and it is not accessible by using "ALT+TAB"

**Please provide any additional information below**

## Versions and main components

`$ conda3 list -n root | egrep -iw "spyder|python |qt|pyqt"`
* Spyder Version: 3.2.3
* Python Version: 3.6.2
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Mac OS X 10.13

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment] 2017-10-18 14:00
Thanks for reporting. This is a duplicate of issue #5036.

**Closed by ccordoba12** 2017-10-18 14:00 UTC
