### ISSUE TITLE
Dropdowns in the wrong display

### ISSUE THREAD

**Issue by ricardobarriosp** [spyder-ide/spyder#11353] opened 2020-01-20 12:31 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Dropdown from Menu/Button appear in the wrong display. My current configuration is a laptop, with two external monitors. Bultin laptop display is turned-off, and only working with the two external monitors. So I have monitors 1 (laptop, disabled), 2 and 3 (external).

### What steps reproduce the problem?

1. Open Spyder 
2. Change display order, from 2,3 to 3,2 and back to 2,3
3. Move Spyder to display 3

### What is the expected output? What do you see instead?
When clicking on a menu/button, the dropdown should appear right below. 
The dropdown appears at the edge of the other screen (display 2). The same happens whether Spyder maximized or not.
When Spyder is restarted, it works as expected, but if I change again the order of displays the dropdowns appear again in the wrong display. 

In the screenshot below, the border between Display 2 and 3 is in between the Spyder main window and the floating menu.

![spyder-bug](https://user-images.githubusercontent.com/12081250/72726403-8a4b4080-3b88-11ea-9567-18c60b8835c7.png)

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.5 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Win10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.9.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.5 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-01-20 14:23
Thanks for reporting.

@dalthviz, could you verify this one?

**Comment by dalthviz** [comment] 2020-01-24 03:09
@ccordoba12 I was not able to reproduce this one but seems like the restart message added in PRs #11322 and #11358 is being triggered when the disposition of displays changes. Also, while testing I found a error when the screen changes so I made PR #11395

**Comment by ccordoba12** [comment] 2020-01-24 21:35
> I was not able to reproduce this one

Ok, closing then.

> Also, while testing I found a error when the screen changes so I made PR #11395

Great, thanks!

**Closed by ccordoba12** 2020-01-24 21:35 UTC
Labels: status:Awaiting Followup
