### ISSUE TITLE
Outline explorer doesn't display indentation correctly

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9610] opened 2019-06-19 17:58 UTC
## Description
The code:
```python
def foo():
    if True:
        def bar():
            return
    def foobar():
        return
```
Gives the following outline explorer:
![Screenshot 2019-06-19 at 18 59 09](https://user-images.githubusercontent.com/6740194/59788773-5f340200-92c4-11e9-96f2-a04289a7dd67.png)

## Versions

* Spyder version: 4.0.0.dev0 d62835ff2
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.5 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.5.0  :  4.5.1 (OK)
IPython >=4.0      :  7.3.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by bcolsen** [comment] 2019-06-19 20:31
I can confirm this bug. @impact27 Was this in 3.3.4 as well?

**Comment by bcolsen** [comment] 2019-06-19 21:21
@impact27 Never mind about Spyder 3.3.4. In Spyder3 the `if` statements are still included in the outline explorer, so it works as intended.

**Comment by ccordoba12** [comment] 2020-12-13 05:40
Closing because this should be fixed now with the move to use LSP symbols in the Outline.

**Closed by ccordoba12** 2020-12-13 05:40 UTC
Labels: component:Outline Explorer
