### ISSUE TITLE
Cannot import file .spydata

### ISSUE THREAD

**Issue by gianghoang90** [spyder-ide/spyder#16499] opened 2021-09-28 05:17 UTC
### What steps will reproduce the problem?

When I try to import my result in Variable explorer, it doesnt work. My python version in Spyder is 3.8.8.

Is there anyone that faced this problem before? Could you pls help me to deal with it? Thanks so much for your help.

### Traceback
```python-traceback
  File "C:\Users\102\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 247, in <lambda>
    triggered=lambda: self.import_data())
  File "C:\Users\102\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 476, in import_data
    error_message = self.shellwidget.load_data(self.filename, ext)
  File "C:\Users\102\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 153, in load_data
    return self.call_kernel(
  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\102\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 194, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 437, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 493, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call load_data:

  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 340, in _handle_remote_call
    return_value = self._remote_callback(

  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 240, in _remote_callback
    return super(FrontendComm, self)._remote_callback(

  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    return self._remote_call_handlers[call_name](

  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 229, in load_data
    data, error_message = load_func(filename)

  File "C:\Users\102\anaconda3\lib\site-packages\spyder_kernels\utils\iofuncs.py", line 408, in load_dictionary
    data = pickle.loads(fdesc.read())

  File "C:\Users\102\anaconda3\lib\site-packages\matplotlib\__init__.py", line 682, in __setitem__
    raise KeyError(

KeyError: 'examples.directory is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by steff456** [comment] 2021-09-28 17:22
Hi @gianghoang90,

Can you please post here the variable you are trying to import to see if I'm able to reproduce this issue? Also, if you could try to update to Spyder 5.1.5 and let me know if the error persists.

**Comment by gianghoang90** [comment] 2021-09-29 01:58
> Hi @gianghoang90,
> 
> Can you please post here the variable you are trying to import to see if I'm able to reproduce this issue? Also, if you could try to update to Spyder 5.1.5 and let me know if the error persists.

Thank you for your response.

I just tried to import my saved results. 

Here is my spydata file. Please find the attached file.

[training 12.36.zip](https://github.com/spyder-ide/spyder/files/7248315/training.12.36.zip)

I havent updated my Spyder to 5.1.5 yet. It's still Spyder 4.2.5.

I will update Spyder and try again.

**Comment by steff456** [comment] 2021-10-05 16:52
Hi! So I tested your results and it seems you have a `*.pickle` which is not supported for the variable explorer. I also don't recommend saving in that format because it is highly sensible to the versions of the packages you are using at the time of saving. If you notice, all the other files load as expected, so please continue to save them in `*.npy` in the future.

I'm sorry we are unable to do something else to fix your issue :(

**Comment by gianghoang90** [comment] 2021-10-06 01:51
Dear @steff456,

I'll save my data in *.npy in the future.

Thank you so much for your kind support.

**Comment by ccordoba12** [comment] 2023-03-05 19:10
Closing because this was answered.

**Closed by ccordoba12** 2023-03-05 19:10 UTC
Labels: status:Awaiting Followup
