### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by SongFGH** [spyder-ide/spyder#6012] opened 2017-12-19 01:13 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\pythonIDEAnaconda\lib\site-packages\spyder\plugins\editor.py", line 1840, in load
    self.edit_filetypes = get_edit_filetypes()
  File "D:\pythonIDEAnaconda\lib\site-packages\spyder\config\utils.py", line 119, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "D:\pythonIDEAnaconda\lib\site-packages\spyder\config\utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "D:\pythonIDEAnaconda\lib\site-packages\pygments\lexers\__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "D:\pythonIDEAnaconda\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "D:\pythonIDEAnaconda\lib\site-packages\pkg_resources\__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "D:\pythonIDEAnaconda\lib\site-packages\pkg_resources\__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "D:\pythonIDEAnaconda\lib\site-packages\pkg_resources\__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (jedi 0.9.0 (d:\pythonideanaconda\lib\si

**Comment by CAM-Gerlach** [comment] 2017-12-19 01:40
Thanks for reporting. The error traceback that was posted is incomplete. However, it is very likely a duplicate of e.g. #5673 , an error that's been reported numerous times now. As the full error message states, Jedi is only compatible with `parso` 0.1.0, not 0.1.1. Therefore, you can update `jedi` to the latest version with `conda update jedi` (or with `pip`, if you use that instead); (you can also downgrade to `parso` 0.1.0 with e.g. `conda install parso=0.1.0` ) and so this issue will be closed.

**Closed by CAM-Gerlach** 2017-12-19 01:40 UTC
