### ISSUE TITLE
Spyder debugger experience - jump to code line/Move current debug position

### ISSUE THREAD

**Issue by hofingermarkus** [spyder-ide/spyder#2515] opened 2015-07-03 09:25 UTC
Hi guys,

I really think Spyder is awesome and I would like to make a suggestion for an even further enhancement :)

It would be great if Spyder provided some graphical representation for pdb's "j(ump) lineno" command, that allows to set the next line that will be executed during debugging.
This is such a powerful debugging tool, as it allows to skip over malfunction code or to go back if you missed the important step etc.. It should therefore have a graphical representation, especially to let newbies know that this is possible.

a) An easy way could be to simply open a pop up a like "enter a line number for next statement to debug"
b) Another awesome, but surely more difficult option to implement, would be to have an arrow that indicates the current line for the debugger (which is then independent from the line the mouse cursor selects). Then during a debug session, one could simply take that arrow with the mouse and move it up or down, similar as in VBA (from Excel/Word). Of course this option is more difficult, as Spyder would need to know what jumps are legal and which jumps are prohibited...

**Comment by ccordoba12** [comment] 2015-07-03 17:28
Thanks for the suggestion, it's very intersting! We'll see what we can do about it.

**Comment by ccordoba12** [comment] 2017-08-13 18:32
Closing this one as a duplicate of #528.

**Closed by ccordoba12** 2017-08-13 18:32 UTC
Labels: component:Debugger, resolution:Duplicate, type:Enhancement

**Comment by sanuparaballi** [comment] 2025-02-21 15:11
How is this a duplicate of the mentioned thread? It is completely different and I feel what @hofingermarkus has asked is really really useful! Google got me here when I was trying to figure out how to do exactly the same.
