### ISSUE TITLE
trying to import saved data

### ISSUE THREAD

**Issue by ShrinivasIyer** [spyder-ide/spyder#21064] opened 2023-06-23 02:38 UTC
### What steps will reproduce the problem?

trying to import saved data trying to import saved datatrying to import saved datatrying to import saved datatrying to import saved data

### Traceback
```python-traceback
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 170, in <lambda>
    triggered=lambda x: self.import_data(),
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 489, in import_data
    nsb.import_data(filenames=filenames)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 239, in import_data
    error_message = self.shellwidget.load_data(self.filename,
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 155, in load_data
    return self.call_kernel(
  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 224, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 440, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 496, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call load_data:

  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    return_value = self._remote_callback(

  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 273, in _remote_callback
    return super(FrontendComm, self)._remote_callback(

  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](

  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 260, in load_data
    data, error_message = load_func(filename)

  File "C:\Users\user\anaconda3\lib\site-packages\spyder_kernels\utils\iofuncs.py", line 411, in load_dictionary
    data = pickle.loads(fdesc.read())

TypeError: DimensionHolder.__init__() missing 1 required positional argument: 'worksheet'

```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.0.0 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.4.0 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.11.2 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.7.2 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.0 (OK)
numpy >=1.7                                      :  1.23.5 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.10.0 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by dalthviz** [comment] 2023-08-18 21:25
Hi @ShrinivasIyer sorry for the late reply and thank you for the feedback! Seems like your `.spydata` file contains `openpyxl` related variables which Spyder is unable to load. Does your current env have a different version of `openpyxl` from the one where the `.spydata` file was created? Maybe that could be causing the problem.

Seems like this could be related with https://github.com/spyder-ide/spyder/issues/13120

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2024-07-06 00:10
Closing as a duplicate of #13120

**Closed by dalthviz** 2024-07-06 00:10 UTC
Labels: resolution:Duplicate, component:Variable Explorer, status:Awaiting Followup
