### ISSUE TITLE
Missing imported modules while debugging another file

### ISSUE THREAD

**Issue by felipeespic** [spyder-ide/spyder#3392] opened 2016-09-01 13:51 UTC
## Description of your problem

Dear All,

I have 3 files:

a. startup script: A module ("debugging module") is imported here.
b. master script: The script that is passed to the function debugfile(). 
c. external module: It contains a function called by the master script. This external module is imported in the master script.

My startup script imports a module that I use only for debugging ("debugging module"). If I try to debug a function in a "external module" that is called by the master script, it looses the "debugging module" imported by the startup script. On the contrary, if I debug the master script, the imported "debugging module" works as expected. I am using pdb.

Thanks,

Felipe

**What steps will reproduce the problem?**
1. Import the "debugging module" in the startup script.
2. Put a breakpoint in a function in the external module called by the master script.
3. Press the "Debug" button.
4. Once the current frame reaches the breakpoint in the external module, check that the "debugging module" is still loaded.

**What is the expected output? What do you see instead?**

It is expected that the module keeps loaded during all the debugging session, no matter which file the current frame is located in.
## Versions and main components
- Spyder Version: 2.3.9
- Python Version: 2.7
- Operating system: Ubuntu 16.04LTS
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  None (NOK)
pyflakes >=0.5.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.10.3 (OK)
sphinx >=0.6.6     :  None (NOK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by Nodd** [comment] 2016-09-01 14:01
If I understand your problem correctly, what you want is not how python work. If you import a module in a file, you can access it only in that file. If you want to use it in another file, you have to import it there. When you debug a function, you are in the function's namespace, you you only have access to the same variables( including modules) that the function has access to.
To be more precise the module you want is loaded, but you have no reference to it in the function you're debugging so you can't use it without importing it.

**Comment by fzec1** [comment] 2016-09-01 14:43
Hi, 

Thank you for your reply. Actually, I am going to edit the message to make it more clear.

>  If you import a module in a file, you can access it only in that file. If you want to use it in another file, you have to import it there.

I do not agree. I am importing the module in the startup script file, and I can access it from the master file without importing it there. I think that is the objective of the startup file.

**Comment by ccordoba12** [comment] 2016-09-01 14:52
I don't understand what we should do to solve this problem :-)

**Comment by fzec1** [comment] 2016-09-01 15:01
Hi Carlos, 

Do not you understand what the problem is about? or you do not understand how to solve it?

I am editing my message to make it more clear.

Thanks,

**Comment by ccordoba12** [comment] 2016-09-01 15:09
How are you importing or running your startup script?

**Comment by fzec1** [comment] 2016-09-01 15:13
I specified it in Preferences->Console->PYTHONSTARTUP replacement.

**Comment by ccordoba12** [comment] 2016-09-01 15:19
Ok, that's right. The problem is we haven't considered this use case, and it seems very particular to your situation.

So the best we can suggest you is to look at our code and try to come up with a pull request to fix it :-)

**Comment by fzec1** [comment] 2016-09-01 15:27
Ok, thank you. I will see if I can do something to fix it :)

**Comment by ccordoba12** [comment] 2017-04-26 16:10
Closing because we don't plan to address this.

**Closed by ccordoba12** 2017-04-26 16:10 UTC
Labels: component:Debugger, type:Enhancement
