### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ufcolemanlab** [spyder-ide/spyder#6588] opened 2018-03-03 16:49 UTC
To reproduce:  I was accessing syntax coloring under preferences and applying zenburn, then internal error.  NOTE:  after canceling the error dialog, I was able to return to python without restarting, all seemed ok.

  File "/Users/jcoleman/anaconda/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "/Users/jcoleman/anaconda/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/Users/jcoleman/anaconda/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/Users/jcoleman/anaconda/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/Users/jcoleman/anaconda/lib/python2.7/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by CAM-Gerlach** [comment] 2018-03-03 18:20
Thanks for reporting. This is a duplicate of issue #6519 , and will hopefully be fixed in the next release.

**Closed by CAM-Gerlach** 2018-03-03 18:20 UTC

**Comment by ufcolemanlab** [comment] 2018-03-05 17:27
awesome, thanks.

**Comment by ufcolemanlab** [comment] 2018-03-05 17:54
awesome thanks.

**Comment by chenhao1UMBC** [comment] 2018-03-07 22:13
I encontered the same error

**Comment by CAM-Gerlach** [comment] 2018-03-07 22:31
> I encontered the same error

@chenhao1UMBC Okay...? Did the linked solution, ``conda install tornado=4.5.3`` not fix it for you?
