### ISSUE TITLE
Pandas Series not showing in Spyder Variable explorer

### ISSUE THREAD

**Issue by joy2014** [spyder-ide/spyder#2823] opened 2015-11-20 16:40 UTC
I updated my pandas to v.0.17.0.  After that, pandas series is not showing in Variable explorer.  I guess Type core.series.Series not a supported Type under variable explorer?  

here is the example,  test and df will show up in variable explorer, but not s1. 
```
import numpy as np
import pandas as pd

test = np.array([1,2,3,4,5])
df = pd.DataFrame(test, columns = ['test'])
s1 = pd.Series(test)
type(s1)
```

pandas: v0.17.0
spyder: 2.3.7

**Comment by ccordoba12** [comment] 2015-11-20 19:27
This is a duplicate of issue #2815 and will be fixed in 2.3.8

**Closed by ccordoba12** 2015-11-20 19:27 UTC
Labels: duplicate
