### ISSUE TITLE
Run cell scrolls the current line to be the first

### ISSUE THREAD

**Issue by liavassif** [spyder-ide/spyder#4606] opened 2017-06-14 11:07 UTC
## Description of your problem
When running a cell (without advance), the editor scrolls so that the line where the cursor is becomes the top line (assuming the cell has more lines than the editor window)

**What steps will reproduce the problem?**

1. Place the cursor on any line in a cell
2. Run cell (either using the menu or keyboard shortcut)

**What is the expected output? What do you see instead?**
Editor text and cursor position should not change

## Versions and main components

* Spyder Version:3.14
* Python Version:3.5.2
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system: Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-06-14 19:48
Thanks for reporting. We'll fix this after we release Spyder 3.2.

**Comment by goanpeca** [comment] 2019-11-29 02:04
I cannot reproduce this issue. Closing.

**Closed by goanpeca** 2019-11-29 02:04 UTC
Labels: component:Editor, type:Bug
