### ISSUE TITLE
ipython freezes at random during debugging

### ISSUE THREAD

**Issue by Andrew-Swan** [spyder-ide/spyder#19616] opened 2022-09-26 15:54 UTC
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Debugging code in Spyder can fail at random, where the ipython window freezes when stepping through code. No errors or output of any kind are generated, the console simply hangs. The only remedy is to kill the console and start over.

Debugging the same script twice in a row (in a fresh console each time) will almost certainly produce different reuslts: the console may hang at an earlier or later point on the second run, or it may successfully step through all the code.

There is no discernable pattern to this: the only common elements are the frequency with which it happens (about 50% of debug sessions) and the complete absence of any useful output or error messages.

It does not appear to depend on CPU load or memory usage, how long Spyder has been running, the complexity of the script, how many lines of code have been stepped through, which modules have been loaded, whether I/O operations are being attempted, or the nature of the last line run before the crash. It can happen at a print() statement after stepping through a few lines of code for a few seconds, or ipython can remain stable when stepping through hundreds of lines of code over many minutes.

This has been happening to me since Spyder 5.0, on multiple machines under both Windows and Linux, but it is continuing in a freshly-created conda environment on a fresh install of WIndows 10 on stable hardware. It is a frequent and fatal problem that is a major impediment to working with Spyder, and is thus a serious enough bug to warrant reporting despite the lack of reproducibility or helpful output.

### What steps reproduce the problem?

1. Start debugging a script
2. Step through the code

### What is the expected output? What do you see instead?

See above

### Paste Traceback/Error Below (if applicable)

```python-traceback

Not available

```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.8.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment] 2022-09-27 13:52
Hey @Andrew-Swan, thanks for reporting. This looks like a duplicate of issue #17523. Are you using the Tkinter Matplotlib backend?

**Comment by Andrew-Swan** [comment] 2022-09-27 21:15
No, I don't think so. The backend is set to "auto" in the preferences, but this is what a new console reports:

import matplotlib
matplotlib.get_backend()
Out[1]: 'Qt5Agg'

**Comment by Andrew-Swan** [comment] 2022-09-27 21:22
Also I think this is not a duplicate of #17523 because the debugger fails at random, rather than at the first breakpoint

**Comment by ccordoba12** [comment] 2022-09-27 23:48
Ok, sorry to hear that. Perhaps setting the backend to Inline could help. If that's not the case, I'm afraid there's little we can do about this unless you're able to narrow down the cause (it could also be generated by the code you're trying to debug). That's because we have many tests for our debugger, which don't show the problem you're describing, and we haven't heard about a problem like this in the past.

**Comment by ccordoba12** [comment] 2022-09-27 23:52
@impact27, do you have any idea about a possible cause for this?

**Comment by ccordoba12** [comment] 2022-10-10 17:05
Closing due to lack of response.

@Andrew-Swan, please post a comment when you find a way to reproduce this issue.

**Closed by ccordoba12** 2022-10-10 17:05 UTC
Labels: status:Awaiting Followup

**Comment by tony-pythony** [comment] 2024-04-16 07:18
I think I found how to reproduce this - but may be its a total different behavior:
Start up the debugger with a code of you choice. Let it run until a set breakpoint. After that use the "run line" button once - it shows the expected behavior: Advancing to the next line of code exec. 
But, then - just like you want to advance further in the code the next 20 lines - click the "run line" button often and fast, say 10 times. You'll see the execution lag and spyder/debug is executing the lines with the line highlighting with the code editor jumping to the line to be executed. The next click on the "run line" button leads to the "not executing anymore" behavior.

If you do it slowly, awaiting each line change and then click the "run line" button - most of the time I dont see an issue with this. But if you do it faster, like 2-3-4-5 times a second - the editor at some point still highlights the last line executed and stops there. Doing nothing, If, in this state, I click the "run line" button several times - nothing happens. Frustrated, like I am, clicking on the "stop debugger" button stops the script (expected) - but, then, all the clicks on the "run line" button done after "the hang" will be executed and showed as expected in the editor jumping to the lines quickly.

While it hangs, just a restart of the kernel (ctrl+".") resolves that issue. Stopping the debugger with the "stop debugging" button does it resolve too, but the code after a potential bug is then possibly executed too without control.

It seems like the editor chokes and miss events sent from the other parts. I hope, this helps to locate the problem.
For me: I exercise patience, now. Thanks for your beatiful work!

Spyder 5.5.4

# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.22.2 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.1.0 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.0.0 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.1,<2.6.0    :  2.5.1 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.3 (OK)
numpy >=1.7                      :  1.26.3 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  1.12 (OK)


I just tried it with a script with:
- only definitions of functions and dict initialisation in code: No problem here.
- When debugger entered a lengthy function: here i just reproduced the behavior.

**Comment by ccordoba12** [comment] 2024-04-19 01:16
Thanks for the additional feedback @tony-pythony! What did you mean by this? 

> When debugger entered a lengthy function: here i just reproduced the behavior.
