### ISSUE TITLE
Unable to save workspace on ubuntu

### ISSUE THREAD

**Issue by hiteshnitetc** [spyder-ide/spyder#7249] opened 2018-06-04 07:47 UTC
## Problem Description
Unable to save workspace (variables from variable explorer using save data as icon). I asked similar question [5647](https://github.com/spyder-ide/spyder/issues/5647) and [7196](https://github.com/spyder-ide/spyder/issues/7196). Some time adding .spydata works. But now it's not working. Is that because i have very large variables in variable explorer. Because i tried with single list like `a=[1,2,3]` and saving it using .spydata and it works. 
this is my snip of variable explorer with large variables (from which you can understand amount of variables, this is only half picture, all are not coming in one picture)
![screenshot from 2018-06-04 12-01-41](https://user-images.githubusercontent.com/30615882/40904807-8fadd97a-67f9-11e8-979f-4eb5c50d566b.png)

### What steps will reproduce the problem?
I am unable give code. because it is very large code, with lots of data

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Linux 4.13.0-43-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-06-04 15:27
Closing as a duplicate of the issues you mentioned. Please don't open more new issues about this.

**Closed by ccordoba12** 2018-06-04 15:27 UTC

**Comment by CAM-Gerlach** [comment] 2018-06-04 17:17
It is likely that there are specific type(s) of variables present in your session that Spyder is having trouble saving. If you can try to isolate those, or provide more information about which are present, please do so over at #5647 . Thanks.
