### ISSUE TITLE
My spyder crashs

### ISSUE THREAD

**Issue by PoppinElo** [spyder-ide/spyder#7436] opened 2018-07-12 18:19 UTC
### What steps will reproduce the problem?

I ejecute and .py: that script saves many values of variables in a .txt. But that .txt was so big spyder crashes. Then spyder's console cant be opened. I got to reinstall spyder

### Traceback
```python-traceback
  File "/usr/local/lib/python3.5/dist-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'json': {'documentation_url': 'https://developer.github.com/v3', 'message': 'Bad credentials'}, 'code': 401}
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.5.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-24-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.6 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.17.1 (OK)
numpy >=1.7       :  1.14.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.1.1 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-12 20:37
Thanks for reporting. This is a duplicate of issue #7403.

**Closed by ccordoba12** 2018-07-12 20:37 UTC
