### ISSUE TITLE
When I select the current working directory, the Python has stopped working

### ISSUE THREAD

**Issue by Augus-LHB-LPH** [spyder-ide/spyder#6117] opened 2018-01-03 07:48 UTC
## Description

**What steps will reproduce the problem?**

1. Browse a working directory
2. Python has stopped working
3. 

**What is the expected output? What do you see instead?**
I want to see a window to select the working directory, but i saw the dialog that tell me "Python has stopped working!"

**Please provide any additional information below**
In addition to selecting the current working directory, open the file and save the file with similar errors

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-03 14:26
> Browse a working directory

How are you doing that?

**Comment by CAM-Gerlach** [comment] 2018-01-03 18:51
In addition, please follow the suggestions in our [troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), and if they don't fix it for you, post here with the additional information requested. If we don't hear from you, this issue will be closed after a week (7 days). Thanks!

**Comment by Augus-LHB-LPH** [comment] 2018-01-04 01:58
Click the button on the navigation bar

**Comment by CAM-Gerlach** [comment] 2018-01-04 03:15
Which button would that be? A screenshot at least would be nice...not to mention some more information and what you've tried already, as suggested in the guide above.

**Comment by Augus-LHB-LPH** [comment] 2018-01-04 03:33
![image](https://user-images.githubusercontent.com/25689042/34549342-f1910604-f142-11e7-80ab-98c4fedd44cf.png)
 I saw the dialog that tell me "Python has stopped working!" when I clicked the button

**Comment by CAM-Gerlach** [comment] 2018-01-04 04:05
I'm on Windows 8.1 Pro x64 and Spyder 3.2.5, and I cannot reproduce the error you describe. whether or not a project is open, or if I enter an arbitrary path in the box, If it isn't fixed in Spyder 3.2.5, which you should update to with ``conda update spyder`` from the Anaconda prompt, it its likely it is something machine-specific of some sort. Does the open file button or menu item also produce the same error? If so, then its a duplicate of  #3903 , and is likely related regardless. Please let us know if this is the case.

In any case, as stated previously, please follow the suggestions in the **Basic First Aid** section of the above linked troubleshooting guide, as well as the linked issue thread, and if none of them resolve the problem and it can be isolated to Spyder rather than a system issue (unlikely), post the information requested there. Thank you.

**Comment by Augus-LHB-LPH** [comment] 2018-01-08 09:59
I have solved the problem , thank you !

**Comment by CAM-Gerlach** [comment] 2018-01-08 14:16
How did you solve it? Was it indeed a duplicate of #3903 ? If you let us know more information, we can either rule it out as a Spyder problem or solve it for you and all other users in the future, should it re-occur, as is the purpose of posting on Github's issue tracker rather than a help forum. Thanks!

**Comment by CAM-Gerlach** [comment] 2018-01-16 02:24
Closed due to lack of response. Please do reopen if you have more information about the problem, how you solved it, or its recoccurance. Thanks.

**Closed by CAM-Gerlach** 2018-01-16 02:24 UTC
Labels: status:AwaitingFollowup
