### ISSUE TITLE
Spyder 5 complains of missing dependency but shows it should be OK in the same message

### ISSUE THREAD

**Issue by ronanpaixao** [spyder-ide/spyder#15210] opened 2021-04-09 18:52 UTC
### What steps will reproduce the problem?

I just upgraded to Spyder 5.0.0 (using conda). Upon startup, Spyder immediately complains with an error message:

--------

**You have missing dependencies!**

`# Mandatory:`
`spyder_kernels >= 2.0.1,<2.1.0 : 2.0.1 (NOK)`

**Please install them to avoid this message.**

*Note*: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we *strongly* recoomend you to install all the listed missing dependencies.

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.

--------

The message itself shows that the version should be OK. I can click the OK button and go on, but the message is very annoying and the behavior is wrong.

**Comment by ronanpaixao** [comment] 2021-04-09 18:53
Screenshots:

Message shown at startup:

![image](https://user-images.githubusercontent.com/7624997/114227605-9b2dd080-994b-11eb-8383-3ce56235a961.png)

Dependencies dialog:

![image](https://user-images.githubusercontent.com/7624997/114227723-bac4f900-994b-11eb-81be-4ba7041e2d0e.png)

**Comment by xaverm** [comment] 2021-04-09 19:04
Exactly the same issue here. With exactly the same steps to reproduce the problem.

**Comment by ccordoba12** [comment] 2021-04-09 21:45
Hey @ronanpaixao and @xaverm, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-09 21:45 UTC

**Comment by ronanpaixao** [comment] 2021-04-10 00:18
Thanks for the response!

I think the problem with my search was that GitHub defaults to search open issues, while this was already closed. Sorry about the duplicate!

**Comment by ccordoba12** [comment] 2021-04-10 00:29
No problem, it's fine.
