### ISSUE TITLE
When using a network drive at work: 1) %clear generates this error: The system cannot find the path specified. 2) Spyder project explorer is blank.

### ISSUE THREAD

**Issue by RuslanBergenov** [spyder-ide/spyder#10879] opened 2019-11-28 22:48 UTC
## Problem Description

I'm having this issue on at work, not at home. I'm only observing it when my Spyder project is located on a drive different from where Anaconda is installed (That's my understanding).

C:\Users\MYNAME\AppData\Local\Continuum\anaconda3\Scripts\anaconda.exe - this is my local drive. This is where Anaconda is installed. I CANNOT access these the files in this directory from another machine in my organization.

\MYORGNAME\MyDocs\R\MYNAME\directory. I think that's another drive? This is where my Spyder project is. I CAN access these files from any machine in my organization. My understanding is that this is a different drive from where Anaconda is installed.

In this situation, I am having two issues. 1) %clear generated this error: The system cannot find the path specified. 2) Spyder project explorer is blank.

Both issues go away if i move my Spyder project here: C:\Users\MYNAME - in any of the subfolders.

This is a bit inconvenient, because there was a reason I was putting my Spyder project in \MYORGNAME\MyDocs\R\MYNAME\directory - I wanted to access them from another machine (laptop, tablet etc.)

### What steps reproduce the problem?

1. Put a Spyder project on a network drive in your organization. 
2. Type %clear in the console 
3. See if the the Project Explorer displays the files in the project

### What is the expected output?
1) % clear should clear the console. 
2) Project Explorer should display the files in the project.

###  What do you see instead?
1) %clear generates this error: The system cannot find the path specified. 
2) Spyder project explorer is blank.

## Versions

* Spyder version: 3.3.6
* Python version: Python 3.7.3 64-bit
* Qt version: Qt 5.9.6 
* PyQt version: PyQt5 5.9.2 
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

![1](https://user-images.githubusercontent.com/45578394/69834259-b2589c00-11f6-11ea-9e91-b43ff18614fc.png)

**Comment by ccordoba12** [comment] 2019-11-28 23:04
Thanks, but someone else reported the same these days. So I'm closing this one as a duplicate of #10762.

**Closed by ccordoba12** 2019-11-28 23:04 UTC
