### ISSUE TITLE
Spyder 3 Editor: no code completion for modules in PYTHONPATH

### ISSUE THREAD

**Issue by zsoltlazar** [spyder-ide/spyder#4182] opened 2017-02-21 23:35 UTC
## Description

**What steps will reproduce the problem?**

In the editor:
1. import somemoduleavailableinthePYTHONPATH
2. somemoduleavailableinthePYTHONPATH.    

**What is the expected output? What do you see instead?**
No symbol list appears.

**Please provide any additional information below**
Putting the path into the 'PYTHONPATH manager' does not help.
Clicking on the 'Update module names list' does not help
The issue appeared when upgrading from Spyder 2 (available by default in Ubuntu 14.04) to Spyder 3.1.3 using pip
Code completion works fine in the console. 
In the editor code completion works only for standard modules (numpy, scipy) and modules in the same folder as the script.

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.6
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Dependencies
Babel==2.3.4
JPype==0.5.4.2
Jinja2==2.9.5
MarkupSafe==0.23
MySQL-python==1.2.3
PAM==0.4.2
Pillow==2.3.0
Pmw==1.3.2
PyX==0.12.1
Pygments==2.2.0
Pyro==3.14
QtAwesome==0.4.4
QtPy==1.2.1
SciTools==0.9.0
ScientificPython==2.9.4
Sphinx==1.5.2
Twisted-Core==13.2.0
Twisted-Web==13.2.0
VTK==5.8.0
adium-theme-ubuntu==0.3.4
alabaster==0.7.9
appdirs==1.4.0
apt-xapian-index==0.45
argparse==1.2.1
astroid==1.4.9
backports-abc==0.5
backports.functools-lru-cache==1.3
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bleach==1.5.0
certifi==2017.1.23
chardet==2.3.0
colorama==0.2.5
command-not-found==0.3
configobj==4.7.2
configparser==3.5.0
cycler==0.10.0
debtagshw==0.1
decorator==4.0.11
defer==1.0.6
deluge==1.3.6
dirspec==13.10
docutils==0.13.1
duplicity==0.6.23
easygui==0.96
entrypoints==0.2.2
enum34==1.1.6
functools32==3.2.3.post2
gnuplot-py==1.8
html5lib==0.9999999
httplib2==0.8
hunspell==0.1
imagesize==0.7.1
instant==1.3.0
iotop==0.6
ipykernel==4.5.2
ipython==5.2.2
ipython-genutils==0.1.0
isort==4.2.5
jedi==0.9.0
jsonschema==2.6.0
jupyter-client==5.0.0
jupyter-core==4.3.0
lazy-object-proxy==1.2.2
lockfile==0.8
logilab-common==0.61.0
lxml==3.3.3
matplotlib==2.0.0
mccabe==0.6.1
mercurial==2.8.2
mistune==0.7.3
mysql-connector-python==1.1.6
mysql-utilities==1.3.5
nbconvert==5.1.1
nbformat==4.3.0
networkx==1.8.1
nose==1.3.7
numexpr==2.2.2
numpy==1.12.0
numpydoc==0.6.0
oauthlib==0.6.1
oneconf==0.3.7.14.4.1
packaging==16.8
pandas==0.16.0
pandocfilters==1.4.1
paramiko==1.10.1
pathlib2==2.2.1
patsy==0.3.0
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
piston-mini-client==0.7.5
prompt-toolkit==1.0.13
psutil==5.1.3
ptyprocess==0.5.1
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pyflakes==1.5.0
pygame===1.9.1release
pygobject==3.12.0
pylint==1.6.5
pyparsing==2.1.10
pyserial==2.6
pysmbc==1.0.14.1
pysqlite==2.6.3
python-apt===0.9.3.5ubuntu2
python-dateutil==2.6.0
python-debian===0.1.21-nmu2ubuntu2
python-distutils-extra==2.38
python-igraph==0.6.5
python-libtorrent==0.16.13
pytz==2016.10
pyxdg==0.25
pyzmq==16.0.2
qtconsole==4.2.1
reportlab==3.0
requests==2.13.0
roman==2.0.0
rope==0.10.3
scandir==1.5
scikit-learn==0.16.0
scikits.statsmodels==0.3.1
scipy==0.18.1
sessioninstaller==0.0.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
sklearn-pandas==0.0.9
snowballstemmer==1.2.1
software-center-aptd-plugins==0.0.0
spyder==3.1.3
ssh-import-id==3.21
statsmodels==0.6.1
subprocess32==3.2.7
system-service==0.1.6
testpath==0.3
tornado==4.4.2
traitlets==4.3.1
unity-lens-photos==1.0
urllib3==1.7.1
vboxapi==1.0
wcwidth==0.1.7
wheel==0.24.0
wrapt==1.10.8
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xdiagnose===3.6.3build2
xdot==0.5
zope.interface==4.0.5
```

**Comment by ccordoba12** [comment] 2017-02-22 13:37
Thanks for reporting. This is a duplicate of issue #4141.

**Closed by ccordoba12** 2017-02-22 13:37 UTC
Labels: resolution:Duplicate
