### ISSUE TITLE
"Kernel died, restarting..." repeats until I close Spyder.

### ISSUE THREAD

**Issue by yujenny** [spyder-ide/spyder#3506] opened 2016-10-06 02:05 UTC
## Description of your problem

**What steps will reproduce the problem?**

1.  Open Spyder
2. 
3. 

**What is the expected output? What do you see instead?**

Expect a working kernel, instead get the repeating message:
>> Kernel died, restarting
>> Kernal died, restarting

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5
* Operating system: Mac OS El Capitan

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-06 02:10
Please start Spyder from a terminal, and paste the error messages shown there.

**Comment by randomgambit** [comment] 2016-10-12 14:05
Hi, I am getting the same exact error. I just start Spyder and the kernel dies several times before being available

**Comment by randomgambit** [comment] 2016-10-12 14:18
I am behind a firewall, and therefore I disabled the option to check for updates at startup. Just run `spyder --reset` in the command line and the problem persists. All dependencies are OK as well. Could this be due to some network issue?

**Comment by randomgambit** [comment] 2016-10-12 14:31
```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by randomgambit** [comment] 2016-10-12 14:47
Last, @ccordoba12  starting spyder via the terminal does nothing. I still see `Kernel died, restarting...` 6/7 times before actually seeing

```
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

Note that the `Kernel died, restarting...` lines have disappeared from the console at this point

**Comment by ccordoba12** [comment] 2016-10-12 15:15
@randomgambit, this is a duplicate of issue #3444, so I'm closing it. Please add further comments on that issue :-)

**Closed by ccordoba12** 2016-10-12 15:15 UTC

**Comment by gorbatov** [comment] 2016-11-20 17:25
Kernel died, restarting can not use spyder at all this msg persist.
Initially has version 3.0.0 upgraded to 3.0.1.
Just trying to do some examples from theano tutorial

**Comment by ccordoba12** [comment] 2016-11-20 21:53
Please run Spyder from a terminal (i.e. cmd.exe on Windows) with this command

    spyder --show-console

and post the errors you're seeing in the terminal.

**Comment by cheresioana** [comment] 2016-12-03 20:56
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\****> spyder --show-console

There isn't anything in the console from the operating system. The errors only appear in the Console from spyder

Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Kernel died, restarting
Kernel died, restarting
Kernel died, restarting

**Comment by kjoth** [comment] 2017-01-26 14:58
spyder --show-console 

Starting Spyder from console just opens spyder and "Connecting to kernel" is displayed for long.. No messages in the terminal

**Comment by mido11AS** [comment] 2017-04-17 17:45
im using Spyder 3 and Python 3.6 running on windows 7 ... and i have got the same error "Kernel died, restarting" 
the problem was something related to Python. it was unable to run because of some windows feature need to be up to date "mainly Service Pack 1" ... i used that windows file update to solve the problem and it worked very well [Windows6.1-KB2999226-x64](https://www.microsoft.com/en-us/download/confirmation.aspx?id=49093)

**Comment by tricostume** [comment] 2017-11-10 14:43
I had Anaconda 3.5 (32 bits) for a Win(64 bits) computer. It was working perfectly. At that time I was careful enough to download both 32 and 64 bit versions of Anaconda 3.5. Today I needed to install 64 bits version and updated to 3.6 from command window. I had then this problem of kernel dying. I deinstalled and reinstalled Anaconda 3.5 for 64 bits and Spyder works well without updating.

**Comment by madhushree14** [comment] 2018-03-08 10:24
same error i got while importing tensorflow. i uninstalled anaconda and reinstall miniconda and then open jupyter. it resolved.

**Comment by FatenKhm** [comment] 2018-03-15 14:30
I uninstalled anaconda and I installed miniconda but the problem not resolved. here is my machine configuration: CPU i3, RAM 3G, Ubuntu 16.04 64bits. Is this a problem?

**Comment by Zaveian** [comment] 2018-04-10 12:47
this worked for me as well

**Comment by aghasd5** [comment] 2018-05-20 22:04
I installed reinstalled Tensorflow using the below pip command and it started working for me.
pip install --ignore-installed --upgrade tensorflow-gpu

**Comment by Pyuser37** [comment] 2018-10-01 22:09
I have this same issue when any Qt window is opened. After the kernel restarts the window will run. 
Anaconda 1.8.7
Spyder 3.2.8
Python 3.7

**Comment by Florian1209** [comment] 2018-10-12 14:57
I have this same named issue Kernel died, restarting... but in my case it 's a memory overload that break the kernel.
Example: I try to display a very big image in the kernel.

```
import imageio
import matplotlib.pyplot as plt

im = imageio.mimread('image.tif')
plt.figure(figsize=(2048,2048)) #int this case, 2048 inch, it's a very big image!
plt.imshow(im[1])
```
-> Kernel died, restarting

I understand why the kernel die, but the console should return a message like memory overload.

**Comment by kldeepika** [comment] 2018-10-26 16:51
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.2 (OK)

**Comment by kldeepika** [comment] 2018-10-26 16:52
my kernel is showing the layout.but it showing the options when we place the mouse on the menu and tools etc,its showing black window.please solve dis

**Comment by kamalkundal** [comment] 2019-04-11 13:50
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)

**Comment by rkc9603869349** [comment] 2020-03-17 04:56
try whether there is any python file recently created has predefined keywords

for me creating a python file logging.py created the issue,
Kernel died, restarting...
Kernel died, restarting...
Kernel died, restarting...
Kernel died, restarting...


i changed filename to user_logging.py which resolved the issue for me

check whether you are overloading any predefined packages of python

**Comment by PandyaSmit** [comment] 2020-04-14 05:57
Ran into a similar problem. Tried "Reset Spyder to factory defaults" and it solved my problem.

**Comment by ZhongLIFR** [comment] 2022-12-20 14:42
this error is still not resolved in 2022

**Comment by Amiralioghli** [comment] 2024-03-02 17:24
I am strugling the same issue, when i run the on terminal "Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.
fromIccProfile: failed minimal tag size sanity" message is appeard, and the kernel is dying.....

what should i do, can anyone help me please?
