### ISSUE TITLE
Pressing Ctrl+V inside a snippet is generating an error

### ISSUE THREAD

**Issue by Priyansh2001here** [spyder-ide/spyder#10584] opened 2019-11-02 15:25 UTC
### What steps will reproduce the problem?

```python
import matplotlib.pyplot as plt
plt.plot(<Ctrl+V>)
```

I just pressed ctrl + v inside closed paranthesis and the error occured

### Traceback
```python-traceback
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 52, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 236, in _process_text
    self.insert_text(text, line, column)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 383, in insert_text
    first_token = token_nodes[0]
IndexError: list index out of range
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.7.4
* Qt version: 5.11.2
* PyQt5 version: 5.11.3
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.16.5 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-11-02 18:58
Thanks for reporting. @steff456, please take a look at this one.

**Comment by steff456** [comment] 2019-11-04 19:40
I'm not able to reproduce this error neither on mac or in linux

**Comment by ccordoba12** [comment] 2019-11-05 01:49
I reproduced it very simply, when snippets are activated. Simply copy some text in your clipboard, then select `plt.plot` and paste your text on the first snippet with `Ctrl+V`. That should generate the error.

**Comment by andfoy** [comment] 2019-11-05 15:52
![ezgif com-video-to-gif(16)](https://user-images.githubusercontent.com/1878982/68223204-5ebdae80-ffba-11e9-8b71-6826614f2d27.gif)

I am also unable to reproduce this one

**Comment by ccordoba12** [comment] 2019-11-19 16:53
@dalthviz, please try to replicate this one to see if it's still an error in master. It's weird because I could replicate it as soon as it came up.

**Comment by dalthviz** [comment] 2019-11-19 17:12
@ccordoba12 I couldn't reproduce this neither. However another error seems present (when trying to paste `1` for the code snippet of `plot([x], [y], label=[str])`, visible at the end of the following gif):

![sn](https://user-images.githubusercontent.com/16781833/69168774-4aeb6f80-0ac5-11ea-8afa-1982c745a798.gif)

**Comment by ccordoba12** [comment] 2019-11-19 17:15
Ok, please take a look at that error instead.

**Comment by ccordoba12** [comment] 2020-08-09 19:07
This has not been reported anymore. Closing then.

**Closed by ccordoba12** 2020-08-09 19:07 UTC
Labels: component:Editor, type:Bug
