### ISSUE TITLE
Add ligature rendering in editor

### ISSUE THREAD

**Issue by keriszafir** [spyder-ide/spyder#3001] opened 2016-02-22 20:05 UTC
## Description of your problem

Spyder IDE doesn't render ligatures (combinations of glyphs into one single symbol) in fonts supporting them.  

**What steps will reproduce the problem?**
1. Install a font with support for programming ligatures - such as Fira Code https://github.com/tonsky/FiraCode
2. Select the font in Tools > Preferences > Editor > Font
3. In the editor, enter some character combinations leading to ligatures, such as "==", "=>", "!=" 

Groups of characters should be converted to ligatures - they are displayed as separate characters instead.
## Versions and main components
- Spyder Version: 2.3.8 (from PyPI)
- Python Version: 3.5
- Operating system: Debian amd64, stretch/sid, Xfce4
## Dependencies

IPython >=1.0      :  2.4.1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.4.2 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  1.5.2 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.1.0 (OK)

**Comment by acz13** [comment] 2017-01-07 00:14
This is pretty weird... I was using spyder fine for months with ligatures and I recently reinstalled it and I don't have ligatures anymore...

**Comment by cwdjankoski** [comment] 2018-07-27 13:45
I'm also having troubles getting it (firacode with ligatures) to work properly with 
QTKit: Get Info String: QTKit 7.7.3
spyder v3.3.0 on macOS 10.12.6.
I can choose the font in the preferences but ligatures do not display. 
Anyone has an idea for possible workaround or fix? happy to provide more info or help!

**Comment by liuyigh** [comment] 2019-12-08 05:19
Any chance to get this feature?

**Comment by ccordoba12** [comment] 2019-12-08 15:49
I don't know if this can be done in Qt (the graphical toolkit Spyder is built on top of). And this is very low priority for us, sorry.

**Comment by Akintola-Stephen** [comment] 2020-12-17 23:26
How do I install Fira code in Spyder IDE ?

**Comment by skjerns** [comment] 2022-11-05 15:13
Somehow I have the opposite problem:

In my Spyder, ligatures have appeared (as of 5.3 I think?)

Is there any way to get rid of them without changing fonts?

![Animation](https://user-images.githubusercontent.com/14980558/200126766-1d595daa-d61b-4dbf-8db9-668432fed32d.gif)

**Comment by ccordoba12** [comment] 2022-11-05 23:20
@skjerns, we didn't do anything special to fix this (that's why the issue is still open). My guess is that it was solved in Qt itself because since 5.3.0 Spyder can work with Qt/PyQt 5.15. So a workaround that you can try is to create a new environment with Spyder and PyQt 5.12 to see if that helps.

**Comment by ccordoba12** [comment] 2022-11-05 23:21
And I'm going to close this one as already solved.

**Closed by ccordoba12** 2022-11-05 23:21 UTC
Labels: type:Enhancement, community:Help wanted, component:Editor
