### ISSUE TITLE
Bug on lines wrapped

### ISSUE THREAD

**Issue by area912** [spyder-ide/spyder#22149] opened 2024-06-06 08:21 UTC
### What steps will reproduce the problem?

Hello,
When activating the wrap option on editor, there is an offset at the lines number on the side.

Thanks,
Best,
A user of spyder

## Versions

* Spyder version: 5.4.2  (pip)
* Python version: 3.10.8 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Linux 4.18.0-425.3.1.el8.x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.2.0 (OK)
cloudpickle >=0.5.0                  :  2.2.1 (OK)
cookiecutter >=1.6.0                 :  2.4.0 (OK)
diff_match_patch >=20181111          :  20230430 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0              :  8.23.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  1.0.1 (OK)
jsonschema >=3.2.0                   :  4.19.1 (OK)
keyring >=17.0.0                     :  24.2.0 (OK)
nbconvert >=4.0                      :  7.9.2 (OK)
numpydoc >=0.6.0                     :  1.6.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.9.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.5 (OK)
pygments >=2.0                       :  2.17.2 (OK)
pylint >=2.5.0;<3.0                  :  2.17.7 (OK)
pylint_venv >=2.1.1                  :  3.0.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                 :  1.7.4 (OK)
pylsp_black >=1.2.0                  :  1.3.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.3 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.4 (OK)
qtpy >=2.1.0                         :  2.4.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  63.2.0 (OK)
sphinx >=0.6.6                       :  7.2.6 (OK)
spyder_kernels >=2.4.2;<2.5.0        :  2.4.4 (OK)
textdistance >=4.2.0                 :  4.6.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  3.0.0 (OK)
xdg >=0.26                           :  0.28 (OK)
zmq >=22.1.0                         :  25.1.2 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.8.3 (OK)
numpy >=1.7                          :  1.23.4 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.9.2 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.5.1 :  0.5.1 (OK)
```

**Comment by dalthviz** [comment] 2024-08-01 00:53
Hi @area912 thank you for the report! Seems like this could be a duplicate of #20802 could it be possible for you to update your Spyder installation and check again (current Spyder 5 latest release is Spyder 5.5.5)? Let us know!

**Comment by dalthviz** [comment] 2024-11-06 23:41
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/20802

**Closed by dalthviz** 2024-11-06 23:41 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
