### ISSUE TITLE
i just open the preference and then warnning

### ISSUE THREAD

**Issue by JrSKYworkerlucas** [spyder-ide/spyder#9583] opened 2019-06-15 12:15 UTC
### What steps will reproduce the problem?

i just open the preference then this warnning occurs

### Traceback
```python-traceback
    widget = plugin.create_configwidget(dlg)
    configwidget.initialize()
    self.setup_page()
    "separate window.") % (inline, automatic))
TypeError: not all arguments converted during string formatting
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-15 12:32
Thanks for reporting. This is a duplicate of issue #9390 and it'll be fixed in our next beta.

**Closed by ccordoba12** 2019-06-15 12:32 UTC
