### ISSUE TITLE
Unexpected indent when running a single cell

### ISSUE THREAD

**Issue by AlbertoSabater** [spyder-ide/spyder#11023] opened 2019-12-11 09:57 UTC
When encapsulating the code in single cells, if one cell is inside an if clause, `unexpected indent error` raises when you run that cell. Sample code:

```
print('a')
# %%
if True:
    # %%
    print('b')
```

In the code above, there are three cells. If you run the first and third cells in that order, there will be an error in this last execution. Is there a way to solve this bug?

**Comment by goanpeca** [comment] 2019-12-11 17:48
@impact27 @bcolsen ?

**Comment by Karido** [comment] 2019-12-11 20:10
Same problem here.
This was not the case in Spyder 3. I just upgraded and got this error now.

```
if __name__ == '__main__':
    bla_main = []
#%% cell1
   bla_1 = []
#%% cell2
bla_2 = []
```
When I run the cells main or bla_2 they work. But Cell 1 does not work.
Actually I want to be able to run the cells without having to indent them because I want to be able to run the file as a whole afterwards.

**Comment by bcolsen** [comment] 2019-12-11 20:35
I cannot reproduce this. 

I get this output if I run the 1st then the third cell:
```python
runcell(0, '/home/user/untitled2.py')
a

runcell(2, '/home/user/untitled2.py')
b
```
And this output if I run all three:
```python
runcell(0, '/home/user/untitled2.py')
a

runcell(1, '/home/user/untitled2.py')
  File "/home/user/untitled2.py", line 31
    print('b')
    ^
SyntaxError: unexpected EOF while parsing


runcell(2, '/home/user/untitled2.py')
b
```

Even at that I don't think that Spyder should actually support code cell that are in indented blocks since that will usually result in broken code. Please see my comments in #9337 about this.

**Comment by bcolsen** [comment] 2019-12-11 20:44
I also can't reproduce @Karido's example. I get no errors and all the variables are created. I'm on latest master/ Linux /python 3.7

I have used code cells in `if __name__ == '__main__':` blocks before. I think that's a reasonable use case.

**Comment by Karido** [comment] 2019-12-11 21:17
Thank you for your answer. In a new file, it worked for me aswell. I think unindented comments force the list definitions to be fully indented. Is this intended? I am pretty sure, in Spyder 3, this was different.

The following code throws the error:

```
import numpy as np 

if __name__ == '__main__':
    list_def = []
    # some lines of functions and comments
#%%
    new_list_def = []
    for i in range(1):
        some_list = []
#        # some more functions (**indented cross on the left side throws the error, without it works**)
        for j in range(1):
            # some functions
            some_list.append(1)
        new_list_def.append(1)
#%%

```
With the cross, it states that new_list_def = [] is an unexpected indent.

**Comment by bcolsen** [comment] 2019-12-12 00:35
Thank you @Karido! I can reproduce that.

That's an issue with the dedenting of the code for runcell(). @impact27 Are we doing any code preprocessing to fix indentations. Ipython has some code for this.

**Comment by impact27** [comment] 2019-12-12 01:07
The preprocessing is done here:
https://github.com/spyder-ide/spyder-kernels/blob/b7132890812e61defe5aa25c9f06e82821d07656/spyder_kernels/customize/spydercustomize.py#L361

The IPython preprocessing is only enabled if the file is a `.ipy` file. All the cleanup transforms are disabled to avoid removing blank lines (Which would break tracebacks)

We only need to remove `leading_empty_lines` but the code would be specific to python3. If we keep `leading_indent` this would work, but I am not sure it should.

**Comment by impact27** [comment] 2019-12-15 18:07
Fixed by https://github.com/spyder-ide/spyder-kernels/pull/190

**Closed** 2020-02-28 21:00 UTC
Labels: component:Editor, component:IPython Console, v4.1.0
