### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by giannhs694** [spyder-ide/spyder#6904] opened 2018-04-05 18:16 UTC
File "/home/john/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "/home/john/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/home/john/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/home/john/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/home/john/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by ccordoba12** [comment] 2018-04-05 18:46
This is fixed in our latest version (3.2.8). Please update by opening a terminal (xterm, konsole, etc) and running there

    conda update spyder

**Closed by ccordoba12** 2018-04-05 18:46 UTC

**Comment by CAM-Gerlach** [comment] 2018-04-09 03:34
Thanks for reporting. This error is a duplicate of #6519 , which is fixed with Spyder 3.2.8.
