### ISSUE TITLE
ValueError when trying to launch Spyder with Python 3.6

### ISSUE THREAD

**Issue by bmlew** [spyder-ide/spyder#3636] opened 2016-11-02 07:38 UTC
## ValueError: source code string cannot contain null bytes

**What steps will reproduce the problem?**

1. Just run spyder.exe 
2. open spyder crash log
3. Traceback (most recent call last):
  File "C:\Users\Blew\Miniconda\lib\site-packages\spyder\app\mainwindow.py", line 2998, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Blew\Miniconda\lib\site-packages\spyder\app\mainwindow.py", line 2902, in run_spyder
    main.setup()
  File "C:\Users\Blew\Miniconda\lib\site-packages\spyder\app\mainwindow.py", line 793, in setup
    from spyder.plugins.help import Help
  File "C:\Users\Blew\Miniconda\lib\site-packages\spyder\plugins\help.py", line 33, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
ValueError: source code string cannot contain null bytes

**What is the expected output? What do you see instead?**
The spyder IDE launch

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3
* Python Version:3.6
* Operating system:windows 8.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
can't

**Comment by ccordoba12** [comment] 2016-11-02 14:36
I don't know what's be happening in this case, sorry :-/

**Comment by goanpeca** [comment] 2016-11-02 14:52
Python Version:3.6 ?

**Comment by bmlew** [comment] 2016-11-02 16:51
Yes

**Comment by bmlew** [comment] 2016-11-03 06:28
yes

**Comment by ccordoba12** [comment] 2016-11-10 18:01
@stonebig, could we test this problem in a beta version of WinPython?

**Comment by stonebig** [comment] 2016-11-11 15:08
"WinPython-3.6.0.0Preview"  is released now, and I didn't notice a problem from "WinPython-3.6.0.0Preview" Spyder launcher icon.

@bmlew didn't precise is full environnement, so it's hard to suggest any direction. 

For Winpython part, that apparently works:
- all is compiled from Windows, by myself or Christoph Gohlke.
- the just Arrived Qt part is PyQt4 made per Christoph Gohlke,
- no windows/linux layer (cygwin, msys, ... whatever) is used.

**Comment by ccordoba12** [comment] 2016-11-16 20:41
Closing as we can't reproduce this one.

**Closed by ccordoba12** 2016-11-16 20:41 UTC
Labels: Comp-Help, Type-Bug

**Comment by ss-sathishsampath** [comment] 2018-10-30 05:08
Use Uncompyle to decompile the previously compiled version(.pyc). you will get the previous version of the python file. 
https://github.com/rocky/python-uncompyle6
