### ISSUE TITLE
opencv2

### ISSUE THREAD

**Issue by namratesh** [spyder-ide/spyder#8235] opened 2018-11-13 14:38 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

ValueError: Invalid Signature: b'b1ae3d863280c3d7d66f9def45af8a95a385439638e5b779f4f406bc9a093890'
ValueError: Invalid Signature: b'b1ae3d863280c3d7d66f9def45af8a95a385439638e5b779f4f406bc9a093890'
ValueError: Invalid Signature: b'b1ae3d863280c3d7d66f9def45af8a95a385439638e5b779f4f406bc9a093890'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.6
* Qt Versions: 5.11.2, PyQt5 5.11.3 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.13.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  7.1.1 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2018-11-13 16:17
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by ccordoba12** [comment] 2018-11-23 22:42
Closing because of lack of response.

**Closed by ccordoba12** 2018-11-23 22:42 UTC
Labels: status:Awaiting Followup
