### ISSUE TITLE
Outline to show only cells (or special comments like ###) - type:enhancement component:Outline

### ISSUE THREAD

**Issue by bgerazov** [spyder-ide/spyder#7055] opened 2018-05-03 12:52 UTC
I really like using cells and writing/testing my code one cell at a time is awesome! In fact this is probably one of the best features in Spyder!

I also love the Outline which allows me to quickly go to a location in a file, even in multiple files. The problem is that the Outline gets cluttered with if/for/while loops that are not indented, and this makes it difficult to find the cell your looking for.

What would be very useful is if we could limit the Outline to contain only cell titles (or special marks such as ###). And maybe nest the if/for/while loops within the cells (even if they have no indent).

Thanks and keep up the awesome work!

**Comment by ccordoba12** [comment] 2018-05-03 15:39
Thanks for reporting. This was already fixed and it'll be part of Spyder 4, to be released in Q1 of next year.

**Closed by ccordoba12** 2018-05-03 15:39 UTC

**Comment by CAM-Gerlach** [comment] 2018-05-06 20:11
Duplicate of #5821
