### ISSUE TITLE
please help me for solving this error 

### ISSUE THREAD

**Issue by cmyldz** [spyder-ide/spyder#5054] opened 2017-08-25 07:54 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\cem\Desktop\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 876, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "C:\Users\cem\Desktop\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 922, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "C:\Users\cem\Desktop\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Users\cem\Desktop\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\qtconsole\console_widget.py", line 631, in execute
    self._execute(source, hidden)
  File "C:\Users\cem\Desktop\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\qtconsole\frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.1.dev0 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (O

**Comment by ccordoba12** [comment] 2017-08-25 15:01
Closing as a duplicate of issue #5053.

**Closed by ccordoba12** 2017-08-25 15:01 UTC
