### ISSUE TITLE
Show blank spaces in the preferences doesn't do anything

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9418] opened 2019-05-24 12:45 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

show blank spaces in the preferences doesn't do anything. I can turn it on from the source menu, but not from the preferences.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment] 2019-05-24 12:59
I cannot reproduce this on latest master.

**Comment by ccordoba12** [comment] 2019-05-24 13:44
Me neither.

**Comment by CAM-Gerlach** [comment] 2019-05-24 17:44
It worked for me in both prefs and the Source menu on Win 8.1, Py 3.7, Qt 5.9.7 and the latest ``master``, although Spyder hung and become unresponsive for a good 20 seconds before implementing it.

**Comment by bcolsen** [comment] 2019-05-24 21:50
I can't reproduce the original bug

> Spyder hung and become unresponsive for a good 20 seconds before implementing it.

When I have lots of files open the preferences are much slower than the menu option.

**Comment by CAM-Gerlach** [comment] 2019-05-24 22:33
> When I have lots of files open the preferences are much slower than the menu option.

For me, the menu option was ~15 seconds (with a decent number of long files and two panes), while the prefs option was well over 30 seconds. Typically, saving most preference options locks up Spyder for up to a few seconds (maybe 10 or more changing the color scheme, at least with a lot of files open) but I've never seen anything like that. But I digress.

**Comment by ccordoba12** [comment] 2019-05-31 09:26
@impact27, did you manage to make this work at the end or it's still failing for you?

**Comment by ccordoba12** [comment] 2019-06-29 11:33
Closing for now because we were unable to reproduce it. It was probably fixed by PR #9637.

**Closed by ccordoba12** 2019-06-29 11:33 UTC
Labels: status:Awaiting Followup
