### ISSUE TITLE
Spyder debugger breaks when using pandas MultiIndex

### ISSUE THREAD

**Issue by ba-tno** [spyder-ide/spyder#17821] opened 2022-05-04 11:46 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Appending a column to the index works fine while running, but fails when in debug mode. I'm using Spyder `5.3.0` on Windows with pandas `1.4.2`.

I've created some dummy code that shows the problem:
```py
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [100, 200, 300], "c": ["a", "b", "c"]})

df.set_index("a", inplace=True)
df.set_index("b", append=True, inplace=True)

print(df)
print(df.index)
```

I thought I would work around it with:

```py
# df.set_index("b", append=True, inplace=True)
df = df.reset_index().set_index(["a", "b"])
```

But the same issue persists.

Running this using `pdb` does work as expected

As it is a pandas error I've added this also to their issue tracker: https://github.com/pandas-dev/pandas/issues/46890

### What steps reproduce the problem?

1. Create a script that adds a MultiIndex in a pandas DataFrame (for example, see above)
2. Run it in Spyder debugging mode
3. Step through the code, over the `set_index()` line.

### What is the expected output? What do you see instead?

Expected output:
```txt
       c
a b     
1 100  a
2 200  b
3 300  c
MultiIndex([(1, 100),
            (2, 200),
            (3, 300)],
           names=['a', 'b'])
```
Actual output:
```txt
Traceback (most recent call last):
  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\spyder_kernels\customize\spyderpdb.py", line 776, in run
    super(SpyderPdb, self).run(cmd, globals, locals)
  File "C:\Users\username\Miniconda3\envs\some-env\lib\bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "c:\users\username\path\temp.py", line 6, in <module>
    df.set_index("b", append=True, inplace=True)
  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\frame.py", line 5560, in set_index
    index._cleanup()
  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\indexes\base.py", line 843, in _cleanup
    self._engine.clear_mapping()
  File "pandas\_libs\properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__
  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\indexes\multi.py", line 1097, in _engine
    return MultiIndexUIntEngine(self.levels, self.codes, offsets)
  File "pandas\_libs\index.pyx", line 635, in pandas._libs.index.BaseMultiIndexCodesEngine.__init__
  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\indexes\multi.py", line 136, in _codes_to_ints
    codes <<= self.offsets
AttributeError: 'MultiIndex' object has no attribute 'offsets'
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 5.3.0 None
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

<details>
<summary>Fold out for dependencies</summary>

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.5 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
paramiko >=2.4.0              :  2.10.3 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.13.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.7 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)

```

</details>

**Comment by ba-tno** [comment] 2022-05-04 17:35
Strange... here's the full `environment.yml` file of the environment I use:

<details>
<summary>Click to fold out</summary>

```yml
name: some-env
channels:
  - conda-forge
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=22.3.0=pyhd8ed1ab_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2021.10.8=py310h5588dad_2
  - click=8.1.3=py310h5588dad_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.0=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - fonttools=4.33.3=py310he2412df_0
  - freetype=2.10.4=h546665d_1
  - ftputil=5.0.3=pyhd8ed1ab_0
  - greenlet=1.1.2=py310h8a704f9_2
  - icu=69.1=h0e60522_0
  - importlib-metadata=4.11.3=py310h5588dad_1
  - importlib_metadata=4.11.3=hd8ed1ab_1
  - intel-openmp=2022.0.0=h57928b3_3663
  - ipykernel=6.13.0=py310hbbfc1a7_0
  - ipython=7.33.0=py310h5588dad_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py310h5588dad_1
  - jpeg=9e=h8ffe710_1
  - jupyter_client=7.3.0=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py310h5588dad_0
  - keyring=23.4.0=py310h5588dad_2
  - kiwisolver=1.4.2=py310h476a331_1
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=14_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=14_win64_mkl
  - libclang=13.0.1=default_h81446c8_0
  - libdeflate=1.10=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - liblapack=3.9.0=14_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.3.0=hc4061b1_3
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.11=h8ffe710_1014
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.5.1=py310h5588dad_0
  - matplotlib-base=3.5.1=py310h79a7439_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py310h5588dad_5
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - numpy=1.22.3=py310hed7ac4c_2
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1n=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py310hf5e1058_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.0=py310h767b3fd_2
  - pip=22.0.4=pyhd8ed1ab_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psutil=5.9.0=py310he2412df_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pygments=2.12.0=pyhd8ed1ab_0
  - pymysql=1.0.2=pyhd8ed1ab_0
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyqt=5.12.3=py310h5588dad_8
  - pyqt-impl=5.12.3=py310h8a704f9_8
  - pyqt5-sip=4.19.18=py310h8a704f9_8
  - pyqtchart=5.12=py310h8a704f9_8
  - pyqtwebengine=5.12.1=py310h8a704f9_8
  - python=3.10.4=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pywin32=303=py310he2412df_0
  - pywin32-ctypes=0.2.0=py310h5588dad_1005
  - pyzmq=22.3.0=py310h73ada01_2
  - qt=5.12.9=h556501e_6
  - setuptools=62.1.0=py310h5588dad_0
  - six=1.16.0=pyh6c4a22f_0
  - spyder-kernels=2.3.0=py310h5588dad_0
  - sqlalchemy=1.4.36=py310he2412df_0
  - sqlite=3.38.3=h8ffe710_0
  - tbb=2021.5.0=h2d74725_1
  - tk=8.6.12=h8ffe710_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py310he2412df_3
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.3=py310he2412df_0
  - typing_extensions=4.2.0=pyha770c72_1
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py310he2412df_1
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xlsxwriter=3.0.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h8ffe710_1014
  - zstd=1.5.2=h6255e5f_0
prefix: C:\Users\username\Miniconda3\envs\some-env

```

</details>

**Comment by dalthviz** [comment] 2022-05-04 18:12
Checked with your env specs and I was able to reproduce this!

![imagen](https://user-images.githubusercontent.com/16781833/166749471-f2b5e41d-9c5e-4877-acc3-e58561fdd12a.png)

I was also able to reproduce this with IPython:

![imagen](https://user-images.githubusercontent.com/16781833/166795129-2bc7d34d-c0e6-401c-a458-77cf6ea96dfa.png)

From what I see maybe this related with the support for Python (3.10.4) I guess this is something to check over IPython @ccordoba12? 

As a workaround please use Python <=3.9

**Comment by eddaz7** [comment] 2022-05-04 18:15
i think it's because of python 3.10
i have a similar problem debugging with spyder and pandas when i read a parquet file pandas-dev/pandas/#46890

**Comment by eddaz7** [comment] 2022-05-04 18:19
> Checked with your env specs and I was able to reproduce this!
> 
> ![imagen](https://user-images.githubusercontent.com/16781833/166749471-f2b5e41d-9c5e-4877-acc3-e58561fdd12a.png)
> 
> I was also able to reproduce this with IPython:
> 
> ![imagen](https://user-images.githubusercontent.com/16781833/166795129-2bc7d34d-c0e6-401c-a458-77cf6ea96dfa.png)
> 
> From what I see maybe this related with the support for Python (3.10.4) I guess this is something to check over IPython @ccordoba12?
> 
> As a workaround please use Python <=3.9

yep, for me i downgraded to python 3.9 and it worked again

**Comment by eddaz7** [comment] 2022-05-04 18:20
also i get the same error ad @dalthviz when i read the parquet file:
Attribute error: 'Multiindex' object has no attribute 'offsets'

**Comment by ccordoba12** [comment] 2022-05-05 14:17
I don't know why this is happening, but since @dalthviz was able to reproduce it in terminal IPython, I think this is not a Spyder problem but a Pandas one. So the discussion should be continued on https://github.com/pandas-dev/pandas/issues/46890.

@ba-tno, @eddaz7, what do you say?

**Comment by eddaz7** [comment] 2022-05-06 07:06
yes, i think it's a pandas error with python 3.10
thanks

**Comment by ccordoba12** [comment] 2022-05-06 12:36
Ok, closing this one then.

**Closed by ccordoba12** 2022-05-06 12:36 UTC
Labels: type:Bug, component:IPython Console, status:Awaiting Followup, upstream

**Comment by FTL-Citepa** [comment] 2022-05-12 09:24
I have the same issue when I'm trying to debug an instruction calling read_feather. No problem when I run it but exact same error. Is it really not a problem with spyder ?

**Comment by ba-tno** [comment] 2022-08-08 18:23
[This issue is resolved](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1208455954) in pandas 1.4.3 and/or Spyder 5.3.2.
