### ISSUE TITLE
Spyder internal error warning after using "break" inside a for loop

### ISSUE THREAD

**Issue by ahuard0** [spyder-ide/spyder#16373] opened 2021-09-07 08:33 UTC
### What steps will reproduce the problem?

Type in "import torch" into the iPython console and you will get this error.

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "C:\Program Files\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 315, in _comm_message
    encoding='latin-1')
ModuleNotFoundError: No module named 'torch'
```

## Versions

* Spyder version: 5.1.3 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.5.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ahuard0** [comment] 2021-09-07 08:38
The error happens as soon as "break" is encountered in the for loop.  This is a test script.

`from CIFAR10 import CIFAR10
from torch.utils.data import DataLoader


dataset_val = CIFAR10(bool_train=False, bool_tensor=True)
dataloader_val = DataLoader(dataset_val)

for imgs, labels in dataloader_val:
    batch_size = imgs.shape[0]
    break`

**Comment by steff456** [comment] 2021-09-07 18:02
Hi @ahuard0,

So, you have pytorch installed in your environment? The `break` command is inside the function you have or outside?

**Comment by ahuard0** [comment] 2021-09-07 20:04
Yes, PyTorch is installed. I’m avoiding using break statements, which allowed PyTorch to work correctly. Oddly enough, PyTorch works fine in debug mode with a breakpoint on the break statement, but crashes Spyder once break executes. 

Andrew Huard
UCSB Perm #6611446
Cell:  (805) 791-6704

On Sep 7, 2021, at 11:02 AM, Stephannie Jimenez Gacha ***@***.***> wrote:

﻿
Hi @ahuard0,

So, you have pytorch installed in your environment? The break command is inside the function you have or outside?

**Comment by ccordoba12** [comment] 2021-09-08 15:10
Pinging @dalthviz about this one because it seems very similar to a problem he helped to find the cause recently.

**Comment by dalthviz** [comment] 2021-09-08 16:11
Hi @ahuard0 could you select the option `Exclude unsupported data types` from the Variable Explorer options menu and check if that helps?

If that workaround works, I think this could be related/be a duplicate of https://github.com/spyder-ide/spyder/issues/16348

**Comment by ahuard0** [comment] 2021-09-09 12:24
"Exclude unsupported data types" fixed the issue.  Thank you!

**Comment by dalthviz** [comment] 2021-09-09 16:20
Glad is working for you @ahuard0 !

**Comment by ccordoba12** [comment] 2021-09-09 19:21
Closing then as a duplicate of #16348.

**Closed by ccordoba12** 2021-09-09 19:21 UTC
Labels: status:Awaiting Followup
