### ISSUE TITLE
Python 3.6 interpreter - invalid file path

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#15359] opened 2021-04-20 08:44 UTC
I am trying to use Spyder 4.2.5 with a parallel installation of Python 3.8 and 3.6. Conda is set to be added to the system path. This did work before, and I need python on my system path!

1. I use a fresh install of Anaconda including python 3.8.
2. I create an environment with `conda create -n py36 python==3.6.8`
3. I want to select python 3.6 within Spyder, however, I get `invalid file path` - there is no further error message to pin down the problem

![image](https://user-images.githubusercontent.com/14980558/115366311-8102b680-a1c5-11eb-9272-9707e9f22e12.png)

Solutions I tried (reinstalled anaconda before each)

- install `spyder-kernels` via conda within the py36 env (same version as for 4.2.5: 1.10.2)
- install `spyder-kernels` via pip
- run `conda update -all`
- run `conda update anaconda/conda`
- update to spyder 5.0.0 in both envs

What does work:
1. install anaconda 2020.07 including Spyder 4.1.5 (with spyder-kernels 1.9.2)
2. I create an environment with `conda create -n py36 python==3.6.8`
3. Manually select python.exe

Why does this not work any longer? Would it be possible to give some more detailed debugging information in this case?

**Comment by steff456** [comment] 2021-04-20 21:28
Hi @skjerns,

When you open the dropdown in the python interpreter preference, do all your environments appear under there?

Please let me know if you see it there

**Comment by skjerns** [comment] 2021-04-21 03:54
Yes, all of them get recognized correctly!

-----------
Sent from mobile

**Comment by steff456** [comment] 2021-04-21 03:56
If you select the environment you are looking for, then that error appears or it is working?

We added the detection of environments so you don't have to type them in.

**Comment by skjerns** [comment] 2021-04-21 06:23
The error appears either way

-----------
Sent from mobile

**Comment by ccordoba12** [comment] 2021-04-21 14:24
@skjerns, this is a duplicate of issue #12615. We don't know why it happens only for Python 3.6

Please continue the discussion there.

**Closed by ccordoba12** 2021-04-21 14:24 UTC
Labels: status:Awaiting Followup

**Comment by ccordoba12** [comment] 2021-04-21 14:27
> and I need python on my system path!

This is really odd. What do you need to do that? And what Python version?

(Please answer in the other issue)

**Comment by EcoFin** [comment] 2021-04-23 02:45
Having read this discussion I am really puzzled.  Just installed Spyder 5.0.1 (in Anaconda3 on Win 10 x64).  Had to install spyder-kernels in the python 3.6.13 environment I am working in (which unfortunately can't be upgraded past 3.6).  Conda chose spyder-kernels 2.0.1 which seemed fine.

When I restarted  the new Spyder version it couldn't open a console.  I went to preferences to select the python interpreter for that environment and got the "invalid file path" message.  But selecting interpreters for any of 7 (yup, seven) other python 3.6.13 environments works completely fine!

Any suggestions of what I should look for?  I would really prefer not do simply delete and try to reconstruct this particular environment because it is particularly complex, although that is the only thing I can think of right now.

**Comment by ccordoba12** [comment] 2021-04-23 03:47
I really don't understand why our validation process is failing for Python 3.6. sorry.

**Comment by skjerns** [comment] 2021-04-23 07:27
Is there any log/debug/output that we could check for what exactly is going wrong or where the validation fails?

**Comment by EcoFin** [comment] 2021-04-23 15:52
I have attached a debug log in case that .helps

 

With base active (where spyder is installed), but located in the environment (ayzipline) whose interpreter I have tried unsuccessfully to activate (and where spyder-kernels 2.0.1 is installed) I run spyder in debug mode. 

 

At line 808 there is a reference to the mkdocs python interpreter (3.6.13 strangely).  That is what it loaded at startup only because that is the one I tested last yesterday evening before shutdown.

 

At line 1921 I try to change that to the python.exe (also 3.6.13) in the ayzipline conda env (which is the one I want).  “Apply” at gives the invalid file path error.

 

I then change the interpreter back to the Backtrader python.exe (again 3.6.13) which is where I was working until I upgraded to ver 5.0.1 and ran into all this trouble yesterday.

 

Then I shut down Spyder to send you this information.

 

Sincerely

Arthur younger

**Comment by skjerns** [comment] 2021-07-06 09:39
Is there any update on this? It still appears with Spyder 5.0.3

I enabled the debuglog, but there seems to be no message related to the failing of detecting the environment.

**Comment by skjerns** [comment] 2021-07-06 10:15
I solved the problem!

1. I reinstalled anaconda with the latest version.
2. I uninstalled both spyder and spyder-kernels from conda base via `conda remove spyder --force` and `conda remove spyder-kernels --force`
3. I install spyder via  `pip install spyder` and `pip install spyder-kernels` in base
4. I created a plain py36 environment `conda create -n py36 python pip`
5. I installed the current version of `spyder-kernels` in the py36 environment via pip

Now everything works as expected :)
