### ISSUE TITLE
Cannot write [ in spyder

### ISSUE THREAD

**Issue by josesan77** [spyder-ide/spyder#17351] opened 2022-02-16 10:26 UTC
Cannot write **[**, only **]** bracket, therefore cannot make subsets **[ ]**. The [ bracket can be written in any other editor (Notepad, Word, ...) or consoles (Win Command Prompt, Anaconda Prompt, ...)
While typing "ALT Gr + F" (which I have to type to get [ symbol ) nothing shows up. Sometimes it seems that Spyder reacts something (hidden) because the software window 'blinks' once, but this is not reproducible. In general nothing happens.

Checked Spyder Preferences / Keyboard shortcuts, but could not find such keyboard combination as "ALT Gr + F". 

This error persists since last Anaconda + Spyder update in 2022 January.

Spyder ver 5.1.5 (Python 3.8.8. 64 bit, Qt 5.9.7, PyQt5 5.9.2, Windows 10)

*  Reproduced the issue after updating with ``conda update spyder`` (Admin mode)
*  Reproducable both in the editor and in the console
* Restarted Spyder, several times (after updating, as well)
    * Nothing was modified in preferences, no reset was made... but then I made it accoridng to Basic Troubleshoot guide... not fixed the issue (just have to start setting up my environment again :( )
    * Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### Paste Traceback/Error Below (if applicable)

```python-traceback



### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)

**Comment by dalthviz** [comment] 2022-02-16 15:57
Hi @josesan77 thank you for the feedback! I think this could be a duplicate of #15654 . Could you check the info there and let us know if something helps in your case? Thanks!

**Comment by tony-pythony** [comment] 2022-02-23 18:56
At first, I wrote the very same into the thread [https://github.com/spyder-ide/spyder/issues/15654] - my wrong. Sorry.

I would like to add, in my long term experience on windows and dos - the Alt GR was never used for functions or actions. It was always, in every program I ever used, it was always the key I need to press for getting | (pipe) or other special symbols.
On the other side, the ALT key is used for invoking the menu open or this kind of function.

As it is Windows specific, I would leave it to the users to remap them in the settings, if they need it - but, as a "standard" for Usability, would leave Alt Gr out of shortcuts definitions.

with macOS, I remember, the Alt GR did not have any function beside special characters, too.

usually, ctrl-key is associated with shortcuts (f.e. ctrl+f), or in combination like ctrl+alt, ctrl+shift, ctrl+alt+shift, to offer more functions for same keys.

So, there is a kind of paradigm which is used since a long time and almost everything is built upon/around it. I wouldn't map the Alt Gr to any function/shortcut - except for left-handed/right-handed reasons :) and leave that to the user

thank you for your time and work gals & guys !

**Comment by ccordoba12** [comment] 2022-02-23 22:20
> I would like to add, in my long term experience on windows and dos - the Alt GR was never used for functions or actions

We didn't use `Alt Gr` for a shortcut, we simply used `Alt`. But it seems in Hungarian and Czech keyboards that's mapped to `Alt Gr`.

In any case, that was fixed in our 5.2.0 version, released last November. Since it's still not available in Anaconda @josesan77, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Closed by ccordoba12** 2022-02-23 22:20 UTC
Labels: status:Awaiting Followup

**Comment by jablka** [comment] 2022-09-26 17:38
I have similar problem while using Slovak keyboard (see layout [here](http://kbdlayout.info/kbdsl1)).
When trying to type `'` sign, I press `AltGr+P`, but somehow Spyder takes it as if `Ctrl+P` was pressed and it opens up a `file switcher` pop-up.
I had to delete Ctrl+P shortcut in Preferences. But this is certainly not ideal solution. This is an Issue!

**Comment by dalthviz** [comment] 2022-09-26 17:48
Hi @jablka could you open a new issue with the details you provided here? Also, in that new issue, could you help us figuring out an alternative shortcut which doesn't collide with characters on your layout? Thanks!

**Comment by jablka** [comment] 2022-09-26 17:58
the new shortcut is not needed.
I think we should rather question why Spyder IDE takes `AltGr+P` pressed as if `Ctr+P` is pressed.
I don't have this issue elsewhere (e.g. Notepad++).

**Comment by dalthviz** [comment] 2022-09-26 18:36
Checking a little bit I think the problem is that we have `Ctrl+Alt+P` (which is equivalent to pressing `AltGr+P`) as a shortcut for the Symbol finder by default (which is the File Switcher instance with the `@` command prefiled when launched), so that default shortcut will need to be changed to prevent the issue (probably in general we will need to do a review for `Ctrl + Alt` shortcuts to prevent it to collide with typing characters).

Anyhow, could you please open a new issue so we can continue the discussion there, please?

**Comment by jablka** [comment] 2022-09-26 18:41
ah, now I understand.
Yes, you are right, the `@` sign was there too.
Ok, I will open up a new issue.
Thanks

**Comment by josesan77** [comment] 2023-01-15 16:40
I am sorry not replying earlier. In deed, you are right the Find File option was accessed by pressing the keyboard shortcuts (Hungarian keyboard), so I have found this shortcut set and have erased in Spyder to be able to write "[" symbol (AltGr + F) as it is more important.
Thanks for jablka and for dalthviz for the help and thinking about rethinking the keyboard shortcuts!
(I just came back because I am reinstalling Anaconda and Spyder and found by accident your replies that were hidden for me in my email system. My Conda was installed precisely 2 years ago and is arrived to a point that it collapses. :( But that's an another story.)
Thanks again!
