### ISSUE TITLE
Kernel died, restarting - ValueError: More than one filename match found for utility code Capsule

### ISSUE THREAD

**Issue by JakesBas** [spyder-ide/spyder#5643] opened 2017-11-02 10:09 UTC
## Description of your problem
I'm studying a course on machine learning via Udemy. I'm running into an error in a simple linear regression example where I try to fit regression line to a training data set. The kernel dies and restarts.

**What steps will reproduce the problem?**

1. When trying to fit a simple linear regression line tot the training set using the following code:
    from sklearn.linear_model import LinearRegression
    regr = LinearRegression()
    regr.fit(X_train, y_train)
    the iPython kernel dies and restarts

**What is the expected output? What do you see instead?**
A linear regression line is expected to be fitted to training the dataset.

**Please provide any additional information below**

Traceback (most recent call last):

  File "<ipython-input-1-f36a8d41893c>", line 1, in <module>
    get_ipython().magic('load_ext Cython')

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2163, in magic
    return self.run_line_magic(magic_name, magic_arg_s)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2084, in run_line_magic
    result = fn(*args,**kwargs)

  File "<decorator-gen-65>", line 2, in load_ext

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\IPython\core\magic.py", line 193, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\IPython\core\magics\extension.py", line 66, in load_ext
    res = self.shell.extension_manager.load_extension(module_str)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\IPython\core\extensions.py", line 86, in load_extension
    if self._call_load_ipython_extension(mod):

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\IPython\core\extensions.py", line 133, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\__init__.py", line 11, in load_ipython_extension
    from .Build.IpythonMagic import CythonMagics  # pylint: disable=cyclic-import

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Build\IpythonMagic.py", line 82, in <module>
    from .Inline import cython_inline

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Build\Inline.py", line 17, in <module>
    from ..Compiler.ParseTreeTransforms import (CythonTransform,

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\ParseTreeTransforms.py", line 1506, in <module>
    class AnalyseDeclarationsTransform(EnvTransform):

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\ParseTreeTransforms.py", line 1514, in AnalyseDeclarationsTransform
    """, level='c_class', pipeline=[NormalizeTree(None)])

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\TreeFragment.py", line 235, in __init__
    mod = t = parse_from_strings(name, fmt_code, fmt_pxds, level=level, initial_pos=initial_pos)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\TreeFragment.py", line 58, in parse_from_strings
    context = StringParseContext(name)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\TreeFragment.py", line 33, in __init__
    create_testscope=False)

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\Main.py", line 75, in __init__
    from . import Builtin, CythonScope

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\CythonScope.py", line 8, in <module>
    from . import MemoryView

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\MemoryView.py", line 9, in <module>
    from . import Buffer

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\Buffer.py", line 4, in <module>
    from .ModuleNode import ModuleNode

  File "C:\Users\Jakes\Anaconda3\lib\site-packages\Cython\Compiler\ModuleNode.py", line 2913, in <module>
    capsule_utility_code = UtilityCode.load("Capsule")

  File "Cython\Compiler\Code.py", line 254, in Cython.Compiler.Code.UtilityCodeBase.load

ValueError: More than one filename match found for utility code Capsule

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.5.2
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  4.2.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-11-02 14:09
Thanks for reporting. This is a duplicate of issue #5299 and there you'll find a temporary solution.

We'll fix this in our 3.2.5 version.

**Closed by ccordoba12** 2017-11-02 14:09 UTC
