### ISSUE TITLE
Run file (F5) stops almost immediately

### ISSUE THREAD

**Issue by wietmazairac** [spyder-ide/spyder#16285] opened 2021-08-26 09:31 UTC
## Problem Description
Run file (F5) stops almost immediately.
A new "In [x]:" does not appear.
No error messages are displayed.

### What steps reproduce the problem?
1. Open .py file
2. Click Run file (F5) multiple times

### What is the expected output? What do you see instead?
The .py file is expected to run and output is expected to appear in the Console.

Instead, in the Console the name of the runfile and the working directory are displayed.
And then nothing happens anymore. No error messages appear either.

Sometimes, opening a new console enables me to run the code.

### Paste Traceback/Error Below (if applicable)

Not applicable

## Versions

* Spyder version: 5.1.1.
* Python version: 3.9.6 
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.7.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (OK)

**Comment by ccordoba12** [comment] 2021-08-29 18:06
Hey @wietmazairac, thanks for reporting. This problem is caused you're not printing anything in your file.

For instance, if you have the following contents in your file

```python
a = 2 + 3
```

and then run it with `F5`, you won't see anything in the console.

Instead, you need to write the following


```python
a = 2 + 3
print(a)
```

Then you'll see a `5` in the console.

So please print the results you want to see and let us know if that works for you.

**Comment by wietmazairac** [comment] 2021-08-30 06:31
Hey @ccordoba12, thanks for your answer. No, that's not it.

I print things in my file.

Sometimes the file runs, sometimes is does not.
I have to close the console to try another run.

After clicking Run File (F5), in the Console the name of the runfile and the working directory are displayed.
I would also expect "In [x]:" to appear, indicating that the Console is ready for some new input.
However, "In [x]:" does not appear either. Therefore, it is not possible to run the file again or to enter a command manually.

**Comment by ccordoba12** [comment] 2021-08-30 13:25
Could you post a screenshot of what you're seeing? I don't understand what's happening in your case.

**Comment by wietmazairac** [comment] 2021-08-30 13:40
It looked like this.
I can't help you anymore. I reinstalled Windows and Anaconda. Now it works fine again.
It would be nice however to know what could have caused this issue.

![image](https://user-images.githubusercontent.com/40294132/131347977-c885483e-9df4-484a-ab84-a84a8ca735ed.png)

**Comment by ccordoba12** [comment] 2021-08-30 15:05
I'm going to close this issue because everything is working fine now.

**Closed by ccordoba12** 2021-08-30 15:05 UTC
Labels: status:Awaiting Followup

**Comment by wietmazairac** [comment] 2021-09-01 22:21
Same problem came up again...

**Comment by ccordoba12** [comment] 2021-09-01 22:31
I have no idea, sorry.

**Comment by wietmazairac** [comment] 2021-09-01 22:34
Is it possible to see what happens in the background?

**Comment by ccordoba12** [comment] 2021-09-01 22:49
See `spyder --help` for the debugging options.

**Comment by wietmazairac** [comment] 2021-09-20 07:19
Still facing the same problem.

**Comment by ccordoba12** [comment] 2021-09-20 15:50
@wietmazairac, did you change your graphics backend in `Preferences > IPython console > Graphics`?

If so, what's your current backend?

**Comment by wietmazairac** [comment] 2021-09-20 19:03
Yes, I think I did. I set it to Qt5.

**Comment by ccordoba12** [comment] 2021-09-20 19:08
Please close Spyder, reopen it and try again.

**Comment by wietmazairac** [comment] 2021-09-20 19:10
Which backend should I select before restarting?

**Comment by ccordoba12** [comment] 2021-09-20 19:29
Just leave Qt5 and restart.

**Comment by wietmazairac** [comment] 2021-09-21 06:47
Tried that many times. Sometimes the problems disappears, but it always reappears.

**Comment by wietmazairac** [comment] 2021-10-05 07:37
Changing back to Qt5 seems to cause the problem.
Reseting Spyder (backend to inline) seems to solve the problem.
Not sure, though.

Is it plausible backend and my problem are related?

**Comment by anutkk** [comment] 2021-11-10 12:44
@wietmazairac  Any chance your script has the line:

    if__name__ == '__main__':

which is required generally by multiprocess ?

I have the same issue and it seems to be correlated to this. Not sure though.

**Comment by wietmazairac** [comment] 2021-11-13 18:25
Yes, I use that line.
Not sure though either if that's the cause.

**Comment by anutkk** [comment] 2021-11-14 09:02
@wietmazairac Same here. No problem when this line does not appear, and this happens almost every time to scripts where it does appear. The problem is that this line is actually required in many cases.

The workarounds that work for me (even though I can't explain them):
* Running cell-by-cell
* Disable "Remove all variables before execution"
* Remove if __name__ == '__main__': when feasible.

Now it's well-known that IPython and multiprocessing don't get along, even though they generally work. The big question is: why did this happen so suddenly?
