### ISSUE TITLE
Ctrl+I, currently is there a way to trick spyder to inspect from ipyconsole when actually in editor?

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#9200] opened 2019-04-25 00:37 UTC
There are many issues about Ctrl+I working in ipython console but not in the editor. The more I use spyder the more I hate that I have to copy the line to ipython console to inspect the object and switch back to the editor to continue.

Is it possible to implement a patch or plugin for the short term until this issue is solved? For example maybe:
* Instead of copying the line to ipython console, Ctrl+I to inspect it, then switching back to the editor to continue.  Make this working automatically with a shortcut key. Or:
* Another inspecting behavior to inspect an object in the editor, trick spyder to believe it's in the ipython console.

Or if it's not the dev team's interest, can someone point out a way how to implement this?

**Comment by ccordoba12** [comment] 2019-04-25 12:47
This is basically a duplicate of issue #2162. And please don't insist, we're not going to add any short term solution for this.

**Closed by ccordoba12** 2019-04-25 12:47 UTC

**Comment by ccordoba12** [comment] 2019-04-25 12:52
The only solution we're going to accept (as I told you before) is a PyLS plugin that creates a kernel in the background and gets completions from it.

Here you can find a PyLS plugin for MyPy:

https://github.com/tomv564/pyls-mypy

And you also need to learn about Abstract Syntax Trees in Python (i.e. its `ast` module) to detect definitions in your code, i.e. things like `a = 10` and evaluate those assignments in the kernel.

If/once you something working, we can take a look at it and include it in Spyder. Thanks for understanding.
