### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by AtulKSigma** [spyder-ide/spyder#6779] opened 2018-03-16 18:54 UTC
1. Opened preference
2. Opened Help
3. Clicked on checkbox next to Editor
4. Clicked on Apply

 ` File "F:\opt\Continuum\anaconda3\envs\sigmainfo\lib\site-packages\spyder\plugins\configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
File "F:\opt\Continuum\anaconda3\envs\sigmainfo\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
File "F:\opt\Continuum\anaconda3\envs\sigmainfo\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
File "F:\opt\Continuum\anaconda3\envs\sigmainfo\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
`

**Comment by CAM-Gerlach** [comment] 2018-03-16 23:17
Thanks for reporting. This error is a duplicate of #6519 , which is fixed with Spyder 3.2.8. Accordingly, please update.

**Closed by CAM-Gerlach** 2018-03-16 23:17 UTC
