### ISSUE TITLE
Error: No such file or directory: 'sn_0_942310/.spyproject/workspace.ini'

### ISSUE THREAD

**Issue by ysumath1** [spyder-ide/spyder#6049] opened 2017-12-24 17:52 UTC
## Description
Spyder installed on MacOS High Sierra 
**What steps will reproduce the problem?**

1. Launching spyder in any supported manner (from terminal, or through Mac applications window)

Followed some MacOS specific directions here: https://stackoverflow.com/questions/20723977/ways-to-invoke-python-and-spyder-on-osx/44348973#44348973

As recommended in this issue post: https://github.com/spyder-ide/spyder/issues/4945

These fixes seem only to apply to launching spyder from Mac-friendly `Applications` folder; launch from terminal should be clean. In my experience, it is not. 

Installed Spyder from GitHub repo, not via Anaconda.

**What is the expected output? What do you see instead?**

Expected output is error free launch of Spyder.

**Please provide any additional information below**

  File "/usr/local/lib/python2.7/site-packages/spyder/plugins/projects.py", line 147, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/usr/local/lib/python2.7/site-packages/spyder/plugins/editor.py", line 2841, in setup_open_files
    filenames = self.projects.get_project_filenames()
  File "/usr/local/lib/python2.7/site-packages/spyder/plugins/projects.py", line 321, in get_project_filenames
    recent_files = self.current_active_project.get_recent_files()
  File "/usr/local/lib/python2.7/site-packages/spyder/widgets/projects/type/__init__.py", line 79, in get_recent_files
    default=[])
  File "/usr/local/lib/python2.7/site-packages/spyder/config/user.py", line 380, in get
    self.set(section, option, default)
  File "/usr/local/lib/python2.7/site-packages/spyder/config/user.py", line 448, in set
    self._save()
  File "/usr/local/lib/python2.7/site-packages/spyder/config/user.py", line 124, in _save
    raise(e)
IOError: [Errno 2] No such file or directory: 'sn_0_942310/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 4.0.0.dev0 
* Python Version: 2.7.14
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.6.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
psutil >=0.3      :  5.4.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-24 22:58
Thanks for reporting, and sorry you are experiencing issues. 

This appears to be a more direct duplicate of #5934 , and both previous instances involved macOS 10.13 High Sierra and Python 2.7, though one was system Python as you're using, and one was Anaconda. While you are welcome to try to get it working on your own if you're an experienced user (as I take it you probably are), we only officially recommend using it with the Anaconda distribution. Also, last I heard there are still issues being reported with python and 10.13 that are in the process of being fixed, though I can't recall specifically what the trouble was.

Therefore, this will be closed as a duplicate as well as for the other reasons mentioned. However, if you have further information to add, you are welcome to post it in the other thread. Additionally, I would point you to my comment in the aforementioned issue thread, as well as our [CONTRIBUTING readme](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md), our [installation documentation](https://github.com/spyder-ide/spyder/blob/master/doc/installation.rst), and the [workflow page](https://github.com/spyder-ide/spyder/wiki/Dev:-Github-Workflow) on our wiki for further help and suggestions. Best of luck!

**Closed by CAM-Gerlach** 2017-12-24 22:58 UTC

**Comment by ysumath1** [comment] 2017-12-25 02:13
Thanks, I'll check out the resources you've linked me to! I use Spyder with Anaconda on my Ubuntu box at work, but Anaconda has given me quite a bit of grief, as it doesn't play nicely with some pre-built deep learning modules (e.g. original Python Faster RCNN). So I've tried to avoid Anaconda on my Mac. That said, I do really, really like the feel of the Spyder IDE. I'm not a very experienced programmer, and its simple layout and interactive IPython terminal are invaluable to me.

**Comment by ysumath1** [comment] 2017-12-25 02:16
Also-- the `spyder --reset` command worked like a charm!
