### ISSUE TITLE
Plans to become a native browser application

### ISSUE THREAD

**Issue by jgbradley1** [spyder-ide/spyder#8464] opened 2018-12-20 00:53 UTC
There are a few [instances](https://hub.docker.com/r/compdatasci/spyder-desktop/) on DockerHub where spyder has been packaged up to run. The problem is all docker approaches that I've seen thus far use an XServer approach to make it work, which feels more like a workaround than an actual solution.

Are there any plans to work toward making Spyder a native browser application? Similar to how [Eclipse Theia](https://github.com/theia-ide) is designed to both be a desktop and cloud IDE that use the same software stack.

**Comment by bcolsen** [comment] 2018-12-20 06:11
Duplicate of #4743

It is not feasible to rewrite Spyder as a webapp at this point but if technology progresses in using the Qt toolkit with python on the web then one day browsers will run Spyder.  Maybe one day Wayland will run an a web browser https://github.com/udevbe/greenfield.

Currently an XServer and web based VNC is the best bet to run Spyder in a browser.  

There is also the ability to connect to remote kernel within Spyder so you can have a desktop app front end and the back end running on a server.

**Closed by bcolsen** 2018-12-20 06:12 UTC

**Comment by techtonik** [comment] 2022-06-22 07:48
Qt now works in the browser https://www.qt.io/qt-examples-for-webassembly

With this issue tracking Python connection to it https://bugreports.qt.io/browse/PYSIDE-962
