### ISSUE TITLE
Cannot change keyboard shortcuts

### ISSUE THREAD

**Issue by ysBach** [spyder-ide/spyder#5371] opened 2017-10-01 07:54 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Turn the spyder on and go to Preferences ->Keyboard shortcuts
2. changing any shortcut to a new one makes spyder to close with 
`Segmentation fault      (core dumped) spyder`
I first tried "open profiler" to "ctrl+F10" but failed. Then I tried many random changes but all failed so far.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
```IPython >=4.0    :  6.2.0 (OK)
cython >=0.21    :  0.27 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment] 2017-10-01 15:24
What is your Qt and PyQt versions?

**Comment by ysBach** [comment] 2017-10-02 04:43
@ccordoba12 Sorry for not attaching it from the beginning (I was not sure whether the followings are what I was asked)

```
$ qmake -v
QMake version 3.0
Using Qt version 5.6.2 in /home/aaa/anaconda3/bin/lib
```
and
```python
from PyQt5.QtCore import QT_VERSION_STR
print(QT_VERSION_STR)
# 5.6.2
```

**Comment by ccordoba12** [comment] 2017-10-11 18:04
This is duplicate of issue #5426.

**Closed by ccordoba12** 2017-10-11 18:04 UTC
