### ISSUE TITLE
Editor tabs bulky

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#15890] opened 2021-06-16 23:06 UTC
Occupy more vertical and horizontal space compared to Spyder 4:

<img src="https://user-images.githubusercontent.com/16495490/122306062-e4386d00-cf18-11eb-9375-a82184de29ba.png" width="800">

Possible to change?

**Comment by ccordoba12** [comment] 2021-06-17 22:20
Hey @OverLordGoldDragon, thanks for reporting. This is basically a duplicate of issue https://github.com/spyder-ide/ux-improvements/issues/41.

We haven't had time to address it, but we hope to do it in the coming months.

**Closed by ccordoba12** 2021-06-17 22:20 UTC
