### ISSUE TITLE
Spyder not listed in Windows search after Windows installer

### ISSUE THREAD

**Issue by epogrebnyak** [spyder-ide/spyder#16168] opened 2021-08-07 09:23 UTC
## Problem Description

I run Windows installer for Spyder 5.1.1, but the application does not appear in Windows search. It is listed in applications list.

This is a bit confusing as Win-S is a common way to find an application, and in my case it does show Anaconda-based installation, but not the MSI-based intallation. So it takes a bit of time to figure out how to run a new version of Spyder.

### What steps reproduce the problem?

1. Download Winodws installer
2. Run the installer 
3. Win-S - Spyder 5 does not show. 

### What is the expected output? What do you see instead?

I expect Windows search to show the icon of Spyder5 after I type `spyder`.

## Versions

* Spyder version: 5.1.1
* Python version: as supplied with spyder
* Operating System name/version: Winodws 10

**Comment by juanis2112** [comment] 2021-08-08 06:17
Hi @epogrebnyak. Thanks for reporting. @dalthviz can you reproduce this behaviour on Windows?

**Comment by dalthviz** [comment] 2021-08-09 19:45
Hi @epogrebnyak I was unable to reproduce this (although I first did an uninstall of a previous Spyder version installed through the Windows installer to do the test).

Did you have installed Spyder through the installer before or is the first time? Let us know!

**Comment by epogrebnyak** [comment] 2021-08-09 20:39
I had an Anaconda installation of Spyder and the new installation was the
first one via installer.

Maybe it is marginal case for Spyder (Windows installer after existing
Anaconda), so feel free to dismiss the issue - perhaps it is a rare
circumstance (more effort maybe needed elsewhere).

пн, 9 авг. 2021 г., 22:45 Daniel Althviz Moré ***@***.***>:

**Comment by dalthviz** [comment] 2021-08-10 05:46
Thank you for the feedback @epogrebnyak ! Maybe it is marginal but I also have Anaconda installed so it could be some other factor :/ Maybe some how the registry entry for the shortcuts is not being taken into account in your case. Could you try to restart your system/machine and check again for the Spyder shortcut through `Win + S` shortcut. Let us know :)

**Comment by epogrebnyak** [comment] 2021-08-11 07:42
The new Spyder is back in Winodws search after deep reboot (with battery recharge, not shown after regular reboot - maybe several reboots played a role). I have both versions of Spyder shown in search now. So if you are experienceing same issue the recipe... is to reboot. 

Should probably close now?

**Comment by dalthviz** [comment] 2021-08-11 07:54
Thank you for the feedback @epogrebnyak ! Since is working now for you I think we could close this one indeed.

Thank you again for letting us know how you manage to make it work :+1:

**Closed by dalthviz** 2021-08-11 07:54 UTC
Labels: OS:Windows, resolution:Completed, tag:Installer
