### ISSUE TITLE
Incorrect auto-indentation

### ISSUE THREAD

**Issue by lxkain** [spyder-ide/spyder#3473] opened 2016-09-28 21:06 UTC
## Description

**What steps will reproduce the problem?**
1. write: s = listener.loc[(listener['listener'] == l) & (listener['session'] == 1)]['sentence_id']
2. press ENTER
3. 

**What is the expected output? What do you see instead?**
The editor indents the next line, but it shouldn't

**Please provide any additional information below**
## Version and main components
- Spyder Version: 3.0.0 
- Python Version: 3.4.5
- Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Dependencies

```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2016-09-29 07:19
Where do you expect the next line to be indented?

**Comment by lxkain** [comment] 2016-09-29 11:52
I see that I was unclear about it. The editor indents this line as if I hadn't close one of the ] brackets. My expectation is that the cursor should go right underneath the first character of the previous line (i.e. unchanged indentation level).

**Comment by ccordoba12** [comment] 2016-11-01 16:01
@rlaverde, since you work on something similar before, please take a look at this one.

**Comment by lhorstma** [comment] 2016-11-01 18:33
I'm having the same Issue! Whenever I type a closing bracket, parenthesis, etc. on a line that was auto indented, the next line is also auto-indented (even though it shouldn't be)

**Comment by rlaverde** [comment] 2016-11-02 02:33
I can not reproduce this issue with the current 3.x branch, (although I can confirm It is present in v3.0.0), could you wait until v3.0.2 release and test if this bug is still happening.

**Comment by ccordoba12** [comment] 2016-11-22 18:42
@rlaverde, please solve this one this week.

**Comment by rlaverde** [comment] 2016-11-23 15:26
@ccordoba12 I'm working on it, I think the logic related to indentation and opening-closing brackets have to be changed (issue #3700 is also related to this, if not the same)

**Comment by ccordoba12** [comment] 2016-11-23 15:27
Yep, I think so too. Thanks for working on these issues :-)

**Closed** 2017-01-07 21:23 UTC
Labels: Comp-Editor, Type-Bug
