### ISSUE TITLE
Autoformat stopped working after opening project

### ISSUE THREAD

**Issue by DarthReca** [spyder-ide/spyder#15478] opened 2021-05-01 08:18 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After opening a Spyder project, autoformat does not format any more the code, also if I open another file or project. 

### What steps reproduce the problem?

1. Open project
2. Source -> Format file or selection with ... (Autopep, Black)

## Versions

* Spyder version: 5.0.1
* Python version: 3.8.8 64-bit
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 

### Dependencies

atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.23.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.7.2 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.18.5 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by steff456** [comment] 2021-05-03 21:18
Hi @DarthReca,

I'm unable to reproduce this issue. I just have two quick questions:
1. The autoformatting is not working or the option is not clickable? Can you also post a gif showing the behavior you are experiencing?
2. Do you have Kite installed?

**Comment by DarthReca** [comment] 2021-05-04 15:55
Hi @steff456,

1. The option is clickable, but pressing it seems to do nothing
2. Kite is installed

I will updated a gif as soon as possible

**Comment by steff456** [comment] 2021-05-04 16:13
Hi @DarthReca,

With the information you gave me, this issue should be fixed by #15448. It will be available in our next version 5.0.2 that is scheduled to be released soon. Please once it is out, update your Spyder and let me know if the error persists.

**Comment by DarthReca** [comment] 2021-05-04 16:22
Hi @steff456,

I upload the the gif to be complete.

![desktop](https://user-images.githubusercontent.com/9790318/117036224-7c7de800-ad05-11eb-91b4-7f3e55d23861.gif)

Thanks for the support, I will wait for the version.

**Closed** 2021-05-11 17:11 UTC
Labels: status:Awaiting Followup
