### ISSUE TITLE
Kernel dies when pandas.read_clipboard() is called

### ISSUE THREAD

**Issue by ayhanfuat** [spyder-ide/spyder#3167] opened 2016-05-13 12:21 UTC
## Description of your problem

Whenever I try to load a dataframe from the clipboard with [pandas.read_clipboard()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_clipboard.html) I see the message "It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console."

**What steps will reproduce the problem?**
1.  Copy some table to clipboard:

```
   c1  c2  c3  c4
0   1   2   2   1
1   1   3   2   3
2   3   4   4   3
3   4   5   6   5
4   5   6   9   7
```
1. Import pandas and call read_clipboard

```
import pandas as pd
df = pd.read_clipboard()
```

**What is the expected output? What do you see instead?**

It is expected to have the table loaded in the dataframe df. Instead, it displays the message:

> It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

**Please provide any additional information below**

I have two environments: one with Python 2.7.11 (named p2) and one with Python 3.5.1 (named p3). Root environment also has Python 3.5.1. The problem does not occur in p2. With Python 3.5.1 it occurs with both pandas v0.18.0 and v0.18.1.

If I run Python (3.5.1 with root env or with p3 env.) from the command line, it loads the dataframe with no errors. 

Environment p3 in Spyder:

![pdclipboard2](https://cloud.githubusercontent.com/assets/6108349/15247486/43ff56d4-191d-11e6-93fc-8480ff912450.PNG)

Root environment:

![pdclipboard1](https://cloud.githubusercontent.com/assets/6108349/15247498/5b8fd3fa-191d-11e6-90aa-29981d9a4c50.PNG)

Environment p3 in command line:

![pdreadclipboard4](https://cloud.githubusercontent.com/assets/6108349/15247521/73ef593e-191d-11e6-81d5-e081612418bf.PNG)

Environment p3 with IPython from the command line:

![pdclipboard5](https://cloud.githubusercontent.com/assets/6108349/15247645/3ba1dc68-191e-11e6-9d2d-d209fffaee9f.PNG)
## Versions and main components
- Spyder Version: 2.3.8
- Python Version: 3.5.1
- Operating system: Windows 10 Pro 64-bit
## Dependencies

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by pbreach** [comment] 2016-05-24 07:27
I have the exact same issue and setup. Hope this gets fixed. The problem only came up after switching from Python 2.7 to 3.5 Anaconda distributions for me.

**Comment by ccordoba12** [comment] 2016-05-25 20:49
This is a very strange problem indeed! We'll try to fix it for Spyder 3.0 :-)

**Comment by KPilnacek** [comment] 2016-06-07 09:51
To me, this happens as well with the same setup.

**Comment by ccordoba12** [comment] 2016-06-24 02:49
I'm sorry but I'm unable to reproduce this problem in Spyder 2.3.9 nor in master using Windows 7 64 bits.

**Comment by pbreach** [comment] 2016-06-24 02:58
Same for me at this time but I'm unsure why...

**Comment by YW1986** [comment] 2016-09-12 14:58
Same here.

**Comment by ayhanfuat** [comment] 2016-09-12 15:23
I am also still experiencing the same problem and couldn't find a workaround. I suspect it is related to qtconsole as it works fine on ipython shell.

**Comment by rishabh-dimri88** [comment] 2016-09-29 19:25
Encountered the same problem in Spyder and Jupyter notebook

![image](https://cloud.githubusercontent.com/assets/22165575/18968898/86494ce8-8650-11e6-89e2-749a6079ac89.png)

**Comment by ccordoba12** [comment] 2016-09-29 20:16
Please update to Spyder 3.0 and try again :-)

**Comment by Foucl** [comment] 2016-09-29 21:21
fwiw, i tried on my windows 10 x64 machine and have no issues with read_clipboard() in spyder 3.0 (running in a python 2.7 environment) and 2.3.9 (with python 3.4).

**Comment by ayhanfuat** [comment] 2016-09-29 21:28
Unfortunately I still have the same issue. In v3.0 it restarts itself though. :)

![ss](https://cloud.githubusercontent.com/assets/6108349/18973090/909fa508-86a4-11e6-8ea5-2f8ba7e22a27.PNG)

**Comment by ayhanfuat** [comment] 2016-10-21 20:26
This is being discussed here as well: https://github.com/jupyter/notebook/issues/1667

I guess it is not a Spyder issue after all.

**Comment by ccordoba12** [comment] 2016-10-22 15:24
Well, that's a relief :-)

**Comment by aravindsd** [comment] 2016-11-13 17:05
**See Pandas documentation to use read_clipboard**
It seems pandas read_clipboard need optional dependencies are which are not yet compatible with python 3.5. I guess that's hindrance for _**read_clipboard**_

http://pandas.pydata.org/pandas-docs/stable/install.html#optional-dependencies

![image](https://cloud.githubusercontent.com/assets/19371042/20247366/58a93212-a9f0-11e6-8a5b-a22eb8ba036d.png)

**Comment by ccordoba12** [comment] 2017-08-13 18:01
Closing because there's nothing we can do in Spyder about this.

**Closed by ccordoba12** 2017-08-13 18:01 UTC
Labels: component:IPython Console, type:Bug
