### ISSUE TITLE
Connecting to kernel fails because of update to Matplotlib 1.5

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#2793] opened 2015-10-31 23:21 UTC
Since two days, my spyder ide does not connect to a kernel anymore?
When I start spyder, the IPython console shows "Connecting to kernel ...." and gets stuck on that

when I look into the console, it says:

'import sitecustomize' failed; use -v for traceback
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049

**Comment by xaverm** [comment] 2015-11-01 09:52
Please let me add some more info to this issue. Any help would be most appreciated! Thank you.

1) the system this occurs on is linux `openSUSE 13.1 (x86_64)`, version = `13.1`, codename = Bottle, `kernel 3.11.10-29-desktop`

2) running ipython in a terminal I have: `Python 2.7.6`, `IPython 3.2.1`

3) Spyder's version is `Spyder 2.3.7`. This version is from Tue 06 Oct 2015, and has been installed on Oct. 11. Since then Spyder has been used heavily without issues until ~2 days ago.

4) the issue is **not user-specific**. Setting up a fresh default user with non-existent `~/.ipython` and non-existent `~/.spyder` and invoking spyder for its first time for this user will produce the same issue

5) 'other' ipython dev-tools, like ipython's-browser notebook work without problems

6)  I don't know if this is of any help, but I have attached a figure showing the update history of the system for the last ~10 days, only related to potential python stuff, i.e. the output of `tail -200 /var/log/zypp/history | grep insta | grep py`
![update](https://cloud.githubusercontent.com/assets/2843926/10868172/7e90d4a2-8085-11e5-84ce-29a0a287b483.png)

**Comment by TurkishGetup** [comment] 2015-11-01 17:53
There seems to be compatibility issues with the recent updated matplotlib-1.5.0 and spyder. I had similar problems after upgrading matplotlib. Downgrading matplotlib to 1.4.3 fixed the problem for me. I am on Manjaro Linux.

**Comment by xaverm** [comment] 2015-11-01 22:29
Yes, your suggestion works for me for now. Thank you!
This is certainly not an optimal state of affairs. Hopefully there will be a true fix soon? Matplotlib is among the most rapidly moving targets on the scene. So a remaining compatibility issue with Spyder would be awkward.

**Comment by ELE3E** [comment] 2015-11-02 08:04
Worked for me too. I've been trying solutions for days now. Finally!

**Comment by davidovitch** [comment] 2015-11-02 18:20
This doesn't seem to affect the python3 version of Matplotlib/Spyder (on my Arch Linux installation at least).

**Comment by dallasmasters** [comment] 2015-11-02 19:58
Bump. Confirmed for me too.

**Comment by ELE3E** [comment] 2015-11-02 20:10
Shouldn't this be posted as a matplotlib issue instead?

**Comment by TimothyVD** [comment] 2015-11-03 14:49
I had the same problem (OpenSuse 13.1/python2.7/matplotlib1.5-dev/latest spyder version). I could fix the automatic connection to the kernel if I removed the cycler module. However, this module is required by matplotlib1.5-dev. I "fixed" this issue by manually connecting to an external kernel, but in that way no plots are shown (I only had to save figures).

**Comment by ccordoba12** [comment] 2015-11-03 16:23
Thanks for the report and for finding the solution. I'll investigate what's happening and try to solve the problem as soon as possible.

**Comment by hmendozap** [comment] 2015-11-04 21:47
Confirmed on Ubuntu 14.04, ipython 4.0.0 and Spyder 2.3.7. I had to revert to matplotlib 1.4.3

**Comment by ccordoba12** [comment] 2015-11-16 00:14
I can reproduce the error and will fix it in version 2.3.8 (to be released in a couple of days).

I had to wait until Continuum released packages for Matplotlib 1.5 to test this. Thanks for your patience :-)

**Closed** 2015-11-22 16:42 UTC
Labels: bug, IPython-Console
