### ISSUE TITLE
Typing on the editor is very slow

### ISSUE THREAD

**Issue by vin9912** [spyder-ide/spyder#16051] opened 2021-07-20 17:18 UTC
### What steps will reproduce the problem?

1. Opened Spyder
2. Typed into editor

I use MacOS Catalina 10.15.7 and Spyder 5.0.5. Typing is significantly laggy but weirdly there's no such problem if I typed into the console.

**Comment by ccordoba12** [comment] 2021-07-21 00:31
Hey @vin9912, thanks for reporting. This is a duplicate of issue #15631. Please take a look at it for possible workarounds.

**Closed by ccordoba12** 2021-07-21 00:31 UTC
