### ISSUE TITLE
Show graphics, windows 10 , python 3.9.6, ryzen 5 3400 G , Vegas 11 2GB

### ISSUE THREAD

**Issue by Walberf17** [spyder-ide/spyder#16272] opened 2021-08-24 10:40 UTC
### What steps will reproduce the problem?

I am trying to use matplotlib...

not showing graphics, so I went to Tools > Preferences > IPython Console> Graphics > Graphics backend > Backend > 

then I tryed to set as automatic, but it doens't connect to Kernel, 

So i went the same path again and try change it again, but this error happens.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Program Files\Spyder\pkgs\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 453, in apply_plugin_settings
    for client in self.clients]
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 453, in <listcomp>
    for client in self.clients]
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 353, in get_matplotlib_backend
    blocking=True).get_matplotlib_backend()
  File "C:\Program Files\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 555, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 212, in _get_call_return_value
    raise CommError("Cannot block on a disconnected comm")
spyder_kernels.comms.commbase.CommError: Cannot block on a disconnected comm
```

## Versions

* Spyder version: 5.1.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.3 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment] 2021-08-24 14:19
Hey @Walberf17, thanks for reporting. This is a duplicate of issue #15875, so I'm going to close your bug report in favor of that one.

Just leave a message on that issue if you want to follow the progress of solving this bug.

**Closed** 2021-08-24 14:19 UTC
