### ISSUE TITLE
Anaconda Launcher Reports I have ver 2.3.7 whereas I have 2.3.6. Error starting 

### ISSUE THREAD

**Issue by ArthurZ** [spyder-ide/spyder#2794] opened 2015-11-01 20:11 UTC
The Anaconda Launcher reports I have ver 2.3.7 installed, but when I start it from the Launcher I am getting an error:
Please check Spyder installation requirements: PyQt4 4.6+ (or PySide 1.2.0+) is required.
I am on Windows 7 Pro 64 Bit.
However, there is no problem starting Spyder from the Start menu, but it is ver. 2.3.6 in Help --> About.
Note: I attempted to run conda update -all and was getting linking errors

**Comment by ccordoba12** [comment] 2015-11-04 21:24
I think this is going to be fixed in a couple of days.

**Comment by ccordoba12** [comment] 2015-11-04 21:25
By the Anaconda team, I mean, not by us :-)

**Comment by ccordoba12** [comment] 2015-11-16 00:11
Closing because this is not a bug in Spyder but in Anaconda. I think this can be fixed by running

    conda update python

and then running

    conda update pyqt

**Closed by ccordoba12** 2015-11-16 00:11 UTC
