### ISSUE TITLE
%prun bug in console

### ISSUE THREAD

**Issue by KidElectric** [spyder-ide/spyder#14631] opened 2021-01-21 18:32 UTC
### What steps will reproduce the problem?

Define function fun(input1,input2) in cell block.

in console, attempt to run:
%prun fun(input1,input2)-> upon typing first parenthesis this error occurs. Probably something about looking up documentation for Help tab kills it

### Traceback
```python-traceback
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/control.py", line 58, in keyPressEvent
    self._key_paren_left(text)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/control.py", line 50, in _key_paren_left
    self.show_object_info(last_obj)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 1446, in show_object_info
    self.help.set_object_text(text, ignore_unknown=False)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/plugins/help/plugin.py", line 528, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/plugins/help/plugin.py", line 718, in show_help
    source_text = shell.get_source(obj_text)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/help.py", line 151, in get_source
    ).get_source(objtxt)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 555, in __call__
    call_dict, call_data, self._comm_id)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 152, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 437, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 493, in _sync_error
    error_wrapper.raise_error()
  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_source:

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 343, in _handle_remote_call
    buffer['call_kwargs'])

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 354, in _remote_callback
    *call_args, **call_kwargs)

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/console/kernel.py", line 398, in get_source
    return getsource(obj)

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/utils/dochelpers.py", line 164, in getsource
    src = to_text_string(inspect.getsource(obj))

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/inspect.py", line 965, in getsourcelines
    return getblock(lines[lnum:]), lnum + 1

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/inspect.py", line 940, in getblock
    for _token in tokens:

  File "/home/brian/anaconda3/envs/py37/lib/python3.7/tokenize.py", line 519, in _tokenize
    raise TokenError("EOF in multi-line string", strstart)

tokenize.TokenError: ('EOF in multi-line string', (2, 0))

```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.8.0-40-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.4.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.2.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.0.5 (NOK)
scipy >=0.17.0                  :  1.4.1 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by andfoy** [comment] 2021-01-22 03:24
Hi @KidElectric, thanks for opening this issue, could you please provide a GIF with a set of reproducible steps for this error?

**Comment by andfoy** [comment] 2021-01-28 23:14
I'm closing this one, since there was not a follow up answer during the last week.

**Closed by andfoy** 2021-01-28 23:14 UTC
Labels: status:Awaiting Followup
