### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hartmann/.spyder-py3/profiler.results

### ISSUE THREAD

**Issue by mjhartmann** [spyder-ide/spyder#5701] opened 2017-11-08 16:30 UTC
## Description

Hi,

I have seen similar problems reported but none of the suggested fixes seemed to work in my case:

**What steps will reproduce the problem?**

1. I'm trying to profile python code 
2. press "Stop" to stop profiling
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/anaconda3/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "/anaconda3/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "/anaconda3/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "/anaconda3/lib/python3.6/site-packages/spyder_profiler/widgets/profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "/anaconda3/lib/python3.6/pstats.py", line 72, in __init__
    self.init(arg)
  File "/anaconda3/lib/python3.6/pstats.py", line 86, in init
    self.load_stats(arg)
  File "/anaconda3/lib/python3.6/pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hartmann/.spyder-py3/profiler.results'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin
* Mac OS High Sierra 10.13.1

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by rlaverde** [comment] 2017-11-08 22:53
Closing as duplicate of #5587, the fix will be released as a part of spyder3.2.5

**Closed by rlaverde** 2017-11-08 22:53 UTC
