### ISSUE TITLE
Internal problem when using Pytorch in another enviornment

### ISSUE THREAD

**Issue by newyorker123** [spyder-ide/spyder#16657] opened 2021-10-29 08:55 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm using a latest standalone version spyder on my MacOs with miniconda. Everything works fine on the base environment.

And I create a new environment by conda, install the spyder-kernal. Other packages like numpy works fine on Spyder Ipython console of the new environment.

But after I install Pytorch in the new environment, and import it in the  IPython console, and run`x = torch.rand(5, 3)` ,a window would pop out and says internal problems`ModuleNotFoundError: No module named 'torch'`. And no matter what code I run after that, the window would keep popping out.  While there is no error reported in the console, and the `x` is indeed created and can be printed.

The issue#14734 seemed the same. But the conclusion there is to install a spyder in the new environment instead of using spyder-kernal. But I really want to avoid that. So is it possible to fix this?

### What steps reproduce the problem?

1. creat a new conda environment and install Pytorch
2. import Pytorch
3. run Pytorch code

### What is the expected output? What do you see instead?
<img width="1221" alt="截屏2021-10-29 下午5 12 32" src="https://user-images.githubusercontent.com/43869995/139409447-a2ff0b8b-200e-49f5-8428-a8d7d7f80b2b.png">

### Paste Traceback/Error Below (if applicable)

```python-traceback
Exception in comms call get_namespace_view:
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/comms/commbase.py", line 314, in _comm_message
ModuleNotFoundError: No module named 'torch'
```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Mac Os Big Sur

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by steff456** [comment] 2021-11-01 15:59
Hi @newyorker123,

Indeed we have received a couple of these issues with the same error. we are not sure why this is happening, but can you try installing the latest version of Spyder with the macOS installer and then connect to this environment that has spyder-kernels and Pytorch? Please let me know if the error persists.

**Comment by newyorker123** [comment] 2021-11-01 16:23
> Hi @newyorker123,
> 
> Indeed we have received a couple of these issues with the same error. we are not sure why this is happening, but can you try installing the latest version of Spyder with the macOS installer and then connect to this environment that has spyder-kernels and Pytorch? Please let me know if the error persists.



> Hi @newyorker123,
> 
> Indeed we have received a couple of these issues with the same error. we are not sure why this is happening, but can you try installing the latest version of Spyder with the macOS installer and then connect to this environment that has spyder-kernels and Pytorch? Please let me know if the error persists.

Do you mean to uninstall the Spyder I'm currently using and reinstall it again?  Cause the Spyder I'm using now already is the latest standalone MacOS version

**Comment by steff456** [comment] 2021-11-01 19:56
My bad! I thought you installed Spyder directly from conda, we will try to track this down, it is a really weird problem but for now please install Spyder in that environment.

**Comment by alextimans** [comment] 2021-11-01 20:16
Had exactly the same issue literally yesterday, installing spyder locally in the specified env did the trick for me. Still very weird though, cleaning the env, updating spyder-kernels etc. nothing fixed it. I'm using the standalone macOS with miniforge on an M1 Air, thought it might be related to the miniforge distribution but apparently not so. Hope this will find a resolve, I really enjoy having a single spyder install only.

**Comment by eichlerwest** [comment] 2022-09-29 17:19
I am having the same problem with the latest standalone on M1 Air. When I try from the environment, I get an error that I need to use spyder-kernels=2.3 even though I am already using that version.

**Comment by ccordoba12** [comment] 2023-03-05 19:15
Since this is referring to Pytorch, I'm going to close this issue as a duplicate of #16456.

**Closed by ccordoba12** 2023-03-05 19:15 UTC
Labels: status:Awaiting Followup
