### ISSUE TITLE
Code Folding shortcuts in spyder IDE

### ISSUE THREAD

**Issue by uprokevin** [spyder-ide/spyder#22195] opened 2024-06-22 08:41 UTC
Hello,

is it possible to create a shortcut to folder all code up to some level ?
Reason is we often work with very large files...

Stackoverflow:
https://stackoverflow.com/questions/59943300/keyboard-shortcut-for-code-folding-in-spyder

2018 open issue:
https://github.com/spyder-ide/spyder/issues/6810
https://github.com/spyder-ide/spyder/issues/2430

Thanks !

**Comment by jmoraispk** [comment] 2024-07-04 03:09
Hi @uprokevin 

I am also interested in this code-folding feature. Is it already possible, Carlos @ccordoba12 ?

I often have multiple cells (#%%) and want to close all of them, but I don't know how. 

I have been a donator for two years and will continue to be. This feature would be a nice addition. 

(On a separate note, improving remote development would be amazing too. I just had to switch to vs code for remote development in a container because even though I could setup spyder kernels there, most features like debugging didn't work)

**Comment by dalthviz** [comment] 2024-11-27 00:22
> 2018 open issue:
https://github.com/spyder-ide/spyder/issues/6810

Hi there, so as mentioned this is a duplicate of https://github.com/spyder-ide/spyder/issues/6810

> (On a separate note, improving remote development would be amazing too. I just had to switch to vs code for remote development in a container because even though I could setup spyder kernels there, most features like debugging didn't work)

There is some ongoing work to improve remote development capabilities inside Spyder. Not totally sure about remote debugging although it seems there are some issues open about that which we will try to tackle in future releases (issue like https://github.com/spyder-ide/spyder/issues/21996 https://github.com/spyder-ide/spyder/issues/10946) 🤔 

Since seems like a round of questions and answer related to the code folding shortcuts idea has been done over https://github.com/spyder-ide/spyder/issues/21009 I will be closing this. However, any further feedback related with the shortcuts for the code folding is appreciated over #6810 Thank you!

**Closed by dalthviz** 2024-11-27 00:22 UTC
Labels: resolution:Duplicate

**Comment by ccordoba12** [comment] 2024-11-27 16:58
> I have been a donator for two years and will continue to be. This feature would be a nice addition.

@jmoraispk, sorry for the late reply. I agree with what you said and we'll try to implement it next year (the problem is that right now we are understaffed for all the things we'd like to do).
