### ISSUE TITLE
Plotting in master branch has issues(2.3 works)

### ISSUE THREAD

**Issue by anderwm** [spyder-ide/spyder#2263] opened 2015-03-23 20:59 UTC
Plots generated inside a python console cannot be displayed when the code is checked out from Master.  Plotting works as expected in Ipython console, and also works as expected in 2.3.

The plot is generated [matplotlib.lines.Line2D object at 0x7f165e88b110] but can't be .show()  Even with ion() it doesn't display.

**Comment by ccordoba12** [comment] 2015-03-23 23:09
Thanks for reporting, this is a duplicate of issue #2231.

**Closed by ccordoba12** 2015-03-23 23:09 UTC
Labels: duplicate

**Comment by anderwm** [comment] 2015-03-24 02:38
Sorry, I looked for a similar issue... But I guess not hard enough.

**Comment by SylvainCorlay** [comment] 2015-03-24 02:47
Thanks for reporting anyway.

**Comment by ccordoba12** [comment] 2015-03-24 15:59
Yes, don't worry about it ;-) Thanks for reporting, this will be fixed 
in beta1.
