### ISSUE TITLE
Add reset button to the Variable Explorer

### ISSUE THREAD

**Issue by mvkrdndm** [spyder-ide/spyder#2985] opened 2016-02-14 00:33 UTC
hi,  would not be more easy if we could use a button instead of typing on ipython console for resetting values  " typing %reset and afterwards confirming it " is being used a lot

![image 002](https://cloud.githubusercontent.com/assets/16892782/13030909/953f384e-d2c2-11e5-860f-e6a3f647a083.png)

**Comment by Prikers** [comment] 2017-07-30 21:07
I am very interested in having this feature (same as the R Studio broom). There is already a `reset_namespace` method available in for the iPython console so there may not be a lot of modifications. However as it involves adding a new icon / changing the interface, I guess you would prefer to keep the PR in the core dev team, correct?

As a new feature it is tagged v4.0 but if this is an easy one, do you think this could be part of the v.3.x serie?

(by the #313 may be a duplicate of this one)

**Comment by ccordoba12** [comment] 2017-07-30 22:01
You're right, this is a duplicate of issue #313.

**Closed by ccordoba12** 2017-07-30 22:01 UTC
Labels: component:Variable Explorer, resolution:Duplicate, type:Enhancement

**Comment by ccordoba12** [comment] 2017-07-30 22:04
And sure, we'll take a look at this in a future 3.x release.
