### ISSUE TITLE
Spyder is very slow

### ISSUE THREAD

**Issue by surrealvarez** [spyder-ide/spyder#11187] opened 2019-12-27 14:47 UTC
### What steps will reproduce the problem?

Spyder is very slow when a a file with many lines is open. Also, Kite uses too much memory and it is incredibly slow. Please, either improve this or remove Kite since the autocompletion is not really the fastest.

### Traceback
```python-traceback
  File "C:\Users\wv5945\AppData\Local\Continuum\anaconda3_2\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 256, in paintEvent
    self._draw_fold_region_background(block, painter)
  File "C:\Users\wv5945\AppData\Local\Continuum\anaconda3_2\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 300, in _draw_fold_region_background
    end = self.folding_regions[start]
KeyError: 3315
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.3
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.12 (OK)
IPython >=4.0                :  7.6.1 (OK)
matplotlib >=2.0.0           :  3.1.0 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by OverLordGoldDragon** [comment] 2019-12-27 20:00
Can confirm; with multiple tabs open w/ ~1000 lines each, scrolling and moving the cursor becomes quite laggy - don't know if Kite's responsible, will try disabling.

**Comment by ccordoba12** [comment] 2019-12-28 00:41
Duplicate of #11001

**Comment by ccordoba12** [comment] 2019-12-28 00:42
Duplicate of #10918

**Closed by ccordoba12** 2019-12-28 00:41 UTC

**Comment by ccordoba12** [comment] 2019-12-28 00:42
The slowness issues will be fixed in 4.0.1, to be released next week.

**Comment by ccordoba12** [comment] 2019-12-28 00:44
Besides, we don't have control over what Kite does, but you can uninstall it and use Spyder without problems.

**Comment by texadactyl** [comment] 2020-01-02 17:35
@ccordoba12 Just received the 4.0.1 email notification.  Tried `conda install -y spyder=4.0.1` and the update is not there yet.  Was I too quick on the gun?

**Comment by ccordoba12** [comment] 2020-01-02 17:37
The release is out but conda packages take a couple of days to be uploaded by the Anaconda team. I informed them already about the new version, but we can't do anything else about it,

**Comment by texadactyl** [comment] 2020-01-02 17:39
No worries.

I am used to other folks who do not email until repos are verified as updated.  That is also what I do for my Linux contributions too.  But, that is not a criticism.

**Comment by DGuidi** [comment] 2020-09-22 07:05
for my experience (spyder 4.1.4) I see that spyder is almost unusable if I turn off kite for autocompletion.
Not found an option to disable integration.
