### ISSUE TITLE
Autoformat files on save

### ISSUE THREAD

**Issue by alandema** [spyder-ide/spyder#16134] opened 2021-08-03 12:12 UTC
### What steps will reproduce the problem?

I'm trying to use the feature of autoformat file on save for autopep8. It usually worked fine in 4.2.5, but now when I save the file, some lines are duplicated at the end of the script.

It does not seems to have a pattern of how many lines it will repeat. Also sometimes, trying to save again will not reproduce the problem.

To try to reproduce you can simply
```
import numpy as np
```
And save. 

In my case it will append a line 
```
 as np
```
in the end of my script.

I'm using python 3.8.6 and Windows 7

**Comment by ba-tno** [comment] 2021-08-03 14:02
Probably a duplicate of #16123?

**Comment by alandema** [comment] 2021-08-03 14:35
> Probably a duplicate of #16123?

 Indeed,it looks like the same problem.

**Closed** 2021-08-03 14:37 UTC
