### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by xushiluo** [spyder-ide/spyder#6605] opened 2018-03-05 12:49 UTC
OS: windows 10 64bit
1. Click Tools->Preferences->Syntax coloring
2. Select Scheme: **Spyder Dark** and click **apply** button
3. Then, Spyder internal error occurs

**Comment by ccordoba12** [comment] 2018-03-05 14:23
Thanks for reporting. This is a duplicate of issue #6519, which will be fixed in our next version.

**Closed by ccordoba12** 2018-03-05 14:23 UTC
