### ISSUE TITLE
Update PyQt5 requirements

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder#16068] opened 2021-07-23 12:12 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Currently the spyder requirements request PyQT5<5.13 (set in https://github.com/spyder-ide/spyder/pull/8756) . The latest PyQt5 release from 5.12.x is from June 2019.

Can we update the PyQt5 requirements? Several other packages are requesting versions > 5.12.

@ccordoba12 

### What steps reproduce the problem?

Download and install Spyder

### What is the expected output? What do you see instead?

Not relevant

### Paste Traceback/Error Below (if applicable)

Not relevant

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.x
* Python version:  Any
* Qt version: Any
* PyQt version: 5.x
* Operating System name/version: Any

### Dependencies

```
Not relevant
```

**Comment by juanis2112** [comment] 2021-07-24 01:58
@eendebakpt thanks for reporting. @ccordoba12 can you take a look at this one?

**Comment by ccordoba12** [comment] 2021-07-24 18:12
There are two things about this:

* We don't have a big incentive to update our requirement because Anaconda, which is our main distribution channel by far, only has packages for Qt 5.12.
* However, thanks to a contract with a client, we're in the process of creating conda packages for Qt 5.15. So, we'll add support for more recent versions in the coming months.

**Comment by ccordoba12** [comment] 2021-07-24 18:14
I'm going to close this issue as a duplicate of #12829.

**Closed by ccordoba12** 2021-07-24 18:14 UTC
