### ISSUE TITLE
List of ignored linting warnings/errors not applied after app restart

### ISSUE THREAD

**Issue by whitehat007** [spyder-ide/spyder#13803] opened 2020-09-18 02:34 UTC
### What steps will reproduce the problem?

Every time I launch Spyder, the linting engine will fail to respect the list of ignored warnings/errors I set in preferences. Modifying the list in some way (say, add a space then delete) and then pressing Apply fixes the issue for the current session.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment] 2020-09-18 12:24
Hey @whitehat007, thanks for reporting. Do you start Spyder with an open project?

**Comment by whitehat007** [comment] 2020-09-18 12:29
Yes I do, and if I have multiple files open, the problem is with all of them (though I only need to do the workaround once).

**Comment by ccordoba12** [comment] 2020-09-18 14:54
That's what I imagined. This is a duplicate of issue #13351 and we'll try to fix it in our next release.

In the meantime, you can restart the Python language server by clicking on the `LSP Python` entry in our status bar to correctly apply your settings after Spyder starts:

![Selección_104](https://user-images.githubusercontent.com/365293/93612158-c68fa480-f994-11ea-9933-eb6a65d5d052.png)

**Closed by ccordoba12** 2020-09-18 14:54 UTC
Labels: status:Awaiting Followup
