### ISSUE TITLE
Not able to launch Ipython console from Spyder

### ISSUE THREAD

**Issue by barthwalsamarth** [spyder-ide/spyder#2720] opened 2015-09-26 20:03 UTC
## Description

**What steps will reproduce the problem?**

1. Click a console
2. Open an Ipython console
3. 

**What is the expected output? What do you see instead?**
<img width="1440" alt="screen shot 2015-09-26 at 22 03 09" src="https://cloud.githubusercontent.com/assets/9243770/10119589/674cc708-649a-11e5-89ea-7b2d9e4d2118.png">

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment] 2015-09-28 01:34
This is a duplicate of issue #2709

**Closed by ccordoba12** 2015-09-28 01:35 UTC
Labels: duplicate

**Comment by ccordoba12** [comment] 2015-09-28 14:49
Sorry, the right duplicate issue is #2679.
