### ISSUE TITLE
Environment variables in standalone Spyder

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#17890] opened 2022-05-15 23:27 UTC
Hi,

I am using the Spyder standalone version on macOS, and when I set environment variables in  `~/.zshrc`, Spyder doesn't seem to be able to pick them up.  As a result, I cannot access them in Spyder via `os.environ[...]`.

Is this an expected behavior, or a bug?  Thank you!

I also searched the official Spyder documentation and couldn't find an explanation.

**Comment by mrclary** [comment] 2022-05-16 20:19
@jsh9, thanks for reporting this issue! I'll investigate this issue for you and get back.

**Comment by mrclary** [comment] 2022-05-16 20:20
@jsh9, sorry, forgot to confirm: are you using Spyder version 5.3.0?

**Comment by mrclary** [comment] 2022-05-16 22:02
@jsh9, I am unable to reproduce the issue with Spyder 5.3.0 on my M1 iMac which has zsh as the default shell. If you have environment variables set in `~/.zshrc`, they should be available in IPython consoles. This feature was added for Spyder 5.3.0, so if you are not using that version you will have to update. If you are using Spyder 5.3.0, please share more information about your system so that I can try again to reproduce the issue.

**Comment by mrclary** [comment] 2022-08-29 16:13
@jsh9, was your issue resolved? We have not received feedback for some time, so I will close this issue. If your problem has not been resolved, please feel free to reopen the issue.

**Closed by mrclary** 2022-08-29 16:13 UTC
Labels: status:Awaiting Followup
