### ISSUE TITLE
Untitled file won't close annoying bug

### ISSUE THREAD

**Issue by PierreRaybaut** [spyder-ide/spyder#2634] opened 2015-08-23 13:55 UTC
Hi there,

As a simple user, I'm reporting an annoying bug :)

How to reproduce it with Spyder v2.3.5.2 on Windows (10):
1. Close all opened files.
2. Restart Spyder: there should be only the "temp.py" file, as expected.
3. Leave the temp.py file opened.
4. Open 3 or 4 files.
5. Close all files (Ctrl+Shift+W).
==> The temp.py file is renamed "untitled0.py" and Spyder ask if it should be saved before closed.
Ok, why not, but, when answering "No", the "untitled0.py" file is renamed "untitled1.py" and Spyder asks again if it should be saved before closed, and so on and so forth.

-Pierre

**Comment by ccordoba12** [comment] 2015-08-23 15:11
Hey @PierreRaybaut!! Good to see you're still using Spyder :-)

This is a duplicate of issue #2625. I'll fix it on **2.3.6**.

**Closed by ccordoba12** 2015-08-23 15:11 UTC
Labels: duplicate

**Comment by ccordoba12** [comment] 2015-08-23 15:13
Sorry, I forgot to mention that **2.3.6** will be released next week. It's main purpose is making Spyder compatible with IPython/Jupyter 4.0.

**Comment by PierreRaybaut** [comment] 2015-08-23 15:17
Yep. Still using it :)
