### ISSUE TITLE
commandes in Python consol need many (lot of) "enter" to execute

### ISSUE THREAD

**Issue by matthias2t** [spyder-ide/spyder#3532] opened 2016-10-13 13:41 UTC
## Description of your problem
When starting Spyder, pressing F5 to run a file writes the command ("run ... .py") but I have to press enter many many times to launch the program.

**What steps will reproduce the problem?**

1. updating Spyder (conda update qt pyqt &conda install spyder)
2. opening a script
3. press F5

**What is the expected output? What do you see instead?**
Expected output is to run the script.
Instead, Nothing happens. No prompt is shown. If I press Enter about 20 times, the script executes correctly.

**Please provide any additional information below**
it works fine with IPython

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5.1 
* Operating system: windows10-64
Python 3.5.1 |Anaconda 4.1.1 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5a1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-13 14:11
Thanks for reporting. This is a duplicate of issue #1831.

**Closed by ccordoba12** 2016-10-13 14:11 UTC
