### ISSUE TITLE
"SyntaxError: 'await' outside function" when using Run cell

### ISSUE THREAD

**Issue by nbud** [spyder-ide/spyder#14938] opened 2021-03-16 17:10 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

IPython allows using await keyword outside functions, which is very helpful for debugging ([%autoawait magic](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html)).

Consider the following snippet:

```
async def ping():
    return "pong"

await ping()
```

### What steps reproduce the problem?

1. Create new file, copy above snippet
2. Run > Run cell

### What is the expected output? What do you see instead?

- Expected output: "pong"
- Actual result: SyntaxError: 'await' outside function

Note that selected the code and performing *Run > Run selection* (F9) gives the expected "pong".

 Running the file (Run >Run, F5) also gives a SyntaxError, which I consider being the correct behaviour.

As a comparison, Visual Code gives a SyntaxError when running the file, but runs successfully when running the cell. For me, this is the best behaviour, hence the present ticket.

## Versions

Freshly installed from ``conda create -n spyder spyder``

* Spyder version: 4.2.3 None
* Python version: 3.9.2 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

* IPython 7.21.0

**Comment by ccordoba12** [comment] 2021-03-17 00:23
Hey @nbud, thanks for reporting. I didn't know that IPython allows you to do that.

For now, I think you need to switch from using the `runcell` command to paste the contents of cells directly into the console. For that, you need to go to the menu:

    Tools > Preferences > Editor > Run Code

and activate the option called `Copy full cell contents to the console when running code cells`.

**Comment by ccordoba12** [comment] 2021-03-17 00:23
@impact27, do you think we could something else about this?

**Comment by nbud** [comment] 2021-03-17 07:48
Thank you @ccordoba12, your workaround worked.

**Comment by impact27** [comment] 2021-03-17 08:26
This might be relevant:
https://github.com/jupyter/qtconsole/issues/377

**Comment by impact27** [comment] 2021-03-17 08:44
The problem is that the python way of doing that would be:
```
asyncio.run(ping())
```
But that doesn't work with ipykernel because there already is an asyncio loop running. The workaround they found was to allow instead:
```
await ping()
```
But that is not proper python. Therefore it doesn't really make sense to expect a random await in a python file. I am not sure what the solution is here.

**Comment by ccordoba12** [comment] 2021-03-17 23:53
> Therefore it doesn't really make sense to expect a random await in a python file.

Ok, I understand that and it makes sense to me.

> I am not sure what the solution is here.

I think the only possible solution for now is to avoid using `runcell`, as I mentioned above. So I'm going to close this one.

**Closed by ccordoba12** 2021-03-17 23:53 UTC
Labels: status:Awaiting Followup
