### ISSUE TITLE
Spyder launch script opens in Editor on startup

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#10471] opened 2019-10-20 19:22 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Since Spyder 4.0.0.b5, when launching, the startup script is opened in the Editor.

I'm using an anaconda installation and a dedicated Spyder environment.

### What steps reproduce the problem?

1. When Spyder is open, ensure that `~/anaconda3/envs/<spyder env>/bin/spyder` is not currently open in the Editor and quit Spyder.
2. Open Spyder
```
(<spyder env>) >> spyder
```
3. Observe the Editor opening any previously open documents _and_  `~/anaconda3/envs/<spyder env>/bin/spyder`

### What is the expected output? What do you see instead?
I expect the Editor to open only those documents that were open when Spyder was last quit.

## Versions

* Spyder version: 4.0.0b5 and above
* Python version: 3.7.0 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Darwin 18.7.0 (Mac OS 10.14.6)

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by mrclary** [comment] 2019-10-20 19:23
To be clear, this does not happen in 4.0.0b4 but does happen in 4.0.0b5, 4.0.0b6, and 4.0.0b7.

**Comment by ccordoba12** [comment] 2019-10-21 00:18
Thanks for reporting. This is a duplicate of issue #10436 and it'll be fixed in our next version.

**Closed by ccordoba12** 2019-10-21 00:18 UTC
