### ISSUE TITLE
Unexpected shut down

### ISSUE THREAD

**Issue by saikumar010** [spyder-ide/spyder#7923] opened 2018-09-20 07:24 UTC
## Description

**What steps will reproduce the problem?**

1. Opening a new file 
2. Browsing the working directory while a file is open in the editor
3. Anyhow I try to open a new file when a file is already open in the editor

**What is the expected output? What do you see instead?**
To open a new file or browse files in a directory. Instead, the spyder application shuts down.

**Please provide any additional information below**
The workaround for this problem is that I have to close all files that are open in the editor and only then I would be able to browse files or open a new file. Please try to fix this issue or let me know if there is something that I have to do from my side to solve this issue, Thanks!

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2018-09-20 19:26
This looks like a duplicate of #3903. Please look there for a possible solution.

You can also try to update PyQt and see if that helps by closing Spyder, opening an Anaconda Prompt running there

    conda update pyqt
    conda install sip=4.19.8

and trying again.

**Comment by ccordoba12** [comment] 2018-10-03 14:47
Closing because of lack of response.

**Closed by ccordoba12** 2018-10-03 14:47 UTC
Labels: status:Awaiting Followup
