### ISSUE TITLE
Spyder Internal Problem with DataFrame (pandas 2.0.0)

### ISSUE THREAD

**Issue by PhilipYip1988** [spyder-ide/spyder#20770] opened 2023-04-04 09:47 UTC
## Problem Description

Opening a pandas (version 2.0.0) dataframe in Spyder shows an internal error.

### What steps reproduce the problem?

1.  Install Spyder in Python environment with pandas 2.0.0
2. Create a dataframe
3. Open the dataframe in the variable explorer

### What is the expected output? What do you see instead?

An internal error displays.

### Paste Traceback/Error Below (if applicable)

```
Traceback (most recent call last):
  File "C:\Users\pyip\AppData\Local\mambaforge\envs\spyder\Lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 211, in createEditor
    if not editor.setup_and_check(value, title=key):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pyip\AppData\Local\mambaforge\envs\spyder\Lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 957, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pyip\AppData\Local\mambaforge\envs\spyder\Lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "C:\Users\pyip\AppData\Local\mambaforge\envs\spyder\Lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 244, in max_min_col_update
    for __, col in self.df.iteritems():
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\pyip\AppData\Local\mambaforge\envs\spyder\Lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'iteritems'. Did you mean: 'isetitem'?
```

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.11.2 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.12.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.10 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.17.1 (OK)
pylint_venv >=2.1.1           :  3.0.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.1 (OK)
qtpy >=2.1.0                  :  2.3.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.6.1 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  3.0.0 (OK)
zmq >=22.1.0                  :  25.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=3.0.0            :  3.7.1 (OK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  2.0.0 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)

```

**Comment by ccordoba12** [comment] 2023-04-04 15:00
Hey @PhilipYip1988, thanks for reporting. This is a duplicate of issue #20496 and it'll be fixed in our next version (5.4.3), to be released later today.

In the meantime, please downgrade to Pandas 1.5.

**Closed by ccordoba12** 2023-04-04 15:00 UTC
