### ISSUE TITLE
Hover tips crash itself

### ISSUE THREAD

**Issue by liuyigh** [spyder-ide/spyder#10852] opened 2019-11-26 17:45 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hover tips crash itself. Does not crash Spyder.

### What steps reproduce the problem?

1. Open spyder and a python file
2. Point cursor to an object, such as `np.arange()`
3. Hover tip crashes

### What is the expected output? What do you see instead?
Expect a hover tip. I see a crash report window instead.

### Paste Traceback/Error Below (if applicable)

```python-traceback

  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1217, in handle_hover_response
    at_point=self._last_point)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 634, in show_hint
    inspect_word=inspect_word)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/widgets/mixins.py", line 474, in _check_signature_and_format
    name_plus_char = inspect_word + open_func_char
TypeError: can only concatenate tuple (not "str") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3716, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3598, in run_spyder
    app.exec_()
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 349, in on_msg_received
    handler(resp['result'], req_id)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 169, in process_hover_result
    {'params': contents})
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 284, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 921, in handle_response
    handler(params)
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1224, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "/Users/LaVie/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 952, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)

```

## Versions

* Spyder version: 4.0.0.rc2
* Python version: 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS 10.11.6

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.8.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.0;<0.32.0        :  0.31.1 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by bcolsen** [comment] 2019-11-26 18:16
Thanks for the error report!

I'm closing this error as a duplicate of #10757, please see that report.

**Closed by bcolsen** 2019-11-26 18:16 UTC

**Comment by liuyigh** [comment] 2019-11-26 19:23
Thanks. Apparently I didn't do a thorough search. Sorry about it.
