### ISSUE TITLE
New Feature : Session Management

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1704] opened 2015-02-17 20:29 UTC
_From [phyo.arkarlwin](https://code.google.com/u/phyo.arkarlwin/) on 2014-01-23T12:55:50Z_

I am planning to add session management for Spyderlib.

It will have following features.
-Allow to save sessions without quitting
-A New view for session management (List of Sessions)
-Setting for path folder to keep session files.
-~/.spyder2/sessions for default folders.

Comments please.

PS: There is no issue tracking available in BitBucket?? Or this issue tracker is preferred?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1704_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 20:29
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-01-23T10:30:55Z_

Cool, thanks for the heads up. Just a couple of comments:

1. We already have the functionality to save and load sessions. See:

File > Load session...
File > Save session and quit...

2. Sessions should really be attached to projects because I think the two belong together. Please see how RStudio creates projects, which basically are sessions with a bit more metadata attached (Ideally we should also save and load the IPython and Python interpreters state and reload it when you switch projects).


Issues will remain here for the foreseeable future.

**Labels:** Cat-ProjectExplorer MS-v2.4

**Comment by spyder-issues-migrator** [comment] 2015-02-17 20:29
_From [phyo.arkarlwin](https://code.google.com/u/phyo.arkarlwin/) on 2014-01-24T12:11:20Z_

thanks carlos!

1.yes i use current session features a lot. but just want to save session without qutting and a session management like project manager would be cool.

2.before spyder i used kate alot for projects and i use kate sessions instead of project.
attaching session to project sounds cool we can have a .session folder inside each project associated.and reload it there.
one thing to consider is how about when we work on multiple projects? can't merge session with projects then.

3.good idea .how can we restore ipython state with coding errs?

**Comment by spyder-issues-migrator** [comment] 2015-02-17 20:29
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-01-25T06:05:35Z_

1. Yes, I really would like to see session management in Spyder too.

2. RStudio has a toolbar widget that lets you switch quite easily between projects http://www.rstudio.com/images/screenshots/rstudio-projects.png You can only have one project open at a time but that's fine because it'll avoid confusions. Take a look at plugins/workingdirectory.py to see how we build a toolbar widget.

3. We need to use dill for that https://github.com/uqfoundation/dill because

"Dill also provides the capability to: ... save and load python interpreter sessions".

**Comment by spyder-issues-migrator** [comment] 2015-02-17 20:29
_From [mas...@scaryhits.com](https://code.google.com/u/112246939082556816811/) on 2014-01-27T10:06:27Z_

WOW! Dill very nice! I am going to work on those features! Gonna love Dill!


Also i found others requested : https://code.google.com/p/spyderlib/issues/detail?id=1433 Should we merge?

**Comment by spyder-issues-migrator** [comment] 2015-02-17 20:29
_From [mas...@scaryhits.com](https://code.google.com/u/112246939082556816811/) on 2014-01-27T10:13:59Z_

2 . I see now , it list projects + session,

I don't know R as i am Python man :D never used R before , Scipy + Numpy + Scikit-learn are my tools  , and Spyder is my weapon.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 20:29
_From [cello...@gmail.com](https://code.google.com/u/102564725150183579541/) on 2015-01-04T09:26:32Z_

Dropping in a bit late -- any progress on this feature?  The main reason I want to be able to save w/o quitting is to have a "safety" mechanism to save all my workspace in case of a power failure, computer crash, etc.

**Comment by ccordoba12** [comment] 2015-07-13 05:02
This is related to Projects, so assigning @goanpeca to solve it :-)

**Comment by ccordoba12** [comment] 2016-08-29 01:22
This is really a duplicate of issue #1317.

**Closed by ccordoba12** 2016-08-29 01:22 UTC
Labels: 2–5 stars, Comp-Project-Explorer, Type-Enhancement
