### ISSUE TITLE
Error: Socket can't be open

### ISSUE THREAD

**Issue by bikong2** [spyder-ide/spyder#2441] opened 2015-05-18 10:27 UTC
## Description

When i star spyder, Problems occur. 

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> D:\Program Files (x86)\Anaconda\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anaconda\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\introspection.py", line 62, in run
    sock.bind( ("127.0.0.1", self.port) )
  File "D:\Program Files (x86)\Anaconda\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] 

Exception in thread Thread-5:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anaconda\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\introspection.py", line 62, in run
    sock.bind( ("127.0.0.1", self.port) )
  File "D:\Program Files (x86)\Anaconda\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] 
```

**Comment by ccordoba12** [comment] 2015-05-18 15:49
This problem is caused because we can't open a socket (i.e. an internal IP address) in your computer for communication between several Spyder components.

The cause could be your antivirus and/or firewall, which is too restrictive and doesn't let us do that operation.

Try to deactivate them for a while and start Spyder again to see if that fixes your problem.

**Comment by bikong2** [comment] 2015-05-20 15:25
Thks, i've fixed the problem.




Xihua Li
Baidu Corporation  
Baidu Campus, No. 10, Shangdi 10th, Haidian District, Beijing, China
TEL: 15810540336
Email: lixihua9@126.com
--------------------------------------------------------
北京市海淀区上地十街10号百度大厦
百度公司商务搜索部
李习华

From: Carlos Cordoba
Date: 2015-05-18 23:49
To: spyder-ide/spyder
CC: 李习华
Subject: Re: [spyder] Error: Socket can't be open (#2441)
This problem is caused because we can't open a socket (i.e. an internal IP address) in your computer for communication between several Spyder components.
The cause could be your antivirus and/or firewall, which is too restrictive and doesn't let us do that operation.
Try to deactivate them for a while and start Spyder again to see if that fixes your problem.

**Comment by Nodd** [comment] 2015-05-20 16:38
This issue pops from time to time. The exception should be catched and replaced by a friendly error dialog with some explanations on how to fix it.

**Comment by bikong2** [comment] 2015-05-21 02:14
Hi,

I start my spyder again, but it failed the same.
So i tried many times, sometimes it work but others not.

so what's the problem?

thks



Xihua Li
Baidu Corporation  
Baidu Campus, No. 10, Shangdi 10th, Haidian District, Beijing, China
TEL: 15810540336
Email: lixihua9@126.com
--------------------------------------------------------
北京市海淀区上地十街10号百度大厦
百度公司商务搜索部
李习华

From: Carlos Cordoba
Date: 2015-05-18 23:49
To: spyder-ide/spyder
CC: 李习华
Subject: Re: [spyder] Error: Socket can't be open (#2441)
This problem is caused because we can't open a socket (i.e. an internal IP address) in your computer for communication between several Spyder components.
The cause could be your antivirus and/or firewall, which is too restrictive and doesn't let us do that operation.
Try to deactivate them for a while and start Spyder again to see if that fixes your problem.

**Comment by ccordoba12** [comment] 2015-05-21 19:26
I think the problem is with your antivirus or firewall. Have you tried to run Spyder with the deactivated already?

**Comment by bikong2** [comment] 2015-05-22 01:44
hi, i turn off my antivirus and firewall, the same problem occurs.

so, is there any other ways to fixed the problem.

**Comment by bikong2** [comment] 2015-06-24 03:33
我解决了这个问题，方法如下：

解决步骤：
①在防火墙，杀毒软件当中添加程序白名单；
②更改：
D:\Program Files (x86)\Anaconda\Lib\site-packages\spyderlib\widgets\externalshell\introspection.py
文件中的62行为：
for loopCount in range(600, 0, -1):
            try:
                sock.bind( ("localhost", self.port) )
                break
            except OSError:
                if DEBUG:
                    logging.debug('Notification server: Bind on port %d failed...' % (self.port))
                if not loopCount:
                    raise
            import time
            time.sleep(1)
即可。
相当于让代码多次尝试连接端口。

**Comment by ccordoba12** [comment] 2017-04-26 16:07
Closing because this is a very old bug.

**Closed by ccordoba12** 2017-04-26 16:07 UTC
Labels: component:Python Console, OS:Windows, type:Bug
