### ISSUE TITLE
Dragging link object over Spyder window panes causes error (mishandled drag events)

### ISSUE THREAD

**Issue by e-d-n-a** [spyder-ide/spyder#5284] opened 2017-09-20 02:36 UTC
## Description

Dragging a link/url from browser to explorer in Win7, while passing over certain window panes in
Spyder causes error message (see below).
I already noticed this in Spyder version 3.1.4 (and Help/IPython panes), but there no error window appeared, but messages in the IPython console.

**What steps will reproduce the problem?**

1.  Using WinPython-32bit-3.6.1.0Qt5 in Win7
2.  Start Spyder IDE (version 3.2.3)
3.  Drag url in browser via icon in address bar or link in page (e.g. using Firefox) over Editor pane in Spyder (no drop required!)

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Program Files (x86)\WinPython\WinPython-32bit-3.6.1.0Qt5\python-3.6.1\lib\site-packages\spyder\widgets\editor.py", line 2206, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.8.0, PyQt5 5.8.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-20 03:17
Thanks for reporting. We'll take a look at this problem in a future release.

**Comment by ccordoba12** [comment] 2017-10-17 22:22
Closing as a duplicate of issue #5218.

**Closed by ccordoba12** 2017-10-17 22:22 UTC
Labels: component:Main Window, resolution:Duplicate, type:Bug
