### ISSUE TITLE
hanging display of picture extracted from gif

### ISSUE THREAD

**Issue by gbwust** [spyder-ide/spyder#12837] opened 2020-05-23 09:22 UTC
### What steps will reproduce the problem?

it seems cv2.destroyAllWindows() does not properly remove the picture. system hangs in debugging 
I have repeated the test several times and then I got this internal spyder problem after restarting the kernel.

### Traceback
```python-traceback
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\psutil\_pswindows.py", line 868, in send_signal
    cext.proc_kill(self.pid)
PermissionError: [WinError 5] Toegang geweigerd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 581, in _restart_thread_main
    stderr=self.stderr_handle)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\jupyter_client\manager.py", line 411, in restart_kernel
    self.shutdown_kernel(now=now, restart=True)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\jupyter_client\manager.py", line 377, in shutdown_kernel
    self.finish_shutdown()
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\jupyter_client\manager.py", line 338, in finish_shutdown
    self._kill_kernel()
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 86, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 59, in kill_proc_tree
    child_process.send_signal(sig)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\psutil\__init__.py", line 292, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\psutil\__init__.py", line 1214, in send_signal
    self._proc.send_signal(sig)
  File "C:\Users\G.B. Wust\anaconda3\envs\spyder_tests\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=16676)
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.7
* Qt version: 5.12.8
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.1.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by goanpeca** [comment] 2020-05-24 18:22
Hi @gbwust, thanks for the report.

It seems this issue is a duplicate of #12630. Will close in favor of that one. Please follow that issue for updates on it.

Cheers!

**Closed by goanpeca** 2020-05-24 18:22 UTC
