### ISSUE TITLE
Error message about Sphinx on first ctrl+I in 3.2.7

### ISSUE THREAD

**Issue by master-nemo** [spyder-ide/spyder#6578] opened 2018-03-02 11:59 UTC
I would not report this error, I remember that pip installation is not supported, but previous version of spyder haven't this problem, so maybe it just caused by new changes? maybe something related to #6570 ?

**What steps will reproduce the problem?**

on first (in session) calling "Inspect current object" (ctrl+I) the error message occured:
```
The following error occured when calling Sphinx 1.7.1.
Incompatible Sphinx version or decoding failed.
Error message: path is on drive J: start on drive F:
```

meanwhile `ctrl+I` (second calling don't lead to error message) will display help on current object as expected but IF subwindow `help` not displayed - it not automacicly shows up as it was in previous version.

_note1:_
drive F: is where all python and spyder installed and where working directory located.
drive J: nothing related python or spyder on it. just  `%TMP%` and `%TEMP%` is `J:\TMP`. 
_note2:_
Both  `pip install -U sphinx` and  `pip install -U spyder`
processed and report `Requirement already up-to-date` for all packages
I tried it from cloned spyder too. same result.

Here is debug log ( from `python bootstrap.py --debug` ) for 1s try (when displayed error message)
```
info request
info request from rope finished: "{'calltip': 'sum(sequence[, start])', 'note': 'Present in __builtin__ module', 'argspec': '(sequence" in 0.0 sec
No valid responses acquired
refresh_panels
```

for second (and others) when error message not displayed:
```
info request
info request from rope finished: "{'calltip': 'sum(sequence[, start])', 'note': 'Present in __builtin__ module', 'argspec': '(sequence" in 0.0 sec
No valid responses acquired
```

## Versions and main components
* Spyder Version: 3.2.7
* Python Version: 2.7.9 
* Operating system: windows 7 x86

## Dependencies
IPython >=4.0;<6.0:  5.5.0 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.1 (OK)
sympy >=0.7.3     :  1.0 (OK)

**Comment by ccordoba12** [comment] 2018-03-02 15:16
Thanks for reporting. This is a duplicate of issue #6549.

**Closed by ccordoba12** 2018-03-02 15:16 UTC
