### ISSUE TITLE
except while saving file with black enabled

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#17715] opened 2022-04-20 17:54 UTC
### What steps will reproduce the problem?

I think this is due to black - when I hit save I often get this exception when I have auto formatting with black on save enabled. This happens both when I just press save button, or use CTRL+ALT+I to auto format the file.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1926, in _save_file
    self.modification_changed(index=index)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2382, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1926, in _save_file
    self.modification_changed(index=index)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2382, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1926, in _save_file
    self.modification_changed(index=index)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2382, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1926, in _save_file
    self.modification_changed(index=index)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2382, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.8
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 7

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=2.5.0                :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=3.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment] 2022-04-20 18:29
Hi @rlabbe thank you for the feedback! I think this is a duplicate of https://github.com/spyder-ide/spyder/issues/14639 If that is the case, could you share with use an example code that triggers this in your end on that issue? I tried to replicate it locally but was unable to. Let us know!

**Comment by rlabbe** [comment] 2022-04-20 18:43
It seems variable - the file it was crashing on no longer causes a problem. I'll try to upload something if it happens again. I've poked into the spyder editor internals a bit before - if there is a way for me to help you debug this let me know. It does look like a duplicate. I can turn on "directly enter debugger when errors appear" and see if I can glean anything when the exception occurs the next time. 

It is perhaps worth noting I have a bit of an Frankenstein installation - I couldn't get anaconda to install the most recent version of spyder (5.1.5 in anaconda) because I am running an older version of anaconda for reasons not worth going into here. So I pip installed 5.3.0 because of numerous issues with the 4.x version that installation came with.  The dependencies all look okay, however.

**Comment by ccordoba12** [comment] 2022-04-20 19:00
Thanks @rlabbe for reporting this problem again! That gave me the motivation to see how to reproduce it and I finally did it.

This starts to happen as soon as you reorganize tabs in the editor. Since we're using the tab index to perform some operations after auto-formatting, and that index is borked with the tab movement, this error keeps showing up after that.

I'll post more details on issue #14639 so that @dalthviz can fix it.

**Closed by ccordoba12** 2022-04-20 19:00 UTC
Labels: status:Awaiting Followup

**Comment by ccordoba12** [comment] 2022-04-20 19:25
Correction: This happens when a formatting options is taking place and you close some tabs in the editor. See https://github.com/spyder-ide/spyder/issues/14639#issuecomment-1104370362.
