### ISSUE TITLE
LG

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#3004] opened 2016-02-25 01:42 UTC
I can not find the file "myapp.log" at current directory：

import logging
logging.basicConfig(level=logging.DEBUG,
                format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
                datefmt='%a, %d %b %Y %H:%M:%S',
                filename='myapp.log',
                filemode='w')
logging.debug('This is debug message')
logging.info('This is info message')
logging.warning('This is warning message')

**Comment by ccordoba12** [comment] 2016-02-25 16:43
I'm sorry but this not a Spyder bug or problem, but instead a problem with your code. So I'm closing this issue.

You could ask about coding problems in a website called StackOverflow.

**Closed by ccordoba12** 2016-02-25 16:43 UTC

**Comment by A-Pai** [comment] 2016-02-26 00:24
@ccordoba12 but I can find the file "myapp.log" if I use IDLE,so I think there is no error with my code

**Comment by Nodd** [comment] 2016-07-23 19:53
This is a duplicate of #2572, see there for more informations.
