### ISSUE TITLE
Codes not executing since updating to 5.5.1

### ISSUE THREAD

**Issue by cmusco618** [spyder-ide/spyder#21867] opened 2024-03-08 17:19 UTC
### What steps will reproduce the problem?

I upgraded to 5.5.1 and now none of my codes are working. I get the following when trying to executing: 

runfile('/Users/xxx/Documents/Analysis/vna_plot.py', wdir='/Users/xxx/Documents/Analysis')
Traceback (most recent call last):

  File /Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/Analysis/vna_plot.py:10
    import scipy

  File /Applications/Spyder.app/Contents/Resources/lib/python3.9/scipy/__init__.py:67
    from scipy._lib import _pep440

  File /Applications/Spyder.app/Contents/Resources/lib/python3.9/scipy/_lib/__init__.py:12
    from scipy._lib._testutils import PytestTester

  File /Applications/Spyder.app/Contents/Resources/lib/python3.9/scipy/_lib/_testutils.py:21
    _tags = list(sys_tags())

  File packaging/tags.pyc:543 in sys_tags

  File packaging/tags.pyc:212 in cpython_tags

  File packaging/tags.pyc:400 in mac_platforms

  File subprocess.pyc:528 in run

CalledProcessError: Command '['/Applications/Spyder.app/Contents/MacOS/python', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 1.

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/Applications/Spyder.app/Contents/MacOS/python'
  isolated = 0
  environment = 1
  user site = 0
  import site = 0
  sys._base_executable = '/Applications/Spyder.app/Contents/MacOS/python'
  sys.base_prefix = '/Users/runner/hostedtoolcache/Python/3.9.14/x64'
  sys.base_exec_prefix = '/Users/runner/hostedtoolcache/Python/3.9.14/x64'
  sys.platlibdir = 'lib'
  sys.executable = '/Applications/Spyder.app/Contents/MacOS/python'
  sys.prefix = '/Users/runner/hostedtoolcache/Python/3.9.14/x64'
  sys.exec_prefix = '/Users/runner/hostedtoolcache/Python/3.9.14/x64'
  sys.path = [
    '/Users/runner/hostedtoolcache/Python/3.9.14/x64/lib/python39.zip',
    '/Users/runner/hostedtoolcache/Python/3.9.14/x64/lib/python3.9',
    '/Users/runner/hostedtoolcache/Python/3.9.14/x64/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000001180af600 (most recent call first):
<no Python frame>

## Versions

* Spyder version: 5.5.1 237175ba9 (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.11
* PyQt5 version: 5.15.10
* Operating System: macOS-12.7.2-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.21.1 (OK)
keyring >=17.0.0                 :  24.3.0 (OK)
nbconvert >=4.0                  :  7.15.0 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.3 (OK)
pylint_venv >=3.0.2              :  None (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.3.0 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  69.0.3 (OK)
sphinx >=0.6.6                   :  5.1.1 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.6.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.0 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.8 (OK)
matplotlib >=3.0.0               :  3.8.2 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.0 (OK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment] 2024-03-12 00:29
Hey @cmusco618, thanks for reporting. Did you install Spyder with our Intel or M1 installer?

**Comment by cmusco618** [comment] 2024-03-12 01:38
Hi there, thanks for getting back to me about this issue. I uninstalled Spyder and installed Anaconda and it appears to be working without issue now. 

Thanks

___________________
Christopher Muscatello
General Atomics
Diagnostics Center of Excellence
G02-305
Office: 858-455-2256
Mobile: 440-823-8364

**Comment by ccordoba12** [comment] 2024-03-13 01:32
Ok, that's good news. Thanks for letting us know about it.

Since the problem is fixed now, I'm going to close this issue.

**Closed by ccordoba12** 2024-03-13 01:32 UTC
Labels: status:Awaiting Followup
