### ISSUE TITLE
Error clicking Preferences

### ISSUE THREAD

**Issue by ebassinNCH** [spyder-ide/spyder#5621] opened 2017-10-31 15:48 UTC
## Description

**What steps will reproduce the problem?**

1. Clicked the "Preferences" menu
2. 
3. 

**What is the expected output? What do you see instead?**
The window

**Please provide any additional information below**

  File "/usr/local/bin/Anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2609, in edit_preferences
    widget.initialize()
  File "/usr/local/bin/Anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 77, in initialize
    self.load_from_conf()
  File "/usr/local/bin/Anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 381, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-10-31 16:04
Thanks for reporting. This is a duplicate of issue #5578 and it'll be fixed in our 3.2.5 version.

In the meantime, you can run in a terminal

    spyder --reset

to fix this problem.

**Closed by ccordoba12** 2017-10-31 16:04 UTC
