### ISSUE TITLE
Case sensitive search icon "Aa" cannot be activated

### ISSUE THREAD

**Issue by mjherold** [spyder-ide/spyder#4516] opened 2017-05-26 17:49 UTC
## Description
If Search -> Replace Text is activated a window appears at the bottom to enter the text and its replacement. The "Aa" icon on the right for case sensitivity, the "[-]" and other icons are unresponsive.

Running spyder (3.1.4) under OS X (Sierra version 10.12.5).

**What steps will reproduce the problem?**

1. Open a file in Spyder, and select in menu bar Search -> Replace Text
2. Type in search tem, and try to activate case-sensitivity by clicking on "Aa" icon.
3. 

**What is the expected output? What do you see instead?**
Case sensitivity is not activated

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 2.7.13
* Qt Versions: 5.8.0, PyQt5 5.8.2 on Darwin

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment] 2017-05-26 21:14
Thanks for reporting. We'll take a look at this after we release 3.2

**Comment by goanpeca** [comment] 2019-11-27 19:20
Cannot reproduce this with master. Closing

**Closed by goanpeca** 2019-11-27 19:20 UTC
Labels: component:Editor, type:Bug
