### ISSUE TITLE
notebook error in arch-linux

### ISSUE THREAD

**Issue by f4try** [spyder-ide/spyder#14531] opened 2021-01-04 16:19 UTC
### What steps will reproduce the problem?

(process:16705): Gtk-WARNING **: 00:17:02.302: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 00:17:02.328: Failed to load module "colorreload-gtk-module"

open notebook and close notebook

### Traceback
```python-traceback
  File "/home/zz/anaconda3/envs/tf/lib/python3.8/site-packages/spyder_notebook/widgets/notebooktabwidget.py", line 214, in close_client
    client.shutdown_kernel()
  File "/home/zz/anaconda3/envs/tf/lib/python3.8/site-packages/spyder_notebook/widgets/client.py", line 312, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "/home/zz/anaconda3/envs/tf/lib/python3.8/site-packages/spyder_notebook/widgets/client.py", line 281, in get_kernel_id
    sessions_url = self.get_session_url()
  File "/home/zz/anaconda3/envs/tf/lib/python3.8/site-packages/spyder_notebook/widgets/client.py", line 272, in get_session_url
    return self.add_token(url_path_join(self.server_url, 'api/sessions'))
  File "/home/zz/anaconda3/envs/tf/lib/python3.8/site-packages/notebook/utils.py", line 50, in url_path_join
    initial = pieces[0].startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.9.13-arch1-1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.18.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.8.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.1 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  50.3.0.post20201006 (OK)
sphinx >=0.6.6                  :  3.4.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.1 (OK)
pandas >=1.1.1                  :  1.2.0 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

# Spyder plugins:
spyder_notebook                 :  0.3.1 (OK)
```

**Comment by steff456** [comment] 2021-01-04 17:22
Hi @f4try,

This is a duplicate of spyder-ide/spyder-notebook#314, please follow that thread to get the fix.

Thanks for reporting!

**Closed by steff456** 2021-01-04 17:22 UTC

**Comment by f4try** [comment] 2021-01-04 17:52
It helps a lot. Thank you, @steff456 .
