### ISSUE TITLE
Feature: Saved python interpreter path with Project

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#11676] opened 2020-02-28 04:55 UTC
In general, the Project should save all about Spyder IDE setup (even the shortcuts, open tabs...).
It would enable to have self-embedded projects.

We often navigate with different projects even on a single project.
Having to double on one shortctut to have the ENV ready for dev (without any manual setup),
is a MUST.

**Comment by cccsmoreno** [comment] 2020-02-28 14:08
This would be so very useful

**Comment by ccordoba12** [comment] 2020-02-28 15:06
Duplicate of #9804

**Closed by ccordoba12** 2020-02-28 15:06 UTC

**Comment by ccordoba12** [comment] 2020-02-28 15:09
> In general, the Project should save all about Spyder IDE setup (even the shortcuts, open tabs...).
It would enable to have self-embedded projects.

The infrastructure is already there to save all Spyder preferences per project. We just need to expose it in the user interface.

Unfortunately we didn't have time to add it for Spyder 4, but it's planned and it'll be definitely added for Spyder 5.

**Comment by physici** [comment] 2022-05-18 07:24
Has this feature been implemented already? I came across this kind of requirement as I started working with projects and project-dependent virtualenvs. It would be really cool if Spyder would switch the python-interpreter automatically according to the project settings.

**Comment by ccordoba12** [comment] 2022-05-18 13:19
No, it hasn't, sorry.
