### ISSUE TITLE
Problem printing

### ISSUE THREAD

**Issue by michaellohier** [spyder-ide/spyder#8667] opened 2019-01-29 18:00 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.7
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.16.0 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2019-02-01 08:42
Duplicate of #8582. We'll fix this in our next version.

**Closed by ccordoba12** 2019-02-01 08:42 UTC

**Comment by michaellohier** [comment] 2019-02-02 18:33
How can I do until then?

**Comment by ccordoba12** [comment] 2019-02-02 18:35
Just wait, there's no workaround for this, sorry. However, the new version (3.3.3) with this is going to be available in a couple of hours.
