### ISSUE TITLE
Make "Ask for confirmation before closing tabs" in IPython console work for all consoles

### ISSUE THREAD

**Issue by michaelklachko** [spyder-ide/spyder#2790] opened 2015-10-31 03:57 UTC
Feature request: Closing a tab in IPython console should ask for confirmation, or at least there should be an option in preferences to enable such a confirmation.

**Comment by ccordoba12** [comment] 2015-10-31 21:24
We offer a confirmation when you have more than one tab connected to the same kernel.

@michaelklachko, why do you think this is important?

**Comment by michaelklachko** [comment] 2015-10-31 21:53
This is important to me because when I run multiple simulations, I have several tabs open in IPython console, and these tabs accumulate lots of data (simulation results). More than once I accidentally clicked on X mark on the tab label, closing it - terminating simulation and losing all that data. 
Currently there's no confirmation when closing the tabs. I'm using Spyder 2.3.6 on Windows 8.1. 
Note that I have "Ask for confirmation before closing" checkbox enabled in Tools - Preferences - IPython Console, so perhaps this is a bug? 

Also, there's no confirmation when closing the entire Spyder application, but that's another issue.

**Comment by goanpeca** [comment] 2015-11-01 07:20
I guess asking spyder to confirm only makes sense if there is an ongoing process in a console, is this what you imply?

**Comment by michaelklachko** [comment] 2015-11-01 17:45
@goanpeca: no, it shouldn't matter if the code is still running or not, if that's what you mean by "ongoing process". The UI should try to prevent accidental loss of data (computation results shown in the console tabs).

I'm still not sure if this is a feature request or a bug report. What is the purpose of the checkbox in Tools - Preferences - IPython Console - "Ask for confirmation before closing"?

**Comment by goanpeca** [comment] 2015-11-01 17:46
Sure, we could add asking to confirm close as a global option.

Although I would personally disbale it as I would get annoyed with it after a couple of times

Not sure what the "Ask for confirmation..." does, @ccordoba12 ?

**Comment by goanpeca** [comment] 2015-11-01 17:47
@michaelklachko could you create an issue with that ?

**Ask for confirmation before closing spyder as a global option in preferences**?

**Comment by ccordoba12** [comment] 2015-11-03 16:05
There is no need to open a new issue. The option is already there, under the IPython Console preferences, as @michaelklachko pointed out.

The thing is (as I said above) that that option only works when you have more than one console connected to the same kernel. So it's not a bug, but we can change that behavior to ask for confirmation in all cases.

I think @michaelklachko has a good point and we should definitely do that for 3.0 :-)

**Closed** 2016-09-14 21:07 UTC
Labels: Comp-Console-IPython, Type-Enhancement
