### ISSUE TITLE
ipython error, Spyder (Version: 3.2.6  ) can not open ipython console

### ISSUE THREAD

**Issue by lfss007** [spyder-ide/spyder#6641] opened 2018-03-07 09:03 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\AILAB\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1068, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Users\AILAB\Anaconda3\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by csabella** [comment] 2018-03-07 11:45
Thanks for reporting. This is a duplicate of #6627 ; and in any case outside of Spyder's control. To fix for now, run ``conda install tornado=4.5.3`` from the Anaconda Prompt/Terminal/shell (Windows/Mac/Linux) in the ``conda`` environment that Spyder is installed in.

**Closed by csabella** 2018-03-07 11:45 UTC
