### ISSUE TITLE
Unsupported GUI

### ISSUE THREAD

**Issue by el-moh** [spyder-ide/spyder#15423] opened 2021-04-26 06:04 UTC
### What steps will reproduce the problem?

from pycaret.anomaly import *
s = setup(train, session_id = 123)

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 134, in comm_open
    self.log.error("No such comm target registered: %s", target_name)
Message: 'No such comm target registered: %s'
Arguments: ('jupyter.widget',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 134, in comm_open
    self.log.error("No such comm target registered: %s", target_name)
Message: 'No such comm target registered: %s'
Arguments: ('jupyter.widget',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 134, in comm_open
    self.log.error("No such comm target registered: %s", target_name)
Message: 'No such comm target registered: %s'
Arguments: ('jupyter.widget',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: '3e1cd5b4be8446b08c3088810493a454'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('3e1cd5b4be8446b08c3088810493a454',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: '3e1cd5b4be8446b08c3088810493a454'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('3e1cd5b4be8446b08c3088810493a454',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: '3e1cd5b4be8446b08c3088810493a454'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('3e1cd5b4be8446b08c3088810493a454',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 134, in comm_open
    self.log.error("No such comm target registered: %s", target_name)
Message: 'No such comm target registered: %s'
Arguments: ('jupyter.widget',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 134, in comm_open
    self.log.error("No such comm target registered: %s", target_name)
Message: 'No such comm target registered: %s'
Arguments: ('jupyter.widget',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 232, in <module>
    main()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "C:\Users\user\anaconda3\lib\site-packages\qtconsole\comms.py", line 134, in comm_open
    self.log.error("No such comm target registered: %s", target_name)
Message: 'No such comm target registered: %s'
Arguments: ('jupyter.widget',)
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.9
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.6 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.2.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.1 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.1.2 (OK)
scipy >=0.17.0                :  1.5.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment] 2021-04-26 17:24
Hey @el-moh, thanks for reporting. This is a duplicate of issue #15356 and we'll try to fix it in our next version, to be released at the end of the week.

**Closed by ccordoba12** 2021-04-26 17:24 UTC
