### ISSUE TITLE
Ipython console crashes when closing project that has application still running.

### ISSUE THREAD

**Issue by Rblivingstone** [spyder-ide/spyder#5413] opened 2017-10-06 21:22 UTC
## Description

**What steps will reproduce the problem?**

1. Open project containing flask application
2. Run flask application
3. While application is still running close the project

**What is the expected output? What do you see instead?**
I was expecting that spyder would close down the ipython console, and exit the project. Admittedly, this may be a PICNIC error, since I did not close my application, before trying to close the project, but I thought that everything would close down without an error. Got the error message below. 

**Please provide any additional information below**

  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 286, in close_project
    self.restart_consoles()
  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 386, in restart_consoles
    self.main.ipyconsole.restart()
  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1318, in restart
    self.close_client(client=client, force=True)
  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1236, in close_client
    client.stop_button_click_handler()
  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 235, in stop_button_click_handler
    self.interrupt_kernel()
  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 391, in interrupt_kernel
    self.shellwidget.request_interrupt_kernel()
  File "C:\Users\rbarnes\AppData\Local\Continuum\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 345, in request_interrupt_kernel
    self.interrupt_kernel()
  File "C:\Users\rbarnes\App

**Comment by ccordoba12** [comment] 2017-10-07 17:47
Thanks for reporting. We'll take a look at this in a future release.

**Comment by rlaverde** [comment] 2017-10-09 15:10
The console should be stopped  before closing the project?

**Comment by ccordoba12** [comment] 2017-10-09 16:33
It's stopped already.

**Comment by ccordoba12** [comment] 2018-05-09 01:03
I think this is a duplicate of issue #5568 and it's already fixed.

**Closed by ccordoba12** 2018-05-09 01:03 UTC
Labels: component:IPython Console, type:Bug
