### ISSUE TITLE
Ipython console continues line on return

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#2923] opened 2016-01-12 15:52 UTC
After running a script a few times the IPython console no longer accepts a return. I get behavior like

    In [1]: 1<CR>
        ...:           <- this shouldn't happen!!

No matter what I type in, when I hit return it continues the line rather than detecting that the expression can be accepted and executing it. Restarting the kernel with CTRL+. does not fix the problem. If I start a new IPython console the problem does not occur in the new console, but continues to occur in the old one.

This has happened to me on multiple machines. I'm variously on either spyder 2.3.7 or Spyder 2.3.8, all on Windows (7 and 10) using the Anaconda 64 bit distribution (Anaconda 2.4.1, Python 3.5.1)

This may have nothing to do with Spyder, but I never get this behavior when running IPython from the command prompt.

**Comment by ccordoba12** [comment] 2016-01-12 16:39
This is a duplicate of issue #2696. Closing because of that.

**Closed by ccordoba12** 2016-01-12 16:39 UTC
Labels: Duplicate

**Comment by ekipmanager** [comment] 2016-01-20 22:17
@ccordoba12 I have the same issue when I run ipython qtconsole from command line instead of just ipython . Difference from #2696 is that this does not happen normally. The only time I get to this weird mode is when I am playing with a dataframe in pandas and I use tab completion on some of its index functions (e.g. `df.index.get_lev<tab>`) then tab completion stops working and hitting enter will generate a new line. It happens on both mac and linux and with both anaconda 3.19
0 and python 2.7.
By the way, I am not using spyder so as you mentioned in #2696 it might be jupyter-qtconsole issue.

**Comment by ccordoba12** [comment] 2016-01-21 17:59
@ekipmanager, please report your problem here:

https://github.com/jupyter/qtconsole
