### ISSUE TITLE
Exception in thread Thread-20: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Freion** [spyder-ide/spyder#18965] opened 2022-08-06 18:52 UTC
Exception in thread Thread-20: 
Traceback (most recent call last): 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\threading.py", line 917, in _bootstrap_inner 
self.run() 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\site-packages\jupyter_client\threaded.py", line 218, in run 
self.ioloop.start() 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\site-packages\tornado\platform\asyncio.py", line 199, in start 
self.asyncio_loop.run_forever() 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\site-packages\nest_asyncio.py", line 72, in run_forever 
self._run_once() 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\site-packages\nest_asyncio.py", line 106, in _run_once 
event_list = self._selector.select(timeout) 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\selectors.py", line 323, in select 
r, w, _ = self._select(self. _readers, self. _writers, [], timeout) 
File "E:\work\python\anaconda\conda3\envs\py3.7\lib\selectors.py", line 314, in _select 
r, w, x = select. select(r, w, w, timeout) 
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2022-08-08 15:10
Hey @Freion, thanks for reporting. This looks like a duplicate of issue #18974, so I'm going to close it in favor of that one because it has more info.

Please follow that issue by leaving a comment on it to see how the problem is solved.

**Closed by ccordoba12** 2022-08-08 15:10 UTC

**Comment by psmartboy** [comment] 2025-04-04 15:22
File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(**check_kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\base.py", line 492, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\checks\registry.py", line 89, in run_checks       
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\checks\urls.py", line 44, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\checks\urls.py", line 63, in _load_all_namespaces 
    url_patterns = getattr(resolver, "url_patterns", [])
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module        
    return import_module(self.urlconf_name)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\psmar\myworld\my_tennis_club\my_tennis_club\urls.py", line 21, in <module>
    path('',include('members.urls')),
            ~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\psmar\myworld\my_tennis_club\members\urls.py", line 2, in <module>
    from.import views
  File "C:\Users\psmar\myworld\my_tennis_club\members\views.py", line 3, in <module>
    from django.http import httpresponse
ImportError: cannot import name 'httpresponse' from 'django.http' (C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\http\__init__.py)

**Comment by psmartboy** [comment] 2025-04-04 15:23
File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(**check_kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\base.py", line 492, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\checks\registry.py", line 89, in run_checks       
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\checks\urls.py", line 44, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\checks\urls.py", line 63, in _load_all_namespaces 
    url_patterns = getattr(resolver, "url_patterns", [])
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module        
    return import_module(self.urlconf_name)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\psmar\myworld\my_tennis_club\my_tennis_club\urls.py", line 21, in <module>
    path('',include('members.urls')),
            ~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\psmar\myworld\my_tennis_club\members\urls.py", line 2, in <module>
    from.import views
  File "C:\Users\psmar\myworld\my_tennis_club\members\views.py", line 3, in <module>
    from django.http import httpresponse
ImportError: cannot import name 'httpresponse' from 'django.http' (C:\Users\psmar\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\http\__init__.py)

**Comment by ccordoba12** [comment] 2025-04-04 15:43
@psmartboy, that seems an erro with Django, not with Spyder. So, we can't help you with it, sorry.
