### ISSUE TITLE
Code auto completion doesn't work

### ISSUE THREAD

**Issue by peiyaoli** [spyder-ide/spyder#6205] opened 2018-01-14 07:29 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Type "import pandas as pd"
2.  Run this block
3. Type pd.

**What is the expected output? What do you see instead?**
I pressed "Tab" or "Ctrl + Space", no auto completion pops pup 

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.3
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system: Win10 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment] 2018-01-14 08:59
Thanks for reporting. This is a duplicate of #5782 , so please see that issue for more help; the most common solution was removing the ``enum34`` package if you have it. Therefore, this one will be closed.

**Closed by CAM-Gerlach** 2018-01-14 08:59 UTC
