### ISSUE TITLE
Spyder randomly crashes

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#11425] opened 2020-01-29 15:23 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

My spyder randomly freezes and doesn't recover from it. Unfortunately this error is extremely random, therefore difficult to reproduce.

I'm mainly posting this issue to ask if there is any way to get what is going on in spyder before the crash? some kind of error log? If not you can close this issue right away

Win10, Spyder 4.0.1, conda all up to date.

**Comment by ccordoba12** [comment] 2020-01-29 16:22
This looks like a duplicate of #11222, which is already fixed and it'll be part of our next release. If you encounter the same problem after 4.1.0 is released, please open a new issue.

**Closed by ccordoba12** 2020-01-29 16:22 UTC
