### ISSUE TITLE
when I edit python code in spyder It shows err

### ISSUE THREAD

**Issue by youzhibo** [spyder-ide/spyder#6239] opened 2018-01-18 03:51 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "c:\users\heting\appdata\local\programs\python\python35\lib\site-packages\pygments\lexers\__init__.py", line 168, in fi

**Comment by CAM-Gerlach** [comment] 2018-01-18 06:22
Thanks for reporting. The error traceback that was posted is incomplete, so the problem cannot be conclusively diagnosed; however, if you read the end of the traceback, it likely tells you exactly what to do to fix it. Most likely it probably either a duplicate of e.g. #5673 , an error that's been reported numerous times now which means you need to update ``jedi``, or your ``setuptools`` needing to be updated, or something else wrong with your manual ``pip``  installation, which is for experts only and for which we don't have the resources to provide individual support. Therefore, this issue will be closed. Best of luck.

**Closed by CAM-Gerlach** 2018-01-18 06:22 UTC
