### ISSUE TITLE
Error when connecting to external kernels

### ISSUE THREAD

**Issue by tnxgalaxy** [spyder-ide/spyder#7084] opened 2018-05-07 19:06 UTC
I tried to connect to a remote ipython kernel using a local json file and got this message

This error seems to be similar to this one:
https://github.com/spyder-ide/spyder-notebook/issues/145

also note that the workaround also works, that is downgrading these two components:
pip install tornado==4.5.3
pip install jupyter_client==5.2.2

error displayed:
  File "/opt/anaconda3/envs/spyder/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1060, in create_client_for_kernel
    password)
  File "/opt/anaconda3/envs/spyder/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1782, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "/opt/anaconda3/envs/spyder/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 57, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'

workaround commands output (also shows original versions that include the bug):
(spyder) tnx@ibootis-mint ~/Desktop/computing/config/anaconda $ pip install tornado==4.5.3
Collecting tornado==4.5.3
  Downloading https://files.pythonhosted.org/packages/e3/7b/e29ab3d51c8df66922fea216e2bddfcb6430fb29620e5165b16a216e0d3c/tornado-4.5.3.tar.gz (484kB)
    100% |████████████████████████████████| 491kB 933kB/s 
Building wheels for collected packages: tornado
  Running setup.py bdist_wheel for tornado ... done
  Stored in directory: /home/tnx/.cache/pip/wheels/72/bf/f4/b68fa69596986881b397b18ff2b9af5f8181233aadcc9f76fd
Successfully built tornado
Installing collected packages: tornado
  Found existing installation: tornado 5.0.2
    Uninstalling tornado-5.0.2:
      Successfully uninstalled tornado-5.0.2
Successfully installed tornado-4.5.3
(spyder) tnx@ibootis-mint ~/Desktop/computing/config/anaconda $ pip install jupyter_client==5.2.2
Collecting jupyter_client==5.2.2
  Downloading https://files.pythonhosted.org/packages/42/8a/5cca4d98fe28c4db6c2879b69ca5d106e0f4415aafda8bc4074deddbc3da/jupyter_client-5.2.2-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
Requirement already satisfied: jupyter-core in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from jupyter_client==5.2.2) (4.4.0)
Requirement already satisfied: tornado>=4.1 in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from jupyter_client==5.2.2) (4.5.3)
Requirement already satisfied: pyzmq>=13 in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from jupyter_client==5.2.2) (17.0.0)
Requirement already satisfied: python-dateutil>=2.1 in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from jupyter_client==5.2.2) (2.7.2)
Requirement already satisfied: traitlets in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from jupyter_client==5.2.2) (4.3.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from python-dateutil>=2.1->jupyter_client==5.2.2) (1.11.0)
Requirement already satisfied: ipython_genutils in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from traitlets->jupyter_client==5.2.2) (0.2.0)
Requirement already satisfied: decorator in /opt/anaconda3/envs/spyder/lib/python3.6/site-packages (from traitlets->jupyter_client==5.2.2) (4.3.0)
Installing collected packages: jupyter-client
  Found existing installation: jupyter-client 5.2.3
    Uninstalling jupyter-client-5.2.3:
      Successfully uninstalled jupyter-client-5.2.3
Successfully installed jupyter-client-5.2.2

**Comment by ccordoba12** [comment] 2018-05-07 21:27
Thanks for reporting. We'll notify this error to the Jupyter guys so they can fix it.

**Comment by ccordoba12** [comment] 2018-05-07 21:34
Closing as a duplicate of #7082.

**Closed by ccordoba12** 2018-05-07 21:34 UTC
Labels: component:IPython Console, type:Bug
