### ISSUE TITLE
Delete all variables in Variable explorer

### ISSUE THREAD

**Issue by jk-1** [spyder-ide/spyder#11748] opened 2020-03-08 12:05 UTC
### What steps will reproduce the problem?

1. You have several variables in Variable Explorer (VE)
2. You select them all by selecting the first and then rest by keeping mouse button down and dragging downwards until all are selected.
3. From popup menu select command Remove
4. This will remove only one (Error!).
5. Redo step 2.
6. Redo step 3.
7. This will remove all remaining and the Issue Reporter window will show up.

### Traceback
```python-traceback
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'y'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'X_train'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'X_test'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'y_train'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'y_test'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'sc'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'classifier'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'y_pred'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'cm'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'X_set'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'y_set'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'X1'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'X2'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'i'
Exception in comms call remove_value:
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "/home/jk/.local/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'j'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.6.9
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-88-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  10.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.4.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.0 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
sphinx >=0.6.6               :  2.4.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-03-08 13:05
Duplicate of #11001

**Comment by ccordoba12** [comment] 2020-03-08 13:06
It'll be fixed in our next version.

**Closed by ccordoba12** 2020-03-08 13:05 UTC
