### ISSUE TITLE
spyder broken with IPython 4

### ISSUE THREAD

**Issue by flying-sheep** [spyder-ide/spyder#2622] opened 2015-08-17 14:05 UTC
I get

>  ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.

and then consequently:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 3103, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 2989, in run_spyder
    main.setup()
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 830, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/inspector.py", line 43, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 29, in <module>
    from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named 'IPython.qt.console.rich_ipython_widget'
```

/edit: ah, the arch packages just didn’t include qtconsole up until now.

it works, but we should still heed the deprecation warning and try importing from `qtconsole` first.

**Comment by goanpeca** [comment] 2015-08-17 15:02
Spyder will move to the new convention in the upcoming release, and there might be also a minor release to handle this imports coming soon...

**Comment by ccordoba12** [comment] 2015-08-17 17:58
Closing as duplicate of issue #2608 (which is already solved for the stable branch).

`qtconsole` will be added as a hard dependency for 3.0 beta2. This problem is also solved in the latest master (i.e. Spyder doesn't crash if it can find `qtconsole`).

**Closed** 2015-08-17 17:59 UTC
Labels: duplicate

**Comment by flying-sheep** [comment] 2015-08-17 19:55
great, thank you!
