### ISSUE TITLE
Spyder crashes whenever i try to save a new File

### ISSUE THREAD

**Issue by tsnisanth2015** [spyder-ide/spyder#5344] opened 2017-09-27 15:46 UTC
## Description of your problem
Spyder crashes whenever i try to save a new file in anaconda. The only file i am able to use and save is the default temp.py file which is there already when i open spyder.
Anaconda navigator : 1.6.2
Spyder : 3.2.3
The error message says:
"Python stopped working"
"A problem caused the program to stop working correctly.Windows will close the program and notify you if a solution is available"

Can some one guide me on this issue. What steps need to be taken to resolve this issue?

**What steps will reproduce the problem?**
1. Open Anaconda
2. Open Spyder, click on new file
3. Try saving the new file and this error will pop up.

**What is the expected output? What do you see instead?**
The expected output is to see the new file getting saved in the location specified. Instead the spyder application crashes after the following error message.

"Python stopped working"
"A problem caused the program to stop working correctly.Windows will close the program and notify you if a solution is available"

**Please provide any additional information below**
I have the latest update installed on spyder and i have the latest version of anaconda too.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 2.7
* Qt Version: 4.3.0
* PyQt Version: 4.3.0
[Spyder_Issue.docx](https://github.com/spyder-ide/spyder/files/1337807/Spyder_Issue.docx)

* Operating system: Windows 8.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-09-28 15:05
Thanks for reporting. This looks like a duplicate of issue #3903.

Please read that issue to see how to fix this problem.

**Closed by ccordoba12** 2017-09-28 15:05 UTC

**Comment by JamieMBright** [comment] 2023-01-04 15:59
Wouldn't mind reopening this. Just had this issue.

Seems to only affect saving .py files. I do have autopep8 linting which usually activates on save of a .py file.

An older environment of mine works fine.

Broken env:
```
     active environment : datapipelines
    active env location : C:\Users\brigh1j\.conda\envs\datapipelines
            shell level : 2
       user config file : C:\Users\brigh1j\.condarc
 populated config files : C:\Users\brigh1j\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda  (read only)
      conda av data dir : C:\ProgramData\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda\pkgs
                          C:\Users\brigh1j\.conda\pkgs
                          C:\Users\brigh1j\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\brigh1j\.conda\envs
                          C:\ProgramData\Anaconda\envs
                          C:\Users\brigh1j\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
           
           

(datapipelines) C:\Users\brigh1j\ukpn-dso\dso-metrics>conda list spyder
# packages in environment at C:\Users\brigh1j\.conda\envs\datapipelines:
#
# Name                    Version                   Build  Channel
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
spyder                    5.4.1            py39hcbf5309_1    conda-forge
spyder-kernels            2.4.1           win_pyhd8ed1ab_0    conda-forge

(datapipelines) C:\Users\brigh1j\ukpn-dso\dso-metrics>conda list pyQ
# packages in environment at C:\Users\brigh1j\.conda\envs\datapipelines:
#
# Name                    Version                   Build  Channel
pyqt                      5.15.7           py39hb77abff_2    conda-forge
pyqt5-sip                 12.11.0          py39h99910a6_2    conda-forge
pyqtwebengine             5.15.7           py39hb77abff_2    conda-forge

```

And the working env:

```conda info

     active environment : opfor20221223
    active env location : C:\Users\brigh1j\.conda\envs\opfor20221223
            shell level : 2
       user config file : C:\Users\brigh1j\.condarc
 populated config files : C:\Users\brigh1j\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda  (read only)
      conda av data dir : C:\ProgramData\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda\pkgs
                          C:\Users\brigh1j\.conda\pkgs
                          C:\Users\brigh1j\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\brigh1j\.conda\envs
                          C:\ProgramData\Anaconda\envs
                          C:\Users\brigh1j\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False

(opfor20221223) C:\Users\brigh1j\ukpn-dso\dso-metrics>conda list spyder
# packages in environment at C:\Users\brigh1j\.conda\envs\opfor20221223:
#
# Name                    Version                   Build  Channel
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
spyder                    5.4.0            py39hcbf5309_0    conda-forge
spyder-kernels            2.4.0           win_pyhd8ed1ab_1    conda-forge

(opfor20221223) C:\Users\brigh1j\ukpn-dso\dso-metrics>conda list pyq
# packages in environment at C:\Users\brigh1j\.conda\envs\opfor20221223:
#
# Name                    Version                   Build  Channel
pyqt                      5.15.7           py39hb77abff_2    conda-forge
pyqt5-sip                 12.11.0          py39h99910a6_2    conda-forge
pyqtwebengine             5.15.7           py39hb77abff_2    conda-forge
```


My company has pretty strict build controls, so the conda version etc has never changed. The only difference is from spyder and spyder-kernels from  *.4.0 to *.4.1. 

Downgrading these versions down to 5.4.0 and 2.4.0 fixed the issue for me.

**Comment by ccordoba12** [comment] 2023-01-04 16:10
@JamieMBright, we're tracking this new problem on issue #20282. Please follow my instructions in https://github.com/spyder-ide/spyder/issues/20282#issuecomment-1369023685 to see if we're able to understand the cause of it.
