### ISSUE TITLE
Error while checking pandas dataframe/series

### ISSUE THREAD

**Issue by Msantanche** [spyder-ide/spyder#15999] opened 2021-07-09 14:28 UTC
### What steps will reproduce the problem?

Produced a dataframe (in several different trials of code). If I select the object in my editor and run the selected object to see in console how it looks like, Spyder freezes (this happens randomly at some point, not necessarily at the first attempt).

May this be related to the fact that I don't see the Spyder icon (suggesting that my Spyder installation is buggy)? I have tried to uninstall and reinstall anaconda, and also updating Spyder. I also tried to install Spyder with miniconda. Nothing worked.

**Comment by ccordoba12** [comment] 2021-07-12 01:59
Hey @Msantanche, thanks for reporting. Please try to use our Windows or Mac installers to see if the problem is solved for you. You can find them here:

https://github.com/spyder-ide/spyder/releases

**Comment by Msantanche** [comment] 2021-07-15 08:47
Hi,

Now is worse: I get a prompt window at the beginning "missing dependencies"
(parso, jedi) even after installing them. Additionally, I got an error
which prevents kernel to start "no qt platform plugin could be initialized"

Marco Santanché

**Comment by ccordoba12** [comment] 2021-07-19 01:34
Are you using our installers? Or how did you install Spyder?

**Comment by Msantanche** [comment] 2021-07-19 06:19
I tried using Anaconda and installing Spyder. Then I tried updating Spyder through anaconda, given the issues I was experiencing. Then I tried your installers without anaconda, and it was not working. I have tried uninstalling everything and reinstalling through anaconda, and for the moment it works. I am just missing the icon of Spyder when I open it, I hope I won't see the crashing problem again. Main issue: with Spyder without anaconda, I couldn't install some packages with Python version 3.9 (e.g. Scikit-learn). So I cannot update Spyder to the very latest version I think.Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Carlos Cordoba ***@***.***>Datum: Mo., 19. Juli 2021, 03:35An: spyder-ide/spyder ***@***.***>Cc: Marco Santanché ***@***.***>, Mention ***@***.***>Betreff: Re: [spyder-ide/spyder] Error while checking pandas dataframe/series (#15999)
Are you using our installers? Or how did you install Spyder?

**Comment by ccordoba12** [comment] 2021-07-20 07:05
Glad to know it's working fine for you now. Therefore, I'm closing this one.

**Closed by ccordoba12** 2021-07-20 07:05 UTC
Labels: status:Awaiting Followup
