### ISSUE TITLE
Blaze support

### ISSUE THREAD

**Issue by scls19fr** [spyder-ide/spyder#2580] opened 2015-08-02 14:57 UTC
Hello,

it will be nice if variables explorer could support Blaze `blaze.interactive.InteractiveSymbol`

    import blaze as bz
    table_uri = 'dialect+driver://user:password@host:port/databasename::tablename'
    dat = bz.Data(table_uri)

http://blaze.pydata.org
http://blaze.pydata.org/en/latest/rosetta-pandas.html
http://blaze.pydata.org/en/latest/uri.html

with such a feature it will become possible to display inside variables explorer content of :
 
 - CSV files
 - database tables supported by SQLAlchemy (even very long tables !!!)

such feature is now available in gtabview https://github.com/wavexx/gtabview
see https://github.com/wavexx/gtabview/blob/master/gtabview/models.py ExtBlazeModel

Kind regards

PS: contrary to Pandas

    import pandas as pd
    from sqlalchemy import create_engine
    db_uri = 'dialect+driver://user:password@host:port/databasename'
    engine = create_engine(db_uri)
    df = pd.read_sql("tablename", engine)

Blaze doesn't need to fetch the whole table into memory... and so that's very quick.

**Comment by goanpeca** [comment] 2015-08-02 15:40
Cool :-), @ccordoba12 I already have some work in the QTableQuick widget to handle the numpy and pandas cases (of not loading the whole array), and it seems to work fine :-),  (beta 4 most likely)

**Comment by ccordoba12** [comment] 2015-08-02 15:42
Cool! But beta 4? Remember that we're going to have three betas for new features, and that release candidate is meant for bug fixes only.

**Comment by goanpeca** [comment] 2015-08-02 15:52
Oops, beta 3 I meant then....

**Comment by ccordoba12** [comment] 2015-08-02 16:04
I'm going to mark this one as duplicate of issue #2553, to consolidate everything in one place.

**Closed by ccordoba12** 2015-08-02 16:04 UTC
Labels: duplicate

**Comment by ccordoba12** [comment] 2015-08-02 16:06
@scls19fr, please don't open more issues about things supported by `gtabview` that we don't support.

Instead of that, we should try to see how to use `gtabview` as a library.

**Comment by scls19fr** [comment] 2015-08-02 16:11
Glad to know. Thank you in advance for your help!
