### ISSUE TITLE
AttributeError: Nonetype has no attribute "clear" when right clicking in the empty project explorer with no project open

### ISSUE THREAD

**Issue by dc-avasilev** [spyder-ide/spyder#6975] opened 2018-04-17 13:06 UTC
```python-traceback
File "/usr/local/anaconda3/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 480, in contextMenuEvent
    self.update_menu()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 458, in update_menu
    self.menu.clear()
AttributeError: 'NoneType' object has no attribute 'clear'
```
--------
click right button on mouse in cleared project manager window

**Comment by CAM-Gerlach** [comment] 2018-04-17 15:53
Yup, was able to reproduce. Specifically, the window was "cleared" by closing the current project, then reopening it from the menu. @ccordoba12 , do we want to just catch the error and pass (or otherwise better handle it), or go further and disable opening the project explorer when no project is open, since it serves no real purpose?

**Comment by CAM-Gerlach** [comment] 2018-04-17 15:57
Also, I get a series of followup errors:

```python-traceback
  File "C:\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 420, in eventFilter
    event.button() == QtCore.Qt.MidButton and \
AttributeError: 'QContextMenuEvent' object has no attribute 'button'
```

**Comment by ccordoba12** [comment] 2018-04-17 21:25
> do we want to just catch the error and pass

Yep, I think it's the easiest thing to do.

> or go further and disable opening the project explorer when no project is open, since it serves no real purpose?

There's no harm in showing the project explorer empty.

> Also, I get a series of followup errors

This is odd. I don't know why those errors are generated.

**Comment by CAM-Gerlach** [comment] 2018-04-18 00:37
Okay, cool. I'll get to it Soon™

**Comment by ccordoba12** [comment] 2018-05-19 18:59
@dalthviz, please work on this one by catching `AttributeError` in the right places.

**Closed** 2018-05-21 20:17 UTC
Labels: component:Projects, status:Reproduced, type:Bug
