### ISSUE TITLE
Changing font on arch causes crash

### ISSUE THREAD

**Issue by Qrashi** [spyder-ide/spyder#20946] opened 2023-05-19 17:57 UTC
### What steps will reproduce the problem?

I installed spyder using pacman from the official repositories. (5.4.2-1) After changing my theme using "alias spyder='QT_STYLE_OVERRIDE=Fusion spyder'" due to spyder immediately freezing after starting I changed the font to "Source Code Pro" resulting in this crash and the crash dialogue.

This issue is not that important due but due to the window prompting me to report the error i thought that it might help in finding a weird edge-case.

Thanks

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/spyder/plugins/application/container.py", line 331, in _check_updates_ready
    msg = header + content + footer
UnboundLocalError: local variable 'content' referenced before assignment
```

## Versions

* Spyder version: 5.4.2  (pip)
* Python version: 3.10.10 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Linux 6.2.13-1-MANJARO

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1              :  8.12.0 (OK)
jedi >=0.17.2                 :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.1 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.11.0 (OK)
nbconvert >=4.0               :  7.3.1 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0                 :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.17.3 (OK)
pylint_venv >=2.1.1           :  3.0.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.2 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2            :  3.1 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.4.0             :  5.4.2 (OK)
qtpy >=2.1.0                  :  2.3.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.6.1 (OK)
sphinx >=0.6.6                :  6.2.1 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.3 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.3.0 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  25.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.34 (OK)
matplotlib >=3.0.0            :  3.7.1 (OK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                         Version
------------------------------- ------------------------------------
abydos                          0.5.0
alabaster                       0.7.13
anyascii                        0.3.2
anyio                           3.6.2
anytree                         2.8.0
apparmor                        3.1.3
appdirs                         1.4.4
application-utility             1.3.2
argon2-cffi                     21.3.0
argon2-cffi-bindings            21.2.0
arrow                           1.2.3
asciidoc                        10.2.0
astroid                         2.15.4
asttokens                       2.2.1
async-generator                 1.10
atomicwrites                    1.4.1
attrs                           22.2.0
autocommand                     2.2.2
autopep8                        2.0.2
Babel                           2.11.0
backcall                        0.2.0
bcrypt                          4.0.1
beautifulsoup4                  4.11.2
binaryornot                     0.4.4
black                           23.3.0
bleach                          6.0.0
btrfsutil                       6.2.2
cachetools                      5.3.0
certifi                         2022.12.7
cffi                            1.15.1
chardet                         5.1.0
click                           8.1.3
cloudpickle                     2.2.1
colorama                        0.4.6
comm                            0.1.3
configobj                       5.1.0.dev0
construct                       2.10.68
contourpy                       1.0.7
cookiecutter                    2.1.1
cryptography                    40.0.1
cssselect                       1.2.0
cssselect2                      0.7.0
cycler                          0.11.0
Cython                          0.29.34
debugpy                         1.6.7
decorator                       5.1.1
defusedxml                      0.7.1
deprecation                     2.1.0
diff-match-patch                20200713
dill                            0.3.6
distlib                         0.3.6
docopt                          0.6.2
docstring-to-markdown           0.12
docutils                        0.19
duplicity                       1.2.2
entrypoints                     0.4
ewmh                            0.1.6
exceptiongroup                  1.1.1
executing                       1.2.0
fasteners                       0.18
fastjsonschema                  2.16.3
filelock                        3.12.0
flake8                          6.0.0
fonttools                       4.39.3
future                          0.18.2
gmpy2                           2.1.5
google-api-core                 2.11.0
google-api-python-client        2.83.0
google-auth                     2.16.2
google-auth-httplib2            0.1.0
googleapis-common-protos        1.59.0
gufw                            22.4.0
helpdev                         0.7.1
httplib2                        0.22.0
idna                            3.4
imagesize                       1.4.1
importlib-metadata              5.0.0
inflect                         6.0.4
inflection                      0.5.1
iniconfig                       2.0.0
intervaltree                    3.1.0
ipykernel                       6.22.0
ipython                         8.12.0
ipython-genutils                0.2.0
isort                           5.12.0
jaraco.classes                  3.2.3
jaraco.context                  4.3.0
jaraco.functools                3.6.0
jaraco.text                     3.11.1
jarowinkler                     1.2.3
jedi                            0.18.2
jeepney                         0.8.0
jellyfish                       0.9.1
Jinja2                          3.1.2
jinja2-time                     0.2.0
json5                           0.9.13
jsonschema                      4.17.3
jupyter_client                  8.2.0
jupyter_core                    5.3.0
jupyter-events                  0.6.3
jupyter_packaging               0.12.3
jupyter_server                  2.5.0
jupyterlab                      3.6.3
jupyterlab-pygments             0.2.2
jupyterlab_server               2.22.1
keyring                         23.11.0
kiwisolver                      1.4.4
layoutswitcherlib               0.8.35
lazy-object-proxy               1.9.0
Levenshtein                     0.20.9
LibAppArmor                     3.1.3
libvirt-python                  9.2.0
lit                             15.0.7.dev0
lxml                            4.9.2
Mako                            1.2.4
mallard-ducktype                1.0.2
manjaro-sdk                     0.1
Markdown                        3.4.3
markdown-it-py                  2.2.0
MarkupSafe                      2.1.2
material-color-utilities-python 0.1.5
matplotlib                      3.7.1
matplotlib-inline               0.1.6
mccabe                          0.7.0
mdurl                           0.1.2
minimal                         0.1.0
mistune                         2.0.5
more-itertools                  9.1.0
mpmath                          1.3.0
mypy-extensions                 1.0.0
nbclient                        0.7.4
nbconvert                       7.3.1
nbformat                        5.8.0
nest-asyncio                    1.5.6
netsnmp-python                  1.0a1
nftables                        0.1
notebook_shim                   0.2.3
npyscreen                       4.10.5
numpy                           1.24.2
numpydoc                        1.5.0
oauth2client                    4.1.3
ordered-set                     4.1.0
packaging                       23.0
pacman-mirrors                  4.23.2
pandas                          1.5.3
pandocfilters                   1.5.0
paramiko                        2.11.1
parso                           0.8.3
pathspec                        0.11.1
pexpect                         4.8.0
pickleshare                     0.7.5
Pillow                          9.4.0
pip                             23.0.1
platformdirs                    3.2.0
pluggy                          1.0.0
ply                             3.11
pooch                           1.7.0
prometheus-client               0.16.0
prompt-toolkit                  3.0.38
protobuf                        4.21.12
psutil                          5.9.4
ptyprocess                      0.7.0
pulsectl                        22.3.2
pure-eval                       0.2.2
pwquality                       1.4.5
pyaml                           21.10.1
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycairo                         1.23.0
pycodestyle                     2.10.0
pycparser                       2.21
pycryptodomex                   3.17
pydantic                        1.10.7
pydocstyle                      6.3.0
PyDrive2                        1.15.0
pyflakes                        3.0.1
Pygments                        2.14.0
PyGObject                       3.44.1
pykeepass                       4.0.3
pylint                          2.17.3
pylint-venv                     3.0.1
pyls-spyder                     0.4.0
PyNaCl                          1.4.0
pyOpenSSL                       23.1.1
pyparsing                       3.0.9
PyQt5                           5.15.9
PyQt5-sip                       12.12.1
PyQtWebEngine                   5.15.6
pyrsistent                      0.19.3
PySide6                         6.5.0
pytest                          7.3.0
python-dateutil                 2.8.2
python-json-logger              2.0.7
python-lsp-black                1.2.1
python-lsp-jsonrpc              1.0.0
python-lsp-server               1.7.2
python-slugify                  8.0.1
python-xlib                     0.33
pytoolconfig                    1.2.2
pytz                            2022.7.1
pyxDamerauLevenshtein           1.7.1
pyxdg                           0.28
PyYAML                          6.0
pyzmq                           25.0.2
QDarkStyle                      3.1
qstylizer                       0.2.2
QtAwesome                       1.2.3
qtconsole                       5.4.2
QtPy                            2.3.1
ranger-fm                       1.9.3
rapidfuzz                       2.15.0
regex                           2023.3.23
reportlab                       3.6.12
requests                        2.28.2
requests-file                   1.5.1
requests-unixsocket             0.3.0
rich                            13.3.3
rope                            1.7.0
rsa                             4.9
Rtree                           1.0.1
ruamel.yaml                     0.17.21
ruamel.yaml.clib                0.2.7
scipy                           1.10.1
SecretStorage                   3.3.3
Send2Trash                      1.8.0
setproctitle                    1.3.2
setuptools                      67.6.1
shiboken6                       6.5.0
shiboken6-generator             6.5.0
simplejson                      3.18.0
singlejson                      0.2.3
six                             1.16.0
sniffio                         1.3.0
snowballstemmer                 2.2.0
sortedcontainers                2.4.0
soupsieve                       2.4
Sphinx                          6.2.1
sphinxcontrib-applehelp         1.0.4
sphinxcontrib-devhelp           1.0.2
sphinxcontrib-htmlhelp          2.0.1
sphinxcontrib-jsmath            1.0.1
sphinxcontrib-qthelp            1.0.3
sphinxcontrib-serializinghtml   1.1.5
spyder                          5.4.2
spyder-kernels                  2.4.3
stack-data                      0.6.2
svglib                          1.5.1
sympy                           1.11.1
systemd-python                  235
team                            1.0
terminado                       0.17.1
testpath                        0.6.0
text-unidecode                  1.3
textdistance                    4.5.0
three-merge                     0.1.1
tinycss2                        1.2.1
tldextract                      3.4.0
toml                            0.10.2
tomli                           2.0.1
tomlkit                         0.11.7
tornado                         6.2
traitlets                       5.9.0
trove-classifiers               2023.4.20
typing_extensions               4.5.0
uc-micro-py                     1.0.1
ueberzug                        18.1.9
ufw                             0.36.1
ujson                           5.7.0
uritemplate                     4.1.1
urllib3                         1.26.13
validate                        5.1.0.dev0
validate-pyproject              0.12.2.post1.dev0+g2940279.d20230328
virtualenv                      20.17.1
watchdog                        2.3.0
wcwidth                         0.2.5
webencodings                    0.5.1
websocket-client                1.5.1
websockets                      10.4
whatthepatch                    1.0.4
wheel                           0.40.0
wrapt                           1.14.1
wurlitzer                       3.0.3
yapf                            0.32.0
Yapsy                           1.12.2
zipp                            3.15.0

```
</details>

**Comment by dalthviz** [comment] 2023-05-19 19:55
Hi @Qrashi thank you for the feedback! This is a duplicate of https://github.com/spyder-ide/spyder/issues/20406. To prevent the error message from appering you just need to update Spyder to the latest release (5.4.3), although not totally sure is you can do that with pacman :thinking:. You can also follow the instructions in the linked issue to disable the check for updates (which is the thing triggering the error dialog).

Let us know if updating or the info above helps!

**Comment by dalthviz** [comment] 2023-06-20 21:14
Closing as a duplicate of #20406

**Closed by dalthviz** 2023-06-20 21:14 UTC
Labels: resolution:Duplicate, status:Awaiting Followup
