### ISSUE TITLE
NameError: name 'runfile' is not defined 3.0.0b7

### ISSUE THREAD

**Issue by notmyrealhandle** [spyder-ide/spyder#3440] opened 2016-09-21 03:30 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. as clean an install of this spyder version as i can make it, spyder --reset, spyder --default, etc.
2. run any code from the editor via F5 key (or button, etc) e.g. print("test") in temp.py
3. 

**What is the expected output? What do you see instead?**

the code in the editor should run but the following is generated:

runfile('/path/to/temp.py', wdir='/path/to')
Traceback (most recent call last):

  File "<ipython-input-1-efd0e4c0584f>", line 1, in <module>
    runfile('/path/to/temp.py', wdir='/path/to')

NameError: name 'runfile' is not defined

**Please provide any additional information below**
"import spyder.widgets.externalshell" from the console will fix this bug (something missing in an __init__.py file?)

## Versions and main components

* Spyder Version: 3.0.0b7
* Python Version: 3.4.3
* Operating system:Linux ul 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by stonebig** [comment] 2016-09-21 05:01
seems a duplicate of this one https://github.com/spyder-ide/spyder/issues/3428

... so solved in coming beta8

**Comment by ccordoba12** [comment] 2016-09-21 06:56
Yep, this was fixed already.

**Closed by ccordoba12** 2016-09-21 06:56 UTC
