### ISSUE TITLE
Balloon tips sometimes (!) not showing up

### ISSUE THREAD

**Issue by fgotzens** [spyder-ide/spyder#9905] opened 2019-07-28 16:36 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (_does not apply here, as jupyter never shows any balloon tips if I'm right_)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Opening a round bracket `(` in the IPython console does sometimes not invoke showing a balloon tip with possible arguments when calling some functions whereas it _does_ in other functions.

### What steps reproduce the problem?

1. Create an empty function
```python
def database_get(dimension='spatial', description=False, short=True, year=None,
                 table_id=None, internal_id=None):
    return
```
inside a module called `data.py` of a project `myproject`. Then load it via
```python
from myproject import data
```
and call it via `data.database_get(` 
**--> No balloon tip at all.**

2. Then I tried to isolate the problem. Is it maybe related to the number of arguments? So I created a dummy function:
```python
def dummy(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u):
    return
```
![screen_01](https://user-images.githubusercontent.com/24390473/62009800-45a79500-b163-11e9-914a-0afef6e05871.png)

**--> No, it's not! Balloon tip is showing up as expected.**

3. Causes a presetting the arguments with default values the problem?
```python
def dummy(a, i, b=4, c=4., d=True, e='e', f=None, g=None, h=False, *args):
    return
```
![screen_02](https://user-images.githubusercontent.com/24390473/62009868-12193a80-b164-11e9-8f84-7c204a6b5e71.png)

**--> No, it's not! Balloon tip is showing up as expected.**

4. Then I just changed `b=4` to `b=43`:
```python
def dummy(a, i, b=43, c=4., d=True, e='e', f=None, g=None, h=False, *args):
    return
```
![screen_03](https://user-images.githubusercontent.com/24390473/62009921-9ec3f880-b164-11e9-8d24-77a806374d55.png)

**--> There it is! No balloon tip any more.**
**Could it be that the total length of all the arguments causes the problem?**

### What is the expected output? What do you see instead?

I expect seeing balloon tips whenever I open a round bracket of an existing function.

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.3 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 7 Pro

### Dependencies

```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-29 09:36
Thanks for reporting.

@steff456, please verify if this is still the case in master or not.

**Comment by fgotzens** [comment] 2019-07-29 10:40
Just figured out what might be important for bugfixing: 

1. This behaviour rather happens when functions that have been imported from a module are being called. If one just copy&paste's the `def dummy(...)` into a console, the balloon tips most of the time show up as expected.

2. I was able to reproduce this issue on another machine running Python 3.6.5 64-bit, IPython 7.6.1, Qt 5.9.6, PyQt 5.9.2, Windows 8.1.

3. I was **not able** to reproduce on a third machine running Python 2.7.15 64-bit, IPython 5.7.0, Spyder 3.2.8, Qt 5.6.2, PyQt 5.6.2, Windows 8.

**Comment by ccordoba12** [comment] 2019-07-29 11:19
Are you able to reproduce this problem in qtconsole or starting IPython in cmd.exe?

**Comment by fgotzens** [comment] 2019-07-29 14:53
> 
> 
> Are you able to reproduce this problem in qtconsole or starting IPython in cmd.exe?

Well, when starting IPython in cmd.exe, I am not expecting any balloon tips to appear in general in a command line environment?!

Starting `jupyter qtconsole` I cannot reprocude it from there, **it works perfectly**: From what I tested, all balloon tips appear as expected.

**Comment by ccordoba12** [comment] 2019-08-05 17:21
This should be solved in Spyder 4 (to be released in a couple of months) because we fixed several bugs related to showing balloon tips in the IPython console.

Please reopen if that's not the case.

**Closed by ccordoba12** 2019-08-05 17:21 UTC
Labels: status:Awaiting Followup
