### ISSUE TITLE
PEP8 for line breaks before binary operators is incorrect

### ISSUE THREAD

**Issue by munircontractor** [spyder-ide/spyder#4203] opened 2017-02-25 23:57 UTC
Hello Spyder devs,
Spyder indicates a PEP8 violation for line breaks before binary operator. However, that is the PEP8 standard.

![screenshot from 2017-02-25 18-55-56](https://cloud.githubusercontent.com/assets/11322718/23335862/114fd194-fb8c-11e6-89e4-8b313be6c5d7.png)

Here's the [PEP8 for that.](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator)

You can reproduce the problem by writing a line with a break in front of a binary operator.
Example

        x = (1
             + 2)

This happens in Spyder version 3.1.3 on Python 3.5 and 2.7 in Linux installed with `pip`. I also saw this on the Windows version shipped along with WinPython.

Please update that.
Thank you.

**Comment by bilderbuchi** [comment] 2017-02-27 07:13
PEP8 was recently changed, and the tools (here: pycodestyle) are still catching up, so this will trickle down to spyder in a while I guess. 
See https://gitlab.com/pycqa/flake8/issues/139 https://github.com/PyCQA/pycodestyle/issues/498 https://hg.python.org/peps/rev/9afe77ad549b

Close this as not-spyder's-bug?

**Comment by ccordoba12** [comment] 2017-02-27 15:01
We could switch to use `pycodestyle` instead of `pep8`, I think.

**Comment by bilderbuchi** [comment] 2017-02-27 15:30
It's the same thing... pep8 got renamed to pycodestyle.

**Comment by ccordoba12** [comment] 2017-02-27 15:39
I know it's the same thing, but we still use `pep8` as a dependency.

I'm closing this issue as a duplicate of #3197.

**Closed by ccordoba12** 2017-02-27 15:39 UTC
Labels: resolution:Duplicate
