### ISSUE TITLE
Variable explorer with binary data hangs spyder

### ISSUE THREAD

**Issue by Diti24** [spyder-ide/spyder#3196] opened 2016-05-31 17:13 UTC
## Description
After some investigation I finally found the cause (not the solution)
loading binary data in a variable in a variable makes the spyder IDE hang.
This happens only if the Variable exploer is enabled and "Esclude unsupported data types" option is not flagged.

**What steps will reproduce the problem?**

f=open('/tmp/20160530_185413__hmo1002.dat', 'rb')
a=f.read()
type(a)
Out[3]: bytes
len(a)
Out[4]: 2896

If the above sequence is perfomed with the Variable Explorer enabled and  "Esclude unsupported data types" option is not flagged, the IDE will hang...

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
the test data (which is not huge 2896 bytes) is attaced

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.4.4
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
pylint >=0.25      :  0.25.1 (OK)

```

**Comment by Nodd** [comment] 2016-05-31 17:47
Yes, there is a big issue with the variable explorer currently. In your case the data is rather small so it's not a performance issue but a bug somewhere.

**Comment by ccordoba12** [comment] 2016-06-01 03:03
Could you please upload a copy of `20160530_185413__hmo1002.dat` somewhere to test this problem in our side? Thanks :-)

**Comment by Diti24** [comment] 2016-06-01 07:32
Hi, 
I did not notice that is was not uploded, sorry, now in zip format should work
[20160530_185413__hmo1002.dat.zip](https://github.com/spyder-ide/spyder/files/292849/20160530_185413__hmo1002.dat.zip)

**Comment by jitseniesen** [comment] 2016-06-06 12:53
I can reproduce this with 3.0.0b2 but not with current head. I think this may be a duplicate of #3031.

**Comment by jitseniesen** [comment] 2016-06-06 12:56
@Diti24 , if I'm right then upgrading spyder to version 2.3.9 should fix the issue.

**Comment by Diti24** [comment] 2016-06-06 13:04
@jitseniesen, thenks. About 2.3.9 well if I do conda upgrade I remain to 2.3.8... shall I do a manual installation? Shall I do a manual installation or m I missing something

Following is my conda output
conda upgrade spyder
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /mnt/disk2/opt/anaconda3:
#
spyder                    2.3.8                    py34_1

**Comment by jitseniesen** [comment] 2016-06-06 15:32
Sorry, even though I use anaconda I don't really understand it well, so you need somebody else. All I can see is that it works for me. Maybe if you specify the required version number by saying `conda install spyder=2.3.9` it gives you a hint if there is a problem with a dependency or something like that. Or maybe `conda info` says something useful. Hopefully somebody else knows what's going on.

**Comment by ccordoba12** [comment] 2016-06-08 13:52
@Diti24, the problem is Spyder packages for Python 3.4 are not ready. You can update by doing

    conda remove spyder
    pip install spyder

**Closed by ccordoba12** 2016-06-08 13:52 UTC
Labels: Comp-Variable-Explorer, Type-Bug

**Comment by Diti24** [comment] 2016-06-10 08:56
Thank,
can confirm it works with spyder 2.3.9
