### ISSUE TITLE
Variable Explorer - Dictionary Automatically Getting Sorted by Keys Alphabetically

### ISSUE THREAD

**Issue by uygartolgakara** [spyder-ide/spyder#18338] opened 2022-06-18 19:01 UTC
### What steps will reproduce the problem?

1) Make a dictionary as:
my_dict = {"a":1, "c":2, "b":3}

2) Observe my_dict variable looks correct in variable explorer. Meaning, keys are ordered as a,c,b.

3) Click on my_dict variable in variable explorer.

4) Observe that dictionary is automatically sorted by keys. In other words, the order of keys are a,b,c. But the order needs to be a,c,b

## Versions

* Spyder version: 5.3.1 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.1 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.9 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.3.2 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.1 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.8 (OK)
zmq >=22.1.0                         :  23.0.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.2 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by uygartolgakara** [comment] 2022-06-18 19:08
I also leave a screenshot to summarize the issue. As it can be seen, input is given to make a "dd" dictionary. In variable explorer it can be seen that dd variable seems correct in order. (a-c-b) But when dd variable is clicked to analyze further, the order automatically changes to a-b-c, in other words sorted by keys alphabetically.

![to_share](https://user-images.githubusercontent.com/80326697/174452973-8f2e54e4-6841-40b8-87e2-cdea4aa99858.png)

**Comment by ccordoba12** [comment] 2022-06-19 16:51
Hey @uygartolgakara, thanks for reporting. This is a duplicate of issue #9136 and we'll try to fix it in a future version.

**Closed by ccordoba12** 2022-06-19 16:51 UTC
