### ISSUE TITLE
Pyhon multiprocess unable to hit breakpoint to debug fork process in spyder

### ISSUE THREAD

**Issue by Mingming-a** [spyder-ide/spyder#18401] opened 2022-06-23 08:26 UTC
I am trying to debug one of my multi-process programs in Python 3.7 with Anaconda distribution on Spyder 4.1 (latest release came from Anaconda package)- when the sub-process are started, IDE is unable to hit any breakpoints. It is a pity to me. I need to debug multiprocess and check the param's value. Spyder is not supported.
Here is the part of code

def invoke_master(P2):
    try:
        t = time.strftime("%Y%m%d%H%M%S", time.localtime())
        f='D:\log\master.log'
        if os.path.exists(f):
            os.remove(f)
        sys.stdout = Logger(f)
        print('run master process')
        print(f'master is finised')
    finally:
        sys.stdout.reset()    

def invoke_slave(P1):
    try:
        t = time.strftime("%Y%m%d%H%M%S", time.localtime())
        f='D:\log\slave.log'
        if os.path.exists(f):
            os.remove(f)
        sys.stdout = Logger(f)
        print('run slave process')
        print(f'slave is finised')
    finally:
        sys.stdout.reset()
    

if __name__ == '__main__':
    t_t0 = time.time()
    print(f'main time is {t_t0}')
    coresNum = int(mp.cpu_count())
    print(f'cpu core num is {coresNum}')
    time.sleep(2)
    # True means full duplex
    P1, P2 = Pipe(duplex=True)
    master = Process(target=invoke_master, args=(P2,))
    slave = Process(target=invoke_slave, args=(P1,))
    master.start()
    slave.start()
    master.join()
    slave.join()
    t_t1 = time.time()
    print(f'all tasks completed took time={t_t1 - t_t0:.2f}s...')

**Versions**
    Spyder version: 4.1
    Python version: 3.7

**Comment by Mingming-a** [comment] 2022-06-24 02:46
I have updated my Spyder to version 5.3.1 but IDE is unable to hit any breakpoints in function invoke_master or invoke_slave. IDE hit breakpoint in Main function that's not i want. I need IDE hit breakpoint in fork process.

**Comment by impact27** [comment] 2022-06-24 06:21
This is a duplicate of https://github.com/spyder-ide/spyder/issues/8801
I would advise you to write `breakpoint()` where you want to break in the thread. Otherwise the breakpoint only stop on the main thread.

**Comment by Mingming-a** [comment] 2022-06-24 06:40
I used breakpoint() in my code and run, IDE console output breakpoint(), so can i debug forked process by main process. Is there any way to make it happen.
def invoke_master(P2):
try:
t = time.strftime("%Y%m%d%H%M%S", time.localtime())
f='D:\log\master.log'
if os.path.exists(f):
os.remove(f)
sys.stdout = Logger(f)
breakpoint()
print('run master process')
print(f'master is finised')
finally:
sys.stdout.reset()

**Comment by Mingming-a** [comment] 2022-06-24 08:32
Yes, use breakpoint() in threading it will work, but now i need to use breakpoint() in multiprocessing, so the master and slave can parallel work and communicate with each other. When the master run to some code, I hope it pause and i will check some value, after then continue run.

**Comment by impact27** [comment] 2022-06-24 09:31
In threads they also can of do parallel work. Debugging in multiprocessing is not (yet) supported, but in most cases you can debug in threads instead of processes

**Comment by Mingming-a** [comment] 2022-06-24 09:44
Thanks, Python threads has GIL limits, same time allow one thread  to run. Am i right? And i want to output print to separate log file for each thread, what can i do?

**Comment by impact27** [comment] 2022-06-24 10:00
So multiprocessing.dummy works pretty much exactly the same way as multiprocessing, but slower, so I would debug with multiprocessing.dummy, and check if it still works with multiprocessing. This work unless you need a process and not a thread for some reason

**Comment by Mingming-a** [comment] 2022-06-27 01:20
Multiprocessing.dummy is actually multithreading, so i use multi-threads instead process,  and the printed info mixed up from two threads, i need to print redirect to separate log file, can you help me?

**Comment by impact27** [comment] 2022-06-27 07:03
You can use https://docs.python.org/3/library/threading.html#threading.get_ident to name the log files

**Comment by Mingming-a** [comment] 2022-06-27 07:15
You misunderstand what i mean. If i use multi-thread print redirect to master.log and slave.log, the print will redirect to one log file, you can't open two log file in multi-thread. I want to know which thread print the message, they look like same.
def invoke_master(P2):
try:
f='D:\log\master.log'
if os.path.exists(f):
os.remove(f)
sys.stdout = Logger(f)
print('run master process')
print(f'master is finised')
finally:
sys.stdout.reset()

def invoke_slave(P1):
try:
f='D:\log\slave.log'
if os.path.exists(f):
os.remove(f)
sys.stdout = Logger(f)
print('run slave process')
print(f'slave is finised')
finally:
sys.stdout.reset()

**Closed** 2022-06-29 03:05 UTC
Labels: status:Awaiting Followup
