### ISSUE TITLE
Opening Dataframe in Variable Explorer not working with packaged 4.2.1 dmg version of Spyder

### ISSUE THREAD

**Issue by vancromy** [spyder-ide/spyder#14542] opened 2021-01-05 14:19 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted console 

- [ ] Spyder

    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Get an error when attempting to open a pandas Dataframe from the Variable Explorer:
![image](https://user-images.githubusercontent.com/59556820/103656656-26708200-4f69-11eb-895f-d74f61cde2a9.png)

### What steps reproduce the problem?

1. Run a script output a pandas Dataframe.
2. Open Pandas DataFrame from the variable explorer (double-clicking or right-click)
3. 

### What is the expected output? What do you see instead?
Open's new window showing the DataFrame as in previous version of Spyder

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.9.1 64-bit
* Qt version: 5.12.1
* PyQt version: 5.12.3
* Operating System name/version: Darwin 20.2.0 (Mac OS Big Sur) 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by mrclary** [comment] 2021-01-05 17:53
@vancromy, I assume that you are using the "Full" version macOS application and not the "Lite" version, correct?

**Comment by vancromy** [comment] 2021-01-05 18:41
@mrclary Yes, that's correct (I used the link that is documented in the 4.2.1 release notes).

**Comment by mrclary** [comment] 2021-01-05 18:49
I'll take a look. I suspect that this may be caused by pandas residing in the zipped library, in which case it should be an easy fix.

**Comment by mrclary** [comment] 2021-01-05 20:16
It was as I had suspected. Should be fixed by PR #14545

**Closed** 2021-01-05 22:11 UTC
Labels: OS:MacOS, tag:Installer, type:Bug
