### ISSUE TITLE
IPython consoles are not shown because they can't pass of the "Connecting to kernel" step

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2157] opened 2015-02-17 23:33 UTC
_From [RyanA1...@gmail.com](https://code.google.com/u/100274756805842908075/) on 2015-02-04T13:08:31Z_

Spyder Version:  2.3.2
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
zmq >=2.1.11    :  14.3.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Start Spyder OR go to Consoles>Open an IPython Console 

What is the expected output? What do you see instead?

 It should connect to an IPython console. Instead just shows "Connecting to Kernel" and a spinning wheel. 

Please provide any additional information below

. Previous version of Spyder worked fine. When I installed the new Anaconda distribution, it updated Spyder and stopped working.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2157_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:33
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-04T10:25:29Z_

It could be a number of things. To start, please give focus to the Python console, look for a tab called "Kernel" and see if there's an error reported there.

**Labels:** Cat-IPythonConsole MS-v2.3.4

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [RyanA1...@gmail.com](https://code.google.com/u/100274756805842908075/) on 2015-02-04T13:05:17Z_

Thanks for the quick response! 

On the kernel tab, this is what I see (doesn't look like an error...):
"NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049 To connect another client to this kernel, use:
    --existing kernel-14144.json"

If I go to the "Consoles" menu and choose "Connect to an existing kernel" and use the kernel ID # listed, I can connect.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-04T14:58:05Z_

Mmmhh. A couple of people have reported this error. The problem is I don't know how to fix it because I don't know the cause :-(

The thing is this doesn't always occur. It's just for some configurations or setups.

Could you try to deactivate your antivirus or firewall and try again?

**Labels:** -MS-v2.3.4 MS-v2.4

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T10:34:59Z_

**Summary:** IPython consoles are not shown because they can't pass of the "Connecting to kernel" step  \<span class="oldvalue"> (was: Cannot connect to kernel) \</span>

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T11:27:46Z_

issue #1950 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T18:44:33Z_

issue #2094 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [RyanA1...@gmail.com](https://code.google.com/u/100274756805842908075/) on 2015-02-09T08:21:57Z_

Sorry, I can't deactivate antivirus or firewall: I am using a work computer that prevents me from doing that. Let me know if there is anything else I can try to help with this issue.

In the meantime I am using an earlier version of Spyder (2.2.5) that is working well.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:34
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-12T08:41:08Z_

I'm going to redesign the way we start IPython consoles in 2.4 because right now the process is very fragile.

That's why I marked this issue for that version.

**Comment by ralexx** [comment] 2015-03-07 07:02
I experienced this issue (originally #2094) in 2.3.2 under OS X 10.10, now in 2.3.3 seeing "An error ocurred while starting the kernel" in the iPython console window when Preferences/Console/Advanced settings/Python executable is NOT set to Default. 

* *What steps will reproduce the problem?*
1. Specify a custom Python interpreter under Preferences/Console/Advanced settings/Python executable, e.g. `/usr/bin/python` (2.7.6) or `/usr/local/bin/python` (2.7.9)

## Version and main components

* Spyder Version:  2.3.3
* Python Version:  2.7.8
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.1 on Darwin
  OS X 10.10.2

## Optional dependencies

IPython >=1.0   :  3.0.0 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
psutil >=0.3    :  2.2.1 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
zmq >=2.1.11    :  14.5.0 (OK)

**Comment by ccordoba12** [comment] 2015-03-08 18:23
@ralexx The bug you mention was already reported in #2227 and will be fixed in 2.3.4.

**Comment by ccordoba12** [comment] 2015-06-28 17:42
I think this is closely related to issue #1880 (on Windows platforms)

**Comment by ccordoba12** [comment] 2015-09-09 16:14
I'm closing this as a duplicate of issue #1880.

**Closed by ccordoba12** 2015-09-09 16:14 UTC
Labels: duplicate
