### ISSUE TITLE
keyboard focus moved to "help" after auto-import of 

### ISSUE THREAD

**Issue by thierryBottaro** [spyder-ide/spyder#3342] opened 2016-08-04 08:59 UTC
In the Preferences, I checked [Help]"Automatic connections" with IPython Console.
So when I type a function name and "(", the Help sub-window show me the Help of the typed function (that's great!)
But, I can't type the rest of my command in IPython, because the docked-sub-window "Help" took the focus

By the way, in the "Help" sub-window the option "Automatic import" does not have any action (only the checkbox in preferences has an influence on behaviour)
And I think that the "Source : Console/Editor" dropdown is also redondant with the Preferences parameters (there is a checkbox for Editor, Console, IPython Console)

**What steps will reproduce the problem?**

if the "automatic connections" is set
1. in IPython type (not copy-paste) "np.mean( myArray)"

**What is the expected output? What do you see instead?**
I expect "np.mean( myArray)" but only "np.mean(" is in IPython, because the focus has been taken by the Help window.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: Spyder 3.0.0beta 4 from "WinPython-64bit-3.5.2.1Qt5"
* Python Version: 3.5.2 64bits
* Operating system: Win 7

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-08-04 13:56
Thanks for reporting. This is a duplicate of issue #3317.

**Closed** 2016-08-04 13:56 UTC
Labels: Type-Duplicate
