### ISSUE TITLE
SVG backend doesn't look as sharp like it does in IPython notebooks

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#14208] opened 2020-11-12 20:32 UTC
### What steps will reproduce the problem?

SVG backend doesn't look as sharp like it does in IPython notebooks

## Versions

* Spyder version: 4.2.0 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.5.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.5.3 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.2.0.post20200714 (OK)
sphinx >=0.6.6                  :  3.1.2 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.1 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.2.2 (OK)
numpy >=1.7                     :  1.18.5 (OK)
pandas >=1.1.1                  :  1.0.5 (NOK)
scipy >=0.17.0                  :  1.5.0 (OK)
sympy >=0.7.3                   :  1.6.1 (OK)
```
# Figure generated in a Jupyter notebook with SVG backend
![image](https://user-images.githubusercontent.com/14086031/98993393-60d71900-24fc-11eb-8663-2af529b22eb7.png)

# Figure generated in Spyder inline IPython
![image](https://user-images.githubusercontent.com/14086031/98993433-73e9e900-24fc-11eb-9938-cb24e8f91c0e.png)

**Comment by ccordoba12** [comment] 2020-11-13 02:55
Hey @ma-sadeghi, thanks for reporting. This is a duplicate of issue #9987.

We'll try to fix it for Spyder 5.

**Closed by ccordoba12** 2020-11-13 02:55 UTC
