### ISSUE TITLE
Spyder kernel issue with pandas dataframes

### ISSUE THREAD

**Issue by lalita90** [spyder-ide/spyder#20853] opened 2023-04-19 23:05 UTC
## Problem Description
Hi, I have been using Spyder IDE for a while but recently whenever I try to check any thing related to a dataframe in Spyder's console using a command, it throws me an error SpyderKernelApp] ERROR | Exception in message handler. I tried the following solution but it didn't work- conda install ipykernel=5 jupyter_client=6
### What steps reproduce the problem?

1. Python 3.10
2. Mac OS M1 chip (Ventura)
3. Tensorflow 2.12.0

### What is the expected output? What do you see instead?
Expected: df.head()
for this command, I see the following error 

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 796, in inspect_request
    reply_content = self.do_inspect(
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 544, in do_inspect
    bundle = self.shell.object_inspect_mime(
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1838, in object_inspect_mime
    return self.inspector._get_info(
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/IPython/core/oinspect.py", line 738, in _get_info
    info_dict = self.info(obj, oname=oname, info=info, detail_level=detail_level)
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/IPython/core/oinspect.py", line 838, in info
    if info and info.parent and hasattr(info.parent, HOOK_NAME):
  File "/Users/lmeena/miniconda3/lib/python3.10/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

## Versions

* Spyder version: 5.4.3
* Python version: 3.10
* Operating System name/version: Mac OS M1 Ventura 13.2.1
The issue persisted before upgrading the Spyder version as well

**Comment by ccordoba12** [comment] 2023-04-20 17:22
Hey @lalita90, thanks for reporting. This is a duplicate of issue #20816 and we'll try to fix it in our next version (5.4.4). In the meantime, please downgrade IPython to its 8.7 version with the command

    conda install ipython=8.7

I think that should avoid the problem in the meantime, but let us know if it works for you.

**Comment by ccordoba12** [comment] 2023-04-20 17:48
Great! Thanks for letting us know about it. That way we can recommend that solution to other users as well.

I'm going to close this issue since (as I said) it was already reported before.

**Closed by ccordoba12** 2023-04-20 17:48 UTC
Labels: status:Awaiting Followup

**Comment by y11z** [comment] 2023-10-18 21:01
I can't get it through, annoying error msg every commend. plz help

(base) C:\Windows\system32>conda install ipython=8.7
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - ipython=8.7 -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by ccordoba12** [comment] 2023-10-19 01:54
@y11z, any version equal or greater than 8.7 will do the job. So, keep trying with

    conda install ipython=8.8
    conda install ipython=8.9

etc, until you get a version that can be installed in your environment.
