### ISSUE TITLE
cwp.py doesn't append to the PATH  C:\Users\..\anaconda3\envs\my-env\bin... Should Spyder be looking for LIBIOMP5MD.DLL there?

### ISSUE THREAD

**Issue by Tunneller** [spyder-ide/spyder#21760] opened 2024-02-02 17:36 UTC
Not sure if this is a bug... For sure I would not try to repeat this, but somehow after first failing with broken environments but then finally succeeding in updating to conda python 3.10 and latest Spyder 5.4.3 I found myself in the state where Spyder would launch perfectly from my environment, but would crash immediately if launched from the Start Menu. This all on Windows 10. The error message in Event Log pointed me to KERNELBASE.DLL, but that turned out to be a red herring.

If I copied the start menu command and typed it into an Anaconda terminal, then Spyder would launch. If I copied that start menu command into a regular terminal, then Spyder would immediately die with the same KERNELBASE.DLL error reported to the Event log. After hacking around in PDB, I found that the environment being created by CWP.PY was not quite the same environment that did work, specifically it was missing the ....\my-env\bin folder, which has in it LIBIOMP5MD.DLL

I changed CWP.PY to add the term   `join(prefix, "bin"),` to the new_paths and, amazing, Spyder now opens perfectly from the startup menu.

As I say, I don't know if I had a broken environment somehow, but if anyone else is reporting similar mysterious errors on launch then it might be appropriate to update cwp.py for everyone.

**Comment by GitKia1392** [comment] 2024-02-02 23:14
Glad you found a solution yourself. You can contact @ccordoba12 for this to be fixed since i am not a dev(kind of).

Glads
Kiamehr

**Comment by ccordoba12** [comment] 2024-02-08 16:50
Hey @Tunneller, thanks a lot for reporting and finding a solution to this problem. I think it's a duplicate of issue #21749 because it's related to the auto-generated shortcut for Spyder on Windows.

So, I'm going to close it in favor of that one but I'll post your command there because I think it contains the key piece of information we need to solve this.

**Closed by ccordoba12** 2024-02-08 16:50 UTC
