### ISSUE TITLE
fuzzy autocompletion.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11535] opened 2020-02-12 02:40 UTC
Hi,

Can you let the spyder support fuzzy autocompletion instead of beginning-based completion.

Say, for pycurl,  the following:

```
import pycurl
pycurl.time<tab>
```

Should you let it also give suggestions such as:  

pycurl.CONNECT_TIME

Regards

**Comment by goanpeca** [comment] 2020-02-12 03:42
Closing as duplicate of https://github.com/spyder-ide/spyder/issues/2374

**Closed by goanpeca** 2020-02-12 03:42 UTC

**Comment by hongyi-zhao** [comment] 2020-02-12 04:21
It seems it still in progress, and not implemented currently.

**Comment by ccordoba12** [comment] 2020-02-12 14:19
It will be implemented in a couple of months.
