### ISSUE TITLE
Import error when i use " import matpotlib " 

### ISSUE THREAD

**Issue by deep-kiran** [spyder-ide/spyder#5148] opened 2017-09-06 17:08 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/waitingspinner.py", line 177, in rotate
    def rotate(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/waitingspinner.py", line 177, in rotate
    def rotate(self):
KeyboardInterrupt

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 2.7.6
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.3.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2017-09-06 18:35
Thanks for reporting. This is a duplicate of issue #5114.

**Closed by ccordoba12** 2017-09-06 18:35 UTC
