### ISSUE TITLE
Error during launching 

### ISSUE THREAD

**Issue by djaberpy** [spyder-ide/spyder#6313] opened 2018-01-27 21:54 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/djaber/miniconda2/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/home/djaber/miniconda2/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 15: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/djaber/miniconda2/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/home/djaber/miniconda2/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 47: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.1 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-28 08:32
Thanks for reporting. This error ultimately occurs because Spyder is running under Python 2.7, which doesn't have proper Unicode support. It is possible we can work around this on our end, but as we have limited resources and are unfunded at the moment, it might or might not happen soon. In the meantime, you should either use only ASCII characters in the full file paths for your projects (the culprit is may be with a non-ASCII character in your username, if I had to guess) with Python 2, or just upgrade to Python 3 which has proper Unicode support. Also, this appears to be a duplicate of #5001 , which in turn was suggested to be quite similar to #5000 . Therefore, this will be closed.

You are also welcome to look into this yourself and submit a PR to fix it if we aren't able to right away, as if its fixable it shouldn't be too hard if you know a little bit about Python 2/Python 3 compatibility and just follow the error traceback above to find the culprit; it appears that it is due to improper unicode handling in directory names in the Spyder file explorer at ``spyder/widgets/explorer.py", line 144``, so you can take a look there. Thanks.

**Closed by CAM-Gerlach** 2018-01-28 08:32 UTC
