### ISSUE TITLE
')' in string literals breaks editor's parantheses matching

### ISSUE THREAD

**Issue by Amselfass** [spyder-ide/spyder#8547] opened 2019-01-10 17:00 UTC
### What steps will reproduce the problem?

Reproduction steps:
1) Open a new file
2) Enter this line in the editor:
   print(')')
3) Move the cursor to the end of the line

Expected result:
The closing ')' character of the print function should be highlighted in green together with the opening '(' character.

Actual result:
The closing ')' character of the print function is highlighted in red as mis-matched parantheses.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by bcolsen** [comment] 2019-01-11 07:35
@Amselfass Thanks for the bug report!

We are currently tracking this bug in #2965. If need you can discuss it further on that issue.

Closing as duplicate of #2965.

**Closed by bcolsen** 2019-01-11 07:35 UTC
