### ISSUE TITLE
Kernel is not restarted correctly when RecursiveError is thrown on Windows

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#13018] opened 2020-06-13 06:57 UTC
```python
class C():
    @property
    def x(self):
        return self.x
C().x
```
See [here](https://stackoverflow.com/q/62356253/10133797); same if running as a file (main) or from within IPython.

Restarting kernel later rather than sooner, it's non-responsive, so I closed the terminal - yielding this:

![image](https://user-images.githubusercontent.com/16495490/84562337-d2037c00-ad64-11ea-87f6-d106e1af4c74.png)

Closing again worked properly; opened Console 3/A.

**Comment by OverLordGoldDragon** [comment] 2020-06-13 07:30
This is rather strange as some users reported reproducing it from terminal - opened parallel [IPython Issue](https://github.com/ipython/ipython/issues/12387).

**Comment by OverLordGoldDragon** [comment] 2020-06-13 12:56
This also crashes:

```python
def f(*args):
    f(*args)
f()
```
but THESE don't, and properly throw `RecursionError`:

```python
def f():
    f()
f()

def f(x):
    f(x)
f(5)
```

**Comment by goanpeca** [comment] 2020-06-13 17:01
@impact27 do you know what might be going on? Thanks!

**Comment by impact27** [comment] 2020-06-14 07:39
I tried it on macOS and it raises `RecursionError`

**Comment by impact27** [comment] 2020-06-14 07:47
I think the IPKernelApp warning should not prevent the console from being reopened, it is confusing for the user.

**Comment by ccordoba12** [comment] 2020-06-14 21:19
@OverLordGoldDragon, since your code generates a kernel crash on Windows, the only thing we can do is to properly restart it.

That's not happening right now because we're showing the message about comms displayed in your screenshot above. However, it'll be fixed in PR #12972.

**Comment by ccordoba12** [comment] 2020-06-15 05:09
I can confirm this is a problem in IPython (not in Python), so it has to be fixed there.

**Comment by OverLordGoldDragon** [comment] 2020-06-15 05:11
@ccordoba12 How would one test if it's "pure Python" that fails? Run `python file.py` from terminal?

**Comment by ccordoba12** [comment] 2020-06-15 05:13
I started a Python interpreter in a terminal and introduced by hand your first example.

**Comment by OverLordGoldDragon** [comment] 2020-06-15 05:15
@ccordoba12 Last comment [here](https://stackoverflow.com/q/62356253/10133797) confirms reproducing it in terminal (also slightly up: "but from Windows terminal").  I, however, can't reproduce it. There were some [steps](https://github.com/ipython/ipython/issues/12387#issuecomment-643903741) posted in IPython that I'll try today, for reference.

**Comment by ccordoba12** [comment] 2020-06-15 05:33
I could reproduce it on IPython terminal and the IPython maintainer mentioned a workaround for it.

**Closed** 2020-06-16 18:07 UTC
Labels: component:IPython Console, type:Bug
