### ISSUE TITLE
Tooltips are blank/invisble

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1428] opened 2015-02-17 19:18 UTC
_From [dr.bag...@gmail.com](https://code.google.com/u/114994813800044524025/) on 2013-06-04T13:52:58Z_

Spyder Version:  2.2.0
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux 

What steps will reproduce the problem?

1. Run spyder on Ubuntu.
2. Try a tooltip.
3. Not profit. What is the expected output? What do you see instead? Expect to see tooltip information for menu items, instead I see the yellow
tooltip box but no text. 

Please provide any additional information below

. Tooltips show up blank. Running Ubuntu 12.04. Tried it in Unity, gnome 3 and gnome classic. See the screenshot. Basically every menu tooltip is blank. Otherwise, cheers for spyder. Loving it.

**Attachment:** [screen.png](http://code.google.com/p/spyderlib/issues/detail?id=1428)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1428_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [dr.bag...@gmail.com](https://code.google.com/u/114994813800044524025/) on 2013-06-06T10:39:46Z_

I realized that the QT window style I was using (Windows) was overriding my default tooltip color scheme (white on black). Specifically all but the GTK window style set the tooltip background to yellow resulting in white on yellow = all but invisible. 

By explicitly changing the gnome tooltip config (using gnome-color-chooser) to black on yellow I got tooltips back in Spyder. 

If the QT windows style can be set to observe the system defaults, that would prevent this from happening.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-06T14:56:57Z_

I remember I filled this bug to some package a while ago. Seems like it should be an issue for every Qt app on Ubuntu 12.04. I can confirm it for Spyder on 13.04 with Windows style. https://bugs.launchpad.net/ubuntu/+source/mumble/+bug/817380

**Labels:** Cat-SpyderGUI OpSys-Linux Component-PyQt

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-07T09:28:26Z_

So is there something we can do in our side to fix this or not?

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-08T01:39:20Z_

issue #1257 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-08T02:58:41Z_

Looks like this "Windows" is default Qt style, which sets only background color for tooltip. I we knew Qt, we could try to fix it there - https://bugreports.qt-project.org/browse/QTBUG-12059

**Comment by spyder-issues-migrator** [comment] 2015-02-17 19:18
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-08T03:00:00Z_

On our side we can probably override styles.

**Comment by ccordoba12** [comment] 2015-05-02 19:53
Closing as duplicate of issue #2036.

**Closed by ccordoba12** 2015-05-02 19:53 UTC
Labels: 2–5 stars, bug, duplicate, Linux, PyQt, Spyder-Gui
