### ISSUE TITLE
Spyder not Launching in Anaconda Showing os error.

### ISSUE THREAD

**Issue by DSrijon01** [spyder-ide/spyder#12014] opened 2020-03-27 10:41 UTC
### Issue Report Checklist

* 
- [✔️ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

* [✔️ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ✔️] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [✔️ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [✔️ ] Tried basic troubleshooting (if a bug/error)
    * [✔️ ] Restarted Spyder
    * [✔️ ] Reset preferences with ``spyder --reset``
    * [ ✔️] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [✔️ ] Tried the other applicable steps from the Troubleshooting Guide
* [✔️ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Removing Everything Related to Python to install Anaconda ( i was using pycharm but due to some redundant issues i shifted to anaconda)
2.  Installed Anaconda, added it cmdWindows Path.
3. As spyder wasn't running i updated conda.
4.Updated spyder kernel.

### What is the expected output? What do you see instead?
1.Spyder can be started from windows.
2.Spyder can be started from anaconda prompt.
3. Spyder can be launched from windows.

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\app\start.py", line 215, in main
    from spyder.app import mainwindow
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 182, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\utils\environ.py", line 19, in <module>
    from spyder.plugins.variableexplorer.widgets.collectionseditor import (
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 57, in <module>
    from spyder.plugins.variableexplorer.widgets.collectionsdelegate import (
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 31, in <module>
    from spyder.plugins.variableexplorer.widgets.objectexplorer.attribute_model \
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\__init__.py", line 19, in <module>
    from .attribute_model import DEFAULT_ATTR_COLS, DEFAULT_ATTR_DETAILS
  File "C:\Users\User\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\attribute_model.py", line 29, in <module>
    import numpy as np
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 23, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\User\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.6
* Qt version: 4.7.2
* PyQt version: 1.9.0
* Operating System name/version: Widnows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2020-03-27 15:58
Duplicate of #11988

**Closed by ccordoba12** 2020-03-27 15:58 UTC

**Comment by ccordoba12** [comment] 2020-03-27 16:00
This will be fixed in our next version (4.1.2), to be released next week.

In the meantime, please remove this directory

    C:\Users\User\AppData\Roaming\Python

to fix it.
