### ISSUE TITLE
Spyder error needs a solution

### ISSUE THREAD

**Issue by ErmanIZTECH** [spyder-ide/spyder#6078] opened 2017-12-28 15:53 UTC
## Description

**What steps will reproduce the problem?**

1. Launched Spyder
2. written .py
3. tried to run it then this error.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "e:\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "e:\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "e:\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "e:\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "e:\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)

## Version and main components

* Spyder Version: 3.2.4 
*

**Comment by ccordoba12** [comment] 2017-12-28 15:58
Thanks for reporting. This is a duplicate of issue #5080.

**Closed by ccordoba12** 2017-12-28 15:58 UTC
