### ISSUE TITLE
spyder console does not view the full text

### ISSUE THREAD

**Issue by mostafa808** [spyder-ide/spyder#13633] opened 2020-08-26 11:51 UTC
### What steps will reproduce the problem?

when I try running this code:
'import tkinter
 help(tkinter)
'
the spyder console does not show the full text as it shows the last part of text
why console does not show the full text or at least give us the ability to copy text if it is too large such as python standard IDLE

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment] 2020-08-26 18:30
Hi @mostafa808 to show more of the text that `help` gives you, you can increase the buffer size of the IPython Console. For that go to `Tools > Preferences > IPython Console > Display > Source Code > Buffer`. The default value is 500 (that's why you see the help text truncated up to 500 lines):

![image](https://user-images.githubusercontent.com/16781833/91340760-2764fc00-e79e-11ea-8f84-ffc00c2f51be.png)

Seems like the same happens with QtConsole, is that the intended behavior @ccordoba12 ?

Checking with the Python interpreter and IPython what I get is a `-More-` symbol (`-Más-`) at the end and when I press enter more of the help output is loaded:

![image](https://user-images.githubusercontent.com/16781833/91341993-00a7c500-e7a0-11ea-86fa-d952428c8906.png)

**Comment by ccordoba12** [comment] 2020-08-26 22:19
> Seems like the same happens with QtConsole, is that the intended behavior @ccordoba12 ?

Yes, that's correct. We only show a max number of lines at any time in the console to avoid blocking Spyder when a large amount of text comes from the kernel.

**Comment by dalthviz** [comment] 2020-08-27 00:40
So we should close this one @ccordoba12 ?

**Comment by ccordoba12** [comment] 2020-08-27 01:03
Sure, let's close it.

@mostafa808, I hope you know by now how to increase the buffer size of our consoles.

**Closed by ccordoba12** 2020-08-27 01:03 UTC
Labels: status:Awaiting Followup

**Comment by mostafa808** [comment] 2020-08-27 20:33
Many thanks
