### ISSUE TITLE
Running slow tests in a local Mac machine are never passing

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#12247] opened 2020-04-09 15:21 UTC
Currently slow tests are too broken when running on the local machine.

I have ran 7 different times and all the times it fails with a different test but a similar error. 

The error coming up most of the time seems to be this. @impact27 I believe this is related to some work you did. Could you take a look and see if it can be fixed? Thanks

```
ERROR at setup of test_set_new_breakpoints _________________________
SETUP ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/plugin.py", line 551, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/external-deps/spyder-kernels/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/Users/goanpeca/miniconda3/envs/spy36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
________________________________________________________________________________

----------------------------------- Captured stderr setup ------------------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/plugin.py", line 551, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/external-deps/spyder-kernels/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/Users/goanpeca/miniconda3/envs/spy36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
________________________________________________________________________________
------------------------------------- Captured log setup -------------------------------------
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.005875825881958
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.007189989089966
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0022852420806885
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0050947666168213
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.007450819015503
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.008869171142578
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.008169174194336
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.008012056350708
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0089290142059326
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0080981254577637
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0076558589935303
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.007607936859131
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.009030818939209
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0076353549957275
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0063560009002686
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.007880210876465
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0076708793640137
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0059120655059814
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.008551836013794
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0085489749908447
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0058858394622803
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0080008506774902
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0063059329986572
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0092670917510986
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0054237842559814
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.006951093673706
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.005638837814331
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0086121559143066
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0085651874542236
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0062639713287354
___________________ ERROR at setup of test_preferences_last_page_is_loaded ___________________
SETUP ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/plugin.py", line 551, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/external-deps/spyder-kernels/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/Users/goanpeca/miniconda3/envs/spy36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
________________________________________________________________________________

----------------------------------- Captured stderr setup ------------------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/plugin.py", line 551, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/widgets/shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/external-deps/spyder-kernels/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "/Users/goanpeca/miniconda3/envs/spy36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
________________________________________________________________________________
------------------------------------- Captured log setup -------------------------------------
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0045807361602783
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0621681213378906
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0028491020202637
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0018460750579834
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.002249002456665
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0007741451263428
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.00216007232666
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0000979900360107
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003783941268921
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.000962018966675
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0010080337524414
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003131866455078
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0004310607910156
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0006821155548096
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.004056692123413
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003037929534912
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.002547025680542
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0042521953582764
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003441095352173
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0011749267578125
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0036370754241943
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.001817226409912
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0039491653442383
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0010790824890137
WARNING  traitlets:frontend_widget.py:479 kernel died: 2.999730348587036
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003801107406616
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.001321315765381
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003803014755249
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.0023627281188965
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.002403736114502
WARNING  traitlets:frontend_widget.py:479 kernel died: 3.003988027572632
WARNING  traitlets:frontend_widget.py:479 kernel died: 2.9992589950561523
```

**Comment by ccordoba12** [comment] 2020-04-12 21:30
This is basically a duplicate of #11889

**Closed by ccordoba12** 2020-04-12 21:30 UTC
Labels: severity:1-Critical, type:Bug

**Comment by impact27** [comment] 2020-04-13 08:18
I just tried `pytest --run-slow -vv /Users/quentinpeter/pyscripts/spyder/spyder/app/tests/test_mainwindow.py` and everything ran fine. 
 Is the bug always at setup?
Is the bug always in test_mainwindow.py?

**Comment by impact27** [comment] 2020-04-13 08:28
From the errors messages here, it is caused by spyder-kernels launching too slowly. You can tell because it fails at:
`"spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 87, in comm_channel_manager`
This is triggered when sending a comms message to a kernel that hasn't sent any comms yet. It will time out after 45 seconds if the kernel doesn't send anything.
