### ISSUE TITLE
Large files are slow and unstable

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11201] opened 2019-12-31 11:05 UTC
[Demo](https://www.dropbox.com/s/j6hmqvc2wng0wbu/spyder_demo3.mp4?dl=0). Observations:

 - Scrolling is very slow
 - Highlighting is very slow
 - Adding / removing characters is very slow
 - Adding / removing a character when entire file is highlighted leads to freeze/hang

Note: 18000 lines in the file

**Comment by ccordoba12** [comment] 2019-12-31 14:47
Duplicate of #10992

**Comment by ccordoba12** [comment] 2019-12-31 14:47
It'll be fixed in our next version.

**Closed by ccordoba12** 2019-12-31 14:47 UTC

**Comment by ccordoba12** [comment] 2019-12-31 14:48
Several other perfomance improvements were already done and it'll be part of 4.0.1 too.

**Comment by jmoraispk** [comment] 2020-06-21 13:28
@ccordoba12 I'm using Spyder 4.1.3 and I experience this exact issue with a file with just ~1000 lines. Less severe than the @OverLordGoldDragon 's demo, not sure if due to 18x fewer lines or due to some fixes, but it still is very noticeable.

**Comment by fmgithub2017** [comment] 2020-07-08 15:08
> 
> 
> @ccordoba12 I'm using Spyder 4.1.3 and I experience this exact issue with a file with just ~1000 lines. Less severe than the @OverLordGoldDragon 's demo, not sure if due to 18x fewer lines or due to some fixes, but it still is very noticeable.

@ccordoba12 , I have the same problem, it makes Spyder, which is an awesome IDE, unusable. Shouldn't be the case to reopen this issue?

**Comment by dalthviz** [comment] 2020-07-08 17:38
Hi @fmgithub2017 and @jmoraispk we have #13020 open for some editor performance issues detected in Spyder 4.1.3 (we found that some options in the Editor are causing lag/performance issues, most notably `Underline errors and warnings` ). Maybe you can follow up there how we will be tackling the Editor performance issues :)

**Comment by fmgithub2017** [comment] 2020-07-08 18:17
@dalthviz , thanks man, closing the Outline Pane made a massive difference. 

Just a quick unrelated doubt, the Ctrl+Shift+O shortcut just works to open the Outline Pane but not to close it (I have to do it via mouse clicks), is it right?

**Comment by dalthviz** [comment] 2020-07-08 18:32
Glad you where able to work around the problem @fmgithub2017 :+1:

About the shortcuts, yep that shortcut only enables opening the Outline Pane, however there is global shortcut to close panes (`Ctrl+Shift+F4`) that will close the current focused pane

![short](https://user-images.githubusercontent.com/16781833/86956891-776cfe00-c11f-11ea-99cd-d0d86e3cc59c.gif)

**Comment by fmgithub2017** [comment] 2020-07-08 19:02
Hey @dalthviz , thanks again.
It would be great if the same shortcut opens and closes its corresponding pane, but I will try your solution. 
Cheers
