### ISSUE TITLE
Spyder crashes at "Open file"

### ISSUE THREAD

**Issue by bkuijper** [spyder-ide/spyder#5848] opened 2017-11-28 15:44 UTC
## Description of your problem
Whenever I try to change my working directory or open a file Spyder crashes

**What steps will reproduce the problem?**
1. Open Spyder from Windows start menu 
2. Open file (Ctrl+O)

**What is the expected output? What do you see instead?**
Instead of a dialog box I get an pop up screen with "Python has stopped working"

**Please provide any additional information below**
I am pretty new to Anaconda/Spyder, just installed this version, but can't get it to work. Hope this is the right place to ask this question, I am sorry if it is already mentioned before...

## Versions and main components
* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 7

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAMGerlach-Baron** [comment] 2017-11-28 17:10
Thanks for reporting. This appears to be a duplicate of #3903 , which should be fixed as far as it can be on Spyder's end. The problem is due to an interaction between windows and other Qt5 installs/applications on the system; one particular culprit was Dell Backup and Recovery. In any case, you can take at look at the other issue for some suggested workarounds, and this issue can be closed.

**Closed** 2017-11-29 02:29 UTC
