### ISSUE TITLE
run spyder git version within miniconda: Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11335] opened 2020-01-17 12:02 UTC
Hi,

I try to use the latest git version of spyder without installation as follows with pyenv + miniconda:

```
$ git clone https://github.com/spyder-ide/spyder.git spyder.git
$ cd spyder.git
$ pyenv install miniconda3-latest
$ pyenv local miniconda3-latest
$ conda create -n spyder.git python=3.8
$ pyenv local miniconda3-latest/envs/spyder.git 
$ conda install -c conda-forge spyder=4.0.1
$ python bootstrap.py
Executing Spyder from source checkout
Revision 2a1887cfa, Branch: master
01. Patched sys.path with /home/werner/.repo/github.com/spyder-ide/spyder.git
02. PyQt5 is detected, selecting
03. Imported Spyder 5.0.0.dev0
    [Python 3.8.0 64bits, Qt 5.12.6, PyQt5 5.12.3 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:05.2352
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
```

Though spyder starts and runs successfully, but I meet the msg as you can see as following:

Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
 
What's the problem, is this harm, how to eliminate it?

Regards

**Comment by ccordoba12** [comment] 2020-01-17 13:39
Duplicate of #11227

**Closed by ccordoba12** 2020-01-17 13:39 UTC

**Comment by ccordoba12** [comment] 2020-01-17 13:40
The problem is harmless, so don't worry about it.

**Comment by hongyi-zhao** [comment] 2020-01-17 14:34
Thanks.
