### ISSUE TITLE
Remember collapses

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11504] opened 2020-02-09 01:01 UTC
It'd be nice for Spyder to remember which blocks of code I've collapsed when saving code, sparing repetitive manual work upon reopening a file. (Feature request)

**Comment by ccordoba12** [comment] 2020-02-09 15:36
Nice suggestion! We'll try to implement it in a future version.

**Comment by bcolsen** [comment] 2020-02-10 23:31
Saving code folding state is mentioned in #8090(code folding unofficial epic). I'm closing as duplicate of #8090.

**Comment by bcolsen** [comment] 2020-02-10 23:34
Sorry didn't see that it was labelled 4.2. @ccordoba12 can close if you want.

**Comment by ccordoba12** [comment] 2020-02-11 02:37
Sorry, I didn't know this was already mentioned on issue #8090.

**Closed by ccordoba12** 2020-02-11 02:37 UTC
Labels: component:Editor, type:Enhancement
