### ISSUE TITLE
Completion Error on Numpy module

### ISSUE THREAD

**Issue by RickPattonAlicat** [spyder-ide/spyder#12413] opened 2020-04-20 21:58 UTC
### What steps will reproduce the problem?

import numpy as np
begin typing "np.linspace("
Error occurred when typing the "("

### Traceback
```python-traceback
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 94, in comm_channel_manager
    yield
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 132, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder_kernels\comms\commbase.py", line 415, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 142, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'f2e87047010b41af82445a5a12913329': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x000001EE4444ACA8>>), '52c545f0c6c14b00b9bc0edee33fad44': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x000001EE4444ACA8>>), 'a3117cdc12de4155806aa98ee5487cfd': (True, None), 'fe0fe73dedb642e4834c3d83d761d43a': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\control.py", line 58, in keyPressEvent
    self._key_paren_left(text)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\control.py", line 50, in _key_paren_left
    self.show_object_info(last_obj)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\widgets\mixins.py", line 1435, in show_object_info
    self.help.set_object_text(text, ignore_unknown=False)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\help\plugin.py", line 518, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\help\plugin.py", line 697, in show_help
    if not shell.is_defined(obj_text):
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\help.py", line 135, in is_defined
    ).is_defined(objtxt, force_import=force_import)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 132, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\rpatton\Anaconda\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 98, in comm_channel_manager
    self.kernel_client.shell_channel)
KeyError: '85ff55ba835111ea9d493417ebc271d4'
Traceback (most recent call last):
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 94, in comm_channel_manager
    yield
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 132, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder_kernels\comms\commbase.py", line 415, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 142, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'f2e87047010b41af82445a5a12913329': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x000001EE4444ACA8>>), '52c545f0c6c14b00b9bc0edee33fad44': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x000001EE4444ACA8>>), 'a3117cdc12de4155806aa98ee5487cfd': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\control.py", line 58, in keyPressEvent
    self._key_paren_left(text)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\control.py", line 50, in _key_paren_left
    self.show_object_info(last_obj)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\widgets\mixins.py", line 1435, in show_object_info
    self.help.set_object_text(text, ignore_unknown=False)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\help\plugin.py", line 518, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\help\plugin.py", line 697, in show_help
    if not shell.is_defined(obj_text):
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\help.py", line 135, in is_defined
    ).is_defined(objtxt, force_import=force_import)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 132, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\rpatton\Anaconda\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\rpatton\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 98, in comm_channel_manager
    self.kernel_client.shell_channel)
KeyError: '85ff55ba835111ea9d493417ebc271d4'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-04-20 21:59
Duplicate of #11889

**Closed by ccordoba12** 2020-04-20 21:59 UTC

**Comment by ccordoba12** [comment] 2020-04-20 22:00
Please open a new console. That should fix this problem for now.

**Comment by RickPattonAlicat** [comment] 2020-04-20 22:08
Carlos, opening a new console fixed the issue. Thank you. I noticed you had trouble reproducing the prior issue. I forgot some steps in my reproducibility…

With the console already loaded I discovered numpy wasn’t installed (I recently upgraded to spyder4). In a separate Windows command prompt, I did “pip install numpy”. I also re-installed pandas and scipy prior to my error occurring. After installing, then importing numpy, it appears the error occurred when Spyder tried to load the function description for np.linspace

Hope this helps.

**Comment by ccordoba12** [comment] 2020-04-20 22:17
> In a separate Windows command prompt, I did “pip install numpy”

I'm afraid to say it but most probably you broke your Anaconda installation by doing that. That's because pip and conda packages are binary incompatible, you always need to use conda to install packages, unless that's not possible.
