### ISSUE TITLE
pandas with numpy.nan in dictionary causes runtime error

### ISSUE THREAD

**Issue by kitjosh1050** [spyder-ide/spyder#3008] opened 2016-02-26 00:46 UTC
## Description of your problem

**What steps will reproduce the problem?**

I receive a runtime error when typing a parenthesis in the IPython Console **after** I put a pandas dataframe with a numpy.nan in a dictionary. 

1. Now, this wasn't what I did originally to run into this, the simplest code which causes the behaviour is:

```python
import pandas as pd
import numpy as np
df = pd.DataFrame({"a":[1,2]})
df.iloc[0,0] = np.nan
d={}
d["df"] = df
```

2. If I type anything with a parenthesis into the IPython Console. I get this:
```python
C:\Users\Josh.Josh-PC\Anaconda3\lib\site-packages\pandas\core\format.py:2087: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e8).any()
C:\Users\Josh.Josh-PC\Anaconda3\lib\site-packages\pandas\core\format.py:2088: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) &
C:\Users\Josh.Josh-PC\Anaconda3\lib\site-packages\pandas\core\format.py:2089: RuntimeWarning: invalid value encountered in greater
  (abs_vals > 0)).any()
```

**Please provide any additional information below**
I tried the suggested option of installing and re-installing pandas with conda from [here](https://github.com/pydata/pandas/issues/9950) but to no avail.

See also:
[RuntimeWarning: with pandas.dataframes](https://github.com/spyder-ide/spyder/issues/2991])

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 3.5.1 64bit
* Operating system: Windows 7 64bit

## Dependencies
IPython >=1.0      :  4.0.3 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment] 2016-02-29 17:43
I think this is a duplicate of issue #2991, so I'm closing it.

**Closed by ccordoba12** 2016-02-29 17:43 UTC
