### ISSUE TITLE
Spyder crash on python 3.5.2 and windows 7

### ISSUE THREAD

**Issue by blackshirt** [spyder-ide/spyder#3999] opened 2017-01-19 03:18 UTC
## Description of your problem
 I can't start spyder through command line, spyder, spyder --reset, spyder --show-console or even from Anaconda start menu. Its brings me to pop up crash windows with message: python has stopped working, 

**What steps will reproduce the problem?**

1.  start spyder through command line
2. start spyder through anaconda start menu
3. even jupyter qtconsole bring me to error 

**What is the expected output? What do you see instead?**
I hope spyder run normally, 

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
spyder = 3.1.0
* Python Version:
Python 3.5.2 | Anaconda custom (32 bit)
* Operating system:
Windows 7 Ultimate OS

##conda info 

C:\Users\****>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : E:\Progfiles\Miniconda3  (writable)
    default environment : E:\Progfiles\Miniconda3
       envs directories : E:\Progfiles\Miniconda3\envs
          package cache : E:\Progfiles\Miniconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Windows/7 Windows/6.1.7600

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-01-19 04:26
Can you start qtconsole by running this command

    jupyter qtconsole

?

**Comment by blackshirt** [comment] 2017-01-19 06:31
i can't start it, here the traceback

 jupyter qtconsole
Traceback (most recent call last):
  File "E:\Progfiles\Miniconda3\Scripts\jupyter-qtconsole-script.py", line 1, in <module>
    from qtconsole.qtconsoleapp import main
  File "E:\Progfiles\Miniconda3\lib\site-packages\qtconsole\qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "E:\Progfiles\Miniconda3\lib\site-packages\qtconsole\qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "E:\Progfiles\Miniconda3\lib\site-packages\qtconsole\qt_loaders.py", line 290, in load_qt
    result = loaders[api]()
  File "E:\Progfiles\Miniconda3\lib\site-packages\qtconsole\qt_loaders.py", line 192, in import_pyqt4
    from PyQt4 import QtGui, QtCore, QtSvg
ImportError: DLL load failed: The specified procedure could not be found

any help appreciate .. thanks before

**Comment by june8070** [comment] 2017-01-20 08:50
i have face the same problem...
try to download python x,y
its seem to work better and doesn't give atleast traceback  error
but spyder still get crash when we restart it ... but it download and install successfully ......

**Comment by june8070** [comment] 2017-01-20 08:55
https://python-xy.github.io/
download it from here

**Comment by blackshirt** [comment] 2017-01-23 00:25
i think the problem was related to Qt ...but i dont know exactly ...

**Comment by ccordoba12** [comment] 2017-02-02 08:56
I'm closing this bug as a duplicate of issue #3939 because they look seem very similar.

**Closed by ccordoba12** 2017-02-02 08:56 UTC
Labels: resolution:Duplicate
