### ISSUE TITLE
Couldn't Close the Panel , Opened by Vertical Split

### ISSUE THREAD

**Issue by atulsingh7890** [spyder-ide/spyder#5113] opened 2017-09-02 17:53 UTC
## Description

**What steps will reproduce the problem?**

1. Open some files
2. Vertical Split to have another Editor below that
3. Reduce the Size of Help and Console Panel to the right, 
4. Now Try to close the Extra Edtior Panel , When you click the Gear Icon, a pop dialog appears with exception and a dialog for submitting this to GitHub. 

WORKAROUND : After restarting Spyder , this doesnt occur. So i could succesfully close that Panel.

**What is the expected output? What do you see instead?**
I think gear icon should show the menu to have Options which are present in main Menu Item.

**Please provide any additional information below**

  File "/Users/atsingh/anaconda/lib/python2.7/site-packages/spyder/widgets/editor.py", line 1236, in __setup_menu
    add_actions(self.menu, list(actions)+self.__get_split_actions())
  File "/Users/atsingh/anaconda/lib/python2.7/site-packages/spyder/utils/qthelpers.py", line 311, in add_actions
    target.addAction(action)
RuntimeError: wrapped C/C++ object of type QAction has been deleted

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.0.1 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by dalthviz** [comment] 2017-09-02 18:17
I think this is a duplicate of #5074 so it will be fixed for Spyder 3.2.2 (to be released soon).

**Closed by dalthviz** 2017-09-02 18:17 UTC
