### ISSUE TITLE
Spyder was unable to retrieve the value of this variable from the console

### ISSUE THREAD

**Issue by buster47** [spyder-ide/spyder#13582] opened 2020-08-20 08:57 UTC
### What steps will reproduce the problem?

Error is shown when trying to show or copy variable retrieved from docplex optimization. Sample problem shown below. Plus: loading icon in variable explorer is visible all the time. 

```
from docplex.mp.model import Model

mdl = Model('Test')

x1 = mdl.continuous_var(lb=0)
x2 = mdl.continuous_var(lb=0)

mdl.add_constraint(x1+x2>=10)

mdl.minimize(2*x1+x2)

solution = mdl.solve()

print(solution)
```
### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1038, in copy
    obj = self.delegate.get_value(idx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1373, in get_value
    return self.parent().get_value(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1431, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 100, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 152, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 488, in _sync_error
    error_wrapper.raise_error()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_value:

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 315, in _comm_message
    encoding='latin-1')

  File "C:\ProgramData\Anaconda3\lib\site-packages\docplex\mp\linear.py", line 100, in __hash__
    return self._index

AttributeError: _index

```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.6
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2020-08-20 17:27
@impact27, I think we should catch errors like this one when getting a value and simply pass on it. What do you think?

**Comment by impact27** [comment] 2020-08-21 06:51
This looks like an error in the "docplex" package. I am not sure about passing on them silently though. In this situation, I would expect a traceback in the console. What do you think?

**Comment by ccordoba12** [comment] 2020-09-03 15:21
Closing as a duplicate of #13623.

**Comment by ccordoba12** [comment] 2020-09-03 15:22
@buster47, we'll try to fix this problem in our next release.

**Closed by ccordoba12** 2020-09-03 15:21 UTC
Labels: status:Awaiting Followup
