### ISSUE TITLE
Autocomplete does not work properly for some libraries

### ISSUE THREAD

**Issue by ghost** [spyder-ide/spyder#4859] opened 2017-07-30 07:28 UTC
## Description of your problem

Autocomplete does not work properly for some libraries. So if we "import numpy", we can later use "numpy.*autocomplete*". But if we deal with cv2, things are different.

Example bellow

**What steps will reproduce the problem?**

1.1.  import cv2
1.2. cv2.*autocomplete suggest cv2*
1.3. cv2.cv2.*no autocomplete*

So does not work.

But:
2.1.  import cv2 as cv2
2.2. cv2.*autocomplete suggest cv2*
2.3. cv2.cv2.*autocomplete for cv2*

So this one gets me there, but with an extra step. And I cannot run like that, I need to remove extra cv2

**What is the expected output? What do you see instead?**

In a case of "2.3" I can get autocomplete that I need, but I need to remember to delete this extra cv2. Basically, I want to get cv2.*autocomplete for cv2*

## Additional information

This issue only happens in the editor. Console works fine.

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.5.3. 64bit
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-08-09 13:15
@andfoy, can you reproduce this on Windows?

**Comment by andfoy** [comment] 2017-08-09 13:26
This is an actual error related to the packaging of OpenCV, while jedi and other autocompletion engines make suggestions based on the contents of plain python sources, OpenCV is a compiled library packaged on a pyd file that cannot be analysed, unfortunately. We're not the only editor that presents this issue: 

https://stackoverflow.com/questions/18672087/autocomplete-for-opencv-python-in-windows-not-working

https://stackoverflow.com/questions/43093400/code-completion-is-not-working-for-opencv-and-python

https://github.com/autocomplete-python/autocomplete-python/issues/268

https://stackoverflow.com/questions/43231766/visual-studio-weird-behavior-of-auto-complete-for-opencv-python

**Comment by yaceben** [comment] 2017-08-12 22:29
Does not work for any libraries for me, e.g. pattern, numpy, nltk, etc.

```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
numpy >=1.7       :  1.11.0 (OK)
pandas >=0.13.1   :  0.18.0 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.0 (OK)
```

**Comment by andfoy** [comment] 2017-08-12 22:38
@yaceben I think your error is unrelated to this issue (Precompiled library autocompletion). Please open a new issue with this information

**Comment by yaceben** [comment] 2017-08-12 23:11
@andfoy Alright, will do. Thanks

**Comment by andfoy** [comment] 2017-08-14 13:49
@ccordoba, I think we should close this one

**Comment by bcolsen** [comment] 2017-12-19 06:17
I can't reproduce this using latest anaconda and spyder master.

![cv complete](https://user-images.githubusercontent.com/10513354/34143313-69754a24-e449-11e7-9ac8-d17633e66dc5.gif)

**Comment by ccordoba12** [comment] 2019-11-06 21:12
It seems this is solved now, as @MadsDyrmann pointed out.

**Closed by ccordoba12** 2019-11-06 21:12 UTC
Labels: component:Editor, type:Enhancement
