### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by dsankar** [spyder-ide/spyder#7119] opened 2018-05-13 15:25 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
```python-traceback
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
```

**Comment by CAM-Gerlach** [comment] 2018-05-13 16:30
Thanks for reporting. This is a duplicate of #6335 and is a problem with your OS and Python itself, not Spyder. To fix, please run ``conda update spyder python python.app`` from the Terminal.

**Closed by CAM-Gerlach** 2018-05-13 16:30 UTC
