### ISSUE TITLE
Spyder freezes randomly and frequently

### ISSUE THREAD

**Issue by BOZHENG001** [spyder-ide/spyder#16841] opened 2021-11-17 08:49 UTC
## Problem Description
Spyder freezes randomly and frequently.

### What steps reproduce the problem?
Spyder freezes randomly and frequently. It happens multiple times every day when I use Spyder to run my code. It happens randomly when I run my code, sometimes after I run a script several times (e.g. 5 - 10 times), sometimes even the first time I run a script.

### What is the expected output? What do you see instead?
What I see is the IPython console freezes at the step running the file, for example, "runfile('E:/PyCharm/PROJECT/test01.py', wdir='E:/PyCharm/PROJECT')". It does not give me any results I expect, and I am not able to stop the process by "Ctrl + c" or clicking the red square "stop" button. The only way is to restart the kernel.

This issue has been happening to me for a long time since Spyder version 3. or 4.. What I have tried is to keep my Anaconda up to date, so that my Spyder from Anaconda is also updated, but it does not help at all. I have also tried to install and use the newest stand-alone Spyder, but it shows the same issue. Some other methods/suggestions online have been tested also, but they do not help much, such as choosing "Execute in a dedicated console" instead of "Execute in current console".

I consider there can be something wrong or bugs within Spyder, or maybe my setting issues. Could anyone help me here with this issue?

## Versions
* Spyder version: 5.0.5
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by dalthviz** [comment] 2021-11-17 16:06
Hi @BOZHENG001 thank you for the feedback. Is there any possibility that you can share with us some example code that triggers these kind of errors for you?

Without a way to reproduce this from our side is kind of difficult to give you some advice, sorry :/

Let us know!

**Comment by BOZHENG001** [comment] 2021-11-17 16:41
[test45.zip](https://github.com/spyder-ide/spyder/files/7556336/test45.zip)
@dalthviz Thanks for your fast and patient reply. In the attachment, you can find an example code. I just tested this little script, and after running it five times, my Spyder froze. To be honest, I do not think it is an issue with the code since it is just a script with eight lines of code inside. Thanks for your help in advance!

**Comment by dalthviz** [comment] 2021-11-17 17:28
@BOZHENG001 after checking the code indeed I was able to run it mutiple times without any issue. Maybe this could be related with the matplotlib version you are using? Could you run `conda list` from an Anaconda prompt and put the output here? 

Also, what graphics backend to do you have selected in the preferences (`Tools > Preferences > IPython Console> Graphics > Graphics backend`)? and how are you running the script?

Maybe as you say could be something regarding settings and in that case you can run from an Anaconda prompt `spyder --reset` to reset your preferences and check if that helps

**Comment by BOZHENG001** [comment] 2021-11-17 20:15
@dalthviz Please see the output of `conda list` here (I only put matplotlib here, if you need to see other packages, please do not hesitate to let me know):
`matplotlib                3.4.2                    pypi_0    pypi`
`matplotlib-base           3.4.3            py38h49ac443_0`
`matplotlib-inline         0.1.2              pyhd3eb1b0_2`

As for the graphics backend, please check it here. Actually, I have also tried to change this configuration to other options, such as `Inline` and `Tkinter`, but I still meet the same issue. Normally I just run the script by pressing the hotkey `F5`, and I have a general setting as `Remove all variables before execution`
![image](https://user-images.githubusercontent.com/50182201/142274354-6a553072-7986-43d9-877d-6e5d12c9ad3d.png)

The reset has been tried, unfortunately it does not help......

**Comment by dalthviz** [comment] 2021-11-18 17:40
Thanks for the new info @BOZHENG001 , seems like you installed matplotlib using pip instead of conda? Could you try to uninstall matplotlib and reinstall it? Normally mixing packages (pip vs. conda) can cause issues. For more info on that you can check our documentation: https://docs.spyder-ide.org/current/faq.html?highlight=pip#using-install-packages

Let us know if something of the above helps

**Comment by ccordoba12** [comment] 2021-11-19 22:05
@BOZHENG001, when are you seeing the freezes? I mean, does that happen when you're typing code in the editor? Or do you refer to something else?

**Comment by BOZHENG001** [comment] 2021-11-20 08:35
@dalthviz Sorry for my late reply. I used command `conda install matplotlib --force-reinstall` to reinstall matplotlib, and please see the matplotlib version below:
`matplotlib                3.4.2                    pypi_0    pypi`
`matplotlib-base           3.4.3            py38h49ac443_0`  
`matplotlib-inline         0.1.2              pyhd3eb1b0_2`

I have also tried the command `conda install matplotlib=x.x.x` to change between different versions of matplotlib, but it did not help. By the way, the command `conda update --all` now allows me to update Spyder to version 5.1.5, and I have done so, but the issue is still there......

**Comment by BOZHENG001** [comment] 2021-11-20 08:40
@ccordoba12 Thanks for your questions. Spyder does not freeze when I type code in the editor. It only freezes when I run scripts (normally I use the hotkey `F5`.). Sometimes it freezes after I run a script several times (around 5 - 10 times), sometimes even the first time I run a script, it freezes.

**Comment by ccordoba12** [comment] 2021-11-20 18:27
Please change your graphics to Inline and try again. That could help.

**Comment by BOZHENG001** [comment] 2021-11-21 18:37
@ccordoba12 Thanks for your suggestion. After updating Spyder 5.1.5, I tried the `Inline` backend again, and now it seems to work properly (No freezing anymore after running the script even 60 times.). But I am not able to save the figures as `.svg` files, even after changing the setting `Preferences > IPython console > Graphics > Inline backend > Format` into `SVG`. My work prefers vector pictures like in `.svg` format. I do not mind using `Inline` backend, but how should I save the figures into `.svg` format?

There seem to be issues with other options like `Automatic`, `Qt5`, `Qt4`, and `Tkinter`. When using those options, the Spyder freezes frequently (I did not test much, but during my limited tests, they all froze the first time I ran the script.). So maybe the freezing issue is from these options?

**Comment by ccordoba12** [comment] 2021-11-22 03:11
> After updating Spyder 5.1.5, I tried the Inline backend again, and now it seems to work properly

Ok, that's (sort of) good news.

> But I am not able to save the figures as .svg files, even after changing the setting

How are you trying to save them?

> There seem to be issues with other options like Automatic, Qt5, Qt4, and Tkinter

Could post here a simple example that shows that behavior? That way we could try to reproduce it in our side.

**Comment by BOZHENG001** [comment] 2021-11-22 08:36
@ccordoba12 Normally I save figures by clicking `Save plot as... (Ctrl+S)` instead of using some code, and that gives me multiple choices of figure formats, such as `.svg`, `.png`, `.pdf`. Yesterday I changed Spyder settings `Graphics backend` to `Inline`, and `Inline backend > Format` to `SVG`, but by clicking `Save plot as... (Ctrl+S)`, there was only one option for me, which was `.png`. Please see below:
![image](https://user-images.githubusercontent.com/50182201/142824796-8f282934-cb2c-4a70-95b9-43bf03296386.png)

However, today I restarted Spyder, and I could indeed see two options now, which are `.png` and `.svg`. So I suppose that there is a need of restarting Spyder for that setting change. Not nitpicking, but maybe can be future work for Spyder to specify if that setting change needs a restart. Another question might be if it is possible to have more options in the Inline `Save plot as... (Ctrl+S)`? Such as `.pdf` and all the other options shown in other modes like `Automatic` when saving figures?

For the issues with other options like `Qt4`, please see below:
![image](https://user-images.githubusercontent.com/50182201/142826084-348237f5-93f6-4f01-a02b-be25d7fc72f5.png)
This issue is solved after restarting the kernel, but I still face the freezing issue when I try to run some scripts.

For `Tkinter`, I meet errors all the time, please see below:
![image](https://user-images.githubusercontent.com/50182201/142827295-166ee05a-d1f7-4f05-8a48-adece2fc5492.png)
When I try to change `Tkinter` to other options, such as `Inline` and `Automatic`, my IPython console shows `Connecting to kernel` all the time, and if I try to change it again, Spyder shows me the `Issue reporter` window:
![image](https://user-images.githubusercontent.com/50182201/142827841-1b6e1fe9-38e0-4207-b29e-b8b641a9d0bf.png)

I would suppose there can be some errors here from Spyder? Or maybe still just my personal issues......

**Comment by ccordoba12** [comment] 2021-12-01 02:34
> Not nitpicking, but maybe can be future work for Spyder to specify if that setting change needs a restart

We inform that a restart is necessary when changing options for the IPython console, but it seems we missed to do that when modifying the Inline backend format. @dalthviz, could you open an issue about it so we don't forget to address it in the future?

> Another question might be if it is possible to have more options in the Inline Save plot as... (Ctrl+S)? Such as .pdf and all the other options shown in other modes like Automatic when saving figures?

I'm afraid that's not possible because inline figures are static and generated in a single format.

> When I try to change Tkinter to other options, such as Inline and Automatic, my IPython console shows Connecting to kernel all the time, and if I try to change it again, Spyder shows me the Issue reporter window

Could you press the `Show details` button in that window and paste its contents here? That would be really helpful to understand what's happening with the other backends. Thanks!

**Comment by BOZHENG001** [comment] 2021-12-01 09:08
@ccordoba12 Please see the details below:

```
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "E:\Anaconda3\lib\site-packages\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 452, in apply_plugin_settings
    client_backend_not_inline = [
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 453, in <listcomp>
    client.shellwidget.get_matplotlib_backend() != inline_backend
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 351, in get_matplotlib_backend
    return self.call_kernel(
  File "E:\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    raise CommError("The comm is not connected.")
spyder_kernels.comms.commbase.CommError: The comm is not connected.
```

**Comment by ccordoba12** [comment] 2021-12-01 16:54
> Please see the details below

Thanks! This problem should be fixed in our latest version (5.2.0). Please install it from conda-forge by closing Spyder, opening Spyder and running the following commands:

    conda create -n spyder-env -c conda-forge spyder python=3.8
    conda activate spyder
    spyder

Let us know if that works for you. I think the Tkinter backend could still give you problems, but at least Automatic should work.

**Comment by BOZHENG001** [comment] 2021-12-02 11:16
@ccordoba12 Thanks for your suggestion, but I am afraid that I cannot test it now.

Today I updated `matplotlib` package to `version 3.5.0` through `conda update anaconda`, `conda update conda`, and `conda update --all`. After that, I started to have some issues with using matplotlib (for details please check here: [https://github.com/matplotlib/matplotlib/issues/21842](url)). I don't know if you are facing same/similar issues or not, maybe my personal issue again? I don't think it is because of Spyder since I also tested PyCharm and I can still see it there.

Anyway, once I can test your suggestion, I would let you know the result/feedback.

**Comment by BOZHENG001** [comment] 2021-12-02 12:39
@ccordoba12 OK, seems they closed my post already. In their description, it seems I should mention the issue to Spyder and PyCharm. So should we discuss it here in this post or should I open another post for it?

**Comment by BOZHENG001** [comment] 2021-12-03 10:04
@ccordoba12 By your suggested commands, I created a new environment for Spyder, and `Automatic` seems to work properly there.

**Comment by ccordoba12** [comment] 2021-12-03 14:36
Ok, that's really good news! I'm going to close this issue then because I consider it solved now.

**Closed by ccordoba12** 2021-12-03 14:36 UTC
Labels: status:Awaiting Followup

**Comment by clemdumont** [comment] 2023-11-07 16:11
@ccordoba12 I encounter the same problem as described by @BOZHENG001.

When running a complete script, Spyder randomly freezes. A way to solve this is to open and close Spyder several times (it eventually accepts to run my code after 4-5 openings/closings of Spyder).

A way to solve this problem is to change in the settings from:
`Tools > Preferences > IPython Console> Graphics > Graphics backend > Automatic`
to 
`Tools > Preferences > IPython Console> Graphics > Graphics backend > Inline`

However, this presents 2 disadvantages for me:
1. I want to be able to visualize my graphs in a dynamic mode (zoom in and out, scroll to the data points);
2. I want to save my figures in .png format which does not work in the Inline mode.

Note that the problem mostly happens when I run the whole script by pressing `F5` and not when I run section by section (`CTRL+ENTER`) or by selected parts (`F9`).

Is there a way to solve this problem without losing the advantages offered by the `Automatic` mode?

FYI, here are the versions I am using:

- Spyder version: 5.4.3
- Python version: 3.8.16
- Operating System name/version: Windows 10

**Comment by BOZHENG001** [comment] 2023-11-17 07:56
@clemdumont Late reply, please excuse me. Not sure if the issue has been solved for you, but it was exactly the issue I met before.

Your message triggered me to double-check with my own Spyder (version 5.4.3 as well). I tried with two of my old codes, one for plotting and the other for usbhub controlling. The plotting code did not lead to Spyder freezing, even after running it 40 or 50 times. However, the usbhub controlling code indeed ended up with frozen Spyder. More specifically, my usbhub controlling code led to the IPython console freezing instead of the whole Spyder. I can still click "interrupt kernel" button, but it will not do the job. What I can do is to close the frozen console, and start a new console. That helped me to rerun the code.

If your issue has not been solved, maybe you can start a new post/request for it. I would also be glad to be involved into the post to see what really happened and if Spyder will fix in its next version.
