### ISSUE TITLE
Cant view array

### ISSUE THREAD

**Issue by MeharYildirim** [spyder-ide/spyder#8735] opened 2019-02-08 23:08 UTC
### What steps will reproduce the problem?

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset_train = pd.read_csv('Google_Stock_Price_Train.csv')
training_set = dataset_train.iloc[:, 1:2].values

Csv can be found here:
http://www.superdatascience.com/wp-content/uploads/2017/03/Recurrent_Neural_Networks-1.zip

I don't use environments. I use straight pip. Spyder pip installed.

pip list:
absl-py                  0.7.0                                                                                          alabaster                0.7.12                                                                                         astor                    0.7.1                                                                                          astroid                  2.1.0                                                                                          Babel                    2.6.0                                                                                          backcall                 0.1.0                                                                                          bleach                   3.1.0                                                                                          certifi                  2018.11.29                                                                                     chardet                  3.0.4                                                                                          cloudpickle              0.7.0                                                                                          colorama                 0.4.1                                                                                          cycler                   0.10.0                                                                                         decorator                4.3.2                                                                                          defusedxml               0.5.0                                                                                          docutils                 0.14                                                                                           entrypoints              0.3                                                                                            gast                     0.2.2                                                                                          grpcio                   1.18.0                                                                                         h5py                     2.9.0                                                                                          idna                     2.8                                                                                            imagesize                1.1.0                                                                                          ipykernel                5.1.0                                                                                          ipython                  7.2.0                                                                                          ipython-genutils         0.2.0                                                                                          isort                    4.3.4                                                                                          jedi                     0.13.2                                                                                         Jinja2                   2.10                                                                                           jsonschema               2.6.0                                                                                          jupyter-client           5.2.4                                                                                          jupyter-core             4.4.0                                                                                          Keras                    2.2.4                                                                                          Keras-Applications       1.0.7                                                                                          Keras-Preprocessing      1.0.8                                                                                          keyring                  17.1.1                                                                                         kiwisolver               1.0.1                                                                                          lazy-object-proxy        1.3.1                                                                                          Markdown                 3.0.1                                                                                          MarkupSafe               1.1.0                                                                                          matplotlib               3.0.2                                                                                          mccabe                   0.6.1                                                                                          mistune                  0.8.4                                                                                          nbconvert                5.4.0                                                                                          nbformat                 4.4.0                                                                                          numpy                    1.16.1                                                                                         numpydoc                 0.8.0                                                                                          opencv-python            4.0.0.21                                                                                       packaging                19.0                                                                                           pandas                   0.24.1                                                                                         pandocfilters            1.4.2                                                                                          parso                    0.3.2                                                                                          pickleshare              0.7.5                                                                                          Pillow                   5.4.1                                                                                          pip                      19.0.1                                                                                         prompt-toolkit           2.0.8                                                                                          protobuf                 3.6.1                                                                                          psutil                   5.5.0                                                                                          pycodestyle              2.5.0                                                                                          pyflakes                 2.1.0                                                                                          Pygments                 2.3.1                                                                                          pylint                   2.2.2                                                                                          pyparsing                2.3.1                                                                                          PyQt5                    5.9.2                                                                                          python-dateutil          2.8.0                                                                                          pytz                     2018.9                                                                                         pywin32-ctypes           0.2.0                                                                                          PyYAML                   3.13                                                                                           pyzmq                    17.1.2                                                                                         QtAwesome                0.5.6                                                                                          qtconsole                4.4.3                                                                                          QtPy                     1.6.0                                                                                          requests                 2.21.0                                                                                         rope                     0.11.0                                                                                         scikit-learn             0.20.2                                                                                         scipy                    1.2.0                                                                                          setuptools               40.8.0                                                                                         sip                      4.19.8                                                                                         six                      1.12.0                                                                                         snowballstemmer          1.2.1                                                                                          Sphinx                   1.8.4                                                                                          sphinxcontrib-websupport 1.1.0                                                                                          spyder                   3.3.2                                                                                          spyder-kernels           0.4.1                                                                                          tensorboard              1.12.2                                                                                         tensorflow-gpu           1.12.0                                                                                         termcolor                1.1.0                                                                                          testpath                 0.4.2                                                                                          Theano                   1.0.4                                                                                          tornado                  5.1.1                                                                                          traitlets                4.3.2                                                                                          typed-ast                1.3.0                                                                                          urllib3                  1.24.1                                                                                         wcwidth                  0.1.7                                                                                          webencodings             0.5.1                                                                                          Werkzeug                 0.14.1                                                                                         wheel                    0.32.3                                                                                         wrapt                    1.11.1   

### Traceback
```python-traceback
  File "c:\users\artifexus\appdata\local\programs\python\python36\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "c:\users\artifexus\appdata\local\programs\python\python36\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.8
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.16.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-08 23:22
Duplicate of #8582. It'll be fixed in our next version (3.3.3)

**Closed by ccordoba12** 2019-02-08 23:22 UTC
