### ISSUE TITLE
error when setting python version 3.5

### ISSUE THREAD

**Issue by randidwiputra** [spyder-ide/spyder#6050] opened 2017-12-25 07:59 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/randi/.local/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 876, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "/home/randi/.local/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 922, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "/home/randi/.local/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "/home/randi/.local/lib/python2.7/site-packages/qtconsole/console_widget.py", line 632, in execute
    self._execute(source, hidden)
  File "/home/randi/.local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 2.7.13
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.3.0 (OK)
nbconvert >=4.0   :  5.3.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-25 18:59
Thanks for reporting. This issue is a duplicate of #5053 and is solved in Spyder 3.2.4; please update to fix it. Accordingly, this issue will be closed.

**Closed by CAM-Gerlach** 2017-12-25 18:59 UTC
