### ISSUE TITLE
Error installing Spyder from conda

### ISSUE THREAD

**Issue by jc-barreto** [spyder-ide/spyder#13229] opened 2020-07-08 22:46 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I try to install spyder from conda with the command conda install spyder I got an error.

### What steps reproduce the problem?

1. conda install Spyder
2. 
3. 

### What is the expected output? What do you see instead?

I hope to see successful installed, instead I got the error

### Paste Traceback/Error Below (if applicable)

```python-traceback

ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\ProgramData\Anaconda3\envs\SimPEG1401\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

```

## Versions

* Spyder version:  Not installed
* Python version: 3.8.3
* Qt version:  Not installed
* PyQt version: Pyqt5 5.12.3
* Operating System name/version: Windows 10 Pro - 64bits

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment] 2020-07-08 23:55
Hi @jc-barreto sorry to hear that, checking a little bit seems that this is a conda issue caused by a missing variable in the PATH when trying to install packages that depend on Qt, for example Spyder (you can see the issue [here](https://github.com/ContinuumIO/anaconda-issues/issues/10949)).

Following this you will need to setup your PATH env variable with the correct values as explained [here](https://stackoverflow.com/a/8143664). The missing executable (`chcp`) should be located at `C:\Windows\System32\chcp.com` so probably in your path the `%SystemRoot%\system32` string is missing.

I'm closing this since there is not much more that we can do, but let us now if the info above helps you :)

**Closed by dalthviz** 2020-07-08 23:55 UTC
Labels: resolution:NotSpyder
