### ISSUE TITLE
An error ocurred while starting the kernel Traceback (most recent call last): File "C:\Users\intkonsys\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "C:\Users\intkonsys\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\intkonsys\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 10, in  from spyder_kernels.console import start File "C:\Users\intkonsys\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 14, in  from distutils.version import LooseVersion File "C:\Users\intkonsys\Anaconda3\lib\distutils\version.py", line 93, in  class StrictVersion (Version): File "C:\Users\intkonsys\Anaconda3\lib\distutils\version.py", line 130, in StrictVersion version_re = re.compile(r'^(\d+) \. (\d+) (\. (\d+))? ([ab](\d+))?$', AttributeError: module 're' has no attribute 'compile'

### ISSUE THREAD

**Issue by Ashu-jun** [spyder-ide/spyder#8833] opened 2019-02-23 05:02 UTC
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\intkonsys\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\intkonsys\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\intkonsys\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 10, in 
from spyder_kernels.console import start
File "C:\Users\intkonsys\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 14, in 
from distutils.version import LooseVersion
File "C:\Users\intkonsys\Anaconda3\lib\distutils\version.py", line 93, in 
class StrictVersion (Version):
File "C:\Users\intkonsys\Anaconda3\lib\distutils\version.py", line 130, in StrictVersion
version_re = re.compile(r'^(\d+) \. (\d+) (\. (\d+))? ([ab](\d+))?$',
AttributeError: module 're' has no attribute 'compile'

**Comment by Ashu-jun** [comment] 2019-02-23 05:03
please someone tell how to solve this

**Comment by ccordoba12** [comment] 2019-02-23 07:40
Duplicate of #8832.

**Closed by ccordoba12** 2019-02-23 07:40 UTC

**Comment by ccordoba12** [comment] 2019-02-23 07:42
Please don't open the same bug several times. It's a waste of time for us.
