### ISSUE TITLE
Cannot update to version 5.5.4

### ISSUE THREAD

**Issue by Kiamehr5** [spyder-ide/spyder#21989] opened 2024-04-11 06:16 UTC
Hey how it going? 

I had a problem where Spyder would refuse to update. I have no idea why this is happening; heres what i did:

I have a prompt telling me that Spyder v5.5.4 has been released,
Its says "do you want to update now?",
I click "Yes",
Nothing happens, i closed, reseted, retried, nothing, 
Any feedback would be appreciated

> @ccordoba12 u might notice that my profile is similar to @GitKia1392 but sorry i got locked out by 2fa.

**Comment by ccordoba12** [comment] 2024-04-11 15:44
Hey @Kiamehr5, thanks for reporting. It seems this is a duplicate of issue #21905.

For now, the only workaround is to manually uninstall Spyder and then install 5.5.4 afterwards. Sorry for the inconvenience.

**Closed by ccordoba12** 2024-04-11 15:44 UTC

**Comment by Kiamehr5** [comment] 2024-04-11 23:36
Re-open it its not. that one it said it was finished but didn't actually update. Mines does the same but just doesn't do anything

**Comment by Kiamehr5** [comment] 2024-04-12 05:35
reopen it now.

**Comment by Kiamehr5** [comment] 2024-04-13 07:25
RESPOND BRO
