### ISSUE TITLE
Editor now just says 'Editor' instead of filename

### ISSUE THREAD

**Issue by luciansmith** [spyder-ide/spyder#4371] opened 2017-04-19 21:37 UTC
## Description of your problem
In Spyder 3.1.2, the editor window would have the full name of the active tab in the area above the tab list.  Now, in 3.1.3, it just says 'Editor'.  'Editor' is not useful information, as we already know it's an editor.  The full name of the file *was* useful information, especially when the filename was too long to fit on the tab.  If this behavior could be reverted, that'd be great.
## Versions and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.12
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-04-19 22:07
Thanks for reporting. This is a duplicate of issue #4259.

**Closed by ccordoba12** 2017-04-19 22:07 UTC
Labels: resolution:Duplicate
