### ISSUE TITLE
spyder

### ISSUE THREAD

**Issue by brighter23** [spyder-ide/spyder#6255] opened 2018-01-20 11:50 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 695, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 974, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 995, in connect_client_to_kernel
    stderr_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1384, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.

**Comment by CAM-Gerlach** [comment] 2018-01-20 21:49
Thanks for reporting. The error message above is incomplete; please paste the full thing from the error dialog or the internal console. From what we have, this seems like it could be a problem with your install in some fashion, or with your antivirus/firewall, and a possible duplicate of #5257 . Also, this issue has been reported by some when ``TensorFlow`` is installed. 

Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, providing as much specific detail as possible, and we'll try to help if we can. Presuming it occurs on launching, does it only happen when launching Spyder from the Anaconda navigator, the start menu shortcut, and/or directly from the command line (with `spyder`)? Is there anything new, modified or unusual with your installation or environment?  You can get the relevant version information with ``conda list`` from the Anaconda Prompt. Otherwise, your issue will have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by ccordoba12** [comment] 2018-01-28 21:03
Closing as duplicate of issue #6319.

**Closed by ccordoba12** 2018-01-28 21:03 UTC
Labels: resolution:Duplicate
