### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#9809] opened 2019-07-10 07:00 UTC
### What steps will reproduce the problem?

This error happens whenever I open spyder.........

### Traceback
```python-traceback
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pyls\python_ls.py", line 161, in m_initialize
    processId, _kwargs.get('capabilities', {}))
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pyls\config\config.py", line 53, in __init__
    entry_point.load()
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pkg_resources\__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pkg_resources\__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Miniconda\envs\py-dev\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'}}
```

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-10 08:34
@dhirschfeld, please update Jedi with

    conda update jedi

That should fix this error.

**Comment by dhirschfeld** [comment] 2019-07-10 12:17
Will give it a go & report back...

**Comment by ccordoba12** [comment] 2019-07-18 05:57
Duplicate of #9825.

**Closed by ccordoba12** 2019-07-18 05:57 UTC
Labels: status:Awaiting Followup
