### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by zdhughes5** [spyder-ide/spyder#10057] opened 2019-08-21 17:35 UTC
### What steps will reproduce the problem?

$ conda activate base
$ spyder

press tab for tab completion.

EDIT:
Seems intermittent and also occurs when the preview autocomplete pops-up.

Error report pop-up.

### Traceback
```python-traceback
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls/python_ls.py", line 293, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls/python_ls.py", line 214, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls/python_ls.py", line 130, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in __call__
    return outcome.get_result()
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/_tracing.py", line 78, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/pyls/plugins/jedi_completion.py", line 44, in pyls_completions
    definitions = document.jedi_script(position).completions()
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/jedi/api/completion.py", line 103, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),

RuntimeError: generator raised StopIterationWARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.1.6-1.el7.elrepo.x86_64

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.5.2 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-08-22 08:26
Please post a simple code example that generates this error. We need that to reproduce and fix this error in our side.

**Comment by zdhughes5** [comment] 2019-08-22 15:30
```
from PyQt5 import QtCore

class test(QtCore.QObject):

	def __init__(self, var1, var2):
		self.<ERROR POPUP>
```
After the error auto-complete/introspection stops working. Then, it seems to work again after several minutes for a while only to reoccur. Due to the intermittent nature I can't say for certain it is tied specifically to pyqt. I will update if it happens in just vanilla python.

**Comment by ccordoba12** [comment] 2019-08-23 12:17
This is a duplicate of #10009.

**Closed by ccordoba12** 2019-08-23 12:17 UTC
Labels: status:Awaiting Followup

**Comment by ccordoba12** [comment] 2019-08-25 10:52
Please run

    conda install -c spyder-ide jedi=0.14.1

to fix this.
