### ISSUE TITLE
Can't run Spyder with Ipython on Ubuntu 14.04 installed via pip

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#2626] opened 2015-08-18 16:17 UTC
Hi,
I am trying to get Spyder with Ipython working on Ubuntu 14.04 but have not succeeded.

I tried both methods from the installation documents, but I will focus on the pip installation here:

I ran the following commands:
`sudo apt-get install python-qt4 python-sphinx`
`sudo pip install spyder`

However I had two issues when running spyder.
1) Can't bring up an ipython console
2) Can't step through code, stepping just behaves as if I typed next into my console
I tried to illustrate both issues with my attached screen shot.
![screenshot from 2015-08-18 12 06 23](https://cloud.githubusercontent.com/assets/595948/9335373/9cf94236-45a1-11e5-8e02-d97ab0f12ba0.png)

Additionally the following error message is printed to my screen when I run `spyder` from the command line:
```
selah@selah-OptiPlex-9020:~$ spyder
/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
```

Also, maybe relevant... I cannot run `ipython qtconsole` successfully in my terminal.
```
selah@selah-OptiPlex-9020:~$ ipython qtconsole
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python2.7/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named qtconsole.qtconsoleapp
```

Thanks a lot for your time and for making Spyder in the first place.  I'm super excited to use it if I can get it working :D :D

**Comment by ccordoba12** [comment] 2015-08-18 16:57
Closing as duplicate of issue #2608. We're preparing a new stable release to fix this problem.

About the debugging issue: You need to press first the debugging button (i.e. the play and pause button) to enter debug mode. Then you could step through your code using the other buttons :-)

**Closed by ccordoba12** 2015-08-18 16:57 UTC
Labels: duplicate

**Comment by ccordoba12** [comment] 2015-08-18 16:59
Another thing you probably are not aware of: several IPython components were renamed to Jupyter, including qtconsole. To install it you need to run

    pip install qtconsole

and to start it you need to run

    jupyter qtconsole

**Comment by selahlynch** [comment] 2015-08-18 18:10
Thanks!  Sorry I missed the duplicate ticket.

**Comment by ccordoba12** [comment] 2015-08-19 00:27
@selahlynch, don't worry about it ;-)
