### ISSUE TITLE
Feature Change Request: Autocomplete believes almost everything is a function.

### ISSUE THREAD

**Issue by EnderWiggin14** [spyder-ide/spyder#15199] opened 2021-04-08 21:16 UTC
## Problem Description
Make autocomplete/completion more reliable in whether it adds parentheses after selecting the autocomplete option. There are many times when simply typing in a variable or function argument and selecting the completion option will concatenate a set of parentheses to the end as if the autocomplete believes nearly everything is a function. This is really annoying because, if there isn't a space between the end of the variable and the closing parentheses in a function definition, deleting the auto-inserted parentheses causes the closing parentheses of the actual functions to be deleted as well. This happens because after deleting the middle `)` from the currently existing `())` string leaves a pair of `()` which the automatic parentheses pairing routine sees as an associated pair and upon deleting the `(` ends up deleting the `)` as well which then requires retyping that character again.

There are a few rare occasions where it correctly doesn't insert `()`, but those occurrences seem to be random. I haven't figured out what causes the autocomplete feature to decide not to insert the `()`.

Maybe I'm not realizing a specific set of preferences to make it behave the way I think it should behave. I don't want to have to turn of autocomplete or the automatic parentheses placement feature because they are wonderful features when they work in a way that one would expect. I know that this "issue" hasn't always existed. I believe it showed up in one of the releases during 2020. I'm guessing it's the result of the two features interacting in a undesirable way because individually the features work properly. Autocomplete offers the correct autocomplete options, and the automatic parentheses properly inserts `)` when `(` is typed.

Note: I don't use kite because it was a pain to have it constantly looking up documentation. I'm sure that's a result incorrect configuring on my part.

### What steps reproduce the problem?

1. Open a new file.
2. Try typing something like `@staticmethod` but press enter to autocomplete.
3. You should see something like `@staticmethod()`. That's how it behaves for me at least.

## Versions

* Spyder version: 5.0.0
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  51.0.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.4 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by andfoy** [comment] 2021-04-09 19:54
Hi @EnderWiggin14, thanks for raising this issue, it might be caused by Jedi, the library that is used in the Python Language Server https://github.com/python-lsp/python-lsp-server, I think it would be best to move this issue there instead.

**Comment by ccordoba12** [comment] 2021-04-09 22:04
Closing because we can't solve this here. As @andfoy mentioned, please open an issue in `python-lsp-server` instead.

**Closed by ccordoba12** 2021-04-09 22:04 UTC
