### ISSUE TITLE
Spyder on macOS latest apparently never terminates shell process after closing main window

### ISSUE THREAD

**Issue by pitosalas** [spyder-ide/spyder#7001] opened 2018-04-21 21:49 UTC
Spyder is installed via MiniConda. It says everything is up to date. I launch it from a command line shell, with, simply,  "Spyder". If I immediately choose "Quit" the main window closes, but the process in the shell sticks around and has to be killed violently. I've followed the hints in the FAQ and this is not solved. Is this a known bug?

p.s. I see this when I run it but I think I saw somewhere that it is benign:
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```

**Comment by CAM-Gerlach** [comment] 2018-04-21 23:06
Thanks for reporting. I  was unable to reproduce this on Windows 8.1 with Qt 5.6 and Windows 10 with Qt 5.9, with Spyder installed in isolated Anaconda environments (similar to base miniconda) and launched from the command line (although I seemed to have recalled seeing it a couple times on the latter, I may have been mistaken as I couldn't reproduce it).

Can someone with a Mac test this? 

> p.s. I see this when I run it but I think I saw somewhere that it is benign:

You are correct.

**Comment by CAM-Gerlach** [comment] 2018-04-21 23:11
Also, some other things:

Please provide the exact versions of Spyder, Qt, PyQt, Python, and your OS that you are using, as is required by the issue template and listed in the troubleshooting guide. You can find these under Spyder > About or Help > About (not sure which one on Mac). Also, provide the dependency output copied from the About > Dependencies (or Spyder > Dependencies) window as also requested. Finally, if you look in Activity Monitor, which Spyder processies terminate when closing the window, and which do not?

**Comment by CAM-Gerlach** [comment] 2018-04-22 16:12
Okay, thanks. Note that in the future, it is much more concise for us to read, and possibly less work for you to just use the "Copy to clipboard" button indicated on the dependencies dialog and paste that directly, and copy down the four relevant versions from the About dialog into our provided template.

What about

> Finally, if you look in Activity Monitor, which Spyder processes terminate when closing the window, and which do not?

At least on Windows, Spyder normally launches at least six processes, for the main thread, one ipython console, and rope/jedi/fallback completion engines, so it would be important to note exactly what's getting hung up. Other than that, we're just waiting on someone else with a Mac to reproduce the issue, unless you want to take a crack at investigating it further yourself. You can try some of the more advanced troubleshooting methods mentioned in the Guide/FAQ to at least gather more information about what's going on, like enabling debug logging (``export SPYDER_DEBUG=3`` then launch ``spyder`` from the same Terminal window). Thanks.

**Comment by ccordoba12** [comment] 2018-04-23 14:10
@pitosalas, please open Terminal.app and run there

    conda update jupyter_client

and try again.

**Comment by pitosalas** [comment] 2018-04-24 00:37
I tried what you suggested. I rebooted for extra measure. But unfortunately the problem persists.

Attached is the console log.

 

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by CAM-Gerlach** [comment] 2018-04-24 00:44
@pitosalas There's nothing attached; you can't email attachments to github.

Also, yet again...

> What about
>> Finally, if you look in Activity Monitor, which Spyder processes terminate when closing the window, and which do not?

Try ``conda update qt pyqt tornado pyzmq ipykernel ipython python python.app`` for a good measure. Older versions of Qt/PyQt have a number of known issues with High Sierra, there are a few MacOS-related bugs due to Python itself, and there have been various issues reported when the latest versions of the console underpinnings aren't installed in concert.

**Comment by pitosalas** [comment] 2018-04-24 00:53
Sorry about the lack of the image. But anyway, I spoke too soon... Spyder did in the end exit, it was just not immediately. I think your first fix did it. 

Do you have a use for the console log? Here it is.
<img width="1425" alt="screen shot 2018-04-23 at 8 32 09 pm" src="https://user-images.githubusercontent.com/44681/39160261-458f47e8-4738-11e8-8fc4-6e7892f880fb.png">

If you want me to do the additional steps above I am glad to do so.

Spyder is a really nice product for me. I've tried each of the alternatives and I've come back to Spyder.

**Comment by CAM-Gerlach** [comment] 2018-04-24 01:06
> Spyder did in the end exit, it was just not immediately.

Yeah, it can take anywhere from a second or two to ten+ seconds in my experience, depending on the version, how it was installed, the performance of your machine, etc.

> I think your first fix did it.

Which would that be?

> Do you have a use for the console log? Here it is.

Oh, I thought you meant the log from Spyder, haha. In that case, not really...it just shows you updated what Carlos asked you to.

> If you want me to do the additional steps above I am glad to do so.

No need; from what you've said everything is behaving as expected.

> Spyder is a really nice product for me. I've tried each of the alternatives and I've come back to Spyder.

Thanks! We really appreciate your support, particularly given we are now relying on our users and donations for funding after our institutional support ended. Glad you like it!

**Closed by CAM-Gerlach** 2018-04-24 01:06 UTC
Labels: OS:MacOS, component:Main Window, status:Awaiting Followup
