### ISSUE TITLE
AttributeError when saving a file in Spyder 4

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#8268] opened 2018-11-19 18:47 UTC
### What steps will reproduce the problem?

I was saving a file called "lines.py". I don't know what happened.

### Traceback
```python-traceback
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/plugin.py", line 1562, in file_renamed_in_data_in_editorstack
    editorstack.rename_in_data(original_filename, filename)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/editor.py", line 1270, in rename_in_data
    finfo.editor.oe_proxy, finfo.filename)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 691, in file_renamed
    self.treewidget.file_renamed(editor, new_filename)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 297, in file_renamed
    editor_id = editor.get_id()
AttributeError: 'NoneType' object has no attribute 'get_id'
```

## Versions

* Spyder version: 4.0.0.dev0 ab11ce1c1
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
pyls >=0.19.0     :  0.21.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by impact27** [comment] 2018-11-19 18:48
Not related to the file name

**Comment by CAM-Gerlach** [comment] 2018-11-19 19:00
@impact27 Thanks. Does this happen every time you try to save a file? If not, are there specific actions needed to repro it? Can you repro it in safe mode (``spyder --safe-mode``)?

**Comment by jnsebgosselin** [comment] 2018-11-19 19:05
Is this happening with the latest version on master?

**Comment by impact27** [comment] 2018-11-19 19:05
Well right now it does but not usually, I mostly uploaded that so you know it can happen. I will try to get the latest master and see if it still happens.

**Comment by impact27** [comment] 2018-11-19 19:05
The file is saved as expected

**Comment by jnsebgosselin** [comment] 2018-11-19 19:51
> 
> 
> > Is this happening with the latest version on master?
> 
> Yes

Ok thank you very much. I'm not able to reproduce this though... but I will try to investigate further.

**Comment by impact27** [comment] 2018-11-19 20:06
I restarted my computer and now the error appears randomly.

**Comment by jnsebgosselin** [comment] 2018-11-19 20:17
OK thanks, I think I know why this happens. I'm going to work on a fix.

**Comment by CAM-Gerlach** [comment] 2019-03-13 16:37
Duplicate of #8813 and your very own #8926 . Closed in favor of the former, since it has the most detailed error report isolating the exact cause of the error as well as including a directly related one.

**Closed by CAM-Gerlach** 2019-03-13 16:37 UTC
Labels: component:Editor, type:Bug
