### ISSUE TITLE
repetative internal problem about spyder ver. 4.0.1

### ISSUE THREAD

**Issue by justin1204** [spyder-ide/spyder#12594] opened 2020-05-04 03:27 UTC
### What steps will reproduce the problem?

no idea that the spyder will suddenly showed up the message about the crash down yesterday when i opened it again, then after i reinstalled the anaconda, it also popped out the reporter of internal problem again.

the version of spyder is 4.0.1, python is 3.7, and the anaconda version is the latest one on Windows 10.

### Traceback
```python-traceback
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 300, in get_autosave_filename
    autosave_filename = self.name_mapping[filename]
KeyError: 'C:\\Users\\Justin\\Desktop\\Python練習檔案\\練習2.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 347, in maybe_autosave
    self.autosave(finfo)
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 360, in autosave
    autosave_filename = self.get_autosave_filename(finfo.filename)
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 313, in get_autosave_filename
    self.save_autosave_mapping()
  File "C:\Users\Justin\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 258, in save_autosave_mapping
    pidfile.write(pprint.pformat(self.name_mapping))
  File "C:\Users\Justin\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-39: character maps to <undefined>
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by goanpeca** [comment] 2020-05-04 15:52
Hi @justin1204. This seems to be a duplicate of https://github.com/spyder-ide/spyder/issues/11609, which has been fixed and is available with the latest version of Spyder.

Please update by opening a terminal and typing

```
conda install spyder=4.1.2 toml
```

Cheers!

**Closed by goanpeca** 2020-05-04 15:52 UTC
