### ISSUE TITLE
Whenever I try to close a function info tooltip box thing, the report-issue window appeares

### ISSUE THREAD

**Issue by Stargrazer82301** [spyder-ide/spyder#9553] opened 2019-06-11 18:47 UTC
## Description

The issue reporting window pops up almost every time I tried to close a hovering help tooltip box thing associated with a function. This happens very frequently. 

Naturally, this means that this happens dozens/hundreds of times per session.

I think this only happens in the iPython terminal, as opposed to the editor. However, I'm not certain, because tooltips always stop appearing in the editor after it's been open for. a few minutes, and I can't be bothered to restart Spyder over and over again each day.

Spyder in general seems to be getting more and more unstable. =/

### Traceback
```python-traceback
  File "/Users/cclark/Soft/anaconda3/lib/python3.7/site-packages/spyder/widgets/calltip.py", line 122, in hideEvent
    self._cursor_position_changed)
TypeError: 'method' object is not connected
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.0
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.4 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by bcolsen** [comment] 2019-06-11 19:42
Thank you for reporting this bug. 

This looks like a duplicate #9221 which is to be fixed in our next release. I'm closing this issue but if you have a any more comment or ways to reproduce the error, please comment on #9221.

**Closed by bcolsen** 2019-06-11 19:42 UTC
