### ISSUE TITLE
Long NumPy arrays throw off errors

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2151] opened 2015-02-17 23:33 UTC
_From [cmee...@gmail.com](https://code.google.com/u/104521158352818840125/) on 2015-02-03T04:41:40Z_

Spyder Version:  2.3.2
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.4.1 (OK) 

What steps will reproduce the problem?

 1. import numpy; a = numpy.ones((1e6))
2. Open the variable explorer and double-click 'a' to start the array editor
3. Drag the scroller toward the bottom. Observe weird behaviour (it almost reaches the bottom after only a few hundred entries, then suddenly jumps up again and continues to be dragged downward as the entries are now in the 1000's, etc.)
4. Click OK or Cancel to dismiss the array editor and get the following error in the internal console:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\arrayeditor.py", line 168, in columnCount
    return self._data.shape[1]
IndexError: tuple index out of range 

Please provide any additional information below

. I have also on occasion had the entire Spyder application crash when opening 'a' (even after I have successfully opened it and tested the scrolling behaviour above).

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2151_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 23:33
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-03T08:22:42Z_

The behavior you observed about loading a few hundred rows, and then loading some more after reaching the bottom, is intentional. We can't load so much data without blocking the entire application, so we just load a small amount and load the rest on demand.

I'll investigate what happens with the errors you report.

**Summary:** Long NumPy arrays throw off errors  \<span class="oldvalue"> (was: Long arrays throws off array editor) \</span>  
  **Labels:** Cat-VariableExplorer MS-v2.3.4

**Comment by ccordoba12** [comment] 2015-03-09 22:32
I can't reproduce this error. I think this was fixed in 2.3.3 because `columnCount` doesn't return `self._data.shape[1]` anymore.

**Closed by ccordoba12** 2015-03-09 22:32 UTC
Labels: 1 star, bug, Variable-Explorer
