### ISSUE TITLE
keyboardinterrupt

### ISSUE THREAD

**Issue by soroosh12** [spyder-ide/spyder#19575] opened 2022-09-23 17:05 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
kernel in error say to me : interrupted by user

**Comment by dalthviz** [comment] 2022-09-23 17:46
Closing as duplicate of https://github.com/spyder-ide/spyder/issues/19574

**Closed by dalthviz** 2022-09-23 17:46 UTC
Labels: resolution:Duplicate
