### ISSUE TITLE
python3.5 spyder always has problem

### ISSUE THREAD

**Issue by min13s** [spyder-ide/spyder#5930] opened 2017-12-09 01:49 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\ProgramData\Anaconda2\envs\rt2\lib\site-packages\pygments\plu

**Comment by mikofski** [comment] 2017-12-09 02:12
duplicate of #5929 

please provide version info?

spyder: ?
python: ?
anaconda: ?
windows/osx/linux: ?

thx!

**Comment by mikofski** [comment] 2017-12-09 02:51
try downgrading to `jedi==0.10.2` or anconda to 5.0.1, see [this comment](https://github.com/spyder-ide/spyder/issues/5929#issuecomment-350417392) - worked for me

**Comment by ccordoba12** [comment] 2017-12-09 04:39
This error is produced because you have `parso 0.1.1` installed. Please downgrade to `parso 0.1.0` to fix this problem.

You can do that with

    conda install parso=0.1.0

or

    pip install parso==0.1.0

**Closed by ccordoba12** 2017-12-09 04:39 UTC
