### ISSUE TITLE
Options for the LSP server are not being updated.

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10144] opened 2019-09-05 01:11 UTC
## Problem Description

Show code style / Show doc style options are not working from source or preferences menu.

### What steps reproduce the problem?

1. Click `Source` menu and the unselect `Show code style warnings`
2. Warnings do not disappear

### What is the expected output? What do you see instead?

Warnings do not disappear

![warnings](https://user-images.githubusercontent.com/3627835/64303976-29f89100-cf50-11e9-95b2-a4c93bc9542e.gif)

Latest master

pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
pympler >=0.7     :  None (NOK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  1.9.2 (OK)

**Comment by ccordoba12** [comment] 2019-09-09 10:20
Please look for all PyLS and transport scripts running in your system and kill them. Then restart Spyder to see if that helps.

**Comment by ccordoba12** [comment] 2019-09-09 11:52
I found a very simple way to reproduce this: using two Spyder instances. The problem is serious because every time users change an LSP option in the second instance, its related services (completion and linting) stop working completely.

**Comment by ccordoba12** [comment] 2019-09-09 16:09
This is a duplicate of issue #9933.

**Closed by ccordoba12** 2019-09-09 16:09 UTC
Labels: component:Code Completion, type:Bug
