### ISSUE TITLE
Argument cannot work in Spyder 2.3.4

### ISSUE THREAD

**Issue by jwu72** [spyder-ide/spyder#2433] opened 2015-05-10 04:56 UTC
## Description

I have some problems about argument after I installed spyder 2.3.4. The argument in console cannot work when you type function or create objective.  

* *What steps will reproduce the problem?*

For example, if I create a function as below:

```python
def f(x, alpha = 3, beta =2):
    return 3*x + beta
```

* *What is the expected output? What do you see instead?*

Expected: Previously in Spyder 2.3.1, when I type f( in ipython console or editor, spyder will automatically showed argument `(x, alpha =3, beta =2)`. 

What I see now: In Spyder 2.3.4, the argument only showed `( , =, =)`.

* *Please provide any additional information below*

I use Ubuntu 14.04. I hope the argument can work as before and showed all input. 

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment] 2015-05-11 22:13
I think what you're seeing is the same problem as reported in issue #2036. Could you confirm it?

**Comment by jwu72** [comment] 2015-05-12 00:08
Hi:

I think it's similar. My problem is the function argument disappeared. 

![screenshot from 2015-05-11 19 04 36](https://cloud.githubusercontent.com/assets/12377903/7577701/1b84ff84-f811-11e4-8575-f6d9855d4c3a.png)

**Comment by ccordoba12** [comment] 2015-05-13 21:02
Yes, it's exactly the same problem. The only solution right now is to change your windows style in

    Tools > Preferences > General > Qt windows style

and choosing a different option than the default one, which is **GTK+**

----

I'm closing this issue as duplicate of #2036

**Closed by ccordoba12** 2015-05-13 21:02 UTC
Labels: bug, duplicate, IPython-Console
