### ISSUE TITLE
debugger does not debug and also cannot be exited

### ISSUE THREAD

**Issue by tsintsenet** [spyder-ide/spyder#17311] opened 2022-02-08 13:26 UTC
### What steps will reproduce the problem?

just on any code, run debugger, it halts at line #2:

py3\temp.py(2)<module>()
      1 # -*- coding: utf-8 -*-
----> 2 """
      3 Spyder Editor
      4 
      5 This is a temporary script file.
      
      and when pressing the red square, get an error as if i pressed ctrl+c:
 
 --KeyboardInterrupt--
For copying text while debugging, use Ctrl+Shift+C     

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\envs\tfcpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\envs\tfcpu\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 338, in _handle_input_request
    if self._hidden:
AttributeError: 'ShellWidget' object has no attribute '_hidden'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tfcpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\envs\tfcpu\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 338, in _handle_input_request
    if self._hidden:
AttributeError: 'ShellWidget' object has no attribute '_hidden'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  2.0.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.31.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.1.0 (OK)
numpydoc >=0.6.0               :  1.2 (OK)
paramiko >=2.4.0               :  2.8.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.11.2 (OK)
pylint >=1.0                   :  2.9.6 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.3 (OK)
qtconsole >=4.6.0              :  5.2.2 (OK)
qtpy >=1.5.0                   :  1.11.2 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.4.0 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.3.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.5.0 (OK)
numpy >=1.7                    :  1.21.5 (OK)
pandas >=0.13.1                :  1.3.5 (OK)
scipy >=0.17.0                 :  1.7.3 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment] 2022-02-08 15:21
Hey @tsintsenet, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Closed by ccordoba12** 2022-02-08 15:21 UTC

**Comment by bldrake** [comment] 2022-02-11 15:43
I'm still having this problem.
1. downloaded the .dmg file for MacOS
2. installed Spyder
3. tried running my code
4. get the same output as above:
5.       2 # -*- coding: utf-8 -*-
      3 
----> 4 """
      5 Created on Thu Feb 10 13:21:34 2022
6. When I try to end the debug session get the following:
7. --KeyboardInterrupt--
For copying text while debugging, use Ctrl+Shift+C
8. version info
9. * Spyder version: 5.1.5 None
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0
10. Why does the version have 5.1.5 instead of the 5.2.2 that was supposed to be downloaded?

Thanks!

**Comment by bldrake** [comment] 2022-02-11 15:46
This is where I downloaded from:
[Spyder 5.2.2](https://github.com/spyder-ide/spyder/releases/tag/v5.2.2) [Latest](https://github.com/spyder-ide/spyder/releases/latest)
Simple installation

The easiest way to start using Spyder is by downloading our own installers for Windows and macOS:

    /Spyder_64bit_full.exe)
    macOS (10.15+): [Spyder.dmg](https://github.com/spyder-ide/spyder/releases/download/v5.2.2/Spyder.dmg)

**Comment by bldrake** [comment] 2022-02-11 16:26
The problem is that when I enter debug mode, execution doesn't stop at the breakpoint:
* print(i) in the code below.

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Thu Feb 10 13:21:34 2022
@author: bd111
"""

test_break = True
i = 1
* print(i)

print("the end")

**Comment by ccordoba12** [comment] 2022-02-11 16:48
It seems you have Anaconda and also our macOS installer in your computer. Our installer is independent from Anaconda, and you need to run it using Spotlight. Please try that and let us know if it works for you.

**Comment by bldrake** [comment] 2022-02-11 21:39
Issues resolved. Started with a fresh installation of Spyder using pip; conda installation still couldn't stop at first breakpoint nor could the standalone version from the Spyder.dmg file.

Here is the version info:
* Spyder version: 5.2.2 None
* Python version: 3.9.7 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.6.0

I can't do Python without Spyder! At least not as effectively.
Thanks!

**Comment by ccordoba12** [comment] 2022-02-11 22:07
Great! I'm glad you were able to solve your problem.
