### ISSUE TITLE
Errors are shown twice

### ISSUE THREAD

**Issue by rantanplan77** [spyder-ide/spyder#5408] opened 2017-10-06 13:59 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. start sypder or restart the kernel
2. type something that produces an error
(it is the same for all error messages, regardless of how long the kernel is running)

**What is the expected output? What do you see instead?**

I see the same error message twice instead of once:

![doubled error message](https://user-images.githubusercontent.com/17641534/31281057-a05b8776-aaae-11e7-9a7d-507fe91b65d1.PNG)

**Please provide any additional information below**
If I open ipython in a terminal outside spyder, the error message is shown only once. 

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.5.3
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: OS X 10.11.6 

## Dependencies

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.2.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment] 2017-10-06 14:03
Thanks for reporting. We'll take a look at this in a future release.

**Comment by goanpeca** [comment] 2019-12-04 03:31
Cannot reproduce this. Closing.

**Closed by goanpeca** 2019-12-04 03:31 UTC
Labels: component:IPython Console, type:Bug
