### ISSUE TITLE
Spyder launch err

### ISSUE THREAD

**Issue by dai-kan** [spyder-ide/spyder#6281] opened 2018-01-23 23:52 UTC
## Description

**What steps will reproduce the problem?**

1. Launch Spyder from Terminal
2. Launch Spyder from Anaconda Navigator
3. 

**What is the expected output? What do you see instead?**

Error screen with the info below. Anaconda was removed and reinstalled, after that condo update spyder was executed successfully.

There was an effort to make an application directory file to launch spyder such that it could be called from within Fork.app, a GitHub GUI. A .plist file was created and placed in Application/Spyder/Content/ however all that 'stuff' was removed. Some residual might be causing the problem.

**Please provide any additional information below**

  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/plugins/projects.py", line 149, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/plugins/editor.py", line 2680, in setup_open_files
    filenames = self.projects.get_project_filenames()
  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/plugins/projects.py", line 317, in get_project_filenames
    recent_files = self.current_active_project.get_recent_files()
  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/widgets/projects/type/__init__.py", line 79, in get_recent_files
    default=[])
  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/config/user.py", line 380, in get
    self.set(section, option, default)
  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/config/user.py", line 448, in set
    self._save()
  File "/Users/dogan/anaconda2/lib/python2.7/site-packages/spyder/config/user.py", line 124, in _save
    raise(e)
IOError: [Errno 2] No such file or directory: 'sn_0_794818/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-24 04:10
Thanks for reporting. This is an apparent duplicate of  #4945 , and furthermore, with regard to 

> Some residual might be causing the problem.

this is outside of our control. 

However, the problem can likely be fixed with ``spyder --reset`` from the Terminal, or one of the other fixes suggested in that thread (or one of the other duplicates), and you can also try the suggestions in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. Therefore, this issue will be closed. Best of luck!

**Closed by CAM-Gerlach** 2018-01-24 04:10 UTC
