### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ritzdevp** [spyder-ide/spyder#7285] opened 2018-06-13 08:18 UTC
Spyder crashes on handling medium size dataset
eg: 100 thousand rows

**Comment by ccordoba12** [comment] 2018-06-13 11:22
I think this is a duplicate of issue #5830. It'll be fixed in our next release.

**Closed by ccordoba12** 2018-06-13 11:22 UTC

**Comment by ritzdevp** [comment] 2018-06-13 11:28
Thanks
