### ISSUE TITLE
Plot explorer

### ISSUE THREAD

**Issue by srvmig** [spyder-ide/spyder#15951] opened 2021-06-29 17:46 UTC
Is it possible to a add plot explorer in Spyder. For example if there are too many subplots is a plot,  then it hard to read the whole data. If there is a explorer added then it would be possible to open it in another tab then zoom in and zoom out. The feature is available in R studio.

**Comment by ccordoba12** [comment] 2021-06-29 17:58
Hey @srvmig, I don't understand what you mean by this. Please post some screenshots about the RStudio functionality.

**Comment by srvmig** [comment] 2021-06-30 09:12
After generating the plot in Rstudio, If the Zoom button pressed, the plot opens in another window. Which helps to explore the plot. Please check the screenshot. There is a button in Spyder. But it does not work to zoom.
![SS-1](https://user-images.githubusercontent.com/45663120/123934752-6adb5880-d9b5-11eb-90ef-a359bcc708f7.jpg)
![SS-2](https://user-images.githubusercontent.com/45663120/123934788-73339380-d9b5-11eb-9880-9dd4a58b0457.jpg)

**Comment by rhkarls** [comment] 2021-06-30 18:30
I was missing such a feature as well. I work without using the plot pane because I often need interactivity on some figures, but the majority is fine static. If it would be possible to pop out figures when needed that would be superb. I might be able to have a look at this if its not an urgent issue (I'm currently learning qt and have some related slightly related person projects starting). I think it would be cool to pop the figure out to an interactive figure, I think its quite easy if its possible to access the matplotlib Figure object already in the plots plugin (using the qt5 backend). I had a brief look but from what I could find was only static rendered plots - if possible to access the Figure objects already somewhere in the plots plugin could you point me to it @ccordoba12 ?

**Comment by ccordoba12** [comment] 2021-07-01 22:14
@srvmig, you said:

> There is a button in Spyder. But it does not work to zoom.

This is usability bug we're aware of and we'll try to fix it in the future. For the zoom buttons to work you need to deactivate the option called `Fit plots to window` in the options menu of the Plots pane:

![imagen](https://user-images.githubusercontent.com/365293/124195257-aea29080-da8f-11eb-9a19-882c1adffb90.png)

**Comment by ccordoba12** [comment] 2021-07-01 22:26
> If it would be possible to pop out figures when needed that would be superb. I might be able to have a look at this if its not an urgent issue (I'm currently learning qt and have some related slightly related person projects starting)

I agree that would be very nice, and I see two options about it:

1. Use svg as the format for plots, so that zooming works much better than with png plots. For that we'd need to implement issue #9987 because Qt doesn't support the full SVG spec.
2. For full interactivity we'd need to provide a way to easily switch between Matplotlib backends. The backend used by the Plots pane is Inline, but an interactive backend such as Automatic, Qt or Tk is required for zooming and panning. There's PR #14199 for that.

**Comment by srvmig** [comment] 2021-07-02 05:36
I got it. But is it possible to add a feature that when I double click on a plot, then it will open in another window, where I can inspect the plot closely.

**Comment by rhkarls** [comment] 2021-07-02 08:06
> 
>     2. For full interactivity we'd need to provide a way to easily switch between Matplotlib backends. The backend used by the Plots pane is Inline, but an interactive backend such as Automatic, Qt or Tk is required for zooming and panning. There's PR [PR: Add matplotlib state to status bar #14199](https://github.com/spyder-ide/spyder/pull/14199) for that.

@ccordoba12 I wonder if it possible to do that without changing backend. If one can use the QtAgg from mpl without running into dependency issues that is. A quick example of what I mean (apologies for the scaling) :
![spyder_fig_to_qtwidget](https://user-images.githubusercontent.com/2330659/124242007-97f64b00-db1c-11eb-8ee0-dbab862eddbf.gif)

Very nice addition with the matplotlib state btw!

**Comment by ccordoba12** [comment] 2021-07-13 01:48
> If one can use the QtAgg from mpl without running into dependency issues that is. A quick example of what I mean (apologies for the scaling

The problem is that you need a reference to the Matplotlib object that is behind the figure. And I really don't know how to create a mapping between static png images (the ones displayed in the Plots pane) and those objects.

Also, perhaps that's feasible when you use the object-oriented Matplotlib interface. But what about when using `plt`?

**Comment by ccordoba12** [comment] 2021-07-19 01:36
Closing because this is (most probably) not something we can solve in the near future.

The best we can do is to switch to SVG as the format of inline figures.

**Closed by ccordoba12** 2021-07-19 01:36 UTC
Labels: status:Awaiting Followup
