### ISSUE TITLE
'x' mark doesn't appear on top of the editor panels

### ISSUE THREAD

**Issue by cocoaaa** [spyder-ide/spyder#6988] opened 2018-04-18 22:31 UTC
## Problem Description
After updating all the packages in my conda environment, the spyder's editor panels stop showing 'x' marks. I can still close each script by clicking on the empty space (please see the image below). 

![image](https://user-images.githubusercontent.com/8037983/38961387-3b51121c-431d-11e8-9f5a-ef638deb1362.png)

### What steps will reproduce the problem?

1.  upgrade all packages in the current environment using conda

## Package Versions

* Spyder: 3.2.8
* Python:3.6.5
* Qt:5.9.4
* PyQt:5.9.2
* Operating System: MacOS High Sierra 10.13.3

**Comment by CAM-Gerlach** [comment] 2018-04-19 04:00
Thanks for reporting. My guess would be an issue with Qt 5.9 on macOS, particularly High Sierra where Qt support is still rather flaky at last check. Unforunatly, there might not be much we can do about it due to it being Qt's problem...@ccordoba12 ? In the meantime, you can try downgrading Qt (and PyQt) to 5.6.x, although High Sierra is not fully supported there for sure and has some glitches and instability.

**Comment by ccordoba12** [comment] 2018-04-19 15:04
Thanks for reporting. I have a 10.12 VM, so I'll take a look at this when I have some time.

**Comment by jnsebgosselin** [comment] 2018-06-27 16:29
@ccordoba12 possible duplicate of https://github.com/spyder-ide/spyder/issues/4580

**Comment by ccordoba12** [comment] 2018-06-27 23:54
Right, let's close this one.

**Closed by ccordoba12** 2018-06-27 23:54 UTC
Labels: component:Main Window, type:Bug
