### ISSUE TITLE
open app and load files that have moved

### ISSUE THREAD

**Issue by suzannejb** [spyder-ide/spyder#13847] opened 2020-09-23 19:12 UTC
### What steps will reproduce the problem?

I closed Spyder with a particular .py file still open. I moved the file and then opened Spyder again. It crashed right away.

### Traceback
```python-traceback
  File "C:\Users\J86401\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\J86401\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.3 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by dalthviz** [comment] 2020-09-23 19:43
Hi @suzannejb for now as a work around could you try disabling Kite? (you can do it by going to `Preferences > Completion and linting > Advanced > Providers` and unchecking the option `Enable Kite (if the Kite engine is running)`

**Comment by dalthviz** [comment] 2020-09-23 19:50
Checking a little bit more seems like this is a duplicate of #13121 if you have more info regarding this one please post it over #13121 . Let us know if disabling Kite helps :)

**Closed by dalthviz** 2020-09-23 19:50 UTC
Labels: resolution:Duplicate

**Comment by suzannejb** [comment] 2020-09-25 13:16
> Hi @suzannejb for now as a work around could you try disabling Kite? (you can do it by going to `Preferences > Completion and linting > Advanced > Providers` and unchecking the option `Enable Kite (if the Kite engine is running)`

This fixed me. Thanks!

**Comment by ccordoba12** [comment] 2020-09-25 15:18
@suzannejb, that's really good to know!

**Comment by ccordoba12** [comment] 2020-09-25 15:19
@dalthviz, could you try to reproduce this error with @suzannejb's description for it?

> I closed Spyder with a particular .py file still open. I moved the file and then opened Spyder again. It crashed right away.

**Comment by dalthviz** [comment] 2020-09-27 16:10
@ccordoba12 I was unable to reproduce the error :/. Just in case the env's spec where I tested:


<details>

```
# packages in environment at C:\Users\Daniel\Anaconda3\envs\forge415:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
astroid                   2.4.2            py37hc8dfbb8_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py37h4ab8f01_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37h4ab8f01_1000    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.3           py37h26f1ce3_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1007    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              3.1.1            py37h26f1ce3_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
flake8                    3.8.3                      py_1    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        2.0.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        2.0.0                         0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py37h5ca1d4c_0    conda-forge
ipython                   7.18.1           py37hc6149b9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.5.3            py37hc8dfbb8_0    conda-forge
jedi                      0.17.1           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab_pygments       0.1.1              pyh9f0ad1d_0    conda-forge
keyring                   21.4.0           py37hc8dfbb8_1    conda-forge
lazy-object-proxy         1.4.3            py37h8055547_2    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
markupsafe                1.1.1            py37h4ab8f01_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h8055547_1001    conda-forge
nbclient                  0.5.0                      py_0    conda-forge
nbconvert                 6.0.6            py37hc8dfbb8_0    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
nest-asyncio              1.4.0                      py_1    conda-forge
numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandoc                    2.10.1               he774522_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.2.3                     py_0    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
prompt-toolkit            3.0.7                      py_0    conda-forge
psutil                    5.7.2            py37h4ab8f01_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pylint                    2.6.0            py37hc8dfbb8_0    conda-forge
pynacl                    1.3.0           py37h2fa13f4_1001    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3           py37h4ab8f01_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           cpython_h60c2a47_6    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.35.1                     py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywin32                   227              py37hfa6e2cd_0    conda-forge
pywin32-ctypes            0.2.0           py37hc8dfbb8_1001    conda-forge
pyyaml                    5.3.1            py37h4ab8f01_0    conda-forge
pyzmq                     19.0.2           py37h453f00a_0    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_1    conda-forge
qt                        5.12.6               hb2cf2c5_0    conda-forge
qtawesome                 0.7.3              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py37h804a536_1    conda-forge
setuptools                49.6.0           py37hc8dfbb8_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.1.5            py37hc8dfbb8_0    conda-forge
spyder-kernels            1.9.4            py37hc8dfbb8_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
traitlets                 5.0.4                      py_1    conda-forge
typed-ast                 1.4.1            py37hfa6e2cd_0    conda-forge
ujson                     3.2.0            py37h1834ac0_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
watchdog                  0.10.3           py37hc8dfbb8_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
wrapt                     1.11.2           py37h8055547_0    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.2                ha925a31_3    conda-forge
zipp                      3.2.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1009    conda-forge
```

</details>
