### ISSUE TITLE
Error while switching layouts

### ISSUE THREAD

**Issue by shomenbanerjee** [spyder-ide/spyder#5729] opened 2017-11-12 03:54 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2132, in closeEvent
    if self.closing(True):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2186, in closing
    self.save_current_window_settings(prefix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1415, in save_current_window_settings
    self.maximize_dockwidget(restore=True)# Restore non-maximized layout
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2268, in maximize_dockwidget
    self.last_plugin.dockwidget.setWidget(self.last_plugin)
AttributeError: 'NoneType' object has no attribute 'dockwidget'
Error in atexit._run_exitfuncs:

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4

**Comment by ccordoba12** [comment] 2017-11-12 15:24
Thanks for reporting.

@dalthviz, I think you solved a bug similar to this one before. Do you remember why it happens?

**Comment by dalthviz** [comment] 2017-11-12 18:34
I'm not quite sure about this but probably we should add a validation [here](https://github.com/spyder-ide/spyder/blob/3.x/spyder/app/mainwindow.py#L2243) with something like `... or self.last_plugin is None:`?

**Comment by ccordoba12** [comment] 2018-01-08 18:09
Closing as a duplicate of issue #5477.

**Closed by ccordoba12** 2018-01-08 18:09 UTC
Labels: component:Main Window, type:Bug
