### ISSUE TITLE
F5 doesn't work when undocked

### ISSUE THREAD

**Issue by fisherfelix** [spyder-ide/spyder#11145] opened 2019-12-19 23:18 UTC
**Description:**
When using Spyder4 in undocked mode, hitting F5 doesn't run the file. I have to go back to the main IDE screen and hit the play button with my mouse. 

**Steps to reproduce:**

1. Set configuration per file to 'execute in external system window'
2. Undock python script
3. Hit F5

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.3 
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.0.0 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.15.2 (OK)
scipy >=0.17.0               :  1.1.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

**Comment by ccordoba12** [comment] 2019-12-25 15:53
Duplicate of #5123

**Comment by ccordoba12** [comment] 2019-12-25 15:53
This is not an easy thing to solve. It'll probably be addressed in Spyder 5, to be released in 2020.

**Closed by ccordoba12** 2019-12-25 15:53 UTC
