### ISSUE TITLE
Ipython console will not open; connecting to kernel...

### ISSUE THREAD

**Issue by rumble-b** [spyder-ide/spyder#2805] opened 2015-11-08 19:03 UTC
I just got Spyder and upon startup, the iPython console is frozen on "connecting to kernel". Same response if I try to open a new console.

Details:
Spyder 2.3.5.2
Python 2.7.10 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Windows 7

**Comment by ccordoba12** [comment] 2015-11-16 00:40
I think this is a duplicate of issue #2793. If you don't have Matplotlib 1.5, then you should update pyzmq to its latest version. That should also fix your problem.

**Closed by ccordoba12** 2015-11-16 00:40 UTC
Labels: duplicate
