### ISSUE TITLE
Conda update/install most packages wants to roll Spyder back to 

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#11565] opened 2020-02-15 23:41 UTC
## Problem Description

Trying to add or update packages in conda via miniconda console results in:
```
(datascience) C:\Users\bbate>conda install -c conda-forge pypdf2
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\bbate\Miniconda3\envs\datascience

  added / updated specs:
    - pypdf2

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pypdf2-1.26.0              |             py_2          48 KB  conda-forge
    spyder-3.3.6               |           py37_0         2.3 MB
    ------------------------------------------------------------
                                           Total:         2.3 MB

The following NEW packages will be INSTALLED:

  pypdf2             conda-forge/noarch::pypdf2-1.26.0-py_2

The following packages will be DOWNGRADED:

  spyder                                       4.0.1-py37_0 --> 3.3.6-py37_0
  spyder-kernels                               1.8.1-py37_0 --> 0.5.2-py37_0

Proceed ([y]/n)? n

CondaSystemExit: Exiting.
```

The same thing happened with a scikit-learn module etc.

### What steps reproduce the problem?

1.  Installed Spyder 4.0.1 in miniconda
2. conda install pypdf2 (or from a specific source: conda install -c conda-forge pypdf2) 
3. Result:  

The following packages will be DOWNGRADED:

  spyder                                       4.0.1-py37_0 --> 3.3.6-py37_0
  spyder-kernels                               1.8.1-py37_0 --> 0.5.2-py37_0

### What is the expected output? What do you see instead?

Install package without downgrading Spyder

### Paste Traceback/Error Below (if applicable)

```
no other errors 
```

## Versions

Spyder 4.0.1 
Python 3.7.6 64-bit
Qt 5.9.6
PyQt5 5.9.2
Windows 10 

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  2.2.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.1+0.g171c716.dirty (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

```

**Comment by ccordoba12** [comment] 2020-02-16 04:46
Duplicate of #11550

**Closed by ccordoba12** 2020-02-16 04:46 UTC

**Comment by eafpres** [comment] 2020-02-16 04:49
Well, I looked at that and it’s not obvious at all it’s the same. Also, what I’m supposed to do?

**Comment by ccordoba12** [comment] 2020-02-16 04:50
We're not sure yet, sorry.

**Comment by eafpres** [comment] 2020-02-16 04:51
Okay, but then you can’t be sure this is a duplicate. The repro is totally different.

**Comment by ccordoba12** [comment] 2020-02-16 18:01
The problem is Jedi 0.16, which is compatible with Spyder 3.3.6 but not with Spyder 4.

If you want to update to Spyder 4 after it's downgraded by conda, please run

    conda install spyder=4.0.1
