### ISSUE TITLE
Spyder freeze when saving a file

### ISSUE THREAD

**Issue by pj1989** [spyder-ide/spyder#12868] opened 2020-05-26 15:29 UTC
When saving a file sometimes Spyder hangs for several seconds (>30 seconds). Windows even ask to close the problem marking it as "non responding".

I **suspect** the problem to be related to the number/total size of files in the directory.

In my case, I was running some examples from the Desktop where I also have a folder containing about 8GB of data divided in 9000 files. Moving the file to a sub-directory completely eliminated the problem, while running the file on the desktop changing the current directory to be the subdirectory did not improve the problem.

I'm still not 100% sure of what triggers the behavior, but when if it occurs for one file, then it occurs **every** time the file is saved (in that sense, it is 100% reproducible).

If you have any idea regarding other tests that I could perform, I'll be happy to run them for you.

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by pj1989** [comment] 2020-05-26 15:50
EDIT: editing the script and then running it a second time cause the problem to occur again

**Comment by steff456** [comment] 2020-05-26 19:11
Hi @pj1989,

Did you create a project before running the file that you mention?

**Comment by pj1989** [comment] 2020-05-26 19:36
Yes. I had a project open. I then created a file outside the project directory (on the Desktop indeed) to perform some tests. 

Saving this file (or running it after modifying it) triggered the behaviour. However, also after closing the project, the bug was still occurring.

**Comment by ccordoba12** [comment] 2020-05-26 22:37
@pj1989, could you verify if the bug occurs without opening a project?

**Comment by pj1989** [comment] 2020-05-27 10:49
Here are few steps I took that caused the error:

- Reset Spyder with `spyder --reset`
- Rebooted the PC
- Waited for all startup programs to start and for the CPU to be completely free
- Launched Spyder
- Changed current folder from `C:\Users\Name.Surname` to `C:\Users\Name.Surname\Desktop`

**Spyder hangs for about 35 seconds (timed)**

- Click on New File
- Click on Save
- Save the file on Desktop

**Spyder hangs for about 70 seconds**

- Typed few characters in the file (a single space is enough)
- Click Save (or ctrl+S)

**Spyder hangs for about 40 seconds**

I can repeat the last two points as many times I want. Every time I edit the file and click Save, Spyder hangs for almost exactly 40 seconds.

- Change the current directory to `C:\Users\Name.Surname\Desktop\New folder`

**Spyder hangs for about 10 seconds**

- Save the file (with "Save as...") in `C:\Users\Name.Surname\Desktop\New folder`

**No wait**

- Click on "up one level" arrow in the top-right corner to go back to Desktop

**Spyder hangs for about 30 seconds**

- Click again on "up one level" arrow to go back to `C:\Users\Name.Surname`

**Spyder hangs for about 30 seconds**

- Save the file (with "Save as...") in `C:\Users\Name.Surname`

**Spyder hangs for about 15 seconds**


I don't have any other idea. Let me know any other test I could do.
Thank you very much
Luca

**Comment by pj1989** [comment] 2020-05-27 10:54
Forgot to mention, but should be implied, that after `spyder --reset` I don't have any project open, nor in the "recent projects" list.

**Comment by ccordoba12** [comment] 2020-05-27 13:25
Thanks for the detailed explanation @pj1989! I have one more question for you: what did you mean by this?

> Moving the file to a sub-directory completely eliminated the problem

**Comment by pj1989** [comment] 2020-05-27 13:51
It means that if I save the file in a directory inside the desktop and change the current folder to the same directory, saving the file is instantaneous as it is meant to be

If you look, I did this test in the example above and there was indeed "no wait"

**Comment by ccordoba12** [comment] 2020-05-27 14:43
Ok, then I think this is a duplicate of, or quite similar to, issue #10081. Could you confirm?

**Comment by steff456** [comment] 2020-06-03 02:41
Closing this issue because there was not a response after a week.

**Closed by steff456** 2020-06-03 02:41 UTC
Labels: status:Awaiting Followup
