### ISSUE TITLE
`runfile` resets namespace

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14275] opened 2020-11-20 10:50 UTC
I `runfile` a lot, and just noticed that it doesn't involve re-running the startup script. Is this intended? It's rather self-defeating if I must restart the kernel each time for startup functions to be available (or for arbitrary scripts to execute).

**Comment by ccordoba12** [comment] 2020-11-20 14:36
Good point. @impact27, what do you think about this one?

**Comment by impact27** [comment] 2020-11-20 15:49
I am not sure I understand. The startup scripts loads some things in the namespace at the start of the session. What does that have to do with `runfile`? If you want to have access these things, you need to activate `Run in console's namespace instead of an empty one`. Could you give a reproducible example of the problem you are facing?

**Comment by impact27** [comment] 2020-11-20 15:50
Is using `runfile` resetting your namespace?

**Comment by OverLordGoldDragon** [comment] 2020-11-20 15:57
[demo.mp4](https://puu.sh/GPtqI/4a441e6d36.mp4); my "startup script" config:

<img src="https://user-images.githubusercontent.com/16495490/99820328-10019900-2b6a-11eb-8a3c-d70a4ab1e877.png" width="600">

And yes, `runfile` clears all variables and functions (but is not entirely equivalent to resetting kernel), which if I recall it's supposed to. I also checked the box you suggested in `Run -> General settings`, didn't help.

**Comment by impact27** [comment] 2020-11-20 16:06
`runfile` should not clear anything. Without the option, it will create a new namespace, and merge it at the end. With the option, it will use the already existing namespace.

**Comment by impact27** [comment] 2020-11-20 16:08
could you try:
 - set a variable in the console
 - run a random file
 - Check if the variable is still defined?

**Comment by OverLordGoldDragon** [comment] 2020-11-20 16:09
[Yeah](https://puu.sh/GPtHz/7f7e1b0f1e.mp4), and btw it has been like this for months

**Comment by impact27** [comment] 2020-11-20 16:11
Strange, I can't reproduce:
```
In [1]: a = 1

In [2]: runfile('C:/Users/Quentin.Peter/untitled2.py', wdir='C:/Users/Quentin.Peter')

In [3]: a
Out[3]: 1

In [4]: 
```

**Comment by impact27** [comment] 2020-11-20 16:13
Could you give:

## Versions
( You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line.)

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

 ##Dependencies
( go to the menu entry Help > Dependencies,
press the Copy to clipboard button)

**Comment by OverLordGoldDragon** [comment] 2020-11-20 16:20
I also reproduced setting `a = 1` directly in IPython instead of via `runfile`. Info:

 - Win10 x64
 - Spyder 4.2.0
 - Python 3.7.7
 - Qt 5.9.7=vc14h73c81de_0
 - PyQt 5.9.2=py37h6538335_2

<details>
  <summary>environment.txt</summary>

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
_anaconda_depends=2020.07=py37_0
_ipyw_jlab_nb_ext_conf=0.1.0=py37_0
absl-py=0.10.0=pypi_0
alabaster=0.7.12=py37_0
anaconda=custom=py37_1
anaconda-client=1.7.2=py37_0
anaconda-navigator=1.9.12=py37_0
anaconda-project=0.8.4=py_0
appdirs=1.4.4=pyh9f0ad1d_0
argh=0.26.2=py37_0
argon2-cffi=20.1.0=py37he774522_1
asn1crypto=1.4.0=py_0
astroid=2.4.2=py37_0
astropy=4.0=py37he774522_0
atomicwrites=1.4.0=py_0
attrs=19.3.0=py_0
autopep8=1.5.4=py_0
babel=2.8.0=py_0
backcall=0.2.0=py_0
backports=1.0=py_2
backports.functools_lru_cache=1.6.1=py_0
backports.shutil_get_terminal_size=1.0.0=py37_2
backports.tempfile=1.0=py_1
backports.weakref=1.0.post1=py_1
bcrypt=3.1.7=py37he774522_1
beautifulsoup4=4.9.1=py37_0
bitarray=1.4.2=py37he774522_0
bkcharts=0.2=py37_0
black=20.8b1=py_1
blas=1.0=mkl
bleach=3.1.5=py_0
blosc=1.19.0=h7bd577a_0
bokeh=1.4.0=py37_0
boto=2.49.0=py37_0
bottleneck=1.3.2=py37h2a96729_0
brotli=1.0.7=pypi_0
brotlipy=0.7.0=py37he774522_1000
bzip2=1.0.8=he774522_0
ca-certificates=2020.11.8=h5b45459_0
cachetools=4.1.1=pypi_0
certifi=2020.11.8=py37h03978a9_0
cffi=1.14.0=py37h7a1dbc1_0
chardet=3.0.4=py37_1003
click=7.1.2=py_0
cloudpickle=1.5.0=py_0
clyent=1.2.2=py37_1
colorama=0.4.3=py_0
comtypes=1.1.7=py37_1001
conda-package-handling=1.6.1=py37h62dcd97_0
conda-verify=3.4.2=py_1
console_shortcut=0.1.1=4
contextlib2=0.6.0.post1=py_0
cryptography=2.9.2=py37h7a1dbc1_0
cudatoolkit=10.1.243=h74a9793_0
curl=7.71.1=h2a8f88b_1
cycler=0.10.0=py37_0
cython=0.29.21=py37ha925a31_0
cytoolz=0.10.1=py37he774522_0
dask=2.22.0=py_0
dask-core=2.22.0=py_0
dataclasses=0.7=pyhb2cacf7_7
decorator=4.4.2=py_0
defusedxml=0.6.0=py_0
diff-match-patch=20200713=py_0
distributed=2.22.0=py37_0
docutils=0.16=py37_1
entrypoints=0.3=py37_0
et_xmlfile=1.0.1=py_1001
fastcache=1.1.0=py37he774522_0
filelock=3.0.12=py_0
flake8=3.8.3=py_0
flask=1.1.2=py_0
flask-compress=1.5.0=pypi_0
freetype=2.10.2=hd328e21_0
fsspec=0.7.4=py_0
future=0.18.2=py37_1
get_terminal_size=1.0.0=h38e98db_0
gevent=20.6.2=py37he774522_0
glob2=0.7=py_0
gmpy2=2.0.8=py37h0964b28_3
google-auth=1.20.1=pypi_0
google-auth-oauthlib=0.4.1=pypi_0
greenlet=0.4.16=py37he774522_0
grpcio=1.31.0=pypi_0
h5py=2.10.0=py37h5e291fa_0
hdf5=1.10.4=h7ebc959_0
heapdict=1.0.1=py_0
html5lib=1.1=py_0
hypothesis=5.24.0=py_0
icc_rt=2019.0.0=h0cc432a_1
icu=58.2=ha925a31_3
idna=2.10=py_0
imageio=2.6.1=py37_0
imagesize=1.2.0=py_0
importlib-metadata=1.7.0=py37_0
importlib_metadata=1.7.0=0
iniconfig=1.1.1=py_0
intel-openmp=2020.1=216
intervaltree=3.0.2=py_1
ipykernel=5.3.4=py37h5ca1d4c_0
ipython=7.17.0=py37h39e3cac_0
ipython_genutils=0.2.0=py37_0
ipywidgets=7.5.1=py_0
isort=4.3.21=py37_0
itsdangerous=1.1.0=py37_0
jdcal=1.4.1=py_0
jedi=0.17.2=py37h03978a9_1
jinja2=2.11.2=py_0
joblib=0.16.0=py_0
jpeg=9b=hb83a4c4_2
json5=0.9.5=py_0
jsonschema=3.2.0=py37_1
jupyter=1.0.0=py37_7
jupyter_client=6.1.6=py_0
jupyter_console=6.1.0=py_0
jupyter_core=4.6.3=py37_0
jupyterlab=2.1.5=py_0
jupyterlab_server=1.2.0=py_0
keyring=21.3.0=py37_0
kiwisolver=1.2.0=py37h74a9793_0
krb5=1.18.2=hc04afaa_0
lazy-object-proxy=1.4.3=py37he774522_0
libarchive=3.4.2=h5e25573_0
libcurl=7.71.1=h2a8f88b_1
libiconv=1.15=h1df5818_7
liblief=0.10.1=ha925a31_0
libllvm9=9.0.1=h21ff451_0
libpng=1.6.37=h2a8f88b_0
libsodium=1.0.18=h62dcd97_0
libspatialindex=1.9.3=h33f27b4_0
libssh2=1.9.0=h7a1dbc1_1
libtiff=4.1.0=h56a325e_1
libuv=1.40.0=he774522_0
libxml2=2.9.10=h464c3ec_1
libxslt=1.1.34=he774522_0
llvmlite=0.33.0=py37ha925a31_0
locket=0.2.0=py37_1
lxml=4.5.2=py37h1350720_0
lz4-c=1.9.2=h62dcd97_1
lzo=2.10=he774522_2
m2w64-gcc-libgfortran=5.3.0=6
m2w64-gcc-libs=5.3.0=7
m2w64-gcc-libs-core=5.3.0=7
m2w64-gmp=6.1.0=2
m2w64-libwinpthread-git=5.0.0.4634.697f757=2
markdown=3.2.2=pypi_0
markupsafe=1.1.1=py37hfa6e2cd_1
matplotlib=3.1.3=py37_0
matplotlib-base=3.1.3=py37h64f37c6_0
mccabe=0.6.1=py37_1
menuinst=1.4.16=py37he774522_1
mistune=0.8.4=py37hfa6e2cd_1001
mkl=2020.1=216
mkl-service=2.3.0=py37hb782905_0
mkl_fft=1.0.15=py37h14836fe_0
mkl_random=1.1.0=py37h675688f_0
mock=4.0.2=py_0
more-itertools=8.4.0=py_0
mpc=1.1.0=h7edee0f_1
mpfr=4.0.2=h62dcd97_1
mpir=3.0.0=hec2e145_1
mpmath=1.1.0=py37_0
msgpack-python=1.0.0=py37h74a9793_1
msys2-conda-epoch=20160418=1
multipledispatch=0.6.0=py37_0
mypy_extensions=0.4.3=py37hc8dfbb8_2
navigator-updater=0.2.1=py37_0
nbconvert=5.6.1=py37_1
nbformat=5.0.7=py_0
ndim=0.1.4=pypi_0
networkx=2.4=py_1
ninja=1.10.1=py37h7ef1ec2_0
nltk=3.5=py_0
nose=1.3.7=py37_1004
notebook=6.1.1=py37_0
numba=0.51.0rc1=np1.11py3.7hf9181ef_g833c5907c_0
numexpr=2.7.1=py37h25d0782_0
numpy=1.19.1=py37h5510c5b_0
numpy-base=1.19.1=py37ha3acd2a_0
numpydoc=1.1.0=py_0
oauthlib=3.1.0=pypi_0
olefile=0.46=py37_0
openpyxl=3.0.4=py_0
openssl=1.1.1h=he774522_0
orthopy=0.8.4=pypi_0
packaging=20.4=py_0
pandas=1.0.1=py37h47e9c7a_0
pandoc=2.10.1=0
pandocfilters=1.4.2=py37_1
paramiko=2.7.1=py_0
parso=0.7.0=py_0
partd=1.1.0=py_0
path=15.0.0=py37_0
path.py=12.5.0=0
pathlib2=2.3.5=py37_1
pathspec=0.8.1=pyhd3deb0d_0
pathtools=0.1.2=py_1
patsy=0.5.1=py37_0
pep8=1.7.1=py37_0
pexpect=4.8.0=py37_1
pickleshare=0.7.5=py37_1001
pillow=7.2.0=py37hcc1f983_0
pip=20.2.2=py37_0
pkginfo=1.5.0.1=py37_0
plotly=4.9.0=pypi_0
pluggy=0.13.1=py37_0
ply=3.11=py37_0
powershell_shortcut=0.0.1=3
prometheus_client=0.8.0=py_0
prompt-toolkit=3.0.5=py_0
prompt_toolkit=3.0.5=0
protobuf=3.13.0=pypi_0
psutil=5.7.0=py37he774522_0
py=1.9.0=py_0
py-lief=0.10.1=py37ha925a31_0
pyasn1=0.4.8=pypi_0
pyasn1-modules=0.2.8=pypi_0
pycodestyle=2.6.0=py_0
pycosat=0.6.3=py37he774522_0
pycparser=2.20=py_2
pycrypto=2.6.1=py37he774522_10
pycurl=7.43.0.5=py37h7a1dbc1_0
pydocstyle=5.0.2=py_0
pyflakes=2.2.0=py_0
pygments=2.6.1=py_0
pylint=2.5.3=py37_0
pyls-black=0.4.6=pyh9f0ad1d_0
pyls-spyder=0.1.1=pyhd3deb0d_0
pynacl=1.4.0=py37h62dcd97_1
pyodbc=4.0.30=py37ha925a31_0
pyopenssl=19.1.0=py_1
pyparsing=2.4.7=py_0
pyqt=5.9.2=py37h6538335_2
pyreadline=2.1=py37_1
pyrsistent=0.16.0=py37he774522_0
pysocks=1.7.1=py37_1
pytables=3.6.1=py37h1da0976_0
pytest=6.0.1=py37_0
pytest-arraydiff=0.3=py37h39e3cac_0
pytest-astropy=0.8.0=py_0
pytest-astropy-header=0.1.2=py_0
pytest-doctestplus=0.5.0=py_0
pytest-openfiles=0.5.0=py_0
pytest-remotedata=0.3.2=py37_0
python=3.7.7=h81c818b_4
python-dateutil=2.8.1=py_0
python-jsonrpc-server=0.4.0=pyh9f0ad1d_0
python-language-server=0.36.1=pyhd8ed1ab_1
python-libarchive-c=2.9=py_0
python_abi=3.7=1_cp37m
pytorch=1.7.0=py3.7_cuda101_cudnn7_0
pytorch-lightning=0.9.0=pypi_0
pytz=2020.1=py_0
pywavelets=1.1.1=py37he774522_0
pywin32=227=py37he774522_1
pywin32-ctypes=0.2.0=py37_1001
pywinpty=0.5.7=py37_0
pyyaml=5.3.1=py37he774522_1
pyzmq=19.0.1=py37ha925a31_1
qdarkstyle=2.8.1=py_0
qt=5.9.7=vc14h73c81de_0
qtawesome=0.7.2=py_0
qtconsole=4.7.7=pyh9f0ad1d_0
qtpy=1.9.0=py_0
quadpy=0.16.2=pypi_0
regex=2020.10.15=py37he774522_0
requests=2.24.0=py_0
requests-oauthlib=1.3.0=pypi_0
retrying=1.3.3=py37_2
rope=0.17.0=py_0
rsa=4.6=pypi_0
rtree=0.9.4=py37h21ff451_1
ruamel_yaml=0.15.87=py37he774522_1
scikit-image=0.16.2=py37h47e9c7a_0
scikit-learn=0.22.1=py37h6288b17_0
scipy=1.4.1=py37h9439919_0
seaborn=0.10.0=py_0
see-rnn=1.15.1=pypi_0
send2trash=1.5.0=py37_0
setuptools=49.6.0=py37_0
simplegeneric=0.8.1=py37_2
simpleitk=2.0.1=py37ha925a31_0
singledispatch=3.4.0.3=py37_1000
sip=4.19.8=py37h6538335_0
six=1.15.0=py_0
snappy=1.1.8=h33f27b4_0
snowballstemmer=2.0.0=py_0
sortedcollections=1.2.1=py_0
sortedcontainers=2.2.2=py_0
soupsieve=2.0.1=py_0
sphinx=3.2.1=py_0
sphinxcontrib=1.0=py37_1
sphinxcontrib-applehelp=1.0.2=py_0
sphinxcontrib-devhelp=1.0.2=py_0
sphinxcontrib-htmlhelp=1.0.3=py_0
sphinxcontrib-jsmath=1.0.1=py_0
sphinxcontrib-qthelp=1.0.3=py_0
sphinxcontrib-serializinghtml=1.1.4=py_0
sphinxcontrib-websupport=1.2.4=py_0
spyder=4.2.0=py37h03978a9_0
spyder-kernels=1.10.0=py37h03978a9_0
sqlalchemy=1.3.18=py37he774522_0
sqlite=3.32.3=h2a8f88b_0
statsmodels=0.11.0=py37he774522_0
sympy=1.6.2=py37_0
tbb=2020.0=h74a9793_0
tblib=1.6.0=py_0
tensorboard=2.2.0=pypi_0
tensorboard-plugin-wit=1.7.0=pypi_0
termcolor=1.1.0=py37_1
terminado=0.8.3=py37_0
testpath=0.4.4=py_0
threadpoolctl=2.1.0=pyh5ca1d4c_0
three-merge=0.1.1=pyh9f0ad1d_0
tk=8.6.10=he774522_0
toml=0.10.1=py_0
toolz=0.10.0=py_0
torchvision=0.8.1=py37_cu101
tornado=6.0.4=py37he774522_1
tqdm=4.48.2=py_0
traitlets=4.3.3=py37_0
typed-ast=1.4.1=py37he774522_0
typing_extensions=3.7.4.3=py_0
ujson=4.0.1=py37h1834ac0_1
unicodecsv=0.14.1=py37_0
urllib3=1.25.10=py_0
vc=14.1=h0510ff6_4
vs2015_runtime=14.16.27012=hf0eaf9b_3
watchdog=0.10.3=py37_0
wcwidth=0.2.5=py_0
webencodings=0.5.1=py37_1
werkzeug=1.0.1=py_0
wheel=0.34.2=py37_0
widgetsnbextension=3.5.1=py37_0
win_inet_pton=1.1.0=py37_0
win_unicode_console=0.5=py37_0
wincertstore=0.2=py37_0
winpty=0.4.3=4
wrapt=1.11.2=py37he774522_0
xlrd=1.2.0=py37_0
xlsxwriter=1.2.9=py_0
xlwings=0.20.2=py37_0
xlwt=1.3.0=py37_0
xmltodict=0.12.0=py_0
xz=5.2.5=h62dcd97_0
yaml=0.2.5=he774522_0
yapf=0.30.0=py_0
zeromq=4.3.2=ha925a31_2
zict=2.0.0=py_0
zipp=3.1.0=py_0
zlib=1.2.11=h62dcd97_4
zope=1.0=py37_1
zope.event=4.5.0=py37_0
zope.interface=5.1.2=py37he774522_0
zstd=1.4.5=h04227a9_0
```

</details>

<details>
  <summary>Help > Dependencies</summary>

```python
# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.5.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.17.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.5.3 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20200814 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.1 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.1.3 (OK)
numpy >=1.7                     :  1.19.1 (OK)
pandas >=1.1.1                  :  1.0.1 (NOK)
scipy >=0.17.0                  :  1.4.1 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

</details>

**Comment by impact27** [comment] 2020-11-22 09:41
I tested on windows with spyder 4.2.0 and couldn't reproduce. Are you running the kernel in another environment? Because I can't reproduce, I can only give you very generic advice. Have you tried basic troubleshooting?
    * Restarted Spyder
    * Reset preferences with ``spyder --reset``
    * Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * Tried the other applicable steps from the Troubleshooting Guide

**Comment by OverLordGoldDragon** [comment] 2020-11-22 16:05
@impact27 1 doesn't help, but I'll keep 3 in mind next time I do a reinstall; currently it's not worth the trouble. Before I try 2, will I be able to fully restore preferences via `spyder.ini` and `transient.ini` in `.spyder-py3/config`?

**Comment by impact27** [comment] 2020-11-22 16:17
@spyder-ide/core-developers Could you advise on how to back up the preferences?
As an alternative to 3, you could run spyder from a new env:
```
conda create -n spyder-dev python=3
conda activate spyder-dev
conda install -c conda-forge spyder
spyder
```

**Comment by OverLordGoldDragon** [comment] 2020-11-22 17:01
@impact27 Aand nope, didn't work. 

<details>
  <summary>env stuff</summary>

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
alabaster=0.7.12=py_0
appdirs=1.4.4=pyh9f0ad1d_0
argh=0.26.2=pyh9f0ad1d_1002
astroid=2.4.2=py38h32f6830_1
async_generator=1.10=py_0
atomicwrites=1.4.0=pyh9f0ad1d_0
attrs=20.3.0=pyhd3deb0d_0
autopep8=1.5.4=pyh9f0ad1d_0
babel=2.9.0=pyhd3deb0d_0
backcall=0.2.0=pyh9f0ad1d_0
backports=1.0=py_2
backports.functools_lru_cache=1.6.1=py_0
bcrypt=3.2.0=py38h1e8a9f7_1
black=20.8b1=py_1
bleach=3.2.1=pyh9f0ad1d_0
brotlipy=0.7.0=py38hab1e662_1001
ca-certificates=2020.11.8=h5b45459_0
certifi=2020.11.8=py38haa244fe_0
cffi=1.14.3=py38h0e640b1_1
chardet=3.0.4=py38h9bdc248_1008
click=7.1.2=pyh9f0ad1d_0
cloudpickle=1.6.0=py_0
colorama=0.4.4=pyh9f0ad1d_0
cryptography=3.2.1=py38hd8c33c5_0
dataclasses=0.7=pyhb2cacf7_7
decorator=4.4.2=py_0
defusedxml=0.6.0=py_0
diff-match-patch=20200713=pyh9f0ad1d_0
docutils=0.16=py38h9bdc248_2
entrypoints=0.3=pyhd8ed1ab_1003
flake8=3.8.4=py_0
future=0.18.2=py38haa244fe_2
helpdev=0.7.1=pyhd8ed1ab_0
icu=67.1=h33f27b4_0
idna=2.10=pyh9f0ad1d_0
imagesize=1.2.0=py_0
importlib-metadata=2.0.0=py_1
importlib_metadata=2.0.0=1
intervaltree=3.0.2=py_0
ipykernel=5.3.4=py38h7b7c402_1
ipython=7.19.0=py38hc5df569_0
ipython_genutils=0.2.0=py_1
isort=5.6.4=py_0
jedi=0.17.2=py38haa244fe_1
jinja2=2.11.2=pyh9f0ad1d_0
jpeg=9d=h8ffe710_0
jsonschema=3.2.0=py_2
jupyter_client=6.1.7=py_0
jupyter_core=4.7.0=py38haa244fe_0
jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
keyring=21.5.0=py38haa244fe_0
lazy-object-proxy=1.4.3=py38h1e8a9f7_2
libclang=10.0.1=default_hf44288c_1
libpng=1.6.37=h1d00b33_2
libsodium=1.0.18=h8d14728_1
libspatialindex=1.9.3=he025d50_3
markupsafe=1.1.1=py38hab1e662_2
mccabe=0.6.1=py_1
mistune=0.8.4=py38h294d835_1002
mypy_extensions=0.4.3=py38h32f6830_2
nbclient=0.5.1=py_0
nbconvert=6.0.7=py38haa244fe_3
nbformat=5.0.8=py_0
nest-asyncio=1.4.3=pyhd8ed1ab_0
numpydoc=1.1.0=py_1
openssl=1.1.1h=he774522_0
packaging=20.4=pyh9f0ad1d_0
pandoc=2.11.2=h8ffe710_0
pandocfilters=1.4.2=py_1
paramiko=2.7.2=pyh9f0ad1d_0
parso=0.7.0=pyh9f0ad1d_0
pathspec=0.8.1=pyhd3deb0d_0
pathtools=0.1.2=py_1
pexpect=4.8.0=pyh9f0ad1d_2
pickleshare=0.7.5=py_1003
pip=20.2.4=py_0
pluggy=0.13.1=py38h9bdc248_3
prompt-toolkit=3.0.8=pyha770c72_0
psutil=5.7.3=py38hab1e662_0
ptyprocess=0.6.0=py_1001
pycodestyle=2.6.0=pyh9f0ad1d_0
pycparser=2.20=pyh9f0ad1d_2
pydocstyle=5.1.1=py_0
pyflakes=2.2.0=pyh9f0ad1d_0
pygments=2.7.2=py_0
pylint=2.6.0=py38h32f6830_1
pyls-black=0.4.6=pyh9f0ad1d_0
pyls-spyder=0.1.1=pyhd3deb0d_0
pynacl=1.4.0=py38hd4486f3_2
pyopenssl=19.1.0=py_1
pyparsing=2.4.7=pyh9f0ad1d_0
pyqt=5.12.3=py38h7ae7562_4
pyqt5-sip=4.19.18=pypi_0
pyqtchart=5.12=pypi_0
pyqtwebengine=5.12.1=pypi_0
pyrsistent=0.17.3=py38h294d835_1
pysocks=1.7.1=py38h9bdc248_2
python=3.8.6=h60c2a47_0_cpython
python-dateutil=2.8.1=py_0
python-jsonrpc-server=0.4.0=pyh9f0ad1d_0
python-language-server=0.36.1=pyhd8ed1ab_1
python_abi=3.8=1_cp38
pytz=2020.4=pyhd8ed1ab_0
pywin32=228=py38h1e8a9f7_0
pywin32-ctypes=0.2.0=py38h32f6830_1002
pyyaml=5.3.1=py38hab1e662_1
pyzmq=20.0.0=py38h7a0e47e_1
qdarkstyle=2.8.1=pyhd8ed1ab_2
qt=5.12.9=hb2cf2c5_0
qtawesome=1.0.1=pyh9f0ad1d_0
qtconsole=4.7.7=pyh9f0ad1d_0
qtpy=1.9.0=py_0
regex=2020.11.13=py38h294d835_0
requests=2.25.0=pyhd3deb0d_0
rope=0.18.0=pyh9f0ad1d_0
rtree=0.9.4=py38h8b54edf_2
setuptools=49.6.0=py38h9bdc248_2
six=1.15.0=pyh9f0ad1d_0
snowballstemmer=2.0.0=py_0
sortedcontainers=2.3.0=pyhd8ed1ab_0
sphinx=3.3.1=pyhd8ed1ab_0
sphinxcontrib-applehelp=1.0.2=py_0
sphinxcontrib-devhelp=1.0.2=py_0
sphinxcontrib-htmlhelp=1.0.3=py_0
sphinxcontrib-jsmath=1.0.1=py_0
sphinxcontrib-qthelp=1.0.3=py_0
sphinxcontrib-serializinghtml=1.1.4=py_0
spyder=4.2.0=py38haa244fe_0
spyder-kernels=1.10.0=py38haa244fe_0
sqlite=3.33.0=h2a8f88b_0
testpath=0.4.4=py_0
three-merge=0.1.1=pyh9f0ad1d_0
toml=0.10.2=pyhd8ed1ab_0
tornado=6.1=py38h294d835_0
traitlets=5.0.5=py_0
typed-ast=1.4.1=py38h294d835_1
typing_extensions=3.7.4.3=py_0
tzdata=2020d=h14c3975_0
ujson=4.0.1=py38h7ae7562_1
urllib3=1.25.11=py_0
vc=14.1=h0510ff6_4
vs2015_runtime=14.16.27012=hf0eaf9b_3
watchdog=0.10.4=py38haa244fe_0
wcwidth=0.2.5=pyh9f0ad1d_2
webencodings=0.5.1=py_1
wheel=0.35.1=pyhd3eb1b0_0
win_inet_pton=1.1.0=py38h32f6830_1
wincertstore=0.2=py38h32f6830_1005
wrapt=1.11.2=py38h1e8a9f7_1
yaml=0.2.5=he774522_0
yapf=0.30.0=pyh9f0ad1d_0
zeromq=4.3.3=h0e60522_3
zipp=3.4.0=py_0
zlib=1.2.11=h62dcd97_4
```

</details>

**Comment by ccordoba12** [comment] 2020-11-22 17:13
> Could you advise on how to back up the preferences?

As @OverLordGoldDragon mentioned, copying `spyder.ini` and `transient.ini` to another location and then moving them back to `.spyder-py3/config` will restore them.

**Comment by OverLordGoldDragon** [comment] 2020-11-22 18:01
Combining 2 and 3, same result. Also the default toolbar icons are huge.

@impact27 So, if namespace isn't supposed to clear, then what else does `Remove all variables before execution` do? Without it checked the `a` stays pristinely there, but that was always the case.

**Comment by impact27** [comment] 2020-11-22 18:17
Ok so it was the settings. You can disable this option to keep the variables that are not affected by the script you are running. I am not sure running the startup script after every script is a good idea because it might change the result of the script you just ran.

**Comment by OverLordGoldDragon** [comment] 2020-11-22 18:27
@impact27 Valid point, but a simple solution is an extra option (e.g. "always rerun startup script with `runfile`"). The "remove all variables" does help my use as I frequently define (potentially large) arrays whose variable names aren't overridden by ran script. Of course one can explicitly `import` the startup script to run it, but it's between an extra line in every script you run and one in the already-crowded Preferences menu.

**Comment by OverLordGoldDragon** [comment] 2020-11-22 23:25
@ccordoba12 Unfortunately they didn't preserve PYTHONPATH

**Comment by ccordoba12** [comment] 2020-11-23 05:07
> Valid point, but a simple solution is an extra option (e.g. "always rerun startup script with runfile").

We're reluctant to add options to cover specific use cases. However, what we could do is to automatically load the startup script by default after removing all variables.

@impact27, what do you think?

**Comment by impact27** [comment] 2020-11-23 06:58
As I said, running the startup script after every runfile by default could be a bit confusing. For example if you set a variable `myvar` in the startup script and in the file you run, you would not be able to preserve the script's `myvar`.
As a workaround I would advise that the startup script adds whatever you want to keep to the `builtins` module. That way it will survive the `clear`, which is really what you want:
```
import builtins
def myfunc(): print(0)
builtins.myfunc = myfunc
%clear
myfunc()
0
```

**Comment by ccordoba12** [comment] 2020-11-23 21:09
Ok, I agree with @impact27 about this.

Sorry @OverLordGoldDragon but I'm going to close this one as "won't fix" (you can use the workaround provided by @impact27).

**Closed** 2020-11-23 21:10 UTC
Labels: resolution:Wontfix

**Comment by OverLordGoldDragon** [comment] 2020-11-23 21:11
Fair enough. And interesting bot you have there.
