### ISSUE TITLE
Help pane won't go away

### ISSUE THREAD

**Issue by lukecherveny** [spyder-ide/spyder#16382] opened 2021-09-08 17:43 UTC
### What steps will reproduce the problem?

The help pane keeps reappearing when Spyder reopens. If I close it when it's a quadrant, it comes back when Spyder restarts. If I unlock panes, attach the help pane to the console pane so it is a tab and center focus on the console, then when Spyder restarts the focus is on the help pane.

tl;dr: I hate the help pane and don't want to see it

**Comment by dalthviz** [comment] 2021-09-08 18:24
Hi @lukecherveny thanks for the feedback! I was able to reproduce this.

@ccordoba12 is this an expected behavior?

**Comment by ccordoba12** [comment] 2021-09-08 20:11
Hey @lukecherveny, @dalthviz, this is a duplicate of issue #15331. We'll try to fix it in our next release.

**Closed by ccordoba12** 2021-09-08 20:11 UTC
Labels: status:Awaiting Followup, status:Reproduced
