### ISSUE TITLE
Spyder editor issue: when graphic backend is changed to automatic, plot will not show unless editor is closed

### ISSUE THREAD

**Issue by ariannajojo** [spyder-ide/spyder#6991] opened 2018-04-20 02:29 UTC
## Problem Description
Hello, I'm using the editor for Spyder 3.2.8 to graph plots for a class. I need them to appear in a separate window. It was recently updated from 3.1.4, and now the graphs appear inline when I run the file. I researched how to change it with Tools>Preferences>iPython console>graphics. But even setting it to automatic (or any of the other options) and restarting Spyder causes the console to continue "connecting to the server" without ever connecting. When I run the code, the graph does appear in another window but only when I close Spyder entirely, andI can't view it for long since it closes along with it.

For some context, I am mainly using a conda created environment to do this, but the same result occur inside and outside the environment.

I really need the plots to appear in a seperate window so I can enlarge them since the graph comes out too small when saving it as a PNG (or using Snipping tool). Any help is appreciated.
### What steps will reproduce the problem?

1. Updating/resetting spyder
2. Attempting this inside or outside a conda environment
3. Restarting spyder and the linux terminal

## Package Versions

* Spyder: 3.2.8
* Python: 2.7
* Qt: 5.9.5
* PyQt: 5.9.2
* Operating System: Linux

### Dependencies
IPython >=4.0;<6.0:  5.3.0 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.6.4 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
rope >=0.9.4      :  0.9.4 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
sympy >=0.7.3     :  1.0 (OK)

**Comment by CAM-Gerlach** [comment] 2018-04-20 06:10
Thanks for reporting.

> I really need the plots to appear in a seperate window so I can enlarge them since the graph comes out too small when saving it as a PNG (or using Snipping tool).

This is entirely unnecessary, and far better done just by using ``matplotlib``'s ``savefig`` command (or an equivalent in any other half-decent plotting package.

Nevertheless, this appears to be a duplicate of #6452 and is an upstream problem, not anything with Spyder , and can likely be fixed by a simple ``conda install ipykernal`` Please try that, 
along with the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by CAM-Gerlach** [comment] 2018-04-27 22:57
Closed due to lack of response as a likely duplicate. If you can provide more information, and you're sure it is not a duplicate, please reopen and do so. Thanks.

**Closed by CAM-Gerlach** 2018-04-27 22:57 UTC
Labels: status:Awaiting Followup
