### ISSUE TITLE
Home button jumps to the second character instead of the start of the line 

### ISSUE THREAD

**Issue by ilayn** [spyder-ide/spyder#4801] opened 2017-07-24 11:34 UTC
This is really hard to explain but I'll just leave it as a reference in case others might find it.

## Description of your problem

At certain instances when Home key is pressed in the IPython console the cursor jumps to the second column instead of the first column. Resulting with 
![image](https://user-images.githubusercontent.com/1303842/28521394-be5e1772-7073-11e7-9a70-e3fc1d8551dd.png)

**What steps will reproduce the problem?**

Not applicable. Appears sporadically. 

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version: 5.8.0 
* PyQt Version: 5.8.2
* Operating system: Win 10 (64bit)

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment] 2017-07-24 15:05
Thanks for reporting.

**Comment by ccordoba12** [comment] 2017-07-26 02:38
This is a duplicate of issue #4441.

**Closed by ccordoba12** 2017-07-26 02:38 UTC
Labels: component:IPython Console, resolution:Duplicate, type:Bug
