### ISSUE TITLE
Using list of tokenized lists with gensim results in AttributeError: 'QContextMenuEvent' object has no attribute 'button'

### ISSUE THREAD

**Issue by niteshge** [spyder-ide/spyder#5974] opened 2017-12-13 13:55 UTC
## Description

**What steps will reproduce the problem?**

```
import gensim
# let X be a list of tokenized texts (i.e. list of lists of tokens)
model = gensim.models.Word2Vec(X, size=100)
w2v = dict(zip(model.wv.index2word, model.wv.syn0))
```

This part of code could reproduce it for me
**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/nitesh/anaconda3/lib/python3.6/site-packages/qtconsole/console_widget.py", line 420, in eventFilter
    event.button() == QtCore.Qt.MidButton and \
AttributeError: 'QContextMenuEvent' object has no attribute 'button'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-13 15:51
Thanks for reporting. If you could post some code to replicate a minimal tokenized list as you describe, that would be helpful in reproducing this cleanly. Does the same error occur in plain `qtconsole` (I presume not in plain `iPython` since it doesn't depend on Qt)?

**Comment by niteshge** [comment] 2017-12-17 18:27
Hi There,
I should say it is hard to reproduce, because this case doesn’t happen often. However, I see there must be some issue because the spyder left untouched for say one hour and I go back to start my coding the responsiveness doesn't work, for example, auto complete doesn't work and snippets of my code don't execute, it simply shows executing for hours. But if I restart the IDE works well. Personally I have restarted the IDE many times a day just to make it work. Please let me know if there is a fix for this. I feel thats really important to seamlessly code.
And for more details, I got spyder with anaconda navigator.

**Comment by CAM-Gerlach** [comment] 2017-12-18 04:03
Thanks for the update; we certainly want Spyder to be as stable and usable as possible for our users. Code completion and help ("Command-I") not working after being left idle for significant lengths of time, or the machine going to sleep, is a known issue ( #5613 ) that I myself experience frequently and will be fixed and made much more stable in the new architecture currently being implemented for Spyder 4, due out later next year. 

However, if you also referring to arbitrary user code is not executing and hanging the console forever would seem to be a somewhat different problem—by any chance, does it have to do with running parallel code using run file (that's a consistent, known problem with IPython/qtconsole for me)? If you try the same section of code repeatedly in a given session, does occur consistently with that bit, or only sporadically run to run? Does it happen to any and all code in the file one it starts, or only certain segments? Any commonality between them—can you isolate it to something in particular? Thanks.

**Comment by niteshge** [comment] 2017-12-18 19:38
I often see code getting hanged only when I leave the spyder idle for a
while. As you explained this could be a part of know issue(#5613). However,
this occurs randomly for any part of the code there is no particular
segment, hence it is kind of difficult to showcase the code which can
reproduce this issue. But I strongly anticipate this could part of the same
issue(#5613). I am waiting to see stable and more feature in the next
release.

Thanks,
Nitesh Kumar N
ᐧ

**Comment by CAM-Gerlach** [comment] 2017-12-23 21:19
Hey @niteshge , anything new? If you aren't able to isolate this behavior to Spyder and it can't be reproduced, or you think it is a duplicate, then it might be best to close this issue unless/until you do. Thanks for your detailed followups trying to track this down.

**Comment by CAM-Gerlach** [comment] 2018-01-16 07:47
Given we weren't able to isolate this, this issue will be closed for now. If you are able to do so, or have more relevant information to add, then please do so and reopen if warranted. Thanks!

**Closed by CAM-Gerlach** 2018-01-16 07:47 UTC
Labels: status:AwaitingFollowup
