### ISSUE TITLE
clicked save icon

### ISSUE THREAD

**Issue by rwcooper** [spyder-ide/spyder#9331] opened 2019-05-12 05:46 UTC
### What steps will reproduce the problem?

# added a print command to my script
print("Trainer was 10943")
# clicked on save to save the script

### Traceback
```python-traceback
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spyder/widgets/calltip.py", line 122, in hideEvent
    self._cursor_position_changed)
TypeError: 'method' object is not connected
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.3
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Darwin 16.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.4 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-23 10:52
This is a duplicate of issue #9221.

**Closed by ccordoba12** 2019-06-23 10:52 UTC
