### ISSUE TITLE
Creating DataFrames in Python or IPython consoles make Spyder 2.3.6 to hang

### ISSUE THREAD

**Issue by mshashanka** [spyder-ide/spyder#2654] opened 2015-08-28 13:40 UTC
This is similar to https://github.com/spyder-ide/spyder/issues/2652.

I just upgraded to spyder 2.3.6. I am using pandas 0.16.2 and IPython 4.0 on OS X Yosemite. Spyder essentially crashes (it hangs and I have to force quit the application) when I try to run a code snippet like the one below in the spyder ipython console. The same code works just fine if I open ipython in a terminal window and run it.

```python
import pandas as pd
df = pd.read_csv('csv_file.csv')
tmp = df.groupby(['field1', 'field2']).agg( {'field3':['sum'], 'field4':['sum']})
```

**Comment by ccordoba12** [comment] 2015-08-28 16:13
Thanks for reporting. I'll try to fix it ASAP.

Question: was this working for you in Spyder **2.3.5.2**?

**Comment by mshashanka** [comment] 2015-08-28 16:17
Thanks! Yes, it works fine in 2.3.5.2, that's what I'm using now.

M Shashanka




On Fri, Aug 28, 2015 at 9:13 AM -0700, "Carlos Cordoba" <notifications@github.com> wrote:












Thanks for reporting. I'll try to fix it ASAP.



Question: was this working for you in Spyder 2.3.5.2?

**Comment by msweier** [comment] 2015-09-03 16:55
Am also running spyder 2.3.6 w/ pandas 0.16.2 and ipython 4.0.1 on OS X Yosemite and have the same issue when using the pandas pivot function. This can be avoided by shutting variable explorer panel.

**Comment by ccordoba12** [comment] 2015-09-03 19:33
@msweier, this error will be fixed in 2.3.7. Sorry for the inconvenience :-)

**Comment by msweier** [comment] 2015-09-03 19:43
No problem thanks!

**Comment by d1manson** [comment] 2015-09-08 17:04
I'm having the same issue, even just doing `x = pd.DataFrame(np.ones(10))` causes a crash when the variable explorer is open.
..a quick dig around in variable explorer code didn't seem to reveal much - it's quite complicated down there!

**Comment by ccordoba12** [comment] 2015-09-30 03:48
Just for the record: this happens only in Python **2**. Python 3 seems immune to this bug :-)

**Comment by ccordoba12** [comment] 2015-09-30 04:05
This was caused by trying to fix issue #2514.

**Closed** 2015-09-30 04:09 UTC
Labels: bug, Variable-Explorer

**Comment by stonebig** [comment] 2015-09-30 17:15
thanks ! would it be possible to have an earlier 2.3.7 with this important fix ?

**Comment by ccordoba12** [comment] 2015-09-30 20:12
@stonebig, yes, of course. That's why I tagged this issue with the 2.3.7 milestone. I hope to release it this weekend :-)

**Comment by vrajs5** [comment] 2015-10-19 03:55
I think problem is still not resolved with 2.3.7 with following other packages
```
    ipython:   4.0.0-py27_0
    jedi:      0.9.0-py27_0  
    qtconsole: 4.1.0-py27_0
    alabaster: 0.7.3-py27_0
    sphinx:     1.3.1-py27_0
    spyder:    2.3.7-py27_1
```

**Comment by stonebig** [comment] 2015-10-19 12:12
you may try to downgrade to Jedi 0.8.1.

**Comment by vrajs5** [comment] 2015-10-20 03:56
@stonebig - nope jedi downgrade didn't work out...

**Comment by stonebig** [comment] 2015-10-20 08:42
ok, so today, with spyder git of October 14th:
- first start of spyder qtconsole fails
- second start works
![spyder_3dev_python_27_dataframetest](https://cloud.githubusercontent.com/assets/4312421/10602186/166521c0-7717-11e5-9d61-69ab2391b5bf.GIF)

````
!pip list
adodbapi (2.6.0.7)
alabaster (0.7.6)
astroid (1.3.6)
Babel (2.1.1)
backports.ssl-match-hostname (3.4.0.2)
baresql (0.7.2)
bcolz (0.11.3)
beautifulsoup4 (4.4.1)
blaze (0.8.3)
blosc (1.2.8)
bloscpack (0.9.0)
bokeh (0.10.0)
bqplot (0.3.8)
brewer2mpl (1.4.1)
castra (0.1.6)
certifi (2015.9.6.1)
cffi (1.2.1)
click (5.0)
colorama (0.3.3)
configparser (3.5.0b2)
cvxopt (1.1.7)
cx-Freeze (4.3.4)
cycler (0.9.0)
cyordereddict (0.2.2)
Cython (0.23.4)
cytoolz (0.7.3)
dask (0.7.3)
datashape (0.4.7)
db.py (0.4.4)
decorator (4.0.4)
dill (0.2.4)
docopt (0.6.2)
docutils (0.12)
enum34 (1.0.4)
Flask (0.10.1)
formlayout (1.0.15)
funcsigs (0.4)
functools32 (3.2.3.post2)
greenlet (0.4.9)
guidata (1.7.0b5)
guiqwt (3.0.0b6)
h5py (2.5.0)
holoviews (1.3.2)
husl (4.0.3)
ipykernel (4.1.0)
ipyparallel (4.0.2)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
ipywidgets (4.0.3)
itsdangerous (0.24)
jedi (0.8.1)
Jinja2 (2.8)
joblib (0.9.2)
jsonschema (2.5.1)
julia (0.1.1.8)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
Keras (0.2.0)
llvmlite (0.6.0)
lmfit (0.9.1)
locket (0.2.0)
logilab-common (1.1.0)
lxml (3.4.4)
MarkupSafe (0.23)
matplotlib (1.5.0rc2)
mingwpy (0.1.0b3)
mistune (0.7.1)
mpld3 (0.2)
multipledispatch (0.4.8)
mysql-connector-python (2.0.4)
nbconvert (4.0.0)
nbformat (4.0.1)
netCDF4 (1.2.1)
networkx (1.10)
nltk (3.0.5)
nose (1.3.7)
notebook (4.0.6)
numba (0.20.0)
numexpr (2.4.4)
numpy (1.9.3)
numpydoc (0.5)
oct2py (3.3.3)
odo (0.3.4)
pandas (0.17.0)
pandas-datareader (0.2.0)
param (1.3.2)
partd (0.3.2)
path.py (8.1.2)
patsy (0.4.0)
pep8 (1.6.2)
pg8000 (1.10.2)
pickleshare (0.5)
Pillow (3.0.0)
pip (7.1.2)
pkginfo (1.2.1)
prettytable (0.7.2)
psutil (3.2.2)
PuLP (1.5.9)
py (1.4.30)
PyAudio (0.2.8)
pybars3 (0.9.1)
pycparser (2.14)
pyflakes (0.9.2)
Pygments (2.0.2)
pyhdf (0.8.3)
pylint (1.4.3)
PyMeta3 (0.5.1)
pymongo (3.0.3)
pyodbc (3.0.10)
PyOpenGL (3.1.0)
pyparsing (2.0.3)
PyQt4 (4.11.4)
PyQtdesignerplugins (1.1)
pyqtgraph (0.9.10)
PyQwt (5.2.1)
pyserial (2.7)
pytest (2.8.2)
python-dateutil (2.4.2)
PythonQwt (0.3.0)
pytz (2015.6)
pywin32 (219)
PyYAML (3.11)
pyzmq (14.7.0)
qtconsole (4.1.0)
redis (2.10.3)
reportlab (3.2.0)
requests (2.8.1)
requests-toolbelt (0.4.0)
rope (0.10.2)
rpy2 (2.7.2)
Rx (1.2.3)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scilab2py (0.6)
scipy (0.16.0)
seaborn (0.7.0.dev0)
setuptools (18.4)
simplegeneric (0.8.1)
simplejson (3.8.0)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.9)
spyder (3.0.0.dev0)
SQLAlchemy (1.0.8)
sqlite-bro (0.8.10)
sqlparse (0.1.16)
statsmodels (0.6.1)
sympy (0.7.6.1)
tables (3.2.2)
Theano (0.7.0)
toolz (0.7.4)
tornado (4.2.1)
traitlets (4.0.0)
twine (1.6.3)
twitter (1.17.1)
ViTables (2.1)
Werkzeug (0.10.4)
wheel (0.26.0)
winpython (1.2)
xlrd (0.9.4)
XlsxWriter (0.7.6)
xray (0.6.0)

````

**Comment by sean-violante-lendico** [comment] 2015-10-20 09:02
@vrajs5,  there is a separate bug fro empty dataframes!  have you tried that fix
https://github.com/spyder-ide/spyder/issues/2744

**Comment by stonebig** [comment] 2015-10-20 11:38
no issue whatsoever with spyder3.0dev of yesterday night, even on Python 2.7.
