### ISSUE TITLE
I don't think I have any kinda error or bug in here.

### ISSUE THREAD

**Issue by MasterKavi-24** [spyder-ide/spyder#13612] opened 2020-08-24 03:08 UTC
### What steps will reproduce the problem?

#Seriously I don't think I have any errors here. If it is there...
#I don't know what that is. 

### Traceback
```python-traceback
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\projects\plugin.py", line 283, in _create_project
    self.open_project(path=path)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\projects\plugin.py", line 337, in open_project
    self.restart_consoles()
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\projects\plugin.py", line 520, in restart_consoles
    self.main.ipyconsole.restart()
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1088, in restart
    self.create_new_client(give_focus=False)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 665, in create_new_client
    interpreter_versions=self.interpreter_versions(),
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 865, in interpreter_versions
    proc = programs.run_shell_command(cmd)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\utils\programs.py", line 176, in run_shell_command
    return subprocess.Popen(cmdstr, **subprocess_kwargs)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\projects\plugin.py", line 279, in create_new_project
    self.restart_consoles()
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\projects\plugin.py", line 520, in restart_consoles
    self.main.ipyconsole.restart()
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1088, in restart
    self.create_new_client(give_focus=False)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 665, in create_new_client
    interpreter_versions=self.interpreter_versions(),
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 865, in interpreter_versions
    proc = programs.run_shell_command(cmd)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\site-packages\spyder\utils\programs.py", line 176, in run_shell_command
    return subprocess.Popen(cmdstr, **subprocess_kwargs)
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "f:\kavipriyan\pendrive\pycondajavacharm\python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by steff456** [comment] 2020-08-24 17:53
Hi @MasterKavi-24,

Can you please tell us what steps are you doing to encounter this error and upload a gif or an image? In this way we can try to reproduce it and see how to fix it.

**Comment by ccordoba12** [comment] 2020-08-24 18:21
@steff456, I think a way to reproduce this is the following:

* Create a new conda environment with Python and spyder-kernels (let's call it `test-env`).
* Change the Python interpreter in Preferences to select that environment.
* Start a new console to check that things are working as expected.
* Remove `test-env` outside Spyder.
* Try to create a new console.

The last step should generate the error reported by @MasterKavi-24.

**Comment by ccordoba12** [comment] 2020-08-24 18:21
@steff456, please try those steps to see if you reproduce this error.

**Comment by steff456** [comment] 2020-09-09 20:35
I tried to reproduce it macOS, and when I remove the environment outside Spyder and try to create a new console then it creates one in the base environment.

![image](https://user-images.githubusercontent.com/20992645/92650351-fd3d2f00-f2b1-11ea-9c87-1556e054229f.png)

**Comment by ccordoba12** [comment] 2020-09-10 01:08
Closing as a duplicate of #13731, where I told @MasterKavi-24 to use Anaconda instead of pip.

@MasterKavi-24, please don't report this problem anymore unless you're able to reproduce it with Anaconda.

**Closed by ccordoba12** 2020-09-10 01:08 UTC
Labels: status:Awaiting Followup
