### ISSUE TITLE
Feature request: Save / switch python interpreter according to project settings

### ISSUE THREAD

**Issue by physici** [spyder-ide/spyder#20527] opened 2023-02-13 08:31 UTC
Nowadays I'm working a lot with virtual environments and poetry for my projects. Although I love Spyder it is cumbersome that I always have to change the settings for the python interpreter manually when switching projects so that it points to correct the virtual env.

Would it be possible to save the path to the python interpreter in the project configuration folder? And, more importantly, switch to the specified python interpreter when the project is opened?

Maybe you can point me to the Spyder core files where that might be implemented and I try it myself....

Thanks,
Rainer

**Comment by pank** [comment] 2023-02-13 17:05
I think that is #11362

**Comment by ccordoba12** [comment] 2023-02-13 18:42
Hey @physici, thanks for reporting. @pank is right in the sense that it's a duplicate of issue #11362.

We'll try to address this shortcoming in Spyder 6, to be released in the second half of the year.

**Closed by ccordoba12** 2023-02-13 18:42 UTC
