### ISSUE TITLE
console error when typing (

### ISSUE THREAD

**Issue by iAvicenna** [spyder-ide/spyder#17466] opened 2022-03-10 18:04 UTC
### What steps will reproduce the problem?

Any time I type ( or delete a ( in the console I get this error.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/avicenna/anaconda3/envs/spyder-cf/lib/python3.10/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/avicenna/anaconda3/envs/spyder-cf/lib/python3.10/site-packages/spyder/plugins/ipythonconsole/widgets/help.py", line 170, in _handle_inspect_reply
    self._control.show_calltip(
  File "/home/avicenna/anaconda3/envs/spyder-cf/lib/python3.10/site-packages/spyder/widgets/mixins.py", line 603, in show_calltip
    self.calltip_widget.show_tip(point, text, [])
  File "/home/avicenna/anaconda3/envs/spyder-cf/lib/python3.10/site-packages/spyder/widgets/calltip.py", line 505, in show_tip
    point.setY(adjusted_point.y() - tip_height - padding)
TypeError: setY(self, int): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.10.2
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.14.0-1024-oem

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.3 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment] 2022-03-10 18:58
Hi @iAvicenna thank you for the feedback! This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/17130 . The related fix will be available with our next release (Spyder 5.3.0). For the moment to workaround this error you will need to use Python <= 3.9

I will close this as a duplicate but let us know if something of the above helps

**Closed by dalthviz** 2022-03-10 18:58 UTC
Labels: resolution:Duplicate
