### ISSUE TITLE
ow!!error

### ISSUE THREAD

**Issue by jesen8** [spyder-ide/spyder#6785] opened 2018-03-18 02:16 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\console_widget.py", line 413, in eventFilter
    return self._event_filter_console_keypress(event)
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 108, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\console_widget.py", line 1425, in _event_filter_console_keypress
    self.copy()
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\frontend_widget.py", line 249, in copy
    was_newline = text[-1] == '\n'
IndexError: string index out of range

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-03-18 03:09
Thanks for reporting. This is the same error as #5434 and a number of others that were reported but lacked the information needed to reproduce them. I could not reproduce it by the method suggested there, at least naively. Therefore, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). 

Also, if it occurs again, please reference [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!

**Comment by ccordoba12** [comment] 2018-03-18 17:03
This is an error in the `qtconsole` package, not in Spyder. It will be fixed once a new release of it is done.

**Closed by ccordoba12** 2018-03-18 17:03 UTC
