### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by jtibrewal09** [spyder-ide/spyder#7321] opened 2018-06-21 06:20 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

**Comment by ccordoba12** [comment] 2018-06-21 21:15
This is a duplicate of issue #6335. To fix it you need to open Terminal.app and run there:

    conda update python python.app

**Closed by ccordoba12** 2018-06-21 21:15 UTC
