### ISSUE TITLE
Add an option to turn on/off coloring in the Variable explorer

### ISSUE THREAD

**Issue by vdyashin** [spyder-ide/spyder#3677] opened 2016-11-11 05:10 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder
2. Assign some different data structures to some variables
3. See how many different colors Variable explorer have.

**What is the expected output? What do you see instead?**
I expected to have an opportunity to tweak the coloring scheme (inc. the 'all-white-filling' option). I believe that there is no need to duplicate the information given in Type column in Variable explorer by a color.

**Please provide any additional information below**
Reference: #3459 

## Versions and main components

* Spyder Version: 3.0.1

**Comment by ccordoba12** [comment] 2016-11-11 05:26
@goanpeca, we should probably go for turning off colors by default if we want to (eventually) create a dark scheme for Spyder.

**Comment by vdyashin** [comment] 2016-11-11 06:43
> we want to (eventually) create a **dark** scheme

@ccordoba12 wow. I hope that the white one will be available :)

**Comment by ccordoba12** [comment] 2016-11-11 13:28
Yes, the light scheme will be still available :-)

Since 3.0.2 delayed us, I think 3.1 is going to be available in mid January.

**Comment by ccordoba12** [comment] 2017-08-13 17:46
This will be fixed once we add a dark theme for Spyder. So I'm closing it as a duplicate of issue #2350.

**Closed by ccordoba12** 2017-08-13 17:46 UTC
Labels: component:Variable Explorer, resolution:Duplicate, type:Enhancement
