### ISSUE TITLE
SKLEARN Module not available

### ISSUE THREAD

**Issue by anuragjul84** [spyder-ide/spyder#15576] opened 2021-05-10 13:17 UTC
### What steps will reproduce the problem?

getting error "No module named 'sklearn'"

statement
print fakeestimator.predict(X)[:5]

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\lint\__init__.py", line 75, in <module>
    from pylint.lint.parallel import check_parallel
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\lint\parallel.py", line 7, in <module>
    from pylint import reporters
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\reporters\__init__.py", line 25, in <module>
    from pylint import utils
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\utils\__init__.py", line 45, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\pylint\utils\ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "C:\Users\anura\AppData\Local\Programs\Spyder\pkgs\astroid\__init__.py", line 46, in <module>
    from pathlib import Path
ModuleNotFoundError: No module named 'pathlib'

```

## Versions

* Spyder version: 5.0.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  56.2.0 (OK)
sphinx >=0.6.6                :  4.0.0 (OK)
spyder_kernels >=2.0.2;<2.1.0 :  2.0.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment] 2021-05-10 16:57
Hey @anuragjul84, thanks for reporting. The error you reported above is a duplicate of issue #15452 and we'll try to fix it in our next release.

For this problem

> getting error "No module named 'sklearn'"

If you want to use to other modules that don't come with our installer, you need to do the following:

1. Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html).

2. Create a [conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) after that with the packages you want to use and `spyder-kernels`. In your case you need to run these commands in a system terminal (i.e. `cmd.exe`):

        conda activate base
        conda create -n myenv spyder-kernels <foo>

3. Connect Spyder to that environment by following [these instructions](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment] 2021-05-17 02:09
Closing due to lack of response.

**Closed by ccordoba12** 2021-05-17 02:09 UTC
Labels: status:Awaiting Followup
