### ISSUE TITLE
Code style ignore not working

### ISSUE THREAD

**Issue by KRiD999** [spyder-ide/spyder#13737] opened 2020-09-08 15:58 UTC
### What steps will reproduce the problem?

In Spyder Preferences>Code Style I have E501 (line too long) specified to ignore.  When I start Spyder this is not recognized and my long lines are flagged.  If I go into Preferences and re-apply the ignores then it works.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by steff456** [comment] 2020-09-08 16:39
Hi @KRiD999,

I wasn't able to reproduce this issue, so can you walk me through your settings under `Preferences>Code Style` with a screenshot? And please upload a gif with the behavior you are having

**Comment by KRiD999** [comment] 2020-09-08 16:43
I was able to reproduce the issue by 1) setting the ignore codes, 2)
closing and reopening.

See the second picture and the results

[image: image.png]
[image: image.png]

**Comment by steff456** [comment] 2020-09-08 16:46
@KRiD999 can you please upload the images directly to github? The attachments in the mail doesn't render :(

**Comment by KRiD999** [comment] 2020-09-08 16:52
![image1](https://user-images.githubusercontent.com/60403255/92505430-eebf1c80-f1b8-11ea-89a4-ad179dac7d4c.png)
![image2](https://user-images.githubusercontent.com/60403255/92505433-ef57b300-f1b8-11ea-83a6-2b282f108bcd.png)

**Comment by KRiD999** [comment] 2020-09-08 17:59
Have you been able to reproduce the problem?  If not, then there is
something weird going on on my end.  I just recently updated to Spyder
4.1.5 but did see the problem in the previous release.  I think I remember
the problem showing up in that previous release.  Prior to that it was
working fine.

**Comment by steff456** [comment] 2020-09-08 20:40
Hi @KRiD999,

I'm not able to reproduce this in macOS, Linux or Windows in Spyder 4.1.5 with the same configuration you have. I know it is not the best, but can you reset your Spyder's configuration and see if that fixes the issue? 

For resetting the configuration please type in your console `spyder --reset` and try to put them again and see if it works or the error still persists.

**Comment by KRiD999** [comment] 2020-09-08 21:21
The reset worked.  Something must have been corrupted along the way.
Thanks so much for your time and quick response.

-Dirk

**Comment by steff456** [comment] 2020-09-09 02:40
I'm glad your issue is fixed, I'm going to go ahead and close this issue.

Thanks for reporting!

**Closed by steff456** 2020-09-09 02:40 UTC
Labels: status:Awaiting Followup
