### ISSUE TITLE
Automatic generation of docstring not working for class declaration

### ISSUE THREAD

**Issue by mkolmang** [spyder-ide/spyder#19249] opened 2022-08-31 17:16 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Automatic generation of docstring doesn't work for classes but works fine for functions

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
I expect automatic docstring generation for class, but it doesn't work. 1st screenshot describes the problem. 2nd screenshot when it was working fine.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
![issue_1](https://user-images.githubusercontent.com/111177042/187739648-c6eba9e0-eaa0-4773-9d44-019ad190f7da.JPG)
![issue_2](https://user-images.githubusercontent.com/111177042/187739654-872d5d00-3204-433e-84b3-0df0773d6020.JPG)

PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2022-09-01 14:33
Hey @mkolmang, thanks for reporting. I don't understand what you mean by this. Please provide a screenshot of what's not working for you to better understand your problem.

**Comment by mkolmang** [comment] 2022-09-01 14:47
Hey @ccordoba12 , here's the screenshot attahced.

![image](https://user-images.githubusercontent.com/111177042/187942736-32b4a2a8-4fd7-4315-82f2-279e5010b5b8.png)

as you see, the docstrings are automatically generated for the class methods, but not the class itself.
I tried triple quotes, and ctrl+alt+d, but it doesn't generate the docstring under the class definition.

**Comment by ccordoba12** [comment] 2022-09-02 17:16
Ok, I see. We don't do provide docstring generation for classes because they don't have args nor kwargs. So I don't understand what you're expecting to see as a auto-docstrings for classes.

**Comment by mkolmang** [comment] 2022-09-06 10:23
Hi, in previous versions it was possible in Spyder. I'm attaching the screenshot of my old script where it worked.
So I thought it's still possible to generate docstring for classes. 

![image](https://user-images.githubusercontent.com/111177042/188611511-97029931-cb98-4e29-9a4d-fb6c348ef218.png)

**Comment by ccordoba12** [comment] 2022-09-07 15:31
Ok, I didn't know that. @ok97465, could you take a look at this regression, of course, if you're not too busy?

**Comment by ok97465** [comment] 2022-09-10 12:06
I didn't implement the docstring for classes. It doesn't seem to be supported by Pycharm, VsCode's autodocstring and py-doq. 
So it doesn't seem to be easy to implement.

And I tried to implement it at #12068 but at that time it seems to have been decided by the language server to implement.
https://github.com/spyder-ide/spyder/pull/12068#issuecomment-606822087

**Comment by ccordoba12** [comment] 2022-09-12 02:45
Ok, thanks for letting us about that.

@mkolmang, you probably used another editor to generate the class docstring you showed us because we have never supported that functionality, as @ok97465 mentioned. Furthermore, this is a duplicate of issue #11924, which (unfortunately) we don't have time to work on at the moment, sorry.

**Closed by ccordoba12** 2022-09-12 02:45 UTC
Labels: type:Bug, component:Editor
