### ISSUE TITLE
F9 does not work in OSX 10.12

### ISSUE THREAD

**Issue by lithces** [spyder-ide/spyder#4895] opened 2017-08-04 04:47 UTC
## Description of your problem

Keyboard shortcut F9 does not work in OSX 10.12. However if I reassign the shortcut in preference dialog, it starts working again.

F10 works out of the box.

**What steps will reproduce the problem?**

1. start spyder
2. select a line in editor then press F9
3. nothing happens in the ipython console

**What is the expected output? What do you see instead?**
the line in the editor is sent to the console and executed

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 2.7.13 64 bit
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: OSX 10.12.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment] 2017-08-04 15:21
@goanpeca, is F9 working for you or not?

**Comment by zzzhai** [comment] 2017-08-08 06:39
yes, i met the same problem, in the preferences->keyboard shortcut, i change it from F9 to F10(defalut is run profiler) then it works

**Comment by ccordoba12** [comment] 2017-08-19 17:56
@goanpeca, can you reproduce this?

**Comment by goanpeca** [comment] 2017-08-19 18:36
I have 10.12.6 and the shortcut seems to be working fine after a reset

**Comment by ccordoba12** [comment] 2017-08-22 12:45
Closing because we can't reproduce this, sorry.

**Closed by ccordoba12** 2017-08-22 12:45 UTC

**Comment by louis925** [comment] 2018-07-28 03:13
Having the same problem. Pressing F9 in Spyder doesn't run the selected codes. However, if you try to modify the keyboard shortcut in preference > keyboard shortcut, it can detect F9 properly. So F9 work but Spyder didn't run the selected codes.
Spyder version: 3.3.0
MacOS version: 10.13.6
Python version: 3.6.5
Qt version: 5.9.3
PyQt5 version: 5.9.2

**Comment by louis925** [comment] 2018-07-28 03:30
Actually, if you update the PyQt5 to 5.11.2 manually, then the problem is fixed. You can update PyQt5 by pip install -U PyQt5. You might receive an error like spyder 3.3.0 has requirement pyqt5<5.10; python_version >= "3", but you'll have pyqt5 5.11.2 which is incompatible. but I don't find any issue with 5.11.2 on Spyder yet.
