### ISSUE TITLE
Problem with running program

### ISSUE THREAD

**Issue by OcaAnanda** [spyder-ide/spyder#7454] opened 2018-07-15 04:01 UTC
## Description

**What steps will reproduce the problem?**

1.  I run my program and I use raw_input
2.  I input string and the program will do the command on the code
3.  The program will run twice and I had to input string again

**What is the expected output? What do you see instead?**
The expected output is just the result of my program
I see the output but the code seemingly run twice

**Please provide any additional information below**

  File "C:\Users\Hasan Wirasno\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 524, in <lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "C:\Users\Hasan Wirasno\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 541, in editor_accepted
    data = self._editors[editor_id]
KeyError: 488787112L

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-07-15 14:17
I think this is fixed in our latest version. Please update by opening the Anaconda Prompt, running there

    conda update spyder

and try again.

**Comment by CAM-Gerlach** [comment] 2018-07-15 19:07
@ccordoba12 We had two other reports, #5526 and #4901, but both were closed as no response. It seems likely to be something specific to the data frame being viewed, but as that was not provided, we could not test it.

**Comment by ccordoba12** [comment] 2018-07-15 19:31
@OcaAnanda, could you provide us with a simple code example that reproduces this problem? Thanks!

**Comment by ccordoba12** [comment] 2018-07-29 15:54
Closing because of lack of response.

**Closed by ccordoba12** 2018-07-29 15:54 UTC
Labels: status:Awaiting Followup
