### ISSUE TITLE
importing numpy consistently throws error and crashes importing mechanism

### ISSUE THREAD

**Issue by drSeeS** [spyder-ide/spyder#3502] opened 2016-10-05 06:41 UTC
## Description of your problem

**What steps will reproduce the problem?**

1.  Open Spyder
2.  isseu 'import numpy' (no matter in script or console)

**What is the expected output? What do you see instead?**
Instead of importing the package, following error is thrown:

WARNING:traitlets:kernel died: 3.000523805618286
Traceback (most recent call last):
  File "C:\Programm2\Anaconda4\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Programm2\Anaconda4\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 188, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\Programm2\Anaconda4\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 225, in handle_exec_method
    properties = ast.literal_eval(data['text/plain'])
  File "C:\Programm2\Anaconda4\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Programm2\Anaconda4\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 28
    'numpy': {'array_ndim': <function numpy.core.fromnumeric.ndim>,
                            ^
SyntaxError: invalid syntax (hat pointing to \<func..)

- This is sepcific to the numpy package: Before running 'import numpy' I could import none or any other package without problems. Once the error is thrown, the same error will be then thrown again each time i try to import any other package.
- This is specific to spyder. No problem importing in iPython, IPython Notebook.
- can reproduce the error any time
- complete un- and reinstall did not change any behaviours

Thanks for help!

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5.2
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2016-10-05 16:17
Please open a terminal (i.e. `cmd.exe`), run this command

    spyder --reset

and try again

**Comment by drSeeS** [comment] 2016-10-05 20:35
Thanks Carlos!

Already downgraded to 4.1 (Spyder 2),  No new issues so far. Will upgrade again and give it a shot once I got some spare time.

**Comment by ccordoba12** [comment] 2016-10-12 15:12
Closing as a duplicate of issue #3528.

**Closed by ccordoba12** 2016-10-12 15:12 UTC
