### ISSUE TITLE
spyder crashed

### ISSUE THREAD

**Issue by starsky6791** [spyder-ide/spyder#6933] opened 2018-04-09 22:48 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "F:\Program File\anaconda\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "F:\Program File\anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "F:\Program File\anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "F:\Program File\anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1068, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "F:\Program File\anaconda\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "F:\Program File\anaconda\lib\site-packages\jupyter_client\threaded.py", line 217, in start_channels
    super(ThreadedKernelClient, self).start_channels(shell, iopub, stdin, hb)
  File "F:\Program File\anaconda\lib\site-packages\jupyter_client\client.py", line 106, in start_channels
    self.stdin_channel.start()
  File "F:\Program File\anaconda\lib\site-packages\jupyter_client\client.py", line 165, in stdin_channel

**Comment by ccordoba12** [comment] 2018-04-09 23:52
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment] 2018-04-17 15:03
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Closed by CAM-Gerlach** 2018-04-17 15:03 UTC
Labels: status:Awaiting Followup
