### ISSUE TITLE
5.5.3 Updater doesn't work

### ISSUE THREAD

**Issue by OshidaBCF** [spyder-ide/spyder#21905] opened 2024-03-17 18:48 UTC
When i start spyder i get a message that a new version (5.5.3) is available, if i try to do the update a message appear 

it was something about "16 bit" not working on a 64 bit machine

i cannot see the message anymore, i only get a windows 10 warning "this exe cannot be run on this machine" after i tried to fiddle with the compatibility menu

**Comment by rhkarls** [comment] 2024-03-18 08:41
Updater does also not work for me, but without any errors. Clicking yes to proceed and nothing happens. Seems like some other dialog quickly opening and closing after clicking yes.

The "After closing" option is also not working

![spyder_5_2_2_update](https://github.com/spyder-ide/spyder/assets/2330659/1804719d-4583-43e9-ac86-cdf1ddf8ebfa)

```
* Spyder version: 5.5.2  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0
```

**Comment by ClaasBeger** [comment] 2024-03-18 16:24
I have the same issue when trying to use the native installer from 5.5.2 to 5.5.3. The corresponding error message is "The program or feature "...\AppData\Local\Temp\spyder\updates\5.5.3\Spyder-Windows-x86_64.exe" cannot be started or executed by Windows because of an incompatibility issue with 64 bit-versions. Please contact the software developer to find out whether a 64 bit-Windows compatible version is available.". As the message suggests I am using Windows.

**Comment by ccordoba12** [comment] 2024-03-18 17:21
Hey folks, thanks for reporting. It seems we're not downloading the right 5.5.3 artifact for the update or that it's not named correctly. We'll take a look at this one in our next version (5.5.4), to be released asap.

@dalthviz, could you take care of this one? Thanks!

**Closed** 2024-03-19 22:30 UTC
Labels: type:Bug, Installers

**Comment by FGema** [comment] 2024-04-11 13:34
> Hey folks, thanks for reporting. It seems we're not downloading the right 5.5.3 artifact for the update or that it's not named correctly. We'll take a look at this one in our next version (5.5.4), to be released asap.
> 
> @dalthviz, could you take care of this issue? Thanks!

It's my first post, so I don't know if I'm doing right, but I faced a similar error from 5.5.3 to 5.5.4:
![bug 1](https://github.com/spyder-ide/spyder/assets/166710347/966441e4-e222-4ef0-9b53-7b499846a9b0)
![bug 2](https://github.com/spyder-ide/spyder/assets/166710347/77daeb9d-d5a2-4416-a13e-cb8a7c76ca6e)
![bug 3](https://github.com/spyder-ide/spyder/assets/166710347/d05264cc-aeec-4dca-be15-88b026883aa8)
![bug 4](https://github.com/spyder-ide/spyder/assets/166710347/00f5dfec-2f14-4a3a-9fe2-f183bea6e92a)

Also, you can see the "check for updates" entry is disabled at first, and after the error it turns into available.

I won't force the update, so if you need more info, just ask.

**Comment by ccordoba12** [comment] 2024-04-11 15:42
@FGema, this problem was fixed in 5.5.4 but it's still present in versions 5.5.1, up to 5.5.3.

The solution is to manually uninstall Spyder and then install 5.5.4 because the regular update process will generate this error.

**Comment by dalthviz** [comment] 2024-04-11 20:37
@ccordoba12 should we try to add the installer files with the name that is expected for Spyder 5.5.1 to 5.5.4 over the 5.5.4 GitHub release?

**Comment by ccordoba12** [comment] 2024-04-11 21:06
Is that possible? I thought the issue was that the update process was downloading the wrong installer.

**Comment by Kiamehr5** [comment] 2024-04-11 23:49
@ccordoba12 and @dalthviz, Maybe add a manual reinstaller for v5.5.4 or somethin idk

**Comment by dalthviz** [comment] 2024-04-12 01:16
> Is that possible? I thought the issue was that the update process was downloading the wrong installer.

I think so, I just added the renamed installer to the release assets and I was able to go from 5.5.3 to 5.5.4. Also, I think there is no need to uninstall the previous installation since even if you manually download the installer, it should prompt you to uninstall any previous installation and uninstall it for you.

**Comment by ccordoba12** [comment] 2024-04-12 01:34
> I think so, I just added the renamed installer to the release assets and I was able to go from 5.5.3 to 5.5.4.

That's great news! I think having the renamed installer in 5.5.4 should be enough, right? I mean, I don't think we need people to update to previous versions because 5.5.4 has important bugfixes that are not included in 5.5.2 and 5.5.3.

**Comment by dalthviz** [comment] 2024-04-12 20:20
> That's great news! I think having the renamed installer in 5.5.4 should be enough, right? 

I think so, although if for some reason that doesn't work in some user specific case, they will need to download the latest installer manually like for example the latest release page on Github (https://github.com/spyder-ide/spyder/releases/latest) which as I write this should point to the Spyder 5.5.4 release page.

> I mean, I don't think we need people to update to previous versions because 5.5.4 has important bugfixes that are not included in 5.5.2 and 5.5.3.

Yep, as far as I understand the update logic, we always try to update to the latest release. So currently, any check for updates should be always pointing users to update to 5.5.4. Then should be enough to just have the renamed installer over the latest release (5.5.4 currently).

Thinking about this, and I think this was discussed before, but maybe we should upload as part of the installer workflows when doing a release assets with both names (so for example on the Windows case `Spyder-Windows-x86_64.exe` and `Spyder_64bit_full.exe`)?

**Comment by ccordoba12** [comment] 2024-04-16 04:58
> Thinking about this, and I think this was discussed before, but maybe we should upload as part of the installer workflows when doing a release assets with both names (so for example on the Windows case Spyder-Windows-x86_64.exe and Spyder_64bit_full.exe)?

Since we're going to release 5.5.5 now, I think that's a good idea. Could you take care of that? Thanks!

**Comment by FGema** [comment] 2024-04-16 11:17
> > Is that possible? I thought the issue was that the update process was downloading the wrong installer.
> 
> I think so, I just added the renamed installer to the release assets and I was able to go from 5.5.3 to 5.5.4. Also, I think there is no need to uninstall the previous installation since even if you manually download the installer, it should prompt you to uninstall any previous installation and uninstall it for you.

Just an update by my side. Inspired by this comment, I manually downloaded 5.5.4 full from website, renamed -x86_64 and replaced the wrong 1 KB file in the temp AppData folder with the full >200 MB file.
Then I hit "Check for updates" in Spyder and it worked.

So, IMO the problem is just due to the wrong downloaded file.

Hope it helps

**Comment by ccordoba12** [comment] 2024-04-16 13:55
Thanks @FGema for the confirmation!
