### ISSUE TITLE
Unable to import psycopg2 due to mixing packages from different Python installations

### ISSUE THREAD

**Issue by travisstenerson-concert** [spyder-ide/spyder#21228] opened 2023-08-07 17:58 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have an M2 mac running Ventura. 
I am unable to import psycopg2 into Spyder. I installed spyder using the standalone MacOS installer. I manage the packages with pip and have added the path to PYTHONPATH manager in Spyder. I am using the python executable that came with the mac (3.9.6), though I tried spyder's included executable too. 
A number of packages were broken by the new mac chips. Usually you can get around it by installing with --no-binary

You can find lots of issues googling psycopg2 build errors with M1 macs. Generally the solution involves installing psycopg2-binary or installing some brew casks (libpq,openssl,postgresql) and then trying again to pip install psycopg2. This works, and if you successfully pip install either of these, you can open a python shell and import psycopg2.
However you can not import them into spyder. Both versions of psycopg2 give similar but distinct errors with the file `_psycopg.cpython-39-darwin.so`

### What steps reproduce the problem?

1. pip install psycopg2 or psycopg2-binary on M2 mac
2. import psycopg2 in spyder

### What is the expected output? What do you see instead?
Expected output would be a successful import
Current output is an ImportError with this file: `_psycopg.cpython-39-darwin.so`

### Paste Traceback/Error Below (if applicable)

```python-traceback

#if you have installed psycopg2-binary
import psycopg2

  File ~/Library/Python/3.9/lib/python/site-packages/psycopg2/__init__.py:51
    from psycopg2._psycopg import (                     # noqa

ImportError: dlopen(/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): tried: '/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (no such file), '/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')))


#if you have installed psycopg2
import psycopg2

  File ~/Library/Python/3.9/lib/python/site-packages/psycopg2/__init__.py:51
    from psycopg2._psycopg import (                     # noqa

ImportError: dlopen(/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_PQbackendPID'

```

## Versions
5.4.4 and 6.0.0a1 (I tried both)

* Spyder version: 5.4.4 and 6.0.0a1 (I tried both)
* Python version: 3.9.6
* Operating System name/version: MacOS Ventura

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.1.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.1.1 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  0.9.0 (OK)
jsonschema >=3.2.0                                                          :  4.17.3 (OK)
keyring >=17.0.0                                                            :  23.13.1 (OK)
nbconvert >=4.0                                                             :  7.6.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.15.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.4 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                                                        :  1.7.3 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.3.1 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  67.7.2 (OK)
sphinx >=0.6.6                                                              :  7.0.1 (OK)
spyder_kernels >=3.0.0b1,<3.0.0b2                                           :  3.0.0b1 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.0 (OK)

# Optional:
cython >=0.21                                                               :  0.29.35 (OK)
matplotlib >=3.0.0                                                          :  3.7.1 (OK)
numpy >=1.7                                                                 :  1.25.0 (OK)
pandas >=1.1.1                                                              :  2.0.2 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)
```

**Comment by ccordoba12** [comment] 2023-08-08 13:22
Hey @travisstenerson-concert, thanks for reporting. You said:

> I manage the packages with pip and have added the path to PYTHONPATH manager in Spyder

What exact path did you add to Spyder through our PYTHONPATH manager?

**Comment by travisstenerson-concert** [comment] 2023-08-08 14:07
> Hey @travisstenerson-concert, thanks for reporting. You said:
> 
> > I manage the packages with pip and have added the path to PYTHONPATH manager in Spyder
> 
> What exact path did you add to Spyder through our PYTHONPATH manager?

The folder that pip installs packages into:
`/Users/my_username/Library/Python/3.9/lib/python/site-packages`

I was wondering if I had to also add the location that homebrew installed libpq to, but I have not done that.

**Comment by ccordoba12** [comment] 2023-08-09 16:00
>  The folder that pip installs packages into:
/Users/my_username/Library/Python/3.9/lib/python/site-packages

Ok, I was thinking that. And are you using our Mac application? Or how did you install Spyder?

> I was wondering if I had to also add the location that homebrew installed libpq to, but I have not done that.

Better not to for now. I'll explain you why after you answer my previous question.

**Comment by travisstenerson-concert** [comment] 2023-08-09 16:07
@ccordoba12  Is your question about the install or did I miss another question?
Installation was via the installer at this link https://github.com/spyder-ide/spyder/releases/latest/download/Spyder.dmg

But then I uninstalled and used this link to the pre-release https://github.com/spyder-ide/spyder/releases/download/v6.0.0a1/Spyder-6.0.0a1-macOS-x86_64.pkg


I read a few items while searching for a solution that using a conda installation or conda controlled environment may solve the problem, but I figured you might want to know that this common package was working through a python shell but not through spyder so I posted here instead of trying that.

Thanks again for your help

**Comment by ccordoba12** [comment] 2023-08-09 17:33
@mrclary, could you check if you're able to add a path similar to

    /Users/<username>/Library/Python/3.9/lib/python/site-packages

through our PYTHONPATH manager?

We try to prevent that to avoid the problem I described above, but it seems it's possible on Mac.

**Comment by travisstenerson-concert** [comment] 2023-08-09 18:02
@ccordoba12 

I have installed spyder-kernels. I upgraded it for the 6.0.0 spyder version:
``` % pip list
Package            Version
------------------ --------
.....
spyder-kernels     3.0.0b1
.....
```

Also I have been using the interpreter that the python shell uses. I believe this is the default location on a mac, as I did not update python since getting the new macbook. I also tried the spyder-included interpreter but that did not work.

<img width="764" alt="image" src="https://github.com/spyder-ide/spyder/assets/70653044/551faf39-a57d-4671-8da3-3edf6c5634c3">


Is your recommendation to reinstall spyder with conda and use a conda environment?

**Comment by ccordoba12** [comment] 2023-08-09 18:59
> Is your recommendation to reinstall spyder with conda and use a conda environment?

Nop, that's not necessary. What you did was what users should do to use another Python interpreter in Spyder, so it's fine.

Then, please remove this entry in our PYTHONPATH manager

    /Users/<username>/Library/Python/3.9/lib/python/site-packages

and your problem should be fixed (I hope).

**Comment by mrclary** [comment] 2023-08-09 18:59
> @mrclary, could you check if you're able to add a path similar to
> 
> ```
> /Users/<username>/Library/Python/3.9/lib/python/site-packages
> ```
> 
> through our PYTHONPATH manager?

I can add an arbitrary path. In my case I added `/Users/rclary/opt/mambaforge/envs/test/lib/python3.10/site-packages`, which is not already part of the IPython console environment I was using.

It seems to me that the real issue in this post is not using properly formed environments.

@travisstenerson-concert, I'm confused about what environment you are using. When you installed `psycopg2`, what was the exact command that you used? In your first step to reproduce the issue you say `pip install psycopg2`, but this is not possible on macOS since `pip` does not exist; if you installed into the system python environment (HIGHLY discouraged), then you must use `pip3 install psycopg2`. Additionally, Spyder does not list the system Python for use in IPython consoles, so I don't know which Python environment you are using.

Your second step says "import psycopg2 into spyder". What does this mean? Are you using the command `import psycopg2` in the IPython console? If so, then this will not work because the default Python environment is the same as Spyder's runtime environment, which does not have `psycopg2`. Adding some path to PYTHONPATH will not work either, since `psycopg2` must be installed into a fully qualified Python environment.

I recommend the following:
1. Install Spyder (it doesn't matter whether 5.4.4 or 6.0.0a1).
2. If you don't want to use conda, then create a new Python environment in a Terminal like so:
   ```
   $ python3 -m venv new_env
   $ source new_env/bin/activate
   (new_env) $ python -m pip install spyder-kernels psycopg2-binary
   ```
3. Follow the instructions at http://docs.spyder-ide.org/current/faq.html#using-existing-environment to use the new environment in Spyder
4. In Spyder's IPython console, you should be able to
   ```python
   import psycopg2
   ```

**Comment by mrclary** [comment] 2023-08-09 19:03
Sorry, @ccordoba12 and @travisstenerson-concert; my wrote my latest comment before your latest responses and didn't see them before I posted it.

**Comment by ccordoba12** [comment] 2023-08-09 19:09
No worries. You said:

> I can add an arbitrary path. In my case I added /Users/rclary/opt/mambaforge/envs/test/lib/python3.10/site-packages, which is not already part of the IPython console environment I was using.

The problem is that the regexp we're using to check for possible `site-packages` additions through our PPM (which we forbid) is not covering cases like Python 3.10 envs nor those like the one @travisstenerson-concert is trying to use.

> It seems to me that the real issue in this post is not using properly formed environments.

I thought the same for a bit but after seeing @travisstenerson-concert's error I thought it had something to do with mixing Python installations:

>> ImportError: dlopen(/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): tried: '/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (no such file), '/Users/my_username/Library/Python/3.9/lib/python/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (**have 'arm64', need 'x86_64'**)))

**Comment by mrclary** [comment] 2023-08-09 19:28
> The problem is that the regexp we're using to check for possible `site-packages` additions through our PPM (which we forbid) is not covering cases like Python 3.10+ envs nor those like the one @travisstenerson-concert is trying to use.

Okay, got it. We could look into fixing that.

> I thought the same for a bit but after seeing @travisstenerson-concert's error I thought it had something to do with mixing Python installations:
> 
> > > but is an incompatible architecture (have 'arm64', need 'x86_64'))

Okay, I'll check on my M1 and report back regarding mixing architecture. In any case, one cannot install psycopg2 into an arbitrary directory, separate from a Python environment, and expect it work properly.

@travisstenerson-concert, can you check if you have Rosetta installed?
```
$ pgrep -lf oahd
```

**Comment by mrclary** [comment] 2023-08-09 19:56
When creating a venv environment and using it for IPython console on my M1 I get the following:

<details><summary>venv creation</summary>

```
>> /usr/bin/python3 -m venv new_env
>> source new_env/bin/activate
(new_env) >> pip install spyder-kernels psycopg2-binary
Collecting spyder-kernels
  Downloading spyder_kernels-2.4.4-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 2.0 MB/s 
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.7-cp39-cp39-macosx_11_0_arm64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 2.3 MB/s 
Collecting wurlitzer>=1.0.3
  Downloading wurlitzer-3.0.3-py3-none-any.whl (7.3 kB)
Collecting jupyter-client<9,>=7.4.9
  Downloading jupyter_client-8.3.0-py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 1.9 MB/s 
Collecting pyzmq>=22.1.0
  Downloading pyzmq-25.1.0-cp39-cp39-macosx_10_15_universal2.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 5.5 MB/s 
Collecting ipython!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1,!=8.8.0,!=8.9.0,<9,>=7.31.1
  Downloading ipython-8.14.0-py3-none-any.whl (798 kB)
     |████████████████████████████████| 798 kB 6.7 MB/s 
Collecting cloudpickle
  Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting ipykernel<7,>=6.23.2
  Downloading ipykernel-6.25.1-py3-none-any.whl (154 kB)
     |████████████████████████████████| 154 kB 5.7 MB/s 
Collecting matplotlib-inline>=0.1
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting packaging
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting comm>=0.1.1
  Downloading comm-0.1.4-py3-none-any.whl (6.6 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.7-py3-none-any.whl (5.3 kB)
Collecting appnope
  Using cached appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting jupyter-core!=5.0.*,>=4.12
  Downloading jupyter_core-5.3.1-py3-none-any.whl (93 kB)
     |████████████████████████████████| 93 kB 5.9 MB/s 
Collecting debugpy>=1.6.5
  Downloading debugpy-1.6.7.post1-py2.py3-none-any.whl (4.9 MB)
     |████████████████████████████████| 4.9 MB 272 kB/s 
Collecting traitlets>=5.4.0
  Using cached traitlets-5.9.0-py3-none-any.whl (117 kB)
Collecting psutil
  Downloading psutil-5.9.5-cp38-abi3-macosx_11_0_arm64.whl (246 kB)
     |████████████████████████████████| 246 kB 8.7 MB/s 
Collecting tornado>=6.1
  Downloading tornado-6.3.2-cp38-abi3-macosx_10_9_universal2.whl (424 kB)
     |████████████████████████████████| 424 kB 8.8 MB/s 
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting stack-data
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pygments>=2.4.0
  Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 16.0 MB/s 
Collecting typing-extensions
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.0-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 9.4 MB/s 
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Downloading prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
     |████████████████████████████████| 385 kB 8.3 MB/s 
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 8.9 MB/s 
Collecting importlib-metadata>=4.8.3
  Downloading importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Downloading zipp-3.16.2-py3-none-any.whl (7.2 kB)
Collecting platformdirs>=2.5
  Downloading platformdirs-3.10.0-py3-none-any.whl (17 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Installing collected packages: six, zipp, wcwidth, traitlets, pure-eval, ptyprocess, platformdirs, parso, executing, asttokens, typing-extensions, tornado, stack-data, pyzmq, python-dateutil, pygments, prompt-toolkit, pickleshare, pexpect, matplotlib-inline, jupyter-core, jedi, importlib-metadata, decorator, backcall, appnope, psutil, packaging, nest-asyncio, jupyter-client, ipython, debugpy, comm, wurlitzer, ipykernel, cloudpickle, spyder-kernels, psycopg2-binary
Successfully installed appnope-0.1.3 asttokens-2.2.1 backcall-0.2.0 cloudpickle-2.2.1 comm-0.1.4 debugpy-1.6.7.post1 decorator-5.1.1 executing-1.2.0 importlib-metadata-6.8.0 ipykernel-6.25.1 ipython-8.14.0 jedi-0.19.0 jupyter-client-8.3.0 jupyter-core-5.3.1 matplotlib-inline-0.1.6 nest-asyncio-1.5.7 packaging-23.1 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-3.10.0 prompt-toolkit-3.0.39 psutil-5.9.5 psycopg2-binary-2.9.7 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyzmq-25.1.0 six-1.16.0 spyder-kernels-2.4.4 stack-data-0.6.2 tornado-6.3.2 traitlets-5.9.0 typing-extensions-4.7.1 wcwidth-0.2.6 wurlitzer-3.0.3 zipp-3.16.2
WARNING: You are using pip version 21.2.4; however, version 23.2.1 is available.
You should consider upgrading via the '/Users/ryan/new_env/bin/python3 -m pip install --upgrade pip' command.
```
</details>

<details><summary>IPython console traceback</summary>

```python
Traceback (most recent call last):
File "/Users/ryan/new_env/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/Users/ryan/new_env/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 293, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 52, in
from .ipkernel import IPythonKernel
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/ipkernel.py", line 20, in
from .comm.comm import BaseComm
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/comm/__init__.py", line 3, in
from .comm import Comm
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/comm/comm.py", line 15, in
from ipykernel.kernelbase import Kernel
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/kernelbase.py", line 38, in
import psutil
File "/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/__init__.py", line 123, in
from . import _psosx as _psplatform
File "/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psosx.py", line 13, in
from . import _psposix
File "/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psposix.py", line 28, in
from . import _psutil_osx
ImportError: dlopen(/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (no such file), '/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
Traceback (most recent call last):
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Users/ryan/new_env/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/Users/ryan/new_env/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 293, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 52, in
from .ipkernel import IPythonKernel
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/ipkernel.py", line 20, in
from .comm.comm import BaseComm
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/comm/__init__.py", line 3, in
from .comm import Comm
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/comm/comm.py", line 15, in
from ipykernel.kernelbase import Kernel
File "/Users/ryan/new_env/lib/python3.9/site‑packages/ipykernel/kernelbase.py", line 38, in
import psutil
File "/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/__init__.py", line 123, in
from . import _psosx as _psplatform
File "/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psosx.py", line 13, in
from . import _psposix
File "/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psposix.py", line 28, in
from . import _psutil_osx
ImportError: dlopen(/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (no such file), '/Users/ryan/new_env/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```
</details>
So I couldn't even try to import psycopg2.

However, I was successful with a conda environment.
```
mamba create -n new_env spyder-kernels psycopg2
```

I have rosetta installed, so I think there may always be an architecture issue when using the system Python. I think the only solutions will be to either use conda or a brew-installed python; in any case, do not use the system Python.

**Comment by travisstenerson-concert** [comment] 2023-08-10 15:35
Apologies for the reply delay.

@mrclary It's almost definitely an environment issue yes. I am not a developer or software eng.. in my role I never really need to worry about breaking applications or analyses on my local machine.. so I don't use well organized environments. I know this is not recommended and arguably stupid. I use spyder to pull data from tons of sources, explore it and rearrange it. I've managed to do that without worrying too much about environments in the past.  The M2 chip is making me regret that. 

re: rosetta, I actually installed rosetta as I had read it fixes architecture issues for the M1/2 chips, but I was never prompted to install it ever.

```
% pgrep -lf oahd
39978 /usr/libexec/rosetta/oahd
```

also re pip vs pip3.. I have aliased pip3 to pip and python3 to python in my .zsrch file. I should have mentioned that, sorry. 



So if I reinstall python via homebrew, and point to that python exectuable in spyder.. do I leave the pip package install location in my PYTHONPATH? What will be the proper way to install psycopg2 after that?

**Comment by mrclary** [comment] 2023-08-10 16:23
@travisstenerson-concert, thanks for the additional info; that makes things a little more clear.

> So if I reinstall python via homebrew, and point to that python exectuable in spyder.. do I leave the pip package install location in my PYTHONPATH? What will be the proper way to install psycopg2 after that?

* I would definitely remove the alias to the system Python from your shell startup file. Using the system Python is _highly_ discouraged on macOS. This is independent of Intel vs. Apple silicon. I highly recommend using conda (https://www.anaconda.com/download), but Python from Homebrew will work just fine too.
* Regardless of your choice of conda or Homebrew Python, it is best practice to create a Python environment into which you want to install packages. In addition to being able to create multiple environments to serve different purposes, if something goes wrong with the environment it is easy to delete the environment and rebuild it. If you install into the primary Python environment, if something goes wrong your only option may be to reinstall Python; this is much more difficult, and in the case of macOS system Python, may be impossible.
* You should remove the pip package install location from your PYTHONPATH. PYTHONPATH is generally reserved for Python packages and modules that you create yourself locally. Packages that you get from somewhere else (conda, PyPi, ...) should be installed into a Python environment in which case they will be found and do not require insertion into PYTHONPATH.
* To create a new environment with conda:
  ```
  conda create --name new_env spyder-kernels psycopg2
  ```
  But there is a lot of online tutorials about how to work with conda.
* To create a new environment with Homebrew Python:
  ```
  $ python3 -m venv new_env
  $ source new_env/bin/activate
  (new_env) $ python -m pip install spyder-kernels psycopg2-binary
  ```
  But make sure that `python3` is the Homebrew Python. This should be the case if you've installed Python from Homebrew _and_ removed the Python aliases in your shell startup file. But if in doubt, just be explicit: `/opt/homebrew/bin/python3`

I've successfully tested both the conda and Homebrew methods above on my M1 machine.

**Comment by travisstenerson-concert** [comment] 2023-08-10 19:53
@mrclary thanks for the detailed instruction

I avoid conda because there are a lot of packages in medical informatics that don't work in conda, so I had to install them with pip. Or at least that was the case in the past. Using conda always made me run into problems with packages. So I prefer the pip installs as they always work. 

I will try the python environment via homebrew and stop using the system's python executable.

**Closed** 2023-08-11 23:24 UTC
Labels: type:Bug, OS:MacOS, component:Pythonpath manager
