### ISSUE TITLE
Spyder crhashes with Pyqt 5.12

### ISSUE THREAD

**Issue by marianux** [spyder-ide/spyder#8868] opened 2019-02-28 22:19 UTC
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X ] Tried basic troubleshooting (if a bug/error)
    * [X ] Restarted Spyder
    * [X ] Reset preferences with ``spyder --reset``
    * [ X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X ] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder crash with PyQT5 5.12

### What steps reproduce the problem?

1. pip3 install --upgrade --user pyqt5==5.12
2. spyder3 --new-instance &

### What is the expected output? What do you see instead?

mariano@mllamedo-UTN:~$ Traceback (most recent call last):
  File "/home/mariano/.local/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/home/mariano/.local/bin/spyder3", line 10, in <module>
    sys.exit(main())
  File "/home/mariano/.local/lib/python3.6/site-packages/spyder/app/start.py", line 192, in main
    from spyder.app import mainwindow
  File "/home/mariano/.local/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/mariano/.local/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'


```

## Versions

* Spyder version: 3.3.3
* Python version: 3.6
* Qt version: 
* PyQt version: 5.12
* Operating System name/version: Ubuntu 18.04

### Dependencies

```
cannot start spyder
```

Possible workaround:
*************************
Downgrade Pyqt to 5.11.3

$ pip3 install --upgrade --user pyqt5==5.11.3

and the problem dissapear.

P/S: Sorry beforehand if this is not spyder related.

**Comment by ccordoba12** [comment] 2019-03-01 09:41
Duplicate of #8747. To fix this you need to

    pip install pyqtwebengine

**Closed by ccordoba12** 2019-03-01 09:41 UTC

**Comment by dazinger92** [comment] 2019-04-07 19:17
Just wanted to leave a quick comment - for some reason "pip install pyqtwebengin" does not alleviate this error for me.  It installs version 5.12.1.

spyder install log:

C:\WINDOWS\system32>pip install spyder
Requirement already satisfied: spyder in c:\[...]\site-packages (3.3.4)
Requirement already satisfied: psutil in c:\[...]\site-packages (from spyder) (5.4.6)
Requirement already satisfied: pyqt5<5.13; python_version >= "3" in c:\[...]\site-packages (from spyder) (5.12.1)
Requirement already satisfied: pyqtwebengine<5.13 in c:\[...]\site-packages (from spyder) (5.12.1)
Requirement already satisfied: chardet>=2.0.0 in c:\[...]\site-packages (from spyder) (3.0.4)
Requirement already satisfied: nbconvert in c:\[...]\site-packages (from spyder) (5.3.1)
Requirement already satisfied: sphinx in c:\[...]\site-packages (from spyder) (1.7.6)
Requirement already satisfied: rope>=0.10.5 in c:\[...]\site-packages (from spyder) (0.10.7)
Requirement already satisfied: spyder-kernels<1.0,>=0.4.3 in c:\[...]\site-packages (from spyder) (0.4.3)
Requirement already satisfied: qtconsole>=4.2.0 in c:\[...]\site-packages (from spyder) (4.3.1)
Requirement already satisfied: qtpy>=1.5.0 in c:\[...]\site-packages (from spyder) (1.7.0)
Requirement already satisfied: pygments>=2.0 in c:\[...]\site-packages (from spyder) (2.2.0)
Requirement already satisfied: qtawesome>=0.5.7 in c:\[...]\site-packages (from spyder) (0.5.7)
Requirement already satisfied: pycodestyle in c:\[...]\site-packages (from spyder) (2.4.0)
Requirement already satisfied: pyzmq in c:\[...]\site-packages (from spyder) (17.1.0)
Requirement already satisfied: pylint in c:\[...]\site-packages (from spyder) (2.0.0)
Requirement already satisfied: pickleshare in c:\[...]\site-packages (from spyder) (0.7.4)
Requirement already satisfied: numpydoc in c:\[...]\site-packages (from spyder) (0.8.0)
Requirement already satisfied: cloudpickle in c:\[...]\site-packages (from spyder) (0.5.3)
Requirement already satisfied: keyring; sys_platform != "linux2" in c:\[...]\site-packages (from spyder) (13.2.1)
Requirement already satisfied: jedi>=0.9.0 in c:\[...]\site-packages (from spyder) (0.12.1)
Requirement already satisfied: pyflakes in c:\[...]\site-packages (from spyder) (2.0.0)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.14 in c:\[...]\site-packages (from pyqt5<5.13; python_version >= "3"->spyder) (4.19.15)
Requirement already satisfied: nbformat>=4.4 in c:\[...]\site-packages (from nbconvert->spyder) (4.4.0)
Requirement already satisfied: bleach in c:\[...]\site-packages (from nbconvert->spyder) (2.1.3)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\[...]\site-packages (from nbconvert->spyder) (1.4.2)
Requirement already satisfied: mistune>=0.7.4 in c:\[...]\site-packages (from nbconvert->spyder) (0.8.3)
Requirement already satisfied: traitlets>=4.2 in c:\[...]\site-packages (from nbconvert->spyder) (4.3.2)
Requirement already satisfied: jupyter-core in c:\[...]\site-packages (from nbconvert->spyder) (4.4.0)
Requirement already satisfied: jinja2 in c:\[...]\site-packages (from nbconvert->spyder) (2.10)
Requirement already satisfied: entrypoints>=0.2.2 in c:\[...]\site-packages (from nbconvert->spyder) (0.2.3)
Requirement already satisfied: testpath in c:\[...]\site-packages (from nbconvert->spyder) (0.3.1)
Requirement already satisfied: sphinxcontrib-websupport in c:\[...]\site-packages (from sphinx->spyder) (1.1.0)
Requirement already satisfied: requests>=2.0.0 in c:\[...]\site-packages (from sphinx->spyder) (2.19.1)
Requirement already satisfied: six>=1.5 in c:\[...]\site-packages (from sphinx->spyder) (1.11.0)
Requirement already satisfied: packaging in c:\[...]\site-packages (from sphinx->spyder) (17.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\[...]\site-packages (from sphinx->spyder) (0.7.11)
Requirement already satisfied: setuptools in c:\[...]\site-packages (from sphinx->spyder) (40.8.0)
Requirement already satisfied: imagesize in c:\[...]\site-packages (from sphinx->spyder) (1.0.0)
Requirement already satisfied: babel!=2.0,>=1.3 in c:\[...]\site-packages (from sphinx->spyder) (2.6.0)
Requirement already satisfied: snowballstemmer>=1.1 in c:\[...]\site-packages (from sphinx->spyder) (1.2.1)
Requirement already satisfied: colorama>=0.3.5; sys_platform == "win32" in c:\[...]\site-packages (from sphinx->spyder) (0.3.9)
Requirement already satisfied: docutils>=0.11 in c:\[...]\site-packages (from sphinx->spyder) (0.14)
Requirement already satisfied: ipykernel>=4.8.2 in c:\[...]\site-packages (from spyder-kernels<1.0,>=0.4.3->spyder) (4.8.2)
Requirement already satisfied: jupyter-client>=5.2.3 in c:\[...]\site-packages (from spyder-kernels<1.0,>=0.4.3->spyder) (5.2.3)
Requirement already satisfied: ipython-genutils in c:\[...]\site-packages (from qtconsole>=4.2.0->spyder) (0.2.0)
Requirement already satisfied: isort>=4.2.5 in c:\[...]\site-packages (from pylint->spyder) (4.3.4)
Requirement already satisfied: astroid>=2.0.0 in c:\[...]\site-packages (from pylint->spyder) (2.0)
Requirement already satisfied: mccabe in c:\[...]\site-packages (from pylint->spyder) (0.6.1)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\[...]\site-packages (from keyring; sys_platform != "linux2"->spyder) (0.1.2)
Requirement already satisfied: parso>=0.3.0 in c:\[...]\site-packages (from jedi>=0.9.0->spyder) (0.3.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\[...]\site-packages (from nbformat>=4.4->nbconvert->spyder) (2.6.0)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in c:\[...]\site-packages (from bleach->nbconvert->spyder) (1.0.1)
Requirement already satisfied: decorator in c:\[...]\site-packages (from traitlets>=4.2->nbconvert->spyder) (4.3.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\[...]\site-packages (from jinja2->nbconvert->spyder) (1.0)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\[...]\site-packages (from requests>=2.0.0->sphinx->spyder) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in c:\[...]\site-packages (from requests>=2.0.0->sphinx->spyder) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\[...]\site-packages (from requests>=2.0.0->sphinx->spyder) (2018.4.16)
Requirement already satisfied: pyparsing>=2.0.2 in c:\[...]\site-packages (from packaging->sphinx->spyder) (2.2.0)
Requirement already satisfied: pytz>=0a in c:\[...]\site-packages (from babel!=2.0,>=1.3->sphinx->spyder) (2018.5)
Requirement already satisfied: tornado>=4.0 in c:\[...]\site-packages (from ipykernel>=4.8.2->spyder-kernels<1.0,>=0.4.3->spyder) (5.1)
Requirement already satisfied: ipython>=4.0.0 in c:\[...]\site-packages (from ipykernel>=4.8.2->spyder-kernels<1.0,>=0.4.3->spyder) (6.4.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\[...]\site-packages (from jupyter-client>=5.2.3->spyder-kernels<1.0,>=0.4.3->spyder) (2.7.3)
Requirement already satisfied: lazy-object-proxy in c:\[...]\site-packages (from astroid>=2.0.0->pylint->spyder) (1.3.1)
Requirement already satisfied: wrapt in c:\[...]\site-packages (from astroid>=2.0.0->pylint->spyder) (1.10.11)
Requirement already satisfied: webencodings in c:\[...]\site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->spyder) (0.5.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.15 in c:\[...]\site-packages (from ipython>=4.0.0->ipykernel>=4.8.2->spyder-kernels<1.0,>=0.4.3->spyder) (1.0.15)
Requirement already satisfied: backcall in c:\[...]\site-packages (from ipython>=4.0.0->ipykernel>=4.8.2->spyder-kernels<1.0,>=0.4.3->spyder) (0.1.0)
Requirement already satisfied: simplegeneric>0.8 in c:\[...]\site-packages (from ipython>=4.0.0->ipykernel>=4.8.2->spyder-kernels<1.0,>=0.4.3->spyder) (0.8.1)
Requirement already satisfied: wcwidth in c:\[...]\site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->ipykernel>=4.8.2->spyder-kernels<1.0,>=0.4.3->spyder) (0.1.7)

**Comment by washiur17** [comment] 2020-10-15 10:24
I have installed pyqtwebengine, but another error. I have following version installed.
PyQt5 - 5.15.1
PyQtWebEngine - 5.15.1

ERROR: Could not find a version that satisfies the requirement pyqt5<5.13; python_version >= "3" (from spyder) (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1)
ERROR: No matching distribution found for pyqt5<5.13; python_version >= "3" (from spyder)
