### ISSUE TITLE
How to upload/update my under develope project in spyder in githup 

### ISSUE THREAD

**Issue by isalirezag** [spyder-ide/spyder#10342] opened 2019-10-02 15:36 UTC
Thanks for making spyder great every day

Im using Spyder 3.3.6
Python 3.6.6 64-bit | 
Qt 5.9.6 | 
PyQt5 5.9.2 | 
Linux 4.15.0-65-generic 
I am using ubuntu 16.04

I am wondering if there is a way to upload/update my under develope project in spyder in my githup page and keep a copy of each version/update of my code?

Appreciate the help!

**Comment by bcolsen** [comment] 2019-10-02 19:21
> Thanks for making spyder great every day

Thanks for using it!

I'm closing this as a duplicate of #816 which is planned for a future release.

**Closed by bcolsen** 2019-10-02 19:21 UTC
