### ISSUE TITLE
Triangle showing line fails lint not displaying

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10133] opened 2019-09-04 18:46 UTC
### What steps will reproduce the problem?

After installing 4.0.0b4 I am no longer seeing the triangle symbols in the left hand side of the editor denoting a lint error. I do have linting turned on in Preferences.

If I hover the mouse over the line number of a line that has a lint error I get a pop up window displaying the lint error, so linting is happening. I also turned on underlining of errors and warnings, and the underlines seem to be correct as well. 

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-09-04 20:08
This is extremely vague. Please post a code sample that should show a lint error and it's not appearing.

**Comment by rlabbe** [comment] 2019-09-04 20:34
Any string at all. The specific line doesn't matter, so long as it contains an error that triggers lint.  The triangles never appear. For example, put this in line 1 of an otherwise empty editor:

    x     = 1

This should trigger E221 - multiple spaces before operator and W292 - no newline at end of file . Lint successfully finds this, because the text is underlined (I have underlining of errors turned on), and if you hover the mouse over the line number "1" in the left hand gutter it pops up a window displaying both of these. However, the yellow triangle that used to be displayed to the left of the line number is not displayed.

**Comment by bcolsen** [comment] 2019-09-04 21:40
Cannot reproduce on latest master using Ubuntu

![image](https://user-images.githubusercontent.com/10513354/64293630-3ec22e00-cf2a-11e9-8854-9cdc647f3d39.png)

**Comment by ccordoba12** [comment] 2019-09-04 22:48
@dalthviz, can you reproduce this on Windows?

**Comment by dalthviz** [comment] 2019-09-04 23:10
@ccordoba12 it works for me on Windows 10:
![image](https://user-images.githubusercontent.com/16781833/64299576-4213e480-cf3f-11e9-8493-80e7551f315d.png)

**Comment by ccordoba12** [comment] 2019-09-04 23:13
This is probably related to #10139 because right now setting docstring linting is broken through our Preferences.

@rlabbe, I'm going to close this one. Please mention if it's fixed after we release beta5.

**Closed by ccordoba12** 2019-09-04 23:13 UTC
Labels: status:Awaiting Followup
