### ISSUE TITLE
Crash when inspecting pandas Dataframe variable in Variable Explorer

### ISSUE THREAD

**Issue by ben0r33** [spyder-ide/spyder#17438] opened 2022-03-05 11:07 UTC
## What steps will reproduce the problem?
Inspecting pandas Dataframe variable in Variable Explorer causes variable window to crash (double click on variable).
```
import pandas as pd
a=pd.DataFrame([1,2])
```
## Traceback
```
Traceback (most recent call last):
  File "C:\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 203, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 948, in setup_and_check
    self.create_data_table()
  File "C:\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 1072, in create_data_table
    self.dataTable = DataFrameView(self, self.dataModel,
  File "C:\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 538, in __init__
    self.setHorizontalScrollMode(1)
TypeError: 'PySide2.QtWidgets.QAbstractItemView.setHorizontalScrollMode' called with wrong argument types:
  PySide2.QtWidgets.QAbstractItemView.setHorizontalScrollMode(int)
Supported signatures:
  PySide2.QtWidgets.QAbstractItemView.setHorizontalScrollMode(PySide2.QtWidgets.QAbstractItemView.ScrollMode)
```

## Versions
WinPython64-3.10.2.0
  - Spyder version: 5.2.2
  - Python version: 3.10.2
  - qtpy version: 2.0.0
  - qtpy.QtCore:  5.15.2
  - PySide2: 5.15.2.1

## Spyder Dependencies
```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.0 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2022-03-05 17:57
Hey @ben0r33, thanks for reporting. This is a duplicate of issue #17139 and it'll be fixed in our next version (5.3.0).

In the meantime, please Spyder with PyQt5 and Python 3.9 because that version doesn't have this error.

**Closed by ccordoba12** 2022-03-05 17:57 UTC
