### ISSUE TITLE
Enable automatic insertion of closing quotes inside function calls

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#6827] opened 2018-03-23 22:14 UTC
## Problem Description
I want the same behaviour as in jupyter notebook of automatic closing of quotes. I change the setting of spyder editor to enable automatic insertion of closing quotes. 

It works fine while typing in the editor but does not works inside functions.

Could you help me  how to resolve this issue!?

### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python
import numpy as np
import matplotlib.pyplot as plt

a = np.linspace(0,10,2001)
b = np.cos(a*np.pi)

plt.plot(a, b)
plt.title(') # does not work here: only opening quotes

'' # works here: automatically closes the quotes
```

## Package Versions

* Spyder: 3.2.6
* Python: 3.6.4
* Qt:
* PyQt:
* Operating System: windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment] 2018-03-23 22:50
I can confirm this behavior also occurs on my machine. However, I am not sure if it is intended for some reason, or is just a current limitation of the system. I'd certainly prefer if it worked.

@ccordoba12 ?

**Comment by ccordoba12** [comment] 2018-03-23 23:25
I think this happens when there's some text to the right of the quote you're inserting. @Khalilsqu, could you verity it?

**Comment by CAM-Gerlach** [comment] 2018-03-23 23:27
@ccordoba12 Yup, that's it. In this case, its the auto-insertion of the closing paren of the function call that blocks it.

**Comment by Khalilsqu** [comment] 2018-03-24 09:03
@ccordoba12 yes, whenever there is a leading character in the line, the automatic insertion of closing quotes does not work.

**Comment by CAM-Gerlach** [comment] 2018-03-24 17:37
@Khalilsqu A leading character? According to my tests and confirming @ccordoba12 's suspicion above, it was the *trailing* character that was the problem, not the leading one.

**Comment by Khalilsqu** [comment] 2018-10-29 21:41
Hi, Thanks for all efforts toward releasing spyder 4, I installed the dev version but still have this issue.

**Comment by ccordoba12** [comment] 2018-10-29 23:54
That's why this issue this issue is still open.

**Comment by bcolsen** [comment] 2019-01-28 17:08
A fix for this should close the quotes when any closing bracket type or a comma is the next character to the right. A similar functionality is in close brackets.

**Comment by ccordoba12** [comment] 2019-01-28 17:10
So is this going to be fixed by your PR too?

**Comment by CAM-Gerlach** [comment] 2019-01-28 18:08
That'd be really handy, thanks! I can't tell you how many times I forget this, haha.

**Closed** 2019-01-29 12:25 UTC
Labels: component:Editor, status:Reproduced
