### ISSUE TITLE
Spyder 3 hangs on Windows 10 when working in IPython console

### ISSUE THREAD

**Issue by whunter7** [spyder-ide/spyder#11307] opened 2020-01-13 14:34 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder starts normally. After 2-3 directory navigation commands in the IPython console, it freezes. "Not Responding" appears in the title bar (as well as beside one of the Python processes in Task Manager).

### What steps reproduce the problem?

1. Start Spyder any way.
2. Enter 2-3 directory navigation commands in the console, e.g.
`cd`
`cd Desktop`
`ls` -> freeze!
(entering math commands does not cause any problem, e.g. `1+2`, ...).
OR
Execute a small script calling a function to print using run button, and then try to write into console.
OR
presumably many more particular combinations of working directly in the console.

### What is the expected output? What do you see instead?

The console doesn't respond, then the entire Spyder window is shaded white and "Not Responding" appears in the title bar (as well as beside one of the Python processes in Task Manager).

### Paste Traceback/Error Below (if applicable)

Nothing appears in the internal console, nothing appears in the Anaconda Prompt when Spyder is started there. Using flag SPYDER_DEBUG=3, nothing unusual appears, the output ends at "Initialized Rope".

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.11.1 (OK)
cython >=0.21     :  0.29.14 (OK)
jedi >=0.9.0      :  0.15.2 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  1.17.4 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.5.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.3.1 (OK)
sympy >=0.7.3     :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-13 18:43
Duplicate of #10081. We haven't found a fix for that yet, although things could be better in our next release (4.0.2).

**Closed by ccordoba12** 2020-01-13 18:43 UTC
