### ISSUE TITLE
Error when installing Anaconda on D:\ drive

### ISSUE THREAD

**Issue by yebangling** [spyder-ide/spyder#5704] opened 2017-11-09 01:35 UTC
## Description

**What steps will reproduce the problem?**

1. Pop-up when opening anaconda2 spyder
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "D:\Program Files (x86)\Anaconda2\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kerne

**Comment by ccordoba12** [comment] 2017-11-09 03:48
Please install Anaconda in your `C:\` drive and try again.

**Comment by yebangling** [comment] 2017-11-09 06:29
Thanks, the problem with your method has been solved.

**Comment by ccordoba12** [comment] 2017-11-09 12:57
Thanks for the confirmation!

@dalthviz, do you have a `D:\` drive you can install Anaconda into to verify if this error happens to you too?

**Comment by dalthviz** [comment] 2017-11-09 18:49
Yep, I have one :+1:

**Comment by ccordoba12** [comment] 2017-11-09 19:51
Ok, great! Please uninstall your Anaconda from `C:\` though, so the only installation you have is the `D:\` one.

**Comment by CAM-Gerlach** [comment] 2018-01-30 09:06
While the error traceback is incomplete, this is is an apparent duplicate of #6319 , which should be fixed in the next Spyder release. Therefore, this issue will be closed. In the meantime, you can fix it yourself by either:

* Running ``spdyer --reset`` from the Anaconda prompt, or
* Going to ``Preferences`` > ``Python interpreter`` and selecting either the Default interpreter or a new, valid custom one.

**Closed by CAM-Gerlach** 2018-01-30 09:06 UTC
Labels: type:Bug

**Comment by ccordoba12** [comment] 2018-01-30 12:36
This is really a duplicate of issue #4958.

**Comment by CAM-Gerlach** [comment] 2018-01-30 16:33
Thanks @ccordoba12

**Comment by nikhil561997** [comment] 2019-11-21 19:55
I am also facing the same issue. Please help on how I can install Anaconda in D Drive.

**Comment by CAM-Gerlach** [comment] 2019-11-22 00:11
> I am also facing the same issue. Please help on how I can install Anaconda in D Drive.

@nikhil561997 If you're having trouble installing Anaconda, please open an issue with Anaconda instead; the Spyder developers on this repo don't have any direct control over their install process, sorry. Best of luck.

**Comment by 1Lohita** [comment] 2023-09-28 16:02
can we install anaconda in d drive ?

**Comment by ccordoba12** [comment] 2023-09-28 16:17
@1Lohita, yeah, I think it should be possible now (this is a very old issue, as you can see from the dates in each comment).

**Comment by CAM-Gerlach** [comment] 2023-10-27 15:36
FWIW, I've tested installing Anaconda and using Spyder a couple years ago on a (then) fresh Windows 10 laptop, and couldn't find any issues like this. Furthermore, it was reported on an Anaconda with Python 2 compiled in 32-bit (x86) mode, neither of which are fully supported by Anaconda anymore. Therefore, seems pretty unlikely to still have the same problem, at least due to the same cause.

If you do run into a bug with Spyder specifically, you can open a new issue here, or just use [our recommended standalone installers](https://www.spyder-ide.org/#section-download) which avoid most of these issues and can work with your existing Anaconda installation. Thanks!
