### ISSUE TITLE
unexpectly close

### ISSUE THREAD

**Issue by cyf203** [spyder-ide/spyder#12207] opened 2020-04-07 16:13 UTC
### What steps will reproduce the problem?

when I was trying to type code and the unexpectly quit happened.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\fallback\actor.py", line 155, in handle_msg
    msg['current_word'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\fallback\actor.py", line 62, in tokenize
    valid = is_prefix_valid(text, offset, language)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\fallback\utils.py", line 125, in is_prefix_valid
    current_pos_text = text[offset - utf16_diff - 1]
IndexError: string index out of range
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-04-07 16:35
> when I was trying to type code and the unexpectly quit happened.

Please upload the entire file you were editing when this error happened to you.

**Comment by cyf203** [comment] 2020-04-08 15:12
Below is the file that I was working on. But after restart spyder, I can work normally. It occurred occasionally and had no specific trigger.
```
import Functions as func
import agents as ag
import task as tk
import numpy as np
import pandas as pd
from tqdm import tqdm

#%%

def simulate_sessions (agent, task, n_trials = 300, sessions=100):
    print('Simulating: <' + agent.name + '> in <' + task.name + '>')
    result = {}
    for s in tqdm(range(sessions)):
        a1, a2, trans, r, switch_tag = agent.simulation(task, n_trials)
        result[s] = pd.DataFrame({'a1': a1,
                                  'a2': a2,
                                  'trans': trans,
                                  'r': r,
                                  'switch': switch_tag})
    return result

agents = {'Q0': ag.Q_lambda(lambd =0, alpha = 0.5, iTemp = 5),
          'Q1': ag.Q_lambda(lambd =1, alpha = 0.5, iTemp = 5),
          'MB': ag.Model_based(alpha = 0.5, iTemp = 5)}

task_o = tk.Two_step(com_prob = 0.8, block_length = 50, probs = [0.8, 0.2], block_rand = 0.02)
task_flip = tk.Two_step_transition_flip (block_length = 50, probs = [0.8, 0.2], block_rand = 0.02)

data_o = {a_type: simulate_sessions(agent, task_o, n_trials = 1000, sessions = 100) for a_type, agent in agents.items()}
data_flip = {a_type: simulate_sessions(agent, task_flip, n_trials = 1000, sessions = 100) for a_type, agent in agents.items()}

#%%
def analysis_stay_probability (a_type, agent_data, window_length = 20):
    temp = []
    print ('Analysis stay probability: <' + a_type+'> ')
    for t, t_data in agent_data.items():
        if window_length:
            print ('\tlast %s trials\' data'%window_length)
            idx = t_data[t_data['switch'] == 1].index.values
            select = np.hstack([np.arange(i-window_length,i) for i in idx])
            data = t_data.iloc[select].copy()
        else:
            print ('\tall data')
            data = t_data.copy()
        
        data['C1'] =  ((data['trans'] == 1) & (data['r'] == 1)).astype(int)
        data['C0'] =  ((data['trans'] == 1) & (data['r'] == 0)).astype(int)
        data['R1'] =  ((data['trans'] == 0) & (data['r'] == 1)).astype(int)
        data['R0'] =  ((data['trans'] == 0) & (data['r'] == 0)).astype(int)
    
        temp.append(data[['C1','C0','R1','R0']].sum()/len(data[['C1','C0','R1','R0']]))
    temp_df = pd.concat(temp, axis = 1).transpose()
    mean = temp_df.mean()
    se = temp_df.std()/np.sqrt(temp_df.count())
    mean_stay_prob = {'mean': mean, 'se': se}
    return mean_stay_prob

#%%
stay_prob_o = {a_type: analysis_stay_probability (a_type, data, window_length = 20) for a_type, data in data_o.items()}
stay_prob_flip = {a_type: analysis_stay_probability (a_type, data, window_length = 20) for a_type, data in data_flip.items()}


#%%
import matplotlib as mpl
import matplotlib.pyplot as plt
import mplcursors
#check if desired font type available
#if not available download a *.ttf file and move to the 
#folder path: C:\Users\<user name>\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\fonts\ttf\
#Then run the code below and check if the font type exits
# from matplotlib import font_manager
# font_manager._rebuild()
# font_manager.findfont('Arial Narrow')

#Load plot configuration
mpl.rcParams['font.family'] = 'Arial Narrow'
mpl.rcParams['axes.linewidth'] = 1
mpl.rcParams['axes.spines.left'] = True
mpl.rcParams['axes.spines.right'] = False
mpl.rcParams['axes.spines.top'] = False
mpl.rcParams['axes.titlepad'] = 10
mpl.rcParams['xtick.labelsize']= 10 
mpl.rcParams['ytick.labelsize'] =10
mpl.rcParams['xtick.major.pad'] = 3
mpl.rcParams['ytick.major.pad'] = 3
mpl.rcParams['axes.labelpad'] = 2
mpl.rcParams['pdf.fonttype'] = 42 #!!!this is important for generate a clear text figure for illustrator editing
#for PPT purpose
#mpl.rcParams['ytick.color'] = "w"
#mpl.rcParams['xtick.color'] = 'w'
#mpl.rcParams['axes.labelcolor'] = 'w'
#mpl.rcParams['axes.edgecolor'] = 'w'

n_agent = len(agents)
fig, axes = plt.subplots(2, n_agent)
fig.set_size_inches(7, 4)  #w*h (8.5inch width for letter size, publishable, max height is 11inch)
axes = axes.reshape(-1)

x_label = ['C1', 'C0', 'R1', 'R0']
x = [1,2,3,4]

labels = []
n = 0
color = '#4692AA'
for stay_prob in (stay_prob_o, stay_prob_flip):
    for a_type, d in stay_prob.items():
        mean = d['mean'].values
        se = d['se'].values
        l = func.plot_bar (axes[n], x=x, y=mean, SE=se, bar_gap = 0.8,
                           error_kw = {'capsize':10, 'elinewidth':0.5, 'capthick':0.5, 'ecolor': color},
                           lw = 0, edgecolor = color, color = color, tick_label = x_label, label = a_type)    
        func.format_axis(axes[n], ytitle = 'Stay Probabilities', ylim = '0,1', xlim='0.5, 4.5', fig_title = a_type)
        labels.append(l)
        n += 1     

mplcursors.cursor(highlight=True).connect("add", lambda sel: sel.annotation.set_text(sel.artist.get_label()))

fig.patch.set_facecolor('none')
fig.patch.set_alpha(0)
fig.tight_layout()





#%%
def analysis_performance (a_type, agent_data, window_length = 20):
    temp = []
    print ('Analysis performance: <' + a_type+'> ')
    for t, t_data in agent_data.items():
        if window_length:
            print ('\tlast %s trials\' data'%window_length)
            idx = t_data[t_data['switch'] == 1].index.values
            select = np.hstack([np.arange(i-window_length,i) for i in idx])
            data = t_data.iloc[select].copy()
        else:
            print ('\tall data')
            data = t_data.copy()
    
        temp.append(data[data['r']==1].sum()/len(data['r']))
    temp = np.array(temp)
    mean = np.nanmean(temp)
    se = np.nanstd(temp)/np.sqrt(len(temp))
    mean_stay_prob = {'mean': mean, 'se': se}
    return mean_stay_prob



performance_o = {a_type: analysis_performance (a_type, data, window_length = None) for a_type, data in data_o.items()}
performance_flip = {a_type: analysis_performance (a_type, data, window_length = None) for a_type, data in data_flip.items()}


#%%
fig, axes = plt.subplots(1, 2)
fig.set_size_inches(3, 2)  #w*h (8.5inch width for letter size, publishable, max height is 11inch)
axes = axes.reshape(-1)

x_label = [l for l in agents.keys()]
x = np.arange(1,len(agents))
titles = ['No flip', 'Flip']
labels = []
color = '#4692AA'
for n, stay_prob in enumerate((performance_o, performance_flip)):
    perf_df = pd.DataFrame(stay_prob).transpose()
    mean = perf_df['mean'].values
    se = perf_df['se'].values
    l = func.plot_bar (axes[n], x=x, y=mean, SE=se, bar_gap = 0.8,
                       error_kw = {'capsize':6, 'elinewidth':0.5, 'capthick':0.5, 'ecolor': color},
                       lw = 0, edgecolor = color, color = color, tick_label = x_label, label = a_type)    
    func.format_axis(axes[n], ytitle = 'Reward Rate', ylim = '0,1', xlim='0.5, 3.5', fig_title = titles[n])
    labels.append(l)
    n += 1     

mplcursors.cursor(highlight=True).connect("add", lambda sel: sel.annotation.set_text(sel.artist.get_label()))

fig.patch.set_facecolor('none')
fig.patch.set_alpha(0)
fig.tight_layout()
```

**Comment by ccordoba12** [comment] 2020-04-08 18:14
I can't reproduce it with your code. Instead of uploading the contents of your file, please upload the file itself. Thanks!

**Comment by ccordoba12** [comment] 2020-04-10 17:42
Duplicate of #12266

**Closed by ccordoba12** 2020-04-10 17:42 UTC
Labels: status:Awaiting Followup
