### ISSUE TITLE
Spyder Dev Tools: Signal Tracer

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#881] opened 2015-02-17 00:54 UTC
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-12-13T06:40:11Z_

What steps will reproduce the problem?

1. No way to debug how Qt signals really behave in Spyder
2. No way trace signals as they are fired in real-time What is the expected output? What do you see instead? While inspecting Spyder signals, static analysis (i.e. looking at the code) is time consuming and therefore doesn't always end successfully. It will be much more convenient to have a development widget that will serve as entrypoint for debugging signals and handlers.

I'm looking for something that will help me to track signals at run-time (dynamically) by listing all available signals, and help other people understand what's going on (intuitive visualization) by tracking in real-time when fired and handled.

This widget/API should allow:
 - get the list of all signals
 - get the list of all subscribes given signal name
 - receive notification when a new subscriber appears (and vanishes)
 - receive notification when a new signal type appears (and removes)
 - receive notification when a signal fires, in which order subscribers are called

Questions:
 - Does Qt/PySide provide some useful API?
 - Can subscriber cancel signal processing by further subscribers?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=881_

**Comment by spyder-issues-migrator** [comment] 2015-02-17 00:54
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:07:16Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by ccordoba12** [comment] 2015-04-20 19:16
Closing as duplicate of #1421

**Closed by ccordoba12** 2015-04-20 19:16 UTC
Labels: 1 star, duplicate, enhancement, Maintainability
