### ISSUE TITLE
Update Error when adding PyPDF2 package

### ISSUE THREAD

**Issue by Andyfrost22** [spyder-ide/spyder#11589] opened 2020-02-18 17:18 UTC
### What steps will reproduce the problem?

I am working on a project with my team in python. The application that I program in is Spyder. I noticed that I needed to import some additional packages to call certain functions, so I tried various entries in the command prompt. I noticed while I was doing all of this that my version had an available update to 4.1. So I updated it and now it keeps crashing on me. I can't run spyder now. I keep getting this message "Spyder crashed during last session" and "Warning: this command will remove all your Spyder configuration file located in ...". Any help would be great! I just need this to work for my work. 

### Traceback
```python-traceback
  File "C:\PROGRA~1\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 108, in get_status
    self.sig_status_response_ready[dict].emit(kite_status)
TypeError: KiteClient.sig_status_response_ready[dict].emit(): argument 1 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\PROGRA~1\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 108, in get_status
    self.sig_status_response_ready[dict].emit(kite_status)
TypeError: KiteClient.sig_status_response_ready[dict].emit(): argument 1 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\PROGRA~1\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 108, in get_status
    self.sig_status_response_ready[dict].emit(kite_status)
TypeError: KiteClient.sig_status_response_ready[dict].emit(): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  0.8.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.4.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.4.1 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.1 (OK)
pygments >=2.0               :  2.3.1 (OK)
pylint >=0.25                :  2.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.7.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.6 (OK)
matplotlib >=2.0.0           :  3.0.3 (OK)
numpy >=1.7                  :  1.16.2 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.2.1 (OK)
sympy >=0.7.3                :  1.3 (OK)
```

**Comment by ccordoba12** [comment] 2020-02-18 17:35
This is already fixed, right @dalthviz?

**Comment by dalthviz** [comment] 2020-02-18 17:53
@ccordoba12 I think this is a duplicate of #11235 

@Andyfrost22 do you have Kite installed? Could you try what https://github.com/spyder-ide/spyder/issues/11235#issuecomment-571265409 says? Please post your feedback in issue #11235, thanks!

Also @Andyfrost22, you could try to go back to Spyder 3 with `conda install spyder=3.3.6` in order to avoid Spyder crashing for this error.

**Comment by ccordoba12** [comment] 2020-02-18 21:16
Duplicate of #11235

**Closed by ccordoba12** 2020-02-18 21:16 UTC
