### ISSUE TITLE
Include PyQt5 as pip dependency

### ISSUE THREAD

**Issue by JakobJakobson** [spyder-ide/spyder#5736] opened 2017-11-13 12:50 UTC
Dear developers,

I installed Spyder via pip and I noticed that PyQt5 and Matplotlib don't get installed automatically with the ```pip install spyder``` command.
You probably don't want to include to much pip-dependencies into the spyder package but could you include at least one of the PyQts (either 4 or 5)? That would be helpful as Spyder needs one of those to work.
Also I think that matplotlib seems as a pretty useful tool for spyder users, so could you include this as a dependency as well?

Regards,

Jakob

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-11-13 13:23
We can pyqt5 to our dependencies, but matplotlib is really optional, so we can't force it to our users.

**Comment by ccordoba12** [comment] 2017-11-30 02:13
This is a duplicate of issue #3242.

**Closed by ccordoba12** 2017-11-30 02:13 UTC
Labels: tag:Ux-usability, type:Enhancement
