### ISSUE TITLE
unsure -  as I was watching another screen

### ISSUE THREAD

**Issue by mickartz** [spyder-ide/spyder#16192] opened 2021-08-10 14:21 UTC
### What steps will reproduce the problem?

I was doing a lot of graphical printing?
matplotlib and seaborn
heatmaps

### Traceback
```python-traceback

QPainter::save: Painter not active
QPainter::setPen: Painter not active
QFont::setPixelSize: Pixel size <= 0 (0)
QPainter::setFont: Painter not active
QPainter::setOpacity: Painter not active
QPainter::restore: Unbalanced save/restore
Traceback (most recent call last):
  File "C:\Users\micka\anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 243, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\Users\micka\anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 766, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\Users\micka\anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 847, in set_current_thumbnail
    self.figure_viewer.load_figure(
  File "C:\Users\micka\anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 380, in load_figure
    self.scale_image()
  File "C:\Users\micka\anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 487, in scale_image
    self.sig_zoom_changed.emit(self.get_scaling())
  File "C:\Users\micka\anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 491, in get_scaling
    return round(self.figcanvas.width() / self.figcanvas.fwidth * 100)
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment] 2021-08-11 02:55
Hey @mickartz, thanks for reporting. This is a duplicate of issue #15223 and we'll try to fix it in a future release.

**Closed by ccordoba12** 2021-08-11 02:55 UTC
