### ISSUE TITLE
Can not input Chinese by fcitx

### ISSUE THREAD

**Issue by miaochangq** [spyder-ide/spyder#14249] opened 2020-11-18 07:20 UTC
### What steps will reproduce the problem?

I use the Manjaro Linux,but i can not input Chinese by fcitx.

### Traceback
```python-traceback
  File "/home/mcq/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/snippets/actor.py", line 92, in handle_msg
    if language_snippets[current_word]:
  File "/home/mcq/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/snippets/trie.py", line 81, in __getitem__
    if len(sequence) == 0:
TypeError: object of type 'NoneType' has no len()
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.8.3
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.8.18-1-MANJARO

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.5.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.2.1 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.5.3 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  50.3.0 (OK)
sphinx >=0.6.6                  :  3.1.2 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  19.0.1 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.2.2 (OK)
numpy >=1.7                     :  1.18.5 (OK)
pandas >=1.1.1                  :  1.0.5 (NOK)
scipy >=0.17.0                  :  1.5.0 (OK)
sympy >=0.7.3                   :  1.6.1 (OK)
```

**Comment by dalthviz** [comment] 2020-11-18 17:45
Hi @miaochangq this is a duplicate of #14183. The fix (#14186) will be part of our next release (Spyder `4.2.1`)

**Closed by dalthviz** 2020-11-18 17:45 UTC
Labels: resolution:Duplicate

**Comment by jitseniesen** [comment] 2020-11-19 09:39
@miaochangq As for inputting Chinese with fcitx, you need a library called fcitx-qt for this but fcitx-qt is not available in Anaconda. This is discussed in #4120. That issue also contains a possible workaround, but it is a bit complicated.

**Comment by dalthviz** [comment] 2020-11-19 14:23
Thanks @jitseniesen for the info! :+1:
