### ISSUE TITLE
InternalProblem

### ISSUE THREAD

**Issue by alex-taye** [spyder-ide/spyder#14850] opened 2021-03-02 18:30 UTC
### What steps will reproduce the problem?

"Spyder has encountered an internal problem" opened and spyder shutdown shortly after. 

### Traceback
```python-traceback
  File "/Users/alemayehu.taye/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 739, in eventFilter
    self._update_thumbnail_size()
  File "/Users/alemayehu.taye/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 842, in _update_thumbnail_size
    self._setup_thumbnail_size(thumbnail)
  File "/Users/alemayehu.taye/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 826, in _setup_thumbnail_size
    thumbnail.scale_canvas_size(max_canvas_size)
  File "/Users/alemayehu.taye/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 1046, in scale_canvas_size
    if fwidth / fheight > 1:
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by steff456** [comment] 2021-03-02 23:36
Hi @alex-taye,

This issue is a duplicate of https://github.com/spyder-ide/spyder/issues/12253 and it is already fixed. Please update to our latest version.

Thanks for reporting!

**Closed by steff456** 2021-03-02 23:36 UTC
