### ISSUE TITLE
IDE Spyder

### ISSUE THREAD

**Issue by rodneyrick** [spyder-ide/spyder#5976] opened 2017-12-13 14:52 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()

**Comment by CAM-Gerlach** [comment] 2017-12-13 15:34
Thanks for reporting. The error traceback that was posted is apparently incomplete. However, it is very likely a duplicate of e.g. #5673 , an error that's been reported numerous times now. As the full error message states, Jedi is only compatible with `parso` 0.1.0, not 0.1.1. Therefore, you can update `jedi` to the latest version with `conda update jedi` (or with `pip`, if you use that instead); you can also downgrade to `parso` 0.1.0 with e.g. `conda install parso=0.1.0` , and you can close this issue.

**Comment by rodneyrick** [comment] 2017-12-13 17:15
Hi,

Thanks for help me.

Now, it's working.


Att.,

Rodney Rick

**Closed** 2017-12-14 15:39 UTC
