### ISSUE TITLE
Spyder kernel issue

### ISSUE THREAD

**Issue by Biswajit1995** [spyder-ide/spyder#6149] opened 2018-01-06 19:09 UTC
## Description

**What steps will reproduce the problem?**

1. Starting of Spyder
2. Restarting the kernel

**Reinstalled but still this problem persist**
Uninstalled python3.6 (not Anaconda Version) also

**Here is the error that appear on kernel screen**

  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\bsaho.DESKTOP-AEPCQEA\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, i

**Comment by CAM-Gerlach** [comment] 2018-01-06 20:38
Thanks for reporting. While the error message is incomplete, from what can be seen it looks like a likely duplicate of #5257, and this is probably either an issue with your firewall/anitvirus (which should be competely disabled to see if that fixes it), or a problem with your install in some fashion. Updating to the latest Spyder version with ``conda update conda``, resetting spyder's preferences with `spyder --reset` from the Anaconda prompt (closing Spyder before and reopening it after), or uninstalling and doing a clean reinstall of the latest version of Anaconda3 (5.0.1). .

Therefore, this issue will be closed, but if it persists after the above, please follow the rest of our [Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), carefully, and if still present please post and re-open this issue with that information  If we don't hear from you, we'll have to close this issue after a week (7 days). Thanks.

**Closed by CAM-Gerlach** 2018-01-06 20:38 UTC
