### ISSUE TITLE
Spyder blocking internet

### ISSUE THREAD

**Issue by Calvinxc1** [spyder-ide/spyder#3601] opened 2016-10-26 00:21 UTC
## Description of your problem

Spyder seems to randomly/intermittently freeze my internet connection when I have it loaded.

**What steps will reproduce the problem?**
1. Load Spyder
2. Load any internet application (most noticeable with Teamspeak/Skype)

**What is the expected output? What do you see instead?**
Every 30 seconds to a minute anything that uses internet looses connection for about a second or so. With VOIP applications, the audio completely drops during this time, then suddenly comes back.

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 3.0.1
- Python Version: 2.7.12
- Operating system: Windows 10
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by walter7878** [comment] 2018-01-23 01:11
This is killing me, and I have no idea how to solve it... Did not found any solution so far, had to move back to Jupyter

**Comment by CAM-Gerlach** [comment] 2018-01-30 10:07
Thanks for reporting, and sorry you're having such an issue. Can you try updating Spyder and your Anaconda environment to the latest version with 
```
conda update conda 
conda update anaconda
conda update spyder
```
and see if it reoccurs? 

Also, can you try the suggestions in our new [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

Beyond that, can you take a look at your logs and/or firewall to see if any insightful messages are present, and test with any security software disabled? Not really sure how Spyder's doing this...

**Comment by walter7878** [comment] 2018-01-30 12:35
Hi! All udated, firewall down just in case, and still killing my (win 10) connection. 
![data](https://user-images.githubusercontent.com/34683593/35566645-65ab716c-05c2-11e8-9481-deb031e1e0dc.JPG)

**Comment by Calvinxc1** [comment] 2018-01-30 13:28
I'll need to test it this weekend (when I have more then 2 minutes of free time to do so...) but I can say that when I first started using Spyder (about two and a half years ago) this wasn't a problem. It became a problem after updates sometime in late 2015.

**Comment by CAM-Gerlach** [comment] 2018-01-30 16:10
Are those instantaneous values, or totals? I'll keep Process Explorer open during a day's use of Spyder and see what I find. The vast majority of that, if not all of it, is probably loopback traffic from Spyder to the IPython console, and the reverse. One of the big things I can think of is opening and closing large dataframes in the Variable Explorer. However, I'm not the expert on this area so perhaps @ccordoba12 could provide more insight. However, I'm not sure how this would have any actual effect on your real network bandwidth, as it doesn't actually go out via your network interface, though might put load on other parts of your system. Once we get more information from you, we can elevate it to the person who might.

Therefore, can you look through the troubleshooting as I requested above to make sure none of that applies/helps the situation, and provide any of the information suggested there?

**Comment by Calvinxc1** [comment] 2018-02-02 05:04
Just tried it again, after running the updates indicated, same problem. I didn't have any variables loaded, I literally opened Spyder and had it running in the background without having any code run, and I still got the same interruptions in my internet.

I don't think it's a network bandwidth issue, my hunch is it's more to do with something locking up all network interfaces waiting for something. Not sure what though, but it feels very consistent, like some sort of background script running every minute or so.

**Comment by walter7878** [comment] 2018-02-02 08:09
Same here, changing firewall did not change the problem. I just stopped using Spyder, until I found how to solve this, as I need to continue working... :-(

**Comment by CAM-Gerlach** [comment] 2018-02-03 01:45
@Calvinxc1 @walter7878 Okay; really sorry to hear that. I wasn't able to reproduce anything like this on either my Windows 8.1 or Windows 10 machine with Spyder open all the time, so apparently it is affecting some setups, but not others.

As I've been requesting in my last couple posts, in order to maximize the changes of this getting solved both on your end and ours, can you please try the all the procedures listed in our new [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections?

Furthermore, if none of that fixes it, can you provide any of the relevant information listed in the [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section of the guide, if not already present? Again, if we can't reproduce the problem, we can only blindly guess at what's causing it without more information, or until an expert like @ccordoba12 is able to respond. Thanks.

**Comment by ccordoba12** [comment] 2018-02-03 04:04
> or until an expert like @ccordoba12 is able to respond.

I've seen a few reports about this, but I have no idea what's causing this problem, sorry.

**Comment by CAM-Gerlach** [comment] 2018-02-03 05:35
In that case, the above instructions are likely to be your best bet for now.

**Comment by Calvinxc1** [comment] 2018-02-03 22:53
In all steps I closed spyder, applied the step, and reopened spyder but didn't do anything with it (it was sitting in the background while I was keeping an eye on internet activity). Testing method involves running an internet speed test (http://www.speedtest.net/) and using Windows task manager to examine wifi usage during this time. I know if it's being a problem if during the test I see an unexplainable total drop-off of transmission. If I don't notice a dip with one run, I'll run it up to 4 more times.

Restart spyder: had previously done this, no change
Upgrade spyder: already did this, no change
Update spyder dependencies: already did this, no change
Ran "spyder --reset" from anaconda prompt: no change
Ran spyder from a fresh conda env: no change
Reinstall anaconda: had previously done this, no change
Starting spyder in other ways: tried both start menu button and launching from console, no difference

Installing Anaconda for all users (was installed just for me) to startup drive with letter-only directories (Anaconda3 5.0.1, win10, 64bit): No change
Update conda: No change
Update anaconda: No change
Update spyder: No change
Disabled antivirus & spyware software: No change

The interruptions are still in roughly 30 sec to 1 minute intervals, and usually only lasts 1-2 seconds, and they involve a complete loss of any network traffic coming from/going to my computer.

**Comment by Calvinxc1** [comment] 2018-02-06 00:21
One other thing I just noticed: When the connection resumes after being interrupted, there's a huge surge of data that comes in, like my computer was caching what was coming in waiting for the connection to be available again.

**Comment by walter7878** [comment] 2018-02-06 00:52
Another comment here: one Spyder is running, TCP connections go to the top, and only go back down if I close Spyder.

**Comment by ccordoba12** [comment] 2019-07-21 14:53
Closing because this doesn't seem to be a problem anymore.

**Closed by ccordoba12** 2019-07-21 14:53 UTC
Labels: status:Awaiting Followup

**Comment by Calvinxc1** [comment] 2019-07-21 15:10
Umm, no, still an issue, just never resolved.

**Comment by sergionovi** [comment] 2020-07-29 14:28
I am having the same problem

**Comment by dalthviz** [comment] 2020-07-29 16:20
Hi @sergionovi sorry to hear that. Are you using the latest version of Spyder (4.1.4)?

**Comment by sergionovi** [comment] 2020-07-29 17:43
Hi @dalthviz I was using version 3.7. Now I am trying to update it to 4.1.4. I will let you know if the updating solves the problem.

**Comment by CAM-Gerlach** [comment] 2020-07-29 21:04
Just FYI, there isn't a version 3.7 of Spyder; do you mean Python 3.7? Do you observe the exact same behavior as the OP, or is it different? Any details you can provide us would be really helpful in tracking down what's going and seeing what we do to solve it. Thanks!

**Comment by sergionovi** [comment] 2020-07-29 22:43
Hi @CAM-Gerlach, sorry; my spyder version is 3.3.6 and Python 3.7. I was observing the exact behavior. I updated the Spyder to version 4.1.4., but it started to crash as soon as I started it. 
First, there was an error related to matplotlib. This error I could solve. Next, there was another error related to kernels. I tried to solve it, but it did not work. I have used a while ago "pip install' for getting tensor flow. I think that the pip command created the problem. 

Anyway, I got back to version 3.3.6 and the problem related to the WIFI disappeared, but I am not being able to update again to version 4.1.4. I will try to start from zero again by uninstalling everything that is related to anaconda, python, and so on...

**Comment by CAM-Gerlach** [comment] 2020-07-30 08:30
@sergionovi Sorry you had problems updating to Spyder 4. We might be able to help with those issues if we had more information; as one possible tip, the version of Spyder-Kernels in any of your environments will need to be updated to version 1.x to work with Spyder 4. However, I think you're quite right in your guess

> I have used a while ago "pip install' for getting tensor flow. I think that the pip command created the problem.

Because, as you correctly surmise, this can certainly create all kinds of problems with your install, either immediately or down the road. We just produced a [tutorial video on installing Spyder and packages with Spyder, Pip and Conda](https://www.youtube.com/watch?v=Ul79ihg41Rs) describing how to solve this and avoid it in the future, so be sure to check that out. If you continue to run into trouble, see our [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for more help.

Best of luck, and let us know if you run into this issue again on 4.1.4. Thanks for your patience!

**Comment by amandamiotto** [comment] 2021-08-25 00:10
Hey team - This has started to happen to me, but in version 5.05 (via anaconda) on Win 10. My internet speed is going from 20ish mps to 1mps . I've killed everything else except Windows Defender (can't as company SOE) and when I try to downgrade Spyder to 4.0 it now has the same issue - despite working on v4 previously. The only thing I can think of is I did an update to v5.03 recently, then today while debugging up to v5.05. Jupyter hub works fine.
