### ISSUE TITLE
Spyder writes console to previous log files

### ISSUE THREAD

**Issue by marcvandort** [spyder-ide/spyder#3140] opened 2016-04-27 15:47 UTC
Hello,

I wanted to write some of my console output to a logfile, so I adapted some code to my needs. At first glance, it seems to work great. When i use print() it gets written to both the console and my logfile, and I can also write only to the console or the logfile if I so choose. I generate a new logfile each time the script is run.

However, I noticed that if I run the script again in the same IPython console, the _console_ output is written to the previous logfile. When I run it again, it is written to both previous logs, etc. The log output is written only to the new file.  

When I close the console and open a new one, it stops writing to the old logfile. When I run the script from the Windows command line, the problem doesn't occur at all.

**What steps will reproduce the problem?**
Run this script multiple times in the same IPython console.

```
# -*- coding: utf-8 -*-

import sys
import time

class Logger(object):
    def __init__(self, p_logfile):
        self.terminal = sys.stdout
        self.fname = p_logfile

        self.conlist = []
        self.loglist = []

    def write(self, p_message):
        self.console(p_message)
        self.log(p_message)

    def console(self, p_message):
        self.terminal.write(p_message)
        self.conlist.append(p_message)

    def log(self, p_message):
        self.loglist.append(p_message)
        with open(self.fname, 'a') as logfile:
            logfile.write(p_message)

    def flush(self):
        #this flush method is needed for python 3 compatibility.
        #this handles the flush command by doing nothing.
        #you might want to specify some extra behavior here.
        pass

timestamp = round(time.time())
logfile = "test-{}.txt".format(timestamp)
logger = Logger(logfile)
sys.stdout = logger

def overwrite_console(p_str):
    logger.console("{}\r".format(p_str))

logger.log("log only!\n")
logger.console("console only!\n")
print("both log and console\n")


s = 'abcdefghijkl'

for x in range(0,5):
    overwrite_console(s[x]*(5-x))
```

I added conlist and loglist to check how often each function was called, this was exactly as expected.

**What is the expected output? What do you see instead?**

The console output:

```
console only!
both log and console

edcba
```

The (latest) log output:

```
log only!
both log and console
```

Both these are as expected. 

The previous log outputs:

```
log only!
both log and console

console only!
both log and console

aaaaa
bbbb
ccc
dd
e
```

```
log only!
both log and console

console only!
both log and console

aaaaa
bbbb
ccc
dd
e
console only!
both log and console

aaaaa
bbbb
ccc
dd
e
```
## Versions and main components
- Spyder Version: Spyder 2.3.8
- Python Version: 3.5.1 64 bits
- Operating system: Windows 8.1 Enterprise 64-bit
## Dependencies

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by jitseniesen** [comment] 2016-04-30 23:20
I'm not sure this is a bug in spyder. I think the problem is that the first time you run the script, it replaces sys.stdout with a Logger. The second time you run the script, it constructs a new Logger called logger, and logger.terminal is set to sys.stdout. However, at that time, sys.stdout is a Logger connected to the first logfile. So, when sys.stdout is replaced by the second Logger and you print to it, it writes to both logfiles.

**Comment by goanpeca** [comment] 2019-12-04 03:35
As @jitseniesen points out, this does not seem to be  Spyder issue. Closing.

**Closed by goanpeca** 2019-12-04 03:35 UTC
Labels: type:Bug
