### ISSUE TITLE
crash while ctrl+c on input

### ISSUE THREAD

**Issue by AnsenIO** [spyder-ide/spyder#5366] opened 2017-09-29 23:49 UTC
## Description

**What steps will reproduce the problem?**

1. i invoked an input, 
2. at the prompt in the consol pressed ctrl+c
3. 

**What is the expected output? What do you see instead?**
i would expect to stop running the code instead of crashing

**Please provide any additional information below**

  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.2
* Qt Versions: 5.7.1, PyQt5 5.8.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by rlaverde** [comment] 2017-09-29 23:53
This is a duplicate of issue #5158 and it was fixed in Spyder 3.2.3. Please update.

**Closed by rlaverde** 2017-09-29 23:53 UTC
