### ISSUE TITLE
lost variables in save

### ISSUE THREAD

**Issue by JaceWalton** [spyder-ide/spyder#20516] opened 2023-02-10 22:49 UTC
### What steps will reproduce the problem?

are you freaking kidding me! I had a test running for the past 24 hours  and tried to save the variables and they all deleted!
this really needs to get patched!

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 124, in comm_channel_manager
    yield
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 238, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 275, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'b6923a44848d4a44bf2fed929f574486': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 236, in <lambda>
    triggered=lambda x: self.save_data(),
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 569, in save_data
    nsb.save_data()
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 255, in save_data
    error_message = self.shellwidget.save_namespace(self.filename)
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 176, in save_namespace
    return self.call_kernel(
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\w-wow\Anaconda3\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\w-wow\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 127, in comm_channel_manager
    self._comms[comm_id]['comm']._send_channel = (
KeyError: '6f7e25a4a8f211ed9c889b077246461c'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.3.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment] 2023-02-10 23:36
Hi @JaceWalton sorry for the inconvenience! Maybe this could be related with https://github.com/spyder-ide/spyder/issues/17199 and https://github.com/spyder-ide/spyder/issues/18895 ?

Using the `Exclude unsupported data types` option from the Variable Explorer could be a workaround for this (although some variables will not be saved).

For sure Spyder needs to better handle cases where some variables can't be saved which could cause a kernel error and restart which translates to lossing then the current variables available!

**Comment by dalthviz** [comment] 2023-06-20 21:28
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/17199

**Closed by dalthviz** 2023-06-20 21:28 UTC
Labels: resolution:Duplicate, component:Variable Explorer, status:Awaiting Followup
