### ISSUE TITLE
iPython in Spyder 3.1.0 can not import `oauth2client.tools`

### ISSUE THREAD

**Issue by manihamidi** [spyder-ide/spyder#4008] opened 2017-01-19 19:18 UTC
## Description of your problem

After upgrading to Spyder 3.1.0, my scripts that relied on `oauth2client.tools` broke down (when ran from Spyder's ipython console). See below. 

**What steps will reproduce the problem?**

1.`pip install --upgrade spyder` 
2. type `from oauth2client import tools` in Spyder's **ipython console**. 
3. Watch it produce an `IndexError`

**What is the expected output? What do you see instead?**

Expected output: nothing. 
See this error instead: 

```
from oauth2client import tools
Traceback (most recent call last):

  File "<ipython-input-8-1354c76ab290>", line 1, in <module>
    from oauth2client import tools

  File "C:\Users\Mani\Anaconda\lib\site-packages\oauth2client\tools.py", line 98, in <module>
    argparser = _CreateArgumentParser()

  File "C:\Users\Mani\Anaconda\lib\site-packages\oauth2client\tools.py", line 82, in _CreateArgumentParser
    parser = argparse.ArgumentParser(add_help=False)

  File "C:\Users\Mani\Anaconda\lib\argparse.py", line 1586, in __init__
    prog = _os.path.basename(_sys.argv[0])

IndexError: list index out of range
```

**Please provide any additional information below**

NOTE: the error is specific to iPython, when oauth2client.tools is imported from console, it produces no error. 

## Versions and main components

* Spyder Version: 3.1.0
* Python Version: 2.7
* Operating system: windows 7

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.17.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  0.7.6 (OK)

**Comment by ccordoba12** [comment] 2017-01-19 19:31
Thanks for reporting. This is a duplicate of issue #3987 and we'll fix it in Spyder 3.1.1 (to be released in a couple of days).

**Closed by ccordoba12** 2017-01-19 19:31 UTC
