### ISSUE TITLE
Cannot clear console

### ISSUE THREAD

**Issue by Mark531** [spyder-ide/spyder#3110] opened 2016-04-12 08:53 UTC
## Description of your problem

**What steps will reproduce the problem?**
1. Open Spyder
2. Execute a command
3. Right click on the console and choose "clear the console"

**What is the expected output? What do you see instead?**
The console should be cleared but it isn't, all the previous commands still stay visible in the console.
A "%clear" is issued instead.

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 2.3.8
- Python Version: 2.7
- Operating system: Win8 64-bit
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by dhirschfeld** [comment] 2017-01-04 00:13
Note: I also reported this as part of #3458. Restarting the kernel now *does* clear the console but `%clear` and the context menu version are both still not working as desired, at least on Windows x64, py35.

**Comment by ccordoba12** [comment] 2017-01-04 23:39
This is a bug in qtconsole, but I'm marking it for Spyder 3.2 so we don't forget to open a PR in qtconsole to fix it.

@mariacamilaremolinagutierrez, please work on this one after we release 3.1 :-)

**Comment by mariacamilaremolinagutierrez** [comment] 2017-01-27 03:01
@ccordoba12 I can not reproduce this error in the latest version of spyder and qtconsole. The three options that clear the console: right click + clear console, ctrl + L & %clear work perfectly fine in qtconsole and inside spyder.

**Comment by ccordoba12** [comment] 2017-01-27 08:13
@mariacamilaremolinagutierrez, this bug happens only on Windows. Did you test things there?

**Comment by mariacamilaremolinagutierrez** [comment] 2017-01-27 22:22
@ccordoba12 Yes I tested it on Ubuntu and Windows and it worked  in both.

**Comment by ccordoba12** [comment] 2017-01-27 22:47
Not true, on Windows the console is not cleared up completely, only the prompt position is moved to appear at the top of the console.

But the problem is you can scroll up and see your previous history. That's not the same behavior you see on Linux, where the console's previous history is really cleared up :-)

**Comment by mariacamilaremolinagutierrez** [comment] 2017-01-27 23:27
Oh I see! I'm sorry I misunderstood then. I thought you just wanted it to move up. My bad I'll check it then and correct it in qtconsole. Thanks :)

**Comment by C0ppert0p** [comment] 2017-05-23 22:24
This is still happening in the  **iPython console** in **Spyder** 
spyder                    3.1.4                    py36_0
**Windows 7 x64**
was it ever resolved?
It doesn't happen all the time though.
It seems to depend on what python script I run.

**Comment by ccordoba12** [comment] 2017-05-23 22:32
We'll fix it for Spyder 3.2.

**Comment by ccordoba12** [comment] 2017-07-07 12:47
This was fixed in jupyter/qtconsole#225 and it will be part of qtconsole **4.3.1**.

**Closed by ccordoba12** 2017-07-07 12:47 UTC
Labels: component:IPython Console, OS:Windows, type:Bug
