### ISSUE TITLE
"Failed to create shortcut" error on Windows 10 while installing Spyder 6

### ISSUE THREAD

**Issue by nad1** [spyder-ide/spyder#22425] opened 2024-09-04 02:27 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Hi, I wanted to update my Spyder from 5 to 6 with conda instalment. But, i get this error that I didn't get it for Spyder 5.

I tried to install again and again on anaconda and windows prompt with/without running as administrator.

![image](https://github.com/user-attachments/assets/6c65811c-74e8-47a6-a9fb-d8ddd32445b6)

I re-installed Spyder 5.5.6 without any problem.

### What steps reproduce the problem?

1.  The last step of installation. "conda install -c conda-forge spyder=6.0.0"
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 6.0.0
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2024-09-04 16:15
Hey @nad1, thanks for reporting. This is a duplicate of issue @22428, so I'm going to close it in favor of that one.

Please post there the output of `conda list` to better understand why this error is happening. Thanks!

**Closed by ccordoba12** 2024-09-04 16:15 UTC
