### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by achandru** [spyder-ide/spyder#5269] opened 2017-09-18 11:17 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Chandru\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    Traceback (most recent call last):
  File "C:\Users\Chandru\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Users\Chandru\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 220, in _handle_execute_reply
  File "C:\Users\Chandru\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 339, in handle_exec_method
  File "C:\Users\Chandru\Anaconda3\lib\ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Chandru\Anaconda3\lib\ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: {}
handler(msg)
  File "C:\Users\Chandru\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 220, in _handle_execute_reply
  File "C:\Users\Chandru\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 332, in handle_exec_method
  File "C:\Users\Chandru\Anaconda3\lib\ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "C:\

**Comment by ccordoba12** [comment] 2017-09-18 13:02
Closing as a duplicate of issue #5265.

**Closed by ccordoba12** 2017-09-18 13:02 UTC
