### ISSUE TITLE
Auto indentation matching opening parenthesis when terminating statement with ";"

### ISSUE THREAD

**Issue by tdpu** [spyder-ide/spyder#4117] opened 2017-02-07 19:31 UTC
I thought I was experiencing the issue [#3700](https://github.com/spyder-ide/spyder/issues/3700) still in 3.1.2.  But I've noticed that this only happens when terminating a statement with ';'.

Is this intentional? 

i.e.

`misc.imread("myImage.png")`
`<<< indents here`

but 

`misc.imread("myImage.png");`
`............<<< indents here`

- Spyder 3.1.2
- Python 3.5.2 64 bit
- Qt 4.8.7
- PyQt4 (API v2) 4.11.4

**Comment by ccordoba12** [comment] 2017-02-08 16:18
Thanks for reporting. This is a duplicate of issue #4096.

**Closed by ccordoba12** 2017-02-08 16:18 UTC
