### ISSUE TITLE
Code folding marker missing

### ISSUE THREAD

**Issue by StewTheBrew** [spyder-ide/spyder#16383] opened 2021-09-09 09:29 UTC
### What steps will reproduce the problem?

In the previous versions when I hovered the mouse to the left of my code it always displayed the code folding marker. In version 5 this marker is missing

**Comment by ccordoba12** [comment] 2021-09-09 19:29
Hey @StewTheBrew, thanks for reporting. Please let us know the following information:

* Spyder version
* Operating system (Windows, Linux or macOS).
* Installation method (Anaconda, Pip or our own macOS/Windows installer).

**Comment by StewTheBrew** [comment] 2021-09-10 07:57
Hi @ccordoba12, thanks for responding. Spyder version is 5.0. Operating system is Windows 10. Installation method Anaconda. I just signed up here for this, because I tried to post a question on the spyder google group but, I don't know why, it seems not to be working, maybe for some sort of issue with my google account (I tried to post it 2 times). Maybe I just have to update spyder wich I see has been now upgraded to 5.1 version

**Comment by ccordoba12** [comment] 2021-09-10 20:16
Ok, I think this is an installation issue then. Please create a new environment with Spyder by closing it and running the following commands in the Anaconda Prompt:

    conda create -n spyder-env spyder
    conda activate spyder-env
    spyder

Let us know if it works for you.

**Comment by ccordoba12** [comment] 2021-09-11 19:59
> Only thing, now I have to activate the spyder env every time

You should be able to start the Spyder version you installed in your environment from the Windows Start menu or using the Anaconda Navigator.

> Maybe I'll just need to update anaconda and spyder running same old commands in the prompt

Yeah, you can do that too to see if it fixes your problem.

**Comment by ccordoba12** [comment] 2021-09-11 20:00
I'm going to close this issue because it's not a bug with Spyder but an installation issue.

**Closed by ccordoba12** 2021-09-11 20:00 UTC
Labels: status:Awaiting Followup
