### ISSUE TITLE
Spyder IPython console freezes on any error

### ISSUE THREAD

**Issue by huanchunye2015** [spyder-ide/spyder#5133] opened 2017-09-05 00:51 UTC
## Description of your problem
Spyder IPython console freezes on any error

**What steps will reproduce the problem?**
For example just type a non-existent variable, e.g., x[1], and the IPython console will freeze:

Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32)
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

x[1]

Traceback (most recent call last):

  File "<ipython-input-1-98e225784849>", line 1, in <module>
    x[1]

NameError: name 'x' is not defined

But other parts of Spyder still work.

**What is the expected output? What do you see instead?**
I tried the same thing in IPython console and it continues just fine after the error.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6.2
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (specifically Linux Mint 18.1)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-09-05 02:12
Thanks for reporting. This is a duplicate of #4504 and it'll be fixed in 3.2.2

**Closed by ccordoba12** 2017-09-05 02:12 UTC
