### ISSUE TITLE
[Feature Request] Indent Guides

### ISSUE THREAD

**Issue by tastyminerals** [spyder-ide/spyder#4071] opened 2017-01-29 10:45 UTC
Spyder IDE requires [indent guides](https://www.google.de/search?q=Indent+Guides&biw=1598&bih=784&source=lnms&tbm=isch&sa=X&ved=0ahUKEwizxfnUk-fRAhUKWhQKHVYKDugQ_AUIBigB). 

I was using **spyder** for many of my python projects. When writing bigger functions with loops, it is pretty difficult to track the indentation of `return` and other statements with current visual scheme. *Last drop* was my recent bug which I **unexpectedly** found. It was the incorrect indentation of the `return` statement inside a bigger loop (which might turn out to be undetectable under certain conditions). Unfortunately, I haven't noticed it until I reduced my font size. This is certainly no excuse for being inattentive but it happened to me in spyder frequently enough that I stopped using it. It would be nice to have this feature.

I tried using white spaces which *sort-of* help, but, again, the dots in spyder do look too big for me :)

**Comment by ccordoba12** [comment] 2017-01-29 15:36
@rlaverde, could we implement something like this for Spyder 4?

**Comment by rlaverde** [comment] 2017-01-31 16:37
@ccordoba12 Hmm, yes, maybe using a Panel similar to EdgeLine, but first we need an option in PanelsManager to define panels with arbitrary position

**Comment by goanpeca** [comment] 2017-01-31 16:39
@rlaverde but this should be on and off based on the indentation and if there is code or not, so it is not as simple as edgline. The idea is not to add a whole line there.

**Comment by ccordoba12** [comment] 2017-02-15 13:10
I didn't notice but this is a duplicate of an older issue (issue #2987).

**Closed by ccordoba12** 2017-02-15 13:10 UTC
Labels: component:Editor, resolution:Duplicate, type:Feature
