### ISSUE TITLE
error dependencies after update

### ISSUE THREAD

**Issue by ExHunter000** [spyder-ide/spyder#15103] opened 2021-04-04 08:43 UTC
### What steps will reproduce the problem?

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.21.0 (OK)
jedi =0.17.2                  :  0.18.0 (NOK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.8.1 (NOK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.0 (OK)
pylint >=1.0                  :  2.5.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  None (NOK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.18.5 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)

after I update I got error dependencies, I tried to update spyder, install the packages but nothing happend

**Comment by real-yfprojects** [comment] 2021-04-04 10:03
It would be great if you posted your current spyder version and exactly what the problem is. Not only which packages you have installed.

If your using Spyder 5 and the `spyder-kernels` dependency is not ok, this issue was already reported and will be fixed soon.

**Comment by nerohmot** [comment] 2021-04-04 14:43
I don't know about @ExHunter000, but I did install Spyder 5.0.0 via the new (full) installer, and got the same issue with spyder_kernels eventhough the installed version complies to the requirements ...
![image](https://user-images.githubusercontent.com/3516972/113512411-cdfb5180-9564-11eb-9dcd-0137d9529af6.png)

**Comment by nerohmot** [comment] 2021-04-04 16:04
I think this is already fixed with #15091

**Comment by real-yfprojects** [comment] 2021-04-04 17:53
As i already said: This seems to be a duplicat of Issue #15091. It will be fixed with PR #15100.

**Comment by ccordoba12** [comment] 2021-04-05 14:47
Yes, it is a duplicate of issue #15091, so I'm closing it in favor of that one.

**Closed by ccordoba12** 2021-04-05 14:47 UTC
