### ISSUE TITLE
Openining a parenthesis of any function applied to a pandas dot accessed column in IPython console opens and closes several terminals

### ISSUE THREAD

**Issue by momoa16** [spyder-ide/spyder#4781] opened 2017-07-20 18:28 UTC
Hi,

Here's a small test to replicate my issue:

In [1]: import pandas as pd

In [2]: test = pd.DataFrame({'a': [1,2,3], 'b': [5,10,15]})

In [3]: test
Out[3]: 
   a   b
0  1   5
1  2  10
2  3  15

In [4]: test['a'].copy().min()
Out[4]: 1

In [5]: test.a.copy(

Typing a parenthesis after the 'copy' opens and closes instantly several command windows. Any additional opening round bracket will do the same too (i.e. ' ...copy(((( ' ).

I have this behaviour on:
1- Spyder 3.1.4 - python 3.6.1 - IPython.version_info (5, 3, 0, '') - windows 7 Pro 64bits
2- Spyder 3.1.4 - python 3.5.3 - IPython.version_info (5, 3, 0, '') - windows 7 Pro 64bits

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-07-30 15:08
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment] 2017-08-01 23:29
@ccordoba12 I tried this one but I'm not being able to reproduce it. When opening the parenthesis a calltip for the function is shown:

![parent](https://user-images.githubusercontent.com/16781833/28851270-1a105cbe-76e7-11e7-824e-1705bfa993ae.png)

**Comment by ccordoba12** [comment] 2017-08-22 12:47
Closing because we can't reproduce this, sorry.

**Closed by ccordoba12** 2017-08-22 12:47 UTC
