### ISSUE TITLE
Spyder won't launch when installed with Anaconda 2.3.0

### ISSUE THREAD

**Issue by j-hoss** [spyder-ide/spyder#2698] opened 2015-09-17 23:12 UTC
- Install on a win 7 64 bit laptop.
- Python works and ipython works.  
- When i try to launch Spyder, when it gets to "loading file history" it close and says that python.exe (or sometime pythonw.exe) has stopped working.

I tried uninstall and re-install with no luck.

I was able to use the 32 bit version ... 

Help?

**Comment by ccordoba12** [comment] 2015-09-17 23:43
Please a terminal (i.e. `cmd.exe`) and run

    spyder --reset

then try to start Spyder again. That should fix your problem :-)

**Comment by j-hoss** [comment] 2015-09-17 23:51
I launched spyder and observed the issue.
I ran the reset script.
I re-launched Spyder and saw the exact same issue.

**Comment by ccordoba12** [comment] 2015-09-17 23:56
Does your user name has some non-ascii characters on it?

**Comment by ccordoba12** [comment] 2015-09-17 23:56
Like á, ñ, etc?

**Comment by j-hoss** [comment] 2015-09-18 01:38
I do not have any non-ascii characters in my user name.

**Comment by j-hoss** [comment] 2015-09-18 14:59
I'll stick with the 32 bit install until the issue is fixed.  It is the same issue described by multiple people in "Spyder in Windows 10 is not working correctly #2633"

**Comment by dracid** [comment] 2015-09-20 13:59
Sounds like the problem I have here. Windows 8 x64, Anaconda 2.3 x64.
Resetting Spyder does not help at all.

Will try x32 version

**Comment by sho-87** [comment] 2015-10-11 11:21
Is any progress being made on this? I'm running the 32bit of spyder/anaconda/python and it cant start on windows 10, so its not just a 64bit issue

**Comment by ccordoba12** [comment] 2015-11-16 00:36
Closing then as a duplicate of issue #2633.

**Closed by ccordoba12** 2015-11-16 00:36 UTC
Labels: duplicate

**Comment by rmalshe** [comment] 2016-06-04 19:38
Here is what happened when I tried 
C:\Users\rmalshe>spyder --reset

Traceback (most recent call last):
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script
.py", line 1, in <module>
    from spyderlib import start_app
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\start_app.py", line 13, in <module>
    from spyderlib.config import CONF
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\config.py", line 736, in <module>
    subfolder=SUBFOLDER, backup=True, raw_mode=True)
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\userconfig.py", line 215, in __init__
    self.load_from_ini()
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\site-packages\spy
derlib\userconfig.py", line 260, in load_from_ini
    self.readfp(configfile)
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\ConfigParser.py",
 line 324, in readfp
    self._read(fp, filename)
  File "C:\Users\rmalshe\AppData\Local\Continuum\Anaconda3\lib\ConfigParser.py",
 line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: C:\Users\rmalshe\.spyde
r2\spyder.ini
        [line 333]: u'_/switch to outl'

---
Does anyone know the solution to this problem?

**Comment by Nodd** [comment] 2016-06-07 11:52
@rmalshe Try to remove `C:\Users\rmalshe\.spyder2\spyder.ini` by hand. It's strange that it tries to load it before deleting it. What is you spyder version ?

**Comment by rmalshe** [comment] 2016-06-08 04:04
Thank you! that solved the problem. Spyder is very nice to use, and I am somewhat used to it, so it is nice to have it back in action.

**Comment by mukulaggarwal** [comment] 2016-08-02 19:26
Im working on mac. Same happen with me, due to some reason.
I run these commands:
ps aux | grep spyder
kill -9 4-digit-processId
