### ISSUE TITLE
Sypder 4.0.1/0 super laggy

### ISSUE THREAD

**Issue by HendrikKS** [spyder-ide/spyder#11710] opened 2020-03-03 12:59 UTC
## Problem Description

Since updating to Spyder to version 4.0.1 it is super laggy for me on machines behind corporate firewalls. I tested it on my local laptop (Win 7) and on an AWS machine (Win 10). In both cases typing feels really sluggish. When pressing a button i have to wait like 20ms for a letter to apear. Autocompletion via kite works only very slowly with wating times up to 30 seconds. 

At the beginning of the release of Spyder 4.0.0 the problem wasn't as big as now. It became more severe over time. So I thought it might be connected to some firewall issues. I tried to turn off kite to solve the problem, but did not notice any positive effects.

My co-worker is facing the same problem and other ides like pycharm work fine for us.  

Interestingly Spyder runs much smoother on my laptop, when I'm working remote and just dial in into the corporate network via remote connection. 

I don't have any problems on my personal (non-corporate) pc and mac.

## Versions (AWS + local Laptop)
* Spyder version: 4.0.1
* Python version:  3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10/Windows 7

### Dependencies (AWS Machine)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  0.8.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.4.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.4.1 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.1 (OK)
pygments >=2.0               :  2.3.1 (OK)
pylint >=0.25                :  2.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.0.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.7.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.6 (OK)
matplotlib >=2.0.0           :  3.0.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.2.1 (OK)
sympy >=0.7.3                :  1.3 (OK)

### Dependencies (Local Laptop)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  None (NOK)

**Comment by ccordoba12** [comment] 2020-03-03 15:38
Duplicate of #11412

**Comment by ccordoba12** [comment] 2020-03-03 15:38
The situation will be better in our next version (4.1.0) to be released this weekend. More improvements are planned for 4.2, to be released in a couple of months.

**Closed by ccordoba12** 2020-03-03 15:38 UTC
