### ISSUE TITLE
spyder has error when ipython throws "NameError

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#5172] opened 2017-09-08 16:01 UTC
## Description

**What steps will reproduce the problem?**

1. on a new ipython write "a=  this_name_not_found(3.14)"
2. get error from python
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
My friend has windows and py3.6 and it works ok. I have linux and py3.5 and I get the error
  File "/home/tal/anaconda3/envs/pic/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/tal/anaconda3/envs/pic/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.1.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.3.5 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.1.0 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.23.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by rlaverde** [comment] 2017-09-08 18:33
Closing as duplicate of #5158

**Closed by rlaverde** 2017-09-08 18:33 UTC
