### ISSUE TITLE
spyder.plugins.ipythonconsole.utils.kernelspec.SpyderKernelSpec could not be imported

### ISSUE THREAD

**Issue by dbi22** [spyder-ide/spyder#13931] opened 2020-10-06 08:09 UTC
### What steps will reproduce the problem?

conda version : 4.8.5
conda-build version : 3.18.11
python version : 3.8.3.final.0

conda install -c conda-forge spyder spyder-notebook

### Traceback
```python-traceback
  File "/home/dbi/anaconda3/lib/python3.8/site-packages/spyder_notebook/notebookplugin.py", line 301, in open_console
    kernel_id = client.get_kernel_id()
  File "/home/dbi/anaconda3/lib/python3.8/site-packages/spyder_notebook/widgets/client.py", line 281, in get_kernel_id
    sessions_url = self.get_session_url()
  File "/home/dbi/anaconda3/lib/python3.8/site-packages/spyder_notebook/widgets/client.py", line 272, in get_session_url
    return self.add_token(url_path_join(self.server_url, 'api/sessions'))
  File "/home/dbi/anaconda3/lib/python3.8/site-packages/notebook/utils.py", line 50, in url_path_join
    initial = pieces[0].startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-48-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.3.0 (OK)
```

**Comment by steff456** [comment] 2020-10-06 16:07
Hi @dbi22,

This is a duplicate of https://github.com/spyder-ide/spyder-notebook/issues/314, we are working on fixing it right now. 

Thanks for reporting!

**Closed by steff456** 2020-10-06 16:07 UTC
