### ISSUE TITLE
unsupported operand type(s_ for -: 'float' and  'NoneType'

### ISSUE THREAD

**Issue by deFang** [spyder-ide/spyder#7114] opened 2018-05-12 08:00 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported ope

**Comment by CAM-Gerlach** [comment] 2018-05-12 15:59
Thanks for reporting. This is a duplicate of #6767 ; already fixed in the ``3.x`` branch here and should be released as part of Spyder 3.3, due out the beginning of June currently.

**Closed by CAM-Gerlach** 2018-05-12 15:59 UTC
