### ISSUE TITLE
enter in console not functioning properly

### ISSUE THREAD

**Issue by peendebak** [spyder-ide/spyder#3916] opened 2017-01-05 13:03 UTC
This is a weird bug related to the python or ipython console (both have the same issue) and packages which take a long time to load. A minimal example is below.

**What steps will reproduce the problem?**

1.  Create a package `testpackage` with the following content for `__init__.py`:
```
import time
time.sleep(.5)
```
In my actual code the `time.sleep` is not present, but many packages are loaded.

2. Create a script `example.py` with the following content:
```
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  5 13:12:31 2017

@author: eendebakpt
"""

#%%

import testpackage

#%%
```

3. In a fresh console run the block in the script `example.py` using `ctrl-enter`
4. Go to the console, type `1` and press enter. No output is generated
5. Press enter once more, the output is shown.

**What is the expected output? What do you see instead?**

The entire output is this:
```
>>> import testpackage

>>> 1
>>> 
1
>>> 
```
I would expect to see a response
```
>>> import testpackage
>>> 1
1
>>> 
```

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5.2 (anaconda windows 64-bit)
* Operating system: Windows

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-01-05 14:44
This is a problem with the Python console, and it's almost a duplicate of issue #1831, so I'm closing it,

Unfortunately, there's no solution to this problem, sorry.

**Closed by ccordoba12** 2017-01-05 14:44 UTC
