### ISSUE TITLE
Constantly Freezing When Using Large Directory

### ISSUE THREAD

**Issue by bdwilson24** [spyder-ide/spyder#21321] opened 2023-09-09 17:12 UTC
### What steps will reproduce the problem?

I have tried reinstalling spyder. Issue occurs whenever a specific directory is used.

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  7.31.1 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.4.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.11.2 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  66.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.33 (OK)
matplotlib >=3.0.0                               :  3.5.3 (OK)
numpy >=1.7                                      :  1.25.1 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.9.3 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Ben\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2023.03                  py39_0  
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alabaster                 0.7.12             pyhd3eb1b0_0  
alpha-vantage             2.3.1                    pypi_0    pypi
anaconda                  custom                   py39_1  
anaconda-client           1.11.2           py39haa95532_0  
anaconda-navigator        2.3.2            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.3            py39haa95532_1  
astroid                   2.14.2           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
astunparse                1.6.3                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
atomicwrites              1.4.0                      py_0  
attrs                     22.1.0           py39haa95532_0  
automat                   20.2.0                     py_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
babel                     2.11.0           py39haa95532_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0            py39h2bbff1b_1  
beautifulsoup4            4.12.2           py39haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
bitarray                  2.5.1            py39h2bbff1b_0  
bkcharts                  0.2              py39haa95532_1  
black                     23.3.0           py39haa95532_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.3               h6c2663c_0  
bokeh                     2.4.3            py39haa95532_0  
boltons                   23.0.0           py39haa95532_0  
boto3                     1.24.28          py39haa95532_0  
botocore                  1.27.59          py39haa95532_0  
bottleneck                1.3.5            py39h080aedc_0  
brotli                    1.0.9                h2bbff1b_7  
brotli-bin                1.0.9                h2bbff1b_7  
brotlipy                  0.7.0           py39h2bbff1b_1003  
bzip2                     1.0.8                he774522_0  
ca-certificates           2023.01.10           haa95532_0  
cachetools                5.2.0                    pypi_0    pypi
certifi                   2023.5.7         py39haa95532_0  
cffi                      1.15.1           py39h2bbff1b_3  
cfitsio                   3.470                h2bbff1b_7  
chardet                   4.0.0           py39haa95532_1003  
charls                    2.2.0                h6c2663c_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py39haa95532_0  
cloudpickle               2.2.1            py39haa95532_0  
clyent                    1.2.2            py39haa95532_1  
colorama                  0.4.6            py39haa95532_0  
colorcet                  3.0.1            py39haa95532_0  
comm                      0.1.2            py39haa95532_0  
comtypes                  1.1.10          py39haa95532_1002  
conda                     23.5.0           py39haa95532_0  
conda-build               3.24.0           py39haa95532_0  
conda-content-trust       0.1.3            py39haa95532_0  
conda-env                 2.6.0                haa95532_1  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    2.0.2            py39haa95532_0  
conda-package-streaming   0.7.0            py39haa95532_0  
conda-repo-cli            1.0.41           py39haa95532_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
configargparse            1.5.3                    pypi_0    pypi
console_shortcut          0.1.1                         4  
constantly                15.1.0             pyh2b92418_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              39.0.1           py39h21b164f_0  
cssselect                 1.1.0              pyhd3eb1b0_0  
curl                      7.88.1               h2bbff1b_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.33          py39hd77b12b_0  
cytoolz                   0.12.0           py39h2bbff1b_0  
daal4py                   2021.6.0         py39h757b272_1  
dal                       2021.6.0           h59b6b97_874  
dash                      2.9.3                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
dask                      2022.2.1           pyhd3eb1b0_0  
dask-core                 2022.2.1           pyhd3eb1b0_0  
dataclasses               0.8                pyh6d0b6a4_7  
dataframe-image           0.1.3                    pypi_0    pypi
datashader                0.14.2           py39haa95532_0  
datashape                 0.5.4            py39haa95532_1  
debugpy                   1.5.1            py39hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.6            py39haa95532_0  
distributed               2022.2.1           pyhd3eb1b0_0  
distro                    1.8.0                    pypi_0    pypi
docstring-to-markdown     0.11             py39haa95532_0  
docutils                  0.18.1           py39haa95532_3  
entrypoints               0.4              py39haa95532_0  
et_xmlfile                1.1.0            py39haa95532_0  
exceptiongroup            1.1.0                    pypi_0    pypi
fftw                      3.3.9                h2bbff1b_1  
filelock                  3.9.0            py39haa95532_0  
flake8                    6.0.0            py39haa95532_0  
flask                     1.1.2              pyhd3eb1b0_0  
flatbuffers               23.3.3                   pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               ha860e81_0  
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0         py39haa95532_0  
future                    0.18.3           py39haa95532_0  
gast                      0.4.0                    pypi_0    pypi
gensim                    4.1.2            py39hd77b12b_0  
geographiclib             2.0                      pypi_0    pypi
geopy                     2.3.0                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3  
glib                      2.69.1               h5dc1a3c_2  
glob2                     0.7                pyhd3eb1b0_0  
gmplot                    1.4.1                    pypi_0    pypi
google-api-core           2.11.0                   pypi_0    pypi
google-api-python-client  2.70.0                   pypi_0    pypi
google-auth               2.15.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.8.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.57.0                   pypi_0    pypi
gpxpy                     1.5.0                    pypi_0    pypi
greenlet                  2.0.1            py39hd77b12b_0  
grpcio                    1.54.0                   pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
h11                       0.14.0                   pypi_0    pypi
h3                        3.7.6                    pypi_0    pypi
h5py                      3.7.0            py39h3de5c98_0  
hdf5                      1.10.6               h1756f20_1  
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.15.2           py39haa95532_0  
httplib2                  0.21.0                   pypi_0    pypi
huggingface_hub           0.10.1           py39haa95532_0  
hvplot                    0.8.1            py39haa95532_0  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icc_rt                    2022.1.0             h6049295_2  
icu                       58.2                 ha925a31_3  
idna                      3.4              py39haa95532_0  
imagecodecs               2021.8.26        py39hc0a7faf_1  
imageio                   2.19.3           py39haa95532_0  
imagesize                 1.4.1            py39haa95532_0  
imbalanced-learn          0.10.1           py39haa95532_0  
importlib-metadata        6.0.0            py39haa95532_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
incremental               21.3.0             pyhd3eb1b0_0  
inflection                0.5.1            py39haa95532_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    0.6.6            py39haa95532_0  
intel-openmp              2021.4.0          haa95532_3556  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.19.2           py39hd4e2768_0  
ipython                   7.31.1           py39haa95532_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                8.0.6                    pypi_0    pypi
isort                     5.9.3              pyhd3eb1b0_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.0.4              pyhd3eb1b0_1  
itsdangerous              2.0.1              pyhd3eb1b0_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jax                       0.4.8                    pypi_0    pypi
jdcal                     1.4.1              pyhd3eb1b0_0  
jedi                      0.18.1           py39haa95532_1  
jellyfish                 0.9.0            py39h2bbff1b_0  
jinja2                    3.1.2            py39haa95532_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jmespath                  0.10.0             pyhd3eb1b0_0  
joblib                    1.1.1            py39haa95532_0  
jpeg                      9e                   h2bbff1b_1  
jq                        1.6                  haa95532_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3           py39haa95532_0  
jupyter                   1.0.0            py39haa95532_8  
jupyter_client            7.4.9            py39haa95532_0  
jupyter_console           6.6.3            py39haa95532_0  
jupyter_core              5.3.0            py39haa95532_0  
jupyter_server            1.18.1           py39haa95532_0  
jupyterlab                3.4.4            py39haa95532_0  
jupyterlab-widgets        3.0.7                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.3             pyhd3eb1b0_1  
jupyterlab_widgets        3.0.5            py39haa95532_0  
keras                     2.12.0                   pypi_0    pypi
keyring                   23.13.1          py39haa95532_0  
kivy                      2.1.0                    pypi_0    pypi
kivy-deps-angle           0.3.3                    pypi_0    pypi
kivy-deps-glew            0.3.1                    pypi_0    pypi
kivy-deps-sdl2            0.4.5                    pypi_0    pypi
kivy-garden               0.1.5                    pypi_0    pypi
kiwisolver                1.4.4            py39hd77b12b_0  
krb5                      1.19.4               h5b6d351_0  
lazy-object-proxy         1.6.0            py39h2bbff1b_0  
lcms2                     2.12                 h83e58a3_0  
lerc                      3.0                  hd77b12b_0  
libaec                    1.0.4                h33f27b4_1  
libarchive                3.6.2                h2033e3e_1  
libbrotlicommon           1.0.9                h2bbff1b_7  
libbrotlidec              1.0.9                h2bbff1b_7  
libbrotlienc              1.0.9                h2bbff1b_7  
libclang                  16.0.0                   pypi_0    pypi
libclang13                14.0.6          default_h8e68704_1  
libcurl                   7.88.1               h86230a5_0  
libdeflate                1.8                  h2bbff1b_5  
libffi                    3.4.2                hd77b12b_6  
libiconv                  1.16                 h2bbff1b_2  
liblief                   0.12.3               hd77b12b_0  
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.39               h8cc25b3_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libssh2                   1.10.0               hcd4344a_0  
libtiff                   4.5.0                h6c2663c_1  
libuv                     1.44.2               h2bbff1b_0  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.4                hbc33d0d_1  
libwebp-base              1.2.4                h2bbff1b_1  
libxml2                   2.10.3               h0ad7f3c_0  
libxslt                   1.1.37               h2bbff1b_0  
libzopfli                 1.0.3                ha925a31_0  
lightgbm                  3.3.5                    pypi_0    pypi
llvmlite                  0.39.1           py39h23ce68f_0  
locket                    1.0.0            py39haa95532_0  
lxml                      4.9.2            py39h2bbff1b_0  
lz4-c                     1.9.4                h2bbff1b_0  
lzo                       2.10                 he774522_2  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.4.1            py39haa95532_0  
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.5.3            py39haa95532_0  
matplotlib-base           3.5.3            py39hd77b12b_0  
matplotlib-inline         0.1.6            py39haa95532_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdurl                     0.1.2                    pypi_0    pypi
menuinst                  1.4.19           py39h59b6b97_0  
meshio                    5.3.4                    pypi_0    pypi
mistune                   0.8.4           py39h2bbff1b_1000  
mkl                       2021.4.0           haa95532_640  
mkl-service               2.4.0            py39h2bbff1b_0  
mkl_fft                   1.3.1            py39h277e83a_0  
mkl_random                1.2.2            py39hf11a4ad_0  
ml-dtypes                 0.1.0                    pypi_0    pypi
mock                      4.0.3              pyhd3eb1b0_0  
more-itertools            8.12.0             pyhd3eb1b0_0  
mpmath                    1.2.1            py39haa95532_0  
msgpack-python            1.0.3            py39h59b6b97_0  
msys2-conda-epoch         20160418                      1  
multidict                 6.0.2                    pypi_0    pypi
multipledispatch          0.6.0            py39haa95532_0  
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3            py39haa95532_1  
navigator-updater         0.3.0            py39haa95532_0  
nbclassic                 0.4.8            py39haa95532_0  
nbclient                  0.5.13           py39haa95532_0  
nbconvert                 6.4.4            py39haa95532_0  
nbformat                  5.7.0            py39haa95532_0  
nest-asyncio              1.5.6            py39haa95532_0  
networkx                  2.8.4            py39haa95532_1  
ninja                     1.10.2               haa95532_5  
ninja-base                1.10.2               h6d14046_5  
nltk                      3.7                pyhd3eb1b0_0  
nose                      1.3.7           pyhd3eb1b0_1008  
notebook                  6.5.2            py39haa95532_0  
notebook-shim             0.2.2            py39haa95532_0  
numba                     0.56.4           py39hf11a4ad_0  
numexpr                   2.8.4            py39h5b0cc5e_0  
numpy                     1.24.4                   pypi_0    pypi
numpy-base                1.23.5           py39h4da318b_0  
numpydoc                  1.5.0            py39haa95532_0  
oauthlib                  3.2.2                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0  
open3d                    0.17.0                   pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0  
openpyxl                  3.0.10           py39h2bbff1b_0  
openssl                   1.1.1t               h2bbff1b_0  
opt-einsum                3.3.0                    pypi_0    pypi
outcome                   1.2.0                    pypi_0    pypi
packaging                 23.0             py39haa95532_0  
pandas                    1.5.3                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     0.14.1           py39haa95532_0  
param                     1.12.3           py39haa95532_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parsel                    1.6.0            py39haa95532_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
pathlib                   1.0.1              pyhd3eb1b0_1  
pathspec                  0.10.3           py39haa95532_0  
patsy                     0.5.2            py39haa95532_1  
pcre                      8.45                 hd77b12b_0  
pep8                      1.7.1            py39haa95532_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0            py39hd77b12b_0  
pip                       23.0.1           py39haa95532_0  
pkginfo                   1.9.6            py39haa95532_0  
platformdirs              2.5.2            py39haa95532_0  
plotly                    5.9.0            py39haa95532_0  
pluggy                    1.0.0            py39haa95532_1  
ply                       3.11             py39haa95532_0  
pooch                     1.7.0                    pypi_0    pypi
powershell_shortcut       0.0.1                         3  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.14.1           py39haa95532_0  
prompt-toolkit            3.0.36           py39haa95532_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
protego                   0.1.16                     py_0  
protobuf                  4.21.12                  pypi_0    pypi
psutil                    5.9.0            py39h2bbff1b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.11.0             pyhd3eb1b0_0  
py-lief                   0.12.3           py39hd77b12b_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.10.0           py39haa95532_0  
pycosat                   0.6.4            py39h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0            py39haa95532_0  
pycurl                    7.45.2           py39hcd4344a_0  
pydispatcher              2.0.5            py39haa95532_2  
pydocstyle                6.3.0            py39haa95532_0  
pyerfa                    2.0.0            py39h2bbff1b_0  
pyflakes                  3.0.1            py39haa95532_0  
pyglet                    1.5.21                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyhamcrest                2.0.2              pyhd3eb1b0_2  
pyjwt                     2.4.0            py39haa95532_0  
pylint                    2.16.2           py39haa95532_0  
pylint-venv               2.3.0            py39haa95532_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0            py39h8cc25b3_0  
pyodbc                    4.0.34           py39hd77b12b_0  
pyopenssl                 23.0.0           py39haa95532_0  
pyparsing                 3.0.9            py39haa95532_0  
pypiwin32                 223                      pypi_0    pypi
pyqt                      5.15.7           py39hd77b12b_0  
pyqt5-sip                 12.11.0          py39hd77b12b_0  
pyqtwebengine             5.15.7           py39hd77b12b_0  
pyrsistent                0.18.0           py39h196d8e1_0  
pysocks                   1.7.1            py39haa95532_0  
pytables                  3.6.1            py39h56d22b6_1  
pytest                    7.1.2            py39haa95532_0  
python                    3.9.13               h6244533_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py39haa95532_0  
python-graphviz           0.20.1                   pypi_0    pypi
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lmdb               1.4.1            py39hd77b12b_0  
python-lsp-black          1.2.1            py39haa95532_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.7.2            py39haa95532_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.1            py39hd77b12b_0  
pytoolconfig              1.2.5            py39haa95532_1  
pytorch                   1.12.1          cpu_py39h5e1f01c_1  
pytz                      2023.3                   pypi_0    pypi
pyvista                   0.39.1                   pypi_0    pypi
pyviz_comms               2.0.2              pyhd3eb1b0_0  
pywavelets                1.3.0            py39h2bbff1b_0  
pywin32                   305              py39h2bbff1b_0  
pywin32-ctypes            0.2.0           py39haa95532_1000  
pywinpty                  2.0.10           py39h5da7b33_0  
pyyaml                    6.0              py39h2bbff1b_1  
pyzmq                     25.0.2           py39hd77b12b_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.2.2            py39haa95532_0  
qt                        5.15.7               haa95532_0  
qt-main                   5.15.2               he8e5bd7_8  
qt-webengine              5.15.9               hb9a9bb5_5  
qtawesome                 1.2.2            py39haa95532_0  
qtconsole                 5.4.2            py39haa95532_0  
qtpy                      2.2.0            py39haa95532_0  
qtwebkit                  5.212                h2bbfb41_5  
queuelib                  1.5.0            py39haa95532_0  
regex                     2022.7.9         py39h2bbff1b_0  
requests                  2.29.0           py39haa95532_0  
requests-file             1.5.1              pyhd3eb1b0_0  
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-toolbelt         0.9.1              pyhd3eb1b0_0  
rich                      13.3.5                   pypi_0    pypi
rope                      1.7.0            py39haa95532_0  
rsa                       4.9                      pypi_0    pypi
rtree                     1.0.1            py39h2eaa2aa_0  
ruamel.yaml               0.17.21          py39h2bbff1b_0  
ruamel.yaml.clib          0.2.6            py39h2bbff1b_1  
ruamel_yaml               0.17.21          py39h2bbff1b_0  
s3transfer                0.6.0            py39haa95532_0  
scikit-image              0.19.2           py39hf11a4ad_0  
scikit-learn              1.3.0                    pypi_0    pypi
scikit-learn-intelex      2021.6.0         py39haa95532_0  
scipy                     1.9.3            py39he11b74f_0  
scooby                    0.7.2                    pypi_0    pypi
scrapy                    2.8.0            py39haa95532_0  
seaborn                   0.12.0           py39haa95532_0  
selenium                  4.8.2                    pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                66.0.0           py39haa95532_0  
sip                       6.6.2            py39hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.2.1            py39haa95532_0  
snappy                    1.1.9                h6c2663c_0  
sniffio                   1.2.0            py39haa95532_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcollections         2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.4              py39haa95532_0  
sphinx                    5.0.2            py39haa95532_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.4.3            py39haa95532_1  
spyder-kernels            2.4.3            py39haa95532_0  
sqlalchemy                1.4.39           py39h2bbff1b_0  
sqlite                    3.41.2               h2bbff1b_0  
squarify                  0.4.3                    pypi_0    pypi
statsmodels               0.13.2           py39h2bbff1b_0  
sympy                     1.11.1           py39haa95532_0  
tabula                    1.0.5                    pypi_0    pypi
tabula-py                 2.6.0                    pypi_0    pypi
tabulate                  0.8.10           py39haa95532_0  
tbb                       2021.8.0             h59b6b97_0  
tbb4py                    2021.8.0         py39h59b6b97_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.2.2            py39haa95532_0  
tensorboard               2.12.2                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.12.0                   pypi_0    pypi
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-intel          2.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.1           py39haa95532_0  
testpath                  0.6.0            py39haa95532_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textblob                  0.17.1                   pypi_0    pypi
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2021.7.2           pyhd3eb1b0_2  
timezonefinder            6.1.9                    pypi_0    pypi
tinycss                   0.4             pyhd3eb1b0_1002  
tinycss2                  1.2.1            py39haa95532_0  
tk                        8.6.12               h2bbff1b_0  
tldextract                3.2.0              pyhd3eb1b0_0  
tokenizers                0.11.4           py39he5181cf_1  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py39haa95532_0  
tomlkit                   0.11.1           py39haa95532_0  
toolz                     0.12.0           py39haa95532_0  
tornado                   6.2              py39h2bbff1b_0  
tqdm                      4.65.0           py39hd4e2768_0  
traitlets                 5.7.1            py39haa95532_0  
transformers              4.24.0           py39haa95532_0  
trimesh                   3.21.6                   pypi_0    pypi
trio                      0.22.0                   pypi_0    pypi
trio-websocket            0.9.2                    pypi_0    pypi
tweepy                    4.12.1                   pypi_0    pypi
twisted                   22.2.0           py39h2bbff1b_1  
twisted-iocpsupport       1.0.2            py39h2bbff1b_0  
typing-extensions         4.5.0            py39haa95532_0  
typing_extensions         4.5.0            py39haa95532_0  
tzdata                    2023.3                   pypi_0    pypi
ujson                     5.4.0            py39hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.15          py39haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
vtk                       9.2.6                    pypi_0    pypi
w3lib                     1.21.0             pyhd3eb1b0_0  
watchdog                  2.1.6            py39haa95532_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39haa95532_1  
websocket-client          0.58.0           py39haa95532_4  
werkzeug                  2.3.3                    pypi_0    pypi
whatthepatch              1.0.2            py39haa95532_0  
wheel                     0.38.4           py39haa95532_0  
widgetsnbextension        4.0.7                    pypi_0    pypi
win_inet_pton             1.1.0            py39haa95532_0  
win_unicode_console       0.5              py39haa95532_0  
wincertstore              0.2              py39haa95532_2  
winning                   0.4.6                    pypi_0    pypi
winpty                    0.4.3                         4  
wrapt                     1.14.1           py39h2bbff1b_0  
wsproto                   1.2.0                    pypi_0    pypi
xarray                    2022.11.0        py39haa95532_0  
xgboost                   1.3.3                    pypi_0    pypi
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                3.0.3              pyhd3eb1b0_0  
xlwings                   0.29.1           py39haa95532_0  
xz                        5.4.2                h8cc25b3_0  
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
yarl                      1.8.1                    pypi_0    pypi
zeromq                    4.3.4                hd77b12b_0  
zfp                       0.5.5                hd77b12b_6  
zict                      2.2.0            py39haa95532_0  
zipp                      3.11.0           py39haa95532_0  
zlib                      1.2.13               h8cc25b3_0  
zope                      1.0              py39haa95532_1  
zope.interface            5.4.0            py39h2bbff1b_0  
zstandard                 0.19.0           py39h2bbff1b_0  
zstd                      1.5.5                hd43e919_0  

```
</details>

**Comment by ccordoba12** [comment] 2023-09-10 16:47
Hey @bdwilson24, thanks for reporting. I think this is a duplicate of issue #10081, which we'll try to fix for Spyder 6, to be released before the end of the year.

For now, the only workaround is to disable the `Files` pane. To do that, you need to go the menu

    Tools > Preferences > Plugins

and uncheck the `Files` entry from it.

Let us know if that works for you.

**Comment by ccordoba12** [comment] 2024-02-13 17:01
Closing due to lack of response.

**Closed by ccordoba12** 2024-02-13 17:01 UTC
Labels: status:Awaiting Followup
