### ISSUE TITLE
`Segmentation fault` when opened file has been moved

### ISSUE THREAD

**Issue by kai3341** [spyder-ide/spyder#15373] opened 2021-04-21 13:06 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

`Segmentation fault` when opened file has been moved

### What steps reproduce the problem?

1. Open 2 or more files
2. Move all it somewhere via desktop filemamaner
3. Spyder ask to close first inaccessible file. Say "Yes"
4. Spyder ask to close second inaccessible file. Say "Yes"
5. Segmentation fault

### Paste Traceback/Error Below (if applicable)

```python-traceback

(5) kai@asus-ux360c:~/Projects/spyder/5$ spyder 
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Segmentation fault

```

## Versions

* Spyder version: latest installed via `pip install -UI --pre spyder`. But this behavior i know ~1 year
* Python version: Python 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0] on linux
* Qt version: 5.11.3+dfsg-3
* PyQt version: PyQt5-5.12.3-5.12.10-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl
* Operating System name/version: Debian GNU/Linux 10 (buster)

### Dependencies

```
latest
```

**Comment by dalthviz** [comment] 2021-04-22 18:32
Hi @kai3341 thanks for the feedback! I was unable to reproduce this (I tested with the installer on Windows though). Let us know if you manage to get more info regarding this :)

Pinging @ccordoba12 and @andfoy  just in case

**Comment by ccordoba12** [comment] 2021-04-22 22:36
I could reproduce this with the steps described by @kai3341. We'll try to fix it in a future release.

**Comment by ccordoba12** [comment] 2023-02-24 02:29
This is basically the same as issue #18838, so I'm going to close it in favor of that one.

**Closed by ccordoba12** 2023-02-24 02:29 UTC
Labels: type:Bug, OS:Linux, component:Editor
