### ISSUE TITLE
Cannot type in console or editor windows

### ISSUE THREAD

**Issue by Asingwa** [spyder-ide/spyder#6420] opened 2018-02-09 09:56 UTC
## Description

**What steps will reproduce the problem?**

1. The only thing I changed was adding the current directory tab onto the tool bar
2. 
3. 

**What is the expected output? What do you see instead?**
The cursor blinks once and then disappears. I therefore cannot type.

**Please provide any additional information below**

  File "C:\Users\Busarauser\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 317, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\Busarauser\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 330, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-02-09 14:37
Thanks for reporting. This is a duplicate of https://github.com/spyder-ide/spyder-terminal/issues/123. Unfortunately, we don't know how to fix it yet.

In the meantime you could uninstall `spyder-terminal` to avoid this issue.

**Closed by ccordoba12** 2018-02-09 14:37 UTC
