### ISSUE TITLE
Can't connect to kernel, can't run arcpy module

### ISSUE THREAD

**Issue by tannercho** [spyder-ide/spyder#6492] opened 2018-02-22 06:52 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Tanner\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2489, in execute_in_external_console
    console.execute_code(lines)
  File "C:\Users\Tanner\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 970, in execute_code
    sw.execute(to_text_string(lines))
  File "C:\Users\Tanner\Anaconda2\lib\site-packages\qtconsole\history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "C:\Users\Tanner\Anaconda2\lib\site-packages\qtconsole\console_widget.py", line 632, in execute
    self._execute(source, hidden)
  File "C:\Users\Tanner\Anaconda2\lib\site-packages\qtconsole\frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
ro

**Comment by ccordoba12** [comment] 2018-02-22 13:28
Thanks for reporting. This is a duplicate of issue #6308 and it'll be fixed in our 3.2.7 version, to be released in a couple of days.

For now you need to select your the `Default` Python interpreter in

    Tools > Preferences > Python interpreter

**Closed by ccordoba12** 2018-02-22 13:28 UTC
