### ISSUE TITLE
PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class. iPython

### ISSUE THREAD

**Issue by khalismur** [spyder-ide/spyder#2733] opened 2015-10-02 11:38 UTC
Spyder 2.3.6, Python 3.4.3 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux
IPython >=1.0   :  4.0.0 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
psutil >=0.3    :  3.2.1 (OK)
pyflakes >=0.6.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.4 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

Running this script in an iPython console:
>>>import matplotlib.pyplot

Returns lots of text and finally:
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class

The same does not happen in normal Python console.

I believe it has something to do with some Startup setting for the iPython console in Spyder but I don't enough knowledge to find out the specific point.

Importing just matplotlib does not cause this error. Is it something wrong with the pyplot module or with iPython console configuration?

**Comment by ccordoba12** [comment] 2015-10-02 12:38
What is your Spyder version?

**Comment by khalismur** [comment] 2015-10-02 15:04
Spyder 2.3.6

Sorry, forgot that.

**Comment by ccordoba12** [comment] 2015-10-03 00:04
I can't reproduce this error, sorry. It's (most probably) a problem with your installation.

**Comment by khalismur** [comment] 2015-10-03 15:52
I removed Spyder completely  and installed it again and the problem persists. Also, after a google search, it seems some other people had this problem as well.

Very similar environment:
https://stackoverflow.com/questions/30697089/how-to-force-pyqt5-use-for-qobject-class

I'm sorry if this has little or nothing to do with Spyder, but which module should I reinstall in order to try fixing this issue?

**Comment by Nodd** [comment] 2015-10-05 09:28
The problem is that you're using both PyQt4 (in spyder) and PyQt5 (in matplotlib). One solution is to force matplotlib to sue Qt4. If I remember well, it's something like:
```
import matplotlib
matplotlib.use("Q4Agg")
```

**Comment by ccordoba12** [comment] 2015-10-05 13:50
Yes, I also think what @Nodd's says is the error you're facing. You probably are setting your matplotlib backend in your `matplotlibrc` configuration file.

Since this is not a Spyder issue per se, I'm closing it. But feel free to keep posting comments if you want more advice from us :-)

**Closed by ccordoba12** 2015-10-05 13:50 UTC

**Comment by Nodd** [comment] 2015-10-05 21:30
@ccordoba12 I had this problem too, it happens with no modification in `matplotlibrc` . When both PyQt5 and PyQt4 are installed, matplotlib uses PyQt5 by default even if PyQt4 is already used. Maybe we should add a workaround in spyder, or just wait for spyder v3.0 which will use PyQt5 too.

**Comment by khalismur** [comment] 2015-10-07 00:15
Sadly, the problem persists.

A file with these three lines:
```
import matplotlib as mpl
mpl.use("QT4Agg")
import matplotlib.pyplot as plt
```

produces the same error. Normal python console works fine though.

**Comment by Nodd** [comment] 2015-10-08 11:21
The `t` int `Qt` should be lowercase, I don't know if it matters.

I don't know why it has no effect, this is a common fix (see for example https://bitbucket.org/jpcgt/flatcam/issues/128/arch-linux-with-qt5-getting-the)

**Comment by khalismur** [comment] 2015-10-09 10:08
Very strange... The said solution:

```
from PyQt4 import QtGui, QtCore
import matplotlib #new line
matplotlib.use("Qt4Agg") #new line
```
Still outputs the error for me. Again, this never happens with simple Python console.

Thanks for the attention and the help folks. I guess I will just use normal console until Spyder (or iPython?) adopts Qt5...

**Comment by Nodd** [comment] 2015-10-09 11:14
If you feel adventurous, you can use the development version of spyder, which works with Qt5. I use it every day at work so it's still quite stable.

**Comment by RJ3** [comment] 2016-03-24 15:28
Hello there, especially khalismur. I am getting the exact same error message.

Did you ever find a solution to this problem? Spyder3 v3 is still not released yet so it's not really an option for me. I don't understand why this wouldn't work with Spyder 2.3.8.

Really, I just need Spyder to use the PyQt4 runtimes and then use PyQt5 for my development.

**Comment by Nodd** [comment] 2016-03-24 15:52
I think that on the stable version of spyder you can't run a program that uses PyQt5. I'm not sure why exactly, maybe because of some hooks used to integrate the executions into spyder (like breakpoints or variable explorer for example).
Even on spyder v3, I have to switch the configuration option I pointed to earlier because some program use PyQt4 and others PyQt5.

**Comment by RJ3** [comment] 2016-03-24 16:18
Thanks for your quick reply Nodd. Looks like I'll have to use Spyder v3 beta for now. PyQt4 is just too old!

**Comment by RJ3** [comment] 2016-03-25 02:06
Someone told me finally how to fix the problem. In the run settings select "use an external system console". Works fine! I am successfully using Spyder3 v2.3.8 with PyQt5!

**Comment by Nodd** [comment] 2016-03-25 07:46
Oh right, I didn't think about that. That's great !

**Comment by aleksandaratanasov** [comment] 2016-05-31 18:31
Just a note: the problem is present even when no `matplotlib` is used. I started Spyder 2 and wrote a small PyQt5 only (no other Qt-related modules included). Upon running I got that same error. I find the whole Spyder and Spyder2 separation quite problematic. Basically you have to switch to a different version of Spyder every time you want to use a different version of PyQt (and Python respectively). Spyder 2 should support both Python 2.x and 3.x plus PyQt4 and PyQt5 without the need to switch back to Spyder (if all this is done then Spyder will basically become obsolete). In terms of user experience if this is done Spyder will improve greatly omho.

**Comment by DafangWang** [comment] 2019-01-19 16:03
![image](https://user-images.githubusercontent.com/22852599/51429131-810e5780-1c46-11e9-9c1e-8fc62b015b4f.png)
it seems to work for me: comment the original two lines(above), and add two new lines(below), it has no error.
