### ISSUE TITLE
Add fuzzy search to the code completion widget

### ISSUE THREAD

**Issue by jpoeppel** [spyder-ide/spyder#3385] opened 2016-08-31 13:59 UTC
First of all thanks to you all for your great effort! I really love spyder.

Instead of a bug, I want to put something up for discussion which was inspired by the neat file chooser functionality in spyder 3.0 (I hope an issue is the correct place for such a suggestion):

The code completion dropdown is great and really helpful but I often find myself only partially remembering the name of a function. In most cases, it is easy enough to scroll through the list of suggestions to find what one was looking for. However for bigger modules (e.g. numpy/wx etc), this is not too easy, especially if you do not know the first letters (or assume wrong ones).

What I want to put up for discussion is to add some control/key-combination that allows a fuzzy search within this code completion suggestion list. I would not want to use fuzzy search in the normal case, as that could greatly hinder normal typing since unwanted suggestions appear and one might have to move up and down, although one started to type the correct signature. However, with some hotkey it might be a nice feature to have for the use case described above.

So far I didn't get around to look at the codebase for spyder 3.0 (I am vaguely familiar with 2.3) so I haven't looked at the file chooser code yet and how easy or hard it would be to adopt something similar for the code completion, but I would be willing to give this a try if I get some pointers as to where I should look, if you guys think that this could be useful.

**Comment by ccordoba12** [comment] 2016-08-31 14:18
This is a very cool suggestion!! I tried it in Visual Studio Code and it works really well, so we could add fuzzy search by default :-)

@goanpeca, what do you say? Something you would like to take a look at for a future release?

**Comment by goanpeca** [comment] 2016-08-31 14:34
Yes indeed!, I think it can be a default as well, but we would need to refine the fuzzy search, right now the fuzzy rules for points are very basic, but I think good enough to move forward.

This is something I am definitely going to include as a feature in the upcoming releases :-)

**Comment by ccordoba12** [comment] 2019-07-26 08:13
Duplicate of #2374.

**Closed by ccordoba12** 2019-07-26 08:13 UTC
Labels: component:Editor, type:Enhancement
