### ISSUE TITLE
Spyder open file dialog doesn't show special/hidden files macOS 

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3291] opened 2016-07-15 01:32 UTC
## Description of your problem

**What steps will reproduce the problem?**
1. Open spyder 3.0.0beta4 (anaconda installation on OS X 10.11.5)
2. Click on Open File button
3. Using new open file dialog attempt to locate special/hidden files that are visible in the finder
4. Files aren't visible (see screen shot below; dialog on left, Finder window on right)

![spydernoshowhidden](https://cloud.githubusercontent.com/assets/3229632/16860934/305cbd56-49f1-11e6-9b09-de5ca9a14e1c.png)
## Versions and main components
- Spyder Version: 3.0.0beta4
- Python Version: Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)
- Operating system: OS X 10.11.5
## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.9.2 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  None (NOK)
PyQt = 5.6
Qt = 5.6.0

**Comment by ccordoba12** [comment] 2016-07-15 17:10
I think to fixthis we need to change the filter for **All files**. Thanks for reporting it :-)

**Comment by Nodd** [comment] 2016-07-16 11:38
On linux there is a context menu to show or hide hidden files. It's not the same on OSX ?

**Comment by ccordoba12** [comment] 2016-07-28 18:28
(*Note to self*) Something that could help:

http://stackoverflow.com/questions/30117068/qfiledialog-showing-hidden-files-although-system-setting-is-off

**Comment by MattACDC** [comment] 2020-04-08 10:48
It's 2020 and I still can't open my .ipython directory in Spyder... Any update? :))

**Comment by goanpeca** [comment] 2020-04-12 02:13
No longer the case with 4.x


<img width="743" alt="Screen Shot 2020-04-11 at 21 12 48" src="https://user-images.githubusercontent.com/3627835/79058906-3ad15980-7c39-11ea-8f90-00b4a334d79d.png">

Closing @ccordoba12 ?

**Comment by MattACDC** [comment] 2020-04-12 10:07
I use Spyder 4.1.2, MacOS Catalina 10.15.3, and my home directory (which indeed contains a .ipython directory), shows like this:
<img width="797" alt="Screenshot 2020-04-12 at 11 04 32 am" src="https://user-images.githubusercontent.com/4457898/79066170-a5bc7800-7cad-11ea-8f10-03a18648f326.png">
Either  I am doing something wrong with configuration (which is the most likely), or the problem is still there for MacOS.

**Comment by goanpeca** [comment] 2020-04-12 12:09
Sorry I missed the open part. Will fix this:-)

**Comment by goanpeca** [comment] 2020-04-12 12:18
Actually @MattACDC there is nothing to fix you need to use `Cmd+Shift+.` when you have the dialog open... that is the Mac Way

https://osxdaily.com/2011/03/01/show-hidden-files-in-mac-os-x-dialog-boxes-with-commandshiftperiod/

**Comment by MattACDC** [comment] 2020-04-12 15:26
@goanpeca Oh, I see, it works, cheers mate!

**Comment by durack1** [comment] 2020-05-27 21:27
@ccordoba12 @goanpeca it seems that the `CMD+Shift+.` works to view the files, but you can't select them to open the file in Spyder 4.1.2.

Can this be reopened?

**Comment by durack1** [comment] 2020-05-27 21:41
@ccordoba12 @goanpeca bad news, this is still an issue for 4.1.3, so please reopen

**Comment by durack1** [comment] 2020-05-27 21:59
@goanpeca thanks. As an FYI, I am currently on MacOS 10.14.6, let me know if you want any other diagnostic info

**Comment by durack1** [comment] 2020-05-27 22:09
@goanpeca as a workaround, you can still drag and drop a file into the editor window so while it's a bit annoying, Spyder can still edit these files (assuming you can figure out the drag and drop open)

**Comment by ccordoba12** [comment] 2020-05-27 22:14
Is this possible in other editor or IDEs, e.g. VSCode? If not, I'd say we should close this one because it really doesn't have to do with Spyder but with the ooen dialog provided by macOS. Besides, the files can be opened from Files just fine.

**Comment by durack1** [comment] 2020-05-27 22:16
Yep, see below
<img width="1054" alt="Screen Shot 2020-05-27 at 3 15 53 PM" src="https://user-images.githubusercontent.com/3229632/83077776-ff45ef80-a02c-11ea-9ae9-3c08780b932b.png">
[VSCode 1.40.1]

**Comment by dalthviz** [comment] 2020-05-27 23:05
Maybe this could help: https://www.qtcentre.org/threads/67923-Get-QFileDialog-to-display-dot-folder-files

Although I think we currently use the static method `getopenfilenames` to get the files to open and that doesn't receive the filter flags (like `QDir.Hidden`)

**Comment by goanpeca** [comment] 2020-05-27 23:17
Thanks for the heads up @dalthviz and @durack1. I will try to get this fixed for the next 4.1.4 release.

Cheers!

**Closed** 2020-05-28 03:46 UTC
Labels: OS:MacOS, component:Editor, type:Bug

**Comment by ptoche** [comment] 2020-06-11 07:12
I'm on MacOS Catalina and came to this thread because I had set invisible files to visible (`cmd+shift+.`) and couldn't see them. But as stated above, if I used `cmd+shift+.` again while the dialog box was open, the invisible files became visible. Unlike durack1, I was able to select the invisible files and open them. So all good for me with latest Catalina and latest Spyder.

**Comment by durack1** [comment] 2020-06-11 17:10
@ptoche interesting, I just tried the same approach on 10.14.6 and it's not the same. So before opening a Spyder instance, issue `cmd+shift+.` and .files become visible in the finder. Then open Spyder 4.1.3, select the open dialog, navigate to the same directory and can't see the files, issue `cmd+shift+.` while the dialog is open, files become visible BUT not selectable. It's interesting to know this behavior differs across MacOS releases

**Comment by ptoche** [comment] 2020-06-12 00:51
@durack1 , I wonder if it's specific to the files you're trying to open. I see from the screenshot that they may be executables. If you you have a simple python text file, say you try to open `tmp.py` in the `.spyder-py3` directory, does it work?

**Comment by durack1** [comment] 2020-06-12 14:32
@ptoche interesting idea, the perms for the files are below
```
drwxr-xr-x   9  288 Jun 12 07:26 .
drwxr-xr-x  51 1632 May 21 10:33 ..
-rw-r--r--@  1 6148 Jun 12 07:26 .DS_Store
-rwxr-xr-x   1 9250 May 29 17:27 .aliases
-rw-r--r--   1  892 May 21 13:23 .bash_profile
-rwxr-xr-x   1 1271 May 21 11:17 .exports
drwxr-xr-x  13  416 May 21 13:22 .git
-rwxr-xr-x   1  173 May 21 11:09 .paths
-rw-r--r--   1    5 Jun 12 07:26 test.py
```
The perm differences between `.paths` and `.bash_profile` would suggest this isn't the case to me
![Screen Shot 2020-06-12 at 7 30 56 AM](https://user-images.githubusercontent.com/3229632/84513752-c178d600-ac7e-11ea-8a2a-35b497ce383b.png)

**Comment by durack1** [comment] 2020-07-24 16:18
@ccordoba12 @goanpeca thanks folks, 4.1.4 works a treat!
![Screen Shot 2020-07-24 at 9 17 37 AM](https://user-images.githubusercontent.com/3229632/88412528-96f65e80-cd8e-11ea-8cab-77b57e1234d9.png)
