### ISSUE TITLE
Crash when using python netCDF4 in spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1711] opened 2015-02-17 20:29 UTC
_From [Favi...@gmail.com](https://code.google.com/u/100323903298944432890/) on 2014-01-29T02:14:39Z_

The program crashes when I try to open a netcdf file with the suplied netCDF4 library version 1.0.7.

To reproduce:
1.- From the shortcuts window start spyder none-IDE 
2.- In the python console frame, import numpy and netCDF4 
3.- Open a netcdf file with the Dataset comand from netCDF4 
4.- Spyder freezes.

netCDF4 works fine from a Ipython console or the python interpreter, but crashes on the spyder IDE.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1711_

**Comment by goanpeca** [comment] 2015-04-12 09:58
Duplicate of #1604

**Closed** 2015-04-12 09:59 UTC
Labels: 2–5 stars, bug, netcdf4, Spyder-Gui, Windows
