### ISSUE TITLE
Removing a frame created by pdconcat(frames, sort=False)

### ISSUE THREAD

**Issue by moonrox** [spyder-ide/spyder#11442] opened 2020-01-30 22:12 UTC
### What steps will reproduce the problem?

```python
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 29 16:13:10 2020

@author: jmonroe1
"""
import pandas as pd
import io
import requests
import zipcodes as zip


data = pd.read_csv('C:/projects/lab2/Zip_Zhvi_SingleFamilyResidence.csv', encoding='latin-1')
clean_data = data[['RegionID','RegionName','City','State', 'CountyName','SizeRank','1996-04','1996-04','1996-05', '1996-06' ]]
#print(data.describe())
clean_data = clean_data.rename(columns = {'RegionName':'zip_code'}, inplace = True)
clean_data = data.dropna()
print(clean_data.columns)
syr_zips = zip.filter_by(city='Syracuse')
syr_zips = pd.DataFrame(syr_zips)

#new_data = new_data.rename(columns={"RegionName","zip_code"})
#syr_zips = syr_zips.rename(columns={"zip_codes":"zip_code"})

frames = [clean_data, syr_zips]

#Combine the DF's together with the key zip_code
result = pd.concat(frames, sort=False)
print(result.columns)
```

### Traceback
```python-traceback
  File "C:\Users\jmonroe1\AppData\Roaming\Python\Python37\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 790, in contextMenuEvent
    self.refresh_menu()
  File "C:\Users\jmonroe1\AppData\Roaming\Python\Python37\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 707, in refresh_menu
    self.refresh_plot_entries(index)
  File "C:\Users\jmonroe1\AppData\Roaming\Python\Python37\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 712, in refresh_plot_entries
    is_list = self.is_list(key)
  File "C:\Users\jmonroe1\AppData\Roaming\Python\Python37\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1464, in is_list
    return self.var_properties[name]['is_list']
KeyError: 'frames'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.8.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-31 03:35
You have no description about how this error is generated and from the traceback above it's clear that it's not caused by simply running the code you posted.

So please describe in detail how your error appears.

**Comment by ccordoba12** [comment] 2020-02-01 18:04
Duplicate of #11451

**Comment by ccordoba12** [comment] 2020-02-01 18:04
Please **do not** report the same issue several times. It's just a waste of time for us.

**Closed by ccordoba12** 2020-02-01 18:04 UTC
Labels: status:Awaiting Followup
