### ISSUE TITLE
Run cell block - not working as it did before on spyder3

### ISSUE THREAD

**Issue by mayurpande** [spyder-ide/spyder#11253] opened 2020-01-07 17:18 UTC
### Issue Report Checklist

* [ /] Searched the [issues page](https://github.com/spyder-ide/spyder/issues/8994#issuecomment-571671223) for similar reports
* [/ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [/ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)

* [/ ] Tried basic troubleshooting (if a bug/error)
    * [/ ] Restarted Spyder
    * [/ ] Reset preferences with ``spyder --reset``
    * [/ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [/ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am trying to run a cell block within a function to test values in the ipython console. But in spyder4 we have to use `#%%` before and after blocks of code in order for this to happen. 

This works for small blocks of code. But when I try to do large blocks of code, it tells me I have an indentation problem.

### What steps reproduce the problem?

1. Using `#%%`
2. Running cell block code "ctrl+enter"
3. 

### What is the expected output? What do you see instead?
To be able to use the output variables in the ipython console.

Instead I see an indentation error

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.0
* Python version: 3.8
* Qt version: 5.97
* PyQt version: 1.9.0
* Operating System name/version: Ubuntu 18.04 

#code example

```
def cell_block_ex():

    #%%
    path = '/home/<user>/Documents/projects/office'
    prevlist= pd.read_csv(path + '/m/daily.csv',index_col=0)
    #%%
```
The above works fine

then when I try to run this;

```
def cell_block_ex():
    #%%
    path = '/home/<user>/Documents/projects/office'
    prevlist= pd.read_csv(path + '/m/daily.csv',index_col=0)

    datefrom=parse(prevlist.index.max(), dayfirst = True)
    datefrom = datefrom+timedelta(days=1)
    #%%
```
This throws an indentation error for `path`, the problem with this is I need to check a lot more lines of code, so to keep un-indenting and re-indenting, is very time consuming, same with adding the `#%%`. On the old version I was simply able to select the code press ctrl+enter and then analyse my data.

**Comment by bcolsen** [comment] 2020-01-07 23:08
Closing this as a duplicate of #11023.

Please see my comments there. Using code cell inside of functions is a bad idea because you are mixing the local namespace with the global. It's kind of like doing this: https://stackoverflow.com/questions/11543297/make-all-variables-in-a-python-function-global/11543718. To see the value inside a function you should use the debugger which has been improved for spyder4.

**Closed by bcolsen** 2020-01-07 23:08 UTC
