### ISSUE TITLE
Freezing and lagging after 24hours of having Spyder open.

### ISSUE THREAD

**Issue by leet0rz** [spyder-ide/spyder#15009] opened 2021-03-24 18:24 UTC
## Problem Description
While writing anything spyder will freeze up and take 0.5 seconds to show the code I wrote during the freeze.
Even just writing asdfasdfasdfasdfssafd on a blank page will lag.

### What steps reproduce the problem?
Just open spyder and let it stay open for 24 hours with a blank page will produce this bug. 

### What is the expected output? What do you see instead?
Expected output? Actually just using the program without lag.

### Paste Traceback/Error Below (if applicable)
no errors.

## Versions
Version is 4.2.4

* Spyder version:   4.2.4
* Python version: 3.8
* Operating System name/version: windows10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  54.1.2 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

**Comment by ccordoba12** [comment] 2021-03-24 18:55
Hey @leet0rz, thanks for reporting. This is a duplicate of issue #14823.

However, it should only happen for large files (i.e. I can type normally in an empty file).

**Closed by ccordoba12** 2021-03-24 18:55 UTC

**Comment by leet0rz** [comment] 2021-03-24 19:01
> 
> 
> Hey @leet0rz, thanks for reporting. This is a duplicate of issue #14823.
> 
> However, it should only happen for large files (i.e. I can type normally in an empty file).

It happens in empty files too if the client is open for a while.
