### ISSUE TITLE
Error message given selecting directory

### ISSUE THREAD

**Issue by GregSal** [spyder-ide/spyder#11410] opened 2020-01-27 17:21 UTC
### What steps will reproduce the problem?

Error with server style path name:
\\dkphysicspv1\e$\Gregs_Work\Aria CCO Reporting\ARIA_Queries\Structures Query
Work arround: use mapped drive:
S:\Aria CCO Reporting\ARIA_Queries\Structures Query

Notes:
  Appeared with most recent update worked file in previous version
  Could be the "$" in the path name rather than the server style path. 
  

### Traceback
```python-traceback
Exception in comms call set_cwd:
  File "C:\Users\gsalomon\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Users\gsalomon\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Users\gsalomon\anaconda3\Lib\site-packages\spyder_kernels\console\kernel.py", line 352, in set_cwd
    os.chdir(dirname)
FileNotFoundError: [Errno 2] The specified path is invalid: '\\\\\\\\dkphysicspv1\\\\e$\\\\Gregs_Work\\\\Aria CCO Reporting\\\\ARIA_Queries\\\\Structures Query'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-27 17:29
Duplicate of #10785

**Comment by ccordoba12** [comment] 2020-01-27 17:29
It'll be fixed in our next version.

**Closed by ccordoba12** 2020-01-27 17:29 UTC
