### ISSUE TITLE
Linting stops working after a while (Spyder 4)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11189] opened 2019-12-27 19:57 UTC
`# TODO` doesn't yield blue marker, undeclared variables don't yield yellow/red markers, syntax errors don't yield red markers, "Go to definition" fails, and generally many linting features cease functioning after a while of using Spyder. The "Go to definition" stopping working was also present in Spyder 3, but not all the rest.

Don't know exact steps to reproduce, will update when do.

**Comment by ccordoba12** [comment] 2019-12-28 03:47
Duplicate of #11026

**Comment by ccordoba12** [comment] 2019-12-28 03:47
We really don't know why this happens, sorry.

**Closed by ccordoba12** 2019-12-28 03:47 UTC

**Comment by OverLordGoldDragon** [comment] 2019-12-28 12:57
Just to add another - linter gets "stuck" thinking a variable is never used, even after it is, and even after its definition is commented entirely (which should yield a red marker): [lint_demo.mp4](https://www.dropbox.com/s/4j1brjukpple7if/lint_demo.mp4?dl=0)

**Comment by ccordoba12** [comment] 2019-12-28 14:21
Please post your comment on issue #11026 because this one is closed now.
