### ISSUE TITLE
Can get rid of warning message from monitor scale screen

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#11892] opened 2020-03-20 03:11 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After adding an external monitor I get warning "a monitor scale change was detected..." and I can't get rid of the warning not even after not having the monitor connected! (I accept restarting Spyder on the warning message and the issue just keeps appearing)
### What steps reproduce the problem?

1. Adding external monitor
2. Disconnecting external monitor
3. Accepting to restart Spyder on warning message
4. Opening Spyder

![Screen Shot 2020-03-19 at 10 05 50 PM](https://user-images.githubusercontent.com/18587879/77132774-8b84d680-6a2e-11ea-8d93-8de98515ef88.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by rlloretb** [comment] 2020-03-20 08:22
This issue is making Spyder unusable. It keeps popping out every 10 seconds.

**Comment by ccordoba12** [comment] 2020-03-20 13:26
Duplicate of #11846

**Closed by ccordoba12** 2020-03-20 13:26 UTC
