### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by jesen8** [spyder-ide/spyder#6343] opened 2018-01-31 05:42 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\console_widget.py", line 413, in eventFilter
    return self._event_filter_console_keypress(event)
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 108, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\console_widget.py", line 1425, in _event_filter_console_keypress
    self.copy()
  File "c:\users\jesen\appdata\local\programs\python\python35\lib\site-packages\qtconsole\frontend_widget.py", line 249, in copy
    was_newline = text[-1] == '\n'
IndexError: string index out of range

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by Prikers** [comment] 2018-01-31 12:41
Thanks for reporting. This is not a problem with Spyder but a duplicate of

jupyter/qtconsole#264

It needs to be fixed there.

**Closed by Prikers** 2018-01-31 12:41 UTC
