### ISSUE TITLE
Completion and Linting in the Editor for Python files KILLING MY LIFE

### ISSUE THREAD

**Issue by pbower** [spyder-ide/spyder#12112] opened 2020-04-02 22:14 UTC
## Problem Description
The below dialog comes up every 30-45 minutes in Spyder 4.1.1 causing the program to lock and require full restart. It is impossible to explain to my network administrator why I need permissions for an open source python program to open up ports on my system per the dialog. Nor should one have to given it has always worked, and this error only happens intermittently?

![image](https://user-images.githubusercontent.com/37089506/78304534-b02e9180-758a-11ea-852d-9bcec0bce6c5.png)

### What steps reproduce the problem?

1.  Use Spyder 4.1.1 without network admin privileges.
2.  Work for 30 minutes.
3.  Encounter this error
4. Throw computer out window.

### What is the expected output? What do you see instead?
To not encounter the error and not need Spyder to open up ports for 'Completion and Linting'.

### Paste Traceback/Error Below (if applicable)

![image](https://user-images.githubusercontent.com/37089506/78304722-17e4dc80-758b-11ea-99e1-45025a71d2c5.png)

```python-traceback


```

## Versions
* Spyder version: 4.1.1
* Python version: 3.7.6 64 bit
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 Enterprise

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

```

**Comment by ccordoba12** [comment] 2020-04-03 00:57
Duplicate of #11026

**Comment by ccordoba12** [comment] 2020-04-03 00:57
It'll be fixed in our 4.1.2 version, to be released in a couple of days.

**Closed by ccordoba12** 2020-04-03 00:57 UTC

**Comment by pbower** [comment] 2020-04-03 01:14
Great!!!!!!!!!!! Thanks so much
Was almost going to go to VIM for stability...
