### ISSUE TITLE
Crash while opening DataFrame inside list

### ISSUE THREAD

**Issue by ApesRex** [spyder-ide/spyder#6947] opened 2018-04-12 07:50 UTC
Opened a DataFrame (> 20000 rows) inside a list from the Variable explorer. Structure: [df1, df2]. The DataFrames were created with pd.read_csv. The DataFrame-window appears but with an instant crash of Spyder.

### Traceback
```python-traceback
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 207, in headerData
    header = to_text_string(self.df_header[0])
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 207, in headerData
    header = to_text_string(self.df_header[0])
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 207, in headerData
    header = to_text_string(self.df_header[0])
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 207, in headerData
    header = to_text_string(self.df_header[0])
  File "c:\software\python27\arcgisx6410.5\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 3: ordinal not in range(128)
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.13
* Qt version: 4.8.7
* PyQt4 (API v2) version: 4.11.4
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.2 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.6.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment] 2018-04-12 13:17
Thanks for reporting. This is a duplicate of issue #5833.

Until we fix it, the solution is to change your header names to use non-ascii characters.

**Closed by ccordoba12** 2018-04-12 13:17 UTC
