### ISSUE TITLE
Ctrl+I to inspect current objects doesn't work in editor but works in console.

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#8915] opened 2019-03-11 01:46 UTC
I'm using spyder from repository master, windows 10 x64. `Inspect Current Object` works fine in Console, but failed a lot in the editor. I recorded a gif to show, and provided some environment information. Please let me know if there's more info I can provide.

Some description: 
* I opened a spyder, created a new script, 
* Type in `import pandas as pd` in the editor and execute it.
* Type in `pd.read_excel` and hit `ctrl+I` to inspect (to see some args and kwargs of that method)
* The help panel shows `No further documentation available`
* Then type in `pd.read_excel` in the console, and hit `ctrl+I`, the help panel gives the correct help information.

![gif2](https://user-images.githubusercontent.com/4179106/54095684-75881300-43e3-11e9-896b-d8c936398b99.gif)

## Environments:

```
spyder: master (from 2019-03-11)
spyder-kernels: 1.3.0.dev0
```

**More:**
<details><summary>More informations from `conda list`</summary>
<p>

```
C:\Users\user>conda list
# packages in environment at C:\anaconda3:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0                     mro_2
adjusttext                0.7.3                    pypi_0
affine                    2.2.1                    py36_0
alabaster                 0.7.12                     py_0
altair                    2.3.0                 py36_1001
anaconda                  custom           py36h363777c_0
anaconda-client           1.7.2                    py36_0
anaconda-navigator        1.9.6                    py36_0
anaconda-project          0.8.2                    py36_0
appdirs                   1.4.3            py36h28b3542_0
asn1crypto                0.24.0                   py36_0
astroid                   2.0.4                    py36_0
astropy                   3.0.4            py36hfa6e2cd_0
atomicwrites              1.2.1                    py36_0
attrs                     18.2.0           py36h28b3542_0
automat                   0.7.0                    py36_0
autopep8                  1.3.4                    pypi_0
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0                      py36_1
backports-csv             1.0.5                    pypi_0
backports.functools_lru_cache 1.5                        py_1
backports.shutil_get_terminal_size 1.0.0                    py36_2
baidu-aip                 2.2.2.0                  pypi_0
beautifulsoup4            4.7.1                 py36_1001
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h7e685f7_0
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0
bleach                    2.1.2                    pypi_0
blosc                     1.14.4               he51fdeb_0
bokeh                     1.0.4                 py36_1000
boost                     1.68.0           py36hf75dd32_0
boost-cpp                 1.68.0            h6a4c333_1000
boto                      2.49.0                   py36_0
boto3                     1.9.17                     py_0
botocore                  1.12.18                    py_0
bottleneck                1.2.1            py36h452e1ab_1
branca                    0.3.1                      py_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.1.23                     0
cachecontrol              0.12.5                   py36_0
cairo                     1.16.0            hc1b38c8_1000
cartopy                   0.17.0          py36h2ddeffc_1001
certifi                   2018.11.29               py36_0
cffi                      1.11.5           py36h74b6da3_1
cftime                    1.0.1            py36h452e1ab_1
chardet                   3.0.4                    py36_1
click                     7.0                      py36_0
click-plugins             1.0.4                      py_0
cligj                     0.5.0                    pypi_0
cloudpickle               0.5.6                    py36_0
clyent                    1.2.2                    py36_1
colorama                  0.3.9            py36h029ae33_0
coloredlogs               10.0                     py36_0
colorspacious             1.1.2                    pypi_0
comtypes                  1.1.7                    py36_0
conda                     4.6.7                    py36_0
conda-env                 2.6.0                         1
conda-verify              3.1.1                    py36_0
console_shortcut          0.1.1                         3
constantly                15.1.0           py36h28b3542_0
contextily                0.99.0                   pypi_0
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.3.1            py36h74b6da3_0
curl                      7.61.1               h7602738_0
cycler                    0.10.0           py36h009560c_0
cython                    0.29             py36ha925a31_0
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask                      0.15.2                   py36_0
dask-core                 0.19.3                     py_0
datashape                 0.5.4                    py36_1
decorator                 4.2.1                    pypi_0
defusedxml                0.5.0                    py36_1
descartes                 1.1.0                    pypi_0
dill                      0.2.9                    pypi_0
distlib                   0.2.7                    py36_0
distributed               1.23.3                   py36_0
docutils                  0.14             py36h6012d8f_0
elasticsearch             2.3.0                    pypi_0
entrypoints               0.2.3                    py36_2
et_xmlfile                1.0.1            py36h3d2d736_0
expat                     2.2.5                he025d50_0
fastcache                 1.0.2            py36hfa6e2cd_2
ffmpeg                    4.1               h86867b3_1000
filelock                  3.0.8                    py36_0
fiona                     1.7.13                   pypi_0
flashtext                 2.7                      pypi_0
flask                     1.0.2                    py36_1
flask-cors                3.0.6                    py36_0
folium                    0.7.0                      py_0
freetype                  2.9.1                ha9979f8_1
freexl                    1.0.5                hfa6e2cd_0
future                    0.16.0                   pypi_0
gdal                      2.2.3                    pypi_0
geographiclib             1.49                       py_0
geopandas                 0+unknown                pypi_0
geopy                     1.11.0                   pypi_0
geos                      3.6.2                h9ef7328_2
geotiff                   1.4.2             h8408f58_1006
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.6            py36hfa6e2cd_0
git                       2.19.1               h21ff451_0
graphviz                  2.38                 hfd603c8_2
greenlet                  0.4.15           py36hfa6e2cd_0
h5netcdf                  0.6.2                      py_0
h5py                      2.8.0            py36h3bdd7fb_2
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
html2text                 2018.1.9                 pypi_0
html5lib                  1.0.1                    py36_0
humanfriendly             4.16.1                   py36_0
hyperlink                 18.0.0                   py36_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
image-match               1.1.2                    pypi_0
imageio                   2.4.1                    py36_0
imagesize                 1.1.0                    py36_0
imutils                   0.5.2                    pypi_0
incremental               17.5.0                   py36_0
inspyred                  1.0.1                    pypi_0
intel-openmp              2019.0                      118
ipdb                      0.11                     pypi_0
ipykernel                 4.8.0                    pypi_0
ipython                   7.3.0            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              0.24                     py36_1
jdcal                     1.4                      py36_0
jedi                      0.11.1                   pypi_0
jinja2                    2.10                     pypi_0
jmespath                  0.9.3                    py36_0
jpeg                      9c                hfa6e2cd_1001
json-rpc                  1.11.1                     py_0
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_7
jupyter-contrib-core      0.3.3                    pypi_0
jupyter-contrib-nbextensions 0.5.0                    pypi_0
jupyter-highlight-selected-word 0.2.0                    pypi_0
jupyter-latex-envs        1.4.6                    pypi_0
jupyter-nbextensions-configurator 0.4.0                    pypi_0
jupyter_client            5.2.4                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.4.0                    py36_0
jupyter_server            0.0.3                    py36_0
jupyterlab                0.31.5                   pypi_0
jupyterlab-github         0.5.0                    pypi_0
jupyterlab-latex          0.3.1                    pypi_0
jupyterlab-launcher       0.10.3                   pypi_0
jupyterlab_server         0.2.0                    py36_0
jupytext                  1.0.0                    pypi_0
kealib                    1.4.9                h4380d0d_2
keyring                   15.1.0                   py36_0
kiwisolver                1.0.1            py36h6538335_0
krb5                      1.16.1               h038dc86_6
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libboost                  1.67.0               hd9e427e_4
libcurl                   7.61.1               h7602738_0
libgdal                   1.11.2                        1
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
libnetcdf                 4.6.1                h70ac11d_1
libpng                    1.6.35            h7602738_1002
libpq                     10.5                 h5fe2233_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.8.5                h6538335_2
libspatialite             4.3.0a            haf48945_1024
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                h36446d0_2
libwebp                   0.5.2                         7
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.25.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lockfile                  0.12.2           py36h0468280_0
lxml                      4.3.0            py36h1350720_0
lzo                       2.10                 h6df0209_2
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gsl                 2.1                           2
m2w64-libiconv            1.14                          6
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libtiff             4.0.6                         2
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-pcre                8.38                          2
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
mapclassify               2.0.1                    pypi_0
markdown                  3.0.1                    pypi_0
markupsafe                1.0              py36hfa6e2cd_1
matplotlib                3.0.0                    pypi_0
matplotlib-base           3.0.2           py36h3e3dc42_1001
mccabe                    0.6.1                    py36_1
menuinst                  1.4.14           py36hfa6e2cd_0
mercantile                1.0.4                      py_0
mistune                   0.8.3                    pypi_0
mizani                    0.5.3                    pypi_0
mkl                       2019.1                      144
mkl-service               1.1.2            py36hb782905_5
mkl_fft                   1.0.10           py36h14836fe_0
mkl_random                1.0.2                    py36_0
mock                      2.0.0                    pypi_0
more-itertools            4.3.0                    py36_0
moviepy                   0.2.3.2                  pypi_0
mplcairo                  0.1.post28+g9efa978          pypi_0
mpld3                     0.3                      py36_0
mpmath                    1.0.0                    py36_2
msgpack-python            0.5.6            py36he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py36_0
munch                     2.3.2                    py36_0
navigator-updater         0.2.1                    py36_0
nbconvert                 5.4.1                      py_2
nbformat                  4.4.0            py36h3a5bc1b_0
netcdf4                   1.4.1            py36hbfe741f_0
netease-musicbox          0.2.5.3                  pypi_0
networkx                  2.2                      py36_1
nltk                      3.3.0                    py36_0
nodejs                    10.13.0                       0
nose                      1.3.7                    py36_2
notebook                  5.7.4                    py36_0
numba                     0.40.0           py36hf9181ef_0
numexpr                   2.6.9            py36hdce8814_0
numpy                     1.15.4           py36h19fb1c0_0
numpy-base                1.15.4           py36hc3f5095_0
numpydoc                  0.8.0                    py36_0
oauthlib                  2.0.6                    pypi_0
odo                       0.5.1            py36h7560279_0
olefile                   0.46                     py36_0
opencc-python-reimplemented 0.1.4                    pypi_0
opencv                    3.4.3           py36h597e314_201
opencv-python             3.4.4.19                 pypi_0
openjpeg                  2.3.0                h5ec785f_1
openpyxl                  2.5.8                    py36_0
openssl                   1.0.2r               he774522_0
owslib                    0.17.0                   py36_0
packaging                 18.0                     py36_0
palettable                3.1.1                    pypi_0
pandas                    0.24.1           py36ha925a31_0
pandoc                    2.6                           1
pandoc-eqnos              1.3.0                    pypi_0
pandoc-fignos             1.3.0                    pypi_0
pandoc-latex-admonition   1.2.2                    pypi_0
pandoc-tablenos           1.3.0                    pypi_0
pandocfilters             1.4.2                    py36_1
panflute                  1.11.0                   pypi_0
parso                     0.1.1                    pypi_0
partd                     0.3.8            py36hc8e763b_0
patsy                     0.5.0                    py36_0
pbr                       4.0.4                    pypi_0
pcre                      8.42                 hd6b2f15_0
pendulum                  2.0.4                    pypi_0
pep8                      1.7.1                    py36_0
pexpect                   4.6.0                    py36_0
pickleshare               0.7.5                    py36_0
piexif                    1.1.2                    pypi_0
pillow                    5.1.0                    pypi_0
pip                       10.0.0                   pypi_0
pixman                    0.34.0               hcef7cb0_3
pkginfo                   1.4.2                    py36_1
plotnine                  0+unknown                pypi_0
pluggy                    0.7.1            py36h28b3542_0
ply                       3.11                     py36_0
plydata                   0.3.2                    pypi_0
postgresql                10.5                 h5fe2233_0
progress                  1.4                      py36_0
proj4                     5.2.0             hfa6e2cd_1001
prometheus_client         0.4.0                      py_0
prompt_toolkit            2.0.5                    py36_0
psutil                    5.4.7                    pypi_0
psycopg2                  2.7.5            py36h74b6da3_0
pweave                    0.30.3                   pypi_0
py                        1.7.0                    py36_0
pyasn1                    0.4.4            py36h28b3542_0
pyasn1-modules            0.2.2                    py36_0
pybind11                  2.2.4                    pypi_0
pycairo                   1.18.0           py36h63da52a_0
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.19                     py36_0
pycrypto                  2.6.1            py36hfa6e2cd_9
pycryptodomex             3.6.1                    pypi_0
pycurl                    7.43.0.2         py36h74b6da3_0
pydocstyle                3.0.0                    py36_0
pyepsg                    0.3.2                    py36_0
pyflakes                  2.0.0                    py36_0
pyftpdlib                 1.5.4                      py_1
pygame                    1.9.3                    pypi_0
pygments                  2.2.0            py36hb010967_0
pyhamcrest                1.9.0                      py_2
pykdtree                  1.3.1           py36h452e1ab_1002
pykml                     0.1.3                    py36_0
pykrige                   1.4.0           py36h452e1ab_1001
pykriging                 0.2.0                    pypi_0
pylint                    2.1.1                    py36_0
pymupdf                   1.12.5                   pypi_0
pyodbc                    4.0.24           py36h6538335_0
pyopenssl                 18.0.0                   py36_0
pypandoc                  1.4                      pypi_0
pyparsing                 2.3.1                    pypi_0
pypdf2                    1.26.0                   py36_1
pyproj                    1.9.5.1         py36h1fcc0e4_1007
pyqt                      5.6.0            py36ha878b3d_6
pysal                     1.14.3                   pypi_0
pyshp                     1.2.12                   py36_0
pysocks                   1.6.8                    py36_0
pytables                  3.4.4            py36he6f6034_0
pytest                    3.8.2                 py36_1000
pytest-arraydiff          0.2              py36h39e3cac_0
pytest-astropy            0.4.0                    py36_0
pytest-doctestplus        0.1.3                    py36_0
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.3.0                    py36_0
python                    3.6.8                h9f7ef89_1
python-dateutil           2.7.3                    py36_0
python-frontmatter        0.4.2                    pypi_0
python-jsonrpc-server     0.1.0                      py_0
python-language-server    0.21.5                py36_1000
python-slugify            1.2.5                    pypi_0
pythonmagick              0.9.13                   pypi_0
pythonnet                 2.3.0                    pypi_0
pytumblr                  0.0.7                    pypi_0
pytz                      2018.5                   py36_0
pytzdata                  2018.7                   pypi_0
pywavelets                1.0.1            py36h8c2d366_0
pywin32                   224             py36hfa6e2cd_1000
pywin32-ctypes            0.2.0                 py36_1000
pywinpty                  0.5.4                    py36_0
pyyaml                    3.13             py36hfa6e2cd_0
pyzmq                     16.0.4                   pypi_0
qdarkstyle                2.5.4                    pypi_0
qt                        5.6.2           vc14h6f8c307_12
qtawesome                 0.5.5              pyh8a2030e_0
qtconsole                 4.4.3                    py36_0
qtpy                      1.5.2                    py36_0
rasterio                  1.0.5                    pypi_0
requests                  2.21.0                   py36_0
requests-cache            0.4.13                   pypi_0
requests-oauthlib         0.8.0                    pypi_0
rise                      5.2.0                    pypi_0
rope                      0.11.0                   py36_0
rpy2                      2.9.4                    pypi_0
rtree                     0.8.3                    py36_0
ruamel_yaml               0.15.71         py36hfa6e2cd_1000
s3transfer                0.1.13                   py36_0
scikit-image              0.12.3                   pypi_0
scikit-learn              0.20.2           py36h343c172_0
scikit-misc               0.1.1                    pypi_0
scipy                     1.2.0            py36h29ff71c_0
seaborn                   0.9.0                    py36_0
selenium                  3.141.0         py36hfa6e2cd_1000
send2trash                1.5.0                    py36_0
service_identity          17.0.0           py36h28b3542_0
setuptools                38.5.1                   pypi_0
shapely                   1.6.4            py36hc90234e_0
shutilwhich               1.1.0                    pypi_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h6538335_2
six                       1.11.0                   py36_1
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1            py36h763602f_0
snuggs                    1.4.2                    py36_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.0.5                    py36_0
soupsieve                 1.7.1                 py36_1000
sphinx                    1.8.1                    py36_0
sphinx-gallery            0.2.0                    pypi_0
sphinx-rtd-theme          0.4.1                    pypi_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder                    4.0.0.dev0               pypi_0
spyder-kernels            1.3.0.dev0               pypi_0
spyder-notebook           0.2.0.dev0               pypi_0
sqlalchemy                1.2.12           py36he774522_0
sqlite                    3.26.0               he774522_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.3                      py36_0
tblib                     1.3.2            py36h30f5020_0
terminado                 0.8.1                    py36_1
testfixtures              6.3.0                    pypi_0
testpath                  0.4.2                    py36_0
tk                        8.6.8                hfa6e2cd_0
tomd                      0.1.3                    pypi_0
toolz                     0.9.0                    py36_0
tornado                   4.5.3                    pypi_0
tqdm                      4.19.5                   pypi_0
traitlets                 4.3.2            py36h096827d_0
traittypes                0.2.1                      py_1
twisted                   18.7.0           py36hfa6e2cd_1
typed-ast                 1.1.0            py36hfa6e2cd_0
typing                    3.6.4                    py36_0
tzlocal                   1.5.1                    py36_0
unicodecsv                0.14.1           py36h6450c06_0
unidecode                 1.0.22                   pypi_0
urllib3                   1.23                     py36_0
vc                        14.1                 h0510ff6_3
vincent                   0.4.4                      py_1
voila                     0.0.8                      py_0
vs2015_runtime            15.5.2                        3
wand                      0.4.4                    pypi_0
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
werkzeug                  0.14.1                   py36_0
wget                      3.2                      pypi_0
wheel                     0.32.1                   py36_0
widgetsnbextension        3.4.2                    py36_0
win_inet_pton             1.0.1                    py36_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
windows-curses            1.0                      pypi_0
winpty                    0.4.3                         4
wordcloud                 1.5.0                    pypi_0
wrapt                     1.10.11          py36hfa6e2cd_2
xarray                    0.10.9                   py36_0
xerces-c                  3.2.0                h44c76bb_2
xlrd                      1.2.0                    py36_0
xlsxwriter                1.1.2                    py36_0
xlwings                   0.15.1                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.25.0                   py36_0
you-get                   0.4.1193                 pypi_0
youtube-dl                2019.2.8                 pypi_0
zeromq                    4.2.5                he025d50_1
zhconv                    1.4.0                    pypi_0
zict                      0.1.3                    py36_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py36_1
zope.interface            4.5.0            py36hfa6e2cd_0
```
</p>
</details>

**Comment by bcolsen** [comment] 2019-03-11 05:04
Thanks for reporting. I'm closing this as a duplicate of #5522. If you have any more input or ideas on how to fix this feel free to comment on that thread.

A little background on why this happens. In this case Pandas is appending the doc string to the functions using decorators when they are imported. See here: https://github.com/pandas-dev/pandas/blob/f88613929d6c83952cb5a6bf70678a78be480baa/pandas/io/excel/_base.py#L259 

The completion engine used in Spyder, namely Jedi, doesn't execute the decorators so there is no documentation found for these functions. This is also very common in Matplotlib.

**Closed by bcolsen** 2019-03-11 05:04 UTC
