### ISSUE TITLE
IPython console not showing initial banner in Spyder 6

### ISSUE THREAD

**Issue by beew** [spyder-ide/spyder#22440] opened 2024-09-06 01:23 UTC
Ipython console is not displaying initial banners like version of python and version of Ipython etc. 
(the box in Preference > Ipython console > display initial banner is checked)

The banner is displayed briefly when the "Help Spyder" pop up window is a white square.
![Screenshot from 2024-09-05 21-20-06](https://github.com/user-attachments/assets/f28ce25b-42d0-4a1b-9eaf-52b0e6b3cd57)

Once the Help Spyder window is rendered the initial banner in Ipython console disappears. 

![Screenshot from 2024-09-05 21-20-09](https://github.com/user-attachments/assets/ead71949-43b0-47e0-a5d7-dc87a31f0e90)

![Screenshot from 2024-09-05 21-20-17](https://github.com/user-attachments/assets/630ec065-0805-4a06-89a4-273b99c011d9)

The window layout in the pictures is Rstudio layout, but choosing default  shows the same problem.
```

## Versions
* Spyder version: 6.0.0
* Python version: 3.10.9
* PyQt version: 5.15.9
* Operating System name/version: Ubuntu 22.04

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.1.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.1.1 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  6.8.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.13.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.2 (OK)
jellyfish >=0.7                  :  0.9.0 (OK)
jsonschema >=3.2.0               :  4.17.3 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.2.9 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.4 (OK)
pygments >=2.0                   :  2.14.0 (OK)
pylint >=3.1,<4                  :  3.1.0 (OK)
pylint_venv >=3.0.2              :  3.0.2 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  65.5.0 (OK)
sphinx >=0.6.6                   :  6.1.3 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.2.1 (OK)
xdg >=0.26                       :  0.28 (OK)
yarl >=1.9.4                     :  1.9.7 (OK)
zmq >=24.0.0                     :  24.0.1 (OK)

# Optional:
cython >=0.21                    :  0.29.28 (OK)
matplotlib >=3.0.0               :  3.7.1 (OK)
numpy >=1.7                      :  1.23.5 (OK)
pandas >=1.1.1                   :  2.1.3 (OK)
scipy >=0.17.0                   :  1.10.1 (OK)
sympy >=0.7.3                    :  1.13.0 (OK)

```

**Comment by ccordoba12** [comment] 2024-09-06 17:53
Hey @beew, thanks for opening this issue. I have a quick question for you: is the `Help Spyder` window shown for you at every startup?

**Comment by beew** [comment] 2024-09-06 18:44
@ccordoba12 

Yes, it shows everytime. It starts at a white square then it renders just like in the screenshots.

**Comment by ccordoba12** [comment] 2024-09-12 16:32
Ok, that was an oversight on our side and it'll be also fixed in 6.0.1

**Closed** 2024-09-19 17:55 UTC
Labels: type:Bug, component:IPython Console

**Comment by beew** [comment] 2024-09-24 08:47
Hi, actually it is not fixed in 6.0.1

**Comment by ccordoba12** [comment] 2024-09-24 15:13
We tested the solution I proposed for this thoroughly and now we can't reproduce your problem, sorry.

Please check that you correctly installed 6.0.1 given that you're using a custom installation method.

**Comment by beew** [comment] 2024-09-24 17:02
@ccordoba12 

Actually, the "help spyder" box is not showing any more. The iPython banner shows in start up then gone. But otherwise everything is working and there is no error message when start spyder in the terminal.

**Comment by ccordoba12** [comment] 2024-09-24 17:04
> Actually, the "help spyder" box is not showing any more.

That shows that there's something fishy with your installation, so it's up to you to fix it (sorry but we don't support custom installations, only Anaconda and our own installers).

**Comment by beew** [comment] 2024-09-24 17:18
@ccordoba12 

Ok it looks like my configuration is corrupt. If I rename .config/spyder-py3 and start spyder the Ipython banners show (but the "Help spyder" box doesn't show, which is not a big deal. I know where to make a donation.

Question, I want to use the new config but keep my open tabs, which files should I copy over? pub_history.sqlite and history.py don't seem to be the ones.

Thanks.

**Comment by beew** [comment] 2024-09-26 17:56
@ccordoba12 

So I have figured out. Turns out if you have ~ 10 tabs open the Ipython banners disappear. If it is less then they show up.

Weird.

However, if I test with a new spyder-py3 config the "help spyder" splash screen doesn't show up, instead I have the "welcome to spyder, take a tour" splash just like ijn spyder5.x and it only shows the first time you use spyder (after switching to a new config)

**Comment by ccordoba12** [comment] 2024-09-27 01:40
> So I have figured out. Turns out if you have ~ 10 tabs open the Ipython banners disappear. If it is less then they show up.

You're right, I was able to reproduce this problem again like that. Could you open a new issue about it? We can reopen this one because it's already referenced in our changelog.

> Weird. This is not the behavour of Spyder 5x since I always had that many tabs

We changed the mechanism to render the banner for Spyder 6.

**Comment by ccordoba12** [comment] 2024-09-27 02:12
> However, if I test with a new spyder-py3 config the "help spyder" splash screen doesn't show up, instead I have the "welcome to spyder, take a tour" splash just like in spyder5.x and it only shows the first time you use spyder (after switching to a new config) That is actually not bad. Is it intended?

Yes, it is. The `Help Spyder` message is meant to be shown only the 5th and 25th times Spyder starts (to not annoy users). Besides that, we'll show a blue heart in the status bar twice per month that will show the message again when clicked. We think that's a non-intrusive way to remind users for their support.
