### ISSUE TITLE
Numba makes kernel die

### ISSUE THREAD

**Issue by gkvallis** [spyder-ide/spyder#3969] opened 2017-01-16 17:46 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder
2. Open an ipython console. 
3. Type 'from numba import *'

**What is the expected output? What do you see instead?**
I expect nothing. Instead I get:
  kernel died, restarting

**Please provide any additional information below**

This behaviour only occurs on one of my Macs (an iMac). On the other, it works fine. I had thought they  had identical installations, but I guess not. Numba works fine if I import it on a Python console, but not an Ipython console. It also works fine from a jupyter console outside of spyder. 

## Versions and main components

* Spyder Version: 3.0.2
* Python Version:
* Operating system: OS 10.12.2

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by Deewrat** [comment] 2017-05-30 01:52
My similar problem (see just above) was cured by using the "rest to factory defaults" or whatever.
But then next time I  started Spyder the problem is back again!

**Comment by goanpeca** [comment] 2019-11-28 01:33
This seems to no longer apply. Closing.

**Closed by goanpeca** 2019-11-28 01:33 UTC
Labels: component:IPython Console, type:Bug
