### ISSUE TITLE
"Kernel died, restarting" issue perventing me from going ahead with Coursera Python course

### ISSUE THREAD

**Issue by srinivasaramanujana** [spyder-ide/spyder#3899] opened 2016-12-30 20:03 UTC
## Description of your problem: Spyder IDE "Kernel died, restarting"

Unable to update it to 3.0.2.

1. Open CMD:
2. conda update spyder
3. Error received: SSL verification Error

**What steps will reproduce the problem?**

1. Open CMD (Windows 10)
2. spyder --show-console
3. Spyder UI opens with "Kernel died, restarting"

**What is the expected output? What do you see instead? I'm a new user. I should be able to run Python code in it.

PyCharm runs beautifully well but the course required Spyder.

**Please provide any additional information below**
The NOKs in the Dependencies could be the culprit. Let me know how to make them OK.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by srinivasaramanujana** [comment] 2016-12-30 20:11
Here's the course that starts Jan 2. I need issue fixed before this date.

Thank you for your support in advance.

**Comment by ccordoba12** [comment] 2016-12-30 20:18
What are the errors printed in the terminal where you started Spyder with the command

    spyder --show-console

?

Please copy and paste those errors here to help you with your problem.

**Comment by srinivasaramanujana** [comment] 2016-12-31 04:24
Hello Carlos,

No errors get printed in the terminal before and after starting Spyder.

Attaching screenshots.

![pre_open](https://cloud.githubusercontent.com/assets/24758109/21575779/02831a82-cf3f-11e6-8fad-8c6d96af79a4.png)
![post_open](https://cloud.githubusercontent.com/assets/24758109/21575781/0becfd90-cf3f-11e6-9d6a-1c1475ae5b44.png)
![error1](https://cloud.githubusercontent.com/assets/24758109/21575786/17deff54-cf3f-11e6-8568-2857da1d8628.png)

**Comment by ccordoba12** [comment] 2016-12-31 05:59
After Spyder starts please come back to the terminal where you started it to see if some errors are shown there.

It's also possible that kernels take some time to start, so please wait some seconds to see if the kernel eventually starts.

**Comment by srinivasaramanujana** [comment] 2016-12-31 14:27
So I kept the console open for an hour but nothing happened. "Kernel died, restarting" remained on Spyder Console and no error showed up in CMD but the cursor kept on moving every few minutes mysteriously with nothing printed.

![moving_cursor](https://cloud.githubusercontent.com/assets/24758109/21577902/2b1a116e-cf92-11e6-87a1-f71042e5043b.png)

You can see that the cursor has reached the lower right corner of the screen.

Since nothing was happening, I pressed "Esc" and abort error came up because it has to. I don't think that's an issue, right.

![abort_error](https://cloud.githubusercontent.com/assets/24758109/21577918/616c5894-cf92-11e6-89c9-ed1ad5d8935e.png)

Anyways, I tried updating Spyder and following "Failure errors" came up.

![update_error_1](https://cloud.githubusercontent.com/assets/24758109/21577922/90b002ea-cf92-11e6-82e7-bca37100039a.JPG)

Can you please tell me any Spyder alternative for the time being that has exact following benefits:

"One big benefit of the Anaconda installation is that it includes IPython and IPython notebooks. These allow us to keep a whole lesson in one file, separated into cells. We can easily execute the code in a single cell, so that we don’t have to write complete programs to run and test our code ."

**Comment by srinivasaramanujana** [comment] 2017-01-01 16:41
@ccordoba12 Can you please look into the issue and suggest an alternative so that I could take the course?

**Comment by ccordoba12** [comment] 2017-01-02 01:55
Given that there are no visible errors preventing the kernel from running, then I'd say your firewall and/or antivirus are blocking the communications needed for a kernel to start.

So please stop them for a while and try to start Spyder again to see if that fixes the problem. If that works, you'll need to add rules to avoid that blocking.

**Comment by srinivasaramanujana** [comment] 2017-01-04 08:28
I checked. The firewall isn't blocking the kernel or any part of spyder.

**Comment by srinivasaramanujana** [comment] 2017-01-05 00:13
@ccordoba12 
Hey Carlos, you were right. My Internet Security is blocking the kernel to take off.
I have fixed it and kernel starts but with a new issue:
runfile('C:/Users/---/Documents/Python Scripts/untitled0.py', wdir='C:/Users/---/Documents/Python Scripts')

Is it related to setting up Parent Directory?

Please reply soon.

**Comment by srinivasaramanujana** [comment] 2017-01-05 00:20
The console is printing the what I am instructing it to but the runfile error appears first.

**Comment by ccordoba12** [comment] 2017-01-05 04:04
The `runfile` line is the command used by Spyder to evaluate the current file in the Editor in its Python and IPython consoles. So there's no problem with it, don't worry about it :-)

However, there's something very important you could help us with to improve the situation for others facing the same situation: could you let us know how you fixed the kernel blocking problem?

That way we could add a message let people know what they need to do to fix this problem by themselves. Thanks :-)

**Comment by ccordoba12** [comment] 2017-01-06 15:22
I'm closing this bug because the problem is solved now.

**Closed by ccordoba12** 2017-01-06 15:22 UTC

**Comment by srinivasaramanujana** [comment] 2017-01-06 22:48
@ccordoba12

I am using Kaspersky Internet Security which was restricting the following files from within Anaconda3 folder:

pythonw.exe
python.exe

Open KIS's Firewall setting --> Configure application Rules --> these files will be mentioned under Restricted section

Select both --> right click --> Set Network Rule to "Allow" -- Set Restrictions to "Trusted"

Restart  system and the kernel will start just fine.

Or (be careful!)

If you have some other security software in which you cannot locate these files or the way to un-restrict them, shut the security system down for the time you are gonna use Spyder!

(You should know how to access internet when your security system is shut down)

""" Now, for those people using Windows 10, there is a setting which allows you to have the Windows Defender provide additional but limited protection if you have a third party software system installed like KIS or Bitdefender. (Go find this setting for yourself!)"""

Coming back to shutting the security software down to use spyder, if you do this in Windows 10 the Windows Defender will identify the guard down and take over providing "some" security in absence of "security daddy".

Thing about Windows Defender is, it is a bit lenient on Spyder. After all of the above has happened, start spyder. Windows Defender being another security software will try to block the same files mentioned above but unlike KIS or other software, which does not want your comments on your system's security, display a message box asking to Allow or Block the files. It will happen twice or thrice and you just need to keep on clicking "Allow"

The spyder kernel will load without any issues.

- Bik
