### ISSUE TITLE
Connecting to a Existing Kernel (Remote) Issues/User error (not knowing how to set it up properly)

### ISSUE THREAD

**Issue by robromanowski** [spyder-ide/spyder#3447] opened 2016-09-23 14:04 UTC
Sorry if this the wrong place for this, not really a bug, more of an issue - due to mainly just myself not knowing how to set something up properly.

I posted this on Reddit initially and was directed here: so I'll post it here as well (I'm trying to connect from Windows Spyder client to a remote kernel (a RHEL 6.7 server). 

-----------------------------------------
I need help on using the "Connect to remote kernel" in Spyder, and can't figure it out for the life of me.

I am using both Windows and Linux. Windows 7 locally on my work laptop, and connect to a VM running RHEL 6.7 through Putty.

I have Spyder on windows (through anaconda). I also have anaconda installed on RHEL.

I can access Spyder off RHEL by using Exceed (x11) forwarding to send the GUI to windows running Exceed software, and it's very laggy - as expected, due to x11 latency.

I can use the Windows version of Spyder which runs great - but then it's isolated from our RHEL server.

This is where I think the kernel comes in. I want to use the Windows Spyder client, and connect to the remote RHEL server.

I tried to use the "this a remote kernel" checkbox and typed in my hostname "lab2073" or using user@host "rr830088@lab2073" and password, but it didn't connect.

Can you help me with connecting to it? Do I need to pursue the JSON option as a file with the connection properties?

**Comment by ccordoba12** [comment] 2016-09-23 17:57
Thanks for reporting. I don't have time to help you right now, but will do next week :-)

**Comment by robromanowski** [comment] 2016-09-26 17:53
Okay @ccordoba12. Perfect, thanks so much!

**Comment by robromanowski** [comment] 2016-10-04 18:26
Feel free to delete this comment if this isn't allowed - but just wanted to check in on this. I tried checking the other issues, but can't find any thing related.

**Comment by ccordoba12** [comment] 2016-10-15 21:43
I'm closing this as a duplicate of issue #3323.

@robromanowski, I'll explain there what's needed to connect to remote kernels on Linux from Windows, but basically you need to have installed a package called `paramiko`.

**Closed by ccordoba12** 2016-10-15 21:43 UTC
