### ISSUE TITLE
Spyder won't launch on Windows 7 

### ISSUE THREAD

**Issue by surfingsequoia** [spyder-ide/spyder#4091] opened 2017-02-02 07:25 UTC
Dears

I just set-up Anaconda 3 and try to open Spyder from the cmd and this is what i got 

C:\Users\70598832>spyder
Traceback (most recent call last):
  File "C:\Users\70598832\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\70598832\Anaconda3\lib\site-packages\spyder\app\start.py", line
 103, in main
    from spyder.app import mainwindow
  File "C:\Users\70598832\Anaconda3\lib\site-packages\spyder\app\mainwindow.py",
 line 78, in <module>
    from qtpy.compat import from_qvariant
  File "C:\Users\70598832\Anaconda3\lib\site-packages\qtpy\compat.py", line 15,
in <module>
    from .QtWidgets import QFileDialog
  File "C:\Users\70598832\Anaconda3\lib\site-packages\qtpy\QtWidgets.py", line 2
2, in <module>
    from PyQt5.QtWidgets import *
ImportError: DLL load failed: 指定されたプロシージャが見つかりません。

I am working on a Japanese Windows, the last japanse message would be something like " procedure could not be found" sorry about that. 

Could you please help me diagnose and fix the issue? Thank you very much 

* Spyder Version: Not sure 
* Python Version: Not sure 
* Operating system: Windows 7

**Comment by ccordoba12** [comment] 2017-02-02 08:53
Thanks for reporting, this is a duplicate of issue #3939.

Unfortunately, we don't know how to fix it, sorry.

**Closed by ccordoba12** 2017-02-02 08:53 UTC
Labels: resolution:Duplicate
