### ISSUE TITLE
Autocomplete stops working when closing/opening a new file

### ISSUE THREAD

**Issue by Naviden** [spyder-ide/spyder#4469] opened 2017-05-14 10:37 UTC
## Description

**What steps will reproduce the problem?**

Whenever I close a file and open a new one, the autocomplete function and function documentation ( cmd + i) stop working
I tried restarting the kernel with no luck.
What I can't understand is why everything works fine before I close the file and open a new one!

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-05-14 14:11
Thanks for reporting. We'll take a look at this for Spyder 3.2.

**Comment by ccordoba12** [comment] 2017-08-18 22:01
I think this issue is a duplicate of issue #4410.

**Closed by ccordoba12** 2017-08-18 22:01 UTC
Labels: component:Editor, OS:MacOS, type:Bug
