### ISSUE TITLE
Cannot open project sometimes (4.1.4)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#13434] opened 2020-07-30 19:34 UTC
This is upon `Projects > Open Project` (simply clicking, not even selecting folder). Doesn't help: restarting kernel, opening new console, closing existing project. Did help: restarting Spyder.

Unsure if `pip install tensorflow` is involved (no packages below were updated due to it if I recall), but haven't seen this in 4.1.3.

```
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\projects\plugin.py", line 98, in <lambda>
    triggered=lambda v: self.open_project())
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\projects\plugin.py", line 288, in open_project
    self.notify_project_open(path)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\decorators.py", line 22, in wrapper
    self.emit_request(method, params, requires_response)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\projects\plugin.py", line 553, in emit_request
    self.main.completions.broadcast_notification(method, params)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\plugin.py", line 323, in broadcast_notification
    req_type, req)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 578, in broadcast_notification
    self.send_notification(language, request, params)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 569, in send_notification
    client.perform_request(request, params)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 527, in perform_request
    _id = handler(params)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\languageserver\decorators.py", line 41, in wrapper
    params = req(self, *args, **kwargs)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\languageserver\providers\workspace.py", line 46, in send_workspace_folders_change
    folder_uri = path_as_uri(folder)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\plugins\completion\languageserver\providers\utils.py", line 51, in path_as_uri
    path_obj = pathlib.Path(osp.abspath(path))
  File "D:\Anaconda\envs\tf2_env\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
```

**Comment by andfoy** [comment] 2020-07-31 01:48
Hi @OverLordGoldDragon, thanks for opening this issue, however, it is a duplicate of https://github.com/spyder-ide/spyder/issues/13346, so I'm closing this in favor of that one. Thanks!

**Closed by andfoy** 2020-07-31 01:48 UTC
