### ISSUE TITLE
Spyder yields error messages after conda update --all.

### ISSUE THREAD

**Issue by msgnaf** [spyder-ide/spyder#5925] opened 2017-12-08 15:50 UTC
## Description

**What steps will reproduce the problem?**

1. conda update --all
2. Work in Spyder during the update process.
3. Type 'sum(' in the editor (triggered when opening the first brace of any function).

**What is the expected output? What do you see instead?**

Normal behaviour. Instead a windows pops up: "Error: Spyder has encountered a problem..." (including the following error).

**Please provide any additional information below**

  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (c:\users\username\appdata\local\continuum\anaconda3\lib\site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})

**Comment by CAM-Gerlach** [comment] 2017-12-08 17:15
Thanks for reporting. The error is incomplete, but I'm guessing it ends with

```
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (c:\program files\python35\lib\site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})
```

 as it seems highly likely from the existing trace and the circumstances to be a duplicate of the frequently-reported #5673 , #5744 etc ad naseum. Therefore, the solution is the same: As the error message suggests, roll back from `parso` 0.1.1 to 0.1.0 and it will work. Therefore, this issue can be closed.

**Comment by msgnaf** [comment] 2017-12-08 17:19
Thank you very much! This did indeed work:

`conda install parso=0.1.0`

**Comment by CAM-Gerlach** [comment] 2017-12-08 17:23
Great, thanks.

**Closed** 2017-12-08 17:23 UTC
