### ISSUE TITLE
Can't copy the whole DataFrame in variable explorer 

### ISSUE THREAD

**Issue by yomoko** [spyder-ide/spyder#11174] opened 2019-12-24 14:11 UTC
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In spyder 4, when a dataframe is opened, the column names and index column can't be chosen, so they can't be copied. Version 3 isn't like that. Is there a fix? Thanks.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2019-12-24 14:17
Duplicate of #11096

**Comment by ccordoba12** [comment] 2019-12-24 14:18
It'll be fixed in our next version.

**Closed by ccordoba12** 2019-12-24 14:17 UTC
