### ISSUE TITLE
When I press F10

### ISSUE THREAD

**Issue by CodeKong1028** [spyder-ide/spyder#5779] opened 2017-11-17 02:19 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anacoda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 261, in <lambda>
    self.finished(ec, es))
  File "D:\Anacoda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 326, in finished
    self.show_data(justanalyzed=True)
  File "D:\Anacoda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 347, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "D:\Anacoda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 459, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "D:\Anacoda\lib\pstats.py", line 72, in __init__
    self.init(arg)
  File "D:\Anacoda\lib\pstats.py", line 86, in init
    self.load_stats(arg)
  File "D:\Anacoda\lib\pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\.spyder-py3\\profiler.results'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)

**Comment by CAM-Gerlach** [comment] 2017-11-17 02:30
Likely duplicate of #5587; already resolved in forthcoming Spyder 3.2.5.

**Closed** 2017-11-17 14:29 UTC
