### ISSUE TITLE
unknown error  

### ISSUE THREAD

**Issue by tankalasreekar** [spyder-ide/spyder#9916] opened 2019-07-30 03:30 UTC
### What steps will reproduce the problem?

painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'

### Traceback
```python-traceback
  File "C:\Users\Sreekar\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent

Traceback (most recent call last):
  File "C:\Users\Sreekar\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 213, in paintEvent
    self.code_editor.scrollflagarea_paint_event(event)
  File "C:\Users\Sreekar\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1445, in scrollflagarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\Users\Sreekar\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "C:\Users\Sreekar\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1178, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-07-30 08:25
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by ccordoba12** [comment] 2019-08-05 17:19
Closing due to lack of response.

**Closed by ccordoba12** 2019-08-05 17:19 UTC
Labels: status:Awaiting Followup

**Comment by ElMastro** [comment] 2022-01-27 23:44
Mr Cordoba, I have this same issue now, since yesterday after I upgraded python-qtconsole to 5.2.2-1 (last release). What could I provide as information?

**Comment by ccordoba12** [comment] 2022-01-28 03:17
@ElMastro, please stop using the Arch or Manjaro packages for Spyder because they are semibroken (i.e. they sort of work but have some issues because they depend on versions we don't support at moment). Besides, as I already told you, Spyder is not ready for Python 3.10, so there are some bugs that also appear due to that.

**Comment by ElMastro** [comment] 2022-01-28 15:15
I was keeping using to keep the package system's consistency. Do you believe using the version of Pypl (pip install spyder) is ok?
Il 28 gen 2022, 04:18 +0100, Carlos Cordoba ***@***.***>, ha scritto:

**Comment by ccordoba12** [comment] 2022-01-28 15:41
Yes, it is ok, but don't install it with `sudo pip`. Instead, create a pyenv for Python 3.9 first and then install Spyder there.

**Comment by ElMastro** [comment] 2022-01-30 10:39
All right, I understand. Thank you for the suggestion
Il 28 gen 2022, 16:42 +0100, Carlos Cordoba ***@***.***>, ha scritto:
