### ISSUE TITLE
 Spyder has encountered a problem

### ISSUE THREAD

**Issue by angelo1259** [spyder-ide/spyder#5838] opened 2017-11-26 18:00 UTC
## Description

**What steps will reproduce the problem?**

1. Launch Spyder
2. goto Tools/Preferences
3. 

**What is the expected output? What do you see instead?**
No access to the Preferences panel, but a Error message pops up:
 Spyder has encountered a problem
![capture](https://user-images.githubusercontent.com/34007885/33242910-0f4b6c28-d2dc-11e7-8268-1344a11b3ac5.PNG)

**Please provide any additional information below**

  File "C:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\spyder\app\mainwindow.py", line 2610, in edit_preferences
    dlg.add_page(widget)
  File "C:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\spyder\plugins\configdialog.py", line 234, in add_page
    widget.apply_button_enabled.connect(self.apply_btn.setEnabled)
AttributeError: 'NoneType' object has no attribute 'setEnabled'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-11-26 19:08
Thanks for reporting. This is a duplicate of #5649 and a known issue with Spyder 3.2.4; it is fixed in 3.2.5 which will be released something soon. In the meantime, you can run `spyder --reset` from the command line to reset Spyder's preferences which mitigates the issue, at least for the time being. As such, this issue should be closed, unless that or none of the other steps mentioned in that thread work to fix the problem. Thanks.

**Closed** 2017-11-27 01:06 UTC
