### ISSUE TITLE
[Linux] Cannot browse docs from editor

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#11054] opened 2019-12-12 17:50 UTC
**Steps to reproduce:**
* Open some file in the editor.
* Put the focus inside a function call.
* Press Ctrl + I.
```python
import numpy as np
np.arange(<focus here and press Ctrl + I>)
```

**Expected behavior:** Should show documentation for the function in the help pane.

**Actual behavior:** Help pane switches to "Editor" and says Says "No documentation available". If I switch it to "Console" and paste the exact same function name in the search bar, it will display the help for that function.

**Setup:** spyder 4.0.0, running on debian linux (KDE). Problem is not present in the windows version.

**Comment by goanpeca** [comment] 2019-12-12 18:18
Thanks for the report.

Closing as duplicate of https://github.com/spyder-ide/spyder/issues/9279

**Closed by goanpeca** 2019-12-12 18:18 UTC
