### ISSUE TITLE
Find does not open code-folded blocks

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#4709] opened 2017-07-06 12:53 UTC
This one is probably trickier.
if the target is inside a folded bloc, then searching for it does not make anything. Same with successive search.
The difficulty would be to open a folded bloc, and close it back automatically on successive F3 (expected behavior).

**Comment by ccordoba12** [comment] 2017-07-06 22:40
Are you taking about code folding?

**Comment by rlaverde** [comment] 2017-07-06 23:56
> Are you taking about code folding?

Yes, this is related to code folding

Steps to reproduce:
- Fold some code
- Search something that exist in that folded section
- The search partially works, if you unfold the section it the text is selected, but you don't see it because the block is folded.

> The difficulty would be to open a folded bloc, and close it back automatically on successive F3 (expected behavior).

I think the expected behavior is to unfold the block when searching, but not close it back.

**Comment by goanpeca** [comment] 2017-07-07 01:53
>I think the expected behavior is to unfold the block when searching, but not close it back.

I agree with this!

**Comment by sylvain-bougnoux** [comment] 2017-07-10 07:29
Actually if one make successive find (eg pressing F3) and that find steps enter a folded block, the block should obviously be opened. But if F3 is pressed one more (because this find is of no interest) then upon leaving the block, it should be folded back (because one will have to close it back manually). I was thinking of this scenario in my earlier description. 

In the meantime I've checked Visual Studio, it does not fold a block back in this scenario. IMHO it is not the best, but already better then actual situation. Thanks.

**Closed** 2017-07-11 22:53 UTC
Labels: component:Editor, type:Bug
