### ISSUE TITLE
does not type all the characters when I type fast

### ISSUE THREAD

**Issue by shamidreza** [spyder-ide/spyder#2623] opened 2015-08-17 17:58 UTC
The editor does not type all characters when I type fast. Even at a slower type rate it does not follow my characters. This "always" happens, even if the memory is empty and there is no other apps running.
OsX 10.7, Python 2.7

**Comment by ccordoba12** [comment] 2015-08-17 18:03
Closing as duplicate of issue #1508.

**Closed by ccordoba12** 2015-08-17 18:03 UTC
Labels: duplicate
