### ISSUE TITLE
Replacing string

### ISSUE THREAD

**Issue by arturomoncadatorres** [spyder-ide/spyder#8830] opened 2019-02-22 17:19 UTC
### What steps will reproduce the problem?

I have the Spyder Notebook plugin installed and was working on a notebook inside Spyder. Then, I wanted to do a string replacement (`Ctrl + R`) from `path_data` to `PATH_DATA`. When I clicked on "Replace all", I got the error.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\findreplace.py", line 533, in replace_find_all
    self.replace_find(focus_replace_text, replace_all=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\findreplace.py", line 469, in replace_find
    has_selected = self.editor.has_selected_text()
AttributeError: 'NotebookWidget' object has no attribute 'has_selected_text'
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-02-23 11:37
Thanks for reporting. This is a duplicate of issue https://github.com/spyder-ide/spyder-notebook/issues/196.

**Closed by ccordoba12** 2019-02-23 11:37 UTC
