### ISSUE TITLE
Panda DataFrame Issue

### ISSUE THREAD

**Issue by ACE0999** [spyder-ide/spyder#11792] opened 2020-03-13 18:04 UTC
### What steps will reproduce the problem?

Opening a pandas dataframe under variable explorer caused this... no code was running.
Note that this does not cause spyder to crash, just for posting to github popup to come up... closing it I can continue to work with Spyder normally...

### Traceback
```python-traceback
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 341, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Lenovo_student\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 288, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.8.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by dalthviz** [comment] 2020-03-13 18:35
Hi @ACE0999 this seems like a duplicate of #11790 
I'm closing this one in favor of #11790 but @ACE0999 could you give us an example of the data that you where trying to see? Any info to replicate this is greatly appreciated, thanks!

**Closed by dalthviz** 2020-03-13 18:35 UTC

**Comment by dalthviz** [comment] 2020-03-13 18:38
Duplicate of #11790

**Comment by ACE0999** [comment] 2020-03-13 18:39
sure, i'll try to replicate it now, with public data and i'll post it here or in #11790?

**Comment by dalthviz** [comment] 2020-03-13 18:50
Thanks @ACE0999 ! please post it in #11790
