### ISSUE TITLE
Variable Explorer is seriously affecting Spyder performance

### ISSUE THREAD

**Issue by naught101** [spyder-ide/spyder#2624] opened 2015-08-18 02:21 UTC
Currently using 3.0.0dev from git a week or so ago. Performance is really variable. Sometimes it's fine, and I don't notice anything, other times it slows down to unusable (e.g. takes 1 second to type a single character, or just freezes completely for 15 seconds). I am *not* on a slow computer (kubuntu 15.04, intel core i7 vPro, 16GB RAM, SSD for OS, normal HDD for the files I'm editing). 

I'm not sure what's causing it, but I have noticed that the warning/bug symbols next to the editor change really quickly. I guessed that might be something to do with the realtime analysis, but I turned that off, and it's still a problem. I have a couple smallish dataframes loaded (~20k rows,7 cols).

I'm more than happy to spend some time figuring out what's causing this - if you have any ideas for me to try out, let me know.

As a side-note, it'd be nice to have a "turn off real-time analysis while typing" option.

**Comment by goanpeca** [comment] 2015-08-18 02:28
@blink1073 could this be a jedi issue?

**Comment by naught101** [comment] 2015-08-18 03:06
I also tried turning off "automatic code completion", because as far as I can see it mostly happens while typing existing variable names. No change.

**Comment by ccordoba12** [comment] 2015-08-18 03:55
@goanpeca and me always use Spyder to develop Spyder, so we'd already have noticed a problem like this :-)

Maybe the problem is with the Variable Explorer (as reported in issue #2593). Please close it and try to see if that helps.

Else, please use `git bisect` to detect the problematic commit :-)

**Comment by naught101** [comment] 2015-08-18 04:14
Hrm.. So, that does seem to fix the problem, but automatic completion doesn't work without the variable explorer enabled. Removes a lot of the benefit of using spyder over vim in the first place..

Note: I already had automatic variable explorer refresh disabled.

**Comment by naught101** [comment] 2015-08-18 08:28
No, actually, I sometime even have the problem with the variable explorer closed.

**Comment by naught101** [comment] 2015-08-21 02:54
Possibly related to #2517

**Comment by ccordoba12** [comment] 2015-08-23 00:50
Closing as duplicate of issue #2593

**Closed by ccordoba12** 2015-08-23 00:50 UTC
Labels: bug, duplicate, Linux, UI
