### ISSUE TITLE
Spyder automatically reloads emptied file (assuming after a failed save?)

### ISSUE THREAD

**Issue by seberg** [spyder-ide/spyder#4437] opened 2017-05-07 13:45 UTC
Sorry, I cannot give a full reproduction. But I have had it twice happening while editing files mounted through sshfs that spyder would reload the "changed file" (it was the only program using the file (EDIT: only program writing to the file), with all content gone and no way to get back (the first time I thought I hit reload or so, and luckily could rescue the file from a running python script).

Since the file was mounted via sshfs, I assume that timeouts or similar there might have to do with it, but, not knowing the intrinsics of how this works, it does seem weird to me that this can happen, since it seems spyder unsuccessfully tried to save the file and by that emptying the original. Though I suppose it is not impossible that this is due to sshfs, I am surprised that this can occur at all, and it feels like to me like a spyder issue which is just made far more likely to occur due to the sshfs.

## Version and main components

* Ubuntu (gnome) 17.04
* Spyder Version: 3.1.3 
* Python Version: 2.7.13
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment] 2017-05-07 16:52
Thanks for reporting. This is a duplicate of issue #1104.

**Closed by ccordoba12** 2017-05-07 16:52 UTC

**Comment by seberg** [comment] 2017-05-07 16:56
Ah, sorry for missing it, thanks. I do think I get some kind of dialogue, not sure what was on it. But I am also surprised that the file is *empty*, not just that it gets reloaded. Aren't there tricks to make the saving atomic, so that it can't happen that there is an empty file on a failure?

**Comment by ccordoba12** [comment] 2017-05-07 17:09
This is a probably an issue when reading files from sshfs. Sorry for the inconvenience.

**Comment by seberg** [comment] 2017-05-07 17:11
Maybe, but its an issue when writing, not when reading, if it was during reading, the original would still be there.

**Comment by seberg** [comment] 2017-05-07 20:30
Ok, I will leave it at this. I somewhat thought editors usually do a replace/rename kind of thing, that somehow ensures that a file cannot be partially written, so that (unless sshfs is doing weird stuff) I could never end up with the empty version (maybe with a slightly earlier version OK). I am not actually sure that is true, for all I know doing this kind of atomic shuffle may bring its own problems.
