### ISSUE TITLE
unknown_thisproblem keeps coming

### ISSUE THREAD

**Issue by Aishvarya5** [spyder-ide/spyder#13520] opened 2020-08-12 05:31 UTC
### What steps will reproduce the problem?

Everyime I open Spyder, I keep getting this error. I have recently started using Spyder, so can't really understand the reason

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor.py", line 1942, in load
    finfo = self.editorstacks[0].load(filename, set_current=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/editor.py", line 2251, in load
    text, enc = encoding.read(filename)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/utils/encoding.py", line 249, in read
    text, encoding = decode( open(filename, 'rb').read() )
PermissionError: [Errno 1] Operation not permitted: '/Users/aishvarya/Documents/RA/Dream11/D11_Spyder/data_FE_percentile_CommonUsers_Paid.py'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.18.1 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.16 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by dalthviz** [comment] 2020-08-12 23:52
Hi @Aishvarya5 seems like the user that you are using to run Spyder doesn't have access to the file that you are trying to open. Checking a little bit seems like this could be a duplicate of #10406 which seems to be caused by updating of mac OS to Catalina.

This could be helpful in your case: https://www.anaconda.com/blog/how-to-restore-anaconda-after-macos-catalina-update

I'm closing this as a duplicate but let us know if the anaconda guide helps you :)

**Closed by dalthviz** 2020-08-12 23:52 UTC
Labels: resolution:Duplicate
