### ISSUE TITLE
Variables from remote kernel do not show up in Variable Explorer

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#13926] opened 2020-10-05 16:27 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I connect to a remote kernel and execute python code, my variables do not show up in the Spyder variable browser.

### What steps reproduce the problem?

1. On remote machine: run `python -m spyder_kernels.console`.

2. On local machine: use scp to copy config file `kernel-#####.json` to local home directory.
3. Run `spyder` to fire up spyder.
4. Use "Connect to an existing kernel" option to connect.
5. Type `x = 3` into remote kernel console.

### What is the expected output? What do you see instead?
I would expect to see x show up in the list of variables in the variable explorer.  Instead I see no variables in the variable explorer.  When I try the same thing with a local kernel it works just fine.

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt version: PyQt5 5.9.2
* Operating System name/version: macOS Mojave 10.14.6

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)```

**Comment by ccordoba12** [comment] 2020-10-05 16:37
Hey @selahlynch, thanks for reporting. This is a duplicate of issue #11538 and we'll try to fix it in a future version.

**Closed by ccordoba12** 2020-10-05 16:37 UTC

**Comment by selahlynch** [comment] 2020-10-05 16:50
Okay thanks.  I wasn't sure if it was a duplicate, because I can't seem to "restart" my kernel.  I'll follow up about this on #11538.

I am very eager get this issue resolved.  Please let me know if there is any way I can help.  I will attempt to step through in a Spyder development environment to see if that yields any clues.

FYI - I work on a team at the University of Pennsylvania who would like to use Spyder for analyzing healthcare data, thus we need the data to stay on a secure server.
