### ISSUE TITLE
KMeansKMeansKMeans

### ISSUE THREAD

**Issue by ramarante** [spyder-ide/spyder#19335] opened 2022-09-05 23:41 UTC
### What steps will reproduce the problem?

KMeansKMeansKMeansKMeansKMeansKMeansKMeansKMeansKMeansKMeans

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo
```

## Versions

* Spyder version: 5.3.3  (pip)
* Python version: 3.8.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.2 (OK)
keyring >=17.0.0              :  23.8.2 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  65.0.1 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
alright                       2.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.11.7
asttokens                     2.0.5
async-generator               1.10
atomicwrites                  1.4.1
attrs                         21.4.0
autopep8                      1.6.0
Babel                         2.10.3
backcall                      0.2.0
bcrypt                        3.2.2
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.6.0
bleach                        5.0.1
certifi                       2022.6.15
cffi                          1.15.1
chardet                       5.0.0
charset-normalizer            2.1.0
click                         8.1.3
cloudpickle                   2.1.0
colorama                      0.4.5
cookiecutter                  2.1.1
cryptography                  37.0.4
cycler                        0.11.0
Cython                        0.29.32
debugpy                       1.6.2
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.13
diff-match-patch              20200713
dill                          0.3.5.1
docutils                      0.19
entrypoints                   0.4
et-xmlfile                    1.1.0
excel2img                     1.4.0
executing                     0.8.3
fastjsonschema                2.15.3
flake8                        4.0.1
Flask                         2.2.2
fonttools                     4.34.4
h11                           0.13.0
h5py                          3.7.0
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.12.0
importlib-resources           5.8.0
inflection                    0.5.1
intel-openmp                  2022.1.0
intervaltree                  3.1.0
ipykernel                     6.15.1
ipympl                        0.9.1
ipython                       7.34.0
ipython-genutils              0.2.0
ipywidgets                    7.7.1
isort                         5.10.1
itsdangerous                  2.1.2
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
joblib                        1.1.0
jsonschema                    4.6.2
jupyter                       1.0.0
jupyter-client                7.3.4
jupyter-console               6.4.4
jupyter-core                  4.11.1
jupyterlab-pygments           0.2.2
jupyterlab-widgets            1.1.1
keyring                       23.8.2
kiwisolver                    1.4.3
lazy-object-proxy             1.7.1
llvmlite                      0.39.0
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.3
mccabe                        0.6.1
mistune                       0.8.4
mkl                           2022.1.0
MouseInfo                     0.1.3
mypy-extensions               0.4.3
nbclient                      0.6.6
nbconvert                     6.5.0
nbformat                      5.4.0
nest-asyncio                  1.5.5
notebook                      6.4.12
numba                         0.56.0
numpy                         1.22.4
numpydoc                      1.4.0
openpyxl                      3.0.10
outcome                       1.2.0
packaging                     21.3
pandas                        1.4.3
pandocfilters                 1.5.0
paramiko                      2.11.0
parso                         0.8.3
pathspec                      0.9.0
patsy                         0.5.2
pdf2pptx                      1.0.5
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.2.2
platformdirs                  2.5.2
plotly                        5.9.0
pluggy                        1.0.0
pmdarima                      2.0.1
prometheus-client             0.14.1
prompt-toolkit                3.0.30
psutil                        5.9.1
ptyprocess                    0.7.0
pure-eval                     0.2.2
PyAutoGUI                     0.9.53
pybrowsers                    0.5.0
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
PyGetWindow                   0.0.9
Pygments                      2.12.0
pylint                        2.14.5
pyls-spyder                   0.4.0
PyMsgBox                      1.0.9
PyMuPDF                       1.20.1
PyNaCl                        1.5.0
pyodbc                        4.0.34
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyPDF2                        2.5.0
pyperclip                     1.8.2
pypiwin32                     223
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyquaternion                  0.9.9
PyRect                        0.2.0
pyrsistent                    0.18.1
PyScreeze                     0.1.28
PySocks                       1.7.1
python-dateutil               2.8.2
python-dotenv                 0.20.0
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-pptx                   0.6.21
python-slugify                6.1.2
pytoolconfig                  1.2.2
pytweening                    1.0.4
pytz                          2022.1
pywhatkit                     5.4
pywin32                       304
pywin32-ctypes                0.2.0
pywinpty                      2.0.6
pyxlsb                        1.0.9
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.3
qstylizer                     0.2.1
QtAwesome                     1.1.1
qtconsole                     5.3.2
QtPy                          2.1.0
requests                      2.28.1
rope                          1.3.0
Rtree                         1.0.0
scikit-learn                  1.1.1
scipy                         1.8.1
seaborn                       0.11.2
selenium                      4.3.0
Send2Trash                    1.8.0
setuptools                    65.0.1
six                           1.16.0
sklearn                       0.0
sktime                        0.13.2
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.1.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
stack-data                    0.3.0
statsmodels                   0.13.2
tbb                           2021.6.0
tenacity                      8.0.1
terminado                     0.15.0
text-unidecode                1.3
textdistance                  4.3.0
threadpoolctl                 3.1.0
three-merge                   0.1.1
tinycss2                      1.1.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.4
tornado                       6.2
tqdm                          4.64.0
traitlets                     5.3.0
trio                          0.21.0
trio-websocket                0.9.2
typing_extensions             4.3.0
ujson                         5.4.0
urllib3                       1.26.10
watchdog                      2.1.9
wcwidth                       0.2.5
webdriver-manager             3.8.0
webencodings                  0.5.1
Werkzeug                      2.2.2
whatthepatch                  1.0.2
wheel                         0.37.1
widgetsnbextension            3.6.1
wikipedia                     1.4.0
wrapt                         1.14.1
wsproto                       1.1.0
xgboost                       1.6.1
xlrd                          2.0.1
XlsxWriter                    3.0.3
yapf                          0.32.0
zipp                          3.8.0

```
</details>

**Comment by ccordoba12** [comment] 2022-09-06 01:22
Closing as a duplicate of issue #19334.

**Closed by ccordoba12** 2022-09-06 01:22 UTC
