### ISSUE TITLE
Kernel not conn

### ISSUE THREAD

**Issue by XOnanoSmartfoam** [spyder-ide/spyder#16516] opened 2021-09-30 17:08 UTC
### What steps will reproduce the problem?

I tried to change the graphics to automatic instead of inline and now the kernel will not start.

**Comment by ccordoba12** [comment] 2021-10-02 03:30
Hey @XOnanoSmartfoam, thanks for reporting. I'm going to close this as a duplicate of issue #16517, which has more information about your problem.

**Closed by ccordoba12** 2021-10-02 03:30 UTC
