### ISSUE TITLE
add filter and search tool in the variable explorer

### ISSUE THREAD

**Issue by aster94** [spyder-ide/spyder#7015] opened 2018-04-24 23:33 UTC
i would like to suggest a new feature (maybe for spyder 4?)
really i am not sure if this is handled by spyder itself or by the package, in this case pandas, anyway when in the variable explorer i visualize a database I get something like this:

![screenshot 2018-04-25 01 36 42](https://user-images.githubusercontent.com/21184718/39219214-5dccf020-4829-11e8-8202-6e74534bd52a.png)

i think that the possibility to filtering the outputs in the variable explorer could be useful
an example of what i am proposing could be seen in R Studio [here under filtering and searching](https://support.rstudio.com/hc/en-us/articles/205175388-Using-the-Data-Viewer), also the advanced is interesting

this is someway related to #4067 i didn't find anything similar before posting

**Comment by CAM-Gerlach** [comment] 2018-04-25 02:31
> this is someway related to #4067 i didn't find anything similar before posting

Thanks for reporting. You are correct; this is close enough to be a duplicate of #4067 and is currently tentatively planned for Spyder 4; IIRC, there is at least a partial implementation somewhere. However, feel free to post more ideas/suggestions over in that thread; it indeed would be a quite worthwhile feature in my opinion as well.

**Closed by CAM-Gerlach** 2018-04-25 02:31 UTC
