### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by lpdsdx** [spyder-ide/spyder#7072] opened 2018-05-06 03:27 UTC
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_3965896/.spyproject/workspace.ini'

**Comment by CAM-Gerlach** [comment] 2018-05-06 19:53
Thanks for reporting. This appears to be a duplicate of #5765 . If you can provide us more information over on that thread, please do so.

**Closed** 2018-05-06 19:54 UTC
Labels: resolution:Duplicate
