### ISSUE TITLE
Issue when disabling Kite provider

### ISSUE THREAD

**Issue by fcento100** [spyder-ide/spyder#17374] opened 2022-02-20 13:21 UTC
### What steps will reproduce the problem?

The issue triggers when in Tools/Preferences "Enable Kite provider", the state of the checkbox is changed from checked to unchecked then the "Apply" button is pressed. 

If the checkbox was previously unckecked, checking then unchecking then pressing "Apply" triggers an error also.  

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/plugins/preferences/api.py", line 108, in apply_changes
    self.apply_callback()
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/plugins/preferences/api.py", line 140, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/plugins/preferences/api.py", line 168, in _apply_settings_tabs
    self.apply_settings(options)
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/api/preferences.py", line 105, in wrapper
    func(opts)
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/api/plugins/new_api.py", line 550, in apply_conf
    self.after_configuration_update(list(options_set))
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/plugins/completion/plugin.py", line 403, in after_configuration_update
    self.unregister_statusbar(provider_name)
  File "/home/fcento/.miniconda3/lib/python3.10/site-packages/spyder/plugins/completion/plugin.py", line 477, in unregister_statusbar
    if id_ in container.statusbar_widgets[id_]:
TypeError: argument of type 'KiteStatusWidget' is not iterable
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.10.2
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.16.10-arch1-1

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  21.2.1 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.3 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2022-02-20 16:00
Hey @fcento100, thanks for reporting. This is a duplicate of issue #17262 and will be fixed in our next version (5.3.0), to be released next month.

**Closed by ccordoba12** 2022-02-20 16:00 UTC
