### ISSUE TITLE
spyder has encountered a problem when launching from navigator

### ISSUE THREAD

**Issue by scifiss** [spyder-ide/spyder#5258] opened 2017-09-16 19:15 UTC
## Description

**What steps will reproduce the problem?**

1. launch anaconda navigator 1.6.2
2. launch spyder 3.2.3

**What is the expected output? What do you see instead?**
spyder is opened, but an error pops up "spyder has encountered a problem", and freezes in "connecting to kernel" forever.

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 709, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1018, in connect_client_to_kernel
    stderr_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1420, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess

**Comment by scifiss** [comment] 2017-09-16 19:16
Windows firewall is turned off.

**Comment by ccordoba12** [comment] 2017-09-16 19:18
This is a duplicate of #5257. Please post the entire error, as I told you there.

**Closed by ccordoba12** 2017-09-16 19:18 UTC

**Comment by scifiss** [comment] 2017-09-16 19:30
I did post the entire error. You said it is due to firewall, and I said you I turned off the firewall already. Since you closed my previous one, I created another one. I don't understand why you keep closing my ticket, without further discussion or explanation.
