### ISSUE TITLE
Step over/into doesn't work if code editor is undocked

### ISSUE THREAD

**Issue by bajhuman** [spyder-ide/spyder#20695] opened 2023-03-16 15:34 UTC
If the code editor pane is undocked and this window is active, pressing the key for step over / step into has no effect unless you select the main Spyder window first.

* Spyder version: 5.3.3
* Python version: 3.10.8 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10

**Comment by dalthviz** [comment] 2023-03-17 22:45
Hi @bajhuman thank you for the feedback! I think I was able to reproduce this! Could this be related to https://github.com/spyder-ide/spyder/issues/5123 basically when a pane is undocked seems like the shortcuts don't work while the undocked pane has the focus :/

As a workaround, you could instead of undocking the Editor use the `New window` option and then use the `Close` option to hide the Editor pane in the main Spyder window.

Let us know it the info above helps!

**Comment by dalthviz** [comment] 2024-12-12 00:47
Closing as a duplicate of #5123

**Closed by dalthviz** 2024-12-12 00:47 UTC
Labels: type:Bug, resolution:Duplicate, component:Editor, component:Main Window, status:Awaiting Followup
