### ISSUE TITLE
You have missing dependencies - Mandatory rtree >00.9.7: NONE (NOK)

### ISSUE THREAD

**Issue by analyticssolvers** [spyder-ide/spyder#17564] opened 2022-03-28 18:49 UTC
### What steps will reproduce the problem?

It is already installed and Spyder does not detect the installation of rtree

**Comment by dalthviz** [comment] 2022-03-30 17:56
Hi @analyticssolvers thank you for the feedback. This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/17165

We get reports of Spyder not detecting rtree being installed which usually happen due to a fault rtree installation. There is not much we can do in our side but seems like a future rtree version will fix this issue https://github.com/spyder-ide/spyder/issues/17165#issuecomment-1030087616

Let us know if the info above helps!

**Comment by dalthviz** [comment] 2022-04-21 17:40
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/17165

**Closed by dalthviz** 2022-04-21 17:40 UTC
Labels: resolution:Duplicate

**Comment by analyticssolvers** [comment] 2022-10-11 08:56
De: Daniel Althviz Moré ***@***.***> 
Enviado el: miércoles, 30 de marzo de 2022 14:57
Para: spyder-ide/spyder ***@***.***>
CC: analyticssolvers ***@***.***>; Mention ***@***.***>
Asunto: Re: [spyder-ide/spyder] You have missing dependencies - Mandatory rtree >00.9.7: NONE (NOK) (Issue #17564)

 

Hi @analyticssolvers <https://github.com/analyticssolvers>  thank you for the feedback. This seems like a duplicate of #17165 <https://github.com/spyder-ide/spyder/issues/17165> 

We get reports of Spyder not detecting rtree being installed which usually happen due to a fault rtree installation. There is not much we can do in our side but seems like a future rtree version will fix this issue #17165 (comment) <https://github.com/spyder-ide/spyder/issues/17165#issuecomment-1030087616> 

Let us know if the info above helps!
