### ISSUE TITLE
Autocomplete working in console but not in editor

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#7052] opened 2018-05-03 08:54 UTC
After activating code autocompletion in both the editor and the console, I am able to get suggestions as soon as I press tab when writing code on the console, but don't get any suggestions when writing code on the editor.

Happens with multiple spyder versions (currently using 3.2.4, but also happens with 3.2.8 and with some previous ones), installed from the latest anaconda version, an with different jedi versions.

OS: Linux (debian), using KDE

**Comment by ccordoba12** [comment] 2018-05-03 15:32
Thanks for reporting. This is a duplicate of issue #2162.

**Closed by ccordoba12** 2018-05-03 15:32 UTC
