### ISSUE TITLE
Module not building in Spyder interpreter, but fine in console

### ISSUE THREAD

**Issue by j-chacon** [spyder-ide/spyder#5582] opened 2017-10-26 16:36 UTC
Hey all

I've been trying to load a library (pygeoprocessing) in the instance of IPython in Spyder, but it keeps showing me a building error.

`
ImportError: Building module pygeoprocessing.geoprocessing_core failed: ["CompileError: command 'C:\\\\ProgramData\\\\Anaconda2\\\\Scripts\\\\gcc.bat' failed with exit status 1\n"]
`

However, when I do the same in the console, using either Python or IPython, things work just fine.

![image](https://user-images.githubusercontent.com/4971698/32064918-8b61e7e8-ba7b-11e7-8bb1-068947967c60.png)

I have checked the version of the interpreter in the preferences, and it is set to the correct version (the one I know it works).

![image](https://user-images.githubusercontent.com/4971698/32065198-4f269624-ba7c-11e7-8849-20aa9ecbc00b.png)

Is there a bug that is causing this behaviour, or is there something I am missing to do or check perhaps?

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 2.7.14 64Bits
* Qt Version: 5.6.2
* PyQt Version: 5 5.6
* Operating system: Windows 7

## Dependencies
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

Thanks for your time!

**Comment by goanpeca** [comment] 2017-10-26 17:34
@j-chacon hello :-p, try installing anaconda for current user and not all users. all users on windows has funny side effects!

**Comment by j-chacon** [comment] 2017-10-26 20:17
Sure thing

Gracias monito!

**Comment by j-chacon** [comment] 2017-10-26 22:41
I've tried to re-install the whole Anaconda for a single user, and still I keep getting the same error... I even tried to downgrade it to the previous Spyder version, but still the same outcome occurs.

Any ideas about this behaviour?

**Comment by ccordoba12** [comment] 2017-10-27 01:20
This is probably related to #5299.

**Comment by j-chacon** [comment] 2017-10-27 07:27
Indeed, there seems to be an issue with pyximport in Spyder. I've followed the recommendations in #5299 and modified the `spyder\utils\site\sitecustomize.py` commented the lines 171 to 177, adding `HAS_PYXIMPORT = False`. After this, the problem seems to be gone.

**Comment by ccordoba12** [comment] 2017-10-27 14:00
Ok, thanks for the confirmation. That means we can close this one as a duplicate of #5299.

We'll fix that problem in our 3.2.5 version.

**Closed by ccordoba12** 2017-10-27 14:00 UTC
