### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by i3creations** [spyder-ide/spyder#6723] opened 2018-03-11 17:34 UTC
### What steps will reproduce the problem?
1. Select Preferences
2. Change Syntax coloring
3. Change IPython console
4. Click "ok"

### Error messages
  File "/Users/username/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "/Users/username/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/Users/username/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/Users/username/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/Users/username/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by CAM-Gerlach** [comment] 2018-03-11 19:20
Thanks for reporting. This error is a duplicate of #6519 , which we've already fixed on our end and will be released with the next Spyder version 3.2.8, due out soon.

**Closed by CAM-Gerlach** 2018-03-11 19:20 UTC
