### ISSUE TITLE
Problem with Saving a File

### ISSUE THREAD

**Issue by mfizyczka** [spyder-ide/spyder#5282] opened 2017-09-19 18:09 UTC
## I have two problems with saving a file in Windows 10 (64bit). I'm using Anaconda and Spyder 3.2.3.

1. I create a file (with new button) and save it to My Documents. When I click open in Spyder it sees the file but I cannot see the file in My Documents (in Windows explorer)

2. I open a file from a USB stick and make some change in it. Afterwards I try to save it and I have a "Permission denied message". Still I can open the same file in a Notepad and made changes and save them.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6
* Operating system: Windows 10

## Dependencies
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-09-19 22:34
We can't do anything about point 1.

@dalthviz, please take a look at point 2.

**Comment by dalthviz** [comment] 2017-09-23 23:04
@ccordoba12 I tested saving a file in a USB but it works, no message appears.

**Comment by ccordoba12** [comment] 2017-09-24 21:02
@mfizyczka, are you using WinPython or Anaconda?

**Comment by ccordoba12** [comment] 2017-09-28 15:14
Closing because we can't reproduce this problem.

**Closed by ccordoba12** 2017-09-28 15:14 UTC

**Comment by mfizyczka** [comment] 2017-09-28 16:00
Sorry, I didn’t see that mail. I’m using Anaconda. I think that the problem
might be connected with my Firewall. I uninstalled it and than reinstalled
the Anaconda and it helped.

W dniu niedziela, 24 września 2017 Carlos Cordoba <notifications@github.com>
napisał(a):

**Comment by ccordoba12** [comment] 2017-09-28 16:52
Great, thanks for letting us know about it!
