### ISSUE TITLE
Preference error message

### ISSUE THREAD

**Issue by cocoaaa** [spyder-ide/spyder#6659] opened 2018-03-07 18:28 UTC
On Preference -> Syntax coloring, I change the "Scheme" and click Apply.
The changes are applied, but when I click close, the popup window with "Spyder has encountered an internal problem" opens and I get the following errors.

In fact, this doesn't seem to be limited to Syntax coloring -- it happens every time I click on ''close" in other sections in Preference.
### Paste Traceback/Error Below (if applicable)

```python-traceback
  File "/Users/hjsong/anaconda3/envs/py36/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 214, in accept
    configpage.apply_changes()
  File "/Users/hjsong/anaconda3/envs/py36/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/Users/hjsong/anaconda3/envs/py36/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/Users/hjsong/anaconda3/envs/py36/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/Users/hjsong/anaconda3/envs/py36/lib/python3.6/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
```

## Package Versions

* Spyder: 3.2.7
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6.0
* Operating System: MacOS Siera 10.13.3

**Comment by ccordoba12** [comment] 2018-03-07 18:36
Thanks for reporting. This is a duplicate of #6519 and it'll be fixed in our next release.

**Closed by ccordoba12** 2018-03-07 18:36 UTC
