### ISSUE TITLE
Completion and linting in the editor for Python files will not work during current session, or stopped working.

### ISSUE THREAD

**Issue by joseavegaa** [spyder-ide/spyder#13457] opened 2020-08-02 20:27 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After a few seconds of opening Spyder, I get the message in the title of the issue. LSP Python is down. Linting and completion work for a few seconds when opening Spyder, then stopped and the pop up shows again. Same problem as the one describe on #11026. As requested there, I'm opening a new issue. 

### Steps taken that didn't help the issue

- Running `conda update -all`
- Reinstalled Anaconda.
- Running `spyder --reset`
- Unable to reproduce issue on Windows.  

### What steps reproduce the problem?

1. Open Spyder. 
2. Wait a few seconds.
3. The pop-up shows again.

## Versions

* Spyder version: 4.1.4
* Python version: 3.7.7
* Operating System name/version: macOS 10.15.6

## Screenshots
<img width="414" alt="Screenshot 2020-08-02 at 02 22 25 pm" src="https://user-images.githubusercontent.com/26339558/89131645-97e46a00-d4cb-11ea-8c69-e9f774f7c4cd.png">

<img width="154" alt="Screenshot 2020-08-02 at 02 22 41 pm" src="https://user-images.githubusercontent.com/26339558/89131649-a2066880-d4cb-11ea-881c-bbf5bcf421a2.png">

**Comment by steff456** [comment] 2020-08-04 19:35
Hi @joseavegaa,
Can you please create a new conda environment and run spyder from there? Maybe the `conda update -all` damaged something in your environment. 

```
conda create -n test-env python=3.7
conda activate test-env
conda install spyder=4.1.4
```

Please let me know if that works

**Comment by algent-al** [comment] 2020-08-04 22:17
I have this exact issue in Solus. Just updated to version 4.1.4. Using python version 3.7.7.

**Comment by mmfink** [comment] 2020-08-05 18:03
Hello @steff456 
I also have this issue on Windows 10 using spyder 4.1.4 and python 3.7.7

I followed your test-env suggestion and I can confirm that LSP Python works in spyder in the test-env. Of the common packages between the test-env and the environment where it doesn't work, these are the package version differences:

  | test-env | not working env
-- | -- | --
astroid | 2.4.2 | 2.3.3
lazy-object-proxy | 1.4.3 | 1.5.0
pylint | 2.5.3 | 2.4.4
wrapt | 1.11.2 | 1.12.1

I force installed pylint=2.5.3 in the not working env:
```
>conda install pylint=2.5.3

## Package Plan ##

  added / updated specs:
    - pylint=2.5.3

The following packages will be UPDATED:

  astroid                                      2.3.3-py37_0 --> 2.4.2-py37_0
  pylint                                       2.4.4-py37_0 --> 2.5.3-py37_0

The following packages will be DOWNGRADED:

  lazy-object-proxy                    1.5.0-py37he774522_0 --> 1.4.3-py37he774522_0
  wrapt                               1.12.1-py37he774522_1 --> 1.11.2-py37he774522_0
```

...which takes care of all the version discrepancies. Unfortunately, that didn't make any difference in the error when opening spyder.

Any further suggestions on how to troubleshoot this? While I can run spyder from the test-env, I'd rather run it from the other env where the other packages I need are.

**Comment by steff456** [comment] 2020-08-05 18:06
@mmfink, can you please put in here the `conda list` result in the not working environment?

**Comment by mmfink** [comment] 2020-08-05 19:01
@steff456 - its rather long:
Name | Version | Build Channel
-- | -- | --
_anaconda_depends | 2020.07 | py37_0
_ipyw_jlab_nb_ext_conf | 0.1.0 | py37_0
alabaster | 0.7.12 | py37_0
anaconda | custom | py37_1
anaconda-client | 1.7.2 | py37_0
anaconda-navigator | 1.9.12 | py37_0
anaconda-project | 0.8.4 | py_0
argh | 0.26.2 | py37_0
asn1crypto | 1.3.0 | py37_1
astroid | 2.4.2 | py37_0
astropy | 4.0.1.post1 | py37he774522_1
atomicwrites | 1.4.0 | py_0
attrs | 19.3.0 | py_0
autopep8 | 1.5.3 | py_0
babel | 2.8.0 | py_0
backcall | 0.2.0 | py_0
backports | 1 | py_2
backports.functools_lru_cache | 1.6.1 | py_0
backports.shutil_get_terminal_size | 1.0.0 | py37_2
backports.tempfile | 1 | py_1
backports.weakref | 1.0.post1 | py_1
bcrypt | 3.1.7 | py37he774522_1
beautifulsoup4 | 4.9.1 | py37_0
bitarray | 1.4.2 | py37he774522_0
bkcharts | 0.2 | py37_0
blas | 1 | mkl
bleach | 3.1.5 | py_0
blosc | 1.19.0 | h7bd577a_0
bokeh | 2.1.1 | py37_0
boto | 2.49.0 | py37_0
bottleneck | 1.3.2 | py37h2a96729_1
brotlipy | 0.7.0 | py37he774522_1000
bzip2 | 1.0.8 | he774522_0
ca-certificates | 2020.6.24 | 0
certifi | 2020.6.20 | py37_0
cffi | 1.14.0 | py37h7a1dbc1_0
cftime | 1.2.1 | py37h2a96729_0
chardet | 3.0.4 | py37_1003
click | 7.1.2 | py_0
cloudpickle | 1.5.0 | py_0
clyent | 1.2.2 | py37_1
colorama | 0.4.3 | py_0
comtypes | 1.1.7 | py37_1001
conda | 4.8.3 | py37_0
conda-build | 3.18.11 | py37_0
conda-env | 2.6.0 | 1
conda-package-handling | 1.6.1 | py37h62dcd97_0
conda-verify | 3.4.2 | py_1
console_shortcut | 0.1.1 | 4
contextlib2 | 0.6.0.post1 | py_0
cryptography | 2.9.2 | py37h7a1dbc1_0
curl | 7.67.0 | h2a8f88b_0
cycler | 0.10.0 | py37_0
cython | 0.29.21 | py37ha925a31_0
cytoolz | 0.10.1 | py37he774522_0
dask | 2.20.0 | py_0
dask-core | 2.20.0 | py_0
decorator | 4.4.2 | py_0
defusedxml | 0.6.0 | py_0
diff-match-patch | 20200713 | py_0
distributed | 2.20.0 | py37_0
docutils | 0.16 | py37_1
entrypoints | 0.3 | py37_0
et_xmlfile | 1.0.1 | py_1001
expat | 2.2.9 | h33f27b4_2
fastcache | 1.1.0 | py37he774522_0
filelock | 3.0.12 | py_0
flake8 | 3.8.3 | py_0
flask | 1.1.2 | py_0
freetype | 2.10.2 | hd328e21_0
freexl | 1.0.5 | hfa6e2cd_0
fsspec | 0.7.4 | py_0
future | 0.18.2 | py37_1
gdal | 2.3.3 | py37hdf43c64_0
geos | 3.7.1 | h33f27b4_0
get_terminal_size | 1.0.0 | h38e98db_0
gevent | 20.6.2 | py37he774522_0
glob2 | 0.7 | py_0
gmpy2 | 2.0.8 | py37h0964b28_3
greenlet | 0.4.16 | py37he774522_0
h5py | 2.10.0 | py37h5e291fa_0
hdf4 | 4.2.13 | h712560f_2
hdf5 | 1.10.4 | h7ebc959_0
heapdict | 1.0.1 | py_0
html5lib | 1.1 | py_0
icc_rt | 2019.0.0 | h0cc432a_1
icu | 58.2 | ha925a31_3
idna | 2.1 | py_0
imageio | 2.9.0 | py_0
imagesize | 1.2.0 | py_0
importlib-metadata | 1.7.0 | py37_0
importlib_metadata | 1.7.0 | 0
intel-openmp | 2020.1 | 216
intervaltree | 3.0.2 | py_1
ipykernel | 5.3.4 | py37h5ca1d4c_0
ipython | 7.16.1 | py37h5ca1d4c_0
ipython_genutils | 0.2.0 | py37_0
ipywidgets | 7.5.1 | py_0
isort | 4.3.21 | py37_0
itsdangerous | 1.1.0 | py37_0
jdcal | 1.4.1 | py_0
jedi | 0.17.1 | py37_0
jinja2 | 2.11.2 | py_0
joblib | 0.16.0 | py_0
jpeg | 9b | hb83a4c4_2
json5 | 0.9.5 | py_0
jsonschema | 3.2.0 | py37_1
jupyter | 1.0.0 | py37_7
jupyter_client | 6.1.6 | py_0
jupyter_console | 6.1.0 | py_0
jupyter_core | 4.6.3 | py37_0
jupyterlab | 2.1.5 | py_0
jupyterlab_server | 1.2.0 | py_0
kealib | 1.4.12 | h07cbb95_0
keyring | 21.2.1 | py37_0
kiwisolver | 1.2.0 | py37h74a9793_0
krb5 | 1.16.4 | hc04afaa_0
lazy-object-proxy | 1.4.3 | py37he774522_0
libarchive | 3.4.2 | h5e25573_0
libboost | 1.67.0 | hd9e427e_4
libcurl | 7.67.0 | h2a8f88b_0
libgdal | 2.3.3 | h10f50ba_0
libiconv | 1.15 | h1df5818_7
libkml | 1.3.0 | he5f2a48_4
liblief | 0.10.1 | ha925a31_0
libllvm9 | 9.0.1 | h21ff451_0
libnetcdf | 4.6.1 | h411e497_2
libpng | 1.6.37 | h2a8f88b_0
libpq | 11.2 | h3235a2c_0
libsodium | 1.0.18 | h62dcd97_0
libspatialindex | 1.9.3 | h33f27b4_0
libspatialite | 4.3.0a | hc36aec2_19
libssh2 | 1.9.0 | h7a1dbc1_1
libtiff | 4.1.0 | h56a325e_1
libxml2 | 2.9.10 | h464c3ec_1
libxslt | 1.1.34 | he774522_0
llvmlite | 0.33.0 | py37ha925a31_0
locket | 0.2.0 | py37_1
lxml | 4.5.2 | py37h1350720_0
lz4-c | 1.9.2 | h62dcd97_1
lzo | 2.1 | he774522_2
m2w64-gcc-libgfortran | 5.3.0 | 6
m2w64-gcc-libs | 5.3.0 | 7
m2w64-gcc-libs-core | 5.3.0 | 7
m2w64-gmp | 6.1.0 | 2
m2w64-libwinpthread-git | 5.0.0.4634.697f757 | 2
markupsafe | 1.1.1 | py37hfa6e2cd_1
matplotlib | 3.2.2 | 0
matplotlib-base | 3.2.2 | py37h64f37c6_0
mccabe | 0.6.1 | py37_1
menuinst | 1.4.16 | py37he774522_1
mistune | 0.8.4 | py37hfa6e2cd_1001
mkl | 2020.1 | 216
mkl-service | 2.3.0 | py37hb782905_0
mkl_fft | 1.1.0 | py37h45dec08_0
mkl_random | 1.1.1 | py37h47e9c7a_0
mock | 4.0.2 | py_0
more-itertools | 8.4.0 | py_0
mpc | 1.1.0 | h7edee0f_1
mpfr | 4.0.2 | h62dcd97_1
mpir | 3.0.0 | hec2e145_1
mpmath | 1.1.0 | py37_0
msgpack-python | 1.0.0 | py37h74a9793_1
msys2-conda-epoch | 20160418 | 1
multipledispatch | 0.6.0 | py37_0
navigator-updater | 0.2.1 | py37_0
nbconvert | 5.6.1 | py37_1
nbformat | 5.0.7 | py_0
netcdf4 | 1.4.2 | py37h812ae01_0
networkx | 2.4 | py_1
nltk | 3.5 | py_0
nose | 1.3.7 | py37_1004
notebook | 6.0.3 | py37_0
numba | 0.50.1 | py37h47e9c7a_0
numexpr | 2.7.1 | py37h25d0782_0
numpy | 1.19.1 | py37h5510c5b_0
numpy-base | 1.19.1 | py37ha3acd2a_0
numpydoc | 1.1.0 | py_0
olefile | 0.46 | py37_0
openpyxl | 3.0.4 | py_0
openssl | 1.1.1g | he774522_0
packaging | 20.4 | py_0
pandas | 1.0.5 | py37h47e9c7a_0
pandoc | 2.1 | 0
pandocfilters | 1.4.2 | py37_1
paramiko | 2.7.1 | py_0
parso | 0.7.0 | py_0
partd | 1.1.0 | py_0
path | 14.0.1 | py37_0
path.py | 12.0.2 | py_0
pathlib2 | 2.3.5 | py37_1
pathtools | 0.1.2 | py_1
patsy | 0.5.1 | py37_0
pcre | 8.44 | ha925a31_0
pep8 | 1.7.1 | py37_0
pexpect | 4.8.0 | py37_1
pickleshare | 0.7.5 | py37_1001
pillow | 7.2.0 | py37hcc1f983_0
pip | 20.1.1 | py37_1
pkginfo | 1.5.0.1 | py37_0
pluggy | 0.13.1 | py37_0
ply | 3.11 | py37_0
powershell_shortcut | 0.0.1 | 3
proj4 | 5.2.0 | ha925a31_1
prometheus_client | 0.8.0 | py_0
prompt-toolkit | 3.0.5 | py_0
prompt_toolkit | 3.0.5 | 0
psutil | 5.7.0 | py37he774522_0
py | 1.9.0 | py_0
py-lief | 0.10.1 | py37ha925a31_0
pycodestyle | 2.6.0 | py_0
pycosat | 0.6.3 | py37he774522_0
pycparser | 2.2 | py_2
pycrypto | 2.6.1 | py37he774522_10
pycurl | 7.43.0.5 | py37h7a1dbc1_0
pydocstyle | 5.0.2 | py_0
pyflakes | 2.2.0 | py_0
pygments | 2.6.1 | py_0
pylint | 2.5.3 | py37_0
pynacl | 1.4.0 | py37h62dcd97_1
pyodbc | 4.0.30 | py37ha925a31_0
pyopenssl | 19.1.0 | py_1
pyparsing | 2.4.7 | py_0
pyqt | 5.9.2 | py37h6538335_2
pyreadline | 2.1 | py37_1
pyrsistent | 0.16.0 | py37he774522_0
pysocks | 1.7.1 | py37_1
pytables | 3.6.1 | py37h1da0976_0
pytest | 5.4.3 | py37_0
python | 3.7.7 | h81c818b_4
python-dateutil | 2.8.1 | py_0
python-jsonrpc-server | 0.3.4 | py_1
python-language-server | 0.34.1 | py37_0
python-libarchive-c | 2.9 | py_0
pytz | 2020.1 | py_0
pywavelets | 1.1.1 | py37he774522_0
pywin32 | 227 | py37he774522_1
pywin32-ctypes | 0.2.0 | py37_1001
pywinpty | 0.5.7 | py37_0
pyyaml | 5.3.1 | py37he774522_1
pyzmq | 19.0.1 | py37ha925a31_1
qdarkstyle | 2.8.1 | py_0
qt | 5.9.7 | vc14h73c81de_0
qtawesome | 0.7.2 | py_0
qtconsole | 4.7.5 | py_0
qtpy | 1.9.0 | py_0
regex | 2020.6.8 | py37he774522_0
requests | 2.24.0 | py_0
rope | 0.17.0 | py_0
rtree | 0.9.4 | py37h21ff451_1
ruamel_yaml | 0.15.87 | py37he774522_1
scikit-image | 0.16.2 | py37h47e9c7a_0
scikit-learn | 0.23.1 | py37h25d0782_0
scipy | 1.5.0 | py37h9439919_0
seaborn | 0.10.1 | py_0
send2trash | 1.5.0 | py37_0
setuptools | 49.2.0 | py37_0
simplegeneric | 0.8.1 | py37_2
singledispatch | 3.4.0.3 | py37_0
sip | 4.19.8 | py37h6538335_0
six | 1.15.0 | py_0
snappy | 1.1.8 | h33f27b4_0
snowballstemmer | 2.0.0 | py_0
sortedcollections | 1.2.1 | py_0
sortedcontainers | 2.2.2 | py_0
soupsieve | 2.0.1 | py_0
sphinx | 3.1.2 | py_0
sphinxcontrib | 1 | py37_1
sphinxcontrib-applehelp | 1.0.2 | py_0
sphinxcontrib-devhelp | 1.0.2 | py_0
sphinxcontrib-htmlhelp | 1.0.3 | py_0
sphinxcontrib-jsmath | 1.0.1 | py_0
sphinxcontrib-qthelp | 1.0.3 | py_0
sphinxcontrib-serializinghtml | 1.1.4 | py_0
sphinxcontrib-websupport | 1.2.3 | py_0
spyder | 4.1.4 | py37_0
spyder-kernels | 1.9.2 | py37_0
sqlalchemy | 1.3.18 | py37he774522_0
sqlite | 3.32.3 | h2a8f88b_0
statsmodels | 0.11.1 | py37he774522_0
sympy | 1.6.1 | py37_0
tbb | 2020 | h74a9793_0
tblib | 1.6.0 | py_0
terminado | 0.8.3 | py37_0
testpath | 0.4.4 | py_0
threadpoolctl | 2.1.0 | pyh5ca1d4c_0
tk | 8.6.10 | he774522_0
toml | 0.10.1 | py_0
toolz | 0.10.0 | py_0
tornado | 6.0.4 | py37he774522_1
tqdm | 4.47.0 | py_0
traitlets | 4.3.3 | py37_0
typed-ast | 1.4.1 | py37he774522_0
typing_extensions | 3.7.4.2 | py_0
ujson | 1.35 | py37hfa6e2cd_0
unicodecsv | 0.14.1 | py37_0
urllib3 | 1.25.9 | py_0
vc | 14.1 | h0510ff6_4
vs2015_runtime | 14.16.27012 | hf0eaf9b_3
watchdog | 0.10.3 | py37_0
wcwidth | 0.2.5 | py_0
webencodings | 0.5.1 | py37_1
werkzeug | 1.0.1 | py_0
wheel | 0.34.2 | py37_0
widgetsnbextension | 3.5.1 | py37_0
win_inet_pton | 1.1.0 | py37_0
win_unicode_console | 0.5 | py37_0
wincertstore | 0.2 | py37_0
winpty | 0.4.3 | 4
wrapt | 1.11.2 | py37he774522_0
xerces-c | 3.2.2 | ha925a31_0
xlrd | 1.2.0 | py37_0
xlsxwriter | 1.2.9 | py_0
xlwings | 0.19.5 | py37_0
xlwt | 1.3.0 | py37_0
xmltodict | 0.12.0 | py_0
xz | 5.2.5 | h62dcd97_0
yaml | 0.2.5 | he774522_0
yapf | 0.30.0 | py_0
zeromq | 4.3.2 | ha925a31_2
zict | 2.0.0 | py_0
zipp | 3.1.0 | py_0
zlib | 1.2.11 | h62dcd97_4
zope | 1 | py37_1
zope.event | 4.4 | py37_0
zope.interface | 4.7.1 | py37he774522_0
zstd | 1.4.5 | h04227a9_0

**Comment by steff456** [comment] 2020-08-06 17:28
Hi @mmfink, can you do me another favor? Please start spyder in debug mode with `spyder --debug-info verbose` and in the main menu go to `Tools>LSP` and upload the logs under that option here

**Comment by mmfink** [comment] 2020-08-06 17:52
Here you go, @steff456 
This is the text of the **server_python.log** file. The file clears all contents as soon as the error dialog asking if you want to restart appears, so I would only be uploading empty files to you. At least I get a few seconds to copy/paste the contents. :-) 

Nothing appears in the **transport_python.log**

```
Traceback (most recent call last):
  File "C:\Python3\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python3\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\anaconda3\lib\site-packages\pyls\__main__.py", line 12, in <module>
    from .python_ls import (PythonLanguageServer, start_io_lang_server,
  File "C:\Python3\anaconda3\lib\site-packages\pyls\python_ls.py", line 12, in <module>
    from . import lsp, _utils, uris
  File "C:\Python3\anaconda3\lib\site-packages\pyls\_utils.py", line 9, in <module>
    import jedi
  File "C:\Python3\anaconda3\lib\site-packages\jedi\__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "C:\Python3\anaconda3\lib\site-packages\jedi\api\__init__.py", line 24, in <module>
    from jedi.api import classes
  File "C:\Python3\anaconda3\lib\site-packages\jedi\api\classes.py", line 24, in <module>
    from jedi.inference.utils import unite
  File "C:\Python3\anaconda3\lib\site-packages\jedi\inference\__init__.py", line 70, in <module>
    from jedi.inference import imports
  File "C:\Python3\anaconda3\lib\site-packages\jedi\inference\imports.py", line 24, in <module>
    from jedi.inference import sys_path
  File "C:\Python3\anaconda3\lib\site-packages\jedi\inference\sys_path.py", line 8, in <module>
    from jedi.common import traverse_parents
ImportError: bad magic number in 'jedi.common': b'\x03\xf3\r\n'
```

Also, these lines appear every second or so in the Anaconda console:
```
2020-08-06 11:46:52,738 [DEBUG] [spyder.plugins.completion.languageserver.client] -> LSP server for python is down!!
2020-08-06 11:46:52,738 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Transport layer for python is down!!
```

**Comment by steff456** [comment] 2020-08-06 18:44
It seems that there's a problem in the environment, so to fix it please go to `User\Anaconda\envs\not-working-env\Lib\site-packages` inside that folder please run in cmd `DEL /Q /F /S "*.pyc"`
After that the LSP should be working fine, please let me know if this fixes the issue

**Comment by mmfink** [comment] 2020-08-06 18:58
Yes! Working now. Thanks so much!

**Comment by steff456** [comment] 2020-08-06 19:09
@algent-al as you are working in Linux please go to the site-packages `~/anaconda3/envs/not-working-env/lib/python3.7/site-packages` and inside the folder run `find . -name \*.pyc -delete`
That will also fix your environment :)

**Comment by algent-al** [comment] 2020-08-06 19:31
Hi @steff456 I have updated spyder using Solus build tools and not by using environments and i have installed it system wide. I don't have anaconda folder. Just need to mention that I am not a spyder3 user, just trying this for curiosity.

**Comment by steff456** [comment] 2020-08-06 21:27
@algent-al we recommend using anaconda for Spyder, if you are new to python I will highly recommend to you to start using conda as manager even if you are only using it for curiosity :)

**Comment by joseavegaa** [comment] 2020-08-07 16:45
Hello @steff456. 

I have run the command `find ~/anaconda3/envs/not-working-env/lib/python3.7/site-packages -name "*.pyc" -delete`, restarted Spyder, and still getting the error. 

Following that, I have started Spyder with `spyder --debug-info verbose` and got the same output as @mmfink from `server_python.log`, but the last line is this one instead:

`ImportError: cannot import name 'traverse_parents' from 'jedi.common' (/opt/anaconda3/lib/python3.7/site-packages/jedi/common/__init__.py)`

**Comment by steff456** [comment] 2020-08-07 17:15
Hi @joseavegaa,
That sounds like a nice idea, please let me know if reinstalling Anaconda your problem is fixed

**Comment by joseavegaa** [comment] 2020-08-07 18:51
@steff456 seems that the problem was resolved by a clean installation. Thanks.

**Comment by ccordoba12** [comment] 2020-08-09 20:36
Closing this one because all people involved were able to solve their problems.

**Closed by ccordoba12** 2020-08-09 20:36 UTC
Labels: status:Awaiting Followup

**Comment by algent-al** [comment] 2020-08-11 20:19
@steff456 Solved this issue for Solus, with this spyder installed system wide.
I had some missing dependencies like:
- python-language-server
- python-jsonrpc-server
- python-ujson

spyder didn't report in "Help > Dependecies" that pyls (python-language-server) was missing.

**Comment by steff456** [comment] 2020-08-11 20:26
@algent-al thanks for the follow-up response, we will be adding these dependencies into the report dialog so it will be easier for us to see installation problems related to the PyLS. I'm glad that you could solve your Spyder :)
