### ISSUE TITLE
Uninformative display string for E128 

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10069] opened 2019-08-23 19:27 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If code style linting is enable, the editor displays a tooltip describing errors when you hover the cursor over the orange triangle in the margin. For example you might see

    pycodestyle [W504]: W504 line break after binary operator

If you trigger E128 the error message is uninformative. It reads something like:

    pycodestyle [E128]: E128 6

In other words, there is no textual description of what E128 means. I believe this worked in Spyder 3.x, but don't have it installed to check. 

As an aside, displaying the error/warning number both in and outside the brackets seems redundant, but perhaps you don't have control over that, or there are cases where they might be different?

### What steps reproduce the problem?
E128 is for continuation line under-indented, so put the following in an edit window:

    print(3 + 
       4)

in the editor. 

### What is the expected output? What do you see instead?

Something similar to 

    pycodestyle [E128]: E128 continuation line under-indented for visual indent

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.0b2
* Python version: 3.7.3 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.1.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.12 (OK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.6.1 (OK)
matplotlib >=2.0.0 :  3.1.0 (OK)
pylint >=0.25      :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment] 2019-08-24 08:40
Thanks for reporting. This is not something we can solve here though.

This is basically a duplicate of [this issue](https://github.com/palantir/python-language-server/issues/342) in our dependency that handles linting and code completion in the editor.

**Closed by ccordoba12** 2019-08-24 08:40 UTC

**Comment by ccordoba12** [comment] 2019-08-24 08:41
> As an aside, displaying the error/warning number both in and outside the brackets seems redundant, but perhaps you don't have control over that, or there are cases where they might be different?

This is fixed in beta4, please update.
