### ISSUE TITLE
Traceback on Spyder launch when auto-opens previous project

### ISSUE THREAD

**Issue by Keou0007** [spyder-ide/spyder#9557] opened 2019-06-12 02:51 UTC
### What steps will reproduce the problem?

Close spyder, saving all currently open files in current project.
Open spyder
Traceback!

### Traceback
```python-traceback
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/lsp/client.py", line 259, in on_msg_received
    handler(resp['params'])
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/lsp/client.py", line 320, in process_server_capabilities
    if isinstance(server_capabilites['textDocumentSync'], int):
KeyError: 'textDocumentSync'
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 2.6.32-754.14.2.el6.x86_64

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.1.0 (OK)
psutil >=0.3       :  5.6.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.10 (OK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.0 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-16 17:51
I can't reproduce this after PR #9482, so I'm going to close it for now.

@Keou0007, please test things after we release beta3 (on June 26 or 27) to see if that's the case for you too.

**Closed by ccordoba12** 2019-06-16 17:51 UTC
Labels: component:Code Completion, type:Bug

**Comment by Keou0007** [comment] 2019-06-17 01:25
Will do

**Comment by Keou0007** [comment] 2019-07-04 07:12
I just installed beta3 on my linux machine and got this traceback on launch again. It seems sporadic now though, I've opened spyder 3 or 4 times today and gotten the traceback once.
