### ISSUE TITLE
os.system not opening DOS CMD console

### ISSUE THREAD

**Issue by mikeiz** [spyder-ide/spyder#13289] opened 2020-07-14 16:42 UTC
### What steps will reproduce the problem?

Before I  upgraded to 4.x this command would open a DOS command widnow and execute cmd. Now it executes and no window opens. 
os.system(cmd)

## Versions

* Spyder version: 4.1.3 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```

**Comment by steff456** [comment] 2020-07-14 19:13
Hi @mikeiz,

You can go to `Tools > Preferences > IPython Console > Advanced settings > Windows` and deactivate the option `Hide command line output windows generated by the subprocess module`. Please let me know if that works for you

**Comment by steff456** [comment] 2020-07-21 17:08
I'm closing this issue because there was no follow up response after a week.

**Closed by steff456** 2020-07-21 17:08 UTC
Labels: status:Awaiting Followup

**Comment by kbauer** [comment] 2021-02-18 20:51
I can reproduce the issue. With `Hide command line output windows generated by the subprocess module` unchecked, `os.system` and `subprocess.call` produce no command window.

Possibly related to https://github.com/spyder-ide/spyder/issues/14783, i.e. the output is sent to the console, from which Spyder was started.
