### ISSUE TITLE
spyder is not showing tensorflow log information in ipython console

### ISSUE THREAD

**Issue by jontis** [spyder-ide/spyder#5287] opened 2017-09-20 08:57 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. run simple tensorflow script with logging in spyder
2. 
3. 

**What is the expected output? What do you see instead?**
full output is desired, minimal output is received

**Please provide any additional information below**
# running this program (on tensorflow-gpu ):
import tensorflow as tf
import numpy as np
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

# In a normal ipython, this outputs:
...alot...
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0
2017-09-20 10:52:19.124843: I tensorflow/core/common_runtime/direct_session.cc:300] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0

MatMul: (MatMul): /job:localhost/replica:0/task:0/gpu:0
2017-09-20 10:52:19.129557: I tensorflow/core/common_runtime/simple_placer.cc:872] MatMul: (MatMul)/job:localhost/replica:0/task:0/gpu:0
b: (Const): /job:localhost/replica:0/task:0/gpu:0
2017-09-20 10:52:19.129585: I tensorflow/core/common_runtime/simple_placer.cc:872] b: (Const)/job:localhost/replica:0/task:0/gpu:0
a: (Const): /job:localhost/replica:0/task:0/gpu:0
2017-09-20 10:52:19.129603: I tensorflow/core/common_runtime/simple_placer.cc:872] a: (Const)/job:localhost/replica:0/task:0/gpu:0
[[ 22.  28.]
 [ 49.  64.]]

# In spyder, I see only this:
[[ 22.  28.]
 [ 49.  64.]]

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system: mint 18.1

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment] 2017-09-20 13:02
Thanks for reporting. This is a duplicate of issue #3777.

**Closed by ccordoba12** 2017-09-20 13:02 UTC
