### ISSUE TITLE
Code Outline not showing classes, methods in *some* file (Spyder 5.3.1 Anaconda)

### ISSUE THREAD

**Issue by cg-mayrhofer** [spyder-ide/spyder#18712] opened 2022-07-18 09:44 UTC
### Issue Report Checklist

* [yes] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [yes] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [yes] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [yes] Restarted Spyder
    * [yes] Reset preferences with ``spyder --reset``
    * [yes] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [yes] Tried the other applicable steps from the Troubleshooting Guide

## Problem Description

I find the code outline does not contain the class / methods / variables for **some** files. Some other files work. 
Let me give you an example: 
The files in the screenshot dumatherm.py and helpers.py are both located in the same directory. Both files contain sections (which are shown in the code outline) and of course methods or classes (which are only shown in helpers.py. 
Even if I delete all content in the dumatherm.py file and add some new code like a method, the code outline does not display the methods. 

![grafik](https://user-images.githubusercontent.com/77964479/179482846-ea507c5e-47cd-45fb-8cf1-5e9d16458517.png)

I have not really found an issue that is similar because in my case the difference is:
- for some files code outline works as expected, for others not
- I *can* use the *go to definition* in all files
- I am on Spyder 5, most issues I found were for Spyder 4

### What steps reproduce the problem?

1. load an existing spyder project 
2. Code outline behaves like described

## Versions

* Spyder version: 5.3.1
* Python version: 3.9.7
* Qt version: 5.15.4
* PyQt version: 5.15.7
* Operating System name/version: win 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.4.4 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.8.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.1.10 (OK)
qtawesome >=1.0.2                    :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  61.2.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  None (NOK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  None (NOK)
scipy >=0.17.0                       :  1.7.3 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_unittest.unittestplugin 0.5.0 :  0.5.0 (OK)

```

**Comment by ccordoba12** [comment] 2022-07-20 14:53
Hey @cg-mayrhofer, thanks for reporting. This is a duplicate of issue #16406 and we'll try to fix it in our next version (5.3.3) to be released at the end of August.

**Closed by ccordoba12** 2022-07-20 14:53 UTC
