### ISSUE TITLE
ipdb pushing me to console rather than iPython console

### ISSUE THREAD

**Issue by ganong123** [spyder-ide/spyder#3334] opened 2016-07-29 14:56 UTC
## Description of your problem

**What steps will reproduce the problem?**
1. I open an iPython console like this
[iPython_console_screenshot.pdf](https://github.com/spyder-ide/spyder/files/390772/iPython_console_screenshot.pdf)
2. I set a few breakpoints in the editor and start the debugger

**What is the expected output? What do you see instead?**
I'd like to use the debugger in the iPython console. Instead, I'm ending up in the regular console.

[python_console_screenshot.pdf](https://github.com/spyder-ide/spyder/files/390774/python_console_screenshot.pdf)
## Versions and main components
- Spyder Version: 2.3.8
- Python Version: 2.7.11 
- Operating system: El Capitan 10.11.5
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by Diti24** [comment] 2016-08-22 14:28
I don't thing this is a bug. It is the expected behavior.
Unfortunately debugging with Spyder is really a pain :-(. 
I tried to use spyder for several months it is really a nice IDE, I was waiting and hoping the debugging would become more comfortable in the future, but unfortunately it is still not usable.
Recently I moved to the pyzo IDE which is much better for what concerns debugging.

**Comment by ccordoba12** [comment] 2016-08-22 14:43
@Diti24, what are the advantages of Pyzo over Spyder for debugging?

**Comment by ccordoba12** [comment] 2016-08-22 14:44
@ganong123, it depends on where you have your current focus, either in the Python or IPython console because there you enter debug mode.

**Comment by Diti24** [comment] 2016-08-22 18:03
@ccordoba12
In pyzo when you debug, you have the basic ipython (nice userfriendly) working: 
all the auto-completion working, 
F9 evaluate selection is working,
arrow-up/down working (to recall older statements)
There are not so much points but are fundamental thinks which make the difference.

**Comment by ccordoba12** [comment] 2017-04-26 16:05
Closing as this doesn't apply anymore.

**Closed by ccordoba12** 2017-04-26 16:05 UTC
Labels: component:IPython Console, type:Bug
