### ISSUE TITLE
I don't know what 

### ISSUE THREAD

**Issue by qa-136** [spyder-ide/spyder#22393] opened 2024-08-28 19:14 UTC
### What steps will reproduce the problem?

I'm not so sure about this, sorry. I just want my Spyder to work well

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 105, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder_kernels/comms/commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 224, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder_kernels/comms/commbase.py", line 435, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 246, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 283, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'ce357e2ac3d74674bb70da33ca38eed4': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), '01edc74e65bf4206a6a9e6cd96f19962': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), 'f0657824d01846e196aeee071053ee36': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), '5cb3e2d86a8343e28ab626845e7cecbf': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), '3f5f95b8d01341f6a106e0b3539ceacd': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), 'f96895d6c3664f07ae4ba003d8c3fcdd': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), '936dff5afd1e4c52829d62f38688c310': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), '888a6b3792d4473c928696611663010b': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), 'd5dc52d2f6d94e6680b8f23e2d0de3ae': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), '21de2487220e46fdbae8bbc7bce7e413': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), 'ec900d52418d4f328c942f26d5c51af7': (False, <bound method ClientWidget._show_special_console_error of <spyder.plugins.ipythonconsole.widgets.client.ClientWidget object at 0x33b129cf0>>), 'bcb8032703f34bfdbd6eb2ac5e99ca50': (True, None), '7fb2a3644f424441836a01ff7a75c2fc': (True, None), '00ccc36763e94143b6c4f148971c463d': (True, None), '7fb39c448a3d485783b0ae8729246d75': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/variableexplorer/widgets/main_widget.py", line 576, in save_array
    self._current_editor.save_array()
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/widgets/collectionseditor.py", line 1201, in save_array
    data = self.delegate.get_value(self.currentIndex())
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/widgets/collectionseditor.py", line 1555, in get_value
    return self.parent().get_value(name)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/widgets/collectionseditor.py", line 1614, in get_value
    value = self.shellwidget.get_value(name)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 107, in get_value
    raise ValueError(msg % reason_big)
ValueError: <br><i>The variable is too big to be retrieved.</i><br><br><br><b>Note</b>: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.5.5 bef1bdcdc (standalone)
* Python version: 3.10.11 64-bit
* Qt version: 5.15.11
* PyQt5 version: 5.15.10
* Operating System: macOS-14.5-arm64-arm-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.25.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.4 (OK)
jsonschema >=3.2.0               :  4.22.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.3 (OK)
pylint_venv >=3.0.2              :  None (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  65.5.0 (OK)
sphinx >=0.6.6                   :  5.1.1 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=24.0.0                     :  26.0.3 (OK)

# Optional:
cython >=0.21                    :  3.0.10 (OK)
matplotlib >=3.0.0               :  3.9.0 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment] 2024-10-02 16:43
Hey @qa-136, thanks for reporting and sorry for the late reply. This is a duplicate of issue #12913 and we'll try to fix it in a future version.

**Closed by ccordoba12** 2024-10-02 16:43 UTC
