### ISSUE TITLE
Spyder 3.4.4 and Sphinx 2.01 or 2.1 breaks help formatting

### ISSUE THREAD

**Issue by Dan-Patterson** [spyder-ide/spyder#9527] opened 2019-06-07 04:15 UTC
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 3.4.4 fresh install with a package distribution unrelated to spyder.  This version distributed Sphinx 2.01 instead of 1.8.5 which it did a version ago.
However.... Code formatting in the help is broken under Sphinx version 2.01.
I did a 
`conda install sphinx=1.8.5 --no-pin` 
and the problem went away.  I also tried upgrading to Sphinx 2.1 but the problem remains.
I am unsure what happened between 1.85 and 2.01/2.1 but the help documents for python/numpy functionality is broken between versions.  Hopefully the image will show what I mean.  The image shows what is correct in version 1.8.5, 
```

## Versions
* Spyder version: 3.4.4
* Python version:  Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
* IPython 7.5.0 -- An enhanced Interactive Python.
* Operating System name/version: Windows 10

IPython >=4.0     :  7.5.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.4 (OK)

![sphinx_bug](https://user-images.githubusercontent.com/6071199/59080729-4be26900-88b8-11e9-8652-0004b54bf39b.png)

**Comment by ccordoba12** [comment] 2019-06-07 09:00
Thanks for reporting. We'll take a look at it in a future release.

**Comment by ccordoba12** [comment] 2019-07-30 09:35
Closing as a duplicate of #9888.

**Closed by ccordoba12** 2019-07-30 09:35 UTC
Labels: component:Help, type:Bug
