### ISSUE TITLE
Autocomplete as soon as we type

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2599] opened 2015-08-07 03:41 UTC
The current autocomplete is triggered when we hit ctrl + space if I am not wrong, it would be awesome to have autocomplete like atom has which doesn't need a keyboard trigger and suggests as soon as we start typing

**Comment by ccordoba12** [comment] 2015-08-08 15:15
Closing as a duplicate of issue #1914. We're considering to implement this for 3.0 or 3.1.

**Closed by ccordoba12** 2015-08-08 15:15 UTC
Labels: duplicate
