### ISSUE TITLE
Kernel will not load and says It needs to be downloaded, yet it id downloaded

### ISSUE THREAD

**Issue by RI7TE** [spyder-ide/spyder#20261] opened 2022-12-25 23:35 UTC
### What steps will reproduce the problem?

Open up Spyder and console will not connect to kernel

### Traceback
```python-traceback
Error initializing plugin EntryPoint(name='KWallet', value='keyring.backends.kwallet', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 202, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.kwallet'
Error initializing plugin EntryPoint(name='SecretService', value='keyring.backends.SecretService', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 202, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.SecretService'
Error initializing plugin EntryPoint(name='Windows', value='keyring.backends.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 202, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.Windows'
Error initializing plugin EntryPoint(name='chainer', value='keyring.backends.chainer', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 202, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint(name='libsecret', value='keyring.backends.libsecret', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 202, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.libsecret'
Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
Traceback (most recent call last):
  File "keyring/backend.pyc", line 202, in _load_plugins
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.macOS'
```

## Versions

* Spyder version: 5.4.0 510c6249c (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.1.0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  None (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by dalthviz** [comment] 2022-12-26 18:24
Hi @RI7TE Seems like you are using the standalone version of Spyder on MacOS, right? Did you just installed Spyder or did you updated a previous installation? Could you share with us any steps to reproduce this issue in our side?

Any further information to understand your setup and understand how the issue is being triggered is greatly appreciated, let us know!

**Comment by dalthviz** [comment] 2022-12-26 18:38
Also, could this be related with an OS update to MacOS Ventura for example? What do you think @mrclary ?

**Comment by mrclary** [comment] 2022-12-27 01:39
@dalthviz @RI7TE, I cannot reproduce the OP on my Ventura system (13.1):

* Spyder version: 5.4.0 510c6249c (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.2.0

**Comment by dalthviz** [comment] 2022-12-27 17:52
Thanks for checking @mrclary !

@RI7TE could you try to reinstall Spyder and check again? Let us know if that helps!

**Comment by dalthviz** [comment] 2023-03-15 19:36
Closing as a duplicate since https://github.com/spyder-ide/spyder/issues/20681 was fixed with https://github.com/spyder-ide/spyder/pull/20686

**Closed by dalthviz** 2023-03-15 19:36 UTC
Labels: resolution:Duplicate, OS:MacOS, status:Awaiting Followup, Installers
