### ISSUE TITLE
ignore strings when highlighting matching parentheses

### ISSUE THREAD

**Issue by lxkain** [spyder-ide/spyder#3474] opened 2016-09-28 21:59 UTC
## Description

**What steps will reproduce the problem?**

1. type: print('creating all {} listeners ({} blocks of {} listeners'.format())
2. hover the cursor at the end of the line
3. 

**What is the expected output? What do you see instead?**
I expect the first paren to be highlighted, instead the one inside the string is highlighted. The string should be ignored for parens matching.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.4.5
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2016-09-29 07:21
Thanks for reporting. This is a duplicate of issue #1673.

**Closed by ccordoba12** 2016-09-29 07:21 UTC
