### ISSUE TITLE
Not so good with numpy

### ISSUE THREAD

**Issue by Zwenjay** [spyder-ide/spyder#6224] opened 2018-01-16 23:31 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\printing.py", line 192, in as_escaped_unicode
    result = compat.text_type(thing)  # we should try this first
  File "D:\Users\wenjiez\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\base.py", line 72, in __repr__

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2018-01-17 02:07
Thanks for reporting, but as this appears to be a duplicate of your other issue  #6225 , it will be closed. Please do not open duplicate issues one after another; this just creates more clutter and gets in the way of us trying to help solve your problem.

**Closed by CAM-Gerlach** 2018-01-17 02:07 UTC
