### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by nkrvls96** [spyder-ide/spyder#12872] opened 2020-05-26 17:57 UTC
I installed python and anacoda and once i've run spyder an error occured on kernel.
I have windows 10

Traceback (most recent call last):
File "C:\Users\admin\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\admin\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\admin\anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\admin\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 308, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\admin\anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\admin\anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 562, in initialize
self.init_kernel()
File "C:\Users\admin\anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 447, in init_kernel
user_ns=self.user_ns,
File "C:\Users\admin\anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\admin\anaconda3\lib\site‑packages\spyder_kernels\console\kernel.py", line 33, in __init__
super(SpyderKernel, self).__init__(*args, **kwargs)
File "C:\Users\admin\anaconda3\lib\site‑packages\ipykernel\ipkernel.py", line 68, in __init__
kernel = self,
File "C:\Users\admin\anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\admin\anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 687, in __init__
self.init_magics()
File "C:\Users\admin\anaconda3\lib\site‑packages\ipykernel\zmqshell.py", line 593, in init_magics
super(ZMQInteractiveShell, self).init_magics()
File "C:\Users\admin\anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 2250, in init_magics
m.PylabMagics, m.ScriptMagics,
File "C:\Users\admin\anaconda3\lib\site‑packages\IPython\core\magic.py", line 405, in register
m = m(shell=self.shell)
File "C:\Users\admin\anaconda3\lib\site‑packages\IPython\core\magics\osm.py", line 52, in __init__
self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
File "C:\Users\admin\anaconda3\lib\re.py", line 234, in compile
return _compile(pattern, flags)
File "C:\Users\admin\anaconda3\lib\re.py", line 286, in _compile
p = sre_compile.compile(pattern, flags)
File "C:\Users\admin\anaconda3\lib\sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "C:\Users\admin\anaconda3\lib\sre_parse.py", line 924, in parse
p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Users\admin\anaconda3\lib\sre_parse.py", line 420, in _parse_sub
not nested and not items))
File "C:\Users\admin\anaconda3\lib\sre_parse.py", line 810, in _parse
p = _parse_sub(source, state, sub_verbose, nested + 1)
File "C:\Users\admin\anaconda3\lib\sre_parse.py", line 420, in _parse_sub
not nested and not items))
File "C:\Users\admin\anaconda3\lib\sre_parse.py", line 501, in _parse
code = _escape(source, this, state)
File "C:\Users\admin\anaconda3\lib\sre_parse.py", line 402, in _escape
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \P at position 52

**Comment by steff456** [comment] 2020-05-26 22:54
Hi @nkrvls96,

Closing this issue because it is a duplicate of #10329 

Thanks for reporting!

**Closed by steff456** 2020-05-26 22:54 UTC

**Comment by ccordoba12** [comment] 2020-05-26 23:44
@nkrvls96, you can also find a temporal solution to your problem on that issue.

**Comment by nkrvls96** [comment] 2020-05-27 17:54
@steff456 problem solved. Thank you
