### ISSUE TITLE
submit

### ISSUE THREAD

**Issue by kings07** [spyder-ide/spyder#6029] opened 2017-12-20 22:14 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
    from .__pkginfo__ import version as __version__
    from setuptools import __version__ as setuptools_version
    from setuptools.extension import Extension
    _Extension = get_unpatched(distutils.core.Extension)
AttributeError: module 'distutils.core' has no attribute 'Extension'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2

**Comment by CAM-Gerlach** [comment] 2017-12-21 02:34
Thanks for reporting. Please describe step by step how you got this error so we can reproduce it in our side. If we don't hear from you, we'll have to close this issue in a week (7 days) from now. 

Also, looking at the error it appears likely to be something with your install. How did you install Spyder? Methods other than Anaconda can be tricky and cause various problems, and thus are mostly for experts and officially unsupported.

**Comment by CAM-Gerlach** [comment] 2017-12-29 03:18
Closed due to lack of response.

**Closed by CAM-Gerlach** 2017-12-29 03:18 UTC
Labels: status:AwaitingFollowup
