### ISSUE TITLE
Spyder internal problem

### ISSUE THREAD

**Issue by weiying-wang** [spyder-ide/spyder#13610] opened 2020-08-23 18:47 UTC
### What steps will reproduce the problem?

- Tried to convert first row as headers of columns
using df.columns = df.iloc[0]
- Didn't get error message but told there is a sypder internal issue

### Traceback
```python-traceback
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/collectionsdelegate.py", line 162, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 904, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 137, in __init__
    self.max_min_col_update()
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 228, in max_min_col_update
    for dummy, col in self.df.iteritems():
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 901, in iteritems
    yield from self.items()
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 894, in items
    yield k, self._get_item_cache(k)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3586, in _get_item_cache
    values = self._data.get(item)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 966, in get
    raise ValueError("cannot label index with a null key")
ValueError: cannot label index with a null key
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.0.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by steff456** [comment] 2020-08-24 17:41
Hi @weiying-wang,

This seems a problem related to Pandas rather than a problem with Spyder. I couldn't reproduce it with a sample dataframe of pandas. Can you post here the dataframe which gives you this error to see if we can reproduce it?

**Comment by steff456** [comment] 2020-09-01 17:49
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!

**Closed by steff456** 2020-09-01 17:49 UTC
Labels: status:Awaiting Followup
