### ISSUE TITLE
Error during kite tutorial

### ISSUE THREAD

**Issue by NK308** [spyder-ide/spyder#11110] opened 2019-12-16 16:57 UTC
### What steps will reproduce the problem?

Installed kite, error occured in line 184 of kite_tutorial.py
I tried to let the autocompletition fill in the signature and choose plt.plot(my_x, label=[str]) as signature as the error popped up.

### Traceback
```python-traceback
  File "/home/nk/anaconda3/envs/spyder-test/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 860, in insert_snippet
    leaf, snippet_root, ast, line, column)
  File "/home/nk/anaconda3/envs/spyder-test/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 489, in _insert_snippet_at_node
    list(possible_snippet.placeholder) +
TypeError: 'TextNode' object is not iterable
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.3
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-72-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.1 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.5 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-17 02:40
Duplicate of #10971

**Closed by ccordoba12** 2019-12-17 02:40 UTC
