### ISSUE TITLE
regex sometimes hangs when trying to search non-ASCII source text #12913

### ISSUE THREAD

**Issue by DIV-on-github** [spyder-ide/spyder#12914] opened 2020-06-01 05:37 UTC
### What steps will reproduce the problem?

Same as second issue descibed in 
regex sometimes hangs when trying to search non-ASCII source text #12913

I was trying to step through the code, and ended up on line 313 of re.py.
The code hung.  I wanted to copy the contents of variable "pattern" in the Variable Explorer.  I got an error that the variable is 'too big' (even though it is a string no more than 100 characters long), but that was not supposed to be reported, and then eventually I got this error.  

### Traceback
```python-traceback
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 96, in get_value
    return self.call_kernel(
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder_kernels\comms\commbase.py", line 537, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 131, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder_kernels\comms\commbase.py", line 415, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 142, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'2079c071c7c34c4daa0f65c8e1e2f486': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'bbc62bd24f4e4922a335b76bcdbfb33f': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'c13b851c315242ed9b91583115231d81': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'bf99dc0ff3f6434482c0d968fcf16fda': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'd4b5999f57e24f0d802fd8baf8649327': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'dec4e9775b8d4770ab4903c30df932fb': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '981e9260eb9e4bd9b1fee85ccee2eda0': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'd7d5af5130824a9f85c2ec7d9c1aa8df': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '0a0d91aef45e4ffabdebd18bfeec1569': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '3d7207e38c21484c9a744ad2e79a7665': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'aa706079237d47d7a76c868841bcb13e': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'a81ab41d5be44ec0af9be8affe6e19c3': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'bbc70698b157407a9a34d38cee1f300c': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '7cfb90beeb094f8984e6fd672aaa2cf1': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'e06b7a9e86064fdea92b4cc03c1ed06f': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '3d59ab4ee45d48c480d2a7ac3d57b6ac': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'b99f7eb8e5fa40f4a5c8e28d423ac274': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '2da43065348b478aa90610414a2c0d3e': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'd7a0e14e3e614764818483594fdaea9a': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '1cadef849abe4f30bff6f21f02af496f': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'a8d27ecaa04f4424b300a6c4d16193fd': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '1566eb4f38164caab9574ec212c9fe07': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '87d5e18adb1043e689b89c5d7a38db18': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '7f4ae023519f4096ae4e6e94805ec93b': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '79ee73f3c16b405498e5fd62ed58c2cd': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), 'ef40f0b75b024439824cb3ccefc6c3af': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '815e6577866f4fbba87b3525701f6f6e': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '3d9c5718f01c4d6b9f3abb5f9ac5ec58': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '87e12de6868447b6968d6367aeb7881b': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '359ff286b7be4d1e9be043a155fc170d': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '1ad49330295f47c88118653902bc449c': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '91ec03115884492aa1582bb706890d63': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '52bbe7ad7d4e41af8d4f8a5d57810f4c': (False, <bound method ShellWidget.remote_set_cwd of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x0000017532024CA0>>), '1d14997e591844378c6177fb2a4be59e': (True, None), 'd509a1c445cc44f4b60db2fcd82da3c0': (True, None), '43a80ad4dcfc419d9bbc8b3f14683e11': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1040, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1383, in get_value
    return self.parent().get_value(name)
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1438, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Program files (portable)\WinPy_3-8\WPy64-3830\python-3.8.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 101, in get_value
    raise ValueError(msg % reason_big)
ValueError: The variable is too big to be retrieved.<br><br>Note: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.8.3
* Qt version: 5.14.2
* PyQt5 version: 5.14.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.14.0 (OK)
jedi >=0.15.2                  :  0.17.0 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso >=0.5.2                  :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.33.0          :  0.32.0 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.19 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.4 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment] 2020-06-01 15:10
Thanks for the report.

Closing as duplicate of #12913

**Closed by goanpeca** 2020-06-01 15:10 UTC
