### ISSUE TITLE
Syder5 complains about spyder-kernel dependency, but is contradictory.

### ISSUE THREAD

**Issue by rosyth** [spyder-ide/spyder#15108] opened 2021-04-05 11:13 UTC
### What steps will reproduce the problem?

Start Spyder.

Complaint pop up.  
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)

But to me .... >=  2.0.1 means my 2.0.1 is OK, not NOK !

Dependencies list
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.13.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.7.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.3.1 (OK)
pylint >=1.0                  :  2.4.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  50.3.1 (OK)
sphinx >=0.6.6                :  1.8.5 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.3 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  19.0.2 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.2 (OK)
scipy >=0.17.0                :  1.6.0 (OK)
sympy >=0.7.3                 :  None (NOK)

**Comment by stonebig** [comment] 2021-04-05 12:30
Duplicate of https://github.com/spyder-ide/spyder/issues/15091

You can apply a one character fix

**Comment by ccordoba12** [comment] 2021-04-05 14:40
Hey @rosyth, thanks for reporting. We'll release a new version with a fix for that problem later today.

**Closed by ccordoba12** 2021-04-05 14:40 UTC
