### ISSUE TITLE
'kernel died: %s'

### ISSUE THREAD

**Issue by dantekmfdm** [spyder-ide/spyder#15500] opened 2021-05-04 13:02 UTC
### What steps will reproduce the problem?

o iniciate a new proyect and save in a specific place of my hard drive D: for my proyect, shows the foññowing error.

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'a3c2b18aacd511eb94dbd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('a3c2b18aacd511eb94dbd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'cde11f1facd511ebb24dd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('cde11f1facd511ebb24dd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'cde11f1facd511ebb24dd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('cde11f1facd511ebb24dd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'cde11f1facd511ebb24dd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('cde11f1facd511ebb24dd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'cde11f1facd511ebb24dd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('cde11f1facd511ebb24dd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'cde11f1facd511ebb24dd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('cde11f1facd511ebb24dd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 113, in get_comm
    return self.comms[comm_id]
KeyError: 'cde11f1facd511ebb24dd43d7eed62cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 48, in _dispatch
    getattr(self, msg_type)(msg)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 172, in comm_msg
    comm = self.get_comm(comm_id)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\comms.py", line 117, in get_comm
    self.log.warning("No such comm: %s", comm_id)
Message: 'No such comm: %s'
Arguments: ('cde11f1facd511ebb24dd43d7eed62cc',)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.008878707885742,)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.0008807182312,)
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\utils\external\github.py", line 246, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\dante\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\widgets\github\backend.py", line 141, in send_report
    ret = repo.issues.post(title=title, body=body)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\utils\external\github.py", line 124, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\utils\external\github.py", line 260, in _http
    raise ApiError(url, req, resp)
spyder.utils.external.github.ApiError: https://api.github.com/repos/spyder-ide/spyder/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dante\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dante\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dante\AppData\Local\Programs\Python\Python39\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\widgets\reporterror.py", line 380, in _submit_to_github
    github_report = github_backend.send_report(title, issue_text)
  File "c:\users\dante\appdata\local\programs\python\python39\lib\site-packages\spyder\widgets\github\backend.py", line 143, in send_report
    _logger().warning('Failed to send bug report on Github. '
Message: 'Failed to send bug report on Github. response=%r'
Arguments: {'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.23.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.4.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by steff456** [comment] 2021-05-04 16:26
Hi @dantekmfdm,

It seems this is a duplicate of #15356, that is already fixed by #15462 and will be part of our next version that is going to be released soon. Please keep up posted in our repo and our social media to update to it once it's available.

Thanks for reporting!

**Closed by steff456** 2021-05-04 16:26 UTC
