### ISSUE TITLE
error after close the current project 

### ISSUE THREAD

**Issue by flyluyun** [spyder-ide/spyder#5047] opened 2017-08-24 09:11 UTC
## Description

**What steps will reproduce the problem?**

1. close the current project
2. 
3. 

**What is the expected output? What do you see instead?**
the expected output is just the normal layout,but  i see "Connecting to kernel" instead.
![2017-08-24 17 09 30](https://user-images.githubusercontent.com/18591534/29658877-15d1a756-88ef-11e7-8eef-fe28d90a7341.png)

**Please provide any additional information below**

  File "/Users/liufei/anaconda/lib/python3.5/site-packages/spyder/plugins/projects.py", line 286, in close_project
    self.restart_consoles()
  File "/Users/liufei/anaconda/lib/python3.5/site-packages/spyder/plugins/projects.py", line 386, in restart_consoles
    self.main.ipyconsole.restart()
  File "/Users/liufei/anaconda/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 1286, in restart
    self.create_new_client(give_focus=False)
  File "/Users/liufei/anaconda/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 977, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/liufei/anaconda/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 998, in connect_client_to_kernel
    stderr_file)
  File "/Users/liufei/anaconda/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 1386, in create_kernel_manager_and_kernel_client
    stderr = codecs.open(stderr_file, 'w', encoding='utf-8')
  File "/Users/liufei/anaconda/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/1z/1j3jtw4n6b768bx9w9rxy2xm0000gn/T/spyder-liufei/kernel-321d815cc229.stderr'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-08-24 19:39
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment] 2018-09-10 17:34
Closing as a duplicate of issue #7800.

**Closed by ccordoba12** 2018-09-10 17:34 UTC
Labels: component:Projects, type:Bug
