### ISSUE TITLE
'Create new file' shortcut does not work when File Explorer is focused

### ISSUE THREAD

**Issue by okke-formsma** [spyder-ide/spyder#4334] opened 2017-04-07 08:56 UTC
**What steps will reproduce the problem?**

1. Select the file explorer
2. Press ctrl+n
3. Nothing happens

**What is the expected output? What do you see instead?**

I expected to see a new file being creating. Instead, nothing happens.

This issue is similar to #3344. Is there a way to force shortcuts to be global instead of local? It's really annoying to remember which shortcuts work depending on which area of the screen has focus.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.5.2
* Qt Version: 5.6.2
* PyQt Version: 4.6
* Operating system: Windows

**Comment by ccordoba12** [comment] 2017-04-07 16:43
Not at the moment and I think we're not going to expose that possibility.

The thing is we're creating a new set of external plugins which will introduce shortcuts of their own, and we want to avoid conflicts with Spyder main shortcuts.

Besides, in Spyder 4 we're going to expose a public API for other people to create plugins, and that could introduce even more conflicts between shortcuts.

In any case, I'm closing this issue as a duplicate of issue #3344.

**Closed by ccordoba12** 2017-04-07 16:43 UTC
Labels: resolution:Duplicate
