### ISSUE TITLE
spyder crashes every time sorry for repeating the issue# 6159 but problem not solved

### ISSUE THREAD

**Issue by nunoyu** [spyder-ide/spyder#6160] opened 2018-01-07 19:13 UTC
Description of your problem
Spyder fail to initialize with Windows Server 2012 R2 version.
It just crashes all the time.

What steps will reproduce the problem?

It occurs every time when I tried to start the program.
What is the expected output? What do you see instead?
I saw something like : spyder 0Xc000012d

Please provide any additional information below
I've already uninstalled and installed several times, but it didn't revolve the problem.

Versions and main components
Spyder Version: 3.2.4
Python Version: 3.6.3, 32bits
Qt Version: no Qt found with command: pip list
PyQt Version: QtPy 1.3.1, no PyQt found
Operating system: windows server 2012 R2

conda installation got memory error too!

Exception:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215
, in main
status = self.run(options, args)
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", lin
e 335, in run
wb.build(autobuilding=True)
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in b
uild
self.requirement_set.prepare_files(self.finder)
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380
, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 620
, in prepare_file
session=self.session, hashes=hashes)
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\download.py", line 809, i
n unpack_url
unpack_file_url(link, location, download_dir, hashes=hashes)
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\download.py", line 715, i
n unpack_file_url
unpack_file(from_path, location, content_type, link)
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils_init.py", line
599, in unpack_file
flatten=not filename.endswith('.whl')
File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils_init_.py", line
488, in unzip_file
data = zip.read(name)
File "C:\ProgramData\Anaconda3\lib\zipfile.py", line 1315, in read
return fp.read()
File "C:\ProgramData\Anaconda3\lib\zipfile.py", line 835, in read
buf += self._read1(self.MAX_N)
File "C:\ProgramData\Anaconda3\lib\zipfile.py", line 925, in _read1
data = self._decompressor.decompress(data, n)
MemoryError

error message when tried to run spyder in command window.

Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>spyder
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy_init_.py", line 148,
in 
from PySide import version as PYSIDE_VERSION # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in

sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 14
4, in main
from spyder.app import mainwindow
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", li
ne 49, in 
requirements.check_qt()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line
39, in check_qt
import qtpy
File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy_init_.py", line 154,
in 
raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by ccordoba12** [comment] 2018-01-07 19:16
Closing as duplicate of #6159. It's clear you don't know how to use or install Spyder with Anaconda or pip, so please don't open more issues about this.

**Comment by ccordoba12** [comment] 2018-01-07 19:16
Also, please read

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

**Closed by ccordoba12** 2018-01-07 19:16 UTC

**Comment by nunoyu** [comment] 2018-01-07 19:20
ok, thanks!

**Comment by stonebig** [comment] 2018-01-07 19:22
it's strange you wanted to install Python 32 bit on a 2012 server (that I presume is 64 bit). It may be the problem. Also, if it's a web server, maybe the server is too low on memory

**Comment by nunoyu** [comment] 2018-01-07 19:27
because I have some dll files that only work with py 32 bits. Maybe the memory should be a problem. But I have another webserver with the same size of memory. But that one works well. Tricky problem!

**Comment by CAM-Gerlach** [comment] 2018-01-08 01:33
Please continue the discussion, if there is anything further to discuss, on the other thread. Thanks.
