### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by chillaxd** [spyder-ide/spyder#6634] opened 2018-03-07 05:04 UTC
Ipython kernel is not strating.
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/anaconda3/lib/python3.6/site-packages/jupyter_client/threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "/anaconda3/lib/python3.6/site-packages/jupyter_client/client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "/anaconda3/lib/python3.6/site-packages/jupyter_client/threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "/anaconda3/lib/python3.6/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 357, in initialize
    self.make_current()
  File "/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError

**Comment by CAM-Gerlach** [comment] 2018-03-07 05:13
Thanks for reporting. This is a duplicate of #6627 ; and in any case outside of Spyder's control. To fix for now, run ``conda install tornado=4.5.3`` from the Anaconda Prompt/Terminal/shell (Windows/Mac/Linux) in the ``conda`` environment that Spyder is installed in.

**Closed by CAM-Gerlach** 2018-03-07 05:13 UTC
