### ISSUE TITLE
Project on network drive

### ISSUE THREAD

**Issue by hetfmt** [spyder-ide/spyder#11369] opened 2020-01-21 10:39 UTC
### Issue Report Checklist

* [+] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [+] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [+] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [- ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [+] Tried basic troubleshooting (if a bug/error)
    * [+] Restarted Spyder
    * [-] Reset preferences with ``spyder --reset``
    * [+] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [-] Tried the other applicable steps from the Troubleshooting Guide
* [+] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Trying to access or create a project on a network drive generates an error.

### What steps reproduce the problem?

1. I copied a folder from my local disc to a network drive and wanted to open the existing Spyder project located in the folder (on the network drive). This produces the current error.

2. I then deletede the project folder and tried to create a new project (on the remote network folder), but when pressing "Create" I received the same error. Even though I received the error, the ".spyproject" folder is created at the correct location.

3. Finally I tried to map a parent folder as a network-drive. Now, creating a project, caused Spyder to crash, but after restarting everything seemed to work as expected.

It looks like too many (duplicate) backslashes are added to the path-string. I have "coded" the folder-names in the "FileNotFoundError"-line in the python-traceback below.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Exception in comms call set_cwd:
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\spyder_kernels\console\kernel.py", line 352, in set_cwd
    os.chdir(dirname)
FileNotFoundError: [Errno 2] The specified path is invalid: '\\\\\\\\<server_name>\\\\<folder_name_1>\\\\<folder_name_2>\\\\<folder_name_3>\\\\<project_parent_folder>'

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.4
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment] 2020-01-21 14:06
Duplicate of #10785

**Comment by ccordoba12** [comment] 2020-01-21 14:06
Until we fix that bug, please don't use network drives, sorry.

**Closed by ccordoba12** 2020-01-21 14:06 UTC

**Comment by hetfmt** [comment] 2020-01-22 07:50
Hi Carlos,
Thank you for your fast response.
I just want to add a comment to #10785 (something that I didn’t try before I created #11369):


  1.  I have no problem changing to a network drive in the console:
os.chdir(r'\\<server_name>\<folder_name>\<folder_name>\<folder_name>\<project_parent_folder>’)
  2.  If I try to change to the same folder using the “folder navigation” on the Spyder “icon-bar”, I get the error.

Regards,
Henrik



Henrik Toft • Frontmatec Smørum A/S
Senior Specialist • Phone: +45 445 037 11

**Comment by ccordoba12** [comment] 2020-01-22 13:55
Ok, then it's an error in our side.
