### ISSUE TITLE
Middle mouse button click on editor tabs may close wrong tab

### ISSUE THREAD

**Issue by matheger** [spyder-ide/spyder#12558] opened 2020-04-30 18:30 UTC
Found a minor UI issue: When clicking the middle mouse button on the filename in an editor tab, it closes that tab, as expected. However, when doing this anywhere on the "X" symbol part of the tab, Spyder closes the next tab to the right.

E.g. in this image: 
![Untitled](https://user-images.githubusercontent.com/34485360/80745300-4fd53600-8add-11ea-81c8-334ed0880208.png)
Middle mouse button click in the red area should close "temp.py", but it closes "untitled1.py". 
(Literal) Edge case: Clicking in the green area should close "untitled1.py", but does nothing.

Python 3.7.7 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10
clean miniconda environment & spyder --reset

**Comment by goanpeca** [comment] 2020-05-04 02:10
Thanks for the report @matheger . I do not have a mouse handy to check this problem, but what you say indeed suggest something is wrong.

Will try to tackle this in a future release.

Cheers!

**Comment by steff456** [comment] 2020-05-04 16:26
Hi @goanpeca I'm unable to check this issue because I don't have a mouse either. We can ask in the team to see if someone can reproduce this.

**Comment by bcolsen** [comment] 2020-05-04 16:51
I can reproduce this in Ubuntu

**Comment by goanpeca** [comment] 2020-05-04 21:26
>Hi @goanpeca I'm unable to check this issue because I don't have a mouse either. We can ask in the team to see if someone can reproduce this.

@steff456 you can overcome this by using https://karabiner-elements.pqrs.org/ with some configuration like the following one:

<img width="958" alt="Screen Shot 2020-05-04 at 16 23 17" src="https://user-images.githubusercontent.com/3627835/81015053-97342d00-8e23-11ea-8ed1-00df2ac3925c.png">

On Mac the `X` is to the left, but if I click on the right where the `X` would be on other operating systems, I get the same behavior. On the animation, I clicked F1 (Fn+F1) in the `py` portion of the name and the next tab closed instead of the one I clicked. So I can reproduce this.

![image](https://user-images.githubusercontent.com/3627835/81015195-e0847c80-8e23-11ea-985d-58d04e2119d8.png)

**Closed** 2020-05-15 17:58 UTC
Labels: component:Editor, tag:Ui, tag:Ux-usability, type:Bug
