### ISSUE TITLE
Cannot commit or browse repository from File Explorer pane

### ISSUE THREAD

**Issue by jvbmov** [spyder-ide/spyder#7593] opened 2018-08-01 08:47 UTC
### What steps will reproduce the problem?

When right clicking the "Commit" or "Browse repository" buttons in the File explorer pane this error occurs (git 2.18.0). Workflow was fine with Spyder 3.2.*

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 393, in <lambda>
    self.vcs_command(fnames, 'commit')
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 825, in vcs_command
    for path in sorted(fnames):
TypeError: 'bool' object is not iterable
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.6
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.4 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.0 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
sympy >=0.7.3     :  1.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-08-01 15:32
Thanks for reporting. We'll take a look at this in a future release.

**Comment by courtneypk-work** [comment] 2018-08-15 01:00
I have the exact same issue on OS X.
- Spyder version: 3.3.0
- Python version: Python 3.6.5 :: Anaconda custom (64-bit)
- Qt version: 5.9.6
- PyQt5 version: 5.9.2
- Operating System: Mac OS X 10.13.6

IPython >=4.0     :  6.4.0 (OK)
cython >=0.21     :  0.28.4 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.0 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
psutil >=0.3      :  5.4.6 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
sympy >=0.7.3     :  1.2 (OK)

**Comment by ccordoba12** [comment] 2018-08-25 04:18
This is a duplicate of issue #7733.

**Closed by ccordoba12** 2018-08-25 04:18 UTC
Labels: component:File Explorer, type:Bug
