### ISSUE TITLE
Turtle/TCL Not Working, macOS Monterey (12.6)

### ISSUE THREAD

**Issue by jeff-jm** [spyder-ide/spyder#19499] opened 2022-09-19 01:05 UTC
### What steps will reproduce the problem?

I am trying to run code in Spyder on my Mac that uses Turtle/TCL. I am able to run this code fine on my Windows Computer and VS Code, but am unable to run in in spyder. 

I am new to spyder so I apologize if I am missing something obvious or for being a fool in general.

This is the error I am receiving:

```
TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.12_1/lib/tcl8.6 /Applications/Spyder.app/Contents/lib/tcl8.6 /Applications/Spyder.app/lib/tcl8.6 /Applications/Spyder.app/Contents/library /Applications/Spyder.app/library /Applications/Spyder.app/tcl8.6.12/library /Applications/tcl8.6.12/library
```

This probably means that Tcl wasn't installed properly.

## Versions

* Spyder version: 5.3.3 43b5344e5 (standalone)
* Python version: 3.9.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 21.6.0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.14.0 (OK)
keyring >=17.0.0                     :  23.8.2 (OK)
nbconvert >=4.0                      :  7.0.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  65.3.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.4.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by mrclary** [comment] 2022-09-20 21:25
@jeff-jm, can you post a minimum working example of the code you are trying to run? Also, is your macOS running on Intel or Arm?

**Comment by jeff-jm** [comment] 2022-09-20 21:44
> @jeff-jm, can you post a minimum working example of the code you are trying to run? Also, is your macOS running on Intel or Arm?

I am on an 2020 (unfortunately) Intel MacBook Pro running latest software MacOS Moneterey 12.6. 

It may also be relevant to note that Zsh is my default shell, that is, opening the Terminal App on Mac opens a Zsh shell rather than traditional bash shell. This caused my Anaconda Navigator to have problems (I am using standalone Spyder). I don't think that's the issue here but just thought I should note. 

**### Here is the code I am trying to run, pasted from Spyder & VS code:** 

#### BEGIN IMPORT SECTION ####
import turtle
import time
import random
#### END IMPORT SECTION ####


#### BEGIN FUNCTION/CLASS DEFINITION ####

#### END FUNCTION/CLASS DEFINITION ####


#### BEGIN SCRIPT EXECUTION ####
window = turtle.Screen()
window.colormode(255)
window.title('Title')
window.bgcolor((0,0,0))
window.tracer(0) 

x = window.window_width()
y = window.window_height()


xmin = 0-x//2
xmax = x//2
ymin = 0-y//2
ymax = y//2


for i in range(10000):
    tx = random.randrange(xmin,xmax) 
    ty = random.randrange(ymin,ymax) 
    box = turtle.Turtle() 
    box.shape('square') 
    

    r = 0
    g = 0
    b = 0
    if tx > 0: 
        r = 255
    elif tx < 0: 
        b = 255
    else: 
        r = 125
        g = 125
        b = 125
        
    if ty >= 0 and ty < ymax*0.5: 
        r = r*0.75
        g = g*0.75
        b = b*0.75
    elif ty < 0 and ty >= ymin*0.5: 
        r = r*0.5
        g = g*0.5
        b = b*0.5
    elif ty < ymin*0.5: 
        r = r*0.25
        g = g*0.25
        b = b*0.25
    
    r = int(r)
    g = int(g)
    b = int(b)
    box.color((r,g,b)) 
    box.up() 
    box.goto(tx,ty) 
    window.update() 
    time.sleep(0.001) 
turtle.done()
turtle.bye()
#### END SCRIPT EXECUTION ####

------------------------------------------------code end----------------------------------------------

The error I receive (exclusively in Spyder, runs fine in visual studio code):


TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.12_1/lib/tcl8.6 /Applications/Spyder.app/Contents/lib/tcl8.6 /Applications/Spyder.app/lib/tcl8.6 /Applications/Spyder.app/Contents/library /Applications/Spyder.app/library /Applications/Spyder.app/tcl8.6.12/library /Applications/tcl8.6.12/library


This probably means that Tcl wasn't installed properly.


Let me know if you need any more info!

**Comment by jeff-jm** [comment] 2022-09-20 21:55
> @jeff-jm, can you post a minimum working example of the code you are trying to run? Also, is your macOS running on Intel or Arm?

I am on an 2020 (unfortunately) Intel MacBook Pro running latest software MacOS Moneterey 12.6. 

I am kind of unfamiliar with GitHub, but I attached a .docx file with the exact code that I am trying to run copy pasted. You should be able to copy this code directly into Spyder/any IDE. It is a simple program that draws squares in a window, with half being blue and half being red, going in a gradient pattern. 
[codeexample.docx](https://github.com/spyder-ide/spyder/files/9611485/codeexample.docx)

It may also be relevant to note that Zsh is my default shell, that is, opening the Terminal App on Mac opens a Zsh shell rather than traditional bash shell. This caused my Anaconda Navigator to have problems (howeverI am using standalone Spyder). I don't think that's the issue here but just thought I should note. 

The error I receive (exclusively in Spyder, runs fine in visual studio code):

TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.12_1/lib/tcl8.6 /Applications/Spyder.app/Contents/lib/tcl8.6 /Applications/Spyder.app/lib/tcl8.6 /Applications/Spyder.app/Contents/library /Applications/Spyder.app/library /Applications/Spyder.app/tcl8.6.12/library /Applications/tcl8.6.12/library


This probably means that Tcl wasn't installed properly.


Here are some screenshots of Spyder and visual studio code. Let me know if you need any more info!

<img width="1435" alt="spyder" src="https://user-images.githubusercontent.com/101373780/191371760-28a488e5-6d1d-4215-bb55-2ecf69903488.png">

<img width="1402" alt="visualstudio" src="https://user-images.githubusercontent.com/101373780/191371791-f68498bd-b6d7-4a35-819b-d70da0a817cb.png">

**Comment by mrclary** [comment] 2022-09-20 22:26
> I am kind of unfamiliar with GitHub, but I attached a .docx file with the exact code that I am trying to run copy pasted.

@jeff-jm, thanks for the additional information. I'm also using an Intel Macbook Pro running macOS 12.6. I also get an error running the code you provided, although it is not identical. Nevertheless, the code should run properly if you change Spyder's graphics backend to Tkinter. Be sure to restart your IPython console after making the change. Below is a screencast illustrating this.

![issue-19499](https://user-images.githubusercontent.com/9618975/191375572-a3d90bd9-bc5b-451f-b5a4-3c153d3778c6.gif)

**Comment by jeff-jm** [comment] 2022-09-20 22:35
Thanks for the quick reply! 

When looking into this problem, I found that solution online, but unfortunately, this is not solving the issue for me. I will attach some photos of the error with Tkinter as Graphics Backend:

<img width="722" alt="Screen Shot 2022-09-20 at 5 31 26 PM" src="https://user-images.githubusercontent.com/101373780/191376707-1a438f4d-823a-4998-8ce6-be37c2f210eb.png">
<img width="1430" alt="Screen Shot 2022-09-20 at 5 31 42 PM" src="https://user-images.githubusercontent.com/101373780/191376734-9715a68b-85dd-4695-bdc4-d2837b7adfe1.png">

I tried uninstalling and reinstalling the standalone application, but it unfortunately has not solved the problem. I did do a complete uninstall and reinstall of Anaconda Navigator recently, could this be interfering with the Spyder standalone application?

Thanks for everything!

**Comment by mrclary** [comment] 2022-09-21 00:53
Okay, I've reproduced the same error on macOS 12.5.1 running on an M1 processor with release 5.3.3. It seems to be the same error message from #14656 (https://github.com/spyder-ide/spyder/issues/14656#issuecomment-769497466).

```python
[In 1]: import tkinter

[In 2]: tkinter.tk()
Traceback (most recent call last):

  File "/var/folders/sc/1rrvv5750vx9bdrq5cbktybh0000gn/T/ipykernel_4397/207895174.py", line 1, in <cell line: 1>
    tkinter.Tk()

  File "tkinter/__init__.pyc", line 2270, in __init__

TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.12_1/lib/tcl8.6 /Applications/Spyder.app/Contents/lib/tcl8.6 /Applications/Spyder.app/lib/tcl8.6 /Applications/Spyder.app/Contents/library /Applications/Spyder.app/library /Applications/Spyder.app/tcl8.6.12/library /Applications/tcl8.6.12/library



This probably means that Tcl wasn't installed properly.
```
My previous successful test was actually performed with a recent development artifact. Given that #14656 was resolved without any action on our part, and that a recent dev build seems to work, I'm going to hypothesize that the issue may have to do with a change in tkinter and or Tcl/Tk that may be resolved for our next release.

@jeff-jm you can test this by downloading a recent dev build here: https://github.com/spyder-ide/spyder/actions/runs/3024730384

**Comment by mrclary** [comment] 2022-09-21 04:11
@jeff-jm, so I've confirmed that the latest development build works. So it should be fixed for you upon our next release. Or you may use the development build that I linked to in my previous comment. Another possible workaround is to use an external conda environment for IPython console, rather than Spyder's internal one. See instructions here: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#working-with-other-environments-and-python-installations

**Comment by ccordoba12** [comment] 2022-09-21 22:27
> @jeff-jm, so I've confirmed that the latest development build works

Ok, let's close this issue then. @jeff-jm, please check 5.4.0 when it's released and open a new issue if that version doesn't fix this problem.

**Closed by ccordoba12** 2022-09-21 22:27 UTC
Labels: status:Awaiting Followup
