### ISSUE TITLE
Spyder hangs "Loading Code Analysis" when starting from console in Linux

### ISSUE THREAD

**Issue by marianux** [spyder-ide/spyder#22450] opened 2024-09-06 19:53 UTC
Update to v6.0.0 and launch "spyder &" from the console. The result is always the same when using the fork "&" operator. When launching spyder without forking a new process, the IDE starts flawlessly. 

This is the output when running  "spyder --debug-info verbose &"

[...]
2024-09-06 16:35:50,336 [INFO] [spyder.app.mainwindow] -> Loading Code Analysis...
2024-09-06 16:35:50,346 [INFO] [spyder.app.mainwindow] -> Loading pylint...
2024-09-06 16:35:50,376 [INFO] [spyder.app.mainwindow] -> Registering shortcuts for pylint...
2024-09-06 16:35:50,376 [DEBUG] [spyder.api.plugin_registration.registry] -> Plugin preferences has already loaded
2024-09-06 16:35:50,376 [DEBUG] [spyder.api.plugin_registration.mixins] -> Calling <bound method Pylint.on_preferences_available of <spyder.plugins.pylint.plugin.Pylint object at 0x7f18b8026200>>
2024-09-06 16:35:50,376 [DEBUG] [spyder.api.plugin_registration.registry] -> Plugin editor has already loaded
2024-09-06 16:35:50,376 [DEBUG] [spyder.api.plugin_registration.mixins] -> Calling <bound method Pylint.on_editor_available of <spyder.plugins.pylint.plugin.Pylint object at 0x7f18b8026200>>
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.registry] -> Plugin project_explorer has already loaded
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.mixins] -> Calling <bound method Pylint.on_projects_available of <spyder.plugins.pylint.plugin.Pylint object at 0x7f18b8026200>>
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.registry] -> Plugin mainmenu has already loaded
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.registry] -> Registering plugin pythonpath_manager - <class 'spyder.plugins.pythonpath.plugin.PythonpathManager'>
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_main_menu_available is watching plugin mainmenu
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_main_menu_teardown will handle plugin teardown for mainmenu
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_projects_available is watching plugin project_explorer
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_projects_teardown will handle plugin teardown for project_explorer
2024-09-06 16:35:50,377 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_toolbar_available is watching plugin toolbar
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_toolbar_teardown will handle plugin teardown for toolbar
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_main_menu_available is watching plugin mainmenu
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_main_menu_teardown will handle plugin teardown for mainmenu
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_projects_available is watching plugin project_explorer
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_projects_teardown will handle plugin teardown for project_explorer
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_toolbar_available is watching plugin toolbar
2024-09-06 16:35:50,378 [DEBUG] [spyder.api.plugin_registration.mixins] -> Method on_toolbar_teardown will handle plugin teardown for toolbar

[Here it hangs...]

**Comment by ccordoba12** [comment] 2024-09-06 21:39
Hey @marianux, thanks for reporting. This is a duplicate of issue #22415, so I'm going to close it in favor of that.

You can also find there some workarounds to deal with that problem while we fix it.

**Closed by ccordoba12** 2024-09-06 21:39 UTC
