### ISSUE TITLE
Editor removing characters when press TAB to indent

### ISSUE THREAD

**Issue by JohnRobson** [spyder-ide/spyder#4279] opened 2017-03-19 19:44 UTC
## Description of your problem

Editor removing characters when press TAB to indent.

**What steps will reproduce the problem?**

1. go to some line of your code
2. press TAB (to increase indent) or press SHIFT+TAB (to remove indent)
3. some characters will disappear!!!

I'm using Indentation characters "Tabulations", not Space indentation. Tab stop with: 2 spaces

**Please provide any additional information below**
Another problem (maybe related) when press ENTER to create a new line, the editor create a big indent (10 tabs).

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Qt Version: 5.8.0
* PyQt Version: 5.7.1
* Operating system: ArchLinux updated

## Dependencies

jedi >=0.8.1     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.2.0 (OK)
pycodestyle >=0.6:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  2.0.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-03-21 05:00
@rlaverde, please take a look at this one.

**Comment by rlaverde** [comment] 2017-03-21 15:22
This is a duplicate of #4037 and have been fixed in spyder 3.1.3, 

Please update to our latest version (3.1.3 at the moment).

**Closed by rlaverde** 2017-03-21 15:22 UTC
Labels: component:Editor, type:Bug
