### ISSUE TITLE
Spyder crashing on startup with Tornado 5

### ISSUE THREAD

**Issue by gabrielclow** [spyder-ide/spyder#6662] opened 2018-03-07 19:10 UTC
## Problem Description
Spyder crashing with tornado 5

### What steps will reproduce the problem?

1.  "conda update --all" updated tornado 4.5.3 to 5
2. try to start Spyder
3. crash

Reverting bug
1a. "conda install tornado 4.5" downgrade tornado 5 to 4.5.3
2a. launch Spyder
3a. launches OK

### What is the expected output? What do you see instead?
I expect to launch Spyder, instead it crashes

### Paste Traceback/Error Below (if applicable)

```python-traceback

On Anaconda prompt:
(base) C:\Users\user>spyder
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\app\mainwindow.py", line 1172, in setup
    self.setup_layout(default=False)
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\app\mainwindow.py", line 1457, in setup_layout
    self.setup_default_layouts('default', settings)
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\app\mainwindow.py", line 1633, in setup_default_layouts
    widget.toggle_view(True)
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\user\Miniconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\user\Miniconda3\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\user\Miniconda3\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\user\Miniconda3\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\user\Miniconda3\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\user\Miniconda3\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\user\Miniconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\user\Miniconda3\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Users\user\Miniconda3\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Users\user\Miniconda3\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError

```

## Package Versions

* Spyder: 3.2.7
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6.0
* Operating System: Windows 10 64bits

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by stonebig** [comment] 2018-03-07 19:26
maybe there is a simple fix:
https://github.com/jupyterlab/jupyterlab/pull/4121

**Comment by ccordoba12** [comment] 2018-03-07 19:56
This is a duplicate of issue #6627. Please see there for a solution.

**Closed by ccordoba12** 2018-03-07 19:56 UTC
