### ISSUE TITLE
Control K not working macOS 10.13.3

### ISSUE THREAD

**Issue by conradwt** [spyder-ide/spyder#6591] opened 2018-03-03 23:38 UTC
## Problem Description

The keyboard shortcut, Control + K, not working on macOS.  It simply does nothing.

### What steps will reproduce the problem?

1. add cursor to the front of a line which contains text
2. Control + K 

### What is the expected output? What do you see instead?

Expected

I expected that the line would be removed from the file.

Actual

Nothing happened with zero error or feedback from the editor.

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Package Versions

* Spyder:  3.2.7
* Python: Python 3.6.4 :: Anaconda custom (64-bit)
* Qt:  ??
* PyQt: 5.10.1
* Operating System:  macOS 10.13.3

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by CAM-Gerlach** [comment] 2018-03-04 03:34
At least on Windows, I believe the default is <kbd>Ctrl</kbd> - <kbd>D</kbd>. Did you check the Spyder keyboard shortcuts manager? What shortcut did you set for delete line there?

**Comment by conradwt** [comment] 2018-03-04 04:00
@CAM-Gerlach I have already checked the keyboard shortcuts and `Control-K` should kill to the end of the line.  On macOS, `Control-D` is mapped to delete a single character.

**Comment by CAM-Gerlach** [comment] 2018-03-04 05:14
On Windows, its mapped by default to <kbd>Meta</kbd> <kbd>K</kbd>; I guess <kbd>Meta</kbd> maps to <kbd>Control</kbd> on the Mac (since Ctrl maps to Command, and Alt maps to Option)? There's no Meta key on Windows (aside from the Windows key which is generally OS reserved), but if I change it to <kbd>Ctrl</kbd> - <kbd>K</kbd>it works fine. Is there someone with a Mac who can test this?

**Comment by csabella** [comment] 2018-03-04 10:31
Duplicate of #5323.

**Comment by CAM-Gerlach** [comment] 2018-03-04 17:30
Yup. Thanks @csabella

**Closed by CAM-Gerlach** 2018-03-04 17:30 UTC
Labels: OS:MacOS, component:Preferences, status:Awaiting Followup
