### ISSUE TITLE
spyder problem

### ISSUE THREAD

**Issue by lazymilkcoffee** [spyder-ide/spyder#5961] opened 2017-12-12 05:22 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1712, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "E:\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ASUS\\.spyder-py3\\template.py'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by CAM-Gerlach** [comment] 2017-12-12 05:47
Thanks for reporting. This is a duplicate of #5717 ; see my and ccordoba's comments there. In summary, possibly either a mangled install (thus do a clean uninstall and reinstall the latest version of Anaconda), or something to do with your antivirus or other security software messing with the file. Therefore, this should be closed. 

If you have further information about any special circumstances in your environment, anything that preceded this error, whether the file at that path exists and is readable, and anything else helpful that you can think of, feel free to add it to that thread, as it will help both us and yourself track down the problem. Best of luck!

**Closed** 2017-12-12 19:40 UTC
