### ISSUE TITLE
cannot create new Folder in new Project

### ISSUE THREAD

**Issue by fzfy** [spyder-ide/spyder#13857] opened 2020-09-25 11:57 UTC
### What steps will reproduce the problem?

1. click Project->New Project->Enter Any Name->Create to create a New Project
2. Right click the new project Name in rhe project panel and click New -> Folder->Enter any valid name
3. An Error Meesage appear : unable to create folder ....

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.0 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by juanis2112** [comment] 2020-09-26 00:06
Hi @fzfy, thanks for reporting this. This issue is a duplicate of https://github.com/spyder-ide/spyder/issues/13722 which was fixed recently for our new version of spyder to be released on November.

**Closed by juanis2112** 2020-09-26 00:06 UTC

**Comment by MCilento93** [comment] 2020-09-29 21:39
> Hi @fzfy, thanks for reporting this. This issue is a duplicate of #13722 which was fixed recently for our new version of spyder to be released on November.

Well,
I have the same issue on Spyder 4.1.5 fresh installed.
Thank you,
