### ISSUE TITLE
Configs reset and disappear

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12149] opened 2020-04-05 11:10 UTC
Spyder (4.1.1) just decided to forget itself; I open it in a conda env as usual, and everything from the theme to keyboard shortcuts, linter configs, and Kite have reset to default. Also plots look horrible. Tried other conda envs, same. I don't even see my custom coloring theme in Appearance preferences.

I haven't installed any new packages since last time Spyder worked normally, or changed any Spyder config - I just restarted the computer. What's the deal? More importantly, how do I recover my previous configs? I have set them up all over again, but this'll be quite a problem if recurring.

**Comment by OverLordGoldDragon** [comment] 2020-04-05 13:35
It also "detached" itself from the Anaconda Powershell Prompt that was used to launch it:

<img src="https://user-images.githubusercontent.com/16495490/78499794-c5124d00-7763-11ea-98dc-5106a251ea5f.png" width="600">

**Comment by ccordoba12** [comment] 2020-04-05 17:23
Sorry to hear this. I think it could happen when you open several Spyder instances at the same time. Was that the case here?

> More importantly, how do I recover my previous configs?

Backups are placed in

    C:\Users\<your user>\.spyder-py3\config\backups

You can recover your previous settings from `spyder.ini.bak` (if I'm not mistaken).

**Comment by OverLordGoldDragon** [comment] 2020-04-05 17:26
@ccordoba12 Great, thanks; and yeah, I had three open. Also, there are several baks (below); I'm guessing the latest one is of the current, and older ones are of the previous? So say I store the latest backup elsewhere so it's not overwritten - how do I make it the "active" config (which I'm guessing is `/configspyder.ini`)?

<img src="https://user-images.githubusercontent.com/16495490/78505337-eaaf4e80-7783-11ea-9b3f-18c500742c71.png" width="550">

**Comment by ccordoba12** [comment] 2020-04-05 17:29
You need to move `spyder.ini.bak` and `transient.ini.bak`, with names `spyder.ini` and `transient.ini`, respectively, to

    C:\Users\<your user>\.spyder-py3\config\

That should do the trick.

**Comment by ccordoba12** [comment] 2020-04-05 17:31
I'm going to leave this open to see if we can fix it.

**Comment by ptoche** [comment] 2020-05-27 09:05
I experienced a complete reset of `spyder.ini` after I had attempted to set a keyboard shortcut to an "illegal" key. Namely `F11`, which `MacOS` binds to something. Did you by any chance make some changes to the shortcuts? Or to any other of the settings defined in `spyder.ini` ? Perhaps some kind of conflict like the one I experienced could have caused that "reset". What happens, I think, is that if Spyder detects an anomaly in the `spyder.ini` file, it trashes it and recreates a brand new one based on the default template. 

@ccordoba12 Please allow me to hijack this thread briefly to comment on one point: I have noticed, as you point out, (and recently reported) that "conflicts" resulting in a recreation of  `spyder.ini` can be caused by two environments sharing the same `spyder.ini` (a behaviour you plan to change in a future release, I believe). I also noticed that the backup `spyder.bak` is recreated at every restart. That means, if I'm not mistaken, that if you experience an issue and restart _twice_, the `spyder.back` will just be a copy of the default `spyder.ini` and will not allow you to recover your lost settings. I think it would be reasonable to save, say, 10 backup copies before deleting old ones. (personally I have a script that is executed when I set my `PATH` to `conda` and makes a backup every time I start, which quickly accumulates, but every so often I trash them manually.)

**Comment by OverLordGoldDragon** [comment] 2020-07-02 15:19
It just happened again, and this time didn't have multiple Spyders open. Just launched from terminal after turning on PC; Spyder opened to an existing project, and additionally `kite_tutorial.py`.

@ptoche I made no such changes.

**Comment by OverLordGoldDragon** [comment] 2020-07-02 15:25
How does the numbering work, by the way? I had my existing backups as `spyder.ini-57.0.0.bak` and `transient.ini-57.0.0.bak`, but as soon as I moved them to `/config` (and renamed), they were overwritten in `/backups` (dated this minute instead of 2 months ago). If this happened before I restored the backup it'd be bad news; will make explicit backup.

**Comment by ccordoba12** [comment] 2020-07-02 16:22
@goanpeca, any ideas about what could be happening here?

**Comment by goanpeca** [comment] 2020-07-02 19:13
I can look into @ptoche examples. For the others cases, it will be hard without some more context or steps to reproduce it.

**Comment by ccordoba12** [comment] 2020-07-02 21:11
@goanpeca, could it be an issue with our config manager discarding the current config somehow and creating a new one? in Spyder 3 we had a try/except that did just that, but I couldn't find it in Spyder 4.

**Comment by goanpeca** [comment] 2020-07-02 21:31
It is possible, but I do not recall the old way of doing it, since that was refactored a lot.

**Comment by OverLordGoldDragon** [comment] 2024-03-29 18:11
Just noting, haven't had this occur again.

**Comment by ccordoba12** [comment] 2024-03-30 16:08
Ok, thanks for letting us know about it @OverLordGoldDragon. I'm going to close this issue then.

**Closed by ccordoba12** 2024-03-30 16:08 UTC
Labels: type:Bug
