### ISSUE TITLE
"Set as current console's working directory" button not working on Python 3

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1844] opened 2015-02-17 21:10 UTC
_From [wei.chen...@gmail.com](https://code.google.com/u/104458465353672494695/) on 2014-06-07T01:10:01Z_

Spyder Version:  2.3.0rc
Python Version:  3.4.1
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
IPython >=0.13  :  2.1.0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
pep8 >=0.6      :  None (NOK)
psutil >=0.3    :  2.1.1 (OK)
pyflakes >=0.6.0:  0.8.1 (OK)
pygments >=1.6  :  1.6 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  0.7.5 (OK) 

What steps will reproduce the problem?

1. open spyder
2. click file explorer, change the directory
3. click on the "set as current console's working directory" button 

What is the expected output? What do you see instead?

 The current working directory should be changed.
Instead, the current working directory is never changed. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1844_

**Comment by cle1109** [comment] 2015-04-17 09:42
I also noticed that this button does not work. Maybe this bug was introduced with iPython 3? I looked a bit into the code but couldn't figure out the problem. Could it be that the emitted signal `set_current_console_wd.emit(getcwd()` is not connected to a corresponding slot?

**Comment by ccordoba12** [comment] 2015-04-17 21:17
Thanks for noticing it. I'll try to fix it for beta1

**Comment by ccordoba12** [comment] 2015-06-15 18:41
The fix for this problem is going to be released in Spyder **2.3.5**

**Closed** 2015-06-15 18:40 UTC
Labels: 1 star, bug

**Comment by cle1109** [comment] 2015-06-15 19:16
Great! Looking forward to this release!

**Comment by kjmobile** [comment] 2016-11-25 22:44
I can't see any "set as current console's working directory" button". 
I am using windows 10.  How can i set my working directory?

**Comment by ccordoba12** [comment] 2016-11-26 00:28
That button was removed in Spyder 3.0. Now, as soon as you select a new directory in the Working Directory toolbar, it's set in our Python and IPython consoles.

**Comment by pravinsham** [comment] 2017-05-04 09:01
yes, it is fixed, I use Spyder 3.1.2 from Anaconda distribution. thanks a lot. I was using older version of spyder and searching for solution. Thank you @@ccordoba12

**Comment by wiselyloh** [comment] 2017-05-12 05:34
I have Spyder 3.1.3 (python 3.6) giving me the same trouble. I found that it is a bug. The workaround is that in file explorer, click the pull down directory list once, then it will update the working directory somehow. try your luck.

**Comment by ValdemarOrn** [comment] 2017-06-12 23:33
wiselyloh's comment is accurate. I had the same issue, working directory was not changing until I clicked the dropdown and then re-ran my script, then magically the directory had updated to what I had chosen.

This is an outstanding bug and needs fixing.

OS: Windows 8.1 64 bit
Python 3.6
Spyder 3.1.4

**Comment by ccordoba12** [comment] 2017-06-13 01:16
This bug was fixed for the IPython console in 3.1.3, I don't know what you mean.

**Comment by cbrnr** [comment] 2017-06-13 06:31
I can confirm that this (unintended) behavior occurs in Spyder 3.1.4. If you change folders in the File Explorer panel, the path gets updated in the dropdown menu in the toolbar. However, the working directory does not get updated in the IPython console automatically. To update the working directory, you have to click into the path dropdown menu and hit enter.

**Comment by ccordoba12** [comment] 2017-06-13 14:17
@cbrnr, right, we are aware of this serious usability problem (which is different from the one reported here). It'll be fixed in Spyder **3.2**.

**Comment by rodrigocamargo** [comment] 2017-06-28 01:47
ccordoba12 This is not working. I tested Spyder 3.1.4 on Mac through Anaconda, and the directory is only set when you click at the dropdown and choose the directory. It doesn't work if you navigate through File Explorer.

**Comment by varghese-robin** [comment] 2017-09-04 21:10
not able to see any "set the working directory" button in Spyder (Python 3.6). I either have to provide the entire file path or I have to use set working director commands.

**Comment by MBiagio** [comment] 2017-12-03 03:14
I don't get a "set working directory" button either.  Version 3.2.4

How do I set working directory? What commands do I use?

**Comment by ccordoba12** [comment] 2017-12-03 16:17
@MBiagio, you don't need to press any button. Simply selecting a new directory will change it automatically in your current IPython console.

**Comment by jnsebgosselin** [comment] 2017-12-04 14:00
@MBiagio 

![working_dir](https://user-images.githubusercontent.com/10170372/33556272-4add8cee-d8d1-11e7-9c4b-cc35388e1302.gif)

**Comment by Gabomfim** [comment] 2018-02-22 14:12
If you can't update your working directory try this:
Run > Configuration per file:
 In working directory settings >the current working directory

Hope I can help!

**Comment by abhijithvnair94** [comment] 2018-11-03 06:58
> @MBiagio
> 
> ![working_dir](https://user-images.githubusercontent.com/10170372/33556272-4add8cee-d8d1-11e7-9c4b-cc35388e1302.gif)

I tried this , but this is not working in spyder3. Kindly help

**Comment by ccordoba12** [comment] 2018-11-03 15:14
@abhijithvnair94, you're probably using a very old version of Spyder. Please update or use Anaconda in case it's not possible to do it through your Linux distro.

**Comment by Ankit-ww** [comment] 2019-07-16 06:51
runfile('C:/Users/Ankit/.spyder-py3/temp.py', wdir='C:/Users/Ankit/Desktop/Deep_Learning_A_Z')
what is the meaning of this .i am not getting this

**Comment by JeremyShore** [comment] 2019-08-14 00:53
I fixed it with my Spyder version 3.3.6 on Mac:

I did what Gabomfim (above) said: go to Run > Configuration per file... > and I selected, "The current working directory" under the heading: "Working Directory settings"

now for each run I do, it stays on the same chosen directory instead of reverting to the default Spyder directory: /Users/NAME/.spyder-py3 after each run. Good Luck!
