### ISSUE TITLE
annoying  popup

### ISSUE THREAD

**Issue by qedseung** [spyder-ide/spyder#13354] opened 2020-07-22 04:58 UTC
### What steps will reproduce the problem?

this popped up when dragging and dropping a file into spyder.
But keeps popping up after closing the issue reporter, even when completely idle.

### Traceback
```python-traceback
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1393, in handle_hover_response
    self._request_hover_clicked)
TypeError: CodeEditor.sig_display_object_info[str, bool].emit(): argument 1 has unexpected type 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\qedse\Anaconda3\envs\py4prod\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\mainwindow.py", line 3679, in run_spyder
    app.exec_()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 302, in <lambda>
    lambda: self.receive_timeout(req_id))
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 136, in receive_timeout
    self.howto_send_to_codeeditor(req_id)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 205, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 273, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1019, in handle_response
    handler(params)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1406, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1050, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1393, in handle_hover_response
    self._request_hover_clicked)
TypeError: CodeEditor.sig_display_object_info[str, bool].emit(): argument 1 has unexpected type 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\qedse\Anaconda3\envs\py4prod\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\mainwindow.py", line 3679, in run_spyder
    app.exec_()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 302, in <lambda>
    lambda: self.receive_timeout(req_id))
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 136, in receive_timeout
    self.howto_send_to_codeeditor(req_id)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 205, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 273, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1019, in handle_response
    handler(params)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1406, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1050, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1393, in handle_hover_response
    self._request_hover_clicked)
TypeError: CodeEditor.sig_display_object_info[str, bool].emit(): argument 1 has unexpected type 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\qedse\Anaconda3\envs\py4prod\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\app\mainwindow.py", line 3679, in run_spyder
    app.exec_()
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 302, in <lambda>
    lambda: self.receive_timeout(req_id))
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 136, in receive_timeout
    self.howto_send_to_codeeditor(req_id)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 205, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\completion\plugin.py", line 273, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1019, in handle_response
    handler(params)
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1406, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "C:\Users\qedse\Anaconda3\envs\py4prod\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1050, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.0 (OK)
numpy >=1.7                    :  1.18.0 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.5.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment] 2020-07-22 16:55
Hi @qedseung seems like this is a duplicate of #13297 I'm closing this one but I think I managed to replicate this! As a work around please disable Kite completions from the preferences dialog (`Tools > Preferences > Completion and linting > Advanced > Enable Kite`)

**Closed by dalthviz** 2020-07-22 16:55 UTC
Labels: resolution:Duplicate
