### ISSUE TITLE
spyder on Windows 10 (py 3.5, QT5) not showing anything

### ISSUE THREAD

**Issue by radeksvarz** [spyder-ide/spyder#3877] opened 2016-12-22 19:06 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. install python 3.5, create and activate virtual env
2. pip install QT5 and spyder
3. run spyder

**What is the expected output? What do you see instead?**
I can only see the blank spyder window.
When using mouse I can right click, which shows menus. Menus activate corresponding dialogs (e.g. Preferences)

**installed**

alabaster (0.7.9)
astroid (1.4.9)
Babel (2.3.4)
bleach (1.5.0)
colorama (0.3.7)
decorator (4.0.10)
docutils (0.13.1)
entrypoints (0.2.2)
html5lib (0.9999999)
imagesize (0.7.1)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
isort (4.2.5)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter-client (4.4.0)
jupyter-core (4.2.1)
lazy-object-proxy (1.2.2)
MarkupSafe (0.23)
mccabe (0.5.3)
mistune (0.7.3)
nbconvert (5.0.0)
nbformat (4.2.0)
pandocfilters (1.4.1)
pep8 (1.7.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.9)
psutil (5.0.1)
pyflakes (1.3.0)
Pygments (2.1.3)
pylint (1.6.4)
PyQt5 (5.7)
pytz (2016.10)
pyzmq (16.0.2)
QtAwesome (0.3.3)
qtconsole (4.2.1)
QtPy (1.1.2)
requests (2.12.4)
rope-py3k (0.9.4.post1)
setuptools (20.10.1)
simplegeneric (0.8.1)
sip (4.18.1)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.5.1)
spyder (3.0.2)
testpath (0.3)
tornado (4.4.2)
traitlets (4.3.1)
wcwidth (0.1.7)
win-unicode-console (0.5)
wrapt (1.10.8)

**Comment by ccordoba12** [comment] 2016-12-22 22:58
Are you using an Nvidia video card?

**Comment by radeksvarz** [comment] 2016-12-23 01:15
yes, GeForce GT 540M or Intel Graphics 3000

**Comment by ccordoba12** [comment] 2016-12-23 02:47
This seems a duplicate of issue #3520. You have two options to fix this problem

1. Try to use PyQt 5.6 wheels.
2. Install the Anaconda Python distribution, which doesn't have this problem.

I'm sorry to say it, but this is a problem in the PyQt 5.7 wheels and there's nothing we can do about it.

**Closed by ccordoba12** 2016-12-23 02:47 UTC

**Comment by radeksvarz** [comment] 2016-12-23 08:11
Thank you top pointing out. I resolved that by copying opengl32sw.dll to the Scripts folder of the virtual env.

I suggest to put related note to the Installation page.
