### ISSUE TITLE
Opening file from SSHFS-mapped linux drive possible errors and delays executing it through `Run selection or current line (F9)`

### ISSUE THREAD

**Issue by gabiteodoru** [spyder-ide/spyder#17698] opened 2022-04-18 13:34 UTC
### What steps will reproduce the problem?

Try to open a file from an SSHFS-mapped linux drive.

I figured out a quick-and-dirty fix: on line `647` of `ntpath.py` I've added

```
import psutil
if [i for i in psutil.disk_partitions() if i.device[0]==path[0].upper()][0].fstype == 'FUSE':
    return path
```

But perhaps there are some nicer ways to deal with this :)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\user\miniconda3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'E:\\repo\\algoUtils.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\miniconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2187, in load
    current_editor = self.set_current_filename(filename,
  File "c:\users\user\miniconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 1721, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "c:\users\user\miniconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1512, in set_current_filename
    index = self.has_filename(filename)
  File "c:\users\user\miniconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1501, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "c:\users\user\miniconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1499, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "c:\users\user\miniconda3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "c:\users\user\miniconda3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'E:\\repo\\algoUtils.py'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.28.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  4.1.0 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.2.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment] 2022-04-18 22:52
Hey @gabiteodoru. thanks for reporting. I don't understand why this happens but we'll try to fix it in our next version (5.3.1), to be released in mid May.

@dalthviz, could you take a look at this one? Thanks!

**Comment by ccordoba12** [comment] 2022-04-18 22:53
Note: It's important for us to solve this one if we want to support SSHFS mounts in the future for our partnership with TDK.

**Comment by gabiteodoru** [comment] 2022-04-18 23:01
@ccordoba12 Thanks for responding, and thanks guys for building and maintaining Spyder, I love this thing! :)
If you're working on SSHFS support -- I did get it working today but there is a big snag -- I use F9 a lot to "Run selection", but if I "Run selection" on a snippet of code from a remote SSHFS-drive file, it takes a few extra seconds. I tried disabling some options like "Save file before running" or "Run in local directory of the file", but to no avail it's still slow. I thought about submitting a bug request, but I'm not sure how I could measure the time an F9 executes. If you do have any ideas what might be making it slower, I'm happy to try to get my hands dirty :) Thanks again!

**Comment by ccordoba12** [comment] 2022-04-18 23:07
Thanks for your kind words @gabiteodoru! What you said could be caused by network latency, but @dalthviz will confirm that once he starts working on this.

**Comment by gabiteodoru** [comment] 2022-04-18 23:12
> Thanks for your kind words @gabiteodoru! What you said could be caused by network latency, but @dalthviz will confirm that once he starts working on this.

This issue about the F9-run-snippet-delay: I was running in a local interpreter both snippets from a local file and a remote file, so in theory it should not need to use network for this operation at all ... (?)

**Comment by dalthviz** [comment] 2022-04-25 19:10
Checking this I was able to open a file using a SSHFS-mapped linux drive (from a virtualbox Ubuntu machine since I don't have access to a remote server to test this). Just in case, I was able to do so by following this guide: https://phoenixnap.com/kb/sshfs#ftoc-heading-2 and doing some port forwarding configuration. Also I think @gabiteodoru was able to setup this already so proably already find the way to overcome issues regarding Windows and Linux file systems incompatibilities.

Regarding the slow execution, could you share with us the code you are running @gabiteodoru ? I checked with some simple code snippets and I didn't saw delays (although that could be caused since my mapping is at the end all local and the code I'm using to test is quite simple).  Thinking about this, maybe your runs with the `Run current selection` could be taking some time since the code you are running needs to access data from your mapped drive or other remote source?

Any new info to reproduce this is greatly appreciated. Let us know!

**Comment by dalthviz** [comment] 2022-04-26 16:03
I see, I really don't know what we could do to improve the situation there if it is caused by some sort of latency, sorry :/

Although, checking a little bit, when using the F9/Run selection or current line what we do is to copy-paste the selection or current line from the editor widget to the console so I would say that even if the file is SSHFS-mapped the actions done using F9 don't use any network:

https://github.com/spyder-ide/spyder/blob/c08b5cfd36b0cd6f3282c5f8171da4d804e56597/spyder/plugins/editor/widgets/editor.py#L2769-L2792

https://github.com/spyder-ide/spyder/blob/c08b5cfd36b0cd6f3282c5f8171da4d804e56597/spyder/plugins/editor/widgets/base.py#L525-L579

Also, following your comment (` I was running in a local interpreter both snippets from a local file and a remote file, so in theory it should not need to use network for this operation at all ... (?)`), maybe the delay is caused at console level when executing. What happens if you directly write the code in the console like copy-pasting it? Do you see a delay executing it @gabiteodoru ?

Let us know!

**Comment by ccordoba12** [comment] 2022-05-14 15:33
Closing due to lack of response.

**Closed by ccordoba12** 2022-05-14 15:33 UTC
Labels: type:Bug, component:Editor, status:Awaiting Followup
