### ISSUE TITLE
application crashes

### ISSUE THREAD

**Issue by expired-brain** [spyder-ide/spyder#5796] opened 2017-11-20 00:38 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "X:\Anaconda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "X:\Anaconda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "X:\Anaconda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "X:\Anaconda\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "X:\Anaconda\lib\pstats.py", line 81, in __init__
    self.init(arg)
  File "X:\Anaconda\lib\pstats.py", line 95, in init
    self.load_stats(arg)
  File "X:\Anaconda\lib\pstats.py", line 109, in load_stats
    f = open(arg, 'rb')
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Exp\\.spyder\\profiler.results'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pan

**Comment by ccordoba12** [comment] 2017-11-20 01:41
Thanks for reporting. This is a duplicate of issue #5107 and it'll be fixed in our 3.2.5 version.

In the meantime, you can run in a terminal (cmd.exe)

    spyder --reset

to fix it.

**Closed by ccordoba12** 2017-11-20 01:41 UTC
