### ISSUE TITLE
Go to definition segmentation fault

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#4115] opened 2017-02-07 15:12 UTC
## Description of your problem
Go to definition sometimes creates a segmentation fault

**What steps will reproduce the problem?**

1.  Click go to definition on some function
2.  Watch Spyder die from a segmentation fault: 11 (on MacOS )
or
2. "Python has stopped working" on windows 10

## Versions and main components

* Spyder Version: 3.1.2 (Windows) / dev0 (MacOs)
* Python Version: 3.6.0

## Dependencies
Whatever comes with anaconda

**Comment by ccordoba12** [comment] 2017-02-07 19:29
Thanks for reporting. This is a duplicate of issue #3940.

**Closed by ccordoba12** 2017-02-07 19:29 UTC
Labels: resolution:Duplicate, type:Bug
