### ISSUE TITLE
Make Pdb continuation prompt consistent

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14476] opened 2020-12-21 16:54 UTC
I don't know if there's some profound reason for this but it sure interferes with smooth text manipulation:

![image](https://user-images.githubusercontent.com/16495490/102801276-70386480-43ce-11eb-82cc-00d8b75a5b2b.png)

I can't `Shift + Arrow Up` or `NumLock: 7, 1`, or even simply `Arrow Up` (or any direction) consistently, always have to adjust for that first line differing from rest. Would help if they were all vertically aligned just like in Editor.

**Comment by steff456** [comment] 2020-12-21 19:42
Hi @OverLordGoldDragon,

In which OS are you working on? I'm unable to reproduce this error, when I paste multiple lines in the iPython console I have the following view,

![image](https://user-images.githubusercontent.com/20992645/102815662-b673d080-439a-11eb-927a-41db00c065f4.png)

**Comment by ccordoba12** [comment] 2020-12-21 20:20
@steff456, the problem is with the `IPdb` prompt, not with the regular `In` one.

@OverLordGoldDragon, I also found this problem and tried to fix it for 4.2.1, but unfortunately I didn't have time to do it.

@impact27, could you give us a hand with it?

**Comment by impact27** [comment] 2020-12-21 20:36
Fixed in  #14478

**Comment by ccordoba12** [comment] 2020-12-21 20:54
Great! Thanks for your quick reply!

**Closed** 2020-12-21 23:44 UTC
Labels: component:Debugger, type:Bug
