### ISSUE TITLE
Spyder stops working

### ISSUE THREAD

**Issue by maakl** [spyder-ide/spyder#6266] opened 2018-01-22 06:54 UTC
## Description

When I attempt to open a folder or save a file, windows says that spyder has stopped working.

**What steps will reproduce the problem?**
Any attempt to open folder or save a new file.
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
I had an earlier version of anaconda installed, and spyder worked fine, but I've never gotten spyder to work on newer version.  I've uninstalled and reinstalled anaconda exactly by the instructions, updated conda, spyder, and qt without using pip, but no success. 
When I uninstalled an earlier version, it left an anaconda shell in the control panel.  The uninstall programs said there was an earlier version, but when I tried to uninstall it, the control panel said nothing was in there.  I removed that trace as well, but I wonder if permission to open a folder is not set right.  Windows doesn't say anything to that effect, but I wonder.  I've looked in regedit and I didn't see any registries set to an older version.  I hope you can help.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)


IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-22 14:33
This looks like a duplicate of #3903. Please take a look at that issue for a possible fix.

**Closed by ccordoba12** 2018-01-22 14:33 UTC

**Comment by CAM-Gerlach** [comment] 2018-01-23 01:21
Also, if that doesn't help, please see the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) for more things to try. Best of luck!
