### ISSUE TITLE
Autocomplete should not triger on writing numbers

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#10833] opened 2019-11-25 17:44 UTC
I'm not sure if it's solved by PR: Prevent automatic completions on backspace and return #10802, so I'll add it just in case.

In Spyder 4.0.0rc2 if you start typing a number in the Editor, after three numbers the autocomplete triggers as so:

![image](https://user-images.githubusercontent.com/15214418/69564796-f0b24900-0fb3-11ea-9111-8a7f9977d443.png)

**Comment by goanpeca** [comment] 2019-11-25 17:45
@gerazov could you provide a example?

**Comment by impact27** [comment] 2019-11-25 19:14
1. Make sure "Show completions on the fly" is activated
 2. write in the editor: `a = 123`
 3. Wait 300ms for the completion on the fly to appear

**Comment by goanpeca** [comment] 2019-11-25 19:15
Aha, yes, this is not desirable.

**Comment by bcolsen** [comment] 2019-11-25 19:54
I think that these are the fallback completions.

In issue #10797 @ccordoba12 said:
>@andfoy is going to change the current behavior, so fallback completions are requested only on demand. That should fix most if not all of these annoying issues.

That should fix this as issue well as issues where spaces make completions like this:

![Autocomplete_space](https://user-images.githubusercontent.com/10513354/69572302-183bee00-0f81-11ea-8e8d-480a7f6f9b2b.gif)

![Autocomplete_space_middle](https://user-images.githubusercontent.com/10513354/69572328-28ec6400-0f81-11ea-83ce-0c7c6440e710.gif)

**Comment by ccordoba12** [comment] 2020-01-27 20:41
Let's close this one as a duplicate of #10540.

**Closed by ccordoba12** 2020-01-27 20:41 UTC
Labels: component:Code Completion, component:Editor, type:Bug
