### ISSUE TITLE
No comments [Google translated]

### ISSUE THREAD

**Issue by Calambuuur** [spyder-ide/spyder#6316] opened 2018-01-28 14:13 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda\Anaconda3\envs\py35\lib\site-packages\qtconsole\console_widget.py", line 413, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Anaconda\Anaconda3\envs\py35\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 107, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "C:\Anaconda\Anaconda3\envs\py35\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Anaconda\Anaconda3\envs\py35\lib\site-packages\qtconsole\console_widget.py", line 1425, in _event_filter_console_keypress
    self.copy()
  File "C:\Anaconda\Anaconda3\envs\py35\lib\site-packages\qtconsole\frontend_widget.py", line 249, in copy
    was_newline = text[-1] == '\n'
IndexError: string index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment] 2018-01-28 16:18
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by CAM-Gerlach** [comment] 2018-01-28 19:20
For the record, the error appears to be a duplicate of #5095 and #5434 ; you closed the former as a NotSpyder, as the error traceback was entirely within the ``qtconsole`` codebase, and the latter as a NoResponce.

**Comment by ccordoba12** [comment] 2018-01-28 19:29
@CAM-Gerlach, could you open an issue in qtconsole about this? Issue #5095 contains a clear description of the problem.

**Closed by ccordoba12** 2018-01-28 19:29 UTC
Labels: status:AwaitingFollowup

**Comment by CAM-Gerlach** [comment] 2018-01-28 21:03
@ccordoba12 Done; opened as [qtconsole #264](https://github.com/jupyter/qtconsole/issues/264).
