### ISSUE TITLE
Matplotlib not installed or didn't load correctly in Spyder 5.3.1

### ISSUE THREAD

**Issue by jtskowronek** [spyder-ide/spyder#18003] opened 2022-05-25 05:31 UTC
### What steps will reproduce the problem?

I installed Spyder 5.3.1, fired it up, and iPython console is complaining that matplotlib isn't installed or didn't load correctly.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\client.py", line 735, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 533, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 83, in wrapper
    raise e
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 492, in _async_shutdown_kernel
    await ensure_async(self.request_shutdown(restart=restart))
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 397, in _async_request_shutdown
    self._connect_control_socket()
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 318, in _connect_control_socket
    self._control_socket = self._create_connected_socket("control")
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\connect.py", line 605, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\JTS\AppData\Local\Programs\Spyder\pkgs\zmq\sugar\context.py", line 258, in socket
    raise ZMQError(Errno.ENOTSUP)
zmq.error.ZMQError: Not supported
```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.1 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.9 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.3.2 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.1 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.8 (OK)
zmq >=22.1.0                         :  23.0.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.2 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by rhkarls** [comment] 2022-05-25 11:18
It seems importing PyQt5 from the Spyder console fails with 5.3.1 (from installer). With the same environment this is not a problem with 5.3.0 installer.

There's no ImportError with the python console or IPython console outside of Spyder and using the same environment. I have not tried 5.3.1 from conda-forge or pypi, only tried with the installer version.

    from PyQt5 import QtCore
    Traceback (most recent call last):
    
      File "C:\Users\username\AppData\Local\Temp\ipykernel_17452\1680556063.py", line 1, in <cell line: 1>
        from PyQt5 import QtCore
    
      File "C:\Users\username\Miniconda3\envs\myenv\lib\site-packages\PyQt5\__init__.py", line 41, in <module>
        find_qt()
    
      File "C:\Users\username\Miniconda3\envs\myenv\lib\site-packages\PyQt5\__init__.py", line 33, in find_qt
        raise ImportError("unable to find Qt5Core.dll on PATH")
    
    ImportError: unable to find Qt5Core.dll on PATH

I believe conda installs the dll's with a _conda suffix, like Qt5Core_conda.dll.

**Comment by jtskowronek** [comment] 2022-05-30 10:17
I attempted to update pyqt from 5.12.3 to 5.15 with conda via conda-forge,
but got what seems like a few thousand lines of conflicts that you probably
aren't interested in reading through.

**Comment by dalthviz** [comment] 2022-05-30 15:55
Checking a little bit this seems like this could be caused due to the addition of the micromamba executable to handle the env activation at https://github.com/spyder-ide/spyder/pull/17692/ and https://github.com/spyder-ide/spyder/pull/17856 to the installers. If I comment out the code that gives the path to the micromamba executable (which causes the activation to fallback to find the conda executable) and instead return `None` I'm able to import PyQt 5.12 without issue. Just in case, the code I'm refering is this (maybe as a workaround for the moment @jtskowronek you could try to make the code bellow return `None` in you Spyder installation):

https://github.com/spyder-ide/spyder/blob/551c30fc214079f11b16d2de73f5a3fd7a6351b2/spyder/config/base.py#L591-L602

@mrclary could it be that the micromamba executable needs something else set besides the path to the env to activate things when involving binaries like the PyQt .dlls? 🤔

**Comment by mrclary** [comment] 2022-06-11 14:08
> Checking a little bit this seems like this could be caused due to the addition of the micromamba executable to handle the env activation at #17692 and #17856 to the installers. If I comment out the code that gives the path to the micromamba executable (which causes the activation to fallback to find the conda executable) and instead return `None` I'm able to import PyQt 5.12 without issue. Just in case, the code I'm refering is this (maybe as a workaround for the moment @jtskowronek you could try to make the code bellow return `None` in you Spyder installation):
> 
> https://github.com/spyder-ide/spyder/blob/551c30fc214079f11b16d2de73f5a3fd7a6351b2/spyder/config/base.py#L591-L602
> 
> @mrclary could it be that the micromamba executable needs something else set besides the path to the env to activate things when involving binaries like the PyQt .dlls? 🤔

Hmm... I don't know why this would be happening. I don't think that it should matter what mechanism is used to activate an environment, but I'll take a look at it this week and see.

**Comment by mrclary** [comment] 2022-06-16 17:14
Just to be clear, with Spyder 5.3.1, everything works fine if the external environment uses PyQt 5.15, but has issues if the external environment uses PyQt 5.12, correct?

**Comment by dalthviz** [comment] 2022-06-16 17:25
Yep, as far as I tested :+1: although not sure if there are other modules that fail to be imported due to some .dll error besides PyQt. Could this be something that only happens on Windows? or maybe due to the micromamba version we are bundling with the Windows installer?

**Comment by mrclary** [comment] 2022-06-21 19:05
On my Windows VM, I do not get the OP error, but the following (IPython console graphics backend set to Qt5):
```
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython  -- An enhanced Interactive Python.

=========================================================================
NOTE: The following error appeared when setting your Matplotlib backend!!
=========================================================================

Failed to import any qt binding

This is most likely caused by missing packages in the Python environment
or installation whose interpreter is located at:

    C:\Users\rclary\AppData\Local\mambaforge\envs\test-18003-512\python.exe
```

**Comment by dalthviz** [comment] 2022-06-21 19:14
Thanks for the testing @mrclary ! If you try to import PyQt5 you get the error I saw too?

I was also checking this at the moment and seems like when using micromamba to activate the conda env some paths are missing from the `PATH` env variable.

Testing with an env call `pyqt512-cf` and the following env details:

<details>

Using to create the env:

```
conda create -n pyqt512-cf -c conda-forge spyder-kernels pyqt=5.12
```

```
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.0            py39h415ef7b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
ipykernel                 6.15.0             pyh025b116_0    conda-forge
ipython                   7.33.0           py39hcbf5309_0    conda-forge
jedi                      0.18.1           py39hcbf5309_1    conda-forge
jpeg                      9e                   h8ffe710_1    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0           py39hcbf5309_0    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libzlib                   1.2.12               h8ffe710_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1o               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
psutil                    5.9.1            py39hb82d6ee_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hb0d2dfa_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.9.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pywin32                   303              py39hb82d6ee_0    conda-forge
pyzmq                     23.1.0           py39he46f08e_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
setuptools                62.6.0           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyder-kernels            2.3.1            py39hcbf5309_0    conda-forge
sqlite                    3.38.5               h8ffe710_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tornado                   6.1              py39hb82d6ee_3    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zlib                      1.2.12               h8ffe710_1    conda-forge
```

</details>

Using micromamba I got as `PATH` env variable:

```
['C:\\Users\\dalth\\AppData\\Local\\Programs\\Spyder\\pkgs\\PyQt5\\Qt5\\bin',
 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\',
 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\',
 'C:\\Windows\\system32',
 'C:\\Windows',
 'C:\\Windows\\System32\\Wbem',
 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\',
 'C:\\Windows\\System32\\OpenSSH\\',
 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL',
 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL',
 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT',
 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT',
 'C:\\Program Files\\Git\\cmd',
 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
 'C:\\Users\\dalth\\.pyenv\\pyenv-win\\bin',
 'C:\\Users\\dalth\\.pyenv\\pyenv-win\\shims',
 'C:\\Users\\dalth\\AppData\\Local\\Microsoft\\WindowsApps',
 'C:\\Users\\dalth\\AppData\\Local\\Programs\\Microsoft VS Code\\bin',
 'C:\\Program Files (x86)\\GnuWin32\\bin']
```

Using conda I got as `PATH` env variable:

```
['C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf',
 'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Library\\mingw-w64\\bin',
 'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Library\\usr\\bin',
 'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Library\\bin',
 'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Scripts',
 'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\bin',
 'C:\\Users\\dalth\\anaconda3\\condabin',
 'C:\\Users\\dalth\\AppData\\Local\\Programs\\Spyder\\pkgs\\PyQt5\\Qt5\\bin',
 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS',
 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS',
 'C:\\Windows\\system32',
 'C:\\Windows',
 'C:\\Windows\\System32\\Wbem',
 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0',
 'C:\\Windows\\System32\\OpenSSH',
 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL',
 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL',
 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT',
 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT',
 'C:\\Program Files\\Git\\cmd',
 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
 'C:\\Users\\dalth\\.pyenv\\pyenv-win\\bin',
 'C:\\Users\\dalth\\.pyenv\\pyenv-win\\shims',
 'C:\\Users\\dalth\\AppData\\Local\\Microsoft\\WindowsApps',
 'C:\\Users\\dalth\\AppData\\Local\\Programs\\Microsoft VS Code\\bin',
 'C:\\Program Files (x86)\\GnuWin32\\bin']
```


Missing paths with micromamba:

```

'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf',
'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Library\\mingw-w64\\bin',
'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Library\\usr\\bin',
'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Library\\bin',
'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\Scripts',
'C:\\Users\\dalth\\anaconda3\\envs\\pyqt512-cf\\bin',
'C:\\Users\\dalth\\anaconda3\\condabin',

```

Checking the PyQt5 package seems like for PyQt 5.12 with Python 3.9 the related .dll files are located at `<env dir>/Library/bin` but for PyQt 5.15 with Python 3.9 they are available also at the package dir level `<env-dir>/Lib/site-packages/PyQt5/Qt5/bin` so I guess that's the reason PyQt 5.15 works and PyQt 5.12 fails to import. However, then I'm not totally sure what we should do (we could modify the `PATH` from our side with what is needed but not sure if there could be any other approach less intrusive and robust than that).

**Comment by mrclary** [comment] 2022-06-21 19:40
Yes, I can reproduce the error in [this comment](https://github.com/spyder-ide/spyder/issues/18003#issuecomment-1137482245).

> Checking the PyQt5 package seems like for PyQt 5.12 with Python 3.9 the related .dll files are located at <env dir>/Library/bin but for PyQt 5.15 with Python 3.9 they are available also at the package dir level <env-dir>/Lib/site-packages/PyQt5/Qt5/bin so I guess that's the reason PyQt 5.15 works and PyQt 5.12 fails to import. However, then I'm not totally sure what we should do (we could modify the PATH from our side with what is needed but not sure if there could be any other approach less intrusive and robust than that).

I'll look into what is going on with PATH. Environment variables passed to IPython Console should be exactly the same, regardless of whether micromamba or conda are used. Is it possible that conda adds those extra paths and micromamba does not?

**Comment by mrclary** [comment] 2022-06-22 00:39
@dalthviz, it turns out not to be an issue with micromamba, but an issue with the batch script I wrote. Apparently, when setting the variable `SCRIPT` in the logic statement, it cannot be expanded until after the entire logic statement is completed, so the `call %SCRIPT%` statement was just producing `call `. Moving it after the logic block results in the correct behavior with `%SCRIPT%` properly expanded.

#18387 should fix this issue.

@jtskowronek, sorry for the inconvenience.

**Closed** 2022-06-22 15:21 UTC
Labels: type:Bug, tag:Installer

**Comment by jtskowronek** [comment] 2022-10-11 08:22
Thanks for the patch suggestion. I'm not familiar with how to install
spyder from source, so I don't think I can test your patch until I do. I
don't have time to mess around with it this week, but maybe next week;
unless it's just a matter of running a few straightforward commands to
build an executable in Windows 10, then I might be up to try it sooner.
