### ISSUE TITLE
Spyder fails to start Git from Project pane

### ISSUE THREAD

**Issue by BurnNote** [spyder-ide/spyder#16163] opened 2021-08-06 09:57 UTC
## Problem Description
Trying to open Git from the Project Pane does not work (right click and then either "commit" or "browse repository"). Instead, the issue reporter pops up. This is the case for both options for opening it. 

The Git repository can be opened and worked with normally normally. 

The branch indicator and number of uncommited files showed normally and correctly until I tried to create a branch for testing it, at which point those indicators went away and it only shows blank:
![grafik](https://user-images.githubusercontent.com/38980850/128492626-8c184093-d4ca-46ab-8ae2-49f8f14b01a3.png)

The problem appeared after upgrading to spyder 5 from 4.1.3. It persists after restart and switching projects. 

## Versions
* Spyder version: 5.0.5
* Python version: 3.8.11 64-bit 
* Qt version: Qt 5.9.7
* PyQt version: PyQt5 5.9.2 
* Operating System name/version: Windows 10 
* Git: 2.22.0.windows.1
*spyder-kernels: 2.0.5

**Comment by ccordoba12** [comment] 2021-08-16 16:41
Hey @BurnNote, thanks for reporting. This is a duplicate of issue #15458 and fixed already in our latest release (5.1.1).

If you're using Anaconda, please be patient, it should be available there soon. You can also use our installers for Windows in the meantime:

https://github.com/spyder-ide/spyder/releases

**Closed by ccordoba12** 2021-08-16 16:41 UTC
