### ISSUE TITLE
Python 3.12 error

### ISSUE THREAD

**Issue by sh-shahrokhi** [spyder-ide/spyder#21515] opened 2023-11-11 19:27 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
error in ipython console after pointing spyder to 3.12 interpreter

### What steps reproduce the problem?

1. installed python 3.12 and spyder-kernels from pypi in a new env (named "np").
2. pointed spyder which is installed in a 3.10 env (named "img") to the interpreter in 3.12 env ("np").

### What is the expected output? What do you see instead?

this error in ipython console

An error ocurred while starting the kernel
The error is:
```
Traceback (most recent call last):
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2134, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_core\utils\__init__.py", line 173, in wrapped
return loop.run_until_complete(inner)
File "D:\Programs\mambaforge\envs\img\lib\asyncio\base_events.py", line 649, in run_until_complete
return future.result()
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_client\manager.py", line 96, in wrapper
raise e
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_client\manager.py", line 87, in wrapper
out = await method(self, *args, **kwargs)
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_client\manager.py", line 435, in _async_start_kernel
kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_client\manager.py", line 400, in _async_pre_start_kernel
kw = await self.provisioner.pre_launch(**kw)
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_client\provisioning\local_provisioner.py", line 198, in pre_launch
kernel_cmd = km.format_kernel_cmd(
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\jupyter_client\manager.py", line 307, in format_kernel_cmd
cmd = self.kernel_spec.argv + extra_arguments
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\spyder\plugins\ipythonconsole\utils\kernelspec.py", line 107, in argv
get_conda_activation_script(),
File "D:\Programs\mambaforge\envs\img\lib\site‑packages\spyder\utils\conda.py", line 95, in get_conda_activation_script
if osp.basename(exe).startswith('micromamba'):
File "D:\Programs\mambaforge\envs\img\lib\ntpath.py", line 242, in basename
return split(p)[1]
File "D:\Programs\mambaforge\envs\img\lib\ntpath.py", line 211, in split
p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType 
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please do not use it to run your code

>>> Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\workers\updates.py", line 116, in start
    channel, channel_url = get_spyder_conda_channel()
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 398, in _submit_to_github
    issue_text = self.render_issue(
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\widgets\reporterror.py", line 339, in render_issue
    proc = run_program(exe, args=args)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 257, in run_program
    fullcmd = find_program(program)
  File "D:\Programs\mambaforge\envs\img\lib\site-packages\spyder\utils\programs.py", line 129, in find_program
    if not basename.endswith(extensions):
AttributeError: 'NoneType' object has no attribute 'endswith'


```

## Versions

* Spyder version: 5.5.0
* Python version: 3.10.13
* Qt version: 5.15.8
* PyQt version: 5.15.9
* Operating System name/version: Windows 11 x64 (Displayed as 10)

### Dependenciesv

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.4.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.17.2 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.11.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  3.3.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.5 (OK)
pygments >=2.0                   :  2.16.1 (OK)
pylint >=2.5.0,<3.1              :  3.0.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.0 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=22.1.0                     :  25.1.1 (OK)

# Optional:
cython >=0.21                    :  3.0.5 (OK)
matplotlib >=3.0.0               :  3.8.1 (OK)
numpy >=1.7                      :  1.26.0 (OK)
pandas >=1.1.1                   :  2.1.3 (OK)
scipy >=0.17.0                   :  1.11.3 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

![image](https://github.com/spyder-ide/spyder/assets/107148416/b188ebbb-d565-4efa-96aa-3ddf3dcf08ca)

**Comment by ccordoba12** [comment] 2024-01-17 16:49
Hey @sh-shahrokhi, thanks for reporting and sorry for the late response. This is basically a duplicate of issue #20357 and it's caused by installing Mambaforge (in your case) in a non-standard location.

The only solution we can offer you for now is to install it in `C:\ProgramData`. However, we'll try to come up with a proper fix later during the year.

**Closed by ccordoba12** 2024-01-17 16:49 UTC
