### ISSUE TITLE
Copying nothing with Ctrl + C freezes and crashes Spyder

### ISSUE THREAD

**Issue by Chuck321123** [spyder-ide/spyder#21828] opened 2024-02-22 18:53 UTC
### Issue Report Checklist

Checklist checked

## Problem Description
So you can copy and paste pretty much anything in Spyder, but when you stand on a fresh line and hit Ctrl + C (without copying anything specific) it crashes Spyder.

### What steps reproduce the problem?

Hit Ctrl + C without copying anything

### What is the expected output?

That it doesnt crash Spyder

## Versions
* Spyder version: 5.5.0  (conda)
* Python version: 3.12.1 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  1.7.3 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.15.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.0 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=22.1.0                     :  25.1.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.2 (OK)
numpy >=1.7                      :  1.26.3 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  None (NOK)

```

**Comment by Chuck321123** [comment] 2024-02-24 13:44
@ccordoba12 I'll just upload a video where i demonstrate the bug. I have nothing on my script. Also, the bug still appears if i disable all plugins (except editor).

https://github.com/spyder-ide/spyder/assets/123987501/d2afb635-128f-4d99-b2ad-eb8f4316a4ea

**Comment by ccordoba12** [comment] 2024-02-25 17:49
Ok, thanks for the video. Unfortunately, I can't reproduce the problem on Linux.

Could post screenshots with the options you have in `Preferences > Editor`? Perhaps one or more of them are causing this bug.

**Comment by ccordoba12** [comment] 2024-03-12 00:38
Closing because I was unable to reproduce this.

**Closed by ccordoba12** 2024-03-12 00:38 UTC
Labels: status:Awaiting Followup

**Comment by Chuck321123** [comment] 2024-03-12 17:28
@ccordoba12 Weirdly, I can't reproduce it either anymore. I'll let you know if it happens again and I find the cause.
