### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings' when attempting to activate Automatic Connections for Help

### ISSUE THREAD

**Issue by LUNTSAI** [spyder-ide/spyder#6673] opened 2018-03-08 07:39 UTC
Cannot auto connect to the editor...
And the use of help always show "no document available"

**Comment by CAM-Gerlach** [comment] 2018-03-08 08:46
You've given us extremely little information to go on, but it sounds like an install issue of some sort. What do you mean by

> Cannot auto connect to the editor...

Please be clear and detailed.

Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Thanks, and best of luck!

**Comment by LUNTSAI** [comment] 2018-03-08 09:13
Sorry for my short problem description.
My "help" by press Ctrl + I work well in IPython console, however, when I tried to use this short cut in editor, it always showed the "No documentation available". 
I tried to Preference -> Help -> Automatic connection to select both editor and IPython console, but everytime I pressed apply, it showed the following message "Spyder has encounterd an internal problem".
Is it related to the problem of the fall lunch of Anaconda Navigator? (Today, I found my Anaconda cannot lunch, it shows psutil.AccessDenied pid = 8752)

**Comment by CAM-Gerlach** [comment] 2018-03-08 11:26
> My "help" by press Ctrl + I work well in IPython console, however, when I tried to use this short cut in editor, it always showed the "No documentation available".

This is a duplicate of a well known issue,  #2162 , that can be caused by a number of different proximate causes. Check out that thread for some fixes.

>  Is it related to the problem of the fall lunch of Anaconda Navigator?

Well, it is spring now...does it have a problem with breakfast and dinner as well?

All jokes aside, the latter isn't because I reproduced it just now. However, the former might be, if it is, then it is completely outside of Spyder' control and you should do a complete uninstall and reinstall of the latest version of Anaconda, You can also try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

> I tried to Preference -> Help -> Automatic connection to select both editor and IPython console, but everytime I pressed apply, it showed the following message "Spyder has encounterd an internal problem".

This is a new, separate issue, and although useless by itself without the error traceback it gave you, I was able to easily reproduce it by simply doing what you stated in the latest version of Spyder. The traceback (below) is very similar but not quite identical to #6519 , and the proximate trigger is different, so I'm not sure if it needs to be addressed separately. @ccordoba12 ?

File "C:\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

**Comment by ccordoba12** [comment] 2018-03-08 15:28
> The traceback (below) is very similar but not quite identical to #6519 , and the proximate trigger is different, so I'm not sure if it needs to be addressed separately. @ccordoba12 ?

The underlying cause is the same as the one reported on issue #6519, so this is fixed now and it'll be part of 3.2.8.

**Closed by ccordoba12** 2018-03-08 15:28 UTC
Labels: component:Preferences, type:Bug

**Comment by CAM-Gerlach** [comment] 2018-03-08 19:21
Great!

**Comment by LUNTSAI** [comment] 2018-03-09 13:09
Thanks all ~
Some kind of weird...
Maybe the short-cut of spyder went wrong for some reason...
After I reset my Anaconda and used it to lunch spyder, the problems were no longer exist.

**Comment by CAM-Gerlach** [comment] 2018-03-09 15:25
I explain the likely causes of each issue above.

The help/inspection issue is usually due to some particular or another of your install, so that's unsurprising.

The Anaconda Navigator issue certainly is, and has nothing to do with Spyder.

The help connection issue is related to another known bug, and will be fixed in the next release.
