### ISSUE TITLE
IPython terminal instances apparently leaking memory

### ISSUE THREAD

**Issue by eps82** [spyder-ide/spyder#5268] opened 2017-09-18 10:54 UTC
## Description of your problem

Closing an IPython tab does not seem to free any memory.

**What steps will reproduce the problem?**

1. Open Spyder on Windows
2. Open Windows Task Manager
3. Close IPython terminal so a new instance replaces it. Memory usage will keep going up by ~50MB every time.

**What is the expected output? What do you see instead?**

If the previous terminals are truly gone, I'd expect their memory usage to be gone. Are they still accessible from within the IDE? If so, how? They don't seem to be available.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4.dev0
* Python Version: 3.6.1
* Qt Version: 5.8.0
* PyQt Version: 5.8.1
* Operating system: Windows 7
* Distribution: WinPython-64bit-3.6.1.0Qt5

## Dependencies

jedi >=0.9.0     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-09-18 22:53
> Memory usage will keep going up by ~50MB every time.

And what is the observed result in your case? Sorry, but you don't say anything about it.

**Comment by eps82** [comment] 2017-09-19 05:31
Sorry, I think one of us is misunderstanding. I meant to say that <i>is</i> the observed result. Every time I close a terminal and a new one replaces it memory usage increases, cumulatively, because apparently the old one isn't freed.

**Comment by ccordoba12** [comment] 2017-09-19 13:23
But where are you observing the increase in memory? In the main Spyder process? Because when you close an IPython console, the process associated with it is completely killed.

**Comment by eps82** [comment] 2017-09-19 13:36
I don't know which process it is, as there are several "pythonw.exe" instances I can't tell apart (I'm not familiar with Spyder's hierarchy either). Whichever it is, it's the biggest one, and it becomes evident after doing it several times. I'm now on a different computer and it has the same behaviour although the memory increase is smaller (~10MB).

**Comment by ccordoba12** [comment] 2017-09-19 13:39
> Whichever it is, it's the biggest one

Ok, that should be the Spyder one. We'll take a look at this after we release 3.2.4.

Thanks for reporting, we were unaware of this problem.

**Comment by ccordoba12** [comment] 2017-11-26 17:24
Let's merge this one as a duplicate of issue #5830.

**Closed by ccordoba12** 2017-11-26 17:24 UTC
Labels: component:IPython Console, type:Bug
