### ISSUE TITLE
Auto indentation may include too many indents

### ISSUE THREAD

**Issue by brodders61** [spyder-ide/spyder#4167] opened 2017-02-18 09:30 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. use Spyder editor, hit return
2. either will be OK or persistently:
3. generates multiple (excessive) indents 
4. once suffering this effect, Sypder uses it consistently as if auto-indent has got wrong idea where things should be and wants to stick to that opinion

Example
```
for some text:
   working normally
                                    suddenly borked
   user del's to here but on next RETURN
                                    back to here again, forever on every RETURN
```

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.13 64bit
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Win 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment] 2017-02-18 15:17
Thanks for reporting. This is a duplicate of issue #4096.

**Closed by ccordoba12** 2017-02-18 15:17 UTC
