### ISSUE TITLE
Spyder 5: KeyError traceback messages get printed as new input in console

### ISSUE THREAD

**Issue by waeiski** [spyder-ide/spyder#15155] opened 2021-04-07 07:19 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
![Screenshot_20210407_094303](https://user-images.githubusercontent.com/31708782/113824292-4a21af00-9788-11eb-81fa-6f5637cb4280.png)

Traceback messages related to reading .yaml files such as the one in the screenshot get printed as 'input' in the ipython console. It has to be deleted using backspace (or highlighting + backspace) before any new lines can be written into ipython console. Also, the traceback seems to be cut off early. I've created a few environments with miniconda + spyder 5 and the problem persists in all of them. No similar errors in Spyder 4, which is why I'm thinking it has something to do with Spyder rather than the other libraries I use.

Maybe the error message is somehow escaping from where it should be?

This error is not catastrophic, just annoying. The new Spyder works and looks fine otherwise on my end, thanks!

### What steps reproduce the problem?

1. conda create --name myenv
2. conda install spyder
3. spyder
4. read a nonexistent .yaml config file (I'm using searchtweets-v2 library from Twitter to read .yaml configs)

### Paste Traceback/Error Below (if applicable)

```python-traceback

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.2
* Qt version:  5.12.9
* PyQt version: 5.12.3
* Operating System name/version: 5.10.23-1-MANJARO

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment] 2021-04-07 16:44
Hey @waeiski, thanks for reporting. Please post a simple and reproducible code example, so we can test this in our side.

**Comment by waeiski** [comment] 2021-04-08 06:52
Okay here goes.


Here's my environment setup: 

1. `conda create --name myenv`
2. `conda activate myenv`
2. `conda install -c conda-forge spyder`
3. `conda install -c conda-forge geopandas`
4. `conda install -c conda-forge seaborn`
5. `pip install searchtweets-v2`
6. `spyder`

Then here's the part throwing the weird error if not searching for in the right directory. This happens with both `load_credentials()` and `read_config()`.

```
from searchtweets import read_config, load_credentials

# load twitter keys
search_cred = load_credentials('.twitter_keys.yaml',
                               yaml_key = 'search_tweets_v2',
                               env_overwrite = False)

# load configuration for search query
config = read_config('search_config.yaml')

```

**Comment by ccordoba12** [comment] 2021-04-08 17:21
Thanks @waeiski! But what's in `.twitter_keys.yaml` and `search_config.yaml`? Without knowing what to put in those file we won't be able to run your code.

**Comment by waeiski** [comment] 2021-04-12 06:43
Hi @ccordoba12, it doesn't matter what's in those files, the error occurs in this case when the function is trying to find a .yaml file that isn't there. E.g. If my current working directory doesn't contain the file `.twitter_keys.yaml` and I try to read it into `search_creds` then the traceback message gets printed as an input in the console.

But if it helps here's the basic structure for both.

.twitter_keys.yaml:

```
search_tweets_v2:
  endpoint: https://api.twitter.com/2/tweets/search/all
  consumer_key: your_consumer_key
  consumer_secret: your_super_secret_consumer_secret
  bearer_token: your_magic_token
```

and for search_config.yaml:

```
search_rules:
    query: place_country:IS
    tag: iceland_test

search_params:
    results-per-call: 500
    max-tweets: 1000000

output_params:
    filename_prefix: iceland_test
    results_per_file: 100000
```

**Comment by ccordoba12** [comment] 2024-01-04 22:22
Closing because the reported errors don't seem to come from Spyder.

**Closed by ccordoba12** 2024-01-04 22:22 UTC
Labels: type:Bug, component:IPython Console
