### ISSUE TITLE
Line Number and line don't align on OSX

### ISSUE THREAD

**Issue by spacegoing** [spyder-ide/spyder#2721] opened 2015-09-27 05:48 UTC
![screen shot 2015-09-27 at 3 47 35 pm](https://cloud.githubusercontent.com/assets/5180020/10121447/1de3d990-652f-11e5-9638-d307214188f2.png)

**Comment by ccordoba12** [comment] 2015-09-28 01:30
This is a duplicate of issue #2296.

**Closed by ccordoba12** 2015-09-28 01:30 UTC
Labels: duplicate
