### ISSUE TITLE
After the variables are sorted, the index will not change(Pandas), and the size will be disordered(dict)

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#14182] opened 2020-11-10 04:00 UTC
## Problem Description
When pandas.DataFrame and pandas.Series variables are sorted, the row index will not change accordingly.
When dict type variables are sorted by size, the size is out of order.

![spyder变量](https://user-images.githubusercontent.com/1759365/98626069-db146b80-234b-11eb-9adb-9b41ca6beb9e.gif)

## Versions

* Spyder version: 4.2.0
* Python version: 3.7.6
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: win10

**Comment by ccordoba12** [comment] 2020-11-10 19:19
Hey @leavor, thanks for reporting. This is a duplicate of issue #13544 and we'll fix it in our next release.

**Closed by ccordoba12** 2020-11-10 19:19 UTC
