### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by hieroPhant** [spyder-ide/spyder#7411] opened 2018-07-08 17:58 UTC
### What steps will reproduce the problem?

installed some upgrades in Anaconda and others in Shell

### Traceback
```python-traceback
  File "/Users/benito/anaconda3/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/benito/anaconda3/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/benito/anaconda3/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/benito/anaconda3/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/Users/benito/anaconda3/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/Users/benito/anaconda3/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/benito/anaconda3/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/benito/anaconda3/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.15
* Qt version: 4.8.7
* PyQt4 (API v2) version: 4.11.4
* Operating system: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.5.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
psutil >=0.3      :  5.4.6 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-07-08 19:57
This is a dupliacate of issue #6335. Unfortunately, it's a bug in Python itself and although it was fixed in Python **3.6.5**, it was not backported to Python 2.7.

So you have two options:

1. Move to use Python >= 3.6.5
2. Patch Python 2.7 yourself. You'll find the necessary code in issue mentioned above, but you won't get any further help from us because (as I said) this is not a bug in Spyder.

**Closed by ccordoba12** 2018-07-08 19:57 UTC
