### ISSUE TITLE
"Python quit unexpectedly" when Mac goes to sleep

### ISSUE THREAD

**Issue by MarkMoulton** [spyder-ide/spyder#6234] opened 2018-01-17 17:26 UTC
## Description of your problem
I leave spyder open and step away and my Mac goes to sleep.  Returning, I get the message "Python quit unexpectedly",  requiring that I restart spyder.  Fortunately, spyder remembers where I left off. Upgrading to the most recent versions of spyder and anaconda doesn't seem to help.  Unfortunately, the problem is intermittent (though frequent), and I have trouble reproducing it.  It may have to do with how long the computer is sleeping.

**What steps will reproduce the problem?**

1. Work in spyder
2. Let computer sleep a few hours
3. Reawaken computer

* Spyder Version:  3.2.6
* Python Version:  2.7.14
* Qt Version:  5.6.2
* PyQt Version:  5.6.0
* Operating system:  MacOS 10.13.2 (High Sierra)

**Comment by CAM-Gerlach** [comment] 2018-01-17 20:23
Thanks for reporting. Perhaps it has something to do with #5613 ? Or, perhaps known issues with Qt/PyQt on macOS High Sierra outside of our control? Can you run Spyder from the Terminal with ``spyder --debug`` and see if anything interesting prints to the Console before/when it crashes?

**Comment by MarkMoulton** [comment] 2018-01-17 23:42
Thanks, CAM-Gerlach.  Issue #5613 does sound similar, except in my case spyder just crashes.  I couldn't run "spyder --debug" from the terminal, probably due to being clueless (see below), but spyder alone yields a few warnings.

Mark

Markm-iMac:~ markhmoulton$ spyder --debug
Usage: spyder [options] files

spyder: error: no such option: --debug
Markm-iMac:~ markhmoulton$ spyder -debug
Usage: spyder [options] files

spyder: error: no such option: -d
Markm-iMac:~ markhmoulton$ spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by CAM-Gerlach** [comment] 2018-01-18 00:43
I assumed it would be the same on non-Windows platforms since it is already following the standard *nix command line syntax rather than the horrible windows ones, but I guess not. In any case, you can do it via setting the environment variable ``SPYDER_DEBUG=3`` first before you launch ``spyder`` from the command line.

It could also be something funky with your Anaconda install, so please try a clean uninstall/reinstall and the other steps in our [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections and see if it reoccurs. Finally, as mentioned previously, it could have some issues due to incomplete support in Qt/PyQt for 10.13, which we have no control over unfortunately.

**Comment by MarkMoulton** [comment] 2018-01-18 18:39
I did a clean uninstall/reinstall of Anaconda, but that didn't fix the issue.  I think the problem might be that my python scripts are sort of in the cloud (Google drive, though a local synced copy is kept), and they are left open when my machine goes to sleep.  When working on local scripts I seem to be okay, but more experiments are necessary.

**Comment by MarkMoulton** [comment] 2018-01-18 22:28
No, my hypothesis about running scripts from Google drive wasn't borne out.  I got "Python quit unexpectedly" even with a local script.  My machine was asleep for around 1.5 hours.

**Comment by CAM-Gerlach** [comment] 2018-01-18 23:34
Okay, thanks for following up. Can you start in ``DEBUG`` mode as requested above, watching carefully for any console output between when you left it and when it crashes, as well as go through the other steps in the linked sections of the troubleshooting guide? Otherwise, there isn't much we can do if we can't reproduce it. Also, BTW, that warning is harmless and can be ignored, just FYI.

**Comment by MarkMoulton** [comment] 2018-01-19 22:49
Below are what I believe are the relevant console outputs before and after a crash.  

Unrelated observation:  When starting up this morning I did not get the crash message and noticed that one of my scripts in spyder had not been saved.  Could this have prevented the crash somehow?

Mark

Last login: Fri Jan 19 12:18:32 on ttys001
Markm-iMac:~ markhmoulton$ SPYDER_DEBUG=3
Markm-iMac:~ markhmoulton$ spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
/Users/markhmoulton/anaconda2/bin/pythonw: line 3:  3431 Segmentation fault: 11  /Users/markhmoulton/anaconda2/python.app/Contents/MacOS/python "$@"
Markm-iMac:~ markhmoulton$ spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by CAM-Gerlach** [comment] 2018-01-20 00:23
Thanks again for the followup. My comments:

> ``Markm-iMac:~ markhmoulton$ SPYDER_DEBUG=3``

Sorry, been using too much of other shells lately; Spyder didn't start in debug mode or you'd see a bunch of messages. You need ``export SPYDER_DEBUG=3`` to actually set the variable in the environment.

> ``[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0``

As mentioned previously, this warning is spurious, unrelated to Spyder and can be ignored; see #3730 for more on that.

> ``/Users/markhmoulton/anaconda2/bin/pythonw: line 3: 3431 Segmentation fault: 11 /Users/markhmoulton/anaconda2/python.app/Contents/MacOS/python "$@"``

This is the actual error, in case you weren't aware. However, the simple fact that it was a segfault doesn't tell us too much by itself without knowing what Spyder was doing at the time, which is what debug mode should hopefully give us some clue into. 

However, it is quite useful in that it appears to be the return of #3732 seen on OG Sierra for High Sierra, as the behavior (segfaults on sleep with the latest macOS version and an older Qt version) appears to be identical, other than the OS and Qt versions being one more recent. Therefore, please try updating Qt and PyQt to the latest versions with ``conda update qt pyqt``, which will hopefully resolve it. 

If not, again, please reference my first post and go through the steps of the aforementioned Troubleshooting Guide (one of which would have been this one), which fixes most crashes.

> Unrelated observation: When starting up this morning I did not get the crash message and noticed that one of my scripts in spyder had not been saved. Could this have prevented the crash somehow?

Interesting; its possible. However, without debug output and more repeated testing, no way to really know for sure.

**Comment by CAM-Gerlach** [comment] 2018-01-20 00:36
> Therefore, please try updating Qt and PyQt to the latest versions with conda update qt pyqt, which will hopefully resolve it.

Actually, scratch that; Qt/PyQt 5.9.x (much less 5.10.x) isn't on conda; you should have the latest available. Still, ``conda update qt pyqt qtpy`` doesn't hurt. You can install them manually with the installer or with ``pip``, but that's a bit of a pain and can easily break your existing installation if you're not careful. Therefore, I recommend you try the other steps in the troubleshooting guide and see if that resolves it, and have the debug flag turned on per above in case it doesn't so we can find out more. Thanks.

**Comment by MarkMoulton** [comment] 2018-01-20 04:58
Thanks for dogging this.  See attached debug_log.txt.  A lot of starting and restarting and timing out.  My conda qt, pyqt, and qtpy were up to date.
Mark

[debug_log.txt](https://github.com/spyder-ide/spyder/files/1648574/debug_log.txt)

**Comment by CAM-Gerlach** [comment] 2018-01-20 05:12
Yeah, that actually helps with #5613 though I'm not quite sure what to do about it. However, there's nothing that directly suggests what's happening with the segfault, other than something with Qt which is the probable issue and outside our control. Did it happen again with an open/unsaved file? Also, I know I've mentioned this a few times so please let me know if you have so I stop nagging you, but please go through all the steps in the aforementioned sections of the troubleshooting guide to make sure none of that resolves it. Thanks.

**Comment by MarkMoulton** [comment] 2018-01-21 03:52
I did _most_, but not all, of the steps suggested in the trouble-shooting guide, including a clean uninstall and reinstall, with subsequent updates.  I think the only thing I didn't do is the "reset", which seemed unnecessary in light of the reinstall.  

Interesting data point:  I did another experiment  leaving an open spyder file unsaved, and again no crash message.  So I think there is definitely something there.

**Comment by CAM-Gerlach** [comment] 2018-01-21 04:34
Okay, thanks. Both the **Basic Troubleshooting** and the **Emergency CPR** sections, right? Also, ``spyder --reset`` is probably still a good idea just in case, since I'm not sure if uninstall/reinstall actually resets the preferences and other config/saved state files since they are stored completely separately from your actual Spyder installation.

> Interesting data point: I did another experiment leaving an open spyder file unsaved, and again no crash message.

Interesting indeed, thanks. Not sure exactly what to make of it without a trace of some sort on the error, except that it suggests an open/unsaved file either prevents something from running that is dropping an error after a while, or preempts it.

> Resource temporarily unavailable
Errored [fallback, rope, or jedi]

Yes, this is related to the timeout issue with code completion/help/introspection stopping working after sleep (or lockscreen, at least on windows), but I'm not sure if it contributes to your problem or not.

I wish I had more for you, but with what limited information we have and without easy access to a Mac running High Sierra to test and reproduce this on, I'm not sure how much more we can do without at least a full debug trace of the actual error crashing the program, and even so, the most likely source at the moment is something upstream in ``qt`` or ``pyqt`` related to High Sierra that we have no control over. However, keep us up to date, and there is always a chance someone here with far more experience than I will have some better insight. Best of luck!

**Comment by MarkMoulton** [comment] 2018-01-21 04:49
Thanks, CAM-Gerlach.

I think I covered most of the trouble-shooting steps in the docs, but I'll sweep through and try whatever I missed and let you know if anything changes.  For what it's worth, the "Resource temporarily unavailable" message is still printing out on my terminal an hour later.  

You've been extremely helpful with all this.  Fortunately, it's only a minor inconvenience.  I just wanted to make sure the issue got added to the record.

Mark

**Comment by CAM-Gerlach** [comment] 2018-01-21 05:39
Thanks very much for doing so. The

> Resource temporarily unavailable

message with regard to ``jedi``/``rope`` etc. will presumably occur continuously after the machine has woken from sleep, as these are never successfully initialized after timing out during sleep as discussed elsewhere. No idea if it is related; it happens on Windows, Mac, and IIRC Linux as well, but doesn't cause an application crash, just loss of completion/introspection/help functionality until Spyder is restarted.

**Comment by ccordoba12** [comment] 2018-01-21 15:56
> as these are never successfully initialized after timing out during sleep as discussed elsewhere

The problem is I don't see this on Linux, so I can't reproduce it nor fix it, sorry.

**Comment by ccordoba12** [comment] 2018-01-21 15:56
Sorry, I closed the issue by mistake.

**Comment by jlindsey1** [comment] 2018-02-14 20:43
I have also just started experiencing this issue since upgrading to macOS 10.13.3 with Spyder 3.2.6. 

Is there any information I could provide to help with this issue? Just throwing the offer out if needed.

**Comment by CAM-Gerlach** [comment] 2018-02-14 23:47
Thanks for your offer @jlindsey1 . It seems likely the problem has something to do with Qt/PyQt 5.6.x not being fully compatible with High Sierra, and Anaconda still not moving to a more recent version. In that case, unfortunately there isn't much to be done except wait for High Sierra to be supported by them, as we don't really have any control over that.

**Comment by jlindsey1** [comment] 2018-02-15 10:57
No worries @CAM-Gerlach , feel free to reach out if you need any support at some point.

**Comment by ccordoba12** [comment] 2019-10-15 00:03
This should be fixed now due to our rewrite of our completion and linting architecture, which will be available in Spyder 4 (to be released in a month or so).

**Closed by ccordoba12** 2019-10-15 00:03 UTC
Labels: OS:MacOS, status:Awaiting Followup
