### ISSUE TITLE
"TypeError: decoding Unicode is not supported" when debugging

### ISSUE THREAD

**Issue by greenorca** [spyder-ide/spyder#2277] opened 2015-03-26 08:05 UTC
## Description
After updating to Spyder2.3.4, I notice some strange behavior:
* running a script (F5) that loads other modules works fine
* running the same script (F5) with an additional line "pdb.set_trace()" will produce the above error
* the line position of the pdb call doesn't matter
* running the same script in a standalone ipython console works well (including the pdb call)

I haven't seen this behavior in previous versions of Spyder
* *What is the expected output? What do you see instead?*

* *Please provide any additional information below*
using xubuntu14.04
If I can provide any further info, pls let me know.
Thanks a lot for providing the cool Spyder IDE!

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.6
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies

pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=1.0   :  2.2.0 (OK)
zmq >=2.1.11    :  14.0.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.3b2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
jedi >=0.8.1    :  0.8.1-final0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.3   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

**Comment by Nodd** [comment] 2015-03-26 08:12
I can't reproduce it with master branch on Arch Linux. I didn't try with 2.3.4

Is there a full stack trace in addition to the line in the title ?

**Comment by greenorca** [comment] 2015-03-26 08:18
I've never seen this issue with previous versions of Spyder (2.2, 2.3.3...)
Is that the stack trace you want:

  File "<ipython-input-13-b9ce967c29ed>", line 1, in <module>
    runfile('/mnt/data/Research/001_Tegut/Python/AgentSystem_003_paper/opti_ants_V2_006_bastel.py', wdir='/mnt/data/Research/001_Tegut/Python/AgentSystem_003_paper')

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/mnt/data/Research/001_Tegut/Python/AgentSystem_003_paper/opti_ants_V2_006_bastel.py", line 42, in <module>
    res = wh.optimizeDeliveryTimeFrame()

  File "/mnt/data/Research/001_Tegut/Python/AgentSystem_003_paper/opti_ants_V2_006_bastel.py", line 42, in <module>
    res = wh.optimizeDeliveryTimeFrame()

  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)

  File "/usr/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)

  File "/usr/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 488, in interaction
    self.notify_spyder(frame) #-----Spyder-specific-------------------------

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 432, in notify_spyder
    fname = unicode(fname, "utf-8")

TypeError: decoding Unicode is not supported

**Comment by greenorca** [comment] 2015-03-26 08:30
Addon: just installed pyflakes, pep8 and pylint using pip.
Odd behavior still the same.
Above used scripts were working well with Spyder 2.3.3

**Comment by greenorca** [comment] 2015-03-26 08:34
Solution: cleared all Spyder breakpoints (many existed in the module that was called). Now script runs fine with the pdb.set_trace() line and new breakpoints set up in the submodules.

Sorry for bothering, thanks a lot!
:-)

**Comment by ccordoba12** [comment] 2015-03-26 16:17
Grrr, another error that I didn't noticed. It'll be fixed in 3.0 now ;-)

**Closed** 2015-03-26 16:27 UTC
Labels: Debugger

**Comment by greenorca** [comment] 2015-03-26 21:31
Incredible response time :+1: 
Anyway, clearing the bulk of breakpoints that were set in the modules with the previous version of Spyder (2.3.3) solved the issue.
Thanks a lot
