### ISSUE TITLE
Spyder 5 - It says I have a missing dependency: spider-kernels missing or not >=2.01 and < 2.1.0. But is is there

### ISSUE THREAD

**Issue by galiloe** [spyder-ide/spyder#15294] opened 2021-04-15 11:58 UTC
### Issue Report Checklist

* [y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [y] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [y] Tried basic troubleshooting (if a bug/error)
    * [y] Restarted Spyder
    * [y] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [y] Tried the other applicable steps from the Troubleshooting Guide
* [y] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have installed Spyder 5 on Windows 10x64, using the standard Spyder5.exe install provided by Spyder. When I starte Spyder I get an error box with the following message

     # Mandatory:
     spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)
 
As you can see a valid version of spyder-kernels IS installed. This seems to a be a spurious error message

I';ve pasted the dependencies below. As you can see,they are all met, yet Spyder 5 is incorrectly showing the spyder-kernels dependency as not met. The fact that the console works shows a valid version is installed.

As I said this appears to be a spurious error message.

### What steps reproduce the problem?

1. This happens on a pure vanilla install of Spyder 5 from the exe file supplied by Spyder
2. It happens every time I start Spyder 5
3. Doing a reset does that get rid of this error

### What is the expected output? What do you see instead?

Given I have a valid version of spyder-kernels installed, I would not to see this error box.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5
* Python version: 3.7 (came with Spyder 5)
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 x64

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)

```
PASTE DEPENDENCIES HERE
```

**Comment by CristinaMadrid** [comment] 2021-04-15 15:34
I am having the same issue but with paramiko instead. It asks to install >=2.4 but 2.7.2 is installed in an environment I created for QGIS. here the result of conda list:

# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0  
appdirs                   1.4.4                      py_0  
argh                      0.26.2                   py37_0  
arrow                     0.13.1                   py37_0  
astroid                   2.5              py37haa95532_1  
async_generator           1.10             py37h28b3542_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py37he774522_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py37h2bbff1b_1003  
bzip2                     1.0.8                he774522_0  
ca-certificates           2021.4.13            haa95532_1  
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2020.12.5        py37haa95532_0  
cffi                      1.14.5           py37hcd4344a_0  
cfitsio                   3.470                he774522_6  
chardet                   4.0.0           py37haa95532_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
colorama                  0.4.4              pyhd3eb1b0_0  
cookiecutter              1.7.2              pyhd3eb1b0_0  
coverage                  5.5              py37h2bbff1b_2  
cryptography              3.4.7            py37h71e12ea_0  
curl                      7.76.1               hf1763fc_0    conda-forge
decorator                 5.0.6              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
docutils                  0.17             py37haa95532_1  
entrypoints               0.3                      py37_0  
exiv2                     0.27.1               hfa2c1cf_0    conda-forge
expat                     2.3.0                h6c2663c_2  
flake8                    3.9.0              pyhd3eb1b0_0  
fontconfig                2.13.1            h1989441_1005    conda-forge
freetype                  2.10.4               hd328e21_0  
freexl                    1.0.6                h2bbff1b_0  
future                    0.18.2                   py37_1  
gdal                      3.2.2            py37h3a36fe1_2    conda-forge
geos                      3.9.1                h6c2663c_0  
geotiff                   1.6.0                h8e90983_5    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
gsl                       2.6                  hdfb1a43_2    conda-forge
hdf4                      4.2.13               h712560f_2  
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
httplib2                  0.19.1             pyhd8ed1ab_0    conda-forge
icu                       68.1                 h6c2663c_0  
idna                      2.10               pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        3.10.0           py37haa95532_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
inflection                0.5.1            py37haa95532_0  
intel-openmp              2020.2                      254  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.22.0           py37hd4e2768_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
jedi                      0.17.2           py37haa95532_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_2  
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_core              4.7.1            py37haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
kealib                    1.4.14               h96bfa42_2    conda-forge
keyring                   22.3.0           py37haa95532_0  
krb5                      1.17.1               hc04afaa_0  
lazy-object-proxy         1.6.0            py37h2bbff1b_0  
libblas                   3.9.0                     8_mkl    conda-forge
libboost                  1.67.0               hd9e427e_4  
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_0    conda-forge
libcurl                   7.76.1               hf1763fc_0    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.2.2                h48ef39c_2    conda-forge
libglib                   2.68.1               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0                he5f2a48_4  
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h2a8f88b_0  
libpq                     13.1                 h4f54205_2    conda-forge
libprotobuf               3.15.8               h7755175_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h62dcd97_0  

libspatialindex           1.9.3                h6c2663c_0  
libspatialite             5.0.1                h6b539a6_4    conda-forge
libssh2                   1.9.0                h7a1dbc1_1  
libtiff                   4.2.0                hc10be44_0    conda-forge
libwebp                   1.2.0                h2bbff1b_0  
libwebp-base              1.2.0                h2bbff1b_0  
libxml2                   2.9.10               hb89e7f3_3  
libxslt                   1.1.34               he774522_0  
libzip                    1.7.3                hfed4ece_0    conda-forge
lz4-c                     1.9.3                h2bbff1b_0  
markupsafe                1.1.1            py37hfa6e2cd_1  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4           py37hfa6e2cd_1001  
mkl                       2020.4             hb70f87d_311    conda-forge
mkl-service               2.3.0            py37h196d8e1_0  
mkl_fft                   1.3.0            py37h46781fe_0  
mkl_random                1.1.1            py37h47e9c7a_0  
mock                      4.0.3              pyhd3eb1b0_0  
mypy_extensions           0.4.3                    py37_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
nose2                     0.9.2                      py_0    conda-forge
numpy                     1.19.2           py37hadc3359_0  
numpy-base                1.19.2           py37ha3acd2a_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
openjpeg                  2.4.0                h48faf41_0    conda-forge
openssl                   1.1.1k               h2bbff1b_0  
owslib                    0.23.0             pyhd3eb1b0_0  
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.12                 haa95532_0  
pandocfilters             1.4.3            py37haa95532_1  
**paramiko                  2.7.2                      py_0**  
parso                     0.7.0                      py_0  
pathspec                  0.7.0                      py_0  
pcre                      8.44                 ha925a31_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       21.0.1           py37haa95532_0  
pixman                    0.40.0               he774522_0  
plotly                    4.14.3             pyhd3eb1b0_0  
pluggy                    0.13.1           py37haa95532_0  
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 h0f1a9bc_2    conda-forge
poyo                      0.5.0              pyhd3eb1b0_0  
proj                      8.0.0                h1cfcee9_0    conda-forge
prompt-toolkit            3.0.17             pyh06a4308_0  
psutil                    5.8.0            py37h2bbff1b_1  
psycopg2                  2.8.6            py37hd8e9650_2    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycparser                 2.20                       py_2  
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  
pylint                    2.7.4            py37haa95532_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pynacl                    1.4.0            py37h62dcd97_1  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyproj                    3.0.1            py37h66f9032_1    conda-forge
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
pyqtwebkit                5.212            py37h9e7b984_1    conda-forge
pyrsistent                0.17.3           py37he774522_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.0                hea74fb7_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-slugify            4.0.1                      py_0  
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pywin32                   227              py37he774522_1  
pywin32-ctypes            0.2.0                 py37_1001  
pyyaml                    5.4.1            py37h2bbff1b_1  
pyzmq                     20.0.0           py37hd77b12b_1  
qca                       2.2.1                hd7ce7fb_3    conda-forge
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qgis                      3.18.1           py37h7913d5c_1    conda-forge
qjson                     0.9.0             hd7ce7fb_1006    conda-forge
qscintilla2               2.11.2           py37h9e7b984_4    conda-forge
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtkeychain                0.12.0               h552f0f6_0    conda-forge
qtlocation                5.12.9               ha925a31_0    conda-forge
qtpy                      1.9.0                      py_0  
qtwebkit                  5.212                hb258684_1    conda-forge
qwt                       6.1.6                h552f0f6_0    conda-forge
qwtpolar                  1.1.1                hd7ce7fb_7    conda-forge
regex                     2021.4.4         py37h2bbff1b_0  
requests                  2.25.1             pyhd3eb1b0_0  
retrying                  1.3.3                    py37_2  
rope                      0.18.0                     py_0  
rtree                     0.9.7            py37h2eaa2aa_1  
setuptools                52.0.0           py37haa95532_0  
six                       1.15.0           py37haa95532_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
sphinx                    1.8.5                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    5.0.0            py37haa95532_1  
spyder-kernels            2.0.1            py37haa95532_0  
sqlite                    3.35.4               h2bbff1b_0  
testpath                  0.4.4              pyhd3eb1b0_0  
text-unidecode            1.3                        py_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tiledb                    2.2.7                hf84e3da_0    conda-forge
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.10               he774522_0  
toml                      0.10.2             pyhd3eb1b0_0  
tornado                   6.1              py37h2bbff1b_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py37h2bbff1b_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py37hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  1.0.2            py37haa95532_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wheel                     0.36.2             pyhd3eb1b0_0  
whichcraft                0.6.1              pyhd3eb1b0_0  
win_inet_pton             1.1.0            py37haa95532_0  
wincertstore              0.2                      py37_0  
wrapt                     1.12.1           py37he774522_1  
xerces-c                  3.2.3                ha925a31_0  
xz                        5.2.5                h62dcd97_0  
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.3                ha925a31_3  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h62dcd97_4  
zstd                      1.4.9                h19a0ad4_0

**Comment by ccordoba12** [comment] 2021-04-15 15:59
Hey @galiloe and @CristinaMadrid, this is a duplicate of issue #15091 and it'll be fixed in our next version (5.0.1), to be released shortly.

**Closed by ccordoba12** 2021-04-15 15:59 UTC

**Comment by galiloe** [comment] 2021-04-15 16:34
Hi @ccordoba12,

Thanks for the update. I apologize for setting up a new issue. I did try searching to see if it existed already, but I didn't find anything.

Mike

**Comment by ccordoba12** [comment] 2021-04-15 16:54
No worries, it's fine.

**Comment by CristinaMadrid** [comment] 2021-04-15 19:31
Same here. Thanks Carlos!
