### ISSUE TITLE
Spyder console converting FileNames to lowercase on Windows

### ISSUE THREAD

**Issue by Dollarius** [spyder-ide/spyder#20127] opened 2022-11-29 08:12 UTC
## Problem Description
Since (about) June this year, spyder console on Windows converts the .py scriptname into lowercase.
This is a serious problem for me because I need to use the .py scriptname to generate output files, with the same case.
I know that Windows is case insensitive, but the file I generate are to be used (also) on Unix machines, which are case sensitive.

### What steps reproduce the problem?
Running the file "CasePreservationTest.py" containing the simple code:
```
import time
print('Result: '+__file__)
time.sleep(5)
```

1. as a standalone .py file: `Result: D:\CasePreservationTest.py`
2. from spyder console: `Result: d:\casepreservationtest.py`

### What is the expected output?
spyder console should preserve the filename case:
CasePreservationTest.py <-- AND NOT --> casepreservationtest.py

Is it possible to restore the original behaviour (i.e., case preservation)?
Is there a new method for getting the case-preserved script name?

## Versions
Python 3.9.4 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Windows 11

**Comment by dalthviz** [comment] 2022-11-30 18:27
Hi @Dollarius thank you for the feedback! I was able to reproduce this. Maybe something is done over `spyder-kernels` when running code @ccordoba12 @impact27 to change `__file__` ?

**Comment by impact27** [comment] 2022-12-01 06:12
The problem here is that the debugger (pdb) normalises the filenames, so there are other issues linked to path capitalisation. Your use case is an edge case and the current behaviour looks reasonable to me. I would suggest that you don't rely on __file__ to find a script capitalisation on windows, but instead implement something with `os.listdir`.
Of course if you have ideas on how to improve on the current behaviour and are willing to open a PR, I would be happy to discuss.

**Comment by Dollarius** [comment] 2022-12-01 06:27
@impact27 and @dalthviz Thank you very much for your input!
It seemed like a (newly introduced) bug to me, but if the new behaviour is intended, I just found the following workaround:
```
import time, os
print('Bad result: '+__file__)
print('Good result: '+os.path.basename(os.path.realpath(__file__)))
time.sleep(5)
```

Which, from the file CasePreservationWorkAround.py, produces the following output:
```
Bad result: d:\casepreservationworkaround.py
Good result: CasePreservationWorkAround.py
```

This workaround satisfies my needs, so thank you very much for your suggestions.
I hope that the library os.path will keep the present behaviour also in the future.

**Comment by dalthviz** [comment] 2022-12-01 19:59
Glad to hear that you found a workaround @Dollarius ! Following @impact27 explanation I'm closing this for now as wontfix (since the normalization is done to prevent more issues while debugging) but if you have further comments or suggestions let us know!

**Closed by dalthviz** 2022-12-01 19:59 UTC
Labels: component:IPython Console, status:Awaiting Followup, status:Reproduced
