### ISSUE TITLE
"Go to definition" not working for files in the same folder

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#14604] opened 2021-01-17 10:00 UTC
This issue may be similar to another issue that I submitted before (https://github.com/spyder-ide/spyder/issues/13523).

**Expected behavior:**

When pressing "Ctrl + G" (or "Cmd + G") on a function name in the editor, and when this function is not defined in the current script, Spyder should take me to that function's definition in another file.

**Actual behavior:**

If the function's definition is in the current working directory, then Spyder does not take me to its definition.  Only when the function is defined in another folder does Spyder take me there.

(This behavior exists for Spyder 4.2.1, but as far as I know, Spyder 4.1.3 or earlier versions work as expected.)

**Comment by ccordoba12** [comment] 2021-01-18 16:15
Hey @jsh9, thanks for reporting. This is a duplicate of issue #14236.

**Comment by ccordoba12** [comment] 2021-01-18 16:16
And we plan to solve it for 4.2.2, to be released in February 15th.

**Closed by ccordoba12** 2021-01-18 16:15 UTC
