### ISSUE TITLE
Code completion bug, variable or function starting with '_'

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#10291] opened 2019-09-24 06:59 UTC
## Problem Description
Completing '_' or '__', no expected candidates
Completing '_test'  '_v'  '__test'  '__v', no candidates appear

![20190924_141957](https://user-images.githubusercontent.com/1759365/65486737-d8e91680-ded7-11e9-854a-6e9a82e79a2e.gif)

However, the same operation is normal in spyder 3.3.6
![20190924_142306](https://user-images.githubusercontent.com/1759365/65488128-f966a000-deda-11e9-9433-df9bd84a5640.gif)

## Code
```Python
class TestClass(object):
    def __init__(self):
        self.var = None
        self._var = None
        self.__var = None
        self.___var = None
    def main(self):
        self._
    def testFunc(self):
        pass
    def _testFunc(self):
        pass
    def __testFunc(self):
        pass
    def ___testFunc(self):
        pass
```
## Versions

* Spyder version: 4.0.0b5
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win7

**Comment by bcolsen** [comment] 2019-09-24 20:55
There is something strange happening here.

I get completions for `_` but it lists the triple ones first. With double underscore I get only the triples and with the triple underscores I get no completions.

**Comment by goanpeca** [comment] 2020-05-05 15:24
I cannot reproduce this with the latest Spyder 4.1.2

![image.png](https://images.zenhubusercontent.com/560c1b40638e718c995d70b3/736af32d-228b-44b4-9f7f-8d48b71dad45)

Closing

**Closed by goanpeca** 2020-05-05 15:24 UTC
Labels: component:Code Completion, type:Bug
