### ISSUE TITLE
cannot see code autocompletion. Although I have turned it on

### ISSUE THREAD

**Issue by TahaAsif** [spyder-ide/spyder#8183] opened 2018-11-01 07:18 UTC
### What steps will reproduce the problem?

When ever I type any code, I can not see recommended funtions

## Versions

* Spyder version: 3.3.0 
* Python version: 2.7.15rc1
* Qt version: 5.9.5
* PyQt5 version: 5.10.1
* Operating System: Linux 4.15.0-36-generic

### Dependencies

```
pyflakes >=0.5.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.6 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
matplotlib >=2.0.0:  2.1.1 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment] 2018-11-01 15:16
This is a duplicate of issue #5782. Please see there for possible solutions.

**Closed by ccordoba12** 2018-11-01 15:16 UTC
