### ISSUE TITLE
problem with spider

### ISSUE THREAD

**Issue by jsrini78** [spyder-ide/spyder#6211] opened 2018-01-15 20:19 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\sjayar2\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2609, in edit_preferences
    widget.initialize()
  File "C:\Users\sjayar2\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 77, in initialize
    self.load_from_conf()
  File "C:\Users\sjayar2\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 381, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)

**Comment by CAM-Gerlach** [comment] 2018-01-16 02:22
Thanks for reporting. This is a duplicate of #5578 which was fixed in Spyder 3.2.5; please update to that version to prevent it from reoccuring. Also, ``spyder --reset`` (resetting your preferences) will also fix it. Therefore, this issue will be closed.

**Closed by CAM-Gerlach** 2018-01-16 02:22 UTC
