### ISSUE TITLE
TKinter doesn't return focus to Ipython window

### ISSUE THREAD

**Issue by timhockswender** [spyder-ide/spyder#22520] opened 2024-09-17 15:27 UTC
Running 6.6.0 in Windows11. In order to continue editing fter the script runs, I need to delete the current kernel and a new one is created. This was not the behavior a year ago. I changed graphics backend to Tk from Automatic but not help. I can get by to destroy the kernel but I don't think it should be necessary. Advice appreciated.

**Comment by ccordoba12** [comment] 2024-09-23 16:37
Hey @timhockswender, thanks for reporting. Could you post a simple code example that generates this problem?

Without that, I'm afraid we won't be able to help you.

**Comment by timhockswender** [comment] 2024-10-11 22:10
Hi Carlos, I finally got back to this-live in SW Florida with weather aggravations.
At almost all tkinter scripts either do not return to ipython terminal.  Some with a quit button kill the kernel forcing a restart.
I am attaching one taken from a very recent tutorial and one I created. Both fail and I have the latest Spyder. Both in one zip file.

# 
[tKinter_issue.zip](https://github.com/user-attachments/files/17347713/tKinter_issue.zip)

**Comment by ccordoba12** [comment] 2024-10-13 22:54
Hope you're doing well after the last hurricane and thanks for the reproducible example.

@dalthviz, could you check if you're having the same issues with our Windows installer? Thanks!

**Comment by dalthviz** [comment] 2024-10-19 00:11
Hi there @timhockswender if you are using the Tk backend I think to be able to reuse the console after launching your scripts you will need to use something like `app.mainloop(n=1)`. [The `n` kwarg refers to a threshold related to how many root windows are available](https://stackoverflow.com/a/51387226). Since the kernel creates a a hidden one, Tk will get stuck/not drop from the mainloop even when closing the window your script created when setting the backend to Tk.

Let us know if the info above helps!

**Comment by ccordoba12** [comment] 2024-11-17 23:22
Closing due to lack of response. Hopefully the trick @dalthviz gave you helped you to fix this problem.

**Closed by ccordoba12** 2024-11-17 23:22 UTC
Labels: component:IPython Console, status:Awaiting Followup
