### ISSUE TITLE
Fresh Conda install has only partially functioning Spyder

### ISSUE THREAD

**Issue by statespace** [spyder-ide/spyder#3037] opened 2016-03-06 12:57 UTC
## Description

**What steps will reproduce the problem?**

1. Install Conda on fresh Ubuntu (Mint 17.3 64-bit):
bash Downloads/Anaconda3-2.5.0-Linux-x86_64.sh 
conda update --all
2.  Run Spyder
3. Tools -> Preferences

Nothing else is installed / executed

**What is the expected output? What do you see instead?**
Preferences do not load, instead there is internal console error:
```

>>> /home/avalujevs/anaconda3/lib/python3.5/site-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/spyderlib/spyder.py", line 2008, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/spyderlib/plugins/__init__.py", line 212, in create_configwidget
    configwidget.initialize()
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/spyderlib/plugins/configdialog.py", line 59, in initialize
    self.setup_page()
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/spyderlib/plugins/inspector.py", line 136, in setup_page
    jedi_installed = programs.is_module_installed('jedi', '>=0.8.1')
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/spyderlib/utils/programs.py", line 292, in is_module_installed
    actver = get_module_version(module_name)
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/spyderlib/utils/programs.py", line 238, in get_module_version
    mod = __import__(module_name)
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/jedi/api/__init__.py", line 16, in <module>
    from jedi.parser import Parser, load_grammar
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/jedi/parser/__init__.py", line 21, in <module>
    from jedi.parser import tree as pt
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/jedi/parser/tree.py", line 39, in <module>
    from jedi import cache
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/jedi/cache.py", line 32, in <module>
    from jedi import debug
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/jedi/debug.py", line 17, in <module>
    init()
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/colorama/initialise.py", line 37, in init
    wrap_stream(orig_stdout, convert, strip, autoreset, wrap)
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/colorama/initialise.py", line 76, in wrap_stream
    convert=convert, strip=strip, autoreset=autoreset)
  File "/home/avalujevs/anaconda3/lib/python3.5/site-packages/colorama/ansitowin32.py", line 67, in __init__
    strip = conversion_supported or (not wrapped.closed and not is_a_tty(wrapped))
AttributeError: 'SysOutput' object has no attribute 'closed'
```

**Please provide any additional information below**

Editor and console works (at least on simple examples) as intended. Just no access to preferences.

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.5.1
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
IPython >=1.0   :  4.1.2 (OK)
matplotlib >=1.0:  1.5.1 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.0.0 (OK)
pyflakes >=0.6.0:  1.1.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
pylint >=0.25   :  None (NOK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  15.2.0 (OK)

```

**Comment by ccordoba12** [comment] 2016-03-06 14:48
Thanks for reporting. This is a duplicate of issue #2984, and it will be fixed in Spyder 2.3.9.

**Closed by ccordoba12** 2016-03-06 14:48 UTC
Labels: Duplicate
