### ISSUE TITLE
d

### ISSUE THREAD

**Issue by zjlal5753** [spyder-ide/spyder#5411] opened 2017-10-06 20:37 UTC
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python2.7/site-packages/spyder/widgets/explorer.py", line 142, in icon
    if osp.isdir(fname):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-39: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.14
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.4 (OK)
rope >=0.9.4      :  0.10.3 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
psutil >=0.3      :  5.3.1 (OK)
nbconvert >=4.0   :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-10-06 20:57
Closing as a duplicate of issue #5410.

Please update Spyder and don't open more bugs about this.

**Closed by ccordoba12** 2017-10-06 20:57 UTC
