### ISSUE TITLE
An error occurred while starting the kernel

### ISSUE THREAD

**Issue by KelumPerera** [spyder-ide/spyder#18977] opened 2022-08-08 12:37 UTC
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I downloaded python 3.7.7 as Windows x86-64 embeddable zip file, saved the folder in my C: drive and also downloaded and saved "get-pip.py" in the same python directory. And I managed to install several packages including spyder via pip successfully. 

When I start the spyder and corrected the python path and then run print("Hello word"). But I get the below error.

An error ocurred while starting the kernel
0.01s ‑ Debugger warning: It seems the debugger cannot find os.path.realpath.__code__.co_filename (D:\obj\windows‑release\37amd64_Release\msi_python\zip_amd64\ntpath.py).
0.00s ‑ This may make the debugger miss breakpoints in the standard library.
0.00s ‑ Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation. 

### What is the expected output? What do you see instead?
I expect it to run the hello world. But get the above error.

### Paste Traceback/Error Below (if applicable)

However, when I run the same via "View > Panes > Internal Console", I get the hello world printed
```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.2. 
* Python version: 3.7.7
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10 Enterprise 10.0.19042

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.9.1 (OK)
keyring >=17.0.0              :  23.8.1 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  63.4.2 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.3.2;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.6 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by ccordoba12** [comment] 2022-08-08 15:04
Hey @KelumPerera, thanks for reporting. This is a duplicate of issue #18908.

Please follow [this comment](https://github.com/spyder-ide/spyder/issues/18908#issuecomment-1205494761) to see if that fixes your problem. If that's successful or not, please post on that issue and let us know.

**Closed by ccordoba12** 2022-08-08 15:04 UTC

**Comment by KelumPerera** [comment] 2022-08-08 16:58
Thanks @ccordoba12 
Adding the said content to the "C:\python\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py" resolved the issue.

![image](https://user-images.githubusercontent.com/17468031/183472438-ba00f089-8d8f-4c53-9687-db2ed4e06ff7.png)

**Comment by ccordoba12** [comment] 2022-08-08 17:10
Fantastic! Thanks a lot for letting us know about it. We'll take care of it in our next version (5.3.3) to be released at the end of the month.
