### ISSUE TITLE
High typing latency in MacOS - Catalina

### ISSUE THREAD

**Issue by TJTapajyoti** [spyder-ide/spyder#15548] opened 2021-05-07 18:20 UTC
## Problem Description
When I am typing in the Spyder editor I am getting high typing latency. The problem only happens in the editor. The kernel works fine with no latency. 

### What steps reproduce the problem?

1. conda create -n env spyder=5 python=3.9
2. Type in the editor
3. Very slow typing. However, kernel works perfectly. 

### What is the expected output? What do you see instead?

Slow typing. The letter appears one second after I type. 
I tried export QT_MAC_WANTS_LAYER=1 and then launched spyder. It did not solve the problem. 

## Versions

* Spyder version: 5
* Python version: 3.9
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Catalina

**Comment by juanis2112** [comment] 2021-05-08 04:46
Hi @TJTapajyoti thanks for reporting this. Can you let me know what is the length of the file you are opening in your editor?
If the file is longer than 1000 lines, then this is a bug that we are working on for a future release.

**Comment by TJTapajyoti** [comment] 2021-05-10 01:37
@juanis2112 The file is pretty small < 100 lines. The problem does not occur when using an external display. It only happens when working on the retina display. Is it a Graphics card issue?

**Comment by ccordoba12** [comment] 2021-05-10 02:49
I think the problem happens because you're using a very old version of Qt (the graphical toolkit used by Spyder).

Please try to install Spyder from conda-forge (which has a more recent version) and let us know if it works for you:

    conda create -n env2 -c conda-forge spyder=5 python=3.9

**Comment by TJTapajyoti** [comment] 2021-05-10 04:37
@ccordoba12  Thanks. I tried it. However, the problem still persists.

**Comment by TJTapajyoti** [comment] 2021-05-10 04:40
#15535   -  Another issue pointing to the same problem. Issue Number - #15535

**Comment by ccordoba12** [comment] 2021-05-10 04:44
Thanks for noticing that. I closed that issue as a duplicate of this one.

**Comment by ccordoba12** [comment] 2021-05-10 04:45
So, the only known workaround to make Spyder work in Big Sur is to download our [DMG installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg) and then connect it to your conda environments by following our FAQ [here](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

All users that tried this have reported it solves the lags for them.

**Comment by Nixcelsior** [comment] 2021-05-10 04:49
Hi,
If I install Spyder using the DMG installer, will I still open it through Anaconda or does it just use the environment created by Anaconda? 
Sorry, I am new to python. I was also told to use anaconda because it helps setting up environments.

**Comment by ccordoba12** [comment] 2021-05-10 04:51
> or does it just use the environment created by Anaconda?

It can use the environment created by Anaconda, but you need to manually connect the DMG app with it.

You can learn how to do that by following our FAQ [here](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

**Comment by Nixcelsior** [comment] 2021-05-10 04:58
I was getting this error:
No module named 'openpyxl'
That is why I started using anaconda. Now I am using the DMG installer and not opening Spyder through Anaconda, the error is back.

**Comment by ccordoba12** [comment] 2021-05-10 14:41
@Nixcelsior, two questions for you:

* Does the installer shows the latency problems you see in Anaconda?
* Did you connect Spyder to Anaconda following the instructions I mentioned above?

**Comment by TJTapajyoti** [comment] 2021-05-10 16:25
> I was getting this error:
> No module named 'openpyxl'
> That is why I started using anaconda. Now I am using the DMG installer and not opening Spyder through Anaconda, the error is back.

This means that the openpyxl module is not installed. As you said you are new to python let me just try to explain a little bit which will help you forward. @Nixcelsior  . Anaconda is a complete package of python with all the different modules you use in your code. For example - openpyxl, pandas, numpy etc. Its is already included in it. So you do not need to install them separately. I used anaconda for a long time before shifting away from it and making and building by own environments. I recommend you to search installing conda and then creating pythonic conda environments for you work. It is much cleaner and helps you understand the basics of how python works. When you do that, you will see errors like "No module found". That is because it is not installed. Once you find which modules you require, all you need to do is "pip install openpyxl" or "conda install openpyxl" and you will get the module installed. Then the error wont come any more. Kindly read up on modules in python and installing them. You can do pip install through spyder directly in the kernel. But its better to do it in the terminal within the conda environment. Hope that helps.

**Comment by TJTapajyoti** [comment] 2021-05-10 16:26
@ccordoba12  Do you recommend the DMG installed pathway for my problem also?

**Comment by ccordoba12** [comment] 2021-05-10 16:46
> Do you recommend the DMG installed pathway for my problem also?

Yeah, it's the only solution to avoid the latency issues according to all users that have reported that problem.

**Comment by ccordoba12** [comment] 2021-05-10 23:44
@Nixcelsior, did you set these environment variables (`PYTHONHOME` and `PYTHONPATH`) somehow?

**Comment by Nixcelsior** [comment] 2021-05-10 23:46
> @Nixcelsior, did you set these environment variables (`PYTHONHOME` and `PYTHONPATH`) somehow?

I don't think so. I have tried to troubleshoot this issue in the past and have tried a few thing.

**Comment by ccordoba12** [comment] 2021-05-10 23:53
> An error ocurred while starting the kernel

Please post a screenshot of the message you're seeing in our IPython console as well.

**Comment by Nixcelsior** [comment] 2021-05-10 23:57
> IPython console

Is this what you were after?

![Screen Shot 2021-05-11 at 9 56 34 am](https://user-images.githubusercontent.com/83796368/117738373-38c43a80-b23f-11eb-861b-3b2af6db59d4.png)

**Comment by ccordoba12** [comment] 2021-05-11 01:37
Yeah, thanks for your help. I thought it contained other info.

@mrclary, any ideas about why our Mac app is failing to start a kernel for Anaconda with such an error?

**Comment by Nixcelsior** [comment] 2021-05-11 02:09
Actually, it did connect. 
No packages were installed when I installed anaconda3. I thought it installed all the standard packages but it did not. It did not create a 'Anaconda3' environment, just a base(root) environment.

**Comment by mrclary** [comment] 2021-05-11 02:38
@ccordoba12 @Nixcelsior, I'm not sure why that error occurred when restarting the kernel. The `PYTHONHOME` AND `PYTHONPATH` shown in the traceback are the values set by the Spyder.app for internal use (i.e running Spyder). These are intentionally scrubbed from the environment used for Consoles (except `PYTHONPATH` is replaced with what is in the PYTHONPATH Manager). I don't understand why this error would manifest when enacting 'Console'->'Restart Kernel' but not when closing the Console (and it automatically restarts).

I cannot reproduce this error with Spyder 5.0.2 on Big Sur. If you can reliably reproduce the behavior, please create a separate issue.

**Comment by ccordoba12** [comment] 2021-05-23 19:09
Closing due to lack of response.

**Closed by ccordoba12** 2021-05-23 19:09 UTC
Labels: status:Awaiting Followup
