### ISSUE TITLE
await asyncio.sleep(1) hangs

### ISSUE THREAD

**Issue by Lewn** [spyder-ide/spyder#9609] opened 2019-06-19 14:25 UTC
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In a fresh install of spyder, awaiting coroutines with asyncio.sleep in them seem to hang.

### What steps reproduce the problem?

Open a new IPython console in Spyder, and the following will hang:
```python
In [1]: import asyncio

In [2]: await asyncio.sleep(1)
```

### What is the expected output? What do you see instead?
In the ipython console on the command line, outside of spyder, this works:
```python
(py37_forge) C:\Users>ipython
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:18:50) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import asyncio

In [2]: await asyncio.sleep(1)

In [3]:
```

Also in the jupyter qtconsole, this does work fine:
```python
Jupyter QtConsole 4.5.1
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:18:50) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import asyncio

In [2]: await asyncio.sleep(1)

In [3]: 
```

## Versions

* Spyder version: 3.3.4
* Python version: 3.7.3 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.5.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.3 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment] 2019-06-19 14:48
Thanks for reporting. We'll take a look at this in Spyder 4.

**Comment by nbud** [comment] 2021-03-16 17:13
Any plan for this ticket? IPython supports rather well "await", but a non-functioning asyncio.sleep in Spyder is a real blocker for learning/debugging asyncio. It would be great to have this issue fixed :)

**Comment by impact27** [comment] 2022-01-12 17:46
I can't reproduce with the latest 5.x

**Comment by ccordoba12** [comment] 2022-01-12 18:03
Thanks for checking this @impact27! I can't reproduce it either on Linux. Probably this was fixed thanks to the new versions of jupyter-client (7.x) and ipykernel (6.x), which have much better support for asyncio.

Since the next Spyder version (5.2.2, to be released next week) will depend on them, I'm going to close this issue.

**Closed by ccordoba12** 2022-01-12 18:03 UTC
Labels: type:Bug, component:IPython Console

**Comment by mg3146** [comment] 2023-07-12 20:06
For what it's worth, the asyncio.sleep(1) will eventually run through, but it takes a solid 15min
