### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ShockWave08** [spyder-ide/spyder#11305] opened 2020-01-13 12:46 UTC
### What steps will reproduce the problem?

Since updating scikit 0.22.1, issues with opening variables in the Variable explorer tab has became common place. I have no clear explanation, but that of a buggy scikit-learn (0.22.1) install.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 470, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.17.4 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by jitseniesen** [comment] 2020-01-13 13:59
This is caused by incompatible versions of Spyder and NumPy and fixed in Spyder version 3.3.3. Presumably your scikit update also updated numpy. Please update Spyder by opening the Anaconda Prompt and running there

```
conda install spyder=3.3.6
```

Duplicate of #8582

**Closed by jitseniesen** 2020-01-13 13:59 UTC
