### ISSUE TITLE
Issue after removin all variables

### ISSUE THREAD

**Issue by Theeyeball** [spyder-ide/spyder#11424] opened 2020-01-29 11:06 UTC
### What steps will reproduce the problem?

If I want to remove all variables from variable explorer even by "remove all variables" button issue shows up.

### Traceback
```python-traceback
Exception in comms call remove_value:
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\console\kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'blobs'
Exception in comms call remove_value:
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\console\kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'all_labels'
Exception in comms call remove_value:
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\comms\commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\comms\commbase.py", line 353, in _remote_callback
    *call_args, **call_kwargs)
  File "D:\Anaconda\Lib\site-packages\spyder_kernels\console\kernel.py", line 234, in remove_value
    ns.pop(name)
KeyError: 'blobs_labels'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.3
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  0.8.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.4.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.4.1 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.1 (OK)
pygments >=2.0               :  2.3.1 (OK)
pylint >=0.25                :  2.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.0.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.7.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.6 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
numpy >=1.7                  :  1.16.2 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.2.1 (OK)
sympy >=0.7.3                :  1.3 (OK)
```

**Comment by ccordoba12** [comment] 2020-01-29 16:27
Duplicate of #11001

**Comment by ccordoba12** [comment] 2020-01-29 16:28
Unfortunately, we've been unable to reproduce this error. So if you find to **always** reproduce it, please post it in the above issue.

**Closed by ccordoba12** 2020-01-29 16:27 UTC
