### ISSUE TITLE
'%reset -s' fails if get_ipython from IPython is imported

### ISSUE THREAD

**Issue by arman00** [spyder-ide/spyder#3761] opened 2016-11-28 20:58 UTC
## Description of your problem
After importing get_ipython from IPython, when I type '%reset -s' to clear all the variables, instead it prints error message and does not clear all the variables. However, '%reset' works without any issue, or %reset -s works if I don't import from IPython or if I use import IPython. Also, this only happens with spyder versions 3.0.0b7 or above. With 3.0.0b6 and below it works without any issue.

**What steps will reproduce the problem?**

1. from IPython import get_ipython
2. get_ipython().magic('reset -sf')
3. or, %reset -sf

**What is the expected output? What do you see instead?**
Expected behavior is to clear all the variables.
Instead, below error message is printed in the Internal console, and the variables in the variable explorer are not cleared. Also, after this, any command in the IPython console prints the same error message, and new variables never display in the variable explorer.

>>> Traceback (most recent call last):
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 189, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 242, in handle_exec_method
    properties = ast.literal_eval(data['text/plain'])
TypeError: 'NoneType' object is not subscriptable

**Please provide any additional information below**
However, '%reset' works without any issue.
Also, this only happens with spyder versions 3.0.0b7 or above. With 3.0.0b6 and below it works without any issue.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5.2
* Operating system: Windows 7 64-Bit
* IPython: 5.1.0

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.9 (OK)
sympy >=0.7.3    :  1.0 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by goanpeca** [comment] 2019-11-29 01:36
I cannot reproduce this. Closing

**Closed by goanpeca** 2019-11-29 01:36 UTC
Labels: component:IPython Console, type:Bug
