### ISSUE TITLE
Segfault issue, may be related to Kite

### ISSUE THREAD

**Issue by kbauer** [spyder-ide/spyder#15077] opened 2021-04-01 08:23 UTC
### What steps will reproduce the problem?

The issue is hard to reproduce. What I am observing is essentially, that I work normally, keep Spyder open for some hours in the background, and return to find Spyder having crashed.

When starting Spyder from a terminal, I am seeing something along the lines of 

```
>>> spyder
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
```

The most surprising part is, that this occurs while Spyder isn't being actively used.

Since the issue occurs without a clear trigger, I cannot realistically test it with a cleaned configuration either.

I will try to attach output with `spyder --debug-info verbose`, hoping that I will see the crash again in that mode.

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 4.12.14-lp151.28.52-default

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.4.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  50.3.1.post20201107 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  0.10.3 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by kbauer** [comment] 2021-04-01 10:39
This time the issue was triggered, when clicking "check for updates", with the last lines of output being:

```
2021-04-01 12:27:57,500 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2021-04-01 12:28:57,501 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2021-04-01 12:29:57,500 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2021-04-01 12:30:57,501 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2021-04-01 12:31:57,500 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2021-04-01 12:32:08,730 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/status?filename=%2Fhome%2Fkdbauer%2FDocuments%2FNotes%2FX018_210311_ECMI_2021_Talk%2Ftestmodel%2Fecmiplots.py HTTP/1.1" 200 58
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
```

Restarting, and trying "Check for Updates" did not cause a crash, but I now with ``--debug-info verbose`` I also see the font issue line frequently without Spyder crashing, so it might be unrelated after all?

**Comment by kbauer** [comment] 2021-04-01 12:34
It looks like something triggers a segfault, that crashes the python interpreter.

Found by running Spyder from the REPL.

```
___________________________________________________________
14:??:?? ~/anaconda3/lib/python3.8/site-packages/spyder/app 
>>> python3 
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.argv = ["spyder", "--debug-info", "verbose"]
>>> import start; start.main()
2021-04-01 14:32:39,070 [INFO] [spyder.app.mainwindow] -> Start of MainWindow constructor
2021-04-01 14:32:39,457 [INFO] [spyder.app.mainwindow] -> End of MainWindow constructor
2021-04-01 14:32:39,517 [INFO] [spyder.app.mainwindow] -> *** Start of MainWindow setup ***
...
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
2021-04-01 14:26:58,309 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Added thread <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x7ffa042a7820> to queue
2021-04-01 14:26:58,360 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2021-04-01 14:26:58,360 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2021-04-01 14:26:58,360 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2021-04-01 14:26:58,361 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x7ffa042a7820>
2021-04-01 14:26:58,362 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2021-04-01 14:26:58,362 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2021-04-01 14:26:58,362 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 0
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
Failed to compute left/right minimum bearings for "FontAwesome"
[2]    19942 segmentation fault  python3
___________________________________________________________
14:27:00 ~/anaconda3/lib/python3.8/site-packages/spyder/app 
>>>
```

**Comment by kbauer** [comment] 2021-04-01 17:35
Upon running with `--report-segfault`, I obtained the following backtrace upon the next segfault crash:

```
Fatal Python error: Segmentation fault

Thread 0x00007f496bde3700 (most recent call first):
  File "/home/kdbauer/anaconda3/lib/python3.8/http/client.py", line 971 in send
  File "/home/kdbauer/anaconda3/lib/python3.8/http/client.py", line 1010 in _send_output
  File "/home/kdbauer/anaconda3/lib/python3.8/http/client.py", line 1250 in endheaders
  File "/home/kdbauer/anaconda3/lib/python3.8/http/client.py", line 1301 in _send_request
  File "/home/kdbauer/anaconda3/lib/python3.8/http/client.py", line 1255 in request
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392 in _make_request
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670 in urlopen
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439 in send
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 643 in send
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 530 in request
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 543 in get
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/kite/client.py", line 136 in perform_http_request
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/kite/client.py", line 107 in _get_status
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/kite/client.py", line 113 in get_status

Thread 0x00007f4876f3f700 (most recent call first):
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 306 in wait
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 558 in wait
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/jupyter_client/channels.py", line 161 in run
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f48a6ffd700 (most recent call first):
  File "/home/kdbauer/anaconda3/lib/python3.8/selectors.py", line 468 in select
  File "/home/kdbauer/anaconda3/lib/python3.8/asyncio/base_events.py", line 1823 in _run_once
  File "/home/kdbauer/anaconda3/lib/python3.8/asyncio/base_events.py", line 570 in run_forever
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 149 in start
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 187 in run
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f48aeffd700 (most recent call first):
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 302 in wait
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 558 in wait
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 829 in run
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 58 in needs_sqlite
  File "<decorator-gen-17>", line 2 in run
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f48c4c67700 (most recent call first):
  File "/home/kdbauer/anaconda3/lib/python3.8/socket.py", line 292 in accept
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3172 in start_open_files_server
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 870 in run
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/kdbauer/anaconda3/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f49b5fe8740 (most recent call first):
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3415 in check_updates
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3545 in create_window
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3644 in main
  File "/home/kdbauer/anaconda3/lib/python3.8/site-packages/spyder/app/start.py", line 213 in main
  File "<string>", line 1 in <module>
```

**Comment by ccordoba12** [comment] 2021-04-01 22:46
Hey @kbauer, thanks for reporting. This certainly seems a segfault caused by Kite.

Are you using a VPN or something else that modifies the internal traffic in your machine?

**Comment by kbauer** [comment] 2021-04-02 07:07
> Are you using a VPN or something else that modifies the internal traffic in your machine?

Yes. I need to constantly have Barracuda VPN running in order to access the data.

**Comment by ccordoba12** [comment] 2023-11-24 03:58
Closing because we don't support Kite now.

**Closed by ccordoba12** 2023-11-24 03:58 UTC
Labels: status:Awaiting Followup
