### ISSUE TITLE
Enter in the IPython console inserts new line instead of executing current line

### ISSUE THREAD

**Issue by cmeeren** [spyder-ide/spyder#2807] opened 2015-11-13 08:16 UTC
## Description

**What steps will reproduce the problem?**

1. Write anything in an IPython console, e.g. `a = 1`
2. Press <kbd>Enter</kbd>

**What is the expected output? What do you see instead?**

I expect the line to be executed (`a = 1`). Instead a new line is inserted, the same way it automatically is when you start a multi-line statement (e.g. `def foo():`) and press <kbd>Enter</kbd>. Pressing <kbd>Shift</kbd>+<kbd>Enter</kbd> executes the current line.

This happens on both Windows and Linux. It does not happen when IPython is run from a system terminal.

## Version and main components

* Spyder Version: 2.3.7 
* Python Version: 2.7.10
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.5 (OK)
pylint >=0.25      :  1.4.1 (OK)

```

**Comment by ccordoba12** [comment] 2015-11-16 00:38
This is a duplicate of issue #2696.

**Closed by ccordoba12** 2015-11-16 00:38 UTC
Labels: duplicate
