### ISSUE TITLE
When in replace menu tab key does not cycle through buttons

### ISSUE THREAD

**Issue by martinwk** [spyder-ide/spyder#3991] opened 2017-01-18 10:37 UTC
I have updated to spyder 3.0.2 and found that pressing <TAB> does not cycle through the different buttons and fields in the replace pane; this used to be the case in the previous version I used (2.something)

**Comment by ccordoba12** [comment] 2017-01-18 12:51
@mariacamilaremolinagutierrez take a look at this one

**Comment by DStauffman** [comment] 2017-01-19 23:21
I think this is closely related to https://github.com/spyder-ide/spyder/issues/3674

**Comment by ccordoba12** [comment] 2017-02-14 15:51
You're right. Closing as a duplicate of issue #3674.

**Closed by ccordoba12** 2017-02-14 15:51 UTC
Labels: component:Editor, resolution:Duplicate, type:Bug
